### ISSUE TITLE
Development environment composition Error

### ISSUE THREAD

**Issue by sangyoungahn** [spring-projects/spring-boot#10066]
I followed the description in "contributin.adoc" but an error occurred.
1. I switched "advanced mode" when installing Eclipse.
2. <Projects>
   I add the path to the setup file at Github projects.<br>
   Then Double-click on "Spring Boot" and add it in project list.

![step2](https://user-images.githubusercontent.com/28176179/29648116-7daac038-88c7-11e7-8745-2044d9984da0.PNG)

<br>
3. <Variable>
   I activated the "show all variable" button.<br>
   And I inserted the path to the spring-boot cloned in local at "Checkout Location".

![step3-1](https://user-images.githubusercontent.com/28176179/29648171-c78d068e-88c7-11e7-9524-62bb20779d2d.PNG)

<br>
4. <Confirmation>
   Finally, I clicked "finish" button to install.

![step4](https://user-images.githubusercontent.com/28176179/29648183-d32b4fe6-88c7-11e7-9819-c17c7b758a1c.PNG)
<br>

Error Page
![step5](https://user-images.githubusercontent.com/28176179/29648021-2c3df800-88c7-11e7-8f5a-2fb6a21e5ea2.PNG)

```
Executing bootstrap tasks
Java(TM) SE Runtime Environment 1.8.0_144-b01
Product org.eclipse.products.epp.package.java.oxygen
Workspace C:\Users\wwf12\spring-boot-default7\ws
Project com.github.user.project.spring.boot.default
Bundle org.eclipse.oomph.setup 1.8.0.v20170408-0745, build=3059, branch=2161405b80cf99ed791602ba56cdf44084f5ca43
Bundle org.eclipse.oomph.setup.core 1.8.0.v20170531-0903, build=3059, branch=2161405b80cf99ed791602ba56cdf44084f5ca43
Bundle org.eclipse.oomph.setup.installer 1.8.0.v20170327-1117, build=3059, branch=2161405b80cf99ed791602ba56cdf44084f5ca43
Bundle org.eclipse.oomph.setup.p2 1.8.0.v20170318-0419, build=3059, branch=2161405b80cf99ed791602ba56cdf44084f5ca43
Performing Workspace C:\Users\wwf12\spring-boot-default7\ws
Performing P2 Director (Eclipse IDE for Java Developers (Oxygen))
Offline = false
Mirrors = true
Resolving 43 requirements from 12 repositories to C:\Users\wwf12\spring-boot-default7\eclipse
Requirement epp.package.java [4.5.0,4.6.0)
Requirement org.eclipse.platform.feature.group
Requirement org.eclipse.jdt.feature.group
Requirement AnyEditTools.feature.group
Requirement org.eclipse.m2e.maveneclipse.feature.feature.group
Requirement org.springframework.ide.eclipse.boot.dash.feature.feature.group
Requirement org.springframework.ide.eclipse.feature.feature.group
Requirement org.springframework.ide.eclipse.maven.feature.feature.group
Requirement org.eclipse.jst.server_adapters.feature.feature.group
Requirement org.eclipse.jst.server_adapters.ext.feature.feature.group
Requirement org.eclipse.jst.server_ui.feature.feature.group
Requirement org.eclipse.wst.server_adapters.feature.feature.group
Requirement org.eclipse.jst.web_ui.feature.feature.group
Requirement org.eclipse.wst.web_ui.feature.feature.group
Requirement org.sonatype.m2e.buildhelper.feature.feature.group
Requirement org.eclipse.mylyn.github.feature.feature.group
Requirement org.springframework.ide.eclipse.jdt.formatter.feature.feature.group
Requirement epp.package.java [4.7.0,4.8.0)
Requirement org.eclipse.platform.feature.group [4.7.0,4.8.0)
Requirement org.eclipse.rcp.feature.group [4.7.0,4.8.0)
Requirement org.eclipse.buildship.feature.group
Requirement org.eclipse.eclemma.feature.feature.group
Requirement org.eclipse.egit.feature.group
Requirement org.eclipse.egit.mylyn.feature.group
Requirement org.eclipse.jgit.feature.group
Requirement org.eclipse.m2e.feature.feature.group
Requirement org.eclipse.m2e.logback.feature.feature.group
Requirement org.eclipse.mylyn.bugzilla_feature.feature.group
Requirement org.eclipse.mylyn.context_feature.feature.group
Requirement org.eclipse.mylyn.git.feature.group
Requirement org.eclipse.mylyn.hudson.feature.group
Requirement org.eclipse.mylyn.ide_feature.feature.group
Requirement org.eclipse.mylyn.java_feature.feature.group
Requirement org.eclipse.mylyn.wikitext_feature.feature.group
Requirement org.eclipse.mylyn_feature.feature.group
Requirement org.eclipse.recommenders.mylyn.rcp.feature.feature.group
Requirement org.eclipse.recommenders.rcp.feature.feature.group
Requirement org.eclipse.recommenders.snipmatch.rcp.feature.feature.group
Requirement org.eclipse.wst.xml_ui.feature.feature.group
Requirement org.eclipse.oomph.setup.feature.group
Requirement org.eclipse.oomph.setup.jdt.feature.group
Requirement org.eclipse.oomph.setup.maven.feature.group
Requirement org.eclipse.oomph.setup.workingsets.feature.group
Repository http://download.eclipse.org/technology/epp/packages/mars/R
Repository http://download.eclipse.org/releases/mars
Repository http://andrei.gmxhome.de/eclipse
Repository https://dl.bintray.com/philwebb/m2eclipse-maveneclipse
Repository https://dl.bintray.com/philwebb/spring-eclipse-code-formatter
Repository http://dist.springsource.com/release/TOOLS/update/e4.5
Repository http://download.eclipse.org/egit/github/updates/
Repository http://download.eclipse.org/technology/epp/packages/oxygen
Repository http://download.eclipse.org/releases/oxygen/201706281000
Repository http://download.eclipse.org/oomph/updates/milestone/latest
Repository http://download.eclipse.org/technology/m2e/milestones/1.5
Repository http://download.eclipse.org/webtools/repository/luna
Adding repository https://dl.bintray.com/philwebb/spring-eclipse-code-formatter
Adding repository http://download.eclipse.org/technology/epp/packages/mars/R
Adding repository http://download.eclipse.org/releases/mars
Adding repository http://andrei.gmxhome.de/eclipse
Adding repository https://dl.bintray.com/philwebb/m2eclipse-maveneclipse
Adding repository http://download.eclipse.org/egit/github/updates/
Adding repository http://download.eclipse.org/technology/epp/packages/oxygen
Adding repository http://dist.springsource.com/release/TOOLS/update/e4.5
Adding repository http://download.eclipse.org/releases/oxygen/201706281000
Adding repository http://download.eclipse.org/oomph/updates/milestone/latest
Adding repository http://download.eclipse.org/webtools/repository/luna
Adding repository http://download.eclipse.org/technology/m2e/milestones/1.5
Calculating requirements and dependencies.
Cannot complete the request.  Generating details.
ERROR: org.eclipse.equinox.p2.director code=10054 Cannot complete the install because of a conflicting dependency.
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:280)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.resolve(ProfileTransactionImpl.java:425)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:337)
  at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:729)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3324)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3252)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3233)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3133)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:567)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:693)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
  ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1503556230816
  ERROR: org.eclipse.equinox.p2.director code=1 Only one of the following can be installed at once: 
    ERROR: org.eclipse.equinox.p2.director code=0 Eclipse IDE for Java Developers 4.5.0.20150621-1200 (epp.package.java 4.5.0.20150621-1200)
    ERROR: org.eclipse.equinox.p2.director code=0 Eclipse IDE for Java Developers 4.5.1.20150917-1200 (epp.package.java 4.5.1.20150917-1200)
    ERROR: org.eclipse.equinox.p2.director code=0 Eclipse IDE for Java Developers 4.5.2.20160218-0600 (epp.package.java 4.5.2.20160218-0600)
    ERROR: org.eclipse.equinox.p2.director code=0 Eclipse IDE for Java Developers 4.7.0.20170620-1800 (epp.package.java 4.7.0.20170620-1800)
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1503556230816
    ERROR: org.eclipse.equinox.p2.director code=0 To: epp.package.java [4.5.0,4.6.0)
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1503556230816
    ERROR: org.eclipse.equinox.p2.director code=0 To: epp.package.java [4.7.0,4.8.0)

Took 13 seconds.
There are failed tasks.
Press Back to choose different settings or Cancel to abort.
```

**Comment by Hanope** [comment]
I think you already installed eclipse on your computer.
So it seems to occur conflicting dependency error.

Please remove all files and try install again.

**Comment by sangyoungahn** [comment]
Hanope, thank you for answer.
But I did what you asked me to do and I get an error.
