### ISSUE TITLE
Change PostgreSQL version on the 1.5.x release

### ISSUE THREAD

**Issue by joaoandremartins** [spring-projects/spring-boot#10071]
Setting spring-boot 1.5.6 as the Maven parent of my app causes the version of the `org.postgresql:postgresql` dependency to be `9.4.1212.jre7`, which appears to be severely broken. I cannot make a simple JDBC connection:

```
public class App {

  public static void main(String[] args) throws SQLException {
    Connection connection = DriverManager.getConnection([JDBC_URL], [USER], [PASSWORD]);
  }

}
```
Results in:

```
Exception in thread "main" org.postgresql.util.PSQLException: The connection attempt failed.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:272)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:215)
	at org.postgresql.Driver.makeConnection(Driver.java:404)
	at org.postgresql.Driver.connect(Driver.java:272)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.example.postgresqltest.App.main(App.java:17)
Caused by: java.net.SocketException: already connected
	at java.net.Socket.connect(Socket.java:569)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at org.postgresql.core.PGStream.<init>(PGStream.java:61)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:144)
	... 7 more
```

The dependency version in version 2.0.0 is fixed to 42.1.3.
I found postgresql version 41.1.1 to also work.

**Comment by snicoll** [comment]
1.5.x is a maintenance release and we can't upgrade to a new major release of the driver. You are, of course, free to upgrade to a more recent version should you need to.
