### ISSUE TITLE
Configuration properties binder fails with: Failed to instantiate org.springframework.core.io.Resource, specified class is an interface

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-boot#10131]
Configuration properties binding fails with an exception after the Spring Cloud bootstrap context is initialized and triggers configuration properties refresh via `ConfigurationPropertiesBindingPostProcessor`. [`VaultProperties`](https://github.com/spring-cloud/spring-cloud-vault/blob/2.0.x/spring-cloud-vault-config/src/main/java/org/springframework/cloud/vault/config/VaultProperties.java) is bound correctly for the bootstrap. The reported property (`spring.cloud.vault.ssl.key-store.u-r-l`) is not provided by `application.properties`/`bootstrap.properties`.

Dependencies:
* Spring Boot 2.0.0.M3
* Spring Cloud 2.0.M2
* Spring Cloud Vault 2.0.M2

```
org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'spring.cloud.vault.ssl.key-store.u-r-l' to java.net.URL
	at org.springframework.boot.context.properties.bind.Binder.handleBindError(Binder.java:226)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:201)
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindBean$4(Binder.java:299)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:70)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:59)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:51)
	at org.springframework.boot.context.properties.bind.Binder.lambda$null$5(Binder.java:307)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindBean$6(Binder.java:308)
	at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:401)
	at org.springframework.boot.context.properties.bind.Binder$Context.withBean(Binder.java:391)
	at org.springframework.boot.context.properties.bind.Binder.bindBean(Binder.java:305)
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:250)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:197)
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindBean$4(Binder.java:299)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:70)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:59)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:51)
	at org.springframework.boot.context.properties.bind.Binder.lambda$null$5(Binder.java:307)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindBean$6(Binder.java:308)
	at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:401)
	at org.springframework.boot.context.properties.bind.Binder$Context.withBean(Binder.java:391)
	at org.springframework.boot.context.properties.bind.Binder.bindBean(Binder.java:305)
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:250)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:197)
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindBean$4(Binder.java:299)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:70)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:59)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:51)
	at org.springframework.boot.context.properties.bind.Binder.lambda$null$5(Binder.java:307)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindBean$6(Binder.java:308)
	at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:401)
	at org.springframework.boot.context.properties.bind.Binder$Context.withBean(Binder.java:391)
	at org.springframework.boot.context.properties.bind.Binder.bindBean(Binder.java:305)
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:250)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:197)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:186)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:168)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:336)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:306)
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.rebind(ConfigurationPropertiesRebinder.java:117)
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.rebind(ConfigurationPropertiesRebinder.java:98)
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.onApplicationEvent(ConfigurationPropertiesRebinder.java:165)
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.onApplicationEvent(ConfigurationPropertiesRebinder.java:53)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:399)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:353)
	at org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration.afterSingletonsInstantiated(ConfigurationPropertiesRebinderAutoConfiguration.java:79)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:386)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1245)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1233)
	at com.example.demo.DemoApplication.main(DemoApplication.java:14)
Caused by: java.lang.IllegalStateException: Unable to get value for property u-r-l
	at org.springframework.boot.context.properties.bind.JavaBeanBinder$BeanProperty.lambda$getValue$0(JavaBeanBinder.java:290)
	at org.springframework.boot.context.properties.bind.validation.ValidationBindHandler.getValidationTarget(ValidationBindHandler.java:106)
	at org.springframework.boot.context.properties.bind.validation.ValidationBindHandler.validate(ValidationBindHandler.java:96)
	at org.springframework.boot.context.properties.bind.validation.ValidationBindHandler.onFinish(ValidationBindHandler.java:89)
	at org.springframework.boot.context.properties.bind.Binder.handleBindResult(Binder.java:212)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:198)
	... 83 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.core.io.Resource]: Specified class is an interface
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:115)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder$Bean.lambda$getSupplier$0(JavaBeanBinder.java:164)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder$BeanSupplier.get(JavaBeanBinder.java:218)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder$BeanProperty.lambda$getValue$0(JavaBeanBinder.java:287)
	... 88 common frames omitted
```

**Comment by wilkinsona** [comment]
That `u-r-l` is rather odd. @mp911de, what's the quickest was to recreate this?

**Comment by mp911de** [comment]
Here's the code to reproduce the issue: https://github.com/mp911de/spring-boot-10131.

**Comment by mp911de** [comment]
Published Spring Cloud Vault Config without `ignoreInvalidFields` to repo.spring.io, see https://repo.spring.io/snapshot/org/springframework/cloud/spring-cloud-vault-config/2.0.0.BUILD-SNAPSHOT/spring-cloud-vault-config-2.0.0.BUILD-20170831.162031-644.jar.

**Comment by wilkinsona** [comment]
Thank you, @mp911de. That's given me what I needed to boil this down into a standalone test:

```java
	@Test
	public void bindToValidatedBeanWithResourceAndNonEnumerablePropertySource() {
		ConfigurationPropertySources
				.from(Arrays.asList(new PropertySource<String>("test") {

					@Override
					public Object getProperty(String name) {
						return null;
					}

				})).forEach(this.sources::add);
		Validator validator = new SpringValidatorAdapter(Validation.byDefaultProvider()
				.configure().buildValidatorFactory().getValidator());
		this.binder.bind("foo", Bindable.of(ResourceBean.class),
				new ValidationBindHandler(validator));
	}

	@Validated
	public static class ResourceBean {

		private Resource resource;

		public Resource getResource() {
			return this.resource;
		}

		public void setResource(Resource resource) {
			this.resource = resource;
		}

	}
```

Two things are crucial for the failure to occur:

- There must be a property source the isn't enumerable so that we can't tell if there are any descendants of a property that's being bound
- The target for the binding must be `@Validated`

**Comment by mbhave** [comment]
@wilkinsona This is probably not the case here but it seems like the same failure could also happen with an enumerable property source. If there were any descendants of `foo.resource`, for example, if `foo.resource.file` has a value, it will look at all properties on `Resource` and fail because of [this](https://github.com/spring-projects/spring-boot/blob/d969ebad0794015133d37c5bb32fe9168c7e3c3b/spring-boot/src/main/java/org/springframework/boot/context/properties/bind/JavaBeanBinder.java#L68-L68).

**Comment by wilkinsona** [comment]
@mbhave Yep, I think you're right. Any ideas on the best way to fix this? I'm not yet familiar enough with the new binder to feel confident that I know.

**Comment by mbhave** [comment]
I have a fix [here](https://github.com/mbhave/spring-boot/commit/283839e2c7ff4aa2795401e95c779d6c6a536f60). 

/cc @philwebb

**Comment by jmirc** [comment]
When this will be available. Actually, it is impossible to use vault.
