### ISSUE TITLE
Spring Boot server not starting when running on Java 9 and using the module system (Jigsaw)

### ISSUE THREAD

**Issue by pjoole** [spring-projects/spring-boot#10132]
I have a very simple Spring Boot application that I'm trying to run on Java 9 in combination with the module system (Jigsaw).

When I run the application from the classpath there is no issue. However, as soon as I add a module-info.java file, then I get the following error message:

```
2017-08-31 17:50:14.250 DEBUG 5636 --- [           main] .c.l.ClasspathLoggingApplicationListener : Application failed to start with classpath: unknown
2017-08-31 17:50:14.252 ERROR 5636 --- [           main] o.s.boot.SpringApplication               : Error handling failed

java.lang.ClassCastException: spring.boot@2.0.0.M3/org.springframework.boot.context.event.ApplicationFailedEvent cannot be cast to spring.boot@2.0.0.M3/org.springframework.boot.web.context.WebServerInitializedEvent
	at spring.context@5.0.0.RC3/org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167) ~[spring-context-5.0.0.RC3.jar:na]
	at spring.context@5.0.0.RC3/org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.0.0.RC3.jar:na]
	at spring.context@5.0.0.RC3/org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:399) ~[spring-context-5.0.0.RC3.jar:na]
	at spring.context@5.0.0.RC3/org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:353) ~[spring-context-5.0.0.RC3.jar:na]
	at spring.boot@2.0.0.M3/org.springframework.boot.context.event.EventPublishingRunListener.finished(EventPublishingRunListener.java:100) ~[spring-boot-2.0.0.M3.jar:na]
	at spring.boot@2.0.0.M3/org.springframework.boot.SpringApplicationRunListeners.callFinishedListener(SpringApplicationRunListeners.java:79) [spring-boot-2.0.0.M3.jar:na]
	at spring.boot@2.0.0.M3/org.springframework.boot.SpringApplicationRunListeners.finished(SpringApplicationRunListeners.java:72) [spring-boot-2.0.0.M3.jar:na]
	at spring.boot@2.0.0.M3/org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:803) [spring-boot-2.0.0.M3.jar:na]
	at spring.boot@2.0.0.M3/org.springframework.boot.SpringApplication.run(SpringApplication.java:338) [spring-boot-2.0.0.M3.jar:na]
	at spring.boot@2.0.0.M3/org.springframework.boot.SpringApplication.run(SpringApplication.java:1245) [spring-boot-2.0.0.M3.jar:na]
	at spring.boot@2.0.0.M3/org.springframework.boot.SpringApplication.run(SpringApplication.java:1233) [spring-boot-2.0.0.M3.jar:na]
	at security.oauth/be.joole.newit.Application.main(Application.java:12) [classes/:na]

2017-08-31 17:50:14.254 ERROR 5636 --- [           main] o.s.boot.SpringApplication               : Application startup failed
```

I have the feeling that the issue is with the ClassPathLoggingApplicationListener as there is probably no classpath when using the modulepath:

```
2017-08-31 17:50:14.250 DEBUG 5636 --- [           main] .c.l.ClasspathLoggingApplicationListener : Application failed to start with classpath: **unknown** 
```

I have added a SSCCE that easily reproduces the issue:
[SSCCE.zip](https://github.com/spring-projects/spring-boot/files/1267725/SSCCE.zip)

I'm experimenting with the latest Spring Boot release: 2.0.0.M3

**Comment by wilkinsona** [comment]
Thanks for experimenting. Boot doesn't support Java 9 yet. Support is planned for 2.0 but we're not there yet. Please see the various issues labelled with `theme: java9` for details.

**Comment by wilkinsona** [comment]
It's also worth noting that we may limit our Java 9 support to the class path in Java 9 with no module path support.

**Comment by snicoll** [comment]
And that stacktrace is not the thing that makes the application fail, see #10047
