### ISSUE TITLE
Missing useCodeAsDefaultMessage in MessageSourceAutoConfiguration

### ISSUE THREAD

**Issue by diegolovison** [spring-projects/spring-boot#10146]
I would like to set useCodeAsDefaultMessage equals true using my application properties.

If you agree with the change I would like to implement it.

Cheers,

**Comment by snicoll** [comment]
@diegolovison seems sensible, waiting for the PR then.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by diegolovison** [comment]
I am reading the docs on https://github.com/spring-projects/spring-boot#building-from-source and I am facing an issue when I run the command: **mvn clean install -Dmaven.test.skip=true**

And the log is:

```
[INFO] Spring Boot Dependencies ........................... SUCCESS [  5.074 s]
[INFO] Spring Boot Parent ................................. SUCCESS [  1.729 s]
[INFO] Spring Boot Tools .................................. SUCCESS [  0.445 s]
[INFO] Spring Boot Testing Support ........................ SUCCESS [  3.195 s]
[INFO] Spring Boot Loader ................................. SUCCESS [01:18 min]
[INFO] Spring Boot Loader Tools ........................... SUCCESS [  1.727 s]
[INFO] Spring Boot Antlib ................................. SUCCESS [  4.787 s]
[INFO] Spring Boot Auto-Configure Annotation Processor .... SUCCESS [  0.518 s]
[INFO] Spring Boot Configuration Metadata ................. SUCCESS [  0.586 s]
[INFO] Spring Boot Configuration Processor ................ SUCCESS [  1.455 s]
[INFO] Spring Boot Gradle Plugin .......................... SUCCESS [01:22 min]
[INFO] Spring Boot Maven Plugin ........................... FAILURE [03:28 min]
[INFO] Spring Boot ........................................ SKIPPED
[INFO] Spring Boot Test ................................... SKIPPED
[INFO] Spring Boot AutoConfigure .......................... SKIPPED
[INFO] Spring Boot Test Auto-Configure .................... SKIPPED
[INFO] Spring Boot Actuator ............................... SKIPPED
[INFO] Spring Boot Actuator AutoConfigure ................. SKIPPED
[INFO] Spring Boot Developer Tools ........................ SKIPPED
[INFO] Spring Boot Docs ................................... SKIPPED
[INFO] Spring Boot Starters ............................... SKIPPED
[INFO] Spring Boot Logging Starter ........................ SKIPPED
[INFO] Spring Boot Starter ................................ SKIPPED
[INFO] Spring Boot ActiveMQ Starter ....................... SKIPPED
[INFO] Spring Boot AMQP Starter ........................... SKIPPED
[INFO] Spring Boot AOP Starter ............................ SKIPPED
[INFO] Spring Boot Artemis Starter ........................ SKIPPED
[INFO] Spring Boot JDBC Starter ........................... SKIPPED
[INFO] Spring Boot Batch Starter .......................... SKIPPED
[INFO] Spring Boot Cache Starter .......................... SKIPPED
[INFO] Spring Boot Spring Cloud Connectors Starter ........ SKIPPED
[INFO] Spring Boot Data Cassandra Starter ................. SKIPPED
[INFO] Spring Boot Data Cassandra Reactive Starter ........ SKIPPED
[INFO] Spring Boot Data Couchbase Starter ................. SKIPPED
[INFO] Spring Boot Data Elasticsearch Starter ............. SKIPPED
[INFO] Spring Boot Data JPA Starter ....................... SKIPPED
[INFO] Spring Boot Data LDAP Starter ...................... SKIPPED
[INFO] Spring Boot Data MongoDB Starter ................... SKIPPED
[INFO] Spring Boot Data MongoDB Reactive Starter .......... SKIPPED
[INFO] Spring Boot Data Neo4j Starter ..................... SKIPPED
[INFO] Spring Boot Data Redis Starter ..................... SKIPPED
[INFO] Spring Boot Data Redis Reactive Starter ............ SKIPPED
[INFO] Spring Boot Json Starter ........................... SKIPPED
[INFO] Spring Boot Tomcat Starter ......................... SKIPPED
[INFO] Spring Boot Web Starter ............................ SKIPPED
[INFO] Spring Boot Data REST Starter ...................... SKIPPED
[INFO] Spring Boot Data Solr Starter ...................... SKIPPED
[INFO] Spring Boot FreeMarker Starter ..................... SKIPPED
[INFO] Spring Boot Groovy Templates Starter ............... SKIPPED
[INFO] Spring Boot HATEOAS Starter ........................ SKIPPED
[INFO] Spring Boot Integration Starter .................... SKIPPED
[INFO] Spring Boot Validation Starter ..................... SKIPPED
[INFO] Spring Boot Jersey Starter ......................... SKIPPED
[INFO] Spring Boot Jetty Starter .......................... SKIPPED
[INFO] Spring Boot JOOQ Starter ........................... SKIPPED
[INFO] Spring Boot Atomikos JTA Starter ................... SKIPPED
[INFO] Spring Boot Bitronix JTA Starter ................... SKIPPED
[INFO] Spring Boot Narayana JTA Starter ................... SKIPPED
[INFO] Spring Boot Log4j 2 Starter ........................ SKIPPED
[INFO] Spring Boot Mail Starter ........................... SKIPPED
[INFO] Spring Boot Mobile Starter ......................... SKIPPED
[INFO] Spring Boot Mustache Starter ....................... SKIPPED
[INFO] Spring Boot Actuator Starter ....................... SKIPPED
[INFO] Spring Boot Starter Parent ......................... SKIPPED
[INFO] Spring Boot Quartz Starter ......................... SKIPPED
[INFO] Spring Boot Reactor Netty Starter .................. SKIPPED
[INFO] Spring Boot Security Starter ....................... SKIPPED
[INFO] Spring Boot Social Facebook Starter ................ SKIPPED
[INFO] Spring Boot Social Twitter Starter ................. SKIPPED
[INFO] Spring Boot Social LinkedIn Starter ................ SKIPPED
[INFO] Spring Boot Test Starter ........................... SKIPPED
[INFO] Spring Boot Thymeleaf Starter ...................... SKIPPED
[INFO] Spring Boot Undertow Starter ....................... SKIPPED
[INFO] Spring Boot WebFlux Starter ........................ SKIPPED
[INFO] Spring Boot WebSocket Starter ...................... SKIPPED
[INFO] Spring Boot Web Services Starter ................... SKIPPED
[INFO] Spring Boot CLI .................................... SKIPPED
[INFO] Spring Boot Integration Tests ...................... SKIPPED
[INFO] Spring Boot DevTools Tests ......................... SKIPPED
[INFO] Spring Boot Embedded Servlet Container Integration Tests SKIPPED
[INFO] Spring Boot Launch Script Integration Tests ........ SKIPPED
[INFO] Spring Boot Security Tests ......................... SKIPPED
[INFO] Spring Boot Security Tests - Web Hello World ....... SKIPPED
[INFO] Spring Boot Build .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:32 min
[INFO] Finished at: 2017-09-12T14:53:02-03:00
[INFO] Final Memory: 168M/2282M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-invoker-plugin:3.0.0:run (integration-test) on project spring-boot-maven-plugin: 22 builds failed. See console output above for details. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-invoker-plugin:3.0.0:run (integration-test) on project spring-boot-maven-plugin: 22 builds failed. See console output above for details.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: 22 builds failed. See console output above for details.
	at org.apache.maven.plugins.invoker.InvokerSession.handleFailures(InvokerSession.java:260)
	at org.apache.maven.plugins.invoker.InvokerMojo.processResults(InvokerMojo.java:69)
	at org.apache.maven.plugins.invoker.AbstractInvokerMojo.execute(AbstractInvokerMojo.java:717)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more

```

**Comment by snicoll** [comment]
The `ommited` part is the thing that's actually useful. Can you please join us on Gitter? That would be easier than using this issue for support.

**Comment by diegolovison** [comment]
I uploaded the file here without the debug information. [log.txt](https://github.com/spring-projects/spring-boot/files/1297148/log.txt)

I uploaded it on google drive with the debug information ( https://drive.google.com/file/d/0B-3OIjRgoVxwOEtKOE5ZMzhFTVU/view?usp=sharing )

**Comment by diegolovison** [comment]
Using maven with Intellij I was able to successfully "install" the project.


```

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22.410 s
[INFO] Finished at: 2017-09-14T09:59:50-03:00
[INFO] Final Memory: 61M/845M
```

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by snicoll** [comment]
Closing in favour or PR #10466
