### ISSUE TITLE
spring-boot-starter-aop doesn't work with Java 9

### ISSUE THREAD

**Issue by krzyk** [spring-projects/spring-boot#10383]
Spring Boot 1.5.7.RELEASE (as parent and a bom)

I have a project that uses spring-boot-starter-jpa (which uses spring-boot-starter-aop) and it doesn't start correctly because of:
```
Caused by: java.lang.IllegalArgumentException: error at ::0 can't find referenced pointcut controllerBean                                              
    at org.aspectj.weaver.tools.PointcutParser.parsePointcutExpression(PointcutParser.java:301) ~[aspectjweaver-1.8.10.jar:1.8.10]
    at org.springframework.aop.aspectj.AspectJExpressionPointcut.buildPointcutExpression(AspectJExpressionPointcut.java:217) ~[spring-aop-4.3.11.RELEASE.jar:4.3.11.RELEASE]
    at org.springframework.aop.aspectj.AspectJExpressionPointcut.checkReadyToMatch(AspectJExpressionPointcut.java:190) ~[spring-aop-4.3.11.RELEASE.jar:4.3.11.RELEASE]
    at org.springframework.aop.aspectj.AspectJExpressionPointcut.getClassFilter(AspectJExpressionPointcut.java:169) ~[spring-aop-4.3.11.RELEASE.jar:4.3.11.RELEASE]
```
(full log in attachement)
[error.txt](https://github.com/spring-projects/spring-boot/files/1325689/error.txt)

The problem disappears when I add:
```
            <dependency>                                                        
                <groupId>org.aspectj</groupId>                                  
                <artifactId>aspectjweaver</artifactId>                          
                <version>1.9.0.BETA-6</version>                                       
            </dependency>
```
to dependencyManagement section in pom.xml

Unfortunatelly it is available only in spring milestones repo so I can't use it in my project.

**Comment by philwebb** [comment]
Is this error due to some custom AspectJ configuration? I notice the error occurs in `com.akamai.apikeymanager.config`. Also, is there any reason why you can't use aspectjweaver 1.8.10 (which is in maven central)?

A sample would also be helpful so that we can see the problem in action.

**Comment by wilkinsona** [comment]
@philwebb AspectJ 1.9.0 is needed for full compatibility with Java 9. We should probably upgrade in master, but this problem's been reported against 1.5.7 where Java 9 isn't supported.

**Comment by krzyk** [comment]
@philwebb We don't use AspectJ at all, only the annotations from Spring. The bean that is at the top of this exception is:

```
@Profile(Profiles.AUTHORIZATION)
@EnableGlobalMethodSecurity(prePostEnabled = true, securedEnabled = true)
public class MethodSecurityConfig extends GlobalMethodSecurityConfiguration {

    @Override
    public MethodInterceptor methodSecurityInterceptor() throws Exception {
        MethodSecurityInterceptor methodSecurityInterceptor =
            (MethodSecurityInterceptor) super.methodSecurityInterceptor();
        methodSecurityInterceptor.setRejectPublicInvocations(true);
        return methodSecurityInterceptor;
    }

    @Override
    protected AccessDecisionManager accessDecisionManager() {
        AffirmativeBased manager = (AffirmativeBased) super.accessDecisionManager();
        RoleVoter roleVoter = (RoleVoter) manager.getDecisionVoters().stream()
            .filter(v -> v.getClass().equals(RoleVoter.class))
            .findFirst().orElseThrow(IllegalStateException::new);

        roleVoter.setRolePrefix("");
        return manager;
    }

    @Override
    protected MethodSecurityExpressionHandler createExpressionHandler() {
        return new ExtendedMethodSecurityExpressionHandler();
    }
}
```

@wilkinsona So to use Java 9 with Spring Boot I should switch to 2.x milestones, right? Or are you planning to support it also in 1.5.x releases?

**Comment by snicoll** [comment]
There is no plan to support Java9 in the 1.5.x line. And the compatibility is still in progress on master. Upgrading aspectJ as you did is the right thing to do.

**Comment by tunovic** [comment]
Related issue with Java 9 and Spring Boot 2.0.0.M4 when I start using Aspects. Same workaround applied. No issues with JPA only.

**Comment by prasaduvce** [comment]
Upgraded existing Java 8 spring boot Project to Java 9. Got same exception as below. 
 ```
    java.lang.IllegalArgumentException: error at ::0 can't find referenced pointcut controllerMethods
    at org.aspectj.weaver.tools.PointcutParser.parsePointcutExpression(PointcutParser.java:301) ~[aspectjweaver-1.8.10.jar:1.8.10]
	at org.springframework.aop.aspectj.AspectJExpressionPointcut.buildPointcutExpression(AspectJExpressionPointcut.java:226) ~[spring-aop-5.0.0.RC3.jar:5.0.0.RC3]
	at org.springframework.aop.aspectj.AspectJExpressionPointcut.obtainPointcutExpression(AspectJExpressionPointcut.java:197) ~[spring-aop-5.0.0.RC3.jar:5.0.0.RC3]
```

As mentioned in the first comment, adding the below dependency  in pom.xml worked. 
```
<dependency>                                                        
        <groupId>org.aspectj</groupId>                                  
        <artifactId>aspectjweaver</artifactId>                          
        <version>1.9.0.BETA-6</version>                                       
 </dependency>
```
