### ISSUE TITLE
ClassNotFoundException: com.thoughtworks.xstream.io.HierarchicalStreamDriver

### ISSUE THREAD

**Issue by robinsonmark** [spring-projects/spring-boot#10424]
When using parent pom _spring-boot-starter-parent:1.5.7.RELEASE_ and _spring-boot-starter-batch_ you get the following exception:

```
java.lang.NoClassDefFoundError: com/thoughtworks/xstream/io/HierarchicalStreamDriver
	at org.springframework.batch.core.repository.support.JobRepositoryFactoryBean.afterPropertiesSet(JobRepositoryFactoryBean.java:191) ~[spring-batch-core-3.0.8.RELEASE.jar:3.0.8.RELEASE]
	at org.springframework.batch.core.configuration.annotation.DefaultBatchConfigurer.createJobRepository(DefaultBatchConfigurer.java:124) ~[spring-batch-core-3.0.8.RELEASE.jar:3.0.8.RELEASE]
	at org.springframework.batch.core.configuration.annotation.DefaultBatchConfigurer.initialize(DefaultBatchConfigurer.java:99) ~[spring-batch-core-3.0.8.RELEASE.jar:3.0.8.RELEASE]
	at org.springframework.batch.core.configuration.annotation.AbstractBatchConfiguration.getConfigurer(AbstractBatchConfiguration.java:104) ~[spring-batch-core-3.0.8.RELEASE.jar:3.0.8.RELEASE]
	at org.springframework.batch.core.configuration.annotation.SimpleBatchConfiguration.initialize(SimpleBatchConfiguration.java:114) ~[spring-batch-core-3.0.8.RELEASE.jar:3.0.8.RELEASE]
	at org.springframework.batch.core.configuration.annotation.SimpleBatchConfiguration$ReferenceTargetSource.createObject(SimpleBatchConfiguration.java:142) ~[spring-batch-core-3.0.8.RELEASE.jar:3.0.8.RELEASE]
	at org.springframework.aop.target.AbstractLazyCreationTargetSource.getTarget(AbstractLazyCreationTargetSource.java:86) ~[spring-aop-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:192) ~[spring-aop-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at com.sun.proxy.$Proxy50.getJobInstances(Unknown Source) ~[na:na]
	at org.springframework.boot.autoconfigure.batch.JobLauncherCommandLineRunner.getNextJobParameters(JobLauncherCommandLineRunner.java:131) ~[spring-boot-autoconfigure-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at org.springframework.boot.autoconfigure.batch.JobLauncherCommandLineRunner.execute(JobLauncherCommandLineRunner.java:212) ~[spring-boot-autoconfigure-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at org.springframework.boot.autoconfigure.batch.JobLauncherCommandLineRunner.executeLocalJobs(JobLauncherCommandLineRunner.java:231) ~[spring-boot-autoconfigure-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at org.springframework.boot.autoconfigure.batch.JobLauncherCommandLineRunner.launchJobFromProperties(JobLauncherCommandLineRunner.java:123) ~[spring-boot-autoconfigure-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at org.springframework.boot.autoconfigure.batch.JobLauncherCommandLineRunner.run(JobLauncherCommandLineRunner.java:117) ~[spring-boot-autoconfigure-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at hello.Application.main(Application.java:10) [classes/:na]
Caused by: java.lang.ClassNotFoundException: com.thoughtworks.xstream.io.HierarchicalStreamDriver
	at java.net.URLClassLoader.findClass(Unknown Source) ~[na:1.8.0_144]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_144]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[na:1.8.0_144]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_144]
	... 21 common frames omitted
```

This can be replicated with the example project provided at https://github.com/spring-guides/gs-batch-processing

It can be fixed by increasing the version of xstream to 1.4.9

```
<dependency>
   <groupId>com.thoughtworks.xstream</groupId>
   <artifactId>xstream</artifactId>
   <version>1.4.9</version>
</dependency>
```

**Comment by wilkinsona** [comment]
This works fine for me. Boot doesn't manage the version of XStream so you're just getting Batch's default version. For Batch 3.0.8 [that's 1.4.7](https://github.com/spring-projects/spring-batch/blob/3.0.8.RELEASE/build.gradle#L94). I suspect that your copy of the XStream 1.4.7 dependency was corrupted when it was downloaded. Try purging your local repository (`mvn  dependency:purge-local-repository`) and building your application again.
