### ISSUE TITLE
Reinstate testing of Tomcat JSP samples using Java 9

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#10456]
The JSP samples themselves work just fine but the integration tests that are exercising the sample fail.

```
2017-09-29 11:52:10.395 ERROR 62623 --- [o-auto-1-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [The absolute uri: [http://www.springframework.org/tags] cannot be resolved in either web.xml or the jar files deployed with this application] with root cause

org.apache.jasper.JasperException: The absolute uri: [http://www.springframework.org/tags] cannot be resolved in either web.xml or the jar files deployed with this application
	at org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:55) ~[tomcat-embed-jasper-8.5.21.jar:8.5.21]
	at org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:293) ~[tomcat-embed-jasper-8.5.21.jar:8.5.21]
	at org.apache.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:80) ~[tomcat-embed-jasper-8.5.21.jar:8.5.21]
	at org.apache.jasper.compiler.TagLibraryInfoImpl.generateTldResourcePath(TagLibraryInfoImpl.java:251) ~[tomcat-embed-jasper-8.5.21.jar:8.5.21]
	at org.apache.jasper.compiler.TagLibraryInfoImpl.<init>(TagLibraryInfoImpl.java:122) ~[tomcat-embed-jasper-8.5.21.jar:8.5.21]
	at org.apache.jasper.compiler.Parser.parseTaglibDirective(Parser.java:434) ~[tomcat-embed-jasper-8.5.21.jar:8.5.21]
```

**Comment by wilkinsona** [comment]
An app run via its main method (in your IDE for example) also won't work

**Comment by wilkinsona** [comment]
This is a limitation of Tomcat's StandardJarScanner. When running via the main method (rather than as a packaged war), TLDs are found as a result of StandardJarScanner scanning the class path. It does so by walking up the ClassLoader hierarchy and examine the URLs of any URLClassLoaders that it finds. When running via a main method using Java 9, the ClassLoader that has the TLD-containing JARs on its class path is not a URLClassLoader so the TLDs are not found. It works fine when packaging the application is a war because the TLD-containing jars are found by virtue of being packaging in `WEB-INF/lib`.

**Comment by wilkinsona** [comment]
Short of copying and modifying `StandardJarScanner`, I can't see a good way to fix this. While public and non-final, `StandardJarScanner` isn't particularly amenable to being extended. In particular, there's no way to provide an alternative way to get the URLs that are considered to be on the class path and the method that does most of the heavy lifting (`process`) is private.

**Comment by wilkinsona** [comment]
@markt-asf Could some changes to `StandardJarScanner` be considered in Tomcat 8.5.x? If `process` was protected and there was a `scanClassPath` method that we could override then I think we could get this working by falling back to looking at the class path used to launch the JVM (a reasonable approximation in a Boot app for what the scanner currently does).

**Comment by markt-asf** [comment]
This looks like something that Tomcat will need to fix generally for the embedded use case for Java 9.

**Comment by markt-asf** [comment]
This should be fixed in trunk for all 7.0.x, 8.0.x 8.5.x and 9.0.x
At the moment, only the class path is handled for Java 9. The module path is still a TODO.

**Comment by cemo** [comment]
@markt-asf Do you have any timeline for cutting a release?

**Comment by markt-asf** [comment]
Generally Tomcat releases on a monthly basis. The process starts around the beginning of the month with the release typically being available by the middle of the month or earlier.
We've had the October release so the next one will be November.

**Comment by wilkinsona** [comment]
This has been fixed for a while now thanks to the updates that were made to Jasper. We have neglected to reinstate the tests. We can use this issue to do that.

**Comment by wilkinsona** [comment]
I was, in part, too hasty here. The samples that use Tomcat are fine, but Jetty's still using an old version of Jasper that doesn't work with Java 9.
