### ISSUE TITLE
DataJpaTest fails when updating to SpringBoot 1.5.5.RELEASE

### ISSUE THREAD

**Issue by akutschera** [spring-projects/spring-boot#10465]
I have a working test against an in-memory database with Spring Boot 1.5.4.RELEASE (or 2.0.0.M2)
When I upgrade my project to 1.5.5.RELEASE (or 2.0.0.M3) the test fails because it cannot load the application context:
```
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:83)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:117)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
	at org.springframework.boot.test.autoconfigure.SpringBootDependencyInjectionTestExecutionListener.prepareTestInstance(SpringBootDependencyInjectionTestExecutionListener.java:44)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:230)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:228)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:287)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:289)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:247)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.lang.IllegalStateException: Unable to retrieve @EnableAutoConfiguration base packages
	at org.springframework.boot.autoconfigure.AutoConfigurationPackages.get(AutoConfigurationPackages.java:78)
	at org.springframework.boot.autoconfigure.data.AbstractRepositoryConfigurationSourceSupport.getBasePackages(AbstractRepositoryConfigurationSourceSupport.java:78)
	at org.springframework.boot.autoconfigure.data.AbstractRepositoryConfigurationSourceSupport$1.getBasePackages(AbstractRepositoryConfigurationSourceSupport.java:72)
	at org.springframework.data.repository.config.RepositoryConfigurationSourceSupport.getCandidates(RepositoryConfigurationSourceSupport.java:75)
	at org.springframework.data.repository.config.RepositoryConfigurationExtensionSupport.getRepositoryConfigurations(RepositoryConfigurationExtensionSupport.java:83)
...
```
Basically, this is my test
```
@RunWith(SpringRunner.class)
@ContextConfiguration(classes = {SamePackageEntity.class})
@DataJpaTest
public class SamePackageEntityTest {

    @Autowired
    private SamePackageRepository samePackageRepository;

    @Test
    public void repositoryShouldHaveBeenInitialized() throws Exception {
        assertThat( samePackageRepository.count() ).isEqualTo( 0L );
    }

}
```
Is the problem in the update or in my Test?

I've added a pull request to spring-boot-issues that reproduces this problem

**Comment by snicoll** [comment]
That is interesting although your test configuration is wrong all along. `DataJpaTest` is already taking care of the JPA setup and `SamePackageEntity` is _not_ a valid source (it's not a bean, it's not a configuration class, it has no spring lifecycle annotation on it).

Having said that, if I create a `SpringBootConfiguration` in that package and I remove the `@ContextConfiguration` (or if I provide a valid source in `@ContextConfiguration`) it should work and it does not so there is definitely a regression there.

**Comment by dmitrysenkovich** [comment]
I'm experiencing the same problem

**Comment by snicoll** [comment]
Relates to #9282

**Comment by wilkinsona** [comment]
A workaround for this is to add `@AutoConfigurationPackage` to the `@SpringBootConfiguration` class that's needed because there's no `@SpringBootApplication` class in the sample:

```java
package com.github.akutschera.data.jpatest;

import org.springframework.boot.SpringBootConfiguration;
import org.springframework.boot.autoconfigure.AutoConfigurationPackage;

@SpringBootConfiguration
@AutoConfigurationPackage
public class TestConfiguration {

}
```

**Comment by wilkinsona** [comment]
In fact, I think the above may be the best long-term solution to the problem as, arguably, the test is misconfigured and it worked previously only by accident.

This problem only occurs in an atypical Spring Boot application where there's no configuration class (meta-)annotated with `@EnableAutoConfiguration`. That moves from being atypical to arguably being misconfigured when also trying to use one of the test slice annotations (`@DataJpaTest` in this case). One of the primary purposes of the test slice annotations is to narrow down auto-configuration to focus on a particular slice of your application. Therefore, using a test slice annotation when you're not using auto-configuration doesn't make sense. That's what the sample project was attempting to do.

@akutschera I suspect some of the details of why your application is structured the way it is may have got lost in creating a minimal sample. Can you please describe your real-world application in a bit more detail? I'm particularly interested in your main class, use of `@EnableAutoConfiguration` and why you were apparently trying to use `@DataJpaTest` without auto-configuration.

**Comment by akutschera** [comment]
Yes, I tried to strip away as much as possible (and maybe too much)
In real life I am trying to initialize as few classes as possible for each test, because a SpringBootTest takes quite long to initialize and I do not want to create dozens of Beans that I won't use in my tests.

So basically, when I annotate my tests with just `@SpringBootTest` they pass. So I usually do something like `@SpringBootTest(classes = { MyService.class, etc. })`.  When I discovered `@DataJpaTest` I tried to experiment with it to see how it can be used and how to minimalize initialization.

So it was probably a misuse that only used to work by accident. Thanks for the explanation.
From my point of view this can be closed as "won't fix".

**Comment by wilkinsona** [comment]
@akutschera Thanks for following up.

**Comment by nenaraab** [comment]
Hi, 
unfortunately I get the same issue when upgrading from SpringBoot 1.4.1.RELEASE to 1.5.9.RELEASE, even though i have referred to a real `@Configuration` class :-)

[Your Workaround works](https://github.com/spring-projects/spring-boot/issues/10465#issuecomment-336397898), but it is ugly and contradicts the [documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-testing.html#boot-features-testing-spring-boot-applications-testing-autoconfigured-jpa-test).

I've added a [pull request](https://github.com/spring-projects/spring-boot-issues/pull/73) to spring-boot-issues that reproduces this problem and reopened the issue to get notified, when it is fixed or at least documented.

Thanks a lot for your support!

**Comment by wilkinsona** [comment]
@nenaraab You shouldn’t be using `@DataJpaTest` and `@SpringBootTest` at the same time. Also, subclassing part of Boot’s auto-configuration `JpaBaseConfiguration` is discouraged.

**Comment by nenaraab** [comment]
@wilkinsona Thanks for the tips!
Replaced `@SpringBootTest` by `@ContextConfiguration`.

What would be your recommendation for auto configurations? Create my own one and exclude the other one e.g. `JpaBaseConfiguration`?

**Comment by wilkinsona** [comment]
> and: would you mind to reopen this issue, till it is fixed?

I still don't believe there's anything to fix here. Your application fits the description in [this comment I made above](https://github.com/spring-projects/spring-boot/issues/10465#issuecomment-336401586). Specifically, there's no class annotated with `@EnableAutoConfiguration` and you're trying to use `@DataJpaTest`. That only worked previously due to a bug in 1.5.4 and earlier.

> Replaced `@SpringBootTest` by `@ContextConfiguration`

That shouldn't be necessary, and is rather odd as you're referencing an entity in your `@ContextConfiguration` rather than a configuration class. Instead, you should add a main application class annotated with `@SpringBootApplication` (or `@EnableAutoConfiguration`) as shown in the following diff:

```diff
diff --git a/gh-10465/src/main/java/com/github/akutschera/data/jpatest/JpaTestApplication.java b/gh-10465/src/main/java/com/github/akutschera/data/jpatest/JpaTestApplication.java
new file mode 100644
index 0000000..a1961c8
--- /dev/null
+++ b/gh-10465/src/main/java/com/github/akutschera/data/jpatest/JpaTestApplication.java
@@ -0,0 +1,13 @@
+package com.github.akutschera.data.jpatest;
+
+import org.springframework.boot.SpringApplication;
+import org.springframework.boot.autoconfigure.SpringBootApplication;
+
+@SpringBootApplication
+public class JpaTestApplication {
+
+       public static void main(String[] args) throws Exception {
+               SpringApplication.run(JpaTestApplication.class, args);
+       }
+
+}
diff --git a/gh-10465/src/test/java/com/github/akutschera/data/jpatest/SamePackageEntityTest.java b/gh-10465/src/test/java/com/github/akutschera/data/jpatest/SamePackageEntityTest.java
index f3b41da..8c605db 100644
--- a/gh-10465/src/test/java/com/github/akutschera/data/jpatest/SamePackageEntityTest.java
+++ b/gh-10465/src/test/java/com/github/akutschera/data/jpatest/SamePackageEntityTest.java
@@ -11,7 +11,6 @@ import org.springframework.test.context.ContextConfiguration;
 import org.springframework.test.context.junit4.SpringRunner;

 @RunWith(SpringRunner.class)
-@ContextConfiguration(classes = {SamePackageEntity.class})
 @DataJpaTest
 public class SamePackageEntityTest {
```

> What would be your recommendation for auto configurations? Create my own one and exclude the other one e.g. JpaBaseConfiguration?

Upon closer inspection, I've just noticed that you're subclassing `JpaBaseConfiguration` as you want to use Eclipse Link rather than Hibernate. For the purpose, it isn't discouraged.

**Comment by nenaraab** [comment]
Thanks a lot for your expert review and support!
