### ISSUE TITLE
NPE on LdapHealthIndicator

### ISSUE THREAD

**Issue by Bert-R** [spring-projects/spring-boot#10558]
Our code to configure LDAP looks like this:

```java
@Bean
public LdapTemplate ldapTemplate() {
	if (!yonaProperties.getLdap().isEnabled()) {
		logger.info("Skipping LDAP initialization, as it's not enabled.");
		return null;
	}
	LdapContextSource contextSource = new LdapContextSource();
	contextSource.setUrl(yonaProperties.getLdap().getUrl());
	contextSource.setBase(yonaProperties.getLdap().getBaseDn());
	contextSource.setUserDn(yonaProperties.getLdap().getAccessUserDn());
	contextSource.setPassword(yonaProperties.getLdap().getAccessUserPassword());
	contextSource.afterPropertiesSet();
	return new LdapTemplate(contextSource);
}
```

As you see, we leave the bean null when LDAP is not enabled. This worked fine till we upgraded Spring Boot from 1.4.7 to 1.5.7. After that, it started to fail with the below exception:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ldapHealthIndicator' defined in class path resource [org/springframework/boot/actuate/autoconfigure/HealthIndicatorAutoConfiguration$LdapHealthIndicatorConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.health.HealthIndicator]: Factory method 'ldapHealthIndicator' threw exception; nested exception is java.lang.IllegalStateException: Unable to create indicator class org.springframework.boot.actuate.health.LdapHealthIndicator for source interface org.springframework.ldap.core.LdapOperations
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599) ~[spring-beans-4.3.11.RELEASE.jar:4.3.11.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173) ~[spring-beans-4.3.11.RELEASE.jar:4.3.11.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067) ~[spring-beans-4.3.11.RELEASE.jar:4.3.11.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513) ~[spring-beans-4.3.11.RELEASE.jar:4.3.11.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.11.RELEASE.jar:4.3.11.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.11.RELEASE.jar:4.3.11.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.11.RELEASE.jar:4.3.11.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.11.RELEASE.jar:4.3.11.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.11.RELEASE.jar:4.3.11.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.11.RELEASE.jar:4.3.11.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) ~[spring-context-4.3.11.RELEASE.jar:4.3.11.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-4.3.11.RELEASE.jar:4.3.11.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) ~[spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) ~[spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
        at nu.yona.server.DatabaseInitializationApplication.main(DatabaseInitializationApplication.java:24) [main/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.health.HealthIndicator]: Factory method 'ldapHealthIndicator' threw exception; nested exception is java.lang.IllegalStateException: Unable to create indicator class org.springframework.boot.actuate.health.LdapHealthIndicator for source interface org.springframework.ldap.core.LdapOperations
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.3.11.RELEASE.jar:4.3.11.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.3.11.RELEASE.jar:4.3.11.RELEASE]
        ... 15 common frames omitted
Caused by: java.lang.IllegalStateException: Unable to create indicator class org.springframework.boot.actuate.health.LdapHealthIndicator for source interface org.springframework.ldap.core.LdapOperations
        at org.springframework.boot.actuate.autoconfigure.CompositeHealthIndicatorConfiguration.createHealthIndicator(CompositeHealthIndicatorConfiguration.java:65) ~[spring-boot-actuator-1.5.7.RELEASE.jar:1.5.7.RELEASE]
        at org.springframework.boot.actuate.autoconfigure.CompositeHealthIndicatorConfiguration.createHealthIndicator(CompositeHealthIndicatorConfiguration.java:43) ~[spring-boot-actuator-1.5.7.RELEASE.jar:1.5.7.RELEASE]
        at org.springframework.boot.actuate.autoconfigure.HealthIndicatorAutoConfiguration$LdapHealthIndicatorConfiguration.ldapHealthIndicator(HealthIndicatorAutoConfiguration.java:256) ~[spring-boot-actuator-1.5.7.RELEASE.jar:1.5.7.RELEASE]
        at org.springframework.boot.actuate.autoconfigure.HealthIndicatorAutoConfiguration$LdapHealthIndicatorConfiguration$$EnhancerBySpringCGLIB$$3b2c650.CGLIB$ldapHealthIndicator$0(<generated>) ~[spring-boot-actuator-1.5.7.RELEASE.jar:1.5.7.RELEASE]
        at org.springframework.boot.actuate.autoconfigure.HealthIndicatorAutoConfiguration$LdapHealthIndicatorConfiguration$$EnhancerBySpringCGLIB$$3b2c650$$FastClassBySpringCGLIB$$fdc42427.invoke(<generated>) ~[spring-boot-actuator-1.5.7.RELEASE.jar:1.5.7.RELEASE]
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.11.RELEASE.jar:4.3.11.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358) ~[spring-context-4.3.11.RELEASE.jar:4.3.11.RELEASE]
        at org.springframework.boot.actuate.autoconfigure.HealthIndicatorAutoConfiguration$LdapHealthIndicatorConfiguration$$EnhancerBySpringCGLIB$$3b2c650.ldapHealthIndicator(<generated>) ~[spring-boot-actuator-1.5.7.RELEASE.jar:1.5.7.RELEASE]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_144]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_144]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.11.RELEASE.jar:4.3.11.RELEASE]
        ... 16 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_144]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_144]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_144]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_144]
        at org.springframework.boot.actuate.autoconfigure.CompositeHealthIndicatorConfiguration.createHealthIndicator(CompositeHealthIndicatorConfiguration.java:62) ~[spring-boot-actuator-1.5.7.RELEASE.jar:1.5.7.RELEASE]
        ... 28 common frames omitted
Caused by: java.lang.IllegalArgumentException: LdapOperations must not be null
        at org.springframework.util.Assert.notNull(Assert.java:134) ~[spring-core-4.3.11.RELEASE.jar:4.3.11.RELEASE]
        at org.springframework.boot.actuate.health.LdapHealthIndicator.<init>(LdapHealthIndicator.java:40) ~[spring-boot-actuator-1.5.7.RELEASE.jar:1.5.7.RELEASE]
        ... 33 common frames omitted
```

For now, I have disabled the health indicator by setting ``management.health.ldap.enabled`` to ``false``, but it would be better to prevent this issue when LDAP is not configured.

**Comment by philwebb** [comment]
I'm not sure what's changed between 1.4 and 1.5 but we still guard the `LdapHealth` indicator with a `@ConditionalOnBean`. See [line 241 of `HealthIndicatorAutoConfiguration`](https://github.com/spring-projects/spring-boot/blob/3e68c55db92a89e5681297c6216b5e4046fb6594/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/autoconfigure/HealthIndicatorAutoConfiguration.java#L241).

Returning `null` from `@Bean` method isn't recommended as the bean definition still exists. I would suggest that you use a `@ConditionalOnProperty` guard on your `ldapTemplate()` method and also explicitly disable our `LdapAutoConfiguration` so that we never create an LDAP bean for you.

**Comment by Bert-R** [comment]
Thanks for your guidance and sorry for bothering you with a ticket!
