### ISSUE TITLE
spring boot start failed, cannot resolve reference to bean

### ISSUE THREAD

**Issue by GaussDing** [spring-projects/spring-boot#10650]
Hello, my project use spring boot 1.5.3, because use SpringBootApplication decorate start is very slow, so instead Configuration and Import, however then service can not start.

**My Application:**

```
@ImportResource("classpath:spring-context.xml")
@Configuration
@Import({
    AopAutoConfiguration.class,
    AopAutoConfiguration.JdkDynamicAutoProxyConfiguration.class,
    DataSourceAutoConfiguration.class,
    DataSourcePoolMetadataProvidersConfiguration.class,
    DataSourceTransactionManagerAutoConfiguration.class,
    GroovyTemplateAutoConfiguration.class,
    GsonAutoConfiguration.class,
    HsfConsumerAutoConfiguration.class,
    JacksonAutoConfiguration.class,
    JdbcTemplateAutoConfiguration.class,
    JmxAutoConfiguration.class,
    PersistenceExceptionTranslationAutoConfiguration.class,
    ProjectInfoAutoConfiguration.class,
    PropertyPlaceholderAutoConfiguration.class,
    SolrAutoConfiguration.class,
    TransactionAutoConfiguration.class,
    ValidationAutoConfiguration.class,
    HSFConfig.class,
    BeanConfig.class,
    EnvConfig.class,
})
public class Application {
    
    public static void main(String[] args) {
        PandoraBootstrap.run(args);
        SpringApplication.run(Application.class, args);
        // 上线前一些初始化工作
        AppInitCheck.checkInitOk();
        PandoraBootstrap.markStartupAndWait();
    }
}
```

and then **classpath:spring-context.xml:**

```
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd">


    <import resource="classpath:rodimus/spring-*.xml"/>
    <import resource="classpath*:sentinel-tracer.xml" />

</beans>
```

**classpath:rodimus/spring-notify.xml:**

```
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd">

	<bean id="notifyManager" class="xxx" init-method="init">
		<property name="debug" value="false" />
		<property name="debugLocalPort" value="19999" />
		<property name="groupId" value="RODIMUS_SHOP_SCENE" />
		<property name="description" value="SubscriberNotifyManager" />
		<property name="name" value="SubscriberNotifyManager" />
		<property name="messageListener" ref="libraCenterMessageListener" />
	</bean>
```

**the last libraCenterMessageListener code:**

```
@Component
public class LibraCenterMessageListener implements MessageListener {
    @Resource
    private EnvConfig envConfig;
    @Resource
    private SceneManager sceneManager;
    @Resource
    private ShopSceneManager shopSceneManager;
    @Resource
    private DefaultCommonTairManager<Integer> sceneLdbManager;
    @Resource
    private ApplicationConfigService applicationConfigService;
    @Resource
    private ShopScenePromotionManager shopScenePromotionManager;
    
    private static ClientAppInfo CAI = new ClientAppInfo();
    
    static {
        CAI.setAppName("rodimus");
    }

   ...
}
```

**# Issue stacktrace:**

```
[WARNING]
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.taobao.pandora.boot.loader.LaunchRunner.run(LaunchRunner.java:38)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'notifyManager' defined in file [/Users/xilin.ding/GitProject/social/rodimus/rodimus-start/target/classes/rodimus/spring-notify.xml]: Cannot resolve reference to bean 'libraCenterMessageListener' while setting bean property 'messageListener'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'libraCenterMessageListener' available
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1531)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1276)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151)
	at com.taobao.rodimus.Application.main(Application.java:66)
	... 6 more
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'libraCenterMessageListener' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:687)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1207)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:284)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
	... 24 more
Stopping available [components]
```

I think maybe spring boot injection and xml combine use cause the question, beacause LibraCenterMessageListener with @Component decorate, so don't config LibraCenterMessageListener bean xml, If i define LibraCenterMessageListener bean in xml, the LibraCenterMessageListener @Resource class can not find bean that with @Component decorate

@wilkinsona 
thks

**Comment by wilkinsona** [comment]
@GaussDing Unfortunately, it's impossible to diagnose the problem from the information that you've provided. If you'd like us to investigate, please provide a minimal, complete sample that we can use to reproduce the problem. A git repository that we can clone and run or a zip attachment that we can extract and run is ideal.

**Comment by GaussDing** [comment]
@wilkinsona I'm sorry that the project dependency inner service can't not provide
