### ISSUE TITLE
NullPointerException in XADataSourceAutoConfiguration when configuring a LocalContainerEntityManagerFactoryBean

### ISSUE THREAD

**Issue by jdmichal** [spring-projects/spring-boot#10661]
This issue effects at least Spring Boot 1.5.2 and Spring Boot 1.5.4.  I have isolated the error to a small test project, which I have attached:

[spring-boot-repro.zip](https://github.com/spring-projects/spring-boot/files/1389230/spring-boot-repro.zip)

# Code

The code attempts to create a `LocalContainerEntityManagerFactoryBean` with an injected `DataSource`:

    @Bean("entityManagerFactory")
    public static LocalContainerEntityManagerFactoryBean getEntityManagerFactory(
        final javax.sql.DataSource dataSource) {
        
        final LocalContainerEntityManagerFactoryBean entityManagerFactory =
            new LocalContainerEntityManagerFactoryBean();
        entityManagerFactory.setDataSource(dataSource);
        return entityManagerFactory;
    }

This is inline with the [Spring Boot documentation](https://docs.spring.io/spring-boot/docs/1.5.4.RELEASE/reference/htmlsingle/#howto-use-traditional-persistence-xml) for creating an entity manager with a `persistence.xml` file, which is not included in the test project as it's not required to reproduce the issue.

# Expected

I expect that this code would run, and I would have a Spring context containing the correctly-configured `EntityManagerFactory`.

# Actual

I receive the following stack trace:

	Caused by: java.lang.NullPointerException: null
	    at org.springframework.boot.autoconfigure.jdbc.XADataSourceAutoConfiguration.createXaDataSource(XADataSourceAutoConfiguration.java:83) ~[spring-boot-autoconfigure-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
	    at org.springframework.boot.autoconfigure.jdbc.XADataSourceAutoConfiguration.dataSource(XADataSourceAutoConfiguration.java:72) ~[spring-boot-autoconfigure-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
	    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	    at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	    ... 41 common frames omitted

# Debugging Information

Looking at the [relevant line of code](https://github.com/spring-projects/spring-boot/blob/v1.5.4.RELEASE/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jdbc/XADataSourceAutoConfiguration.java#L83) in the debugger, `this.properties` is null.  It should be the auto-wired `DataSourceProperties`.

Removing `spring-boot-starter-jta-bitronix` fixes the issue, presumably because `XADataSourceAutoConfiguration` no longer runs.

The `DataSourceAutoConfiguration` class does not seem to have this issue, but it also requests `DataSourceProperties` as a parameter instead of auto-wiring it.  Unsure whether this difference contributes to the problem.

**Comment by wilkinsona** [comment]
Thanks for the sample. The problem only occurs when the `@Bean` method that creates the `LocalContainerEntityManagerFactoryBean` is declared `static`. There's no need for it to be `static` so I would recommend that you remove it. You may also want to raise a Spring Framework issue I would not expect declaring the method as `static` to break that expected bean lifecycle which is what's causing the `NullPointerException`.

**Comment by jdmichal** [comment]
@wilkinsona Thanks! That did indeed fix the problem. I never would have tried removing the `static`... I'll file an issue on the Spring JIRA.
