### ISSUE TITLE
Support prefix bytes with fat jars

### ISSUE THREAD

**Issue by aantono** [spring-projects/spring-boot#1073]
When trying to create a self-starting bash script with embedded jar (https://coderwall.com/p/ssuaxa) the startup throws an exception.

```
Exception in thread "main" java.lang.IllegalStateException: java.io.IOException: Unable to read bytes
    at org.springframework.boot.loader.ExecutableArchiveLauncher.<init>(ExecutableArchiveLauncher.java:52)
    at org.springframework.boot.loader.ExecutableArchiveLauncher.<init>(ExecutableArchiveLauncher.java:44)
    at org.springframework.boot.loader.JarLauncher.<init>(JarLauncher.java:30)
    at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:45)
Caused by: java.io.IOException: Unable to read bytes
    at org.springframework.boot.loader.jar.Bytes.get(Bytes.java:50)
    at org.springframework.boot.loader.jar.JarEntryData.<init>(JarEntryData.java:66)
    at org.springframework.boot.loader.jar.JarEntryData.fromInputStream(JarEntryData.java:170)
    at org.springframework.boot.loader.jar.JarFile.loadJarEntries(JarFile.java:136)
    at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:126)
    at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:107)
    at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:97)
    at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:47)
    at org.springframework.boot.loader.Launcher.createArchive(Launcher.java:154)
    at org.springframework.boot.loader.ExecutableArchiveLauncher.<init>(ExecutableArchiveLauncher.java:49)
    ... 3 more
```

When testing the file with `jar tvf run.sh` the content of the file gets printed just fine.

After reading http://mesosphere.io/2013/12/07/executable-jars/ it appears that the Zip/Jar format supports prepended arbitrary, non-Zip data and yet remain interpretable to the Zip decompressor, which is what is being used to create self-executing applications.

For some reason the Bytes parsing errors when trying to read that kind of jar. :(

**Comment by Robin479** [comment]
Hi all. I haven't looked at the details of the init.d features, yet, but I wanted to mention here that there is more to a daemon than a simple embedded init.d interface. Specifically, a daemon should (be able to) drop superuser privileges once it has consumed boot configuration files and acquired protected system resources (e.g. binding to port 80). The "user code" that makes up the actual spring application should then be initialized and run without such privileges, e.g. file system IO should usually be restricted to (service) user file permissions (e.g. during usual operation, a newly created file belongs to "myappsysuser" rather than root).

This would certainly require a two-stage ApplicationContext: initializing Spring Boot, acquiring privileged resource, dropping the JVM process to user privileges (a native system call), and then initializing the user coded/provided/configured subsystems.
Have a look at commons-daemon's Daemon interface: initialize()/shutdown() is where you should read system configuration files and acquire privileged resources as root, and start()/stop() is where you actually startup the user's application including thread pools and database access.

**Comment by Robin479** [comment]
...by "user" I mean "developer building a Spring Boot integrated application", of course.
