### ISSUE TITLE
Spring Boot 2.0.0.M5 breaks gRPC-based client libraries

### ISSUE THREAD

**Issue by saturnism** [spring-projects/spring-boot#10744]
Using Spring Boot 2.0.0 M5 to build a simple web app that uses [Google Cloud Pub/Sub client library](https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-pubsub).  This library is gRPC-based, and contains netty & tcnative library that's required for HTTP/2 & ALPN.

However, when initializing, it throws an error that's typical of classpath conflicts w/ tomcat or netty:
```
Caused by: java.lang.IllegalArgumentException: Jetty ALPN/NPN has not been properly configured.
        at io.grpc.netty.GrpcSslContexts.selectApplicationProtocolConfig(GrpcSslContexts.java:159) ~[grpc-netty-1.6.1.jar:1.6.1]
        at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:136) ~[grpc-netty-1.6.1.jar:1.6.1]
        at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:124) ~[grpc-netty-1.6.1.jar:1.6.1]
        at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:94) ~[grpc-netty-1.6.1.jar:1.6.1]
        at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory$DefaultNettyTransportCreationParamsFilterFactory.<init>(NettyChannelBuilder.java:525) ~[grpc-netty-1.6.1.jar:1.6.1]
        at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory$DefaultNettyTransportCreationParamsFilterFactory.<init>(NettyChannelBuilder.java:518) ~[grpc-netty-1.6.1.jar:1.6.1]
        at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory.<init>(NettyChannelBuilder.java:457) ~[grpc-netty-1.6.1.jar:1.6.1]
        at io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:326) ~[grpc-netty-1.6.1.jar:1.6.1]
        at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:315) ~[grpc-core-1.6.1.jar:1.6.1]
        at com.google.api.gax.grpc.InstantiatingChannelProvider.createChannel(InstantiatingChannelProvider.java:131) ~[gax-grpc-0.26.0.jar:na]
        at com.google.api.gax.grpc.InstantiatingChannelProvider.getChannel(InstantiatingChannelProvider.java:116) ~[gax-grpc-0.26.0.jar:na]
        at com.google.cloud.pubsub.v1.Publisher.<init>(Publisher.java:140) ~[google-cloud-pubsub-0.26.0-beta.jar:0.26.0-beta]
        at com.google.cloud.pubsub.v1.Publisher.<init>(Publisher.java:79) ~[google-cloud-pubsub-0.26.0-beta.jar:0.26.0-beta]
        at com.google.cloud.pubsub.v1.Publisher$Builder.build(Publisher.java:625) ~[google-cloud-pubsub-0.26.0-beta.jar:0.26.0-beta]
        at com.example.demo.DemoApplication.lambda$cli$0(DemoApplication.java:30) [classes/:na]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:789) [spring-boot-2.0.0.M5.jar:2.0.0.M5]
        ... 6 common frames omitted
```

This problem does not occur w/ Spring Boot 1.5.x.
This problems does occur w/ Spring Boot 2.0.0 M5 w/ both Java 9 and Java 8.

**Comment by wilkinsona** [comment]
Given the apparent likelihood that this is due to a classpath conflict, can you please provide a sample with the necessary dependencies to reproduce the problem?

**Comment by krm1312** [comment]
Try bumping version of netty-tcnative-boringssl-static to 2.0.6.Final.

https://github.com/netty/netty/commit/5de38051c973b5558bb30379a2f44db7d6f309c3

https://github.com/netty/netty-tcnative/pull/298

There is an unenforced dependency between netty and netty-tcnative-boringssl-static versions I believe.

**Comment by saturnism** [comment]
@krm1312's suggestion worked.  gRPC has dependency on netty 4.1.14.Final to pair w/ tcnative 2.0.3.Final. However, Reactor dependency managed Netty to 4.1.16.Final, which requires the newer version of tcnative.

I suppose if Reactor doesn't want to dep-manage tcnative?

**Comment by bclozel** [comment]
Neither Reactor Netty nor Spring Boot are using that dependency (not even transitively) right now - this might change in the future.

In both cases, we're importing the Netty BOM, which does not manage that dependency.

You can always override the Netty version managed by Boot by changing the `<netty.version>` maven property - this is especially relevant if you're not using Reactor Netty for your application.

**Comment by saturnism** [comment]
In case someone else landed on this issue, also check the new troubleshooting gRPC guide: https://github.com/grpc/grpc-java/blob/master/SECURITY.md#troubleshooting
