### ISSUE TITLE
Devtools with Java 9 can lead to invalid cache

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#10927]
Running DevTools with Java9 leads to

```
java.lang.reflect.InaccessibleObjectException: Unable to make field private static final java.util.WeakHashMap com.sun.naming.internal.ResourceManager.propertiesCache accessible: module java.naming does not "opens com.sun.naming.internal" to unnamed module @6039c586
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:337) ~[na:na]
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:281) ~[na:na]
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:176) ~[na:na]
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:170) ~[na:na]
	at org.springframework.boot.devtools.restart.Restarter.clear(Restarter.java:357) [spring-boot-devtools-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
	at org.springframework.boot.devtools.restart.Restarter.clear(Restarter.java:348) [spring-boot-devtools-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
	at org.springframework.boot.devtools.restart.Restarter.cleanupKnownCaches(Restarter.java:343) [spring-boot-devtools-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
	at org.springframework.boot.devtools.restart.Restarter.cleanupCaches(Restarter.java:328) [spring-boot-devtools-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
	at org.springframework.boot.devtools.restart.Restarter.stop(Restarter.java:314) [spring-boot-devtools-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
	at org.springframework.boot.devtools.restart.Restarter.lambda$restart$1(Restarter.java:250) [spring-boot-devtools-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
	at org.springframework.boot.devtools.restart.Restarter$LeakSafeThread.run(Restarter.java:617) ~[spring-boot-devtools-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
```

Java 9's `com.sun.naming.internal.ResourceManager` doesn't  have a `propertiesCache` anymore.

**Comment by izeye** [comment]
In JDK 9 (Oracle JDK 9.0.1) `com.sun.naming.internal.ResourceManager` still does have `propertiesCache` as follows:

```
    private static final WeakHashMap<Object, Hashtable<? super String, Object>>
            propertiesCache = new WeakHashMap<>(11);
```

Looking at the exception message, the cause is from the usage of the JDK's internal package which is not open any more:

```
java.lang.reflect.InaccessibleObjectException: Unable to make field private static final java.util.WeakHashMap com.sun.naming.internal.ResourceManager.propertiesCache accessible: module java.naming does not "opens com.sun.naming.internal" to unnamed module @6039c586
```
