### ISSUE TITLE
Upgrade to 2.0.0.M6 (from M5) raises ClassNotFoundException on org.neo4j.ogm.exception.core.MetadataException

### ISSUE THREAD

**Issue by igler** [spring-projects/spring-boot#10936]
Caused by: java.lang.ClassNotFoundException: org.neo4j.ogm.exception.core.MetadataException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 94 more

**Comment by wilkinsona** [comment]
I think you have the wrong version of OGM on the classpath. You need 3.0.1 (which is the version provided by Boot's dependency management in 2.0 M6).

**Comment by igler** [comment]
That's it. Thanx.
