### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/logging/log4j/core/impl/Log4jLogEvent$Builder

### ISSUE THREAD

**Issue by fhx** [spring-projects/spring-boot#10938]
Hi Spring Boot,

after upgrading to log4j2 im getting a horrible NoClassDefFoundError for Log4jLogEvent after my tomcat 7 server tries to roll logfile. The error occurs when a (cron) scheduled task is starting execution and tries to write to log (log.info("message")

My configuration is
- spring boot 1.5.8
- spring-boot-starter-log4j2 (which includes log4j-core 2.7)

I am wondering if the error should be fixed in spring boot or apache log4j2, but for now im creating the bug in spring-boot :)

Stacktrace:

```
2017-11-06 10:32:01 [taskScheduler-4] ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task.
java.lang.NoClassDefFoundError: org/apache/logging/log4j/core/impl/Log4jLogEvent$Builder
	at org.apache.logging.log4j.core.appender.rolling.PatternProcessor.formatFileName(PatternProcessor.java:234) ~[log4j-core-2.7.jar:2.7]
	at org.apache.logging.log4j.core.appender.rolling.DefaultRolloverStrategy.purgeAscending(DefaultRolloverStrategy.java:316) ~[log4j-core-2.7.jar:2.7]
	at org.apache.logging.log4j.core.appender.rolling.DefaultRolloverStrategy.purge(DefaultRolloverStrategy.java:299) ~[log4j-core-2.7.jar:2.7]
	at org.apache.logging.log4j.core.appender.rolling.DefaultRolloverStrategy.rollover(DefaultRolloverStrategy.java:517) ~[log4j-core-2.7.jar:2.7]
	at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.rollover(RollingFileManager.java:257) ~[log4j-core-2.7.jar:2.7]
	at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.rollover(RollingFileManager.java:192) ~[log4j-core-2.7.jar:2.7]
	at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.checkRollover(RollingFileManager.java:175) ~[log4j-core-2.7.jar:2.7]
	at org.apache.logging.log4j.core.appender.RollingFileAppender.append(RollingFileAppender.java:280) ~[log4j-core-2.7.jar:2.7]
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156) ~[log4j-core-2.7.jar:2.7]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129) ~[log4j-core-2.7.jar:2.7]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120) ~[log4j-core-2.7.jar:2.7]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84) ~[log4j-core-2.7.jar:2.7]
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:447) ~[log4j-core-2.7.jar:2.7]
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:432) ~[log4j-core-2.7.jar:2.7]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:416) ~[log4j-core-2.7.jar:2.7]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:402) ~[log4j-core-2.7.jar:2.7]
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63) ~[log4j-core-2.7.jar:2.7]
	at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146) ~[log4j-core-2.7.jar:2.7]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2091) ~[log4j-api-2.7.jar:2.7]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:1988) ~[log4j-api-2.7.jar:2.7]
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1960) ~[log4j-api-2.7.jar:2.7]
	at org.apache.logging.log4j.spi.AbstractLogger.info(AbstractLogger.java:1297) ~[log4j-api-2.7.jar:2.7]
	at dk.kmd.saba.datasync.scheduler.BillingImportJob.run(BillingImportJob.java:67) ~[BillingImportJob.class:?]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_112]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
```

**Comment by fhx** [comment]
[log4j2.xml.txt](https://github.com/spring-projects/spring-boot/files/1446542/log4j2.xml.txt)
[pom.xml.txt](https://github.com/spring-projects/spring-boot/files/1446545/pom.xml.txt)

**Comment by wilkinsona** [comment]
Can you please provide a small sample that reproduces the behaviour you have described?

**Comment by fhx** [comment]
not easily, its a scheduled task using a RollingFile appender, the error will occur on the first log message 🗡  pretty annoying setup :) is it mandatory to provide a test application, maybe someone has seen the error before

**Comment by wilkinsona** [comment]
Unfortunately, it's pretty much impossible for us to debug something, particularly that may be a problem in another library, without being able to reproduce it.

When you say "tomcat 7 server", am I right in thinking that you're deploying a war file to a standalone instance of Tomcat?

**Comment by fhx** [comment]
@wilkinsona - i understand and luckily it seems that my error was a byzantine (random) error and I have not been able to reproduce the error.

Thx anyway :-)
