### ISSUE TITLE
Spring-Boot-Starter-Bus-amqp does not work in 2.0.0M6

### ISSUE THREAD

**Issue by wlumetsberger** [spring-projects/spring-boot#10940]
I tried to update my application to spring boot version 2.0.0M6. After updating spring cloud bus amqp does not work any longer. 
I tried using a new application via spring initializr with following configuration and got the same error.

```
buildscript {
	ext {
		springBootVersion = '2.0.0.M6'
	}
	repositories {
		mavenCentral()
		maven { url "https://repo.spring.io/snapshot" }
		maven { url "https://repo.spring.io/milestone" }
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
	}
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = 1.8

repositories {
	mavenCentral()
	maven { url "https://repo.spring.io/snapshot" }
	maven { url "https://repo.spring.io/milestone" }
}


ext {
	springCloudVersion = 'Finchley.M3'
}

dependencies {
	compile('org.springframework.cloud:spring-cloud-starter-bus-amqp')
	compile('org.springframework.boot:spring-boot-starter-web')
	testCompile('org.springframework.boot:spring-boot-starter-test')
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
	}
}
```

The Application won't start and produces following error:

```
2017-11-06 18:02:53.316  INFO 11340 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2017-11-06 18:02:53.327  INFO 11340 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2017-11-06 18:02:53.351  INFO 11340 --- [           main] utoConfigurationReportLoggingInitializer :

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2017-11-06 18:02:53.356 ERROR 11340 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jmxMBeanExporter' defined in class path resource [org/springframework/boot/actuate/autoconfigure/endpoint/jmx/JmxEndpointAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: Found multiple JMX operations with the same name:
    env:
        org.springframework.boot.actuate.endpoint.jmx.JmxEndpointOperation@1effd53c
        org.springframework.boot.actuate.endpoint.jmx.JmxEndpointOperation@46c269e0
    refresh:
        org.springframework.boot.actuate.endpoint.jmx.JmxEndpointOperation@6920614
        org.springframework.boot.actuate.endpoint.jmx.JmxEndpointOperation@6069dd38

        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1704) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:583) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:756) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868) ~[spring-context-5.0.1.RELEASE.jar:5.0.1.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.0.1.RELEASE.jar:5.0.1.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:122) ~[spring-boot-2.0.0.M6.jar:2.0.0.M6]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:751) [spring-boot-2.0.0.M6.jar:2.0.0.M6]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:387) [spring-boot-2.0.0.M6.jar:2.0.0.M6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.0.M6.jar:2.0.0.M6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1245) [spring-boot-2.0.0.M6.jar:2.0.0.M6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1233) [spring-boot-2.0.0.M6.jar:2.0.0.M6]
        at com.example.demo.DemoApplication.main(DemoApplication.java:10) [main/:na]
Caused by: java.lang.IllegalStateException: Found multiple JMX operations with the same name:
    env:
        org.springframework.boot.actuate.endpoint.jmx.JmxEndpointOperation@1effd53c
        org.springframework.boot.actuate.endpoint.jmx.JmxEndpointOperation@46c269e0
    refresh:
        org.springframework.boot.actuate.endpoint.jmx.JmxEndpointOperation@6920614
        org.springframework.boot.actuate.endpoint.jmx.JmxEndpointOperation@6069dd38

        at org.springframework.boot.actuate.endpoint.jmx.annotation.JmxAnnotationEndpointDiscoverer.verifyThatOperationsHaveDistinctName(JmxAnnotationEndpointDiscoverer.java:101) ~[spring-boot-actuator-2.0.0.M6.jar:2.0.0.M6]
        at org.springframework.boot.actuate.endpoint.jmx.annotation.JmxAnnotationEndpointDiscoverer.discoverEndpoints(JmxAnnotationEndpointDiscoverer.java:81) ~[spring-boot-actuator-2.0.0.M6.jar:2.0.0.M6]
        at org.springframework.boot.actuate.autoconfigure.endpoint.EndpointProvider.getEndpoints(EndpointProvider.java:58) ~[spring-boot-actuator-autoconfigure-2.0.0.M6.jar:2.0.0.M6]
        at org.springframework.boot.actuate.autoconfigure.endpoint.jmx.JmxEndpointExporter.registerEndpointMBeans(JmxEndpointExporter.java:76) ~[spring-boot-actuator-autoconfigure-2.0.0.M6.jar:2.0.0.M6]
        at org.springframework.boot.actuate.autoconfigure.endpoint.jmx.JmxEndpointExporter.afterPropertiesSet(JmxEndpointExporter.java:65) ~[spring-boot-actuator-autoconfigure-2.0.0.M6.jar:2.0.0.M6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1763) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1700) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
        ... 16 common frames omitted
```

[demo.zip](https://github.com/spring-projects/spring-boot/files/1447161/demo.zip)

**Comment by philwebb** [comment]
I'm not sure if Spring Cloud Finchley M3 is compatible with Boot M6. @spencergibb @dsyer care to comment?

**Comment by wilkinsona** [comment]
Thanks for the sample. At the very least, we need to improve the exception message by overriding `toString()` on `JmxEndpointOperation`.

The two env endpoint operations that clash are backed by the following methods:

- `org.springframework.cloud.bus.endpoint.EnvironmentBusEndpoint.env(java.lang.String,java.lang.String,java.lang.String)`
- `org.springframework.cloud.bus.endpoint.EnvironmentBusEndpoint.env(java.lang.String,java.lang.String)`

The two refresh endpoint operations that clash are backed by the following methods:

- `org.springframework.cloud.bus.endpoint.RefreshBusEndpoint.refresh(java.lang.String)`
- `org.springframework.cloud.bus.endpoint.RefreshBusEndpoint.refresh()`

I've yet to track down what's causing the change in behaviour such that the exception's now thrown.

**Comment by wilkinsona** [comment]
Ah, I interpreted "I tried to update my application to spring boot version 2.0.0M6" as meaning that it worked with an earlier Boot 2.0 milestone. The same failure occurs with M5 (which is the version that Finchley M3 uses by default).

**Comment by dsyer** [comment]
Finchley.M3 uses Boot 2.0.0.M5. Try snapshots, or wait for M4. Of course the issue might be in Boot (in which case I'd expect failing tests in spring-cloud-commons).

**Comment by wilkinsona** [comment]
The change that triggered the exception isn't in Boot. Finchley M3 has added new endpoints:

- https://github.com/spring-cloud/spring-cloud-bus/commit/399bcb04f7d1515ce8a294cc4a4ba1a5d8653dca#diff-47b21fbce170b7ae8f6a6155aeeb3ad7
- https://github.com/spring-cloud/spring-cloud-bus/blob/2.0.x/spring-cloud-bus/src/main/java/org/springframework/cloud/bus/endpoint/EnvironmentBusEndpoint.java

Looks like Spring Cloud Bus is missing some integration tests and Boot may be missing some support for a Spring Cloud Bus use case. The current JMX endpoint contract requires each operation method to be uniquely named. I can't recall the reason for that but I suspect @snicoll will be able to.

**Comment by wilkinsona** [comment]
I've opened https://github.com/spring-projects/spring-boot/issues/10942 to improve the exception message.

**Comment by snicoll** [comment]
> I can't recall the reason for that but I suspect @snicoll will be able to.

You can't have two JMX operations with the same name. We rely on the method name to infer the JMX operation name.

**Comment by dsyer** [comment]
Maybe we could look for a `@ManagedOperation` or something to get a hint for the JMX operation name?

**Comment by wilkinsona** [comment]
The JMX specification recommends against overloading methods, so my preference would be to make sure that the current restriction is documented and to rename the methods in Spring Cloud.

**Comment by snicoll** [comment]
@dsyer actually that should already work now. Having said that, I agree with Andy that the methods in Spring Cloud should be renamed.

**Comment by snicoll** [comment]
@spencergibb confirmed yesterday that he's going to rename those methods. We have an issue for the exception message so I don't think there's much else we should do here. Let me know if I've missed something.

**Comment by wlumetsberger** [comment]
@snicoll , is it possible to get the Ticket within this issue will be fixed. When would you expect the feature will work again ?

**Comment by wlumetsberger** [comment]
@snicoll @spencergibb  , is there any Ticket for renaming those methods ? In which milestone the renaming will be done ?

**Comment by spencergibb** [comment]
https://github.com/spring-cloud/spring-cloud-bus/issues/92 It will be our next milestone, Finchley.M4
