### ISSUE TITLE
spring-cloud-starter-netflix-zuul does not work on Finchley.M3

### ISSUE THREAD

**Issue by danyflorez** [spring-projects/spring-boot#11011]
I'm trying to make an api gateway but I'm getting an error with following configuration:

`buildscript {
	ext {
		springBootVersion = '2.0.0.M6'
	}
	repositories {
		mavenCentral()
		maven { url "https://repo.spring.io/snapshot" }
		maven { url "https://repo.spring.io/milestone" }
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
	}
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'

group = 'com.mastering.spring.zuul'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = 1.8

repositories {
	mavenCentral()
	maven { url "https://repo.spring.io/snapshot" }
	maven { url "https://repo.spring.io/milestone" }
}

ext {
	springCloudVersion = 'Finchley.M3'
}

dependencies {
	compile('org.springframework.cloud:spring-cloud-starter-netflix-eureka-client')
	compile('org.springframework.cloud:spring-cloud-starter-netflix-zuul')
	testCompile('org.springframework.boot:spring-boot-starter-test')
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
	}
}`

**This is the error:**

`Caused by: java.lang.NoSuchMethodError: org.springframework.boot.actuate.autoconfigure.web.servlet.ManagementServletContext.getContextPath()Ljava/lang/String;
	at org.springframework.cloud.netflix.hystrix.HystrixManagementContextConfiguration.hystrixMetricsStreamServlet(HystrixManagementContextConfiguration.java:58) ~[spring-cloud-netflix-core-2.0.0.M3.jar:2.0.0.M3]
	at org.springframework.cloud.netflix.hystrix.HystrixManagementContextConfiguration$$EnhancerBySpringCGLIB$$5678a89f.CGLIB$hystrixMetricsStreamServlet$1(<generated>) ~[spring-cloud-netflix-core-2.0.0.M3.jar:2.0.0.M3]
	at org.springframework.cloud.netflix.hystrix.HystrixManagementContextConfiguration$$EnhancerBySpringCGLIB$$5678a89f$$FastClassBySpringCGLIB$$42305d21.invoke(<generated>) ~[spring-cloud-netflix-core-2.0.0.M3.jar:2.0.0.M3]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361) ~[spring-context-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.cloud.netflix.hystrix.HystrixManagementContextConfiguration$$EnhancerBySpringCGLIB$$5678a89f.hystrixMetricsStreamServlet(<generated>) ~[spring-cloud-netflix-core-2.0.0.M3.jar:2.0.0.M3]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_144]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:155) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	... 24 common frames omitted`

Am I missing something?

**Comment by snicoll** [comment]
Spring Cloud issues are not handled here. The Spring Cloud team is aware that there are such problem with the  last Spring Boot milestone. Please search their issue tracker before reporting or ask on the #spring-cloud channel on Gitter.

**Comment by jarodriguezparadigma** [comment]
@danyflorez we had the same problem. It is because in HystrixManagementContextConfiguration.hystrixMetricsStreamServlet() is performed a call to this.managementServletContext.getContextPath() 
which is a valid method for that interface in spring-boot 1.5.8 
(https://docs.spring.io/spring-boot/docs/1.5.8.RELEASE/api/org/springframework/boot/actuate/endpoint/mvc/ManagementServletContext.html)

But in spring-boot 2.0.0.M6 it changed to the getServletPath() in package org.springframework.boot.actuate.endpoint.mvc

(https://docs.spring.io/spring-boot/docs/2.0.0.M6/api/org/springframework/boot/actuate/autoconfigure/web/servlet/ManagementServletContext.html)

and it is not changed.

While it is fixed we disable hystrix stream metrics by setting management.hyxtrix.enabled to false

**Comment by rohitrajt** [comment]
@jarodriguezparadigma There was typo in your suggetion. We can add the following to our configs,

```
management.hystrix.enabled: false
```
This works. Thanks.
