### ISSUE TITLE
Align spring.metrics.datadog.api-key vs spring.metrics.export.datadog.apiKey in condition/properties

### ISSUE THREAD

**Issue by srinivasvsk** [spring-projects/spring-boot#11053]
Hello

Was testing the Datadog metrics push on M6 spring boot and micrometer datadog .rc3. 
I continue get exceptions when i use the `api-key`, I get this below error

```
Factory method 'compositeMeterRegistry' threw exception; nested exception is java.lang.IllegalStateException: datadog.apiKey must be set to report metrics to Datadog
```

If we use apiKey, it wont autoconfigure datadog because of 
`@ConditionalOnProperty("spring.metrics.datadog.api-key")` on `DatadogExportConfiguration`

What would be the right way to configure datadog publish properties

**Comment by philwebb** [comment]
@srinivasvsk Can you paste the full stacktrace for the "'compositeMeterRegistry' threw exception" error?

**Comment by philwebb** [comment]
Also what do you mean by

> If we use apiKey, it wont autoconfigure datadog because of
@ConditionalOnProperty("spring.metrics.datadog.api-key") on DatadogExportConfiguration

That condition is saying only add datadog support when `spring.metrics.datadog.api-key` has a value. Are you saying you want a `DatadogMeterRegistry` but you need to get the key from somewhere else?

**Comment by srinivasvsk** [comment]
When i use the api-key below is the full stack trace, im just trying to push the metrics to datadog

`Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'webMetricsFilter' defined in class path resource [org/springframework/boot/actuate/autoconfigure/metrics/web/servlet/WebMvcMetricsConfiguration.class]: Unsatisfied dependency expressed through method 'webMetricsFilter' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'controllerMetrics' defined in class path resource [org/springframework/boot/actuate/autoconfigure/metrics/web/servlet/WebMvcMetricsConfiguration.class]: Unsatisfied dependency expressed through method 'controllerMetrics' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'compositeMeterRegistry' defined in class path resource [org/springframework/boot/actuate/autoconfigure/metrics/MetricsAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.micrometer.core.instrument.composite.CompositeMeterRegistry]: Factory method 'compositeMeterRegistry' threw exception; nested exception is java.lang.IllegalStateException: datadog.apiKey must be set to report metrics to Datadog
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:723) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:458) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1249) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1098) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]`

**Comment by srinivasvsk** [comment]
`Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'compositeMeterRegistry' defined in class path resource [org/springframework/boot/actuate/autoconfigure/metrics/MetricsAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.micrometer.core.instrument.composite.CompositeMeterRegistry]: Factory method 'compositeMeterRegistry' threw exception; nested exception is java.lang.IllegalStateException: datadog.apiKey must be set to report metrics to Datadog
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:583) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1249) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1098) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1133) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1060) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:809) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:715) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	... 39 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.micrometer.core.instrument.composite.CompositeMeterRegistry]: Factory method 'compositeMeterRegistry' threw exception; nested exception is java.lang.IllegalStateException: datadog.apiKey must be set to report metrics to Datadog
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:186) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:575) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	... 52 common frames omitted
Caused by: java.lang.IllegalStateException: datadog.apiKey must be set to report metrics to Datadog
	at io.micrometer.datadog.DatadogConfig.apiKey(DatadogConfig.java:39) ~[micrometer-registry-datadog-1.0.0-rc.3.jar:1.0.0-rc.3]
	at io.micrometer.datadog.DatadogConfig.uri(DatadogConfig.java:58) ~[micrometer-registry-datadog-1.0.0-rc.3.jar:1.0.0-rc.3]
	at org.springframework.boot.actuate.autoconfigure.metrics.export.PropertiesConfigAdapter.get(PropertiesConfigAdapter.java:58) ~[spring-boot-actuator-autoconfigure-2.0.0.M6.jar:2.0.0.M6]
	at org.springframework.boot.actuate.autoconfigure.metrics.export.datadog.DatadogPropertiesConfigAdapter.uri(DatadogPropertiesConfigAdapter.java:51) ~[spring-boot-actuator-autoconfigure-2.0.0.M6.jar:2.0.0.M6]
	at io.micrometer.datadog.DatadogMeterRegistry.<init>(DatadogMeterRegistry.java:59) ~[micrometer-registry-datadog-1.0.0-rc.3.jar:1.0.0-rc.3]
	at org.springframework.boot.actuate.autoconfigure.metrics.export.datadog.DatadogExportConfiguration.lambda$datadogExporter$0(DatadogExportConfiguration.java:52) ~[spring-boot-actuator-autoconfigure-2.0.0.M6.jar:2.0.0.M6]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_73]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[na:1.8.0_73]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[na:1.8.0_73]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_73]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_73]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[na:1.8.0_73]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[na:1.8.0_73]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_73]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[na:1.8.0_73]
	at org.springframework.boot.actuate.autoconfigure.metrics.MetricsAutoConfiguration.compositeMeterRegistry(MetricsAutoConfiguration.java:85) ~[spring-boot-actuator-autoconfigure-2.0.0.M6.jar:2.0.0.M6]
	at org.springframework.boot.actuate.autoconfigure.metrics.MetricsAutoConfiguration$$EnhancerBySpringCGLIB$$504c30b4.CGLIB$compositeMeterRegistry$0(<generated>) ~[spring-boot-actuator-autoconfigure-2.0.0.M6.jar:2.0.0.M6]
	at org.springframework.boot.actuate.autoconfigure.metrics.MetricsAutoConfiguration$$EnhancerBySpringCGLIB$$504c30b4$$FastClassBySpringCGLIB$$3925f878.invoke(<generated>) ~[spring-boot-actuator-autoconfigure-2.0.0.M6.jar:2.0.0.M6]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361) ~[spring-context-5.0.1.RELEASE.jar:5.0.1.RELEASE]`

**Comment by philwebb** [comment]
Do you have `spring.metrics.export.datadog.api-key=XXX` set in your `application.properties`?

If you put a breakpoint in `io.micrometer.core.instrument.step.StepRegistryConfig.DatadogConfig.uri()` what happens if you set into the `apiKey()` call? It should jump into `DatadogPropertiesConfigAdapter.apiKey()` which should return the apiKey from `DatadogProperties`.

**Comment by srinivasvsk** [comment]
It does go to DatadogPropertiesConfigAdapter.apiKey but i think the problem is 

https://github.com/spring-projects/spring-boot/blob/v2.0.0.M6/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/metrics/export/datadog/DatadogProperties.java

Is looking for prefix values with different name?
 @ConfigurationProperties(prefix = "spring.metrics.export.datadog")

**Comment by philwebb** [comment]
@srinivasvsk Ahh thanks! Reading the issue again I see you mentioned that in the title, sorry I missed it.
