### ISSUE TITLE
spring-boot-jpa IN query cause InvalidDataAccessApiUsageException

### ISSUE THREAD

**Issue by liukefeng2008** [spring-projects/spring-boot#11122]
When I use `Root<Foo>.get("bar").in(Lists.newArrayList(1, 2, 3));`
will cause:
```text
org.springframework.dao.InvalidDataAccessApiUsageException: Unaware how to convert value [[2] : java.util.ArrayList] to requested type [java.lang.Integer]; nested exception is java.lang.IllegalArgumentException: Unaware how to convert value [[2] : java.util.ArrayList] to requested type [java.lang.Integer]
        at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:384)
```
then I change thie code
```java
List<Integer> nums = Lists.newArrayList(1, 2, 3);
Root<Foo>.get("bar").in(nums);
```
It work for me.
**I think it is a generic problem.**

**Comment by wilkinsona** [comment]
This doesn’t look like a Spring Boot problem to me. It’s hard to tell where the problem actually is as it’s not clear where the `Root` class or the `get` and `in` methods come from. Can you please provide some more details, ideally a small sample and an explanation of why you think this is a Spring Boot bug.

**Comment by liukefeng2008** [comment]
Thanks for your answer.
My code like:
```java
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;
import org.springframework.data.jpa.domain.Specification;


Specification<Foo> spec = (Root<Foo> root, CriteriaQuery<?> query, CriteriaBuilder cb) -> {
List<Predicate> predicates = new ArrayList<>();
predicates.add(cb.equals(root.get("bar"), "cat"));
predicates.add(cb.notEquals(root.get("dog"), "cat"));
...

predicates.add(root.get("banana").in(Lists.newArrayList(1, 2, 3)));

return cb.and(predicates.toArray(new Predicate[]{}));
}
```

In this code,  will cause:
```
org.springframework.dao.InvalidDataAccessApiUsageException: Unaware how to convert value [[2] : java.util.ArrayList] to requested type [java.lang.Integer]; nested exception is java.lang.IllegalArgumentException: Unaware how to convert value [[2] : java.util.ArrayList] to requested type [java.lang.Integer]
        at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:384)
```
If you change last line to:
```java
List<Integer> nums = Lists.newArrayList(1, 2, 3);
predicates.add(root.get("banana").in(nums));
```
It work for me.

**Comment by wilkinsona** [comment]
Thanks for the additional context. As I suspected, this isn't a problem in Spring Boot itself. Unfortunately, you haven't shared the complete stack trace so I still can't pinpoint exactly where the problem is. It could be in Spring Data JPA, the JPA provider you're using (Hibernate?), or Spring Framework. @olivergierke from the Spring Data team may have some insight, but I'd recommend chatting with the Spring Data team [on Gitter](https://gitter.im/spring-projects/spring-data) to get some further guidance.

**Comment by liukefeng2008** [comment]
Thanks for your answer.
Project used Hibernate.
main stack:
```java
pport.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:59)
        at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:213)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:147)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:133)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:57)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
```
