### ISSUE TITLE
PropertiesConfigAdapter does not handle dependencies between default values in Micrometer config

### ISSUE THREAD

**Issue by GreyTeardrop** [spring-projects/spring-boot#11131]
# Issue

In some cases, default values for `MeterRegistryConfig` descendants' methods might depend on values of other attributes, e.g., default value of `DatadogConfig.uri()` depends on value of `DatadogConfig.apiKey()`:

```java
default String uri() {
    String v = get(prefix() + ".apiHost");
    return v == null ? "https://app.datadoghq.com/api/v1/series?api_key=" + apiKey() : v;
}
```

Existing delegation scheme in `PropertiesConfigAdapter` cannot handle such case. If `uri` is not specified in properties, `PropertiesConfigAdapter` delegates to `defaults` implementation, which in turn asks for `apiKey()` and fails, as `defaults` is not bound to any properties.

# Steps to reproduce

1. Include `org.springframework.boot:spring-boot-starter-actuator` and `io.micrometer:micrometer-registry-datadog` into project.
2. Specify Datadog API key via `spring.metrics.export.datadog.api-key` property (as well as via `spring.metrics.datadog.api-key` as M6 does not have #11053 fix).
3. Start application and see it crash with

```
Caused by: java.lang.IllegalStateException: datadog.apiKey must be set to report metrics to Datadog
    at io.micrometer.datadog.DatadogConfig.apiKey(DatadogConfig.java:39) ~[micrometer-registry-datadog-1.0.0-rc.3.jar:1.0.0-rc.3]
    at io.micrometer.datadog.DatadogConfig.uri(DatadogConfig.java:58) ~[micrometer-registry-datadog-1.0.0-rc.3.jar:1.0.0-rc.3]
    at org.springframework.boot.actuate.autoconfigure.metrics.export.PropertiesConfigAdapter.get(PropertiesConfigAdapter.java:58) ~[spring-boot-actuator-autoconfigure-2.0.0.M6.jar:2.0.0.M6]
    at org.springframework.boot.actuate.autoconfigure.metrics.export.datadog.DatadogPropertiesConfigAdapter.uri(DatadogPropertiesConfigAdapter.java:51) ~[spring-boot-actuator-autoconfigure-2.0.0.M6.jar:2.0.0.M6]
    at io.micrometer.datadog.DatadogMeterRegistry.<init>(DatadogMeterRegistry.java:59) ~[micrometer-registry-datadog-1.0.0-rc.3.jar:1.0.0-rc.3]
    at org.springframework.boot.actuate.autoconfigure.metrics.export.datadog.DatadogExportConfiguration.lambda$datadogExporter$0(DatadogExportConfiguration.java:52) ~[spring-boot-actuator-autoconfigure-2.0.0.M6.jar:2.0.0.M6]
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_152]
    at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[na:1.8.0_152]
    at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[na:1.8.0_152]
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_152]
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_152]
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[na:1.8.0_152]
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[na:1.8.0_152]
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_152]
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[na:1.8.0_152]
    at org.springframework.boot.actuate.autoconfigure.metrics.MetricsAutoConfiguration.compositeMeterRegistry(MetricsAutoConfiguration.java:85) ~[spring-boot-actuator-autoconfigure-2.0.0.M6.jar:2.0.0.M6]
    at org.springframework.boot.actuate.autoconfigure.metrics.MetricsAutoConfiguration$$EnhancerBySpringCGLIB$$ed487e57.CGLIB$compositeMeterRegistry$1(<generated>) ~[spring-boot-actuator-autoconfigure-2.0.0.M6.jar:2.0.0.M6]
    at org.springframework.boot.actuate.autoconfigure.metrics.MetricsAutoConfiguration$$EnhancerBySpringCGLIB$$ed487e57$$FastClassBySpringCGLIB$$6fc70bd2.invoke(<generated>) ~[spring-boot-actuator-autoconfigure-2.0.0.M6.jar:2.0.0.M6]
    at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-5.0.1.RELEASE.jar:5.0.1.RELEASE]
    at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361) ~[spring-context-5.0.1.RELEASE.jar:5.0.1.RELEASE]
    at org.springframework.boot.actuate.autoconfigure.metrics.MetricsAutoConfiguration$$EnhancerBySpringCGLIB$$ed487e57.compositeMeterRegistry(<generated>) ~[spring-boot-actuator-autoconfigure-2.0.0.M6.jar:2.0.0.M6]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_152]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_152]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_152]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_152]
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:155) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
```

# Environment

Spring Boot 2.0.0.M6, Micrometer Datadog 1.0.0-rc.3

# Thoughts

I would be happy to provide a fix via PR, but I'm not sure what would be the best way to fix it. I was able to fix issue by making `uri` fallback delegate to `super` instead of default config:

```java
class DatadogPropertiesConfigAdapter
        extends StepRegistryPropertiesConfigAdapter<DatadogProperties, DatadogConfig>
        implements DatadogConfig {

    private static final DatadogConfig DEFAULTS = (k) -> null;

    DatadogPropertiesConfigAdapter(DatadogProperties properties) {
        super(properties, DEFAULTS);
    }

    @Override
    public String apiKey() {
        return get(DatadogProperties::getApiKey, DatadogConfig::apiKey);
    }

    @Override
    public String hostTag() {
        return get(DatadogProperties::getHostTag, DatadogConfig::hostTag);
    }

    @Override
    public String uri() {
        return get(DatadogProperties::getUri, c -> DatadogConfig.super.uri());
    }

}
```

for consistency (and to make sure any other dependencies are covered) it should be applied to all methods, not just `uri()`. However, it makes code completely ignore passed `DEFAULTS`.

**Comment by GreyTeardrop** [comment]
I've added a PR with a possible fix for this issue.

**Comment by snicoll** [comment]
Closing in favour of PR #11135
