### ISSUE TITLE
@DataJpaTest does not throw exception when saving unpersisted object in @ManyToMany collection

### ISSUE THREAD

**Issue by hughwphamill** [spring-projects/spring-boot#11183]
Reproduction Project here -> https://github.com/hughwphamill/spring-datajpatest-issue

Spring Boot 1.5.8.RELEASE

I would expect that the following test would pass, or at least cause exception

```java
@Test
    public void unmanaged_bar_cannot_be_retrieved_through_foo() throws Exception {
        // Given
        final Foo foo = new Foo("name");
        final Bar bar = new Bar("description");

        // When
        foo.addBar(bar);
        final int fooId = fooRepository.save(foo).getId();
        final Foo retrievedFoo = fooRepository.findOne(fooId);

        // Then
        assertThat(retrievedFoo.getBars()).isEmpty(); // <-- Not Empty!
    }
```

However no exception is thrown and test fails with

```bash
java.lang.AssertionError: 
Expecting empty but was:<[Bar{id=null, description='description'}]>
```

**Comment by snicoll** [comment]
Your test doesn't flush anything and is only working with the first level cache. I've used the `TestEntityManager` and replace that test to use

```
final int fooId = entityManager.persistAndFlush(foo).getId();
```

and I get 

```
java.lang.IllegalStateException: org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing: com.github.hughwphamill.springdata.issue.Bar

	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1689)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1602)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1608)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.flush(AbstractEntityManagerImpl.java:1303)
	at org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager.flush(TestEntityManager.java:172)
	at org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager.persistAndFlush(TestEntityManager.java:132)
	at com.github.hughwphamill.springdata.issue.RepositoryTest.unmanaged_bar_cannot_be_retrieved_through_foo(RepositoryTest.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
```

**Comment by hughwphamill** [comment]
Ok, I think that should be clearly documented, or have the ability to turn off the cache.

If I am using spring data jpa repositories then I expect to be able to test my code in the @DataJpaTest slice, especially code which may handle exceptions from the repository. 

I shouldn't have to get an entity manager involved at all, especially if testing the service layer. 

What do you think?

**Comment by snicoll** [comment]
> What do you think?

The issue has nothing to do with `@DataJpaTest`. As far as I can see, the way you've written the test is wrong (i.e relying on the transaction commit per repository call). `@DataJpaTest` is transactional by default and [this is already documented](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-testing-spring-boot-applications-testing-autoconfigured-jpa-test).

**Comment by hughwphamill** [comment]
Ok I think 8 see the way forward.

Use @DataJpaTest with test entity manager to validate the JPA annotations on the entity. Then use @SpringBootTest to test any code working with repositories.

Thanks for the insight, it's clearer in my head now.

**Comment by hughwphamill** [comment]
Sorry above should be I see the way forward, commenting on mobile!

**Comment by snicoll** [comment]
Actually, no. You should use `@DataJpaTest` to test your repositories as well. If you have more questions, please ask on StackOverflow or join the community on Gitter.
