### ISSUE TITLE
Provide dependency management for JAXB as it's not provided with Java9 anymore

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#11205]
To reproduce, build the `spring-boot-sample-data-jpa` sample (`mvn spring-boot:run` works fine because we're not forking the process) and run the jar with java 9:

`$ java -jar spring-boot-sample-data-jpa-2.0.0.BUILD-SNAPSHOT.jar`

```
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.hibernate.boot.spi.XmlMappingBinderAccess.<init>(XmlMappingBinderAccess.java:43) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
	at org.hibernate.boot.MetadataSources.<init>(MetadataSources.java:87) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:208) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:163) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:51) ~[spring-orm-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365) ~[spring-orm-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:387) ~[spring-orm-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:376) ~[spring-orm-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341) ~[spring-orm-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1769) ~[spring-beans-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1706) ~[spring-beans-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
	... 24 common frames omitted
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563) ~[na:na]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93) ~[spring-boot-sample-data-jpa-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496) ~[na:na]
	... 35 common frames omitted
```

Adding jaxb or adding the `java.xml.bind` modules are two options to fix this issue. If the user choses the former, we don't have dependency management and they have to hardcode the version.

**Comment by GurinderSinghBrar** [comment]
java.xml.bind modules have already been added to spring-boot-parent and spring-boot-samples 
pom.xml.

**Comment by wilkinsona** [comment]
The Platform currently has dependency management for JAX-B 2.3.0 so let's move it over into Boot.
