### ISSUE TITLE
java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy

### ISSUE THREAD

**Issue by mxl123** [spring-projects/spring-boot#11214]
TypeNotPresentExceptionProxy when I run my application

```
20171130 18:00:46-393] ERROR [main][org.springframework.boot.SpringApplication:771]- Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Invocation of init method failed; nested exception is java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at wanfang.service.ServiceApplication.main(ServiceApplication.java:31)
Caused by: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3521)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.createAnnotationData(Class.java:3526)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getAnnotation(Class.java:3415)
	at java.lang.reflect.AnnotatedElement.isAnnotationPresent(AnnotatedElement.java:258)
	at java.lang.Class.isAnnotationPresent(Class.java:3425)
	at org.springframework.core.annotation.AnnotatedElementUtils.hasAnnotation(AnnotatedElementUtils.java:617)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.isHandler(RequestMappingHandlerMapping.java:173)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.initHandlerMethods(AbstractHandlerMethodMapping.java:213)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.afterPropertiesSet(AbstractHandlerMethodMapping.java:184)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.afterPropertiesSet(RequestMappingHandlerMapping.java:127)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)
	... 14 common frames omitted
```

**Comment by wilkinsona** [comment]
Can you please provide a small sample that reproduces the problem?

**Comment by mxl123** [comment]
When I update a dependency which created by another team to a new version, then I got this problem, my spring-boot is 1.5.6.RELEASE. 

This is my main class

@SpringBootApplication
public class ServiceApplication extends SpringBootServletInitializer {

    private static final Logger logger = LoggerFactory.getLogger(ServiceApplication.class);

    public static void main(String[] args) {

        SpringApplication app = new SpringApplication(ServiceApplication.class);
        app.setWebEnvironment(true);

        Set<Object> set = new HashSet<Object>();
        set.add("classpath:applicationContext.xml");
        app.setSources(set);
        ConfigurableApplicationContext context = app.run(args);
        Environment env = context.getBean(Environment.class);
    }
}

**Comment by wilkinsona** [comment]
Unfortunately, just the main class is insufficient. To be able to help you with this, we need a complete, minimal sample that reproduces the problem.

**Comment by mxl123** [comment]
My project can only run under company LAN with the effect JAR, I don't know what can I offer you, maybe you can give me some suggestions about this problem,  then I try to fix by myself.

**Comment by wilkinsona** [comment]
I can try to describe how to diagnose the cause of the failure. You need to set a breakpoint on the constructor of `sun.reflect.annotation.TypeNotPresentExceptionProxy`. You can do that in Eclipse by opening the type and then, in the Outline view, right-clicking on `TypeNotPresentExceptionProxy(String, Throwable)` and selecting `Toggle Method Breakpoint`. If you debug your application with the breakpoint in place, the `Throwable` that's passed to the constructor should provide information about the type that wasn't present.

**Comment by mxl123** [comment]
@wilkinsona Thank you very much,  I have resolve the problem, the dependency onconflict caused it.

**Comment by jigarshah** [comment]
@mxl123 which dependency caused it ? same issue with my app

**Comment by Sam-vish07** [comment]
@mxl123 can you please provide the dependency which caused the conflict. I am also facing the same issue.

**Comment by snicoll** [comment]
All, `TypeNotPresentExceptionProxy` is not specific to a particular dependency and will depend on each project's classpath. We don't use the tracker for questions, so please follow [the advice above](https://github.com/spring-projects/spring-boot/issues/11214#issuecomment-348455967). If that doesn't help, share a minimal project on SO or chat with us on Gitter.
