### ISSUE TITLE
Buggy javassist library dependency with 2.0.0.M6

### ISSUE THREAD

**Issue by jgolubenko** [spring-projects/spring-boot#11225]
[note: this is tested with Java 9.0.1 (Oracle 9.0.1+11), gradle 4.3]

2.0.0.M6 version of spring-boot-starter-data-jpa includes javassist lib via following dependencies:

```
+--- org.springframework.boot:spring-boot-starter-data-jpa: -> 2.0.0.M6
....
|    +--- org.hibernate:hibernate-core:5.2.12.Final
....
|    |    +--- org.javassist:javassist:3.20.0-GA -> 3.22.0-CR2
```

Upon startup of the jar application: `gradle bootJar && java -jar build/libs/app.jar` following runtime exception happens:
```

2017-11-30 12:45:02.661 ERROR 85878 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.boot.archive.spi.ArchiveException: Could not build ClassFile
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1704) ~[spring-beans-5.0.1.RELEASE.jar!/:5.0.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:583) ~[spring-beans-5.0.1.RELEASE.jar!/:5.0.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502) ~[spring-beans-5.0.1.RELEASE.jar!/:5.0.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312) ~[spring-beans-5.0.1.RELEASE.jar!/:5.0.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228) ~[spring-beans-5.0.1.RELEASE.jar!/:5.0.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310) ~[spring-beans-5.0.1.RELEASE.jar!/:5.0.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-5.0.1.RELEASE.jar!/:5.0.1.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1083) ~[spring-context-5.0.1.RELEASE.jar!/:5.0.1.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:858) ~[spring-context-5.0.1.RELEASE.jar!/:5.0.1.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.0.1.RELEASE.jar!/:5.0.1.RELEASE]
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:44) ~[spring-boot-2.0.0.M6.jar!/:2.0.0.M6]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:751) [spring-boot-2.0.0.M6.jar!/:2.0.0.M6]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:387) [spring-boot-2.0.0.M6.jar!/:2.0.0.M6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.0.M6.jar!/:2.0.0.M6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1245) [spring-boot-2.0.0.M6.jar!/:2.0.0.M6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1233) [spring-boot-2.0.0.M6.jar!/:2.0.0.M6]
        at com.company.app.MyApplication.main(MyApplication.java:10) [classes!/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [affiliate-1.0.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [affiliate-1.0.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [affiliate-1.0.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [affiliate-1.0.jar:na]
Caused by: org.hibernate.boot.archive.spi.ArchiveException: Could not build ClassFile
        at org.hibernate.boot.archive.scan.spi.ClassFileArchiveEntryHandler.toClassFile(ClassFileArchiveEntryHandler.java:64) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
        at org.hibernate.boot.archive.scan.spi.ClassFileArchiveEntryHandler.handleEntry(ClassFileArchiveEntryHandler.java:47) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
        at org.hibernate.boot.archive.internal.JarFileBasedArchiveDescriptor.visitArchive(JarFileBasedArchiveDescriptor.java:147) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
        at org.hibernate.boot.archive.scan.spi.AbstractScannerImpl.scan(AbstractScannerImpl.java:47) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
        at org.hibernate.boot.model.process.internal.ScanningCoordinator.coordinateScan(ScanningCoordinator.java:75) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.prepare(MetadataBuildingProcess.java:98) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:228) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:163) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
        at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:51) ~[spring-orm-5.0.1.RELEASE.jar!/:5.0.1.RELEASE]
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:358) ~[spring-orm-5.0.1.RELEASE.jar!/:5.0.1.RELEASE]
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:384) ~[spring-orm-5.0.1.RELEASE.jar!/:5.0.1.RELEASE]
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:373) ~[spring-orm-5.0.1.RELEASE.jar!/:5.0.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1763) ~[spring-beans-5.0.1.RELEASE.jar!/:5.0.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1700) ~[spring-beans-5.0.1.RELEASE.jar!/:5.0.1.RELEASE]
        ... 24 common frames omitted
Caused by: java.io.IOException: invalid constant type: 19 at 5
        at javassist.bytecode.ConstPool.readOne(ConstPool.java:1244) ~[javassist-3.22.0-CR2.jar!/:na]
        at javassist.bytecode.ConstPool.read(ConstPool.java:1175) ~[javassist-3.22.0-CR2.jar!/:na]
        at javassist.bytecode.ConstPool.<init>(ConstPool.java:185) ~[javassist-3.22.0-CR2.jar!/:na]
        at javassist.bytecode.ClassFile.read(ClassFile.java:839) ~[javassist-3.22.0-CR2.jar!/:na]
        at javassist.bytecode.ClassFile.<init>(ClassFile.java:164) ~[javassist-3.22.0-CR2.jar!/:na]
        at org.hibernate.boot.archive.scan.spi.ClassFileArchiveEntryHandler.toClassFile(ClassFileArchiveEntryHandler.java:61) ~[hibernate-core-5.2.12.Final.jar!/:5.2.12.Final]
        ... 37 common frames omitted
```
This issue was already reported, discussed and fixed in javaassist v 3.22.0-GA:
https://github.com/jboss-javassist/javassist/issues/147

Currently M6 release needs following modification to build.gradle in order to run:

```
dependencies {
    compile('org.springframework.boot:spring-boot-starter-data-jpa') {
        exclude group: 'org.javassist' // remove transitive buggy dependency 
    }
    compile('org.javassist:javassist:3.22.0-GA') // add dep with bug fix
    // rest of deps
}
```

**Comment by philwebb** [comment]
Thanks for the detailed report. It looks like this was fixed by [HHH-12048](https://hibernate.atlassian.net/browse/HHH-12048) and will be in Hibernate 5.2.13. I think I'd rather just wait and pickup that release in due course than add a direct managed dependency on javassist which could get out of sync.

**Comment by wilkinsona** [comment]
We’ve got that [dependency management](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-dependencies/pom.xml#L75) already. Complete with an almost certainly stale comment about being the same as Hibernate. Perhaps we should remove it?

**Comment by philwebb** [comment]
Gahh, I missed that :)  Thanks Andy. Yeah, lets re-purpose this one to remove it.

**Comment by wilkinsona** [comment]
The dependency management was originally added in #402. Thymeleaf, via a dependency on `ognl:ognl`, was pulling in a version of javassist that Hibernate didn't like so the dependency management was added to prevent that from happening. Things have moved on since then. 

`thymeleaf-spring5` excludes `ognl:ognl` so, if you're using our Thymeleaf starter, you no longer get `javassist` on the classpath and it's likely to only get onto the classpath via Hibernate. Based on this, I think we can proceed with removing our dependency management of javassist. It would be nice, however, to do that after upgrading to Hibernate 5.3.13 so that we don't drop back to javassist 3.20.

**Comment by wilkinsona** [comment]
We're going to do this now rather than waiting for Hibernate 5.2.13.

**Comment by rajadilipkolli** [comment]
5.2.13 is released now.  http://in.relation.to/2018/02/07/hibernate-orm-5213-final-release/
