### ISSUE TITLE
spring-boot > 2.0.0.M5 problems with loading properties from application.yaml (Kotlin)

### ISSUE THREAD

**Issue by tafypz** [spring-projects/spring-boot#11220]
We are running a spring-integration-ftp process using spring-boot.
Everything works using spring-boot 2.0.0.M5 and spring-integration-ftp 5.0 GA
however using spring boot 2.0.0 M6 or M7 fails to connect to the ftp server (nothing changed in config or code, just changing the version of spring boot).

we are getting this error:
```
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_144]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_144]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_144]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_144]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_144]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_144]
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:188) ~[commons-net-3.5.jar!/:3.5]
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:209) ~[commons-net-3.5.jar!/:3.5]
	at org.springframework.integration.ftp.session.AbstractFtpSessionFactory.createClient(AbstractFtpSessionFactory.java:193) ~[spring-integration-ftp-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.integration.ftp.session.AbstractFtpSessionFactory.getSession(AbstractFtpSessionFactory.java:167) ~[spring-integration-ftp-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
```

Full stacktrace:

```
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:792) ~[spring-boot-2.0.0.M6.jar!/:2.0.0.M6]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:773) ~[spring-boot-2.0.0.M6.jar!/:2.0.0.M6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335) ~[spring-boot-2.0.0.M6.jar!/:2.0.0.M6]
	at com.example.treuters.datastream.ingestor.Application$Companion.main(Application.kt:45) [classes!/:na]
	at com.example.treuters.datastream.ingestor.Application.main(Application.kt) [classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_144]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [treuters-datastream-ftp-ingestor-0.1.1.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [treuters-datastream-ftp-ingestor-0.1.1.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [treuters-datastream-ftp-ingestor-0.1.1.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [treuters-datastream-ftp-ingestor-0.1.1.jar:na]
Caused by: java.lang.IllegalStateException: failed to create FTPClient
	at org.springframework.integration.ftp.session.AbstractFtpSessionFactory.getSession(AbstractFtpSessionFactory.java:170) ~[spring-integration-ftp-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.integration.ftp.session.AbstractFtpSessionFactory.getSession(AbstractFtpSessionFactory.java:41) ~[spring-integration-ftp-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.integration.file.remote.session.CachingSessionFactory$1.createForPool(CachingSessionFactory.java:81) ~[spring-integration-file-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.integration.file.remote.session.CachingSessionFactory$1.createForPool(CachingSessionFactory.java:78) ~[spring-integration-file-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.integration.util.SimplePool.doGetItem(SimplePool.java:193) ~[spring-integration-core-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.integration.util.SimplePool.getItem(SimplePool.java:174) ~[spring-integration-core-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.integration.file.remote.session.CachingSessionFactory.getSession(CachingSessionFactory.java:123) ~[spring-integration-file-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.integration.file.remote.RemoteFileTemplate.execute(RemoteFileTemplate.java:431) ~[spring-integration-file-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.integration.file.remote.gateway.AbstractRemoteFileOutboundGateway.doLs(AbstractRemoteFileOutboundGateway.java:613) ~[spring-integration-file-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.integration.file.remote.gateway.AbstractRemoteFileOutboundGateway.handleRequestMessage(AbstractRemoteFileOutboundGateway.java:584) ~[spring-integration-file-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:109) ~[spring-integration-core-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:141) ~[spring-integration-core-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116) ~[spring-integration-core-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:132) ~[spring-integration-core-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:105) ~[spring-integration-core-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73) ~[spring-integration-core-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:438) ~[spring-integration-core-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:388) ~[spring-integration-core-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:181) ~[spring-messaging-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSendAndReceive(GenericMessagingTemplate.java:227) ~[spring-messaging-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSendAndReceive(GenericMessagingTemplate.java:47) ~[spring-messaging-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
	at org.springframework.messaging.core.AbstractMessagingTemplate.sendAndReceive(AbstractMessagingTemplate.java:45) ~[spring-messaging-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
	at org.springframework.integration.core.MessagingTemplate.sendAndReceive(MessagingTemplate.java:97) ~[spring-integration-core-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.integration.core.MessagingTemplate.sendAndReceive(MessagingTemplate.java:38) ~[spring-integration-core-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.messaging.core.AbstractMessagingTemplate.convertSendAndReceive(AbstractMessagingTemplate.java:95) ~[spring-messaging-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
	at org.springframework.messaging.core.AbstractMessagingTemplate.convertSendAndReceive(AbstractMessagingTemplate.java:85) ~[spring-messaging-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
	at org.springframework.integration.gateway.MessagingGatewaySupport.doSendAndReceive(MessagingGatewaySupport.java:487) ~[spring-integration-core-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.integration.gateway.MessagingGatewaySupport.sendAndReceive(MessagingGatewaySupport.java:461) ~[spring-integration-core-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.integration.gateway.GatewayProxyFactoryBean.invokeGatewayMethod(GatewayProxyFactoryBean.java:520) ~[spring-integration-core-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.integration.gateway.GatewayProxyFactoryBean.doInvoke(GatewayProxyFactoryBean.java:469) ~[spring-integration-core-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.integration.gateway.GatewayProxyFactoryBean.invoke(GatewayProxyFactoryBean.java:460) ~[spring-integration-core-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
	at com.sun.proxy.$Proxy49.fetchFiles(Unknown Source) ~[na:na]
	at com.example.treuters.datastream.ingestor.Application$commandLineRunner$1.run(Application.kt:35) ~[classes!/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:789) ~[spring-boot-2.0.0.M6.jar!/:2.0.0.M6]
	... 12 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_144]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_144]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_144]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_144]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_144]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_144]
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:188) ~[commons-net-3.5.jar!/:3.5]
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:209) ~[commons-net-3.5.jar!/:3.5]
	at org.springframework.integration.ftp.session.AbstractFtpSessionFactory.createClient(AbstractFtpSessionFactory.java:193) ~[spring-integration-ftp-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	at org.springframework.integration.ftp.session.AbstractFtpSessionFactory.getSession(AbstractFtpSessionFactory.java:167) ~[spring-integration-ftp-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
	... 47 common frames omitted
```

**Comment by snicoll** [comment]
@tafypz that's quite hard to track down what is going on with the `Connection Refused` bits. Can you share  a sample that reproduces the problem?

**Comment by tafypz** [comment]
@snicoll My apologies, I spoke too soon.
In the process of creating the sample code for you, I have nailed the issue down to M6 and M7 not picking up properties in application.yaml (We use kotlin):

[application.yaml]
`treuters:
  datastream:
    ftp:
      host: datastreamddl.thomsonreuters.com`

[FtpSourceProperties.kt]
`open class FtpSourceProperties {
    var host: String = "localhost"
    var port: Int = 21
    var userName: String = ""
    var password: String = ""
    var clientMode: FtpClientMode = FtpClientMode.PassiveLocal
    var fileType: FtpFileType = FtpFileType.Binary
    var bufferSize: Int = 100_000
    var remoteFolder: String = "/"
    var outputFolder: String = "ftp-inbound"
}`

[DatastreamFtpSourceProperties.kt]
`@ConfigurationProperties("treuters.datastream.ftp")
class DatastreamFtpSourceProperties : FtpSourceProperties() {
    var filterNames : String = ""
}`

[Config.kt]
`@Configuration
@EnableConfigurationProperties(DatastreamFtpSourceProperties::class)
class Config {
...
}`

We are reading the properties for username and password from a command line argument provided like so: 
--treuters.datastream.ftp.user-name=XXXX --treuters.datastream.ftp.password=YYYY

These get passed through without a hitch.
However the value available to the DatastreamFtpSourceProperties is not the one in application.yaml but "localhost" which is the default value.

this happens on M6 and M7 but not M5

**Comment by snicoll** [comment]
There is nothing immediate that jump at me that would prevent the value to be read. You could try to add the actuator this app and browse to `/actuator/env/treuters.datastream.ftp.host` to see if it's set. If it is, please share a sample that reproduces the issue (adding code in a comment doesn't help us as we'd have to copy/paste  all that ourselves to figure things out).

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by lopitz** [comment]
Hi @tafypz,
I had the same problem today after upgrading from M3 to M7 and finally figured out, that I passed in the program argument `--spring.config.location` with an existing folder. This folder however didn't contain any configuration files. After removing the program argument, it worked as before. It also works, when there is a configuration file in this folder.

Could you pls check, whether you had the same root cause?

**Comment by tafypz** [comment]
@lopitz Thanks, unfortunately we do not use the `--spring.config.location` argument so the problem must be lying somewhere else.

**Comment by snicoll** [comment]
@tafypz any reason why you can't share a sample?

**Comment by tafypz** [comment]
@snicoll we have been swamped with a couple of releases, and passed the property via command line argument as a workaround (using `--reuters.datastream.ftp.host=datastreamddl.thomsonreuters.com`). I will provide a sample when things quiet down.

**Comment by snicoll** [comment]
Alright, let's reopen when you have a sample to share.
