### ISSUE TITLE
 AuditEvent: Principal must not be null when Authentication.getName() returns null

### ISSUE THREAD

**Issue by lukas-krecan-lt** [spring-projects/spring-boot#11241]
If Spring security authentication fails (most likely due to null principal) I am getting this exception which in turn results in 500 HTTP error

```
Caused by: java.lang.IllegalArgumentException: Principal must not be null
	at org.springframework.util.Assert.notNull(Assert.java:134)
	at org.springframework.boot.actuate.audit.AuditEvent.<init>(AuditEvent.java:88)
	at org.springframework.boot.actuate.audit.AuditEvent.<init>(AuditEvent.java:64)
	at org.springframework.boot.actuate.security.AuthorizationAuditListener.onAuthorizationFailureEvent(AuthorizationAuditListener.java:67)
	at org.springframework.boot.actuate.security.AuthorizationAuditListener.onApplicationEvent(AuthorizationAuditListener.java:47)
	at org.springframework.boot.actuate.security.AuthorizationAuditListener.onApplicationEvent(AuthorizationAuditListener.java:33)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.publishEvent(AbstractSecurityInterceptor.java:504)
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:236)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:65)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
```

**Comment by wilkinsona** [comment]
> most likely due to null principal

A `null` principal should [result in an empty string](https://github.com/spring-projects/spring-security/blob/4.2.3.RELEASE/core/src/main/java/org/springframework/security/authentication/AbstractAuthenticationToken.java#L81-L91) being passed to `AuditEvent`:

```
public String getName() {
	if (this.getPrincipal() instanceof UserDetails) {
		return ((UserDetails) this.getPrincipal()).getUsername();
	}

	if (getPrincipal() instanceof Principal) {
		return ((Principal) getPrincipal()).getName();
	}

	return (this.getPrincipal() == null) ? "" : this.getPrincipal().toString();
}
```

If `Authentication.getName()` is returning `null`, I'd like to understand why. Can you please provide a small sample application that reproduces the failure?

**Comment by lukas-krecan-lt** [comment]
Hi, you are right, we have our own implementation of Authentication object and its getName() returns null  for this user.  We can fix it in our code. I will leave it up to you if it's something that needs to be fixed in Spring boot as well.

**Comment by wilkinsona** [comment]
Thanks for following up. `getName()` comes from `java.security.Principal` and its javadoc is silent on whether it's expected that it may return `null`. I guess that means we should tolerate it and map it to an empty string.

**Comment by nklmish** [comment]
@wilkinsona I can take care of this , will update the [constructor](https://github.com/nklmish/spring-boot/blob/master/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/audit/AuditEvent.java#L91). thoughts ?

**Comment by snicoll** [comment]
@nklmish please go ahead. You'll figure it out while writing  the tests for it.

**Comment by snicoll** [comment]
Closing in favour of PR #11320
