### ISSUE TITLE
Spring Data Couchbase reactive should add rxjava as dependencies

### ISSUE THREAD

**Issue by hantsy** [spring-projects/spring-boot#11245]
I converted a  spring data couchbase reactive sample to [boot based](https://github.com/hantsy/spring-reactive-sample/tree/master/boot-data-couchbase). 

But when I added `spring-boot-starter-data-couchbase-reactive` into dependencies, then starts up the application, I got the error info like this:

```
can not find adapter for rx.Single.
```

I have to add the `rxjava` into dependencies to overcome this issue.

```xml
        <dependency>
            <groupId>io.reactivex</groupId>
            <artifactId>rxjava</artifactId>
        </dependency>
        <dependency>
            <groupId>io.reactivex</groupId>
            <artifactId>rxjava-reactive-streams</artifactId>
        </dependency> 
```

And another issue confused me for some days,  my data initializer will cause another exception at runtime.

```java
@Component
@Slf4j
class DataInitializer implements CommandLineRunner {

    private final PostRepository posts;

    public DataInitializer(PostRepository posts) {
        this.posts = posts;
    }

    @Override
    public void run(String[] args) {
        log.info("start data initialization  ...");
        this.posts
            .deleteAll()
            .thenMany(
                Flux
                    .just("Post one", "Post two")
                    .flatMap(
                        title -> this.posts.save(Post.builder().id(UUID.randomUUID().toString()).title(title).content("content of " + title).build())
                    )
            )
            .log()
            .subscribe(
                null,
                null,
                () -> log.info("done initialization...")
            );

    }

}
```
The exception details is here. I have posted [this on stackoverflow some days ago](https://stackoverflow.com/questions/46491963/classcastexception-was-threw-when-call-deleteall-of-reative-spring-data-couchbas).
```
2017-12-02 16:50:50.956 ERROR 15784 --- [-computations-2] reactor.Flux.ConcatArray.1               : onError(java.lang.ClassCastException: rx.Observable cannot be cast to com.couchbase.client.java.view.AsyncViewRow)
2017-12-02 16:50:50.964 ERROR 15784 --- [-computations-2] reactor.Flux.ConcatArray.1               : 

java.lang.ClassCastException: rx.Observable cannot be cast to com.couchbase.client.java.view.AsyncViewRow
	at org.springframework.data.couchbase.repository.support.SimpleReactiveCouchbaseRepository.lambda$deleteAll$8(SimpleReactiveCouchbaseRepository.java:254) ~[spring-data-couchbase-3.0.2.RELEASE.jar:3.0.2.RELEASE]
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69) [rxjava-1.3.4.jar:1.3.4]
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77) [rxjava-1.3.4.jar:1.3.4]
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:101) ~[rxjava-1.3.4.jar:1.3.4]
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:395) ~[rxjava-1.3.4.jar:1.3.4]
	at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:355) ~[rxjava-1.3.4.jar:1.3.4]
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:846) ~[rxjava-1.3.4.jar:1.3.4]
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77) [rxjava-1.3.4.jar:1.3.4]
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77) [rxjava-1.3.4.jar:1.3.4]
	at rx.internal.producers.SingleProducer.request(SingleProducer.java:65) ~[rxjava-1.3.4.jar:1.3.4]
	at rx.Subscriber.setProducer(Subscriber.java:211) ~[rxjava-1.3.4.jar:1.3.4]
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102) [rxjava-1.3.4.jar:1.3.4]
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102) [rxjava-1.3.4.jar:1.3.4]
	at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:110) ~[rxjava-1.3.4.jar:1.3.4]
	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:281) ~[rxjava-1.3.4.jar:1.3.4]
	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:216) ~[rxjava-1.3.4.jar:1.3.4]
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) ~[rxjava-1.3.4.jar:1.3.4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_152]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_152]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_152]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_152]
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: rx.Observable.class
	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118) ~[rxjava-1.3.4.jar:1.3.4]
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73) [rxjava-1.3.4.jar:1.3.4]
	... 22 common frames omitted
```

**Comment by philwebb** [comment]
It looks to me like RxJava is a required dependency if you want to use `com.couchbase.client.java.AsyncBucket` etc. @mp911de Is the the case? If so we should add a managed dependency.

**Comment by mp911de** [comment]
There are two things in there:

1. A bug in Spring Data Couchbase (`ClassCastException`): Please file a ticket at 
https://jira.spring.io/browse/DATACOUCH along a minimal bit of code to reproduce the issue.
2. Spring Boot Starter for Couchbase/Reactive should bring `io.reactivex:rxjava-reactive-streams`:

Spring Data Couchbase requires RxJava 1. Right now it's a transitive dependency of `com.couchbase.client:core-io` and pinned to Spring Data's dependency management (effective version as of Kay SR2 is RxJava 1.3.4):

```
[INFO] |  +- org.springframework.data:spring-data-couchbase:jar:3.0.2.RELEASE:compile
[INFO] |  |  +- org.springframework:spring-context:jar:5.0.2.RELEASE:compile
[INFO] |  |  +- org.springframework:spring-tx:jar:5.0.2.RELEASE:compile
[INFO] |  |  +- org.springframework.data:spring-data-commons:jar:2.0.2.RELEASE:compile
[INFO] |  |  +- com.couchbase.client:java-client:jar:2.5.2:compile
[INFO] |  |  |  \- com.couchbase.client:core-io:jar:1.5.2:compile
[INFO] |  |  |     \- io.reactivex:rxjava:jar:1.3.4:compile
```

What's currently missing from the reactive starter is `io.reactivex:rxjava-reactive-streams`: Couchbase driver and the reactive Template API are based on RxJava 1 while Couchbase's reactive repository support is implemented using Project Reactor. To adapt RxJava 1 to Reactor, Spring Data Couchbase requires an adapter library (`rxjava-reactive-streams`).

**Comment by philwebb** [comment]
Thanks @mp911de. I've raised [DATACOUCH-356](https://jira.spring.io/browse/DATACOUCH-356)  to deal with the `ClassCastException`. We'll use this issue to add the RxJava dependency.

**Comment by hantsy** [comment]
@mp911de @philwebb  Thanks
