### ISSUE TITLE
Actuator with custom http code

### ISSUE THREAD

**Issue by yvladimirov** [spring-projects/spring-boot#11263]
Hello. My rest service return custom http code. In spec I can return any int value.
But if I used Actuator metrics - this not worked, because Metrics can't find custom code

Spring boot 2.0.6M

```
org.springframework.boot.actuate.metrics.web.servlet.WebMvcTags

public static Tag uri(HttpServletRequest request, HttpServletResponse response) {
		if (response != null) {
			HttpStatus status = HttpStatus.valueOf(response.getStatus());
			if (status.is3xxRedirection()) {
				return Tag.of("uri", "REDIRECTION");
			}
			if (status.equals(HttpStatus.NOT_FOUND)) {
				return Tag.of("uri", "NOT_FOUND");
			}
		}
		String uri = (String) request
				.getAttribute(HandlerMapping.BEST_MATCHING_PATTERN_ATTRIBUTE);
		if (uri == null) {
			uri = request.getPathInfo();
		}
		if (!StringUtils.hasText(uri)) {
			uri = "/";
		}
		return Tag.of("uri", uri.isEmpty() ? "root" : uri);
	}

```

Example

```
@SpringBootApplication
@RestController
public class Main {

    @GetMapping
    public ResponseEntity test(){
        return ResponseEntity.status(601).build();
    }

    public static void main(String[] args) {
        SpringApplication.run(Main.class, args);
    }
}

```
ERROR

```
java.lang.IllegalArgumentException: No matching constant for [601]
	at org.springframework.http.HttpStatus.valueOf(HttpStatus.java:520) ~[spring-web-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcTags.uri(WebMvcTags.java:71) ~[spring-boot-actuator-2.0.0.M6.jar:2.0.0.M6]
	at org.springframework.boot.actuate.metrics.web.servlet.DefaultWebMvcTagsProvider.httpRequestTags(DefaultWebMvcTagsProvider.java:56) ~[spring-boot-actuator-2.0.0.M6.jar:2.0.0.M6]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetrics.getTimerBuilder(WebMvcMetrics.java:156) ~[spring-boot-actuator-2.0.0.M6.jar:2.0.0.M6]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetrics.lambda$recordTimerTasks$2(WebMvcMetrics.java:147) ~[spring-boot-actuator-2.0.0.M6.jar:2.0.0.M6]
	at java.util.Collections$SingletonSet.forEach(Collections.java:4767) ~[na:1.8.0_151]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetrics.recordTimerTasks(WebMvcMetrics.java:146) ~[spring-boot-actuator-2.0.0.M6.jar:2.0.0.M6]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetrics.record(WebMvcMetrics.java:126) ~[spring-boot-actuator-2.0.0.M6.jar:2.0.0.M6]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterWithMetrics(WebMvcMetricsFilter.java:99) ~[spring-boot-actuator-2.0.0.M6.jar:2.0.0.M6]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:72) ~[spring-boot-actuator-2.0.0.M6.jar:2.0.0.M6]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) ~[spring-web-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) ~[tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]

```

Workaround

`exclude = MetricsAutoConfiguration.class` -but is no good solution

**Comment by wilkinsona** [comment]
We should probably tolerate the non-standard status code. In the meantime, you can avoid the problem by providing your own `WebMvcTagsProvider` bean.
