### ISSUE TITLE
MockMvc error handling with CompletableFuture regression in 2.0.0.M6+

### ISSUE THREAD

**Issue by mdjnewman** [spring-projects/spring-boot#11345]
In `2.0.0.M5`, the following controller:

```kotlin
@SpringBootApplication
@RestController
class DemoApplication {
    @RequestMapping("/sad", method = arrayOf(RequestMethod.POST))
    fun getErroringCompletableFuture(): CompletableFuture<String> {
        return CompletableFuture.supplyAsync {
            throw RuntimeException()
        }
    }
}
```

coupled with the following advice:

```kotlin
@ControllerAdvice
class ErrorHandlingAdvice {
    @ExceptionHandler(Exception::class)
    fun handleException(exception: Exception): ResponseEntity<*> {
        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body("Handled by ${this.javaClass.simpleName}")
    }
}
```

passes the following test:

```kotlin
@Test
fun errorIsHandled() {
    val mvcResult = mockMvc
        .perform(post("/sad"))
        .andExpect(request().asyncStarted())
        .andReturn()

    mockMvc
        .perform(asyncDispatch(mvcResult))
        .andDo(MockMvcResultHandlers.print())
        .andExpect(content().string("Handled by ErrorHandlingAdvice"))
        .andExpect(status().is5xxServerError)
}
```

In `2.0.0.M6` & `2.0.0.M7`, the status is set to `200` rather than `500`.

A project reproducing this issue can be found at https://github.com/mdjnewman/studious-funicular. There is a `spring-boot-2.0.0.M6` branch which fails, while `master`, using `2.0.0.M5`, passes (see [Travis](https://travis-ci.org/mdjnewman/studious-funicular/branches) for details).

**Comment by mdjnewman** [comment]
Any update on this? I've just checked with `2.0.0.BUILD-SNAPSHOT` (build `432` I believe) and it looks to still be happening.

I'm guessing it's an issue with Spring Framework rather than Spring Boot itself but I'm unsure where else to report it.

**Comment by wilkinsona** [comment]
@mdjnewman Sorry, it looks like this one fell through the cracks. Thank you for the sample project. This appears to be caused by a change in Spring Framework 5.0.1.RELEASE. If I take your master branch the test passes as you have noted above. If I think apply the following change:

```diff
diff --git a/build.gradle b/build.gradle
index 8a55eaa..8aacfb8 100644
--- a/build.gradle
+++ b/build.gradle
@@ -16,6 +16,8 @@ buildscript {
     }
 }

+ext['spring.version'] = '5.0.1.RELEASE'
+
 apply plugin: 'kotlin'
 apply plugin: 'kotlin-spring'
 apply plugin: 'eclipse'
```

The test fails:

```
java.lang.AssertionError: Range for response status value 200 expected:<SERVER_ERROR> but was:<SUCCESSFUL>
	at org.springframework.test.util.AssertionErrors.fail(AssertionErrors.java:55)
	at org.springframework.test.util.AssertionErrors.assertEquals(AssertionErrors.java:82)
	at org.springframework.test.web.servlet.result.StatusResultMatchers.lambda$is5xxServerError$6(StatusResultMatchers.java:100)
	at org.springframework.test.web.servlet.MockMvc$1.andExpect(MockMvc.java:179)
	at com.example.demo.DemoApplicationTests.errorIsHandled(DemoApplicationTests.kt:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:73)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:83)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy1.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
```

The only difference is the version of Spring Framework that's being used (5.0.0.RELEASE vs 5.0.1.RELEASE). Can you please raise a [Spring Framework JIRA](https://jira.spring.io/browse/SPR) so that the Framework team can investigate?

**Comment by mdjnewman** [comment]
Raised https://jira.spring.io/browse/SPR-16430.
