### ISSUE TITLE
Spring webflux - Actual request port must not be undefined

### ISSUE THREAD

**Issue by tombru** [spring-projects/spring-boot#11349]
We are randomly seeing this error in our logs and have failed to reproduce.

```
java.lang.IllegalArgumentException: Actual request port must not be undefined
	at org.springframework.util.Assert.isTrue(Assert.java:116)
	at org.springframework.web.cors.reactive.CorsUtils.isSameOrigin(CorsUtils.java:68)
	at o.s.web.cors.reactive.DefaultCorsProcessor.process(DefaultCorsProcessor.java:69)
	at o.s.web.reactive.handler.AbstractHandlerMapping.lambda$getHandler$1(AbstractHandlerMapping.java:139)
	at r.c.p.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:107)
	at r.core.publisher.Operators$ScalarSubscription.request(Operators.java:1649)
	at r.c.p.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:156)
	at r.c.p.Operators$MultiSubscriptionSubscriber.set(Operators.java:1463)
	at r.c.p.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:1337)
	at r.c.p.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	at reactor.core.publisher.MonoMapFuseable.subscribe(MonoMapFuseable.java:59)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3008)
	at r.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:418)
	at r.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:210)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:128)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:61)
	at reactor.core.publisher.FluxConcatMap.subscribe(FluxConcatMap.java:121)
	at reactor.core.publisher.MonoNext.subscribe(MonoNext.java:40)
	at reactor.core.publisher.MonoSwitchIfEmpty.subscribe(MonoSwitchIfEmpty.java:44)
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:60)
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:60)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoPeekTerminal.subscribe(MonoPeekTerminal.java:61)
	at reactor.core.publisher.MonoPeekFuseable.subscribe(MonoPeekFuseable.java:74)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44)
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44)
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3008)
	at r.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:167)
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56)
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44)
	at reactor.core.publisher.MonoPeekTerminal.subscribe(MonoPeekTerminal.java:61)
	at reactor.ipc.netty.channel.ChannelOperations.applyHandler(ChannelOperations.java:383)
	at reactor.ipc.netty.http.server.HttpServerOperations.onHandlerStart(HttpServerOperations.java:359)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at i.n.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)
```

When the same request is triggered again it is successful. 
We are using
 - spring-boot-starter-parent version 2.0.0.M7
 - spring-cloud version Finchley.M4

The application is not under heavy load but some of the integrations are very slow. The integrations are made using Http.GET and org.springframework.web.reactive.function.client.WebClient

Thanks in advance
Tomas

**Comment by bclozel** [comment]
Hi @tombru 
The port information should be bound at that point (we have multiple tests covering that case).
I can't think of anything that could cause this.

I'll leave this opened for now in case you or someone else can create a repro project for this issue.

**Comment by tombru** [comment]
Thanks for the reply. 

The code can be found [here](https://github.com/tombru/port-must-not-be-undefined). I am not allowed to provide the implementation of the DTO used in the integration (replaced by a String). But is is a simple Lombok Data-object. Apart from that the code don't differ from the application with the error.

**Comment by snicoll** [comment]
@tombru please provide the steps to reproduce the issue

**Comment by tombru** [comment]
Well that is the thing. I haven't managed to reproduce the problem in isolation. I see it happening randomly in both test and production environment. But most of the requests don't give this error. Feel free to close this issue but I currently can't give more information.

**Comment by snicoll** [comment]
Alright. We can reopen if you can provide more info.

**Comment by tombru** [comment]
@snicoll  I managed to reproduce the problem. Happens when origin is included in the request header. Ex -H  'origin: https://foo.com'. In our application this header is passed for all Firefox-clients.

**Comment by bclozel** [comment]
We'd still need more information to reopen this. Can you provide a sample application that demonstrates this issue?

This points to the port information not parsed properly from the request sent by the client.
A simple Boot project replicating your CORS configuration + a curl command that triggers this case would help us narrowing down things.

Also: depending on the server and Boot version you're using, we might be able to track down already resolved issues in Spring Framework.

**Comment by tombru** [comment]
Finally I managed to figure out what is going on. All our request goes through an nginx. The nginx adds a few headers to the request. The actual request will be more similar to
```
curl http://localhost:8220/foo -H 'Host: foo'   -H 'X-Forwarded-Proto: 443'  -H 'origin: http://localhost:8220'
```
If I add a port to the Host-header everything is working as expected. Example
```
curl http://localhost:8220/foo -H 'Host: foo:8220'   -H 'X-Forwarded-Proto: 443'  -H 'origin: http://localhost:8220'
```

**Comment by wilkinsona** [comment]
Thank you, @tombru. I suspect this needs to be addressed in Spring Framework but I'm going to re-open this to hopefully stop the problem from falling through the cracks.

**Comment by bclozel** [comment]
`'X-Forwarded-Proto: 443'` looks wrong to me; `'X-Forwarded-Port: 443'` is supported by Spring Framework.

**Comment by tombru** [comment]
@bclozel I agree! My situation was solved by using ```H 'X-Forwarded-Proto: http'```
