### ISSUE TITLE
Can't read yaml's complex object using @ConfigurationProperties. Integer cannot be cast to String

### ISSUE THREAD

**Issue by krkhnh** [spring-projects/spring-boot#11494]
I'm using Lombok and Spring Boot `v1.5.4.RELEASE`. Also tried Spring Boot `v1.5.9.RELEASE`, but no luck.

I'm trying to read this yml file

    dist-price:
      1234:
        foo: 4567
        bar: false

and put into this class.

    @Repository
    @ConfigurationProperties
    @Data
    @NoArgsConstructor
    public class WebConfigProperty {
    	@NonNull
    	private TreeMap<Integer, Bound> distPrice;
    }

    @Data
    @NoArgsConstructor
    public class Bound {
    	@NonNull
    	private Integer foo;
    
    	@NonNull
    	private Boolean bar;
    }

But I got this error.

    Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
    	at java.lang.String.compareTo(Unknown Source)
    	at java.util.TreeMap.getEntry(Unknown Source)
    	at java.util.TreeMap.get(Unknown Source)
    	at org.springframework.boot.bind.RelaxedDataBinder.isBlanked(RelaxedDataBinder.java:328)
    	at org.springframework.boot.bind.RelaxedDataBinder.initializePath(RelaxedDataBinder.java:283)
    	at org.springframework.boot.bind.RelaxedDataBinder.normalizePath(RelaxedDataBinder.java:259)
    	at org.springframework.boot.bind.RelaxedDataBinder.modifyProperty(RelaxedDataBinder.java:240)
    	at org.springframework.boot.bind.RelaxedDataBinder.modifyProperties(RelaxedDataBinder.java:155)
    	at org.springframework.boot.bind.RelaxedDataBinder.doBind(RelaxedDataBinder.java:128)
    	at org.springframework.validation.DataBinder.bind(DataBinder.java:740)
    	at org.springframework.boot.bind.PropertiesConfigurationFactory.doBindPropertiesToTarget(PropertiesConfigurationFactory.java:272)
    	at org.springframework.boot.bind.PropertiesConfigurationFactory.bindPropertiesToTarget(PropertiesConfigurationFactory.java:240)
    	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:329)
    	... 73 common frames omitted

If I change `TreeMap<Integer, Bound>` to `TreeMap<String, Bound>` it works fine. But I really need to use `Integer`. It seems like `TreeMap`'s key (in this case: `1234`) is being cast to `String`. I don't know why.

It was fine when `TreeMap<Integer, Bound>` was `TreeMap<Integer, Integer>`, and yml was like this.

    dist-price:
      1234: 4567

Just FYI, I wrote about this issue as a [SO question](https://stackoverflow.com/q/48071057/2652379).

**Comment by snicoll** [comment]
There is no need to cross-post at this point.

**Comment by krkhnh** [comment]
Oh... I thought it was a bug so I posted here to report.
