### ISSUE TITLE
Misleading error message from DuplicateServerPropertiesDetector when JDK-based proxying prevents ServerProperties beans from being found

### ISSUE THREAD

**Issue by ooooow** [spring-projects/spring-boot#11511]
1 custom annotion

```
@Target({ElementType.TYPE,ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface MyAnno {
    String value() default "";
}
```

2 custom aop

```
@Aspect
@Component
public class MyAop {
    
    @Around("@target (com.hello.aop.MyAnno)")
    public Object around(ProceedingJoinPoint pjp) throws Throwable {
        Object result = null;
        try {
            System.out.println("around start...." + pjp.getArgs());
             result = pjp.proceed();
            System.out.println("around end....");
        }finally {

        }
        return result;
    }
}
```

3 start  ok

```
@ComponentScan(basePackages = "com.hello")
@EnableAspectJAutoProxy
 public class Application {

    public static void main(String[] args) {
        AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext(Application.class);
        HelloService d = context.getBean(HelloService.class);
        d.sayHello("zhangsan");
    }
}
```

4 start tomcat  failed

```
@SpringBootApplication
@ComponentScan(basePackages = "com.hello")
 @EnableAspectJAutoProxy
 public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class,args);
    }
}
```

```
org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatEmbeddedServletContainerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/EmbeddedServletContainerAutoConfiguration$EmbeddedTomcat.class]: Initialization of bean failed; nested exception is java.lang.IllegalStateException: Multiple ServerProperties beans registered 
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:137) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:536) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at com.hello.Application.main(Application.java:27) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_51]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140) [idea_rt.jar:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatEmbeddedServletContainerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/EmbeddedServletContainerAutoConfiguration$EmbeddedTomcat.class]: Initialization of bean failed; nested exception is java.lang.IllegalStateException: Multiple ServerProperties beans registered 
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.getEmbeddedServletContainerFactory(EmbeddedWebApplicationContext.java:199) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:162) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:134) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	... 13 common frames omitted
Caused by: java.lang.IllegalStateException: Multiple ServerProperties beans registered 
	at org.springframework.util.Assert.state(Assert.java:70) ~[spring-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.boot.autoconfigure.web.ServerPropertiesAutoConfiguration$DuplicateServerPropertiesDetector.customize(ServerPropertiesAutoConfiguration.java:84) ~[spring-boot-autoconfigure-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_51]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333) ~[spring-aop-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) ~[spring-aop-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:173) ~[spring-aop-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) ~[spring-aop-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at com.sun.proxy.$Proxy70.customize(Unknown Source) ~[na:na]
	at org.springframework.boot.context.embedded.EmbeddedServletContainerCustomizerBeanPostProcessor.postProcessBeforeInitialization(EmbeddedServletContainerCustomizerBeanPostProcessor.java:73) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedServletContainerCustomizerBeanPostProcessor.postProcessBeforeInitialization(EmbeddedServletContainerCustomizerBeanPostProcessor.java:59) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:409) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1620) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	... 21 common frames omitted
```

**Comment by wilkinsona** [comment]
@ooooow Please try with Spring Boot 1.5.9. If that doesn’t resolve the issue, please provide a complete sample (something we can unzip or git clone and run) that reproduces the problem.

**Comment by ooooow** [comment]
https://github.com/ooooow/spring-aop-test.git         

This is an example that I provided, using the same error as 1.5.9.It doesn't conflict with spring boot?

**Comment by wilkinsona** [comment]
Thanks for the sample.

This is largely due to how Spring Framework and AspectJ handle advice that uses `@target`. It results in every bean in the context being proxied for AOP purposes. An unwanted side-effect of that is that `ServerProperties` becomes a JDK proxy and can only be seen as the type of one of the three interfaces that it implements. As a result, `DuplicateServerPropertiesDetector` can't find a `ServerProperties` bean so its state assertion fails. It's message is misleading as it reports that it found multiple beans when, in fact, it didn't find any.

Typically, problems caused by JDK-based proxies may be avoided by enabled CGLib-based proxies. Indeed, that's the default in Boot 2.0. In 1.5, it still needs to be enabled, for example by using the `proxyTargetClass` attribute of `@EnableAspectJAutoProxy`:

```
@EnableAspectJAutoProxy(proxyTargetClass=true)
```

Unfortunately, this doesn't help due to the broad advice which requires all beans to be proxied. Actuator's `MetricsFilter` class is `final` so it cannot by proxied with CGLib and the following failure occurs:

```
Caused by: java.lang.IllegalArgumentException: Cannot subclass final class org.springframework.boot.actuate.autoconfigure.MetricsFilter
	at org.springframework.cglib.proxy.Enhancer.generateClass(Enhancer.java:565) ~[spring-core-4.3.14.BUILD-SNAPSHOT.jar:4.3.14.BUILD-SNAPSHOT]
	at org.springframework.cglib.transform.TransformingClassGenerator.generateClass(TransformingClassGenerator.java:33) ~[spring-core-4.3.14.BUILD-SNAPSHOT.jar:4.3.14.BUILD-SNAPSHOT]
	at org.springframework.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25) ~[spring-core-4.3.14.BUILD-SNAPSHOT.jar:4.3.14.BUILD-SNAPSHOT]
	at org.springframework.aop.framework.CglibAopProxy$ClassLoaderAwareUndeclaredThrowableStrategy.generate(CglibAopProxy.java:999) ~[spring-aop-4.3.14.BUILD-SNAPSHOT.jar:4.3.14.BUILD-SNAPSHOT]
	at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:329) ~[spring-core-4.3.14.BUILD-SNAPSHOT.jar:4.3.14.BUILD-SNAPSHOT]
	at org.springframework.cglib.proxy.Enhancer.generate(Enhancer.java:492) ~[spring-core-4.3.14.BUILD-SNAPSHOT.jar:4.3.14.BUILD-SNAPSHOT]
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93) ~[spring-core-4.3.14.BUILD-SNAPSHOT.jar:4.3.14.BUILD-SNAPSHOT]
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91) ~[spring-core-4.3.14.BUILD-SNAPSHOT.jar:4.3.14.BUILD-SNAPSHOT]
	at org.springframework.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54) ~[spring-core-4.3.14.BUILD-SNAPSHOT.jar:4.3.14.BUILD-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_121]
	at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61) ~[spring-core-4.3.14.BUILD-SNAPSHOT.jar:4.3.14.BUILD-SNAPSHOT]
	at org.springframework.cglib.core.internal.LoadingCache.get(LoadingCache.java:34) ~[spring-core-4.3.14.BUILD-SNAPSHOT.jar:4.3.14.BUILD-SNAPSHOT]
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116) ~[spring-core-4.3.14.BUILD-SNAPSHOT.jar:4.3.14.BUILD-SNAPSHOT]
	at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291) ~[spring-core-4.3.14.BUILD-SNAPSHOT.jar:4.3.14.BUILD-SNAPSHOT]
	at org.springframework.cglib.proxy.Enhancer.createHelper(Enhancer.java:480) ~[spring-core-4.3.14.BUILD-SNAPSHOT.jar:4.3.14.BUILD-SNAPSHOT]
	at org.springframework.cglib.proxy.Enhancer.createClass(Enhancer.java:337) ~[spring-core-4.3.14.BUILD-SNAPSHOT.jar:4.3.14.BUILD-SNAPSHOT]
	at org.springframework.aop.framework.ObjenesisCglibAopProxy.createProxyClassAndInstance(ObjenesisCglibAopProxy.java:55) ~[spring-aop-4.3.14.BUILD-SNAPSHOT.jar:4.3.14.BUILD-SNAPSHOT]
	at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:201) ~[spring-aop-4.3.14.BUILD-SNAPSHOT.jar:4.3.14.BUILD-SNAPSHOT]
	... 30 common frames omitted
```

As you have identified in the sample, you can avoid the problem by changing your advice to use `@within` rather than `@target`. I don't fully understand why this is the case as my reading of `org.springframework.aop.aspectj.AspectJExpressionPointcut` is that it should not match when `@target` is used as explained in this comment:

```
// A match test returned maybe - if there are any subtype sensitive variables
// involved in the test (this, target, at_this, at_target, at_annotation) then
// we say this is not a match as in Spring there will never be a different
// runtime subtype.

When `org.springframework.aop.aspectj.RuntimeTestWalker.SubtypeSensitiveVarTypeTestVisitor` is testing the variable type, it's identified as being `target` rather than `@target` and it doesn't identify the subtype sensitive variable:

```
if (varType == AT_THIS_VAR || varType == AT_TARGET_VAR || varType == AT_ANNOTATION_VAR) {
		this.testsSubtypeSensitiveVars = true;
}
```

We'll need some help from the Spring Framework team here I think. /cc @jhoeller

On the Boot side, we can at least improve the error message when `DuplicateServerPropertiesDetector` fails to find any `ServerProperties` beans.

**Comment by wilkinsona** [comment]
The Framework behaviour that I've described is due to [SPR-15533](https://jira.spring.io/browse/SPR-15533).

We can use this issue to make the error produced by `DuplicateServerPropertiesDetector` a little more accurate.

**Comment by alulu-zh** [comment]
@wilkinsona I reproduce this issue by use @args in point cut

**Comment by DeeptiSi** [comment]
Hi
 I am trying to create Spring Boot + Swagger + Mybatis + MySQL
Project having basic Database CRUD operation with Mailer Functionality. I am using Java for it. 
Can Anyone help me on solving the following error:

[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.4.0.RELEASE:run (default-cli) on project project: An exception occurred while running. null: InvocationTargetException: Unable to start embedded container; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatEmbeddedServletContainerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/EmbeddedServletContainerAutoConfiguration$EmbeddedTomcat.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.HttpEncodingAutoConfiguration': Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'spring.http.encoding-org.springframework.boot.autoconfigure.web.HttpEncodingProperties': Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'spring.http.encoding-org.springframework.boot.autoconfigure.web.HttpEncodingProperties': Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException: javax.xml.bind.ValidationException -> [Help 1]


Any help would be appreciated.

**Comment by wilkinsona** [comment]
@DeeptiSi This issue is closed and your comment seems to be about a completely unrelated problem. Please take some time to read the [guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc).

**Comment by DeeptiSi** [comment]
Thanks for your response.
