### ISSUE TITLE
Invalid path for server.ssl.key-store throws port error

### ISSUE THREAD

**Issue by oupablo** [spring-projects/spring-boot#11593]
When configuring a path to a keystore, putting in a valid file path works as expected. However, putting in an invalid path such as:

server.ssl.key-store=non-existant/path/keystore.jks

Results in the following being thrown:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

The Tomcat connector configured to listen on port 8181 failed to start. The port may already be in use or the connector may be misconfigured.
```

Desired result is that the error be related to the the keystore instead of implying that the port is already in use.

**Comment by wilkinsona** [comment]
That's covered by "or the connector may be misconfigured", is it not?

**Comment by oupablo** [comment]
I suppose that covers it. It would be nice if the issue was narrowed down a bit more. There's something like 80+ properties for configuring the embedded server. A little more guidance into what is broken would be nice. Not a show stopper by any means. Just something that would be nice to have.

**Comment by wilkinsona** [comment]
Unfortunately, that's the best that we can do with Tomcat's minimal diagnostics. When the connector's added and it fails to start, Tomcat catches, logs, and swallows the exception so we can't identify that cause of the failure. You can, however, read the log output immediately above the failure analysis to see what happened:

```
2018-01-11 09:51:10.395 ERROR 1477 --- [           main] o.apache.catalina.core.StandardService   : Failed to start connector [Connector[HTTP/1.1-8443]]

org.apache.catalina.LifecycleException: Failed to start component [Connector[HTTP/1.1-8443]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167) ~[tomcat-embed-core-8.5.24.jar!/:8.5.24]
	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:225) ~[tomcat-embed-core-8.5.24.jar!/:8.5.24]
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.addPreviouslyRemovedConnectors(TomcatEmbeddedServletContainer.java:250) [spring-boot-1.5.10.BUILD-SNAPSHOT.jar!/:1.5.10.BUILD-SNAPSHOT]
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:193) [spring-boot-1.5.10.BUILD-SNAPSHOT.jar!/:1.5.10.BUILD-SNAPSHOT]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:297) [spring-boot-1.5.10.BUILD-SNAPSHOT.jar!/:1.5.10.BUILD-SNAPSHOT]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:145) [spring-boot-1.5.10.BUILD-SNAPSHOT.jar!/:1.5.10.BUILD-SNAPSHOT]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) [spring-context-4.3.14.BUILD-SNAPSHOT.jar!/:4.3.14.BUILD-SNAPSHOT]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) [spring-boot-1.5.10.BUILD-SNAPSHOT.jar!/:1.5.10.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.10.BUILD-SNAPSHOT.jar!/:1.5.10.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.10.BUILD-SNAPSHOT.jar!/:1.5.10.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.10.BUILD-SNAPSHOT.jar!/:1.5.10.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.10.BUILD-SNAPSHOT.jar!/:1.5.10.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.10.BUILD-SNAPSHOT.jar!/:1.5.10.BUILD-SNAPSHOT]
	at sample.tomcat.ssl.SampleTomcatSslApplication.main(SampleTomcatSslApplication.java:26) [classes!/:1.5.10.BUILD-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [spring-boot-sample-tomcat-ssl-1.5.10.BUILD-SNAPSHOT.jar:1.5.10.BUILD-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [spring-boot-sample-tomcat-ssl-1.5.10.BUILD-SNAPSHOT.jar:1.5.10.BUILD-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [spring-boot-sample-tomcat-ssl-1.5.10.BUILD-SNAPSHOT.jar:1.5.10.BUILD-SNAPSHOT]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [spring-boot-sample-tomcat-ssl-1.5.10.BUILD-SNAPSHOT.jar:1.5.10.BUILD-SNAPSHOT]
Caused by: org.apache.catalina.LifecycleException: Protocol handler start failed
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1020) ~[tomcat-embed-core-8.5.24.jar!/:8.5.24]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) ~[tomcat-embed-core-8.5.24.jar!/:8.5.24]
	... 21 common frames omitted
Caused by: java.lang.IllegalArgumentException: java.io.FileNotFoundException: /Users/awilkinson/dev/spring/spring-boot/1.5.x/spring-boot-samples/spring-boot-sample-tomcat-ssl/non-existant/path/keystore.jks (No such file or directory)
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:116) ~[tomcat-embed-core-8.5.24.jar!/:8.5.24]
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.initialiseSsl(AbstractJsseEndpoint.java:87) ~[tomcat-embed-core-8.5.24.jar!/:8.5.24]
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:225) ~[tomcat-embed-core-8.5.24.jar!/:8.5.24]
	at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:1146) ~[tomcat-embed-core-8.5.24.jar!/:8.5.24]
	at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:591) ~[tomcat-embed-core-8.5.24.jar!/:8.5.24]
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1018) ~[tomcat-embed-core-8.5.24.jar!/:8.5.24]
	... 22 common frames omitted
Caused by: java.io.FileNotFoundException: /Users/awilkinson/dev/spring/spring-boot/1.5.x/spring-boot-samples/spring-boot-sample-tomcat-ssl/non-existant/path/keystore.jks (No such file or directory)
	at java.io.FileInputStream.open0(Native Method) ~[na:1.8.0_151]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[na:1.8.0_151]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[na:1.8.0_151]
	at java.io.FileInputStream.<init>(FileInputStream.java:93) ~[na:1.8.0_151]
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90) ~[na:1.8.0_151]
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188) ~[na:1.8.0_151]
	at org.apache.tomcat.util.file.ConfigFileLoader.getInputStream(ConfigFileLoader.java:96) ~[tomcat-embed-core-8.5.24.jar!/:8.5.24]
	at org.apache.tomcat.util.net.SSLUtilBase.getStore(SSLUtilBase.java:132) ~[tomcat-embed-core-8.5.24.jar!/:8.5.24]
	at org.apache.tomcat.util.net.SSLHostConfigCertificate.getCertificateKeystore(SSLHostConfigCertificate.java:204) ~[tomcat-embed-core-8.5.24.jar!/:8.5.24]
	at org.apache.tomcat.util.net.jsse.JSSEUtil.getKeyManagers(JSSEUtil.java:184) ~[tomcat-embed-core-8.5.24.jar!/:8.5.24]
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:114) ~[tomcat-embed-core-8.5.24.jar!/:8.5.24]
	... 27 common frames omitted

2018-01-11 09:51:10.402  INFO 1477 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2018-01-11 09:51:10.419  INFO 1477 --- [           main] utoConfigurationReportLoggingInitializer :

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2018-01-11 09:51:10.421 ERROR 1477 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   :

***************************
APPLICATION FAILED TO START
***************************

Description:

The Tomcat connector configured to listen on port 8443 failed to start. The port may already be in use or the connector may be misconfigured.

Action:

Verify the connector's configuration, identify and stop any process that's listening on port 8443, or configure this application to listen on another port.
```

**Comment by oupablo** [comment]
I feared as much. Thanks for looking into it.
