### ISSUE TITLE
Spring Boot Gradle Plugin doesn't support newer Gradle `java-library` correctly for repackage

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-boot#11642]
Spring boot 1.5.9, using kotlin dsl I realize this isn't minimal but I suspect that code simply hasn't been updated to deal with `java-library`

The below doesn't work. *Notes*, JAR_REPOSITORY_URI can point to any maven repo, BOM simply extends the platform BOM and adds a few deps. Any other "proprietary jars" could easily be replaced with a simple controller packaged jar.
```
import com.github.spotbugs.SpotBugsTask
import com.github.spotbugs.SpotBugsPlugin
import io.spring.gradle.dependencymanagement.DependencyManagementPlugin
import io.spring.gradle.dependencymanagement.dsl.DependencyManagementExtension
import io.spring.gradle.dependencymanagement.internal.DependencyManagement
import org.gradle.api.credentials.AwsCredentials
import org.gradle.kotlin.dsl.maven
import org.gradle.kotlin.dsl.repositories
import io.spring.gradle.dependencymanagement.internal.DependencyManagementSettings
import io.spring.gradle.dependencymanagement.internal.dsl.StandardDependencyManagementExtension
import org.gradle.internal.impldep.junit.runner.Version.id
import org.gradle.kotlin.dsl.creating
import org.gradle.kotlin.dsl.support.illegalElementType
import org.gradle.model.internal.core.TypeCompatibilityModelProjectionSupport.description
import org.gradle.plugins.ide.idea.model.IdeaModel
import org.gradle.plugins.ide.idea.model.IdeaProject
import java.lang.System
import java.util.concurrent.TimeUnit

plugins {
    `java-library`
    `maven-publish`
    `checkstyle`
    `idea`
    id("com.github.spotbugs").version("1.6.0")
    id("net.ltgt.errorprone").version("0.0.13")
    id("io.spring.dependency-management").version("1.0.4.RELEASE")
    id("org.springframework.boot").version("1.5.9.RELEASE")
}

repositories {
    maven(System.getenv("JAR_REPOSITORY_URI"))
    jcenter()
}

group = "com.xenoterracide.rpf"
version = "0.1.0-SNAPSHOT"
description = "RPF Application"

configurations.all({
    resolutionStrategy.cacheChangingModulesFor(0, TimeUnit.SECONDS)
})
dependencyManagement {
    imports {
        mavenBom("com.xenoterracide:bom:0.1.0-SNAPSHOT")
    }
}

// In this section you declare the dependencies for your production and test code
dependencies {
    errorprone("com.google.guava:guava:latest.release")
    errorprone("com.google.errorprone:error_prone_core:latest.release")
    compileOnly("com.google.code.findbugs:jsr305")
    compileOnly("com.google.errorprone:error_prone_annotations:latest.release")

    implementation("org.springframework.boot:spring-boot-starter")
    runtimeOnly("org.springframework.boot:spring-boot-devtools")
    runtimeOnly("com.xenoterracide.rpf:sec-user-reg:0.1.0-SNAPSHOT")
    runtimeOnly("org.springframework.boot:spring-boot-starter-data-rest")
    runtimeOnly("org.springframework.boot:spring-boot-starter-actuator")
    runtimeOnly("com.h2database:h2")
}
```
here's the stack

```
$ java -jar app-0.1.0-SNAPSHOT.jar
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/SpringApplication
        at com.xenoterracide.rpf.Application.main(Application.java:9)
        ... 8 more
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.SpringApplication
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 9 more
```
and the jar's contents
```
$ jar tvf app-0.1.0-SNAPSHOT.jar
     0 Tue Jan 16 05:29:42 CST 2018 META-INF/
   238 Tue Jan 16 05:29:42 CST 2018 META-INF/MANIFEST.MF
     0 Tue Jan 16 05:29:42 CST 2018 BOOT-INF/
     0 Tue Jan 16 05:29:42 CST 2018 BOOT-INF/classes/
     0 Sat Dec 30 15:42:56 CST 2017 BOOT-INF/classes/com/
     0 Sat Dec 30 15:42:56 CST 2017 BOOT-INF/classes/com/xenoterracide/
     0 Sat Dec 30 16:02:30 CST 2017 BOOT-INF/classes/com/xenoterracide/rpf/
   727 Sat Dec 30 16:02:30 CST 2017 BOOT-INF/classes/com/xenoterracide/rpf/Application.class
     0 Tue Jan 16 05:29:42 CST 2018 org/
     0 Tue Jan 16 05:29:42 CST 2018 org/springframework/
     0 Tue Jan 16 05:29:42 CST 2018 org/springframework/boot/
     0 Tue Jan 16 05:29:42 CST 2018 org/springframework/boot/loader/
  2415 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/LaunchedURLClassLoader$1.class
  1454 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/PropertiesLauncher$ArchiveEntryFilter.class
  1912 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/PropertiesLauncher$PrefixMatchingArchiveFilter.class
  4599 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/Launcher.class
  1165 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/ExecutableArchiveLauncher$1.class
     0 Tue Jan 16 05:29:42 CST 2018 org/springframework/boot/loader/jar/
  2002 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/jar/JarFile$1.class
 10655 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/jar/Handler.class
  3350 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/jar/JarEntry.class
  1427 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/jar/JarFile$3.class
  3104 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/jar/CentralDirectoryEndRecord.class
   430 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/jar/CentralDirectoryVisitor.class
  1300 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/jar/JarFile$JarFileType.class
 10924 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/jar/JarFileEntries.class
 12762 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/jar/JarFile.class
  1540 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/jar/JarFileEntries$1.class
   672 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/jar/JarURLConnection$1.class
  1199 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/jar/JarFile$2.class
   262 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/jar/JarEntryFilter.class
  4457 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/jar/AsciiBytes.class
  4602 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/jar/CentralDirectoryParser.class
  2169 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/jar/Bytes.class
  1629 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/jar/ZipInflaterInputStream.class
  1967 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/jar/JarFileEntries$EntryIterator.class
   306 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/jar/FileHeader.class
  3641 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/jar/JarURLConnection$JarEntryName.class
  9516 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/jar/JarURLConnection.class
  5449 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/jar/CentralDirectoryFileHeader.class
     0 Tue Jan 16 05:29:42 CST 2018 org/springframework/boot/loader/data/
  1531 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/data/ByteArrayRandomAccessData.class
  3549 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/data/RandomAccessDataFile$DataInputStream.class
  1862 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/data/RandomAccessDataFile$FilePool.class
  1341 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/data/RandomAccessData$ResourceAccess.class
  3319 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/data/RandomAccessDataFile.class
   551 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/data/RandomAccessData.class
  4698 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/LaunchedURLClassLoader.class
  1533 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/JarLauncher.class
  1468 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/MainMethodRunner.class
  1425 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/PropertiesLauncher$1.class
  3128 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/ExecutableArchiveLauncher.class
  1669 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/WarLauncher.class
     0 Tue Jan 16 05:29:42 CST 2018 org/springframework/boot/loader/archive/
  1749 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/archive/JarFileArchive$EntryIterator.class
  3792 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/archive/ExplodedArchive$FileEntryIterator.class
  1068 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/archive/ExplodedArchive$FileEntry.class
  1051 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/archive/JarFileArchive$JarFileEntry.class
   302 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/archive/Archive$Entry.class
  7171 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/archive/JarFileArchive.class
  4974 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/archive/ExplodedArchive.class
   906 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/archive/Archive.class
  1438 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/archive/ExplodedArchive$FileEntryIterator$EntryComparator.class
   399 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/archive/Archive$EntryFilter.class
   273 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/archive/ExplodedArchive$1.class
 18041 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/PropertiesLauncher.class
     0 Tue Jan 16 05:29:42 CST 2018 org/springframework/boot/loader/util/
  4887 Tue Nov 28 09:02:40 CST 2017 org/springframework/boot/loader/util/SystemPropertyUtils.class
```

this does
```
import com.github.spotbugs.SpotBugsTask
import com.github.spotbugs.SpotBugsPlugin
import io.spring.gradle.dependencymanagement.DependencyManagementPlugin
import io.spring.gradle.dependencymanagement.dsl.DependencyManagementExtension
import io.spring.gradle.dependencymanagement.internal.DependencyManagement
import org.gradle.api.credentials.AwsCredentials
import org.gradle.kotlin.dsl.maven
import org.gradle.kotlin.dsl.repositories
import io.spring.gradle.dependencymanagement.internal.DependencyManagementSettings
import io.spring.gradle.dependencymanagement.internal.dsl.StandardDependencyManagementExtension
import org.gradle.internal.impldep.junit.runner.Version.id
import org.gradle.kotlin.dsl.creating
import org.gradle.kotlin.dsl.support.illegalElementType
import org.gradle.model.internal.core.TypeCompatibilityModelProjectionSupport.description
import org.gradle.plugins.ide.idea.model.IdeaModel
import org.gradle.plugins.ide.idea.model.IdeaProject
import java.lang.System
import java.util.concurrent.TimeUnit

plugins {
    `java`
    `maven-publish`
    `checkstyle`
    `idea`
    id("com.github.spotbugs").version("1.6.0")
    id("net.ltgt.errorprone").version("0.0.13")
    id("io.spring.dependency-management").version("1.0.4.RELEASE")
    id("org.springframework.boot").version("1.5.9.RELEASE")
}

repositories {
    maven(System.getenv("JAR_REPOSITORY_URI"))
    jcenter()
}

group = "com.xenoterracide.rpf"
version = "0.1.0-SNAPSHOT"
description = "RPF Application"

configurations.all({
    resolutionStrategy.cacheChangingModulesFor(0, TimeUnit.SECONDS)
})
dependencyManagement {
    imports {
        mavenBom("com.xenoterracide:bom:0.1.0-SNAPSHOT")
    }
}

// In this section you declare the dependencies for your production and test code
dependencies {
    errorprone("com.google.guava:guava:latest.release")
    errorprone("com.google.errorprone:error_prone_core:latest.release")
    compileOnly("com.google.code.findbugs:jsr305")
    compileOnly("com.google.errorprone:error_prone_annotations:latest.release")

    compile("org.springframework.boot:spring-boot-starter")
    runtime("org.springframework.boot:spring-boot-devtools")
    runtime("com.xenoterracide.rpf:sec-user-reg:0.1.0-SNAPSHOT")
    runtime("org.springframework.boot:spring-boot-starter-data-rest")
    runtime("org.springframework.boot:spring-boot-starter-actuator")
    runtime("com.h2database:h2")
}
```

**Comment by wilkinsona** [comment]
IMO, applying the Java Library plugin to a Spring Boot application doesn't make much sense as an application isn't a library. 

By default, the plugin uses the `runtime` configuration to figure out the contents of the fat jar. The `runtime` configuration doesn't extend the `implementation` configuration so its dependencies aren't included in the jar. If you want to include the dependencies from the `implementation` configuration in the jar, you'll have to configure the `customConfiguration` property of the `bootRepackage` task appropriately.
