### ISSUE TITLE
Downgrade Groovy to 2.4.x

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#11745]
Unfortunately 2.5 isn't going to be out of beta in time for Boot 2.0 so we need to downgrade to 2.4.x. This is proving to be tricky. The CLI currently fails to build due to two test failures, each of which is similar to the following:

```
java.lang.RuntimeException: java.lang.NoClassDefFoundError: Unable to load class org.springframework.boot.groovy.GroovyTemplate due to missing dependency groovy/text/TemplateEngine
	at org.codehaus.groovy.control.CompilationUnit.convertUncaughtExceptionToCompilationError(CompilationUnit.java:1101)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1079)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:603)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
	at org.springframework.boot.cli.compiler.GroovyCompiler.compile(GroovyCompiler.java:206)
	at org.springframework.boot.cli.command.archive.ArchiveCommand$ArchiveOptionHandler.run(ArchiveCommand.java:142)
	at org.springframework.boot.cli.command.options.OptionHandler.run(OptionHandler.java:84)
	at org.springframework.boot.cli.command.OptionParsingCommand.run(OptionParsingCommand.java:54)
	at org.springframework.boot.cli.command.CommandRunner.run(CommandRunner.java:219)
	at org.springframework.boot.cli.command.CommandRunner.runAndHandleErrors(CommandRunner.java:171)
	at org.springframework.boot.cli.SpringCli.main(SpringCli.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.NoClassDefFoundError: Unable to load class org.springframework.boot.groovy.GroovyTemplate due to missing dependency groovy/text/TemplateEngine
	at org.codehaus.groovy.vmplugin.v5.Java5.configureClassNode(Java5.java:397)
	at org.codehaus.groovy.ast.ClassNode.lazyClassInit(ClassNode.java:280)
	at org.codehaus.groovy.ast.ClassNode.getDeclaredMethods(ClassNode.java:877)
	at org.codehaus.groovy.ast.ClassNode.getMethods(ClassNode.java:892)
	at org.codehaus.groovy.ast.ClassNode.hasPossibleStaticMethod(ClassNode.java:1313)
	at org.codehaus.groovy.control.StaticImportVisitor.findStaticMethod(StaticImportVisitor.java:597)
	at org.codehaus.groovy.control.StaticImportVisitor.findStaticMethodImportFromModule(StaticImportVisitor.java:463)
	at org.codehaus.groovy.control.StaticImportVisitor.transformMethodCallExpression(StaticImportVisitor.java:270)
	at org.codehaus.groovy.control.StaticImportVisitor.transform(StaticImportVisitor.java:108)
	at org.codehaus.groovy.ast.expr.Expression.transformExpressions(Expression.java:51)
	at org.codehaus.groovy.ast.expr.ArgumentListExpression.transformExpression(ArgumentListExpression.java:69)
	at org.codehaus.groovy.control.StaticImportVisitor.transform(StaticImportVisitor.java:117)
	at org.codehaus.groovy.control.StaticImportVisitor.transformMethodCallExpression(StaticImportVisitor.java:257)
	at org.codehaus.groovy.control.StaticImportVisitor.transform(StaticImportVisitor.java:108)
	at org.codehaus.groovy.ast.ClassCodeExpressionTransformer.visitExpressionStatement(ClassCodeExpressionTransformer.java:142)
	at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:42)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitBlockStatement(CodeVisitorSupport.java:37)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitBlockStatement(ClassCodeVisitorSupport.java:166)
	at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:71)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClassCodeContainer(ClassCodeVisitorSupport.java:104)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitConstructorOrMethod(ClassCodeVisitorSupport.java:115)
	at org.codehaus.groovy.ast.ClassCodeExpressionTransformer.visitConstructorOrMethod(ClassCodeExpressionTransformer.java:53)
	at org.codehaus.groovy.control.StaticImportVisitor.visitConstructorOrMethod(StaticImportVisitor.java:84)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitMethod(ClassCodeVisitorSupport.java:126)
	at org.codehaus.groovy.ast.ClassNode.visitContents(ClassNode.java:1081)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClass(ClassCodeVisitorSupport.java:53)
	at org.codehaus.groovy.control.StaticImportVisitor.visitClass(StaticImportVisitor.java:78)
	at org.codehaus.groovy.control.CompilationUnit$13.call(CompilationUnit.java:671)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1065)
	... 18 more

1 error
```

**Comment by wilkinsona** [comment]
This appears to have caused some build failures on JDK 9.
