### ISSUE TITLE
WebClient hangs on Mono#block

### ISSUE THREAD

**Issue by milosztylenda** [spring-projects/spring-boot#11863]
I have got a Spring Boot WebFlux application which uses a WebClient to fetch data from a remote site and forwards it to the client browser. After 2 or 3 fetches the application hangs up when calling block() on the Mono resulting from the remote site.

When I add a spring-boot-starter-tomcat dependency the problem seems to disappear.

I will create a sample in spring-boot-issues to demonstrate the issue.

My environment:
Spring Boot 2.0.0.RC1,
Linux twix 4.13.0-26-generic #29~16.04.2-Ubuntu SMP Tue Jan 9 22:00:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux,
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

**Comment by bclozel** [comment]
Do you see exceptions in your console? Could you copy/paste them here?

**Comment by milosztylenda** [comment]
When multiple requests are hang and I interrupt the application, the following is logged:

2018-01-31 11:57:55.783  INFO 16912 --- [ctor-http-nio-1] TEST                                     : BEFORE BLOCK
2018-01-31 11:57:55.783  INFO 16912 --- [ctor-http-nio-1] reactor.Mono.OnAssembly.14               : | onSubscribe([Fuseable] FluxOnAssembly.OnAssemblySubscriber)
2018-01-31 11:57:55.784  INFO 16912 --- [ctor-http-nio-1] reactor.Mono.OnAssembly.14               : | request(unbounded)
2018-01-31 11:57:59.280  INFO 16912 --- [      Thread-17] onfigReactiveWebServerApplicationContext : Closing org.springframework.boot.web.reactive.context.AnnotationConfigReactiveWebServerApplicationContext@6d3ba33c: startup date [Wed Jan 31 11:57:41 CET 2018]; root of context hierarchy
2018-01-31 11:57:59.285  INFO 16912 --- [      Thread-17] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
Exception in thread "Thread-17" java.lang.IllegalStateException: reactor.core.Exceptions$ReactiveException: java.util.concurrent.TimeoutException: HttpServer couldn't be stopped within 45000ms
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.stopAndReleaseReactiveWebServer(ReactiveWebServerApplicationContext.java:169)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.onClose(ReactiveWebServerApplicationContext.java:89)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1019)
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:933)
Caused by: reactor.core.Exceptions$ReactiveException: java.util.concurrent.TimeoutException: HttpServer couldn't be stopped within 45000ms
	at reactor.core.Exceptions.propagate(Exceptions.java:326)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:87)
	at reactor.core.publisher.Mono.block(Mono.java:1162)
	at reactor.ipc.netty.tcp.BlockingNettyContext.shutdown(BlockingNettyContext.java:152)
	at org.springframework.boot.web.embedded.netty.NettyWebServer.stop(NettyWebServer.java:109)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.stopAndReleaseReactiveWebServer(ReactiveWebServerApplicationContext.java:165)
	... 3 more
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:89)
		... 7 more
Caused by: java.util.concurrent.TimeoutException: HttpServer couldn't be stopped within 45000ms
	at reactor.ipc.netty.tcp.BlockingNettyContext.shutdown(BlockingNettyContext.java:151)
	... 5 more
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoError] :
	reactor.core.publisher.Mono.error(Mono.java:252)
	reactor.ipc.netty.tcp.BlockingNettyContext.shutdown(BlockingNettyContext.java:151)
	org.springframework.boot.web.embedded.netty.NettyWebServer.stop(NettyWebServer.java:109)
	org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.stopAndReleaseReactiveWebServer(ReactiveWebServerApplicationContext.java:165)
	org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.onClose(ReactiveWebServerApplicationContext.java:89)
	org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1019)
	org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:933)
Error has been observed by the following operator(s):
	|_	Mono.error(BlockingNettyContext.java:151)
	|_	Mono.timeout(BlockingNettyContext.java:151)

**Comment by milosztylenda** [comment]
I have created a pull request - https://github.com/spring-projects/spring-boot-issues/pull/74

I know that using #block defeats the purpose of reactive programming but apart from that I am wondering whether this is an issue with WebFlux/Reactor or my code is just ill.

**Comment by bclozel** [comment]
I've looked at your sample and I don't think this qualifies as a bug.

Your application is indeed blocking right in the middle of a Controller handler; this will block one of the few server threads available and can cause this kind of issue.

This does not behave the same way with Tomcat: since the `WebClient` uses Reactor Netty (and so is the server), they both share Netty resources. But even with Tomcat, doing so might block other parts of your application using the Reactor event loop.

You were right, the `block` operator is the one to blame here.

**Comment by milosztylenda** [comment]
Thank you for the reply!

**Comment by the-geka-clarivate** [comment]
milosztylenda could you tell me how you replaced the "block" calling with something and how did you solve the problem?
