### ISSUE TITLE
Clarify documentation on configuring the root logging level to avoid confusing around use of *

### ISSUE THREAD

**Issue by srinivasvsk** [spring-projects/spring-boot#11949]
Hello,

Im seeing an error when i migrate from M7 to RC1 ,  earlier logging.level.*=ERROR works fine. But when i use similar config, it fails to startup, is there a new syntax?

```
2018-02-06 21:06:18.700 ERROR 98458 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'logging.level' to java.util.Map<java.lang.String, java.lang.String>
        at org.springframework.boot.context.properties.bind.Binder.handleBindError(Binder.java:227)
        at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:203)
        at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:187)
        at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:143)
        at org.springframework.boot.context.logging.LoggingApplicationListener.setLogLevels(LoggingApplicationListener.java:306)
        at org.springframework.boot.context.logging.LoggingApplicationListener.initializeFinalLoggingLevels(LoggingApplicationListener.java:289)
        at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:237)
        at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:199)
        at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:74)
        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:351)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:317)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1234)
```

**Comment by wilkinsona** [comment]
The `*` in the documentation was intended as a placeholder for the name of the logger that you want to configure. If `logging.level.*` worked previously, then that was more by accident than by design. If you want to configure all logging to `ERROR` then you should set the level on the root logger:

```
logging.level.root=ERROR
```

We should probably clarify [the documentation](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#boot-features-custom-log-levels).

**Comment by wilkinsona** [comment]
I've also flagged this for team attention so that we can double-check the change in the binder.

**Comment by snicoll** [comment]
`logging.level.*=ERROR` does not do anything special for me with M7

**Comment by srinivasvsk** [comment]
yeah i changed to logging.level.root,  guess level.*   the error/documentation makes it confusing.
thanks for looking
