### ISSUE TITLE
Restcontroller + webflux + pathvariable

### ISSUE THREAD

**Issue by lilletech** [spring-projects/spring-boot#12133]
Using spring-boot 2.0.0.RC1 with webflux starter dependencies
RestController with GetMapping / pathVariable annotation gives httpcode 500

Source :

```
@GetMapping(name = "/settings/{projectId}", produces = MediaType.APPLICATION_STREAM_JSON_VALUE)
  public Flux<Settings> getSettingsByProjectId(@PathVariable String projectId) {
    final Settings projectSettings = settingsService.getSettingsByProjectId(projectId);
    return Flux.just(projectSettings);
  }
```

I am using WebTestClient 
`webTestClient.get().uri("/settings/test").exchange().expectStatus().isOk()`

Result : 
```
2018-02-20 14:35:20.503 ERROR 10312 --- [ctor-http-nio-6] .a.w.r.e.DefaultErrorWebExceptionHandler : Failed to handle request [GET http://localhost:44613/settings/INOVELAN]

org.springframework.web.server.ServerErrorException: Response status 500 with reason "projectId"
	at org.springframework.web.reactive.result.method.annotation.PathVariableMethodArgumentResolver.handleMissingValue(PathVariableMethodArgumentResolver.java:95) ~[spring-webflux-5.0.3.RELEASE.jar:5.0.3.RELEASE]
	at org.springframework.web.reactive.result.method.annotation.AbstractNamedValueArgumentResolver.handleMissingValue(AbstractNamedValueArgumentResolver.java:237) ~[spring-webflux-5.0.3.RELEASE.jar:5.0.3.RELEASE]
	at org.springframework.web.reactive.result.method.annotation.AbstractNamedValueArgumentResolver.getDefaultValue(AbstractNamedValueArgumentResolver.java:214) ~[spring-webflux-5.0.3.RELEASE.jar:5.0.3.RELEASE]
	at org.springframework.web.reactive.result.method.annotation.AbstractNamedValueArgumentResolver.resolveArgument(AbstractNamedValueArgumentResolver.java:111) ~[spring-webflux-5.0.3.RELEASE.jar:5.0.3.RELEASE]
	at org.springframework.web.reactive.result.method.annotation.AbstractNamedValueSyncArgumentResolver.resolveArgument(AbstractNamedValueSyncArgumentResolver.java:63) ~[spring-webflux-5.0.3.RELEASE.jar:5.0.3.RELEASE]
	at org.springframework.web.reactive.result.method.InvocableHandlerMethod.resolveArg(InvocableHandlerMethod.java:214) ~[spring-webflux-5.0.3.RELEASE.jar:5.0.3.RELEASE]
	at org.springframework.web.reactive.result.method.InvocableHandlerMethod.lambda$null$1(InvocableHandlerMethod.java:179) ~[spring-webflux-5.0.3.RELEASE.jar:5.0.3.RELEASE]
	at java.util.Optional.orElseGet(Optional.java:267) ~[na:1.8.0_151]
	at org.springframework.web.reactive.result.method.InvocableHandlerMethod.lambda$resolveArguments$2(InvocableHandlerMethod.java:177) ~[spring-webflux-5.0.3.RELEASE.jar:5.0.3.RELEASE]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_151]
```

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

In this case, it looks like a simple typo in your code sample (you need to use the path attribute, not the name):

`@GetMapping(path = "/settings/{projectId}", produces = MediaType.APPLICATION_STREAM_JSON_VALUE)`

**Comment by lilletech** [comment]
Sorry, you're right. It's not a bug. Effectively.
Too tired ^^.
