### ISSUE TITLE
Don't validate getters for non root bindings

### ISSUE THREAD

**Issue by Polve** [spring-projects/spring-boot#12227]
I'm using Spring Boot milestones since M1, and updated without any problem until milestone RC1.

But when trying to use RC2 I get a very strange startup error I'm unable to understand. It seems having something to do with websocket threads or something similar, I attach the (hoping) relevant message errors.

If I just use RC1 or earlier milestone the code runs without problems.

```
[...]
Caused by: java.lang.IllegalStateException: Unable to get value for property session-info
        at org.springframework.boot.context.properties.bind.JavaBeanBinder$BeanProperty.lambda$getValue$0(JavaBeanBinder.java:306)
        at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:80)
        at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:61)
        at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:53)
        at org.springframework.boot.context.properties.bind.Binder.lambda$null$5(Binder.java:339)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1357)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
        at org.springframework.boot.context.properties.bind.Binder.lambda$bindBean$6(Binder.java:340)
        at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:439)
        at org.springframework.boot.context.properties.bind.Binder$Context.withBean(Binder.java:425)
        at org.springframework.boot.context.properties.bind.Binder$Context.access$400(Binder.java:379)
        at org.springframework.boot.context.properties.bind.Binder.bindBean(Binder.java:337)
        at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:279)
        at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:221)
        ... 82 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.context.properties.bind.JavaBeanBinder$BeanProperty.lambda$getValue$0(JavaBeanBinder.java:303)
        ... 102 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.sessionData': Scope 'websocket' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No thread-bound SimpAttributes found. Your code is probably not processing a client message and executing in message-handling methods invoked by the SimpAnnotationMethodMessageHandler?
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:357)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
        at org.springframework.aop.target.SimpleBeanTargetSource.getTarget(SimpleBeanTargetSource.java:35)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
        at wf.bitcoin.chainmaster.services.SessionData$$EnhancerBySpringCGLIB$$7eebe356.getSessionId(<generated>)
        at wf.bitcoin.chainmaster.services.SessionService.getSessionInfo(SessionService.java:351)
        ... 107 more
Caused by: java.lang.IllegalStateException: No thread-bound SimpAttributes found. Your code is probably not processing a client message and executing in message-handling methods invoked by the SimpAnnotationMethodMessageHandler?
        at org.springframework.messaging.simp.SimpAttributesContextHolder.currentAttributes(SimpAttributesContextHolder.java:83)
        at org.springframework.messaging.simp.SimpSessionScope.get(SimpSessionScope.java:37)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:345)
        ... 112 more
```

**Comment by wilkinsona** [comment]
> If I just use RC1 or earlier milestone the code runs without problems.

Can you share "the code" or a sample that reproduces the problem?

**Comment by Polve** [comment]
I'm sorry I can't: it's quite a big project and I don't even know where to begin to isolate the problematic code.

But I suppose it's some bean unable to be instantiated, maybe because it can't configure itself from config/application.yml

If you have some hints on how to proceed I'm all hears: for the time being I just develop using RC1.

**Comment by Polve** [comment]
Yes, this is the situation:
* `SessionService` is a class annotated with `@Service` and `@ConfigurationProperties`

Inside the class there is a private property defined this way:

```
@Autowired
private SessionData sessionData;
```

where `SessionData` is a simple class defined this way:

```java
@Component
@Scope(value = "websocket", proxyMode = ScopedProxyMode.TARGET_CLASS)
public class SessionData {

  private String sessionId;
  private final byte[] challenge;

  public SessionData() {
    this.challenge = CmUtils.randomBytes(LEN_BITS256);
  }

  public void setSessionId(String sessionId) {
    this.sessionId = sessionId;
  }

  public String getSessionId() {
    return sessionId;
  }

  public byte[] getChallenge() {
    return challenge;
  }

  @Override
  public String toString() {
    return "SD[" + sessionId + " challenge: " + CmUtils.toHex(challenge) + "]";
  }

}
```

The method of SessionService you asked is defined this way:

```java
public Optional<SessionInfo> getSessionInfo() {
   String sessionId = sessionData.getSessionId();
   // …
   returns things
}
```

**Comment by Polve** [comment]
Is it possible to send private attachments?

**Comment by wilkinsona** [comment]
You could email them to me at awilkinson@pivotal.io.

**Comment by wilkinsona** [comment]
Thanks for the email. I've been able to reproduce the problem. Here's an example that does so:

```java
package com.example.demo;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Scope;
import org.springframework.context.annotation.ScopedProxyMode;
import org.springframework.stereotype.Component;
import org.springframework.validation.annotation.Validated;

@SpringBootApplication
public class Gh12227Application {

	public static void main(String[] args) {
		new SpringApplicationBuilder(Gh12227Application.class)
			.properties("my.fruit=orange")
			.run(args);
	}

	@Component
	@Scope(value = "websocket", proxyMode = ScopedProxyMode.TARGET_CLASS)
	class Scoped {

		public String getValue() {
			return "value";
		}

	}

	@Component
	@ConfigurationProperties("my")
	@Validated
	class MyProperties {

		@Autowired
		private Scoped scoped;

		public String getValue() {
			return scoped.getValue();
		}

	}

}
```

I suspect this change in behaviour is due to the fix for https://github.com/spring-projects/spring-boot/issues/10803. If a `@ConfigurationProperties` class is annotated with `@Validated` and one property that could be bound to the class exists, it appears that all of the class's getter methods are now called, irrespective of whether there's a property in the environment that matches the getter.

The scoping is really irrelevant here. It's just what causes the getter to fail. The following is a simpler recreation:

```java
package com.example.demo;

import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.stereotype.Component;
import org.springframework.validation.annotation.Validated;

@SpringBootApplication
public class Gh12227Application {

	public static void main(String[] args) {
		new SpringApplicationBuilder(Gh12227Application.class)
			.properties("my.fruit=orange")
			.run(args);
	}

	@Component
	@ConfigurationProperties("my")
	@Validated
	class MyProperties {

		public String getValue() {
			throw new UnsupportedOperationException();
		}

	}

}
```

Commenting out either `@Validated` or `.properties("my.fruit=orange")` will prevent the problem from occurring.

As I said above, injecting dependencies (particularly a scoped dependency) into a configuration properties bean is very unusual and may not be something that we want to support. However, I'm not sure that the changed behaviour of every getter being called was intentional and we may be able to avoid it.
