### ISSUE TITLE
Declaring a bean named conversionService prevents binding of Duration configuration properties

### ISSUE THREAD

**Issue by fprochazka** [spring-projects/spring-boot#12237]
Hello,
I have the following problem and I believe it might be a bug.

----

I have a multi-module application

* `core` - working perfectly
* `rest-api` - working perfectly (depends on `core`)
* `web-admin` - I'm currently creating this module (depends on `core`)

```java
@SpringBootConfiguration
@Import({
    CoreBootstrap.class, // config from module core
    WebConfiguration.class,
    WebSecurityConfiguration.class,
})
@PropertySource("classpath:application-web-admin.properties")
public class WebAdminApplication
{

    public static void main(final String[] args)
    {
        new SpringApplicationBuilder(WebAdminApplication.class)
            .registerShutdownHook(true)
            .bannerMode(Banner.Mode.OFF)
            .web(WebApplicationType.SERVLET)
            .run(args);
    }

}
```

```java
@Configuration
@EnableWebSecurity
public class WebSecurityConfiguration extends WebSecurityConfigurerAdapter
{
    ...
```

```java
@Configuration
@Import({
    ForwardedHeadersConfiguration.class, // enables ForwardedHeaderFilter
})
@EnableWebMvc
public class WebConfiguration implements WebMvcConfigurer
{
    ...
```

File `application-web-admin.properties`

```properties
server.servlet.context-path=/
spring.jpa.open-in-view=false
spring.mvc.throw-exception-if-no-handler-found=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
spring.security.filter.order=10
spring.thymeleaf.enabled=true
spring.mvc.locale-resolver=FIXED
spring.mvc.locale=en
#spring.resources.cache.period=1s
#spring.mvc.contentnegotiation.favor-parameter=false
#spring.mvc.contentnegotiation.favor-path-extension=false
management.endpoint.health.showDetails=WHEN_AUTHORIZED
management.endpoint.health.roles=ACTUATOR
```

---

Now - I've been struggling to figure out, why my static resources are returning 404 - and I believe I might have found the reason thanks to [this SO answer](https://stackoverflow.com/a/33852040/602899), so I've removed the `@EnableWebMvc` annotation and suddenly this:

```
23:19:47.623 [main] DEBUG org.springframework.boot.devtools.restart.ChangeableUrls - Matching URLs for reloading : [******]
23:19:53.453 [restartedMain  ] INFO                 com.cogvio.WebAdminApplication:	Starting WebAdminApplication
23:19:53.454 [restartedMain  ] DEBUG                com.cogvio.WebAdminApplication:	Running with Spring Boot v2.0.0.RC2, Spring v5.0.4.RELEASE 
23:19:57.191 [localhost-start] INFO  org.springframework.web.context.ContextLoader:	Root WebApplicationContext: initialization completed in 3684 ms 
23:31:27.431 [restartedMain  ] WARN  ationConfigServletWebServerApplicationContext:	Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration': Unsatisfied dependency expressed through method 'setFilterChainProxySecurityConfigurer' parameter 1; nested exception is org.springframework.beans.factory.BeanExpressionException: Expression parsing failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.cogvio.config.WebSecurityConfiguration': Unsatisfied dependency expressed through method 'setContentNegotationStrategy' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration': Unsatisfied dependency expressed through method 'setConfigurers' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'spring.resources-org.springframework.boot.autoconfigure.web.ResourceProperties': Could not bind properties to 'ResourceProperties' : prefix=spring.resources, ignoreInvalidFields=false, ignoreUnknownFields=false; nested exception is org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'spring.resources.cache.period' to java.time.Duration 
23:31:28.634 [restartedMain  ] ERROR        o.s.b.d.LoggingFailureAnalysisReporter:	

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'spring.resources.cache.period' to java.time.Duration:

    Property: spring.resources.cache.period
    Value: 0
    Origin: "spring.resources.cache.period" from property source "refresh"
    Reason: No converter found capable of converting from type [java.lang.String] to type [@org.springframework.boot.convert.DurationUnit java.time.Duration]

Action:

Update your application's configuration
```

I've tried to step-debug it, but there is multiple conversion services, some of them are static and the binding is happening behind 30+ layers of method calls.

If I uncomment this, nothing changes - the error message stays the same (the `Value: 0` doesn't change)

```properties
spring.resources.cache.period=1s
```

I believe the value comes from here

![screenshot from 2018-02-26 23-52-49](https://user-images.githubusercontent.com/158625/36700515-38aff90a-1b50-11e8-82bb-ac51f656cc33.png)

If I remove this from my `pom.xml`, it starts working

```xml
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <optional>true</optional>
        </dependency>
```

------

After I've "fixed" all this, I've decided that I want to change those settings, so I've set

```properties
spring.resources.cache.cachecontrol.maxAge=P365D
```

but - the same problem

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'spring.resources.cache.cachecontrol.max-age' to java.time.Duration:

    Property: spring.resources.cache.cachecontrol.maxage
    Value: P365D
    Origin: "spring.resources.cache.cachecontrol.maxAge" from property source "class path resource [application-web-admin.properties]"
    Reason: No converter found capable of converting from type [java.lang.String] to type [@org.springframework.boot.convert.DurationUnit java.time.Duration]

Action:

Update your application's configuration
```

Which leads me to think, that Spring Boot contains properties that you simply cannot configure, without creating a custom converter.

**Comment by fprochazka** [comment]
The only thing that worked was this - I haven't found a way to register a converter (as the error message suggests) that would work with `*.properties`

```java
@Configuration
public class ConversionsConfiguration
{

    @Bean
    public CustomEditorConfigurer customEditorConfigurer()
    {
        CustomEditorConfigurer configurer = new CustomEditorConfigurer();
        configurer.setPropertyEditorRegistrars(new PropertyEditorRegistrar[]{
            stringToDurationPropertyEditorRegistrar(),
        });
        return configurer;
    }

    @Bean
    public PropertyEditorRegistrar stringToDurationPropertyEditorRegistrar()
    {
        return registry -> registry.registerCustomEditor(
            Duration.class,
            new ConvertingPropertyEditorAdapter(
                ApplicationConversionService.getSharedInstance(),
                TypeDescriptor.valueOf(Duration.class)
            )
        );
    }

}
```

Now I can configure 

```properties
spring.resources.cache.cachecontrol.maxAge=P365D
```

and the application works even with `spring-boot-devtools`

**Comment by snicoll** [comment]
@fprochazka can you please try your application with Spring Boot `2.0.0.BUILD.SNAPSHOT`?

**Comment by snicoll** [comment]
For the record, I've been trying to reproduce this problem with `2.0.0.RC2` and wasn't unable to.

**Comment by fprochazka** [comment]
You can see it in the logs included 

> Running with Spring Boot v2.0.0.RC2, Spring v5.0.4.RELEASE 

I will try to create a minimal reproducible version, but I might not get to it today.

**Comment by snicoll** [comment]
We are releasing GA tomorrow so I'd appreciate some help here. For a start can you try with the snapshot please?

**Comment by snicoll** [comment]
Did it work with a previous milestone?

**Comment by wilkinsona** [comment]
This looks to be a regression in RC2.

In RC2 and master, the DevTools sample fails to start with this addition:

```diff
diff --git a/spring-boot-samples/spring-boot-sample-devtools/src/main/java/sample/devtools/SampleDevToolsApplication.java b/spring-boot-samples/spring-boot-sample-devtools/src/main/java/sample/devtools/SampleDevToolsApplication.java
index e10f482e0d..1d6dff3990 100644
--- a/spring-boot-samples/spring-boot-sample-devtools/src/main/java/sample/devtools/SampleDevToolsApplication.java
+++ b/spring-boot-samples/spring-boot-sample-devtools/src/main/java/sample/devtools/SampleDevToolsApplication.java
@@ -18,6 +18,9 @@ package sample.devtools;

 import org.springframework.boot.SpringApplication;
 import org.springframework.boot.autoconfigure.SpringBootApplication;
+import org.springframework.context.annotation.Bean;
+import org.springframework.core.convert.ConversionService;
+import org.springframework.core.convert.support.DefaultConversionService;

 @SpringBootApplication
 public class SampleDevToolsApplication {
@@ -26,4 +29,9 @@ public class SampleDevToolsApplication {
                SpringApplication.run(SampleDevToolsApplication.class, args);
        }

+       @Bean
+       public ConversionService conversionService() {
+               return DefaultConversionService.getSharedInstance();
+       }
+
 }
```

The problem does not occur with RC1.

**Comment by wilkinsona** [comment]
I works in RC1 because of [this fallback](https://github.com/spring-projects/spring-boot/blob/6e11b98716912acda3e9a7aad2a24e41b8f9b221/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/properties/bind/convert/BinderConversionService.java#L89).

The exception caught at that point is:

```
org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [@org.springframework.boot.context.properties.bind.convert.DefaultDurationUnit java.time.Duration]
	at org.springframework.core.convert.support.GenericConversionService.handleConverterNotFound(GenericConversionService.java:321)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:194)
	at org.springframework.boot.context.properties.bind.convert.BinderConversionService.lambda$convert$1(BinderConversionService.java:78)
	at org.springframework.boot.context.properties.bind.convert.BinderConversionService.callConversionService(BinderConversionService.java:86)
	at org.springframework.boot.context.properties.bind.convert.BinderConversionService.convert(BinderConversionService.java:78)
	at org.springframework.boot.context.properties.bind.ResolvableTypeDescriptor.convert(ResolvableTypeDescriptor.java:64)
	at org.springframework.boot.context.properties.bind.Binder.convert(Binder.java:233)
	at org.springframework.boot.context.properties.bind.Binder.bindProperty(Binder.java:303)
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:249)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:198)
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindBean$4(Binder.java:313)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:70)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:59)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:51)
	at org.springframework.boot.context.properties.bind.Binder.lambda$null$5(Binder.java:321)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1357)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindBean$6(Binder.java:322)
	at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:415)
	at org.springframework.boot.context.properties.bind.Binder$Context.withBean(Binder.java:405)
	at org.springframework.boot.context.properties.bind.Binder.bindBean(Binder.java:319)
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:261)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:198)
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindBean$4(Binder.java:313)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:70)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:59)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:51)
	at org.springframework.boot.context.properties.bind.Binder.lambda$null$5(Binder.java:321)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1357)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindBean$6(Binder.java:322)
	at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:415)
	at org.springframework.boot.context.properties.bind.Binder$Context.withBean(Binder.java:405)
	at org.springframework.boot.context.properties.bind.Binder.bindBean(Binder.java:319)
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:261)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:198)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:187)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:169)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBinder.bind(ConfigurationPropertiesBinder.java:79)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:167)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:423)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1702)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:583)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1065)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:815)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:721)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:192)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1270)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1127)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:368)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1250)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1099)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1325)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1291)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveMultipleBeans(DefaultListableBeanFactory.java:1193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1096)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory$DependencyObjectProvider.getIfAvailable(DefaultListableBeanFactory.java:1684)
	at org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration.<init>(ErrorMvcAutoConfiguration.java:102)
	at org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration$$EnhancerBySpringCGLIB$$ee05dbbf.<init>(<generated>)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:170)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:271)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1270)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1127)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:368)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1250)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1099)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:516)
	at org.springframework.boot.web.server.ErrorPageRegistrarBeanPostProcessor.getRegistrars(ErrorPageRegistrarBeanPostProcessor.java:80)
	at org.springframework.boot.web.server.ErrorPageRegistrarBeanPostProcessor.postProcessBeforeInitialization(ErrorPageRegistrarBeanPostProcessor.java:71)
	at org.springframework.boot.web.server.ErrorPageRegistrarBeanPostProcessor.postProcessBeforeInitialization(ErrorPageRegistrarBeanPostProcessor.java:59)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:423)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1702)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:583)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:205)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getWebServerFactory(ServletWebServerApplicationContext.java:212)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:176)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:150)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:138)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:388)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1234)
	at sample.devtools.SampleDevToolsApplication.main(SampleDevToolsApplication.java:29)
```

**Comment by fprochazka** [comment]
Awesome, thanks!
