### ISSUE TITLE
ConfigurationPropertyName.isIndexed fails when argument is the empty string

### ISSUE THREAD

**Issue by ulrd** [spring-projects/spring-boot#12363]
After migrating from spring-boot 2.0.0.M7 to 2.0.0.RELEASE (from maven central repo)
I get this error:
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'application' to commons.utils.Application:

    Reason: String index out of range: 0

Action:
Update your application's configuration
```

The application.properties for application looks like:

```
application.name=my-app
application.version=1.0.0
```

The stacktrace (see below) shows the issue is at 
`org.springframework.boot.context.properties.source.ConfigurationPropertyName` line 413
where element is the empty string
```
	private static boolean isIndexed(CharSequence element) {
		return element.charAt(0) == '[' && element.charAt(element.length() - 1) == ']';
	}
```

In 2.0.0.M7 the (working) code is
```
private static boolean isIndexed(CharSequence element) {
		int length = element.length();
		return length > 2 && element.charAt(0) == '['
				&& element.charAt(length - 1) == ']';
	}
```

```
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658)
	at org.springframework.boot.context.properties.source.ConfigurationPropertyName.isIndexed(ConfigurationPropertyName.java:413)
	at org.springframework.boot.context.properties.source.ConfigurationPropertyName.append(ConfigurationPropertyName.java:188)
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindBean$4(Binder.java:332)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:72)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:61)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:53)
	at org.springframework.boot.context.properties.bind.Binder.lambda$null$5(Binder.java:339)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindBean$6(Binder.java:340)
	at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:439)
	at org.springframework.boot.context.properties.bind.Binder$Context.withBean(Binder.java:425)
	at org.springframework.boot.context.properties.bind.Binder$Context.access$400(Binder.java:379)
	at org.springframework.boot.context.properties.bind.Binder.bindBean(Binder.java:337)
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:279)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:221)
```

Additional note: The Application class is a singleton retrieved using a static method:

```
    @Bean
    @ConfigurationProperties("application")
    public Application application()
    {
        return Application.get();
    }
```

**Comment by snicoll** [comment]
Can you please share a sample that we can run that reproduces the problem?

**Comment by ulrd** [comment]
Here is a trivial example. Just change the version in the pom.xml file to make it work/fail

[dummy.zip](https://github.com/spring-projects/spring-boot/files/1788627/dummy.zip)

**Comment by snicoll** [comment]
Thanks. I have no idea why yet, but the presence of this method makes the binding fail:

```java
public static Application get() {
	return instance;
}
```

As soon as this method is removed (even not invoked by anything in the code) binding works.
