### ISSUE TITLE
Spring-Boot 2.0.0.RELEASE Do java.sql.SQLFeatureNotSupportedException: HikariDataSource.getConnection is not implemented

### ISSUE THREAD

**Issue by mattgolem** [spring-projects/spring-boot#12421]
spring-boot v. 2.0.0.RELEASE 

With this Configuration Class,  Application run failed: do java.sql.SQLFeatureNotSupportedException.
The HikariDataSource.getConnection is not implemented

```
@Configuration
@EnableTransactionManagement
@EnableJpaRepositories(entityManagerFactoryRef = "memEntityManagerFactory", transactionManagerRef = "memTransactionManager", basePackages = {
		"com.example.model.repo" })
public class H2JpaConfiguration {
	@Bean(name = "memDataSource")
	@ConfigurationProperties(prefix = "mem.datasource")
	public DataSource dataSource() {
		return DataSourceBuilder.create().build();
	}

	@Bean(name = "memEntityManagerFactory")
	public LocalContainerEntityManagerFactoryBean memEntityManagerFactory(EntityManagerFactoryBuilder builder,
			@Qualifier("memDataSource") DataSource dataSource) {
		
		Properties properties = new Properties();
		properties.setProperty("eclipselink.weaving", "false");
		
		EclipseLinkJpaVendorAdapter eclipseVendor = new EclipseLinkJpaVendorAdapter();
		eclipseVendor.setGenerateDdl(true);
	    
	    LocalContainerEntityManagerFactoryBean emf = builder.dataSource(dataSource)
				.packages("com.example.model.domain")
				.persistenceUnit("VaadinFramework-h2-pu").build();
	    
	    emf.setJpaProperties(properties);
	    emf.setJpaVendorAdapter(eclipseVendor);
	    
	    return emf;
	}

	@Bean(name = "memTransactionManager")
	public PlatformTransactionManager memTransactionManager(
			@Qualifier("memEntityManagerFactory") EntityManagerFactory memEntityManagerFactory) {
		return new JpaTransactionManager(memEntityManagerFactory);
	}
}
```

application.properties

```
mem.datasource.url=jdbc:h2:mem:test_mem
mem.datasource.driver-class-name=org.h2.Driver
mem.datasource.username=sa
mem.datasource.password=
```

Error:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'memEntityManagerFactory' defined in class path resource [com/example/model/H2JpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.1.v20171221-bd47e8f): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLFeatureNotSupportedException
Error Code: 0
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1710) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:583) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1085) ~[spring-context-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:858) ~[spring-context-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:388) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1234) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at com.example.FrameworkVaadinApplication.main(FrameworkVaadinApplication.java:49) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_60]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_60]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-2.0.0.RELEASE.jar:2.0.0.RELEASE]
Caused by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.1.v20171221-bd47e8f): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLFeatureNotSupportedException
Error Code: 0
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:846) ~[eclipselink-2.7.1.jar:2.7.1.v20171221-bd47e8f]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getAbstractSession(EntityManagerFactoryDelegate.java:216) ~[eclipselink-2.7.1.jar:2.7.1.v20171221-bd47e8f]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getDatabaseSession(EntityManagerFactoryDelegate.java:194) ~[eclipselink-2.7.1.jar:2.7.1.v20171221-bd47e8f]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.getDatabaseSession(EntityManagerFactoryImpl.java:540) ~[eclipselink-2.7.1.jar:2.7.1.v20171221-bd47e8f]
	at org.eclipse.persistence.jpa.PersistenceProvider.createContainerEntityManagerFactoryImpl(PersistenceProvider.java:385) ~[eclipselink-2.7.1.jar:2.7.1.v20171221-bd47e8f]
	at org.eclipse.persistence.jpa.PersistenceProvider.createContainerEntityManagerFactory(PersistenceProvider.java:313) ~[eclipselink-2.7.1.jar:2.7.1.v20171221-bd47e8f]
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365) ~[spring-orm-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:388) ~[spring-orm-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:377) ~[spring-orm-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341) ~[spring-orm-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1769) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1706) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	... 21 common frames omitted
Caused by: org.eclipse.persistence.exceptions.DatabaseException: 
Internal Exception: java.sql.SQLFeatureNotSupportedException
Error Code: 0
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:316) ~[eclipselink-2.7.1.jar:2.7.1.v20171221-bd47e8f]
	at org.eclipse.persistence.sessions.JNDIConnector.connect(JNDIConnector.java:147) ~[eclipselink-2.7.1.jar:2.7.1.v20171221-bd47e8f]
	at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:170) ~[eclipselink-2.7.1.jar:2.7.1.v20171221-bd47e8f]
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.setOrDetectDatasource(DatabaseSessionImpl.java:228) ~[eclipselink-2.7.1.jar:2.7.1.v20171221-bd47e8f]
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:804) ~[eclipselink-2.7.1.jar:2.7.1.v20171221-bd47e8f]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:254) ~[eclipselink-2.7.1.jar:2.7.1.v20171221-bd47e8f]
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:759) ~[eclipselink-2.7.1.jar:2.7.1.v20171221-bd47e8f]
	... 32 common frames omitted
Caused by: java.sql.SQLFeatureNotSupportedException: null
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:135) ~[HikariCP-2.7.8.jar:na]
	at org.eclipse.persistence.sessions.JNDIConnector.connect(JNDIConnector.java:144) ~[eclipselink-2.7.1.jar:2.7.1.v20171221-bd47e8f]
	... 37 common frames omitted
```

**Comment by snicoll** [comment]
Thanks for getting in touch but there is nothing that indicates that there is a bug in Spring Boot as you're configuring the application yourself. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.

You may be interested by the [documentation on configuration custom datasources](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-configure-a-datasource) that describes the fact that Hikari doesn't have a `url` property.

**Comment by mattgolem** [comment]
Thanks for your answer, i changed application.properties to

```
mem.datasource.jdbc-url=jdbc:h2:mem:test_mem
mem.datasource.username=sa
mem.datasource.password=
```

but the problem persists.

**Comment by wilkinsona** [comment]
The problem's caused by EclipseLink attempting to get a connection with a username and password (it's calling `getConnection(String, String)`). HikariCP doesn't support getting a connection with a specific username and password. You either need to configure EclipseLink so that it calls `getConnection()` and uses the username and password that's shared across all of the pooled connections or use a different connection pool.
