### ISSUE TITLE
Spring boot class loader slows after some time

### ISSUE THREAD

**Issue by philip1982** [spring-projects/spring-boot#12430]
Our application is spring batch - spring boot (1.4.0.RELEASE) application that calls some services to load data into couchbase. We are using batch -partition  that create 60 task executors that run in parallel to speed up loading. The application runs on a Linux box and is run as a jar application(`java -jar` ...).

The problem we face is that after a period of run say 12 hours the application slows down . On taking the thread dump some of the threads blocked as below 

```
taskExecutor-29 
Stack Trace is: 
java.lang.Thread.State: BLOCKED
at java.lang.Class.forName0(Native Method)
- waiting to lock <7a31ca20> (a org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl$AggregatedClassLoader) owned by "taskExecutor-5" t@177
at java.lang.Class.forName(Class.java:348)
at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.classForName(ClassLoaderServiceImpl.java:226)
at org.hibernate.internal.util.ReflectHelper.getConstantValue(ReflectHelper.java:235)
at org.hibernate.hql.internal.ast.QueryTranslatorImpl$JavaConstantConverter.handleDotStructure(QueryTranslatorImpl.java:615)
at org.hibernate.hql.internal.ast.QueryTranslatorImpl$JavaConstantConverter.visit(QueryTranslatorImpl.java:610)
at org.hibernate.hql.internal.ast.util.NodeTraverser.visitDepthFirst(NodeTraverser.java:60)
at org.hibernate.hql.internal.ast.util.NodeTraverser.traverseDepthFirst(NodeTraverser.java:49)
```

=======the runnabale thread cause
[threaddump.txt](https://github.com/spring-projects/spring-boot/files/1800591/threaddump.txt)
 the issue is as below=====

```
taskExecutor-5 - threadId:177 - state:RUNNABLE
stackTrace:
java.lang.Thread.State: RUNNABLE
at java.lang.Throwable.fillInStackTrace(Native Method)
at java.lang.Throwable.fillInStackTrace(Throwable.java:783)
- locked <37ff8392> (a java.lang.ClassNotFoundException)
at java.lang.Throwable.<init>(Throwable.java:287)
at java.lang.Exception.<init>(Exception.java:84)
at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:75)
at java.lang.ClassNotFoundException.<init>(ClassNotFoundException.java:82)
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
- locked <d34a9c0> (a java.lang.Object)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
- locked <75a1cd57> (a org.springframework.boot.loader.LaunchedURLClassLoader)
at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:89)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl$AggregatedClassLoader.findClass(ClassLoaderServiceImpl.java:209)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
- locked <7a31ca20> (a org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl$AggregatedClassLoader)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.classForName(ClassLoaderServiceImpl.java:226)
at org.hibernate.internal.util.ReflectHelper.getConstantValue(ReflectHelper.java:235)
at org.hibernate.hql.internal.ast.QueryTranslatorImpl$JavaConstantConverter.handleDotStructure(QueryTranslatorImpl.java:615)
at org.hibernate.hql.internal.ast.QueryTranslatorImpl$JavaConstantConverter.visit(QueryTranslatorImpl.java:610)
at org.hibernate.hql.internal.ast.util.NodeTraverser.visitDepthFirst(NodeTraverser.java:60)
at org.hibernate.hql.internal.ast.util.NodeTraverser.traverseDepthFirst(NodeTraverser.java:49)
at org.hibernate.hql.internal.ast.QueryTranslatorImpl.parse(QueryTranslatorImpl.java:284)
at org.hibernate.hql.internal.ast.QueryTranslatorImpl.doCompile(QueryTranslatorImpl.java:187)
- locked <14bc6231> (a org.hibernate.hql.internal.ast.QueryTranslatorImpl)
at org.hibernate.hql.internal.ast.QueryTranslatorImpl.compile(QueryTranslatorImpl.java:142)
at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:115)
at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:76)
at org.hibernate.engine.query.spi.QueryPlanCache.getHQLQueryPlan(QueryPlanCache.java:150)
at org.hibernate.internal.AbstractSessionImpl.getHQLQueryPlan(AbstractSessionImpl.java:302)
at org.hibernate.internal.AbstractSessionImpl.createQuery(AbstractSessionImpl.java:240)
at org.hibernate.internal.SessionImpl.createQuery(SessionImpl.java:1894)
at org.hibernate.jpa.spi.AbstractEntityManagerImpl.createQuery(AbstractEntityManagerImpl.java:291)
at sun.reflect.GeneratedMethodAccessor513.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:298)
at com.sun.proxy.$Proxy104.createQuery(Unknown Source)
```

Not sure why the reloading happens again ? please help

**Comment by wilkinsona** [comment]
Unfortunately, a single thread dump doesn’t really tell us much.

It shows one thread in the process of throwing a ClassNotFoundException from Boot’s LaunchedURLClassLoader and holding a lock in some Hibernate code that several other threads are waiting to acquire.

That could be a recurring problem or something that only happened once. A thread dump doesn’t tell us which. Even if it is a recurring problem, that could be due to some external code repeatedly trying to load a non-existent class, or it could be a problem with the class loader.

If you believe the class loader is the problem, please provide the evidence from which you drew that conclusion.

You may also want to upgrade to a newer version of Spring Boot and, indirectly, Hibernate as whatever is causing the slowdown you have apparently seen may have already been fixed.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by philip1982** [comment]
Sorry for thr delay. We have deployed the spring boot 1.4 application as a war in tomcat  to see whether the blocking issue  comes. The issue was reporoduced again and is more prominitent .Pleasse find attached multiple thread dumps from application . No the thread stack points to the classloaded of tomcat.

As ssugested we have stated to upgrade the jars ( springboot to 1.5 as we are not able to upgrade to 2.x due to elastic upgrade required)  . Thanks for the support

**Comment by wilkinsona** [comment]
Thanks for the additional information. It's interesting to learn that the problem occurs when your application is deployed as a war file. In that case, Spring Boot's ClassLoader isn't used so it disproves the theory that's claimed in the title of this issue.

Knowing that the issue isn't in Spring Boot's ClassLoader makes Hibernate the most likely cause. Some searching backs this up: https://vladmihalcea.com/the-performance-penalty-of-class-forname-when-parsing-jpql-and-criteria-queries/.

As [suspected above](https://github.com/spring-projects/spring-boot/issues/12430#issuecomment-372139985), it looks like upgrading to a newer version of Hibernate will resolve the problem.

**Comment by philip1982** [comment]
Thanks for the  information. Please note that it is ' Spring boot war ' file  that is deployed in tomcat

**Comment by wilkinsona** [comment]
> Please note that it is ' Spring boot war ' file that is deployed in tomcat

That doesn't matter. Spring Boot's class loader is one involved when you're running a fat jar or war using `java -jar`.

**Comment by qq65827** [comment]
tks~
