### ISSUE TITLE
Jar loader fails when using full path from different context handler

### ISSUE THREAD

**Issue by ikeyat** [spring-projects/spring-boot#12483]
## Problem
I faced an exception when loading more than 2 dozer mapping files with dozer-spring and Spring Boot.
The following exception is exactly thrown at the time when loading the 2nd dozer mapping file.
It is usual for dozer users to load many dozer mapping files. I think this problem should be resolved.

This exception is **NOT** thrown without Spring Boot.

```
org.xml.sax.SAXException: Parsing Fatal Error
Line:   1
URI:   null
Message: Content is not allowed in prolog.
```

## Analysis
This behavior may be caused by  ``org.springframework.boot.loader.data.RandomAccessDataFile$DataInputStream`` that loads the 2nd dozer mapping file.
On the other hands, the 1st dozer mapping file is loaded by ``org.springframework.boot.loader.data.ZipInflaterInputStream``. It successes to load as I wrote.

I doubt the difference comes from how to get URL of the 2nd mapping file.
For the 2nd dozer mapping file, URL is got through ``Thread.currentThread().getContextClassLoader().getResource(stringValue)``. This may lead to use ``org.springframework.boot.loader.data.RandomAccessDataFile$DataInputStream`` for the 2nd dozer mapping file.
(``stringValue`` is like ``"jar:file:/C:/xxx/target/xxx.jar!/META-INF/xxx/xxx-mapping.xml"`` )

Without Spring Boot, ``Thread.currentThread().getContextClassLoader().getResource(stringValue)`` is never called and ``sun.net.www.protocl.jar.JarURLConnection$JarURLInputStream`` is used to load every dozer mapping file.

## Repro
Repro: https://github.com/debugroom/sample/blob/develop/sample-spring-boot/src/main/java/org/debugroom/sample/spring/boot/config/TestDozerApp.java

Spring Boot: 1.5.9.RELEAE, 2.0.0.RELEASE
Dozer: 5.5.1
Dozer-Spring: 5.5.1

**Comment by philwebb** [comment]
@ikeyat There's a lot of moving parts in that sample application and I'm having trouble using it. Are you able to create a simpler application that shows the problem, preferably without using Lombok?

**Comment by ikeyat** [comment]
@philwebb 
I uploaded another repors.
https://github.com/ikeyat/spring-boot-issues/tree/master/spring-boot-issue-12483
https://github.com/ikeyat/spring-boot-issues/tree/master/spring-boot-issue-12483-noboot

The first one is to repro the exception with Spring Boot (and its jar repackage). Please execute it from an executable jar.
The second one is to prove the exception is not thrown without Spring Boot (but using maven-assembly-plugin instead of spring boot repackage).

**Comment by philwebb** [comment]
Thanks for the simplified project @ikeyat.

I'm still trying to get to the bottom of this, but it looks like `JarURLConnection` is not throwing exceptions when it should be.

It looks like the classloader is calling `Handler.openConnection(..)` for the URL `jar:file:/Users/pwebb/projects/spring-boot/samples/spring-boot-issues/spring-boot-issue-12483/target/spring-boot-issue-12483-0.0.1-SNAPSHOT.jar!/META-INF/dozer/test1/bean1-mapping.xml`. The `Handler` being used was created from another context URL and it has the following `jarFile`, `/Users/pwebb/projects/spring-boot/samples/spring-boot-issues/spring-boot-issue-12483/target/spring-boot-issue-12483-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-boot-starter-2.0.0.RELEASE.jar`

We then go into `JarURLConnection.get` and eventually get an empty `JarEntryName`. That means that `NOT_FOUND_CONNECTION` is not thrown and the classloader things it's found a valid URL.

**Comment by philwebb** [comment]
I think the following test in `JarFileTests` replicates the problem:

```java
	@Test
	public void createUrlFromStringWithContextWhenNotFound() throws Exception {
		// gh-12483
		JarURLConnection.setUseFastExceptions(true);
		try {
			JarFile.registerUrlProtocolHandler();
			JarFile nested = this.jarFile
					.getNestedJarFile(this.jarFile.getEntry("nested.jar"));
			URL context = nested.getUrl();
			URL notFoundUrl = new URL(context,
					"jar:" + this.rootJarFile.toURI() + "!/no.dat");
			this.thrown.expect(FileNotFoundException.class);
			notFoundUrl.openStream();
		}
		finally {
			JarURLConnection.setUseFastExceptions(false);
		}
	}
```

**Comment by philwebb** [comment]
It's a regression I think, but it works by accident in 1.5 because the following is thrown:

```
java.lang.AssertionError: 
Expected: an instance of java.io.FileNotFoundException
     but: <java.lang.StringIndexOutOfBoundsException: String index out of range: -6> is a java.lang.StringIndexOutOfBoundsException
Stacktrace was: java.lang.StringIndexOutOfBoundsException: String index out of range: -6
	at java.lang.String.substring(String.java:1931)
	at org.springframework.boot.loader.jar.JarURLConnection.extractFullSpec(JarURLConnection.java:286)
	at org.springframework.boot.loader.jar.JarURLConnection.get(JarURLConnection.java:257)
	at org.springframework.boot.loader.jar.Handler.openConnection(Handler.java:96)
	at java.net.URL.openConnection(URL.java:979)
	at java.net.URL.openStream(URL.java:1045)
	at org.springframework.boot.loader.jar.JarFileTests.createUrlFromStringWithContextWhenNotFound(JarFileTests.java:500)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)

	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.junit.rules.ExpectedException.handleException(ExpectedException.java:252)
	at org.junit.rules.ExpectedException.access$000(ExpectedException.java:106)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:241)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
```

**Comment by ikeyat** [comment]
@philwebb 
Thanks! The problem was resolved in my app with your fix.
