### ISSUE TITLE
spring boot data redis starter redisTemplate keys result 0 and lua script making-no-sense exception

### ISSUE THREAD

**Issue by Jovons** [spring-projects/spring-boot#12531]
The following code is a combination of both sample project and code segments from script lua section in reference (https://docs.spring.io/spring-data/redis/docs/2.0.5.RELEASE/). 
The following code meets 3 issues however:
1) redisTemplate.opsForValue.get("hello")   prints a value, but redisTemplate.keys("*") result in 0.
2) when running lua script with stringRedisTemplate, it somehow deserializes the array or collection ARGS in `execute(RedisScript<T> script, List<K> keys, Object... args)`  as a single String (when debug I stepped in), and thereafter  throws following exception:

java.lang.ClassCastException: java.util.Arrays$ArrayList cannot be cast to java.lang.String
	at org.springframework.data.redis.serializer.StringRedisSerializer.serialize(StringRedisSerializer.java:35) ~[spring-data-redis-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.data.redis.core.script.DefaultScriptExecutor.keysAndArgs(DefaultScriptExecutor.java:112) ~[spring-data-redis-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.data.redis.core.script.DefaultScriptExecutor.lambda$execute$0(DefaultScriptExecutor.java:60) ~[spring-data-redis-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:224) ~[spring-data-redis-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:184) ~[spring-data-redis-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:171) ~[spring-data-redis-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.data.redis.core.script.DefaultScriptExecutor.execute(DefaultScriptExecutor.java:58) ~[spring-data-redis-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.data.redis.core.script.DefaultScriptExecutor.execute(DefaultScriptExecutor.java:52) ~[spring-data-redis-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:346) ~[spring-data-redis-2.0.5.RELEASE.jar:2.0.5.RELEASE]

3) when using lua script with redisTemplate, using example from the former mentioned official reference , it throws `ERR Error compiling script (new function): user_script:1: '=' expected near '/'` for more details see: https://stackoverflow.com/questions/49334757/spring-boot-redis-running-lua-script-fails

This is the code:

```
@SpringBootApplication
public class SampleRedisApplication implements CommandLineRunner {

	@Autowired
	private StringRedisTemplate template;

	@Autowired
	private RedisTemplate redisTemplate;

	@Override
	public void run(String... args) throws Exception {
		{
			ValueOperations<String, Integer> stringIntegerValueOperations = this.redisTemplate.opsForValue();
			String key = "hello";
			int v = 100;
			if (!this.redisTemplate.hasKey(key)) {
				System.out.println("write redisTemplate");
				stringIntegerValueOperations.set(key, v);
			}
			Set<String> keys = this.redisTemplate.keys("*");
			System.out.println(String.join(",", keys));
		}
		{
			ValueOperations<String, String> ops = this.template.opsForValue();
			String key = "spring.boot.redis.test";
			if (!this.template.hasKey(key)) {
			ops.set(key, "foo");
			System.out.println("write stringTemplate");
		}
			Set<String> keys = this.template.keys("*");
			System.out.println(String.join(",", keys));
		}
		
		RedisScript<Boolean> script = RedisScript.of("META-INF/scripts/checkandset.lua", Boolean.class);
		template.execute(script, singletonList("key"), asList("1",  "2"));
	}


	public static void main(String[] args) {
		// Close the context so it doesn't stay awake listening for redis
		SpringApplication.run(SampleRedisApplication.class, args).close();
	}

}
```

**Comment by wilkinsona** [comment]
This looks like an issue with Spring Data Redis to me rather than an issue with how Spring Boot configures Spring Data Redis. Please open a [JIRA ticket](https://jira.spring.io/browse/DATAREDIS) to report this to the Data Redis team. If it turns out that it is a problem in Spring Boot we can re-open this issue.
