### ISSUE TITLE
Exceptions raised in `running` listeners called from SpringApplication.run can leak application context

### ISSUE THREAD

**Issue by stevenschlansker** [spring-projects/spring-boot#12549]
On Spring Boot 2.0.0.RELEASE, the `SpringApplication.run` method reads:
```java
		try {
			... start up context...
			listeners.started(context);
			callRunners(context, applicationArguments);
		}
		catch (Throwable ex) {
			handleRunFailure(context, listeners, exceptionReporters, ex);
			throw new IllegalStateException(ex);
		}
		listeners.running(context);
		return context;
```
Notably, the `listeners.running` call is outside the large try/catch block.  If an exception is thrown from a running listener, it is never caught:

```
Exception in thread "main" org.apache.kafka.streams.errors.InvalidStateStoreException: the state store, private.chat.endpoint, may have migrated to another instance.
	at org.apache.kafka.streams.state.internals.QueryableStoreProvider.getStore(QueryableStoreProvider.java:60)
	at org.apache.kafka.streams.KafkaStreams.store(KafkaStreams.java:1043)
...
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:399)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:353)
	at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:103)
	at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:78)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:341)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:137)
	at com.opentable.server.OTApplication.run(OTApplication.java:48)
	at com.opentable.server.OTApplication.run(OTApplication.java:32)
	at com.opentable.chat.service.WorkerMain.main(WorkerMain.java:28)
```
and by exiting SpringApplication.run abnormally on line 341, notice how we leak a started and running `context` -- the caller is not able to close the context, nor does Spring Boot do it for you -- so you end up with a "zombie" partially initialized instance.

**Comment by stevenschlansker** [comment]
Additionall, we also have a `ApplicationFailedEvent` listener which we'd expect to fire, but does not.

**Comment by wilkinsona** [comment]
> notice how we leak a started and running context

That's a bug that we should fix. Thanks for the report.

> Additionally, we also have a ApplicationFailedEvent listener which we'd expect to fire, but does not.

As things stand, you shouldn't expect an `ApplicationFailedEvent` to be published. By that point an `ApplicationReadyEvent` will have been received by some listeners and we do not want them to receive both an `ApplicationReadyEvent` and an `ApplicationFailedEvent` as the two events are contradictory.

**Comment by snicoll** [comment]
@wilkinsona I've hacked in cd9611e and I think I've fixed the issue. I've tried to extract `handleRunFailure` in something more generic (to avoid invoking the listeners in this new case) but the API felt a bit awkward so I went with an extra boolean flag to determine if the listeners have to be invoked or not. 

Would you mind having a look please?

**Comment by wilkinsona** [comment]
Thanks, @snicoll. I wonder if passing `null` for the run listeners would be better than the extra `boolean` flat?

**Comment by snicoll** [comment]
@wilkinsona oh my, good catch. I overlooked that, definitely better!
