### ISSUE TITLE
Integration tests are regularly failing on CI

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#12689]
See https://ci.spring.io/teams/spring-boot/pipelines/spring-boot/jobs/build/builds/1093 for example.

Hijack shows logs like this:

```
# Created on 2018-03-29T23:47:49.343
Corrupted STDOUT by directly writing to native stream in forked JVM 1. Stream '#   http://bugreport.java.com/bugreport/crash.jsp'.
java.lang.IllegalArgumentException: Stream stdin corrupted. Expected comma after third character in command '#   http://bugreport.java.com/bugreport/crash.jsp'.
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient$OperationalData.<init>(ForkClient.java:506)
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.processLine(ForkClient.java:212)
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.consumeLine(ForkClient.java:179)
	at org.apache.maven.plugin.surefire.booterclient.output.ThreadedStreamConsumer$Pumper.run(ThreadedStreamConsumer.java:88)
	at java.lang.Thread.run(Thread.java:748)


# Created on 2018-03-29T23:47:49.344
Corrupted STDOUT by directly writing to native stream in forked JVM 1. Stream '# The crash happened outside the Java Virtual Machine in native code.'.
java.lang.IllegalArgumentException: Stream stdin corrupted. Expected comma after third character in command '# The crash happened outside the Java Virtual Machine in native code.'.
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient$OperationalData.<init>(ForkClient.java:506)
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.processLine(ForkClient.java:212)
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.consumeLine(ForkClient.java:179)
	at org.apache.maven.plugin.surefire.booterclient.output.ThreadedStreamConsumer$Pumper.run(ThreadedStreamConsumer.java:88)
	at java.lang.Thread.run(Thread.java:748)


# Created on 2018-03-29T23:47:49.344
Corrupted STDOUT by directly writing to native stream in forked JVM 1. Stream '# See problematic frame for where to report the bug.'.
java.lang.IllegalArgumentException: Stream stdin corrupted. Expected comma after third character in command '# See problematic frame for where to report the bug.'.
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient$OperationalData.<init>(ForkClient.java:506)
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.processLine(ForkClient.java:212)
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.consumeLine(ForkClient.java:179)
	at org.apache.maven.plugin.surefire.booterclient.output.ThreadedStreamConsumer$Pumper.run(ThreadedStreamConsumer.java:88)
	at java.lang.Thread.run(Thread.java:748)


# Created on 2018-03-29T23:47:49.344
Corrupted STDOUT by directly writing to native stream in forked JVM 1. Stream '#'.
java.lang.IllegalArgumentException: Stream stdin corrupted. Expected comma after third character in command '#'.
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient$OperationalData.<init>(ForkClient.java:506)
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.processLine(ForkClient.java:212)
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.consumeLine(ForkClient.java:179)
	at org.apache.maven.plugin.surefire.booterclient.output.ThreadedStreamConsumer$Pumper.run(ThreadedStreamConsumer.java:88)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by philwebb** [comment]
Also seeing a lot of http://maven.apache.org/surefire/maven-failsafe-plugin/faq.html#corruptedstream

**Comment by philwebb** [comment]
Seems to be generally a bit better

![screen shot 2018-04-04 at 8 48 57 pm](https://user-images.githubusercontent.com/519772/38346395-a7596722-3849-11e8-8b53-5217bcbdc6bc.png)

**Comment by mbhave** [comment]
Some of it might be because we moved away from snapshots right before the release but we can reopen if it goes back to being red.

**Comment by philwebb** [comment]
Yeah, I'm not totally convinced correlation implies causation
