### ISSUE TITLE
JVM truststore/keystore config conflict with EmbeddedServletContainerCustomizer.setSslStoreProvider(...)

### ISSUE THREAD

**Issue by icha024** [spring-projects/spring-boot#12688]
### Env
Spring-Boot 1.5.10
(Default Tomcat servlet)

### Use case
I have to interact with multiple systems that require SSL client, and so the easiest thing to do is to set the truststore with global CA cert on the whole app via `-Djavax.net.ssl.trustStore=...`

And I need to load the private keypair programatically via Vault on startup.

### Issue
Truststore created by `EmbeddedServletContainerCustomizer.setSslStoreProvider(...)` does not seem to have a default password. This is normally fine, but when used with `-Djavax.net.ssl.trustStorePassword=...` to set a global truststore/password then this error shows in the logs:
```
java.security.UnrecoverableKeyException: Password verification failed
```
It looks like Tomcat is using the JVM arg to validate the SslStoreProvider truststore even when a customised SSL Provider was passed in.

### To Replicate
Get Mark Paluch's sample project on Spring Cloud Vault to set SSL store provider programatically on startup:
https://github.com/mp911de/spring-cloud-vault-config-samples/blob/master/spring-cloud-vault/pki/readme.md

Run it with the `-Djavax.net.ssl.trustStorePassword=...` flag

### What I've tried so far

1. I've tried `EmbeddedServletContainerCustomizer.setSsl(...)` to pass in a password, it didn't work. I also tried omitting the password - also didn't work.

2. Read in the truststore file, then merged it with the Vault's response cert chain as the SSL Provider, and then remove the trustore JVM property before Tomcat loads - this seem to have worked, but anything that get loaded after this no longer have access to the global truststore config (not a very nice solution)

**Comment by philwebb** [comment]
Can you attach the full stack trace please? I'm interested to know where specifically in the Tomcat codebase the truststore is loaded.

**Comment by icha024** [comment]
Command `mvn -Djavax.net.ssl.trustStorePassword=password spring-boot:run` (only password, no truststore file were actually passed in to show the point)

```
2018-03-30 21:26:07.922  INFO 1013 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'configurationPropertiesRebinder': registering with JMX server as MBean [org.springframework.cloud.context.properties:name=configurationPropertiesRebinder,context=4024c5b4,type=ConfigurationPropertiesRebinder]
2018-03-30 21:26:08.018  WARN 1013 --- [           main] o.apache.tomcat.util.net.SSLHostConfig   : The provided trust store password could not be used to unlock and/or validate the trust store. Retrying to access the trust store with a null password which will skip validation.

java.security.UnrecoverableKeyException: Password verification failed
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:778) ~[na:1.8.0_161]
	at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:56) ~[na:1.8.0_161]
	at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224) ~[na:1.8.0_161]
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70) ~[na:1.8.0_161]
	at java.security.KeyStore.load(KeyStore.java:1445) ~[na:1.8.0_161]
	at org.apache.tomcat.util.net.SSLUtilBase.getStore(SSLUtilBase.java:139) ~[tomcat-embed-core-8.5.27.jar:8.5.27]
	at org.apache.tomcat.util.net.SSLHostConfig.getTruststore(SSLHostConfig.java:713) ~[tomcat-embed-core-8.5.27.jar:8.5.27]
	at org.apache.tomcat.util.net.jsse.JSSEUtil.getTrustManagers(JSSEUtil.java:300) [tomcat-embed-core-8.5.27.jar:8.5.27]
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:114) [tomcat-embed-core-8.5.27.jar:8.5.27]
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.initialiseSsl(AbstractJsseEndpoint.java:87) [tomcat-embed-core-8.5.27.jar:8.5.27]
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:225) [tomcat-embed-core-8.5.27.jar:8.5.27]
	at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:1150) [tomcat-embed-core-8.5.27.jar:8.5.27]
	at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:591) [tomcat-embed-core-8.5.27.jar:8.5.27]
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1018) [tomcat-embed-core-8.5.27.jar:8.5.27]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.5.27.jar:8.5.27]
	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:225) [tomcat-embed-core-8.5.27.jar:8.5.27]
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.addPreviouslyRemovedConnectors(TomcatEmbeddedServletContainer.java:250) [spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:193) [spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:297) [spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:145) [spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) [spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) [spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at com.clianz.vault.ssl.demo.DemoApplication.main(DemoApplication.java:35) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_161]
	at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:527) [spring-boot-maven-plugin-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]

2018-03-30 21:26:08.032  INFO 1013 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8080 (https)
2018-03-30 21:26:08.035  INFO 1013 --- [           main] c.clianz.vault.ssl.demo.DemoApplication  : Started DemoApplication in 3.262 seconds (JVM running for 6.372)

```

**Comment by icha024** [comment]
Update: Undertow and Jetty don't see this warning. Only Tomcat seem to be effected.

**Comment by mbhave** [comment]
This seems similar to #11391

**Comment by icha024** [comment]
@philwebb @mbhave Yes it seem related to #11391 and I've extended it to use the same mechanism for omitting trust-store password (first PR).

Both changes has been back-ported to 1.5.x branch (second PR).

**Comment by mbhave** [comment]
Marking as a duplicate in favor of PR #13088.
