### ISSUE TITLE
Multiple @ServletComponentScan annotated class may cause UnsupportedOperationException

### ISSUE THREAD

**Issue by vivimice** [spring-projects/spring-boot#12714]
# Description

When a project contains multiple `@ServletComponentScan` annotated class in classpath, and at least one annotation don't explicitly specify `basePackages` and `basePackageClass` attribute, the application MAY
fail on startup, caused by UnsupportedOperationException:

<pre>
java.lang.UnsupportedOperationException: null
	at java.util.AbstractCollection.add(AbstractCollection.java:262)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
	at org.springframework.boot.web.servlet.ServletComponentScanRegistrar.updatePostProcessor(ServletComponentScanRegistrar.java:62)
	at org.springframework.boot.web.servlet.ServletComponentScanRegistrar.registerBeanDefinitions(ServletComponentScanRegistrar.java:48)
	...
</pre>

# Reproduction

There is a single class application to reproduce this bug just for demostration.

<pre>
@SpringBootApplication
public class SpringBootTest1 {
    public static void main(String[] args) {
        SpringApplication.run(SpringBootTest1.class, args);
    }
    
    @ServletComponentScan
    public static class Config1 {
        
    }
    
    @ServletComponentScan
    public static class Config2 {
        
    }
}
</pre>

**Comment by philwebb** [comment]
Closing in favor of PR #12715
