### ISSUE TITLE
LoggingApplicationListenerTests.addLogFileProperty fails intermittently on Bamboo

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#12734]
```
java.lang.AssertionError: 
Expecting:
 <"2018-04-03 10:58:27.696 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@8c549a7 processing 0 keys, 0 updates
2018-04-03 10:58:27.696 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : updateable 0
2018-04-03 10:58:27.696 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : updates 0
2018-04-03 10:58:27.696 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@8c549a7 waiting on select
2018-04-03 10:58:27.696 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@8c549a7 woken up from select, 0/0 selected
2018-04-03 10:58:27.696 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@8c549a7 processing 0 keys, 0 updates
2018-04-03 10:58:27.696 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : updateable 0
2018-04-03 10:58:27.696 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : updates 0
2018-04-03 10:58:27.696 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@8c549a7 waiting on select
2018-04-03 10:58:27.696 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@8c549a7 woken up from select, 0/0 selected
2018-04-03 10:58:27.696 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@8c549a7 processing 0 keys, 0 updates
2018-04-03 10:58:27.696 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : updateable 0
2018-04-03 10:58:27.696 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : updates 0
2018-04-03 10:58:27.697 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@8c549a7 waiting on select
2018-04-03 10:58:27.697 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@8c549a7 woken up from select, 0/0 selected
2018-04-03 10:58:27.697 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@8c549a7 processing 0 keys, 0 updates
2018-04-03 10:58:27.697 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : updateable 0
2018-04-03 10:58:27.697 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : updates 0
2018-04-03 10:58:27.697 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@8c549a7 waiting on select
2018-04-03 10:58:27.697 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@8c549a7 woken up from select, 0/0 selected
2018-04-03 10:58:27.697 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@8c549a7 processing 0 keys, 0 updates
2018-04-03 10:58:27.697 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : updateable 0
2018-04-03 10:58:27.697 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : updates 0
2018-04-03 10:58:27.697 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@8c549a7 waiting on select
2018-04-03 10:58:27.697 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@8c549a7 woken up from select, 0/0 selected
2018-04-03 10:58:27.697 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@8c549a7 processing 0 keys, 0 updates
2018-04-03 10:58:27.697 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : updateable 0
2018-04-03 10:58:27.697 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : updates 0
2018-04-03 10:58:27.697 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@8c549a7 waiting on select
2018-04-03 10:58:27.698 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@8c549a7 woken up from select, 0/0 selected
2018-04-03 10:58:27.698 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@8c549a7 processing 0 keys, 0 updates
2018-04-03 10:58:27.698 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : updateable 0
2018-04-03 10:58:27.698 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : updates 0
2018-04-03 10:58:27.698 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@8c549a7 waiting on select
2018-04-03 10:58:27.698 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@8c549a7 woken up from select, 0/0 selected
2018-04-03 10:58:27.698 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@8c549a7 processing 0 keys, 0 updates
2018-04-03 10:58:27.698 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : updateable 0
2018-04-03 10:58:27.698 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : updates 0
2018-04-03 10:58:27.698 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@8c549a7 waiting on select
2018-04-03 10:58:27.698 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@8c549a7 woken up from select, 0/0 selected
2018-04-03 10:58:27.698 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@8c549a7 processing 0 keys, 0 updates
2018-04-03 10:58:27.698 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : updateable 0
2018-04-03 10:58:27.699 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@8c549a7 woken up from select, 0/0 selected
2018-04-03 10:58:27.699 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@8c549a7 processing 0 keys, 0 updates
2018-04-03 10:58:27.699 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : updateable 0
2018-04-03 10:58:27.699 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : updates 0
2018-04-03 10:58:27.699 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@8c549a7 waiting on select
2018-04-03 10:58:27.699 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@8c549a7 woken up from select, 0/0 selected
2018-04-03 10:58:27.699 DEBUG 13605 --- [p1376398022-202] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@8c549a7 processing 0 keys, 0 updates
target/foo.log [main] 13605 o.s.b.l.LoggingApplicationListenerTests: Hello world
 BOOTBOOT">
to start with:
 <"target/foo.log">

	at org.springframework.boot.logging.LoggingApplicationListenerTests.addLogFileProperty(LoggingApplicationListenerTests.java:206)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.springframework.boot.testutil.InternalOutputCapture$1.evaluate(InternalOutputCapture.java:60)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

It looks like an earlier test has left Jetty running and it's polluting the log.

**Comment by wilkinsona** [comment]
See #12735.

**Comment by wilkinsona** [comment]
It just failed again:

```
java.lang.AssertionError: 
Expecting:
 <"2018-04-04 12:59:09.381 DEBUG 1443 --- [p1460444157-158] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@4f113505 waiting on select
2018-04-04 12:59:09.381 DEBUG 1443 --- [p1460444157-158] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@4f113505 woken up from select, 0/0 selected
2018-04-04 12:59:09.381 DEBUG 1443 --- [p1460444157-158] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@4f113505 processing 0 keys, 0 updates
2018-04-04 12:59:09.381 DEBUG 1443 --- [p1460444157-158] org.eclipse.jetty.io.ManagedSelector     : updateable 0
2018-04-04 12:59:09.381 DEBUG 1443 --- [p1460444157-158] org.eclipse.jetty.io.ManagedSelector     : updates 0
2018-04-04 12:59:09.382 DEBUG 1443 --- [p1460444157-158] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@4f113505 waiting on select
2018-04-04 12:59:09.382 DEBUG 1443 --- [p1460444157-158] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@4f113505 woken up from select, 0/0 selected
2018-04-04 12:59:09.382 DEBUG 1443 --- [p1460444157-158] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@4f113505 processing 0 keys, 0 updates
2018-04-04 12:59:09.382 DEBUG 1443 --- [p1460444157-158] org.eclipse.jetty.io.ManagedSelector     : updateable 0
2018-04-04 12:59:09.382 DEBUG 1443 --- [p1460444157-158] org.eclipse.jetty.io.ManagedSelector     : updates 0
2018-04-04 12:59:09.382 DEBUG 1443 --- [p1460444157-158] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@4f113505 waiting on select
2018-04-04 12:59:09.382 DEBUG 1443 --- [p1460444157-158] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@4f113505 woken up from select, 0/0 selected
2018-04-04 12:59:09.383 DEBUG 1443 --- [p1460444157-158] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@4f113505 processing 0 keys, 0 updates
2018-04-04 12:59:09.383 DEBUG 1443 --- [p1460444157-158] org.eclipse.jetty.io.ManagedSelector     : updateable 0
2018-04-04 12:59:09.383 DEBUG 1443 --- [p1460444157-158] org.eclipse.jetty.io.ManagedSelector     : updates 0
2018-04-04 12:59:09.383 DEBUG 1443 --- [p1460444157-158] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@4f113505 waiting on select
2018-04-04 12:59:09.383 DEBUG 1443 --- [p1460444157-158] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@4f113505 woken up from select, 0/0 selected
2018-04-04 12:59:09.383 DEBUG 1443 --- [p1460444157-158] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@4f113505 processing 0 keys, 0 updates
2018-04-04 12:59:09.383 DEBUG 1443 --- [p1460444157-158] org.eclipse.jetty.io.ManagedSelector     : updateable 0
2018-04-04 12:59:09.384 DEBUG 1443 --- [p1460444157-158] org.eclipse.jetty.io.ManagedSelector     : updates 0
2018-04-04 12:59:09.384 DEBUG 1443 --- [p1460444157-158] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@4f113505 waiting on select
2018-04-04 12:59:09.384 DEBUG 1443 --- [p1460444157-158] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@4f113505 woken up from select, 0/0 selected
2018-04-04 12:59:09.384 DEBUG 1443 --- [p1460444157-158] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@4f113505 processing 0 keys, 0 updates
2018-04-04 12:59:09.384 DEBUG 1443 --- [p1460444157-158] org.eclipse.jetty.io.ManagedSelector     : updateable 0
2018-04-04 12:59:09.384 DEBUG 1443 --- [p1460444157-158] org.eclipse.jetty.io.ManagedSelector     : updates 0
2018-04-04 12:59:09.384 DEBUG 1443 --- [p1460444157-158] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@4f113505 waiting on select
2018-04-04 12:59:09.375 DEBUG 1443 --- [p1362912862-172] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@236c5187 processing 0 keys, 0 updates
2018-04-04 12:59:09.375 DEBUG 1443 --- [p1460444157-159] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@394c846e processing 0 keys, 0 updates
2018-04-04 12:59:09.405 DEBUG 1443 --- [p1460444157-158] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@4f113505 woken up from select, 0/0 selected
2018-04-04 12:59:09.406 DEBUG 1443 --- [p1460444157-158] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@4f113505 processing 0 keys, 0 updates
2018-04-04 12:59:09.406 DEBUG 1443 --- [p1460444157-158] org.eclipse.jetty.io.ManagedSelector     : updateable 0
2018-04-04 12:59:09.406 DEBUG 1443 --- [p1460444157-158] org.eclipse.jetty.io.ManagedSelector     : updates 0
2018-04-04 12:59:09.406 DEBUG 1443 --- [p1460444157-158] org.eclipse.jetty.io.ManagedSelector     : Selector sun.nio.ch.EPollSelectorImpl@4f113505 waiting on select
target/foo.log [main] 1443 o.s.b.l.LoggingApplicationListenerTests: Hello world
 BOOTBOOT">
to start with:
 <"target/foo.log">

	at org.springframework.boot.logging.LoggingApplicationListenerTests.addLogFileProperty(LoggingApplicationListenerTests.java:206)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.springframework.boot.testutil.InternalOutputCapture$1.evaluate(InternalOutputCapture.java:60)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```
