### ISSUE TITLE
DevTools stopped working on Java 6

### ISSUE THREAD

**Issue by imgx64** [spring-projects/spring-boot#12826]
Yes, I know Java 6 is long dead. But Spring Boot 1.5.x is supposed to still support it.

Commit 1468585 broke DevTools on Java 6 because `getClassLoadingLock` was [added in Java 7](https://docs.oracle.com/javase/7/docs/api/java/lang/ClassLoader.html#getClassLoadingLock(java.lang.String)).

```
Exception in thread "restartedMain" java.lang.NoSuchMethodError: org.springframework.boot.devtools.restart.classloader.RestartClassLoader.getClassLoadingLock(Ljava/lang/String;)Ljava/lang/Object;
	at org.springframework.boot.devtools.restart.classloader.RestartClassLoader.loadClass(RestartClassLoader.java:145)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:47)
```

This affects 1.5.11.RELEASE and 1.5.12.RELEASE.

**Comment by snicoll** [comment]
As part of this, we need to figure out why animal sniffer didn't catch this.

**Comment by wilkinsona** [comment]
Animal Sniffer didn't catch it due to a bug which I have reported [here](https://github.com/mojohaus/animal-sniffer/issues/49).
