### ISSUE TITLE
WebClient threads are not automatically shut down

### ISSUE THREAD

**Issue by rburgst** [spring-projects/spring-boot#12884]
It seems that an auto-configured `WebClient` is not automatically shut down when the application finishes.

See the following repo

https://github.com/rburgst/webclient-thread-hang-example

more specifically 
https://github.com/rburgst/webclient-thread-hang-example/blob/master/src/main/kotlin/com/example/demo/WebclientThreadExampleApplication.kt#L46

When running the app from IntelliJ the application main method exits but the `reactor-http-nio-X` threads are still running.

I would expect them to be shut down automatically.

**Comment by rburgst** [comment]
it seems that the following thread is the culprit:
```
"server@6396" prio=5 tid=0x1a nid=NA waiting
  java.lang.Thread.State: WAITING
	  at sun.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	  at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	  at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:81)
	  at reactor.core.publisher.Mono.block(Mono.java:1175)
	  at org.springframework.boot.web.embedded.netty.NettyWebServer$1.run(NettyWebServer.java:111)

```

**Comment by rburgst** [comment]
Ok, found it myself, the trick is to set the WebApplicationType to NONE, unfortunately this is not easy to find.

```
fun main(args: Array<String>) {
    runApplication<WebclientThreadExampleApplication>(*args) {
        webApplicationType = WebApplicationType.NONE
    }
}
```

**Comment by snicoll** [comment]
@rburgst You have a web app running on port 8080 and if that's not what you want, then you need to disable that. A section [was recently added in the doc](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#howto-disable-web-server)
