### ISSUE TITLE
spring-boot-gradle-plugin (2.0.0.RELEASE) somehow breaks compatibility with jruby-gradle-plugin

### ISSUE THREAD

**Issue by ARnikev** [spring-projects/spring-boot#12897]
Hi!
I'm developing service using spring boot and use asciidoctor-gradle-plugin + jruby-gradle-plugin for my project docs generation. After migration of my project from spring boot 1.5.6.RELEASE to 2.0.0.RELEASE version i've run into a problem that 'asciidoctor' task, that assemble docs for my project, started to fail executing dependent 'jrubyPrepare' task with following error:

```
Execution failed for task ":jrubyPrepare".
 Could not resolve all files for configuration ":gems".
    java.lang.NullPointerException (no error message)
```

Considering the log message, it fails while trying to resolve gems dependencies:

```
Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':gems'.
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.rethrowFailure(DefaultConfiguration.java:915)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1600(DefaultConfiguration.java:116)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:889)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getFiles(DefaultConfiguration.java:401)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getFiles(Unknown Source)
        at org.gradle.api.internal.file.CompositeFileCollection.getFiles(CompositeFileCollection.java:56)
        at org.gradle.api.internal.file.AbstractFileCollection.iterator(AbstractFileCollection.java:68)
        at com.github.jrubygradle.GemUtils.getGems(GemUtils.groovy:33)
        at com.github.jrubygradle.GemUtils$getGems.call(Unknown Source)
        at com.github.jrubygradle.JRubyPrepare.gemsAsFileCollection(JRubyPrepare.groovy:36)
        at com.github.jrubygradle.JRubyPrepare.copy(JRubyPrepare.groovy:69)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:788)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:755)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
        ... 104 more
```

Why do i post this issue here? Because if i comment out applying of 'org.springframework.boot' plugin in my build script - everything works fine. So, it seems like 'spring-boot-gradle-plugin' plugin somehow breaks 'jruby-gradle-plugin'.

I've made example project so you can reproduce this exception - [example](https://github.com/ARnikev/spring-boot-2-asciidoctor). You can reproduce the issue running such task:
`./gradlew clean asciidoctor`
If you change spring boot version to 1.5.6.RELEASE or comment out applying of 'org.springframework.boot' plugin - everything works fine.

I've also reported this issue to 'jruby-gradle-plugin' repository - [issue](https://github.com/jruby-gradle/jruby-gradle-plugin/issues/326).

It would be great if you gave me some idea about what could be the problem. Thank you.

**Comment by snicoll** [comment]
A command on master gives me this

```
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'srping-boot-2-with-docs'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find com.github.jruby-gradle:jruby-gradle-plugin:2.0.5.
     Searched in the following locations:
         https://jcenter.bintray.com/com/github/jruby-gradle/jruby-gradle-plugin/2.0.5/jruby-gradle-plugin-2.0.5.pom
         https://jcenter.bintray.com/com/github/jruby-gradle/jruby-gradle-plugin/2.0.5/jruby-gradle-plugin-2.0.5.jar
         file:/Users/snicoll/.m2/repository/com/github/jruby-gradle/jruby-gradle-plugin/2.0.5/jruby-gradle-plugin-2.0.5.pom
         file:/Users/snicoll/.m2/repository/com/github/jruby-gradle/jruby-gradle-plugin/2.0.5/jruby-gradle-plugin-2.0.5.jar
     Required by:
         project :
```

**Comment by ARnikev** [comment]
@snicoll yeah, sorry for that, i've forgotten to remove mavenLocal dependency of jruby plugin that i used for debugging. Please pull from master and try one more time.

**Comment by lavcraft** [comment]
I have a similar problem with spring-boot 2.0.1.RELEASE

**Comment by gorelikov** [comment]
It's critical problem for me as well

**Comment by wilkinsona** [comment]
I think this needs to be raised against Gradle as that's where the `NullPointerException` is occurring:

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':jrubyPrepare'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:623)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:578)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':gems'.
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.rethrowFailure(DefaultConfiguration.java:915)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1600(DefaultConfiguration.java:116)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:889)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getFiles(DefaultConfiguration.java:401)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getFiles(Unknown Source)
        at org.gradle.api.internal.file.AbstractFileCollection.iterator(AbstractFileCollection.java:68)
        at org.gradle.util.CollectionUtils.filter(CollectionUtils.java:150)
        at org.gradle.api.internal.file.AbstractFileCollection$3.getFiles(AbstractFileCollection.java:223)
        at org.gradle.api.internal.file.AbstractFileCollection.iterator(AbstractFileCollection.java:68)
        at org.gradle.util.CollectionUtils.filter(CollectionUtils.java:150)
        at org.gradle.api.internal.file.AbstractFileCollection$3.getFiles(AbstractFileCollection.java:223)
        at org.gradle.api.internal.file.CompositeFileCollection.getFiles(CompositeFileCollection.java:56)
        at com.github.jrubygradle.GemUtils.extractGems(GemUtils.groovy:62)
        at com.github.jrubygradle.GemUtils$extractGems$0.call(Unknown Source)
        at com.github.jrubygradle.JRubyPrepare.copy(JRubyPrepare.groovy:54)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:788)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:755)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
        ... 30 more
Caused by: java.lang.NullPointerException
        at org.gradle.api.internal.artifacts.ivyservice.DefaultConfigurationResolver.resolveArtifacts(DefaultConfigurationResolver.java:160)
        at org.gradle.api.internal.artifacts.ivyservice.ShortCircuitEmptyConfigurationResolver.resolveArtifacts(ShortCircuitEmptyConfigurationResolver.java:91)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.resolveArtifacts(ErrorHandlingConfigurationResolver.java:81)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveArtifactsIfRequired(DefaultConfiguration.java:536)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:459)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1700(DefaultConfiguration.java:116)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getSelectedArtifacts(DefaultConfiguration.java:898)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:886)
        ... 55 more
```

We can re-open this issue if it turns out that the Spring Boot plugin is doing something wrong.

**Comment by ARnikev** [comment]
Okay, i'll report this issue to Gradle also. Thank you.
