### ISSUE TITLE
Spring WebFlux with Undertow Serves Resources With Blocking IO

### ISSUE THREAD

**Issue by Brandon-Godwin** [spring-projects/spring-boot#12893]
## Spring Boot Version
Tested with `2.0.1.RELEASE` and the latest commit on master c43eb898238fd334c.

## Issue
When using Spring WebFlux with Undertow, serving a sufficiently large static resource will cause Undertow to throw the following exception and only partially serve the file:

```
2018-04-17 21:55:59.082 ERROR 21768 --- [   XNIO-1 I/O-4] o.s.w.s.adapter.HttpWebHandlerAdapter    : Unhandled failure: UT000094: Blocking await method called from IO thread. Blocking IO must be dispatched to a worker thread or deadlocks will result., response already set (status=null)
2018-04-17 21:55:59.089 ERROR 21768 --- [   XNIO-1 I/O-4] o.s.h.s.r.UndertowHttpHandlerAdapter     : Handling completed with error

java.io.IOException: UT000094: Blocking await method called from IO thread. Blocking IO must be dispatched to a worker thread or deadlocks will result.
        at io.undertow.server.HttpServerExchange$WriteDispatchChannel.awaitWritable(HttpServerExchange.java:2026) ~[undertow-core-1.4.24.Final.jar:1.4.24.Final]
        at org.xnio.channels.Channels.transferBlocking(Channels.java:514) ~[xnio-api-3.3.8.Final.jar:3.3.8.Final]
        at org.springframework.http.server.reactive.UndertowServerHttpResponse.lambda$null$1(UndertowServerHttpResponse.java:114) ~[spring-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.Mono.subscribe(Mono.java:3080) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.FluxConcatIterable$ConcatIterableSubscriber.onComplete(FluxConcatIterable.java:141) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.FluxConcatIterable.subscribe(FluxConcatIterable.java:60) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoIgnoreElements.subscribe(MonoIgnoreElements.java:37) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.Mono.subscribe(Mono.java:3080) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:172) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:53) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1073) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:398) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:210) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:128) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:61) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.FluxConcatMap.subscribe(FluxConcatMap.java:121) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoNext.subscribe(MonoNext.java:40) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:60) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoSwitchIfEmpty.subscribe(MonoSwitchIfEmpty.java:44) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:60) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.Mono.subscribe(Mono.java:3080) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:167) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:271) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:803) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:115) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:1630) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:156) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:1444) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:1318) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoMapFuseable.subscribe(MonoMapFuseable.java:59) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.Mono.subscribe(Mono.java:3080) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:418) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:210) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:128) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:61) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.FluxConcatMap.subscribe(FluxConcatMap.java:121) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoNext.subscribe(MonoNext.java:40) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoSwitchIfEmpty.subscribe(MonoSwitchIfEmpty.java:44) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:60) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:60) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoPeekTerminal.subscribe(MonoPeekTerminal.java:61) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1073) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoZip$ZipCoordinator.signal(MonoZip.java:241) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoZip$ZipInner.onNext(MonoZip.java:323) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:1630) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoZip$ZipInner.onSubscribe(MonoZip.java:312) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.Mono.subscribe(Mono.java:3080) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoZip.subscribe(MonoZip.java:128) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:60) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoPeekTerminal.subscribe(MonoPeekTerminal.java:61) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoPeekFuseable.subscribe(MonoPeekFuseable.java:74) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.Mono.subscribe(Mono.java:3080) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:167) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at reactor.core.publisher.Mono.subscribe(Mono.java:3080) [reactor-core-3.1.6.RELEASE.jar:3.1.6.RELEASE]
        at org.springframework.http.server.reactive.UndertowHttpHandlerAdapter.handleRequest(UndertowHttpHandlerAdapter.java:76) [spring-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:336) [undertow-core-1.4.24.Final.jar:1.4.24.Final]
        at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:255) [undertow-core-1.4.24.Final.jar:1.4.24.Final]
        at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136) [undertow-core-1.4.24.Final.jar:1.4.24.Final]
        at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:147) [undertow-core-1.4.24.Final.jar:1.4.24.Final]
        at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:93) [undertow-core-1.4.24.Final.jar:1.4.24.Final]
        at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:52) [undertow-core-1.4.24.Final.jar:1.4.24.Final]
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) [xnio-api-3.3.8.Final.jar:3.3.8.Final]
        at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291) [xnio-api-3.3.8.Final.jar:3.3.8.Final]
        at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286) [xnio-api-3.3.8.Final.jar:3.3.8.Final]
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) [xnio-api-3.3.8.Final.jar:3.3.8.Final]
        at org.xnio.nio.QueuedNioTcpServer$1.run(QueuedNioTcpServer.java:129) [xnio-nio-3.3.8.Final.jar:3.3.8.Final]
        at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:582) [xnio-nio-3.3.8.Final.jar:3.3.8.Final]
        at org.xnio.nio.WorkerThread.run(WorkerThread.java:466) [xnio-nio-3.3.8.Final.jar:3.3.8.Final]
```
It appears that `org.springframework.http.server.reactive.UndertowServerHttpResponse.writeWith` is calling `org.xnio.channels.Channels.transferBlocking`, which is blocking the Undertow IO thread.

## Reproduction Steps
* Using the `spring-boot-sample-webflux` project, create a `public` directory in `src/main/resources/` and place [this picture](https://user-images.githubusercontent.com/389562/38908186-17f12ffe-428d-11e8-8f82-da9d74a8dbde.jpg) in there.
* Add the following dependency to the pom file:
  ```
  <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-undertow</artifactId>
  </dependency>
  ```
* Run the project with `mvn spring-boot:run` and navigate to http://localhost:8080/test.jpg.

**Comment by snicoll** [comment]
@Brandon-Godwin thanks for the details but there's no indication here that there an issue in Spring Boot. Could you please report this against [the Spring Framework issue tracker](https://jira.spring.io/browse/SPR)?

When you do, I'd appreciate if you could share a zip of the actual sample (or a reference to a repository). The instructions are simple enough to provide something that will help us to quickly reproduce the issue.
