### ISSUE TITLE
RabbitMQ的CachingConnectionFactory添加@RefreshScope注解会报错

### ISSUE THREAD

**Issue by marga8080** [spring-projects/spring-boot#12908]
项目中需要使用Spring Cloud Config刷新RabbitMQ的配置，但是加上`@RefreshScope`后启动工程会报错

```JAVA
@Bean
@RefreshScope
public ConnectionFactory connectionFactory(RabbitProperties config) throws Exception {
  RabbitConnectionFactoryBean factory = new RabbitConnectionFactoryBean();
  if (config.determineHost() != null) {
    factory.setHost(config.determineHost());
  }
  factory.setPort(config.determinePort());
  if (config.determineUsername() != null) {
    factory.setUsername(config.determineUsername());
  }
  if (config.determinePassword() != null) {
    factory.setPassword(config.determinePassword());
  }
  if (config.determineVirtualHost() != null) {
    factory.setVirtualHost(config.determineVirtualHost());
  }
  if (config.getRequestedHeartbeat() != null) {
    factory.setRequestedHeartbeat(config.getRequestedHeartbeat());
  }
  RabbitProperties.Ssl ssl = config.getSsl();
  if (ssl.isEnabled()) {
    factory.setUseSSL(true);
    if (ssl.getAlgorithm() != null) {
      factory.setSslAlgorithm(ssl.getAlgorithm());
    }
    factory.setKeyStore(ssl.getKeyStore());
    factory.setKeyStorePassphrase(ssl.getKeyStorePassword());
    factory.setTrustStore(ssl.getTrustStore());
    factory.setTrustStorePassphrase(ssl.getTrustStorePassword());
  }
  if (config.getConnectionTimeout() != null) {
    factory.setConnectionTimeout(config.getConnectionTimeout());
  }
  factory.afterPropertiesSet();
  CachingConnectionFactory connectionFactory = new CachingConnectionFactory(factory.getObject());
  connectionFactory.setAddresses(config.determineAddresses());
  connectionFactory.setPublisherConfirms(config.isPublisherConfirms());
  connectionFactory.setPublisherReturns(config.isPublisherReturns());
  if (config.getCache().getChannel().getSize() != null) {
    connectionFactory
      .setChannelCacheSize(config.getCache().getChannel().getSize());
  }
  if (config.getCache().getConnection().getMode() != null) {
    connectionFactory
      .setCacheMode(config.getCache().getConnection().getMode());
  }
  if (config.getCache().getConnection().getSize() != null) {
    connectionFactory.setConnectionCacheSize(
      config.getCache().getConnection().getSize());
  }
  if (config.getCache().getChannel().getCheckoutTimeout() != null) {
    connectionFactory.setChannelCheckoutTimeout(
      config.getCache().getChannel().getCheckoutTimeout());
  }
  return connectionFactory;
}
```

报错信息如下：

```
java.lang.NullPointerException: null
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createConnection(CachingConnectionFactory.java:570) ~[spring-rabbit-1.7.4.RELEASE.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333) ~[spring-aop-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) ~[spring-aop-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133) ~[spring-aop-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121) ~[spring-aop-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) ~[spring-aop-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at com.sun.proxy.$Proxy124.createConnection(Unknown Source) ~[na:na]
	at org.springframework.amqp.rabbit.core.RabbitTemplate.doExecute(RabbitTemplate.java:1430) ~[spring-rabbit-1.7.4.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:1411) ~[spring-rabbit-1.7.4.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:1387) ~[spring-rabbit-1.7.4.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.core.RabbitAdmin.getQueueProperties(RabbitAdmin.java:336) ~[spring-rabbit-1.7.4.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.redeclareElementsIfNecessary(SimpleMessageListenerContainer.java:1171) ~[spring-rabbit-1.7.4.RELEASE.jar:na]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1422) [spring-rabbit-1.7.4.RELEASE.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
```

**Comment by marga8080** [comment]
spring boot version is 1.5.7.RELEASE

**Comment by snicoll** [comment]
@marga8080 you are configuring the connection yourself (not using Spring Boot's auto-configuration) and you're using `@RefreshScope` that is a concept in Spring Cloud. 

Google translates tells me that:

> The project needs to use Spring Cloud Config to refresh the RabbitMQ configuration, but launching the project with @RefreshScope will complain

It's not obvious why it fails, neither why you think that `@RefreshScope` causes the problem. The issue tracker for `@RefreshScope` is [here](https://github.com/spring-cloud/spring-cloud-commons/issues). Before creating an issue there, please consider creating a minimal sample that the Spring Cloud team can use to reproduce the problem.
