### ISSUE TITLE
Java 9 / Java 10 Module Mode: Tests failing due to initializationError: java.lang.NoClassDefFoundError: Could not initialize class org.springframework.test.context.junit4.SpringRunner

### ISSUE THREAD

**Issue by testphreak** [spring-projects/spring-boot#12910]
**Environment**

Spring Boot: 2.0.1.RELEASE
Java: "10" 2018-03-20 (Vendor: Oracle Corporation)
Maven: 3.5.3
maven-compiler-plugin: 3.7.0
maven-surefire-plugin: 2.21.0
macOS: 10.12.6

**Issue**

Greetings Spring Boot team! Congratulations on the recent release of Spring Boot 2! 

Recently I decided to update my Spring Boot 1.5.9 / Java 8 project to Spring Boot 2 / Java 10. While I was able to build, package and run my project in `ClassPath mode`, I wanted to take the project a step further and run in `Module mode (JPMS)`. 

This is where I am running into an issue during Maven test execution. My tests start failing in the `test` phase.

Relevant stack trace:

```java
[INFO] --- maven-surefire-plugin:2.21.0:test (default-test) @ turbo ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.axiom.turbo.UserControllerIntegrationTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 s <<< FAILURE! - in com.axiom.turbo.UserControllerIntegrationTest
[ERROR] initializationError(com.axiom.turbo.UserControllerIntegrationTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.springframework.test.context.junit4.SpringRunner
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:362)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
```

Pasting relevant section from my pom.xml (Some of the arguments/options maybe unnecessary, trying different solutions to fix the issue)

```xml
<plugin>
	<artifactId>maven-compiler-plugin</artifactId>
	<version>3.7.0</version>
	<configuration>
		<source>10</source>
		<target>10</target>
		<release>10</release>
		<compilerArgs>
			<arg>--add-modules=java.xml.bind,java.base</arg>
		</compilerArgs>
	</configuration>
	<dependencies>
		<dependency>
			<groupId>org.ow2.asm</groupId>
			<artifactId>asm</artifactId>
			<version>6.1.1</version>
		</dependency>
	</dependencies>
</plugin>

<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-surefire-plugin</artifactId>
	<version>2.21.0</version>
	<configuration>
		<trimStackTrace>false</trimStackTrace>
		<argLine>
			--add-modules=java.xml.bind
			--illegal-access=deny
			--add-opens java.base/java.lang=ALL-UNNAMED
			--add-reads java.base=ALL-UNNAMED
		</argLine>
	</configuration>
	<dependencies>
		<dependency>
			<groupId>org.ow2.asm</groupId>
			<artifactId>asm</artifactId>
			<version>6.1.1</version>
		</dependency>
	</dependencies>
</plugin>
```

My `jvm.config` under the `.mvn` directory of my project:

```
--add-modules java.xml.bind
--add-opens java.base/java.lang=ALL-UNNAMED
--add-reads java.base=ALL-UNNAMED
--illegal-access=deny
```

The test class itself is pretty ordinary.

```java
package com.axiom.turbo;

import com.axiom.turbo.model.User;
import com.axiom.turbo.repository.UserRepository;
import org.junit.After;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.boot.web.server.LocalServerPort;
import org.springframework.http.ResponseEntity;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.web.util.UriComponentsBuilder;

import java.net.URI;

/**
 * Created by testphreak on 10/11/17
 */
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT, classes = Turbo.class)
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@ActiveProfiles("test")
public class UserControllerIntegrationTest {

    @Autowired
    private TestRestTemplate testRestTemplate;

    @LocalServerPort
    private int localServerPort;

    @Autowired
    protected UserRepository userRepository;

    public User setUpUser() {
        User user = new User();
        user.setAccountId("63543454534");
        user.setUserId("SDFSDFSF23423DFSDFD");
        user.setUserName("sdsfdsdf");
        user.setKey("5oDvN8n0UtUO5cNfetmvwQ");
        return userRepository.saveAndFlush(user);
    }

    @After
    public void resetDb() {
        userRepository.deleteAll();
    }

    @Test
    public void getUserTest() {
        User user = setUpUser();
        String url = "http://localhost:" + this.localServerPort;
        URI uri = UriComponentsBuilder.fromHttpUrl(url).path("/abc/api/users")
                .queryParam("userId", user.getUserId()).build().toUri();
        ResponseEntity<String> response = this.testRestTemplate.getForEntity(uri, String.class);
        Assert.assertTrue(response.getBody().contains(user.getUserId()));
    }
}
```

My `module-info.java`:

```java
/**
 * Created by testphreak on 4/17/18
 */
module com.axiom.turbo {
    requires spring.data.jpa;
    requires spring.context;
    requires spring.tx;
    requires com.fasterxml.jackson.annotation;
    requires hibernate.core;
    requires spring.data.commons;
    requires hibernate.jpa;
    requires java.validation;
    requires org.apache.logging.log4j;
    requires spring.beans;
    requires spring.webmvc;
    requires spring.web;
    requires spring.boot;
    requires spring.boot.autoconfigure;
}
```

I hope this information is good enough. I have tried a few solutions the last couple of days, but have run into a dead end. Your feedback is greatly appreciated. If you feel the issue does not belong here please point me to the right project. Thanks in advance!

**Comment by snicoll** [comment]
Thanks for the kinds words and the details @testphreak but, looking at the stacktrace, it doesn't belong here indeed. I am not sure that creating an issue in the Spring Framework tracker is going to be any better. I don't have an immediate idea for your question but, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question on StackOverflow (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by testphreak** [comment]
@snicoll, I have a temporary workaround for the issue where the tests get executed by SureFire and the build succeeds when it's `forkCount` is set to 0 (by default it's 1). I am not sure where the issue is. It could be one of:

1. SureFire (at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:362))
2. JUnit (tried both 4 and 5) (at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104))
3. Spring (Could not initialize class org.springframework.test.context.junit4.SpringRunner)

I have posted the question on [StackOverflow](https://stackoverflow.com/questions/49924515/noclassdeffounderror-tests-fail-during-maven-test-phase-when-surefire-forkcount). It appears that there was a similar [question](https://stackoverflow.com/questions/48311898/springjunit4classrunner-broken-in-spring5) posted back in January that still isn't resolved.
