### ISSUE TITLE
Load static resource jars with paths containing plus symbol

### ISSUE THREAD

**Issue by ShawnTuatara** [spring-projects/spring-boot#12942]
From: https://github.com/spring-projects/spring-boot/pull/11991#issuecomment-382583667

With the latest changes on the `AbstractEmbeddedServletContainerFactory` there is a knock-on issue with paths that contain the `+` symbol. This symbol gets converted to a blank space instead of being kept as a `+`. This is due to the fact that `+` is an alternate form of `%20` so when it gets decoded it turns into a space.

For my team's specific use case we ran into the problem as we are using SemVer (https://semver.org/) and are adding build metadata (https://semver.org/#spec-item-10) to the artifact when doing incremental builds. In the end the artifact will be something like `demo-dependency-1.0.0+buildmeta.jar`.

```
2018-04-22 13:31:21.443  WARN 793064 --- [ost-startStop-1] .t.TomcatEmbeddedServletContainerFactory : Unable to open jar '\.m2\repository\com\example\demo-dependency\1.0.0 buildmeta\demo-dependency-1.0.0 buildmeta.jar' to determine if it contains static resources

java.io.FileNotFoundException: \.m2\repository\com\example\demo-dependency\1.0.0 buildmeta\demo-dependency-1.0.0 buildmeta.jar (The system cannot find the path specified)
        at java.util.zip.ZipFile.open(Native Method) ~[na:1.8.0_151]
        at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[na:1.8.0_151]
        at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[na:1.8.0_151]
        at java.util.jar.JarFile.<init>(JarFile.java:166) ~[na:1.8.0_151]
        at java.util.jar.JarFile.<init>(JarFile.java:130) ~[na:1.8.0_151]
        at org.springframework.boot.context.embedded.AbstractEmbeddedServletContainerFactory.isResourcesJar(AbstractEmbeddedServletContainerFactory.java:154) [spring-boot-1.5.12.RELEASE.jar:1.5.12.RELEASE]
        at org.springframework.boot.context.embedded.AbstractEmbeddedServletContainerFactory.isStaticResourceJar(AbstractEmbeddedServletContainerFactory.java:115) [spring-boot-1.5.12.RELEASE.jar:1.5.12.RELEASE]
        at org.springframework.boot.context.embedded.AbstractEmbeddedServletContainerFactory.getUrlsOfJarsWithMetaInfResources(AbstractEmbeddedServletContainerFactory.java:101) [spring-boot-1.5.12.RELEASE.jar:1.5.12.RELEASE]
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.access$100(TomcatEmbeddedServletContainerFactory.java:99) [spring-boot-1.5.12.RELEASE.jar:1.5.12.RELEASE]
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory$1.lifecycleEvent(TomcatEmbeddedServletContainerFactory.java:228) [spring-boot-1.5.12.RELEASE.jar:1.5.12.RELEASE]
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94) [tomcat-embed-core-8.5.29.jar:8.5.29]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5113) [tomcat-embed-core-8.5.29.jar:8.5.29]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.5.29.jar:8.5.29]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1421) [tomcat-embed-core-8.5.29.jar:8.5.29]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1411) [tomcat-embed-core-8.5.29.jar:8.5.29]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
```

https://github.com/ShawnTuatara/spring-boot-issue-12942

Note: For the demo dependency I had to explicitly set the `<version>` but in our build pipeline that version is set while going through the pipeline.

**Comment by wilkinsona** [comment]
Thanks for the report and sample project, @ShawnTuatara. The fix will be available in 1.5.13 snapshots once [this build](https://build.spring.io/browse/BOOT-PUB7-1152) has finished. When it has, it'd be great if you could try 1.5.13.BUILD-SNAPSHOT available from https://repo.spring.io/snapshot and confirm that the problem's been fixed in your application as well as in the sample.
