### ISSUE TITLE
Exception when running as systemd service causes SSL handshake error 525

### ISSUE THREAD

**Issue by SnuK87** [spring-projects/spring-boot#13004]
**Problem:**
When I run my Spring Boot application as systemd service I get an exception on startup and the SSL handshake fails (error 525). 
If I run the application using `java -jar ...` then it's working well so I assume that the error must be caused by the start script of the `spring-boot-maven-plugin`.

**Exception shown:**
```
java.lang.IllegalAccessException: class org.apache.tomcat.util.buf.ByteBufferUtils cannot access class jdk.internal.ref.Cleaner (in module java.base) because module java.base does not export jdk.internal.ref to unnamed module @14d7c1f2
	at sun.reflect.Reflection.throwIllegalAccessException(java.base@9-internal/Reflection.java:411) ~[na:na]
	at sun.reflect.Reflection.throwIllegalAccessException(java.base@9-internal/Reflection.java:402) ~[na:na]
	at sun.reflect.Reflection.ensureMemberAccess(java.base@9-internal/Reflection.java:99) ~[na:na]
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(java.base@9-internal/AccessibleObject.java:355) ~[na:na]
	at java.lang.reflect.AccessibleObject.checkAccess(java.base@9-internal/AccessibleObject.java:347) ~[na:na]
	at java.lang.reflect.Method.invoke(java.base@9-internal/Method.java:525) ~[na:na]
	at org.apache.tomcat.util.buf.ByteBufferUtils.<clinit>(ByteBufferUtils.java:67) ~[tomcat-embed-core-8.5.29.jar!/:8.5.29]
	at org.apache.tomcat.util.net.SocketBufferHandler.expand(SocketBufferHandler.java:155) [tomcat-embed-core-8.5.29.jar!/:8.5.29]
	at org.apache.tomcat.util.net.SecureNioChannel.processSNI(SecureNioChannel.java:334) [tomcat-embed-core-8.5.29.jar!/:8.5.29]
	at org.apache.tomcat.util.net.SecureNioChannel.handshake(SecureNioChannel.java:175) [tomcat-embed-core-8.5.29.jar!/:8.5.29]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1436) [tomcat-embed-core-8.5.29.jar!/:8.5.29]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.29.jar!/:8.5.29]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9-internal/ThreadPoolExecutor.java:1158) [na:na]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9-internal/ThreadPoolExecutor.java:632) [na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.29.jar!/:8.5.29]
	at java.lang.Thread.run(java.base@9-internal/Thread.java:804) [na:na]
```
**Environment:**
Spring Boot version: 2.0.1.RELEASE
JDK version: OpenJDK Runtime Environment (build 9.0.4+11)
OS: Ubuntu 16.04

I'm not sure if it's a bug or just some missing customization of the start script but I couldn't find  similar questions on SO.

**Comment by wilkinsona** [comment]
I think that exception is benign, although it is surprising. It looks like Tomcat has failed to identify that it's running on Java 9. Nonetheless, it should just log it as a warning and then carry on.

> If I run the application using java -jar ... then it's working well so I assume that the error must be caused by the start script

Ultimately, the start script just calls `java -jar`.  It could be a problem with the script, but it could also be a problem with your environment. For example, you could have a configuration file in the wrong place so it's only found in one situation and not the other. You could examine the command line that was used in each case to see if there are any differences. It's also worth checking if the two are using the same working directory.

If this doesn't help, then we're going to need some more information. The ideal would be a minimal sample that reproduces the problem.
