### ISSUE TITLE
Yaml parsing exception handling

### ISSUE THREAD

**Issue by cebaa** [spring-projects/spring-boot#1309]
In `application.yaml` I have this:

```
spring.profiles.active: ${profiles}
```

If I run this without specifying a profile, I get the following exception:

```
java.util.regex.PatternSyntaxException: Illegal repetition near index 0
${profiles}
^
	at java.util.regex.Pattern.error(Pattern.java:1924)
	at java.util.regex.Pattern.closure(Pattern.java:3104)
	at java.util.regex.Pattern.sequence(Pattern.java:2101)
	at java.util.regex.Pattern.expr(Pattern.java:1964)
	at java.util.regex.Pattern.compile(Pattern.java:1665)
	at java.util.regex.Pattern.<init>(Pattern.java:1337)
	at java.util.regex.Pattern.compile(Pattern.java:1022)
	at java.util.regex.Pattern.matches(Pattern.java:1128)
	at java.lang.String.matches(String.java:2063)
	at org.springframework.boot.yaml.ArrayDocumentMatcher.matches(ArrayDocumentMatcher.java:54)
	at org.springframework.boot.yaml.SpringProfileDocumentMatcher.matches(SpringProfileDocumentMatcher.java:62)
	at org.springframework.boot.yaml.YamlProcessor.process(YamlProcessor.java:213)
	at org.springframework.boot.yaml.YamlProcessor.process(YamlProcessor.java:141)
	at org.springframework.boot.yaml.YamlProcessor.process(YamlProcessor.java:127)
	at org.springframework.boot.yaml.YamlPropertiesFactoryBean.getObject(YamlPropertiesFactoryBean.java:80)
	at org.springframework.boot.env.YamlPropertySourceLoader.load(YamlPropertySourceLoader.java:56)
	at org.springframework.boot.env.PropertySourcesLoader.load(PropertySourcesLoader.java:126)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.loadIntoGroup(ConfigFileApplicationListener.java:360)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:349)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:317)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.addPropertySources(ConfigFileApplicationListener.java:155)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:138)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:131)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:120)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:98)
	at org.springframework.boot.context.event.EventPublishingRunListener.publishEvent(EventPublishingRunListener.java:100)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:59)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:284)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:952)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:941)
```

Probably worth adding a custom exception here, if possible carrying more details, it's rather confusing this way.

Related to [this issue](https://github.com/spring-projects/spring-boot/issues/1301).

**Comment by btiernay** [comment]
Perhaps `YamlProcessor` could throw an exception that a dedicated `FailureAnalyzer` could catch?

**Comment by wilkinsona** [comment]
As far as I can tell, the YAML in the original report is insufficient to reproduce the problem. You need something like this:

```yaml
spring.profiles.active: ${profiles}
---
spring.profiles: foo
```

I don't understand why we're interpreting the values of `spring.profiles.active` as regular expressions. Spring Framework doesn't support regular expression-based profile activation so it leads to a weird imbalance where profile-specific properties in a YAML file are available, but profile-specific beans are not.

This YAML file:

```yaml
spring.profiles.active: '[a-z]+'
---
spring.profiles: abc
foo: bar
---
spring.profiles: def
bar: baz
```

And this application:

```java
package com.example;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Profile;

@EnableAutoConfiguration
@Configuration
@ComponentScan
public class Gh1309Application {

	public static void main(String[] args) {
		ConfigurableApplicationContext context = SpringApplication.run(Gh1309Application.class, args);
		System.out.println(context.getEnvironment().getProperty("foo"));
		System.out.println(context.getEnvironment().getProperty("bar"));
		System.out.println(context.getBean("baz"));
	}

	@Bean
	@Profile("abc")
	public String baz() {
		return "bloop";
	}

}
```

Produces this output:

```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                        

2016-08-30 10:35:12.701  INFO 15142 --- [           main] com.example.Gh1309Application            : Starting Gh1309Application on aw-rmbp.home with PID 15142 (/Users/awilkinson/dev/workspaces/spring/spring-boot/master/gh-1309/target/classes started by awilkinson in /Users/awilkinson/dev/workspaces/spring/spring-boot/master/gh-1309)
2016-08-30 10:35:12.704  INFO 15142 --- [           main] com.example.Gh1309Application            : The following profiles are active: [a-z]+
2016-08-30 10:35:12.739  INFO 15142 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@7e9a5fbe: startup date [Tue Aug 30 10:35:12 BST 2016]; root of context hierarchy
2016-08-30 10:35:13.242  INFO 15142 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2016-08-30 10:35:13.252  INFO 15142 --- [           main] com.example.Gh1309Application            : Started Gh1309Application in 0.827 seconds (JVM running for 1.096)
bar
baz
Exception in thread "main" 2016-08-30 10:35:13.254  INFO 15142 --- [       Thread-1] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@7e9a5fbe: startup date [Tue Aug 30 10:35:12 BST 2016]; root of context hierarchy
org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'baz' is defined
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:677)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1180)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:284)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1076)
	at com.example.Gh1309Application.main(Gh1309Application.java:20)
2016-08-30 10:35:13.255  INFO 15142 --- [       Thread-1] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
```

The profile-specific `foo` and `bar` properties are in the environment because the YAML processing does regular expression-based matching of the profile names. The `baz` bean is not in the context as Spring Framework does not perform regular expression-based matching.

As far as I can tell, removing the use of regular expression would align the behaviour with Spring Framework's profile matching and would also get rid of the unhelpful expression that is leaking an implementation detail.

**Comment by wilkinsona** [comment]
There's no need for the regular expression. Removing it will avoid the problem of the value not being a valid regular expression.
