### ISSUE TITLE
Deployment to Weblogic 12.1.3.0 fails since 1.5.11 RELEASE

### ISSUE THREAD

**Issue by pmihalcin** [spring-projects/spring-boot#13125]
I put together [minimal sample](https://github.com/pmihalcin/boot-weblogic) which reproduces problem. When you try to deploy given application to Weblogic 12.1.3.0, it fails to start with following exception:

```
<May 9, 2018 6:25:25 PM CEST> <Error> <Deployer> <BEA-149265> <Failure occurred in the execution of deployment request with ID "290176514936800" for task "0". Error is: "weblogic.application.ModuleException: null
null"
weblogic.application.ModuleException: null
null
	at weblogic.servlet.internal.WebAppModule.createModuleException(WebAppModule.java:1824)
	at weblogic.servlet.internal.WebAppModule.init(WebAppModule.java:270)
	at weblogic.servlet.internal.WebAppModule.init(WebAppModule.java:682)
	at weblogic.application.internal.flow.ScopedModuleDriver.init(ScopedModuleDriver.java:162)
	at weblogic.application.internal.ExtensibleModuleWrapper.init(ExtensibleModuleWrapper.java:98)
	Truncated. see log file for complete stacktrace
Caused By: java.lang.IllegalArgumentException
	at com.bea.objectweb.asm.ClassReader.<init>(Unknown Source)
	at com.bea.objectweb.asm.ClassReader.<init>(Unknown Source)
	at weblogic.application.utils.annotation.ClassInfoImpl.<init>(ClassInfoImpl.java:41)
	at weblogic.application.utils.annotation.ClassfinderClassInfos.polulateOneClassInfo(ClassfinderClassInfos.java:240)
	at weblogic.application.utils.annotation.ClassfinderClassInfos.populateClassInfos(ClassfinderClassInfos.java:193)
	Truncated. see log file for complete stacktrace
> 
<May 9, 2018 6:25:25 PM CEST> <Warning> <Deployer> <BEA-149004> <Failures were detected while initiating deploy task for application "boot-weblogic_war_exploded".> 
<May 9, 2018 6:25:25 PM CEST> <Warning> <Deployer> <BEA-149078> <Stack trace for message 149004
weblogic.application.ModuleException: null
null
	at weblogic.servlet.internal.WebAppModule.createModuleException(WebAppModule.java:1824)
	at weblogic.servlet.internal.WebAppModule.init(WebAppModule.java:270)
	at weblogic.servlet.internal.WebAppModule.init(WebAppModule.java:682)
	at weblogic.application.internal.flow.ScopedModuleDriver.init(ScopedModuleDriver.java:162)
	at weblogic.application.internal.ExtensibleModuleWrapper.init(ExtensibleModuleWrapper.java:98)
	Truncated. see log file for complete stacktrace
Caused By: java.lang.IllegalArgumentException
	at com.bea.objectweb.asm.ClassReader.<init>(Unknown Source)
	at com.bea.objectweb.asm.ClassReader.<init>(Unknown Source)
	at weblogic.application.utils.annotation.ClassInfoImpl.<init>(ClassInfoImpl.java:41)
	at weblogic.application.utils.annotation.ClassfinderClassInfos.polulateOneClassInfo(ClassfinderClassInfos.java:240)
	at weblogic.application.utils.annotation.ClassfinderClassInfos.populateClassInfos(ClassfinderClassInfos.java:193)
	Truncated. see log file for complete stacktrace
> 
```

It doesn't happen with `1.5.10.RELEASE` version

**Comment by wilkinsona** [comment]
Thanks for the report, but this looks like a WebLogic problem to me. It's presumably triggered by a dependency upgrade in Spring Boot 1.5.11. It would appear that the version of ASM used by WebLogic isn't capable of parsing a class file. Hopefully the full log output will identify the class in question. With that information you could either raise a support ticket with Oracle, downgrade the dependency to one that WebLogic can cope with, or both.

**Comment by beijing1** [comment]
how did you find this out? I am having similar issue but not sure which third party lib is causing this? Does the weblogic server log say it somewhere? I could not find it in AdminServer.log, maybe I am not checking the right log?

**Comment by pmihalcin** [comment]
@beijing1 You can see that when you try to deploy war using deployer (it is used e.g. when you deploy from Intellij IDEA using weblogic run configuration).

**Comment by beijing1** [comment]
Hi thanks for the reply!
I did not use any IDE to deploy, just directly dropped it to autodeployed folder or through console. I checked in the server log, did not seem find anything obvious.


Sent from Yahoo Mail for iPhone


On Monday, March 4, 2019, 3:54 PM, Patrik Mihalcin <notifications@github.com> wrote:


@beijing1 You can see that when you try to deploy war using deployer (it is used e.g. when you deploy from Intellij IDEA using weblogic run configuration).

**Comment by 18752125869** [comment]
how did you solve this problem?

**Comment by FuadEfendi** [comment]
I have the same issue right now, unfortunately WLS 12.1.3 is the only Development edition I can use.

**Comment by baranirajarathinam** [comment]
@FuadEfendi  same issue for me and i am also using 12.1.3.  were you able to resolve the issue?  can you plz post the resolution?
