### ISSUE TITLE
NPE in StandardPomDependencyManagementConfigurer

### ISSUE THREAD

**Issue by asarkar** [spring-projects/spring-boot#13193]
Gradle 4.7, Boot plugin v2.0.2.RELEASE

I'm upgrading a bunch of apps from Boot 1.5 to 2, as well as to Gradle 4, and in the process came across the following exception:

```
Caused by: java.lang.NullPointerException
    at io.spring.gradle.dependencymanagement.internal.StandardPomDependencyManagementConfigurer.differentVersions(StandardPomDependencyManagementConfigurer.java:175)
    at io.spring.gradle.dependencymanagement.internal.StandardPomDependencyManagementConfigurer.configureBomImports(StandardPomDependencyManagementConfigurer.java:136)
    at io.spring.gradle.dependencymanagement.internal.StandardPomDependencyManagementConfigurer.doConfigurePom(StandardPomDependencyManagementConfigurer.java:115)
```

There was no indication given that what it was trying to resolve when the NPE occurred. By removing one dependency at a time, I found that it was cause by a Sleuth `mavenBom` import (don't remember which one). The project being an internal one, and because I don't know what caused the NPE, I'm not able to reproduce the problem in a standalone application.

I think some additional debugging info would be very useful, like what it was trying to resolve when it blew up, and what exactly is null.

**Comment by wilkinsona** [comment]
I have opened https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/213.
