### ISSUE TITLE
Allow property values that contain placeholders to be bound as-is

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#13202]
In 1.5, it was possible to bind a property value that contained an unresolvable placeholder due to [this change](https://github.com/spring-projects/spring-boot/commit/8922a6be4aa17495bc3303bc8898b797d2fc573f). In 2.0, that's no longer possible and the binding will fail with an exception similar to the following:

```
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'placeholder' in value "Value with ${placeholder}"
    at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:172) ~[spring-core-5.0.6.RELEASE.jar:5.0.6.RELEASE]
    at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:124) ~[spring-core-5.0.6.RELEASE.jar:5.0.6.RELEASE]
    at org.springframework.boot.context.properties.bind.PropertySourcesPlaceholdersResolver.resolvePlaceholders(PropertySourcesPlaceholdersResolver.java:60) ~[spring-boot-2.0.2.RELEASE.jar:2.0.2.RELEASE]
    at org.springframework.boot.context.properties.bind.Binder.bindProperty(Binder.java:323) ~[spring-boot-2.0.2.RELEASE.jar:2.0.2.RELEASE]
    at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:267) ~[spring-boot-2.0.2.RELEASE.jar:2.0.2.RELEASE]
    at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:221) ~[spring-boot-2.0.2.RELEASE.jar:2.0.2.RELEASE]
    ... 43 common frames omitted
```

If we adopt the approach that was taken in 1.x (ignore any placeholder resolution failures), a property value with a placeholder could be bound as-is as long as there's no property with that value. Ideally, we'd like to be able to support binding a value that contains something that looks like a placeholder but that should not be treated as one.

**Comment by philwebb** [comment]
I think the old approach might be the least bad option.

**Comment by wilkinsona** [comment]
Fixed by https://github.com/spring-projects/spring-boot/commit/0df37b917bc14f9a83793876a58864f27da5caf8 (I missed up the issue reference in the commit).

**Comment by artemyarulin** [comment]
Hm, after this change there is no validation anymore - with 2.0.2 if certain placeholder cannot be resolved application would throw an exception on start, but after 2.0.3 it would be running just fine and example `config.dbConn` would have value of `"${DB_CONN}"` which is really confusing

cc @wilkinsona

**Comment by artemyarulin** [comment]
Understand that - Spring has a rather long history, thanks for your prompt reply
