### ISSUE TITLE
byte-buddy-1.7.11.jar corrupt in Spring Boot 2.0.2?

### ISSUE THREAD

**Issue by mr-bobz** [spring-projects/spring-boot#13219]
I am using STS (3.9.4) on macOS (v10.13.4, High Sierra) to create a new 'Sprint Starter Project'

I have picked Maven, Java 8 and Spring Boot 2.0.2 with only Web.

However the project cannot be built due to the following error:
Archive for required library: '/Users/bobz/.m2/repository/net/bytebuddy/byte-buddy/1.7.11/byte-buddy-1.7.11.jar' in project 'mailer' cannot be read or is not a valid ZIP file 

byte-buddy-1.7.11.jar exists in above path and is ~3MB.  I think there is something wrong with the jar format, as shown below!

```
jar -tvf /Users/bobz/.m2/repository/net/bytebuddy/byte-buddy/1.7.11/byte-buddy-1.7.11.jar 
java.util.zip.ZipException: invalid CEN header (bad signature)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:126)
	at sun.tools.jar.Main.list(Main.java:1115)
	at sun.tools.jar.Main.run(Main.java:293)
	at sun.tools.jar.Main.main(Main.java:1288)
```

I ran 

> mvn dependency:purge-local-repository

 a couple of times and updated project to make sure it is not a temporary issue!

**Comment by mr-bobz** [comment]
FYI, above error is happening in all **2.x** versions. I downgraded to _1.5.14_.BUILD-SNAPSHOT and above error went away.

Got another one in Test, 

> Type mismatch: cannot convert from Class<SpringRunner> to Class<? extends Runner>

but I think for now I will just comment out 

> @RunWith(SpringRunner.class)

**Comment by mr-bobz** [comment]
@cemo, thanks deleting that jar file manually and updating project worked 👍

**Comment by mandos7** [comment]
After overwriting the byte-buddy-1.7.11.jar you must update the project: 
Right-click on the project, Properties, Maven, update project...
