### ISSUE TITLE
ErrorPageFilter produces pointless logging when failure is due to a ClientAbortException

### ISSUE THREAD

**Issue by amkad** [spring-projects/spring-boot#13221]
I want to suppress logging of `org.apache.catalina.connector.ClientAbortException`. It's possible to catch to ignore this exception in an own filter but in some cases `ClientAbortException` is thrown by `response.flushBuffer()` in `ErrorPageFilter#doFilter`.

I would propose to make `ErrorPageFilter#handleCommittedResponse` protected, to be able to customize exception handling.

**Comment by philwebb** [comment]
Have you tried creating a dedicated `Filter` that's registered before the `ErrorPageFilter` to handle this?

**Comment by amkad** [comment]
Yes, I tried and it solves the problem in most of cases but sometimes, e.g. when a controller responded with `resp.sendError(...)`, `ClientAbortException` may happen in `ErrorPageFilter`

```
org.apache.catalina.connector.ClientAbortException: java.io.IOException: An established connection was aborted by the software in your host machine
	at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:393)
	at org.apache.tomcat.util.buf.ByteChunk.flushBuffer(ByteChunk.java:426)
	at org.apache.catalina.connector.OutputBuffer.realWriteChars(OutputBuffer.java:471)
	at org.apache.tomcat.util.buf.CharChunk.flushBuffer(CharChunk.java:393)
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:339)
	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:317)
	at org.apache.catalina.connector.Response.flushBuffer(Response.java:510)
	at org.apache.catalina.connector.ResponseFacade.flushBuffer(ResponseFacade.java:318)
	at javax.servlet.ServletResponseWrapper.flushBuffer(ServletResponseWrapper.java:176)
	at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:121)
...
```

spring-boot:1.5.12.RELEASE

**Comment by philwebb** [comment]
OK, that makes sense. I guess the exception isn't triggered until the error handling occurs.

**Comment by philwebb** [comment]
We've discussed this and we'd rather not made that method protected. Instead we'll deal check for `ClientAbortException` in `handleCommittedResponse` ourselves and suppress the log.
