### ISSUE TITLE
"No ConfigurableListableBeanFactory available" thrown while using ClassPathScanningCandidateComponentProvider

### ISSUE THREAD

**Issue by todoakaio** [spring-projects/spring-boot#13226]
**Spring Boot 2.0.2.RELEASE**

I'm getting the following exception on application startup:
```
java.lang.IllegalStateException: No ConfigurableListableBeanFactory available
	at org.springframework.util.Assert.state(Assert.java:73) ~[spring-core-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.context.annotation.ConditionEvaluator$ConditionContextImpl.getBeanFactory(ConditionEvaluator.java:206) ~[spring-context-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.recordEvaluation(SpringBootCondition.java:113) ~[spring-boot-autoconfigure-2.0.2.RELEASE.jar:2.0.2.RELEASE]
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:49) ~[spring-boot-autoconfigure-2.0.2.RELEASE.jar:2.0.2.RELEASE]
```
I'm using the demo project from https://start.spring.io/ but with two edits: I created a `@Configuration` class as follows:
```java
@Configuration
public class DemoConfiguration {

  @Bean
  public ClassPathScanningCandidateComponentProvider classPathScanningCandidateComponentProvider(Environment environment) {
    ClassPathScanningCandidateComponentProvider classPathScanningCandidateComponentProvider =
        new ClassPathScanningCandidateComponentProvider(true, environment);
    classPathScanningCandidateComponentProvider.findCandidateComponents("com.example");
    return classPathScanningCandidateComponentProvider;
  }
}
```
I also added `@ConditionalOnNotWebApplication` on the main class, which is also annotated with `@SpringBootApplication`. It doesn't matter which `@ConditionalOn` is there.

The exception is being thrown from `ConditionEvaluator`, which assures that the beanFactory being returned is not null:
```java
@Override
public ConfigurableListableBeanFactory getBeanFactory() {
	Assert.state(this.beanFactory != null, "No ConfigurableListableBeanFactory available");
	return this.beanFactory;
}
```
However, the calling class, `SpringBootCondition`, uses this method to check whether the beanFactory is null:
```java
private void recordEvaluation(ConditionContext context, String classOrMethodName,
		ConditionOutcome outcome) {
	if (context.getBeanFactory() != null) {
		ConditionEvaluationReport.get(context.getBeanFactory())
				.recordConditionEvaluation(classOrMethodName, this, outcome);
	}
}
```
As a result, the expression `context.getBeanFactory() != null` never returns false, but rather throws a `java.lang.IllegalStateException: No ConfigurableListableBeanFactory available` if it is null.

In the above example, I instantiate a `ClassPathScanningCandidateComponentProvider` directly, but this problem also occurs from the `ClassPathScanningCandidateComponentProvider` instantiated in `org.springframework.boot.test.context.SpringBootConfigurationFinder`, which is used when running tests with `@RunWith(SpringRunner.class)`.

For example, simply running the demo's only test will fail if there is an `@ConditionalOn` anywhere in the project with the following stacktrace:
```
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: file [/Users/.../demo/out/production/classes/com/example/demo/DemoApplication.class]; nested exception is java.lang.IllegalStateException: Error processing condition on com.example.demo.DemoApplication

	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.scanCandidateComponents(ClassPathScanningCandidateComponentProvider.java:454)
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:316)
	at org.springframework.boot.test.context.SpringBootConfigurationFinder.scanPackage(SpringBootConfigurationFinder.java:67)
	at org.springframework.boot.test.context.SpringBootConfigurationFinder.findFromPackage(SpringBootConfigurationFinder.java:59)
	at org.springframework.boot.test.context.SpringBootConfigurationFinder.findFromClass(SpringBootConfigurationFinder.java:52)
	at org.springframework.boot.test.context.SpringBootTestContextBootstrapper.getOrFindConfigurationClasses(SpringBootTestContextBootstrapper.java:239)
	at org.springframework.boot.test.context.SpringBootTestContextBootstrapper.processMergedContextConfiguration(SpringBootTestContextBootstrapper.java:153)
	at org.springframework.test.context.support.AbstractTestContextBootstrapper.buildMergedContextConfiguration(AbstractTestContextBootstrapper.java:395)
	at org.springframework.test.context.support.AbstractTestContextBootstrapper.buildDefaultMergedContextConfiguration(AbstractTestContextBootstrapper.java:312)
	at org.springframework.test.context.support.AbstractTestContextBootstrapper.buildMergedContextConfiguration(AbstractTestContextBootstrapper.java:265)
	at org.springframework.test.context.support.AbstractTestContextBootstrapper.buildTestContext(AbstractTestContextBootstrapper.java:108)
	at org.springframework.boot.test.context.SpringBootTestContextBootstrapper.buildTestContext(SpringBootTestContextBootstrapper.java:97)
	at org.springframework.test.context.TestContextManager.<init>(TestContextManager.java:139)
	at org.springframework.test.context.TestContextManager.<init>(TestContextManager.java:124)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTestContextManager(SpringJUnit4ClassRunner.java:151)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.<init>(SpringJUnit4ClassRunner.java:142)
	at org.springframework.test.context.junit4.SpringRunner.<init>(SpringRunner.java:49)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.IllegalStateException: Error processing condition on com.example.demo.DemoApplication
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:64)
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108)
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:88)
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:71)
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.isConditionMatch(ClassPathScanningCandidateComponentProvider.java:515)
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.isCandidateComponent(ClassPathScanningCandidateComponentProvider.java:498)
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.scanCandidateComponents(ClassPathScanningCandidateComponentProvider.java:431)
	... 30 more
Caused by: java.lang.IllegalStateException: No ConfigurableListableBeanFactory available
	at org.springframework.util.Assert.state(Assert.java:73)
	at org.springframework.context.annotation.ConditionEvaluator$ConditionContextImpl.getBeanFactory(ConditionEvaluator.java:206)
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.recordEvaluation(SpringBootCondition.java:113)
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:49)
	... 36 more
```

**Comment by snicoll** [comment]
@todoakaio there are a lot of moving pieces and pasting code in text means we'll have to replicate and hope we'll get the same arrangement. Rather than us wasting time on this than helping you, could you please share a minimal sample we can run ourselves? Thanks.

**Comment by wilkinsona** [comment]
It would also be useful to know why you want to add a condition to your application's main class. I can't think of a reason for needing to do so.

**Comment by todoakaio** [comment]
Sure thing.

The sample project is here: https://github.com/todoakaio/demo-bootbug

You can find the bug by both starting the application and by running the only test.

I also moved the `@ConditionalOn` out of the application's main class, @wilkinsona, and put it on a second `Configuration` class, since that's closer to our real world use case. The real use case is to prevent Spring Boot from configuring Quartz unless a certain property is set to true, which we do by using `@ConditionalOnProperty("com.example.quartz.enabled")`

**Comment by wilkinsona** [comment]
Thanks for the sample, @todoakaio.

This looks to be a regression from 1.5 due to Boot not being updated for a breaking change in Spring Framework 5.0. In 4.3, the contract for `ConditionContext.getBeanFactory()` is the following:

```java
	/**
	 * Return the {@link ConfigurableListableBeanFactory} that will hold the bean
	 * definition should the condition match, or {@code null} if the bean factory
	 * is not available.
	 */
	ConfigurableListableBeanFactory getBeanFactory();
```

In 5.0 it's changed so that `null` will no longer be returned:

```java
	/**
	 * Return the {@link ConfigurableListableBeanFactory} that will hold the bean
	 * definition should the condition match.
	 */
	ConfigurableListableBeanFactory getBeanFactory();
```

Instead, as noted above, it throws an (undocumented) `IllegalStateException`.

**Comment by wilkinsona** [comment]
The problem can be worked around by using a `ClassPathBeanDefinitionScanner`:

```diff
diff --git a/src/main/java/com/example/demo/DemoConfiguration.java b/src/main/java/com/example/demo/DemoConfiguration.java
index 4abefa3..aef0a0f 100644
--- a/src/main/java/com/example/demo/DemoConfiguration.java
+++ b/src/main/java/com/example/demo/DemoConfiguration.java
@@ -2,16 +2,19 @@ package com.example.demo;

 import org.springframework.context.annotation.Bean;
 import org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider;
+import org.springframework.context.annotation.ClassPathBeanDefinitionScanner;
 import org.springframework.context.annotation.Configuration;
 import org.springframework.core.env.Environment;
+import org.springframework.beans.factory.support.BeanDefinitionRegistry;
+import org.springframework.context.ApplicationContext;

 @Configuration
 public class DemoConfiguration {

   @Bean
-  public ClassPathScanningCandidateComponentProvider classPathScanningCandidateComponentProvider(Environment environment) {
+  public ClassPathScanningCandidateComponentProvider classPathScanningCandidateComponentProvider(ApplicationContext context, Environment environment) {
     ClassPathScanningCandidateComponentProvider classPathScanningCandidateComponentProvider =
-        new ClassPathScanningCandidateComponentProvider(true, environment);
+        new ClassPathBeanDefinitionScanner((BeanDefinitionRegistry)context, true, environment);
     classPathScanningCandidateComponentProvider.findCandidateComponents("com.example");
     return classPathScanningCandidateComponentProvider;
   }
```

**Comment by snicoll** [comment]
@wilkinsona I guess `OnExpressionCondition` should be reworked as part of this one? The null check that I introduced is useless there (as a few others we have).

I had a talk with Juergen and I think we'll have to swallow the pill and rely on that exception now in case of broken setup. According to @jhoeller, it should only happen with a custom `ClassPathScanningCandidateComponentProvider` that doesn't provide a `BeanFactory`. 

Did you have something else in mind?

**Comment by philwebb** [comment]
Spring Framework issue [SPR-16866](https://jira.spring.io/browse/SPR-16866) has been fixed so I think the `IllegalArgumentException` will no longer occur.
