### ISSUE TITLE
TrustStore issue with Jetty and IBM JDK

### ISSUE THREAD

**Issue by fabriziocucci** [spring-projects/spring-boot#13267]
### Environment

* macOS Sierra: `10.12.6`
* Spring Boot: `1.5.9.RELEASE`
* Java:
```
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 8.0.5.10 - pxa6480sr5fp10-20180214_01(SR5 FP10))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64 Compressed References 20180208_378436 (JIT enabled, AOT enabled)
OpenJ9   - 39bb844
OMR      - c04ccb2
IBM      - 2321a81)
JCL - 20180209_01 based on Oracle jdk8u161-b12
```

### Description

I have a simple Spring Boot application configured as follows:

```yaml
server.ssl.enabled: true
server.ssl.key-alias: my-application
server.ssl.key-store: classpath:keystore.p12
server.ssl.key-store-password: changeit
server.ssl.key-store-type: PKCS12
```

If I use Tomcat as embedded server everything works fine. If I replace Tomcat with Jetty, the following exception is thrown:

```
Caused by: java.io.IOException: Invalid keystore format
	at com.ibm.crypto.provider.JavaKeyStore.engineLoad(Unknown Source)
	at java.security.KeyStore.load(KeyStore.java:1456)
	at org.eclipse.jetty.util.security.CertificateUtils.getKeyStore(CertificateUtils.java:52)
	at org.eclipse.jetty.util.ssl.SslContextFactory.loadTrustStore(SslContextFactory.java:1055)
	at org.eclipse.jetty.util.ssl.SslContextFactory.load(SslContextFactory.java:257)
	at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:222)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
	at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:72)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:276)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:238)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainer.start(JettyEmbeddedServletContainer.java:143)
```

I had a quick look at the source code, specifically at `SslContextFactory#loadTrustStore`, and it seems that Jetty is trying to use the keystore configured in the `application.yaml` also as trustore but it is trying to load it with the wrong configuration (e.g. `type` in the snippet below is `JKS` instead of `PKCS12`):

```java
// code from org.eclipse.jetty.util.ssl.SslContextFactory (9.4.7.v20170914)

protected KeyStore loadTrustStore(Resource resource) throws Exception
{
    String type = getTrustStoreType();
    String provider = getTrustStoreProvider();
    String passwd = _trustStorePassword == null ? null : _trustStorePassword.toString();
    if (resource == null || resource.equals(_keyStoreResource))
    {
        resource = _keyStoreResource;
        if (type == null)
            type = _keyStoreType;
        if (provider == null)
            provider = _keyStoreProvider;
        if (passwd == null)
            passwd = _keyStorePassword == null ? null : _keyStorePassword.toString();
    }
    return CertificateUtils.getKeyStore(resource, type, provider, passwd);
}
```

The above doesn't cause any problem with the Oracle JDK because the concrete implementation of `java.security.KeyStoreSpi` used to load the truststore (in the subsequent calls) seems to be resilient enough to try both `JKS` and `PKCS12` (speculating a bit here given the name of the loader `sun.security.provider.JavaKeyStore$DualFormatJKS`).

A quick (and dirty?) workaround for this requires explicitely setting the truststore type in the `application.yaml`:

```yaml
server.ssl.enabled: true
server.ssl.key-alias: my-application
server.ssl.key-store: classpath:keystore.p12
server.ssl.key-store-password: changeit
server.ssl.key-store-type: PKCS12

server.ssl.trust-store-type: PKCS12
```

_Pherhaps_ a better solution would be to slightly change the `JettyEmbeddedServletContainerFactory#configureSslTrustStore` to set, for the truststore, the same parameters used for the keystore, if no truststore is explicitely configured.

Anyway, **if** this is considered a (minor) bug, I'd be happy to contribute the fix.

**Comment by philwebb** [comment]
It seems like a sensible change to me. A pull-request would be most welcome.

**Comment by fabriziocucci** [comment]
Thanks for your prompt feedback @philwebb.

I'm going to give it a try! 😎

**Comment by fabriziocucci** [comment]
My bad, I was actually testing with Spring Boot `1.5.9.RELEASE`!

It turns out that the issue disappears if upgrading to `1.5.10.RELEASE` because of [this](https://github.com/spring-projects/spring-boot/commit/88b15baf20b3e7d3d5eefd1f692cb4d7c436cafc).

In fact, upgrading Jetty from `9.4.7.v20170914` to `9.4.8.v20171121` actually solves the issue because Jetty code is now actually doing what I've implemented in [my pull request](https://github.com/spring-projects/spring-boot/pull/13270):

```java
// code from org.eclipse.jetty.util.ssl.SslContextFactory (9.4.8.v20171121)
protected KeyStore loadTrustStore(Resource resource) throws Exception
{
    String type = Objects.toString(getTrustStoreType(), getKeyStoreType());
    String provider = Objects.toString(getTrustStoreProvider(), getKeyStoreProvider());
    String passwd = Objects.toString(_trustStorePassword, Objects.toString(_keyStorePassword, null));
    if (resource == null)
        resource = _keyStoreResource;
    return CertificateUtils.getKeyStore(resource, type, provider, passwd);
}
```

Sorry @philwebb, feel free to close this issue and the related pull request if you believe this is no longer necessary.

**Comment by snicoll** [comment]
Thanks for the follow-up
