### ISSUE TITLE
"URI is not hierarchical" exception when using src/main/resources/META-INF/resources in WAR

### ISSUE THREAD

**Issue by BastiaanProot** [spring-projects/spring-boot#13265]
We run a JSP app as a Spring-boot WAR.
We went from 1.5.12 to 1.5.13 and encountered this error during startup:

```
Caused by: java.lang.IllegalArgumentException: URI is not hierarchical
	at java.io.File.<init>(File.java:418)
	at org.springframework.boot.context.embedded.tomcat.TomcatResources.addResourceJars(TomcatResources.java:63)
```

Indeed TomcatResources.java:63 changed to the following in 1.5.13:

`addDir(new File(url.toURI()).getAbsolutePath(), url);`

in 1.5.12 it was:

`addDir(file, url);`

Where file came from `url.getFile()`.

In our case the value of url is something like:

`jar:file:/opt/app/app.war!/WEB-INF/classes!/`

so `new File(url.toURI())` fails.

**Comment by BastiaanProot** [comment]
You can reproduce the error by adding a resource file (e.g. test.ico) to _src/main/resources/META-INF/resources_ in the [spring-boot-sample-tomcat-jsp example](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples/spring-boot-sample-tomcat-jsp).

Meanwhile I have been able to avoid the error by moving my resources out of _src/main/resources/META-INF/resources_ and into _src/main/webapp_ where they belong.

Us putting the resources in the _src/main/resources/META-INF/resources_ directory was left over from an old attempt to convert the war to a jar.

**Comment by philwebb** [comment]
Here's the full stack trace from the tomcat sample. The error doesn't occur in the IDE, only when running `java -jar`.

```
java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].TomcatEmbeddedContext[]]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) [na:1.8.0_144]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) [na:1.8.0_144]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:941) ~[tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:872) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1421) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1411) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].TomcatEmbeddedContext[]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	... 6 common frames omitted
Caused by: java.lang.IllegalArgumentException: URI is not hierarchical
	at java.io.File.<init>(File.java:418) ~[na:1.8.0_144]
	at org.springframework.boot.context.embedded.tomcat.TomcatResources.addResourceJars(TomcatResources.java:63) ~[spring-boot-1.5.14.BUILD-SNAPSHOT.jar!/:1.5.14.BUILD-SNAPSHOT]
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory$1.lifecycleEvent(TomcatEmbeddedServletContainerFactory.java:228) ~[spring-boot-1.5.14.BUILD-SNAPSHOT.jar!/:1.5.14.BUILD-SNAPSHOT]
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5154) ~[tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	... 6 common frames omitted
```
