### ISSUE TITLE
Unit Test Problem - Running All Tests Together 

### ISSUE THREAD

**Issue by roanbrasil** [spring-projects/spring-boot#13304]
Hello, it is my first report. I think might be a issue. Lets show What I am trying to do. I am recently working with spring boot and I am developing Unit Tests.

When I run isolated each test works fine and If i run all testes I got an  error.

Test 1, running all tests:

```
15:49:48.048 [main] DEBUG org.springframework.test.context.support.AbstractDirtiesContextTestExecutionListener - After test method: context [DefaultTestContext@797badd3 testClass = AccountBalanceUpdateServiceTest, testInstance = br.com.package.infrastructure.AccountBalanceUpdateServiceTest@51df223b, testMethod = insertDataWhenArgsIsPresent@AccountBalanceUpdateServiceTest, testException = org.mockito.exceptions.verification.TooManyActualInvocations: 
br.com.package.infrastructure.mysql.MysqlRepository bean.updateAccountBalance(
    2016-12,
    2017-01,
    "6"
);
Wanted 1 time:
 at br.com.package.infrastructure.AccountBalanceUpdateServiceTest.insertDataWhenArgsIsPresent(AccountBalanceUpdateServiceTest.java:46)
But was 2 times. Undesired invocation:
 at br.com.package.infrastructure.AccountBalanceUpdateService.lambda$run$0(AccountBalanceUpdateService.java:43)
, mergedContextConfiguration = [MergedContextConfiguration@77be656f testClass = AccountBalanceUpdateServiceTest, locations = '{}', classes = '{class br.com.package.infrastructure.AccountBalanceUpdateServiceTest$Config}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{}', contextCustomizers = set[org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@3ecd23d9, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@64f6106c, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@f42bfc1a, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@4516af24], contextLoader = 'org.springframework.test.context.support.DelegatingSmartContextLoader', parent = [null]], attributes = map[[empty]]], class annotated with @DirtiesContext [false] with mode [null], method annotated with @DirtiesContext [false] with mode [null].

org.mockito.exceptions.verification.TooManyActualInvocations: 
br.com.package.infrastructure.mysql.MysqlRepository bean.updateAccountBalance(
    2016-12,
    2017-01,
    "6"
);
Wanted 1 time:

 at br.com.package.infrastructure.AccountBalanceUpdateServiceTest.insertDataWhenArgsIsPresent(AccountBalanceUpdateServiceTest.java:46)
But was 2 times. Undesired invocation:
 at br.com.package.infrastructure.AccountBalanceUpdateService.lambda$run$0(AccountBalanceUpdateService.java:43)
	at br.com.package.infrastructure.AccountBalanceUpdateServiceTest.insertDataWhenArgsIsPresent(AccountBalanceUpdateServiceTest.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:73)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:83)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

Test2: When I run All Tests

```
15:49:48.015 [main] DEBUG org.springframework.test.context.support.AbstractDirtiesContextTestExecutionListener - After test method: context [DefaultTestContext@797badd3 testClass = AccountBalanceUpdateServiceTest, testInstance = br.com.package.infrastructure.AccountBalanceUpdateServiceTest@21d8bcbe, testMethod = insertDataWhenArgsIsNotPresent@AccountBalanceUpdateServiceTest, testException = Argument(s) are different! Wanted:
br.com.package.infrastructure.mysql.MysqlRepository bean.updateAccountBalance(
    2018-04,
    2018-05,
    "1"
);
-> at br.com.package.infrastructure.AccountBalanceUpdateServiceTest.insertDataWhenArgsIsNotPresent(AccountBalanceUpdateServiceTest.java:54)
Actual invocation has different arguments:
br.com.package.infrastructure.mysql.MysqlRepository bean.updateAccountBalance(
    2016-11,
    2016-12,
    "1"
);
-> at br.com.package.infrastructure.AccountBalanceUpdateService.lambda$run$0(AccountBalanceUpdateService.java:43)
, mergedContextConfiguration = [MergedContextConfiguration@77be656f testClass = AccountBalanceUpdateServiceTest, locations = '{}', classes = '{class br.com.package.infrastructure.AccountBalanceUpdateServiceTest$Config}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{}', contextCustomizers = set[org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@3ecd23d9, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@64f6106c, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@f42bfc1a, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@4516af24], contextLoader = 'org.springframework.test.context.support.DelegatingSmartContextLoader', parent = [null]], attributes = map[[empty]]], class annotated with @DirtiesContext [false] with mode [null], method annotated with @DirtiesContext [false] with mode [null].


Argument(s) are different! Wanted:
br.com.package.infrastructure.mysql.MysqlRepository bean.updateAccountBalance(
    2018-04,
    2018-05,
    "1"
);
-> at br.com.package.infrastructure.AccountBalanceUpdateServiceTest.insertDataWhenArgsIsNotPresent(AccountBalanceUpdateServiceTest.java:54)
Actual invocation has different arguments:
br.com.package.infrastructure.mysql.MysqlRepository bean.updateAccountBalance(
    2016-11,
    2016-12,
    "1"
);
-> at br.com.package.infrastructure.AccountBalanceUpdateService.lambda$run$0(AccountBalanceUpdateService.java:43)

Comparison Failure:  <Click to see difference>

Argument(s) are different! Wanted:
br.com.package.infrastructure.mysql.MysqlRepository bean.updateAccountBalance(
    2018-04,
    2018-05,
    "1"
);
-> at br.com.package.infrastructure.AccountBalanceUpdateServiceTest.insertDataWhenArgsIsNotPresent(AccountBalanceUpdateServiceTest.java:54)
Actual invocation has different arguments:
br.com.package.infrastructure.mysql.MysqlRepository bean.updateAccountBalance(
    2016-11,
    2016-12,
    "1"
);
-> at br.com.package.infrastructure.AccountBalanceUpdateService.lambda$run$0(AccountBalanceUpdateService.java:43)

	at br.com.package.infrastructure.AccountBalanceUpdateServiceTest.insertDataWhenArgsIsNotPresent(AccountBalanceUpdateServiceTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:73)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:83)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

I have my class like bellow that doesnt work:

```java
@RunWith(SpringRunner.class)
public class AccountBalanceUpdateServiceTest {

    @Autowired
    private AccountBalanceUpdateService service;

    @MockBean
    private AccountBalanceUpdateRepository repository;
 @Rule
    public ExpectedException thrown = ExpectedException.none();

    @Before
    public void prepare() {
        Mockito.clearInvocations(this.repository);
    }

    @Test
    public void insertDataWhenArgsIsPresent() throws Exception {
        
        service.run("201701", "201701", "6");

        verify(this.repository).updateAccountBalance(YearMonth.of(2016, 12), YearMonth.of(2017, 1), "6");
    }

    @Test
    public void insertDataWhenArgsIsNotPresent() throws Exception {

        service.run("");

        verify(this.repository, atLeastOnce()).updateAccountBalance(YearMonth.now().minusMonths(1L), YearMonth.now(), "1");
        verify(this.repository, atLeastOnce()).updateAccountBalance(YearMonth.now().minusMonths(1L), YearMonth.now(), "2");
        verify(this.repository, atLeastOnce()).updateAccountBalance(YearMonth.now().minusMonths(1L), YearMonth.now(), "6");
        verify(this.repository, atLeastOnce()).updateAccountBalance(YearMonth.now().minusMonths(1L), YearMonth.now(), "12");
        verify(this.repository, atLeastOnce()).updateAccountBalance(YearMonth.now().minusMonths(1L), YearMonth.now(), "17");
        verify(this.repository, atLeastOnce()).updateAccountBalance(YearMonth.now().minusMonths(1L), YearMonth.now(), "19");
        verify(this.repository, atLeastOnce()).updateAccountBalance(YearMonth.now().minusMonths(1L), YearMonth.now(), "21");
        verify(this.repository, atLeastOnce()).updateAccountBalance(YearMonth.now().minusMonths(1L), YearMonth.now(), "23");
        verify(this.repository, atLeastOnce()).updateAccountBalance(YearMonth.now().minusMonths(1L), YearMonth.now(), "25");
        verify(this.repository, atLeastOnce()).updateAccountBalance(YearMonth.now().minusMonths(1L), YearMonth.now(), "26");
    }

    @Test
    public void insertDataWhenArgsIsPresentAndWrong() throws Exception {

        thrown.expect(RuntimeException.class);
        thrown.expectMessage("Start Month should be at least bigger than 201612");
        service.run("201612", "201701", "6");
    }

    @Configuration
    @EnableConfigurationProperties
    @Import({AccountBalanceUpdateService.class, MysqlRepository.class, QueryConfiguration.class})
    public static class Config {

    }
}
```

As work around I did the code bellow and works fine, I think there is one problem with Spring Runner:

```java
public class AccountBalanceUpdateServiceTest {

    @Rule
    public ExpectedException thrown = ExpectedException.none();

    @InjectMocks
    private AccountBalanceUpdateService service;

    @Mock
    private AccountBalanceUpdateRepository repository;

    @Before
    public void prepare() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void insertDataWhenArgsIsPresent() throws Exception {

        service.run("201701", "201701", "6");

        verify(this.repository).updateAccountBalance(YearMonth.of(2016, 12), YearMonth.of(2017, 1), "6");
    }

    @Test
    public void insertDataWhenArgsIsNotPresent() throws Exception {

        service.run("");

        verify(this.repository, atLeastOnce()).updateAccountBalance(YearMonth.now().minusMonths(1L), YearMonth.now(), "1");
        verify(this.repository, atLeastOnce()).updateAccountBalance(YearMonth.now().minusMonths(1L), YearMonth.now(), "2");
        verify(this.repository, atLeastOnce()).updateAccountBalance(YearMonth.now().minusMonths(1L), YearMonth.now(), "6");
        verify(this.repository, atLeastOnce()).updateAccountBalance(YearMonth.now().minusMonths(1L), YearMonth.now(), "12");
        verify(this.repository, atLeastOnce()).updateAccountBalance(YearMonth.now().minusMonths(1L), YearMonth.now(), "17");
        verify(this.repository, atLeastOnce()).updateAccountBalance(YearMonth.now().minusMonths(1L), YearMonth.now(), "19");
        verify(this.repository, atLeastOnce()).updateAccountBalance(YearMonth.now().minusMonths(1L), YearMonth.now(), "21");
        verify(this.repository, atLeastOnce()).updateAccountBalance(YearMonth.now().minusMonths(1L), YearMonth.now(), "23");
        verify(this.repository, atLeastOnce()).updateAccountBalance(YearMonth.now().minusMonths(1L), YearMonth.now(), "25");
        verify(this.repository, atLeastOnce()).updateAccountBalance(YearMonth.now().minusMonths(1L), YearMonth.now(), "26");
    }

    @Test
    public void insertDataWhenArgsIsPresentAndWrong() throws Exception {
        thrown.expect(RuntimeException.class);
        thrown.expectMessage("Start Month should be at least bigger than 201612");
        service.run("201612", "201701", "6");
    }
}
```

If someone need my Service Class:

```java
@Slf4j
@Component
public class AccountBalanceUpdateService implements CommandLineRunner {

    @Autowired
    private AccountBalanceUpdateRepository repository;

    private YearMonth startMonth = YearMonth.now().minusMonths(3L);

    private YearMonth endMonth = YearMonth.now();

    private List<String> companyCodeList = new ArrayList();

    @Override
    public void run(String... args) throws Exception {

        long startTime = System.currentTimeMillis();

        this.setParams(args);

        log.info("Starting Processing [startMonth={}, endMonth={}, companyCodeList={}]", startMonth, endMonth, companyCodeList.toString());

        while (!endMonth.isBefore(startMonth)) {
            YearMonth previousMonth = startMonth.minusMonths(1L);

            companyCodeList.forEach(companyCode ->
                    this.repository.updateAccountBalance(previousMonth, startMonth, companyCode));

            startMonth = startMonth.plusMonths(1L);
        }
        log.info("Finished [elapsedTime={}]", elapsedTimeSince(startTime));
    }

    private void setParams(String[] args) {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyyMM");
        String[] companyArray = new String[]{"1", "2", "6", "12", "17", "19", "21", "23", "25", "26"};
        if (args.length > 2 && isNotBlank(args[0])
                && isNotBlank(args[1]) && isNotBlank(args[2])) {

            startMonth = YearMonth.parse(args[0], formatter);
            endMonth = YearMonth.parse(args[1], formatter);

            this.monthVerification(formatter);

            String companyCode = args[2];
            companyCodeList.addAll(Arrays.asList(companyCode.split(",")));

        } else if (args.length == 2 && isNotBlank(args[0])
                && isNotBlank(args[1])) {

            startMonth = YearMonth.parse(args[0], formatter);
            endMonth = YearMonth.parse(args[1], formatter);

            this.monthVerification(formatter);

            companyCodeList.addAll(Arrays.asList(companyArray));
        } else {
            companyCodeList.addAll(Arrays.asList(companyArray));
        }
    }

    private void monthVerification(DateTimeFormatter formatter) {
        if (!startMonth.isAfter(YearMonth.parse("201612", formatter))) {
            throw new RuntimeException("Start Month should be at least bigger than 201612");
        }
    }

    private String elapsedTimeSince(long startTime) {
        return String.valueOf(System.currentTimeMillis() - startTime);
    }
}
```

**Comment by philwebb** [comment]
It's a little hard to tell what's going on from the snippets that you've included. One possible problem might be the `Mockito.clearInvocations(this.repository)` call that you're making. That shouldn't be required.

If you'd like us to investigate further could you please provide a complete sample application that we can clone/download and run.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
