### ISSUE TITLE
Building a RestTemplate using RestTemplateBuilder fails with a ClassNotFoundException when OkHttp 2 is on the classpath

### ISSUE THREAD

**Issue by jmirc** [spring-projects/spring-boot#13314]
I just updated a project with Spring Boot 2.0.2 and I am getting the following exception

```
Caused by: java.lang.IllegalArgumentException: Could not find class [org.springframework.http.client.OkHttpClientHttpRequestFactory]
	at org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:313)
	at org.springframework.boot.web.client.RestTemplateBuilder.detectRequestFactory(RestTemplateBuilder.java:600)
	at org.springframework.boot.web.client.RestTemplateBuilder.configureRequestFactory(RestTemplateBuilder.java:566)
	at org.springframework.boot.web.client.RestTemplateBuilder.configure(RestTemplateBuilder.java:535)
	at org.springframework.boot.web.client.RestTemplateBuilder.build(RestTemplateBuilder.java:523)
	at org.springframework.boot.web.client.RestTemplateBuilder.build(RestTemplateBuilder.java:509)
	at org.springframework.boot.test.web.client.TestRestTemplate.<init>(TestRestTemplate.java:133)
```

The `RestTemplateBuilder` is trying to validate if some HTTP client factories exist and the `org.springframework.http.client.OkHttpClientHttpRequestFactory` doesn't exist anymore in Spring Framework.

**Comment by wilkinsona** [comment]
Thanks for the report. Which version of Spring Boot were you using before you upgraded?

**Comment by jmirc** [comment]
I used the version 2.0.1

**Comment by wilkinsona** [comment]
Thanks. That's rather surprising as support for OkHttp 2 was [dropped from Spring Framework in 5.0.0.RC1](https://github.com/spring-projects/spring-framework/commit/47c4cf7abf231018e102bf51d83dd92c656f8996#diff-236d76a32498dc4077feba20b487d555). We've missed aligning `RestTemplateBuilder` with that, but I would not expect an upgrade from Spring Boot 2.0.1 to 2.0.2 to trigger the problem. Rather, any Spring Boot 2.0.x version should be affected. Perhaps you could clarify the situation by providing a small sample that works with 2.0.1 and fails with 2.0.2?

**Comment by wilkinsona** [comment]
Thanks, @chrismathews. Your analysis matches my own which is why I was surprised that @jmirc had only seen the problem when upgrading from 2.0.2 to 2.0.1.

**Comment by chrismathews** [comment]
Thanks for the quick turnaround Andy!

**Comment by jmirc** [comment]
Hi Andy, sorry for my late reply. I checked why with the Spring Boot 2.0.1.RELEASE I didn't get the issue. 

I didn't get the issue with the previous version because of the `RestTemplateBuilder` class that used the apache http client library provided by `spring-cloud-commons`.
With the Spring Boot 2.0.2.RELEASE, the apache http client library is not provided any more and the `RestTemplateBuilder` class used the okhttp client that I have on the classpath.
