### ISSUE TITLE
Actuator info endpoint in Boot 2.0.2 fails due to EnvironmentInfoContributor throwing BindException

### ISSUE THREAD

**Issue by marcelstoer** [spring-projects/spring-boot#13481]
Calling the actuator info endpoint in Boot 2.0.2 fails with
```
org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'info' to java.util.Map<java.lang.String, java.lang.Object>
	at org.springframework.boot.context.properties.bind.Binder.handleBindError(Binder.java:250) ~[spring-boot-2.0.2.RELEASE.jar:2.0.2.RELEASE]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:226) ~[spring-boot-2.0.2.RELEASE.jar:2.0.2.RELEASE]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:210) ~[spring-boot-2.0.2.RELEASE.jar:2.0.2.RELEASE]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:166) ~[spring-boot-2.0.2.RELEASE.jar:2.0.2.RELEASE]
	at org.springframework.boot.actuate.info.EnvironmentInfoContributor.contribute(EnvironmentInfoContributor.java:47) ~[spring-boot-actuator-2.0.2.RELEASE.jar:2.0.2.RELEASE]
	at org.springframework.boot.actuate.info.InfoEndpoint.info(InfoEndpoint.java:52) ~[spring-boot-actuator-2.0.2.RELEASE.jar:2.0.2.RELEASE]
...
Caused by: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [java.util.Map<java.lang.String, java.lang.Object>]
	at org.springframework.core.convert.support.GenericConversionService.handleConverterNotFound(GenericConversionService.java:321) ~[spring-core-5.0.6.RELEASE.jar:5.0.6.RELEASE]
...
```

I'm a bit lost digging up more detailed information as to what could cause this.

Looks related to #11892 and #11216.

**Comment by wilkinsona** [comment]
> I'm a bit lost digging up more detailed information as to what could cause this.

It will be caused by the properties that begin `info.` in your application's `Environment`. Could you use the `env` endpoint to look for all such properties and let us know their keys and values?

**Comment by marcelstoer** [comment]
> It will be caused by the properties that begin `info.`

That much I figured by going through your code. A manual scan over the config files in the environment didn't reveal anything suspicious, though.

> use the `env` endpoint to look for all such properties

Thanks Andy, good point. Didn't think of this. Will report back if I can reproduce the issue.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by marcelstoer** [comment]
Sorry, can't reproduce atm.

**Comment by tarmo-randma** [comment]
I get the same error every time I disable avtuator endpoint by default and enable info with a separately with an yml formatted file.

This produces error:
```
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /api/core/actuator
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true
```

This works as expected:
```
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /api/core/actuator
      exposure:
        include: "*"
  endpoint.info.enabled: true
```

If I look at the /env endpoint when info is producing the error, what I noticed was that the parameters from my application.yml were included twice and in one of the sections the parameters were interpreted incorrectly as if the file was not parsed as yml. I will copy the truncated version of the env output below.

```
{
  "activeProfiles" : [ ],
  "propertySources" : [ {
    "name" : "server.ports",
    "properties" : {
      "local.server.port" : {
        "value" : 8443
      }
    }
  }, {
    "name" : "servletContextInitParams",
    "properties" : { }
  }, {
    "name" : "systemProperties",
    "properties" : {
      "redacted" : {}
    }
  }, {
    "name" : "systemEnvironment",
    "properties" : {
      "redacted" : {}
    }
  }, {
    "name" : "applicationConfig: [classpath:/application.yml]",
    "properties" : {
      "partly redacted" : {},
      "management.endpoints.enabled-by-default" : {
        "value" : false,
        "origin" : "class path resource [application.yml]:38:25"
      },
      "management.endpoints.web.base-path" : {
        "value" : "/api/core/actuator",
        "origin" : "class path resource [application.yml]:40:18"
      },
      "management.endpoints.web.exposure.include" : {
        "value" : "*",
        "origin" : "class path resource [application.yml]:42:18"
      },
      "management.endpoint.env.enabled" : {
        "value" : true,
        "origin" : "class path resource [application.yml]:53:16"
      },
      "management.endpoint.health.show-details" : {
        "value" : "when_authorized",
        "origin" : "class path resource [application.yml]:55:21"
      },
      "management.endpoint.health.enabled" : {
        "value" : true,
        "origin" : "class path resource [application.yml]:56:16"
      },
      "management.endpoint.info.enabled" : {
        "value" : true,
        "origin" : "class path resource [application.yml]:60:16"
      },
    }
  }, {
    "name" : "class path resource [version.properties]",
    "properties" : {
      "redacted" : {}
    }
  }, {
    "name" : "class path resource [application.yml]",
    "properties" : {
      "exposure" : {
        "value" : ""
      },
      "env" : {
        "value" : ""
      },
      "web" : {
        "value" : ""
      },
      "base-path" : {
        "value" : "/api/core/actuator"
      },
      "health" : {
        "value" : ""
      },
      "endpoint" : {
        "value" : ""
      },
      "show-details" : {
        "value" : "when_authorized"
      },
      "endpoints" : {
        "value" : ""
      },
      "enabled-by-default" : {
        "value" : "false"
      },
      "info" : {
        "value" : ""
      }
    }
  } ]
}
```

**Comment by wilkinsona** [comment]
@tarmo-randma We never managed to reproduce this one. If you can turn those snippets into a complete and minimal sample (as a zip attached to this issue or in a separate git repository) we can re-open this and take another look.
