### ISSUE TITLE
java.io.FileNotFoundException: ReactiveWebContext resource [liquibase] cannot be resolved to URL

### ISSUE THREAD

**Issue by zhaichen** [spring-projects/spring-boot#13499]
I had this problem too, used spring-boot-version: 2.0.3.RELEASE, The liquibase jira bug over there is unattended

bug url：https://liquibase.jira.com/browse/CORE-3121

```
java.io.FileNotFoundException: ReactiveWebContext resource [liquibase] cannot be resolved to URL
	at org.springframework.core.io.AbstractResource.getURL(AbstractResource.java:100)
	at liquibase.integration.spring.SpringLiquibase$SpringResourceOpener.init(SpringLiquibase.java:114)
	at liquibase.resource.ClassLoaderResourceAccessor.<init>(ClassLoaderResourceAccessor.java:25)
	at liquibase.integration.spring.SpringLiquibase$SpringResourceOpener.<init>(SpringLiquibase.java:71)
	at liquibase.integration.spring.SpringLiquibase.createResourceOpener(SpringLiquibase.java:486)
	at liquibase.integration.spring.SpringLiquibase.createLiquibase(SpringLiquibase.java:436)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:386)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1767)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1704)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:581)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:503)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:61)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243)
```

**Comment by snicoll** [comment]
@zhaichen please do not open duplicate issues, that’s not going to change our position on #10625. If we do we can reopen that one.
