### ISSUE TITLE
IllegalArgumentException: URI has an authority component when UNC path is on Classpath

### ISSUE THREAD

**Issue by cyberdreamandroid** [spring-projects/spring-boot#13493]
Starting with Spring Boot 2.0.2, we get an Exception when starting a spring boot webserver (tomcat or jetty) on command line. This only happens when we use an UNC path on our classpath (needed for configuration files and log4j.properties). Everything worked with 2.0.0 and 2.0.1.

Stacktrace:

```
Caused by: java.lang.IllegalArgumentException: URI has an authority component
        at java.io.File.<init>(File.java:423) ~[na:1.8.0_121]
        at org.springframework.boot.web.servlet.server.StaticResourceJars.toFile(StaticResourceJars.java:75) ~[spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
        at org.springframework.boot.web.servlet.server.StaticResourceJars.addUrl(StaticResourceJars.java:86) ~[spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
        at org.springframework.boot.web.servlet.server.StaticResourceJars.getUrlsFrom(StaticResourceJars.java:58) ~[spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
        at org.springframework.boot.web.servlet.server.StaticResourceJars.getUrls(StaticResourceJars.java:45) ~[spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
        at org.springframework.boot.web.servlet.server.AbstractServletWebServerFactory.getUrlsOfJarsWithMetaInfResources(AbstractServletWebServerFactory.java:282) ~[spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
        at org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory.configureDocumentRoot(JettyServletWebServerFactory.java:268) ~[spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
        ... 12 common frames omitted
```

**Comment by wilkinsona** [comment]
This looks somewhat similar to https://github.com/spring-projects/spring-boot/issues/13265. I suspect that 1.5.x may be affected too.

**Comment by wilkinsona** [comment]
1.5.x does not appeared to be affected.

**Comment by gwcary** [comment]
A local user was starting a Spring Boot 1.5.19 app with -javaagent:\\rdcx200\EDM\tpj\aspectjweaver.jar and getting the IllegalArgumentException. This appears to be a change from earlier versions of Spring Boot.

**Comment by wilkinsona** [comment]
@gwcary I can't see the connection between your comment and this issue. The change made in this issue was only made in 2.0.4 and later. If you believe you've seen a change between 1.5.19 and an earlier version, I don't think it's related to this issue. If you would like us to investigate, please open a new issue with a minimal sample that reproduces the problem.
