### ISSUE TITLE
Unable to start up application due to missing EmbeddedServletContainerFactory bean

### ISSUE THREAD

**Issue by wjam** [spring-projects/spring-boot#1351]
An application which has just been upgraded to 1.1.5 no longer starts up and instead throws an exception. The workaround for the issue to is specify a dependency on `spring-boot-starter-tomcat` in the pom.

```
Caused by: org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.getEmbeddedServletContainerFactory(EmbeddedWebApplicationContext.java:185)
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:158)
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:132)
    ... 7 more
```

**Comment by yoting** [comment]
You can use default server tomcat, not use jetty.
