### ISSUE TITLE
When using the Actuator, an app with a custom DispatcherServlet bean named dispatcherServlet fails to start

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#13527]
The changes made to fix https://github.com/spring-projects/spring-boot/issues/12934 and https://github.com/spring-projects/spring-boot/issues/13106 mean that an app like this:

```java
package com.example.demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.web.servlet.DispatcherServlet;

@SpringBootApplication
public class CustomDispatcherServletApplication {

	public static void main(String[] args) {
		SpringApplication.run(CustomDispatcherServletApplication.class, args);
	}

	@Bean
	public DispatcherServlet dispatcherServlet() {
		return new DispatcherServlet();
	}

}
```

Will fail to start with a failure like this:

```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.0.3.RELEASE)

2018-06-19 20:20:20.305  INFO 8473 --- [           main] c.e.d.CustomDispatcherServletApplication : Starting CustomDispatcherServletApplication on aw-rmbp.local with PID 8473 (/Users/awilkinson/dev/workspaces/spring/spring-boot/2.0.x/custom-dispatcher-servlet/target/classes started by awilkinson in /Users/awilkinson/dev/workspaces/spring/spring-boot/2.0.x/custom-dispatcher-servlet)
2018-06-19 20:20:20.308  INFO 8473 --- [           main] c.e.d.CustomDispatcherServletApplication : No active profile set, falling back to default profiles: default
2018-06-19 20:20:20.352  INFO 8473 --- [           main] ConfigServletWebServerApplicationContext : Refreshing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@35083305: startup date [Tue Jun 19 20:20:20 BST 2018]; root of context hierarchy
2018-06-19 20:20:21.517  INFO 8473 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2018-06-19 20:20:21.541  INFO 8473 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2018-06-19 20:20:21.542  INFO 8473 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.31
2018-06-19 20:20:21.550  INFO 8473 --- [ost-startStop-1] o.a.catalina.core.AprLifecycleListener   : The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/Users/awilkinson/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.]
2018-06-19 20:20:21.643  INFO 8473 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2018-06-19 20:20:21.643  INFO 8473 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1294 ms
2018-06-19 20:20:21.872 ERROR 8473 --- [ost-startStop-1] o.s.b.web.embedded.tomcat.TomcatStarter  : Error starting Tomcat context. Exception: org.springframework.beans.factory.BeanCreationException. Message: Error creating bean with name 'servletEndpointRegistrar' defined in class path resource [org/springframework/boot/actuate/autoconfigure/endpoint/web/ServletEndpointManagementContextConfiguration$WebMvcServletEndpointManagementContextConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.endpoint.web.ServletEndpointRegistrar]: Factory method 'servletEndpointRegistrar' threw exception; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.boot.autoconfigure.web.servlet.DispatcherServletPathProvider' available
2018-06-19 20:20:21.889  INFO 8473 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2018-06-19 20:20:21.894  WARN 8473 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
2018-06-19 20:20:21.902  INFO 8473 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-06-19 20:20:22.007 ERROR 8473 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Method servletEndpointRegistrar in org.springframework.boot.actuate.autoconfigure.endpoint.web.ServletEndpointManagementContextConfiguration$WebMvcServletEndpointManagementContextConfiguration required a bean of type 'org.springframework.boot.autoconfigure.web.servlet.DispatcherServletPathProvider' that could not be found.
	- Bean method 'mainDispatcherServletPathProvider' not loaded because Default DispatcherServlet found dispatcher servlet bean dispatcherServlet


Action:

Consider revisiting the conditions above or defining a bean of type 'org.springframework.boot.autoconfigure.web.servlet.DispatcherServletPathProvider' in your configuration.
```

I'm not entirely sure how to fix this. We need to get hold of the dispatcher servlet that's going to dispatch to any servlet endpoints and get the path to which it's mapped.

`EndpointRequest` falls back to `""` if there's no `DispatcherServletPathProvider` but I'm not sure that's right either.

**Comment by lpetit-yseop** [comment]
I am facing this issue at work.

The workaround I found at the moment is to add the missing bean, like this:

```java
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

@Component
public class DispatcherServletPathProvider implements org.springframework.boot.autoconfigure.web.servlet.DispatcherServletPathProvider {

    @Value("${server.servlet.context-path}")
    private String servletContextPath;

    @Override
    public String getServletPath() {
        return servletContextPath;
    }

}
```

I don't know whether having a default implementation like this for this bean would solve the issue generically?

**Comment by wilkinsona** [comment]
@lpetit-yseop That's a good workaround, but I think you want to use `server.servlet.path` rather than `server.servlet.context-path`.

A generic solution is more complicated if we want to cope with custom dispatcher servlet registration beans. They may not be using the `server.servlet.path` property to configure the servlet's URL mapping(s) so we'd need to find the registration bean and reverse engineer the path from its URL mapping.

**Comment by lpetit-yseop** [comment]
Thank you for the confirmation.

I am having a hard time truly understanding the relation between `server.servlet.context-path` and `server.servlet.path`.
Currently, I only find light descriptions in the Spring Boot documentation like `server.servlet.path=/ # Path of the main dispatcher servlet.`, no mention in the Spring MVC documentation…

Did I miss some place where it is documented, like "the full real path for controllers results in `/${server.servlet.context-path}/${server.servlet.path}` being pre-pended to routes defined at the controller-level, etc.?

**Comment by lpetit-yseop** [comment]
So, if I want my workaround to be more resilient to future unexpected changes, should I be using a combination of `server.servlet.context-path` and `server.servlet.path` (like `return servletContextPath + "/" + servletPath;`) or only `servletPath` as you mention?

**Comment by ranarula** [comment]
I was looking at the fix done for spring-projects/spring-boot#13106 . Unfortunately the fix is breaking a few of our integration test when we are trying to upgrade to SpringBoot 2.0.3 from 2.0.2. It for scenarios when need MVC context with Jersey. We need MVC with Jersey for cases when we need to serve static files? 

We are seeing the following error
```
Method servletEndpointRegistrar in org.springframework.boot.actuate.autoconfigure.endpoint.web.ServletEndpointManagementContextConfiguration$WebMvcServletEndpointManagementContextConfiguration required a bean of type 'org.springframework.boot.autoconfigure.web.servlet.DispatcherServletPathProvider' that could not be found.
    - Bean method 'mainDispatcherServletPathProvider' not loaded because Default DispatcherServlet found non dispatcher servlet bean dispatcherServlet

Action:

Consider revisiting the conditions above or defining a bean of type 'org.springframework.boot.autoconfigure.web.servlet.DispatcherServletPathProvider' in your configuration.
```

I feel line 57 in ServletEndpointManagementContextConfiguration.java should have another condition as @Conditional(DefaultDispatcherServletCondition.class)

The work around we are using for now is to have the following config in our tests 
```
   @Bean
   @Primary
    public DispatcherServletPathProvider testDispatcherServletPathProvider() {
      return () -> "";
    }
```

**Comment by mbhave** [comment]
@ranarula I think that's a slightly different issue than the one being discussed here. Could raise a separate issue with a minimal sample that reproduces the behavior you described?

**Comment by ranarula** [comment]
Thanks @mbhave, Will create a sample and an issue but seems its related to this in a sense that in my case instead of a custom DispatcherServlet we have a real DispatcherServlet from MVC in the context

Though looking at it closely seems just adding the the above suggested change might not work alone as there is `@ConditionalOnMissingClass` on Jersey config

**Comment by ltorzynski** [comment]
This bug still exists in 2.0.4.RELEASE

**Comment by ltorzynski** [comment]
This issue still exists in 2.0.4.RELEASE. Having custom DispatcherServlet defined and during startup, following error occurs:

> Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.boot.autoconfigure.web.servlet.DispatcherServletPath' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:346)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:333)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:344)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:333)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:344)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:333)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1107)
	at org.springframework.boot.actuate.autoconfigure.endpoint.web.ServletEndpointManagementContextConfiguration$WebMvcServletEndpointManagementContextConfiguration.servletEndpointRegistrar(ServletEndpointManagementContextConfiguration.java:72)
	at org.springframework.boot.actuate.autoconfigure.endpoint.web.ServletEndpointManagementContextConfiguration$WebMvcServletEndpointManagementContextConfiguration$$EnhancerBySpringCGLIB$$3c361396.CGLIB$servletEndpointRegistrar$0(<generated>)
	at org.springframework.boot.actuate.autoconfigure.endpoint.web.ServletEndpointManagementContextConfiguration$WebMvcServletEndpointManagementContextConfiguration$$EnhancerBySpringCGLIB$$3c361396$$FastClassBySpringCGLIB$$7b0e7375.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361)
	at org.springframework.boot.actuate.autoconfigure.endpoint.web.ServletEndpointManagementContextConfiguration$WebMvcServletEndpointManagementContextConfiguration$$EnhancerBySpringCGLIB$$3c361396.servletEndpointRegistrar(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 70 more

**Comment by snicoll** [comment]
@ltorzynski that's not the same bug at all, please look at the stacktrace. If you register your own `DispatcherServlet` you need to provide a bean of type `DispatcherServletPath` that provides the path of the "main" dispatcher servlet. If you have a single dispatcher servlet and you need to register it yourself, the easiest is to use `DispatcherServletRegistrationBean`. I can see that's not documented properly so I've created #14145

**Comment by ltorzynski** [comment]
@snicoll  thanks for explanations -  I am migrating from 1.5.X to 2.0.X and just found this.

Now I understand, but this is strange - DispatcherServletRegistrationBean is from org.springframework.boot.autoconfigure.web.servlet package and is documented as: "ServletRegistrationBean} for the auto-configured {@link DispatcherServlet}". If it is now also required for manual registration of DispatcherServlet both its package and documentation should be updated.

**Comment by snicoll** [comment]
>  If it is now also required for manual registration of DispatcherServlet both its package and documentation should be updated.

It isn't, it's just a convenience. Can you join us [on Gitter](https://github.com/spring-projects/spring-boot)? We should stop hijacking this issue and I'd be interested to understand why you need a custom `DispatcherServlet` setup.

**Comment by philwebb** [comment]
@chrisleves Can you please open a new issue and provide a sample application that shows the problem.
