### ISSUE TITLE
FileNotFoundException while file exists

### ISSUE THREAD

**Issue by bahrmichael** [spring-projects/spring-boot#13553]
**Bug**

Spring fails to build the configuration context due to a `FileNotFoundException`. This file however is created a couple seconds before, as shown by the File Log below.

File created: 14:14:42
FileNotFoundException: 14:15:07

Tomcat version: 8.0.49
Spring Boot version: 1.5.12.RELEASE

We're not using the embedded tomcat, but a provided one via the cargo-maven2-plugin.

I am trying to understand why this is the case and what could be done to read the file.

```
    22-06 14:15:07,558 [localhost-startStop-1][] ERROR org.springframework.boot.SpringApplication    (771) - Application startup failed
    org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [com.vw.mbbc.registrationserver.RegistrationserverWebappApplication]; nested exception is java.io.FileNotFoundException: Could not open ServletContext resource [/path/to/myapp.properties]
    	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:183) ~[spring-context-4.3.16.RELEASE.jar:4.3.16.RELEASE]
    	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:308) ~[spring-context-4.3.16.RELEASE.jar:4.3.16.RELEASE]
    	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:228) ~[spring-context-4.3.16.RELEASE.jar:4.3.16.RELEASE]
    	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:272) ~[spring-context-4.3.16.RELEASE.jar:4.3.16.RELEASE]
    	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:92) ~[spring-context-4.3.16.RELEASE.jar:4.3.16.RELEASE]
    	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687) ~[spring-context-4.3.16.RELEASE.jar:4.3.16.RELEASE]
    	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:525) ~[spring-context-4.3.16.RELEASE.jar:4.3.16.RELEASE]
    	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.12.RELEASE.jar:1.5.12.RELEASE]
    	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.12.RELEASE.jar:1.5.12.RELEASE]
    	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.12.RELEASE.jar:1.5.12.RELEASE]
    	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.12.RELEASE.jar:1.5.12.RELEASE]
    	at org.springframework.boot.web.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:154) [spring-boot-1.5.12.RELEASE.jar:1.5.12.RELEASE]
    	at org.springframework.boot.web.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:134) [spring-boot-1.5.12.RELEASE.jar:1.5.12.RELEASE]
    	at org.springframework.boot.web.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:87) [spring-boot-1.5.12.RELEASE.jar:1.5.12.RELEASE]
    	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:169) [spring-web-4.3.16.RELEASE.jar:4.3.16.RELEASE]
    	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5302) [catalina.jar:8.0.49]
    	at com.vw.mbbc.registrationserver.access.EnhancedContext.startInternal(EnhancedContext.java:133) [registration-tomcat.jar:?]
    	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145) [catalina.jar:8.0.49]
    	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:753) [catalina.jar:8.0.49]
    	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729) [catalina.jar:8.0.49]
    	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717) [catalina.jar:8.0.49]
    	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:974) [catalina.jar:8.0.49]
    	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1850) [catalina.jar:8.0.49]
    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_162]
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
    	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
    Caused by: java.io.FileNotFoundException: Could not open ServletContext resource [/path/to/myapp.properties]
    	at org.springframework.web.context.support.ServletContextResource.getInputStream(ServletContextResource.java:141) ~[spring-web-4.3.16.RELEASE.jar:4.3.16.RELEASE]
    	at org.springframework.core.io.support.EncodedResource.getInputStream(EncodedResource.java:154) ~[spring-core-4.3.16.RELEASE.jar:4.3.16.RELEASE]
    	at org.springframework.core.io.support.PropertiesLoaderUtils.fillProperties(PropertiesLoaderUtils.java:98) ~[spring-core-4.3.16.RELEASE.jar:4.3.16.RELEASE]
    	at org.springframework.core.io.support.PropertiesLoaderUtils.fillProperties(PropertiesLoaderUtils.java:72) ~[spring-core-4.3.16.RELEASE.jar:4.3.16.RELEASE]
    	at org.springframework.core.io.support.PropertiesLoaderUtils.loadProperties(PropertiesLoaderUtils.java:58) ~[spring-core-4.3.16.RELEASE.jar:4.3.16.RELEASE]
    	at org.springframework.core.io.support.ResourcePropertySource.<init>(ResourcePropertySource.java:65) ~[spring-core-4.3.16.RELEASE.jar:4.3.16.RELEASE]
    	at org.springframework.core.io.support.DefaultPropertySourceFactory.createPropertySource(DefaultPropertySourceFactory.java:36) ~[spring-core-4.3.16.RELEASE.jar:4.3.16.RELEASE]
    	at org.springframework.context.annotation.ConfigurationClassParser.processPropertySource(ConfigurationClassParser.java:442) ~[spring-context-4.3.16.RELEASE.jar:4.3.16.RELEASE]
    	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:273) ~[spring-context-4.3.16.RELEASE.jar:4.3.16.RELEASE]
    	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:247) ~[spring-context-4.3.16.RELEASE.jar:4.3.16.RELEASE]
    	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:192) ~[spring-context-4.3.16.RELEASE.jar:4.3.16.RELEASE]
    	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:294) ~[spring-context-4.3.16.RELEASE.jar:4.3.16.RELEASE]
    	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:247) ~[spring-context-4.3.16.RELEASE.jar:4.3.16.RELEASE]
    	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:200) ~[spring-context-4.3.16.RELEASE.jar:4.3.16.RELEASE]
    	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:169) ~[spring-context-4.3.16.RELEASE.jar:4.3.16.RELEASE]
    	... 27 more
```

File Log

```
    Fri Jun 22 14:14:41 CEST 2018
    ls: /path/to/myapp.properties: No such file or directory
    Fri Jun 22 14:14:42 CEST 2018
    -rw-r--r--  1 michaelbahr  staff  157 Jun 22 14:14:42 2018 /path/to/myapp.properties
    Fri Jun 22 14:14:43 CEST 2018
    -rw-r--r--  1 michaelbahr  staff  157 Jun 22 14:14:43 2018 /path/to/myapp.properties
```

Pom Excerpt

```
<tomcat.version>8.0.49</tomcat.version>
...
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jersey</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-tomcat</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

...

            <dependency>
                <groupId>org.apache.tomcat</groupId>
                <artifactId>tomcat-catalina</artifactId>
                <version>${tomcat.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.apache.tomcat</groupId>
                <artifactId>tomcat-coyote</artifactId>
                <version>${tomcat.version}</version>
                <scope>provided</scope>
            </dependency>
```

Paths are absolute and were reduced for privacy, but do match 100%.

Please let me know what further information I can provide to investigate. I'm not able to provide a reproducer.

**Comment by wilkinsona** [comment]
Accessing a resource via the servlet context, as is being done here, is not the same as accessing it directly on the file system. A file existing at `/path/to/myapp.properties` on the filesystem will not be available at `/path/to/myapp.properties` via the servlet context.

> I'm not able to provide a reproducer.

Unfortunately, without a reproducer, it's going to be very hard to diagnose this. All I can say at the moment is that you expectation about how resources can be access via the servlet context appears to be incorrect. If you would like us to spend some time trying to help you, please spend some time to provide a project that reproduces the problem.

**Comment by bahrmichael** [comment]
Thanks for the hint on the difference between servlet context and file system. I did not know that exists and will read into it. If you have any links on that topic I would appreciate them :)

**Comment by philwebb** [comment]
@bahrmichael There is some API documentation on [ServletContextResource](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/context/support/ServletContextResource.html) that might help. Ultimately that class delegates to the `ServletContext` so you might want to look at the [getResource](https://docs.oracle.com/javaee/6/api/javax/servlet/ServletContext.html#getResource(java.lang.String)) and [getResourceAsStream](https://docs.oracle.com/javaee/6/api/javax/servlet/ServletContext.html#getResourceAsStream(java.lang.String)) documentation.

If those links don't help, I'd suggest asking on stackoverflow.com

**Comment by bahrmichael** [comment]
Thanks for your help!
