### ISSUE TITLE
application/stream+x-jackson-smile doesn't work in WebFlux

### ISSUE THREAD

**Issue by robertdanci** [spring-projects/spring-boot#13759]
I'm creating a new issue in reference to #10756 as it doesn't seem to work in the latest spring boot release.

The code to reproduce is the same as in the referenced issue.

Dependencies:
spring boot 2.0.3.RELEASE 
jackson-dataformat-smile 2.8.9
spring 5.0.7.RELEASE

Relevant stack trace:

```
java.lang.UnsupportedOperationException: Non-blocking source not (yet?) support for this format (Smile)

	at com.fasterxml.jackson.core.JsonFactory._requireJSONFactory(JsonFactory.java:1605)
	at com.fasterxml.jackson.core.JsonFactory.createNonBlockingByteArrayParser(JsonFactory.java:962)
	at org.springframework.http.codec.json.Jackson2Tokenizer.tokenize(Jackson2Tokenizer.java:83)
	at org.springframework.http.codec.json.AbstractJackson2Decoder.tokenize(AbstractJackson2Decoder.java:93)
	at org.springframework.http.codec.json.AbstractJackson2Decoder.decode(AbstractJackson2Decoder.java:78)
	at org.springframework.http.codec.DecoderHttpMessageReader.read(DecoderHttpMessageReader.java:87)
	at org.springframework.web.reactive.function.BodyExtractors.lambda$null$3(BodyExtractors.java:151)
	at org.springframework.web.reactive.function.BodyExtractors$$Lambda$261/808447015.apply(Unknown Source)
	at java.util.Optional.map(Optional.java:215)
	at org.springframework.web.reactive.function.BodyExtractors.readWithMessageReaders(BodyExtractors.java:249)
	at org.springframework.web.reactive.function.BodyExtractors.lambda$toFlux$5(BodyExtractors.java:142)
	at org.springframework.web.reactive.function.BodyExtractors$$Lambda$260/707635461.extract(Unknown Source)
	at org.springframework.web.reactive.function.client.DefaultClientResponse.body(DefaultClientResponse.java:87)
	at org.springframework.web.reactive.function.client.DefaultClientResponse.bodyToFlux(DefaultClientResponse.java:140)
	at org.springframework.test.web.reactive.server.DefaultWebTestClient$DefaultResponseSpec.returnResult(DefaultWebTestClient.java:358)
```

**Comment by wilkinsona** [comment]
Thanks, but as discussed in #10756, the code that reproduces the problem doesn't use Spring Boot. If there's an issue somewhere I suspect it will either be in Spring Framework or in Jackson. Note that Framework 5 is compiled and tested against Jackson 2.9, and that's also the version provided by Boot's dependency management. I'd recommend that you test against Jackson 2.9.x. If the problem persists, I'd then review https://jira.spring.io/browse/SPR-16151. After doing so, if you still believe there's a problem, you could consider opening a Spring Framework or Jackson issue depending on where you believe the problem lies.

**Comment by robertdanci** [comment]
I've tested against Jackson 2.9.x and it works! 
Thanks
