### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.server.handler.gzip.GzipHandler

### ISSUE THREAD

**Issue by zhangshuge** [spring-projects/spring-boot#13758]
I used the 1.5.2.release version, replacing the tomcat container with jetty, and the application started the following exception from The Times.Need separate, please introduce org. Eclipse. Jetty. The server handler. Gzip. GzipHandler bag?

Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.server.handler.gzip.GzipHandler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_111]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_111]
	at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainerFactory.getEmbeddedServletContainer(JettyEmbeddedServletContainerFactory.java:170) ~[spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:164) ~[spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:134) ~[spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	... 8 more

**Comment by wilkinsona** [comment]
I would guess that the Jetty jar that contains GZipHandler is corrupted. Try deleting it from Maven’s cache and rebuilding your application. Alternatively, and you should do this anyway, upgrade to Spring Boot 1.5.14 which will cause a new version of Jetty to be downloaded. If this doesn’t help, please provide a minimal sample that reproduces the problem and we can re-open the issue and investigate.

**Comment by zhangshuge** [comment]
@wilkinsona  thanks!
