### ISSUE TITLE
Handling request when using undertow behaves different to the default reactor-netty

### ISSUE THREAD

**Issue by NeoGitCrt1** [spring-projects/spring-boot#13764]
I have a simple request using webflux style aiming to response records from db finding by the requested id.

when using the default reactor-netty it works fine,but when switched to undertow the same code throws exception as below:
```
2018-07-13 10:11:00.022 ERROR [c,fea81dbc8c8e46d0,517edad308a8e9fa,false] 1100 --- [ntLoopGroup-2-2] o.s.w.s.adapter.HttpWebHandlerAdapter    : Failed to handle request [POST http://192.168.12.30:6878/hi]

java.lang.IllegalStateException: UT000002: The response has already been started
	at io.undertow.server.HttpServerExchange.setStatusCode(HttpServerExchange.java:1406) ~[undertow-core-1.4.25.Final.jar:1.4.25.Final]
	at org.springframework.http.server.reactive.UndertowServerHttpResponse.applyStatusCode(UndertowServerHttpResponse.java:77) ~[spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.http.server.reactive.AbstractServerHttpResponse.lambda$null$4(AbstractServerHttpResponse.java:214) ~[spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at reactor.core.publisher.MonoRunnable.subscribe(MonoRunnable.java:42) ~[reactor-core-3.1.8.RELEASE.jar:3.1.8.RELEASE]
	at reactor.core.publisher.MonoLift.subscribe(MonoLift.java:46) ~[reactor-core-3.1.8.RELEASE.jar:3.1.8.RELEASE]
	at reactor.core.publisher.MonoOnAssembly.subscribe(MonoOnAssembly.java:76) ~[reactor-core-3.1.8.RELEASE.jar:3.1.8.RELEASE]
	at reactor.core.publisher.Mono.subscribe(Mono.java:3080) ~[reactor-core-3.1.8.RELEASE.jar:3.1.8.RELEASE]
	at reactor.core.publisher.FluxConcatIterable$ConcatIterableSubscriber.onComplete(FluxConcatIterable.java:147) ~[reactor-core-3.1.8.RELEASE.jar:3.1.8.RELEASE]
	at reactor.core.publisher.FluxConcatIterable.subscribe(FluxConcatIterable.java:61) ~[reactor-core-3.1.8.RELEASE.jar:3.1.8.RELEASE]
	at reactor.core.publisher.FluxLift.subscribe(FluxLift.java:46) ~[reactor-core-3.1.8.RELEASE.jar:3.1.8.RELEASE]
	at reactor.core.publisher.FluxOnAssembly.subscribe(FluxOnAssembly.java:252) ~[reactor-core-3.1.8.RELEASE.jar:3.1.8.RELEASE]
	at reactor.core.publisher.MonoIgnoreElements.subscribe(MonoIgnoreElements.java:37) ~[reactor-core-3.1.8.RELEASE.jar:3.1.8.RELEASE]
	at reactor.core.publisher.MonoLift.subscribe(MonoLift.java:46) ~[reactor-core-3.1.8.RELEASE.jar:3.1.8.RELEASE]
	at reactor.core.publisher.MonoOnAssembly.subscribe(MonoOnAssembly.java:76) ~[reactor-core-3.1.8.RELEASE.jar:3.1.8.RELEASE]
	at reactor.core.publisher.Mono.subscribe(Mono.java:3080) ~[reactor-core-3.1.8.RELEASE.jar:3.1.8.RELEASE]
	at org.springframework.http.server.reactive.ChannelSendOperator$WriteBarrier.onNext(ChannelSendOperator.java:181) ~[spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:450) ~[reactor-core-3.1.8.RELEASE.jar:3.1.8.RELEASE]
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:81) ~[spring-cloud-sleuth-core-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:115) ~[reactor-core-3.1.8.RELEASE.jar:3.1.8.RELEASE]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:450) ~[reactor-core-3.1.8.RELEASE.jar:3.1.8.RELEASE]
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:81) ~[spring-cloud-sleuth-core-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:198) ~[reactor-core-3.1.8.RELEASE.jar:3.1.8.RELEASE]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:450) ~[reactor-core-3.1.8.RELEASE.jar:3.1.8.RELEASE]
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:81) ~[spring-cloud-sleuth-core-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:238) ~[reactor-core-3.1.8.RELEASE.jar:3.1.8.RELEASE]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:450) ~[reactor-core-3.1.8.RELEASE.jar:3.1.8.RELEASE]
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:81) ~[spring-cloud-sleuth-core-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73) ~[reactor-core-3.1.8.RELEASE.jar:3.1.8.RELEASE]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:450) ~[reactor-core-3.1.8.RELEASE.jar:3.1.8.RELEASE]
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:81) ~[spring-cloud-sleuth-core-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:238) ~[reactor-core-3.1.8.RELEASE.jar:3.1.8.RELEASE]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:450) ~[reactor-core-3.1.8.RELEASE.jar:3.1.8.RELEASE]
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:81) ~[spring-cloud-sleuth-core-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:108) ~[reactor-core-3.1.8.RELEASE.jar:3.1.8.RELEASE]
	at com.mongodb.reactivestreams.client.internal.ObservableToPublisher$1.onNext(ObservableToPublisher.java:68) ~[mongodb-driver-reactivestreams-1.7.1.jar:na]
	at com.mongodb.async.client.AbstractSubscription.onNext(AbstractSubscription.java:135) ~[mongodb-driver-async-3.6.4.jar:na]
	at com.mongodb.async.client.AbstractSubscription.processResultsQueue(AbstractSubscription.java:203) ~[mongodb-driver-async-3.6.4.jar:na]
	at com.mongodb.async.client.AbstractSubscription.tryProcessResultsQueue(AbstractSubscription.java:159) ~[mongodb-driver-async-3.6.4.jar:na]
	at com.mongodb.async.client.AbstractSubscription.addToQueue(AbstractSubscription.java:117) ~[mongodb-driver-async-3.6.4.jar:na]
	at com.mongodb.async.client.MongoIterableSubscription$2.onResult(MongoIterableSubscription.java:101) ~[mongodb-driver-async-3.6.4.jar:na]
	at com.mongodb.async.client.MongoIterableSubscription$2.onResult(MongoIterableSubscription.java:87) ~[mongodb-driver-async-3.6.4.jar:na]
	at com.mongodb.operation.AsyncQueryBatchCursor.next(AsyncQueryBatchCursor.java:135) ~[mongodb-driver-core-3.6.4.jar:na]
	at com.mongodb.operation.AsyncQueryBatchCursor.next(AsyncQueryBatchCursor.java:99) ~[mongodb-driver-core-3.6.4.jar:na]
	at com.mongodb.async.client.MongoIterableSubscription.requestMoreData(MongoIterableSubscription.java:87) ~[mongodb-driver-async-3.6.4.jar:na]
	at com.mongodb.async.client.MongoIterableSubscription$1.onResult(MongoIterableSubscription.java:55) ~[mongodb-driver-async-3.6.4.jar:na]
	at com.mongodb.async.client.MongoIterableSubscription$1.onResult(MongoIterableSubscription.java:48) ~[mongodb-driver-async-3.6.4.jar:na]
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49) ~[mongodb-driver-core-3.6.4.jar:na]
	at com.mongodb.async.client.AsyncOperationExecutorImpl$1$1.onResult(AsyncOperationExecutorImpl.java:70) ~[mongodb-driver-async-3.6.4.jar:na]
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49) ~[mongodb-driver-core-3.6.4.jar:na]
	at com.mongodb.operation.FindOperation$3.onResult(FindOperation.java:822) ~[mongodb-driver-core-3.6.4.jar:na]
	at com.mongodb.operation.OperationHelper$ReferenceCountedReleasingWrappedCallback.onResult(OperationHelper.java:353) ~[mongodb-driver-core-3.6.4.jar:na]
	at com.mongodb.operation.CommandOperationHelper$1.onResult(CommandOperationHelper.java:389) ~[mongodb-driver-core-3.6.4.jar:na]
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49) ~[mongodb-driver-core-3.6.4.jar:na]
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor$2.onResult(DefaultServer.java:207) ~[mongodb-driver-core-3.6.4.jar:na]
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49) ~[mongodb-driver-core-3.6.4.jar:na]
	at com.mongodb.connection.CommandProtocolImpl$1.onResult(CommandProtocolImpl.java:102) ~[mongodb-driver-core-3.6.4.jar:na]
	at com.mongodb.connection.DefaultConnectionPool$PooledConnection$1.onResult(DefaultConnectionPool.java:458) ~[mongodb-driver-core-3.6.4.jar:na]
	at com.mongodb.connection.UsageTrackingInternalConnection$2.onResult(UsageTrackingInternalConnection.java:110) ~[mongodb-driver-core-3.6.4.jar:na]
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49) ~[mongodb-driver-core-3.6.4.jar:na]
	at com.mongodb.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:381) ~[mongodb-driver-core-3.6.4.jar:na]
	at com.mongodb.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:359) ~[mongodb-driver-core-3.6.4.jar:na]
	at com.mongodb.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:651) ~[mongodb-driver-core-3.6.4.jar:na]
	at com.mongodb.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:618) ~[mongodb-driver-core-3.6.4.jar:na]
	at com.mongodb.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:487) ~[mongodb-driver-core-3.6.4.jar:na]
	at com.mongodb.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:484) ~[mongodb-driver-core-3.6.4.jar:na]
	at com.mongodb.connection.netty.NettyStream.readAsync(NettyStream.java:236) ~[mongodb-driver-core-3.6.4.jar:na]
	at com.mongodb.connection.InternalStreamConnection.readAsync(InternalStreamConnection.java:484) ~[mongodb-driver-core-3.6.4.jar:na]
	at com.mongodb.connection.InternalStreamConnection.access$1100(InternalStreamConnection.java:74) ~[mongodb-driver-core-3.6.4.jar:na]
	at com.mongodb.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:608) ~[mongodb-driver-core-3.6.4.jar:na]
	at com.mongodb.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:593) ~[mongodb-driver-core-3.6.4.jar:na]
	at com.mongodb.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:487) ~[mongodb-driver-core-3.6.4.jar:na]
	at com.mongodb.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:484) ~[mongodb-driver-core-3.6.4.jar:na]
	at com.mongodb.connection.netty.NettyStream.readAsync(NettyStream.java:236) ~[mongodb-driver-core-3.6.4.jar:na]
	at com.mongodb.connection.netty.NettyStream.handleReadResponse(NettyStream.java:266) ~[mongodb-driver-core-3.6.4.jar:na]
	at com.mongodb.connection.netty.NettyStream.access$600(NettyStream.java:66) ~[mongodb-driver-core-3.6.4.jar:na]
	at com.mongodb.connection.netty.NettyStream$InboundBufferHandler.channelRead0(NettyStream.java:325) ~[mongodb-driver-core-3.6.4.jar:na]
	at com.mongodb.connection.netty.NettyStream$InboundBufferHandler.channelRead0(NettyStream.java:322) ~[mongodb-driver-core-3.6.4.jar:na]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647) ~[netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:547) ~[netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:501) ~[netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461) ~[netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[netty-common-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.25.Final.jar:4.1.25.Final]
	at java.base/java.lang.Thread.run(Thread.java:844) ~[na:na]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoLift] :
	reactor.core.publisher.Mono.fromRunnable(Mono.java:404)
	org.springframework.http.server.reactive.AbstractServerHttpResponse.lambda$doCommit$5(AbstractServerHttpResponse.java:213)
	java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1492)
	java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	org.springframework.http.server.reactive.AbstractServerHttpResponse.doCommit(AbstractServerHttpResponse.java:225)
	org.springframework.http.server.reactive.AbstractServerHttpResponse.lambda$writeWith$1(AbstractServerHttpResponse.java:176)
	org.springframework.http.server.reactive.ChannelSendOperator$WriteBarrier.onNext(ChannelSendOperator.java:181)
	org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:81)
	reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:115)
	org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:81)
	reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:198)
	org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:81)
	reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:238)
	org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:81)
	reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
	org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:81)
	reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:238)
	org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:81)
	reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:108)
	com.mongodb.reactivestreams.client.internal.ObservableToPublisher$1.onNext(ObservableToPublisher.java:68)
	com.mongodb.async.client.AbstractSubscription.onNext(AbstractSubscription.java:135)
	com.mongodb.async.client.AbstractSubscription.processResultsQueue(AbstractSubscription.java:203)
	com.mongodb.async.client.AbstractSubscription.tryProcessResultsQueue(AbstractSubscription.java:159)
	com.mongodb.async.client.AbstractSubscription.addToQueue(AbstractSubscription.java:117)
	com.mongodb.async.client.MongoIterableSubscription$2.onResult(MongoIterableSubscription.java:101)
	com.mongodb.async.client.MongoIterableSubscription$2.onResult(MongoIterableSubscription.java:87)
	com.mongodb.operation.AsyncQueryBatchCursor.next(AsyncQueryBatchCursor.java:135)
	com.mongodb.operation.AsyncQueryBatchCursor.next(AsyncQueryBatchCursor.java:99)
	com.mongodb.async.client.MongoIterableSubscription.requestMoreData(MongoIterableSubscription.java:87)
	com.mongodb.async.client.MongoIterableSubscription$1.onResult(MongoIterableSubscription.java:55)
	com.mongodb.async.client.MongoIterableSubscription$1.onResult(MongoIterableSubscription.java:48)
	com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
	com.mongodb.async.client.AsyncOperationExecutorImpl$1$1.onResult(AsyncOperationExecutorImpl.java:70)
	com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
	com.mongodb.operation.FindOperation$3.onResult(FindOperation.java:822)
	com.mongodb.operation.OperationHelper$ReferenceCountedReleasingWrappedCallback.onResult(OperationHelper.java:353)
	com.mongodb.operation.CommandOperationHelper$1.onResult(CommandOperationHelper.java:389)
	com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
	com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor$2.onResult(DefaultServer.java:207)
	com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
	com.mongodb.connection.CommandProtocolImpl$1.onResult(CommandProtocolImpl.java:102)
	com.mongodb.connection.DefaultConnectionPool$PooledConnection$1.onResult(DefaultConnectionPool.java:458)
	com.mongodb.connection.UsageTrackingInternalConnection$2.onResult(UsageTrackingInternalConnection.java:110)
	com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
	com.mongodb.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:381)
	com.mongodb.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:359)
	com.mongodb.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:651)
	com.mongodb.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:618)
	com.mongodb.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:487)
	com.mongodb.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:484)
	com.mongodb.connection.netty.NettyStream.readAsync(NettyStream.java:236)
	com.mongodb.connection.InternalStreamConnection.readAsync(InternalStreamConnection.java:484)
	com.mongodb.connection.InternalStreamConnection.access$1100(InternalStreamConnection.java:74)
	com.mongodb.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:608)
	com.mongodb.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:593)
	com.mongodb.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:487)
	com.mongodb.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:484)
	com.mongodb.connection.netty.NettyStream.readAsync(NettyStream.java:236)
	com.mongodb.connection.netty.NettyStream.handleReadResponse(NettyStream.java:266)
	com.mongodb.connection.netty.NettyStream.access$600(NettyStream.java:66)
	com.mongodb.connection.netty.NettyStream$InboundBufferHandler.channelRead0(NettyStream.java:325)
	com.mongodb.connection.netty.NettyStream$InboundBufferHandler.channelRead0(NettyStream.java:322)
	io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
	io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:547)
	io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:501)
	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
	io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
Error has been observed by the following operator(s):
	|_	Mono.fromRunnable(AbstractServerHttpResponse.java:213)
	|_	Flux.concat(AbstractServerHttpResponse.java:227)
	|_	Flux.then(AbstractServerHttpResponse.java:227)
	|_	Mono.error(HandlerResult.java:152)
	|_	Mono.flatMap(DispatcherHandler.java:177)
	|_	Mono.onErrorResume(DispatcherHandler.java:177)
	|_	Mono.flatMap(DispatcherHandler.java:161)
	|_	Mono.defer(DefaultWebFilterChain.java:72)
	|_	Mono.doAfterSuccessOrError(HttpTraceWebFilter.java:99)
	|_	Mono.flatMap(HttpTraceWebFilter.java:82)
	|_	Mono.defer(DefaultWebFilterChain.java:72)
	|_	Mono.then(TraceWebFilter.java:131)
	|_	Mono.error(TraceWebFilter.java:141)
	|_	Mono.flatMap(TraceWebFilter.java:134)
	|_	Mono.compose(TraceWebFilter.java:131)
	|_	Mono.defer(DefaultWebFilterChain.java:72)
	|_	Mono.doOnSuccess(MetricsWebFilter.java:64)
	|_	Mono.doOnError(MetricsWebFilter.java:64)
	|_	Mono.compose(MetricsWebFilter.java:58)
	|_	Mono.defer(DefaultWebFilterChain.java:72)
	|_	Mono.error(AbstractErrorWebExceptionHandler.java:235)
	|_	Mono.onErrorResume(ExceptionHandlingWebHandler.java:68)
	|_	Mono.error(ResponseStatusExceptionHandler.java:57)
	|_	Mono.onErrorResume(ExceptionHandlingWebHandler.java:68)
```

below is my code
```
.andRoute(POST("/hi").and(accept(APPLICATION_JSON, APPLICATION_STREAM_JSON)), request -> {
        Mono<Map<String, String>> bodyToMono = request.bodyToMono(new ParameterizedTypeReference<Map<String, String>>() {});
        return ServerResponse
                .accepted()
                .contentType(APPLICATION_STREAM_JSON)
                .hint("as", "multiline")
                .body(
                        bodyToMono.flatMapMany(
                                one -> {
                                    log.info("hi body:{}", one.toString());
                                    return userInfoRepo.findByAcc(one.getOrDefault("acc", "AR2"));
                                }
                        ).doOnError(
                                e -> {
                                    log.error("hi doOnError", e);
                                }
                        )
                        , UserInfo.class
                );
    }

);

```

version info:
spring-boot-starter-parent  2.0.3.RELEASE
spring-boot-starter-webflux  2.0.3.RELEASE(the default version managed by parent)
spring-boot-starter-undertow  2.0.3.RELEASE(the default version managed by parent)

the new springboot2.x is cool,wish to getting better! thank you!

**Comment by wilkinsona** [comment]
I suspect that this is a bug in Spring Framework. To allow us to diagnose the problem can you please turn your snippet into a minimal sample project (something that we can unzip or git clone and run) that reproduces the problem?

**Comment by NeoGitCrt1** [comment]
I have tried these:
1. simple spring boot responses Flux(created from simple numer sequnce) as body.  using undertow works fine.
2. simple spring boot responses Flux(created from reactive-mongodb repostory ) as body. using undertow  works fine.
3. springcloud, from service-b calls service-c(responses Flux(created from reactive-mongodb repostory ) as body).  service-c side using undertow failed like mentioned.

you can clone from [https://gitee.com/neo00001/springcloudversionF.git](https://gitee.com/neo00001/springcloudversionF.git)
usage:
1. start DiscoveryMain in infra module
2. start BMain and CMain in service module
3. CMain needs mongoDB
4. curl http://localhost:6878/init     ->to initialze data
5. curl http://localhost:6778/hyperstream/FX0    ->to test. see service-c's log.

**Comment by wilkinsona** [comment]
Thanks, but that's not really a minimal sample. Can you please try to reduce it to a single service that fails when a request is made to it?

**Comment by NeoGitCrt1** [comment]
Hi, I've minimized.
And I've found that when using the CodecCustomizer( in my DataServerWebConfiguration) AND accessing reactive-mongodb repostory it fails as above.
if use the CodecCustomizer( in DataServerWebConfiguration) and NOT accessing reactive-mongodb repostory(like simply produce integer sequnce) it does not fail.

And the minimal sample is in the same place(https://gitee.com/neo00001/springcloudversionF.git)

just start up CMain in service module is ok.

**Comment by wilkinsona** [comment]
Thanks. That sounds like a bug in your custom codec. In addition to the probable bug, as far as I know, you cannot safely use Gson with WebFlux as it is blocking. I would recommend that you use Jackson and the codec from Spring Framework instead.
