### ISSUE TITLE
Liquibase actuator endpoint cannot retrieve change sets when using Hikari and a custom Liquibase DataSource URL

### ISSUE THREAD

**Issue by vova-uvarov** [spring-projects/spring-boot#13832]
**SpringBoot 2.0.3.RELEASE**

I am create simple project for repeat error. https://github.com/vova-uvarov/liquibase-actuator-error
steps for repeat
1) run project
2) get http://localhost:8080/actuator/liquibase

get error on browser:

```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri Jul 20 13:22:46 MSK 2018
There was an unexpected error (type=Internal Server Error, status=500).
Unable to get Liquibase change sets
```

error in application logs

```
java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-1) has been closed.
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96) ~[HikariCP-2.7.9.jar:na]
	at org.springframework.boot.actuate.liquibase.LiquibaseEndpoint.createReport(LiquibaseEndpoint.java:82) ~[spring-boot-actuator-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.actuate.liquibase.LiquibaseEndpoint.lambda$liquibaseBeans$0(LiquibaseEndpoint.java:69) ~[spring-boot-actuator-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[na:1.8.0_121]
	at org.springframework.boot.actuate.liquibase.LiquibaseEndpoint.liquibaseBeans(LiquibaseEndpoint.java:68) ~[spring-boot-actuator-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:223) ~[spring-core-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.boot.actuate.endpoint.invoke.reflect.ReflectiveOperationInvoker.invoke(ReflectiveOperationInvoker.java:76) ~[spring-boot-actuator-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.actuate.endpoint.annotation.AbstractDiscoveredOperation.invoke(AbstractDiscoveredOperation.java:61) ~[spring-boot-actuator-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.actuate.endpoint.web.servlet.AbstractWebMvcEndpointHandlerMapping$ServletWebOperationAdapter.handle(AbstractWebMvcEndpointHandlerMapping.java:243) ~[spring-boot-actuator-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.actuate.endpoint.web.servlet.AbstractWebMvcEndpointHandlerMapping$OperationHandler.handle(AbstractWebMvcEndpointHandlerMapping.java:299) ~[spring-boot-actuator-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209) ~[spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877) ~[spring-webmvc-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783) ~[spring-webmvc-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991) ~[spring-webmvc-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925) ~[spring-webmvc-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974) ~[spring-webmvc-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:866) ~[spring-webmvc-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851) ~[spring-webmvc-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:158) ~[spring-boot-actuator-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:126) ~[spring-boot-actuator-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:111) ~[spring-boot-actuator-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90) ~[spring-boot-actuator-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109) ~[spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) ~[spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) ~[spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1468) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
```

the mistake is that org.springframework.boot.actuate.liquibase.LiquibaseEndpoint#createReport use for getConnection this code

```java
DataSource dataSource = liquibase.getDataSource();
JdbcConnection connection = new JdbcConnection(dataSource.getConnection());
```

datasource here it was already closed earlier in `org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration.DataSourceClosingSpringLiquibase`

**Comment by wilkinsona** [comment]
The closing of the `DataSource` was introduced to fix https://github.com/spring-projects/spring-boot/issues/9218. I think we probably need to suppress that when Actuator is being used and the Liquibase endpoint is enabled.

**Comment by wilkinsona** [comment]
A fix that works on 1.5 is in [this branch](https://github.com/wilkinsona/spring-boot/tree/gh-13832). The endpoint infrastructure in 1.5 makes it harder to identify if an endpoint is enabled so the close of the `DataSource` is prevented whenever the auto-configuration of `LiquibaseEndpoint` kicks in.

In 2.0, it would be nice to be able to only prevent the close of the `DataSource` if the Liquibase endpoint is enabled. Unfortunately, `@ConditionalOnEnabledEndpoint` can only be used on a `@Bean` method that returns an endpoint. It would be useful in this scenario to be able to do something like this:

```java
@Bean
@ConditionalOnEnabledEndpoint(LiquibaseEndpoint.class)
public static BeanPostProcessor preventDataSourceCloseBeanPostProcessor() {
	return new BeanPostProcessor() {

		@Override
		public Object postProcessBeforeInitialization(Object bean, String beanName)
				throws BeansException {
			if (bean instanceof DataSourceClosingSpringLiquibase) {
				((DataSourceClosingSpringLiquibase) bean)
						.setCloseDataSourceOnceMigrated(false);
			}
			return bean;
		}

	};
}
```

**Comment by snicoll** [comment]
> Unfortunately, @ConditionalOnEnabledEndpoint can only be used on a @Bean method that returns an endpoint.

@wilkinsona this is no longer the case in 2.1. See `IntegrationGraphEndpointAutoConfiguration` for an example. If we really need this feature in 2.0, we can consider backporting it

**Comment by wilkinsona** [comment]
Oh, nice! Thanks for the pointer. It would be useful for this issue as it'll allow us to only prevent the `DataSource` from being closed if the endpoint's enabled. I'll back port the addition of the `endpoint` attribute as part of merging the fix for this forwards into 2.0.x.

**Comment by wilkinsona** [comment]
I changed my mind about doing the backport as part of fixing this. I've opened #14787 to tackle it separately.

**Comment by wilkinsona** [comment]
While this can happen in 1.5, to be affected it's necessary to have changed the default connection pool  to Hikari and to have used properties to configure a Liquibase-specific `DataSource`. A workaround is to use `@LiquibaseDataSource` rather than the properties.

**Comment by thomasreiser** [comment]
@wilkinsona, the adjustments of commit are currently leading to a issue on our side. We are now having a pool of 10 open connects (=HikariCP default) just for Liquibase which is totally useless. If we need a connection for the liquibase actuator endoint, wouldn't it be enough to limit the pool in the **AutoConfiguration** or allow an Liquibase-individual setup of pool size in the properties?

Thats our current configuration:
```yaml
datasource:
  initialization-mode: always
  url: jdbc:oracle:thin:@myserver:1521/mydb
  username: my_user
  password: my_password
  type: com.zaxxer.hikari.HikariDataSource
  driver-class-name: oracle.jdbc.pool.OracleDataSource
  hikari:
    minimum-idle: 1
    maximum-pool-size: 5
    idle-timeout: 600000
    max-lifetime: 1800000
    connection-test-query: select 1 from dual
  liquibase:
    url: ${spring.datasource.url}
    user: my_other_user
    password: my_other_password
    defaultSchema: some_schema
    dropFirst: false
    changeLog: classpath:/db/changelog/database.xml
    enabled: true
    contexts: default
```

In detail, this configuration leads to to two separate `DataSource`s:
- The main data source used by the application which is limited to max. 5 connections
- And the Liquibase data source holding always 10 open connections because this is the HikariCP default

I really don't like that behaviour because that are quite a lot of unnecessary connections to the DB server in case of many microservices.

I have already tried to setup a custom `@LiquibaseDataSource` but that does not work:
```java
@Configuration
public class LiquibaseConfiguration {
  @LiquibaseDataSource
  public DataSource createDataSource(Properties someConnectionProps) {
     // Create data source, set pool size to 1 and return it
     return ds;
  }
}
```

It looks like Spring Boot tries to create the Liquibase `DataSource` before the autoconfiguration creates the "real" `DataSource` and thus, other `@Configuration`s who are doing an `@Autowire` on `java.sql.DataSource` receive the Liquibase data source and not the real one we have received before..

Am I doing something wrong or is there an issue with the liquibase integration?
Would you accept a pull request allowing developers to setup custom connection pool configuration like it is done like by `spring.datasource.liquibase` (someting like `spring.liquibase.hikari` and so on)?

**Comment by wilkinsona** [comment]
> We are now having a pool of 10 open connects (=HikariCP default) just for Liquibase which is totally useless.

While 10 connections may not be ideal, prior to this change the Liquibase endpoint did not work. If that hadn't caused you a problem you can disable the endpoint. Doing should stop the Liquibase-specific data source from being kept open.

> It looks like Spring Boot tries to create the Liquibase DataSource before the autoconfiguration creates the "real" DataSource. … Am I doing something wrong or is there an issue with the liquibase integration?

User-provided configuration always runs before Boot's auto-configuration. As mentioned in the javadoc of `@LiquibaseDataSource`, if you want to keep your main data source you will have to configure it yourself and mark it as `@Primary`.

> Would you accept a pull request allowing developers to setup custom connection pool configuration 

There's certainly some room for improvement here, but I'm not sure we're ready to jump to a particular solution. Can you please open a new issue so that we can consider some options?
