### ISSUE TITLE
Bean validation throws java.lang.ClassCastException: org.eclipse.persistence.jpa.PersistenceProvider cannot be cast to javax.persistence.spi.PersistenceProvider in Weblogic 12.2.1.3.0

### ISSUE THREAD

**Issue by pmihalcin** [spring-projects/spring-boot#13892]
I have Spring Boot `1.5.14.RELEASE` web application deployed to Weblogic `12.2.1.3.0`. 
There is `UpstreamEvent` DTO:
```
@Getter
@Setter
public class UpstreamEvent {
    @NotNull
    @DateTimeFormat(iso = DATE)
    private LocalDate transactionDate;
}
```
and `UpstreamEventController` (simplified)
```
@RestController
@RequestMapping("/api/get-matching-codes")
public class UpstreamEventController {

    @GetMapping
    @PreAuthorize("checkPermission('READ')")
    ResponseEntity<Set<String>> getMatchingMerchantCodes(@Valid UpstreamEvent event) {

		...
	
        return ResponseEntity.ok().body(codes.stream().collect(toSet()));
    }
}
```

Thanks to @Valid, bean validation kicks in.

The problem doesn't occur locally with embedded tomcat.
It only manifests at Weblogic's runtime as follows:
```
18-07-25 13:16:35.807 [[ACTIVE] ExecuteThread: '17' for queue: 'weblogic.kernel.Default (self-tuning)'] DEBUG o.s.w.s.m.m.a.ServletInvocableHandlerMethod [] - Failed to resolve argument 0 of type 'net.homecredit.mer.web.evaluation.web.upstream.UpstreamEvent'
javax.validation.ValidationException: HV000041: Call to TraversableResolver.isReachable() threw an exception.
	at org.hibernate.validator.internal.engine.ValidatorImpl.isReachable(ValidatorImpl.java:1653)
	at org.hibernate.validator.internal.engine.ValidatorImpl.isValidationRequired(ValidatorImpl.java:1629)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateMetaConstraint(ValidatorImpl.java:613)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraint(ValidatorImpl.java:584)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForSingleDefaultGroupElement(ValidatorImpl.java:528)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForDefaultGroup(ValidatorImpl.java:496)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForCurrentGroup(ValidatorImpl.java:461)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateInContext(ValidatorImpl.java:411)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validate(ValidatorImpl.java:208)
	at org.springframework.validation.beanvalidation.SpringValidatorAdapter.validate(SpringValidatorAdapter.java:119)
	at org.springframework.boot.autoconfigure.web.WebMvcValidator.validate(WebMvcValidator.java:69)
	at org.springframework.validation.DataBinder.validate(DataBinder.java:892)
	at org.springframework.web.method.annotation.ModelAttributeMethodProcessor.validateIfApplicable(ModelAttributeMethodProcessor.java:166)
	at org.springframework.web.method.annotation.ModelAttributeMethodProcessor.resolveArgument(ModelAttributeMethodProcessor.java:113)
	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:121)
	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:158)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:128)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
```

```
Caused by: java.lang.ClassCastException: org.eclipse.persistence.jpa.PersistenceProvider cannot be cast to javax.persistence.spi.PersistenceProvider
	at javax.persistence.Persistence$1.isLoaded(Persistence.java:110)
	at org.hibernate.validator.internal.engine.resolver.JPATraversableResolver.isReachable(JPATraversableResolver.java:47)
	at org.hibernate.validator.internal.engine.resolver.DefaultTraversableResolver.isReachable(DefaultTraversableResolver.java:128)
	at org.hibernate.validator.internal.engine.resolver.CachingTraversableResolverForSingleValidation.isReachable(CachingTraversableResolverForSingleValidation.java:36)
	at org.hibernate.validator.internal.engine.ValidatorImpl.isReachable(ValidatorImpl.java:1644)
	... 114 common frames omitted
```

**Comment by snicoll** [comment]
What makes you think this error is related to Spring Boot? This looks solely related to the deployment environment where two incompatible versions of the JPA API are present.

**Comment by pmihalcin** [comment]
I thought it could be related to dependencies which are used in `org.springframework.boot:spring-boot-starter-web:1.5.14.RELEASE` or `org.springframework.boot:spring-boot-starter-data-jpa:1.5.14.RELEASE`
