### ISSUE TITLE
Support ensureUniqueRuntimeObjectNames globally rather than only on Actuator endpoints

### ISSUE THREAD

**Issue by sddakoty** [spring-projects/spring-boot#13959]
In a tomcat container, it's possible to deploy war files with zero downtime by using "parallel deployment":
https://tomcat.apache.org/tomcat-8.0-doc/config/context.html#Parallel_deployment

This is done be adding a prefix to the war as follows:
mywar##1.war
mywar##2.war
mywar##3.war

In spring-boot-1.x this requires the following property to be enabled, as otherwise JXM expose would clash when using `actuator` for health tracking:

`management.endpoints.jmx.unique-names=true`

I upgraded to `spring-boot-2.0.4`, and this seems to be broken now. On parallel deployment of the same application build with spring 2, the following exception is thrown and prevents application startup (in this example the database jxm bean):

```
[][] 2018-07-31 16:22:26,066 ERROR o.s.b.SpringApplication: Application run failed
org.springframework.jmx.export.UnableToRegisterMBeanException: Unable to register MBean [HikariDataSource (null)] with key 'dataSource'; nested exception is javax.management.InstanceAlreadyExistsException: com.zaxxer.hikari:name=dataSource,type=HikariDataSource
	at org.springframework.jmx.export.MBeanExporter.registerBeanNameOrInstance(MBeanExporter.java:625) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.jmx.export.MBeanExporter.lambda$registerBeans$2(MBeanExporter.java:551) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at java.util.HashMap.forEach(HashMap.java:1289) ~[?:1.8.0_171]
	at org.springframework.jmx.export.MBeanExporter.registerBeans(MBeanExporter.java:551) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.jmx.export.MBeanExporter.afterSingletonsInstantiated(MBeanExporter.java:434) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:776) ~[spring-beans-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762) ~[spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:398) ~[spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:330) ~[spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:157) ~[spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:137) ~[spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:91) ~[spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:172) ~[spring-web-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5055) ~[catalina.jar:9.0.7]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[catalina.jar:9.0.7]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:742) ~[catalina.jar:9.0.7]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:718) ~[catalina.jar:9.0.7]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:703) ~[catalina.jar:9.0.7]
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:986) ~[catalina.jar:9.0.7]
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:492) ~[catalina.jar:9.0.7]
	at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1651) ~[catalina.jar:9.0.7]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:287) ~[tomcat-coyote.jar:9.0.7]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819) ~[?:1.8.0_171]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801) ~[?:1.8.0_171]
	at org.apache.catalina.manager.ManagerServlet.check(ManagerServlet.java:1571) ~[catalina.jar:9.0.7]
	at org.apache.catalina.manager.HTMLManagerServlet.upload(HTMLManagerServlet.java:294) ~[catalina.jar:9.0.7]
	at org.apache.catalina.manager.HTMLManagerServlet.doPost(HTMLManagerServlet.java:212) ~[catalina.jar:9.0.7]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) ~[servlet-api.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:9.0.7]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:9.0.7]
	at org.apache.catalina.filters.CsrfPreventionFilter.doFilter(CsrfPreventionFilter.java:136) ~[catalina.jar:9.0.7]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:9.0.7]
	[...]
Caused by: javax.management.InstanceAlreadyExistsException: com.zaxxer.hikari:name=dataSource,type=HikariDataSource
	at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437) ~[?:1.8.0_171]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898) ~[?:1.8.0_171]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966) ~[?:1.8.0_171]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900) ~[?:1.8.0_171]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324) ~[?:1.8.0_171]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522) ~[?:1.8.0_171]
	at org.springframework.jmx.support.MBeanRegistrationSupport.doRegister(MBeanRegistrationSupport.java:137) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.jmx.export.MBeanExporter.registerBeanInstance(MBeanExporter.java:671) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.jmx.export.MBeanExporter.registerBeanNameOrInstance(MBeanExporter.java:615) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
```

**Comment by snicoll** [comment]
> I upgraded to spring-boot-2.0.4, and this seems to be broken now. 

Spring Boot is not the only component that may interact with the JMX domain and `management.endpoints.jmx.unique-names` doesn't control all JMX beans in the context (only Actuator endpoints and the `DataSource` is not one of them).

It looks like you are relying on the preferred connection pool and by upgrading to 2.0 you also moved to Hikari. The Hikari `DataSource` bean is also an MBean so we're going to expose it with our regular JMX support.

I can see something missing in our support there though. We could use a `spring.jmx.unique-names` property and have something more global rather than having a dedicated support for Actuator endpoints. 

Can you please add the following in your project to validate that it works?

```java
@Bean
public ParentAwareNamingStrategy objectNamingStrategy() {
	ParentAwareNamingStrategy namingStrategy = new ParentAwareNamingStrategy(
			new AnnotationJmxAttributeSource());
	namingStrategy.setEnsureUniqueRuntimeObjectNames(true);
	// Uncomment if you're using "spring.jmx.default-domain"
	//namingStrategy.setDefaultDomain("xyz");
	return namingStrategy;
}
```

**Comment by sddakoty** [comment]
Thanks for the suggestion, indeed it works now.
I like your suggestion of a more global property to use, instead restricting the actuator endpoints only!

**Comment by snicoll** [comment]
Thanks for the fast feedback! Alright, let's reuse this issue to suggest this to be added then.

**Comment by snicoll** [comment]
Closing in favour of PR #13990

**Comment by paulouechi** [comment]
Two days trying to solve the problem.
Thanks snicoll !!!!!
