### ISSUE TITLE
a problem about  'spring-boot-devtools' togetter with ehcach3

### ISSUE THREAD

**Issue by cuivip** [spring-projects/spring-boot#13958]
my springboot application integrate ehcach3 as it's cache layer. version of spring boot is 2.0.1.RELEASE

cache config in **application.yml** file:
`  cache:
    jcache:
      config: classpath:ehcache3.xml`

**echcache3.xml**:
`
&lt;config xmlns='http://www.ehcache.org/v3'
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:jsr107="http://www.ehcache.org/v3/jsr107"
        xsi:schemaLocation="http://www.ehcache.org/v3 http://www.ehcache.org/schema/ehcache-core-3.0.xsd
                            http://www.ehcache.org/v3/jsr107 http://www.ehcache.org/schema/ehcache-107-ext-3.0.xsd"&gt;
    
    <persistence directory="java.io.tmpdir/ehcache"/>
  
    <cache alias="config">
        <key-type>java.lang.String</key-type>
        <value-type>com.opespro.admin.po.SysConfig</value-type>
        <expiry>
                <none/>
        </expiry>
        <resources>
            <heap unit="entries">20000</heap>
            <offheap unit="MB">100</offheap>
            <disk persistent="true" unit="MB" >640</disk>
        </resources>
        <jsr107:mbeans enable-management="true" enable-statistics="true"/>
    </cache>
    
&lt;/config&gt;
`

I have an   application listener  initialize the cache  config  after application started

`package com.opespro.common.base;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cache.Cache;
import org.springframework.cache.CacheManager;
import org.springframework.context.ApplicationListener;
import org.springframework.context.event.ContextRefreshedEvent;
import org.springframework.stereotype.Component;

import com.opespro.admin.po.SysCode;
import com.opespro.admin.po.SysCodeType;
import com.opespro.admin.po.SysConfig;
import com.opespro.admin.service.SysCodeService;
import com.opespro.admin.service.SysConfigService;
 
@Component
public class ApplicationStartListener implements ApplicationListener<ContextRefreshedEvent>{

    private Logger logger = LoggerFactory.getLogger(getClass());
    
    @Autowired
    private SysConfigService sysConfigService;
 
    @Autowired
    private CacheManager  cacheManager ;
    
    @Override
    public void onApplicationEvent(ContextRefreshedEvent event) {
 
        List<SysConfig> list = sysConfigService.queryAll();
        Cache cache=cacheManager.getCache("config");
        cache.clear();
        
        for (SysConfig config : list) {
            cache.put(config.getConfigKey(), config);
        }
        logger.info("application has been started");
    }
}`

I am developing with **Eclipse**, A normal start-up is fine，but when some java codes are changed,the Devtools restart my application. an exception throw from echache3 ：

`
java.lang.ClassCastException: Invalid value type, expected : com.opespro.admin.po.SysConfig but was : com.opespro.admin.po.SysConfig
	at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore.checkValue(AbstractOffHeapStore.java:1069) ~[ehcache-3.5.2.jar:3.5.2 7941fa2573343b31ae56a12564404552c6d6eff0]
	at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore.put(AbstractOffHeapStore.java:222) ~[ehcache-3.5.2.jar:3.5.2 7941fa2573343b31ae56a12564404552c6d6eff0]
	at org.ehcache.impl.internal.store.tiering.TieredStore.put(TieredStore.java:110) ~[ehcache-3.5.2.jar:3.5.2 7941fa2573343b31ae56a12564404552c6d6eff0]
	at org.ehcache.core.Ehcache.doPut(Ehcache.java:86) ~[ehcache-3.5.2.jar:3.5.2 7941fa2573343b31ae56a12564404552c6d6eff0]
	at org.ehcache.core.EhcacheBase.put(EhcacheBase.java:189) ~[ehcache-3.5.2.jar:3.5.2 7941fa2573343b31ae56a12564404552c6d6eff0]
	at org.ehcache.jsr107.Eh107Cache.put(Eh107Cache.java:176) ~[ehcache-3.5.2.jar:3.5.2 7941fa2573343b31ae56a12564404552c6d6eff0]
	at org.springframework.cache.jcache.JCacheCache.put(JCacheCache.java:92) ~[spring-context-support-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at com.opespro.common.base.ApplicationStartListener.onApplicationEvent(ApplicationStartListener.java:49) ~[classes/:na]
	at com.opespro.common.base.ApplicationStartListener.onApplicationEvent(ApplicationStartListener.java:1) ~[classes/:na]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:400) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:354) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:888) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:161) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at com.opespro.FacilitesBoot.main(FacilitesBoot.java:15) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_92]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_92]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-2.0.1.RELEASE.jar:2.0.1.RELEASE]
`

**Comment by snicoll** [comment]
@cuivip thanks for the report but please upgrade to the latest bugfix release before reporting an issue. This has already been fixed in #13338. If upgrading didn't fix your problem, please share a sample that we can run ourselves (not code in text, a github repo or a link to download a project) and we can reopen this issue.
