### ISSUE TITLE
could not startup spring boot app with TWO HTTPS connectors in embedded tomcat

### ISSUE THREAD

**Issue by gqming** [spring-projects/spring-boot#14051]
-  spring boot version: 2.0.4.RELEASE
-  only configure the default connector as HTTPS listen on port 9443, app startup normal
-  add another connector as HTTPS listen on port 6443, app startup failed
-  the two connectors use the same cert file "sample.jks" downloaded from "https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples/spring-boot-sample-tomcat-ssl/src/main/resources" 
-  the exception detail as follows

```
2018-08-13 20:32:00.503  INFO 6020 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 9443 (https) 6443 (https)
2018-08-13 20:32:00.539  WARN 6020 --- [           main] o.a.t.util.net.openssl.OpenSSLEngine     : Failed getting cipher list

java.lang.Exception: Invalid Server SSL Protocol (error:140A90A1:lib(20):func(169):reason(161))
	at org.apache.tomcat.jni.SSLContext.make(Native Method) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.tomcat.util.net.openssl.OpenSSLEngine.<clinit>(OpenSSLEngine.java:72) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.tomcat.util.net.openssl.OpenSSLUtil.getImplementedProtocols(OpenSSLUtil.java:61) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.tomcat.util.net.SSLUtilBase.<init>(SSLUtilBase.java:53) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.tomcat.util.net.openssl.OpenSSLUtil.<init>(OpenSSLUtil.java:41) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.tomcat.util.net.openssl.OpenSSLImplementation.getSSLUtil(OpenSSLImplementation.java:36) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:104) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.initialiseSsl(AbstractJsseEndpoint.java:87) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:225) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.tomcat.util.net.AbstractEndpoint.init(AbstractEndpoint.java:1086) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.init(AbstractJsseEndpoint.java:268) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:581) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.coyote.http11.AbstractHttp11Protocol.init(AbstractHttp11Protocol.java:68) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.connector.Connector.initInternal(Connector.java:993) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.core.StandardService.initInternal(StandardService.java:549) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:875) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:140) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:367) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:107) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.<init>(TomcatWebServer.java:86) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getTomcatWebServer(TomcatServletWebServerFactory.java:413) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:174) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:179) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:152) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544) [spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:398) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:330) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at speedyapp.SpringBootBarApplication.main(SpringBootBarApplication.java:23) [classes/:na]

2018-08-13 20:32:00.809 ERROR 6020 --- [           main] o.apache.catalina.core.StandardService   : Failed to initialize connector [Connector[HTTP/1.1-6443]]

org.apache.catalina.LifecycleException: Failed to initialize component [Connector[HTTP/1.1-6443]]
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:112) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.core.StandardService.initInternal(StandardService.java:549) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:875) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:140) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:367) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:107) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.<init>(TomcatWebServer.java:86) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getTomcatWebServer(TomcatServletWebServerFactory.java:413) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:174) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:179) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:152) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544) [spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:398) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:330) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at speedyapp.SpringBootBarApplication.main(SpringBootBarApplication.java:23) [classes/:na]
Caused by: org.apache.catalina.LifecycleException: Protocol handler initialization failed
	at org.apache.catalina.connector.Connector.initInternal(Connector.java:995) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107) [tomcat-embed-core-8.5.32.jar:8.5.32]
	... 18 common frames omitted
Caused by: java.lang.IllegalArgumentException: Error initializing SSL context
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:116) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.initialiseSsl(AbstractJsseEndpoint.java:87) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:225) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.tomcat.util.net.AbstractEndpoint.init(AbstractEndpoint.java:1086) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.init(AbstractJsseEndpoint.java:268) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:581) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.coyote.http11.AbstractHttp11Protocol.init(AbstractHttp11Protocol.java:68) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.connector.Connector.initInternal(Connector.java:993) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	... 19 common frames omitted
Caused by: javax.net.ssl.SSLException: Error initializing SSL context
	at org.apache.tomcat.util.net.openssl.OpenSSLContext.<init>(OpenSSLContext.java:184) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.tomcat.util.net.openssl.OpenSSLUtil.createSSLContext(OpenSSLUtil.java:73) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:113) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	... 26 common frames omitted
Caused by: java.lang.Exception: Unable to create SSLContext. Check that SSLEngine is enabled in the AprLifecycleListener, the AprLifecycleListener has initialised correctly and that a valid SSLProtocol has been specified
	at org.apache.tomcat.util.net.openssl.OpenSSLContext.<init>(OpenSSLContext.java:176) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	... 28 common frames omitted
Caused by: java.lang.Exception: Invalid Server SSL Protocol (error:140A90A1:lib(20):func(169):reason(161))
	at org.apache.tomcat.jni.SSLContext.make(Native Method) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.tomcat.util.net.openssl.OpenSSLContext.<init>(OpenSSLContext.java:171) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	... 28 common frames omitted
```

**source code:**
```

import org.apache.catalina.connector.Connector;
import org.apache.coyote.http11.Http11NioProtocol;
import org.springframework.boot.web.embedded.tomcat.TomcatConnectorCustomizer;
import org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory;
import org.springframework.boot.web.servlet.server.ConfigurableServletWebServerFactory;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class WebServerConfiguration
{
	private final static String KEY_STORE_BASE_PATH = "e:\\tmp\\keystore\\";
	
	@Bean
	public ConfigurableServletWebServerFactory webServerFactory()
	{
		TomcatServletWebServerFactory factory = new TomcatServletWebServerFactory();
		factory.addConnectorCustomizers(new TomcatConnectorCustomizer()
		{
			@Override
			public void customize(Connector connector)
			{
				/**
				 * configure the default connector as HTTPS
				 */
				connector.setPort(9443);
				connector.setSecure(true);
				connector.setScheme("https");
				Http11NioProtocol proto = (Http11NioProtocol) connector.getProtocolHandler();
				proto.setSSLEnabled(true);
				proto.setKeystoreFile(KEY_STORE_BASE_PATH + "sample.jks");
				proto.setKeystorePass("secret");
				proto.setKeyPass("password");
			}
		});
		
		/**
		 * create another connector as HTTPS too
		 */
		Connector connector2 = new Connector(TomcatServletWebServerFactory.DEFAULT_PROTOCOL);
		connector2.setPort(6443);
		connector2.setSecure(true);
		connector2.setScheme("https");
		
		Http11NioProtocol proto = (Http11NioProtocol) connector2.getProtocolHandler();
		proto.setSSLEnabled(true);
		proto.setKeystoreFile(KEY_STORE_BASE_PATH + "sample.jks");
		proto.setKeystorePass("secret");
		proto.setKeyPass("password");
		
		factory.addAdditionalTomcatConnectors(connector2);
		
		return factory;
	}
}

```

**Comment by wilkinsona** [comment]
The error that you are seeing is coming from OpenSSL. The code `140A90A1` means that there are no ciphers. Given that you have configured SSL yourself, this is out of Spring Boot's control.

**Comment by gqming** [comment]
the two connectors use the same keystore "sample.jks", if only left the default connector app startup normal
