### ISSUE TITLE
Regression bug with WebFlux (between 2.0.3.RELEASE and 2.0.4.RELEASE) [TestCase provided]

### ISSUE THREAD

**Issue by eximius313** [spring-projects/spring-boot#14160]
🐞 Bug report

I'm providing test case: [spring_reactor_bug.zip](https://github.com/spring-projects/spring-boot/files/2306129/spring_reactor_bug.zip)

If you run `$ ./gradlew test` then test will fail with:
```
java.lang.AssertionError: PublisherProbe should not have been cancelled but it was
	at reactor.test.publisher.PublisherProbe.assertWasNotCancelled(PublisherProbe.java:73)
	at com.example.demo.MyControllerTests.shouldAllowRetrieval(MyControllerTests.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:436)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
```
but if you edit `build.gradle` file and change SpringBoot version back to `2.0.3.RELEASE` (comment line 4) then test will pass.

**Comment by snicoll** [comment]
@eximius313 thanks for the report but that issue isn't related to Spring Boot. I've only downgraded the Spring Framework version and the test passed. I am unsure where the problem might be, I've paged @simonbasle for a quick review before asking you to report this somewhere else.

**Comment by eximius313** [comment]
ok, so let's wait for @simonbasle opinion

**Comment by simonbasle** [comment]
@eximius313 on a side note, **this is NOT a regression**, in the sense that it is fine for the `Mono` to be cancelled here, it happens _after_ the `Mono` has emitted its item. Behavior is ultimately unchanged.

Fixing the extraneous cancellation would require a change in both Reactor core and Spring Framework:
 - in reactor, we would need to detect cycles of `Mono.from(Flux.from(Mono))`
 - in SPR we would need to replace `Flux.from(mono).map(...)` with `Flux.from(mono.map(...))`, so that the code keeps the "mono-to-flux" adapter visible (resulting in the reactor optimization discussed above being applicable)
