### ISSUE TITLE
MongoDB (sub)Document conversion fails after upgrade to Spring Boot 2.0.4

### ISSUE THREAD

**Issue by jreijn** [spring-projects/spring-boot#14177]
We’re currently updating our project from Spring Boot 1.5.8 to Spring Boot 2.0.4 and seem to have hit a problem with what I think lies in spring-data-mongodb. After a chat on Gitter with @mp911de he suggested to raise an issue here.

We have a pretty basic project setup. In our project we do use document subtypes (we have a Question object with subtypes SingleSelectQuestion and MultiSelectQuestion) which are stored in the same collection.

The `Question` object is annotated with `@Document` and the `SingleSelectQuestion` is annotated with `@TypeAlias`, etc.

I've tried to debug the problem and from what I’ve seen the `MappingMongoConvertor` has a reference to a `MongoMappingContext`. The `MongoMappingContext` contains an `initialEntitySet` (prop of AbstractMappingContext). With Spring Boot 1.5.8 the `initialEntitySet` is filled with my entities (SingleSelectQuestion, etc). In 1.5.8 it works because the MongoMappingContext Bean is created from `MongoDataAutoConfiguration`. In the `MongoDataAutoConfiguration` the bean is created and performs an entity scan to set the `initialEntitySet`. With Spring Boot 2.0.4 and the later version of Spring Data the `initialEntitySet` stays empty because the `MongoMappingContext` is created elsewhere (not from the `MongoDataAutoConfiguration`). 

Logging the auto wiring process shows this:

```
MongoDataAutoConfiguration#mongoMappingContext:
      Did not match:
         - @ConditionalOnMissingBean (types: org.springframework.data.mongodb.core.mapping.MongoMappingContext; SearchStrategy: all) found beans of type 'org.springframework.data.mongodb.core.mapping.MongoMappingContext' mongoMappingContext (OnBeanCondition)
```

The rest of the Bean from Spring Data MongoDB is are being created from `MongoDataAutoConfiguration`, only the `MongoMappingContext` isn't.

Our configuration class is pretty simple:

```
@Configuration
@EnableMongoRepositories(basePackages = {
    "nl.domain.someproject.tools.datastore",
    "nl.domain.someproject.security.datastore"
})
public class DatastoreConfig {
}
```

We use explicit imports of several configuration classes and have specified specific packages in which the mongo repositories reside.

The `EnableMongoRepositories` annotation seems to actually trigger the registration of the `MongoMappingContext` bean via the `MongoRepositoriesRegistrar`. It ends up triggering `MongoRepositoryConfigurationExtension#registerBeansForRoot` which adds the `MongoMappingContext` to the `BeanDefinitionRegistry` without setting the initialEntitySet. 

For the `@Document` annotated classed that have a defined Repository it seems to work just fine in Spring Boot 2.0.4, but not for the type aliased classes, which did work with Spring Boot 1.5.8+ because of the entity scan. 
I noticed that in the Spring Data MongoDB 1.10.x branch @olivergierke removed the #registerBeansForRoot method (see https://github.com/spring-projects/spring-data-mongodb/commit/8d36e42b1b98c146a6b82db4d7f5cf9f55f9aeea#diff-61291cccc50d5a43d4248924195054ff) due to some side effect with Boot, but it seems it was again in the 2.0.x branch after adding support for RxJava.

For demo purposes of the issue we've created a very [simple demo project](https://github.com/RDBreed/mongomappingcontextdemo). It contains 3 tests for the different scenarios. The `EnableMongoScanConfigurationTest` shows that it has only registered **one** entity instead of **2** like the other tests.

**Comment by olivergierke** [comment]
Would you mind clarifying what the actual symptoms are? Initial entity set being populated or not is one thing but in general the `MappingContext` adds entities on the fly, i.e. the lookups made from `MongoTemplate` should make them get added over time. That in turn means that verifying on the presence of the `PersistentEntity` instances in the `MappingContext` is sort of invalid as the non-presence doesn't indicate something doesn't work downstream.

**Comment by jreijn** [comment]
Yes I'm sorry we're focussing to much on where we think the problem might lie. 

In short the problem we are facing is as follows:

During the startup of our application the application loads and we do not see any errors during startup.

When the user loads the UI of the application and moves over to the questions view we hit and error in our backend. Note that no other interactions with the same type of entities have occurred through the backend (no updates, inserts, etc).

The stacktrace is as follows (shortened a little to focus on the important parts): 

```
org.springframework.data.mapping.model.MappingInstantiationException: Failed to instantiate nl.domain.tools.question.Question using constructor protected nl.domain.tools.question.Question() with arguments 
	at org.springframework.data.convert.ReflectionEntityInstantiator.createInstance(ReflectionEntityInstantiator.java:81)
	at org.springframework.data.convert.ClassGeneratingEntityInstantiator.createInstance(ClassGeneratingEntityInstantiator.java:86)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:273)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:253)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:202)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:198)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:86)
	at org.springframework.data.mongodb.core.MongoTemplate$ProjectingReadCallback.doWith(MongoTemplate.java:2830)
	at org.springframework.data.mongodb.core.MongoTemplate.executeFindMultiInternal(MongoTemplate.java:2448)
	at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:2267)
	at org.springframework.data.mongodb.core.ExecutableFindOperationSupport$ExecutableFindSupport.doFind(ExecutableFindOperationSupport.java:213)
	at org.springframework.data.mongodb.core.ExecutableFindOperationSupport$ExecutableFindSupport.all(ExecutableFindOperationSupport.java:169)
	at org.springframework.data.mongodb.repository.query.AbstractMongoQuery.lambda$getExecution$1(AbstractMongoQuery.java:113)
	at org.springframework.data.mongodb.repository.query.AbstractMongoQuery.execute(AbstractMongoQuery.java:97)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:590)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:578)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy138.findAllByFilterToolId(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:197)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy138.findAllByFilterToolId(Unknown Source)
	at nl.domain.tools.filtertool.FilterToolService.obtainAllQuestions(FilterToolService.java:434)
	at nl.domain.tools.question.QuestionController.obtainAllQuestions(QuestionController.java:53)
.......
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [nl.domain.tools.question.Question]: Is it an abstract class?; nested exception is java.lang.InstantiationException
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:173)
	at org.springframework.data.convert.ReflectionEntityInstantiator.createInstance(ReflectionEntityInstantiator.java:79)
	... 152 more
```

When we first hit our API endpoint we use `FilterToolService.obtainAllQuestions` to fetch our questions. 

```
public List<Question> obtainAllQuestions(String filterToolId) {
    List<Question> questions = questionRepository.findAllByFilterToolId(filterToolId);
    if (questions == null) {
        return new ArrayList<>();
    }
    return questions;
}

```

Our repository is pretty simple:

```
@Repository
public interface QuestionRepository extends MongoRepository<Question, String>, QuestionRepositoryCustom {

    List<Question> findAllByFilterToolId(String filterToolId);

    void deleteAllByFilterToolId(String filterToolId);

}
```

As you might notice we use our abstract type as the type specified in the repository, but we expect a subtype like SingleSelectQuestion to be returned. I've attached a diagram of our object model for reference.

![singleselectquestion](https://user-images.githubusercontent.com/494110/44514791-4d43fb80-a6c1-11e8-8249-4f32f4b6915c.png)

The above error is correct, because the Question class is an abstract class, but we expect to get either a `SingleSelectQuestion` or `MultipleSelectQuestion` like we did get with Spring Boot 1.5.8.

**Comment by olivergierke** [comment]
That's helpful, thanks. Just to check the obvious: the documents returned by MongoDB contain the type information necessary to find out that a document actually has to become a `SelectQuestion` etc. right?

**Comment by jreijn** [comment]
Yes they contain the `_class` information within the document. All documents were created through spring data, but good that you asked. 

Our document(s) look like this (copy from MongoDB). I've sanitised the actual content because this is a customer project.

```
{
  "_id": "5a04803496c4a609f5dfc1d1",
  "_class": "SingleSelectQuestion",
  "answerOptions": [
    {
      "_id": "7ec8c8ec-6bdb-4504-a497-80e3fc7352c2",
      "text": "...",
      "feedback": "...",
      "helpText": "..."
    },
    {
      "_id": "8899a520-9665-45e0-954d-9933ea2701ec",
      "text": "...",
      "feedback": "..."
    }
  ],
  "filterToolId": "5a006c2f16ecfb04dad76dee",
  "text": "...",
  "workingTitle": "...",
  "helpText": "...",
  "order": 250,
  "relevantFor": []
}
```

We've also updated the demo project and added a new test to show the failing conversion when using @EnableMongoRepositories.

**Comment by olivergierke** [comment]
Thanks, Jeroen. I'll investigate.

**Comment by snicoll** [comment]
Thanks @olivergierke - @jreijn if that turns out not to be the case, let's follow up on the Spring Data issue tracker please. Thank you.

**Comment by jreijn** [comment]
@olivergierke yes I would love to. I tried adding the dependency and adding  https://repo.spring.io/snapshot/ as a repository for my project, but if I browse that repo I don't see the artifact. Which artifact repository contains the snapshot jar?

**Comment by olivergierke** [comment]
Something went wrong with the feature branch init script. I've fixed that. Binaries should be available now. Feedback at the [ticket](https://jira.spring.io/browse/DATAMONGO-2068) in Spring Data MongoDB for now, please :).
