### ISSUE TITLE
Dropwizard metrics major version increase for Java 10 compatibility

### ISSUE THREAD

**Issue by laszlokiss** [spring-projects/spring-boot#14183]
Spring Boot parent 2.0.3 uses dropwizard-metrics 3.2.6 which causes the following exception with Java 10 on Unix system:
`java.lang.reflect.InaccessibleObjectException: Unable to make public long com.sun.management.internal.OperatingSystemImpl.getOpenFileDescriptorCount() accessible: module jdk.management does not "opens com.sun.management.internal"
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:337)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:281)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:198)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:192)
        at com.codahale.metrics.jvm.FileDescriptorRatioGauge.invoke(FileDescriptorRatioGauge.java:48)
        at com.codahale.metrics.jvm.FileDescriptorRatioGauge.getRatio(FileDescriptorRatioGauge.java:35)`

The issue was [fixed](https://github.com/dropwizard/metrics/pull/1236) in dropwizard 4.0.0 version.
Simple [demo project](https://github.com/laszlokiss/MetricsTest) for reproducing the error.

**Comment by snicoll** [comment]
@laszlokiss thanks for the report but we don't upgrade to a new feature release of a third party dependency in a maintenance release of Spring Boot (and certainly not a major one). Spring Boot 2.1 can be considered once/if micrometer catches up (see https://github.com/micrometer-metrics/micrometer/issues/587)

In any case, we have an automated process to align and upgrade dependencies so we'll process this in due course if need to be. In the meantime, you can override the version of that dependency if that works for your use cases.
