### ISSUE TITLE
Upgrade to Spring Data Kay SR10

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#14328]

**Comment by bclozel** [comment]
The SNAPSHOT upgrade done in d53839e is failing the build right now. It seems that it's related to the changes done in [DATACMNS-1174](https://jira.spring.io/browse/DATACMNS-1174).

@mp911de, I've created [a sample app with a Reactive MongoDB repository and a JPA repository](https://github.com/bclozel/strict-repos).  Starting that application fails with:

```
2018-09-10 10:43:06.618 ERROR 3087 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.dao.InvalidDataAccessApiUsageException: Reactive Repositories are not supported by JPA. Offending repository is com.example.strictrepos.mongo.ExampleReactiveRepository!
	at org.springframework.data.repository.config.RepositoryConfigurationExtensionSupport.useRepositoryConfiguration(RepositoryConfigurationExtensionSupport.java:316) ~[spring-data-commons-2.0.10.BUILD-20180910.082402-70.jar:2.0.10.BUILD-SNAPSHOT]
	at org.springframework.data.repository.config.RepositoryConfigurationExtensionSupport.getRepositoryConfigurations(RepositoryConfigurationExtensionSupport.java:100) ~[spring-data-commons-2.0.10.BUILD-20180910.082402-70.jar:2.0.10.BUILD-SNAPSHOT]
	at org.springframework.data.repository.config.RepositoryConfigurationDelegate.registerRepositoriesIn(RepositoryConfigurationDelegate.java:126) ~[spring-data-commons-2.0.10.BUILD-20180910.082402-70.jar:2.0.10.BUILD-SNAPSHOT]
	at org.springframework.boot.autoconfigure.data.AbstractRepositoryConfigurationSourceSupport.registerBeanDefinitions(AbstractRepositoryConfigurationSourceSupport.java:60) ~[spring-boot-autoconfigure-2.0.5.BUILD-20180907.194911-78.jar:2.0.5.BUILD-SNAPSHOT]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.lambda$loadBeanDefinitionsFromRegistrars$1(ConfigurationClassBeanDefinitionReader.java:358) ~[spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[na:na]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsFromRegistrars(ConfigurationClassBeanDefinitionReader.java:357) ~[spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:145) ~[spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:117) ~[spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:328) ~[spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:233) ~[spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:271) ~[spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:91) ~[spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:694) ~[spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532) ~[spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:780) ~[spring-boot-2.0.5.BUILD-20180907.195016-78.jar:2.0.5.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:412) ~[spring-boot-2.0.5.BUILD-20180907.195016-78.jar:2.0.5.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333) ~[spring-boot-2.0.5.BUILD-20180907.195016-78.jar:2.0.5.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1277) ~[spring-boot-2.0.5.BUILD-20180907.195016-78.jar:2.0.5.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1265) ~[spring-boot-2.0.5.BUILD-20180907.195016-78.jar:2.0.5.BUILD-SNAPSHOT]
	at com.example.strictrepos.StrictReposApplication.main(StrictReposApplication.java:10) ~[classes/:na]
```

Reverting the Spring Data upgrade by removing  the `spring-data-releasetrain.version` override in the POM makes things work as expected.

Is there something wrong in the application setup? Is there something we should update in the Spring Boot auto-configuration to avoid that?

**Comment by mp911de** [comment]
Thanks. Going to have a look.

**Comment by mp911de** [comment]
We added a check to Spring Data to fail if a reactive repository is not supported by a store module but didn't consider the ordering of checks. Right now, we reject repositories too early, before even checking whether a particular store module is able to implement the repository.

**Comment by mp911de** [comment]
I filed [DATACMNS-1389](https://jira.spring.io/browse/DATACMNS-1389) to fix the issue.

**Comment by mp911de** [comment]
The fix is in place. @bclozel Care to give the latest Kay snapshots a try?

**Comment by bclozel** [comment]
My repro project works now and the offending Spring Boot integration test is locally green. I've manually [started a new CI run](https://ci.spring.io/teams/spring-boot/pipelines/spring-boot-2.0.x/jobs/build/builds/466) as well.

Thanks @mp911de !
