### ISSUE TITLE
Cassandra auto-configuration requires load balancing policy, reconnection policy and retry policy classes to have a default constructor

### ISSUE THREAD

**Issue by gekster** [spring-projects/spring-boot#14461]
I configured my spring data cassandra client using spring boot application.yml and autoconfiguration.

It works for me but only when I not use **spring.data.reconnection-policy** property. When I use any of them **(com.datastax.driver.core.policies.ConstantReconnectionPolicy** or **com.datastax.driver.core.policies.ExponentialReconnectionPolicy**) I goet this error on startup:

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.datastax.driver.core.policies.ConstantReconnectionPolicy]: No default constructor found; nested exception is java.lang.NoSuchMethodException: com.datastax.driver.core.policies.ConstantReconnectionPolicy.()
    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:127) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE] at org.springframework.boot.context.properties.PropertyMapper$Source.lambda$as$2(PropertyMapper.java:207) ~[spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
    at org.springframework.boot.context.properties.PropertyMapper$Source.to(PropertyMapper.java:302) ~[spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
    at org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration.cassandraCluster(CassandraAutoConfiguration.java:77) ~[spring-boot-autoconfigure-2.0.3.RELEASE.jar:2.0.3.RELEASE]
    at org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration$$EnhancerBySpringCGLIB$$2f475e40.CGLIB$cassandraCluster$0() ~[spring-boot-autoconfigure-2.0.3.RELEASE.jar:2.0.3.RELEASE]
```

I extended policy class and added default constructor there. With new class inside my application.yml everything works.

This is my application.yml:

I configured my spring data cassandra client using spring boot application.yml and autoconfiguration.

It works for me but only when I not use spring.data.reconnection-policy property. When I use any of them (com.datastax.driver.core.policies.ConstantReconnectionPolicy or com.datastax.driver.core.policies.ExponentialReconnectionPolicy) I goet this error on startup:

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.datastax.driver.core.policies.ConstantReconnectionPolicy]: No default constructor found; nested exception is java.lang.NoSuchMethodException: com.datastax.driver.core.policies.ConstantReconnectionPolicy.() 
    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:127) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE] 
    at org.springframework.boot.context.properties.PropertyMapper$Source.lambda$as$2(PropertyMapper.java:207) ~[spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE] 
    at org.springframework.boot.context.properties.PropertyMapper$Source.to(PropertyMapper.java:302) ~[spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE] 
    at org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration.cassandraCluster(CassandraAutoConfiguration.java:77) ~[spring-boot-autoconfigure-2.0.3.RELEASE.jar:2.0.3.RELEASE] 
    at org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration$$EnhancerBySpringCGLIB$$2f475e40.CGLIB$cassandraCluster$0() ~[spring-boot-autoconfigure-2.0.3.RELEASE.jar:2.0.3.RELEASE]
```

I extended policy class and added default constructor there. With new class inside my application.yml everything works. Is it possible to configure reconnection policy without workaround or this is a bug?
Spring Data 2.0.10.RELEASE

**Comment by wilkinsona** [comment]
It's a bug and I don't think there's a good way for us to offer property-based configuration of the reconnection or load balancing properties. If you want to customise them I would recommend either using your custom subclass that provides a default constructor or using a `org.springframework.boot.autoconfigure.cassandra.ClusterBuilderCustomizer` bean instead.

**Comment by wilkinsona** [comment]
The only option I can think of here is to deprecate the two properties and point people towards the cluster builder customiser instead.

**Comment by wilkinsona** [comment]
In 1.5 and 2.0 we're going to clarify that the policies must have a default constructor. We'll deprecate the properties in 2.1.
