### ISSUE TITLE
Environment variable that does not follow guidelines for use of _ is still successfully bound if another property source contains a property that is bound to the same target

### ISSUE THREAD

**Issue by Bert-R** [spring-projects/spring-boot#14479]
We have custom properties, built like this:

```
@ConfigurationProperties("yona")
@Configuration
public class YonaProperties
{
	@NestedConfigurationProperty
	private final AnalysisServiceProperties analysisService = new AnalysisServiceProperties();
```

Properties would be set on ``AnalysisServiceProperties`` in this way:
```
yona.analysisService.someProperty=someValue
```

Or through an environment variable, like this:
```
YONA_ANALYSIS_SERVICE_SOME_PROPERTY=someValue
```

With Spring Boot 1.5, it was OK to not have any ``yona.analysisService.xxx`` property in ``application.properties`` and still set one through an environment variable like ``YONA_ANALYSIS_SERVICE_XXX``. 

With Spring Boot 2.0.4, that doesn't work anymore. At least one ``yona.analysisService.xxx`` must exist in ``application.properties``. It's OK to set ``xxx`` in ``application.properties`` and ``yyy`` through the environment, but there needs to be at least one.

**Comment by wilkinsona** [comment]
Here's a minimal example that reproduces the behaviour described above:

```java
package com.example.demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.ConfigurableApplicationContext;

@SpringBootApplication
@EnableConfigurationProperties(YonaProperties.class)
public class Gh14479Application {

	public static void main(String[] args) {
		ConfigurableApplicationContext context = SpringApplication.run(Gh14479Application.class, args);
		YonaProperties yonaProperties = context.getBean(YonaProperties.class);
		System.out.println((yonaProperties.getAnalysisService().getAlpha()));
		System.out.println((yonaProperties.getAnalysisService().getBravo()));
	}

}

@ConfigurationProperties("yona")
class YonaProperties {

	private final AnalysisServiceProperties analysisService = new AnalysisServiceProperties();

	public AnalysisServiceProperties getAnalysisService() {
		return analysisService;
	}

	public class AnalysisServiceProperties {

		private String alpha;

		private String bravo;

		public String getAlpha() {
			return alpha;
		}

		public void setAlpha(String alpha) {
			this.alpha = alpha;
		}

		public String getBravo() {
			return bravo;
		}

		public void setBravo(String bravo) {
			this.bravo = bravo;
		}

	}

}
```

Run with no properties:

```
$ java -jar target/gh-14479-0.0.1-SNAPSHOT.jar
…
null
null
```

Run with an environment variable and a command line property and both take effect:

```
$ YONA_ANALYSIS_SERVICE_ALPHA=one java -jar target/gh-14479-0.0.1-SNAPSHOT.jar --yona.analysis-service.bravo=two
…
one
two
```

Run with just a command line property and it takes effect:

```
$ java -jar target/gh-14479-0.0.1-SNAPSHOT.jar --yona.analysis-service.bravo=two
…
null
two
```

Run with just an environment variable and it has no effect:

```
$ YONA_ANALYSIS_SERVICE_ALPHA=one java -jar target/gh-14479-0.0.1-SNAPSHOT.jar
…
null
null
```

**Comment by Bert-R** [comment]
That's it indeed. Thanks for making the repro!

**Comment by wilkinsona** [comment]
When only the environment variable is set, the configuration property name `yona.analysis-service` is called with `yona.analysis.service.alpha` and `yonaanalysisservicealpha` to see if it's an ancestor. In both cases `false` is returned so it appears that the are no properties to be bound to the `AnalysisServiceProperties` instance so binding stops.

When the property `yona.analysis-service.bravo` has been set on the command line in addition to the environment variable, the configuration property name `yona.analysis-service` is also called with `yona.analysis-service.bravo`. It correctly determines that it is an ancestor of the passed-in name, so binding continues and both properties are then bound.

**Comment by Bert-R** [comment]
That's actually not the case. See the property class implementation [here](https://github.com/yonadev/yona-server/blob/master/core/src/main/java/nu/yona/server/properties/AnalysisServiceProperties.java). The property name is camelCased, see [``application.properties``](https://github.com/yonadev/yona-server/blob/master/core/src/main/resources/application.properties).

**Comment by wilkinsona** [comment]
Sorry, I'm not sure what you think isn't the case. The property class and the configuration in `application.properties` are both fine. It's the environment variable that's problematic. Taking things back to your original example, you need to use `YONA_ANALYSISSERVICE_SOMEPROPERTY` rather than `YONA_ANALYSIS_SERVICE_SOME_PROPERTY` so that the `_` separators are only used in between properties and not within the name of a property.

**Comment by Bert-R** [comment]
Mmm. Is that the aspect of relaxed binding being a little less relaxed in 2.0?  :)

**Comment by wilkinsona** [comment]
Yes, this is part of the relaxed binding not being quite so relaxed.

**Comment by Bert-R** [comment]
OK, clear. It's a bit unfortunate that it sometimes works, depending on whether or not the property was bound otherwise.

**Comment by wilkinsona** [comment]
We'd like to fix this by the binding ignoring the environment variable that's malformed.

**Comment by wilkinsona** [comment]
Fixing this as we'd like will regress https://github.com/spring-projects/spring-boot/issues/10873.

I think we have a few options:

1. Revert the change for #10873 such that `foo.the-bar` just produces `FOO_THEBAR`
2. Change the ancestor checking somehow such that `yona.analysis-service` would be identified as an ancestor of `YONA_ANALYSIS_SERVICE_SOME_PROPERTY`
3. Live with the current behavior

2 feels like the least bad option, but I'm not sure how realistic it is.

**Comment by mbhave** [comment]
I think we should revert the change for #10873 because it's confusing that the 1.5 style properties only work sometimes.

**Comment by philwebb** [comment]
We could perhaps revert #10873 for 2.1, but I think it would be a bit harsh to do it in 2.0.x. If I remember correctly #10873 was also added at the request of a Spring Clould project (but I can't remember which one).

**Comment by wilkinsona** [comment]
I wonder if we could make the ancestor checking more lenient? What about ignoring everything that isn’t a letter, and then, ignoring case, seeing if one starts with the other. Occasional false positives aren’t the end of the world as it’s just used as a way of short-circuiting binding isn’t it?

**Comment by mbhave** [comment]
The ancestor check is also used in the [`MapBinder`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/properties/bind/MapBinder.java#L69) when binding entries in a map. Making the check lenient might cause some conversion exceptions there but I'm not totally sure.

**Comment by wilkinsona** [comment]
I've tried adding a separate, more lenient ancestor check and only calling it from the various `containsDescendantOf` methods on the various `ConfigurationPropertySource` implementations. To simulate a worst-case scenario, I'm just returned `true`. Without auto-configuration enabled it fixes the scenario described above. With auto-configuration enabled it breaks other property binding. Specifically, I see this failure:

```
org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'spring.info.build.location.u-r-l' to java.net.URL
	at org.springframework.boot.context.properties.bind.Binder.handleBindError(Binder.java:250) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:226) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.Binder.lambda$5(Binder.java:333) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:73) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:62) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:54) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.Binder.lambda$7(Binder.java:341) ~[classes/:na]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_181]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359) ~[na:1.8.0_181]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[na:1.8.0_181]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) ~[na:1.8.0_181]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[na:1.8.0_181]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_181]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[na:1.8.0_181]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_181]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[na:1.8.0_181]
	at org.springframework.boot.context.properties.bind.Binder.lambda$6(Binder.java:342) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:441) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.Binder$Context.withBean(Binder.java:427) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.Binder$Context.access$5(Binder.java:424) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.Binder.bindBean(Binder.java:339) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:278) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:221) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.Binder.lambda$5(Binder.java:333) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:73) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:62) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:54) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.Binder.lambda$7(Binder.java:341) ~[classes/:na]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_181]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359) ~[na:1.8.0_181]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[na:1.8.0_181]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) ~[na:1.8.0_181]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[na:1.8.0_181]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_181]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[na:1.8.0_181]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_181]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[na:1.8.0_181]
	at org.springframework.boot.context.properties.bind.Binder.lambda$6(Binder.java:342) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:441) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.Binder$Context.withBean(Binder.java:427) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.Binder$Context.access$5(Binder.java:424) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.Binder.bindBean(Binder.java:339) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:278) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:221) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.Binder.lambda$5(Binder.java:333) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:73) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:62) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:54) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.Binder.lambda$7(Binder.java:341) ~[classes/:na]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_181]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359) ~[na:1.8.0_181]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[na:1.8.0_181]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) ~[na:1.8.0_181]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[na:1.8.0_181]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_181]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[na:1.8.0_181]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_181]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[na:1.8.0_181]
	at org.springframework.boot.context.properties.bind.Binder.lambda$6(Binder.java:342) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:441) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.Binder$Context.withBean(Binder.java:427) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.Binder$Context.access$5(Binder.java:424) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.Binder.bindBean(Binder.java:339) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:278) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:221) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:210) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:192) ~[classes/:na]
	at org.springframework.boot.context.properties.ConfigurationPropertiesBinder.bind(ConfigurationPropertiesBinder.java:82) ~[classes/:na]
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.bind(ConfigurationPropertiesBindingPostProcessor.java:107) ~[classes/:na]
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:93) ~[classes/:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1691) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:573) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1135) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1062) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:818) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:724) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:197) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1267) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1124) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:535) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:759) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869) ~[spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) [classes/:na]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:386) [classes/:na]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) [classes/:na]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1242) [classes/:na]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1230) [classes/:na]
	at com.example.demo.Gh14479Application.main(Gh14479Application.java:15) [classes/:na]
Caused by: java.lang.IllegalStateException: Unable to get value for property u-r-l
	at org.springframework.boot.context.properties.bind.JavaBeanBinder$BeanProperty.lambda$0(JavaBeanBinder.java:307) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.JavaBeanBinder$Bean.get(JavaBeanBinder.java:186) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:49) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.Binder.lambda$7(Binder.java:341) ~[classes/:na]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_181]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359) ~[na:1.8.0_181]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[na:1.8.0_181]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) ~[na:1.8.0_181]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[na:1.8.0_181]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_181]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[na:1.8.0_181]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_181]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[na:1.8.0_181]
	at org.springframework.boot.context.properties.bind.Binder.lambda$6(Binder.java:342) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:441) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.Binder$Context.withBean(Binder.java:427) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.Binder$Context.access$5(Binder.java:424) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.Binder.bindBean(Binder.java:339) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:278) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:221) ~[classes/:na]
	... 99 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at org.springframework.boot.context.properties.bind.JavaBeanBinder$BeanProperty.lambda$0(JavaBeanBinder.java:304) ~[classes/:na]
	... 118 common frames omitted
Caused by: java.io.FileNotFoundException: class path resource [META-INF/build-info.properties] cannot be resolved to URL because it does not exist
	at org.springframework.core.io.ClassPathResource.getURL(ClassPathResource.java:195) ~[spring-core-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	... 123 common frames omitted
```

This is happening due to a call to `getURL` on the `Resource` that's held by `org.springframework.boot.autoconfigure.info.ProjectInfoProperties.Build`.

**Comment by mbhave** [comment]
I tried something here and it seems like it would work: https://github.com/mbhave/spring-boot/commit/b926b594be46f50318022175fd90cf6c8eb88d22

@wilkinsona @philwebb What do you think?

**Comment by philwebb** [comment]
This may have broken spring cloud stream
