### ISSUE TITLE
Update to 1.5.16 brings Mysql 5.1.47 that causes NPE

### ISSUE THREAD

**Issue by php-coder** [spring-projects/spring-boot#14638]
It could be an invalid issue but I'd like to heads up you that mysql 5.1.47 could lead to NPE in the code that was working before: https://bugs.mysql.com/bug.php?id=92089

I've upgraded from Spring Boot 1.5.15 to 1.5.16 and one of the tests start failing immediately:
```
Caused by: java.lang.NullPointerException: null
	at com.mysql.jdbc.PreparedStatement.setTimestamp(PreparedStatement.java:4241) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.setTimestamp(DelegatingPreparedStatement.java:147) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.setTimestamp(DelegatingPreparedStatement.java:147) ~[commons-dbcp-1.4.jar:1.4]
	at org.springframework.jdbc.core.StatementCreatorUtils.setValue(StatementCreatorUtils.java:456) ~[spring-jdbc-4.3.19.RELEASE.jar:4.3.19.RELEASE]
	at org.springframework.jdbc.core.StatementCreatorUtils.setParameterValueInternal(StatementCreatorUtils.java:241) ~[spring-jdbc-4.3.19.RELEASE.jar:4.3.19.RELEASE]
	at org.springframework.jdbc.core.StatementCreatorUtils.setParameterValue(StatementCreatorUtils.java:156) ~[spring-jdbc-4.3.19.RELEASE.jar:4.3.19.RELEASE]
	at org.springframework.jdbc.core.PreparedStatementCreatorFactory$PreparedStatementCreatorImpl.setValues(PreparedStatementCreatorFactory.java:292) ~[spring-jdbc-4.3.19.RELEASE.jar:4.3.19.RELEASE]
	at org.springframework.jdbc.core.PreparedStatementCreatorFactory$PreparedStatementCreatorImpl.createPreparedStatement(PreparedStatementCreatorFactory.java:244) ~[spring-jdbc-4.3.19.RELEASE.jar:4.3.19.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633) ~[spring-jdbc-4.3.19.RELEASE.jar:4.3.19.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:910) ~[spring-jdbc-4.3.19.RELEASE.jar:4.3.19.RELEASE]
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.update(NamedParameterJdbcTemplate.java:318) ~[spring-jdbc-4.3.19.RELEASE.jar:4.3.19.RELEASE]
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.update(NamedParameterJdbcTemplate.java:299) ~[spring-jdbc-4.3.19.RELEASE.jar:4.3.19.RELEASE]
	at ru.mystamps.web.feature.series.JdbcSeriesDao.add(JdbcSeriesDao.java:120) ~[classes/:na]
	at ru.mystamps.web.feature.series.SeriesServiceImpl.add(SeriesServiceImpl.java:106) ~[classes/:na]
```

Here is the `JdbcSeriesDao.add()` method: https://github.com/php-coder/mystamps/blob/6d4e10a746b7aed3c50b40b71ee7993c8f5f5772/src/main/java/ru/mystamps/web/feature/series/JdbcSeriesDao.java#L97-L133

I'm sorry if it's an invalid issue because I'm using commons-dbcp (I don't remember whether it's supported in 1.5.x or not).

**Comment by snicoll** [comment]
Thanks but there's nothing we can do here. Once the bug in MySQL is fixed and released we'll pick it up.
