### ISSUE TITLE
Regression: vanilla non-web app barfs on startup

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#14697]
This change has introduced a bug I think: https://github.com/spring-projects/spring-boot/issues/14589. It needs to check if the web class are on the classpath before comparing them to the current context class.

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/web/context/WebApplicationContext
	at org.springframework.boot.SpringApplication.deduceWebApplicationType(SpringApplication.java:1204)
	at org.springframework.boot.SpringApplication.setApplicationContextClass(SpringApplication.java:1199)
	at org.springframework.boot.reflect.AutoListener.onApplicationEvent(AutoListener.java:62)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.starting(EventPublishingRunListener.java:69)
	at org.springframework.boot.SpringApplicationRunListeners.starting(SpringApplicationRunListeners.java:48)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
	at com.example.auto.SpringApplication.run(SpringApplication.java:42)
	at com.example.auto.SpringApplication.run(SpringApplication.java:37)
	at com.example.auto.AutoApplication.main(AutoApplication.java:39)
Caused by: java.lang.ClassNotFoundException: org.springframework.web.context.WebApplicationContext
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more
```

**Comment by snicoll** [comment]
😱

**Comment by wilkinsona** [comment]
Thanks for catching this, @dsyer. #14589 hasn't made it into a release yet so I've re-opened it so that we can fix the CNFE.
