### ISSUE TITLE
Endpoint IDs should support camelCase

### ISSUE THREAD

**Issue by jfgosselin** [spring-projects/spring-boot#14773]
Regarding #11107 as discussed with @snicoll , an endpoint id with camel case (or pascal case) is rejected when a method is added to the Endpoint .

This was tested on Spring Boot 2.0.5 and 2.1.0.M4

e.g.:

```
@Component
@Endpoint(id = "camelCase")
public class CamelCaseEndpoint {

  @ReadOperation
  public String hello() {
    return "hello";
  }
}
```

```
Description:

Configuration property name 'management.endpoint.camelCase.cache.time-to-live' is not valid:

    Invalid characters: 'C'
    Bean: jmxMBeanExporter
    Reason: Canonical names should be kebab-case ('-' separated), lowercase alpha-numeric characters and must start with a letter

Action:

Modify 'management.endpoint.camelCase.cache.time-to-live' so that it conforms to the canonical names requirements.
```

**Comment by philwebb** [comment]
I wonder if we shouldn't just make it a requirement that endpoint IDs are a-z and lowercase.

**Comment by snicoll** [comment]
I am not sure we should do that considering that the ID is the default path and that would be rather limited. We have some code that translates the ID to a valid canonical name (this issue was reported before) but for some reason a regression of some kind was introduced.

**Comment by snicoll** [comment]
`EndpointIdTimeToLivePropertyFunction` uses endpoint id to compute the cache ttl key and doesn't take this into account.

**Comment by snicoll** [comment]
Actually both properties are affected. `OnEnabledEndpointCondition` does not work with an id that is not using our canonical format. And `EndpointIdTimeToLivePropertyFunction` is affected as well.

Both would work if `ConfigurationMetadata#toDashedCase()` was made available somewhere  or if, more generally, there was a way to "clean" a configuration name so that it complies with our canonical format. 

We said that going from the canonical format to the original format wasn't possible but I am not sure we've discussed the possibility to go from a format to the canonical format. We would need this feature to properly support camel case endpoints.

Due to the annotation processor, that logic will have to be copy/pasted unfortunately.

**Comment by snicoll** [comment]
We need to figure out what we want to do with #14802 first

**Comment by philwebb** [comment]
I'm pretty convinced we should enforce some rules around endpoint IDs. We could support camel case if we're careful. I think limiting chars to alpha numeric would be a good move regardless.

**Comment by snicoll** [comment]
Right now, it breaks if you have a main read operation as we attempt to get the TTL. If you tried to make your endpoint conditional, it would break as well. 

There are two competing use cases here:

1. The ID is used to defer some things (the web path and the JMX name being the most obvious)
2. We want the format of the id to be predictable

It is hard to have an opinion for the web path as different users have different requirements. We want to clean and harmonize the JMX name attribute however (to use pascal case which is another part that's not really consistent right now, see `DefaultEndpointObjectNameFactory`).

In the end, the only reason why I am hesitant to force users to use the canonical format is that they'd have to configure a custom web path if they want one with a different format.

Another potential solution that was discussed offline was to move the simple `String` to `EndpointId`. This class would take the raw value from the annotation and would be able to produce a canonical version out of it which would be used in all configuration keys. If it isn't able to, it should produce an exception. Due to the AP dependencies, it means this code would have to be duplicated.

The only thing weird left is to have an endpoint identified as `mySuperEndpoint` and having to exclude it by id using `my-super-endpoint`.

**Comment by philwebb** [comment]
Here's the full stacktrace for the issue reported:

```
org.springframework.boot.context.properties.source.InvalidConfigurationPropertyNameException: Configuration property name 'management.endpoint.camelCase.cache.time-to-live' is not valid
	at org.springframework.boot.context.properties.source.InvalidConfigurationPropertyNameException.throwIfHasInvalidChars(InvalidConfigurationPropertyNameException.java:51) ~[classes/:na]
	at org.springframework.boot.context.properties.source.ConfigurationPropertyName.lambda$3(ConfigurationPropertyName.java:459) ~[classes/:na]
	at org.springframework.boot.context.properties.source.ConfigurationPropertyName.processElement(ConfigurationPropertyName.java:550) ~[classes/:na]
	at org.springframework.boot.context.properties.source.ConfigurationPropertyName.process(ConfigurationPropertyName.java:540) ~[classes/:na]
	at org.springframework.boot.context.properties.source.ConfigurationPropertyName.of(ConfigurationPropertyName.java:456) ~[classes/:na]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:166) ~[classes/:na]
	at org.springframework.boot.actuate.autoconfigure.endpoint.EndpointIdTimeToLivePropertyFunction.apply(EndpointIdTimeToLivePropertyFunction.java:54) ~[classes/:na]
	at org.springframework.boot.actuate.autoconfigure.endpoint.EndpointIdTimeToLivePropertyFunction.apply(EndpointIdTimeToLivePropertyFunction.java:36) ~[classes/:na]
	at org.springframework.boot.actuate.endpoint.invoker.cache.CachingOperationInvokerAdvisor.apply(CachingOperationInvokerAdvisor.java:46) ~[classes/:na]
	at org.springframework.boot.actuate.endpoint.invoke.OperationInvokerAdvisor.apply(OperationInvokerAdvisor.java:42) ~[classes/:na]
	at org.springframework.boot.actuate.endpoint.annotation.DiscoveredOperationsFactory.applyAdvisors(DiscoveredOperationsFactory.java:104) ~[classes/:na]
	at org.springframework.boot.actuate.endpoint.annotation.DiscoveredOperationsFactory.createOperation(DiscoveredOperationsFactory.java:96) ~[classes/:na]
	at org.springframework.boot.actuate.endpoint.annotation.DiscoveredOperationsFactory.lambda$createOperation$1(DiscoveredOperationsFactory.java:80) ~[classes/:na]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_144]
	at java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet.lambda$entryConsumer$0(Collections.java:1575) ~[na:1.8.0_144]
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812) ~[na:1.8.0_144]
	at java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$UnmodifiableEntrySetSpliterator.tryAdvance(Collections.java:1594) ~[na:1.8.0_144]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[na:1.8.0_144]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) ~[na:1.8.0_144]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[na:1.8.0_144]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_144]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[na:1.8.0_144]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_144]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[na:1.8.0_144]
	at org.springframework.boot.actuate.endpoint.annotation.DiscoveredOperationsFactory.createOperation(DiscoveredOperationsFactory.java:82) ~[classes/:na]
	at org.springframework.boot.actuate.endpoint.annotation.DiscoveredOperationsFactory.lambda$createOperations$0(DiscoveredOperationsFactory.java:74) ~[classes/:na]
	at org.springframework.core.MethodIntrospector.lambda$selectMethods$0(MethodIntrospector.java:70) ~[spring-core-5.0.10.BUILD-SNAPSHOT.jar:5.0.10.BUILD-SNAPSHOT]
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:562) ~[spring-core-5.0.10.BUILD-SNAPSHOT.jar:5.0.10.BUILD-SNAPSHOT]
	at org.springframework.core.MethodIntrospector.selectMethods(MethodIntrospector.java:68) ~[spring-core-5.0.10.BUILD-SNAPSHOT.jar:5.0.10.BUILD-SNAPSHOT]
	at org.springframework.boot.actuate.endpoint.annotation.DiscoveredOperationsFactory.createOperations(DiscoveredOperationsFactory.java:73) ~[classes/:na]
	at org.springframework.boot.actuate.endpoint.annotation.EndpointDiscoverer.addOperations(EndpointDiscoverer.java:216) ~[classes/:na]
	at org.springframework.boot.actuate.endpoint.annotation.EndpointDiscoverer.convertToEndpoint(EndpointDiscoverer.java:194) ~[classes/:na]
	at org.springframework.boot.actuate.endpoint.annotation.EndpointDiscoverer.convertToEndpoints(EndpointDiscoverer.java:185) ~[classes/:na]
	at org.springframework.boot.actuate.endpoint.annotation.EndpointDiscoverer.discoverEndpoints(EndpointDiscoverer.java:125) ~[classes/:na]
	at org.springframework.boot.actuate.endpoint.annotation.EndpointDiscoverer.getEndpoints(EndpointDiscoverer.java:117) ~[classes/:na]
	at org.springframework.boot.actuate.autoconfigure.endpoint.jmx.JmxEndpointAutoConfiguration.jmxMBeanExporter(JmxEndpointAutoConfiguration.java:95) ~[classes/:na]
	at org.springframework.boot.actuate.autoconfigure.endpoint.jmx.JmxEndpointAutoConfiguration$$EnhancerBySpringCGLIB$$647fa87b.CGLIB$jmxMBeanExporter$1(<generated>) ~[classes/:na]
	at org.springframework.boot.actuate.autoconfigure.endpoint.jmx.JmxEndpointAutoConfiguration$$EnhancerBySpringCGLIB$$647fa87b$$FastClassBySpringCGLIB$$24b727c4.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-5.0.10.BUILD-SNAPSHOT.jar:5.0.10.BUILD-SNAPSHOT]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:365) ~[spring-context-5.0.10.BUILD-SNAPSHOT.jar:5.0.10.BUILD-SNAPSHOT]
	at org.springframework.boot.actuate.autoconfigure.endpoint.jmx.JmxEndpointAutoConfiguration$$EnhancerBySpringCGLIB$$647fa87b.jmxMBeanExporter(<generated>) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_144]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.0.10.BUILD-SNAPSHOT.jar:5.0.10.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:583) ~[spring-beans-5.0.10.BUILD-SNAPSHOT.jar:5.0.10.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1246) ~[spring-beans-5.0.10.BUILD-SNAPSHOT.jar:5.0.10.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1096) ~[spring-beans-5.0.10.BUILD-SNAPSHOT.jar:5.0.10.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:535) ~[spring-beans-5.0.10.BUILD-SNAPSHOT.jar:5.0.10.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495) ~[spring-beans-5.0.10.BUILD-SNAPSHOT.jar:5.0.10.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.10.BUILD-SNAPSHOT.jar:5.0.10.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.0.10.BUILD-SNAPSHOT.jar:5.0.10.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.10.BUILD-SNAPSHOT.jar:5.0.10.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.10.BUILD-SNAPSHOT.jar:5.0.10.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:759) ~[spring-beans-5.0.10.BUILD-SNAPSHOT.jar:5.0.10.BUILD-SNAPSHOT]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) ~[spring-context-5.0.10.BUILD-SNAPSHOT.jar:5.0.10.BUILD-SNAPSHOT]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:548) ~[spring-context-5.0.10.BUILD-SNAPSHOT.jar:5.0.10.BUILD-SNAPSHOT]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[classes/:na]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) [classes/:na]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:386) [classes/:na]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) [classes/:na]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1242) [classes/:na]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1230) [classes/:na]
	at com.example.demo.ScratchApplication.main(ScratchApplication.java:10) [classes/:na]
```

**Comment by snicoll** [comment]
This change broke Spring Cloud as it has an endpoint named `hystrix.stream`. Having the dot there is less than ideal and I think the Spring Cloud team should do something about it 

Reopening to see how we can assist them with that change.

**Comment by dsyer** [comment]
FWIW that endpoint name was chosen by Netflix in the year dot. I think it's unreasonable not to support endpoint paths that are valid URLs.

**Comment by snicoll** [comment]
> I think it's unreasonable not to support endpoint paths that are valid URLs

That's a fair statement if that was configuring the path. It isn't. The ID is used in many other places like in configuration properties and to infer the `ObjectName` of the `MBean` we expose for the endpoint.

**Comment by dsyer** [comment]
I know that. It's just a bit of a steep gradient here - all Spring Cloud apps with Hystrix and Actuator are now broken. Maybe we could grandfather them somehow?

`WebEndpointProperties` as a `pathMapping` property: 

> Mapping between endpoint IDs and the path that should expose them.

That's ultimately probably all we need if we can get the rules straight about legal ids? But that might not solve the problem of existing apps.

**Comment by 391861737** [comment]
I suppose it make sense if `spring-boot-actuator` parses the endpoint ids and convert them to the alternative camelCased name so that it can support both side ?

**Comment by philwebb** [comment]
I think we need to support `.` names in 2.0.x, it's too much of a breaking change otherwise.

**Comment by philwebb** [comment]
> I think it's unreasonable not to support endpoint paths that are valid URLs,

I know it's a pain, but I think I'd rather selectively add supported chars to the ID if they're needed rather than supporting all URL chars. I'll start with adding `.` and we'll see how far that gets us.

**Comment by philwebb** [comment]
Reopening because of `-` :(

https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-commons/src/main/java/org/springframework/cloud/client/serviceregistry/endpoint/ServiceRegistryEndpoint.java

**Comment by philwebb** [comment]
Reopening again to consider the URL changing to lowercase
