### ISSUE TITLE
public/error/error.html not picked up

### ISSUE THREAD

**Issue by agent0** [spring-projects/spring-boot#14811]
Hi,

in my application I have turned off the whitelabel error page. When I define an error page for a specific HTTP response code in the public/error directory, the respective page is shown when the error arises. However, when an error is issued where no specific page ist available, the generic page (error.html) is not shown, instead I get an exception that I have a circular view path defined:

```
javax.servlet.ServletException: Circular view path [error]: would dispatch back to the current handler URL [/error] again. Check your ViewResolver setup! (Hint: This may be the result of an unspecified view, due to default view name generation.)
	at org.springframework.web.servlet.view.InternalResourceView.prepareForRendering(InternalResourceView.java:209)
	at org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:147)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:314)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1325)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1069)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1008)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:866)
```
A brief look into  `DefaultErrorWebExceptionHandler` showed, that indeed error.html should be displayed in this case...

**Comment by philwebb** [comment]
Do you have a small sample you can share that shows the problem?

**Comment by agent0** [comment]
Not at hand, I might be able to put one together in the next couple of days.

**Comment by agent0** [comment]
I tried setting up an example using the starter project provided by spring.io (https://spring.io/guides/gs/spring-boot/). Unfortunatly, the error page handling as described in https://docs.spring.io/spring-boot/docs/2.0.5.RELEASE/reference/html/boot-features-developing-web-applications.html did not work at all: I put a custom 404.html in public/error and according to the documentation, the error page should be displayed even without disabling the whitelabel error page. This was not the case and after adding `server.error.whitelabel.enabled=false` in `application.properties`, the above error is thrown.

**Comment by agent0** [comment]
[14811.zip](https://github.com/spring-projects/spring-boot/files/2476154/14811.zip)
Here is the minimal starter project. Opening `http://localhost:8080/Welcome.html` should display a static welcome page, any other URL should give the error.

**Comment by agent0** [comment]
Ok, I seem to understand, where my basic fault lies: since we are not using the reactive web package, `DefaultErrorWebExceptionHandler` is not used at all, instead the `BasicErrorController` comes into play. Although the two classes have similar functionality to map HTTP status codes to custom error pages, the latter appears not to have a fallback mechanism (`error.html`) that applies if no specific page is found. What I still do not understand is why the basic example I posted does not work as described...

**Comment by bclozel** [comment]
In your sample, the error page is named `404..html`, with an extra `.` in it. Removing that dot makes things work as expected.
