### ISSUE TITLE
Fix WebFlux instrumentation after SPR-17395

### ISSUE THREAD

**Issue by making** [spring-projects/spring-boot#14876]
After update to Spring Boot 2.1.0.RC1,   `ClassCastException` occurred as follows

```
java.lang.ClassCastException: class java.lang.String cannot be cast to class org.springframework.web.util.pattern.PathPattern (java.lang.String is in module java.base of loader 'bootstrap'; org.springframework.web.util.pattern.PathPattern is in unnamed module of loader 'app')
	at org.springframework.boot.actuate.metrics.web.reactive.server.WebFluxTags.uri(WebFluxTags.java:98)
	at org.springframework.boot.actuate.metrics.web.reactive.server.DefaultWebFluxTagsProvider.httpRequestTags(DefaultWebFluxTagsProvider.java:37)
	at org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter.error(MetricsWebFilter.java:104)
	at org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter.lambda$filter$3(MetricsWebFilter.java:86)
```

While this is [an issue in Spring Framework](https://jira.spring.io/browse/SPR-17395), Spring Boot should have an integration test to detect this detect that.

**Comment by bclozel** [comment]
Here is a workaround in the meantime - developers can override the default `WebFluxTagsProvider` bean and provide their own implementation like this:

```java
package com.example.demo;

import java.util.Arrays;

import io.micrometer.core.instrument.Tag;

import org.springframework.boot.actuate.metrics.web.reactive.server.WebFluxTags;
import org.springframework.boot.actuate.metrics.web.reactive.server.WebFluxTagsProvider;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.http.HttpStatus;
import org.springframework.web.reactive.HandlerMapping;
import org.springframework.web.reactive.function.server.RouterFunctions;
import org.springframework.web.server.ServerWebExchange;
import org.springframework.web.util.pattern.PathPattern;

@Configuration
public class WebFluxMetrixConfig {

	@Bean
	public WebFluxTagsProvider customTagsProvider() {
		return new WebFluxTagsProvider() {

			private final Tag URI_NOT_FOUND = Tag.of("uri", "NOT_FOUND");
			private final Tag URI_REDIRECTION = Tag.of("uri", "REDIRECTION");
			private final Tag URI_ROOT = Tag.of("uri", "root");

			@Override
			public Iterable<Tag> httpRequestTags(ServerWebExchange exchange, Throwable exception) {
				return Arrays.asList(WebFluxTags.method(exchange), uriTag(exchange),
						WebFluxTags.exception(exception), WebFluxTags.status(exchange),
						WebFluxTags.outcome(exchange));
			}

			Tag uriTag(ServerWebExchange exchange) {
				String matchingPattern = exchange
						.getAttribute(RouterFunctions.MATCHING_PATTERN_ATTRIBUTE);
				if (matchingPattern != null) {
					return Tag.of("uri", matchingPattern);
				}
				PathPattern pathPattern = exchange
						.getAttribute(HandlerMapping.BEST_MATCHING_PATTERN_ATTRIBUTE);
				if (pathPattern != null) {
					return Tag.of("uri", pathPattern.getPatternString());
				}
				HttpStatus status = exchange.getResponse().getStatusCode();
				if (status != null) {
					if (status.is3xxRedirection()) {
						return URI_REDIRECTION;
					}
					if (status == HttpStatus.NOT_FOUND) {
						return URI_NOT_FOUND;
					}
				}
				String path = exchange.getRequest().getPath().value();
				if (path.isEmpty()) {
					return URI_ROOT;
				}
				return Tag.of("uri", path);
			}
		};
	}
}
```

**Comment by making** [comment]
It works for me, thanks!

**Comment by bclozel** [comment]
[SPR-17395](https://jira.spring.io/browse/SPR-17395) added integration tests for this case. I've just updated the instrumentation since we don't need a specific case for WebFlux.fn now - everything is configured through `RouterFunctionMapping` and is using the same request attribute now.
