### ISSUE TITLE
spring boot 2.0 with oracle cluster by using hikari pool,  Cause: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: null

### ISSUE THREAD

**Issue by godpit** [spring-projects/spring-boot#14930]
application.properties:

```
spring.datasource.url=jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = xxx)(PORT = 1521))(ADDRESS = (PROTOCOL = TCP)(HOST = xxx)(PORT = 1521))(ADDRESS = (PROTOCOL = TCP)(HOST = xxx)(PORT = 1521))(LOAD_BALANCE = no)(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = mboapdb)))
spring.datasource.hikari.username=xxx
spring.datasource.hikari.password=xxx
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
```

```
error:
2018-10-23 14:08:25.860  INFO 121346 --- [nio-8092-exec-1] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2018-10-23 14:08:27.252 ERROR 121346 --- [nio-8092-exec-1] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Exception during pool initialization.

java.lang.NullPointerException: null
        at oracle.jdbc.driver.T4CConnection.updateSessionProperties(T4CConnection.java:1862) ~[ojdbc7-12.2.0.1.0.jar!/:12.1.0.1.0]
        at oracle.jdbc.driver.T4CTTIkvarr.unmarshal(T4CTTIkvarr.java:119) ~[ojdbc7-12.2.0.1.0.jar!/:12.1.0.1.0]
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:515) ~[ojdbc7-12.2.0.1.0.jar!/:12.1.0.1.0]
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249) ~[ojdbc7-12.2.0.1.0.jar!/:12.1.0.1.0]
        at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:416) ~[ojdbc7-12.2.0.1.0.jar!/:12.1.0.1.0]
        at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:825) ~[ojdbc7-12.2.0.1.0.jar!/:12.1.0.1.0]
        at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:596) ~[ojdbc7-12.2.0.1.0.jar!/:12.1.0.1.0]
        at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:715) ~[ojdbc7-12.2.0.1.0.jar!/:12.1.0.1.0]
        at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:385) ~[ojdbc7-12.2.0.1.0.jar!/:12.1.0.1.0]
        at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:30) ~[ojdbc7-12.2.0.1.0.jar!/:12.1.0.1.0]
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:564) ~[ojdbc7-12.2.0.1.0.jar!/:12.1.0.1.0]
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117) ~[HikariCP-2.7.9.jar!/:na]
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123) ~[HikariCP-2.7.9.jar!/:na]
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:365) ~[HikariCP-2.7.9.jar!/:na]
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:194) ~[HikariCP-2.7.9.jar!/:na]
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:460) [HikariCP-2.7.9.jar!/:na]
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:534) [HikariCP-2.7.9.jar!/:na]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) [HikariCP-2.7.9.jar!/:na]
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) [HikariCP-2.7.9.jar!/:na]
```

However, another one is ok.

```
spring.datasource.url=jdbc:oracle:thin:@//xxxx:1521/orcl
spring.datasource.hikari.username=xx
spring.datasource.hikari.password=xx
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
```

please, help me, thanks a lot!

**Comment by godpit** [comment]
use oracle 12c

**Comment by philwebb** [comment]
I don't think this is a bug in Spring Boot. We're simply passing connection strings to the JDBC driver. It looks like an error with `ojdbc7` or your connection string is malformed.

I'd suggest asking on stackoverflow.com to see if anyone else has had the issue.
