### ISSUE TITLE
log4j2 logfile is blank if spring-boot-starter-web isn't part of the project when using java 11

### ISSUE THREAD

**Issue by ssinger** [spring-projects/spring-boot#15074]
If I create a spring-boot application that uses the log4j2 starter and configure it to log to a file and I start the application I see that the log file gets created but it is always empty.

Everything works as expected with java 8 (the logs go in the file) but if I run the application with java 11 I get an empty file

If I add the spring-boot-starter-web to the pom file I then get data in my log file but I think the logging starts later in the startup process than normal.

If my project has a log42.properties in the classpath (versus log4j2-basic.properties ) then logging works.

[log4j2-failures.zip](https://github.com/spring-projects/spring-boot/files/2542738/log4j2-failures.zip)

The attached project demonstrates this.
I see this with spring-boot 2.1.0 and 2.0.6

**Comment by wilkinsona** [comment]
Thanks for the same but the `src` folder in the zip appears to be empty:

```
 unzip -l log4j2-failures.zip 
Archive:  log4j2-failures.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
       51  11-02-2018 13:54   application.properties
     1813  11-02-2018 14:02   pom.xml
        0  11-02-2018 12:09   src/
---------                     -------
     1864                     3 files
```

Could you update it with the necessary source files please?

**Comment by ssinger** [comment]
[log4j2-failures.zip](https://github.com/spring-projects/spring-boot/files/2543003/log4j2-failures.zip)

Sorry about that. Try this version

**Comment by wilkinsona** [comment]
Thanks. I can run the sample now but it has left me a bit confused. Why are you resetting the `LoggerContext` in a bean? If I remove that and update your `application.properties` file to configure `logging.file=test.log` which is the simplest way to configure logging to a file, I get console output and output in `test.log` that looks like this when run with Java 11:

```
2018-11-02 15:58:50.152  INFO 32106 --- [main] t.Main                                   : Starting Main on Andys-MacBook-Pro.local with PID 32106 (/Users/awilkinson/Downloads/log4j2-failures-2/target/classes started by awilkinson in /Users/awilkinson/Downloads/log4j2-failures-2)
2018-11-02 15:58:50.158  INFO 32106 --- [main] t.Main                                   : No active profile set, falling back to default profiles: default
2018-11-02 15:58:50.481  INFO 32106 --- [main] t.Main                                   : Started Main in 0.632 seconds (JVM running for 2.885)
```

Can you please simplify the sample further and describe precisely what needs to be done and in which directory to reproduce the problem?

**Comment by ssinger** [comment]
Also worth noting.

If I run the program with
mvn spring-boot:run 
it works (I get log output on the console and in the file) but if I do it via java directly I don't

**Comment by wilkinsona** [comment]
Thanks, I can reproduce the behaviour you've described now. When you add `spring-boot-starter-web` all of the logging that appears is from Tomcat:

```
2018-11-02 19:59:17.193  INFO 37358 --- [main] o.a.c.c.StandardService                  : Starting service [Tomcat]
2018-11-02 19:59:17.197  INFO 37358 --- [main] o.a.c.c.StandardEngine                   : Starting Servlet Engine: Apache Tomcat/9.0.12
2018-11-02 19:59:17.207  INFO 37358 --- [main] o.a.c.c.AprLifecycleListener             : The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/Users/awilkinson/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.]
2018-11-02 19:59:17.278  INFO 37358 --- [main] o.a.c.c.C.[.[.[/]                        : Initializing Spring embedded WebApplicationContext
```

This is significant as Tomcat uses Java Util Logging which is then routed into Log4j2. It would appear that logging that's using the Commons Logging API (as Spring Boot and Spring Framework do) isn't being routed correctly, but logging that uses JUL is.

**Comment by wilkinsona** [comment]
It's not the routing that's wrong, but Log4J's configuration of the root logger's level. It ends up being ERROR because Log4J ends up with two `LoggerContext` instances, one that Boot's configured (created first) and another that's left with its default configuration. The second context is created due to a failure to find the first. There's a clue in the output as to why the first one isn't found and re-used:

```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. 
```

This also results in an NPE that Log4J swallows:

```
java.lang.NullPointerException
	at org.apache.logging.log4j.util.StackLocator.getCallerClass(StackLocator.java:110)
	at org.apache.logging.log4j.util.StackLocator.getCallerClass(StackLocator.java:123)
	at org.apache.logging.log4j.util.StackLocatorUtil.getCallerClass(StackLocatorUtil.java:55)
	at org.apache.logging.log4j.util.StackLocatorUtil.getCallerClass(StackLocatorUtil.java:49)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:72)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:228)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:174)
	at org.springframework.boot.logging.log4j2.Log4J2LoggingSystem.getLoggerContext(Log4J2LoggingSystem.java:264)
	at org.springframework.boot.logging.log4j2.Log4J2LoggingSystem.beforeInitialize(Log4J2LoggingSystem.java:131)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationStartingEvent(LoggingApplicationListener.java:217)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:196)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.starting(EventPublishingRunListener.java:69)
	at org.springframework.boot.SpringApplicationRunListeners.starting(SpringApplicationRunListeners.java:48)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at test.Main.main(Main.java:11)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
```

This prevents Log4J from determining the caller's class and, therefore, from getting its `ClassLoader`. The `ClassLoader` is needed as that's how a `LoggerContext` is looked up.

I believe we can avoid the problem by giving Log4J a helping hand and passing in the `ClassLoader` when we ask `LogManager` for the context:

```java
LogManager.getContext(getClass().getClassLoader(), false);
```

**Comment by wilkinsona** [comment]
The change described above means that we now correctly initialise the `LoggerContext` for classes loaded by `LaunchedURLClassLoader`. Without this change, Boot was initialising the default context. A side-effect of correcting this is that Tomcat's logging is lost. This occurs because Tomcat's logging, which is routed into Log4J for the JUL SLF4J bridge, uses the default context. It uses the default context because `Log4jLoggerFactory` is [reliant on being able to get the caller's class](https://github.com/apache/logging-log4j2/blob/8a063ce09bf59bbf96e82f728a06b913cde8128d/log4j-slf4j-impl/src/main/java/org/apache/logging/slf4j/Log4jLoggerFactory.java#L42-L43) which doesn't work on Java 11. I believe logging performed via JBoss logging also suffers from a similar limitation.

As things stand, it looks like we should recommend that users of Java 11 stick with Logback as Log4J2 does not appear to be fully Java 11 compatible.

**Comment by wilkinsona** [comment]
Thanks to [this comment](https://github.com/spring-projects/spring-boot/issues/12523#issuecomment-435488830) from @lumeche, I now realise that I have done Log4J2 a disservice. It is Java 11 compatible, due to [this alternative implementation of `StackLocator`](https://github.com/apache/logging-log4j2/blob/master/log4j-api-java9/src/main/java/org/apache/logging/log4j/util/StackLocator.java) that is packaged in a multi-release jar. That doesn't work in a Spring Boot fat jar as we've yet to implement support for multi-release jars nested in `BOOT-INF/lib` (#12523).

**Comment by MartyIX** [comment]
> As things stand, it looks like we should recommend that users of Java 11 stick with Logback as Log4J2 does not appear to be fully Java 11 compatible.

I can't do that in my project as I use some custom Log4j2 plugins. This issue currently blocks me from upgrading to JDK 11.
