### ISSUE TITLE
BeanDefinitionStoreException after Upgrading to Boot 2.1.0

### ISSUE THREAD

**Issue by THD-Thomas-Lang** [spring-projects/spring-boot#15178]
Hey there,  
after upgrading from Spring Boot 2.0.6 to Spring Boot 2.1.0 i am getting the above exception:
`org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: file [D:\dev\projects\okb\target\okb-0.0.1-SNAPSHOT\WEB-INF\classes\de\thd\okb\component\MailHelper.class]; nested exception is java.lang.ArrayIndexOutOfBoundsException: 257`
The given component is defined as follows:
```java
package de.thd.okb.component;

import de.thd.okb.model.db.JobOffer;
import de.thd.okb.model.dto.ExpiredJobOfferProjection;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.MessageSource;
import org.springframework.context.annotation.PropertySource;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.core.env.Environment;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.stereotype.Component;
import org.thymeleaf.TemplateEngine;
import org.thymeleaf.context.Context;

import javax.validation.constraints.NotNull;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * Helper for creating mails.
 *
 * @author tlang
 */
@Component
@Slf4j
@RequiredArgsConstructor(onConstructor = @__(@Autowired))
public class MailHelper implements IMailHelper {

    private final @NonNull
    Environment environment;

    private final @NonNull
    MessageSource messageSource;

    private final @NonNull
    TemplateEngine templateEngine;

    private final @NonNull
    IMessageHelper messageHelper;

    /**
     * Generates email messages based on the given values.
     *
     * @param emailAddress given email addresses
     * @param jobOffers    given job offers
     * @return Iterable of SimpleMailMessage
     */
    @Override
    public Iterable<SimpleMailMessage> generateNewJobOfferEmails(@NonNull Iterable<String> emailAddress, @NonNull Iterable<JobOffer> jobOffers) {
        final Context ctx = new Context(LocaleContextHolder.getLocale());
        Set<SimpleMailMessage> simpleMailMessages = new HashSet<>();
        final SimpleMailMessage[] simpleMailMessage = {new SimpleMailMessage()};
        emailAddress.forEach((email) -> jobOffers.forEach((jobOffer -> {

            simpleMailMessage[0].setSubject(this.messageSource.getMessage("email.joboffer.subject", new Object[]{}, LocaleContextHolder.getLocale()));
            simpleMailMessage[0].setFrom(this.environment.getRequiredProperty("email.noreply"));
            simpleMailMessage[0].setTo(email);

            final @NotNull long jobOfferId = jobOffer.getJobOfferId();

            ctx.setVariable("company", jobOffer.getCompany().getName());
            ctx.setVariable("contact", jobOffer.getCompanyContact().toString());
            ctx.setVariable("description", jobOffer.getDescription());
            ctx.setVariable("jobofferid", String.valueOf(jobOfferId));

            final List<String> jobTypeCodes = jobOffer.getJobOfferJobTypeSet().stream().map(s -> s.getJobType().getCode()).collect(Collectors.toList());
            final List<String> studyCourseCodes = jobOffer.getJobOfferStudyCourseSet().stream().map(s -> s.getStudyCourse().getCode()).collect(Collectors.toList());

            ctx.setVariable("jobtypes", messageHelper.translateJobTypeToList(jobTypeCodes, LocaleContextHolder.getLocale()));
            ctx.setVariable("studycourses", messageHelper.translateStudyCourseToList(studyCourseCodes, LocaleContextHolder.getLocale()));
            final String text = templateEngine.process("text/newJobOffersNotification", ctx);
            simpleMailMessage[0].setText(text);
            simpleMailMessages.add(simpleMailMessage[0]);
            log.error(simpleMailMessage[0].toString());

        })));
        return simpleMailMessages;
    }

    /**
     * Generates email messages based on the soon to be expired jobs.
     *
     * @param soonToBeExpiredJobOffers given soon to be expired jobs
     * @return Iterable of SimpleMailMessage
     */
    @Override
    public Iterable<SimpleMailMessage> generateSoonToBeExpiredJobOfferEmails(Iterable<ExpiredJobOfferProjection> soonToBeExpiredJobOffers) {
        final Context ctx = new Context(LocaleContextHolder.getLocale());
        List<SimpleMailMessage> simpleMailMessages = new ArrayList<>();
        final SimpleMailMessage[] simpleMailMessage = {new SimpleMailMessage()};
        final String[] email = {soonToBeExpiredJobOffers.iterator().next().getEmail()};
        StringBuilder stringBuilder = new StringBuilder();
        soonToBeExpiredJobOffers.forEach((jobOfferProjection) -> {
            if (!email[0].equals(jobOfferProjection.getEmail())) {
                simpleMailMessage[0].setText(stringBuilder.toString());
                simpleMailMessages.add(new SimpleMailMessage(simpleMailMessage[0]));
                stringBuilder.setLength(0);
            }

            ctx.setVariable("expirationDate", jobOfferProjection.getValidUntilDate().format(DateTimeFormatter.ofPattern("dd.MM.yyyy")));
            ctx.setVariable("description", jobOfferProjection.getShortDesc());
            ctx.setVariable("jobOfferId", String.valueOf(jobOfferProjection.getOfferId()));
            final String text = templateEngine.process("text/expiredJobOfferNotification", ctx);
            stringBuilder.append(text);
            simpleMailMessage[0].setSubject(this.messageSource.getMessage("email.joboffer.expired.subject", new Object[]{}, LocaleContextHolder.getLocale()));
            simpleMailMessage[0].setFrom(this.environment.getRequiredProperty("email.noreply"));
            simpleMailMessage[0].setTo(jobOfferProjection.getEmail());


            email[0] = jobOfferProjection.getEmail();

        });
        log.error(simpleMailMessages.toString());
        return simpleMailMessages;
    }
}
```
Please note that if i comment the lines with the `forEach` Lambda it works. 
It does also work in Spring Boot 2.0.6 (uncommented version).
I can´t find any mistake on my part on upgrading.
Please find here my pom:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>de.thd</groupId>
    <artifactId>okb</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>war</packaging>

    <name>okb</name>
    <description>Online Career Stock Market</description>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.0.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <failOnMissingWebXml>false</failOnMissingWebXml>
    </properties>

    <profiles>
        <profile>
            <id>dev</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <spring.profiles.active>dev</spring.profiles.active>
            </properties>
        </profile>
        <profile>
            <id>prod</id>
            <properties>
                <spring.profiles.active>prod</spring.profiles.active>
            </properties>
        </profile>
    </profiles>

    <dependencies>
        <dependency>
            <groupId>nz.net.ultraq.thymeleaf</groupId>
            <artifactId>thymeleaf-layout-dialect</artifactId>
            <version>2.3.0</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.thymeleaf.extras/thymeleaf-extras-springsecurity5 -->
        <dependency>
            <groupId>org.thymeleaf.extras</groupId>
            <artifactId>thymeleaf-extras-springsecurity5</artifactId>
            <version>3.0.4.RELEASE</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-cache</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-ldap</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-mail</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.springframework.security/spring-security-test -->
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-test</artifactId>
            <version>5.1.1.RELEASE</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.2.5</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.projectlombok/lombok -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.2</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>


</project>

```
If you guys need further information or a repository for checking this out, please let me know. 
Some folks have also had this issue #14277 (closed) - maybe in another context.

Thank you for your help!  
Thank you also for your great tool Spring Boot!  
Without Spring Boot the world of coding would be a very cold place :)  

Kind regards!
Thomas

**Comment by wilkinsona** [comment]
A repository that reproduces the problem is always useful and welcome. The complete stack trace of the failure would be too.

**Comment by THD-Thomas-Lang** [comment]
Thank you for your quick reply. Please see here the stack trace:
```
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: file [D:\dev\projects\okb\target\okb-0.0.1-SNAPSHOT\WEB-INF\classes\de\thd\okb\component\MailHelper.class]; nested exception is java.lang.ArrayIndexOutOfBoundsException: 257
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.scanCandidateComponents(ClassPathScanningCandidateComponentProvider.java:454) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:316) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:275) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.annotation.ComponentScanAnnotationParser.parse(ComponentScanAnnotationParser.java:132) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:287) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:242) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:199) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:167) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:315) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:232) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:95) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:691) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:528) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) ~[spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) ~[spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:157) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:137) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:91) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:171) [spring-web-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5098) [catalina.jar:9.0.12]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:9.0.12]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743) [catalina.jar:9.0.12]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719) [catalina.jar:9.0.12]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:703) [catalina.jar:9.0.12]
	at org.apache.catalina.startup.HostConfig.manageApp(HostConfig.java:1737) [catalina.jar:9.0.12]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:287) [tomcat-coyote.jar:9.0.12]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819) [na:1.8.0_181]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801) [na:1.8.0_181]
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:457) [catalina.jar:9.0.12]
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:406) [catalina.jar:9.0.12]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:287) [tomcat-coyote.jar:9.0.12]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819) [na:1.8.0_181]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801) [na:1.8.0_181]
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468) [na:1.8.0_181]
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76) [na:1.8.0_181]
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309) [na:1.8.0_181]
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401) [na:1.8.0_181]
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829) [na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357) [na:1.8.0_181]
	at sun.rmi.transport.Transport$1.run(Transport.java:200) [na:1.8.0_181]
	at sun.rmi.transport.Transport$1.run(Transport.java:197) [na:1.8.0_181]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_181]
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196) [na:1.8.0_181]
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573) [na:1.8.0_181]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834) [na:1.8.0_181]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688) [na:1.8.0_181]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_181]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 257
	at org.springframework.asm.ClassReader.readLabel(ClassReader.java:2440) ~[spring-core-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.asm.ClassReader.createLabel(ClassReader.java:2456) ~[spring-core-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.asm.ClassReader.readTypeAnnotations(ClassReader.java:2522) ~[spring-core-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.asm.ClassReader.readCode(ClassReader.java:1686) ~[spring-core-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.asm.ClassReader.readMethod(ClassReader.java:1275) ~[spring-core-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.asm.ClassReader.accept(ClassReader.java:679) ~[spring-core-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.asm.ClassReader.accept(ClassReader.java:391) ~[spring-core-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:65) ~[spring-core-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:103) ~[spring-core-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.core.type.classreading.CachingMetadataReaderFactory.getMetadataReader(CachingMetadataReaderFactory.java:123) ~[spring-core-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.scanCandidateComponents(ClassPathScanningCandidateComponentProvider.java:430) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	... 65 common frames omitted
```

**Comment by THD-Thomas-Lang** [comment]
In the meantime i will type a repository and post the link here ... Thank you!

**Comment by THD-Thomas-Lang** [comment]
So here is the repository. Everything beeing notable is written in the Readme file. I hope this helps.
Please respond if there is somethings missing:
https://github.com/THD-Thomas-Lang/boot15178.git

**Comment by THD-Thomas-Lang** [comment]
@wilkinsona Thank you for your help. I can live with the variable being not `@NotNull` ... Anyway thank you and thank you for Spring Boot.
Keep it up!
Kind regards!
Thomas
