### ISSUE TITLE
Spring devtools close h2 database during integration tests 

### ISSUE THREAD

**Issue by mschwartau** [spring-projects/spring-boot#15277]
We had an issue with Spring boot 2.0.6 but I could reproduce it using spring boot 2.1.0. 

During our integrations test we sometimes got errors like the following (see [example project](https://github.com/mschwartau/spring-devtools-issue-15277)):
```
org.springframework.jdbc.datasource.init.ScriptStatementFailedException: Failed to execute SQL script statement #1 of class path resource [sql/Schema_clean.sql]: delete from t_example; nested exception is org.h2.jdbc.JdbcSQLException: Tabelle "T_EXAMPLE" nicht gefunden
Table "T_EXAMPLE" not found; SQL statement:
delete from t_example [42102-197]
	at org.springframework.jdbc.datasource.init.ScriptUtils.executeSqlScript(ScriptUtils.java:507) ~[spring-jdbc-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.jdbc.datasource.init.ResourceDatabasePopulator.populate(ResourceDatabasePopulator.java:240) ~[spring-jdbc-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.jdbc.datasource.init.DatabasePopulatorUtils.execute(DatabasePopulatorUtils.java:48) ~[spring-jdbc-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.jdbc.datasource.init.ResourceDatabasePopulator.execute(ResourceDatabasePopulator.java:255) ~[spring-jdbc-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener.lambda$executeSqlScripts$3(SqlScriptsTestExecutionListener.java:229) ~[spring-test-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener.executeSqlScripts(SqlScriptsTestExecutionListener.java:228) ~[spring-test-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener.executeSqlScripts(SqlScriptsTestExecutionListener.java:142) ~[spring-test-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener.beforeTestMethod(SqlScriptsTestExecutionListener.java:112) ~[spring-test-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.test.context.TestContextManager.beforeTestMethod(TestContextManager.java:291) ~[spring-test-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74) [spring-test-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86) [spring-test-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84) [spring-test-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251) [spring-test-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97) [spring-test-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61) [spring-test-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70) [spring-test-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190) [spring-test-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.junit.runners.Suite.runChild(Suite.java:128) [junit-4.12.jar:4.12]
	at org.junit.runners.Suite.runChild(Suite.java:27) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137) [junit-4.12.jar:4.12]
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68) [junit-rt.jar:na]
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47) [junit-rt.jar:na]
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242) [junit-rt.jar:na]
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70) [junit-rt.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: Tabelle "T_EXAMPLE" nicht gefunden
```

We found out that spring dev tools are the cause for this, because spring dev tools closes the database sometimes. In our example, it needs a combination of:
- spring dev tools as dependency
- @DirtiesContext before a test using the @SqlGroup
- @MockBean in classes before and after the @DirtiesContext annotated test class
- integration tests with @SqlGroup which are exectuded after @DirtiesContext
See our [example project](https://github.com/mschwartau/spring-devtools-issue-15277) to reproduce the error. Just execute the [FailingSuite](https://github.com/mschwartau/spring-devtools-issue-15277/blob/master/src/test/java/com/example/sqlbug/FailingSuite.java) to get the above error. 

Workaround currently:
- remove spring dev tools dependency completely
- exclude `DevToolsDataSourceAutoConfiguration` which causes the issue: `@SpringBootApplication(exclude = DevToolsDataSourceAutoConfiguration.class)`

**Comment by wilkinsona** [comment]
Thanks for the sample. Ideally, DevTools wouldn't even be on the classpath when running tests. You can achieve that by using our [recommend configuration for DevTools with Gradle](https://docs.spring.io/spring-boot/docs/2.0.6.RELEASE/reference/htmlsingle/#using-boot-devtools):

```groovy
configurations {
	developmentOnly
	runtimeClasspath {
		extendsFrom developmentOnly
	}
}
dependencies {
	developmentOnly("org.springframework.boot:spring-boot-devtools")
}
```

That said, we probably still need to do something about this as the above won't help anyone who is using Maven or is using an IDE that doesn't separate the main and test classpaths and hits this problem.

**Comment by wilkinsona** [comment]
The problem is that the same database is being shared across multiple application contexts and when the database is closed at the end of IntegrationTest2 it loses changes that were made to it when IntegrationTest1 ran:

1. IntegrationTest1 runs
    1. It refreshes an application context
    2. Liquibase applies a changeset that creates the `T_EXAMPLE` table
2. IntegrationTest2 runs
    1. It refreshes a new application context as it has a different cache key (no use of `@MockBean`) 
    2. Liquibase runs again but has nothing to do as the database from IntegrationTest1 is reused
    3. The test is marked `@DirtiesContext` so the context is closed
    4. DevTools closes the database, losing the schema changes made by Liquibase
3. IntegrationTest3 runs
    1. The context from IntegrationTest1 is reused as the cache keys match
    2. Liquibase does not run as a cached context is reused
    3. The schema cleaning fails as `T_EXAMPLE` does not exist


A possible solution that works for any build system is to use `@AutoConfigureTestDatabase` to ensure that each context that's create has its own database. This aligns the database's lifecycle with the context's lifecycle, thereby preventing a database from being closed when its context may be reused.

**Comment by mschwartau** [comment]
Thanks, using `@AutoConfigureTestDatabase` solved the issue for me :-). Then only downside is that according to `org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer`

> @AutoConfigureTestDatabase cannot be used in combination with the @Component annotations @SpringBootApplication, @Configuration

so basically it has to be added to each `@SpringBootTest` which needs a database. But that's no problem because I wrote an [ArchUnit test](https://github.com/TNG/ArchUnit) which enforces this.

Just if someone has the same problem, our ArchUnit test looks like this:
```
@RunWith(ArchUnitRunner.class)
@AnalyzeClasses(packages = "our.base.package.name.here")
public class PreventInstableDatabaseTestsTest {

    private static Class<?>[] NO_CLASSES = new Class[0];

    // see issue https://github.com/spring-projects/spring-boot/issues/15277
    @ArchTest
    public static final ArchRule use_autoconfigure_testdatabase = ArchRuleDefinition
            .classes()
            .that().areAnnotatedWith(SqlGroup.class).or(new UseJpaBaseApplicationClass())
            .should().beAnnotatedWith(AutoConfigureTestDatabase.class);


    public static class UseJpaBaseApplicationClass extends DescribedPredicate<JavaClass> {

        public UseJpaBaseApplicationClass() {
            super("use *jpaTestMain class (see https://github.com/spring-projects/spring-boot/issues/15277)");
        }

        @Override
        public boolean apply(JavaClass input) {
            final Class<?>[] classes = input.tryGetAnnotationOfType(SpringBootTest.class)
                    .transform(ann -> ann.classes())
                    .or(NO_CLASSES);

            return Stream.of(classes).anyMatch(c -> c.equals(ApplicationJpaTestMain.class));
        }
    }
}
```

With this test, nobody should forget to add  `@AutoConfigureTestDatabase`.
