### ISSUE TITLE
Autoconfigured DomainClassConverter reads nested Repositories even if they aren't explicitly wired in.

### ISSUE THREAD

**Issue by kalexmills** [spring-projects/spring-boot#15280]
I have encountered a situation where the auto-configured `DomainClassConverter` used by Spring Boot seems to be utilizing a nested repository with `@Async` annotated methods even when that nested repository is not explicitly being wired in. This can result in an `argument type mismatch` when Spring boot attempts to use the asynchronous version of a method, rather than only looking at the `CrudRepository` sub-interfaces, as one would have expected from [the line in the spring-data-jpa documentation that says](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#core.web.basic):

> Currently, the repository has to implement CrudRepository to be eligible to be discovered for conversion. 

When the documentation states that `CrudRepository` is the only interface considered by `DomainClassConverter`, I didn't expect that Spring Boot would attempt to use an inner repository which extends `Repository`.

[Here is a link](https://github.com/NiftySoft/example-spring-data-jpa/tree/potential-domain-class-converter-autoconfig-bug) to a working maven project that demonstrates the supposed bug in an integration test. You can comment / uncomment the interface at WidgetRepository:45 to see the supposed bug.

In case you don't want to check out that repo, I have some of the relevant details below. At the very bottom, you'll find the stacktrace I am getting.

Here are the relevant portions of the repository. `@EnableJpaRepositories(considerNestedRepositories = true)` is set on the Application, while `@EnableSpringDataWebSupport` is set on the only `@Configuration` annotated class.

```
/**
 * WidgetRepository is a Spring Data JPA repository for Widgets.
 */
public interface WidgetRepository extends CrudRepository<Widget, Long> {

    List<Widget> findAllByType(Widget.Type type);

    // ... irrelevant stuff omitted here, see repo for details ...

    // commenting out this inner class resolves the error. But shouldn't one be able to do this?
    interface Asynchrony extends Repository<Widget, Long> {
        @Async
        Future<Optional<Widget>> findById(Long id);

        @Async
        Future<Long> count();

        @Async
        Future<List<Widget>> findAllByType(Widget.Type type);

        @Async
        Future<Boolean> existsById(Long id);

        interface SprocketsOnly extends Repository<Widget, Long> {
            @Async
            Future<WidgetViews.SprocketsOnly> findById(Long id);

            @Async
            Future<List<WidgetViews.SprocketsOnly>> findAll();
        }
    }
}
```

Here is the relevant controller.
```
@Controller
@RequestMapping(value = "/widget", produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
@Slf4j
public class WidgetController {

    private final WidgetRepository widgetRepository;

    @Inject
    public WidgetController(WidgetRepository widgetRepository){
        this.widgetRepository = widgetRepository;
    }

    // This controller automagically converts the Widget ID to a Widget object.
    @ResponseBody
    @GetMapping(value = "/{id}")
    Widget getWidget(@PathVariable("id") Widget widget) {
        log.info(widget.toString());
        return widget;
    }
}
```

Here is the snippet from the integration test which results in the stacktrace at the bottom of this description.
```
        mockMvc.perform(get("/widget/" + w.getId())
                            .accept(MediaType.APPLICATION_JSON_UTF8))
                .andDo(print())
                .andExpect(status().isOk());
```

Here are the relevant parts of `pom.xml`.
```
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.0.5.RELEASE</version>
    </parent>

    <properties>
        <java.version>1.8</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-json</artifactId>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.16.8</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>3.11.1</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>javax.inject</groupId>
            <artifactId>javax.inject</artifactId>
            <version>1</version>
        </dependency>
    </dependencies>
```

And finally... here is the stack trace one sees when the endpoint is hit.
```
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalStateException: argument type mismatch
HandlerMethod details: 
Controller [com.niftysoft.example.controller.WidgetController]
Method [com.niftysoft.example.model.Widget com.niftysoft.example.controller.WidgetController.getWidget(com.niftysoft.example.model.Widget)]
Resolved arguments: 
[0] [type=org.springframework.scheduling.annotation.AsyncResult] [value=org.springframework.scheduling.annotation.AsyncResult@45571cfc]


	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:866)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
	at org.springframework.test.web.servlet.TestDispatcherServlet.service(TestDispatcherServlet.java:71)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.springframework.mock.web.MockFilterChain$ServletFilterProxy.doFilter(MockFilterChain.java:166)
	at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:133)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:133)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:133)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:133)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:133)
	at org.springframework.test.web.servlet.MockMvc.perform(MockMvc.java:165)
	at com.niftysoft.example.controller.WidgetControllerIT.getWidgetTest(WidgetControllerIT.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:73)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:83)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.IllegalStateException: argument type mismatch
HandlerMethod details: 
Controller [com.niftysoft.example.controller.WidgetController]
Method [com.niftysoft.example.model.Widget com.niftysoft.example.controller.WidgetController.getWidget(com.niftysoft.example.model.Widget)]
Resolved arguments: 
[0] [type=org.springframework.scheduling.annotation.AsyncResult] [value=org.springframework.scheduling.annotation.AsyncResult@45571cfc]

	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:214)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:891)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
	... 51 more
Caused by: java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
	... 59 more
```

**Comment by kalexmills** [comment]
... seems that you can only have one repository for a given entity. I was struggling with the naming conventions for the methods (which is not very thoroughly documented 👎 ... the documentation ought to state that the ending `By` is required). I have since figured out that WidgetRepository can be rewritten to look like this.

```
public interface WidgetRepository extends CrudRepository<Widget, Long> {

    List<Widget> findAllByType(Widget.Type type);

    Future<List<Widget>> findAllAsyncBy();

    Future<Optional<Widget>> findAsyncById(Long id);

    Future<Long> countAsyncBy();

    Future<List<Widget>> findAllAsyncByType(Widget.Type type);

    Future<Boolean> existsAsyncById(Long id);

    Future<WidgetViews.SprocketsOnly> findSprocketsOnlyAsyncById(Long id);

    Future<List<WidgetViews.SprocketsOnly>> findAllSprocketsOnlyAsyncBy();
}
```
This fixes things for me. It seems that there must be only one repository for each Entity in Spring Boot.

**Comment by wilkinsona** [comment]
I’m pleased to hear that you figured out your problem. The functionality you have described is not part of Spring Boot itself but provided by Spring Data JPA. If you believe that the documentation could be improved, please open a [Spring Data JPA JIRA](https://repo.spring.io/browse/DATAJPA).

**Comment by kalexmills** [comment]
@wilkinsona that's a dead link for me.

**Comment by bclozel** [comment]
@kalexmills link is now fixed.

**Comment by wilkinsona** [comment]
I know that Spring Data REST has a limitation of only easily allowing one repository per entity ([DATAREST-923](https://jira.spring.io/browse/DATAREST-923)) but I am not aware of Data JPA having a similar restriction. Spring Boot does not do anything to introduce such a restriction.
