### ISSUE TITLE
/restart endpoint is failing with the error "java.lang.IllegalStateException: org.springframework.context.annotation.AnnotationConfigApplicationContext has been closed already"

### ISSUE THREAD

**Issue by nandu777** [spring-projects/spring-boot#15300]
```
2018-11-27 12:09:58.463  INFO 20344 --- [     Thread-113] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@23d23d98: startup date [Tue Nov 27 12:07:41 IST 2018]; parent: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@5a62b2a4
2018-11-27 12:09:58.466  INFO 20344 --- [     Thread-113] ConfigServletWebServerApplicationContext : Closing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@5a62b2a4: startup date [Tue Nov 27 12:07:23 IST 2018]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@53fe15ff
2018-11-27 12:09:58.467  INFO 20344 --- [     Thread-113] o.s.c.n.e.s.EurekaServiceRegistry        : Unregistering application xc-auth-server with eureka with status DOWN
2018-11-27 12:09:58.467  WARN 20344 --- [     Thread-113] com.netflix.discovery.DiscoveryClient    : Saw local status change event StatusChangeEvent [timestamp=1543300798467, current=DOWN, previous=UP]
2018-11-27 12:09:58.467  INFO 20344 --- [     Thread-113] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@753e4eb5: startup date [Tue Nov 27 12:07:48 IST 2018]; parent: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@5a62b2a4
2018-11-27 12:09:58.468  INFO 20344 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_XC-AUTH-SERVER/xc-auth-server: registering service...
2018-11-27 12:09:58.472  INFO 20344 --- [     Thread-113] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 2147483647
2018-11-27 12:09:58.473  INFO 20344 --- [     Thread-113] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 2147483547
2018-11-27 12:09:58.473  INFO 20344 --- [     Thread-113] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 2147482647
2018-11-27 12:09:58.476  INFO 20344 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_XC-AUTH-SERVER/xc-auth-server - registration status: 204
2018-11-27 12:09:58.484  INFO 20344 --- [container-0-C-1] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService
2018-11-27 12:09:58.923  INFO 20344 --- [container-0-C-1] essageListenerContainer$ListenerConsumer : Consumer stopped
2018-11-27 12:09:58.924  INFO 20344 --- [     Thread-113] s.i.k.i.KafkaMessageDrivenChannelAdapter : stopped org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter@9ba167e
2018-11-27 12:09:58.924  INFO 20344 --- [     Thread-113] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 0
2018-11-27 12:09:58.924  INFO 20344 --- [     Thread-113] o.s.i.endpoint.EventDrivenConsumer       : Removing {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
2018-11-27 12:09:58.924  INFO 20344 --- [     Thread-113] o.s.i.channel.PublishSubscribeChannel    : Channel 'xc-auth-server-1.errorChannel' has 0 subscriber(s).
2018-11-27 12:09:58.924  INFO 20344 --- [     Thread-113] o.s.i.endpoint.EventDrivenConsumer       : stopped _org.springframework.integration.errorLogger
2018-11-27 12:09:58.924  INFO 20344 --- [     Thread-113] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase -2147482648
2018-11-27 12:09:58.926  INFO 20344 --- [     Thread-113] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2018-11-27 12:09:58.927  INFO 20344 --- [     Thread-113] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans
2018-11-27 12:09:58.931  INFO 20344 --- [     Thread-113] s.c.a.AnnotationConfigApplicationContext : Closing FeignContext-xc-application-registry: startup date [Tue Nov 27 12:07:32 IST 2018]; parent: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@5a62b2a4
2018-11-27 12:09:58.933  INFO 20344 --- [     Thread-113] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
2018-11-27 12:09:58.934  INFO 20344 --- [     Thread-113] com.netflix.discovery.DiscoveryClient    : Shutting down DiscoveryClient ...
2018-11-27 12:10:01.937  INFO 20344 --- [     Thread-113] com.netflix.discovery.DiscoveryClient    : Unregistering ...
2018-11-27 12:10:01.951  INFO 20344 --- [     Thread-113] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_XC-AUTH-SERVER/xc-auth-server - deregister  status: 200
2018-11-27 12:10:01.963  INFO 20344 --- [     Thread-113] com.netflix.discovery.DiscoveryClient    : Completed shut down of DiscoveryClient
2018-11-27 12:10:01.963  INFO 20344 --- [     Thread-113] o.s.i.monitor.IntegrationMBeanExporter   : Unregistering JMX-exposed beans on shutdown
2018-11-27 12:10:01.963  INFO 20344 --- [     Thread-113] o.s.i.monitor.IntegrationMBeanExporter   : Unregistering JMX-exposed beans
2018-11-27 12:10:01.964  INFO 20344 --- [     Thread-113] o.s.i.monitor.IntegrationMBeanExporter   : Summary on shutdown: apikeys-channel-readable
2018-11-27 12:10:01.964  INFO 20344 --- [     Thread-113] o.s.i.monitor.IntegrationMBeanExporter   : Summary on shutdown: errorChannel
2018-11-27 12:10:01.964  INFO 20344 --- [     Thread-113] o.s.i.monitor.IntegrationMBeanExporter   : Summary on shutdown: apikeys-channel-writable
2018-11-27 12:10:01.964  INFO 20344 --- [     Thread-113] o.s.i.monitor.IntegrationMBeanExporter   : Summary on shutdown: nullChannel
2018-11-27 12:10:01.964  INFO 20344 --- [     Thread-113] o.s.i.monitor.IntegrationMBeanExporter   : Summary on shutdown: org.springframework.cloud.stream.binding.StreamListenerMessageHandler@320e179f
2018-11-27 12:10:01.964  INFO 20344 --- [     Thread-113] o.s.i.monitor.IntegrationMBeanExporter   : Summary on shutdown: _org.springframework.integration.errorLogger.handler
2018-11-27 12:10:02.563  INFO 20344 --- [     Thread-113] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2018-11-27 12:10:02.568  INFO 20344 --- [ost-startStop-2] o.apache.catalina.core.StandardWrapper   : Waiting for [1] instance(s) to be deallocated for Servlet [dispatcherServlet]
2018-11-27 12:10:03.573  INFO 20344 --- [ost-startStop-2] o.apache.catalina.core.StandardWrapper   : Waiting for [1] instance(s) to be deallocated for Servlet [dispatcherServlet]
2018-11-27 12:10:04.577  INFO 20344 --- [ost-startStop-2] o.apache.catalina.core.StandardWrapper   : Waiting for [1] instance(s) to be deallocated for Servlet [dispatcherServlet]
2018-11-27 12:10:04.677  INFO 20344 --- [ost-startStop-2] o.a.c.c.C.[Tomcat].[localhost].[/]       : Destroying Spring FrameworkServlet 'dispatcherServlet'
2018-11-27 12:10:04.699  INFO 20344 --- [     Thread-113] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@53fe15ff: startup date [Tue Nov 27 12:07:15 IST 2018]; root of context hierarchy
2018-11-27 12:10:04.702  INFO 20344 --- [     Thread-113] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService
2018-11-27 12:10:04.706 ERROR 20344 --- [     Thread-113] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: org.springframework.context.annotation.AnnotationConfigApplicationContext@53fe15ff has been closed already
	at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1073) ~[spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBeanNamesForType(AbstractApplicationContext.java:1185) ~[spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.getOrderedBeansOfType(BootstrapApplicationListener.java:329) ~[spring-cloud-context-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.apply(BootstrapApplicationListener.java:303) ~[spring-cloud-context-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:107) ~[spring-cloud-context-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:70) ~[spring-cloud-context-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127) ~[spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:74) ~[spring-boot-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54) ~[spring-boot-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:364) ~[spring-boot-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:323) ~[spring-boot-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.cloud.context.restart.RestartEndpoint.doRestart(RestartEndpoint.java:160) [spring-cloud-context-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.cloud.context.restart.RestartEndpoint.safeRestart(RestartEndpoint.java:99) [spring-cloud-context-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
```

2018-11-27 12:10:04.706  INFO 20344 --- [     Thread-113] o.s.c.context.restart.RestartEndpoint    : Could not doRestart: org.springframework.context.annotation.AnnotationConfigApplicationContext@53fe15ff has been closed already

Process finished with exit code 0

**Comment by snicoll** [comment]
The restart endpoint is a Spring Cloud feature, please report that against the [appropriate issue tracker](https://github.com/spring-cloud/spring-cloud-commons).
