### ISSUE TITLE
EmbeddedMongoAutoConfiguration.determineVersion(…) fails with NPE when no features are configured and spring.mongodb.embedded.version specifies a version not included in de.flapdoodle.embed.mongo.distribution.Version

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-boot#15311]
Affected Spring Boot versions: 2.1.x (2.1.0.RELEASE and 2.1.1.BUILD-SNAPSHOT)

Steps to reproduce:

1. Create empty Spring Boot project and add `spring-boot-starter-data-mongodb` and `de.flapdoodle.embed.mongo` (test) dependencies
2. Add `application.properties` configuring `spring.mongodb.embedded.version` (e.g. `spring.mongodb.embedded.version=3.4.1`)
3. Start application

```
Caused by: java.lang.NullPointerException: null
	at org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration.determineVersion(EmbeddedMongoAutoConfiguration.java:162) ~[spring-boot-autoconfigure-2.1.1.BUILD-20181127.152604-52.jar:2.1.1.BUILD-SNAPSHOT]
	at org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration.embeddedMongoConfiguration(EmbeddedMongoAutoConfiguration.java:130) ~[spring-boot-autoconfigure-2.1.1.BUILD-20181127.152604-52.jar:2.1.1.BUILD-SNAPSHOT]
	at org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration$$EnhancerBySpringCGLIB$$d5560118.CGLIB$embeddedMongoConfiguration$1(<generated>) ~[spring-boot-autoconfigure-2.1.1.BUILD-20181127.152604-52.jar:2.1.1.BUILD-SNAPSHOT]
	at org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration$$EnhancerBySpringCGLIB$$d5560118$$FastClassBySpringCGLIB$$7f400318.invoke(<generated>) ~[spring-boot-autoconfigure-2.1.1.BUILD-20181127.152604-52.jar:2.1.1.BUILD-SNAPSHOT]
```

Gist to reproduce: https://gist.github.com/mp911de/d4d40ebd5560bea3c9bf68806be3e68c

**Comment by wilkinsona** [comment]
Thank you, @mp911de. Looks like a regression introduced in https://github.com/spring-projects/spring-boot/commit/1a8f519922b288491cc64d5ef0a0b95f443d7a66.
