### ISSUE TITLE
HibernateMetricsAutoConfiguration will fail, when using different JPA implementation

### ISSUE THREAD

**Issue by ihrigb** [spring-projects/spring-boot#15317]
When using a different JPA implementation than Hibernate, `HibernateMetricsAutoConfiguration` ([link](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/metrics/orm/jpa/HibernateMetricsAutoConfiguration.java)) will fail, as it is based on Hibernate components.

**The following happens usually:**
Hibernate is initialized before this auto configuration class. Then `HibernateMetricsAutoConfiguration` will be checked for conditions

```
@ConditionalOnClass({ EntityManagerFactory.class, MeterRegistry.class })
@ConditionalOnBean({ EntityManagerFactory.class, MeterRegistry.class })
```

The conditions are matching, so the auto configuration class will be taken into account.

**Without Hibernate:**
Any other JPA vendor (e. g. Eclipse Link) will be set up. Now, with micrometer also active, we also will have as well class and bean of `EntityManagerFactory` and `MeterRegistry`. Now again, `HibernateMetricsAutoConfiguration` will be taken into account. As now, hibernate is *not* in the classpath, we will get `java.lang.ClassNotFoundException: org.hibernate.SessionFactory`.

**Suggestion for a fix**
This should be easy to fix, by adding a third class to `@ConditionalOnClass`. That class should be specific to Hibernate, to make sure, that the JPA vendor really is Hibernate. So the fix could be:

```
@ConditionalOnClass({ EntityManagerFactory.class, MeterRegistry.class, SessionFactory.class })
@ConditionalOnBean({ EntityManagerFactory.class, MeterRegistry.class })
```

I can take care of this and provide a PR, if this is confirmed. Not sure, if there is a more appropriate way to tell, if the JPA vendor is Hibernate.

**Comment by snicoll** [comment]
Good catch! Backing off when Hibernate is  not present is definitely something we should do and test that scenario. The metrics itself will backoff if the entity manager is based on another provider.

**Comment by wilkinsona** [comment]
I think there's a bug in Micrometer here as the intent appears to be that it should [tolerate JPA providers other than Hibernate](https://github.com/micrometer-metrics/micrometer/blob/6cdc476985b2f6e57d0c2487dd0745e7d02aabd6/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jpa/HibernateMetrics.java#L170-L185). If it isn't Hibernate, then, as @snicoll says above, it won't register any meters.

**Comment by ihrigb** [comment]
Here is a stack trace, if that helps:

```
Caused by: java.lang.NoClassDefFoundError: org/hibernate/SessionFactory
    at io.micrometer.core.instrument.binder.jpa.HibernateMetrics.getStatistics(HibernateMetrics.java:180)
    at io.micrometer.core.instrument.binder.jpa.HibernateMetrics.hasStatisticsEnabled(HibernateMetrics.java:166)
    at io.micrometer.core.instrument.binder.jpa.HibernateMetrics.<init>(HibernateMetrics.java:57)
    at org.springframework.boot.actuate.autoconfigure.metrics.orm.jpa.HibernateMetricsAutoConfiguration.bindEntityManagerFactoryToRegistry(HibernateMetricsAutoConfiguration.java:71)
```

**Comment by snicoll** [comment]
@ihrigb thank you very much for the report, this should be fixed in the next bug fix release due this week. I've also reported the micrometer issue https://github.com/micrometer-metrics/micrometer/issues/1037

**Comment by ihrigb** [comment]
Thanks!
