### ISSUE TITLE
Hazelcast + spring-boot-data-jpa: cacheManager initialisation issue after upgrade from 2.0.4 -> 2.0.5

### ISSUE THREAD

**Issue by JorgenRingen** [spring-projects/spring-boot#15359]
Issue after upgrading from version 2.0.4 to 2.0.5+.

Startup fails with:
`Caused by: org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'cacheManager': Requested bean is currently in creation: Is there an unresolvable circular reference?` 

Instantiating HazelcastInstance bean manually and instantiation relies upon a JpaRepository bean. This causes a circular reference on the cacheManager bean.
```
@Bean public FooMapStore fooMapStore(FooRepository fooRepository) {}
@Bean public Config config(FooMapStore fooMapStore) {}
@Bean public HazelcastInstance hazelcastInstance(Config config) { }
```
I've debugged the dependency graph and it looks like this:
entityManagerFactory -> **cacheManager** -> JCacheCacheConfiguration -> hazelcastPropertiesCustomizer -> hazelcastInstance -> config -> fooMapStore -> fooRepository -> (inner bean)#hash -> entityManagerFactory -> **cacheManager**

I suspect the issue might be related to https://github.com/spring-projects/spring-boot/issues/14467 ?

Sample application: https://github.com/JorgenRingen/spring-boot-error-cachemanager-currently-in-creation

Any suggestions for workarounds?

**Comment by JorgenRingen** [comment]
Okey, I see we should've avoided the cycle in the first place.

Are there any preferable way of deferring the registration? As a first draft I'm doing a "lazy-lookup" from the ApplicationContext on the first call on FooRepository from FooMapStore, but it feels a bit awkward :-)
```
public class FooMapStore implements MapStore<Long, Foo> {

    @Autowired 
    private ApplicationContext applicationContext;
    private FooRepository fooRepository;

    @Override public void store(Long key, Foo value) {
        fooRepository().findAll();
    }

    private FooRepository fooRepository() {
        if (this.fooRepository == null) {
            this.fooRepository = applicationContext.getBean(FooRepository.class);
        }
        return fooRepository;
    }
   ...
```

**Comment by snicoll** [comment]
Thanks for the feedback. That's not really what I have in mind. I was more thinking about retrieving the `HazelcastInstance` latter and alter its configuration to register an extra store. Is that a use case that Hazelcast supports?

**Comment by JorgenRingen** [comment]
I thought about registering the MapStore in a BeanPostProcessor, but according to [com.hazelcast.config.Config](https://docs.hazelcast.org/docs/3.9/javadoc/com/hazelcast/config/Config.html) "[Config instances] should not be modified after they are used to create HazelcastInstance". The creation of the HazelcastInstance bean instantiates it: `return Hazelcast.getOrCreateHazelcastInstance(config);`

**Comment by snicoll** [comment]
@JorgenRingen that's not what [this issue indicates](https://github.com/hazelcast/hazelcast/pull/10757). I've tried and got another Hazelcast problem that I don't really understand:

```
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: There is no suitable serializer for class com.example.cachemanagercurrentlyincreationerror.FooMapStore
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.serializerFor(AbstractSerializationService.java:491) ~[hazelcast-3.9.4.jar:3.9.4]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:254) ~[hazelcast-3.9.4.jar:3.9.4]
	... 44 common frames omitted
```

I've submitted a PR to your repro project.

**Comment by lukass77** [comment]
please re-check this issue is not a duplicate with same root cause as this one - https://github.com/spring-projects/spring-boot/issues/4960

**Comment by snicoll** [comment]
@lukass77 the issue is open and we'd like to make sure this works without any modification on your end. So, no, it's not a duplicate.

**Comment by nkavian** [comment]
I have a similar issue. I want to initialize the Hazelcast Config with one setting from my database, which then I'm hit with the cyclical issue.

**Comment by StefanPopa02** [comment]
Any updates on this? I'm facing a similar issue

**Comment by snicoll** [comment]
Reviewing this, there isn't a way to deal automatically with the cycle without breaking https://github.com/spring-projects/spring-boot/issues/4158. At the end of the day, you're asking Spring Boot to auto-configure Hazelcast, Hibernate, and the Cache abstraction. When in this configuration, Spring Boot makes sure that:

1. The cache infrastructure is configured before Hibernate is itself configured.
2. Hazelcast is configured before Hibernate itself is configured.

If you disagree with this order, then you should take care of the configuration:

1. Configure the JCacheManager yourself
2. Disable the link between Hibernate and Hazelcast (see also #4960)

In the sample above, this means that the application should be updated to:

```java
@SpringBootApplication(exclude =  HazelcastJpaDependencyAutoConfiguration.class)
public class CachemanagerCurrentlyInCreationErrorApplication {

    public static void main(String[] args) {
        SpringApplication.run(CachemanagerCurrentlyInCreationErrorApplication.class, args);
    }

}
```

And the `CacheConfiguration` needs an extra bean:

```java
@Bean
public JCacheCacheManager jcacheCacheManager(HazelcastInstance hazelcastInstance) {
	CacheManager cacheManager = SpringHazelcastCachingProvider.getCacheManager(hazelcastInstance, null, new Properties());
	return new JCacheCacheManager(cacheManager);
}
```

With that in place, I am not entirely sure that's doing what the OP wants. Typically, such setup can't use Hazelcast as a second level cache and that is unrelated to Spring Boot.
