### ISSUE TITLE
 Failed to execute goal com.querydsl:querydsl-maven-plugin:4.1.4:jpa-export (generate-qtypes) on project repository

### ISSUE THREAD

**Issue by hongli8881** [spring-projects/spring-boot#15381]

**Comment by hongli8881** [comment]
When I try to build Northwind repository module, I got following errors.

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.891s
[INFO] Finished at: Mon Dec 03 15:13:07 EST 2018
[INFO] Final Memory: 33M/492M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.querydsl:querydsl-maven-plugin:4.1.4:jpa-export (generate-qtypes) on project repository: Execution generate-qtypes of goal com.querydsl:querydsl-maven-plugin:4.1.4:jpa-export failed: sun.reflect.annotation.TypeNotPr
esentExceptionProxy -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.querydsl:querydsl-maven-plugin:4.1.4:jpa-export (generate-qtypes) on project repository: Execution generate-qtypes of goal com.querydsl:querydsl-maven-plugin:4.1.4:jpa
-export failed: sun.reflect.annotation.TypeNotPresentExceptionProxy
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution generate-qtypes of goal com.querydsl:querydsl-maven-plugin:4.1.4:jpa-export failed: sun.reflect.annotation.TypeNotPresentExceptionProxy
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:115)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
        at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
        at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
        at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
        at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
        at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
        at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
        at java.lang.Class.createAnnotationData(Class.java:3521)
        at java.lang.Class.annotationData(Class.java:3510)
        at java.lang.Class.getAnnotation(Class.java:3415)
        at java.lang.reflect.AnnotatedElement.isAnnotationPresent(AnnotatedElement.java:258)
        at java.lang.Class.isAnnotationPresent(Class.java:3425)
        at com.querydsl.codegen.GenericExporter.handleClass(GenericExporter.java:525)
        at com.querydsl.codegen.GenericExporter.scanPackages(GenericExporter.java:516)
        at com.querydsl.codegen.GenericExporter.export(GenericExporter.java:193)
        at com.querydsl.maven.AbstractExporterMojo.execute(AbstractExporterMojo.java:162)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
        ... 20 more

**Comment by wilkinsona** [comment]
Did you mean to report this as a Spring Boot issue? It looks like a bug in QueryDSL's Maven plugin. If you think it's caused by Spring Boot, can you please explain why and provide a minimal sample that reproduces the problem?

**Comment by hongli8881** [comment]
Hi,

When I try Spring Roo project Nothwind, I got this errors.

The pom including following

<plugin>
                                  <groupId>com.querydsl</groupId>
                                  <artifactId>querydsl-maven-plugin</artifactId>
                                  <version>${querydsl.version}</version>

                                  <executions>
                                         <execution>
                                                <id>generate-qtypes</id>
                                                
                                                <phase>generate-sources</phase>
                                                
                                                
                                                <goals>
                                                       <goal>jpa-export</goal>
                                                       
                                                </goals>
                                                <configuration>
                                                       <targetFolder>target/generated-sources/java</targetFolder>
                                                       <packages>
                                                              <package>org.springframework.data.jpa.domain.support</package>
                                                              <package>org.northwind.model</package>
                                                       </packages>
                                                       <packageName>org.northwind.model</packageName>
                                                </configuration>
                                         </execution>
                                         <execution>
                                                <id>compile-qtypes</id>
                                                <goals>
                                                       <goal>compile</goal>
                                                </goals>
                                                <configuration>
                                                       <sourceFolder>target/generated-sources/java</sourceFolder>
                                                </configuration>
                                         </execution>
                                  </executions>

                           </plugin>

Regards,

Hong Li

TTS GLOBAL Canada Payments NPS
Citibank Canada technology Service
5900 Hurontario St, Mississauga, ON L5R 0B8
[cid:image005.jpg@01CECF0F.478C28F0]: +1 (905) 755-3217

**Comment by wilkinsona** [comment]
Thanks for sharing your pom but it isn’t what we need. As I said above, it looks like a bug in QueryDSL's Maven plugin. If you think it's caused by Spring Boot, can you please explain why and provide a minimal sample that reproduces the problem?

**Comment by wilkinsona** [comment]
Actually, maybe the pom does help. I think it may be a configuration error. You have configured the plugin to process one of Spring Data’s packages:

    <package>org.springframework.data.jpa.domain.support</package>

I don’t think that’s necessary and should be removed.

**Comment by hongli8881** [comment]
Thank you very much for your reply. I just follow Spring Roo - Reference Documentation https://docs.spring.io/spring-roo/docs/current/reference/html/#resources-source-repository sept by step. When I try to make maven build of repository module I got the error message.


All pom files are auto generated including the querydsl-maven-plugin. I tried to remove <package>org.springframework.data.jpa.domain.support</package> still get same error message even I changed java version from 1.8 to 1.7. It is really appreciated if you have help to solve this issue.

Regards,

Hong Li

**Comment by wilkinsona** [comment]
Given that, I assume, you're using Spring Boot, it's not clear to me why you're following some instructions in Spring Roo's reference documentation. Also, it's still not clear why you think this is a problem with Spring Boot. I'm afraid I can't afford to spend any more time on this without a minimal sample that reproduces the problem. As I've asked twice before, can you please provide one?

**Comment by hongli8881** [comment]
It should be dependency conflict issue. However, I cannot fix it. Attached are the 2 pom file. I do not know if it can help.

Regards,

Hong Li

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by hongli8881** [comment]
Attached is the pom files of parent and module. Hope it can help.

Regards,

Hong Li

TTS GLOBAL Canada Payments NPS
Citibank Canada technology Service
5900 Hurontario St, Mississauga, ON L5R 0B8
[cid:image005.jpg@01CECF0F.478C28F0]: +1 (905) 755-3217
