### ISSUE TITLE
In container mode: NoUniqueBeanDefinitionException: localValidatorFactoryBean,mvcValidator

### ISSUE THREAD

**Issue by patoi** [spring-projects/spring-boot#1539]
__Exception:__
```
Caused by: org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [javax.validation.Validator] is defined: expected single matching bean but found 2: localValidatorFactoryBean,mvcValidator
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:970)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:858)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:480)
	... 101 common frames omitted
```
__App config:__
```java
@Configuration
@ComponentScan(basePackages = "com.mypkg")
@EnableAutoConfiguration
@EnableTransactionManagement
@EnableAspectJAutoProxy
public class TomcatStart {

    /**
     * @param args
     */
    public static void main(String[] args) {
        SpringApplication springApp = new SpringApplication(TomcatStart.class);
        springApp.addListeners(new ApplicationPidListener("application.pid"));
        springApp.run(args);
    }

    /**
     * JSR303 validator.
     * @return validator
     */
    @Bean
    public LocalValidatorFactoryBean localValidatorFactoryBean() {
        return new LocalValidatorFactoryBean();
    }
```
__pom.xml:__
```xml
...
        <dependency>
            <groupId>org.springframework.hateoas</groupId>
            <artifactId>spring-hateoas</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.security.oauth</groupId>
            <artifactId>spring-security-oauth2</artifactId>
            <version>2.0.2.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-jwt</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>
        
        <!-- WebService dep. -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-ws</artifactId>
        </dependency>
        <dependency>
            <groupId>wsdl4j</groupId>
            <artifactId>wsdl4j</artifactId>
        </dependency>
...
```
__Symptom:__
When I started the application in embedded mode, then there is no exception. When I started in 'container mode' (deploying the war file original or modificated) I've got this exception.

__Workaround:__ using ```@Quailifier``` annotation.
```java
@Component
public class ValidatorComponent<T> {

    @Autowired
    @Qualifier(value = "localValidatorFactoryBean")
    private Validator validator; 
...
```
__Assumption:__
Spring WS depends on Spring MVC. It worked fine until there is no Spring WS in project.

**Comment by wilkinsona** [comment]
The Spring MVC documentation [has been updated](https://github.com/spring-projects/spring-framework/commit/6890e65d2cd98ad89e08e2afbbb1213241a791ac) to recommend the use of `@Primary`. For example:

```java
@Bean
@Primary
public Validator localValidatorFactoryBean() {
    return new LocalValidatorFactoryBean();
}
```
