### ISSUE TITLE
spring-boot-cli broken compatibility with spring-cloud-cli

### ISSUE THREAD

**Issue by bygui86** [spring-projects/spring-boot#15607]
Hello,

working on **Contract testing**, I would like to execute the **spring-cloud-cli** `spring cloud stubrunner` using the local maven repository (~/.m2) where I pushed my stubs.

I installed **spring-boot-cli** through **brew**, that takes the very last version 2.1.1.RELEASE.
Commands are
    `brew tap pivotal/tap`
    `brew install springboot`
The installation completes without any error.

Then I installed **spring-cloud-clit**  through the spring-boot-cli itself with the command:
`spring install org.springframework.cloud:spring-cloud-cli:2.0.0.RELEASE`
The installation completes without any error, just this log:
`Installing into: /usr/local/Cellar/springboot/2.1.1.RELEASE/lib/ext`

However, when I try any spring cloud command, I got the following errors:
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.NoSuchMethodError: org.springframework.cloud.launcher.cli.LauncherCommand$LauncherOptionHandler.option(Ljava/util/Collection;Ljava/lang/String;)Ljoptsimple/OptionSpecBuilder;
	at org.springframework.cloud.launcher.cli.LauncherCommand$LauncherOptionHandler.options(LauncherCommand.java:89)
	at org.springframework.boot.cli.command.options.OptionHandler.getParser(OptionHandler.java:68)
	at org.springframework.boot.cli.command.options.OptionHandler.run(OptionHandler.java:83)
	at org.springframework.boot.cli.command.OptionParsingCommand.run(OptionParsingCommand.java:54)
	at org.springframework.boot.cli.command.CommandRunner.run(CommandRunner.java:219)
	at org.springframework.boot.cli.command.CommandRunner.runAndHandleErrors(CommandRunner.java:171)
	at org.springframework.boot.cli.SpringCli.main(SpringCli.java:63)
	... 8 more
```

I also tried other versions of spring-boot-cli in combination with spring-cloud-cli:

- **spring-boot-cli-2.2.0.BUILD-SNAPSHOT** seems to have the same issue with spring-cloud-cli-1.4.0.RELEASE and 2.0.0.RELEASE.

- **spring-boot-cli-2.1.0.RELEASE** seems to have the same issue with spring-cloud-cli-1.4.0.RELEASE and 2.0.0.RELEASE.

The only version I found working is **spring-boot-cli-2.0.7.RELEASE** with **spring-cloud-cli-2.0.0.RELEASE**.
With spring-boot-cli-2.0.7.RELEASE and spring-cloud-cli-1.4.0.RELEASE, the command `spring cloud stubrunner` does not find my stubs, probably because this is a feature introduced later than version 1.4.0.

**JDK version is 1.8.0.192**

I found the same problem tracked by [this issue](https://github.com/spring-cloud/spring-cloud-cli/issues/80) but in my opinion this is a problem of spring-boot-cli not spring-cloud-cli.

**Comment by snicoll** [comment]
> I found the same problem tracked by this issue but in my opinion this is a problem of spring-boot-cli not spring-cloud-cli.

I disagree and we can revisit this one the Spring Cloud team has looked at https://github.com/spring-cloud/spring-cloud-cli/issues/80
