### ISSUE TITLE
JspTemplateAvailabilityProvider causes java.security.AccessControlException

### ISSUE THREAD

**Issue by dezmond78** [spring-projects/spring-boot#15679]
We are running a Spring Boot powered application in form of a WAR file in a dedicated Tomcat server due to customer requirements. We're also using the Java Security Manager in order to fullfill our security requirements.

Yesterday we finally upgraded our stack to Spring Boot 2.1.1 (from 2.0.2). Since then our application is unable to start because `JspTemplateAvailabilityProvider` is causing a `java.security.AccessControlException`.

```
...
Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "src/main/webapp/index" "read")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
        at java.security.AccessController.checkPermission(AccessController.java:884)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
        at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
        at java.io.File.exists(File.java:814)
        at org.springframework.boot.autoconfigure.web.servlet.JspTemplateAvailabilityProvider.isTemplateAvailable(JspTemplateAvailabilityProvider.java:45)
        at org.springframework.boot.autoconfigure.template.TemplateAvailabilityProviders.findProvider(TemplateAvailabilityProviders.java:158)
        at org.springframework.boot.autoconfigure.template.TemplateAvailabilityProviders.getProvider(TemplateAvailabilityProviders.java:145)
        at org.springframework.boot.autoconfigure.template.TemplateAvailabilityProviders.getProvider(TemplateAvailabilityProviders.java:119)
        at org.springframework.boot.autoconfigure.web.servlet.WelcomePageHandlerMapping.welcomeTemplateExists(WelcomePageHandlerMapping.java:69)
        at org.springframework.boot.autoconfigure.web.servlet.WelcomePageHandlerMapping.<init>(WelcomePageHandlerMapping.java:59)
        at org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter.welcomePageHandlerMapping(WebMvcAutoConfiguration.java:362)
        at org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter$$EnhancerBySpringCGLIB$$84cc0ba.CGLIB$welcomePageHandlerMapping$10(<generated>)
        at org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter$$EnhancerBySpringCGLIB$$84cc0ba$$FastClassBySpringCGLIB$$bfd95f3a.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
        at org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter$$EnhancerBySpringCGLIB$$84cc0ba.welcomePageHandlerMapping(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        ... 39 more
```

I looks like this is caused by this code in `JspTemplateAvailabilityProvider`:

```
@Override
public boolean isTemplateAvailable(String view, Environment environment,
		ClassLoader classLoader, ResourceLoader resourceLoader) {
	if (ClassUtils.isPresent("org.apache.jasper.compiler.JspConfig", classLoader)) {
		String resourceName = getResourceName(view, environment);
		if (resourceLoader.getResource(resourceName).exists()) {
			return true;
		}
		return new File("src/main/webapp", resourceName).exists();
	}
	return false;
}
```

The line of interest is this:

```
return new File("src/main/webapp", resourceName).exists();
```

This code was added in June 2018 and introduced in Spring Boot 2.0.4, see [pull request](https://github.com/spring-projects/spring-boot/commit/b1d8cc55fcc7b354d056707cd820c6f1c19e718d).

I can't see a way to disable this component and it is messing with our security policy. All rules in this policy have to be explained and discussed with our customer. Right now the best explanation I have is this: Our framework is doing a check for a file we don't have and we don't need which is used by a technology (JSP) we don't use.

**Comment by wilkinsona** [comment]
See #10060 of which this is a specific example. I'm not going to close this as a duplicate just yet as I think we should consider fixing it separately given that it's caused by "a check for a file we don't have and we don't need which is used by a technology (JSP) we don't use".

**Comment by dezmond78** [comment]
Also, consider this:

- `src/main/resources` is a relative folder in the working directory of the application
- the file `index` has no ending (like `.html`, or `.jsp`)
- The component `JspTemplateAvailabilityProvider` will try to find any file at this location. In the meantime we had the same issues but with a different file `src/main/resources/error`.

The important question is: In what situation do you expect to have an external resource like `src/main/resources/index` (without file extension) in the application working directory on a productive server? Again, an external `src/main/resources` folder on a productive server...

**Comment by wilkinsona** [comment]
We'll catch the `AccessControlException` and fall through to returning false.

**Comment by wilkinsona** [comment]
Closing in favour of PR #15778.
