### ISSUE TITLE
spring-boot-starter-parent 2.1.2.RELEASE amqp rabbit not work

### ISSUE THREAD

**Issue by 502647092** [spring-projects/spring-boot#15697]
i upgrade spring-boot-starter-parent 2.1.0.RELEASE to 2.1.2.RELEASE application can't start
```log

java.lang.IllegalAccessError: class org.springframework.amqp.rabbit.listener.$Proxy224 cannot access its superinterface org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer$ContainerDelegate
	at java.lang.reflect.Proxy.defineClass0(Native Method)
	at java.lang.reflect.Proxy.access$300(Proxy.java:228)
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:642)
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557)
	at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230)
	at java.lang.reflect.WeakCache.get(WeakCache.java:127)
	at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419)
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:719)
	at org.springframework.aop.framework.JdkDynamicAopProxy.getProxy(JdkDynamicAopProxy.java:123)
	at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:110)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.initializeProxy(AbstractMessageListenerContainer.java:1135)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.initialize(AbstractMessageListenerContainer.java:1161)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.afterPropertiesSet(AbstractMessageListenerContainer.java:1109)
	at org.springframework.amqp.rabbit.listener.RabbitListenerEndpointRegistry.createListenerContainer(RabbitListenerEndpointRegistry.java:186)
	at org.springframework.amqp.rabbit.listener.RabbitListenerEndpointRegistry.registerListenerContainer(RabbitListenerEndpointRegistry.java:154)
	at org.springframework.amqp.rabbit.listener.RabbitListenerEndpointRegistry.registerListenerContainer(RabbitListenerEndpointRegistry.java:128)
	at org.springframework.amqp.rabbit.listener.RabbitListenerEndpointRegistrar.registerAllEndpoints(RabbitListenerEndpointRegistrar.java:140)
	at org.springframework.amqp.rabbit.listener.RabbitListenerEndpointRegistrar.afterPropertiesSet(RabbitListenerEndpointRegistrar.java:133)
	at org.springframework.amqp.rabbit.annotation.RabbitListenerAnnotationBeanPostProcessor.afterSingletonsInstantiated(RabbitListenerAnnotationBeanPostProcessor.java:257)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:863)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at com.sixi.ali.appservice.AliAppServiceApplication.main(AliAppServiceApplication.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
```

**Comment by wilkinsona** [comment]
Thanks for the report, but "not work" and "can't start" don't tell us enough to diagnose the problem. I can see from the stack trace that's you're using DevTools. Does the problem also occur without DevTools being involved? If you'd like us to spend some time investigating the problem, please spend some time to provide a minimal sample that reproduces it. Something that we can unzip or git clone is ideal.

**Comment by giant35** [comment]
I have similar problem, when my project use devtools then can't start , remove devtools then ok .
I try to make a tiny demo  add spring detools + spring amqp starter + spring web starter , but demo is ok . 
So may be is my project too weird.

My project start exception is : 

```

15:37:41.879	[restartedMain]	ERROR 	o.s.boot.SpringApplication 	-	 Application run failed org.springframework.beans.factory.BeanInitializationException: Failed to initialize message listener container; nested exception is org.springframework.amqp.UncategorizedAmqpException: java.lang.IllegalArgumentException: non-public interface is not defined by the given loader 
 	at org.springframework.amqp.rabbit.listener.RabbitListenerEndpointRegistry.createListenerContainer(RabbitListenerEndpointRegistry.java:189) 
 	at org.springframework.amqp.rabbit.listener.RabbitListenerEndpointRegistry.registerListenerContainer(RabbitListenerEndpointRegistry.java:154) 
 	at org.springframework.amqp.rabbit.listener.RabbitListenerEndpointRegistry.registerListenerContainer(RabbitListenerEndpointRegistry.java:128) 
 	at org.springframework.amqp.rabbit.listener.RabbitListenerEndpointRegistrar.registerAllEndpoints(RabbitListenerEndpointRegistrar.java:140) 
 	at org.springframework.amqp.rabbit.listener.RabbitListenerEndpointRegistrar.afterPropertiesSet(RabbitListenerEndpointRegistrar.java:133) 
 	at org.springframework.amqp.rabbit.annotation.RabbitListenerAnnotationBeanPostProcessor.afterSingletonsInstantiated(RabbitListenerAnnotationBeanPostProcessor.java:257) 
 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:863) 
 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863) 
 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) 
 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) 
 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) 
 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) 
 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) 
 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) 
 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) 
 	at thelook.wms.App.main(App.java:28) 
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
 	at java.base/java.lang.reflect.Method.invoke(Method.java:566) 
 	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) 
 Caused by: org.springframework.amqp.UncategorizedAmqpException: java.lang.IllegalArgumentException: non-public interface is not defined by the given loader 
 	at org.springframework.amqp.rabbit.support.RabbitExceptionTranslator.convertRabbitAccessException(RabbitExceptionTranslator.java:83) 
 	at org.springframework.amqp.rabbit.connection.RabbitAccessor.convertRabbitAccessException(RabbitAccessor.java:116) 
 	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.initialize(AbstractMessageListenerContainer.java:1179) 
 	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.afterPropertiesSet(AbstractMessageListenerContainer.java:1109) 
 	at org.springframework.amqp.rabbit.listener.RabbitListenerEndpointRegistry.createListenerContainer(RabbitListenerEndpointRegistry.java:186) 
 	... 20 common frames omitted 
 Caused by: java.lang.IllegalArgumentException: non-public interface is not defined by the given loader 
 	at java.base/java.lang.reflect.Proxy$ProxyBuilder.mapToModule(Proxy.java:798) 
 	at java.base/java.lang.reflect.Proxy$ProxyBuilder.<init>(Proxy.java:630) 
 	at java.base/java.lang.reflect.Proxy.lambda$getProxyConstructor$1(Proxy.java:426) 
 	at java.base/jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329) 
 	at java.base/jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205) 
 	at java.base/java.lang.reflect.Proxy.getProxyConstructor(Proxy.java:424) 
 	at java.base/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1006) 
 	at org.springframework.aop.framework.JdkDynamicAopProxy.getProxy(JdkDynamicAopProxy.java:123) 
 	at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:110) 
 	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.initializeProxy(AbstractMessageListenerContainer.java:1135) 
 	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.initialize(AbstractMessageListenerContainer.java:1161) 
 	... 22 common frames omitted 

```

**Comment by snicoll** [comment]
@giant35 perhaps you could share your build?  I suspect that your build is overriding certain versions so that incompatible libraries are on the classpath. We suspect that there isn't an issue in Spring Boot but can't say for sure without more details.

**Comment by giant35** [comment]
@snicoll My project is use maven , may be spring-cloud Finchley.SR2 override de version
this is the pom.xml


```

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>test</groupId>
    <artifactId>proj1</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>war</packaging>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <spring-cloud-version>Finchley.SR2</spring-cloud-version>
    </properties>    
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.2.RELEASE</version>
    </parent>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud-version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>        
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.webjars</groupId>
            <artifactId>bootstrap</artifactId>
            <version>3.3.7</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
        </dependency>
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>jstl</artifactId>
        </dependency>
        <!-- Provided -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
<!--            <scope>provided</scope>-->
        </dependency>
        <dependency>
            <groupId>org.apache.tomcat.embed</groupId>
            <artifactId>tomcat-embed-jasper</artifactId>
<!--            <scope>provided</scope>-->
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-test-autoconfigure</artifactId>
            <scope>test</scope>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>            
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>3.17</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-taglibs</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-amqp</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-cache</artifactId>
        </dependency>
        <dependency>
            <groupId>net.sf.ehcache</groupId>
            <artifactId>ehcache</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>fluent-hc</artifactId>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>commons-java-jdk11</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.sun.mail</groupId>
            <artifactId>javax.mail</artifactId>
        </dependency>
        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-annotations</artifactId>
            <version>1.5.16</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-ldap</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>3.17</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-zipkin</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-sleuth</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-sleuth-zipkin</artifactId>
        </dependency>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-core</artifactId>            
        </dependency>     
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context-indexer</artifactId>
            <optional>true</optional>
        </dependency>           
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-influx</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
    </dependencies>
    <build>
        <finalName>proj1</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <useSystemClassLoader>false</useSystemClassLoader>
                </configuration>
            </plugin>
            <plugin>
                <groupId>pl.project13.maven</groupId>
                <artifactId>git-commit-id-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>revision</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <dotGitDirectory>${project.basedir}/.git</dotGitDirectory>
                </configuration>
            </plugin>              
            
            <!--增加swagger-plugin-->
            <plugin>
                <groupId>com.github.kongchen</groupId>
                <artifactId>swagger-maven-plugin</artifactId>
                <version>3.1.7</version><!--（貌似别的版本不行，耗了挺长时间的） -->
                <configuration>                    
                    <apiSources>                        
                        <apiSource>
                            <springmvc>true</springmvc>
                            <locations>
                                <location>com.test.rest</location>
                            </locations>
                            <schemes>
                                <scheme>http</scheme>
                                <scheme>https</scheme>
                            </schemes>
                            <basePath>http://test.com</basePath>
                            <info>
                                <title>test API</title>
                                <version>v1</version>
                                <contact>
                                    <email>TTT@test.com</email>
                                    <name>TTT</name>
                                </contact>
                            </info>
                            <swaggerDirectory>${basedir}/docs/</swaggerDirectory>
                        </apiSource>
                    </apiSources>
                </configuration>
                <executions>
                    <execution>
                        <phase>compile</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>                 
        </plugins>
    </build>    
</project>


```

**Comment by 502647092** [comment]
@wilkinsona 
[test-rabbitmq-service.zip](https://github.com/spring-projects/spring-boot/files/2762298/test-rabbitmq-service.zip)

**Comment by snicoll** [comment]
@502647092 thank you for the sample. Please consider trimming down the dependencies of the sample in the future as doing so would have pointed to the proper issue tracker for this issue.

If you remove `spring-cloud-starter-sleuth` this exception goes away. There is also some machinery involved with `@EnableAspectJAutoProxy(proxyTargetClass = true, exposeProxy = true)` 

I don't believe this to be a Spring Boot issue so please report the sample against the [spring-cloud-sleuth project](https://github.com/spring-cloud/spring-cloud-sleuth)

**Comment by wilkinsona** [comment]
I was just looking at this too and I'm not sure that I agree. The problem only occurs with a combination of Sleuth and DevTools. If I remove DevTools the problem goes away. It may be that the fix needs to be made in Sleuth, but I think we need to investigate a bit more to be sure.

For the record, the minimal set of dependencies to reproduce the problem is the following:

```xml
    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-sleuth</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-amqp</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>
```

**Comment by baev** [comment]
Running into the same issue but have no Sleuth in my project. Created a project that reproduces the problem: https://github.com/baev/spring-amqp-issue

**Comment by wilkinsona** [comment]
Thank you, @baev. That tells us that it's a general proxying problem rather than something specific to Sleuth.

**Comment by arthur657834** [comment]
same error，waiting for solution

**Comment by SuperSpectre** [comment]
Same issue after upgrading from Spring Boot 2.0.8 + Spring Cloud Finchley to Spring Boot 2.1.2 + Spring Cloud Greenwich.

Excluding `spring-boot-devtools` from the dependencies solved it.
Sleuth is not used.

**Comment by wilkinsona** [comment]
@SuperSpectre Thanks. @baev has already brought it to our attention the Sleuth does not have to be used for the problem to occur. We believe that it's a general proxying problem and any use of an advice chain on `SimpleRabbitListenerContainerFactory` will trigger the problem. If your application does not fit that description, can you please provide some more details?

**Comment by wilkinsona** [comment]
This appears to be a regression in Spring AMQP caused by [this change](https://github.com/spring-projects/spring-amqp/commit/787dfa00f80d2ed33ffe40b9a0431652c72acc15#diff-22d665a9e03fe5324a13e998b57ed24dL1134). The problem can be reproduced without involving Spring Boot:

```java
 ClassLoader child = new URLClassLoader(new URL[0], AmqpProxyingBug.class.getClassLoader());
 Thread.currentThread().setContextClassLoader(child);
 SimpleRabbitListenerContainerFactory listenerContainerFactory = new SimpleRabbitListenerContainerFactory();
 listenerContainerFactory.setAdviceChain((MethodInterceptor) MethodInvocation::proceed);
 listenerContainerFactory.setConnectionFactory(new CachingConnectionFactory());
 listenerContainerFactory.createListenerContainer().afterPropertiesSet();
```

In this case, the proxy is created using the `child` class loader but it is attempting to create a proxy for the `AbstractMessageListenerContainer$ContainerDelegate` interface which is visible to the parent class loader but is also private. This makes the interface inaccessible and an `IllegalAccessError` is thrown.

**Comment by wilkinsona** [comment]
I have opened https://github.com/spring-projects/spring-amqp/issues/897.

**Comment by devinsba** [comment]
I was able to reproduce this error without `spring-amqp` on the classpath. The difference being only removing devtools fixed it, no other dependency worked as far as I could test. Should I open a new issue and put together an example? Or continue here?

**Comment by philwebb** [comment]
@devinsba That sounds like a different root cause. Could you please open a new issue with an example.
