### ISSUE TITLE
404 errors are not handled correctly when application is deployed as WAR to WebSphere (Cannot forward. Response already committed)

### ISSUE THREAD

**Issue by imgx64** [spring-projects/spring-boot#1575]
The bug happens with 1.1.5.RELEASE and 1.2.0.BUILD-SNAPSHOT.

Using this project: https://github.com/spring-guides/gs-convert-jar-to-war-maven/tree/master/complete , deployed as a WAR to IBM WebSphere 8.0.0.9 (However, it works correctly on Tomcat), when I visit a non-existent page (For example: `curl -i http://localhost:9080/gs-convert-jar-to-war-maven/nonexistent`), I get HTTP 200 response and a blank page:

```
HTTP/1.1 200 OK
X-Powered-By: Servlet/3.0
Content-Language: en-US
Transfer-Encoding: chunked
Date: Thu, 18 Sep 2014 05:04:26 GMT

```

(This is the whole response, there is no body)

And I get this stack trace in the WebSphere logs:

```
[9/18/14 8:04:26:866 AST] 0000002d SystemOut     O com.ibm.ws.logging.WsLogger deliverOrBuffer 2014-09-18 08:04:26.866  WARN 1996 --- [ebContainer : 9] c.i.w.w.srt.SRTServletResponse           : WARNING: Cannot set status. Response already committed.

[9/18/14 8:04:26:869 AST] 0000002d SystemOut     O   2014-09-18 08:04:26.869 ERROR 1996 --- [ebContainer : 9] o.s.boot.context.web.ErrorPageFilter     : Forwarding to error page from request [/nonexistent] due to exception [Cannot forward. Response already committed.]

java.lang.IllegalStateException: Cannot forward. Response already committed.
        at com.ibm.ws.webcontainer.webapp.WebAppRequestDispatcher.dispatch(WebAppRequestDispatcher.java:1149)
        at com.ibm.ws.webcontainer.webapp.WebAppRequestDispatcher.forward(WebAppRequestDispatcher.java:194)
        at org.springframework.boot.context.web.ErrorPageFilter.handleErrorStatus(ErrorPageFilter.java:134)
        at org.springframework.boot.context.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:111)
        at org.springframework.boot.context.web.ErrorPageFilter.access$000(ErrorPageFilter.java:58)
        at org.springframework.boot.context.web.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:87)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.boot.context.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:100)
        at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:195)
        at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
        at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:960)
        at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1064)
        at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:3815)
        at com.ibm.ws.webcontainer.webapp.WebGroup.handleRequest(WebGroup.java:304)
        at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:981)
        at com.ibm.ws.webcontainer.WSWebContainer.handleRequest(WSWebContainer.java:1662)
        at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:200)
        at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:453)
        at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewRequest(HttpInboundLink.java:515)
        at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.processRequest(HttpInboundLink.java:306)
        at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.ready(HttpInboundLink.java:277)
        at com.ibm.ws.tcp.channel.impl.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:214)
        at com.ibm.ws.tcp.channel.impl.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:113)
        at com.ibm.ws.tcp.channel.impl.AioReadCompletionListener.futureCompleted(AioReadCompletionListener.java:175)
        at com.ibm.io.async.AbstractAsyncFuture.invokeCallback(AbstractAsyncFuture.java:217)
        at com.ibm.io.async.AsyncChannelFuture.fireCompletionActions(AsyncChannelFuture.java:161)
        at com.ibm.io.async.AsyncFuture.completed(AsyncFuture.java:138)
        at com.ibm.io.async.ResultHandler.complete(ResultHandler.java:204)
        at com.ibm.io.async.ResultHandler.runEventProcessingLoop(ResultHandler.java:775)
        at com.ibm.io.async.ResultHandler$2.run(ResultHandler.java:905)
        at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1702)


[9/18/14 8:04:26:870 AST] 0000002d SystemOut     O   2014-09-18 08:04:26.870 ERROR 1996 --- [ebContainer : 9] o.s.boot.context.web.ErrorPageFilter     : Cannot forward to error page for/gs-convert-jar-to-war-maven/nonexistent (response is committed), so this response may have the wrong status code

java.lang.IllegalStateException: Cannot forward. Response already committed.
        at com.ibm.ws.webcontainer.webapp.WebAppRequestDispatcher.dispatch(WebAppRequestDispatcher.java:1149)
        at com.ibm.ws.webcontainer.webapp.WebAppRequestDispatcher.forward(WebAppRequestDispatcher.java:194)
        at org.springframework.boot.context.web.ErrorPageFilter.handleErrorStatus(ErrorPageFilter.java:134)
        at org.springframework.boot.context.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:111)
        at org.springframework.boot.context.web.ErrorPageFilter.access$000(ErrorPageFilter.java:58)
        at org.springframework.boot.context.web.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:87)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.boot.context.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:100)
        at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:195)
        at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
        at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:960)
        at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1064)
        at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:3815)
        at com.ibm.ws.webcontainer.webapp.WebGroup.handleRequest(WebGroup.java:304)
        at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:981)
        at com.ibm.ws.webcontainer.WSWebContainer.handleRequest(WSWebContainer.java:1662)
        at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:200)
        at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:453)
        at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewRequest(HttpInboundLink.java:515)
        at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.processRequest(HttpInboundLink.java:306)
        at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.ready(HttpInboundLink.java:277)
        at com.ibm.ws.tcp.channel.impl.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:214)
        at com.ibm.ws.tcp.channel.impl.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:113)
        at com.ibm.ws.tcp.channel.impl.AioReadCompletionListener.futureCompleted(AioReadCompletionListener.java:175)
        at com.ibm.io.async.AbstractAsyncFuture.invokeCallback(AbstractAsyncFuture.java:217)
        at com.ibm.io.async.AsyncChannelFuture.fireCompletionActions(AsyncChannelFuture.java:161)
        at com.ibm.io.async.AsyncFuture.completed(AsyncFuture.java:138)
        at com.ibm.io.async.ResultHandler.complete(ResultHandler.java:204)
        at com.ibm.io.async.ResultHandler.runEventProcessingLoop(ResultHandler.java:775)
        at com.ibm.io.async.ResultHandler$2.run(ResultHandler.java:905)
        at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1702)


```

**Comment by dsawsome** [comment]
Hi guys,
  I'm running struts 1.3 application on IBM Liberty Profile WAS 8.5.5.5. The same code base works perfectly in the old RAD+WAS7 environment. However, when it's deployed in the liberty profile, whenever a page not found (error 404) occurs, it does not load my error404.jsp where I specified in the web.xml I've spend quite sometime searching on the web and yet to find a solution.
<p>&lt;error-page&gt;<br /> &lt;error-code&gt;404&lt;/error-code&gt;<br /> &lt;location&gt;/jsp/error404.jsp&lt;/location&gt;<br /> &lt;/error-page&gt;</p>
But this still not solving my problem, anyone's experiencing the same thing?

The following is what shown in my console:
<code>
 2015-07-23 10:56:24,254 [Default Executor-thread-9] ERROR org.apache.struts.tiles.taglib.InsertTag -  - ServletException in '/jsp/mdel_search_results.jsp': JSPG0036E: Failed to find resource /jsp/mdel_search_results.jsp

[ERROR   ] SRVE0777E: Exception thrown by application class 'org.apache.jasper.runtime.PageContextImpl.handlePageException:699'

[ERROR   ] SRVE0777E: Exception thrown by application class 'org.apache.jasper.runtime.PageContextImpl.handlePageException:699'

[ERROR   ] SRVE0777E: Exception thrown by application class 'org.apache.jasper.runtime.PageContextImpl.handlePageException:699'

[WARNING ] WARNING: Cannot set status. Response already committed.

[WARNING ] SRVE8094W: WARNING: Cannot set header. Response already committed.  Stack trace of errant attempt to set header: 
</code>

**Comment by simonmiller99** [comment]
thanks for the 1.8 byte code steer in WLP 8553. Although I'm not using Spring, it helped a lot. I found which jar file was causing the issue by looking in the ffdc files
