### ISSUE TITLE
Build failure on Windows 7 due to encoding problems

### ISSUE THREAD

**Issue by ivanhjc** [spring-projects/spring-boot#15765]
I'm building from command line window by running `mvnw clean install` and the cmd encoding checked with `chcp` is `65001`, and the JVM encoding is UTF-8 as checked via 

    System.out.println(Charset.defaultCharset());
    System.out.println(System.getProperty("file.encoding"));

Java version is as follows:

    java version "1.8.0_201"
    Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
    Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

Here's the complete report:

    -------------------------------------------------------------------------------
    Test set: org.springframework.boot.actuate.autoconfigure.endpoint.web.documentation.EnvironmentEndpointDocumentationTests
    -------------------------------------------------------------------------------
    Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.557 s <<< FAILURE! - in org.springframework.boot.actuate.autoconfigure.endpoint.web.documentation.EnvironmentEndpointDocumentationTests
    env(org.springframework.boot.actuate.autoconfigure.endpoint.web.documentation.EnvironmentEndpointDocumentationTests)  Time elapsed: 0.028 s  <<< ERROR!
    java.lang.IllegalStateException: 
    com.fasterxml.jackson.core.JsonParseException: Invalid UTF-8 middle byte 0xc2
     at [Source: (byte[])"{
      "activeProfiles" : [ ],
      "propertySources" : [ {
        "name" : "systemProperties",
        "properties" : {
          "java.runtime.name" : {
            "value" : "Java(TM) SE Runtime Environment"
          },
          "sun.boot.library.path" : {
            "value" : "C:\\Program Files\\Java\\jdk1.8.0_101\\jre\\bin"
          },
          "java.vm.version" : {
            "value" : "25.101-b13"
          },
          "java.vm.vendor" : {
            "value" : "Oracle Corporation"
          },
          "java.vendor.url" : {
     "[truncated 101118 bytes]; line: 273, column: 29]
    	at org.springframework.boot.actuate.autoconfigure.endpoint.web.documentation.EnvironmentEndpointDocumentationTests.filterProperties(EnvironmentEndpointDocumentationTests.java:138)
    	at org.springframework.restdocs.operation.preprocess.ContentModifyingOperationPreprocessor.preprocess(ContentModifyingOperationPreprocessor.java:56)
    	at org.springframework.restdocs.operation.preprocess.DelegatingOperationResponsePreprocessor.preprocess(DelegatingOperationResponsePreprocessor.java:50)
    	at org.springframework.restdocs.generate.RestDocumentationGenerator.preprocess(RestDocumentationGenerator.java:260)
    	at org.springframework.restdocs.generate.RestDocumentationGenerator.preprocess(RestDocumentationGenerator.java:274)
    	at org.springframework.restdocs.generate.RestDocumentationGenerator.preprocessResponse(RestDocumentationGenerator.java:254)
    	at org.springframework.restdocs.generate.RestDocumentationGenerator.handle(RestDocumentationGenerator.java:195)
    	at org.springframework.restdocs.mockmvc.RestDocumentationResultHandler.handle(RestDocumentationResultHandler.java:55)
    	at org.springframework.test.web.servlet.MockMvc$1.andDo(MockMvc.java:200)
    	at org.springframework.boot.actuate.autoconfigure.endpoint.web.documentation.EnvironmentEndpointDocumentationTests.env(EnvironmentEndpointDocumentationTests.java:73)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
    	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
    	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
    	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
    	at org.springframework.restdocs.JUnitRestDocumentation$1.evaluate(JUnitRestDocumentation.java:62)
    	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
    	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
    	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
    	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
    	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
    	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
    	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
    	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
    	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
    	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
    	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
    	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
    	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
    	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
    Caused by: com.fasterxml.jackson.core.JsonParseException: Invalid UTF-8 middle byte 0xc2
     at [Source: (byte[])"{
      "activeProfiles" : [ ],
      "propertySources" : [ {
        "name" : "systemProperties",
        "properties" : {
          "java.runtime.name" : {
            "value" : "Java(TM) SE Runtime Environment"
          },
          "sun.boot.library.path" : {
            "value" : "C:\\Program Files\\Java\\jdk1.8.0_101\\jre\\bin"
          },
          "java.vm.version" : {
            "value" : "25.101-b13"
          },
          "java.vm.vendor" : {
            "value" : "Oracle Corporation"
          },
          "java.vendor.url" : {
     "[truncated 101118 bytes]; line: 273, column: 29]
    	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
    	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:693)
    	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidOther(UTF8StreamJsonParser.java:3549)
    	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidOther(UTF8StreamJsonParser.java:3556)
    	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._decodeUtf8_2(UTF8StreamJsonParser.java:3329)
    	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString2(UTF8StreamJsonParser.java:2461)
    	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishAndReturnString(UTF8StreamJsonParser.java:2413)
    	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.getText(UTF8StreamJsonParser.java:269)
    	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:672)
    	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.mapObject(UntypedObjectDeserializer.java:871)
    	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:654)
    	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.mapObject(UntypedObjectDeserializer.java:895)
    	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:654)
    	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.mapObject(UntypedObjectDeserializer.java:880)
    	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:654)
    	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.mapArray(UntypedObjectDeserializer.java:817)
    	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:668)
    	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:527)
    	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
    	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29)
    	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
    	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3091)
    	at org.springframework.boot.actuate.autoconfigure.endpoint.web.documentation.EnvironmentEndpointDocumentationTests.filterProperties(EnvironmentEndpointDocumentationTests.java:125)
    	... 45 more

**Comment by wilkinsona** [comment]
Thanks for the report but I'm not sure that there is anything that we can do about this. We know that there isn't a general problem on Windows as our [CI is green](https://build.spring.io/browse/BOOT-WIN-1485). There appears to be a character in a System property that is set on your machine that cannot be encoded as UTF-8. We could perhaps make the environment endpoint more robust, but it will be difficult to do so without knowing more about the environment in which you're running the build. If you would like us to investigate further, can you please provide detailed information about the System properties in your JVM.

**Comment by ivanhjc** [comment]
Not sure which properties are needed here but here's the list of properties retrieved from my running environment:

Property | Value
--- | ---
file.encoding | UTF-8
file.separator | \
java.home | C:\Program Files\Java\jdk1.8.0_101\jre
java.vendor | Oracle Corporation
java.vendor.url | http://java.oracle.com/
java.version | 1.8.0_101
line.separator | 
os.arch | amd64
os.name | Windows 7
os.version | 6.1
path.separator | ;
user.dir | F:\projects\onenote
user.home | C:\Users\Administrator
user.name | Administrator

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
