### ISSUE TITLE
@ConditionalOnProperty throw the exception: PersistenceExceptionTranslator must not be null

### ISSUE THREAD

**Issue by Crab2died** [spring-projects/spring-boot#15773]
When I use the annotation `@ConditionalOnProperty` implement dynamic class injection，
class like
```java
 @ConditionalOnProperty(name = {"condition"})
 @Repository
 public class AImpl implements ADao {
       
     @Override
     public String getSomething() {
         try{
             ...code: mybe throw exceptions...
             return "";
         }catch(Exception e){
            throw new RuntimeException(e); 
        }
     } 
 }
```
Sevice class like this
```java
 @Service
 public class ServiceImpl implements ServiceInterface {
     
     @Autowired
     private ADao aDao;  

     @Override
     public String method() {
       // this will throw the exception
       // PersistenceExceptionTranslator must not be null
       return aDao.getSomething();
     } 
 }
````
throw this exception **_sometimes_**: 
```
[dispatcherServlet][182] -Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalArgumentException: PersistenceExceptionTranslator must not be null] with root cause
java.lang.IllegalArgumentException: PersistenceExceptionTranslator must not be null
	at org.springframework.util.Assert.notNull(Assert.java:193)
	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.addDelegate(ChainedPersistenceExceptionTranslator.java:45)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.detectPersistenceExceptionTranslators(PersistenceExceptionTranslationInterceptor.java:172)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:150)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at 
```
I do not use the annotation  `@Transactional `, but I do`t known why throw this exception.

**Comment by snicoll** [comment]
@Crab2died I am afraid I didn't understand what you mean by "dynamic class injection" nor why you think this is a bug in Spring Boot. 

To be sure, can you please share a minimal sample we can run ourselves (a link to a repo or a zip we can download). Thank you.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
