### ISSUE TITLE
IllegalArgumentException while executing bootJar task

### ISSUE THREAD

**Issue by jndietz** [spring-projects/spring-boot#15806]
**Versions**
Spring Boot Dependency Management Plugin 1.0.6.RELEASE
Spring Boot / Gradle Plugin 2.1.2.RELEASE

**Details**
When executing the `:bootJar` task, or `:build`, the build fails with the following error:

```
* What went wrong:
Execution failed for task ':iris-service:bootJar'.
> java.lang.IllegalArgumentException (no error message)

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':iris-service:bootJar'.
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:49)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
	at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.IllegalArgumentException
	at org.springframework.asm.ClassVisitor.<init>(ClassVisitor.java:79)
	at org.springframework.asm.ClassVisitor.<init>(ClassVisitor.java:64)
	at org.springframework.boot.loader.tools.MainClassFinder$ClassDescriptor.<init>(MainClassFinder.java:302)
	at org.springframework.boot.loader.tools.MainClassFinder.createClassDescriptor(MainClassFinder.java:267)
	at org.springframework.boot.loader.tools.MainClassFinder.doWithMainClasses(MainClassFinder.java:139)
	at org.springframework.boot.loader.tools.MainClassFinder.findSingleMainClass(MainClassFinder.java:110)
	at org.springframework.boot.gradle.plugin.MainClassConvention.findMainClass(MainClassConvention.java:74)
	at org.springframework.boot.gradle.plugin.MainClassConvention.resolveMainClass(MainClassConvention.java:68)
	at org.springframework.boot.gradle.plugin.MainClassConvention.call(MainClassConvention.java:63)
	at org.gradle.util.GUtil.uncheckedCall(GUtil.java:459)
	at org.gradle.api.internal.ConventionAwareHelper$2.doGetValue(ConventionAwareHelper.java:82)
	at org.gradle.api.internal.ConventionAwareHelper$MappedPropertyImpl.getValue(ConventionAwareHelper.java:126)
	at org.gradle.api.internal.ConventionAwareHelper.getConventionValue(ConventionAwareHelper.java:109)
	at org.springframework.boot.gradle.tasks.bundling.BootJar_Decorated.getMainClassName(Unknown Source)
	at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$DefaultPropertyValue$1$1.create(AbstractNestedRuntimeBeanNode.java:83)
	at org.gradle.util.SingleMessageLogger.whileDisabled(SingleMessageLogger.java:313)
	at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$DefaultPropertyValue$1.get(AbstractNestedRuntimeBeanNode.java:80)
	at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:125)
	at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$DefaultPropertyValue.getValue(AbstractNestedRuntimeBeanNode.java:138)
	at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$DefaultPropertyValue.validate(AbstractNestedRuntimeBeanNode.java:149)
	at org.gradle.api.internal.tasks.DefaultTaskInputPropertySpec.validate(DefaultTaskInputPropertySpec.java:61)
	at org.gradle.api.internal.tasks.execution.DefaultTaskProperties.validate(DefaultTaskProperties.java:193)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:47)
	... 26 more
```

This seems to be prevalent in any of the Spring Boot 2 versions.  I do not have this behavior when rolling back to 1.5.X.RELEASE.

**Comment by wilkinsona** [comment]
The line numbers in the stack trace don't look right for Spring Boot 2.1.2 (Spring Framework 5.1.4). In particular, the line numbers in `ClassVisitor` where the exception occurs do not match up with the source.

Can you please let us know the version of Java that you're using and provide a minimal sample that reproduces the problem?

**Comment by jndietz** [comment]
@wilkinsona Will do.

**Comment by jndietz** [comment]
Well, of course I'm not able to reproduce it with a new project.  Sorry, I should have done that before posting.  If I had to guess, it is another dependency that is causing me problems.  It has been tough to nail down since it just quit building one day.
