### ISSUE TITLE
Petclinic integration tests failing - data.sql not being run, possibly?

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#15818]
Lots of failures like this if you update the Petclinic to 2.2.0 snapshots:

```
org.springframework.orm.ObjectRetrievalFailureException: Object of class [org.springframework.samples.petclinic.owner.PetType] with identifier [1]: not found
	at org.springframework.samples.petclinic.service.EntityUtils.getById(EntityUtils.java:51)
	at org.springframework.samples.petclinic.service.ClinicServiceTests.shouldFindAllPetTypes(ClinicServiceTests.java:151)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
...
```

**Comment by dsyer** [comment]
I can't reproduce this now (1 hour later). No idea what happened. Probably something JDK-related because I was trying out different JDK builds.
