### ISSUE TITLE
Spring Boot 2.0.7 + Webflux +thymeleaf error pages give type mismatch string to int

### ISSUE THREAD

**Issue by dmbeer** [spring-projects/spring-boot#16006]
I have placed my custom error page in the templates/error/400.html or 404.html and get the following in the console log:

```
org.springframework.web.server.ServerWebInputException: Response status 400 with reason "Type mismatch."; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'int'; nested exception is java.lang.NumberFormatException: For input string: "new-page"
	at org.springframework.web.reactive.result.method.annotation.AbstractNamedValueArgumentResolver.applyConversion(AbstractNamedValueArgumentResolver.java:197) ~[spring-webflux-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.web.reactive.result.method.annotation.AbstractNamedValueArgumentResolver.lambda$resolveArgument$0(AbstractNamedValueArgumentResolver.java:107) ~[spring-webflux-5.0.11.RELEASE.jar:5.0.11.RELEASE]
```

Expected output should be no error logged and correct error page shown.

**Comment by mbhave** [comment]
@dmbeer Can you provide a minimal and complete sample that we can use to reproduce the issue?

**Comment by dmbeer** [comment]
@mbhave In a clean project no. It seems this might be due to my index controller as it expects a number due to page results.
