### ISSUE TITLE
Issue with spring boot v2.1.2 with DocumentBuilderFactory.setFeature(String) 

### ISSUE THREAD

**Issue by shai125** [spring-projects/spring-boot#16058]
Hello,
I tried to upgrade my spring boot application from version 2.1.1 to 2.1.2 and encounter with this error:

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.ws.soap.addressing.server.AnnotationActionEndpointMapping]: Factory method 'annotationActionEndpointMapping' threw exception; nested exception is java.lang.AbstractMethodError: javax.xml.parsers.DocumentBuilderFactory.setFeature(Ljava/lang/String;Z)V
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622)
	... 63 more
Caused by: java.lang.AbstractMethodError: javax.xml.parsers.DocumentBuilderFactory.setFeature(Ljava/lang/String;Z)V
	at org.springframework.xml.DocumentBuilderFactoryUtils.newInstance(DocumentBuilderFactoryUtils.java:58)
	at org.springframework.ws.soap.addressing.version.AbstractAddressingVersion.<clinit>(AbstractAddressingVersion.java:66)
	at org.springframework.ws.soap.addressing.server.AbstractAddressingEndpointMapping.initDefaultStrategies(AbstractAddressingEndpointMapping.java:107)
	at org.springframework.ws.soap.addressing.server.AbstractAddressingEndpointMapping.<init>(AbstractAddressingEndpointMapping.java:98)
	at org.springframework.ws.soap.addressing.server.AbstractActionEndpointMapping.<init>(AbstractActionEndpointMapping.java:38)
	at org.springframework.ws.soap.addressing.server.AbstractActionMethodEndpointMapping.<init>(AbstractActionMethodEndpointMapping.java:34)
	at org.springframework.ws.soap.addressing.server.AnnotationActionEndpointMapping.<init>(AnnotationActionEndpointMapping.java:60)
	at org.springframework.ws.config.annotation.WsConfigurationSupport.annotationActionEndpointMapping(WsConfigurationSupport.java:120)
	at org.springframework.ws.config.annotation.DelegatingWsConfiguration$$EnhancerBySpringCGLIB$$a6890976.CGLIB$annotationActionEndpointMapping$7(<generated>)
	at org.springframework.ws.config.annotation.DelegatingWsConfiguration$$EnhancerBySpringCGLIB$$a6890976$$FastClassBySpringCGLIB$$35b3f47d.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
	at org.springframework.ws.config.annotation.DelegatingWsConfiguration$$EnhancerBySpringCGLIB$$a6890976.annotationActionEndpointMapping(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 64 more
```

I seems that the some jar has problem with the following java 8 method:
DocumentBuilderFactory.setFeature(Ljava/lang/String) 
These are the relevant dependencies in my pom.xml :

 ```
   <dependency>
      <groupId>org.springframework.ws</groupId>
      <artifactId>spring-ws-security</artifactId>
    </dependency>
 ```

 ```
   <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web-services</artifactId>
      <exclusions>
        <exclusion>
          <groupId>ch.qos.logback</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

```

**Comment by wilkinsona** [comment]
It appears that the concrete `javax.xml.parsers.DocumentBuilderFactory` subclass that you have on the classpath does not implement `
javax.xml.parsers.DocumentBuilderFactory.setFeature(Ljava/lang/String;Z)V`. That is not the case by default and also is not the case with the dependencies that you have shown above so I suspect the problem is being caused by another dependency that you have not shown above.

You should be able to diagnose the problem by debugging your application with a breakpoint in `javax.xml.parsers.DocumentBuilderFactory.newInstance()` and looking at the instance that it returns. The fully-qualified name of the instance's class and the jar which it is loaded from (using `getClass().getProtectionDomain().getCodeSource().getLocation()`) should help to pinpoint the cause of the problem..

**Comment by shai125** [comment]
Thanks for replying so quickly.
You were correct to identifying the problem. Indeed some old third party jar was the issue. It implemented DocumentBuilderFactory that crashes my application.

**Comment by wilkinsona** [comment]
Thanks for letting us know. You’ll need to exclude or update that dependency.
