### ISSUE TITLE
JVM doesn't terminate when using Spring Batch and RestClientAutoConfiguration

### ISSUE THREAD

**Issue by gonzalad** [spring-projects/spring-boot#16164]
I'm running a Spring Boot Application containing a single batch job.

The batch job uses the REST ElasticsearchRestTemplate.

When running the application, i.e. via command line:
```
java -cp D:\Dev\sources\portail-assurance-backend\portail-batch\src\test\resources;portail-assurance-batch-0.0.1-SNAPSHOT.jar -Dspring.profiles.active=test -Dspring.batch.job.names=importCsvToEsJob -Dspring.batch.job.enabled=true org.springframework.boot.loader.JarLauncher
```

The batch is executed, but the JVM doesn't exit.

Versions:
* Spring Boot Version: 2.1.2.RELEASE
* Spring Data Elasticsearch: 3.2.0.M1
* Elasticsearch client: 6.5.0

I've done a thread dump (see [1])

The issue seems to come from the fact that RestClientAutoConfiguration creates instances of RestClient and RestHighLevelClient. And those instances use internally a CloseableHttpAsyncClient which needs to be closed before the JVM can terminate.

For information, I've created a jobListener in my project to close those resources at the end of the job (this is a bit of a hack since I do that explicitly, but I didn't find a better way):

```
public class ClosingRestClientJobListener implements org.springframework.batch.core.JobExecutionListener {

    private boolean closeClientsOnJobTermination;

    private Optional<RestClient> restClient;

    private Optional<RestHighLevelClient> restHighLevelClient;

    /**
     * Clôture les clients async si closeClientsOnJobTermination vaut true.
     * Sinon Noop.
     */
    public ClosingRestClientJobListener(boolean closeClientsOnJobTermination, Optional<RestClient> restClient,
            Optional<RestHighLevelClient> restHighLevelClient) {
        this.closeClientsOnJobTermination = closeClientsOnJobTermination;
        this.restClient = restClient;
        this.restHighLevelClient = restHighLevelClient;
    }

    @Override
    public void beforeJob(JobExecution jobExecution) {
    }

    @Override
    public void afterJob(JobExecution jobExecution) {
        if (closeClientsOnJobTermination) {
            restHighLevelClient.ifPresent(it -> close(it));
            restClient.ifPresent(it -> close(it));
        }
    }

    private void close(RestClient restClient) {
        try {
            restClient.close();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    private void close(RestHighLevelClient restHighLevelClient) {
        try {
            restHighLevelClient.close();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    public boolean isCloseClientsOnJobTermination() {
        return closeClientsOnJobTermination;
    }
}
```

[1] Thread dump
And I see 2 RUNNABLE threads like:
```
"pool-2-thread-1@4676" prio=5 tid=0x1a nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Unknown Source:-1)
	  at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source:-1)
	  at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source:-1)
	  at sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source:-1)
	  at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source:-1)
	  - locked <merged>(a sun.nio.ch.WindowsSelectorImpl)
	  - locked <merged>(a java.util.Collections$UnmodifiableSet)
	  - locked <merged>(a sun.nio.ch.Util$3)
	  at sun.nio.ch.SelectorImpl.select(Unknown Source:-1)
	  at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:340)
	  at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:221)
	  at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
	  at java.lang.Thread.run(Unknown Source:-1)
```

I have a ReferenceHandler and a Finalizer thread both in WAITING state.

And 16 RUNNABLE threads :
```
"I/O dispatcher 16@4687" prio=5 tid=0x22 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Unknown Source:-1)
	  at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source:-1)
	  at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source:-1)
	  at sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source:-1)
	  at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source:-1)
	  - locked <merged>(a sun.nio.ch.WindowsSelectorImpl)
	  - locked <merged>(a java.util.Collections$UnmodifiableSet)
	  - locked <merged>(a sun.nio.ch.Util$3)
	  at sun.nio.ch.SelectorImpl.select(Unknown Source:-1)
	  at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:255)
	  at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	  at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	  at java.lang.Thread.run(Unknown Source:-1)
```

**Comment by wilkinsona** [comment]
Thanks for the detailed analysis. I don't yet understand the behaviour that you have described. Both `RestClient` and `RestHighLevelClient` have `close()` methods. Those methods should be called automatically as part of application context shutdown.

**Comment by wilkinsona** [comment]
Are you relying on the shutdown hook to close the context? The shutdown hook will only run if there are no non-daemon threads alive and that won't be the case here. You'll need to close the application context to ensure that everything gets tidied up.

For Batch applications, we typically recommend doing something like this:

```
System.exit(SpringApplication
        .exit(SpringApplication.run(ExampleApplication.class, args)));
```

This will use any `ExitCodeGenerator` beans to determine the application's exit code, close the application context, and then pass the determined exit code into `System.exit`.

If you are already closing the context (either directly or indirectly) and the JVM does not exit please provide a minimal sample application that reproduces the behaviour you have described and we can re-open this issue and take another look.

**Comment by gonzalad** [comment]
Thanks @wilkinsona, adding the exit instruction after SpringApplication.run just fixed my issue.

```
    public static void main(String[] args) {
        SpringApplication.run(PortailAssuranceBatchApplication.class, args);
        System.exit(SpringApplication.exit(SpringApplication.run(PortailAssuranceBatchApplication.class, args)));
    }
```

Thanks very much, I was doing a horrible hack for such a simple thing :(
