### ISSUE TITLE
Inconsistent behavior turning off the check for the change log location: Liquibase fails anyway

### ISSUE THREAD

**Issue by Treehopper** [spring-projects/spring-boot#16232]
Using spring-boot-autoconfigure 2.1.2 and liquibase-core-3.6.2, I would have expected that missing change logs are handled gracefully when checkChangeLogLocation/checkLocation is set to false.
This is the case for Flyway, however, for Liquibase it only means that the LiquibaseAutoConfiguration won't complain, though Liquibase will fail slightly later.
What is the use case for setting checkChangeLogLocation to false, if a missing changelog will result in a failure anyway, or am I missing something?

If this used to work differently, is there a known liquibase bug for that?
Otherwise, I suggest removing the checkChangeLogLocation property.

I get:
```
 Caused by: liquibase.exception.ChangeLogParseException: Error parsing classpath:/db/changelog/db.changelog-master.yaml
 	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:84)
 	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:217)
 	at liquibase.Liquibase.update(Liquibase.java:190)
 	at liquibase.Liquibase.update(Liquibase.java:179)
 	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:353)
 	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:305)
 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1804)
 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1741)
 	... 62 more
 Caused by: java.io.FileNotFoundException: class path resource [db/changelog/db.changelog-master.yaml] cannot be resolved to URL because it does not exist
 	at org.springframework.core.io.ClassPathResource.getURL(ClassPathResource.java:195)
 	at liquibase.integration.spring.SpringLiquibase$SpringResourceOpener.getResourcesAsStream(SpringLiquibase.java:556)
 	at liquibase.util.StreamUtil.singleInputStream(StreamUtil.java:186)
 	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:27)
 	... 69 more
```
instead of:
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.ChangeLogParseException: Error Reading Migration File: class path resource [db/liquibase/changelog-master.xml] cannot be resolved to URL because it does not exist
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1745) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:576) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:307) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:846) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863) ~[spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) ~[spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) ~[spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) ~[spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at com.kpit.diagnostics.dds.core.Application.main(Application.java:13) ~[classes/:na]
Caused by: liquibase.exception.ChangeLogParseException: Error Reading Migration File: class path resource [db/liquibase/changelog-master.xml] cannot be resolved to URL because it does not exist
	at liquibase.parser.core.xml.XMLChangeLogSAXParser.parseToNode(XMLChangeLogSAXParser.java:118) ~[liquibase-core-3.6.2.jar:na]
	at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:15) ~[liquibase-core-3.6.2.jar:na]
	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:217) ~[liquibase-core-3.6.2.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:190) ~[liquibase-core-3.6.2.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:179) ~[liquibase-core-3.6.2.jar:na]
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:353) ~[liquibase-core-3.6.2.jar:na]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:305) ~[liquibase-core-3.6.2.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1741) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	... 16 common frames omitted
Caused by: java.io.FileNotFoundException: class path resource [db/liquibase/changelog-master.xml] cannot be resolved to URL because it does not exist
	at org.springframework.core.io.ClassPathResource.getURL(ClassPathResource.java:195) ~[spring-core-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at liquibase.integration.spring.SpringLiquibase$SpringResourceOpener.getResourcesAsStream(SpringLiquibase.java:556) ~[liquibase-core-3.6.2.jar:na]
	at liquibase.util.StreamUtil.singleInputStream(StreamUtil.java:186) ~[liquibase-core-3.6.2.jar:na]
	at liquibase.parser.core.xml.XMLChangeLogSAXParser.parseToNode(XMLChangeLogSAXParser.java:71) ~[liquibase-core-3.6.2.jar:na]
	... 24 common frames omitted
```

**Comment by philwebb** [comment]
Looking at the Liquibase code I think it might be possible for the `spring.liquibase.change-log` property to use a pattern. Our resource checking only looks for a single file so I guess it's possible that you might have a pattern that won't exist on its own, but will still be supported by liquibase.

It still feels a bit of an odd property for liquibase. My guess is we just added it for parity with Flyway. 

I'll flag this issue to see if anyone else on the team remembers the history.

**Comment by Treehopper** [comment]
I currently work around this issue by running code before the LiquibaseAutoConfiguration, checking for the existence of the resource, and disabling Liquibase in that case via LiquibaseProperties#setEnabled.
I assume the same could be achieved, performing the check within the AutoConfiguration and calling SpringLiquibase#setShouldRun accordingly.

**Comment by bvoss** [comment]
Just a short side note here @mbhave 
Removing the field incl getter/setter from the java class seems to me a bit unexpected on a patch release.
We use the LiquibaseProperties in tests and got compile errors there. Of  course there were easy to fix, but a bit surprising when updating from Spring Boot 2.1.6 to 2.1.7.

**Comment by Treehopper** [comment]
@mbhave Unfortunately your change breaks my workaround and makes matters worse for me. Also, it removes the API symmetry between Liquibase and Flyway support.
If I may ask, why did you decide against adding a resource check within the LiquibaseAutoConfiguration, calling SpringLiquibase#setShouldRun accordingly as suggested in my previous post?

Also, this is an API breaking change. I agree with @bvoss that it shouldn't be in 2.1.7.

**Comment by snicoll** [comment]
@bvoss auto-configurations and related infrastructure shouldn't be considered public API and are not meant to be consumed by applications. That includes `@ConfigurationProperties` type where the key in the environment is really what you should be considering public API. I agree removing a property in a maintenance release is unusual but we're now completely ignoring it so it felt weird to pretend we were still doing something based on its value. We've moved this key in "deprecation error" rather than a simple deprecation as this issue is about ignoring its value entirely. If you are using other configuration properties type in your codebase, I strongly encourage you to stop doing so.

**Comment by snicoll** [comment]
@Treehopper i don't understand the parity argument. The two support are vastly different. Yes, they have a small amount of properties in common. I don't see the point of exposing a property that does nothing in practice. Anyway, you were the one suggesting to remove the property in this very issue so I guess I must be missing something.

**Comment by Treehopper** [comment]
@snicoll I did suggest to remove it in my initial comment, and don't get me wrong, I absolutely agree that not having a property that does nothing is better than having it, but since it would just take about 10 lines of trivial code to fix it: Why not fix it, avoid unusual maintenance changes, and hence improve the situation for everybody?

Note that I made my initial comment before actually looking into the Spring code, and coming up with the workaround. The "10 lines of code" I'm referring to are the ones from my workaround that actually do something. I need ~40 lines of pretty ugly code more to make it run before the _LiquibaseAutoConfiguration_, and ~80 lines of unit tests. Please take my comment from the 9th of April as the more informed one.
If you are open to reconsider, I'd be happy to contribute the change.

I also agree that there is no perfect symmetry between the Liquibase and Flyway support, but the attempt to introduce some, was a move in the right direction IMO.
The application I'm working on is a core component that needs to support both Liquibase and Flyway. Users of that component can decide themselves whether they want to put Liquibase or Flyway migrations on the classpath. Transparently for us, it just works - via convention, without configuration. Much of Spring works in same spirit. The Liquibase support does not, after this change (or without the fix).

**Comment by bvoss** [comment]
@snicoll Thanks for the advice.
In my case my team provide custom autoconfigurations for some common parts of our company incl Liquibase adjustments. And yes there are more often breaking changes in autoconfigurations and ConfigurationProperties, which I think is normal and expected.
We went very well with this for quit some time.
All I want to point out that this was the first time ( I can remember ), when we hit this kind of breaking change in a patch release.
