### ISSUE TITLE
Server fails to start when using AJP/1.3 protocol due to ClassCastException

### ISSUE THREAD

**Issue by masrawi** [spring-projects/spring-boot#16413]
I start the web application with only ajp connector 
```
@Bean
    public WebServerFactoryCustomizer<TomcatServletWebServerFactory> servletContainerCustomizer()
    {
        return server -> server.setProtocol("AJP/1.3");
    }

```

this results in 2.2.0 M1 in 

```
org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is java.lang.ClassCastException: org.apache.coyote.ajp.AjpNioProtocol cannot be cast to org.apache.coyote.http11.AbstractHttp11Protocol
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:157)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:785)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:407)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)

```

the problem seems to be in org.springframework.boot.autoconfigure.web.embedded.TomcatWebServerFactoryCustomizer

```
    private void customizeProcessorCache(ConfigurableTomcatWebServerFactory factory,
            int processorCache) {
        factory.addConnectorCustomizers((
                connector) -> ((AbstractHttp11Protocol<?>) connector.getProtocolHandler())
                        .setProcessorCache(processorCache));
    }
```

should be

```
    private void customizeProcessorCache(ConfigurableTomcatWebServerFactory factory,
            int processorCache) {
        factory.addConnectorCustomizers((
                connector) -> ((AbstractProtocol<?>) connector.getProtocolHandler())
                        .setProcessorCache(processorCache));
    }
```

**Comment by wilkinsona** [comment]
Thanks for trying out a milestone. This is a regression introduced by the changes in https://github.com/spring-projects/spring-boot/pull/15054.
