### ISSUE TITLE
Spring Boot Gradle Plugin "Duplicate library custom.jar"

### ISSUE THREAD

**Issue by ihr** [spring-projects/spring-boot#1646]
In a multi-project Gradle environment, while using Spring Boot Gradle Plugin for **subprojects**, the plugin throws the following exception:

```
Caused by: java.lang.IllegalStateException: Duplicate library custom.jar
        at org.springframework.boot.loader.tools.Repackager$1.library(Repackager.java:171)
        at org.springframework.boot.gradle.repackage.ProjectLibraries.libraries(ProjectLibraries.java:162)
        at org.springframework.boot.gradle.repackage.ProjectLibraries.doWithLibraries(ProjectLibraries.java:96)
        at org.springframework.boot.loader.tools.Repackager.repackage(Repackager.java:161)
        at org.springframework.boot.loader.tools.Repackager.repackage(Repackager.java:129)
        at org.springframework.boot.gradle.repackage.RepackageTask$RepackageAction.repackage(RepackageTask.java:173)
        at org.springframework.boot.gradle.repackage.RepackageTask$RepackageAction.execute(RepackageTask.java:138)
        at org.springframework.boot.gradle.repackage.RepackageTask$RepackageAction.execute(RepackageTask.java:1)
        at org.gradle.internal.Actions$FilteredAction.execute(Actions.java:203)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:110)
        at org.gradle.api.internal.DefaultDomainObjectCollection.withType(DefaultDomainObjectCollection.java:120)
        at org.springframework.boot.gradle.repackage.RepackageTask.repackage(RepackageTask.java:89)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:579)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:562)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 44 more
```

The custom library is declared for the modules which need it like this:

```
compile file('custom.jar')
```

Any ideas why this might be happening?

**Comment by bbarker** [comment]
I seem to still be having a similar issue in 1.4.0.M2 - I'll see if I can get a test case to reproduce.
