### ISSUE TITLE
Atmosphere Resource Error

### ISSUE THREAD

**Issue by bharukaRupesh** [spring-projects/spring-boot#16468]
Hi,

Can anyone please help me on the below atmosphere issue which came after we bumped up our spring version from ```4.3.7``` to ```5.1.5```?

```Caused by: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalStateException: No primary or default constructor found for interface org.atmosphere.cpr.AtmosphereResource
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1013)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.atmosphere.util.AtmosphereFilterChain.doFilter(AtmosphereFilterChain.java:171)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
```

Any help is really appreciated.

**Comment by snicoll** [comment]
This issue tracker is about Spring Boot, not Spring Framework and an incomplete stack trace with no additional information is not going to attract people to help you. Please take the time to create a StackOverflow question with more details, a sample would be ideal. Side note, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues) and the issue template, we prefer to use GitHub issues only for bugs and enhancements.

**Comment by bharukaRupesh** [comment]
Thanks @snicoll  for your kind response.
