### ISSUE TITLE
Mysql jdbc can not work when time zone is in day light saving time zone(such as CDT)

### ISSUE THREAD

**Issue by songxinqiang** [spring-projects/spring-boot#16570]
I am using spring-boot 2.0.13,and the mysql jdbc driver version is 8.0.15.
When i set the system time zone to US/Central,  CST6CDT,and now it's in day light saving time, I can not connect to server anymore.
I only got the exception:
```
java.sql.SQLException: The server time zone value 'CDT' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:76)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:835)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:136)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:541)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:157)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:115)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:78)
```
And according to that,the appliation can not start anymore.
When I use mysql-connector-java 5.1.47 and set `spring.datasource.driverClassName = com.mysql.jdbc.Driver` it works very well.

So, I think it's a regression, and we should use `mysql:mysql-connector-java:5.1.47` or do something in  Datasource init code to solve the problem.

**Comment by wilkinsona** [comment]
This is probably due to some changes in MySQL 8 related to time zones. For example, support for a number of connection properties was removed in MySQL 8. As the error message recommends, you can use the [`serverTimezone` property](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-configuration-properties.html) to fix the problem.

**Comment by songxinqiang** [comment]
yeah, we should add `&serverTimezone=UTC` in jdbcurl, or `CST6CDT` is also OK.
but the DataSource init code use `CDT` in default when system is in `CST6CDT`,so it's an issue?

**Comment by wilkinsona** [comment]
We don't do anything special and just rely on the defaults of the MySQL JDBC driver. If those defaults don't meet your needs, you should override them in your own configuration.
