### ISSUE TITLE
Spring Boot version 2.0.2.RELEASE and Tomcat version 8.5.39

### ISSUE THREAD

**Issue by saulkarl** [spring-projects/spring-boot#16598]
We were running our code, Spring Boot version 2.0.2.RELEASE and Tomcat version 8.5.30 successfully. When our Tomcat was updated to 8.5.39, we got the following exception when deploying our war:

```
Caused by: java.lang.IllegalStateException: Attribute 'javax.websocket.server.ServerContainer' not found in ServletContext
        at org.springframework.util.Assert.state(Assert.java:73)
        at org.springframework.web.socket.server.standard.ServletServerContainerFactoryBean.afterPropertiesSet(ServletServerContainerFactoryBean.java:117)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1765)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1702)
```

We did try Spring Boot version 2.0.9.RELEASE but the same exception occurred.

The following piece of code causes this exception:

```java
@Configuration
@EnableWebSocket
public class WebSocketConfig implements WebSocketConfigurer {
...
  @Bean
  public ServletServerContainerFactoryBean createWebSocketContainer() {
      ServletServerContainerFactoryBean container = new ServletServerContainerFactoryBean();
      container.setMaxTextMessageBufferSize(1048576);
      return container;
  }
...
}
```

**Comment by wilkinsona** [comment]
Thanks for the report. This is a [known issue](https://github.com/spring-projects/spring-framework/issues/22131) in Spring Framework that is out of Spring Boot's control.
