### ISSUE TITLE
HttpHeaders add method throws null pointer exception when deleting and adding same headers

### ISSUE THREAD

**Issue by Deadpool1111** [spring-projects/spring-boot#16610]
I'm using `Spring-boot 2.1.3`I have an HttpHeaders object with some values

      HttpHeaders headers = new HttpHeaders();
      headers.add("Connection", "keep-alive");

But now if i try to delete and add them again it throws `NullPointerException`

      headers.entrySet().removeIf(k->k.getKey().equals("Connection"));
      headers.add("Connection", "keep-alive");

Error:

       Caused by: java.lang.NullPointerException: null
	at org.springframework.util.CollectionUtils$MultiValueMapAdapter.add(CollectionUtils.java:460) ~[spring-core-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.http.HttpHeaders.add(HttpHeaders.java:1559) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at com.demo.DemoMain.run(DemoMain.java:27) ~[main/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:813) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	... 5 common frames omitted

**Comment by philwebb** [comment]
Thanks. This looks like a bug in `LinkedCaseInsensitiveMap`:

```java
@Override
@Nullable
public V computeIfAbsent(String key, Function<? super String, ? extends V> mappingFunction) {
	String oldKey = this.caseInsensitiveKeys.putIfAbsent(convertKey(key), key);
	if (oldKey != null) {
		return this.targetMap.get(oldKey);
	}
	return this.targetMap.computeIfAbsent(key, mappingFunction);
}
```

The `oldKey` variable is not null but the target map doesn't contain the value. I guess we either need to track removals done via `entrySet` or that method should change.
