### ISSUE TITLE
Rework RestartConfiguration's EventListener to avoid an exception being logged at debug level

### ISSUE THREAD

**Issue by diykorey** [spring-projects/spring-boot#16631]
version 2.2.0.M2  provokes error in logs on debug level(see below) Issue doesn't affect app too much I can run project  and seems everything work more or less ok (didnt test deeply). Issue appears only on 2.2.0.M2 with spring-boot-devtools dependency

```
2019-04-24 10:23:15.193 [restartedMain] DEBUG  [DeferredLog.java:224] - Starting application com....Application with URLs [file:/..../target/classes/] - org.springframework.boot.devtools.restart.Restarter
2019-04-24 10:23:15.193 [restartedMain] DEBUG  [SimpleApplicationEventMulticaster.java:181] - Non-matching event type for listener: org.springframework.boot.devtools.autoconfigure.LocalDevToolsAutoConfiguration$RestartConfiguration$$Lambda$582/0x00000008005ef440@110461c - org.springframework.context.event.SimpleApplicationEventMulticaster
java.lang.ClassCastException: class org.springframework.boot.context.event.ApplicationReadyEvent cannot be cast to class org.springframework.boot.devtools.classpath.ClassPathChangedEvent (org.springframework.boot.context.event.ApplicationReadyEvent and org.springframework.boot.devtools.classpath.ClassPathChangedEvent are in unnamed module of loader 'app')
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359)
	at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:105)
	at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:78)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1275)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1263)
	at com.....Application.main(Application.java:12)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
```

**Comment by wilkinsona** [comment]
The exception is benign, hence it being logged at debug level. The logging is [performed by Spring Framework](https://github.com/spring-projects/spring-framework/blob/29d021ae3ce11dacd0793f08524651a23468a06d/spring-context/src/main/java/org/springframework/context/event/SimpleApplicationEventMulticaster.java#L175-L182) when it encounters a lambda-defined listener for which it could not determine the generic type. We can consider switching to an inner-class for the listener declaration. Generally speaking, you should not expect your logs to be free from exceptions when you enable debug level logging.

**Comment by diykorey** [comment]
> The exception is benign, hence it being logged at debug level. The logging is [performed by Spring Framework](https://github.com/spring-projects/spring-framework/blob/29d021ae3ce11dacd0793f08524651a23468a06d/spring-context/src/main/java/org/springframework/context/event/SimpleApplicationEventMulticaster.java#L175-L182) when it encounters a lambda-defined listener for which it could not determine the generic type. We can consider switching to an inner-class for the listener declaration. Generally speaking, you should not expect your logs to be free from exceptions when you enable debug level logging.

Sure I understand, issue created mostly to let team know about that exception. I think nobody should ignore stacktrace in logs

**Comment by philwebb** [comment]
> I think nobody should ignore stacktrace in logs

This logging should only appear if you've explicitly configured `org.springframework` to `DEBUG` level. They don't appear in typical scenarios, and I don't think we should move away from lambdas just to prevent them.

I've raised https://github.com/spring-projects/spring-framework/issues/22834 to see if framework will consider trace level logging instead.

**Comment by philwebb** [comment]
https://github.com/spring-projects/spring-framework/issues/22834 has been fixed
