### ISSUE TITLE
JsonPatch and JsonUnwrapped property: PropertyReferenceException when patching fields in unwrapped path

### ISSUE THREAD

**Issue by genglefr** [spring-projects/spring-boot#16652]
### 2.2.0 M2
I'm using Spring Boot 2.2.0 M2, and I'm building an application on top of Spring Data Rest.
I'm experiencing an issue when using JSON Patch `Content-Type = application/json-patch+json` in combination with `@JsonUnwrapped` properties.

Let's consider I have a Person entity, with a `@JsonUnwrapped` data property that holds a String name field.
I'd like to patch this entity via:

```
curl -X PATCH--data '[{"op":"replace", "path":"/name", "value":"test patch"}]' -H "Content-Type:application/json-patch+json" http://localhost:8080/person/1
```

Unfortunately, this raises an exception:
```
Caused by: org.springframework.data.mapping.PropertyReferenceException: No property name found for type Person!
	at org.springframework.data.mapping.PropertyPath.<init>(PropertyPath.java:94) ~[spring-data-commons-2.2.0.M3.jar:2.2.0.M3]
	at org.springframework.data.mapping.PropertyPath.create(PropertyPath.java:382) ~[spring-data-commons-2.2.0.M3.jar:2.2.0.M3]
	at org.springframework.data.mapping.PropertyPath.create(PropertyPath.java:358) ~[spring-data-commons-2.2.0.M3.jar:2.2.0.M3]
	at org.springframework.data.mapping.PropertyPath.lambda$from$0(PropertyPath.java:311) ~[spring-data-commons-2.2.0.M3.jar:2.2.0.M3]
	at java.base/java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:330) ~[na:na]
	at org.springframework.data.mapping.PropertyPath.from(PropertyPath.java:293) ~[spring-data-commons-2.2.0.M3.jar:2.2.0.M3]
	at org.springframework.data.mapping.PropertyPath.from(PropertyPath.java:276) ~[spring-data-commons-2.2.0.M3.jar:2.2.0.M3]
```
Instead, if I specify my `@JsonUnwrapped` property in the path of the patch request, it works like a charm:
```
curl -X PATCH--data '[{"op":"replace", "path":"/data/name", "value":"test patch"}]' -H "Content-Type:application/json-patch+json" http://localhost:8080/person/1
```
According to me, `@JsonUnwrapped` properties should not be considered when evaluating paths of patch requests.

**Comment by wilkinsona** [comment]
Thanks for the report, but, based on the information provided, I don't think this is a problem with Spring Boot itself. Spring Data REST is managed as a separate project which uses [JIRA](https://jira.spring.io/browse/DATAREST) for issue tracking. If you would like to pursue this, please open a Spring Data REST issue and comment here with a link to it.

**Comment by genglefr** [comment]
Ok got it.
For the follow-up:
https://jira.spring.io/browse/DATAREST-1369
