### ISSUE TITLE
Disable @ConfigurationProperties scan in slice tests

### ISSUE THREAD

**Issue by ebussieres** [spring-projects/spring-boot#16659]
I've found a regression with version 2.2.0.M2.

I have a dao test which is using @DataJpaTest annotation that looks like this : 
```
@DataJpaTest
@RunWith(SpringRunner.class)
@Sql(executionPhase = BEFORE_TEST_METHOD, scripts = "classpath:beforeTestDaoITest.sql")
@Sql(executionPhase = AFTER_TEST_METHOD, scripts = "classpath:afterTestDaoITest.sql")
public class TestDaoITest {
  @Autowired
  private TestDao underTest;

  @Test
  public void whenFindOne_givenExistingId_thenId() {
    Optional<TestEntity> result = this.underTest.findById(1L);

    assertEquals(result.get().id, (Long) 1L);
  }
}
```

In the project, I have a configuration class which use @ConfigurationProperties and it looks like this: 

```
@Configuration
@ConfigurationProperties(prefix = "monitoring")
public class Config {
  private Long id;

  @Bean
  public HealthIndicator healthIndicator(HealthAggregator healthAggregator) {
    HealthIndicatorRegistry healthIndicatorRegistry = new DefaultHealthIndicatorRegistry();
    return new CompositeHealthIndicator(healthAggregator, healthIndicatorRegistry);
  }

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }
}
```

With version 2.1.4.RELEASE, everything works fine. Because it's a DataJpaTest, the Config isn't scanned and the test passes.

With version 2.2.0.M2, the config class is scanned and an error occured in the test because no HealthAggregator bean exists. I think that the reason comes from @ConfigurationProperties, When I remove the @ConfigurationProperties annotation, the config class isn't scanned anymore

I have a working example here that reproduce the problem : https://github.com/ebussieres/spring-boot-2.2-issue

**Comment by wilkinsona** [comment]
Thanks for the sample and for trying out a 2.2 milestone. The problem's an interesting side-effect of  the new configuration property scanning support.

It's [recommended](https://docs.spring.io/spring-boot/docs/2.1.4.RELEASE/reference/htmlsingle/#boot-features-external-config-vs-value) that classes annotated with `@ConfigurationProperties` are POJOs and don't provide any other functionality. They shouldn't also be a `@Configuration` class or a `@RestController` for example. Your code doesn't follow this recommendation which is why the failure's occurring.

I don't think it'll be possible to make configuration property scanning aware of test slices as there's no obvious way of knowing which `@ConfigurationProperties` classes are needed in a particular slice of the application. Let's see if there's anything else we can do.

**Comment by ebussieres** [comment]
I'll check to change our configuration classes for now, I was not aware of that recommendation.

**Comment by wilkinsona** [comment]
@snicoll pointed out that in 2.1 without `@ConfigurationPropertiesScan` no `@ConfigurationProperties` beans will be created until they enabled via `@EnableConfigurationProperties` on the main class. If we don't do any configuration property scanning when running a slice test, we will restore the same behaviour as we have in 2.1.

**Comment by wilkinsona** [comment]
@mbhave has pointed out that we overlooked the scenario where `@EnableConfigurationProperties` was on the main class in 2.1 and was then removed in favour of scanning in 2.2. In this case, the current behaviour of configuration property scanning matches 2.1 and disabling it would create a problem.

**Comment by snicoll** [comment]
> In this case, the current behaviour of configuration property scanning matches 2.1 and disabling it would create a problem.

I might be missing something but I don't see this as a problem. For that to happen, the user has to change something in their code (rely on classpath scanning vs. regular registration). If they do that, it is fair game IMO that the `@ConfigurationProperties` bean goes away. If they don't change anything, tests will work as before.

I know the analogy is not 100% correct but if you move a `@Bean` method on the main class to `@Component` on the target object, it will go away too. If you need to get those `@ConfigurationProperties` bean, you need a way to indicate them and, at the moment, I don't think there is a good use case for scanning them in a slice tests.

**Comment by wilkinsona** [comment]
> If they do that, it is fair game IMO that the @ConfigurationProperties bean goes away

My concern is that in undermines the benefit of moving to configuration property scanning by, potentially, making test slices harder to use. Getting rid of one `@EnableConfiguraionProperties` annotation in your main code only to have to add it to your test code seems like a bit of a mixed bag. On the plus side, it does provide a bit more control.

**Comment by snicoll** [comment]
> making test slices harder to use. 

How is that any different from having to mock a bean that the component you want to test needs exactly? Slice tests run with a reduced classpath so I really don't see why we should consider `@ConfigurationProperties` type.

**Comment by wilkinsona** [comment]
It's different purely because it's something that you didn't have to do before. For that reason, I think it detracts a little bit from the benefits of moving to configuration property scanning.

**Comment by wilkinsona** [comment]
We're going to investigate meta-annotating `@ConfigurationProperties` with `@Component` so that they are picked up by usual component scanning (we need to figure out how to customise the bean name). In the meantime, we think it makes sense for scanning of `@ConfigurationProperties` beans to be disabled for slice tests in the same way that they would be if they were `@Component`s.

**Comment by bclozel** [comment]
I think the build is currently failing because of this enhancement.

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of constructor in sample.test.service.RemoteVehicleDetailsService required a bean of type 'sample.test.service.ServiceProperties' that could not be found.


Action:

Consider defining a bean of type 'sample.test.service.ServiceProperties' in your configuration.

2019-05-10 22:32:52.629 ERROR 5583 --- [           main] o.s.test.context.TestContextManager      : Caught exception while allowing TestExecutionListener [org.springframework.boot.test.autoconfigure.SpringBootDependencyInjectionTestExecutionListener@5acf93bb] to prepare test instance [sample.test.service.RemoteVehicleDetailsServiceTests@12ffd1de]

java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:132) ~[spring-test-5.2.0.M2.jar:5.2.0.M2]
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:122) ~[spring-test-5.2.0.M2.jar:5.2.0.M2]
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:118) ~[spring-test-5.2.0.M2.jar:5.2.0.M2]
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83) ~[spring-test-5.2.0.M2.jar:5.2.0.M2]
	at org.springframework.boot.test.autoconfigure.SpringBootDependencyInjectionTestExecutionListener.prepareTestInstance(SpringBootDependencyInjectionTestExecutionListener.java:44) ~[spring-boot-test-autoconfigure-2.2.0.BUILD-SNAPSHOT.jar:2.2.0.BUILD-SNAPSHOT]
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:244) ~[spring-test-5.2.0.M2.jar:5.2.0.M2]
	at org.springframework.test.context.junit.jupiter.SpringExtension.postProcessTestInstance(SpringExtension.java:98) [spring-test-5.2.0.M2.jar:5.2.0.M2]
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$invokeTestInstancePostProcessors$6(ClassTestDescriptor.java:352) [junit-jupiter-engine-5.4.2.jar:5.4.2]
	at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.executeAndMaskThrowable(JupiterTestDescriptor.java:204) ~[junit-jupiter-engine-5.4.2.jar:5.4.2]
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$invokeTestInstancePostProcessors$7(ClassTestDescriptor.java:352) [junit-jupiter-engine-5.4.2.jar:5.4.2]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_202]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_202]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[na:1.8.0_202]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_202]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_202]
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312) ~[na:1.8.0_202]
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743) ~[na:1.8.0_202]
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742) ~[na:1.8.0_202]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[na:1.8.0_202]
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.invokeTestInstancePostProcessors(ClassTestDescriptor.java:351) [junit-jupiter-engine-5.4.2.jar:5.4.2]
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateAndPostProcessTestInstance(ClassTestDescriptor.java:270) [junit-jupiter-engine-5.4.2.jar:5.4.2]
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$testInstancesProvider$2(ClassTestDescriptor.java:259) [junit-jupiter-engine-5.4.2.jar:5.4.2]
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$testInstancesProvider$3(ClassTestDescriptor.java:263) [junit-jupiter-engine-5.4.2.jar:5.4.2]
	at java.util.Optional.orElseGet(Optional.java:267) ~[na:1.8.0_202]
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$testInstancesProvider$4(ClassTestDescriptor.java:262) [junit-jupiter-engine-5.4.2.jar:5.4.2]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:98) ~[junit-jupiter-engine-5.4.2.jar:5.4.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:97) ~[junit-jupiter-engine-5.4.2.jar:5.4.2]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:68) ~[junit-jupiter-engine-5.4.2.jar:5.4.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$1(NodeTestTask.java:107) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:107) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:75) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_202]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_202]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220) ~[junit-platform-launcher-1.3.1.jar:1.3.1]
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188) ~[junit-platform-launcher-1.3.1.jar:1.3.1]
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202) ~[junit-platform-launcher-1.3.1.jar:1.3.1]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181) ~[junit-platform-launcher-1.3.1.jar:1.3.1]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128) ~[junit-platform-launcher-1.3.1.jar:1.3.1]
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150) ~[surefire-junit-platform-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124) ~[surefire-junit-platform-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384) ~[surefire-booter-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345) ~[surefire-booter-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126) ~[surefire-booter-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418) ~[surefire-booter-2.22.2.jar:2.22.2]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'remoteVehicleDetailsService' defined in file [/tmp/build/fd4135ff/git-repo/spring-boot-samples/spring-boot-sample-test/target/classes/sample/test/service/RemoteVehicleDetailsService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'sample.test.service.ServiceProperties' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:780) ~[spring-beans-5.2.0.M2.jar:5.2.0.M2]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:219) ~[spring-beans-5.2.0.M2.jar:5.2.0.M2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1345) ~[spring-beans-5.2.0.M2.jar:5.2.0.M2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1191) ~[spring-beans-5.2.0.M2.jar:5.2.0.M2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-5.2.0.M2.jar:5.2.0.M2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.2.0.M2.jar:5.2.0.M2]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.2.0.M2.jar:5.2.0.M2]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.0.M2.jar:5.2.0.M2]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.2.0.M2.jar:5.2.0.M2]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.2.0.M2.jar:5.2.0.M2]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:868) ~[spring-beans-5.2.0.M2.jar:5.2.0.M2]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877) ~[spring-context-5.2.0.M2.jar:5.2.0.M2]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.2.0.M2.jar:5.2.0.M2]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:782) ~[spring-boot-2.2.0.BUILD-SNAPSHOT.jar:2.2.0.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:404) ~[spring-boot-2.2.0.BUILD-SNAPSHOT.jar:2.2.0.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:319) ~[spring-boot-2.2.0.BUILD-SNAPSHOT.jar:2.2.0.BUILD-SNAPSHOT]
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:132) ~[spring-boot-test-2.2.0.BUILD-SNAPSHOT.jar:2.2.0.BUILD-SNAPSHOT]
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99) ~[spring-test-5.2.0.M2.jar:5.2.0.M2]
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124) ~[spring-test-5.2.0.M2.jar:5.2.0.M2]
	... 66 common frames omitted
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'sample.test.service.ServiceProperties' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1681) ~[spring-beans-5.2.0.M2.jar:5.2.0.M2]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1239) ~[spring-beans-5.2.0.M2.jar:5.2.0.M2]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1193) ~[spring-beans-5.2.0.M2.jar:5.2.0.M2]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:868) ~[spring-beans-5.2.0.M2.jar:5.2.0.M2]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:771) ~[spring-beans-5.2.0.M2.jar:5.2.0.M2]
	... 84 common frames omitted
```

In our samples, we're declaring a config properties class as a component with `@RestClientTest`. See https://github.com/spring-projects/spring-boot/blob/3b4ff7d74641bd453554df22bc4eaa55da4522d4/spring-boot-samples/spring-boot-sample-test/src/test/java/sample/test/service/RemoteVehicleDetailsServiceTests.java#L43

Changing that to the following fixes the test:
```
@RestClientTest(RemoteVehicleDetailsService.class)
@EnableConfigurationProperties(ServiceProperties.class)
class RemoteVehicleDetailsServiceTests {
```

Wondering if this is an intended consequence or if we want to revisit this issue.

**Comment by mbhave** [comment]
Thanks @bclozel. I don't think I considered this case where `@ConfigurationProperties` that were previously marked with `@Component` were included in the slice test by explicitly adding them as an include in the `TypeExcludeFilter`. 

[This commit](https://github.com/spring-projects/spring-boot/commit/3b4ff7d74641bd453554df22bc4eaa55da4522d4) disables `@ConfigurationPropertiesScan` completely. Instead we may need to do something similar to the `@ComponentScan` filters. I'll revert the commit so that it doesn't block the build.

**Comment by snicoll** [comment]
> Instead we may need to do something similar to the @ComponentScan filter

I am not sure we need that. From my perspective, `@Import(MyProperties.class)` should "just work". That isn't related to component scan, is it? The example above goes in the same direction where classes are listed explicitly and handling of config props (env binding) should be enabled when defining such class explicitly.

**Comment by snicoll** [comment]
We should probably move this in its own issue at some point but we've discussed the possibility to remove our custom component scan code to rely on the standard behaviour of the framework with some extra tuning. I've opened https://github.com/spring-projects/spring-framework/issues/22995 to see what the framework team thinks about the use case and we'll follow-up here accordingly.

**Comment by snicoll** [comment]
Discussing with @jhoeller there are basically two options on the table (with different variants):

1. Open up the core container so that we can merge our custom `@ConfigurationPropertiesScan` with `@ComponentScan`
2. Fix our `@ConfigurationPropertiesScan` so that it is aware of slice test and does the right thing

We've spent some time discussing the first option as it looks the best outcome to me, avoiding an extra package scan and making sure things are harmonized in a single place. One option we considered was to include an `include` filter on [our `@ComponentScan`](https://github.com/spring-projects/spring-boot/blob/73cd1c9c772a4618c64160f6df24b96c74f51d9d/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/SpringBootApplication.java#L56-L57) to make sure `@ConfigurationProperties` type are included and then offer an extra hookpoint on the context to register a special callback.

The purpose of that callback would be to be able to tune/change a `BeanDefinition` for every component that matches scanning. This would be an opportunity for us to inject our special handling for constructor-based binding. Looking at the current hierarchy, we'd need to add something at the level of `AnnotationConfigRegistry ` as we need to do it for contexts that are aware of scanning. Component scan processing is quite specifically isolated at the moment so it would be a challenge to open it up for that use case.

The other option is to fix what we have to include the same `TypeExcludeFilter` so that it is applied there. I will now spike on that idea and see if that fixes the problem exposed here. This would resule in two invocations of the filter but our custom component scan also does that at the moment. If this solution works, we can see if there is a way to mitage that.

**Comment by snicoll** [comment]
So there are a few things that moved since this issue got created. First, we have now the following report when trying to build this project with `2.2.0.M4`:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

com.example.demo.Config is annotated with @ConfigurationProperties and @Configuration. This may cause the @ConfigurationProperties bean to be registered twice.

Action:

Remove @Configuration from com.example.demo.Config or consider disabling automatic @ConfigurationProperties scanning.
```

I think this will mitigate the problem exposed here. However it remains the problem of legit `@ConfigurationProperties` to be scanned in slice tests. 

Registering `TypeExcludeFilter` when we scan for them leads for them to be excluded. If we ever decided that a slice should include them, then it's easy enough to update the filter to do so. The project builds cleanly. The same apply with `RemoteVehicleDetailsServiceTests` (explicit import) even with construct-based binidng. That last bit is a bit of mystery at this point so I need to investigate further.
