### ISSUE TITLE
Unable to start embedded container when Unicode characters are in the java.io.tmpdir path

### ISSUE THREAD

**Issue by devrobertpalmer** [spring-projects/spring-boot#16692]
**Affects:** 
spring framework: '4.3.22.RELEASE',
spring boot: '1.5.19.RELEASE'

We are trying to allow our customers to have non-ASCII characters in their paths for TEMP and TMP on Windows.  When we encode the path with UTF-16 we get the replacement character inside the JVM (? in this case instead of 马).  If we encode the TEMP and TMP locations with UTF-8 we get the following exception:

```
org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to create tempDir. java.io.tmpdir is set to d:\\dev\\near\\马马\\prep
at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:139)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537)
at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:124)
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
at com.tableau.loom.rest.spring.LoomSpringApp.main(LoomSpringApp.java:74)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)\r
Caused by: org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to create tempDir. java.io.tmpdir is set to d:\\dev\\near\\马马\\prep
at org.springframework.boot.context.embedded.AbstractEmbeddedServletContainerFactory.createTempDir(AbstractEmbeddedServletContainerFactory.java:285)
at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.getEmbeddedServletContainer(TomcatEmbeddedServletContainerFactory.java:167)
at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:166)
at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:136)
... 14 more
Caused by: java.io.IOException: The system cannot find the path specified
at java.io.WinNTFileSystem.createFileExclusively(Native Method)
at java.io.File.createTempFile(File.java:2024)
at java.io.File.createTempFile(File.java:2070)
at org.springframework.boot.context.embedded.AbstractEmbeddedServletContainerFactory.createTempDir(AbstractEmbeddedServletContainerFactory.java:276)
... 17 more
```

The directory exists and the run-as user has rwx permissions to the directory.

**Comment by wilkinsona** [comment]
Thanks for the report, but I don't think there's anything we can do about this in Spring Boot. As shown in the stack trace, Spring Boot calls `java.io.File.createTempFile(String, String)`. The JVM uses the value of `java.io.tmpdir` which, apparently, is causing a failure. If you can provide a sample that shows temp file creation working without Spring Boot and failing with it then we can re-open this issue and take another look. Otherwise, this appears to be a limitation of Windows or the JVM that you are using.
