### ISSUE TITLE
Reactive List Operations LeftPop with Duration.ZERO timeout exception

### ISSUE THREAD

**Issue by Guillaume-Mayer** [spring-projects/spring-boot#16711]
When I use leftPop with Duration.ZERO (ReactiveListOperations), I expect it to wait indefinitely.
But it throws a timeout exception after 1 minute which seems to be a default timeout.

Spring Boot 2.1.4 with default settings (Lettuce Core 5.1.6.RELEASE).
Redis 5.0.4

Trace:

```
[ERROR][19-05-03 12:39:51.389][ce-eventExecutorLoop-1-3][             c.c.s.c.SmartRedis4Consumer][] > Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 minute(s)
org.springframework.dao.QueryTimeoutException: Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 minute(s)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:70) ~[spring-data-redis-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41) ~[spring-data-redis-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceReactiveRedisConnection.lambda$translateException$1(LettuceReactiveRedisConnection.java:283) ~[spring-data-redis-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at reactor.core.publisher.Flux.lambda$onErrorMap$24(Flux.java:6186) ~[reactor-core-3.2.8.RELEASE.jar!/:3.2.8.RELEASE]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88) ~[reactor-core-3.2.8.RELEASE.jar!/:3.2.8.RELEASE]
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onError(MonoFlatMapMany.java:243) ~[reactor-core-3.2.8.RELEASE.jar!/:3.2.8.RELEASE]
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126) ~[reactor-core-3.2.8.RELEASE.jar!/:3.2.8.RELEASE]
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126) ~[reactor-core-3.2.8.RELEASE.jar!/:3.2.8.RELEASE]
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126) ~[reactor-core-3.2.8.RELEASE.jar!/:3.2.8.RELEASE]
	at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:87) ~[reactor-core-3.2.8.RELEASE.jar!/:3.2.8.RELEASE]
	at io.lettuce.core.RedisPublisher$ImmediateSubscriber.onError(RedisPublisher.java:905) ~[lettuce-core-5.1.6.RELEASE.jar!/:?]
	at io.lettuce.core.RedisPublisher$State.onError(RedisPublisher.java:703) ~[lettuce-core-5.1.6.RELEASE.jar!/:?]
	at io.lettuce.core.RedisPublisher$RedisSubscription.onError(RedisPublisher.java:349) ~[lettuce-core-5.1.6.RELEASE.jar!/:?]
	at io.lettuce.core.RedisPublisher$SubscriptionCommand.onError(RedisPublisher.java:815) ~[lettuce-core-5.1.6.RELEASE.jar!/:?]
	at io.lettuce.core.RedisPublisher$SubscriptionCommand.completeExceptionally(RedisPublisher.java:809) ~[lettuce-core-5.1.6.RELEASE.jar!/:?]
	at io.lettuce.core.protocol.CommandExpiryWriter.lambda$potentiallyExpire$0(CommandExpiryWriter.java:167) ~[lettuce-core-5.1.6.RELEASE.jar!/:?]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) ~[netty-common-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127) ~[netty-common-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66) ~[netty-common-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[netty-common-4.1.34.Final.jar!/:4.1.34.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.34.Final.jar!/:4.1.34.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
Caused by: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 minute(s)
	at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51) ~[lettuce-core-5.1.6.RELEASE.jar!/:?]
	... 7 more
```

**Comment by wilkinsona** [comment]
Thanks for the report, but this looks like a problem with Spring Data Redis or, perhaps, Lettuce to me. Both are managed as separate projects. Spring Data Redis's issues are managed on JIRA and Lettuce's are managed on GitHub. If you open a Spring Data Redis (or Lettuce) issue, please comment here with a link to it so that anyone who is interested can follow along.

**Comment by Guillaume-Mayer** [comment]
Ok sorry, I'll try that
