### ISSUE TITLE
Deadlock between BackgroundPreinitializer and main thread in Spring Cloud Config Server

### ISSUE THREAD

**Issue by stefanocke** [spring-projects/spring-boot#16744]
Spring Boot Version: 2.1.4.RELEASE
Spring Cloud Version: Greenwich.SR1

(Despite the title, this is probably not a Spring Cloud issue.)

- We have a (quite bare) Spring Cloud Config Server running on embedded tomcat. 
- Since yesterday we get a deadlock (see thread dump below). Not always, but many times.
- So far, it only happended for our Config Server, not for other services.
- So far, we only observed it for a Docker / Kubernetes deployment of the Config Server.
- We use azul/zulu-openjdk-alpine:11 as base image

```
Full thread dump OpenJDK 64-Bit Server VM (11.0.3+7-LTS mixed mode):

...

Found one Java-level deadlock:
=============================
"main":
  waiting to lock monitor 0x0000562c189eb600 (object 0x00000000f743c0f0, a [I),
  which is held by "background-preinit"
"background-preinit":
  waiting to lock monitor 0x0000562c189ee700 (object 0x00000000f6cc4c38, a java.util.jar.JarFile),
  which is held by "main"

Java stack information for the threads listed above:
===================================================
"main":
        at jdk.internal.logger.LoggerFinderLoader.service(java.base@11.0.3/LoggerFinderLoader.java:72)
        - waiting to lock <0x00000000f743c0f0> (a [I)
        at jdk.internal.logger.LoggerFinderLoader.getLoggerFinder(java.base@11.0.3/LoggerFinderLoader.java:206)
        at java.lang.System$LoggerFinder.lambda$accessProvider$0(java.base@11.0.3/System.java:1605)
        at java.lang.System$LoggerFinder$$Lambda$224/0x0000000100331840.run(java.base@11.0.3/Unknown Source)
        at java.security.AccessController.doPrivileged(java.base@11.0.3/Native Method)
        at java.security.AccessController.doPrivileged(java.base@11.0.3/AccessController.java:429)
        at java.lang.System$LoggerFinder.accessProvider(java.base@11.0.3/System.java:1606)
        at java.lang.System$LoggerFinder.getLoggerFinder(java.base@11.0.3/System.java:1594)
        at jdk.internal.logger.LazyLoggers.accessLoggerFinder(java.base@11.0.3/LazyLoggers.java:339)
        at jdk.internal.logger.LazyLoggers.getLoggerFromFinder(java.base@11.0.3/LazyLoggers.java:389)
        at jdk.internal.logger.LazyLoggers.getLazyLogger(java.base@11.0.3/LazyLoggers.java:444)
        at jdk.internal.logger.LazyLoggers.getLogger(java.base@11.0.3/LazyLoggers.java:414)
        at java.lang.System.getLogger(java.base@11.0.3/System.java:1656)
        at jdk.internal.event.EventHelper.<clinit>(java.base@11.0.3/EventHelper.java:45)
        at sun.security.provider.X509Factory.commitEvent(java.base@11.0.3/X509Factory.java:772)
        at sun.security.provider.X509Factory.engineGenerateCertificate(java.base@11.0.3/X509Factory.java:108)
        at java.security.cert.CertificateFactory.generateCertificate(java.base@11.0.3/CertificateFactory.java:355)
        at sun.security.pkcs.PKCS7.parseSignedData(java.base@11.0.3/PKCS7.java:328)
        at sun.security.pkcs.PKCS7.parse(java.base@11.0.3/PKCS7.java:186)
        at sun.security.pkcs.PKCS7.parse(java.base@11.0.3/PKCS7.java:154)
        at sun.security.pkcs.PKCS7.<init>(java.base@11.0.3/PKCS7.java:136)
        at sun.security.util.SignatureFileVerifier.<init>(java.base@11.0.3/SignatureFileVerifier.java:127)
        at java.util.jar.JarVerifier.processEntry(java.base@11.0.3/JarVerifier.java:297)
        at java.util.jar.JarVerifier.update(java.base@11.0.3/JarVerifier.java:230)
        at java.util.jar.JarFile.initializeVerifier(java.base@11.0.3/JarFile.java:757)
        at java.util.jar.JarFile.ensureInitialization(java.base@11.0.3/JarFile.java:1034)
        - locked <0x00000000f6cc4c38> (a java.util.jar.JarFile)
        at java.util.jar.JavaUtilJarAccessImpl.ensureInitialization(java.base@11.0.3/JavaUtilJarAccessImpl.java:69)
        at jdk.internal.loader.URLClassPath$JarLoader$2.getManifest(java.base@11.0.3/URLClassPath.java:870)
        at jdk.internal.loader.BuiltinClassLoader.defineClass(java.base@11.0.3/BuiltinClassLoader.java:788)
        at jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(java.base@11.0.3/BuiltinClassLoader.java:700)
        at jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(java.base@11.0.3/BuiltinClassLoader.java:623)
        - locked <0x00000000f743c9e0> (a java.lang.Object)
        at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@11.0.3/BuiltinClassLoader.java:581)
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.base@11.0.3/ClassLoaders.java:178)
        at java.lang.ClassLoader.loadClass(java.base@11.0.3/ClassLoader.java:521)
        at org.springframework.boot.autoconfigure.condition.FilteringSpringBootCondition$ClassNameFilter.forName(FilteringSpringBootCondition.java:140)
        at org.springframework.boot.autoconfigure.condition.FilteringSpringBootCondition$ClassNameFilter.isPresent(FilteringSpringBootCondition.java:129)
        at org.springframework.boot.autoconfigure.condition.FilteringSpringBootCondition$ClassNameFilter$2.matches(FilteringSpringBootCondition.java:117)
        at org.springframework.boot.autoconfigure.condition.FilteringSpringBootCondition.filter(FilteringSpringBootCondition.java:95)
        at org.springframework.boot.autoconfigure.condition.OnClassCondition.getMatchOutcome(OnClassCondition.java:86)
        at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47)
        at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108)
        at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:218)
        at org.springframework.context.annotation.ConfigurationClassParser.processMemberClasses(ConfigurationClassParser.java:361)
        at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:263)
        at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:242)
        at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:589)
        at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:302)
        at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:242)
        at org.springframework.context.annotation.ConfigurationClassParser.processMemberClasses(ConfigurationClassParser.java:361)
        at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:263)
        at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:242)
        at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:589)
        at org.springframework.context.annotation.ConfigurationClassParser.access$900(ConfigurationClassParser.java:108)
        at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGroupingHandler.lambda$processGroupImports$1(ConfigurationClassParser.java:808)
        at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGroupingHandler$$Lambda$221/0x0000000100333c40.accept(Unknown Source)
        at java.util.ArrayList.forEach(java.base@11.0.3/ArrayList.java:1540)
        at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGroupingHandler.processGroupImports(ConfigurationClassParser.java:804)
        at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorHandler.process(ConfigurationClassParser.java:774)
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:185)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:315)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:232)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:95)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:705)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531)
        - locked <0x00000000f735f4a0> (a java.lang.Object)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139)
        - locked <0x00000000f71270f8> (a java.util.concurrent.atomic.AtomicBoolean)
        at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:203)
        at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:114)
        at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:71)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:75)
        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:347)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139)
        - locked <0x00000000f6e7a5e0> (a java.util.concurrent.atomic.AtomicBoolean)
        at com.example.ConfigserverApplication.main(ConfigserverApplication.java:35)
"background-preinit":
        at java.util.zip.ZipFile.getEntry(java.base@11.0.3/ZipFile.java:346)
        - waiting to lock <0x00000000f6cc4c38> (a java.util.jar.JarFile)
        at java.util.zip.ZipFile$1.getEntry(java.base@11.0.3/ZipFile.java:1121)
        at java.util.jar.JarFile.getEntry0(java.base@11.0.3/JarFile.java:576)
        at java.util.jar.JarFile.getEntry(java.base@11.0.3/JarFile.java:506)
        at java.util.jar.JarFile.getJarEntry(java.base@11.0.3/JarFile.java:468)
        at jdk.internal.loader.URLClassPath$JarLoader.getResource(java.base@11.0.3/URLClassPath.java:929)
        at jdk.internal.loader.URLClassPath$JarLoader.findResource(java.base@11.0.3/URLClassPath.java:912)
        at jdk.internal.loader.URLClassPath$1.next(java.base@11.0.3/URLClassPath.java:341)
        at jdk.internal.loader.URLClassPath$1.hasMoreElements(java.base@11.0.3/URLClassPath.java:351)
        at jdk.internal.loader.BuiltinClassLoader$1.hasNext(java.base@11.0.3/BuiltinClassLoader.java:357)
        at jdk.internal.loader.BuiltinClassLoader$1.hasMoreElements(java.base@11.0.3/BuiltinClassLoader.java:365)
        at java.lang.CompoundEnumeration.next(java.base@11.0.3/ClassLoader.java:3022)
        at java.lang.CompoundEnumeration.hasMoreElements(java.base@11.0.3/ClassLoader.java:3031)
        at java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(java.base@11.0.3/ServiceLoader.java:1202)
        at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(java.base@11.0.3/ServiceLoader.java:1220)
        at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(java.base@11.0.3/ServiceLoader.java:1264)
        at java.util.ServiceLoader$2.hasNext(java.base@11.0.3/ServiceLoader.java:1299)
        at java.util.ServiceLoader$3.hasNext(java.base@11.0.3/ServiceLoader.java:1384)
        at jdk.internal.logger.LoggerFinderLoader.loadLoggerFinder(java.base@11.0.3/LoggerFinderLoader.java:127)
        at jdk.internal.logger.LoggerFinderLoader.service(java.base@11.0.3/LoggerFinderLoader.java:73)
        - locked <0x00000000f743c0f0> (a [I)
        at jdk.internal.logger.LoggerFinderLoader.getLoggerFinder(java.base@11.0.3/LoggerFinderLoader.java:206)
        at java.lang.System$LoggerFinder.lambda$accessProvider$0(java.base@11.0.3/System.java:1605)
        at java.lang.System$LoggerFinder$$Lambda$224/0x0000000100331840.run(java.base@11.0.3/Unknown Source)
        at java.security.AccessController.doPrivileged(java.base@11.0.3/Native Method)
        at java.security.AccessController.doPrivileged(java.base@11.0.3/AccessController.java:429)
        at java.lang.System$LoggerFinder.accessProvider(java.base@11.0.3/System.java:1606)
        at java.lang.System$LoggerFinder.getLoggerFinder(java.base@11.0.3/System.java:1594)
        at jdk.internal.logger.LazyLoggers.accessLoggerFinder(java.base@11.0.3/LazyLoggers.java:339)
        at jdk.internal.logger.LazyLoggers.getLoggerFromFinder(java.base@11.0.3/LazyLoggers.java:389)
        at jdk.internal.logger.LazyLoggers.getLazyLogger(java.base@11.0.3/LazyLoggers.java:444)
        at jdk.internal.logger.LazyLoggers.getLogger(java.base@11.0.3/LazyLoggers.java:414)
        at java.lang.System.getLogger(java.base@11.0.3/System.java:1656)
        at com.sun.jmx.remote.util.ClassLogger.<init>(java.management@11.0.3/ClassLogger.java:38)
        at javax.management.NotificationBroadcasterSupport.<clinit>(java.management@11.0.3/NotificationBroadcasterSupport.java:365)
        at javax.management.MBeanServerDelegate.<init>(java.management@11.0.3/MBeanServerDelegate.java:73)
        at com.sun.jmx.mbeanserver.MBeanServerDelegateImpl.<init>(java.management@11.0.3/MBeanServerDelegateImpl.java:100)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.newMBeanServerDelegate(java.management@11.0.3/JmxMBeanServer.java:1372)
        at javax.management.MBeanServerBuilder.newMBeanServerDelegate(java.management@11.0.3/MBeanServerBuilder.java:66)
        at javax.management.MBeanServerFactory.newMBeanServer(java.management@11.0.3/MBeanServerFactory.java:321)
        - locked <0x00000000f743a538> (a javax.management.MBeanServerBuilder)
        at javax.management.MBeanServerFactory.createMBeanServer(java.management@11.0.3/MBeanServerFactory.java:231)
        at javax.management.MBeanServerFactory.createMBeanServer(java.management@11.0.3/MBeanServerFactory.java:192)
        at java.lang.management.ManagementFactory.getPlatformMBeanServer(java.management@11.0.3/ManagementFactory.java:483)
        - locked <0x00000000f72469b8> (a java.lang.Class for java.lang.management.ManagementFactory)
        at org.apache.tomcat.util.modeler.Registry.getMBeanServer(Registry.java:451)
        - locked <0x00000000f73b6200> (a java.lang.Object)
        at org.apache.catalina.mbeans.MBeanUtils.createServer(MBeanUtils.java:576)
        - locked <0x00000000f73a8810> (a java.lang.Class for org.apache.catalina.mbeans.MBeanUtils)
        at org.apache.catalina.mbeans.MBeanUtils.<clinit>(MBeanUtils.java:80)
        at org.apache.catalina.mbeans.MBeanFactory.<clinit>(MBeanFactory.java:66)
        at org.springframework.boot.autoconfigure.BackgroundPreinitializer$MBeanFactoryInitializer.run(BackgroundPreinitializer.java:143)
        at org.springframework.boot.autoconfigure.BackgroundPreinitializer$1.runSafely(BackgroundPreinitializer.java:106)
        at org.springframework.boot.autoconfigure.BackgroundPreinitializer$1.run(BackgroundPreinitializer.java:98)
        at java.lang.Thread.run(java.base@11.0.3/Thread.java:834)

Found 1 deadlock.
```

**Comment by wilkinsona** [comment]
Thanks for the report and thread dump. Unfortunately, I don't think there's much we can do about it as it looks like a JDK bug to me.

The two locks that are involved are both defined in the JDK, and it's JDK code that's synchronising on them:

- [`jdk.internal.logger.LoggerFinderLoader.lock`](http://hg.openjdk.java.net/jdk/jdk11/file/1ddf9a99e4ad/src/java.base/share/classes/jdk/internal/logger/LoggerFinderLoader.java#l43)
- [`java.util.zip.ZipFile`](http://hg.openjdk.java.net/jdk/jdk11/file/1ddf9a99e4ad/src/java.base/share/classes/java/util/zip/ZipFile.java#l345) (it synchronises on this).

The main thread is defining a class and has locked the `JarFile` from which the class is being loaded. It's verifying a signature which does some logging. This results in `LoggerFinderLoader` being called to get the `LoggerFinder`. This tries to synchronize on `LoggerFinderLoader.lock` which is already locked so it has to wait.

The background pre-init thread has also called some JDK code that does some logging. This results in `LoggerFinderLoader` being called to get the `LoggerFinder`. This has locked `LoggerFinderLoader.lock` and then proceeded to loader the `LoggerFinder`. This uses the `ServiceLoader` and, in accessing a resource in a `JarFile`, the `JarFile` tries to synchronize on itself (`this`). This is the same `JarFile` that the main thread has already locked so the two threads are now deadlocked.

You may be able to work around the problem. You could try disabling the background preinitialisation thread by setting the following system property:

```
spring.backgroundpreinitializer.ignore=true
```

You could also try calling `System.getLogger("avoid-deadlock")` in your application's main method before you do anything else. This should result in `LoggerFinderLoader` completing its initialization such that it does not need to synchronize on `LoggerFinderLoader.lock`.

If you have a support contract with Azul for Zulu, I would recommend filing a bug report with them. If not, filing a bug report with Oracle (https://bugreport.java.com/bugreport/) is the only way that I know of for users to get something into the OpenJDK bug tracker (https://bugs.openjdk.java.net). If you do file something and it results in something publicly accessible, please comment here with a link to it so that we can follow along.

**Comment by stefanocke** [comment]
@wilkinsona , thank you very much for detailed explanation and suggested workarounds. If we take further steps, I will report here.

**Comment by ferstl** [comment]
There is a Bug report for this problem in OpenJDK: https://bugs.openjdk.java.net/browse/JDK-8234466

**Comment by wilkinsona** [comment]
Thanks for joining some dots, @ferstl.
