### ISSUE TITLE
Spring session with reactive redis sometimes fails to update data in the case of a non-shared connection

### ISSUE THREAD

**Issue by wangxing-git** [spring-projects/spring-boot#16877]
### Spring boot version:
`2.1.4.RELEASE`
### pom.xml
```
<dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis-reactive</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.session</groupId>
            <artifactId>spring-session-data-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>27.1-jre</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-pool2</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
```
### RedisConfig.java
```
package com.example.webfluxsessiondemo.config;

import io.lettuce.core.resource.DefaultClientResources;
import org.springframework.beans.BeansException;
import org.springframework.beans.factory.config.BeanPostProcessor;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory;

@Configuration
public class RedisConfig {

    @Bean
    public BeanPostProcessor lettuceConnectionFactoryObjectPostProcessor() {
        return new BeanPostProcessor() {
            @Override
            public Object postProcessBeforeInitialization(Object bean, String beanName) throws BeansException {
                if (bean instanceof LettuceConnectionFactory) {
                    LettuceConnectionFactory lettuceConnectionFactory = ((LettuceConnectionFactory) bean);
                    lettuceConnectionFactory.setShareNativeConnection(false);
                }
                return bean;
            }
        };
    }

    @Bean(destroyMethod = "shutdown")
    public DefaultClientResources lettuceClientResources() {
        return DefaultClientResources.builder()
                .ioThreadPoolSize(20)
                .computationThreadPoolSize(20)
                .build();
    }

}
```
### SpringSessionConfig.java
```
package com.example.webfluxsessiondemo.config;

import org.springframework.context.annotation.Configuration;
import org.springframework.session.data.redis.RedisFlushMode;
import org.springframework.session.data.redis.config.annotation.web.server.EnableRedisWebSession;

@Configuration
@EnableRedisWebSession(redisFlushMode = RedisFlushMode.IMMEDIATE)
public class SpringSessionConfig {
}
```
### SpringSecurityConfig.java
```
package com.example.webfluxsessiondemo.config;

import com.example.webfluxsessiondemo.security.TestReactiveUserDetailsService;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.authentication.UserDetailsRepositoryReactiveAuthenticationManager;
import org.springframework.security.config.web.server.ServerHttpSecurity;
import org.springframework.security.core.userdetails.ReactiveUserDetailsService;
import org.springframework.security.crypto.factory.PasswordEncoderFactories;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.security.web.server.SecurityWebFilterChain;
import org.springframework.security.web.server.context.WebSessionServerSecurityContextRepository;

@Configuration
public class SpringSecurityConfig {

    @Bean
    public ReactiveUserDetailsService getUserDetailsService() {
        return new TestReactiveUserDetailsService();
    }

    @Bean
    public PasswordEncoder passwordEncoder() {
        return PasswordEncoderFactories.createDelegatingPasswordEncoder();
    }

    @Bean
    public SecurityWebFilterChain securityWebFilterChain(final ServerHttpSecurity http) {
        final SecurityWebFilterChain securityWebFilterChain = http
                .authorizeExchange()
                .pathMatchers("/login").permitAll()
                .pathMatchers("/user/me").permitAll()
                .anyExchange().authenticated()
                .and()
                .formLogin()
                .authenticationManager(userDetailsRepositoryReactiveAuthenticationManager())
                .securityContextRepository(webSessionServerSecurityContextRepository())
                .and()
                .csrf().disable()
                .build();
        return securityWebFilterChain;
    }

    @Bean
    public WebSessionServerSecurityContextRepository webSessionServerSecurityContextRepository() {
        return new WebSessionServerSecurityContextRepository();
    }

    @Bean
    public UserDetailsRepositoryReactiveAuthenticationManager userDetailsRepositoryReactiveAuthenticationManager(){
        return new UserDetailsRepositoryReactiveAuthenticationManager(getUserDetailsService());
    }

}
```
When I reset the user information in the session after updating the user information, sometimes the cache is not updated.
### Reproducible example
[webflux-session-demo](https://github.com/wangxing-git/webflux-session-demo)
`Note: For security, I hide the redis host and password in the example.`
Run test `WebfluxSessionDemoApplicationTests`
```
2019-05-16 10:03:37.039  INFO 1920 --- [ctor-http-nio-6] c.e.w.s.TestReactiveUserDetailsService   : loadUserByUsername:test
2019-05-16 10:03:37.249  INFO 1920 --- [ctor-http-nio-6] c.e.w.s.TestReactiveUserDetailsService   : loadUserByUsername:test
2019-05-16 10:03:37.451  INFO 1920 --- [ctor-http-nio-6] c.e.w.s.TestReactiveUserDetailsService   : loadUserByUsername:test
2019-05-16 10:03:37.675  INFO 1920 --- [ctor-http-nio-6] c.e.w.s.TestReactiveUserDetailsService   : loadUserByUsername:test
2019-05-16 10:03:37.874  INFO 1920 --- [ctor-http-nio-6] c.e.w.s.TestReactiveUserDetailsService   : loadUserByUsername:test

java.lang.AssertionError: 
Expected: hasProperty("nickName", "6692778561368372881")
     but: property 'nickName' was "-8326156080247474824"

> GET http://localhost:53988/user/me
> Accept: [application/json;charset=UTF-8]
> WebTestClient-Request-Id: [1]

No content

< 200 OK OK
< Content-Type: [application/json;charset=UTF-8]
< Content-Length: [97]
< Cache-Control: [no-cache, no-store, max-age=0, must-revalidate]
< Pragma: [no-cache]
< Expires: [0]
< X-Content-Type-Options: [nosniff]
< X-Frame-Options: [DENY]
< X-XSS-Protection: [1 ; mode=block]
< Referrer-Policy: [no-referrer]

{"id":"3ac7b489-8048-49f3-8c18-5c7274a3828f","userName":"test","nickName":"-8326156080247474824"}


	at org.springframework.test.web.reactive.server.ExchangeResult.assertWithDiagnostics(ExchangeResult.java:200)
	at org.springframework.test.web.reactive.server.DefaultWebTestClient$DefaultBodySpec.value(DefaultWebTestClient.java:392)
	at com.example.webfluxsessiondemo.WebfluxSessionDemoApplicationTests.contextLoads(WebfluxSessionDemoApplicationTests.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.AssertionError: 
Expected: hasProperty("nickName", "6692778561368372881")
     but: property 'nickName' was "-8326156080247474824"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at org.springframework.test.web.reactive.server.DefaultWebTestClient$DefaultBodySpec.lambda$value$1(DefaultWebTestClient.java:392)
	at org.springframework.test.web.reactive.server.ExchangeResult.assertWithDiagnostics(ExchangeResult.java:197)
	... 33 more
```
And it is normal after removing `RedisConfig`

**Comment by philwebb** [comment]
Thanks for the detailed report. I've transferred this issue to https://github.com/spring-projects/spring-session/issues/1428 since it looks like an issue with Spring Session itself, rather than the way that Spring Boot configures it.
