### ISSUE TITLE
HTTP2 request with json not working using Webflux and Netty

### ISSUE THREAD

**Issue by belkirdi** [spring-projects/spring-boot#16897]
Make just and endpoint that receive request in the body and you will get the same error that I have :

```
curl -X POST -k -H 'Content-Type: application/json' -i 'https://localhost.direct:10000/login' --data '{"username":"test","password":"test"}' return 500 Internal Server Error
```

```
2019-05-17 11:14:39.636 DEBUG [or-http-epoll-2] [SLOG] r.u.Loggers$Slf4JLogger                  : [id: 0xeae659cf, L:/127.0.0.1:10000 - R:/127.0.0.1:55538](H2 - 15) Subscribing inbound receiver [pending: 0, cancelled:false, inboundDone: false]
2019-05-17 11:14:39.708 DEBUG [or-http-epoll-2] [SLOG] o.s.c.l.CompositeLog                     : [eae659cf/1] Resolved [IllegalArgumentException: Object io.netty.handler.codec.http2.DefaultHttp2WindowUpdateFrame@b288dcc of type class io.netty.handler.codec.http2.DefaultHttp2WindowUpdateFrame cannot be converted to ByteBuf] for HTTP POST /login
2019-05-17 11:14:39.708 ERROR [or-http-epoll-2] [SLOG] o.s.c.l.CompositeLog                     : [eae659cf/1] 500 Server Error for HTTP POST "/login"

java.lang.IllegalArgumentException: Object io.netty.handler.codec.http2.DefaultHttp2WindowUpdateFrame@b288dcc of type class io.netty.handler.codec.http2.DefaultHttp2WindowUpdateFrame cannot be converted to ByteBuf
	at reactor.netty.ByteBufFlux.lambda$static$10(ByteBufFlux.java:322)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:206)
	at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:322)
	at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:335)
	at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:463)
	at reactor.netty.http.server.HttpToH2Operations.onInboundNext(HttpToH2Operations.java:73)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:91)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at reactor.netty.http.server.Http2StreamBridgeHandler.channelRead(Http2StreamBridgeHandler.java:90)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.handler.codec.http2.Http2MultiplexCodec$DefaultHttp2StreamChannel$Http2ChannelUnsafe.doRead0(Http2MultiplexCodec.java:1062)
	at io.netty.handler.codec.http2.Http2MultiplexCodec$DefaultHttp2StreamChannel.fireChildRead(Http2MultiplexCodec.java:771)
	at io.netty.handler.codec.http2.Http2MultiplexCodec.onHttp2Frame(Http2MultiplexCodec.java:234)
	at io.netty.handler.codec.http2.Http2FrameCodec$FrameListener.onWindowUpdateRead(Http2FrameCodec.java:549)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onWindowUpdateRead(DefaultHttp2ConnectionDecoder.java:541)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$PrefaceFrameListener.onWindowUpdateRead(DefaultHttp2ConnectionDecoder.java:703)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readWindowUpdateFrame(DefaultHttp2FrameReader.java:601)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:275)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:148)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:242)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.handler.codec.http2.Http2MultiplexCodec.channelRead(Http2MultiplexCodec.java:401)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1478)
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1239)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1276)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:796)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:432)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ com.iwellsite.core.security.authentication.LoginWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	|_ checkpoint ⇢ HTTP POST "/login" [ExceptionHandlingWebHandler]


2019-05-17 11:14:39.742 DEBUG [or-http-epoll-2] [SLOG] o.s.c.l.CompositeLog                     : [eae659cf/1] Encoding [{timestamp=Fri May 17 11:14:39 MDT 2019, path=/login, status=500, error=Internal Server Error, messa (truncated)...]
2019-05-17 11:14:39.846 DEBUG [or-http-epoll-2] [SLOG] r.u.Loggers$Slf4JLogger                  : [id: 0xeae659cf, L:/127.0.0.1:10000 - R:/127.0.0.1:55538](H2 - 15) Dropping frame DefaultLastHttpContent(data: UnpooledSlicedByteBuf(ridx: 0, widx: 37, cap: 37/37, unwrapped: PooledUnsafeDirectByteBuf(ridx: 435, widx: 444, cap: 560)), decoderResult: success), 0 in buffer
2019-05-17 11:14:39.848 DEBUG [or-http-epoll-2] [SLOG] i.n.c.DefaultChannelPipeline             : Discarded inbound message DefaultHttp2SettingsAckFrame that reached at the tail of the pipeline. Please check your pipeline configuration.
```

**Comment by philwebb** [comment]
Could you please provide a sample application that shows the problem.

**Comment by belkirdi** [comment]
Hi Please find below how to reproduce is really simple : 

```
package com.example.http2_500_error_webflux_netty;

import reactor.core.publisher.Mono;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class HTTP2RestController {

	//curl -X GET -k -i 'https://localhost.direct:8888/without_json' return 200
	@GetMapping("/without_json")
	public Mono<Boolean> firstCallWorking() {
		return Mono.just(Boolean.TRUE);
	}

	//curl -X POST -k -i 'https://localhost.direct:8888/without_json' return 200
	@PostMapping("/without_json")
	public Mono<Boolean> secondCallWorking() {
		return Mono.just(Boolean.TRUE);
	}


	//curl -X GET -k -H 'Content-Type: application/json' -i 'https://localhost.direct:8888/with_json' --data '{"key":"key_1", "value":"value_1"}'
	// return 500 Internal Error
	// {"timestamp":"2019-05-17T19:38:03.038+0000","path":"/with_json","status":500,"error":"Internal Server Error","message":"Object io.netty.handler.codec.http2.DefaultHttp2WindowUpdateFrame@2835b70c of type class io.netty.handler.codec.http2.DefaultHttp2WindowUpdateFrame cannot be converted to ByteBuf"}
	@GetMapping("/with_json")
	public Mono<ReqResp> firstCallNotWorking(@RequestBody ReqResp reqResp) {
		return Mono.just(reqResp);
	}

	// curl -X POST -k -H 'Content-Type: application/json' -i 'https://localhost.direct:8888/with_json' --data '{"key":"key_1", "value":"value_1"}'
    // return 500 Internal Error
	// {"timestamp":"2019-05-17T19:38:53.052+0000","path":"/with_json","status":500,"error":"Internal Server Error","message":"Object io.netty.handler.codec.http2.DefaultHttp2WindowUpdateFrame@4265566c of type class io.netty.handler.codec.http2.DefaultHttp2WindowUpdateFrame cannot be converted to ByteBuf"}
	@PostMapping("/with_json")
	public Mono<ReqResp> secondCallNotWorking(@RequestBody ReqResp reqResp) {
		return Mono.just(reqResp);
	}
}
```
application.properties

```
# Server port
server.port=8888

# Logging
logging.level.root=DEBUG

# SSL Configuration
server.ssl.enabled=true
server.ssl.key-store=classpath:localhost.direct.jks
server.ssl.key-store-type=JKS
server.ssl.key-store-password=localhost
server.ssl.key-password=localhost
server.ssl.protocol=TLSv1.2

# HTTP 2.0
server.http2.enabled=true
```
pom.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.1.5.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>http2_500_error_webflux_netty</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>http2_500_error_webflux_netty</name>
	<description>HTTP2 Error</description>

	<properties>
		<java.version>11</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>

		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.projectreactor</groupId>
			<artifactId>reactor-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>
```

**Comment by smaldini** [comment]
While I haven't reproduced it yet, the path where this exception happens is def something for https://github.com/reactor/reactor-netty to fix. Thanks a lot for the detailed report

**Comment by philwebb** [comment]
Thanks @smaldini, I've opened https://github.com/reactor/reactor-netty/issues/744
