### ISSUE TITLE
IllegalArgumentException in SslServerCustomizer.loadStore if ssl.getKeystore() returns null

### ISSUE THREAD

**Issue by billore** [spring-projects/spring-boot#17051]
I have recently upgraded spring-boot from 2.0.8 to 2.1.4.
After upgrade, I have started seeing IllegalArgumentException in `SslServerCustomizer.loadStore` if `ssl.getKeystore()` returns null.

Looking at the code diff, in to older version(2.0.8) there was a null check for resource in the loadStore(), before calling into `ResourceUtils.getURL(resource);`

It looks like this null check is missing in the latest version and due to that, IllegalArgumentException is thrown at a later stage.
Due to this, my existing code has stopped working.

```
Caused by: java.lang.IllegalArgumentException: Resource location must not be null
	at org.springframework.util.Assert.notNull(Assert.java:198) ~[spring-core-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
	at org.springframework.util.ResourceUtils.getURL(ResourceUtils.java:130) ~[spring-core-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
	at org.springframework.boot.web.embedded.netty.SslServerCustomizer.loadStore(SslServerCustomizer.java:164) ~[spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.web.embedded.netty.SslServerCustomizer.loadKeyStore(SslServerCustomizer.java:147) ~[spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.web.embedded.netty.SslServerCustomizer.getKeyStore(SslServerCustomizer.java:117) ~[spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.web.embedded.netty.SslServerCustomizer.getKeyManagerFactory(SslServerCustomizer.java:96) ~[spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
```

![SslServerCustomizer diff 2 0 8 vs 2 1 4](https://user-images.githubusercontent.com/51327595/58807367-90120700-8635-11e9-9586-134caedc272c.png)

**Comment by snicoll** [comment]
Looks like the `null` check was kept for trust store but got removed for key store.

**Comment by wilkinsona** [comment]
This was intentional as it aligns Netty's behaviour with that of Jetty, Tomcat, and Undertow. See https://github.com/spring-projects/spring-boot/pull/15709 for the details.

@billore Can you please describe what you are trying to do? It may be that you were relying on a bug in which case your code may have to change or it may be that you have a use case that we haven't considered and we should change all 4 embedded containers that we submit to accommodate it.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
