### ISSUE TITLE
Cannot use sliced tests(JooqTest) with caching

### ISSUE THREAD

**Issue by nekperu15739** [spring-projects/spring-boot#17065]
Hi, i have some sliced repository test mark with `@JooqTest` and app has enable the cache using `@EnableCaching` like this:

```java
@RunWith(SpringRunner.class)
@JooqTest
@Import(JooqBillingDataRepository.class)
public class JooqBillingDataRepositoryIT {

    @Autowired
    private DSLContext dslContext;

    @Autowired
    private JooqBillingDataRepository repository;

    @Test
    public void insert() {
        final long accommodationId = RandomUtils.nextLong();
        final String lastModifiedBy = RandomStringUtils.randomAlphabetic(10, 30);
        final LocalDateTime lastModifiedDate = LocalDateTime.now();

        final BillingDataRecord record = new BillingDataRecord();
        record.setLastModifiedBy(lastModifiedBy);
        record.setLastModifiedDate(lastModifiedDate);
        record.setAccommodationId(accommodationId);

        final Mono<BillingDataRecord> mono = repository.insert(record);

        StepVerifier.create(mono)
            .consumeNextWith(r -> {
                assertThat(r.getBillingDataId()).isPositive();
                assertThat(r.getAccommodationId()).isEqualTo(accommodationId);
                assertThat(r.getLastModifiedBy()).isEqualTo(lastModifiedBy);
                assertThat(r.getLastModifiedDate()).isEqualToIgnoringSeconds(lastModifiedDate);
            })
            .expectComplete()
            .verify();
    }
```

however, they are failing because some missing cache beans:

```
Caused by: java.lang.IllegalStateException: No CacheResolver specified, and no bean of type CacheManager found. Register a CacheManager bean or remove the @EnableCaching annotation from your configuration.
	at org.springframework.cache.interceptor.CacheAspectSupport.afterSingletonsInstantiated(CacheAspectSupport.java:227)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:860)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:127)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:117)
	... 25 more
```

**Comment by wilkinsona** [comment]
Thanks for opening this, @nekperu15739.

As noted on #5765, we need to add `@AutoConfigureCache` to `@JooqTest`.

**Comment by wilkinsona** [comment]
Closing in favour of #17066.
