### ISSUE TITLE
Spring Data MongoDB: @DBRef does not handle Back-References -> Stackoverflow Exception

### ISSUE THREAD

**Issue by bollywood-coder** [spring-projects/spring-boot#17105]
I want to report a Problem with Spring Boot 2.1.1 and Spring Data MongoDB handling @DBRef Back-References.

Sample Code is in Kotlin.

Lets say I have a class `Parent`

    class Parent(val id: String, val child: Child) {

        init {
            child.parent = this
        }
    }

Also there is a `Child` class with a back reference to the parent!

    class Child {

        @DBRef
        @JsonIgnore
        lateinit var parent: Parent
    }

However, when I want to save and retrieve the parent with

    @Autowired
    lateinit var mongo: MongoOperations

    val parent = Parent("1", Child())
    mongo.save(parent)
    mongo.findById<Parent>("1")

I get `StackOverflow Exception` on the `mongo.findById` call!
However, saving workes fine.

In the Exception stack it shows clearly that MongoDB has problems with resolving DBRef

	at org.springframework.data.mongodb.core.convert.DefaultDbRefResolver.resolveDbRef(DefaultDbRefResolver.java:103)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readAssociation(MappingMongoConverter.java:400)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readProperties(MappingMongoConverter.java:354)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.populateProperties(MappingMongoConverter.java:295)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:275)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:245)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readValue(MappingMongoConverter.java:1491)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$MongoDbPropertyValueProvider.getPropertyValue(MappingMongoConverter.java:1389)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$AssociationAwareMongoDbPropertyValueProvider.getPropertyValue(MappingMongoConverter.java:1438)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$AssociationAwareMongoDbPropertyValueProvider.getPropertyValue(MappingMongoConverter.java:1401)
	at org.springframework.data.mapping.model.PersistentEntityParameterValueProvider.getParameterValue(PersistentEntityParameterValueProvider.java:71)
	at org.springframework.data.mapping.model.SpELExpressionParameterValueProvider.getParameterValue(SpELExpressionParameterValueProvider.java:49)
	at org.springframework.data.convert.ClassGeneratingEntityInstantiator$EntityInstantiatorAdapter.extractInvocationArguments(ClassGeneratingEntityInstantiator.java:250)
	at org.springframework.data.convert.ClassGeneratingEntityInstantiator$EntityInstantiatorAdapter.createInstance(ClassGeneratingEntityInstantiator.java:223)
	at org.springframework.data.convert.ClassGeneratingEntityInstantiator.createInstance(ClassGeneratingEntityInstantiator.java:84)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:272)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:245)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.bulkReadAndConvertDBRefs(MappingMongoConverter.java:1556)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readAndConvertDBRef(MappingMongoConverter.java:1516)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.potentiallyReadOrResolveDbRef(MappingMongoConverter.java:1509)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readValue(MappingMongoConverter.java:1487)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$MongoDbPropertyValueProvider.getPropertyValue(MappingMongoConverter.java:1389)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.getValueInternal(MappingMongoConverter.java:991)

This shown stack continues until Stackoverflow.

**Comment by wilkinsona** [comment]
Thanks for the report. This appears to be a problem with Spring Data MongoDB which is managed as a separate project. They use JIRA for issue management so, unfortunately, we cannot transfer this issue to them. Can you please open a [DATAMONGO](https://jira.spring.io/projects/DATAMONGO) issue and comment here with a link to it.

**Comment by bollywood-coder** [comment]
Thanks... I did

**Comment by wilkinsona** [comment]
[DATAMONGO-2299](https://jira.spring.io/projects/DATAMONGO/issues/DATAMONGO-2299)
