### ISSUE TITLE
Missing outcome tag for WebClient metrics on errors

### ISSUE THREAD

**Issue by 1nDivid** [spring-projects/spring-boot#17219]
**Affects:** 2.2.0.M3

### Description
On error signal there is a problem in MetricsWebClientFilterFunction::filter.
There could be no response and DefaultWebClientExchangeTagsProvider::tags will return not enough tags (no outcome tag) for metrics and we will get:
```
java.lang.IllegalArgumentException: Prometheus requires that all meters with the same name have the same set of tag keys. There is already an existing meter named 'http_client_requests_seconds' containing tag keys [application, clientName, method, outcome, status, uri]. The meter you are attempting to register has keys [application, clientName, method, status, uri].
	at io.micrometer.prometheus.PrometheusMeterRegistry.lambda$collectorByName$9(PrometheusMeterRegistry.java:372)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1932)
	at io.micrometer.prometheus.PrometheusMeterRegistry.collectorByName(PrometheusMeterRegistry.java:359)
	at io.micrometer.prometheus.PrometheusMeterRegistry.newTimer(PrometheusMeterRegistry.java:165)
	at io.micrometer.core.instrument.MeterRegistry.lambda$timer$2(MeterRegistry.java:270)
	at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:575)
	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:528)
	at io.micrometer.core.instrument.MeterRegistry.timer(MeterRegistry.java:268)
	at io.micrometer.core.instrument.Timer$Builder.register(Timer.java:464)
	at org.springframework.boot.actuate.metrics.web.reactive.client.MetricsWebClientFilterFunction.lambda$filter$0(MetricsWebClientFilterFunction.java:99)
```

**Comment by wilkinsona** [comment]
Thanks for the report, @1nDivid. Looks like `DefaultWebClientExchangeTagsProvider` needs to include an outcome tag derived from the `Throwable`.

**Comment by wilkinsona** [comment]
@bclozel The `status` tags for IO error and client error responses don't look quite right to me. I think they'll have values of `IO_ERROR` and `CLIENT_ERROR` respectively, but they're documented as being HTTP status codes. Perhaps we can't map more accurately than that. If that's the case, a documentation update is probably in order. We then need to map those to a particular outcome. I guess `CLIENT_ERROR` can be `OUTCOME_CLIENT_ERROR` but I'm not sure about `IO_ERROR`. What would you suggest?

**Comment by bclozel** [comment]
@wilkinsona I've fixed the documentation and applied similar behavior (and tag values) as the one already implemented for `RestTemplate`.
