### ISSUE TITLE
Default Packages to Scan for EntityManagerFactoryBuilder

### ISSUE THREAD

**Issue by edwardbeckett** [spring-projects/spring-boot#17230]
The `EntityManagerFactoryBuilder#packages` operation is not currently required but should be as the entityManager will be in an invalid state if the packages value is not set. The operation could have a sensible default defense -  ( such as the application base package, etc) 

Further, If the base packages value is not set, an error is issued regarding the persistent unit being unknown causing ambiguity when trying to resolve.

**Comment by philwebb** [comment]
I'm not sure that we can safely make that assumption from the builder. We delegate to `LocalContainerEntityManagerFactoryBean.setPackagesToScan` but the Javadoc for that class has the following:

> Set whether to use Spring-based scanning for entity classes in the classpath instead of using JPA's standard scanning of jar files with persistence.xml markers in them.

I think it there might be a legitimate use-case where the packages are not specified because `persistence.xml` is used.

@edwardbeckett Have you got an example of the kind of error you see when `.packages` is not called?

**Comment by edwardbeckett** [comment]
@philwebb ~ Let me reproduce the configuration...

**Comment by philwebb** [comment]
Thanks @edwardbeckett, can you paste the full stack trace for that `IllegalArgumentException`. I'm thinking we might be able to catch and rethrow it with an additional warning if the packages have not been set.

**Comment by edwardbeckett** [comment]
Surely... here's the trace... 

```
[2019-06-18 15:13:22.806] [WARN ] [PID: 22336] :: [CID: ] :: [restartedMain] [erApplicationContext] :: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [com/inet/activation/config/ActivationDBConfig.class]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: No persistence unit with name 'activation' found
[2019-06-18 15:13:22.809] [DEBUG] [PID: 22336] :: [CID: ] :: [restartedMain] [o.s.b.d.r.Restarter ] :: Creating new Restarter for thread Thread[main,5,main]
[2019-06-18 15:13:22.809] [DEBUG] [PID: 22336] :: [CID: ] :: [restartedMain] [o.s.b.d.r.Restarter ] :: Immediately restarting application
[2019-06-18 15:13:22.809] [DEBUG] [PID: 22336] :: [CID: ] :: [restartedMain] [o.s.b.d.r.Restarter ] :: Created RestartClassLoader org.springframework.boot.devtools.restart.classloader.RestartClassLoader@6aa02ce9
[2019-06-18 15:13:22.809] [DEBUG] [PID: 22336] :: [CID: ] :: [restartedMain] [o.s.b.d.r.Restarter ] :: Starting application com.inet.activation.Activation with URLs [file:/D:/Projects/INET/activation/target/classes/]
[2019-06-18 15:13:22.809] [DEBUG] [PID: 22336] :: [CID: ] :: [restartedMain] [gApplicationListener] :: Application failed to start with classpath: [file:/D:/Projects/INET/activation/target/classes/]
[2019-06-18 15:13:22.819] [ERROR] [PID: 22336] :: [CID: ] :: [restartedMain] [.b.SpringApplication] :: Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [com/inet/activation/config/ActivationDBConfig.class]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: No persistence unit with name 'activation' found
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1105)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at com.inet.activation.Activation.main(Activation.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: java.lang.IllegalArgumentException: No persistence unit with name 'activation' found
	at org.springframework.orm.jpa.persistenceunit.DefaultPersistenceUnitManager.obtainPersistenceUnitInfo(DefaultPersistenceUnitManager.java:736)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.determinePersistenceUnitInfo(LocalContainerEntityManagerFactoryBean.java:384)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:332)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1837)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1774)
	... 19 common frames omitted


Process finished with exit code 0
```

**Comment by philwebb** [comment]
Hmm, annoyingly it's the init method, not the build method that fails. That limits our options somewhat.

**Comment by edwardbeckett** [comment]
Argh... :-/

**Comment by edwardbeckett** [comment]
@philwebb ~ Thanks for the review chief...

**Comment by philwebb** [comment]
Thanks for raising the issue @edwardbeckett. We discussed our options today as a team but unfortunately couldn't find a good way to help with this. The only real option we have is to subclass `LocalContainerEntityManagerFactoryBean` which seems a bit extreme. I think we'll have to leave things as they are I'm afraid.

**Comment by edwardbeckett** [comment]
@philwebb ~ Thanks for the resolve - improving the error handling message should be more than sufficient.
