### ISSUE TITLE
Upgrade to JUnit Jupiter 5.5.0-RC1

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#17266]
This also gives us an opportunity to simplify the build setup required to exclude the vintage engine now that https://github.com/junit-team/junit5/issues/1872 has been fixed.

**Comment by snicoll** [comment]
The upgrade has broken the build:

```
org.junit.platform.commons.PreconditionViolationException: Failed to register extension via @RegisterExtension field [private org.springframework.boot.cli.CliTester org.springframework.boot.cli.RunCommandIntegrationTests.cli]: field must not be private.
	at org.junit.platform.commons.util.Preconditions.condition(Preconditions.java:296)
	at org.junit.jupiter.engine.descriptor.ExtensionUtils.lambda$registerExtensionsFromFields$3(ExtensionUtils.java:103)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.jupiter.engine.descriptor.ExtensionUtils.registerExtensionsFromFields(ExtensionUtils.java:102)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:262)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$2(ClassBasedTestDescriptor.java:247)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$3(ClassBasedTestDescriptor.java:251)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$4(ClassBasedTestDescriptor.java:250)
```

**Comment by wilkinsona** [comment]
`CliTester` needs to be registered as an extension as it's a before each and after each callback.

**Comment by snicoll** [comment]
RC2 is out in the meantime so let's reuse this issue to update to it
