### ISSUE TITLE
Web server factory customizer beans that are also registered explicitly are called twice during web server creation

### ISSUE THREAD

**Issue by tlachy** [spring-projects/spring-boot#17264]
Spring Boot (v2.2.0.M3) fails to start with 

```xml
<dependency>
    <groupId>org.keycloak</groupId>
    <artifactId>keycloak-spring-boot-starter</artifactId>
    <version>6.0.1</version>
</dependency>
```
  

```
019-06-19 12:10:15.909 ERROR 8929 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is java.lang.IllegalArgumentException: Duplicate context initialization parameter [keycloak.config.resolver]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:157) ~[spring-boot-2.2.0.M3.jar:2.2.0.M3]
```

**Comment by wilkinsona** [comment]
Here's the full stack trace of the failure:

```
org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is java.lang.IllegalArgumentException: Duplicate context initialization parameter [keycloak.config.resolver]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:157) ~[spring-boot-2.2.0.M3.jar:2.2.0.M3]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-5.2.0.M2.jar:5.2.0.M2]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.2.0.M3.jar:2.2.0.M3]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:782) [spring-boot-2.2.0.M3.jar:2.2.0.M3]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:404) [spring-boot-2.2.0.M3.jar:2.2.0.M3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:319) [spring-boot-2.2.0.M3.jar:2.2.0.M3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1275) [spring-boot-2.2.0.M3.jar:2.2.0.M3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1263) [spring-boot-2.2.0.M3.jar:2.2.0.M3]
	at com.example.demo.Gh17264Application.main(Gh17264Application.java:10) [classes/:na]
Caused by: java.lang.IllegalArgumentException: Duplicate context initialization parameter [keycloak.config.resolver]
	at org.apache.catalina.core.StandardContext.addParameter(StandardContext.java:3111) ~[tomcat-embed-core-9.0.19.jar:9.0.19]
	at org.keycloak.adapters.springboot.KeycloakBaseSpringBootConfiguration$KeycloakBaseTomcatContextCustomizer.customize(KeycloakBaseSpringBootConfiguration.java:271) ~[keycloak-spring-boot-adapter-core-6.0.1.jar:6.0.1]
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.configureContext(TomcatServletWebServerFactory.java:377) ~[spring-boot-2.2.0.M3.jar:2.2.0.M3]
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.prepareContext(TomcatServletWebServerFactory.java:234) ~[spring-boot-2.2.0.M3.jar:2.2.0.M3]
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:183) ~[spring-boot-2.2.0.M3.jar:2.2.0.M3]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:181) ~[spring-boot-2.2.0.M3.jar:2.2.0.M3]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:154) ~[spring-boot-2.2.0.M3.jar:2.2.0.M3]
	... 8 common frames omitted
```

This looks like a bug in Keycloak.

**Comment by wilkinsona** [comment]
The duplicate is occurring because Keycloak's context customizer has been registered twice. It's registered with `TomcatServletWebServerFactory` via a `WebServerFactoryCustomizer` bean defined by `KeycloakAutoConfiguration`. It's also defined as a bean by `KeycloakAutoConfiguration` which, [this change in 2.2.0.M1](since https://github.com/spring-projects/spring-boot/pull/15492), is automatically registered with the web server factory.

Declaring a `TomcatContextCustomizer` as a bean had no effect prior to 2.2.0.M1 so it isn't something that we had expected anyone to do. As it's registered explicitly, Keycloak could be made compatible with Spring Boot 2.2 but removing the bean definition for its tomcat context customizer. I'll leave this one open for now as we might want to ease the migration path by performing some deduplication when we register `TomcatContextCustomizer` beans with the web server factory.

**Comment by wilkinsona** [comment]
We think we improve this by changing `tomcatContextCustomizers` from an `ArrayList` to a `LinkedHashSet`.

**Comment by wilkinsona** [comment]
Connector customisers have the same problem. For completeness, while the callback is new in 2.2, we should do the same for protocol handler customizers too.

**Comment by wilkinsona** [comment]
We should do this for Jetty and Undertow as well.
