### ISSUE TITLE
Spring WS security with spring boot

### ISSUE THREAD

**Issue by gauravchhimwal** [spring-projects/spring-boot#17314]
Hi,

I am using Spring boot 2.
I am consuming a SOAP web service and getting the below error:

```
Caused by: org.apache.wss4j.common.ext.WSSecurityException: No message with ID "noCallback" found in resource bundle "org/apache/xml/security/resource/xmlsecurity"
	at org.apache.wss4j.dom.action.CustomTokenAction.execute(CustomTokenAction.java:42) ~[wss4j-ws-security-dom-2.2.0.jar:2.2.0]
	at org.apache.wss4j.dom.handler.WSHandler.doSenderAction(WSHandler.java:238) ~[wss4j-ws-security-dom-2.2.0.jar:2.2.0]
	at org.springframework.ws.soap.security.wss4j2.Wss4jHandler.doSenderAction(Wss4jHandler.java:63) ~[spring-ws-security-3.0.7.RELEASE.jar:na]
	at org.springframework.ws.soap.security.wss4j2.Wss4jSecurityInterceptor.secureMessage(Wss4jSecurityInterceptor.java:574) ~[spring-ws-security-3.0.7.RELEASE.jar:na]
	... 105 common frames omitted

2019-06-26 16:27:49.134 ERROR 5496 --- [nio-7070-exec-4] o.a.c.c.C.[.[.[.[dispatcherServlet]      : Servlet.service() for servlet [dispatcherServlet] in context with path [/mobileApp] threw exception [Request processing failed; nested exception is java.lang.ClassCastException: org.springframework.ws.soap.security.callback.CleanupCallback cannot be cast to org.apache.ws.security.WSPasswordCallback] with root cause

java.lang.ClassCastException: org.springframework.ws.soap.security.callback.CleanupCallback cannot be cast to org.apache.ws.security.WSPasswordCallback
	at aero.sita.gsl.common.dto.ClientPasswordCallback.handle(ClientPasswordCallback.java:36) ~[classes/:na]
	at org.springframework.ws.soap.security.wss4j2.Wss4jSecurityInterceptor.cleanUp(Wss4jSecurityInterceptor.java:816) ~[spring-ws-security-3.0.7.RELEASE.jar:na]
	at org.springframework.ws.soap.security.AbstractWsSecurityInterceptor.afterCompletion(AbstractWsSecurityInterceptor.java:267) ~[spring-ws-security-3.0.7.RELEASE.jar:na]
	at org.springframework.ws.client.core.WebServiceTemplate.triggerAfterCompletion(WebServiceTemplate.java:810) ~[spring-ws-core-3.0.7.RELEASE.jar:na]
	at org.springframework.ws.client.core.WebServiceTemplate.doSendAndReceive(WebServiceTemplate.java:638) ~[spring-ws-core-3.0.7.RELEASE.jar:na]
	at org.springframework.ws.client.core.WebServiceTemplate.sendAndReceive(WebServiceTemplate.java:555) ~[spring-ws-core-3.0.7.RELEASE.jar:na]
	at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:390) ~[spring-ws-core-3.0.7.RELEASE.jar:na]
	at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:378) ~[spring-ws-core-3.0.7.RELEASE.jar:na]
	at aero.sita.gsl.config.VisaAppAdaptor.getApplicationNumber(VisaAppAdaptor.java:32) ~[classes/:na]
	at aero.sita.gsl.controller.VisaApplicationSearchController.getVisaDetails(VisaApplicationSearchController.java:29) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_212]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_212]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.0.M3.jar:5.2.0.M3]
```

Below is my configuration class:

```
@Configuration
public class BeanConfig extends WsConfigurerAdapter {
	
	@Autowired
	private Environment env;
	
	@Bean
	public Jaxb2Marshaller marshaller() {
		Jaxb2Marshaller marshaller = new Jaxb2Marshaller();
		marshaller.setContextPath("app");
		return marshaller;
	}

	@Bean
	public VisaAppAdaptor soapConnector(Jaxb2Marshaller marshaller) {
		VisaAppAdaptor client = new VisaAppAdaptor();
		client.setDefaultUri(env.getProperty("uri"));
		client.setMarshaller(marshaller);
		client.setUnmarshaller(marshaller);
		ClientInterceptor[] interceptor = new ClientInterceptor[]{securityInterceptor()};
		client.setInterceptors(interceptor);
		return client;
	}
	
    @Bean
    public Wss4jSecurityInterceptor securityInterceptor(){
        Wss4jSecurityInterceptor wss4jSecurityInterceptor = new Wss4jSecurityInterceptor();
        ClientPasswordCallback pwdCallBack = new ClientPasswordCallback();
        wss4jSecurityInterceptor.setSecurementActions(WSHandlerConstants.TIMESTAMP + " " + WSHandlerConstants.CUSTOM_TOKEN + " " + WSHandlerConstants.USERNAME_TOKEN);
        wss4jSecurityInterceptor.setSecureResponse(false);
        wss4jSecurityInterceptor.setSecurementPasswordType(WSConstants.PW_TEXT);
        wss4jSecurityInterceptor.setSecurementUsername(env.getProperty("soap.auth.username"));
        wss4jSecurityInterceptor.setSecurementPassword(env.getProperty("soap.auth.password"));
        wss4jSecurityInterceptor.setSecurementMustUnderstand(false);
        wss4jSecurityInterceptor.setValidationCallbackHandler(pwdCallBack);
        //wss4jSecurityInterceptor.setSecurementSamlCallbackHandler(pwdCallBack);
        //wss4jSecurityInterceptor.setSecurementActions(WSHandlerConstants.PW_CALLBACK_CLASS);
        //wss4jSecurityInterceptor.handleFault(messageContext)
        wss4jSecurityInterceptor.setSecurementMustUnderstand(false);
        return wss4jSecurityInterceptor;
    }

}
```

**Comment by wilkinsona** [comment]
The failure, a `ClassCastException` is occurring in `aero.sita.gsl.common.dto.ClientPasswordCallback.handle`. This isn't part of Spring Boot or Spring Web Services. Presumably it's your own application code. That's where the fix needs to be made.
