### ISSUE TITLE
1.5.x Wildfly deployment tests fail in environments with IPv6 networking disabled

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#17324]
Despite IPv6 being disabled, Wildfly still tries to use it which results in a startup failure:

```
build	26-Jun-2019 17:07:56	[INFO] [talledLocalContainer] 17:07:56,909 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-8) MSC000001: Failed to start service jboss.undertow.listener.default: org.jboss.msc.service.StartException in service jboss.undertow.listener.default: Could not start http listener
build	26-Jun-2019 17:07:56	[INFO] [talledLocalContainer] 	at org.wildfly.extension.undertow.ListenerService.start(ListenerService.java:150)
build	26-Jun-2019 17:07:56	[INFO] [talledLocalContainer] 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
build	26-Jun-2019 17:07:56	[INFO] [talledLocalContainer] 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
build	26-Jun-2019 17:07:56	[INFO] [talledLocalContainer] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
build	26-Jun-2019 17:07:56	[INFO] [talledLocalContainer] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
build	26-Jun-2019 17:07:56	[INFO] [talledLocalContainer] 	at java.lang.Thread.run(Thread.java:748)
build	26-Jun-2019 17:07:56	[INFO] [talledLocalContainer] Caused by: java.net.SocketException: Protocol family unavailable
build	26-Jun-2019 17:07:56	[INFO] [talledLocalContainer] 	at sun.nio.ch.Net.bind0(Native Method)
build	26-Jun-2019 17:07:56	[INFO] [talledLocalContainer] 	at sun.nio.ch.Net.bind(Net.java:433)
build	26-Jun-2019 17:07:56	[INFO] [talledLocalContainer] 	at sun.nio.ch.Net.bind(Net.java:425)
build	26-Jun-2019 17:07:56	[INFO] [talledLocalContainer] 	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
build	26-Jun-2019 17:07:56	[INFO] [talledLocalContainer] 	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
build	26-Jun-2019 17:07:56	[INFO] [talledLocalContainer] 	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67)
build	26-Jun-2019 17:07:56	[INFO] [talledLocalContainer] 	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:182)
build	26-Jun-2019 17:07:56	[INFO] [talledLocalContainer] 	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:243)
build	26-Jun-2019 17:07:56	[INFO] [talledLocalContainer] 	at org.wildfly.extension.undertow.HttpListenerService.startListening(HttpListenerService.java:115)
build	26-Jun-2019 17:07:56	[INFO] [talledLocalContainer] 	at org.wildfly.extension.undertow.ListenerService.start(ListenerService.java:147)
build	26-Jun-2019 17:07:56	[INFO] [talledLocalContainer] 	... 5 more
```

We should try configuring it to prefer IPv4.

**Comment by wilkinsona** [comment]
There’s no need for this any more as the CI environment has been fixed.
