### ISSUE TITLE
Accept header ends with "," produces HTTP "406 Not Acceptable"

### ISSUE THREAD

**Issue by j3r0lin** [spring-projects/spring-boot#17437]
Spring version: 5.1.8.RELEASE

Send a http request with header like this, containing `, ` at the end.
```http
Accept: application/json, 
```

HeaderContentNegotiationStrategy will produce a HttpMediaTypeNotAcceptableException exception.
```
org.springframework.web.HttpMediaTypeNotAcceptableException: Could not parse 'Accept' header [application/json,]: Invalid mime type "": 'mimeType' must not be empty
	at org.springframework.web.accept.HeaderContentNegotiationStrategy.resolveMediaTypes(HeaderContentNegotiationStrategy.java:59) ~[spring-web-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.web.accept.ContentNegotiationManager.resolveMediaTypes(ContentNegotiationManager.java:124) ~[spring-web-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.getAcceptableMediaTypes(AbstractMessageConverterMethodProcessor.java:391) ~[spring-webmvc-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:229) ~[spring-webmvc-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor.handleReturnValue(HttpEntityMethodProcessor.java:225) ~[spring-webmvc-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:82) ~[spring-web-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
```

That http request works before 5.1.2.RELEASE.
Maybe cause of this parsing method refactor in this commit [f4b05dc](https://github.com/spring-projects/spring-framework/commit/f4b05dc2e730ca667daf8861c6eb2d9a6b83d534#diff-47ef64129825b0e047375d409c7d95a9L260)
`StringUtils.tokenizeToStringArray(mimeTypes, ",")` will strim tokens and ignore empty tokens by default, but now, the replacement method not support that anymore.

**Comment by j3r0lin** [comment]
Wrong place, moved to [spring-framework](https://github.com/spring-projects/spring-framework/issues/23241) repo
