### ISSUE TITLE
Problem with spring security jdbc authentication

### ISSUE THREAD

**Issue by rajjaiswalsaumya** [spring-projects/spring-boot#1745]
withDefaultSchema() not working with postgres

**Comment by wilkinsona** [comment]
The actual failure here is:

```
Caused by: org.postgresql.util.PSQLException: ERROR: type "varchar_ignorecase" does not exist
  Position: 29
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2102)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1835)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:500)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:374)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:366)
	at org.springframework.jdbc.datasource.init.ScriptUtils.executeSqlScript(ScriptUtils.java:457)
	... 57 more
```

Spring Security's default schema isn't compatible with Postgres. You should use some other mechanism to, if necessary, create the required tables and index.

**Comment by thaiphan** [comment]
@wilkinsona Hi there! Do you know if any work has been done to get the default schema to work with Postgres? I ran into this problem today still.

**Comment by wilkinsona** [comment]
I don't. That's a question for the Spring Security team.
