### ISSUE TITLE
Spring boot R2DC custom mapping issue

### ISSUE THREAD

**Issue by nishant-1984** [spring-projects/spring-boot#17475]
Geeting below error:

```
org.springframework.data.mapping.MappingException: Couldn't read column communincation_prefs from Row.
	at org.springframework.data.r2dbc.convert.MappingR2dbcConverter$RowParameterValueProvider.getParameterValue(MappingR2dbcConverter.java:471)
	at org.springframework.data.relational.core.conversion.BasicRelationalConverter$ConvertingParameterValueProvider.getParameterValue(BasicRelationalConverter.java:256)
	at org.springframework.data.convert.KotlinClassGeneratingEntityInstantiator$DefaultingKotlinClassInstantiatorAdapter.extractInvocationArguments(KotlinClassGeneratingEntityInstantiator.java:230)
	at org.springframework.data.convert.KotlinClassGeneratingEntityInstantiator$DefaultingKotlinClassInstantiatorAdapter.createInstance(KotlinClassGeneratingEntityInstantiator.java:204)
	at org.springframework.data.convert.ClassGeneratingEntityInstantiator.createInstance(ClassGeneratingEntityInstantiator.java:84)
	at org.springframework.data.relational.core.conversion.BasicRelationalConverter.createInstance(BasicRelationalConverter.java:146)
	at org.springframework.data.r2dbc.convert.MappingR2dbcConverter.createInstance(MappingR2dbcConverter.java:232)
	at org.springframework.data.r2dbc.convert.MappingR2dbcConverter.read(MappingR2dbcConverter.java:121)
	at org.springframework.data.r2dbc.convert.MappingR2dbcConverter.read(MappingR2dbcConverter.java:116)
	at org.springframework.data.r2dbc.convert.EntityRowMapper.apply(EntityRowMapper.java:46)
	at org.springframework.data.r2dbc.convert.EntityRowMapper.apply(EntityRowMapper.java:29)
```

**I have created custom mapping still getting this issue.**

Configuration code:

```
@Configuration
class DatabaseConfiguration(@Value("\${spring.datasource.host}") val dbhost: String, @Value("\${spring.datasource.port}") val dbport: Int
                            , @Value("\${spring.datasource.database}") val database: String
                            , @Value("\${spring.datasource.username}") val username: String
                            , @Value("\${spring.datasource.password}") val password: String) : AbstractR2dbcConfiguration() {

    @Bean
    override fun r2dbcCustomConversions(): R2dbcCustomConversions {

        val converterList = ArrayList<Converter<*, *>>()
        converterList.add(com.vokalapp.dispatch.model.SocialProfilesReader())
        converterList.add(com.vokalapp.dispatch.model.CommunicationPreferenceReader())
        return R2dbcCustomConversions(converterList)
    }

    @Bean
    override fun getDialect(factory: ConnectionFactory): R2dbcDialect {
        return PostgresDialect()
    }

    @Bean
    override fun connectionFactory(): PostgresqlConnectionFactory {
        val config = PostgresqlConnectionConfiguration.builder() //
                .host(dbhost) //
                .port(dbport) //
                .database(database) //
                .username(username) //
                .password(password) //
                .build()
        return PostgresqlConnectionFactory(config)
    }
}
```

Mapper:

```
@ReadingConverter
class CommunicationPreferenceReader : Converter<Row, CommunicationPreference>{

    override fun convert(source: Row): CommunicationPreference? {
        val mapper = jacksonObjectMapper()

        val default_communincation_prefs_json = """{"whatsapp_prefs_stats": true, "notif_prefs_stats": true, "sms_prefs_stats": true}"""
        val communincation_prefs_json: String = source.get("communincation_prefs", String::class.java)?: default_communincation_prefs_json
        val communincation_prefs: CommunicationPreference = mapper.readValue(communincation_prefs_json)
        return communincation_prefs
    }
}
```

Full enity:

```
data class User(
        @Id
        val id: Int,
        val user_id: String,
        val ref_id: String = "",
        val phone: String = "",
        val email: String = "",
        val status: Int,
        val current_language: Int,
        val device_os: Int,
        val push_token: String = "",
        val handle: String = "",
        val name: String = "",
        val profile_image: String = "",
        val allow_recent: Int = 0,
        val gender: Int,
        val n_followers: Int = 0,
        val n_followings: Int = 0,
        val n_contents: Int = 0,
        val n_plays: Int = 0,
        val n_questions: Int = 0,
        val n_likes: Int = 0,
        val title: String = "",
        val approved: Boolean = false,
        val description: String = "",
        val auto_create: Boolean = true,
        val created_at: Int,
        val modified_at: Int,
        val creation_source: String = "",
        val answerer_type: Int,
        val work_exp: Array<WorkExperience>,
        val machine_approved: Boolean = false,
        val communincation_prefs: Array<CommunicationPreference>,
        val social_profiles: Array<SocialProfiles>,
        val dob: Int = 0,
        val marital_status: Int,
        val fact_level: Int,
        val opinion_level: Int
)
```

Crud class:

```
interface UserDBRepository : ReactiveCrudRepository<User, Int> {

    @Query("SELECT * FROM postgres_users WHERE user_id = $1")
    fun findByUserId(user_id: String): User
}
```

**Comment by wilkinsona** [comment]
Thanks for the report. Spring Data R2DBC is managed as a separate project from Spring Boot. You can find its issue tracker [here](https://github.com/spring-projects/spring-data-r2dbc/issues).
