### ISSUE TITLE
Tomcat crashes when requests containing certain (unencoded) characters.

### ISSUE THREAD

**Issue by dirkdeyne** [spring-projects/spring-boot#17509]
## Background
	
The HTTP/1.1 specification requires that certain characters are %nn encoded when used in URI paths. Unfortunately, many user agents including all the major browsers are not compliant with this specification and use these characters in unencoded form.

## Problem

Tomcat crashes when users make requests containing certain (unencoded) characters 

like: _http://localhost:8080/hello?message=[^_^]_

The user gets an ugly _HTTP Status 400 – Bad Request with a stack trace_

_console output:_
```
java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
  at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:467) ~[tomcat-embed-core-9.0.19.jar:9.0.19]
  at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:294) ~[tomcat-embed-core-9.0.19.jar:9.0.19]
  at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-9.0.19.jar:9.0.19]
  at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:836) [tomcat-embed-core-9.0.19.jar:9.0.19]
  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1747) [tomcat-embed-core-9.0.19.jar:9.0.19]
  at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.19.jar:9.0.19]
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_162]
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_162]
  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.19.jar:9.0.19]
  at java.lang.Thread.run(Thread.java:748) [na:1.8.0_162]
```

_references:_
 - [tomcat-relaxed-chars-issue](https://github.com/dirkdeyne/tomcat-relaxed-chars-issue/tree/issue)
 - [stackoverflow](https://stackoverflow.com/questions/51703746/setting-relaxedquerychars-for-embedded-tomcat)
 
## Fix

Make Tomcat's Context attributes _relaxedPathChars_ and _relaxedQueryChars_ configurable in application.properties

references:
 - [fix](https://github.com/dirkdeyne/spring-boot/tree/tomcat-relaxed-chars)
 - [config tomcat 9](https://tomcat.apache.org/tomcat-9.0-doc/config/http.html)

**Comment by wilkinsona** [comment]
Closing in favour of #17510.
