### ISSUE TITLE
SSL handshake fails when client authentication is enabled and starter-jetty is used

### ISSUE THREAD

**Issue by kmailkarthik** [spring-projects/spring-boot#17541]
SSL handshake fails when using embedded jetty and client authentication for incoming requests. 

## Version: 
2.1.6.RELEASE

## Steps to reproduce:
1.  Exclude starter-tomcat and include starter-jetty.
2.  Configure server.ssl.client-auth to NEED
3.  Send a request with client certificate.
4.  Below logs will be seen on server( debug has to be enabled)
```
Caused by: java.security.cert.CertificateException: No subject alternative names matching IP address <redacted> found
	at sun.security.util.HostnameChecker.matchIP(HostnameChecker.java:154) ~[na:1.8.0_40]
	at sun.security.util.HostnameChecker.match(HostnameChecker.java:91) ~[na:1.8.0_40]
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455) ~[na:1.8.0_40]
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:436) ~[na:1.8.0_40]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:252) ~[na:1.8.0_40]
	at sun.security.ssl.X509TrustManagerImpl.checkClientTrusted(X509TrustManagerImpl.java:130) ~[na:1.8.0_40]
	at sun.security.ssl.ServerHandshaker.clientCertificate(ServerHandshaker.java:1835) ~[na:1.8.0_40]
	... 24 common frames omitted
```

5.  Sample project to reproduce the issue.

	https://github.com/kmailkarthik/demo-springboot-issue
	
	
## Root cause:

https://github.com/eclipse/jetty.project/issues/3454
https://github.com/eclipse/jetty.project/issues/3464

## Fix:
Tried to change SslContextFactory to SslContextFactory.Server in below fork and it fixes the issue.

https://github.com/kmailkarthik/spring-boot/tree/2.1.x

**Comment by wilkinsona** [comment]
I noticed this when upgrading to 9.4.15 but may have misdiagnosed the problem. It can be avoided by adding subject alternative names to the certificates  which I did in https://github.com/spring-projects/spring-boot/commit/946e8267a8eadd508edf2ace3baac58ffa5906ba.

**Comment by bbende** [comment]
I'm not totally sure about this, but I think typically only a server certificate would have a SAN, but not a client certificate for an end-user. 

We have a similar issue to what is described in this JIRA and from reading [Jetty 3454](https://github.com/eclipse/jetty.project/issues/3454), they basically made the endpoint identification enabled by default in SSLContextFactory, but its only meant to be used on the client side, but since `SSLContextFactory` is used on both client and server side, it requires the server to disable it. 

Given the above, I was thinking in the [SslServerCustomizer](https://github.com/spring-projects/spring-boot/blob/543fcdbbfdc807dd4cc70934b076756d80e2d21c/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/embedded/jetty/SslServerCustomizer.java#L134) it should probably use `SslContextFactory.Server` and call `contextFactory.setEndpointIdentificationAlgorithm(null);` by default.
