### ISSUE TITLE
Enable spring-boot-devtools  A java.lang.AbstractMethodError exception occurred

### ISSUE THREAD

**Issue by aijnehs** [spring-projects/spring-boot#17569]
Enable spring-boot-devtools causes java.lang.AbstractMethodError exceptions, disable spring-boot-devtools for normal execution.

```
public abstract class EventHandler<T extends Event> {

    public final Class<T> supportedType = Reflections.getGenericClass(getClass());

    abstract void handleEvent(T event);
}
```

```
@Component
public class SendMailEventHandler extends EventHandler<SendMailEvent> {

    private static final Logger LOG = LoggerFactory.getLogger(SendMailEventHandler.class);

    @Autowired
    private JavaMailSenderImpl mailSender;

    @Override
    public void handleEvent(SendMailEvent event) {
        LOG.info("SendMailEvent: {}", event);

        MimeMessageHelper mmh = new MimeMessageHelper(mailSender.createMimeMessage());
        try {
            mmh.setFrom(event.getFrom(), event.getPersonal());
            mmh.setTo(event.getTo());
            mmh.setCc(event.getCc());
            mmh.setBcc(event.getBcc());
            mmh.setSubject(event.getSubject());
            mmh.setText(event.getText(), event.isHtml());
        } catch (UnsupportedEncodingException | MessagingException e) {
            throw new RuntimeException(e);
        }
        mailSender.send(mmh.getMimeMessage());
    }

}
```

```
@Component
public class EventListener implements ApplicationContextAware {

    private static final Logger LOG = LoggerFactory.getLogger(EventListener.class);

    private Map<Class<? extends Event>, String> eventHandlers;
    private ApplicationContext appContext;

    @Autowired
    private EventStorageHandler storageHandler;

    @JmsListener(
            destination = EventSender.DESTINATION_NAME)
    public void processEvent(Event event) {
        LOG.debug("Event: [{}]", event);
        try {
            storageHandler.storageEvent(event);
        } catch (Exception e) {
            LOG.error("Event storage exception: {}", event, e);
        }

        String beanName = eventHandlers.get(event.getClass());
        LOG.debug("EventHander beanName: [{}]", beanName);
        if (null == beanName) {
            LOG.warn("Unsupported event: [{}]", event);
            return;
        }

        @SuppressWarnings("unchecked")
        EventHandler<Event> handler = appContext.getBean(beanName, EventHandler.class);
        LOG.debug("EventHander object: [{}]", handler);
        if (null == handler) {
            LOG.warn("Not found EventHander: [{}]", event);
            return;
        }
        
        try {
            handler.handleEvent(event);
        } catch (AbstractMethodError e) {
            LOG.error("Tip: This exception occurs if Hot Swapping (spring-boot-devtools) is enabled!!!", e);
        }
    }

    @Override
    @SuppressWarnings("unchecked")
    public void setApplicationContext(ApplicationContext appContext) throws BeansException {
        this.appContext = appContext;
        Map<Class<? extends Event>, String> handlers = new HashMap<>();
        appContext.getBeansOfType(EventHandler.class).forEach((beanName,
                handler) -> {
            handlers.put(handler.supportedType, beanName);
            if (LOG.isDebugEnabled()) {
                LOG.debug("EventHandler -> [{}]:[{}]", handler.supportedType.getName(), beanName);
            }
        });
        this.eventHandlers = Collections.unmodifiableMap(handlers);
    }

}
```

2019-07-18 16:57:18.617 DEBUG 11104 --- [enerContainer-1] event.EventListener    : Event: [event.SendMailEvent@5ee91558]
2019-07-18 16:57:18.618 DEBUG 11104 --- [enerContainer-1] event.EventListener    : EventHander beanName: [sendMailEventHandler]
2019-07-18 16:57:18.618 DEBUG 11104 --- [enerContainer-1] event.EventListener    : EventHander object: [event.SendMailEventHandler@39e0f4f9]
2019-07-18 16:57:18.622 ERROR 11104 --- [enerContainer-1] event.EventListener    : Tip: This exception occurs if Hot Swapping (spring-boot-devtools) is enabled!!!
java.lang.AbstractMethodError: event.EventHandler.handleEvent(Lcom/coshine/admin/event/Event;)V
	at event.EventListener.processEvent(EventListener.java:53) ~[ng-admin-core-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_192]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_192]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_192]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_192]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:171) [spring-messaging-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:120) [spring-messaging-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:114) [spring-jms-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:77) [spring-jms-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:736) [spring-jms-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:696) [spring-jms-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674) [spring-jms-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318) [spring-jms-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257) [spring-jms-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1189) [spring-jms-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1179) [spring-jms-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1076) [spring-jms-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_192]

**Comment by bclozel** [comment]
By any chance, is that class defined in another module in your multi-module project?
In that case, [does this section of the reference docs helps](https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-devtools.html#using-boot-devtools-customizing-classload)?

**Comment by aijnehs** [comment]
> 
> 
> By any chance, is that class defined in another module in your multi-module project?
> In that case, [does this section of the reference docs helps](https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-devtools.html#using-boot-devtools-customizing-classload)?

According to the method on the document, the problem has been solved. Thank you.
