### ISSUE TITLE
Using namespaces in Groovy bean configuration

### ISSUE THREAD

**Issue by ChrLipp** [spring-projects/spring-boot#1757]
I try to write a batch application in Groovy using the bean configuration dsl. Whenever I am using a namespace I receive the following exception

```
Caused by: java.lang.NoClassDefFoundError: groovy.xml.StreamingMarkupBuilder
    at org.springframework.beans.factory.groovy.GroovyDynamicElementReader.class$(GroovyDynamicElementReader.groovy)
    at org.springframework.beans.factory.groovy.GroovyDynamicElementReader.$get$$class$groovy$xml$StreamingMarkupBuilder(GroovyDynamicElementReader.groovy)
    at org.springframework.beans.factory.groovy.GroovyDynamicElementReader.invokeMethod(GroovyDynamicElementReader.groovy:75)
    at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:45)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
    at appcontext$_run_closure1.doCall(appcontext.groovy:7)
    at appcontext$_run_closure1.doCall(appcontext.groovy)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
    at groovy.lang.Closure.call(Closure.java:423)
    at groovy.lang.Closure.call(Closure.java:417)
    at org.springframework.beans.factory.groovy.GroovyBeanDefinitionReader.invokeBeanDefiningClosure(GroovyBeanDefinitionReader.java:423)
    at org.springframework.beans.factory.groovy.GroovyBeanDefinitionReader$1.call(GroovyBeanDefinitionReader.java:209)
    at groovy.lang.Closure.call(Closure.java:439)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
    at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1253)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1209)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
    at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
    at appcontext.run(appcontext.groovy:1)
    at groovy.lang.GroovyShell.evaluate(GroovyShell.java:649)
    at org.springframework.beans.factory.groovy.GroovyBeanDefinitionReader.loadBeanDefinitions(GroovyBeanDefinitionReader.java:229)
    ... 12 more
```

I stripped my project down to 3 files to isolate the error:

First, the build.gradle:

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        final SPRING_BOOT_VERSION = '1.1.8.RELEASE'
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${SPRING_BOOT_VERSION}")
    }
}

apply plugin: 'groovy'
apply plugin: 'spring-boot'

// Gradle settings
wrapper {
    gradleVersion = '2.1'
}

// Java settings
sourceCompatibility = 1.7
targetCompatibility = 1.7
jar {
    baseName = 'myproject'
    version =  '0.0.1-SNAPSHOT'
}

// Dependencies
repositories {
    jcenter()
}

dependencies {
    final GROOVY_VERSION = '2.3.7'

    compile "org.codehaus.groovy:groovy:${GROOVY_VERSION}"
    compile 'org.springframework.boot:spring-boot-starter-batch'
}
```

Second my application class:

```
package example

import org.springframework.boot.SpringApplication
import org.springframework.boot.autoconfigure.EnableAutoConfiguration
import org.springframework.context.annotation.ComponentScan
import org.springframework.core.io.ClassPathResource

@ComponentScan
@EnableAutoConfiguration
public class Application
{
    public static void main(String[] args)
    {
        Object[] sources = [Application.class, new ClassPathResource("appcontext.groovy")]
        SpringApplication.run(sources, args)    }
}
```

Third my `appcontext.groovy` file:

```
beans {
    xmlns batch: 'http://www.springframework.org/schema/batch'

    // Job definition
    batch.job(id: 'job1') {
        batch.step(id: 'step1') {
            batch.tasklet {
            }
        }
    }
}
```

Are namespaces not supported or did I make a mistake?

**Comment by tosha9** [comment]
That was exact problem I was running into as well, so simple but created so much pain.
