### ISSUE TITLE
Build sometimes hangs on CI under EmbeddedMongoAutoConfigurationTests

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#17752]
```
Corrupted STDOUT by directly writing to native stream in forked JVM 1. Stream '	at de.flapdoodle.embed.process.runtime.ProcessControl.waitFor(ProcessControl.java:250)'.
Corrupted STDOUT by directly writing to native stream in forked JVM 1. Stream '	at de.flapdoodle.embed.mongo.AbstractMongoProcess.onAfterProcessStart(AbstractMongoProcess.java:78)'.
Corrupted STDOUT by directly writing to native stream in forked JVM 1. Stream '	at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:116)'.
Corrupted STDOUT by directly writing to native stream in forked JVM 1. Stream '	at de.flapdoodle.embed.mongo.AbstractMongoProcess.<init>(AbstractMongoProcess.java:53)'.
Corrupted STDOUT by directly writing to native stream in forked JVM 1. Stream '	at de.flapdoodle.embed.mongo.MongodProcess.<init>(MongodProcess.java:50)'.
Corrupted STDOUT by directly writing to native stream in forked JVM 1. Stream '	at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:44)'.
Corrupted STDOUT by directly writing to native stream in forked JVM 1. Stream '	at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:34)'.
Corrupted STDOUT by directly writing to native stream in forked JVM 1. Stream '	at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:108)'.
Corrupted STDOUT by directly writing to native stream in forked JVM 1. Stream '	- locked <0x00000000fd103430> (a de.flapdoodle.embed.mongo.MongodExecutable)'.
Corrupted STDOUT by directly writing to native stream in forked JVM 1. Stream '	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)'.
Corrupted STDOUT by directly writing to native stream in forked JVM 1. Stream '	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)'.
Corrupted STDOUT by directly writing to native stream in forked JVM 1. Stream '	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)'.
Corrupted STDOUT by directly writing to native stream in forked JVM 1. Stream '	at java.lang.reflect.Method.invoke(Method.java:498)'.
Corrupted STDOUT by directly writing to native stream in forked JVM 1. Stream '	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1932)'.
Corrupted STDOUT by directly writing to native stream in forked JVM 1. Stream '	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1874)'.
```

**Comment by wilkinsona** [comment]
I've haven't seen this recently. Let's close for now and we can re-open if the problem reappears.
