### ISSUE TITLE
JsonParseException: Trying to read past EOF.

### ISSUE THREAD

**Issue by neilxliu** [spring-projects/spring-boot#17809]
version: 2.1.6-RELEASE
description: query data from mongo by MongoRepository. I use @Query on query statement like "@Query("'requestContent.requestKey':{'$regex':?1,'$options':'i'}}")"
Error occurs when there is no space behind comma
log:
Caused by: org.bson.json.JsonParseException: Trying to read past EOF.
	at org.bson.json.JsonBuffer.read(JsonBuffer.java:39) ~[bson-3.8.2.jar:na]
	at org.bson.json.JsonScanner.nextToken(JsonScanner.java:61) ~[bson-3.8.2.jar:na]
	at org.bson.json.JsonReader.popToken(JsonReader.java:492) ~[bson-3.8.2.jar:na]
	at org.bson.json.JsonReader.readBsonType(JsonReader.java:130) ~[bson-3.8.2.jar:na]
	at org.bson.codecs.DocumentCodec.decode(DocumentCodec.java:149) ~[bson-3.8.2.jar:na]
	at org.bson.codecs.DocumentCodec.decode(DocumentCodec.java:45) ~[bson-3.8.2.jar:na]
	at org.bson.codecs.DocumentCodec.readValue(DocumentCodec.java:222) ~[bson-3.8.2.jar:na]
	at org.bson.codecs.DocumentCodec.decode(DocumentCodec.java:151) ~[bson-3.8.2.jar:na]
	at org.bson.codecs.DocumentCodec.decode(DocumentCodec.java:45) ~[bson-3.8.2.jar:na]
	at org.bson.Document.parse(Document.java:105) ~[bson-3.8.2.jar:na]
	at org.bson.Document.parse(Document.java:90) ~[bson-3.8.2.jar:na]
	at org.springframework.data.mongodb.core.query.BasicQuery.<init>(BasicQuery.java:67) ~[spring-data-mongodb-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.data.mongodb.repository.query.StringBasedMongoQuery.createQuery(StringBasedMongoQuery.java:140) ~[spring-data-mongodb-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.data.mongodb.repository.query.AbstractMongoQuery.execute(AbstractMongoQuery.java:85) ~[spring-data-mongodb-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:605) ~[spring-data-commons-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.lambda$invoke$3(RepositoryFactorySupport.java:595) ~[spring-data-commons-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:595) ~[spring-data-commons-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59) ~[spring-data-commons-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61) ~[spring-data-commons-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]

**Comment by snicoll** [comment]
@neilxliu the issue template you've read before creating this issue states

> 🐞 Bug report (please don't include this emoji/text, just add your details)

So please don't.

I am a surprised by the low-level exception there and it's hard to say if it's a Spring Data issue. We can figure this out if you create an issue [in the appropriate issue tracker](https://jira.spring.io/projects/DATAMONGO) with a small sample that the team can run themselves (not code in text, but a github project or a zip they can download and run).
