### ISSUE TITLE
NPE in BuildInfoMojo when running under eclipse

### ISSUE THREAD

**Issue by purnhar** [spring-projects/spring-boot#17810]
After switching from spring-boot 2.2.0.M4 to 2.2.0.M4 it comes to an NPE when building the my in eclipse (STS 4.3.1.RELEASE). Building at the command line directly with maven 3.6.1 on the command line works totally perfect.

```
null (org.springframework.boot:spring-boot-maven-plugin:2.2.0.M5:build-info:default:generate-resources)

org.apache.maven.plugin.MojoExecutionException
	at org.springframework.boot.maven.BuildInfoMojo.execute(BuildInfoMojo.java:97)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:333)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.lambda$7(MavenImpl.java:1380)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1379)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:52)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:137)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:173)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1$1.call(MavenBuilder.java:116)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:106)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:87)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:201)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:833)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.NullPointerException
	at org.springframework.boot.maven.BuildInfoMojo.getBuildTime(BuildInfoMojo.java:103)
	at org.springframework.boot.maven.BuildInfoMojo.execute(BuildInfoMojo.java:89)
	... 31 more
```

It seems to be related to the following commit: [https://github.com/spring-projects/spring-boot/commit/74d00354f52fdd5191dc5d7e1b54b84d370a0fbb#diff-cffe2e29d4d313b7333e5b12197f2a8a](url)

My configuration of the spring-boot-maven-plugin is as follows:

```
<plugin>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-maven-plugin</artifactId>
	<executions>
		<execution>
			<goals>
				<goal>build-info</goal>
			</goals>
		</execution>
	</executions>
</plugin>
````

As a workaround i could include `<time>off</time>` in my configuration, but thats not what I want to achieve.

**Comment by snicoll** [comment]
Thanks for trying the milestone and reporting the issue. It looks like that the `MavenSession` has a different state when it runs in Eclipse. This might be the reason why we were resorting to a simpler solution before

**Comment by snicoll** [comment]
`this.session.getRequest().getStartTime()` returns `null` when Eclipse runs maven embedded. I guess we can use the previous value as a fallback in this case.

**Comment by glandais-eptica** [comment]
A temporary solution is to add `<time>${build.timestamp}</time>` in plugin configuration
