### ISSUE TITLE
Issue: inability to force shell-type application. App is detected as webapp even under main

### ISSUE THREAD

**Issue by djechelon** [spring-projects/spring-boot#17945]
This *issue* can be also seen as a *request for feature*, read more.

# Summary
Spring Boot decides if the application context is for a web application by testing the classpath.
According to [SpringApplication](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/SpringApplication.java#L271), the decision is made on whether certain "indicator" classes are present in the classpath, regardless of whether the Spring Boot main application class is annotated `@EnableWebMvc` or not.

Since I have a number of web-related dependencies in my classpath, even if not using the web features, Spring incorrectly thinks that my Main class is running inside a servlet container.

# Scenario details
I am upgrading a web+shell project from Spring 4 and Spring Shell 1 to Spring 5 and Spring Shell 2, which is based on Spring Boot.

The legacy application has a single monolithic code base, so no time (read, budget) to refactor.
The legacy application has an entire `src` dir full of classes for the web part, and is currently started as web application. It also features a few Main classes, one of which is used as our main shell entry-point, so that when we package the app as a jar, we can run and use important shell commands that are required to set up an environment prior to launching the real web app.

About dependencies, we currently use Ant/Ivy (again, no time to move to Gradle), so that all dependencies are downloaded to `WEB-INF/lib` directory. I inherited the dependencies, so there is a mix (read, mess) of dependencies, all into `WEB-INF/lib`, these **include** Spring MVC.

Project-level solutions to the problem including splitting the project into modules, correctly handle dependencies and configurations, but it is currently impossible

# Main application

```
@SpringBootApplication(scanBasePackages = {//
    "com.acme.core.shell"//
})
@ImportResource(value = { //
    "classpath*:META-INF/context/data-context.xml", //
    "classpath*:META-INF/context/services-context.xml", //
    "classpath*:META-INF/context/shell/*-context.xml"//
})
@Profile(CachingInitializer.PROFILE_CACHING_DISABLED)
public class MainShell
{
    public static void main(String[] args) throws IOException
    {
        String configLocation = System.getProperty(CFG_LOCATION_PROP);

        if (isBlank(configLocation))
            throw new IllegalStateException(CFG_LOCATION_PROP + ": System property not initialized!");

        MainShell.setConfigLocation(configLocation);

        // Init logger ASAP
        InitLogger.initializeLog4j(configLocation);

        run(MainShell.class, args);
    }

}

```

# Error detail

```
org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.context.ApplicationContextException: Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean.
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:155) ~[spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:742) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:389) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1213) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1202) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at com.acme.core.MainShell.main(MainShell.java:69) [project/:?]
Caused by: org.springframework.context.ApplicationContextException: Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean.
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getWebServerFactory(ServletWebServerApplicationContext.java:202) ~[spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:178) ~[spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:152) ~[spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	... 8 more

```

# Report for issue

Maybe, scanning for the type of application by analysing the classpath is a bit tricky and adds constraints. Obviously, one should not include `spring-webmvc` dependency into a non-web project. But either you inherited that, or you just want that fantastic super-fancy remote utility class handy. I mean, forcing to remove certain dependencies to run an app is a bit odd.

# Request for new feature

It should be possible to force the nature of the Spring application type if the detection criteria cannot be changed.

So, I have reported this ticket in two different views. I would like to hear from the maintainers

**Comment by wilkinsona** [comment]
This is already possible by setting the web application type on your `SpringApplication`. Please see the [reference documentation](https://docs.spring.io/spring-boot/docs/2.1.x/reference/htmlsingle/#howto-create-a-non-web-application) for further details.
