### ISSUE TITLE
Spring-web compatibility issues after upgrading from 2.1.3 to 2.1.7

### ISSUE THREAD

**Issue by 1988andy** [spring-projects/spring-boot#18135]
When I upgraded the spring-boot version from 2.1.3 to 2.1.7, I found that the spring-web version was upgraded from 5.1.5 to 5.1.9. However, when I deployed the project to the server and started tomcat, an error occurred:

2) the document could not be read; 
3) the root element of the document is not <xsd:schema>.
org.xml.sax.SAXParseException; systemId: jar:file:/opt/apache-tomcat-8.5.33_1/webapps/.../WEB-INF/lib/spring-web-5.1.9.RELEASE.jar!/META-INF/web-fragment.xml; lineNumber: 5; columnNumber: 41; schema_reference.4: Failed to read schema document 'https://java.sun.com/xml/ns/javaee/web-fragment_3_0.xsd', because 
1) could not find the document; 
2) the document could not be read; 
3) the root element of the document is not <xsd:schema>.
at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.warning(ErrorHandlerWrapper.java:99)
at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:392)
at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.findSchemaGrammar(XMLSchemaValidator.java:2451)
at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1768)
at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:741)
at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:613)
at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:31

================================================================

The pom.xml file starts like this:
<? The XML version = "1.0" encoding = "utf-8"? >
The < project XMLNS = "http://maven.apache.org/POM/4.0.0" XMLNS: xsi = "http://www.w3.org/2001/XMLSchema-instance"
Xsi: schemaLocation = "http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" >

================================================================

What is the reason for this, or how can I change it to upgrade correctly?

**Comment by philwebb** [comment]
This looks like a bug cause by [this commit](https://github.com/spring-projects/spring-framework/commit/8f77b7366e641af3712c06de77f4baf2714773e9#diff-62f84b3cb725cde35ae2dca3ec8ae924) in Spring Framework which changed `http` to `https`.

I'll transfer the issue to that team for them to look at.
