### ISSUE TITLE
After migrating code to Grails 3.3, FilterRegistrationBean not found error during runtime

### ISSUE THREAD

**Issue by manishb-socialcurry** [spring-projects/spring-boot#18204]
Operating System: Windows 7
GORM Version: 6.1.9.RELEASE
Grails Version: 3.3.8 (therefore, Spring boot 1.5)
JDK Version: 1.8.0_131
Gradle Version: 4.10.3 (As I learnt that Grails 3.3.x is compatible with Gradle 4.x)

After migrating my application from Grails 2.4.3 to Grails 3.3.8 and using the new spring security plugin, while compilation of Java/Groovy files and war assembly go okay, I get the FilterRegistrationBean not found error during deployment.

As you can see from my build.gradle, I am using the following versions of spring security plugins: "org.grails.plugins:spring-security-core:3.2.1" and "org.grails.plugins:spring-security-ui:3.1.1" I have tried all other combinations possible. Like, 3.2.3 of spring-security-core and 3.1.2 of spring-security-ui. I know that Spring boot 1.5 that is used by Grails 3.3.x has moved the FilterRegistrationBean to a different package. One place where I declare this bean (resources.groovy), I am using the new package. Still, I get FilterRegistrationBean class not found error and I just cannot figure out why.

I am including list of all plug-ins that I use. Could one of those plug-ins have a problem with its current version that I am using? Please help.

build.gradle:

```
dependencyManagement {
    imports {
        mavenBom "org.grails:grails-bom:3.3.8"
    }
    applyMavenExclusions false
}

dependencies {
    compile "org.grails:grails-core"
    compile "org.springframework.boot:spring-boot-starter-logging"
    compile "org.springframework.boot:spring-boot-starter-actuator"
    compile "org.springframework.boot:spring-boot-autoconfigure"
    compile "org.springframework.boot:spring-boot-starter-tomcat"

    compile "org.grails:grails-logging"
    compile "org.grails:grails-plugin-rest"
    compile "org.grails:grails-plugin-databinding"
    compile "org.grails:grails-plugin-i18n"
    compile "org.grails:grails-plugin-services"
    compile "org.grails:grails-plugin-url-mappings"
    compile "org.grails:grails-plugin-interceptors"

    compile "org.grails:grails-dependencies"
    compile "org.grails:grails-web-boot"
    runtime "org.springframework:spring-test"
    compile "org.apache.httpcomponents:httpcore"
    compile "org.apache.httpcomponents:httpclient"

    compile "org.grails.plugins:gsp"

//      compile 'org.grails.plugins:audit-logging:2.0.6'

    compile "org.grails.plugins:scaffolding"
    compile "org.grails.plugins:cache"

    compile "commons-io:commons-io:2.4"
    compile "org.xhtmlrenderer:flying-saucer-pdf-itext5:9.1.18"
    compile "org.grails.plugins:joda-time:2.1.0"
    compile "org.grails.plugins:quartz-monitor:1.3"
    compile "org.grails.plugins:remote-pagination:0.5.0"
    compile "org.grails.plugins:ckeditor:4.5.9.0"
    compile "org.grails.plugins:grails-pretty-time:4.0.0"
    compile 'com.bertramlabs.plugins:karman-grails:1.2.1'
    compile "org.grails.plugins:asynchronous-mail:2.0.2"

    compile "org.grails.plugins:asset-pipeline:3.2.1"

    compile "org.grails.plugins:spring-security-core:3.2.1"
    compile "org.grails.plugins:spring-security-ui:3.1.1"

    compile "mysql:mysql-connector-java:5.1.24"

    compile "org.grails.plugins:hibernate5"
    compile "org.hibernate:hibernate-core:5.1.5.Final"
    compile "org.hibernate:hibernate-ehcache:5.1.5.Final"
    compile ("org.grails.plugins:cache-ehcache:3.0.0.M1") {
        exclude group:'net.sf.ehcache'
    }
    compile "net.sf.ehcache:ehcache:2.4.3"

    compile "org.grails.plugins:aws-sdk:1.10.74"
    compile 'org.grails.plugins:converters:4.0.0'
    compile "org.grails.plugins:html-cleaner:3.0.0.1"

    // The following has been separated out in grails 3.3
    compile "org.grails:grails-datastore-gorm-async:6.1.9.RELEASE"

    // plugins needed at runtime
    runtime('org.grails.plugins:rendering:2.0.3', {
        //exclude group: '', module: ''
        //excludes 'itext','itext-rtf'
    })

    runtime "org.grails.plugins:events:4.0.0"
    runtime 'org.grails.plugins:aws-sdk:1.10.74'
    runtime "org.grails.plugins:database-migration:3.0.4"

    // plugin needed to use TLD files for JSP taglibs
    runtime "org.grails:grails-web-jsp"
    runtime "org.grails.plugins:hibernate5"
    runtime "org.hibernate:hibernate-core:5.1.5.Final"
    runtime "org.hibernate:hibernate-ehcache:5.1.5.Final"
    runtime "mysql:mysql-connector-java:5.1.24"

    testCompile "org.grails.plugins:geb:1.1.4"
    testCompile "org.grails:grails-test-mixins:3.3.0"
    testCompile "org.grails.plugins:hibernate5"
    testCompile "org.hibernate:hibernate-core:5.1.5.Final"
    testCompile "org.hibernate:hibernate-ehcache:5.1.5.Final"
    testCompile "mysql:mysql-connector-java:5.1.24"

    console "org.grails:grails-console"
}
grails {
    pathingJar = true
}

bootRun {
    jvmArgs('-Dspring.output.ansi.enabled=always')
    addResources = true
}
```

resources.groovy:

```
import org.springframework.web.filter.CharacterEncodingFilter
import org.springframework.context.support.ConversionServiceFactoryBean
import org.springframework.boot.web.servlet.FilterRegistrationBean
import org.springframework.core.Ordered

// Place your Spring DSL code here

beans = {

    springConfig.addAlias "springSecurityService", "springSecurityCoreSpringSecurityService"

    characterEncodingFilter(CharacterEncodingFilter) {
        encoding = "utf-8"
    }

    conversionService(ConversionServiceFactoryBean)

    charEncodingFilter(FilterRegistrationBean) {
        filter = characterEncodingFilter
        urlPatterns = ['/*']
        order = Ordered.HIGHEST_PRECEDENCE
    }
}

```

Stacktrace:

```
2019-09-07 17:11:39,119 [main] DEBUG g.c.DefaultGrailsApplication - Going to inspect artefact classes.
2019-09-07 17:11:53,396 [main] ERROR o.s.b.SpringApplication - Application startup failed
java.lang.NoClassDefFoundError: org/springframework/boot/context/embedded/FilterRegistrationBean
    at asset.pipeline.AssetPipelineGrailsPlugin$_doWithSpring_closure2.doCall(AssetPipelineGrailsPlugin.groovy:121)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1427)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
    at groovy.lang.Closure.call(Closure.java:418)
    at groovy.lang.Closure.call(Closure.java:412)
    at grails.spring.BeanBuilder.invokeBeanDefiningClosure(BeanBuilder.java:759)
    at grails.spring.BeanBuilder.beans(BeanBuilder.java:588)
    at grails.spring.BeanBuilder.invokeMethod(BeanBuilder.java:531)
    at org.grails.plugins.DefaultGrailsPlugin.doWithRuntimeConfiguration(DefaultGrailsPlugin.java:559)
    at org.grails.plugins.AbstractGrailsPluginManager.doRuntimeConfiguration(AbstractGrailsPluginManager.java:167)
    at grails.boot.config.GrailsApplicationPostProcessor.postProcessBeanDefinitionRegistry(GrailsApplicationPostProcessor.groovy:171)
    at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:272)
    at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:122)
    at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:525)
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
    at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
    at grails.boot.GrailsApp.run(GrailsApp.groovy:84)
    at grails.boot.GrailsApp.run(GrailsApp.groovy:393)
    at grails.boot.GrailsApp.run(GrailsApp.groovy:380)
    at grails.boot.GrailsApp$run.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
    at ite.baseline.Application.main(Application.groovy:8)
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.context.embedded.FilterRegistrationBean
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 34 common frames omitted
```

**Comment by wilkinsona** [comment]
That's the wrong package for `FilterRegistrationBean` in Spring Boot 1.5. The correct package is `org.springframework.boot.web.servlet`. I would guess that you have a dependency that is referencing the old package. This is out of Spring Boot's control.

Please note that Spring Boot 1.5 has [now reached end of life](https://spring.io/blog/2019/08/06/it-is-time-goodbye-spring-boot-1-x) and is no longer supported. I'd recommend skipping Grails 3 and upgrading to Grails 4 which is based on Spring Boot 2.x.
