### ISSUE TITLE
custom URLClassLoader can not reload the updated jar file

### ISSUE THREAD

**Issue by shidongwa** [spring-projects/spring-boot#18300]
I customize my own URLClassLoader in my spring boot application.  My URLClassLoader reload the updated jar file by addURL and close api.  I updated jar file manually right now and I hope to see the updated result from the spring MVC controller endpoint. Please see the code below.

This works as expected if I build and deploy the spring boot application to Jetty as WAR; but if I run the WAR in jar way (java -jar demo.war), I get ClassFormatError as below.

I guess it is related to Spring Boot's customization on JarFile Protocol.  I tested in two ways:
- launch in WAR way, I got the expected result. when I updated the test.jar and accessed the endpoint, the result updated as well.
I ran my test in cmdline like 
`
java -cp jetty-runner-9.4.14.v20181114.jar org.eclipse.jetty.runner.Runner  demo.war
`  or put demo.war under webapps dir of jetty-distribution-9.4.6.v20170531 directly.

below is console output

> jarURLConnection:sun.net.www.protocol.jar.JarURLConnection:jar:file:/tmp/test.jar!/

> handlers:

- launch in spring boot jar way, I got the ClassFormatError after I updated test.jar manually.
I ran my test in cmdline line like
`
java -jar demo.war
`

below is the console output

>jarURLConnection:org.springframework.boot.loader.jar.JarURLConnection:jar:file:/tmp/test.jar!/

> handlers:org.springframework.boot.loader

so the difference is when jarfile loaded in "org.springframework.boot.loader" way, my customized ClassLoader can't reload the updated jar dynamically. My question is :
for spring boot ClassLoader I can understand it uses new jarfile protocal and handlers; but for my customized URLClassLoader, is it possible NOT to use or disable this handlers?

my test environment is as below:
- mac
- JDK 8
- spring boot 2.1.8.RELEASE
- jetty 9.4.19.v20190610

**ClassFormatError**

```
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.ClassFormatError: Truncated class file
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1054) ~[spring-webmvc-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) ~[spring-webmvc-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) ~[spring-webmvc-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897) ~[spring-webmvc-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:645) ~[javax.servlet-api-4.0.1.jar!/:4.0.1]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882) ~[spring-webmvc-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750) ~[javax.servlet-api-4.0.1.jar!/:4.0.1]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:876) ~[jetty-servlet-9.4.19.v20190610.jar!/:9.4.19.v20190610]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623) ~[jetty-servlet-9.4.19.v20190610.jar!/:9.4.19.v20190610]
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:214) ~[websocket-server-9.4.19.v20190610.jar!/:9.4.19.v20190610]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610) ~[jetty-servlet-9.4.19.v20190610.jar!/:9.4.19.v20190610]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) ~[spring-web-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610) ~[jetty-servlet-9.4.19.v20190610.jar!/:9.4.19.v20190610]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92) ~[spring-web-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) ~[spring-web-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610) ~[jetty-servlet-9.4.19.v20190610.jar!/:9.4.19.v20190610]
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) ~[spring-web-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) ~[spring-web-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610) ~[jetty-servlet-9.4.19.v20190610.jar!/:9.4.19.v20190610]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) ~[spring-web-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) ~[spring-web-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610) ~[jetty-servlet-9.4.19.v20190610.jar!/:9.4.19.v20190610]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540) ~[jetty-servlet-9.4.19.v20190610.jar!/:9.4.19.v20190610]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146) ~[jetty-server-9.4.19.v20190610.jar!/:9.4.19.v20190610]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) ~[jetty-security-9.4.19.v20190610.jar!/:9.4.19.v20190610]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) ~[jetty-server-9.4.19.v20190610.jar!/:9.4.19.v20190610]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257) ~[jetty-server-9.4.19.v20190610.jar!/:9.4.19.v20190610]
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1711) ~[jetty-server-9.4.19.v20190610.jar!/:9.4.19.v20190610]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) ~[jetty-server-9.4.19.v20190610.jar!/:9.4.19.v20190610]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1347) ~[jetty-server-9.4.19.v20190610.jar!/:9.4.19.v20190610]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203) ~[jetty-server-9.4.19.v20190610.jar!/:9.4.19.v20190610]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480) ~[jetty-servlet-9.4.19.v20190610.jar!/:9.4.19.v20190610]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1678) ~[jetty-server-9.4.19.v20190610.jar!/:9.4.19.v20190610]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201) ~[jetty-server-9.4.19.v20190610.jar!/:9.4.19.v20190610]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1249) ~[jetty-server-9.4.19.v20190610.jar!/:9.4.19.v20190610]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144) ~[jetty-server-9.4.19.v20190610.jar!/:9.4.19.v20190610]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) ~[jetty-server-9.4.19.v20190610.jar!/:9.4.19.v20190610]
        at org.eclipse.jetty.server.Server.handle(Server.java:505) ~[jetty-server-9.4.19.v20190610.jar!/:9.4.19.v20190610]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370) ~[jetty-server-9.4.19.v20190610.jar!/:9.4.19.v20190610]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267) [jetty-server-9.4.19.v20190610.jar!/:9.4.19.v20190610]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305) [jetty-io-9.4.19.v20190610.jar!/:9.4.19.v20190610]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [jetty-io-9.4.19.v20190610.jar!/:9.4.19.v20190610]
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117) [jetty-io-9.4.19.v20190610.jar!/:9.4.19.v20190610]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781) [jetty-util-9.4.19.v20190610.jar!/:9.4.19.v20190610]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917) [jetty-util-9.4.19.v20190610.jar!/:9.4.19.v20190610]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
Caused by: java.lang.ClassFormatError: Truncated class file
        at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_171]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[na:1.8.0_171]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_171]
 at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[na:1.8.0_171]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_171]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[na:1.8.0_171]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[na:1.8.0_171]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_171]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[na:1.8.0_171]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_171]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_171]
        at com.stone.jdk.demohotswap.DemoHotswapApplication.swap(DemoHotswapApplication.java:64) ~[classes!/:0.0.1-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104) ~[spring-webmvc-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892) ~[spring-webmvc-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039) ~[spring-webmvc-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        ... 46 common frames omitted
```

**controller api endpoint**

```
package com.stone.jdk.demohotswap;

import com.stone.jdk.demohotswap.classloader.MyClassLoader;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.lang.reflect.Method;
import java.net.JarURLConnection;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.Date;

@SpringBootApplication
@RestController
public class DemoHotswapApplication extends SpringBootServletInitializer {
    private static final String PROTOCOL_HANDLER = "java.protocol.handler.pkgs";

    public static void main(String[] args) {
        SpringApplication.run(DemoHotswapApplication.class, args);
    }

    @Override
    protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
        return application.sources(DemoHotswapApplication.class);
    }

    @RequestMapping("/")
    public String index() {
        return "Hello Mr Swap!";
    }

    @RequestMapping("/swap")
    public String swap() {
        MyClassLoader cl = new MyClassLoader();

        String jarFile = String.format("jar:file:%s/%s!/", "/tmp", "test.jar");
        try {
            URL jarUrl = new URL(jarFile);
            cl.addURL(jarUrl);
        } catch (Exception e) {
            e.printStackTrace();
        }

        URL[] urls = cl.getURLs();
        if(urls != null && urls.length > 0) {
            try {
                // Create a jar URL connection object
                JarURLConnection jarURLConnection = (JarURLConnection) urls[0].openConnection();
                System.out.println("jarURLConnection:" + jarURLConnection);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }

        String handlers = System.getProperty(PROTOCOL_HANDLER, "");
        System.out.println("handlers:" + handlers);

        String output = "NA";
        try {
            Class<?> swapClass = cl.loadClass("com.stone.jdk.demohotswap.swapClass.SwapMe");
            Object plugin = swapClass.newInstance();
            Method method = swapClass.getMethod("hello");
            output = (String)method.invoke(plugin);
            System.out.println("output:" + output);
        } catch (Exception ex) {
            ex.toString();
        } finally {
            try {
                cl.close();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }

        return String.format("%s - %s", output,
                new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.sss").format(new Date()));
    }
}
```

**Comment by shidongwa** [comment]
- unzip demo.zip and get demo.war

[demo.zip](https://github.com/spring-projects/spring-boot/files/3639383/demo.zip)

- unzip test.zip and you'll get test-before.jar and test-after.jar, please rename to test.jar and put to /tmp dir for testing.

[test.zip](https://github.com/spring-projects/spring-boot/files/3639384/test.zip)

**Comment by shidongwa** [comment]
you can review the test code from https://github.com/shidongwa/demo-hotswap, thanks.

**Comment by wilkinsona** [comment]
This appears to be a previously unconsidered variant of https://github.com/spring-projects/spring-boot/issues/15964.

**Comment by shidongwa** [comment]
> This appears to be a previously unconsidered variant of #15964.

thanks for your time. yes,  #15964 describes the root cause. But my case is a little different. The issue happens in my customized ClassLoader and jar file, which i think it is isolated from spring boot LaunchedClassLoader.  Is it possible to workaround this issue please?

**Comment by wilkinsona** [comment]
You could try specifying an instance of `sun.net.www.protocol.jar.Handler` as the `URLStreamHandler` when you create the `URL` that is added to your custom `ClassLoader`:

```java
URL jarUrl = new URL(null, jarFile, new sun.net.www.protocol.jar.Handler());
cl.addURL(jarUrl);
```

**Comment by shidongwa** [comment]
> You could try specifying an instance of `sun.net.www.protocol.jar.Handler` as the `URLStreamHandler` when you create the `URL` that is added to your custom `ClassLoader`:
> 
> ```java
> URL jarUrl = new URL(null, jarFile, new sun.net.www.protocol.jar.Handler());
> cl.addURL(jarUrl);
> ```

thanks Andy. It works.

**Comment by wilkinsona** [comment]
Great. Thanks for trying it. As indicated in https://github.com/spring-projects/spring-boot/issues/15964, changing our handler to support this use case would add a significant amount of complexity and I suspect it would hurt performance as well. As such, I'm going to close this issue now that we now that using `sun.net.www.protocol.jar.Handler()` works in your case.
