### ISSUE TITLE
"factory already defined" error with spring-boot-maven-plugin in maven multi-module application 

### ISSUE THREAD

**Issue by asif-anwar** [spring-projects/spring-boot#18467]
We have few live tests in multiple Spring Boot applications. To run the live test, we use _spring-boot-maven-plugin_ to _start_ embedded Tomcat in the _pre-integration-test_ phase and _stop_ it in the _post-integration-test_ phase.

Individual modules work fine, but if we run the build from the parent POM, the 2nd module fails to start Tomcat with _factory already defined_ error.

Boot version: 2.1.8
Here is a sample application to re-produce the issue: [sample-project.zip](https://github.com/spring-projects/spring-boot/files/3677241/sample-project.zip)

Here is the _spring-boot-maven-plugin_ configuration (same in both the child modules):

```
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <executions>
        <execution>
            <id>pre-integration-test</id>
            <goals>
                 <goal>start</goal>
             </goals>
         </execution>
         <execution>
            <id>post-integration-test</id>
            <goals>
               <goal>stop</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```
And here is the Exception:

```
Caused by: java.lang.Error: factory already defined
	at java.net.URL.setURLStreamHandlerFactory(URL.java:1112) ~[na:1.8.0_201]
	at org.apache.catalina.webresources.TomcatURLStreamHandlerFactory.<init>(TomcatURLStreamHandlerFactory.java:130) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.catalina.webresources.TomcatURLStreamHandlerFactory.getInstanceInternal(TomcatURLStreamHandlerFactory.java:53) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.catalina.webresources.TomcatURLStreamHandlerFactory.register(TomcatURLStreamHandlerFactory.java:77) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.catalina.webresources.StandardRoot.registerURLStreamHandlerFactory(StandardRoot.java:701) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.catalina.webresources.StandardRoot.initInternal(StandardRoot.java:683) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	... 45 common frames omitted
```

**Comment by wilkinsona** [comment]
Thanks for the sample. You need to configure your build so that each app is started in a separate JVM and to use different ports for the JMX communication between the Maven JVM and the app's JVM:

```
<configuration>
    <fork>true</fork>
    <jmxPort>9000</jmxPort>
</configuration>
```

```
<configuration>
    <fork>true</fork>
    <jmxPort>9001</jmxPort>
</configuration>
```

**Comment by asif-anwar** [comment]
Thanks.
