### ISSUE TITLE
Spring Boot 2.2: Loading of QuartzAutoConfiguration class fails

### ISSUE THREAD

**Issue by hannespr** [spring-projects/spring-boot#18722]
After having migrated from Spring Boot 2.1.9 to Spring Boot 2.2.0, I am getting the following error on application start: 
```
java.lang.IncompatibleClassChangeError: org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration and org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$SchedulerDependsOnBeanFactoryPostProcessor disagree on InnerClasses attribute
	at java.lang.Class.getDeclaringClass0(Native Method)
	at java.lang.Class.getDeclaringClass(Class.java:1235)
	at java.lang.Class.getEnclosingClass(Class.java:1277)
	at org.springframework.core.annotation.AnnotationsScanner.processClassHierarchy(AnnotationsScanner.java:233)
	at org.springframework.core.annotation.AnnotationsScanner.processClassHierarchy(AnnotationsScanner.java:194)
	at org.springframework.core.annotation.AnnotationsScanner.processClass(AnnotationsScanner.java:130)
	at org.springframework.core.annotation.AnnotationsScanner.process(AnnotationsScanner.java:107)
	at org.springframework.core.annotation.AnnotationsScanner.scan(AnnotationsScanner.java:97)
	at org.springframework.core.annotation.AnnotationsScanner.scan(AnnotationsScanner.java:78)
	at org.springframework.core.annotation.TypeMappedAnnotations.scan(TypeMappedAnnotations.java:242)
	at org.springframework.core.annotation.TypeMappedAnnotations.isPresent(TypeMappedAnnotations.java:98)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBean$BindMethod.isConstructorBindingType(ConfigurationPropertiesBean.java:308)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBean$BindMethod.forClass(ConfigurationPropertiesBean.java:300)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBeanDefinitionValidator.validate(ConfigurationPropertiesBeanDefinitionValidator.java:57)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBeanDefinitionValidator.postProcessBeanFactory(ConfigurationPropertiesBeanDefinitionValidator.java:45)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:286)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:174)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:706)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140)
```

Another application, which is also using the `QuartzAutoConfiguration` and Spring Boot 2.2.0 is starting without problems on the same machine (with the same JDK).

FYI:
```
$java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b05)
OpenJDK 64-Bit Server VM (build 25.222-b05, mixed mode)
```

**Comment by wilkinsona** [comment]
There appears to be a problem with the classpath of the application that is failing, but I can't tell what that is from a stacktrace alone. Can you please launch your application with `-verbose:class` and share the output, particularly the lines related to `QuartzAutoConfiguration` and its inner classes.

**Comment by hannespr** [comment]
Thanks for your quick reply!
I did a `grep QuartzAutoConfiguration` on the output of `bootRun` Gradle-task with `-verbose:class` to filter only these lines. If you need more context, please let me know.

```
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration from file:/home/hannesb/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-autoconfigure/2.2.0.RELEASE/1b3304eec25bb9860bd091a31133e3fe139fcab6/spring-boot-autoconfigure-2.2.0.RELEASE.jar]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$SchedulerDependsOnBeanFactoryPostProcessor from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration from file:/home/hannesb/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-autoconfigure/2.2.0.RELEASE/1b3304eec25bb9860bd091a31133e3fe139fcab6/spring-boot-autoconfigure-2.2.0.RELEASE.jar]
[Unloading class org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration 0x00000007c1139028]
[Unloading class org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration 0x00000007c1138828]
[Unloading class org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration 0x00000007c1138028]
[Unloading class org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration 0x00000007c0fbc028]
[Unloading class org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration 0x00000007c0fba828]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Unloading class org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration 0x00000007c1214828]
[Unloading class org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration 0x00000007c1183028]
[Unloading class org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration 0x00000007c107a828]
[Unloading class org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration 0x00000007c0f7c828]
[Unloading class org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration 0x00000007c0decc28]
[Unloading class org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration 0x00000007c0d5a428]
[Unloading class org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration 0x00000007c0cc8c28]
[Unloading class org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration 0x00000007c0ae4828]
[Unloading class org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration 0x00000007c0a54028]
[Unloading class org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration 0x00000007c09c4828]
[Unloading class org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration 0x00000007c0829c28]
[Unloading class org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration 0x00000007c067ac28]
[Unloading class org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration 0x00000007c0403c28]
[Unloading class org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration 0x00000007c0438428]
[Unloading class org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration 0x00000007c04c4c28]
[Unloading class org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration 0x00000007c055c428]
[Unloading class org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration 0x00000007c06f2c28]
[Unloading class org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration 0x00000007c078a028]
[Unloading class org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration 0x00000007c08dbc28]
[Unloading class org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration 0x00000007c0b19c28]
[Unloading class org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration 0x00000007c0ba9c28]
[Unloading class org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration 0x00000007c0e0a028]
[Unloading class org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration 0x00000007c0e97828]
[Unloading class org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration 0x00000007c0fd8828]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from __JVM_DefineClass__]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$JdbcStoreTypeConfiguration$QuartzSchedulerDependencyConfiguration from file:/home/hannesb/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-autoconfigure/2.2.0.RELEASE/1b3304eec25bb9860bd091a31133e3fe139fcab6/spring-boot-autoconfigure-2.2.0.RELEASE.jar]
[Loaded org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$SchedulerDependsOnBeanFactoryPostProcessor from file:/home/hannesb/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-autoconfigure/2.2.0.RELEASE/1b3304eec25bb9860bd091a31133e3fe139fcab6/spring-boot-autoconfigure-2.2.0.RELEASE.jar]
java.lang.IncompatibleClassChangeError: org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration and org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration$SchedulerDependsOnBeanFactoryPostProcessor disagree on InnerClasses attribute

FAILURE: Build failed with an exception.
```

**Comment by wilkinsona** [comment]
Thanks. The loading from `__JVM_DefineClass__` and the unloading look suspicious to me as I wouldn't expect to see either. I suspect that you have something, perhaps a Java Agent, that is modifying and defining classes as they're loaded. Can you please provide some more information about your application, its dependencies and how you are running it. A minimal sample that reproduces the problem is the ideal way to do this.
