### ISSUE TITLE
No longer possible to use inner class bean annotated with ConfigurationProperties

### ISSUE THREAD

**Issue by PascalSchumacher** [spring-projects/spring-boot#18934]
After upgrading from Spring Boot `2.2.0.RELEASE` to `2.2.1.RELEASE` the following configuration class no longer works:

```java
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import com.zaxxer.influx4j.InfluxDB;

@Configuration
public class InfluxDbConfig {

    @Bean
    public InfluxDB influxDb(InfluxDbConfigProperties influxDb) {
        return InfluxDB.builder().setUsername(influxDb.username).build();
    }

    @ConfigurationProperties("influxdb")
    public static class InfluxDbConfigProperties {

        private String username;

        public String getUsername() {
            return username;
        }

        public void setUsername(String username) {
            this.username = username;
        }
    }
}
```

Start-up fails with:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method influxDb in my.company.InfluxDbConfig required a bean of type 'my.company.InfluxDbConfig$InfluxDbConfigProperties' that could not be found.
```

`@SpringBootTest`s fail with:

```
java.lang.IllegalStateException: Failed to load ApplicationContext
	...
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'influxDb' defined in class path resource [de/telekom/dms/config/InfluxDbConfig.class]: Unsatisfied dependency expressed through method 'influxDb' parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'de.telekom.dms.config.InfluxDbConfig$InfluxDbConfigProperties' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:787)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:528)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:125)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
	... 44 common frames omitted
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'my.company.InfluxDbConfig$InfluxDbConfigProperties' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1695)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1253)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:874)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:778)
	... 62 common frames omitted
```

**Comment by wilkinsona** [comment]
I suspect this is because configuration properties scanning [is no longer enabled by default](https://spring.io/blog/2019/11/07/spring-boot-2-2-1-available-now). If so, it won't be specific to an inner-class but will apply to all `@ConfigurationProperties` beans that are not explicitly enabled via `@EnableConfigurationProperties`.

Can you try please adding `@ConfigurationPropertiesScan` to your app on the same class as `@SpringBootApplication` and let us know if it helps. If it does not, please create a complete and minimal sample, zip it up, and share it with us by attaching it to this issue.

**Comment by PascalSchumacher** [comment]
Thank you very much for the quick reply.

Adding `@ConfigurationPropertiesScan` restores the `2.2.0` behavior.

I did not read the relase announcement (just skimmed the release notes on github) and missed this change.

Sorry for the noise.

**Comment by wilkinsona** [comment]
Not at all. We've realised we need to go a better job of communicating this sort of change on the rare occasions when we make them. We're going to start calling them out at the top of the GitHub release notes as well as in the announcement blog post.
