### ISSUE TITLE
@RequestMappings view in Spring Tool Suite 3.9.x doesn't populate since upgrading project to Spring Boot 2.2.x

### ISSUE THREAD

**Issue by lordofthemoon** [spring-projects/spring-boot#18939]
We use Spring Tool Suite 3.9.4 and since upgrading one of our Spring Boot projects from 2.1.9 to 2.2.1, STS's "@RequestMappings" view no longer populates.  The error log records the following stack trace:

```
org.springframework.core.annotation.AnnotationConfigurationException: Attribute 'proxyBeanMethods' in annotation [org.springframework.boot.SpringBootConfiguration] is declared as an @AliasFor nonexistent attribute 'proxyBeanMethods' in annotation [org.springframework.context.annotation.Configuration].; nested exception is java.lang.NoSuchMethodException: org.springframework.context.annotation.Configuration.proxyBeanMethods()
	at org.springframework.core.annotation.AnnotationUtils$AliasDescriptor.<init>(AnnotationUtils.java:2089)
	at org.springframework.core.annotation.AnnotationUtils$AliasDescriptor.from(AnnotationUtils.java:2056)
	at org.springframework.core.annotation.AnnotationUtils.getAttributeAliasNames(AnnotationUtils.java:1726)
	at org.springframework.core.annotation.AnnotationUtils.isSynthesizable(AnnotationUtils.java:1685)
	at org.springframework.core.annotation.AnnotationUtils.synthesizeAnnotation(AnnotationUtils.java:1468)
	at org.springframework.core.annotation.AnnotationUtils.synthesizeAnnotationArray(AnnotationUtils.java:1572)
	at org.springframework.core.annotation.AnnotationUtils.getAnnotations(AnnotationUtils.java:231)
	at org.springframework.core.type.classreading.AnnotationAttributesReadingVisitor.visitEnd(AnnotationAttributesReadingVisitor.java:76)
	at org.springframework.asm.ClassReader.readAnnotationValues(ClassReader.java:2020)
	at org.springframework.asm.ClassReader.accept(ClassReader.java:676)
	at org.springframework.asm.ClassReader.accept(ClassReader.java:527)
	at org.springframework.ide.eclipse.core.java.classreading.JdtConnectedMetadataReader.<init>(JdtConnectedMetadataReader.java:45)
	at org.springframework.ide.eclipse.core.java.classreading.JdtMetadataReaderFactory.getMetadataReader(JdtMetadataReaderFactory.java:53)
	at org.springframework.ide.eclipse.core.java.classreading.CachingJdtMetadataReaderFactory.getMetadataReader(CachingJdtMetadataReaderFactory.java:38)
	at org.springframework.ide.eclipse.beans.core.internal.model.BeansJavaConfig.registerBean(BeansJavaConfig.java:368)
	at org.springframework.ide.eclipse.beans.core.internal.model.BeansJavaConfig$2.call(BeansJavaConfig.java:229)
	at org.springframework.ide.eclipse.beans.core.internal.model.BeansJavaConfig$2.call(BeansJavaConfig.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodException: org.springframework.context.annotation.Configuration.proxyBeanMethods()
	at java.lang.Class.getDeclaredMethod(Class.java:2130)
	at org.springframework.core.annotation.AnnotationUtils$AliasDescriptor.<init>(AnnotationUtils.java:2082)
	... 22 more
```

with session data:

```
eclipse.buildId=3.9.4.201804120943-RELEASE-e46
java.version=1.8.0_91
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Framework arguments:  -product org.springsource.sts.ide
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.springsource.sts.ide
```

If I modify my project's pom.xml to use Spring Boot 2.1.9.RELEASE then the "@RequestMappings" view populates immediately after the workspace refreshes.

**Comment by snicoll** [comment]
Thanks for the report but that looks like a tooling issue. Please report that [in their issue tracker](https://github.com/spring-projects/spring-ide/issues) and add a link so that we can follow-up accordingly.

**Comment by lordofthemoon** [comment]
Thanks.  Logged https://github.com/spring-projects/spring-ide/issues/398
