### ISSUE TITLE
The latest version starts with a loop of code？？？？？？

### ISSUE THREAD

**Issue by pog2g** [spring-projects/spring-boot#19066]
spring boot 2.2.1.RELEASE starter   keeps showing ：
```
javax.management.InstanceNotFoundException: org.springframework.boot:type=Admin,name=SpringApplication
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1083) ~[na:na]
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:637) ~[na:na]
	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678) ~[na:na]
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1443) ~[na:na]
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1307) ~[na:na]
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1399) ~[na:na]
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.getAttribute(RMIConnectionImpl.java:637) ~[na:na]
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor39.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359) ~[na:na]
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200) ~[na:na]
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197) ~[na:na]
	at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196) ~[na:na]
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562) ~[na:na]
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796) ~[na:na]
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677) ~[na:na]
	at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2019-11-20 15:41:15 DEBUG 2724 --- [-192.168.32.101] javax.management.remote.rmi              : [javax.management.remote.rmi.RMIConnectionImpl@27ad40f3: connectionId=rmi://192.168.32.101  24] closing.
2019-11-20 15:41:15 DEBUG 2724 --- [-192.168.32.101] javax.management.remote.rmi              : [javax.management.remote.rmi.RMIConnectionImpl@27ad40f3: connectionId=rmi://192.168.32.101  24] closed.
2019-11-20 15:41:15 DEBUG 2724 --- [-192.168.32.101] sun.rmi.loader                           : RMI TCP Connection(3)-192.168.32.101: name = "[Ljava.rmi.server.ObjID;", codebase = "", defaultLoader = jdk.internal.loader.ClassLoaders$PlatformClassLoader@4a5c0d33
2019-11-20 15:41:15 DEBUG 2724 --- [-192.168.32.101] sun.rmi.loader                           : RMI TCP Connection(3)-192.168.32.101: name = "java.rmi.server.ObjID", codebase = "", defaultLoader = jdk.internal.loader.ClassLoaders$PlatformClassLoader@4a5c0d33
2019-11-20 15:41:15 DEBUG 2724 --- [-192.168.32.101] sun.rmi.loader                           : RMI TCP Connection(3)-192.168.32.101: name = "java.rmi.server.UID", codebase = "", defaultLoader = jdk.internal.loader.ClassLoaders$PlatformClassLoader@4a5c0d33
2019-11-20 15:41:15 DEBUG 2724 --- [-192.168.32.101] sun.rmi.loader                           : RMI TCP Connection(3)-192.168.32.101: name = "java.rmi.dgc.Lease", codebase = "", defaultLoader = jdk.internal.loader.ClassLoaders$PlatformClassLoader@4a5c0d33
2019-11-20 15:41:15 DEBUG 2724 --- [-192.168.32.101] sun.rmi.loader                           : RMI TCP Connection(3)-192.168.32.101: name = "java.rmi.dgc.VMID", codebase = "", defaultLoader = jdk.internal.loader.ClassLoaders$PlatformClassLoader@4a5c0d33
2019-11-20 15:41:15 DEBUG 2724 --- [-192.168.32.101] sun.rmi.loader                           : RMI TCP Connection(3)-192.168.32.101: name = "[B", codebase = "", defaultLoader = jdk.internal.loader.ClassLoaders$PlatformClassLoader@4a5c0d33
2019-11-20 15:41:15 DEBUG 2724 --- [-192.168.32.101] sun.rmi.loader                           : RMI TCP Connection(3)-192.168.32.101: name = "javax.management.ObjectName", codebase = ""
2019-11-20 15:41:15 DEBUG 2724 --- [-192.168.32.101] javax.management.remote.rmi              : connectionId=rmi://192.168.32.101  25, name=org.springframework.boot:type=Admin,name=SpringApplication, attribute=Ready
2019-11-20 15:41:15 DEBUG 2724 --- [-192.168.32.101] sun.rmi.server.call                      : RMI TCP Connection(3)-192.168.32.101: [192.168.32.101] exception: 
```

why，，，
This section of the log has been looping for four or five minutes before the normal start, the log made info, although after the invisible, but also to wait for four or five minutes before the real start

**Comment by wilkinsona** [comment]
That's debug logging that shouldn't be enable by default. So that we can determine why it's enabled for you, can you please create a small sample that reproduces the behaviour you're seeing and share it with us by zipping it up and attaching it here?

**Comment by pog2g** [comment]
It turned out that the database connection failed and it was going to stay that way

**Comment by wilkinsona** [comment]
Thanks for letting us know.
