### ISSUE TITLE
Spring Boot 2.2.1.RELEASE: upgrade to h2 1.4.200 makes drop table fails between SpringBootTest when using different webEnvironments

### ISSUE THREAD

**Issue by philipreimer** [spring-projects/spring-boot#19183]
Attached [demo.zip](https://github.com/spring-projects/spring-boot/files/3902745/demo.zip)
 is a simple spring boot `2.2.1.RELEASE` demo application with two `SpringBootTest`s. 

One is using the default `webEnvironment=SpringBootTest.WebEnvironment.MOCK`.

The other is using `webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT`.

There are also two JPA entities `A` and `B`, where `B` has a reference to `A` (`@ManyToOne`).

The project uses h2 embedded database.

When running the tests via `mvn clean test`, spring tries to drop and recreate the database tables between tests, which fails. This in turn lets inserting the test data in `data.sql` fail, because the data from the first test is still there.

The same project and tests work fine when using spring boot `2.2.0.RELEASE`.

It seems that the h2 upgrade from `1.4.199` to `1.4.200` causes this. Using spring boot `2.2.1.RELEASE` and just downgrading h2 to `1.4.199` lets the tests pass again.

## Steps to reproduce:

1. run `mvn clean test` in attached demo project

## Result:
Second test fails because of:
```
GenerationTarget encountered exception accepting command : Error executing DDL "drop table table_a if exists" via JDBC Statement
...
Caused by: Cannot drop "TABLE_A" because "FK18G0PAJIUWBD9HI0PI0Q03TPO" depends on it;
```

## Expected Result:
* dropping and recreating the database tables between tests should succeed.
* test should pass

**Comment by wilkinsona** [comment]
Thanks for the sample. The SQL call that's failing is being made by Hibernate:

```
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Cannot drop "TABLE_A" because "FK18G0PAJIUWBD9HI0PI0Q03TPO" depends on it; SQL statement:
drop table table_a if exists [90107-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:576) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.message.DbException.get(DbException.java:205) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.command.ddl.DropTable.prepareDrop(DropTable.java:98) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.command.ddl.DropTable.update(DropTable.java:124) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.command.CommandContainer.update(CommandContainer.java:198) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.command.Command.executeUpdate(Command.java:251) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:228) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201) ~[h2-1.4.200.jar:1.4.200]
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95) ~[HikariCP-3.4.1.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HikariCP-3.4.1.jar:na]
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:54) ~[hibernate-core-5.4.8.Final.jar:5.4.8.Final]
	... 99 common frames omitted
```

There's a [Hibernate issue](https://hibernate.atlassian.net/browse/HHH-13711) tracking the problem. Their H2 dialect needs to catch up with H2 now adhering more closely to the SQL standard. We'll upgrade to a new version of Hibernate as it becomes available. In the meantime I'd recommend that you, and anyone else affected by this, uses H2 1.4.199.
