### ISSUE TITLE
ConditionEvaluationReport is incomplete when used with spring-cloud-starter-aws-parameter-store-config

### ISSUE THREAD

**Issue by fprochazka** [spring-projects/spring-boot#19212]
Hello,
I'm starting a new project and I'm trying to be very careful about what is enabled, therefore I'm consulting the `ConditionEvaluationReport`. But it turns out, that when it's used with `spring-cloud-starter-aws-parameter-store-config`, the report is missing some classes. I'm not sure if this is a spring-boot issue or spring-cloud issue, but hopefully, it's okey here.

The spring cloud bootstrap process "hijacks" the initialization of the spring context and it initializes only a necessary minimum of dependencies so it can load the properties from aws parameter store. Then it loads the parameters and adds them to the "main" context which is then enabled to continue initializing.

The "cloud" context prints one report and then the "main" context prints another one. I've observed the "cloud" context to be incomplete.

<details>
 <summary>The `report` property is first initialized here</summary>

```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener.initialize(ConditionEvaluationReportLoggingListener.java:86)
	  at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:626)
	  at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:370)
	  at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	  at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140)
	  - locked <0x1286> (a java.util.concurrent.atomic.AtomicBoolean)
	  at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:203)
	  at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:114)
	  at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:71)
	  at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	  at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	  at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	  at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	  at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:76)
	  at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
	  at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:345)
	  at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	  at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140)
	  - locked <0x1287> (a java.util.concurrent.atomic.AtomicBoolean)
	  at com.cogvio.ConsoleApplication.main(ConsoleApplication.java:47)
```

</details>

<details>
 <summary>later, the report is logged from here</summary>

```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener.logAutoConfigurationReport(ConditionEvaluationReportLoggingListener.java:126)
	  at org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener.logAutoConfigurationReport(ConditionEvaluationReportLoggingListener.java:104)
	  at org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener.onApplicationEvent(ConditionEvaluationReportLoggingListener.java:94)
	  at org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener$ConditionEvaluationReportListener.onApplicationEvent(ConditionEvaluationReportLoggingListener.java:164)
	  at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	  at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	  at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	  at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:403)
	  at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:360)
	  at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:897)
	  at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553)
	  - locked <0x17ac> (a java.lang.Object)
	  at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	  at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	  at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	  at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140)
	  - locked <0x1286> (a java.util.concurrent.atomic.AtomicBoolean)
	  at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:203)
	  at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:114)
	  at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:71)
	  at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	  at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	  at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	  at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	  at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:76)
	  at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
	  at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:345)
	  at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	  at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140)
	  - locked <0x1287> (a java.util.concurrent.atomic.AtomicBoolean)
	  at com.cogvio.ConsoleApplication.main(ConsoleApplication.java:47)
```

</details>

I'm registering the classes using `META-INF/spring.factories` and I've verified that they in fact are correctly registered and executed

```properties
org.springframework.cloud.bootstrap.BootstrapConfiguration=\
com.cogvio.config.AWSCredentialsConfiguration,\
com.cogvio.config.AWSSimpleSystemsManagementConfiguration
```

<details>
 <summary>AWSSimpleSystemsManagementConfiguration.java</summary>

```java
package com.cogvio.config;

import com.amazonaws.auth.AWSCredentialsProvider;
import com.amazonaws.regions.Regions;
import com.amazonaws.services.simplesystemsmanagement.AWSSimpleSystemsManagement;
import com.amazonaws.services.simplesystemsmanagement.AWSSimpleSystemsManagementClientBuilder;
import org.springframework.boot.autoconfigure.AutoConfigureAfter;
import org.springframework.boot.autoconfigure.AutoConfigureBefore;
import org.springframework.cloud.aws.autoconfigure.paramstore.AwsParamStoreBootstrapConfiguration;
import org.springframework.cloud.aws.core.region.RegionProvider;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;

@Configuration
@Import({
    AWSCredentialsConfiguration.class,
})
@AutoConfigureAfter(AWSCredentialsConfiguration.class)
@AutoConfigureBefore(AwsParamStoreBootstrapConfiguration.class)
public class AWSSimpleSystemsManagementConfiguration
{

    @Bean
    public AWSSimpleSystemsManagement ssmClient(
        final AWSCredentialsProvider credentialsProvider,
        final RegionProvider awsRegionProvider
    )
    {
        return AWSSimpleSystemsManagementClientBuilder.standard()
            .withCredentials(credentialsProvider)
            .withRegion(Regions.fromName(awsRegionProvider.getRegion().getName()))
            .build();
    }

}
```

</details>

I would expect the configuration class to be listed in the `Unconditional classes:` section, but it's not, even through it's executed (verified with debugger).

-----

Relevant libraries & versions

* `org.springframework.boot:spring-boot-starter:jar:2.2.1.RELEASE`
* `org.springframework.cloud:spring-cloud-starter-aws:jar:2.1.2.RELEASE`
* `org.springframework.cloud:spring-cloud-starter-aws-parameter-store-config:jar:2.1.2.RELEASE`

**Comment by philwebb** [comment]
@spencergibb This feels like it might be a Spring Cloud specific issue, is there a better issue tracker to raise it in?

**Comment by spencergibb** [comment]
https://github.com/spring-cloud/spring-cloud-aws/issues

**Comment by philwebb** [comment]
Thanks @spencergibb. @fprochazka I'm afraid I can't move this issue, would you mind recreating it in https://github.com/spring-cloud/spring-cloud-aws/issues?

**Comment by fprochazka** [comment]
No problem! -> https://github.com/spring-cloud/spring-cloud-aws/issues/511
