### ISSUE TITLE
spring boot '1.1.6'  project.  to '1.2.0.RC1'  : Cannot subclass final class class com.sun.proxy.$Proxy88

### ISSUE THREAD

**Issue by aasheikh** [spring-projects/spring-boot#1929]
I had the following code  in spring boot '1.1.6'  project. I have changed to '1.2.0.RC1'

It caused the error below. I have removed the `@Repository` stereotype and it has worked. 
I haven't changed anything else in the project

``` java
@Repository
public interface ShowRoomReposiory extends MongoRepository<ShowRoom, ObjectId> {}
```

```
java.lang.IllegalStateException: Failed to load ApplicationContext
    at org.springframework.test.context.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:94)
    at org.springframework.test.context.DefaultTestContext.getApplicationContext(DefaultTestContext.java:72)
    at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:117)
    at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
    at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:212)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:200)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:252)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:254)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:217)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:83)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
    at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:68)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:163)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
    at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
    at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:355)
    at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'showRoomServiceImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.hornsofttech.nayriba.storefront.domain.repository.ShowRoomReposiory com.hornsofttech.nayriba.storefront.domain.service.ShowRoomServiceImpl.shopReposiory; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'showRoomReposiory': Post-processing of FactoryBean's singleton object failed; nested exception is org.springframework.aop.framework.AopConfigException: Could not generate CGLIB subclass of class [class com.sun.proxy.$Proxy88]: Common causes of this problem include using a final class or a non-visible class; nested exception is java.lang.IllegalArgumentException: Cannot subclass final class class com.sun.proxy.$Proxy88
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1204)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:302)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:229)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:298)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:762)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:109)
    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:691)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:321)
    at org.springframework.boot.test.SpringApplicationContextLoader.loadContext(SpringApplicationContextLoader.java:105)
    at org.springframework.test.context.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:68)
    at org.springframework.test.context.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:86)
    ... 44 more
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.hornsofttech.nayriba.storefront.domain.repository.ShowRoomReposiory com.hornsofttech.nayriba.storefront.domain.service.ShowRoomServiceImpl.shopReposiory; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'showRoomReposiory': Post-processing of FactoryBean's singleton object failed; nested exception is org.springframework.aop.framework.AopConfigException: Could not generate CGLIB subclass of class [class com.sun.proxy.$Proxy88]: Common causes of this problem include using a final class or a non-visible class; nested exception is java.lang.IllegalArgumentException: Cannot subclass final class class com.sun.proxy.$Proxy88
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:555)
    at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:87)
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
    ... 60 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'showRoomReposiory': Post-processing of FactoryBean's singleton object failed; nested exception is org.springframework.aop.framework.AopConfigException: Could not generate CGLIB subclass of class [class com.sun.proxy.$Proxy88]: Common causes of this problem include using a final class or a non-visible class; nested exception is java.lang.IllegalArgumentException: Cannot subclass final class class com.sun.proxy.$Proxy88
    at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:116)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1514)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:313)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1127)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1051)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:949)
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:527)
    ... 62 more
Caused by: org.springframework.aop.framework.AopConfigException: Could not generate CGLIB subclass of class [class com.sun.proxy.$Proxy88]: Common causes of this problem include using a final class or a non-visible class; nested exception is java.lang.IllegalArgumentException: Cannot subclass final class class com.sun.proxy.$Proxy88
    at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:212)
    at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:109)
    at org.springframework.aop.framework.AbstractAdvisingBeanPostProcessor.postProcessAfterInitialization(AbstractAdvisingBeanPostProcessor.java:91)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:422)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.postProcessObjectFromFactoryBean(AbstractAutowireCapableBeanFactory.java:1713)
    at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:113)
    ... 69 more
Caused by: java.lang.IllegalArgumentException: Cannot subclass final class class com.sun.proxy.$Proxy88
    at org.springframework.cglib.proxy.Enhancer.generateClass(Enhancer.java:446)
    at org.springframework.cglib.transform.TransformingClassGenerator.generateClass(TransformingClassGenerator.java:33)
    at org.springframework.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
    at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:216)
    at org.springframework.cglib.proxy.Enhancer.createHelper(Enhancer.java:377)
    at org.springframework.cglib.proxy.Enhancer.createClass(Enhancer.java:317)
    at org.springframework.aop.framework.ObjenesisCglibAopProxy.createProxyClassAndInstance(ObjenesisCglibAopProxy.java:57)
    at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:202)
    ... 74 more
```

**Comment by emersonf** [comment]
I had the same problem going from 1.1.9 to 1.2.1. In my case both solutions work, i.e. disabling the exception translator or removing the `@Repository` annotations.

**Comment by sourcekick** [comment]
I do not like the suggested solutions.

- It is cumbersome to add the property to all application property files if you have many microservices and several target environments.

- It is also not nice to be forced to remove the @Repository stereotype. Especially where you already have a lot of repositories and large distributed dev teams producing new microservices choosing the Spring Boot way, it is again cumbersome.

How about forking this issue to the Spring Data umbrella project and its sub projects to make it work (if this has not been done already)? @olivergierke

**Comment by olivergierke** [comment]
`@Repository` should only be used if you intend to apply exception translation to that particular bean as that's what the JavaDoc clearly suggests. For simple renames use `@Component`. Other than that propose Spring Data repositories don't need to get exception translation applied as the repository proxy mechanism already takes care of that for you.

**Comment by sourcekick** [comment]
I disagree with the part that `@Repository` is only there for exception translation, and thus I think a fix to make things interoperable and robust would be appropriate. The JavaDoc also states: "This annotation is a general-purpose stereotype and individual teams may narrow their semantics and use as appropriate. [...] The annotated class is also clarified as to its role in the overall application architecture for the purpose of tooling, aspects, etc."

**Comment by olivergierke** [comment]
Right, but you don't get this without the former "being eligible for exception translation". So if your type does not qualify for that, you must not use the annotation. I'm terribly sorry but I don't think anyone is going to be able to alter the semantics of the usage of the annotation. So while I am basically with you that in this particular case the combination of the two semantical aspects is problematic, there's nothing we can do about it as we can't alter the way the (Spring) container works. 

My "nothing to fix here" statement was targeted at Spring Data, as we don't control the way the container handles `@Repository` annotations. Hence, the only way to work around this is not using this particular annotation but `@Component`. If you still want to use an annotation to equip all repositories with, you can craft your own `@Repository` and meta-annotate it with `@Component`.

**Comment by joensson** [comment]
If one really want to use the @Repository annotation - but don't want  the automatic exception translation and for some reason don't want to add the property that disables the exception translation - then one (although slightly hacky) alternative could be to declare your own custom PersistenceExceptionTranslationPostProcessor in your config and set its repositoryAnnotationType to some other annotation than the default ```@Repository``` (it cannot be null). 
The ApplicationContext will prefer a locally defined post processor over the default post processor that does exception translation for @Repository beans.

However, under normal circumstances I would not do this - I recommend using the ```spring.dao.exceptiontranslation.enabled=false``` property, or as Oliver suggest - simple using either @Component or your own custom @Repository annotation.

Example: 
```java
@Bean
public PersistenceExceptionTranslationPostProcessor customExceptionTranslator() {
    PersistenceExceptionTranslationPostProcessor pp = new PersistenceExceptionTranslationPostProcessor();
    pp.setRepositoryAnnotationType(RepositoryWithExceptionTranslation.class);
}
```

**Comment by sourcekick** [comment]
This is quite exactly the approach that I took yesterday, and I also consider it hacky. I registered a custom `PersistenceExceptionTranslationPostProcessor` that is never eligible.

**Comment by philwebb** [comment]
@sourcekick Any specific reason why `spring.dao.exceptiontranslation.enabled=false` doesn't work for you?

**Comment by sourcekick** [comment]
I would consider that as a workaround, but it is not a nice solution. One reason is that there are a lot of microservices im my project, i.e. Applications, and I do not want to introduce this setting in each of them, just to get the compatibility of the libraries. Another reason is that when any developers create new Applications and are not aware of this issue, they might do unecessary debugging sessions.

**Comment by AlexCzar** [comment]
So just to summarize.
* If I need exception translation to be applied and work, I only need to use `@Repository` on the interfaces or classes that do not extend spring-data's repository interfaces.
* If my interface extends a spring-data's repository (e.g. `CrudRepository`) the exception translation will be applied even without the annotation.

And a question. Do I need to use `@Component` instead of `@Repository` if I want `@ComponentScan` to work or extending a spring-data's `*Repository` will take care of that also?

**Comment by wilkinsona** [comment]
> Do I need to use @Component instead of @Repository if I want @ComponentScan to work

No, `@Repository` is annotated with `@Component` so it will be detected by component scanning

**Comment by AlexCzar** [comment]
@wilkinsona that is not what I asked, obviously I cannot use `@Repository` as this throws a CGLIB exception, so do I need `@Component` instead of it?

P. S. I checked the boot scenario and I obviously do not need neither `@Repository` nor `@Component` there, my repositories which extend `*Repository` are picked up and exception translation works, so disregard those points in my original question.

**Comment by philwebb** [comment]
@AlexCzar You don't need any annotations if you extend Spring Data's `Repository` interface.

**Comment by AlexCzar** [comment]
Thanks, @philwebb
