### ISSUE TITLE
Can not use Kotlin multiplatform module with Webflux

### ISSUE THREAD

**Issue by iTanChi** [spring-projects/spring-boot#19295]
In my multi module project, I have a kotlin multiplatform module with jvm target, for example:

`commonMain`:
```
expect class Platform {
  fun getName(): String
}
expect val platformName: String
```

`jvmMain`
```
actual class Platform {
  actual fun getName(): String = platformName
}
actual val platformName: String = "JVM"
```

In my android module in the same project, I can include the multiplatform module above and it can compile, run and display the text `JVM`

And the same result when I include it in a module using spring boot web mvc. The api can return the text `JVM`

```
@RestController
@RequestMapping("/")
class Controller {

    @GetMapping("")
    fun index(): Any {
        return mapOf<String, String>("name" to Platform().getName())
    }

}
```

But when I change my spring boot module to webflux and change my controller to this:

```
@RestController
@RequestMapping("/")
class Controller {

    @GetMapping("")
    suspend fun index(): Any {
        return mapOf<String, String>("name" to Platform().getName())
    }

}
```

The project can compile and run but will throw this error when requesting the api:

```
Caused by: java.lang.ClassNotFoundException: com.example.multiplatform.Platform
```

I have tried to find any related issues but got nothing.

My config:
```
Gradle: 5.6.4
Android Gradle: 3.5.2
Spring Boot: 2.2.1
Kotlin: 1.3.61
```

**Comment by wilkinsona** [comment]
Thanks for the report. I can't see why switching from Spring MVC to Spring WebFlux would affect the ability to load your `com.example.multiplatform.Platform` class. Can you please provide a complete and minimal example so that we can try to figure out what's going on?

**Comment by iTanChi** [comment]
@wilkinsona sorry for late response, you can checkout this project https://github.com/iTanChi/tmdb. it has the same error when running api module

**Comment by wilkinsona** [comment]
Thanks. I see a different error:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'reactorClientHttpConnector' defined in class path resource [org/springframework/boot/autoconfigure/web/reactive/function/client/ClientHttpConnectorConfiguration$ReactorNetty.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.http.client.reactive.ReactorClientHttpConnector]: Factory method 'reactorClientHttpConnector' threw exception; nested exception is java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: io/netty/handler/codec/http/HttpHeaders
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:645) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:625) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66) ~[spring-boot-2.2.1.RELEASE.jar:2.2.1.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) [spring-boot-2.2.1.RELEASE.jar:2.2.1.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.2.1.RELEASE.jar:2.2.1.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.2.1.RELEASE.jar:2.2.1.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.1.RELEASE.jar:2.2.1.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.1.RELEASE.jar:2.2.1.RELEASE]
        at net.norutan.tmdb.api.ApiApplicationKt.main(ApiApplication.kt:13) [main/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_202]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_202]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_202]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_202]
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-2.2.1.RELEASE.jar:2.2.1.RELEASE]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.http.client.reactive.ReactorClientHttpConnector]: Factory method 'reactorClientHttpConnector' threw exception; nested exception is java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: io/netty/handler/codec/http/HttpHeaders
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:640) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        ... 24 common frames omitted
Caused by: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: io/netty/handler/codec/http/HttpHeaders
        at reactor.netty.http.client.HttpClient.<clinit>(HttpClient.java:963) ~[reactor-netty-0.9.1.RELEASE.jar:0.9.1.RELEASE]
        at org.springframework.http.client.reactive.ReactorClientHttpConnector.initHttpClient(ReactorClientHttpConnector.java:85) ~[spring-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.http.client.reactive.ReactorClientHttpConnector.<init>(ReactorClientHttpConnector.java:77) ~[spring-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.boot.autoconfigure.web.reactive.function.client.ClientHttpConnectorConfiguration$ReactorNetty.reactorClientHttpConnector(ClientHttpConnectorConfiguration.java:58) ~[spring-boot-autoconfigure-2.2.1.RELEASE.jar:2.2.1.RELEASE]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_202]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_202]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_202]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_202]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        ... 25 common frames omitted
Caused by: java.lang.NoClassDefFoundError: io/netty/handler/codec/http/HttpHeaders
        ... 34 common frames omitted
Caused by: java.lang.ClassNotFoundException: io.netty.handler.codec.http.HttpHeaders
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_202]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_202]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[na:1.8.0_202]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_202]
        ... 34 common frames omitted
```

This is caused by some incorrect exclusions on `r2dbc-mysql`. The latest snapshots of the experimental R2DBC Spring Boot support should give you a version that has corrected the problem.

**Comment by iTanChi** [comment]
thanks @wilkinsona I tried removing all related spring data and can run the module using bootRun gradle task. But I got the reported issue by executing main function or using run button in intellijIdea. Btw I will try upgrading the spring data r2dbc version

**Comment by wilkinsona** [comment]
If `bootRun` succeeds and running the main method in your IDE fails, it sounds like your IDE isn't setting up the classpath correctly.
