### ISSUE TITLE
ErrorPageFilter flushes response buffer of successful response

### ISSUE THREAD

**Issue by jordi-rubio** [spring-projects/spring-boot#1938]
We are experiencing problems when requests are being cancelled on client-side and the response Buffer is not yet empty. The ErrorPageFilter tries to flush the response Buffer causing an IOException (see below).

The response code the servlet is sending is 200, so I wonder why the ErrorPageFilter tries to flush those responses. Isn't the servlet container responsible for flushing?

We use Spring Boot 1.1.9.RELEASE.

```
2014-11-17 00:06:07,692 ERROR [http-apr-8080-exec-1] o.s.boot.context.web.ErrorPageFilter -  - Cannot forward to error page for request to /my-app/internal/hystrix.stream as the response has already been committed. As a result, the response may have the wrong status code. If your application is running on WebSphere Application Server you may be able to resolve this problem by setting  com.ibm.ws.webcontainer.invokeFlushAfterService to false
org.apache.catalina.connector.ClientAbortException: null
        at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:407) ~[catalina.jar:7.0.56]
        at org.apache.tomcat.util.buf.ByteChunk.flushBuffer(ByteChunk.java:480) ~[tomcat-coyote.jar:7.0.56]
        at org.apache.catalina.connector.OutputBuffer.realWriteChars(OutputBuffer.java:485) ~[catalina.jar:7.0.56]
        at org.apache.tomcat.util.buf.CharChunk.flushBuffer(CharChunk.java:464) ~[tomcat-coyote.jar:7.0.56]
        at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:353) ~[catalina.jar:7.0.56]
        at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:331) ~[catalina.jar:7.0.56]
        at org.apache.catalina.connector.Response.flushBuffer(Response.java:610) ~[catalina.jar:7.0.56]
        at org.apache.catalina.connector.ResponseFacade.flushBuffer(ResponseFacade.java:306) ~[catalina.jar:7.0.56]
        at org.springframework.boot.context.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:116) [spring-boot-1.1.9.RELEASE.jar:1.1.9.RELEASE]
        at org.springframework.boot.context.web.ErrorPageFilter.access$000(ErrorPageFilter.java:59) [spring-boot-1.1.9.RELEASE.jar:1.1.9.RELEASE]
        at org.springframework.boot.context.web.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:88) [spring-boot-1.1.9.RELEASE.jar:1.1.9.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.0.8.RELEASE.jar:4.0.8.RELEASE]
        at org.springframework.boot.context.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:101) [spring-boot-1.1.9.RELEASE.jar:1.1.9.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.56]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.56]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) [catalina.jar:7.0.56]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) [catalina.jar:7.0.56]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503) [catalina.jar:7.0.56]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170) [catalina.jar:7.0.56]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) [catalina.jar:7.0.56]
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950) [catalina.jar:7.0.56]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [catalina.jar:7.0.56]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421) [catalina.jar:7.0.56]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070) [tomcat-coyote.jar:7.0.56]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611) [tomcat-coyote.jar:7.0.56]
        at org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2399) [tomcat-coyote.jar:7.0.56]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_05]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_05]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-coyote.jar:7.0.56]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_05]
Caused by: java.io.IOException: null
        at org.apache.coyote.http11.InternalAprOutputBuffer.flushBuffer(InternalAprOutputBuffer.java:205) ~[tomcat-coyote.jar:7.0.56]
        at org.apache.coyote.http11.InternalAprOutputBuffer.access$100(InternalAprOutputBuffer.java:37) ~[tomcat-coyote.jar:7.0.56]
        at org.apache.coyote.http11.InternalAprOutputBuffer$SocketOutputBuffer.doWrite(InternalAprOutputBuffer.java:235) ~[tomcat-coyote.jar:7.0.56]
        at org.apache.coyote.http11.filters.ChunkedOutputFilter.doWrite(ChunkedOutputFilter.java:117) ~[tomcat-coyote.jar:7.0.56]
        at org.apache.coyote.http11.AbstractOutputBuffer.doWrite(AbstractOutputBuffer.java:192) ~[tomcat-coyote.jar:7.0.56]
        at org.apache.coyote.Response.doWrite(Response.java:499) ~[tomcat-coyote.jar:7.0.56]
        at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:402) ~[catalina.jar:7.0.56]
        ... 30 common frames omitted
```

**Comment by rishiparanjape** [comment]
Still happening as of 1.4.4

**Comment by snicoll** [comment]
@rishiparanjape commenting on a 2 years+ old issue isn't a great way to get support. If you believe you've found  an issue, please create a new issue with a sample that demonstrates the problem.
