### ISSUE TITLE
PortInUseException when using SpyBean in integration testing

### ISSUE THREAD

**Issue by EdisKrsmanovic** [spring-projects/spring-boot#19382]
Tried with Spring Boot 2.0.9.RELEASE, Spring Boot 2.1.5.RELEASE and Spring Boot 2.2.2.RELEASE (With mockito version 2.28.2 and even with the newest 3.2.0). 

Only happens when I have 2 or more integration tests in one package(one of them must have SpyBean field), and then if I run all tests in that package at once. When I run tests individually it doesn't happen. I can solve the problem by using webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT. Also if I use MockBean instead of SpyBean it doesn't happen.
Here's a stack trace: 
		
		Java.lang.IllegalStateException: Failed to load ApplicationContext

		at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:125)
		at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:108)
		at org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener.postProcessFields(MockitoTestExecutionListener.java:99)
		at org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener.injectFields(MockitoTestExecutionListener.java:79)
		at org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener.prepareTestInstance(MockitoTestExecutionListener.java:54)
		at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:246)
		at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:227)
		at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:289)
		at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
		at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:291)
		at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:246)
		at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
		at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
		at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
		at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
		at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
		at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
		at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
		at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
		at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
		at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
		at org.junit.runners.Suite.runChild(Suite.java:128)
		at org.junit.runners.Suite.runChild(Suite.java:27)
		at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
		at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
		at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
		at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
		at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
		at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
		at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
		at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
		at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
		at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
		at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
	Caused by: org.springframework.boot.web.server.PortInUseException: Port 9090 is already in use
		at org.springframework.boot.web.embedded.jetty.JettyWebServer.start(JettyWebServer.java:153)
		at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.startWebServer(ServletWebServerApplicationContext.java:311)
		at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:164)
		at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554)
		at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
		at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
		at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:386)
		at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
		at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:127)
		at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
		at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:117)
		... 33 more

**Comment by bclozel** [comment]
I'm not sure I see the link with `@SpyBean` here. Maybe using that uses a different application context (one that isn't the previous one, cached) and requires a new server instance?

Maybe your application is trying to execute two different integration tests with different application contexts (and thus servers), at the same time? In this case, I'd argue that this is expected since we can't have context caching and tests with fixed ports at the same time.

In this case, using a random port is in my opinion a good practice.

If this analysis differs from what you're seeing, could you share a sample application we could take a look at? Thanks!

**Comment by bclozel** [comment]
Hey @EdisKrsmanovic , I just wanted to know a bit more about your use case.
My previous comment is not an attempt to get this closed and out of our way - if you can share more about your use case and your expectations, maybe we can improve the current behavior.
Thanks

**Comment by EdisKrsmanovic** [comment]
@bclozel Hey, sorry for closing the issue. I tried making an example Spring Boot project replicating the same issue I had but I wasn't able to make it. I'll reopen the issue once I manage to make an example and elaborate a bit more. Thanks.
