### ISSUE TITLE
Docker socket-based integration does not work on Linux

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#19836]
Running `DockerApiIntegrationTests` on Linux leads to the following:

```
java.lang.UnsatisfiedLinkError: 'int org.springframework.boot.cloudnativebuildpack.socket.LinuxDomainSocket.connect(int, org.springframework.boot.cloudnativebuildpack.socket.LinuxDomainSocket$SockaddrUn, int)
at org.springframework.boot.cloudnativebuildpack.socket.LinuxDomainSocket.connect(Native Method)
at org.springframework.boot.cloudnativebuildpack.socket.LinuxDomainSocket.connect(LinuxDomainSocket.java:45)
at org.springframework.boot.cloudnativebuildpack.socket.DomainSocket.open(DomainSocket.java:72)
at org.springframework.boot.cloudnativebuildpack.socket.DomainSocket.<init>(DomainSocket.java:61)
at org.springframework.boot.cloudnativebuildpack.socket.LinuxDomainSocket.<init>(LinuxDomainSocket.java:37)
at org.springframework.boot.cloudnativebuildpack.socket.DomainSocket.get(DomainSocket.java:144)
at org.springframework.boot.cloudnativebuildpack.docker.DockerConnectionSocketFactory.createSocket(DockerConnectionSocketFactory.java:48)
at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:119)
at org.apache.http.impl.conn.BasicHttpClientConnectionManager.connect(BasicHttpClientConnectionManager.java:313)
at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
at org.springframework.boot.cloudnativebuildpack.docker.HttpClientHttp.execute(HttpClientHttp.java:135)
at org.springframework.boot.cloudnativebuildpack.docker.HttpClientHttp.post(HttpClientHttp.java:84)
at org.springframework.boot.cloudnativebuildpack.docker.DockerApi$ImageApi.pull(DockerApi.java:150)
at org.springframework.boot.cloudnativebuildpack.docker.DockerApiIntegrationTests.pullImage(DockerApiIntegrationTests.java:38)
```

**Comment by wilkinsona** [comment]
Fixed by 62a848f1b120c836882fbbd50a608eb42f78e244.
