### ISSUE TITLE
Local gradle build hangs intermittently on launch script tests

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#19862]
My local build seems to hang on the launch script tests. Running with `--debug` gives:

```
2020-01-22T19:36:39.301-0800 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] > Task :spring-boot-tests:spring-boot-integration-tests:spring-boot-launch-script-tests:intTest
2020-01-22T19:36:44.291-0800 [DEBUG] [TestEventLogger] 
2020-01-22T19:36:44.291-0800 [DEBUG] [TestEventLogger] SysVinitLaunchScriptIntegrationTests > CentOS 6.9-a23bced6 PASSED
2020-01-22T19:36:44.292-0800 [DEBUG] [TestEventLogger] 
2020-01-22T19:36:44.292-0800 [DEBUG] [TestEventLogger] SysVinitLaunchScriptIntegrationTests > Ubuntu xenial-20160914 STARTED
2020-01-22T19:36:45.571-0800 [DEBUG] [TestEventLogger] 
2020-01-22T19:36:45.571-0800 [DEBUG] [TestEventLogger] SysVinitLaunchScriptIntegrationTests > Ubuntu xenial-20160914 STANDARD_OUT
2020-01-22T19:36:45.571-0800 [DEBUG] [TestEventLogger]     19:36:45.570 [Test worker] INFO  o.t.i.builder.ImageFromDockerfile - Transferred 15 MB KB to Docker daemon
2020-01-22T19:36:45.668-0800 [DEBUG] [TestEventLogger]     19:36:45.667 [Test worker] INFO  🐳 [spring-boot-launch-script/ubuntu-xenial-20160914:latest] - Creating container for image: spring-boot-launch-script/ubuntu-xenial-20160914:latest
2020-01-22T19:36:45.707-0800 [DEBUG] [TestEventLogger]     19:36:45.707 [Test worker] INFO  o.t.utility.RegistryAuthLocator - Credential helper/store (docker-credential-desktop) does not have credentials for index.docker.io
2020-01-22T19:36:46.133-0800 [DEBUG] [TestEventLogger]     19:36:46.132 [Test worker] INFO  🐳 [spring-boot-launch-script/ubuntu-xenial-20160914:latest] - Starting container with ID: a34d9bdc0d70313d952793005c91716edea7884e7800b735a04444e09b9dd957
2020-01-22T19:36:46.723-0800 [DEBUG] [TestEventLogger]     19:36:46.723 [Test worker] INFO  🐳 [spring-boot-launch-script/ubuntu-xenial-20160914:latest] - Container spring-boot-launch-script/ubuntu-xenial-20160914:latest is starting: a34d9bdc0d70313d952793005c91716edea7884e7800b735a04444e09b9dd957
2020-01-22T19:36:46.733-0800 [DEBUG] [TestEventLogger]     19:36:46.733 [Test worker] INFO  🐳 [spring-boot-launch-script/ubuntu-xenial-20160914:latest] - Container spring-boot-launch-script/ubuntu-xenial-20160914:latest started in PT2.441S
2020-01-22T19:36:51.620-0800 [DEBUG] [TestEventLogger] 
2020-01-22T19:36:51.620-0800 [DEBUG] [TestEventLogger] SysVinitLaunchScriptIntegrationTests > Ubuntu xenial-20160914 PASSED
2020-01-22T19:36:51.620-0800 [DEBUG] [TestEventLogger] 
2020-01-22T19:36:51.620-0800 [DEBUG] [TestEventLogger] SysVinitLaunchScriptIntegrationTests > Ubuntu trusty-20160914 STARTED
2020-01-22T19:36:52.748-0800 [DEBUG] [TestEventLogger] 
2020-01-22T19:36:52.748-0800 [DEBUG] [TestEventLogger] SysVinitLaunchScriptIntegrationTests > Ubuntu trusty-20160914 STANDARD_OUT
2020-01-22T19:36:52.748-0800 [DEBUG] [TestEventLogger]     19:36:52.749 [Test worker] INFO  o.t.i.builder.ImageFromDockerfile - Transferred 15 MB KB to Docker daemon
2020-01-22T19:36:52.821-0800 [DEBUG] [TestEventLogger]     19:36:52.822 [Test worker] INFO  🐳 [spring-boot-launch-script/ubuntu-trusty-20160914:latest] - Creating container for image: spring-boot-launch-script/ubuntu-trusty-20160914:latest
2020-01-22T19:36:52.861-0800 [DEBUG] [TestEventLogger]     19:36:52.862 [Test worker] INFO  o.t.utility.RegistryAuthLocator - Credential helper/store (docker-credential-desktop) does not have credentials for index.docker.io
2020-01-22T19:36:52.888-0800 [LIFECYCLE] [org.gradle.cache.internal.DefaultFileLockManager] 
2020-01-22T19:36:52.888-0800 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2020-01-22T19:36:52.888-0800 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2020-01-22T19:36:52.888-0800 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2020-01-22T19:36:52.889-0800 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2020-01-22T19:36:52.889-0800 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2020-01-22T19:36:52.889-0800 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2020-01-22T19:36:52.793-0800 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] 
2020-01-22T19:36:52.793-0800 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] > Task :spring-boot-tests:spring-boot-integration-tests:spring-boot-launch-script-tests:intTest
2020-01-22T19:36:53.304-0800 [DEBUG] [TestEventLogger]     19:36:53.304 [Test worker] INFO  🐳 [spring-boot-launch-script/ubuntu-trusty-20160914:latest] - Starting container with ID: 93cb7063b3c29e28106190c1ccb0cd3fdaa72dbb5cf0243ae76e6e66ed90a2ae
2020-01-22T19:36:53.931-0800 [DEBUG] [TestEventLogger]     19:36:53.931 [Test worker] INFO  🐳 [spring-boot-launch-script/ubuntu-trusty-20160914:latest] - Container spring-boot-launch-script/ubuntu-trusty-20160914:latest is starting: 93cb7063b3c29e28106190c1ccb0cd3fdaa72dbb5cf0243ae76e6e66ed90a2ae
2020-01-22T19:36:53.941-0800 [DEBUG] [TestEventLogger]     19:36:53.942 [Test worker] INFO  🐳 [spring-boot-launch-script/ubuntu-trusty-20160914:latest] - Container spring-boot-launch-script/ubuntu-trusty-20160914:latest started in PT2.321S
2020-01-22T19:36:58.925-0800 [DEBUG] [TestEventLogger] 
2020-01-22T19:36:58.926-0800 [DEBUG] [TestEventLogger] SysVinitLaunchScriptIntegrationTests > Ubuntu trusty-20160914 PASSED
2020-01-22T19:36:58.926-0800 [DEBUG] [TestEventLogger] 
2020-01-22T19:36:58.927-0800 [DEBUG] [TestEventLogger] SysVinitLaunchScriptIntegrationTests PASSED
2020-01-22T19:36:58.927-0800 [DEBUG] [TestEventLogger] 
2020-01-22T19:36:58.927-0800 [DEBUG] [TestEventLogger] Gradle Test Executor 1 PASSED
2020-01-22T19:36:58.927-0800 [LIFECYCLE] [org.gradle.api.internal.tasks.testing.worker.TestWorker] 
2020-01-22T19:36:58.927-0800 [INFO] [org.gradle.api.internal.tasks.testing.worker.TestWorker] Gradle Test Executor 1 finished executing tests.
2020-01-22T19:36:58.927-0800 [DEBUG] [org.gradle.process.internal.worker.child.ActionExecutionWorker] Completed Gradle Test Executor 1.
2020-01-22T19:37:02.897-0800 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2020-01-22T19:37:02.897-0800 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2020-01-22T19:37:02.897-0800 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2020-01-22T19:37:02.898-0800 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2020-01-22T19:37:02.898-0800 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2020-01-22T19:37:02.898-0800 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2020-01-22T19:37:12.887-0800 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
....
2020-01-22T20:17:22.938-0800 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2020-01-22T20:17:22.938-0800 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2020-01-22T20:17:22.938-0800 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2020-01-22T20:17:22.938-0800 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2020-01-22T20:17:22.938-0800 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
<============-> 99% EXECUTING [50m 9s]
> IDLE
> IDLE
> IDLE
> IDLE
> :spring-boot-tests:spring-boot-integration-tests:spring-boot-launch-script-tests:intTest > 93 tests completed, 1 skipped
> IDLE
> IDLE
```

jstack reports:

```
Full thread dump OpenJDK 64-Bit Server VM (25.232-b09 mixed mode):

"Attach Listener" #28 daemon prio=9 os_prio=31 tid=0x00007f7f8fac0800 nid=0x6303 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Forward input" #27 prio=5 os_prio=31 tid=0x00007f7fa20ca800 nid=0x9807 waiting on condition [0x0000700007a74000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007bc263b38> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at org.gradle.util.DisconnectableInputStream.read(DisconnectableInputStream.java:140)
	at org.gradle.launcher.daemon.client.InputForwarder$1.run(InputForwarder.java:78)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)

"DisconnectableInputStream source reader" #26 daemon prio=5 os_prio=31 tid=0x00007f7fa2084800 nid=0x610b runnable [0x0000700007946000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:255)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	- locked <0x00000007bc0f6bd8> (a java.io.BufferedInputStream)
	at org.gradle.util.DisconnectableInputStream$1.run(DisconnectableInputStream.java:98)
	at java.lang.Thread.run(Thread.java:748)

"process reaper" #22 daemon prio=10 os_prio=31 tid=0x00007f7fa0952800 nid=0x9603 runnable [0x0000700007971000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.UNIXProcess.waitForProcessExit(Native Method)
	at java.lang.UNIXProcess.lambda$initStreams$3(UNIXProcess.java:289)
	at java.lang.UNIXProcess$$Lambda$11/1834224344.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"pool-1-thread-1" #20 prio=5 os_prio=31 tid=0x00007f7f4f9d3800 nid=0x9903 waiting on condition [0x0000700007843000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007bc1352a8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"Service Thread" #17 daemon prio=9 os_prio=31 tid=0x00007f7f6f809800 nid=0x5e03 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread11" #16 daemon prio=9 os_prio=31 tid=0x00007f7fa0016800 nid=0x9d03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread10" #15 daemon prio=9 os_prio=31 tid=0x00007f7fa1004800 nid=0x5c03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread9" #14 daemon prio=9 os_prio=31 tid=0x00007f7fa0812000 nid=0x9f03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread8" #13 daemon prio=9 os_prio=31 tid=0x00007f7f58800000 nid=0xa103 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread7" #12 daemon prio=9 os_prio=31 tid=0x00007f7f8f83e000 nid=0x5a03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread6" #11 daemon prio=9 os_prio=31 tid=0x00007f7fa0000000 nid=0x5803 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread5" #10 daemon prio=9 os_prio=31 tid=0x00007f7f6f809000 nid=0xa303 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread4" #9 daemon prio=9 os_prio=31 tid=0x00007f7f6f808000 nid=0xa503 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread3" #8 daemon prio=9 os_prio=31 tid=0x00007f7f6f807800 nid=0x5703 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread2" #7 daemon prio=9 os_prio=31 tid=0x00007f7f8f82d000 nid=0xa803 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #6 daemon prio=9 os_prio=31 tid=0x00007f7f8f82c800 nid=0xa903 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=31 tid=0x00007f7f6f806000 nid=0x3603 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 tid=0x00007f7f6f805800 nid=0x3803 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=31 tid=0x00007f7fa0811000 nid=0x4303 in Object.wait() [0x000070000670d000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000007bc0f7588> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	- locked <0x00000007bc0f7588> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)

"Reference Handler" #2 daemon prio=10 os_prio=31 tid=0x00007f7fa080b000 nid=0x4403 in Object.wait() [0x000070000660a000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000007bc14b9b8> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x00000007bc14b9b8> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"main" #1 prio=5 os_prio=31 tid=0x00007f7fa2000800 nid=0x2603 runnable [0x00007000056db000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
	at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
	at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000007bc23b330> (a sun.nio.ch.Util$3)
	- locked <0x00000007bc23b320> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000007bc23b110> (a sun.nio.ch.KQueueSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
	at org.gradle.internal.remote.internal.inet.SocketConnection$SocketInputStream.read(SocketConnection.java:185)
	at com.esotericsoftware.kryo.io.Input.fill(Input.java:146)
	at com.esotericsoftware.kryo.io.Input.require(Input.java:178)
	at com.esotericsoftware.kryo.io.Input.readVarInt(Input.java:355)
	at com.esotericsoftware.kryo.io.Input.readInt(Input.java:350)
	at org.gradle.internal.serialize.kryo.KryoBackedDecoder.readSmallInt(KryoBackedDecoder.java:126)
	at org.gradle.internal.serialize.DefaultSerializerRegistry$TaggedTypeSerializer.read(DefaultSerializerRegistry.java:141)
	at org.gradle.internal.serialize.Serializers$StatefulSerializerAdapter$1.read(Serializers.java:36)
	at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:81)
	at org.gradle.launcher.daemon.client.DaemonClientConnection.receive(DaemonClientConnection.java:77)
	at org.gradle.launcher.daemon.client.DaemonClientConnection.receive(DaemonClientConnection.java:35)
	at org.gradle.launcher.daemon.client.DaemonClient.monitorBuild(DaemonClient.java:211)
	at org.gradle.launcher.daemon.client.DaemonClient.executeBuild(DaemonClient.java:180)
	at org.gradle.launcher.daemon.client.SingleUseDaemonClient.execute(SingleUseDaemonClient.java:55)
	at org.gradle.launcher.daemon.client.SingleUseDaemonClient.execute(SingleUseDaemonClient.java:38)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:56)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:212)
	at org.gradle.launcher.cli.DefaultCommandLineActionFactory$ParseAndBuildAction.execute(DefaultCommandLineActionFactory.java:404)
	at org.gradle.launcher.cli.DefaultCommandLineActionFactory$ParseAndBuildAction.execute(DefaultCommandLineActionFactory.java:376)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:38)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:23)
	at org.gradle.launcher.cli.DefaultCommandLineActionFactory$WithLogging.execute(DefaultCommandLineActionFactory.java:369)
	at org.gradle.launcher.Main.doAction(Main.java:35)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:35)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)

"VM Thread" os_prio=31 tid=0x00007f7fa080a000 nid=0x4603 runnable 

"GC task thread#0 (ParallelGC)" os_prio=31 tid=0x00007f7fa200d800 nid=0x2107 runnable 

"GC task thread#1 (ParallelGC)" os_prio=31 tid=0x00007f7fa200e000 nid=0x1f03 runnable 

"GC task thread#2 (ParallelGC)" os_prio=31 tid=0x00007f7fa0800800 nid=0x1d03 runnable 

"GC task thread#3 (ParallelGC)" os_prio=31 tid=0x00007f7fa0801000 nid=0x5403 runnable 

"GC task thread#4 (ParallelGC)" os_prio=31 tid=0x00007f7fa0801800 nid=0x2b03 runnable 

"GC task thread#5 (ParallelGC)" os_prio=31 tid=0x00007f7fa0805000 nid=0x5103 runnable 

"GC task thread#6 (ParallelGC)" os_prio=31 tid=0x00007f7fa0805800 nid=0x5003 runnable 

"GC task thread#7 (ParallelGC)" os_prio=31 tid=0x00007f7fa200e800 nid=0x4e03 runnable 

"GC task thread#8 (ParallelGC)" os_prio=31 tid=0x00007f7fa1005800 nid=0x4d03 runnable 

"GC task thread#9 (ParallelGC)" os_prio=31 tid=0x00007f7fa1006000 nid=0x4b03 runnable 

"GC task thread#10 (ParallelGC)" os_prio=31 tid=0x00007f7fa1007000 nid=0x4903 runnable 

"GC task thread#11 (ParallelGC)" os_prio=31 tid=0x00007f7fa1007800 nid=0x4703 runnable 

"GC task thread#12 (ParallelGC)" os_prio=31 tid=0x00007f7fa1008000 nid=0x2f03 runnable 

"VM Periodic Task Thread" os_prio=31 tid=0x00007f7f6f804800 nid=0x9a03 waiting on condition 

JNI global references: 243
```

**Comment by wilkinsona** [comment]
That looks like the JVM running the wrapper is waiting for communication from the daemon. If it happens again, it might be useful to get a thread dump from the daemon and any worker VMs.

**Comment by wilkinsona** [comment]
I don't think we've seen this one recently.
