### ISSUE TITLE
RedisReactiveHealthIndicator Redis Sentinel using password

### ISSUE THREAD

**Issue by sraveh** [spring-projects/spring-boot#20191]
Hi,

When using Spring boot 2.2.4 with Spring cloud gateway version Hoxton.SR1 with Rate limit filter using Redis Sentinel. The RedisReactiveHealthIndicator fails if redis sentinel is configure to use password.

```
org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getNativeConnection(LettuceConnectionFactory.java:1199) ~[spring-data-redis-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getConnection(LettuceConnectionFactory.java:1178) ~[spring-data-redis-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getSharedReactiveConnection(LettuceConnectionFactory.java:952) ~[spring-data-redis-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getReactiveConnection(LettuceConnectionFactory.java:429) ~[spring-data-redis-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getReactiveConnection(LettuceConnectionFactory.java:94) ~[spring-data-redis-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
	at reactor.core.publisher.MonoSupplier.call(MonoSupplier.java:85) ~[reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at reactor.core.publisher.FluxSubscribeOnCallable$CallableSubscribeOnSubscription.run(FluxSubscribeOnCallable.java:225) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: io.lettuce.core.RedisConnectionException
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:75) ~[lettuce-core-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56) ~[lettuce-core-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at io.lettuce.core.AbstractRedisClient.getConnection(AbstractRedisClient.java:234) ~[lettuce-core-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at io.lettuce.core.RedisClient.connect(RedisClient.java:207) ~[lettuce-core-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.lambda$getConnection$1(StandaloneConnectionProvider.java:115) ~[spring-data-redis-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
	at java.util.Optional.orElseGet(Optional.java:369) ~[?:?]
	at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.getConnection(StandaloneConnectionProvider.java:115) ~[spring-data-redis-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getNativeConnection(LettuceConnectionFactory.java:1197) ~[spring-data-redis-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
	... 13 more
Caused by: io.lettuce.core.RedisCommandExecutionException: NOAUTH Authentication required.
```

**Comment by snicoll** [comment]
@sraveh that looks like a duplicate of #19436 for which there is a fix in Lettuce `5.2.2.RELEASE`. Spring Boot `2.2.4` isn't using that but you can override `lettuce.version` to use `5.2.2.RELEASE` and see if that fixes your problem too. If that does not, please raise an issue on [the lettuce issue tracker](https://github.com/lettuce-io/lettuce-core/issues) with a small sample that reproduces the problem.
