### ISSUE TITLE
@MessagingGateway + @ConditionalOnBean = NPE

### ISSUE THREAD

**Issue by wwadge** [spring-projects/spring-boot#2080]
If you define ConditionalOnBean like this:
```
@ConditionalOnBean(name = "fooChannel")
@MessagingGateway(defaultRequestChannel = "fooChannel")
public interface Messaging { }
```

and a main application like this:
```
@Configuration
@ComponentScan
@EnableIntegration
@IntegrationComponentScan
@EnableAutoConfiguration
public class Application {
    public static void main(String[] args) {         SpringApplication.run(Application.class, args) }
}
```

you get the following NPE:
```
Caused by: java.lang.NullPointerException
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.containsBean(OnBeanCondition.java:135)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchingBeans(OnBeanCondition.java:124)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:79)
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:45)
```

because the beanFactory is null so beanFactory.containsBean(beanName) fails.

(this is on 1.2.0.RC2)

**Comment by snicoll** [comment]
I can't reproduce the NPE with 1.3.3 on the sample project. See the [Javadoc warning](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/condition/ConditionalOnBean.java#L34-L37) about use outside auto-configuration.
