### ISSUE TITLE
Unable to override "request" scope using CustomScopeConfigurer nor ApplicationContextInitializer

### ISSUE THREAD

**Issue by ceefour** [spring-projects/spring-boot#2082]
Affects: 1.1.9.RELEASE.

This `AppInitializer` worked in plain Spring + web.xml :

```
public class RequestOrCommandAppInitializer implements
		ApplicationContextInitializer<ConfigurableApplicationContext> {

	@Override
	public void initialize(ConfigurableApplicationContext applicationContext) {
			final CustomScopeConfigurer scopeConfigurer = new CustomScopeConfigurer();
			scopeConfigurer.setScopes(ImmutableMap.<String, Object>of(WebApplicationContext.SCOPE_REQUEST, new RequestOrCommandScope()));
			applicationContext.addBeanFactoryPostProcessor(scopeConfigurer);
	}
	
}
```

However in Spring Boot, it never worked. All request beans seem to always use the "original" Spring RequestScope.

I tried doing this, but still doesn't work:

	@Bean @Order(Ordered.LOWEST_PRECEDENCE)
	public static CustomScopeConfigurer requestOrCommandScopeConfigurer() {
		final CustomScopeConfigurer scopeConfigurer = new CustomScopeConfigurer();
		scopeConfigurer.setScopes(ImmutableMap.<String, Object>of(WebApplicationContext.SCOPE_REQUEST, new RequestOrCommandScope()));
		return scopeConfigurer;
	}

Stacktrace confirms this, my custom `request` scope override (`RequestOrCommandScope`) is never called by Spring.

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sysConfig' defined in class id.co.bippo.common.BippoSysConfigConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [id.co.bippo.common.BippoSysConfig]: Factory method 'sysConfig' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.tenantRef': Scope 'request' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet/DispatcherPortlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:602) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1113) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1008) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:505) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:216) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:350) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:331) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:968) ~[spring-context-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.soluvas.commons.shell.ExtCommandSupport.getBean(ExtCommandSupport.java:157) ~[classes/:na]
	at id.co.bippo.promotion.shell.PromoMigrateFromMongoCommand.doExecute(PromoMigrateFromMongoCommand.java:49) ~[classes/:na]
	at org.apache.karaf.shell.console.AbstractAction.execute(AbstractAction.java:33) ~[org.apache.karaf.shell.console-2.2.9.jar:na]
	at org.soluvas.commons.shell.ExtCommandSupport.execute(ExtCommandSupport.java:86) ~[classes/:na]
	at org.apache.felix.gogo.commands.basic.AbstractCommand.execute(AbstractCommand.java:35) ~[org.apache.karaf.shell.console-2.2.9.jar:na]
	at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:474) ~[org.apache.karaf.shell.console-2.2.9.jar:na]
	at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:400) ~[org.apache.karaf.shell.console-2.2.9.jar:na]
	at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108) ~[org.apache.karaf.shell.console-2.2.9.jar:na]
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183) ~[org.apache.karaf.shell.console-2.2.9.jar:na]
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120) ~[org.apache.karaf.shell.console-2.2.9.jar:na]
	at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:89) ~[org.apache.karaf.shell.console-2.2.9.jar:na]
	at org.apache.karaf.shell.console.jline.Console.run(Console.java:172) ~[org.apache.karaf.shell.console-2.2.9.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
	at blast.shell.karaf.ssh.BlastShellFactoryImpl$ShellImpl$2.doRun(BlastShellFactoryImpl.java:130) [blast-shell-karaf-ssh-0.13.jar:na]
	at blast.shell.karaf.ssh.BlastShellFactoryImpl$ShellImpl$2.run(BlastShellFactoryImpl.java:125) [blast-shell-karaf-ssh-0.13.jar:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [id.co.bippo.common.BippoSysConfig]: Factory method 'sysConfig' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.tenantRef': Scope 'request' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet/DispatcherPortlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:591) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1113) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1008) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:505) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:216) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:350) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:331) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:968) ~[spring-context-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.soluvas.commons.shell.ExtCommandSupport.getBean(ExtCommandSupport.java:157) ~[classes/:na]
	at id.co.bippo.promotion.shell.PromoMigrateFromMongoCommand.doExecute(PromoMigrateFromMongoCommand.java:49) ~[classes/:na]
	at org.apache.karaf.shell.console.AbstractAction.execute(AbstractAction.java:33) ~[org.apache.karaf.shell.console-2.2.9.jar:na]
	at org.soluvas.commons.shell.ExtCommandSupport.execute(ExtCommandSupport.java:86) ~[classes/:na]
	at org.apache.felix.gogo.commands.basic.AbstractCommand.execute(AbstractCommand.java:35) ~[org.apache.karaf.shell.console-2.2.9.jar:na]
	at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:474) ~[org.apache.karaf.shell.console-2.2.9.jar:na]
	at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:400) ~[org.apache.karaf.shell.console-2.2.9.jar:na]
	at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108) ~[org.apache.karaf.shell.console-2.2.9.jar:na]
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183) ~[org.apache.karaf.shell.console-2.2.9.jar:na]
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120) ~[org.apache.karaf.shell.console-2.2.9.jar:na]
	at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:89) ~[org.apache.karaf.shell.console-2.2.9.jar:na]
	at org.apache.karaf.shell.console.jline.Console.run(Console.java:172) ~[org.apache.karaf.shell.console-2.2.9.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
	at blast.shell.karaf.ssh.BlastShellFactoryImpl$ShellImpl$2.doRun(BlastShellFactoryImpl.java:130) [blast-shell-karaf-ssh-0.13.jar:na]
	at blast.shell.karaf.ssh.BlastShellFactoryImpl$ShellImpl$2.run(BlastShellFactoryImpl.java:125) [blast-shell-karaf-ssh-0.13.jar:na]
	... 24 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.tenantRef': Scope 'request' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet/DispatcherPortlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:351) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.aop.target.SimpleBeanTargetSource.getTarget(SimpleBeanTargetSource.java:35) ~[spring-aop-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:187) ~[spring-aop-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at com.sun.proxy.$Proxy92.getTenantId(Unknown Source) ~[na:na]
	at org.soluvas.commons.tenant.TenantBeans.getCurrent(TenantBeans.java:346) ~[classes/:na]
	at id.co.bippo.common.BippoSysConfigConfig.sysConfig(BippoSysConfigConfig.java:91) ~[classes/:na]
	at id.co.bippo.common.BippoSysConfigConfig$$EnhancerBySpringCGLIB$$f2ba35ba.CGLIB$sysConfig$2(<generated>) ~[na:na]
	at id.co.bippo.common.BippoSysConfigConfig$$EnhancerBySpringCGLIB$$f2ba35ba$$FastClassBySpringCGLIB$$91c046ce.invoke(<generated>) ~[na:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:312) ~[spring-context-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at id.co.bippo.common.BippoSysConfigConfig$$EnhancerBySpringCGLIB$$f2ba35ba.sysConfig(<generated>) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:591) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1113) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1008) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:505) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:216) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:350) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:331) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:968) ~[spring-context-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.soluvas.commons.shell.ExtCommandSupport.getBean(ExtCommandSupport.java:157) ~[classes/:na]
	at id.co.bippo.promotion.shell.PromoMigrateFromMongoCommand.doExecute(PromoMigrateFromMongoCommand.java:49) ~[classes/:na]
	at org.apache.karaf.shell.console.AbstractAction.execute(AbstractAction.java:33) ~[org.apache.karaf.shell.console-2.2.9.jar:na]
	at org.soluvas.commons.shell.ExtCommandSupport.execute(ExtCommandSupport.java:86) ~[classes/:na]
	at org.apache.felix.gogo.commands.basic.AbstractCommand.execute(AbstractCommand.java:35) ~[org.apache.karaf.shell.console-2.2.9.jar:na]
	at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:474) ~[org.apache.karaf.shell.console-2.2.9.jar:na]
	at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:400) ~[org.apache.karaf.shell.console-2.2.9.jar:na]
	at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108) ~[org.apache.karaf.shell.console-2.2.9.jar:na]
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183) ~[org.apache.karaf.shell.console-2.2.9.jar:na]
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120) ~[org.apache.karaf.shell.console-2.2.9.jar:na]
	at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:89) ~[org.apache.karaf.shell.console-2.2.9.jar:na]
	at org.apache.karaf.shell.console.jline.Console.run(Console.java:172) ~[org.apache.karaf.shell.console-2.2.9.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
	at blast.shell.karaf.ssh.BlastShellFactoryImpl$ShellImpl$2.doRun(BlastShellFactoryImpl.java:130) [blast-shell-karaf-ssh-0.13.jar:na]
	at blast.shell.karaf.ssh.BlastShellFactoryImpl$ShellImpl$2.run(BlastShellFactoryImpl.java:125) [blast-shell-karaf-ssh-0.13.jar:na]
	... 25 more
Caused by: java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet/DispatcherPortlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
	at org.springframework.web.context.request.RequestContextHolder.currentRequestAttributes(RequestContextHolder.java:131) ~[spring-web-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.web.context.request.AbstractRequestAttributesScope.get(AbstractRequestAttributesScope.java:41) ~[spring-web-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:336) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.aop.target.SimpleBeanTargetSource.getTarget(SimpleBeanTargetSource.java:35) ~[spring-aop-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:187) ~[spring-aop-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at com.sun.proxy.$Proxy92.getTenantId(Unknown Source) ~[na:na]
	at org.soluvas.commons.tenant.TenantBeans.getCurrent(TenantBeans.java:346) ~[classes/:na]
	at id.co.bippo.common.BippoSysConfigConfig.sysConfig(BippoSysConfigConfig.java:91) ~[classes/:na]
	at id.co.bippo.common.BippoSysConfigConfig$$EnhancerBySpringCGLIB$$f2ba35ba.CGLIB$sysConfig$2(<generated>) ~[na:na]
	at id.co.bippo.common.BippoSysConfigConfig$$EnhancerBySpringCGLIB$$f2ba35ba$$FastClassBySpringCGLIB$$91c046ce.invoke(<generated>) ~[na:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:312) ~[spring-context-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at id.co.bippo.common.BippoSysConfigConfig$$EnhancerBySpringCGLIB$$f2ba35ba.sysConfig(<generated>) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:591) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1113) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1008) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:505) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:216) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:350) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:331) ~[spring-beans-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:968) ~[spring-context-4.1.2.RELEASE.jar:4.1.2.RELEASE]
	at org.soluvas.commons.shell.ExtCommandSupport.getBean(ExtCommandSupport.java:157) ~[classes/:na]
	at id.co.bippo.promotion.shell.PromoMigrateFromMongoCommand.doExecute(PromoMigrateFromMongoCommand.java:49) ~[classes/:na]
	at org.apache.karaf.shell.console.AbstractAction.execute(AbstractAction.java:33) ~[org.apache.karaf.shell.console-2.2.9.jar:na]
	at org.soluvas.commons.shell.ExtCommandSupport.execute(ExtCommandSupport.java:86) ~[classes/:na]
	at org.apache.felix.gogo.commands.basic.AbstractCommand.execute(AbstractCommand.java:35) ~[org.apache.karaf.shell.console-2.2.9.jar:na]
	at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:474) ~[org.apache.karaf.shell.console-2.2.9.jar:na]
	at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:400) ~[org.apache.karaf.shell.console-2.2.9.jar:na]
	at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108) ~[org.apache.karaf.shell.console-2.2.9.jar:na]
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183) ~[org.apache.karaf.shell.console-2.2.9.jar:na]
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120) ~[org.apache.karaf.shell.console-2.2.9.jar:na]
	at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:89) ~[org.apache.karaf.shell.console-2.2.9.jar:na]
	at org.apache.karaf.shell.console.jline.Console.run(Console.java:172) ~[org.apache.karaf.shell.console-2.2.9.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
	at blast.shell.karaf.ssh.BlastShellFactoryImpl$ShellImpl$2.doRun(BlastShellFactoryImpl.java:130) [blast-shell-karaf-ssh-0.13.jar:na]
	at blast.shell.karaf.ssh.BlastShellFactoryImpl$ShellImpl$2.run(BlastShellFactoryImpl.java:125) [blast-shell-karaf-ssh-0.13.jar:na]
	... 41 more
```

**Comment by philwebb** [comment]
I've updated 1.2.1 so that scopes are not replaced. I'm not keen to apply this to 1.1.x as there is chance it could break existing applications.

**Comment by ceefour** [comment]
Thank you Phil :-)



Hendy Irawan - on Twitter <http://twitter.com/hendybippo> - on LinkedIn
<http://id.linkedin.com/in/hendyirawan>
Web Developer | Bippo Indonesia <http://www.bippo.co.id/> | Akselerator
Bisnis | Bandung
