### ISSUE TITLE
http-nio-8080-Acceptor-0 parking and refuse request

### ISSUE THREAD

**Issue by shlsky** [spring-projects/spring-boot#20965]
my spring boot website refuse request, but the JVM  is running. The stack information is as follows

```
"http-nio-8080-Acceptor-0" #130 daemon prio=5 os_prio=0 tid=0x00007f159f6b4530 nid=0x1fcf waiting on condition [0x00007f14dd973000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000005cde53ca0> (a org.apache.tomcat.util.threads.LimitLatch$Sync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at org.apache.tomcat.util.threads.LimitLatch.countUpOrAwait(LimitLatch.java:117)
	at org.apache.tomcat.util.net.AbstractEndpoint.countUpOrAwaitConnection(AbstractEndpoint.java:1062)
	at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:447)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None

"http-nio-8080-ClientPoller-0" #128 daemon prio=5 os_prio=0 tid=0x00007f14e06492e0 nid=0x1fcd runnable [0x00007f14dd9f5000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000005c22aba70> (a sun.nio.ch.Util$3)
	- locked <0x00000005c22aba60> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000005c22aba18> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at org.apache.tomcat.util.net.NioEndpoint$Poller.run(NioEndpoint.java:785)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None

http-nio-8080-Acceptor-0 is parking.
```

**Comment by shlsky** [comment]
spring boot 1.5.3.RELEASE

**Comment by snicoll** [comment]
@shlsky a partial thread dump is nowhere near enough information to figure out what might be going on. Please note that Spring Boot 1.x is End Of Life since August 2019 so I urge you to upgrade as soon as possible. Once you've done that and if the problem still occurs, please share a small sample we can run ourselves (zip or link to a github repo) and we can reopen this issue.
