### ISSUE TITLE
@ConfigurationProperties with @ConstructorBinding unable to bind default value supplied with @DefaultValue

### ISSUE THREAD

**Issue by jannis-baratheon** [spring-projects/spring-boot#21263]
Spring-boot version: 2.2.6.RELEASE

I have some simple ConfigurationProperties:

	package com.example.demo;
	
	import java.nio.file.Path;
	import org.springframework.boot.context.properties.ConfigurationProperties;
	import org.springframework.boot.context.properties.ConstructorBinding;
	import org.springframework.boot.context.properties.bind.DefaultValue;

	@ConfigurationProperties
	@ConstructorBinding
	public class ConfigurationPropertiesWithPathProperty {
		public static final String DEFAULT_VALUE = "default_value";

		private final Path somePathProperty;

		public ConfigurationPropertiesWithPathProperty(@DefaultValue(DEFAULT_VALUE) Path somePathProperty) {
			this.somePathProperty = somePathProperty;
		}

		public Path getSomePathProperty() {
			return somePathProperty;
		}
	}

I test it using a `org.springframework.boot.context.properties.bind.Binder`:

	package com.example.demo;

	import static org.assertj.core.api.Assertions.assertThat;

	import java.nio.file.Paths;
	import java.util.HashMap;
	import java.util.Map;
	import org.junit.jupiter.api.Test;
	import org.springframework.boot.context.properties.bind.BindResult;
	import org.springframework.boot.context.properties.bind.Bindable;
	import org.springframework.boot.context.properties.bind.Binder;
	import org.springframework.boot.context.properties.source.MapConfigurationPropertySource;

	public class PropertiesTest {

		@Test
		void bindsPathProperty() {
			String expectedPropertyValue = "some_value";
			Map<String, String> properties = new HashMap<>();
			properties.put("some_path_property", expectedPropertyValue);
			Binder binder = new Binder(new MapConfigurationPropertySource(properties));

			BindResult<ConfigurationPropertiesWithPathProperty> bindResult =
					binder.bind("", Bindable.of(ConfigurationPropertiesWithPathProperty.class));

			assertThat(bindResult.get().getSomePathProperty())
					.isEqualTo(Paths.get(expectedPropertyValue));
		}
	}

So far so good. Now when I try to bind the default value:

	package com.example.demo;

	import static org.assertj.core.api.Assertions.assertThat;

	import java.nio.file.Paths;
	import java.util.Collections;
	import java.util.HashMap;
	import java.util.Map;
	import org.junit.jupiter.api.Test;
	import org.springframework.boot.context.properties.bind.BindResult;
	import org.springframework.boot.context.properties.bind.Bindable;
	import org.springframework.boot.context.properties.bind.Binder;
	import org.springframework.boot.context.properties.source.MapConfigurationPropertySource;

	public class PropertiesTest {

		@Test
		void bindsDefaultValueToPathProperty() {
			Binder binder = new Binder(new MapConfigurationPropertySource(Collections.emptyMap()));

			BindResult<ConfigurationPropertiesWithPathProperty> bindResult =
					binder.bind("", Bindable.of(ConfigurationPropertiesWithPathProperty.class));

			assertThat(bindResult.get().getSomePathProperty())
					.isEqualTo(Paths.get(ConfigurationPropertiesWithPathProperty.DEFAULT_VALUE));
		}
	}

I get an exception:

	Failed to bind properties under '' to com.example.demo.ConfigurationPropertiesWithPathProperty
	org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under '' to com.example.demo.ConfigurationPropertiesWithPathProperty
		at org.springframework.boot.context.properties.bind.Binder.handleBindError(Binder.java:364)
		at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:324)
		at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:308)
		at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:238)
		at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:199)
		at com.example.demo.PropertiesTest.bindsDefaultValueToPathProperty(PropertiesTest.java:36)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:675)
		at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:125)
		at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:132)
		at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:124)
		at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:74)
		at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
		at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:104)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:62)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:43)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:35)
		at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
		at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:202)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:198)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:69)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
		at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
		at java.util.ArrayList.forEach(ArrayList.java:1257)
		at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
		at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
		at java.util.ArrayList.forEach(ArrayList.java:1257)
		at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
		at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
		at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
		at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
		at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
		at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
		at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
		at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
		at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
		at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
		at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
		at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
		at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
		at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
		at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
		at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
		at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
		at com.sun.proxy.$Proxy2.stop(Unknown Source)
		at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:132)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
		at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
		at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
		at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
		at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
		at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
		at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
		at java.lang.Thread.run(Thread.java:748)
	Caused by: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String[]] to type [@org.springframework.boot.context.properties.bind.DefaultValue java.nio.file.Path]
		at org.springframework.core.convert.support.GenericConversionService.handleConverterNotFound(GenericConversionService.java:321)
		at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:194)
		at org.springframework.boot.context.properties.bind.BindConverter$CompositeConversionService.convert(BindConverter.java:170)
		at org.springframework.boot.context.properties.bind.BindConverter.convert(BindConverter.java:96)
		at org.springframework.boot.context.properties.bind.ValueObjectBinder$ConstructorParameter.getDefaultValue(ValueObjectBinder.java:234)
		at org.springframework.boot.context.properties.bind.ValueObjectBinder.bind(ValueObjectBinder.java:68)
		at org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$5(Binder.java:452)
		at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:572)
		at org.springframework.boot.context.properties.bind.Binder$Context.withDataObject(Binder.java:558)
		at org.springframework.boot.context.properties.bind.Binder$Context.access$400(Binder.java:513)
		at org.springframework.boot.context.properties.bind.Binder.bindDataObject(Binder.java:450)
		at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:391)
		at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:320)
		... 92 more

**Comment by philwebb** [comment]
Thanks for the detailed description. The cause of the problem is that the conversion service does not support the array type used in `@DefaultValue` when using the `TypeConverterConverter` service.

The `Path` object uses a `PropertyEditor` based converter. If it has a full `Converter` then the `ArrayToObjectConverter` would take care of conversion.

**Comment by philwebb** [comment]
From @mbhave in the original issue:

For this, we rely on Spring Framework's `PathEditor` for converting from `String` to `Path`. The `PathEditor` returns a null value if the source value is `""`. This might be something that needs to be fixed in Spring Framework. If the rest of the team agrees, this issue will need to be transferred to Spring Framework's issue tracker.
