### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: # Licensed to the Apache Software Foundation (ASF) under one or more

### ISSUE THREAD

**Issue by basu58** [spring-projects/spring-boot#21491]
```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.3.0.RELEASE)

2020-05-18 20:28:28.958  INFO 16648 --- [           main] com.basu.ServletInitializer              : Starting ServletInitializer v1.0 on RudraPC with PID 16648 (E:\spring mvc workspace\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps\SpringBootDemo\WEB-INF\classes started by basud in C:\WINDOWS\System32)
2020-05-18 20:28:28.971  INFO 16648 --- [           main] com.basu.ServletInitializer              : No active profile set, falling back to default profiles: default
2020-05-18 20:28:32.176  INFO 16648 --- [           main] o.a.c.c.C.[.[.[/SpringBootDemo]          : Initializing Spring embedded WebApplicationContext
2020-05-18 20:28:32.177  INFO 16648 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 2962 ms
2020-05-18 20:28:33.399  INFO 16648 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-05-18 20:28:34.225  INFO 16648 --- [           main] com.basu.ServletInitializer              : Started ServletInitializer in 7.012 seconds (JVM running for 17.106)
2020-05-18 20:28:34.357  INFO 16648 --- [           main] org.apache.jasper.servlet.TldScanner     : At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
2020-05-18 20:28:34.404  INFO 16648 --- [           main] org.apache.coyote.ajp.AjpNioProtocol     : Starting ProtocolHandler ["ajp-nio-8019"]
2020-05-18 20:28:34.416  INFO 16648 --- [           main] org.apache.catalina.startup.Catalina     : Server startup in [13,804] milliseconds
2020-05-18 20:28:36.708 ERROR 16648 --- [nio-3536-exec-3] o.s.b.w.servlet.support.ErrorPageFilter  : Forwarding to error page from request [/index.jsp] due to exception [org.apache.jasper.JasperException: Unable to compile class for JSP]

org.apache.jasper.JasperException: org.apache.jasper.JasperException: Unable to compile class for JSP
	at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:604) ~[jasper.jar:9.0.24]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:422) ~[jasper.jar:9.0.24]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385) ~[jasper.jar:9.0.24]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329) ~[jasper.jar:9.0.24]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[servlet-api.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:9.0.24]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.24]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-websocket.jar:9.0.24]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.24]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.24]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.24]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.24]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.24]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.24]
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:128) [spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:66) [spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:103) [spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:121) [spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.24]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.24]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.24]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.24]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.24]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.24]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526) [catalina.jar:9.0.24]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.24]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.24]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678) [catalina.jar:9.0.24]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.24]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.24]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat-coyote.jar:9.0.24]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:9.0.24]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860) [tomcat-coyote.jar:9.0.24]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587) [tomcat-coyote.jar:9.0.24]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.24]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_20]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_20]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.24]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_20]
Caused by: org.apache.jasper.JasperException: Unable to compile class for JSP
	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:619) ~[jasper.jar:9.0.24]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:399) ~[jasper.jar:9.0.24]
	... 44 common frames omitted
Caused by: javax.el.ELException: Unable to find ExpressionFactory of type [# Licensed to the Apache Software Foundation (ASF) under one or more]
	at javax.el.ExpressionFactory.newInstance(ExpressionFactory.java:152) ~[el-api.jar:3.0.FR]
	at javax.el.ExpressionFactory.newInstance(ExpressionFactory.java:91) ~[el-api.jar:3.0.FR]
	at org.apache.jasper.compiler.PageInfo.<init>(PageInfo.java:80) ~[jasper.jar:9.0.24]
	at org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:120) ~[jasper.jar:9.0.24]
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:385) ~[jasper.jar:9.0.24]
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:362) ~[jasper.jar:9.0.24]
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:346) ~[jasper.jar:9.0.24]
	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:603) ~[jasper.jar:9.0.24]
	... 45 common frames omitted
Caused by: java.lang.ClassNotFoundException: # Licensed to the Apache Software Foundation (ASF) under one or more
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1365) ~[catalina.jar:9.0.24]
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1188) ~[catalina.jar:9.0.24]
	at javax.el.ExpressionFactory.newInstance(ExpressionFactory.java:145) ~[el-api.jar:3.0.FR]
	... 52 common frames omitted

2020-05-18 20:28:36.737  INFO 16648 --- [nio-3536-exec-3] o.a.c.c.C.[.[.[/SpringBootDemo]          : Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-05-18 20:28:36.738  INFO 16648 --- [nio-3536-exec-3] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-05-18 20:28:36.762  INFO 16648 --- [nio-3536-exec-3] o.s.web.servlet.DispatcherServlet        : Completed initialization in 24 ms
```

**Comment by wilkinsona** [comment]
This looks like a bug in your Tomcat setup. 3.0.FR of the EL API is trying to create a new `ExpressionFactory` instance and is finding some metadata that is causing it to use an Apache licence header as the fully-qualified type of the `ExpressionFactory` implementation. This is out of Spring Boot's control so I'm afraid there's nothing that we can do to help you here.
