### ISSUE TITLE
BeanCurrentlyInCreationException when using Atomikos and AOP

### ISSUE THREAD

**Issue by tvahrst** [spring-projects/spring-boot#21566]
Our Spring Boot applications are using Atomikos as JTA transaction manager (spring-boot-starter-jta-atomikos). Now we are trying to define an AspectJ Aspect for the datasource(s) for some reason. This leads to a BeanCurrentlyInCreationException. (see stacktrace at the end)

**Reason**: The exceptions is the result of the collision of two autoconfigurations

-  `AtomikosJtaConfiguration` defines a BeanFactoryPostProcessor (`AtomikosDependsOnBeanFactoryPostProcessor`) which in turn defines 'dependsOn' relations between `DataSource`s and Spring `PlatformTransactionManager`.

- `DataSourceInitializationConfiguration` defines a `DataSourceInitializerPostProcessor` which forces initialization of `DataSourceInitializerInvoker` as soon as a `DataSource` is seen. This causes an injection of the DataSource (currently in creation) into the DataSourceInitializer. 

Although this happens after the aspect kicks in (so the datasource is already finished), the former dependson rule signals to Spring a circular dependency.

Showcase: https://github.com/tvahrst/springboot-atomikos-aop-problem
Spring Boot version 2.3.0

I suppose, this isn't easily to solve, but it would help, if we could disable the DataSourceInitializer Autoconfiguration with an appropriate property. Our current workaround: we define a dummy-bean named `dataSourceInitializerPostProcessor` which blocks the bean definition of the regular post processor.

```
rg.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'dataSource': Bean with name 'dataSource' has been injected into other beans [atomikosTransactionManager] in its raw version as part of a circular reference, but has eventually been wrapped. This means that said other beans do not use the final version of the bean. This is often the result of over-eager type matching - consider using 'getBeanNamesForType' with the 'allowEagerInit' flag turned off, for example.
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:624) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:895) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at com.example.demo.DemoApplication.main(DemoApplication.java:12) ~[classes/:na]
```

**Comment by snicoll** [comment]
The review of datasource initialization in `2.5.x` has actually fixed this issue so I am going to close this now. Please upgrade to `2.5.x` at your earliest convenience.

**Comment by tvahrst** [comment]
> The review of datasource initialization in `2.5.x` has actually fixed this issue so I am going to close this now. Please upgrade to `2.5.x` at your earliest convenience.

Thx, works!
