### ISSUE TITLE
Lettuce adaptive refresh not working

### ISSUE THREAD

**Issue by kuldeepsingh99** [spring-projects/spring-boot#21583]
I am using spring latest version 2.3.1 and lettuce adaptive refresh is not working for me.

I am using 1 Master 2 Slave and 2 sentinel node, i have deployed the application in docker containers, in AWS ec2 ubuntu instance.

When master node dies then i am getting connection time out
```
io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 minute(s)
        at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51) ~[lettuce-core-5.3.0.RELEASE.jar!/:5.3.0.RELEASE]
        at io.lettuce.core.protocol.CommandExpiryWriter.lambda$potentiallyExpire$0(CommandExpiryWriter.java:167) ~[lettuce-core-5.3.0.RELEASE.jar!/:5.3.0.RELEASE]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.49.Final.jar!/:4.1.49.Final]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) ~[netty-common-4.1.49.Final.jar!/:4.1.49.Final]
        at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66) ~[netty-common-4.1.49.Final.jar!/:4.1.49.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.49.Final.jar!/:4.1.49.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.49.Final.jar!/:4.1.49.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.49.Final.jar!/:4.1.49.Final]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]

```

here is the application.yaml file configuration for redis

```
cache:
    type: redis  
    redis:
      cache-null-values: false
      time-to-live: 100000
      use-key-prefix: true
      
  redis:
    sentinel:
      master: mymaster
      nodes:
        - redis-sentinel:26379
        - redis-sentinel-1:26380
    timeout: 10s
        
        
    lettuce:
      pool:
        max-idle: -1
        max-active: -1
        max-wait: 2s
      cluster:
        refresh:
          adaptive: true
          period: 5s   
```

**Comment by philwebb** [comment]
Thanks for the report, but I think this is likely to be an issue with the Lettuce driver rather than something in Spring Boot's control. Please raise an issue with the Lettuce team [here](https://github.com/lettuce-io/lettuce-core/issues).

**Comment by kuldeepsingh99** [comment]
@philwebb As per this [issue](https://github.com/spring-projects/spring-boot/issues/15630) i have done the correct configuration, but still its working
