### ISSUE TITLE
spring-boot and spring-data-cassandra create the same @Bean

### ISSUE THREAD

**Issue by tszmytka** [spring-projects/spring-boot#21741]
Building a sample Cassandra-based application using spring-boot `2.3.0.RELEASE` and spring-data-cassandra `3.0.0.RELEASE` causes a clash for a bean of type `ReactiveSessionFactory`.
```
2020-06-07 15:26:34,604 DEBUG o.s.b.d.LoggingFailureAnalysisReporter [main] Application failed to start due to an exception
org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'reactiveCassandraSessionFactory' defined in class path resource [org/springframework/boot/autoconfigure/data/cassandra/CassandraReactiveDataAutoConfiguration.class]: Cannot register bean definition [Root bean: class [null]; scope=; abstract=false; lazyInit=null; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.data.cassandra.CassandraReactiveDataAutoConfiguration; factoryMethodName=reactiveCassandraSessionFactory; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/data/cassandra/CassandraReactiveDataAutoConfiguration.class]] for bean 'reactiveCassandraSessionFactory': There is already [Root bean: class [null]; scope=; abstract=false; lazyInit=null; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=cassandraConfig; factoryMethodName=reactiveCassandraSessionFactory; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [dev/tomek/data-cassandra/sampleapplication/persistence/CassandraConfig.class]] bound.
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.registerBeanDefinition(DefaultListableBeanFactory.java:943) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:286) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:144) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:120) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:331) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:236) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:280) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:96) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:706) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:62) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) [spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at dev.tomek.data-cassandra.sampleapplication.Sampleapplication.main(Sampleapplication.java:16) [main/:?]
```
`spring-data-cassandra` defines it in `AbstractReactiveCassandraConfiguration`, which you extend and mark with @Configuration.
`spring-boot` defines it in `CassandraReactiveDataAutoConfiguration`

I would annotate the bean in `CassandraReactiveDataAutoConfiguration` with `@ConditionalOnMissingBean`. This will allow applications to define their own `ReactiveSessionFactory` (through `AbstractReactiveCassandraConfiguration` or otherwise) and still provide a default definition if needed.

I can provide a PR but wanted to confirm the approach first.

**Comment by flinden68** [comment]
I want to have a look at this issue. Good opportunity to set up everything as described in Contributing Guidelines

**Comment by tszmytka** [comment]
Hi @flinden68 
Sorry but I already claimed this. I wrote this in the initial message but it got deleted while rephrasing by @snicoll 
The issue was only to confirm my solution proposal.

@snicoll Could you please assign the issue to me? Or is such a note enough?

**Comment by flinden68** [comment]
@snicoll Is the solution by adding only @ConditionalOnMissingBean to the bean? Seems too easy

**Comment by flinden68** [comment]
@tszmytka No problem, just fix it. I will wait for another one

**Comment by snicoll** [comment]
Fair enough @tszmytka. I've turn this as a first timer to let folks who never contributed to OSS to give it a go but you're right you've offered to help when you raised the issue. It's all yours.
