### ISSUE TITLE
@EnableConfigurationProperties should deduplicate

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-boot#2204]
I have independent modules that each need injection of a common "deployment info" `ConfigurationProperties` file. I'd like to simply annotate their autoconfig classes with `@EnableConfigurationProperties`, but then I end up with multiple copies of the properties bean and duplicate-bean exceptions.

Since the contents of the properties beans will be identical, the registrar for `@EnableConfigurationProperties` should register just one copy of the bean for any number of annotation-based requests.

**Comment by snicoll** [comment]
Dave, there's another example in #2639 it seems.

**Comment by dsyer** [comment]
Yeah, and it's obvious why that one is broken: the `@ConfigurationProperties` class is a `@Component` and it is directly referenced in `@EnableConfigurationProperties` so it is being added twice.

**Comment by wilkinsona** [comment]
Closing due to lack of response. Please comment again and we can reopen the issue if you're still having trouble.

**Comment by chrylis** [comment]
I've tried to replicate this and haven't been able to with 1.2.3. I'll update if it happens again.

**Comment by bogdansolga** [comment]
I still get an ```No qualifying bean of type [org.springframework.boot.autoconfigure.web.ServerProperties] is defined: expected single matching bean but found 2: serverProperties,server.CONFIGURATION_PROPERTIES``` error in 1.3.0.M2, although I'm not using the ```@EnableConfigurationProperties``` annotation directly on any config. 

Something must have changed in 1.3.0.M2, as I haven't got this issue in 1.3.0.M1.

Can anyone help me identify the culprit? I can try posting the simplified code, of course.

**Comment by dsyer** [comment]
That specific issue was dealt with in 1.3 but after M2 I believe. The culprit is Spring Session autoconfig. Try a snapshot.

**Comment by bogdansolga** [comment]
Thanks, Dave! Indeed, the issue no longer appears if I remove Spring Session from the classpath.

**Comment by dgomesbr** [comment]
Hmmm I'm still experiencing this on 1.3.0M5

APIProperties.java |
------------ |
```java
@Data
@ConfigurationProperties(prefix = "api")
@Configuration
public class APIProperties {
    List<String> blockedExtesions;
}
```

application.yml |
------------ |
```yaml
api:
  config:
    blocked:
      extensions:
        - ".exe"
        - ".dll"
        - ".bin"
        - ".dat"
        - ".osx"
```


ShortrConfigApplication.java |
------------ |
```@SpringBootApplication
@EnableAsync
@EnableConfigurationProperties({APIProperties.class})
public class ShortrConfigApplication {
    public static void main(String[] args) {
        SpringApplication.run(ShortrConfigApplication.class, args);
    }
}
```

Problematic bean:

ShorteningService.java |
------------ |
```java
@RestController
public class ShorteningService {

    private APIProperties props;

    @Autowired
    public ShorteningService(APIProperties apiProperties) {
        this.props = apiProperties;
    }

    @RequestMapping("test")
    String test(){
        return props.getBlockedExtesions().toString();
    }
}
```

Exception is:
```log
2015-09-13 22:15:25.973  WARN 61100 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [com.diegomagalhaes.shortr.api.configuration.APIProperties] is defined: expected single matching bean but found 2: APIProperties,api.CONFIGURATION_PROPERTIES
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1079) ~[spring-beans-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:967) ~[spring-beans-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:813) ~[spring-beans-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741) ~[spring-beans-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	... 24 common frames omitted
Wrapped by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'shorteningService' defined in file [D:\dev\projects\shortr\shortr-api\target\classes\com\diegomagalhaes\shortr\api\ShorteningService.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [com.diegomagalhaes.shortr.api.configuration.APIProperties]: : No qualifying bean of type [com.diegomagalhaes.shortr.api.configuration.APIProperties] is defined: expected single matching bean but found 2: APIProperties,api.CONFIGURATION_PROPERTIES; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [com.diegomagalhaes.shortr.api.configuration.APIProperties] is defined: expected single matching bean but found 2: APIProperties,api.CONFIGURATION_PROPERTIES
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749) ~[spring-beans-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:185) ~[spring-beans-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1143) ~[spring-beans-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046) ~[spring-beans-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510) ~[spring-beans-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:305) ~[spring-beans-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:301) ~[spring-beans-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:196) ~[spring-beans-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772) ~[spring-beans-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:834) ~[spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537) ~[spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) [spring-boot-1.3.0.M5.jar:1.3.0.M5]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:667) [spring-boot-1.3.0.M5.jar:1.3.0.M5]
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:342) [spring-boot-1.3.0.M5.jar:1.3.0.M5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:273) [spring-boot-1.3.0.M5.jar:1.3.0.M5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:980) [spring-boot-1.3.0.M5.jar:1.3.0.M5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:969) [spring-boot-1.3.0.M5.jar:1.3.0.M5]
	at com.diegomagalhaes.shortr.ShortrConfigApplication.main(ShortrConfigApplication.java:15) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140) [idea_rt.jar:na]
```

**Comment by snicoll** [comment]
Remove `@Configuration` from `APIProperties ` and you'll be fine. If that class is actually a configuration (you define `@Bean` or what not) my recommendation is to separate the two. It's more clear that way anyway.

**Comment by dgomesbr** [comment]
:+1:  Super thanks @snicoll
