### ISSUE TITLE
spring-boot-configuration-processor not compatible with Eclipse APT

### ISSUE THREAD

**Issue by kdvolder** [spring-projects/spring-boot#2287]
After configuring Eclipse to run the annotation processor as part of the build, it crashes the project's build with this exception:

java.lang.IllegalArgumentException: Unsupported location: CLASS_PATH
	at org.eclipse.jdt.internal.apt.pluggable.core.filer.IdeFilerImpl.getFileFromOutputLocation(IdeFilerImpl.java:188)
	at org.eclipse.jdt.internal.apt.pluggable.core.filer.IdeFilerImpl.getResource(IdeFilerImpl.java:154)
	at org.springframework.boot.configurationprocessor.ConfigurationMetadataAnnotationProcessor.mergeManualMetadata(ConfigurationMetadataAnnotationProcessor.java:302)
	at org.springframework.boot.configurationprocessor.ConfigurationMetadataAnnotationProcessor.writeMetaData(ConfigurationMetadataAnnotationProcessor.java:280)
	at org.springframework.boot.configurationprocessor.ConfigurationMetadataAnnotationProcessor.process(ConfigurationMetadataAnnotationProcessor.java:123)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:139)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:110)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:159)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:134)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:855)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:434)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:367)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:179)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:304)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:61)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:256)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:175)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:401)
	at org.eclipse.core.internal.resources.Project$1.run(Project.java:618)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2313)
	at org.eclipse.core.internal.resources.Project.internalBuild(Project.java:597)
	at org.eclipse.core.internal.resources.Project.build(Project.java:114)
	at org.eclipse.jdt.internal.ui.util.CoreUtility$BuildJob.run(CoreUtility.java:161)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

**Comment by philwebb** [comment]
Is there any documentation on how to enable the annotation processor in eclipse?

**Comment by kdvolder** [comment]
> Is there any documentation on how to enable the annotation processor in eclipse?

This is indeed a bit complicated. Glad you already figured out how to use m2e-apt. 

Just FYI: STS support for editing properties files will provide a Maven and Gradle project configurator to automatically enable JDT-APT when spring-boot-configuration-processor is on the classpath (i.e. future version of STS will automatically enable this if you import or update a maven/gradle project). So hopefully in the future the spring-boot-configuration-processor should 'just work' instead of needing you to figure this out.

**Comment by dnouls** [comment]
@philwebb can you explain what you did to get it to work with m2e-apt ? I get the same error in eclipse with another annotation processor. I have m2e-apt installed in eclipse (Oxygen) but the code generator is not properly executing.

**Comment by snicoll** [comment]
@dnouls we don't use the tracker for questions and this issue is closed for over 2 years. Please do ask on StackOverflow or join us on Gitter.
