### ISSUE TITLE
Hystrix Dashboard from Spring Cloud 1.0.0.BUILD-SNAPSHOT will no longer start with Spring Boot 1.2.1.BUILD-SNAPSHOT

### ISSUE THREAD

**Issue by mstine** [spring-projects/spring-boot#2305]
App found here (https://github.com/mstine/microservices-lab/tree/master/springbox-cloud/hystrixDashboard) will not start.

Stacktrace:
=========

    Caused by: java.lang.IllegalStateException: Error processing condition on org.springframework.boot.actuate.autoconfigure.ManagementServerPropertiesAutoConfiguration.managementServerProperties
            at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:58)
            at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:102)
            at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:185)
            at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.j va:148)
            at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:124)
            at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:318)
            at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:239)
            at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:254)
            at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:94)
            at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:606)
            at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:462)
            at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
            at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:691)
            at org.springframework.boot.SpringApplication.run(SpringApplication.java:321)
            at org.springframework.boot.SpringApplication.run(SpringApplication.java:961)
            at org.springframework.boot.SpringApplication.run(SpringApplication.java:950)
            at io.pivotal.microservices.hystrixdashboard.Application.main(Application.java:23)
            ... 6 more
    Caused by: java.lang.IllegalArgumentException: @ConditionalOnMissingBean annotations must specify at least one bean (type, name or annotation)
            at org.springframework.util.Assert.isTrue(Assert.java:65)
            at org.springframework.boot.autoconfigure.condition.OnBeanCondition$BeanSearchSpec.<init>(OnBeanCondition.java:219)
            at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:88)
            at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:45)
            ... 22 more

Eventually removed the issue by locking Boot dependencies down to 1.2.0.RELEASE with Gradle dependency mgmt plugin:

    dependencyManagement {
            dependencies {
                dependencySet(group:"org.springframework.boot", version: springBootVersion) {
                    entry "spring-boot-starter"
                    entry "spring-boot-starter-web"
                    entry "spring-boot-starter-actuator"
                    entry "spring-boot"
                    entry "spring-boot-autoconfigure"
                }
            }
        }

All of this seems to have happened in the last two days...everything was working on January 5. I was OOO on January 6, and noticed the problem this evening, January 7. Nothing has changed in the Hystrix Dashboard code in several days, so I'm guessing something was introduced in Boot in the last two days that has made Hystrix Dashboard unhappy. All other apps in this repo work fine.

**Comment by mstine** [comment]
Turns out this was me inadvertently mismatching dependencies...locking everything down to 1.2.1.BUILD-SNAPSHOT resolves the issue.

**Comment by ruairitobrien** [comment]
Thanks for this. Ran in to the same issue and this (locking to  1.2.1.RELEASE) solved it.
