### ISSUE TITLE
JarCommand removes @GrabResolver before it can be used

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#2330]
JarCommand removes `@GrabResolver` before it can be used (in an AST), so any dependencies that need to be resolved externally are missing or wrong (and you might only find out at runtime).

**Comment by philwebb** [comment]
Got a sample app?

**Comment by wilkinsona** [comment]
__app.groovy:__
```groovy
@GrabResolver(name = 'restlet.org', root = 'http://maven.restlet.org')
@Grab('org.restlet:org.restlet:1.1.9')
class MyApp {

}
```

```
$ rm -r ~/.m2/repository/org/restlet
$ spring jar my-app.jar app.groovy

startup failed:
General error during conversion: org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact org.restlet:org.restlet:jar:1.1.9 in local (file:/Users/awilkinson/.m2/repository/)

org.springframework.boot.cli.compiler.grape.DependencyResolutionFailedException: org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact org.restlet:org.restlet:jar:1.1.9 in local (file:/Users/awilkinson/.m2/repository/)
	at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.resolve(AetherGrapeEngine.java:304)
	at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.grab(AetherGrapeEngine.java:112)
	at groovy.grape.Grape.grab(Grape.java:163)
	at groovy.grape.GrabAnnotationTransformation.visit(GrabAnnotationTransformation.java:358)
	at org.codehaus.groovy.transform.ASTTransformationVisitor$3.call(ASTTransformationVisitor.java:319)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:923)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:585)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:561)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:538)
	at org.springframework.boot.cli.compiler.GroovyCompiler.compile(GroovyCompiler.java:197)
	at org.springframework.boot.cli.command.jar.JarCommand$JarOptionHandler.run(JarCommand.java:127)
	at org.springframework.boot.cli.command.options.OptionHandler.run(OptionHandler.java:92)
	at org.springframework.boot.cli.command.OptionParsingCommand.run(OptionParsingCommand.java:53)
	at org.springframework.boot.cli.command.CommandRunner.run(CommandRunner.java:221)
	at org.springframework.boot.cli.command.CommandRunner.runAndHandleErrors(CommandRunner.java:171)
	at org.springframework.boot.cli.SpringCli.main(SpringCli.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact org.restlet:org.restlet:jar:1.1.9 in local (file:/Users/awilkinson/.m2/repository/)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:405)
	at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.resolve(AetherGrapeEngine.java:298)
	... 21 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.restlet:org.restlet:jar:1.1.9 in local (file:/Users/awilkinson/.m2/repository/)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:462)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:264)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:388)
	... 22 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.restlet:org.restlet:jar:1.1.9 in local (file:/Users/awilkinson/.m2/repository/)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:538)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:439)
	... 24 more

1 error
```
