### ISSUE TITLE
JVM Crash in Test Excecution

### ISSUE THREAD

**Issue by GrmpfNarf** [spring-projects/spring-boot#23536]
Hello everybody,
updating Spring Boot from 2.3.2.RELEASE to 2.3.3.RELEASE cases some of my tests to crash the JVM. The issue remains in 2.3.4.RELEASE.

The issue only appears when executing the Build in Jenkins and not local on my computer.

````
ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project wbcigw: There are test failures.
[ERROR] 
[ERROR] Please refer to /XXX/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /XXXXX && /opt/java/jdk-11.0.3+7/bin/java -javaagent:/XXXX/.m2/repository/org/jacoco/org.jacoco.agent/0.8.6/org.jacoco.agent-0.8.6-runtime.jar=destfile=/XXX/target/jacoco.exec -jar /XXX/target/surefire/surefirebooter15011613432869566080.jar /XXXX/target/surefire 2020-09-30T09-17-31_909-jvmRun1 surefire18437430297612775987tmp surefire_01229251053928594050tmp
[ERROR] Process Exit Code: 0
[ERROR] Crashed tests:
[ERROR] XXXXTest
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /XXXX && /opt/java/jdk-11.0.3+7/bin/java -javaagent:/XXX/.m2/repository/org/jacoco/org.jacoco.agent/0.8.6/org.jacoco.agent-0.8.6-runtime.jar=destfile=/XXXX/target/jacoco.exec -jar /XXXX/target/surefire/surefirebooter15011613432869566080.jar /XXXX/target/surefire 2020-09-30T09-17-31_909-jvmRun1 surefire18437430297612775987tmp surefire_01229251053928594050tmp
[ERROR] Process Exit Code: 0
[ERROR] Crashed tests:
[ERROR] XXXTest
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:669)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:282)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
````

The Testclass is configured like this
````
@Transactional(value = "XXX.hsql.transactionManager")
@SpringBootTest(classes = {DatabaseTestApplication.class}, webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("dbtest")
@AutoConfigureTestEntityManager
@AutoConfigureTestDatabase
````
It uses JUNIT 5 normal and Prameterized Tests

Downgrading the spring-boot-starter-test to 2.3.2.RELEASE does not work.
I also tried to replace the changed dependency versions from ``spring-boot-dependencies`` by the old ones from 2.3.2.RELEASE but this also does not help.

The Project has two Datasources, also in the tests.

If any more informations needed I will try to provide them.

Thanks in advance.

**Comment by wilkinsona** [comment]
Thanks for the report.

If the JVM is crashing, there's not much we can do about, unfortunately, and you'd have to raise it with your JVM provider. However, it's not clear from the above that the JVM has actually crashed. Have you checked the dump files as recommended by Surefire?

> Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.

**Comment by GrmpfNarf** [comment]
Hi,
you are right the JDK is a little outdated. I've requested to update it on Jenkins maybe the error will be resolved with that. I will respond with the result as soon as possible. Thanks for the hint.

**Comment by GrmpfNarf** [comment]
Hi,
thanks again for the hint the issue is resolved by updating the jdk on the Jenkins server. For the sake of completnesses:
The issue appears on AdoptOpenJDK in version 11.0.3+7-hotspot and does not appear anymore in the current version 11.0.8+10.
