### ISSUE TITLE
It's not possible making Callable method in Spring Controller under Undertow

### ISSUE THREAD

**Issue by tryIO** [spring-projects/spring-boot#2365]
Hi! I just tried the following piece of Groovy code:

    @SpringBootApplication
    class WebApp { static void main(String ... args) { SpringApplication.run WebApp, args }

    @RestController
    class DummyController {
        @RequestMapping('/dummy')
        Callable<String> dummy { return { 'Dummy' } }
    }

and run it with the default embedded server in starter-web (that is Tomcat). This works ok and the endpoint responds w/o any issues, however if I try to switch to the new starter-undertow, the server throws such exception: 

    java.lang.IllegalStateException: No value for key [org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean@166e2c19] bound to thread [XNIO-1 task-2]
        at org.springframework.transaction.support.TransactionSynchronizationManager.unbindResource(TransactionSynchronizationManager.java:210)
        at org.springframework.orm.jpa.support.OpenEntityManagerInViewInterceptor.afterConcurrentHandlingStarted(OpenEntityManagerInViewInterceptor.java:136)
        at org.springframework.web.servlet.handler.WebRequestHandlerInterceptorAdapter.afterConcurrentHandlingStarted(WebRequestHandlerInterceptorAdapter.java:80)
        at org.springframework.web.servlet.HandlerExecutionChain.applyAfterConcurrentHandlingStarted(HandlerExecutionChain.java:186)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:877)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:82)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:61)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchToPath(ServletInitialHandler.java:192)
        at io.undertow.servlet.spec.RequestDispatcherImpl.error(RequestDispatcherImpl.java:403)
        at io.undertow.servlet.spec.RequestDispatcherImpl.error(RequestDispatcherImpl.java:314)
        at io.undertow.servlet.spec.HttpServletResponseImpl.doErrorDispatch(HttpServletResponseImpl.java:148)
        at io.undertow.servlet.spec.HttpServletResponseImpl.sendError(HttpServletResponseImpl.java:136)
        at io.undertow.servlet.spec.HttpServletResponseImpl.sendError(HttpServletResponseImpl.java:167)
        at org.springframework.web.context.request.async.TimeoutCallableProcessingInterceptor.handleTimeout(TimeoutCallableProcessingInterceptor.java:43)
        at org.springframework.web.context.request.async.CallableInterceptorChain.triggerAfterTimeout(CallableInterceptorChain.java:81)
        at org.springframework.web.context.request.async.WebAsyncManager$2.run(WebAsyncManager.java:293)
        at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:140)
        at io.undertow.servlet.spec.AsyncContextImpl.onAsyncTimeout(AsyncContextImpl.java:615)
        at io.undertow.servlet.spec.AsyncContextImpl.access$600(AsyncContextImpl.java:71)
        at io.undertow.servlet.spec.AsyncContextImpl$TimeoutTask$1.run(AsyncContextImpl.java:488)
        at io.undertow.servlet.spec.AsyncContextImpl$TaskDispatchRunnable.run(AsyncContextImpl.java:575)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Do I missed something that I need to configure properly for Undertow, or there's really something wrong?

Here my configuration of dependencies in Gradle:

	dependencies {
		compile group: 'org.codehaus.groovy', name: 'groovy-all', version: '2.4.0-rc-1'

		compile group: 'org.springframework.boot', name: 'spring-boot-starter-web', version: "${springBoot}"
		compile group: 'org.springframework.boot', name: 'spring-boot-starter-undertow', version: "${springBoot}"
		compile group: 'org.springframework.boot', name: 'spring-boot-starter-data-jpa', version: "${springBoot}"
		compile group: 'org.springframework.boot', name: 'spring-boot-starter-data-rest', version: "${springBoot}"
		compile group: 'org.springframework.boot', name: 'spring-boot-starter-actuator', version: "${springBoot}"

		compile group: 'org.hsqldb', name: 'hsqldb', version: '2.3.2'
	}

**Comment by wilkinsona** [comment]
We are configuring the Undertow deployment's context path to `/` by default. Undertow's `AsyncContextImpl.dispatch` tries to look up the deployment using the request URI. This was returning `null` and leading to a silent failure of the dispatch followed by the timeout shown above.

A workaround to get this working with 1.2.1 is to customise the deployment with the correct context path (""):

```java
    @Bean
    public UndertowEmbeddedServletContainerFactory factory() {
    	UndertowEmbeddedServletContainerFactory factory = new UndertowEmbeddedServletContainerFactory();
    	factory.addDeploymentInfoCustomizers(new UndertowDeploymentInfoCustomizer() {
			
			@Override
			public void customize(DeploymentInfo deploymentInfo) {
				deploymentInfo.setContextPath("");
			}
		});
    	return factory;
    }
```

**Comment by tryIO** [comment]
That's great thanks! Here the same code in Groovy:

    @Bean
    UndertowEmbeddedServletContainerFactory factory() {
        def factory = new UndertowEmbeddedServletContainerFactory()

        factory.addDeploymentInfoCustomizers({ info -> info.setContextPath(GString.EMPTY) } as UndertowDeploymentInfoCustomizer)

        return factory
    }
