### ISSUE TITLE
Issue with Thymeleaf DOCTYPE on Spring Boot 1.2.1

### ISSUE THREAD

**Issue by davetownsend** [spring-projects/spring-boot#2401]
Getting this error with boot 1.2.1 when going back to a Thymeleaf page. 
```
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
file:/Users/DTownsend/projects/matson/mobile/sma-api-proxy/build/resources/main/templates/dashboard.html: 1: unexpected token: < @ line 1, column 1.
   <!DOCTYPE html SYSTEM "http://www.thymeleaf.org/dtd/xhtml1-strict-thymeleaf-spring4-3.dtd">
```
Do not get the error on boot 1.1.10

Using Groovy 2.3.9

Also tried ```<!DOCTYPE html SYSTEM "http://www.thymeleaf.org/dtd/xhtml1-strict-thymeleaf-spring4-4.dtd">``` with same error results.

_Full Stack Trace for reference_
```
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
file:/Users/DTownsend/projects/matson/mobile/sma-api-proxy/build/resources/main/templates/dashboard.html: 1: unexpected token: < @ line 1, column 1.
   <!DOCTYPE html SYSTEM "http://www.thymeleaf.org/dtd/xhtml1-strict-thymeleaf-spring4-3.dtd">
   ^

1 error

	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:978) ~[spring-webmvc-4.1.3.RELEASE.jar:4.1.3.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857) ~[spring-webmvc-4.1.3.RELEASE.jar:4.1.3.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:734) ~[jboss-servlet-api_3.0_spec-1.0.2.Final-redhat-1.jar!/:1.0.2.Final-redhat-1]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842) ~[spring-webmvc-4.1.3.RELEASE.jar:4.1.3.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) ~[jboss-servlet-api_3.0_spec-1.0.2.Final-redhat-1.jar!/:1.0.2.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295) [jbossweb-7.3.2.Final-redhat-1.jar!/:7.3.2.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.3.2.Final-redhat-1.jar!/:7.3.2.Final-redhat-1]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88) ~[spring-web-4.1.3.RELEASE.jar:4.1.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.1.3.RELEASE.jar:4.1.3.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.3.2.Final-redhat-1.jar!/:7.3.2.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.3.2.Final-redhat-1.jar!/:7.3.2.Final-redhat-1]
	at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter.doFilterInternal(EndpointWebMvcAutoConfiguration.java:288) ~[spring-boot-actuator-1.2.0.RELEASE.jar:1.2.0.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.1.3.RELEASE.jar:4.1.3.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.3.2.Final-redhat-1.jar!/:7.3.2.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.3.2.Final-redhat-1.jar!/:7.3.2.Final-redhat-1]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77) ~[spring-web-4.1.3.RELEASE.jar:4.1.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.1.3.RELEASE.jar:4.1.3.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.3.2.Final-redhat-1.jar!/:7.3.2.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.3.2.Final-redhat-1.jar!/:7.3.2.Final-redhat-1]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118) ~[spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84) ~[spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) ~[spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113) ~[spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) ~[spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103) ~[spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) ~[spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113) ~[spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) ~[spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154) ~[spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) ~[spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45) ~[spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) ~[spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:201) ~[spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) ~[spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:110) ~[spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) ~[spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:57) ~[spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.1.3.RELEASE.jar:4.1.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) ~[spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87) ~[spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) ~[spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50) ~[spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.1.3.RELEASE.jar:4.1.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) ~[spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192) ~[spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160) ~[spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.3.2.Final-redhat-1.jar!/:7.3.2.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.3.2.Final-redhat-1.jar!/:7.3.2.Final-redhat-1]
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:100) ~[spring-boot-actuator-1.2.0.RELEASE.jar:1.2.0.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.1.3.RELEASE.jar:4.1.3.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.3.2.Final-redhat-1.jar!/:7.3.2.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.3.2.Final-redhat-1.jar!/:7.3.2.Final-redhat-1]
	at org.springframework.boot.actuate.autoconfigure.MetricFilterAutoConfiguration$MetricsFilter.doFilterInternal(MetricFilterAutoConfiguration.java:90) ~[spring-boot-actuator-1.2.0.RELEASE.jar:1.2.0.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.1.3.RELEASE.jar:4.1.3.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.3.2.Final-redhat-1.jar!/:7.3.2.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.3.2.Final-redhat-1.jar!/:7.3.2.Final-redhat-1]
	at org.springframework.boot.context.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:108) [spring-boot-1.2.0.RELEASE.jar:1.2.0.RELEASE]
	at org.springframework.boot.context.web.ErrorPageFilter.access$000(ErrorPageFilter.java:59) [spring-boot-1.2.0.RELEASE.jar:1.2.0.RELEASE]
	at org.springframework.boot.context.web.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:88) [spring-boot-1.2.0.RELEASE.jar:1.2.0.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.1.3.RELEASE.jar:4.1.3.RELEASE]
	at org.springframework.boot.context.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:101) [spring-boot-1.2.0.RELEASE.jar:1.2.0.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.3.2.Final-redhat-1.jar!/:7.3.2.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.3.2.Final-redhat-1.jar!/:7.3.2.Final-redhat-1]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:230) [jbossweb-7.3.2.Final-redhat-1.jar!/:7.3.2.Final-redhat-1]
	at org.apache.catalina.core.StandardContextValve.__invoke(StandardContextValve.java:149) [jbossweb-7.3.2.Final-redhat-1.jar!/:7.3.2.Final-redhat-1]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java) [jbossweb-7.3.2.Final-redhat-1.jar!/:7.3.2.Final-redhat-1]
	at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50) [jboss-as-jpa-7.3.4.Final-redhat-1.jar!/:7.3.4.Final-redhat-1]
	at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50) [jboss-as-jpa-7.3.4.Final-redhat-1.jar!/:7.3.4.Final-redhat-1]
	at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) [jboss-as-web-7.3.4.Final-redhat-1.jar!/:7.3.4.Final-redhat-1]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145) [jbossweb-7.3.2.Final-redhat-1.jar!/:7.3.2.Final-redhat-1]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.3.2.Final-redhat-1.jar!/:7.3.2.Final-redhat-1]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.3.2.Final-redhat-1.jar!/:7.3.2.Final-redhat-1]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:336) [jbossweb-7.3.2.Final-redhat-1.jar!/:7.3.2.Final-redhat-1]
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856) [jbossweb-7.3.2.Final-redhat-1.jar!/:7.3.2.Final-redhat-1]
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653) [jbossweb-7.3.2.Final-redhat-1.jar!/:7.3.2.Final-redhat-1]
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:926) [jbossweb-7.3.2.Final-redhat-1.jar!/:7.3.2.Final-redhat-1]
	at java.lang.Thread.run(Thread.java:744) [na:na]
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
file:/Users/DTownsend/projects/matson/mobile/sma-api-proxy/build/resources/main/templates/dashboard.html: 1: unexpected token: < @ line 1, column 1.
   <!DOCTYPE html SYSTEM "http://www.thymeleaf.org/dtd/xhtml1-strict-thymeleaf-spring4-3.dtd">
```

**Comment by davetownsend** [comment]
Thought this may have been related to jrebel since the html file is being referenced from the local build dir:
```
file:/Users/DTownsend/projects/matson/mobile/sma-api-proxy/build/resources/main/templates/dashboard.html
```

started server without jrebel and getting same error but now referencing the ```vfs```
```
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
vfs:/content/SMAProxy.war/WEB-INF/classes/templates/dashboard.html: 1: unexpected token: < @ line 1, column 1.
   <!DOCTYPE html SYSTEM "http://www.thymeleaf.org/dtd/xhtml1-strict-thymeleaf-spring4-3.dtd">
```
This app is running on JBoss EAP 6.2.4.GA

**Comment by wilkinsona** [comment]
This sounds a lot like #2212. Do you have groovy-all or groovy-templates on the classpath?

**Comment by davetownsend** [comment]
Yep, that's what it was, groovy-all was the issue. thx.

**Comment by wilkinsona** [comment]
@davetownsend Did you have caching disabled? If you have a set of steps that can reproduce this reliably, we'd love to hear them as I don't think we're 100% sure of (all the) cause(s) of #2212. Thanks.

**Comment by davetownsend** [comment]
@wilkinsona I tried it with both ```spring.thymeleaf.cache=false``` and ```spring.thymeleaf.cache=true``` with the same error result when ```compile 'org.codehaus.groovy:groovy-all:2.4.0``` in gradle.build.

I was able to resolve 2 ways.

1. Leave  ```compile 'org.codehaus.groovy:groovy-all:2.4.0``` in build file and add ```spring.groovy.template.enabled=false``` in application.properties.

2. Change dependency from ```compile 'org.codehaus.groovy:groovy-all:2.4.0``` to  ```compile org.codehaus.groovy:groovy:2.4.0``` (with this setting, caching settings makes no difference, it works properly on or off)

I opted for option 2 based on @dsyer comment in https://github.com/spring-projects/spring-boot/issues/2212 about groovy-all.

**Comment by wilkinsona** [comment]
@davetownsend Thanks. The cache setting making no difference matches some analysis that I did earlier today. If you have the time to share a small app that illustrates the problem I'd love to get my hands on it. Thus far, we've been unable to figure out exactly why things are breaking when groovy-all is on the classpath as the Groovy template stuff should only be looking at templates named `*.tpl`.

**Comment by davetownsend** [comment]
@wilkinsona sure, here's a working sample. https://github.com/davetownsend/test-bug

Just clone the repo
Run gradle build
Run ./start.sh
Point browser to: [http://localhost:8181/admin/dashboard](http://localhost:8181/admin/dashboard)

Click the **docs** button to go to docs page
then click **back to dashboard** link and the page will blow up.  

You can open build.gradle and comment out ```compile "org.codehaus.groovy:groovy-all:$groovyVersion"```
and uncomment ```//compile "org.codehaus.groovy:groovy:$groovyVersion"``` 
re-build and run app and the links should properly

**Comment by wilkinsona** [comment]
@davetownsend Fantastic. Thank you!
