### ISSUE TITLE
RedisAutoConfiguration fails without jedis

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-boot#2406]
Not really sure if this a real problem but it looks like missing jedis libs are causing some trouble. I'm implementing dist locking in `spring-cloud-cluster` on top of redis any rely `RedisAutoConfiguration` to create `RedisConnectionFactory` so that I can autowire it.

I originally just used `org.springframework.integration:spring-integration-redis` which is pulling in `spring-data-redis` but not `redis.clients:jedis`. This leads to error:

```
java.lang.IllegalStateException: Failed to introspect annotations: class org.springframework.boot.autoconfigure.redis.RedisAutoConfiguration
	at org.springframework.core.annotation.AnnotatedElementUtils.process(AnnotatedElementUtils.java:166)
	at org.springframework.core.annotation.AnnotatedElementUtils.isAnnotated(AnnotatedElementUtils.java:73)
	at org.springframework.core.type.StandardAnnotationMetadata.isAnnotated(StandardAnnotationMetadata.java:102)
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:74)
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:64)
	at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.registerBean(AnnotatedBeanDefinitionReader.java:140)
	at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.registerBean(AnnotatedBeanDefinitionReader.java:127)
	at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.register(AnnotatedBeanDefinitionReader.java:122)
	at org.springframework.context.annotation.AnnotationConfigApplicationContext.register(AnnotationConfigApplicationContext.java:150)
	at org.springframework.cloud.autoconfigure.lock.RedisLockServiceAutoConfigurationTests.testDefaults(RedisLockServiceAutoConfigurationTests.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3513)
	at java.lang.Class.annotationData(Class.java:3502)
	at java.lang.Class.getAnnotations(Class.java:3438)
	at org.springframework.core.annotation.AnnotatedElementUtils.doProcess(AnnotatedElementUtils.java:192)
	at org.springframework.core.annotation.AnnotatedElementUtils.process(AnnotatedElementUtils.java:162)
	... 33 more
```

Using `org.springframework.boot:spring-boot-starter-redis` naturally takes this error away.

I was a bit surprised that `@ConditionalOnClass` is throwing error if one of its classes are not on a classpath(in this case Jedis.class):

```
@Configuration
@ConditionalOnClass({ JedisConnection.class, RedisOperations.class, Jedis.class })
@EnableConfigurationProperties
public class RedisAutoConfiguration {
```

I've always thought that `@ConditionalOnClass` is actually safe even if classes are missing from a classpath.

**Comment by wilkinsona** [comment]
It works (there's no exception and RedisAutoConfiguration is switched off) for me without Jedis on the classpath. From the auto-configuration report produced by running with `--debug`:

    RedisAutoConfiguration
          - required @ConditionalOnClass classes not found: redis.clients.jedis.Jedis (OnClassCondition)

@jvalkeal Can you provide some more info about your dependencies when it blows up please?

**Comment by jvalkeal** [comment]
Right ok, lemmy try to isolate this in a simpler example. I now kinda remember @dsyer mentioning that you may get
```
Caused by: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
```
which is masking the real error. I kinda then assumed that it must be jedis because adding
```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-redis</artifactId>
</dependency>
```
made error go away. Naturally by a quick look(I checked what got pulled in to a project classpath) a assumed that it was a jedis missing from a classpath. So there must be something else. Thanks for looking this.

**Comment by jvalkeal** [comment]
This is a simplified example showing same issue. Below boot cli app throws errors but adding spring-boot-starter-redis back to deps makes it work.

```
@Grab('org.springframework.integration:spring-integration-redis:4.1.0.RELEASE')
@Grab('org.springframework.boot:spring-boot-starter:1.2.1.RELEASE')
//@Grab('org.springframework.boot:spring-boot-starter-redis:1.2.1.RELEASE')

import org.springframework.boot.autoconfigure.redis.RedisAutoConfiguration
import org.springframework.boot.test.EnvironmentTestUtils
import org.springframework.context.annotation.AnnotationConfigApplicationContext

public class App implements CommandLineRunner {

  void run(String... args) {
    AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext();
    EnvironmentTestUtils.addEnvironment(context);
    context.register(RedisAutoConfiguration.class);
    context.refresh();
  }

}
```

**Comment by wilkinsona** [comment]
Thanks (that's a weird CLI app, but it does illustrate the failure).

It's failing because `StandardAnnotationMetadata` is used when a class is explicitly registered with the application context. It uses standard Java reflection to look at the class's annotations which falls in a heap when it encounters an annotation the references a class that isn't on the classpath. When it's an auto-configuration class that's being used conventionally, i.e. the class hasn't been explicitly registered with the context, it's the ASM-based `AnnotationMetadataReadingVisitor` `AnnotationMetadata` implementation that's used. The ASM-based implementation has no problem with annotations the reference classes that are not on the classpath.

I think we either need to find another way the achieve your goal, or you need to ask for an enhancement to Spring Framework to use `AnnotationMetadataReadingVisitor` across the board.

**Comment by jvalkeal** [comment]
That's for the explanation Andy. I think this is not an issue to me because this was something I did in unit tests and thus would not happen in real boot app. I just didn't realize the real cause.
