### ISSUE TITLE
Multiple DB/Transaction Manager and No Unique bean exception upgrading to spring 1.2.1

### ISSUE THREAD

**Issue by leninayya** [spring-projects/spring-boot#2409]
Spring boot 1.1.9 worked fine with Multiple db/JPA EM and TxMgrs, but ended up NoUniqueBeanDefinitionException in spring boot 1.2.1.

org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [org.springframework.transaction.PlatformTransactionManager] is defined: expected single matching bean but found 4: aTransaction,bTransaction,transactionManager,cTransaction
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:365)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:331)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.determineTransactionManager(TransactionAspectSupport.java:370)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:271)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodIntercceptor.invoke(CrudMethodMetadataPostProcessor.java:122)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy123.save(Unknown Source)

**Comment by snicoll** [comment]
This isn't related to Spring Boot at all but to the upgrade to Spring Framework 4.1.4 that introduced a regression. It's already fixed for the upcoming release that Boot 1.2.2 will integrate.

Could you please flag your "main" transaction manager as `@Primary` as explained [on the related issue](https://jira.spring.io/browse/SPR-12541?focusedCommentId=111032&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-111032)? 

Please reopen if that does not fix your issue.

**Comment by wilkinsona** [comment]
See #2413 for Boot upgrading to Spring Framework 4.1.5
