### ISSUE TITLE
2.4.0: Instantiating a FullTextEntityManager fails

### ISSUE THREAD

**Issue by knoobie** [spring-projects/spring-boot#24144]
After upgrading from 2.3.5.RELEASE to 2.4.0 instantiating a `FullTextEntityManager` (hibernate search) from an injected `EntityManager` is not possible anymore. The same code worked in the past and is derived from the [official documentation](https://docs.jboss.org/hibernate/stable/search/reference/en-US/html_single/#_indexing) or [baeldung](https://www.baeldung.com/hibernate-search#building-the-lucene-index).

Code to reproduce:
https://github.com/knoobie/spring-2-4-entitymanager

How to check: 
- run the test; test fails on service#load
- you can verify that it worked, if you just change the version to 2.3.5.RELEASE again and start the test (it doesn't fail)

Stacktrace:

```log
java.lang.ClassCastException: com.sun.proxy.$Proxy98 cannot be cast to org.hibernate.engine.spi.SessionImplementor

	at org.hibernate.search.impl.FullTextSessionImpl.<init>(FullTextSessionImpl.java:62)
	at org.hibernate.search.impl.ImplementationFactory.createFullTextSession(ImplementationFactory.java:35)
	at org.hibernate.search.Search.getFullTextSession(Search.java:45)
	at org.hibernate.search.jpa.Search.getFullTextEntityManager(Search.java:49)
	at com.example.demo.search.MyService.load(MyService.java:51)
	at com.example.demo.search.MyService$$FastClassBySpringCGLIB$$195495fd.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:371)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:134)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at com.example.demo.search.MyService$$EnhancerBySpringCGLIB$$9e31f121.load(<generated>)
	at com.example.demo.DemoApplicationTests.contextLoads(DemoApplicationTests.java:20)
```

**Comment by wilkinsona** [comment]
Thanks for the sample. I believe this change in behaviour is due to [this change](https://github.com/spring-projects/spring-framework/commit/ba65cef52bbb28e8286faf6d36b5a7ed2b253fa5#diff-afeebda7df0b9f0e8a817b54dc877e9170bcf8af7bdc36c89974ca2b798ebd2aR86) in Spring Framework 5.3.

The `entityManagerInterface` has changed from `org.hibernate.jpa.HibernateEntityManager` to `org.hibernate.Session`. This has a knock-on effect when Hibernate Search attempts to unwrap the `EntityManager` as a `Session`:

```
private static Session getSession(EntityManager em) {
    try {
        return em.unwrap( Session.class );
    }
    catch (PersistenceException e) {
        throw new SearchException(
                "Trying to use Hibernate Search with a non-Hibernate EntityManager", e
        );
    }
}
```

The `EntityManager` (a Spring Framework created proxy) now implements `Session` so the proxy is returned as-is. The proxy does not implement `SessionImplementor` so the subsequent cast fails. In Spring Framework 5.2 the proxy wasn't an instance of `Session` so a different code path was taken.

We'll transfer this to the Spring Framework team so that they can take a look.
