### ISSUE TITLE
Caused by: java.lang.IllegalStateException: Error processing condition on org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration$RedisConfiguration.stringRedisTemplate

### ISSUE THREAD

**Issue by dsgoers** [spring-projects/spring-boot#24206]
Hi.  I'm using Spring Boot 1.5.22.RELEASE and Apache CXF 3.3.8.  I'm not sure if this is a Spring or CXF issue, but when I upgraded from CXF 3.1.12 to 3.3.8, I get this error:

```
18-Nov-2020 15:04:24.343 SEVERE [localhost-startStop-17] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start: 
	org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[<omitted>.]
		at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:970)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1841)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
	Caused by: java.lang.IllegalStateException: Error processing condition on org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration$RedisConfiguration.stringRedisTemplate
		at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:60)
		at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:102)
		at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:179)
		at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:140)
		at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:116)
		at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:320)
		at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:228)
		at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:272)
		at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:92)
		at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687)
		at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:524)
		at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:123)
		at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:666)
		at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:353)
		at org.springframework.boot.SpringApplication.run(SpringApplication.java:300)
		at org.springframework.boot.web.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:151)
		at org.springframework.boot.web.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:131)
		at org.springframework.boot.web.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:91)
		at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:169)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5154)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		... 10 more
	Caused by: java.lang.reflect.MalformedParameterizedTypeException
		at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.validateConstructorArguments(ParameterizedTypeImpl.java:58)
		at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.<init>(ParameterizedTypeImpl.java:51)
		at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.make(ParameterizedTypeImpl.java:92)
		at sun.reflect.generics.factory.CoreReflectionFactory.makeParameterizedType(CoreReflectionFactory.java:105)
		at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:140)
		at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
		at sun.reflect.generics.repository.MethodRepository.getReturnType(MethodRepository.java:68)
		at java.lang.reflect.Method.getGenericReturnType(Method.java:255)
		at org.springframework.core.MethodParameter.getGenericParameterType(MethodParameter.java:397)
		at org.springframework.core.SerializableTypeWrapper$MethodParameterTypeProvider.getType(SerializableTypeWrapper.java:338)
		at org.springframework.core.SerializableTypeWrapper.forTypeProvider(SerializableTypeWrapper.java:146)
		at org.springframework.core.ResolvableType.forType(ResolvableType.java:1346)
		at org.springframework.core.ResolvableType.forMethodParameter(ResolvableType.java:1249)
		at org.springframework.core.ResolvableType.forMethodParameter(ResolvableType.java:1217)
		at org.springframework.core.ResolvableType.forMethodReturnType(ResolvableType.java:1160)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:759)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:638)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:607)
		at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1496)
		at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1018)
		at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.addBeanTypeForNonAliasDefinition(BeanTypeRegistry.java:217)
		at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.addBeanTypeForNonAliasDefinition(BeanTypeRegistry.java:195)
		at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.addBeanType(BeanTypeRegistry.java:188)
		at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.updateTypesIfNecessary(BeanTypeRegistry.java:175)
		at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.getNamesForType(BeanTypeRegistry.java:112)
		at org.springframework.boot.autoconfigure.condition.OnBeanCondition.collectBeanNamesForType(OnBeanCondition.java:171)
		at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanNamesForType(OnBeanCondition.java:158)
		at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchingBeans(OnBeanCondition.java:128)
		at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:103)
		at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47)
		... 30 more
1
```

**Comment by philwebb** [comment]
I'm afraid it's hard to say what could cause this error without more details. Can you share a small project that reproduces the problem?

**Comment by dsgoers** [comment]
Unfortunately all our code is proprietary so I can't share any of it.  Is there something else I could check or try?

**Comment by philwebb** [comment]
It doesn't have to be your exact code, just any small project that can replicate the image. Other things to check are that the JDK versions match (has CXF raised the minimum requirements) and are all JAR files consistent (check that you're not mixing different Boot jar versions.

You can also try adding an exception breakpoint on `MalformedParameterizedTypeException` and walking up the stack to `MethodParameter.getGenericParameterType` to see what method parameter is actually failing.

**Comment by spencergibb** [comment]
>  I'm using Spring Boot 1.5.22.RELEASE

**Comment by philwebb** [comment]
Thanks @spencergibb, I missed that. @dsgoers You should upgrade to a later version of Spring Boot as 1.5.x is no longer supported.

**Comment by dsgoers** [comment]
Thanks.  I'll upgrade my Spring Boot version ASAP.  In terms of the original issue, the method in question is `CxfAutoConfiguration.cxfServletRegistration`, so looks like it's a CXF issue rather than a Spring one.

**Comment by dsgoers** [comment]
I created an issue on the CXF page: https://issues.apache.org/jira/browse/CXF-8374

**Comment by philwebb** [comment]
I don't think this is a CFX issue either, I rather suspect it's a version mismatch. The `CxfAutoConfiguration.cxfServletRegistration` method returns a `ServletRegistrationBean<CXFServlet>`. In Spring Boot 1.5, `ServletRegistrationBean` didn't have a generic type, in 2.x it does.

I suspect that if you upgrade your application to the latest Spring Boot version then you'll find the exception isn't thrown.
