### ISSUE TITLE
I got mention execption while executing hibernate project . Please help 

### ISSUE THREAD

**Issue by roshanpal333** [spring-projects/spring-boot#24476]
Dec 12, 2020 12:17:06 AM org.hibernate.Version logVersion
INFO: HHH000412: Hibernate ORM core version [WORKING]
Exception in thread "main" java.lang.NoClassDefFoundError: net/bytebuddy/NamingStrategy$SuffixingRandom$BaseNameResolver
	at org.hibernate.orm.core@5.4.25.Final/org.hibernate.cfg.Environment.buildBytecodeProvider(Environment.java:345)
	at org.hibernate.orm.core@5.4.25.Final/org.hibernate.cfg.Environment.buildBytecodeProvider(Environment.java:337)
	at org.hibernate.orm.core@5.4.25.Final/org.hibernate.cfg.Environment.<clinit>(Environment.java:230)
	at org.hibernate.orm.core@5.4.25.Final/org.hibernate.boot.registry.StandardServiceRegistryBuilder.<init>(StandardServiceRegistryBuilder.java:161)
	at org.hibernate.orm.core@5.4.25.Final/org.hibernate.boot.registry.StandardServiceRegistryBuilder.<init>(StandardServiceRegistryBuilder.java:96)
	at org.hibernate.orm.core@5.4.25.Final/org.hibernate.cfg.Configuration.reset(Configuration.java:158)
	at org.hibernate.orm.core@5.4.25.Final/org.hibernate.cfg.Configuration.<init>(Configuration.java:124)
	at org.hibernate.orm.core@5.4.25.Final/org.hibernate.cfg.Configuration.<init>(Configuration.java:118)
	at javatutoroom.com.hibernate.App.main(App.java:15)
Caused by: java.lang.ClassNotFoundException: net.bytebuddy.NamingStrategy$SuffixingRandom$BaseNameResolver
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 9 more

**Comment by scottfrederick** [comment]
@roshanpal333 You need to add a dependency to Byte Buddy to your project build file, as shown on [its project page](https://bytebuddy.net/). You can omit the version from your build file, as Spring Boot will manage a version that is compatible. 

If you have further questions, please follow-up on StackOverfow. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
