### ISSUE TITLE
Gradle plugin: Changes to incubating dependency management APIs

### ISSUE THREAD

**Issue by uklance** [spring-projects/spring-boot#2482]
This is just a heads-up that he gradle plugin will need to be tweaked for gradle 2.4 to avoid the following exception:

```
Caused by: java.lang.NoSuchMethodError: org.gradle.api.artifacts.DependencyResolveDetails.getTarget()Lorg/gradle/api/artifacts/ModuleVersionSelector;
    at org.springframework.boot.gradle.resolve.SpringBootResolutionStrategy$VersionResolver.execute(SpringBootResolutionStrategy.java:57)
    at org.springframework.boot.gradle.resolve.SpringBootResolutionStrategy$VersionResolver.execute(SpringBootResolutionStrategy.java:1)
    at org.gradle.internal.Actions$CompositeAction.execute(Actions.java:75)
    at org.gradle.api.internal.artifacts.ivyservice.DependencySubstitutionResolver.resolve(DependencySubstitutionResolver.java:40)
    ... 70 more
```
Full details [here](http://forums.gradle.org/gradle/topics/fails-to-create-grails-war-on-openshift)

**Comment by wilkinsona** [comment]
Thanks for the warning. The use of deprecated on some methods on `DependencyResolveDetails` while others are removed entirely is a bit baffling. The dangers of using an incubating API, I suppose.

**Comment by wilkinsona** [comment]
The change in Gradle was [reverted](https://github.com/gradle/gradle/commit/c70ac9b84b7db43ebebc360c1013613f49ad7b1e) so there's nothing for us to do here.
