### ISSUE TITLE
java.lang.IllegalStateException: Failed to introspect annotations on spring-cloud-samples/zuul-server

### ISSUE THREAD

**Issue by chornyi** [spring-projects/spring-boot#2551]
To reproduce:

1. Checkout https://github.com/spring-cloud-samples/zuul-server
2. Replace @EnableZuulProxy with @EnableZuulServer in ZuulServerApplication.java.
3. Package the application using `mvn package` 
4. Execute using `java -jar .\zuul-server-1.0.0.BUILD-SNAPSHOT.jar`

         java.lang.IllegalStateException: Failed to introspect annotations: class zuulserver.ZuulServerApplication
			at org.springframework.core.annotation.AnnotatedElementUtils.process(AnnotatedElementUtils.java:166)
			at org.springframework.core.annotation.AnnotatedElementUtils.isAnnotated(AnnotatedElementUtils.java:73)
			at org.springframework.core.type.StandardAnnotationMetadata.isAnnotated(StandardAnnotationMetadata.java:102)
			at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:74)
			at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:64)
			at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.registerBean(AnnotatedBeanDefinitionReader.java:140)
			at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.registerBean(AnnotatedBeanDefinitionReader.java:127)
			at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.register(AnnotatedBeanDefinitionReader.java:122)
			at org.springframework.boot.BeanDefinitionLoader.load(BeanDefinitionLoader.java:159)
			at org.springframework.boot.BeanDefinitionLoader.load(BeanDefinitionLoader.java:135)
			at org.springframework.boot.BeanDefinitionLoader.load(BeanDefinitionLoader.java:127)
			at org.springframework.boot.SpringApplication.load(SpringApplication.java:620)
			at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
			at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139)
			at zuulserver.ZuulServerApplication.main(ZuulServerApplication.java:21)
			at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
			at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
			at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
			at java.lang.reflect.Method.invoke(Unknown Source)
			at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
			at java.lang.Thread.run(Unknown Source)
			Caused by: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
			at sun.reflect.annotation.AnnotationParser.parseClassArray(Unknown Source)
			at sun.reflect.annotation.AnnotationParser.parseArray(Unknown Source)
			at sun.reflect.annotation.AnnotationParser.parseMemberValue(Unknown Source)
			at sun.reflect.annotation.AnnotationParser.parseAnnotation2(Unknown Source)
			at sun.reflect.annotation.AnnotationParser.parseAnnotations2(Unknown Source)
			at sun.reflect.annotation.AnnotationParser.parseAnnotations(Unknown Source)
			at java.lang.Class.createAnnotationData(Unknown Source)
			at java.lang.Class.annotationData(Unknown Source)
			at java.lang.Class.getAnnotations(Unknown Source)
			at org.springframework.core.annotation.AnnotatedElementUtils.doProcess(AnnotatedElementUtils.java:192)
			at org.springframework.core.annotation.AnnotatedElementUtils.doProcess(AnnotatedElementUtils.java:209)
			at org.springframework.core.annotation.AnnotatedElementUtils.process(AnnotatedElementUtils.java:162)
			... 20 common frames omitted
			java.lang.reflect.InvocationTargetException
			at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
			at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
			at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
			at java.lang.reflect.Method.invoke(Unknown Source)
			at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
			at java.lang.Thread.run(Unknown Source)
			Caused by: java.lang.IllegalStateException: Failed to introspect annotations: class zuulserver.ZuulServerApplication
			at org.springframework.core.annotation.AnnotatedElementUtils.process(AnnotatedElementUtils.java:166)
			at org.springframework.core.annotation.AnnotatedElementUtils.isAnnotated(AnnotatedElementUtils.java:73)
			at org.springframework.core.type.StandardAnnotationMetadata.isAnnotated(StandardAnnotationMetadata.java:102)
			at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:74)
			at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:64)
			at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.registerBean(AnnotatedBeanDefinitionReader.java:140)
			at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.registerBean(AnnotatedBeanDefinitionReader.java:127)
			at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.register(AnnotatedBeanDefinitionReader.j:122)
			at org.springframework.boot.BeanDefinitionLoader.load(BeanDefinitionLoader.java:159)
			at org.springframework.boot.BeanDefinitionLoader.load(BeanDefinitionLoader.java:135)
			at org.springframework.boot.BeanDefinitionLoader.load(BeanDefinitionLoader.java:127)
			at org.springframework.boot.SpringApplication.load(SpringApplication.java:620)
			at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
			at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139)
			at zuulserver.ZuulServerApplication.main(ZuulServerApplication.java:21)
			... 6 more
			Caused by: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
			at sun.reflect.annotation.AnnotationParser.parseClassArray(Unknown Source)
			at sun.reflect.annotation.AnnotationParser.parseArray(Unknown Source)
			at sun.reflect.annotation.AnnotationParser.parseMemberValue(Unknown Source)
			at sun.reflect.annotation.AnnotationParser.parseAnnotation2(Unknown Source)
			at sun.reflect.annotation.AnnotationParser.parseAnnotations2(Unknown Source)
			at sun.reflect.annotation.AnnotationParser.parseAnnotations(Unknown Source)
			at java.lang.Class.createAnnotationData(Unknown Source)
			at java.lang.Class.annotationData(Unknown Source)
			at java.lang.Class.getAnnotations(Unknown Source)
			at org.springframework.core.annotation.AnnotatedElementUtils.doProcess(AnnotatedElementUtils.java:192)
			at org.springframework.core.annotation.AnnotatedElementUtils.doProcess(AnnotatedElementUtils.java:209)
			at org.springframework.core.annotation.AnnotatedElementUtils.process(AnnotatedElementUtils.java:162)
			... 20 more

**Comment by snicoll** [comment]
I guess you meant to report that against the `spring-cloud` project, right? See https://github.com/spring-cloud-samples/zuul-server/issues
