### ISSUE TITLE
unable to run Tests with release 1.2.2

### ISSUE THREAD

**Issue by BigMichi1** [spring-projects/spring-boot#2572]
after i updated to version 1.2.2 my tests are no longer running all fail with this exception

```
java.lang.IllegalAccessError: tried to access class org.springframework.test.context.support.TestPropertySourceUtils from class org.springframework.boot.test.SpringApplicationContextLoader$PropertySourceLocationsInitializer
	at org.springframework.boot.test.SpringApplicationContextLoader$PropertySourceLocationsInitializer.initialize(SpringApplicationContextLoader.java:290)
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:567)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.test.SpringApplicationContextLoader.loadContext(SpringApplicationContextLoader.java:100)
	at org.springframework.test.context.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:68)
	at org.springframework.test.context.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:86)
	at org.springframework.test.context.DefaultTestContext.getApplicationContext(DefaultTestContext.java:72)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:117)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:212)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:200)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:252)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:254)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:217)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:83)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:68)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:163)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

**Comment by wilkinsona** [comment]
1.2.2 requires Spring Framework 4.1.5

**Comment by davicdsalves** [comment]
Does that mean that I need to manually insert the property of spring version? Shouldn't _spring-boot-dependencies_ bring it?

**Comment by snicoll** [comment]
of course it will. Your project is probably forcing it in some form.

Please have a look to [the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-build-systems)

**Comment by davicdsalves** [comment]
I have read the documentation.
Also I'm not forcing it in any way.

**Comment by snicoll** [comment]
alright, show your project config then.

**Comment by davicdsalves** [comment]
I fixed it thanks for your time.

**Comment by claytantor** [comment]
Hey @davicdsalves it really helps when you explain how you fixed it.

**Comment by alvarogarcia7** [comment]
@claytantor agree

I've solved it upgrading to 4.1.5.RELEASE. Important to do ``mvn clean package``, otherwise your old dependencies are still there.

**Comment by franziskas** [comment]
@claytantor I fixed it by removing our own dependency definition (and version number!) for mockito from the pom and running `mvn clean`. I guess we have to accept Spring choosing the Mockito version for us. Found the solution here: http://stackoverflow.com/a/41041477

**Comment by AlthafAzeez** [comment]
I fixed this by removing the mockito library dependency from my project
