### ISSUE TITLE
MetricsFilter throws NPE when removing non-existant guage

### ISSUE THREAD

**Issue by checketts** [spring-projects/spring-boot#2590]
In one environment, we ran into a sporatic `NullPointerException`s. They didn't have a stacktrace so when re-running the server with `-XX:-OmitStackTraceInFastThrow` so the stack trace would not get thrown out by the JVM we saw several of the following:

```
java.lang.NullPointerException
	at org.springframework.boot.actuate.metrics.reader.MetricRegistryMetricReader.remove(MetricRegistryMetricReader.java:188)
	at org.springframework.boot.actuate.metrics.reader.MetricRegistryMetricReader.onGaugeRemoved(MetricRegistryMetricReader.java:121)
	at com.codahale.metrics.MetricRegistry.notifyListenerOfRemovedMetric(MetricRegistry.java:366)
	at com.codahale.metrics.MetricRegistry.onMetricRemoved(MetricRegistry.java:360)
	at com.codahale.metrics.MetricRegistry.remove(MetricRegistry.java:156)
	at org.springframework.boot.actuate.metrics.writer.CodahaleMetricWriter.set(CodahaleMetricWriter.java:97)
	at org.springframework.boot.actuate.metrics.writer.CompositeMetricWriter.set(CompositeMetricWriter.java:54)
	at org.springframework.boot.actuate.metrics.writer.DefaultGaugeService.submit(DefaultGaugeService.java:41)
	at org.springframework.boot.actuate.autoconfigure.MetricFilterAutoConfiguration$MetricsFilter.doFilterInternal(MetricFilterAutoConfiguration.java:111)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:175)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:620)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:540)
	at java.lang.Thread.run(Thread.java:745)
```

My service is wiring up its own `MetricsRegistry` (from CodaHaleMetrics), so it could be possible that that there were 2 registries? Unlikely due to `@ConditionalOnMissingBean`, but worth mentioning.

**Comment by wilkinsona** [comment]
There's a visibility problem with the fields in `MetricRegistryMetricReader`. They need to be final (or volatile) to guarantee that their values are consistently visible across different threads.

**Comment by wilkinsona** [comment]
cc @graemerocher

**Comment by graemerocher** [comment]
yeah this is the same error I got, same exact trace

**Comment by wilkinsona** [comment]
There are a number of other ways in which `MetricRegistryMetricReader` is not thread-safe and, as it implements `MetricRegistryListener` it really needs to be.
