### ISSUE TITLE
MetricRegistryMetricReader.findOne throws ClassCastException for Gauge<Set<String>>

### ISSUE THREAD

**Issue by paskos** [spring-projects/spring-boot#2593]
```java
if (metric instanceof Gauge) {
			@SuppressWarnings("unchecked")
			Gauge<Number> value = (Gauge<Number>) metric;
			return new Metric<Number>(metricName, value.getValue());
}
```
`metricRegistry.register( PROP_METRIC_REG_JVM_THREADS , new ThreadStatesGaugeSet() );`

```
Caused by: java.lang.ClassCastException: java.util.Collections$EmptySet cannot be cast to java.lang.Number
	at org.springframework.boot.actuate.metrics.reader.MetricRegistryMetricReader.findOne(MetricRegistryMetricReader.java:82)
	at org.springframework.boot.actuate.metrics.reader.MetricRegistryMetricReader$MetricRegistryIterator.next(MetricRegistryMetricReader.java:211)
	at org.springframework.boot.actuate.metrics.reader.MetricRegistryMetricReader$MetricRegistryIterator.next(MetricRegistryMetricReader.java:194)
	at org.springframework.boot.actuate.endpoint.MetricReaderPublicMetrics.metrics(MetricReaderPublicMetrics.java:47)
	at org.springframework.boot.actuate.endpoint.MetricsEndpoint.invoke(MetricsEndpoint.java:65)
	at org.springframework.boot.actuate.endpoint.MetricsEndpoint.invoke(MetricsEndpoint.java:36)
	at org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke(EndpointMvcAdapter.java:56)

```

**Comment by mstine** [comment]
Here's an app that duplicates this: https://github.com/mstine/statsd-graphite-demo

**Comment by snicoll** [comment]
Thanks for the app Matt, very helpful.

**Comment by wilkinsona** [comment]
The `deadlocks` `Gauge` produces `Set<String>`:

```java
gauges.put("deadlocks", new Gauge<Set<String>>() {
    @Override
    public Set<String> getValue() {
        return deadlockDetector.getDeadlockedThreads();
    }
});
```
 but we assume that all `Gauge` instances will be `Gauge<Number>:

```java
if (metric instanceof Gauge) {
    @SuppressWarnings("unchecked")
    Gauge<Number> value = (Gauge<Number>) metric;
    return new Metric<Number>(metricName, value.getValue());
}
```
