### ISSUE TITLE
Actuator: ClassCastException for non-numeric gauge values

### ISSUE THREAD

**Issue by dacrome** [spring-projects/spring-boot#2627]
[Dropwizard Metrics Gauges] (https://dropwizard.github.io/metrics/3.1.0/getting-started/#gauges) are not only accepting numeric values. [Spring Boot] (https://github.com/spring-projects/spring-boot/blob/master/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/metrics/Metric.java#L32) should also support other types than numbers. I think it's enough to support String, Boolean, Number and Integer.

I realized this when I registered the [HystrixCodaHaleMetricsPublisher] (https://github.com/Netflix/Hystrix/blob/master/hystrix-contrib/hystrix-codahale-metrics-publisher/src/main/java/com/netflix/hystrix/contrib/codahalemetricspublisher/HystrixCodaHaleMetricsPublisher.java) and called the /metrics endpoint:
```
Caused by: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Number
	at org.springframework.boot.actuate.metrics.reader.MetricRegistryMetricReader.findOne(MetricRegistryMetricReader.java:82)
	at org.springframework.boot.actuate.metrics.reader.MetricRegistryMetricReader$MetricRegistryIterator.next(MetricRegistryMetricReader.java:211)
	at org.springframework.boot.actuate.metrics.reader.MetricRegistryMetricReader$MetricRegistryIterator.next(MetricRegistryMetricReader.java:194)
	at org.springframework.boot.actuate.endpoint.MetricReaderPublicMetrics.metrics(MetricReaderPublicMetrics.java:47)
	at org.springframework.boot.actuate.endpoint.MetricsEndpoint.invoke(MetricsEndpoint.java:65)
	at org.springframework.boot.actuate.endpoint.MetricsEndpoint.invoke(MetricsEndpoint.java:36)
	at org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke(EndpointMvcAdapter.java:56)
```

**Comment by snicoll** [comment]
We had that discussion already, see #2593

**Comment by dacrome** [comment]
I'm sorry, I've probably searched only in the open ones.

**Comment by snicoll** [comment]
hey, no worries!

**Comment by philwebb** [comment]
#2593 was recently fixed in commit 743482a BTW.

**Comment by dacrome** [comment]
Thanks for the feedback. But why ignoring the non-numeric values when metrics allows not only numeric values? hystrix makes use of this and provides [properties](https://github.com/Netflix/Hystrix/wiki/Metrics-and-Monitoring#property-values-informational) with Boolean, String and Number. The above mentioned commit is just a fix to prevent the ClassCastException. My intention in the first place to open this issue is to support also non-numeric values. Is there a reason to support only numeric values?

**Comment by tkrille** [comment]
+1

I really need non-numeric values working, too.

**Comment by wilkinsona** [comment]
If you'd like to see support for non-numeric values, #2682 is the place to make your voice heard.
