### ISSUE TITLE
@EnableConfigurationProperties throws NoUniqueBeanDefinitionException

### ISSUE THREAD

**Issue by sddakoty** [spring-projects/spring-boot#2639]
When using ```@EnableConfigurationProperties(MyProperties.class)```, it is expected that this class is only wired once. When I want to inject this class, this should work out of the box.

BUT: currently ```EnableConfigurationPropertiesImportSelector``` will inject a bean in addition named `<prefix>.CONFIGURATION_PROPERTIES`.

```
NoUniqueBeanDefinitionException: No qualifying bean of type [MyProperties] is defined: expected single matching bean but found 2: myProperties,my.CONFIGURATION_PROPERTIES
```

Reproduced as follows, using ```spring-boot-1.2.2.RELEASE```:

```
@EnableAutoConfiguration
@ComponentScan
@EnableConfigurationProperties(MyProperties.class)
public class AppConfig {
	public static void main(String args[]) {
	    SpringApplication.run(AppConfig.class, args);
	}
}

@Component
@ConfigurationProperties(prefix = "my")
public class MyProperties {
    private String name;

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
}

@Service
public class MyService {
    @Autowired
//    @Qualifier("myProperties") //enabling this explicit would make it work again
    private MyProperties props;

    @PostConstruct
    public void run() {
        System.out.println(props.getName());
    }
}

application.properties:
my.name=test
```

Result:
```
2015-03-12 11:12:53.434  WARN 5108 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'myService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private de.spring.test.MyProperties de.spring.test.MyService.props; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [de.spring.test.MyProperties] is defined: expected single matching bean but found 2: myProperties,my.CONFIGURATION_PROPERTIES
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1202)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
	at de.spring.test.AppConfig.main(AppConfig.java:13)
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private de.spring.test.MyProperties de.spring.test.MyService.props; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [de.spring.test.MyProperties] is defined: expected single matching bean but found 2: myProperties,my.CONFIGURATION_PROPERTIES
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:561)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 15 common frames omitted
Caused by: org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [de.spring.test.MyProperties] is defined: expected single matching bean but found 2: myProperties,my.CONFIGURATION_PROPERTIES
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1054)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:942)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:533)
	... 17 common frames omitted
```

**Comment by snicoll** [comment]
Duplicates #2204

**Comment by philwebb** [comment]
See https://github.com/spring-projects/spring-boot/issues/2204#issuecomment-78463138 for a description of why you're getting the exception.
