### ISSUE TITLE
Profile-specific resolution should still happen when processing 'spring.config.import' properties

### ISSUE THREAD

**Issue by pshakhov** [spring-projects/spring-boot#26960]
Hi all! We are up the spring-boot version from 2.4.2 to 2.5.1 and catch problem when run app:

```java
13:03:51.052 [main] DEBUG org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter - Application failed to start due to an exception
org.springframework.boot.context.config.ConfigDataLocationNotFoundException: Config data location 'consul:' cannot be found
    at org.springframework.boot.context.config.ConfigDataEnvironment.checkMandatoryLocations(ConfigDataEnvironment.java:383)
    at org.springframework.boot.context.config.ConfigDataEnvironment.applyToEnvironment(ConfigDataEnvironment.java:326)
    at org.springframework.boot.context.config.ConfigDataEnvironment.processAndApply(ConfigDataEnvironment.java:233)
    at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:102)
    at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:94)
    at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:100)
    at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:86)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
    at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:82)
    at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:63)
    at java.util.ArrayList.forEach(ArrayList.java:1259)
    at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117)
    at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111)
    at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:62)
    at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:374)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:332)
    at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:144)
    at ru.tinkoff.bpm.flexconsumer.FlexConsumerApplicationKt.main(FlexConsumerApplication.kt:19)
```
The problem sounds like this: In the loader class ConfigDataLocationResolvers a check has been added-whether to load the settings, if they relate to a specific profile. (on the first screen)
![image](https://user-images.githubusercontent.com/32340504/122569636-9d02c700-d053-11eb-8eb6-f980d3d8c928.png)
But in the implementation of loading settings from the consul, there is such an implementation(the ConsulConfigDataLocationResolver class) that settings that do not relate to some profile are not loaded at all
![image](https://user-images.githubusercontent.com/32340504/122569670-a724c580-d053-11eb-95cd-d982666c3991.png)

How "force" configuration loading?

application-production.yml
```yaml
spring:
  config:
    import:
      - 'consul:'
      - 'vault://'
```
On spring-boot 2.4.2 and 2.4.5 its works as expected with exact configurations, from 2.4.6 and higher we are getting troubled.

**Comment by philwebb** [comment]
I think this might be due to #26753.

**Comment by philwebb** [comment]
It's quite similar to #26753 so I think we should probably restore the old behavior and add some tests.

**Comment by UbaidurRehman1** [comment]
@philwebb 
2.5.2 will contains the old behavior `profile-specific resolution`. Am I right?
