### ISSUE TITLE
Problems using the /metrics endpoint of Spring Boot Actuator on Google App Engine

### ISSUE THREAD

**Issue by chrisbianca** [spring-projects/spring-boot#2701]
Hi,

I'm aware that support for Google App Engine is not perfect, but I'm still keen to try and make use of the framework as it provides so many pluses.  For the most part, everything has been working fine, but I've just tried to enable the actuator project and am having some problems with the /metrics endpoint.  It works locally but it does not work when deploying it to Google App Engine.  The exception is as follows:

```
java.lang.NoClassDefFoundError: Could not initialize class com.google.apphosting.runtime.security.shared.stub.java.lang.management.ManagementFactory
	at org.springframework.boot.actuate.endpoint.SystemPublicMetrics.addBasicMetrics(SystemPublicMetrics.java:74)
	at org.springframework.boot.actuate.endpoint.SystemPublicMetrics.metrics(SystemPublicMetrics.java:57)
	at org.springframework.boot.actuate.endpoint.MetricsEndpoint.invoke(MetricsEndpoint.java:65)
	at org.springframework.boot.actuate.endpoint.MetricsEndpoint.invoke(MetricsEndpoint.java:36)
	at org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke(EndpointMvcAdapter.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:45)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:777)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:706)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:943)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:877)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:220)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441)
	at java.lang.Thread.run(Thread.java:745)
```

The cause of this is that ManagementFactory is one of Google App Engine's restricted classes so can't be referenced.  I've had a quick look through the actuator code, but can't see an easy way of disabling this particular metric.

Does anybody have any suggestions for how to work around this problem?  Or am I going to be unable to make use of the metrics functionality on Google App Engine?

Thanks,
Chris

**Comment by snicoll** [comment]
Interesting. 

In the mean-time you can create your own `MetricsEndpoint` bean on the basis of [the one we auto-configure](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/autoconfigure/EndpointAutoConfiguration.java#L128) (obviously removing `SystemPublicMetrics` from the list). 

That being said, I am not sure what we should do. Maybe rationalize the use of JMX consistently so that if we disable it via configuration, all usages should back off?

**Comment by chrisbianca** [comment]
Ok thanks.  I'll take a look.

It does seem sensible that all references to JMX should be enabled/disabled via the configuration.  I've already had to disable JMX to allow the application to start correctly on GAE so was quite surprised when I encountered issues down the line.

**Comment by snicoll** [comment]
I agree.

**Comment by chrisbianca** [comment]
For reference, adding the following to my configuration worked:

```
	@Bean
	@ConditionalOnMissingBean
	public MetricsEndpoint metricsEndpoint() {
		List<PublicMetrics> publicMetrics = new ArrayList<PublicMetrics>();
		if (this.publicMetrics != null) {
			for (PublicMetrics pm : this.publicMetrics) {
				if (!(pm instanceof SystemPublicMetrics)) {
					publicMetrics.add(pm);
				}
			}
		}
		Collections.sort(publicMetrics, AnnotationAwareOrderComparator.INSTANCE);
		return new MetricsEndpoint(publicMetrics);
	}
```

**Comment by snicoll** [comment]
Cool, thanks for letting us know!
