### ISSUE TITLE
Custom ApplicationEventMulticaster makes integration tests fail

### ISSUE THREAD

**Issue by EvgeniGordeev** [spring-projects/spring-boot#2710]
Fails on 1.2.2.RELEASE. When a custom ApplicationEventMulticaster is defined in the application configuration:
```java
    @Bean
    public ApplicationEventMulticaster applicationEventMulticaster() {
        return new TransactionAwareApplicationEventMulticaster();
    }
```
And it's working in usual running mode, all integration tests still fail:
```java
Caused by: java.lang.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: org.springframework.context.annotation.AnnotationConfigApplicationContext@1fb3dab: startup date [Tue Mar 24 23:36:53 CDT 2015]; root of context hierarchy
	at org.springframework.context.support.AbstractApplicationContext.getApplicationEventMulticaster(AbstractApplicationContext.java:344)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:331)
	at org.springframework.boot.autoconfigure.orm.jpa.DataSourceInitializedPublisher.postProcessAfterInitialization(DataSourceInitializedPublisher.java:69)
```

**Comment by philwebb** [comment]
I tried adding a custom `applicationEventMulticaster` `@Bean` to `SampleDataJpaApplication` and I couldn't replicate the problem. Are you able to provide a [sample application](https://github.com/spring-projects/spring-boot-issues) that demonstrates the issue?

**Comment by EvgeniGordeev** [comment]
Cannot reproduce either. Didn't debug to the end and when found a similar error on SO stopped investigating with a thought 'it might be a regression'. Sorry for that.
