### ISSUE TITLE
javaFx 15 jlink and package，then run：Failed to bind properties under 'spring.config' to

### ISSUE THREAD

**Issue by OceanBelongsToMe** [spring-projects/spring-boot#27127]
```
org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'spring.config' to org.springframework.boot.context.config.ConfigDataProperties
	at spring.boot@2.5.2/org.springframework.boot.context.properties.bind.Binder.handleBindError(Unknown Source)
	at spring.boot@2.5.2/org.springframework.boot.context.properties.bind.Binder.bind(Unknown Source)
	at spring.boot@2.5.2/org.springframework.boot.context.properties.bind.Binder.bind(Unknown Source)
	at spring.boot@2.5.2/org.springframework.boot.context.properties.bind.Binder.bind(Unknown Source)
	at spring.boot@2.5.2/org.springframework.boot.context.config.ConfigDataProperties.get(Unknown Source)
	at spring.boot@2.5.2/org.springframework.boot.context.config.ConfigDataEnvironmentContributor.withBoundProperties(Unknown Source)
	at spring.boot@2.5.2/org.springframework.boot.context.config.ConfigDataEnvironmentContributors.withProcessedImports(Unknown Source)
	at spring.boot@2.5.2/org.springframework.boot.context.config.ConfigDataEnvironment.processInitial(Unknown Source)
	at spring.boot@2.5.2/org.springframework.boot.context.config.ConfigDataEnvironment.processAndApply(Unknown Source)
	at spring.boot@2.5.2/org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(Unknown Source)
	at spring.boot@2.5.2/org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(Unknown Source)
	at spring.boot@2.5.2/org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(Unknown Source)
	at spring.boot@2.5.2/org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(Unknown Source)
	at spring.context@5.3.8/org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(Unknown Source)
	at spring.context@5.3.8/org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(Unknown Source)
	at spring.context@5.3.8/org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(Unknown Source)
	at spring.context@5.3.8/org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(Unknown Source)
	at spring.boot@2.5.2/org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(Unknown Source)
	at spring.boot@2.5.2/org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(Unknown Source)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at spring.boot@2.5.2/org.springframework.boot.SpringApplicationRunListeners.doWithListeners(Unknown Source)
	at spring.boot@2.5.2/org.springframework.boot.SpringApplicationRunListeners.doWithListeners(Unknown Source)
	at spring.boot@2.5.2/org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(Unknown Source)
	at spring.boot@2.5.2/org.springframework.boot.SpringApplication.prepareEnvironment(Unknown Source)
	at spring.boot@2.5.2/org.springframework.boot.SpringApplication.run(Unknown Source)
	at spring.boot@2.5.2/org.springframework.boot.SpringApplication.run(Unknown Source)
	at spring.boot@2.5.2/org.springframework.boot.SpringApplication.run(Unknown Source)
	at springboot.javafx.support@2.1.7-SNAPSHOT/de.felixroske.jfxsupport.AbstractJavaFxApplicationSupport.lambda$init$1(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Failed to extract parameter names for org.springframework.boot.context.config.ConfigDataProperties(java.util.List,org.springframework.boot.context.config.ConfigDataProperties$Activate)
	at spring.core@5.3.8/org.springframework.util.Assert.state(Unknown Source)
	at spring.boot@2.5.2/org.springframework.boot.context.properties.bind.ValueObjectBinder$DefaultValueObject.parseConstructorParameters(Unknown Source)
	at spring.boot@2.5.2/org.springframework.boot.context.properties.bind.ValueObjectBinder$DefaultValueObject.<init>(Unknown Source)
	at spring.boot@2.5.2/org.springframework.boot.context.properties.bind.ValueObjectBinder$DefaultValueObject.get(Unknown Source)
	at spring.boot@2.5.2/org.springframework.boot.context.properties.bind.ValueObjectBinder$ValueObject.get(Unknown Source)
	at spring.boot@2.5.2/org.springframework.boot.context.properties.bind.ValueObjectBinder.bind(Unknown Source)
	at spring.boot@2.5.2/org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$5(Unknown Source)
	at spring.boot@2.5.2/org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Unknown Source)
	at spring.boot@2.5.2/org.springframework.boot.context.properties.bind.Binder$Context.withDataObject(Unknown Source)
```

**Comment by wilkinsona** [comment]
The code that's failing is attempting to bind properties to a `ConfigDataProperties` instance using its constructor. This binding uses Spring Framework's `DefaultParameterNameDiscoverer` to discover the names of its constructor parameters and this discovery has failed.  The default discover delegates to reflection- and local variable table-based discovered. Spring Boot's own code is compiled with `-parameters` which should allow the reflection-based discovery to find the parameters.

A stack trace alone isn't sufficient to diagnose the problem, but I suspect it's due to how you have assembled things with jlink. You may be able to use the debugger to determine why the parameter name discovery is failing and correct your configuration.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
