### ISSUE TITLE
weblogic 12.1.3 deployment problem: Failed to instantiate WebApplicationInitializer class

### ISSUE THREAD

**Issue by kkrzeminski** [spring-projects/spring-boot#2738]
Weblogic is unable to dpeloy applicaiton build with Spring boot 1.2.2 (Weblogic 12.1.3)

      "weblogic.application.ModuleException: weblogic.management.DeploymentException: Failed to instantiate WebApplicationInitializer class"
         weblogic.application.ModuleException: weblogic.management.DeploymentException: Failed to instantiate WebApplicationInitializer class
         at weblogic.application.internal.ExtensibleModuleWrapper.start(ExtensibleModuleWrapper.java:140)

Workaround: 
 - Deploying a WAR in an Old (Servlet 2.5) Container (http://docs.spring.io/spring-boot/docs/current/reference/html/howto-traditional-deployment.html#howto-servlet-2-5)

**Comment by wilkinsona** [comment]
@kkrzeminski Can you share the full stack trace of the failure please?

**Comment by kkrzeminski** [comment]
WebApplicationInitializer is an interface weblogic (12.1.3) tries to instantiate it.

Stacktrace:
     weblogic.application.ModuleException: weblogic.management.DeploymentException: Failed to instantiate WebApplicationInitializer class                                                                         
            at weblogic.application.internal.ExtensibleModuleWrapper.start(ExtensibleModuleWrapper.java:140)                                                                                                     
            at weblogic.application.internal.flow.ModuleListenerInvoker.start(ModuleListenerInvoker.java:124)                                                                                                    
            at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:216)                                                                                                           
            at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:211)                                                                                                           
            at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:42)                                                                                                               
            at weblogic.application.internal.flow.ModuleStateDriver.start(ModuleStateDriver.java:73)                                                                                                             
            at weblogic.application.internal.flow.StartModulesFlow.activate(StartModulesFlow.java:24)                                                                                                            
            at weblogic.application.internal.BaseDeployment$2.next(BaseDeployment.java:729)                                                                                                                      
            at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:42)                                                                                                               
            at weblogic.application.internal.BaseDeployment.activate(BaseDeployment.java:258)                                                                                                                    
            at weblogic.application.internal.SingleModuleDeployment.activate(SingleModuleDeployment.java:48)                                                                                                     
            at weblogic.application.internal.DeploymentStateChecker.activate(DeploymentStateChecker.java:165)                                                                                                    
            at weblogic.deploy.internal.targetserver.AppContainerInvoker.activate(AppContainerInvoker.java:80)                                                                                                   
            at weblogic.deploy.internal.targetserver.operations.AbstractOperation.activate(AbstractOperation.java:587)                                                                                           
            at weblogic.deploy.internal.targetserver.operations.ActivateOperation.activateDeployment(ActivateOperation.java:150)                                                                                 
            at weblogic.deploy.internal.targetserver.operations.ActivateOperation.doCommit(ActivateOperation.java:116)                                                                                           
            at weblogic.deploy.internal.targetserver.operations.AbstractOperation.commit(AbstractOperation.java:339)                                                                                             
            at weblogic.deploy.internal.targetserver.DeploymentManager.handleDeploymentCommit(DeploymentManager.java:846)                                                                                        
            at weblogic.deploy.internal.targetserver.DeploymentManager.activateDeploymentList(DeploymentManager.java:1275)                                                                                       
            at weblogic.deploy.internal.targetserver.DeploymentManager.handleCommit(DeploymentManager.java:442)                                                                                                  
            at weblogic.deploy.internal.targetserver.DeploymentServiceDispatcher.commit(DeploymentServiceDispatcher.java:176)                                                                                    
            at weblogic.deploy.service.internal.targetserver.DeploymentReceiverCallbackDeliverer.doCommitCallback(DeploymentReceiverCallbackDeliverer.java:195)                                                  
            at weblogic.deploy.service.internal.targetserver.DeploymentReceiverCallbackDeliverer.access$100(DeploymentReceiverCallbackDeliverer.java:13)                                                         
            at weblogic.deploy.service.internal.targetserver.DeploymentReceiverCallbackDeliverer$2.run(DeploymentReceiverCallbackDeliverer.java:68)                                                              
            at weblogic.work.SelfTuningWorkManagerImpl$WorkAdapterImpl.run(SelfTuningWorkManagerImpl.java:548)                                                                                                   
            at weblogic.work.ExecuteThread.execute(ExecuteThread.java:311)                                                                                                                                       
            at weblogic.work.ExecuteThread.run(ExecuteThread.java:263)                                                                                                                                           
    Caused By: weblogic.management.DeploymentException: Failed to instantiate WebApplicationInitializer class                                                                                                    
            at weblogic.servlet.internal.WebAppServletContext.initContainerInitializer(WebAppServletContext.java:1397)                                                                                           
            at weblogic.servlet.internal.WebAppServletContext.initContainerInitializers(WebAppServletContext.java:1331)                                                                                          
            at weblogic.servlet.internal.WebAppServletContext.initContainerInitializers(WebAppServletContext.java:1317)                                                                                          
            at weblogic.servlet.internal.WebAppServletContext.preloadResources(WebAppServletContext.java:1834)                                                                                                   
            at weblogic.servlet.internal.WebAppServletContext.start(WebAppServletContext.java:2876)                                                                                                              
            at weblogic.servlet.internal.WebAppModule.startContexts(WebAppModule.java:1661)                                                                                                                      
            at weblogic.servlet.internal.WebAppModule.start(WebAppModule.java:823)                                                                                                                               
            at weblogic.application.internal.ExtensibleModuleWrapper$StartStateChange.next(ExtensibleModuleWrapper.java:360)                                                                                     
            at weblogic.application.internal.ExtensibleModuleWrapper$StartStateChange.next(ExtensibleModuleWrapper.java:356)                                                                                     
            at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:42)                                                                                                               
            at weblogic.application.internal.ExtensibleModuleWrapper.start(ExtensibleModuleWrapper.java:138)                                                                                                     
            at weblogic.application.internal.flow.ModuleListenerInvoker.start(ModuleListenerInvoker.java:124)                                                                                                    
            at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:216)                                                                                                           
            at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:211)                                                                                                           
            at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:42)                                                                                                               
            at weblogic.application.internal.flow.ModuleStateDriver.start(ModuleStateDriver.java:73)                                                                                                             
            at weblogic.application.internal.flow.StartModulesFlow.activate(StartModulesFlow.java:24)                                                                                                            
            at weblogic.application.internal.BaseDeployment$2.next(BaseDeployment.java:729)                                                                                                                      
            at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:42)                                                                                                               
            at weblogic.application.internal.BaseDeployment.activate(BaseDeployment.java:258)                                                                                                                    
            at weblogic.application.internal.SingleModuleDeployment.activate(SingleModuleDeployment.java:48)                                                                                                     
            at weblogic.application.internal.DeploymentStateChecker.activate(DeploymentStateChecker.java:165)                                                                                                    
            at weblogic.deploy.internal.targetserver.AppContainerInvoker.activate(AppContainerInvoker.java:80)                                                                                                   
            at weblogic.deploy.internal.targetserver.operations.AbstractOperation.activate(AbstractOperation.java:587)                                                                                           
            at weblogic.deploy.internal.targetserver.operations.ActivateOperation.activateDeployment(ActivateOperation.java:150)                                                                                 
            at weblogic.deploy.internal.targetserver.operations.ActivateOperation.doCommit(ActivateOperation.java:116)                                                                                           
            at weblogic.deploy.internal.targetserver.operations.AbstractOperation.commit(AbstractOperation.java:339)                                                                                             
            at weblogic.deploy.internal.targetserver.DeploymentManager.handleDeploymentCommit(DeploymentManager.java:846)                                                                                        
            at weblogic.deploy.internal.targetserver.DeploymentManager.activateDeploymentList(DeploymentManager.java:1275)                                                                                       
            at weblogic.deploy.internal.targetserver.DeploymentManager.handleCommit(DeploymentManager.java:442)                                                                                                  
            at weblogic.deploy.internal.targetserver.DeploymentServiceDispatcher.commit(DeploymentServiceDispatcher.java:176)                                                                                    
            at weblogic.deploy.service.internal.targetserver.DeploymentReceiverCallbackDeliverer.doCommitCallback(DeploymentReceiverCallbackDeliverer.java:195)                                                  
            at weblogic.deploy.service.internal.targetserver.DeploymentReceiverCallbackDeliverer.access$100(DeploymentReceiverCallbackDeliverer.java:13)                                                         
            at weblogic.deploy.service.internal.targetserver.DeploymentReceiverCallbackDeliverer$2.run(DeploymentReceiverCallbackDeliverer.java:68)                                                              
            at weblogic.work.SelfTuningWorkManagerImpl$WorkAdapterImpl.run(SelfTuningWorkManagerImpl.java:548)                                                                                                   
            at weblogic.work.ExecuteThread.execute(ExecuteThread.java:311)                                                                                                                                       
            at weblogic.work.ExecuteThread.run(ExecuteThread.java:263)                                                                                                                                           


Envirnoment

    java.io.tmpdir = /tmp
    java.library.path = /opt/ibm/java-x86_64-70/jre/lib/amd64/compressedrefs:/opt/ibm/java-x86_64-70/jre/lib/amd64::/
    86_64/oci920_8:/usr/lib
    java.naming.factory.initial = weblogic.jndi.WLInitialContextFactory
    java.naming.factory.url.pkgs = weblogic.jndi.factories:weblogic.corba.j2ee.naming.url:weblogic.jndi.factories:web
    java.runtime.name = Java(TM) SE Runtime Environment
    java.runtime.version = pxa6470sr8fp10-20141219_01 (SR8 FP10)
    java.security.policy = /app/wl12c/DOMAIN/Middleware/wlserver/server/lib/weblogic.policy
    java.specification.name = Java Platform API Specification
    java.specification.vendor = Sun Microsystems Inc.
    java.specification.version = 1.7
    java.util.prefs.PreferencesFactory = java.util.prefs.FileSystemPreferencesFactory
    java.vendor = IBM Corporation
    java.vendor.url = http://www.ibm.com/
    java.version = 1.7.0
    java.vm.info = JRE 1.7.0 Linux amd64-64 Compressed References 20141216_227497 (JIT enabled, AOT enabled)
    J9VM - R26_Java726_SR8_20141216_0955_B227497
    JIT  - r11.b07_20141003_74578.05
    GC   - R26_Java726_SR8_20141216_0955_B227497_CMPRSS
    J9CL - 20141216_227497
    java.vm.name = IBM J9 VM
    java.vm.specification.name = Java Virtual Machine Specification
    java.vm.specification.vendor = Sun Microsystems Inc.
    java.vm.specification.version = 1.0
    java.vm.vendor = IBM Corporation
    java.vm.version = 2.6
    javax.management.builder.initial = weblogic.management.jmx.mbeanserver.WLSMBeanServerBuilder
    javax.rmi.CORBA.PortableRemoteObjectClass = weblogic.iiop.PortableRemoteObjectDelegateImpl
    javax.rmi.CORBA.UtilClass = weblogic.iiop.UtilDelegateImpl
    jxe.current.romimage.version = 17
    jxe.lowest.romimage.version = 17
    org.omg.CORBA.ORBClass = weblogic.corba.orb.ORB
    org.omg.CORBA.ORBSingletonClass = weblogic.corba.orb.ORB
    os.arch = amd64
    os.encoding = UTF-8
    os.name = Linux
    os.version = 3.10.0-123.13.2.el7.x86_64
    path.separator = :
    sun.arch.data.model = 64
    sun.boot.class.path = /app/wl12c/DOMAIN/Middleware/wlserver/../oracle_common/modules/endorsed/jsr250-api.jar:/ap
    /../oracle_common/modules/endorsed/javax-xml-bind.jar:/opt/ibm/java-x86_64-70/jre/lib/amd64/compressedrefs/jclSC1
    /lib/jlm.jar:/opt/ibm/java-x86_64-70/jre/lib/ibmorb.jar:/opt/ibm/java-x86_64-70/jre/lib/ibmorbapi.jar:/opt/ibm/ja
    :/opt/ibm/java-x86_64-70/jre/lib/ibmjgssfw.jar:/opt/ibm/java-x86_64-70/jre/lib/ibmjssefw.jar:/opt/ibm/java-x86_64
    pt/ibm/java-x86_64-70/jre/lib/ibmjsseprovider2.jar:/opt/ibm/java-x86_64-70/jre/lib/ibmcertpathprovider.jar:/opt/i
    /opt/ibm/java-x86_64-70/jre/lib/resources.jar:/opt/ibm/java-x86_64-70/jre/lib/rt.jar:/opt/ibm/java-x86_64-70/jre/
    sun.boot.library.path = /opt/ibm/java-x86_64-70/jre/lib/amd64/compressedrefs:/opt/ibm/java-x86_64-70/jre/lib/amd6
    sun.cpu.endian = little
    sun.io.unicode.encoding = UnicodeLittle
    sun.java.command = weblogic.Server
    sun.java.launcher = SUN_STANDARD
    sun.java.launcher.pid = 19837
    sun.jnu.encoding = UTF-8
    user.country = US
    user.dir = /app/wl12c/DOMAIN/domains/cadevdomain
    user.home = /home/weblogic
    user.language = en
    user.name = weblogic
    user.timezone = Europe/Warsaw
    vde.home = /app/wl12c/DOMAIN/domains/cadevdomain/servers/AdminServer/data/ldap
    weblogic.Name = AdminServer
    weblogic.ProductionModeEnabled = true
    weblogic.home = /app/wl12c/DOMAIN/Middleware/wlserver/server
    weblogic.utils.cmm.lowertier.ServiceDisabled = true
    wls.home = /app/wl12c/DOMAIN/Middleware/wlserver/server

**Comment by wilkinsona** [comment]
Thanks. I'd guess that WebLogic's trying to instantiate an implementation of `WebApplicationInitializer` rather than `WebApplicationInitializer` itself but that's just a guess. Is that all that WebLogic tells you about the failure? Some information about why the instantiation failed is what I'm looking for.

**Comment by kkrzeminski** [comment]
As i remember weblogic (debugged) simply instantiates interface .
So we can close this issue or send it to Oracle support service. 
Or I can change deployment style to ear with libs in ear folder, which maybe prevent from instanitation of spring boot classeses.

**Comment by wilkinsona** [comment]
Thanks again. If it really is trying to instantiate an interface then it does sound like Oracle support is the best place to handle this. That said, I'd still like to know why it's trying to instantiate the interface. I can't imagine that it's a general problem, otherwise WebLogic would be broken for many, many people.

**Comment by kkrzeminski** [comment]
Lack of time, may be next time i'll send to oracle support
