### ISSUE TITLE
Spring Boot 1.2.2 incompatible with jackson-datatype-joda version 2.5.0+

### ISSUE THREAD

**Issue by chrisbianca** [spring-projects/spring-boot#2746]
I've just tried to update to Spring Boot version 1.2.2 and found that it is incompatible with jackson-datatype-joda version 2.5.0+.  This is because in the later versions of the jackson-datatype-joda library, the class JacksonJodaFormat no longer exists.

See the following stack trace:

```
[INFO] java.lang.IllegalStateException: Could not evaluate condition on org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration$JacksonObjectMapperConfiguration#jacksonObjectMapper due to internal class not found. This can happen if you are @ComponentScanning a springframework package (e.g. if you put a @ComponentScan in the default package by mistake)
[INFO] 	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:51)
[INFO] 	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:102)
[INFO] 	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:194)
[INFO] 	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:148)
[INFO] 	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:124)
[INFO] 	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:318)
[INFO] 	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:239)
[INFO] 	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:254)
[INFO] 	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:94)
[INFO] 	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:606)
[INFO] 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:462)
[INFO] 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
[INFO] 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
[INFO] 	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139)
[INFO] 	at org.springframework.boot.legacy.context.web.SpringBootContextLoaderListener.initWebApplicationContext(SpringBootContextLoaderListener.java:61)
[INFO] 	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
[INFO] 	at org.mortbay.jetty.handler.ContextHandler.startContext(ContextHandler.java:548)
[INFO] 	at org.mortbay.jetty.servlet.Context.startContext(Context.java:136)
[INFO] 	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1250)
[INFO] 	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:517)
[INFO] 	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:467)
[INFO] 	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
[INFO] 	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
[INFO] 	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
[INFO] 	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
[INFO] 	at org.mortbay.jetty.Server.doStart(Server.java:224)
[INFO] 	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
[INFO] 	at com.google.appengine.tools.development.JettyContainerService.startContainer(JettyContainerService.java:255)
[INFO] 	at com.google.appengine.tools.development.AbstractContainerService.startup(AbstractContainerService.java:288)
[INFO] 	at com.google.appengine.tools.development.AutomaticInstanceHolder.startUp(AutomaticInstanceHolder.java:26)
[INFO] 	at com.google.appengine.tools.development.AbstractModule.startup(AbstractModule.java:87)
[INFO] 	at com.google.appengine.tools.development.Modules.startup(Modules.java:105)
[INFO] 	at com.google.appengine.tools.development.DevAppServerImpl.doStart(DevAppServerImpl.java:258)
[INFO] 	at com.google.appengine.tools.development.DevAppServerImpl.access$000(DevAppServerImpl.java:47)
[INFO] 	at com.google.appengine.tools.development.DevAppServerImpl$1.run(DevAppServerImpl.java:213)
[INFO] 	at com.google.appengine.tools.development.DevAppServerImpl$1.run(DevAppServerImpl.java:211)
[INFO] 	at java.security.AccessController.doPrivileged(Native Method)
[INFO] 	at com.google.appengine.tools.development.DevAppServerImpl.start(DevAppServerImpl.java:211)
[INFO] 	at com.google.appengine.tools.development.DevAppServerMain$StartAction.apply(DevAppServerMain.java:277)
[INFO] 	at com.google.appengine.tools.util.Parser$ParseResult.applyArgs(Parser.java:48)
[INFO] 	at com.google.appengine.tools.development.DevAppServerMain.run(DevAppServerMain.java:219)
[INFO] 	at com.google.appengine.tools.development.DevAppServerMain.main(DevAppServerMain.java:210)
[INFO] Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/datatype/joda/ser/JacksonJodaFormat
[INFO] 	at java.lang.Class.getDeclaredMethods0(Native Method)
[INFO] 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
[INFO] 	at java.lang.Class.getDeclaredMethods(Class.java:1967)
[INFO] 	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:571)
[INFO] 	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:490)
[INFO] 	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:474)
[INFO] 	at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:534)
[INFO] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:677)
[INFO] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:621)
[INFO] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:591)
[INFO] 	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1397)
[INFO] 	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:968)
[INFO] 	at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry$OptimizedBeanTypeRegistry.addBeanTypeForNonAliasDefinition(BeanTypeRegistry.java:257)
[INFO] 	at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry$OptimizedBeanTypeRegistry.addBeanType(BeanTypeRegistry.java:246)
[INFO] 	at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry$OptimizedBeanTypeRegistry.getNamesForType(BeanTypeRegistry.java:227)
[INFO] 	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.collectBeanNamesForType(OnBeanCondition.java:158)
[INFO] 	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanNamesForType(OnBeanCondition.java:147)
[INFO] 	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchingBeans(OnBeanCondition.java:119)
[INFO] 	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:94)
[INFO] 	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:45)
[INFO] 	... 41 common frames omitted
[INFO] Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.datatype.joda.ser.JacksonJodaFormat
[INFO] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
[INFO] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[INFO] 	at java.security.AccessController.doPrivileged(Native Method)
[INFO] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
[INFO] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[INFO] 	at com.google.appengine.tools.development.IsolatedAppClassLoader.loadClass(IsolatedAppClassLoader.java:216)
[INFO] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[INFO] 	... 61 common frames omitted
```

**Comment by wilkinsona** [comment]
I'm pretty sure this is a duplicate of #2573. Can you please try a 1.2.3 snapshot available from https://repo.spring.io/libs-snapshot.

**Comment by chrisbianca** [comment]
You're right, it works again with 1.2.3 snapshot.
Sorry, I hadn't noticed that there was already a closed issue.

**Comment by wilkinsona** [comment]
No problem. Thanks for trying the snapshot.
