### ISSUE TITLE
org.springframework.boot.logging.LoggingApplicationListener throws NPE on Google App Engine

### ISSUE THREAD

**Issue by johannburkard** [spring-projects/spring-boot#2759]
Tried to upgrade from Spring Boot 1.1.0.BUILD-SNAPSHOT to 1.1.9-RELEASE and the app wouldn't start up.

```
Uncaught exception from servlet
java.lang.NullPointerException
	at org.springframework.boot.logging.LoggingApplicationListener.cleanLogTempProperty(LoggingApplicationListener.java:172)
	at org.springframework.boot.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:145)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:126)
```

The culprit:

```
	private void cleanLogTempProperty() {
		// Logback won't read backslashes so add a clean path for it to use
		if (!StringUtils.hasLength(System.getProperty("LOG_TEMP"))) {
			String path = System.getProperty("java.io.tmpdir");
			path = StringUtils.cleanPath(path);
			if (path.endsWith("/")) {
				path = path.substring(0, path.length() - 1);
			}
			System.setProperty("LOG_TEMP", path);
		}
	}
```

Path is null on GAE, presumably, because there is no file system and no temporary directory there.

**Comment by philwebb** [comment]
We aren't planning any further updates to the 1.1.x line, are you also seeing the same problem with the latest 1.2 release?

**Comment by johannburkard** [comment]
Just upgraded to 1.2.3-RELEASE, had to fix a few bugs since the ServletUriComponentsBuilder is now doing a lot more work and my el-cheapo Groovy proxies wouldn't cut it.

But the app starts up fine. :+1: Not surprising since that code is gone.
