### ISSUE TITLE
SolrAutoConfiguration is not compatible with Solr 5.0 and fails with a rather unhelpful message

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#2795]
This probably isn't a huge problem until Spring Data Solr supports 5.0, but it currently fails with a rather unhelpful message:

```
Exception in thread "main" java.lang.IllegalStateException: Error processing condition on org.springframework.boot.autoconfigure.solr.SolrAutoConfiguration.solrServer
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:58)
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:102)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:190)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:148)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:124)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:318)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:239)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:254)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:94)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:606)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:462)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
	at demo.So29520654Application.main(So29520654Application.java:10)
Caused by: java.lang.IllegalArgumentException: @ConditionalOnMissingBean annotations must specify at least one bean (type, name or annotation)
	at org.springframework.util.Assert.isTrue(Assert.java:65)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$BeanSearchSpec.<init>(OnBeanCondition.java:223)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:92)
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:45)
	... 15 more
```

The `@ConditionalOnMissingBean` annotation is believed to be incomplete as the attempt to deduce the bean's type has failed. This failure is included in a debug log message and then swallowed. In this case the swallowed exception is a `VerifyError` as the type hierarchy of `CloudSolrServer` has changed in 5.0 and it's no longer a `SolrServer` subclass:

```
java.lang.VerifyError: Bad return type
Exception Details:
  Location:
    org/springframework/boot/autoconfigure/solr/SolrAutoConfiguration.createSolrServer()Lorg/apache/solr/client/solrj/SolrServer; @27: areturn
  Reason:
    Type 'org/apache/solr/client/solrj/impl/CloudSolrServer' (current frame, stack[0]) is not assignable to 'org/apache/solr/client/solrj/SolrServer' (from method signature)
  Current Frame:
    bci: @27
    flags: { }
    locals: { 'org/springframework/boot/autoconfigure/solr/SolrAutoConfiguration' }
    stack: { 'org/apache/solr/client/solrj/impl/CloudSolrServer' }
  Bytecode:
    0000000: 2ab4 0005 b600 06b8 0007 9900 12bb 0008
    0000010: 592a b400 05b6 0006 b700 09b0 bb00 0a59
    0000020: 2ab4 0005 b600 0bb7 000c b0            
  Stackmap Table:
    same_frame(@28)
```

I used the debugger the figure this out. Given the fatal nature of failing to deduce the bean's type, I wonder if the `VerifyError` should be logged at something higher than debug.

**Comment by christophstrobl** [comment]
Thanks @wilkinsona. theres's already [DATASOLR-232](https://jira.spring.io/browse/DATASOLR-232) and the according issue branch available. Unfortunately this will be a breaking change in sd-solr as well so we're thinking about a 2.0 release for this one.

**Comment by jcastaldoFoodEssentials** [comment]
Yesterday the spring data project updated to a 2.0.0-SNAPSHOT with the solr 5 changes.

I pulled the spring-boot code and edited the pom file to accept solr 5.2.1, the spring snapshot repository,  and the 2.0.0-SNAPSHOT from the repository.

Then, I went and edited SolrRepositoriesAutoConfiguration.java, SolrAutoConfiguration.java, and SolrRepositoriesAutoConfigurationTests.java to use the SolrClient, HttpSolrClient, and CloudSolrClient classes.

I tried to compile the code and found that the auto-configure could not compile because it could not find the RedisTestServer class, but I didn't touch anything with that.

I'd like to get this code to you guys or hear feedback on where I should go from here. Should I issue a pull request or should I push to a branch? 

Any and all responses are welcome. 

Thank you.

**Comment by philwebb** [comment]
@jcastaldoFoodEssentials Thanks for looking at this. If you could push your branch to your GitHub fork and provide a link we could take a look.

**Comment by jcastaldoFoodEssentials** [comment]
@philwebb 

You can see what I've done at
https://github.com/jcastaldoFoodEssentials/spring-boot/tree/possible_solr_5_changes

So, I have been able to get everything to compile up to the spring-boot-sample-data-solr. It couldn't auto write the ProductRepository which made sense to me because that class is simply a interface.

Now, for the changes I made. You'll see I changed the pom in the auto configure and the actuator to accept solrj 5.3.0 and the 2.0.0.Build.Snapshot of Spring Data Solr. I don't think this is going to be something you want, so what can I do to eliminate that to be more in line with what you guys want?

For the actual auto configure I switched everything from SolrServer to use SolrClient. The issue I could see with that is backwards compatibility with older versions of solrj people may be using. If there is a way to support older versions of solrj please tell me and I can implement it. 

In the actuator I changed the HealthMonitor to look for SolrClient instead of SolrServer which was done to ensure the tests pass.

Tell me what you think.

**Comment by jcastaldoFoodEssentials** [comment]
@philwebb 

So, I fixed the compilation issues. I figured out where the versions were being defined for solrj so I updated that instead of updating it everywhere in the pom files like a dummy haha. I also explicitly added the spring data solr build that had solr 5 support instead of relying on the Gosling Release Dependency to provide it.

I updated everything to work and I can confirm it compiles properly.

You can see it at https://github.com/jcastaldoFoodEssentials/spring-boot/tree/solr5

Thanks Phil.

**Comment by philwebb** [comment]
See also #3959
