### ISSUE TITLE
JCE cannot cannot authenticate the provider BC

### ISSUE THREAD

**Issue by Captain-P-Goldfish** [spring-projects/spring-boot#28157]
Hi I am getting the above error on windows only when running my springboot application. Springboot is packaging the third party libraries under BOOT-INF/lib and something causes the signature of bouncy castle to get broken when executed under windows. I am not sure if this is really spring-boot related but it seems possible given the mentioned circumstances. It runs perfectly fine under linux.

I am using Oracle JDK 11 and 17. Error occurs for both versions.
You should be able to reproduce the problem by checking out the following project:
https://github.com/Captain-P-Goldfish/goldfishs-oauth2-client
run `mvn package -DskipTests` and run the jar in the application module `java -jar oauth-test-client.jar`. No need to setup any configurations. It should start immediatedly. If access your browser afterwards under `http://localhost:8080` the error should immediately occur.

**Comment by wilkinsona** [comment]
Thanks for the sample. Unfortunately, it doesn't reproduce the problem for me on Windows 10 using Java 11. The client starts successfully and I can access http://localhost:8080 in a browser. It redirects to http://localhost:8080/views/jwts and successfully renders the page.

If you would like us to spend some more time investigating, can you please provide some more details on what we need to do to reproduce the problem?

**Comment by Captain-P-Goldfish** [comment]
Did you build the jar-file?
From what you wrote it sounds like you started the project from the IDE. I get this error only from the built jar-file. And the very same jar file is then started on my ubuntu distribution over WSL where it works perfectly.

And I am a little bit confused... I can reliably recreate the problem on three different machines... I got no idea how it works on your machine...

this is the error I get:
(The NullPointer at the end of the stacktrace is the result of the provider that could not be authenticated)

```
←[m02 Okt. 2021 13:41:36,792 [http-nio-8080-exec-1] ←[31mERROR←[m de.captaingoldfish.restclient.database.entities.Keystore (Keystore.java:146) - ←[31merror constructing MAC: java.lang.SecurityException: JCE cannot authenticate the provider BC
java.io.IOException: error constructing MAC: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12KeyStoreSpi.engineLoad(Unknown Source)
        at java.base/java.security.KeyStore.load(KeyStore.java:1473)
        at de.captaingoldfish.restclient.commons.keyhelper.KeyStoreSupporter.readKeyStore(KeyStoreSupporter.java:487)
        at de.captaingoldfish.restclient.database.entities.Keystore.getKeyStore(Keystore.java:142)
        at de.captaingoldfish.restclient.database.entities.Keystore.getKeyStoreAliases(Keystore.java:279)
        at de.captaingoldfish.restclient.application.endpoints.keystore.KeystoreHandler.listResources(KeystoreHandler.java:230)
        at de.captaingoldfish.scim.sdk.server.endpoints.ResourceEndpointHandler.listResources(ResourceEndpointHandler.java:528)
        at de.captaingoldfish.scim.sdk.server.endpoints.ResourceEndpoint.resolveRequest(ResourceEndpoint.java:279)
        at de.captaingoldfish.scim.sdk.server.endpoints.ResourceEndpoint.handleRequest(ResourceEndpoint.java:216)
        at de.captaingoldfish.scim.sdk.server.endpoints.ResourceEndpoint.handleRequest(ResourceEndpoint.java:104)
        at de.captaingoldfish.restclient.application.endpoints.ScimController.handleScimRequest(ScimController.java:66)
        at de.captaingoldfish.restclient.application.endpoints.ScimController$$FastClassBySpringCGLIB$$7550be0e.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
        at de.captaingoldfish.restclient.application.endpoints.ScimController$$EnhancerBySpringCGLIB$$36cd90f0.handleScimRequest(<generated>)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:887)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1684)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:833)
←[m02 Okt. 2021 13:41:36,796 [http-nio-8080-exec-1] ←[31mERROR←[m de.captaingoldfish.scim.sdk.common.response.ErrorResponse (ErrorResponse.java:58) - ←[31mCannot invoke "java.security.KeyStore.aliases()" because the return value of "de.captaingoldfish.restclient.database.entities.Keystore.getKeyStore()" is null
de.captaingoldfish.scim.sdk.common.exceptions.InternalServerException: Cannot invoke "java.security.KeyStore.aliases()" because the return value of "de.captaingoldfish.restclient.database.entities.Keystore.getKeyStore()" is null
        at de.captaingoldfish.scim.sdk.server.endpoints.ResourceEndpointHandler.listResources(ResourceEndpointHandler.java:603)
        at de.captaingoldfish.scim.sdk.server.endpoints.ResourceEndpoint.resolveRequest(ResourceEndpoint.java:279)
        at de.captaingoldfish.scim.sdk.server.endpoints.ResourceEndpoint.handleRequest(ResourceEndpoint.java:216)
        at de.captaingoldfish.scim.sdk.server.endpoints.ResourceEndpoint.handleRequest(ResourceEndpoint.java:104)
        at de.captaingoldfish.restclient.application.endpoints.ScimController.handleScimRequest(ScimController.java:66)
        at de.captaingoldfish.restclient.application.endpoints.ScimController$$FastClassBySpringCGLIB$$7550be0e.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
        at de.captaingoldfish.restclient.application.endpoints.ScimController$$EnhancerBySpringCGLIB$$36cd90f0.handleScimRequest(<generated>)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:887)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1684)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "java.security.KeyStore.aliases()" because the return value of "de.captaingoldfish.restclient.database.entities.Keystore.getKeyStore()" is null
        at de.captaingoldfish.restclient.database.entities.Keystore.getKeyStoreAliases(Keystore.java:279)
        at de.captaingoldfish.restclient.application.endpoints.keystore.KeystoreHandler.listResources(KeystoreHandler.java:230)
        at de.captaingoldfish.scim.sdk.server.endpoints.ResourceEndpointHandler.listResources(ResourceEndpointHandler.java:528)
        ... 66 more
←[m
```

**Comment by wilkinsona** [comment]
I'm not sure what gave you the impression I had used an IDE. I started the app using `java -jar`. I've just done so again to double-check:

```
C:\dev\temp\goldfishs-oauth2-client\application\target>java -jar oauth2-test-client.jar

                   ___      _     _  __ _     _    _
                  / _ \___ | | __| |/ _(_)___| |__( )__
                 / /_\/ _ \| |/ _` | |_| / __| '_ \/ __|
                / /_\\ (_) | | (_| |  _| \__ \ | | \__ \
                \____/\___/|_|\__,_|_| |_|___/_| |_|___/

  __  ____  ____  __ _  __  ____     ___  __   __ _  __ _  ____  ___  ____
 /  \(  _ \(  __)(  ( \(  )(    \   / __)/  \ (  ( \(  ( \(  __)/ __)(_  _)
(  O )) __/ ) _) /    / )(  ) D (  ( (__(  O )/    //    / ) _)( (__   )(
 \__/(__)  (____)\_)__)(__)(____/   \___)\__/ \_)__)\_)__)(____)\___) (__)

                 ______        __      ________          __
                /_  __/__ ___ / /_____/ ___/ (_)__ ___  / /_
                 / / / -_|_-</ __/___/ /__/ / / -_) _ \/ __/
                /_/  \__/___/\__/    \___/_/_/\__/_//_/\__/


03 Oct 2021 09:49:48,047 [main] [37mINFO [m de.captaingoldfish.restclient.application.OAuth2RestClient (StartupInfoLogger.java:55) - [37mStarting OAuth2RestClient using Java 11.0.7 on c802ce5-OOBE-01 with PID 5640 (C:\dev\temp\goldfishs-oauth2-client\application\target\oauth2-test-client.jar started by Andy Wilkinson in C:\dev\temp\goldfishs-oauth2-client\application\target)
[m03 Oct 2021 09:49:48,076 [main] [1;34mDEBUG[m de.captaingoldfish.restclient.application.OAuth2RestClient (StartupInfoLogger.java:56) - [1;34mRunning with Spring Boot v2.4.3, Spring v5.3.4
[m03 Oct 2021 09:49:48,079 [main] [37mINFO [m de.captaingoldfish.restclient.application.OAuth2RestClient (SpringApplication.java:660) - [37mNo active profile set, falling back to default profiles: default
[m03 Oct 2021 09:49:51,313 [main] [37mINFO [m org.springframework.data.repository.config.RepositoryConfigurationDelegate (RepositoryConfigurationDelegate.java:128) - [37mBootstrapping Spring Data JPA repositories in DEFAULT mode.
[m03 Oct 2021 09:49:51,734 [main] [37mINFO [m org.springframework.data.repository.config.RepositoryConfigurationDelegate (RepositoryConfigurationDelegate.java:188) - [37mFinished Spring Data repository scanning in 357 ms. Found 9 JPA repository interfaces.
[m03 Oct 2021 09:49:53,852 [main] [37mINFO [m org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker (PostProcessorRegistrationDelegate.java:376) - [37mBean 'databaseConfig' of type [de.captaingoldfish.restclient.database.config.DatabaseConfig$$EnhancerBySpringCGLIB$$e48c1801] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[m03 Oct 2021 09:49:55,143 [main] [37mINFO [m org.springframework.boot.web.embedded.tomcat.TomcatWebServer (TomcatWebServer.java:108) - [37mTomcat initialized with port(s): 8080 (http)
[m03 Oct 2021 09:49:55,195 [main] [37mINFO [m org.apache.coyote.http11.Http11NioProtocol (DirectJDKLog.java:173) - [37mInitializing ProtocolHandler ["http-nio-8080"]
[m03 Oct 2021 09:49:55,196 [main] [37mINFO [m org.apache.catalina.core.StandardService (DirectJDKLog.java:173) - [37mStarting service [Tomcat]
[m03 Oct 2021 09:49:55,202 [main] [37mINFO [m org.apache.catalina.core.StandardEngine (DirectJDKLog.java:173) - [37mStarting Servlet engine: [Apache Tomcat/9.0.43]
[m03 Oct 2021 09:49:55,438 [main] [37mINFO [m org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] (DirectJDKLog.java:173) - [37mInitializing Spring embedded WebApplicationContext
[m03 Oct 2021 09:49:55,439 [main] [37mINFO [m org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext (ServletWebServerApplicationContext.java:289) - [37mRoot WebApplicationContext: initialization completed in 7138 ms
[m03 Oct 2021 09:49:56,124 [main] [37mINFO [m de.captaingoldfish.scim.sdk.server.schemas.ResourceTypeFactory (ResourceTypeFactory.java:110) - [37mResource schema with id 'urn:ietf:params:scim:schemas:core:2.0:ServiceProviderConfig' is already registered. The new instance is not equal to the old schema document. The old document is being replaced by the new one
[m03 Oct 2021 09:49:56,180 [main] [37mINFO [m de.captaingoldfish.scim.sdk.server.schemas.ResourceTypeFactory (ResourceTypeFactory.java:110) - [37mResource schema with id 'urn:ietf:params:scim:schemas:core:2.0:ResourceType' is already registered. The new instance is not equal to the old schema document. The old document is being replaced by the new one
[m03 Oct 2021 09:49:56,214 [main] [37mINFO [m de.captaingoldfish.scim.sdk.server.schemas.ResourceTypeFactory (ResourceTypeFactory.java:110) - [37mResource schema with id 'urn:ietf:params:scim:schemas:core:2.0:Schema' is already registered. The new instance is not equal to the old schema document. The old document is being replaced by the new one
[m03 Oct 2021 09:49:56,332 [main] [37mINFO [m de.captaingoldfish.restclient.database.config.DatabaseConfig (DatabaseConfig.java:111) - [37mconnecting to HSQLDB server: jdbc:hsqldb:file:./hsql-db/application-db
[m03 Oct 2021 09:49:58,029 [main] [37mINFO [m hsqldb.db.HSQLDB7C3AF66636.ENGINE (null:-1) - [37mcheckpointClose start
[m03 Oct 2021 09:49:58,030 [main] [37mINFO [m hsqldb.db.HSQLDB7C3AF66636.ENGINE (null:-1) - [37mcheckpointClose synched
[m03 Oct 2021 09:49:58,077 [main] [37mINFO [m hsqldb.db.HSQLDB7C3AF66636.ENGINE (null:-1) - [37mcheckpointClose script done
[m03 Oct 2021 09:49:58,113 [main] [37mINFO [m hsqldb.db.HSQLDB7C3AF66636.ENGINE (null:-1) - [37mcheckpointClose end
[m03 Oct 2021 09:49:58,201 [main] [37mINFO [m de.captaingoldfish.restclient.database.config.DatabaseConfig (DatabaseConfig.java:257) - [37mSuccessfully connected to database: HSQL Database Engine : 2.5.1
[m03 Oct 2021 09:49:58,480 [main] [37mINFO [m org.hibernate.jpa.internal.util.LogHelper (LogHelper.java:31) - [37mHHH000204: Processing PersistenceUnitInfo [name: default]
[m03 Oct 2021 09:49:58,733 [main] [37mINFO [m org.hibernate.Version (Version.java:44) - [37mHHH000412: Hibernate ORM core version 5.4.28.Final
[m03 Oct 2021 09:49:59,219 [main] [37mINFO [m org.hibernate.annotations.common.Version (JavaReflectionManager.java:56) - [37mHCANN000001: Hibernate Commons Annotations {5.1.2.Final}
[m03 Oct 2021 09:50:00,623 [main] [37mINFO [m org.hibernate.dialect.Dialect (Dialect.java:175) - [37mHHH000400: Using dialect: org.hibernate.dialect.HSQLDialect
[m03 Oct 2021 09:50:05,346 [main] [37mINFO [m org.hibernate.engine.transaction.jta.platform.internal.JtaPlatformInitiator (JtaPlatformInitiator.java:52) - [37mHHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
[m03 Oct 2021 09:50:05,395 [main] [37mINFO [m org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean (AbstractEntityManagerFactoryBean.java:437) - [37mInitialized JPA EntityManagerFactory for persistence unit 'default'
[m03 Oct 2021 09:50:07,878 [main] [37mINFO [m de.captaingoldfish.restclient.application.projectconfig.ThymeleafConfig (ThymeleafConfig.java:69) - [37mset application context: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@70e38ce1, started on Sun Oct 03 09:49:48 BST 2021
[m03 Oct 2021 09:50:08,456 [main] [37mINFO [m de.captaingoldfish.scim.sdk.server.schemas.ResourceTypeFactory (ResourceTypeFactory.java:110) - [37mResource schema with id 'urn:ietf:params:scim:schemas:captaingoldfish:2.0:HttpClientSettings' is already registered. The new instance is not equal to the old schema document. The old document is being replaced by the new one
[m03 Oct 2021 09:50:08,624 [main] [37mINFO [m de.captaingoldfish.scim.sdk.server.schemas.ResourceTypeFactory (ResourceTypeFactory.java:110) - [37mResource schema with id 'urn:ietf:params:scim:schemas:captaingoldfish:2.0:CurrentWorkflowSettings' is already registered. The new instance is not equal to the old schema document. The old document is being replaced by the new one
[m03 Oct 2021 09:50:09,323 [main] [37mINFO [m de.captaingoldfish.restclient.application.projectconfig.ThymeleafConfig (ThymeleafConfig.java:128) - [37msetting up Thymeleaf template engine.
[m03 Oct 2021 09:50:10,274 [main] [37mINFO [m de.captaingoldfish.restclient.application.projectconfig.ThymeleafConfig (ThymeleafConfig.java:157) - [37msetting up Thymeleaf template resolver
[m03 Oct 2021 09:50:10,567 [main] [37mINFO [m de.captaingoldfish.restclient.application.projectconfig.ThymeleafConfig (ThymeleafConfig.java:180) - [37msetting up Thymeleaf view resolver
[m03 Oct 2021 09:50:15,608 [main] [37mINFO [m liquibase.lockservice (JavaLogger.java:23) - [37mSuccessfully acquired change log lock
[m03 Oct 2021 09:50:18,525 [main] [37mINFO [m liquibase.changelog (JavaLogger.java:23) - [37mReading from PUBLIC.DATABASECHANGELOG
[m03 Oct 2021 09:50:19,217 [main] [37mINFO [m liquibase.lockservice (JavaLogger.java:23) - [37mSuccessfully released change log lock
[m03 Oct 2021 09:50:19,225 [main] [37mINFO [m liquibase.lockservice (JavaLogger.java:23) - [37mSuccessfully acquired change log lock
[mSkipping auto-registration
03 Oct 2021 09:50:19,228 [main] [33mWARN [m liquibase.hub (JavaLogger.java:23) - [33mSkipping auto-registration
[m03 Oct 2021 09:50:19,244 [main] [37mINFO [m liquibase.lockservice (JavaLogger.java:23) - [37mSuccessfully released change log lock
[m03 Oct 2021 09:50:19,587 [main] [33mWARN [m org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration (JpaBaseConfiguration.java:221) - [33mspring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
[m03 Oct 2021 09:50:22,287 [main] [37mINFO [m org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor (ExecutorConfigurationSupport.java:181) - [37mInitializing ExecutorService 'applicationTaskExecutor'
[m03 Oct 2021 09:50:27,137 [main] [37mINFO [m de.captaingoldfish.restclient.application.projectconfig.ThymeleafConfig (ThymeleafConfig.java:89) - [37madded resourceHandler (pathPattern: '/images/**'), (resourceLocation: '[classpath:/de/captaingoldfish/restclient/application/static/media/, classpath:/de/captaingoldfish/restclient/application/]')
[m03 Oct 2021 09:50:27,293 [main] [37mINFO [m de.captaingoldfish.restclient.application.projectconfig.ThymeleafConfig (ThymeleafConfig.java:93) - [37madded resourceHandler (pathPattern: '/images/**'), (resourceLocation: '[classpath:/de/captaingoldfish/restclient/application/static/media/, classpath:/de/captaingoldfish/restclient/application/]')
[m03 Oct 2021 09:50:27,457 [main] [37mINFO [m de.captaingoldfish.restclient.application.projectconfig.ThymeleafConfig (ThymeleafConfig.java:102) - [37madded resourceHandler (pathPattern: '/static/css/**'), (resourceLocation: '[classpath:/de/captaingoldfish/restclient/application/static/css/]')
[m03 Oct 2021 09:50:27,533 [main] [37mINFO [m de.captaingoldfish.restclient.application.projectconfig.ThymeleafConfig (ThymeleafConfig.java:111) - [37madded resourceHandler (pathPattern: '/static/js/**'), (resourceLocation: '[classpath:/de/captaingoldfish/restclient/application/static/js/]')
[m03 Oct 2021 09:50:30,735 [main] [37mINFO [m org.apache.coyote.http11.Http11NioProtocol (DirectJDKLog.java:173) - [37mStarting ProtocolHandler ["http-nio-8080"]
[m03 Oct 2021 09:50:31,218 [main] [37mINFO [m org.springframework.boot.web.embedded.tomcat.TomcatWebServer (TomcatWebServer.java:220) - [37mTomcat started on port(s): 8080 (http) with context path ''
[m03 Oct 2021 09:50:31,379 [main] [37mINFO [m de.captaingoldfish.restclient.application.OAuth2RestClient (StartupInfoLogger.java:61) - [37mStarted OAuth2RestClient in 44.664 seconds (JVM running for 49.864)
[m03 Oct 2021 09:50:31,568 [main] [37mINFO [m de.captaingoldfish.restclient.application.OAuth2RestClient (OAuth2RestClient.java:41) - [37m
              __             __           __
        _____/ /_____ ______/ /____  ____/ /
       / ___/ __/ __ `/ ___/ __/ _ \/ __  /
      (__  ) /_/ /_/ / /  / /_/  __/ /_/ /
     /____/\__/\__,_/_/   \__/\___/\__,_/___      ____
   _______  _______________  __________/ __/_  __/ / /_  __
  / ___/ / / / ___/ ___/ _ \/ ___/ ___/ /_/ / / / / / / / /
 (__  ) /_/ / /__/ /__/  __(__  |__  ) __/ /_/ / / / /_/ /
/____/\__,_/\___/\___/\___/____/____/_/  \__,_/_/_/\__, /
                                                  /____/


[m03 Oct 2021 09:50:53,868 [http-nio-8080-exec-1] [37mINFO [m org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] (DirectJDKLog.java:173) - [37mInitializing Spring DispatcherServlet 'dispatcherServlet'
[m03 Oct 2021 09:50:53,872 [http-nio-8080-exec-1] [37mINFO [m org.springframework.web.servlet.DispatcherServlet (FrameworkServlet.java:525) - [37mInitializing Servlet 'dispatcherServlet'
[m03 Oct 2021 09:50:53,906 [http-nio-8080-exec-1] [37mINFO [m org.springframework.web.servlet.DispatcherServlet (FrameworkServlet.java:547) - [37mCompleted initialization in 9 ms
[m
```

Accessing http://localhost:8080 works fine as I described above.

Unfortunately, a sample that reproduces the problem or a detailed analysis of the failure, I don't think we're going to be able to help you.

**Comment by Captain-P-Goldfish** [comment]
> I'm not sure what gave you the impression I had used an IDE

In my eyes that was the only logical conclusion since I have not a single system that does not reproduce this problem. I am going to ask some more colleagues to test it for me. Maybe someone will have a good idea :-)

**Comment by Captain-P-Goldfish** [comment]
We tried it on some other machines now... Its getting weird... It works on some machines and on some it does not... seems to be a problem with some windows settings?
In this case I do not think that's an issue for you. But thanks for trying :-)

**Comment by wilkinsona** [comment]
Thanks for letting us know.
