### ISSUE TITLE
Getting a bootstrap error on adoptopenjdk/openjdk8:alpine after migrating to 2.5.5

### ISSUE THREAD

**Issue by nightswimmings** [spring-projects/spring-boot#28374]
After migrating from Spring Boot 2.3 to 2.5, I am getting an error when running the fatjar of the app as packaged by JKube on a docker image with image base adoptopenjdk/openjdk8:alpine. The whole strack is pure Boot's bootstrap, no domain classes anywhere, and the whole logging when the image is run consists on:

```
Exception in thread "main" java.time.DateTimeException: Invalid value for MonthOfYear (valid values 1 - 12): 0
	(...)
	at java.time.LocalDateTime.of(LocalDateTime.java:336)
        at org.springframework.boot.loader.jar.CentralDirectoryFileHeader.decodeMsDosFormatDateTime(CentralDirectoryFileHeader.java:130)
	 (...)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
```

I am surprised because this seems like an old fixed bug: https://github.com/spring-projects/spring-boot/issues/19518. Might it be a regression?

**Comment by scottfrederick** [comment]
Thanks for validating the problem @nightswimmings.
