### ISSUE TITLE
Name clash when using Spring Data REST and a class named Config

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#2852]
##### Application.java

```java
import org.springframework.boot.SpringApplication;

public class Application {

	public static void main(String[] args) throws Exception {
		SpringApplication.run(Config.class, args);
	}

}
```

##### Config.java

```java
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Config {

}
```

##### Failure with 1.2.3.RELEASE
```
Caused by: java.lang.ClassCastException: sample.data.jpa.Config$$EnhancerBySpringCGLIB$$4239d784 cannot be cast to org.springframework.data.rest.core.config.RepositoryRestConfiguration
	at org.springframework.boot.autoconfigure.data.rest.SpringBootRepositoryRestMvcConfiguration$$EnhancerBySpringCGLIB$$f355098a.config(<generated>)
	at org.springframework.data.rest.webmvc.config.RepositoryRestMvcConfiguration.resourceMappings(RepositoryRestMvcConfiguration.java:516)
	at org.springframework.boot.autoconfigure.data.rest.SpringBootRepositoryRestMvcConfiguration$$EnhancerBySpringCGLIB$$f355098a.CGLIB$resourceMappings$4(<generated>)
	at org.springframework.boot.autoconfigure.data.rest.SpringBootRepositoryRestMvcConfiguration$$EnhancerBySpringCGLIB$$f355098a$$FastClassBySpringCGLIB$$98e5de9d.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:309)
	at org.springframework.boot.autoconfigure.data.rest.SpringBootRepositoryRestMvcConfiguration$$EnhancerBySpringCGLIB$$f355098a.resourceMappings(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 107 more
```

Question on Stackoverflow: http://stackoverflow.com/questions/29744481/spring-data-rest-boot-app-fails-to-start-with-java-config-class/29748100#29748100

**Comment by wilkinsona** [comment]
The `config` method produces a bean with a very generic name. IMO, that method would be better named something like `repositoryRestConfiguration`. /cc @olivergierke

**Comment by wilkinsona** [comment]
I've opened [DATAREST-540](https://jira.spring.io/browse/DATAREST-540) to track the proposed change to the name of the `RepositoryRestConfiguration` bean. I'm closing this issue as there's nothing we can do in Spring Boot to address the problem and we'll pick up the change in Spring Data REST in due course.
