### ISSUE TITLE
Error after sending 'kill -s term' to spring boot application

### ISSUE THREAD

**Issue by firov** [spring-projects/spring-boot#2875]
This error occurs frequently on application shutdown by kill -s term
stack trace:
        
    Exception in thread "Resource Destroyer in BasicResourcePool.close()" java.lang.NoClassDefFoundError: com/mchange/v2/resourcepool/BasicResourcePool$1DestroyResourceTask
            at com.mchange.v2.resourcepool.BasicResourcePool.destroyResource(BasicResourcePool.java:1040)
            at com.mchange.v2.resourcepool.BasicResourcePool.destroyResource(BasicResourcePool.java:1010)
            at com.mchange.v2.resourcepool.BasicResourcePool.access$100(BasicResourcePool.java:44)
            at com.mchange.v2.resourcepool.BasicResourcePool$5.run(BasicResourcePool.java:1260)
    Caused by: java.lang.ClassNotFoundException: com.mchange.v2.resourcepool.BasicResourcePool$1DestroyResourceTask
            at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
            at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
            at java.security.AccessController.doPrivileged(Native Method)
            at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
            at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:170)
            at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:136)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
            ... 4 more
    Caused by: java.util.zip.ZipException: invalid code lengths set
            at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
            at org.springframework.boot.loader.jar.ZipInflaterInputStream.read(ZipInflaterInputStream.java:52)
            at sun.misc.Resource.getBytes(Resource.java:124)
            at java.net.URLClassLoader.defineClass(URLClassLoader.java:450)
            at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
            at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
            ... 11 more
    Exception in thread "Thread-2" java.lang.NoClassDefFoundError: org/apache/tomcat/util/ExceptionUtils
            at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:234)
            at org.apache.catalina.startup.Tomcat.stop(Tomcat.java:349)
            at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.stop(TomcatEmbeddedServletContainer.java:245)
            at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.stopAndReleaseEmbeddedServletContainer(EmbeddedWebApplicationContext.java:277)
            at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.doClose(EmbeddedWebApplicationContext.java:142)
            at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:804)

**Comment by wilkinsona** [comment]
Can you share a sample project that illustrates the problem please?

**Comment by firov** [comment]
I try on simplified project but didn't succeed. I think this problem may be the result of changing class path:

    <plugin>
        <artifactId>maven-jar-plugin</artifactId>
        <version>2.5</version>
        <configuration>
            <archive>
                <manifestEntries>
                    <Class-Path>config/</Class-Path>
                </manifestEntries>
            </archive>
        </configuration>
    </plugin>

**Comment by firov** [comment]
The problem was in alternative class-path, with default one everything works fine.

**Comment by firov** [comment]
Problem is not in class-path

**Comment by Ivanenok** [comment]
I have a similar problem. i catch exception like it after replacing application jar "on-the-fly" while application works. I try shutdown application and get this exception than. looks like problem in loader which lost handle to original jar.

i will try reproduce in simple project.

``` java
2015-09-02 23:46:27.052  INFO [Thread-8] --- o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 2147483647
2015-09-02 23:46:27.057  WARN [Thread-8] --- o.s.c.support.DefaultLifecycleProcessor  : Failed to stop bean 'agentLifeCycles'
java.lang.NoClassDefFoundError: org/springframework/context/support/DefaultLifecycleProcessor$1
        at org.springframework.context.support.DefaultLifecycleProcessor.doStop(DefaultLifecycleProcessor.java:229)
        at org.springframework.context.support.DefaultLifecycleProcessor.access$300(DefaultLifecycleProcessor.java:51)
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.stop(DefaultLifecycleProcessor.java:363)
        at org.springframework.context.support.DefaultLifecycleProcessor.stopBeans(DefaultLifecycleProcessor.java:202)
        at org.springframework.context.support.DefaultLifecycleProcessor.onClose(DefaultLifecycleProcessor.java:118)
        at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:877)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.doClose(EmbeddedWebApplicationContext.java:150)
        at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:804)
Caused by: java.lang.ClassNotFoundException: org.springframework.context.support.DefaultLifecycleProcessor$1
        at java.net.URLClassLoader$1.run(URLClassLoader.java:370)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:170)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:136)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 8 common frames omitted
Caused by: java.util.zip.ZipException: invalid code lengths set
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
        at org.springframework.boot.loader.jar.ZipInflaterInputStream.read(ZipInflaterInputStream.java:52)
        at sun.misc.Resource.getBytes(Resource.java:124)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:462)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        ... 15 common frames omitted
```

**Comment by wilkinsona** [comment]
@Ivanenok I'm not surprised to hear that caused a failure. I doubt that we'll ever support replacing the application's jar while it's running. If you want hot reloading support, you should look at the dev tools which are new in 1.3 or something like JRebel.
