### ISSUE TITLE
Liquibase and jetty compatibility

### ISSUE THREAD

**Issue by triberraar** [spring-projects/spring-boot#2878]
When i use liquibase and tomcat everything works smoothly. However when i switch to Jetty by modifying my pom as follows:

    <dependency>
	 <groupId>org.springframework.boot</groupId>
	 <artifactId>spring-boot-starter-web</artifactId>
	 <exclusions>
		<exclusion>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
		</exclusion>
	 </exclusions>
    </dependency>
    <dependency>
	 <groupId>org.springframework.boot</groupId>
	 <artifactId>spring-boot-starter-jetty</artifactId>
    </dependency>

I get an exception while liquibase runs:

    java.io.FileNotFoundException: ServletContext resource [/] cannot be resolved to URL because it does not exist
    	at org.springframework.web.context.support.ServletContextResource.getURL(ServletContextResource.java:156)
	    at liquibase.integration.spring.SpringLiquibase$SpringResourceOpener.init(SpringLiquibase.java:77)
    	at liquibase.resource.AbstractResourceAccessor.<init>(AbstractResourceAccessor.java:22)
	    at liquibase.resource.ClassLoaderResourceAccessor.<init>(ClassLoaderResourceAccessor.java:18)
    	at liquibase.integration.spring.SpringLiquibase$SpringResourceOpener.<init>(SpringLiquibase.java:67)
	    at liquibase.integration.spring.SpringLiquibase.createResourceOpener(SpringLiquibase.java:396)
    	at liquibase.integration.spring.SpringLiquibase.createLiquibase(SpringLiquibase.java:357)
	    at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:315)
    	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1633)
	    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
    	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
	    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
    	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
    	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
    	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:293)
	    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
    	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:956)
	    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:747)
    	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
    	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
	    at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
    	at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
	    at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
    	at be.tribersoft.triber_fund.Application.main(Application.java:10)

The execution of the liquibase scripts is succesful however.

**Comment by wilkinsona** [comment]
There's some similarity to #2654, but this is when running an application rather than its tests.

Adding an empty `src/main/webapp` folder silences the error when running in an IDE are via `mvn spring-boot:run`. It doesn't help with an executable archive, though, unless you run it from the folder that contains `src/main/webapp`, i.e. Jetty seems to look outside the archive for the folder:

    java -jar target/spring-boot-sample-liquibase-1.2.3.RELEASE.jar
    …
    2015-04-27 09:34:35.670  INFO 8022 --- [           main] o.e.jetty.server.handler.ContextHandler  : Started o.s.b.c.e.j.JettyEmbeddedWebAppContext@7e49550d{/,file:/Users/awilkinson/dev/spring/spring-boot/spring-boot-samples/spring-boot-sample-liquibase/src/main/webapp/,AVAILABLE}

**Comment by cmuchinsky** [comment]
This issue appears to affect Undertow as well as Jetty
