### ISSUE TITLE
banner.charset value cannot be converted

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#2889]
Try to set both `banner.charset` and `banner.location` and you'll get this

```
2015-04-27 10:25:49.866  WARN 90717 --- [           main] org.springframework.boot.ResourceBanner  : Banner not printable: class path resource [static/my-banner.txt] (class java.lang.IllegalArgumentException: 'Cannot convert value [UTF-8] from source type [String] to target type [Charset]')

java.lang.IllegalArgumentException: Cannot convert value [UTF-8] from source type [String] to target type [Charset]
	at org.springframework.core.env.PropertySourcesPropertyResolver.getProperty(PropertySourcesPropertyResolver.java:94)
	at org.springframework.core.env.PropertySourcesPropertyResolver.getProperty(PropertySourcesPropertyResolver.java:65)
	at org.springframework.core.env.AbstractPropertyResolver.getProperty(AbstractPropertyResolver.java:143)
	at org.springframework.core.env.AbstractEnvironment.getProperty(AbstractEnvironment.java:526)
	at org.springframework.boot.ResourceBanner.printBanner(ResourceBanner.java:58)
	at org.springframework.boot.SpringApplication.printBanner(SpringApplication.java:479)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:288)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
	at demo.DemoApplication.main(DemoApplication.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by snicoll** [comment]
This is weird, we don't seem to have such feature in the core and I couldn't find a trace of that anywhere else. Inspecting on a property of type `Charset` I can see that the related `ConversionService` has a `NO_MATCH` cache for the pair `String` to `Charset`. Yet, the injected value is the expected one so something else should convert that but I have no idea what. 

ping @jhoeller

**Comment by snicoll** [comment]
I locally added a `Charset` converter in https://github.com/snicoll/spring-framework/commit/1086ee78268cfa38e6c80a0f3e5e15141ccb2f3d and that did the trick. @jhoeller any idea why we don't have such converter? I am considering adding that for 4.2.

**Comment by joshthornhill** [comment]
For what it's worth, there is a CharsetEditor in spring-beans. The banner.* props are not being set on an object so they didn't leverage that. 
Also the docs reference "banner.encoding" whereas the code uses "banner.charset". I would be happy to fix that. Though I personally think it's a little awkward that the show-banner property is under spring.main, but the other 2 banner configurations are not. There may be a very good reason though.

**Comment by snicoll** [comment]
Good catch and that's why it does work when binding the value since that editor is used for the conversion. I am still unsure what to do regarding the converter but should hear back from @jhoeller this week.

As for the properties, I'll fix the doc. `spring.main` corresponds to the properties that are available on the `SpringApplication` class. I find it weird to integrate those two properties in there. On the other hand, create a root namespace for that thing is weird but that's my own personal opinion. Some team members like short property names and we didn't really make up on mind on that stuff.

Thanks!

**Comment by snicoll** [comment]
This has actually been fixed in the framework itself (see https://github.com/spring-projects/spring-framework/commit/0612bc7bc5a82ff7414d8c8bcf665599d23a5225). A `Charset` converter is now available by default.
