### ISSUE TITLE
Main application class is deduced incorrectly in tests launched by SpringApplicationContextLoader

### ISSUE THREAD

**Issue by MeLoco1** [spring-projects/spring-boot#2930]
According to [Spring Boot's reference guide](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#boot-features-banner) , a custom banner.txt should support the ${application.version} and ${application.formatted-version} placeholders. 

In my app I use ${application.formatted-version} and it shows v2.17.

My app version is 0.0.1 and here is my MANIFEST.MF:
Manifest-Version: 1.0
Implementation-Title: server
Implementation-Version: 0.0.1
.....

Seems like ${application.formatted-version} is taken from surefire-booter. 

2015-05-10 22:04:37.206  INFO 6555 --- [           main] o.a.maven.surefire.booter.ForkedBooter   : Starting ForkedBooter v2.17 on Locos-MacBook-Pro.local with PID 6555 (/Users/Loco/.m2/repository/org/apache/maven/surefire/surefire-booter/2.17/surefire-booter-2.17.jar started by Loco ..............
At least this only I found with v2.17.
The same problem with ${application.version}

My Spring boot version: 1.2.3.RELEASE

**Comment by wilkinsona** [comment]
The culprit is `SpringApplication.deduceMainApplicationClass`:

```
private Class<?> deduceMainApplicationClass() {
	try {
		StackTraceElement[] stackTrace = new RuntimeException().getStackTrace();
		for (StackTraceElement stackTraceElement : stackTrace) {
			if ("main".equals(stackTraceElement.getMethodName())) {
				return Class.forName(stackTraceElement.getClassName());
			}
		}
	}
	catch (ClassNotFoundException ex) {
		// Swallow and continue
	}
	return null;
}
```

When tests are being run with Surefire, the only method in the stack called `main` is that of `ForkedBooter`:

```
java.lang.RuntimeException
	at demo.Gh2930ApplicationTests.contextLoads(Gh2930ApplicationTests.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:73)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:82)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:73)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:224)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:83)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:68)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:163)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

In addition to the version number problem described above, there are also another couple of log messages that are "wrong":

```
2015-05-11 15:16:50.807  INFO 14977 --- [           main] o.a.maven.surefire.booter.ForkedBooter   : Starting ForkedBooter v2.17 on aw-rmbp.local with PID 14977 (/Users/awilkinson/.m2/repository/org/apache/maven/surefire/surefire-booter/2.17/surefire-booter-2.17.jar started by awilkinson in /Users/awilkinson/dev/workspaces/spring/spring-boot/gh-2930)
…
2015-05-11 15:16:51.120  INFO 14977 --- [           main] o.a.maven.surefire.booter.ForkedBooter   : Started ForkedBooter in 0.469 seconds (JVM running for 0.869)
```

Something similar happens when running tests in STS:

```
2015-05-11 15:21:31.159  INFO 14994 --- [           main] o.e.j.i.junit.runner.RemoteTestRunner    : Starting RemoteTestRunner on aw-rmbp.local with PID 14994 (/Applications/sts-3.6.0.RELEASE/configuration/org.eclipse.osgi/406/0/.cp started by awilkinson in /Users/awilkinson/dev/workspaces/spring/spring-boot/gh-2930)
…
2015-05-11 15:21:31.477  INFO 14994 --- [           main] o.e.j.i.junit.runner.RemoteTestRunner    : Started RemoteTestRunner in 0.463 seconds (JVM running for 0.865)
```

Setting the main application class when tests are being run via `SpringApplicationContextLoader` will correct the log messages, for example:

```
2015-05-11 15:27:49.304  INFO 15060 --- [           main] demo.Gh2930ApplicationTests              : Starting Gh2930ApplicationTests on aw-rmbp.local with PID 15060 (/Users/awilkinson/dev/workspaces/spring/spring-boot/gh-2930/target/test-classes started by awilkinson in /Users/awilkinson/dev/workspaces/spring/spring-boot/gh-2930)
…
2015-05-11 15:27:49.641  INFO 15060 --- [           main] demo.Gh2930ApplicationTests              : Started Gh2930ApplicationTests in 0.499 seconds (JVM running for 0.951)
```
