### ISSUE TITLE
 ErrorPageSecurityFilter cannot be destroyed in a Servlet 3.1 compatible container

### ISSUE THREAD

**Issue by lesnydar** [spring-projects/spring-boot#29558]
It seems connected to #28790 .

Regarding Spring Boot 2.6.2
Weblogic 12.2.1.4 is not Servlet 4.0 compatible

```
####<2022-01-25 09:35:41,918 CET> <Error> <HTTP> <GR4-0015186> <AdminServer> <[STANDBY] ExecuteThread: '8' for queue: 'weblogic.kernel.Default (self-tuning)'> <<WLS Kernel>> <> <5e86cbed-995a-4000-83cd-cd235d222fb3-00000015> <1643099741918> <[severity-value: 8] [rid: 0] [partition-id: 0] [partition-name: DOMAIN] > <BEA-101267> <Failed while destroying filter: errorPageSecurityFilter.
java.lang.AbstractMethodError
	at weblogic.servlet.internal.FilterManager$FilterDestroyAction.run(FilterManager.java:416)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:344)
	at weblogic.security.service.SecurityManager.runAsForUserCode(SecurityManager.java:197)
	at weblogic.servlet.provider.WlsSecurityProvider.runAsForUserCode(WlsSecurityProvider.java:203)
	at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:71)
	at weblogic.servlet.internal.FilterManager.destroyFilter(FilterManager.java:378)
	at weblogic.servlet.internal.FilterManager.destroyFilter(FilterManager.java:368)
	at weblogic.servlet.internal.FilterManager.destroyFilters(FilterManager.java:342)
	at weblogic.servlet.internal.WebAppServletContext.destroy(WebAppServletContext.java:3259)
	at weblogic.servlet.internal.ServletContextManager.destroyContext(ServletContextManager.java:251)
	at weblogic.servlet.internal.HttpServer.unloadWebApp(HttpServer.java:693)
	at weblogic.servlet.internal.WebAppModule.destroyContexts(WebAppModule.java:1897)
	at weblogic.servlet.internal.WebAppModule.deactivate(WebAppModule.java:946)
	at weblogic.application.internal.ExtensibleModuleWrapper$ActivateStateChange.previous(ExtensibleModuleWrapper.java:328)
	at weblogic.application.internal.ExtensibleModuleWrapper$ActivateStateChange.previous(ExtensibleModuleWrapper.java:313)
	at weblogic.application.utils.StateMachineDriver.previousState(StateMachineDriver.java:207)
	at weblogic.application.utils.StateMachineDriver.previousState(StateMachineDriver.java:193)
	at weblogic.application.internal.ExtensibleModuleWrapper.deactivate(ExtensibleModuleWrapper.java:163)
	at weblogic.application.internal.flow.ModuleListenerInvoker.deactivate(ModuleListenerInvoker.java:131)
	at weblogic.application.internal.flow.ModuleStateDriver$2.previous(ModuleStateDriver.java:216)
	at weblogic.application.internal.flow.ModuleStateDriver$2.previous(ModuleStateDriver.java:207)
	at weblogic.application.utils.StateMachineDriver.previousState(StateMachineDriver.java:207)
	at weblogic.application.utils.StateMachineDriver.previousState(StateMachineDriver.java:193)
	at weblogic.application.internal.flow.ModuleStateDriver.deactivate(ModuleStateDriver.java:101)
	at weblogic.application.internal.flow.DeploymentCallbackFlow.deactivate(DeploymentCallbackFlow.java:120)
	at weblogic.application.internal.BaseDeployment$2.previous(BaseDeployment.java:758)
	at weblogic.application.utils.StateMachineDriver.previousState(StateMachineDriver.java:207)
	at weblogic.application.utils.StateMachineDriver.previousState(StateMachineDriver.java:193)
	at weblogic.application.internal.BaseDeployment.deactivate(BaseDeployment.java:285)
	at weblogic.application.internal.SingleModuleDeployment.deactivate(SingleModuleDeployment.java:52)
	at weblogic.application.internal.DeploymentStateChecker.deactivate(DeploymentStateChecker.java:202)
	at weblogic.deploy.internal.targetserver.AppContainerInvoker.deactivate(AppContainerInvoker.java:114)
	at weblogic.deploy.internal.targetserver.operations.AbstractOperation.silentDeactivate(AbstractOperation.java:743)
	at weblogic.deploy.internal.targetserver.operations.RedeployOperation.unprepareDeployment(RedeployOperation.java:222)
	at weblogic.deploy.internal.targetserver.operations.RedeployOperation.doPrepare(RedeployOperation.java:130)
	at weblogic.deploy.internal.targetserver.operations.AbstractOperation.prepare(AbstractOperation.java:242)
	at weblogic.deploy.internal.targetserver.DeploymentManager.handleDeploymentPrepare(DeploymentManager.java:800)
	at weblogic.deploy.internal.targetserver.DeploymentManager.prepareDeploymentList(DeploymentManager.java:1352)
	at weblogic.deploy.internal.targetserver.DeploymentManager.handlePrepare(DeploymentManager.java:270)
	at weblogic.deploy.internal.targetserver.DeploymentServiceDispatcher.prepare(DeploymentServiceDispatcher.java:177)
	at weblogic.deploy.service.internal.targetserver.DeploymentReceiverCallbackDeliverer.doPrepareCallback(DeploymentReceiverCallbackDeliverer.java:186)
	at weblogic.deploy.service.internal.targetserver.DeploymentReceiverCallbackDeliverer.access$000(DeploymentReceiverCallbackDeliverer.java:14)
	at weblogic.deploy.service.internal.targetserver.DeploymentReceiverCallbackDeliverer$1.run(DeploymentReceiverCallbackDeliverer.java:47)
	at weblogic.work.SelfTuningWorkManagerImpl$WorkAdapterImpl.run(SelfTuningWorkManagerImpl.java:681)
	at weblogic.invocation.ComponentInvocationContextManager._runAs(ComponentInvocationContextManager.java:352)
	at weblogic.invocation.ComponentInvocationContextManager.runAs(ComponentInvocationContextManager.java:337)
	at weblogic.work.LivePartitionUtility.doRunWorkUnderContext(LivePartitionUtility.java:57)
	at weblogic.work.PartitionUtility.runWorkUnderContext(PartitionUtility.java:41)
	at weblogic.work.SelfTuningWorkManagerImpl.runWorkUnderContext(SelfTuningWorkManagerImpl.java:655)
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:420)
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:360)
```

**Comment by philwebb** [comment]
Thanks. It looks like we missed `destroy`. I've added the method and also put in a test.

**Comment by lesnydar** [comment]
> Thanks. It looks like we missed `destroy`. I've added the method and also put in a test.

Thank you.
Regards, 
Darek
