### ISSUE TITLE
MongoProperties uri  and host/port validation conflicts (again) with EmbeddedMongoAutoConfiguration when having uri set

### ISSUE THREAD

**Issue by okrische** [spring-projects/spring-boot#29886]
Using spring-boot-autoconfigure 2.6.3

In my application.properties i have this uri as a convenient default:

``spring.data.mongodb.uri = mongodb://127.0.0.1:27017/${spring.application.name}``

My test class looks like this:

```
@ExtendWith(SpringExtension.class)
@SpringBootTest(classes = {Application.class, EmbeddedMongoAutoConfiguration.class},
        webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT,
        properties = {"spring.data.mongodb.port=0", "spring.mongodb.embedded.version=3.6.5"})
@ActiveProfiles({"testing"})
public class ApiTest {
    ...
}
```

When starting up, i get the exception:

```
Caused by: java.lang.IllegalStateException: Invalid mongo configuration, either uri or host/port/credentials/replicaSet must be specified
	at org.springframework.util.Assert.state(Assert.java:76)
	at org.springframework.boot.autoconfigure.mongo.MongoPropertiesClientSettingsBuilderCustomizer.validateConfiguration(MongoPropertiesClientSettingsBuilderCustomizer.java:61)
	at org.springframework.boot.autoconfigure.mongo.MongoPropertiesClientSettingsBuilderCustomizer.customize(MongoPropertiesClientSettingsBuilderCustomizer.java:52)
	at org.springframework.boot.autoconfigure.mongo.MongoClientFactorySupport.customize(MongoClientFactorySupport.java:55)
	at org.springframework.boot.autoconfigure.mongo.MongoClientFactorySupport.createMongoClient(MongoClientFactorySupport.java:49)
	at org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration.mongo(MongoAutoConfiguration.java:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 192 more
```

When i remove the default uri from default application.properties, then the test just works fine.

However, my expectation is, that when an embedded mongo database is used, then the client should be setup to connect to the embedded database, ignoring the uri.

Technically, when looking at the code, the MongoPropertiesClientSettingsBuilderCustomizer just needs to ignore the uri, when it calls validateConfiguration(), when the embedded port is set.

It does already so, when it later calls applyHostAndPort(), where it overrides the uri with a new one, so that the client connects to the embedded database.

I think this is a regression from #8219 that originated from #6739

Thank you.

**Comment by wilkinsona** [comment]
Embedded Mongo will allocate an ephemeral port by default so there's no need to set `spring.data.mongodb.port` to `0`. As far as I can tell, you will get the behaviour that you want if you remove this property from your test. Can you please give that a try and let us know how it goes?
