### ISSUE TITLE
Micrometer new relic correct dependency is "difficult" to use.

### ISSUE THREAD

**Issue by mshukry11** [spring-projects/spring-boot#29908]
Currently there are 2 implementations for micrometer new relic:
1. `io.micrometer:micrometer-registry-new-relic`
2. `com.newrelic.telemetrymicrometer-registry-new-relic'

According to the repo of the 2nd implementation site (which is by newrelic): https://github.com/newrelic/micrometer-registry-newrelic, that is the version one should use, as it will supersede the 1st implementation

```Note: the micrometer project currently includes a NewRelicMeterRegistry that writes metrics to NewRelic as custom events. This implementation is intended to supersede that, as [dimensional metrics](https://docs.newrelic.com/docs/using-new-relic/data/understand-data/new-relic-data-types#dimensional-metrics) are a better fit for micrometer metrics than custom [events](https://docs.newrelic.com/docs/using-new-relic/data/understand-data/new-relic-data-types#events-new-relic).``

However currently spring uses the 1st implementation.

If one wants to use spring boot (specifically actuator autoconfigur) together with the 2nd (and "correct") implementation of newrelic, they have to:
1. Still add the 1st implementation dependency since Spring boot actuator autoconfigure will not compile without it, but add it with `compileOnly`.
2. Add the 2nd implementation as well, using `implementation`.
3. Create a new NewrelicProperties config which will not have any dependency on the 1st implementation (e.g. `ClientProviderType`)
4. Create a `NewRelicConfiguration` class for bean configs. This might be needed anyway.

**Comment by wilkinsona** [comment]
Thanks for the report. Unfortunately I'm a bit confused by the steps that you have described. If you want to use `com.newrelic.telemetrymicrometer-registry-new-relic` with Spring Boot, there should be any need to compile Spring Boot's code. The only step that should be necessary is to define your own `NewRelicRegistry` bean that's configured to meet your needs. Can you please clarify?

**Comment by mshukry11** [comment]
@wilkinsona compile wasn't the right word. When trying to run without that dependency:

```
Caused by: java.lang.IllegalStateException: Failed to introspect Class [org.springframework.boot.actuate.autoconfigure.metrics.export.newrelic.NewRelicProperties] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@77556fd]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:481) ~[spring-core-5.3.15.jar:5.3.15]
	at org.springframework.util.ReflectionUtils.doWithLocalMethods(ReflectionUtils.java:321) ~[spring-core-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:267) ~[spring-beans-5.3.15.jar:5.3.15]
	... 113 common frames omitted
Caused by: java.lang.NoClassDefFoundError: io/micrometer/newrelic/ClientProviderType
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[na:na]
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166) ~[na:na]
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2309) ~[na:na]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:463) ~[spring-core-5.3.15.jar:5.3.15]
	... 115 common frames omitted
Caused by: java.lang.ClassNotFoundException: io.micrometer.newrelic.ClientProviderType
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[na:na]
	... 119 common frames omitted
```

**Comment by mshukry11** [comment]
@wilkinsona you are correct about that part, I apologize.
Updated the description accordingly.

Note I also added what are the most "painful" parts for me, which is using a different prefix.
We work with multiple services, some which still uses the "old" versions where spring boot configuration doesn't strictly depends on the 1st implementation, and as part of our infrastructure we have config for `management.metrics.export.newrelic` prefix (not in any specific app, but for all of them).

Now for newer apps, we need to use a different prefix.

**Comment by wilkinsona** [comment]
Thanks for the clarification. While I believe the plan is for Micrometer's NewRelic registry to be replaced by NewRelic's own that isn't a straightforward transition. Until such a time as NewRelic's implementation is, functionality wise, a drop-in replacement and Micrometer's implementation is then deprecated, I don't think we can do anything here. Spring Boot supporting both would not achieve what you want as the two have different configuration options so Boot would end up with different property prefixes.

@shakuzen please let me know if I've missed anything here or things have moved on since the discussion in https://github.com/newrelic/micrometer-registry-newrelic/issues/46.

**Comment by shakuzen** [comment]
Since that discussion, New Relic Insights (the API/system used by the implementation in the Micrometer repo) has been deprecated (see https://github.com/micrometer-metrics/micrometer/issues/3033), which hopefully means the transition from Insights has been made as smooth as possible by now on the New Relic side and us deprecating the registry in Micrometer does not cause too much disruption for users. We'd like to get feedback from users about anything we can do in Micrometer to help switching. Spring Boot users can follow https://github.com/micrometer-metrics/micrometer/issues/3033 for updates on the registry in the Micrometer repository and provide that feedback.

**Comment by wilkinsona** [comment]
Thanks, @shakuzen. I've subscribed to #3033.

If necessary, we can re-open this issue or open a new issue once the direction for the New Relic registry is finalized.
