### ISSUE TITLE
UnsupportedOperationException with jetty 10.0.8

### ISSUE THREAD

**Issue by aesthetics** [spring-projects/spring-boot#29988]
Hello,

We are using spring boot 2.6.3 and after updating from jetty 10.0.7 to 10.0.8 the following error appears at the startup of the application:

```
org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is java.lang.UnsupportedOperationException
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:163)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:577)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:414)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
	at custom.CustomApplication.main(CustomApplication.java:10)
Caused by: java.lang.UnsupportedOperationException: null
	at java.base/java.util.Collections$UnmodifiableCollection.clear(Collections.java:1079)
	at org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory.configureWebAppContext(JettyServletWebServerFactory.java:235)
	at org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory.getWebServer(JettyServletWebServerFactory.java:164)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:182)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:160)
	... 8 common frames omitted
```

The dependency used for jetty is the following:

```
 <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jetty</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.eclipse.jetty.websocket</groupId>
                    <artifactId>websocket-server</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.eclipse.jetty.websocket</groupId>
                    <artifactId>javax-websocket-server-impl</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

Thanks

**Comment by wilkinsona** [comment]
Duplicates https://github.com/spring-projects/spring-boot/pull/29555 and https://github.com/spring-projects/spring-boot/issues/29556.
