### ISSUE TITLE
UnsupportedOperationException from JettyServletWebServerFactory when using Jetty 10.0.8

### ISSUE THREAD

**Issue by markrmiller** [spring-projects/spring-boot#30024]
Sorry if this is being tracked elsewhere, I did some digging and could not find anything related.

I've recently tried upgrading to the Jetty 10.0.8 release for a bug fix and regardless of spring-boot version, I see the following exception at runtime:

```
  java.lang.UnsupportedOperationException
            at java.base/java.util.Collections$UnmodifiableCollection.clear(Collections.java:1086)
            at org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory.configureWebAppContext(JettyServletWebServerFactory.java:221)
            at org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory.getWebServer(JettyServletWebServerFactory.java:153)
            at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:182)
            at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:160)
            ... 32 more

```

The fix I'm looking for relates to the alias functionality coincidentally, and it seems this call is no longer working: https://github.com/spring-projects/spring-boot/blob/89b2015adf4e46b4437d9591e7222ca378554138/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/embedded/jetty/JettyServletWebServerFactory.java#L233

**Comment by scottfrederick** [comment]
This appears to be a duplicate of #29555 and #29556. 

> regardless of spring-boot version, I see the following exception at runtime:

@markrmiller Can you confirm that you see the exception with Spring Boot `2.5.10` or `2.6.4`? If so, provide a complete minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it and attaching it to this issue.

**Comment by markrmiller** [comment]
Looking into and will report back shortly.

**Comment by markrmiller** [comment]
Yup, sorry, my fault. We have a kind of a complicated gradle versioning system that pulls this in via an adobe s3 mock project and my attempts to force the feb 22 release versions of spring-boot were, in the end, doing some surprising things in terms of what versions actually ended up getting pulled in. This issue is resolved for Solr with the release versions mentioned above.
