### ISSUE TITLE
Embedded Tomcat errors on launch after upgrading from 1.0.1.RELEASE to 1.1.12.RELEASE

### ISSUE THREAD

**Issue by naymesh** [spring-projects/spring-boot#3049]
I have been developing with spring-boot 1.0.1.RELEASE for a while. Thought it would be a good idea to upgrade to the latest 1.x version so just bumped the dependency to 1.1.12.RELEASE.

With this, I get an error on startup:

```


  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::       (v1.1.12.RELEASE)

14:48:22.010 [main] INFO  org.ibp.Main.logStarting (54) - Starting Main on Naymeshs-MacBook-Pro.local with PID 21854 (/Users/naymesh/src/gcp/BMSAPI/target/classes started by naymesh in /Users/naymesh/src/gcp/BMSAPI)
14:48:25.434 [main] INFO  org.apache.catalina.core.StandardService.log (183) - Starting service Tomcat
14:48:25.435 [main] INFO  org.apache.catalina.core.StandardEngine.log (183) - Starting Servlet Engine: Apache Tomcat/7.0.50
14:48:26.844 [localhost-startStop-1] INFO  org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/bmsapi].log (183) - Initializing Spring embedded WebApplicationContext

...
...

14:48:31.415 [main] INFO  org.apache.coyote.http11.Http11NioProtocol.log (183) - Initializing ProtocolHandler ["http-nio-19080"]
14:48:31.429 [main] INFO  org.apache.coyote.http11.Http11NioProtocol.log (183) - Starting ProtocolHandler ["http-nio-19080"]
14:48:31.437 [main] INFO  org.apache.tomcat.util.net.NioSelectorPool.log (183) - Using a shared selector for servlet write/read
14:48:31.497 [main] ERROR org.springframework.boot.SpringApplication.run (338) - Application startup failed
java.lang.NoSuchMethodError: org.apache.catalina.core.StandardContext.loadOnStartup([Lorg/apache/catalina/Container;)Z
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedContext.deferredLoadOnStartup(TomcatEmbeddedContext.java:53) ~[spring-boot-1.1.12.RELEASE.jar:1.1.12.RELEASE]
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.startConnector(TomcatEmbeddedServletContainer.java:204) ~[spring-boot-1.1.12.RELEASE.jar:1.1.12.RELEASE]
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:147) ~[spring-boot-1.1.12.RELEASE.jar:1.1.12.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:272) ~[spring-boot-1.1.12.RELEASE.jar:1.1.12.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:132) ~[spring-boot-1.1.12.RELEASE.jar:1.1.12.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:485) ~[spring-context-4.0.9.RELEASE.jar:4.0.9.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:109) ~[spring-boot-1.1.12.RELEASE.jar:1.1.12.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:691) [spring-boot-1.1.12.RELEASE.jar:1.1.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320) [spring-boot-1.1.12.RELEASE.jar:1.1.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:952) [spring-boot-1.1.12.RELEASE.jar:1.1.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:941) [spring-boot-1.1.12.RELEASE.jar:1.1.12.RELEASE]
	at org.ibp.Main.main(Main.java:35) [classes/:na]
```

Spring related pom.xml excerpts:

```
...
	<properties>
		<spring-boot-version>1.1.12.RELEASE</spring-boot-version>
                ....
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<version>${spring-boot-version}</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-thymeleaf</artifactId>
			<version>${spring-boot-version}</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-jdbc</artifactId>
			<version>${spring-boot-version}</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-mongodb</artifactId>
			<version>${spring-boot-version}</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<version>${spring-boot-version}</version>
			<scope>test</scope>
		</dependency>
               ....
           <dependencies>
```

Seems similar to [#1148](https://github.com/spring-projects/spring-boot/issues/1148) but in my case the embedded tomcat version is 7.0.50. I checked whether the [fix attached to the issue](5d317f2dc7b75f9da692caf536f13bf2971e7dd0) is present in 1.1.12 or not, and it seems it is there.

Thanks in advance for your help!

**Comment by snicoll** [comment]
Spring Boot 1.1.12 is shipped with Tomcat `7.0.59` and you claim to use `7.0.50` so you must have other customizations than what you are showing. Can you try with that tomcat version to see if that resolves the issue? If it doesn't a sample project that reproduces the problem would help because there is nothing wrong with the pom snippet that you have put in your description (but i guess the problem is behind the dots).

**Comment by naymesh** [comment]
Thanks @snicoll and sorry, I _should_ have raised this on StackOverflow. Apologies.

I have no explicit dependency on any tomcat version in my pom.

And you are right, 1.1.12 of boot pulls 7.0.59 of embedded tomcat, checked with mvn dependency hierarchy view:

`$ mvn dependency:tree -Dverbose`

```
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:1.1.12.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:1.1.12.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot:jar:1.1.12.RELEASE:compile
[INFO] |  |  |  +- (org.springframework:spring-core:jar:4.0.9.RELEASE:compile - omitted for duplicate)
[INFO] |  |  |  \- (org.springframework:spring-context:jar:4.0.9.RELEASE:compile - omitted for duplicate)
[INFO] |  |  +- org.springframework.boot:spring-boot-autoconfigure:jar:1.1.12.RELEASE:compile
[INFO] |  |  |  \- (org.springframework.boot:spring-boot:jar:1.1.12.RELEASE:compile - omitted for duplicate)
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:1.1.12.RELEASE:compile
[INFO] |  |  |  +- org.slf4j:jcl-over-slf4j:jar:1.7.10:compile
[INFO] |  |  |  |  \- (org.slf4j:slf4j-api:jar:1.7.11:compile - omitted for conflict with 1.7.7)
[INFO] |  |  |  +- org.slf4j:jul-to-slf4j:jar:1.7.11:compile
[INFO] |  |  |  |  \- (org.slf4j:slf4j-api:jar:1.7.11:compile - omitted for conflict with 1.7.7)
[INFO] |  |  |  +- org.slf4j:log4j-over-slf4j:jar:1.7.11:compile
[INFO] |  |  |  |  \- (org.slf4j:slf4j-api:jar:1.7.11:compile - omitted for conflict with 1.7.7)
[INFO] |  |  |  \- (ch.qos.logback:logback-classic:jar:1.1.3:compile - omitted for conflict with 1.1.2)
[INFO] |  |  +- (org.springframework:spring-core:jar:4.0.9.RELEASE:compile - omitted for duplicate)
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.13:runtime
[INFO] |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:1.1.12.RELEASE:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:7.0.59:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:7.0.59:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-logging-juli:jar:7.0.59:compile
[INFO] |  |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:7.0.59:compile
[INFO] |  |     \- (org.apache.tomcat.embed:tomcat-embed-core:jar:7.0.59:compile - omitted for duplicate)
```

Can't see any tomcat dependency version 7.0.50 in entire dependency tree. All tomcat jars are 7.0.59. Don't know why the startup log still prints 7.0.50.

```
19:06:53.164 [main] INFO  org.apache.catalina.core.StandardService.log (183) - Starting service Tomcat
19:06:53.165 [main] INFO  org.apache.catalina.core.StandardEngine.log (183) - Starting Servlet Engine: Apache Tomcat/7.0.50
```

I will try and reproduce this in a sample project and post the results here.

Thanks again!

**Comment by naymesh** [comment]
@snicoll I will post this on StackOverflow. Please remove the issue. Apologies again.

**Comment by snicoll** [comment]
No need to :) Now it has started, let's finish it here. Post the sample project somewhere and I'll have a look.

**Comment by naymesh** [comment]
@snicoll I finally got to the the root cause. One of my project's internal dependencies (separate Maven project in eclipse workspace) had Tomcat 7.0.50 library on its build class path (explains why tomcat version being printed was 7.0.50 as well). On launching it seems, the tomcat libraries from that other project's class path were taking precedence. Removing the Tomcat library from the other project which the spring-boot project depended on, solved the issue. My sincere apologies again. Please close the issue. Thanks!

**Comment by snicoll** [comment]
No need to apologize.Thanks for the feedback!

**Comment by charmingoh** [comment]
Because **spring-boot-starter-web** depends on **spring-boot-starter-validation**，and **spring-boot-starter-validation** depends on **org.apache.tomcat.embed:tomcat-embed-el:compile**，so you can add below:

```xml
<dependency>
    <groupId>org.apache.tomcat.embed</groupId>
    <artifactId>tomcat-embed-el</artifactId>
    <scope>provided</scope>
</dependency>
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-tomcat</artifactId>
    <scope>provided</scope>
</dependency>
```

then the problem fixed.
