### ISSUE TITLE
Problem reset a metric

### ISSUE THREAD

**Issue by diego522** [spring-projects/spring-boot#3062]
Hi, I'm using a counter service to registry some custom metrics. When I try to reset I have this problem

```
org.springframework.messaging.MessageDeliveryException: Failed to handle GenericMessage [payload=delete, headers={metricName=counter.localcache.no-hit.count, id=6f7ee3c0-21d4-13fc-631a-2daa34ef5108, timestamp=1432822106650}] to org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask@1f33c1da in org.springframework.boot.actuate.metrics.writer.MetricWriterMessageHandler@285b00cf; nested exception is java.lang.ClassCastException: java.lang.String cannot be cast to org.springframework.boot.actuate.metrics.Metric
	at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:144)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to org.springframework.boot.actuate.metrics.Metric
	at org.springframework.boot.actuate.metrics.writer.MetricWriterMessageHandler.handleMessage(MetricWriterMessageHandler.java:46)
	at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:135)
	... 3 more
```

Can't cast the name of the metric to Metric object.

This is my code

```
@Service
public class CustomMetricReset
{

	@Autowired
	private CounterService counterService;

	public void reset()
	{
		counterService.reset("localcache.no-hit.count");
	}
}
```

Cheers!

**Comment by seanhot** [comment]
so ...

**Comment by pandanti** [comment]
Hi,

this issue has been corrected. See this issue : 
https://github.com/spring-projects/spring-boot/issues/3378

**Comment by wilkinsona** [comment]
@pandanti Thanks for testing. Closing in favour of #3378.
