### ISSUE TITLE
Unable to instantiate factory class [org.springframework.cloud.consul.config.ConsulConfigDataLocationResolver] for factory type [org.springframework.boot.context.config.ConfigDataLocationResolver]

### ISSUE THREAD

**Issue by xuxiaowei-com-cn** [spring-projects/spring-boot#31198]
**Describe the bug**
```
"D:\Program Files\dragonwell-17.0.3.0.3+7-GA\bin\java.exe" -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:57498,suspend=y,server=n -XX:TieredStopAtLevel=1 -noverify -Dspring.output.ansi.enabled=always -Dcom.sun.management.jmxremote -Dspring.jmx.enabled=true -Dspring.liveBeansView.mbeanDomain -Dspring.application.admin.enabled=true -javaagent:C:\Users\xuxiaowei\AppData\Local\JetBrains\IntelliJIdea2022.1\captureAgent\debugger-agent.jar=file:/C:/Users/xuxiaowei/AppData/Local/Temp/capture.props -Dfile.encoding=UTF-8 -classpath "D:\IdeaProjects\xuxiaowei-cloud-next\gateway\target\classes;D:\Apache\apache-maven-3.6.3-repo\org\springframework\cloud\spring-cloud-starter-consul-config\4.0.0-M2\spring-cloud-starter-consul-config-4.0.0-M2.jar;D:\Apache\apache-maven-3.6.3-repo\org\springframework\cloud\spring-cloud-starter-consul\4.0.0-M2\spring-cloud-starter-consul-4.0.0-M2.jar;D:\Apache\apache-maven-3.6.3-repo\org\springframework\cloud\spring-cloud-consul-core\4.0.0-M2\spring-cloud-consul-core-4.0.0-M2.jar;D:\Apache\apache-maven-3.6.3-repo\com\ecwid\consul\consul-api\1.4.5\consul-api-1.4.5.jar;D:\Apache\apache-maven-3.6.3-repo\com\google\code\gson\gson\2.9.0\gson-2.9.0.jar;D:\Apache\apache-maven-3.6.3-repo\org\apache\httpcomponents\httpclient\4.5.13\httpclient-4.5.13.jar;D:\Apache\apache-maven-3.6.3-repo\commons-codec\commons-codec\1.15\commons-codec-1.15.jar;D:\Apache\apache-maven-3.6.3-repo\org\apache\httpcomponents\httpcore\4.4.15\httpcore-4.4.15.jar;D:\Apache\apache-maven-3.6.3-repo\org\springframework\cloud\spring-cloud-consul-config\4.0.0-M2\spring-cloud-consul-config-4.0.0-M2.jar;D:\Apache\apache-maven-3.6.3-repo\org\springframework\cloud\spring-cloud-commons\4.0.0-M2\spring-cloud-commons-4.0.0-M2.jar;D:\Apache\apache-maven-3.6.3-repo\org\springframework\security\spring-security-crypto\6.0.0-M5\spring-security-crypto-6.0.0-M5.jar;D:\Apache\apache-maven-3.6.3-repo\org\springframework\cloud\spring-cloud-starter-consul-discovery\4.0.0-M2\spring-cloud-starter-consul-discovery-4.0.0-M2.jar;D:\Apache\apache-maven-3.6.3-repo\org\springframework\cloud\spring-cloud-consul-discovery\4.0.0-M2\spring-cloud-consul-discovery-4.0.0-M2.jar;D:\Apache\apache-maven-3.6.3-repo\org\springframework\cloud\spring-cloud-starter-bootstrap\4.0.0-M2\spring-cloud-starter-bootstrap-4.0.0-M2.jar;D:\Apache\apache-maven-3.6.3-repo\org\springframework\cloud\spring-cloud-starter\4.0.0-M2\spring-cloud-starter-4.0.0-M2.jar;D:\Apache\apache-maven-3.6.3-repo\org\springframework\cloud\spring-cloud-context\4.0.0-M2\spring-cloud-context-4.0.0-M2.jar;D:\Apache\apache-maven-3.6.3-repo\org\springframework\security\spring-security-rsa\1.0.10.RELEASE\spring-security-rsa-1.0.10.RELEASE.jar;D:\Apache\apache-maven-3.6.3-repo\org\bouncycastle\bcpkix-jdk15on\1.68\bcpkix-jdk15on-1.68.jar;D:\Apache\apache-maven-3.6.3-repo\org\bouncycastle\bcprov-jdk15on\1.68\bcprov-jdk15on-1.68.jar;D:\Apache\apache-maven-3.6.3-repo\org\springframework\boot\spring-boot-starter-actuator\3.0.0-M3\spring-boot-starter-actuator-3.0.0-M3.jar;D:\Apache\apache-maven-3.6.3-repo\org\springframework\boot\spring-boot-starter\3.0.0-M3\spring-boot-starter-3.0.0-M3.jar;D:\Apache\apache-maven-3.6.3-repo\org\springframework\boot\spring-boot\3.0.0-M3\spring-boot-3.0.0-M3.jar;D:\Apache\apache-maven-3.6.3-repo\org\springframework\spring-context\6.0.0-M4\spring-context-6.0.0-M4.jar;D:\Apache\apache-maven-3.6.3-repo\org\springframework\spring-aop\6.0.0-M4\spring-aop-6.0.0-M4.jar;D:\Apache\apache-maven-3.6.3-repo\org\springframework\spring-expression\6.0.0-M4\spring-expression-6.0.0-M4.jar;D:\Apache\apache-maven-3.6.3-repo\org\springframework\boot\spring-boot-autoconfigure\3.0.0-M3\spring-boot-autoconfigure-3.0.0-M3.jar;D:\Apache\apache-maven-3.6.3-repo\org\springframework\boot\spring-boot-starter-logging\3.0.0-M3\spring-boot-starter-logging-3.0.0-M3.jar;D:\Apache\apache-maven-3.6.3-repo\ch\qos\logback\logback-classic\1.2.11\logback-classic-1.2.11.jar;D:\Apache\apache-maven-3.6.3-repo\ch\qos\logback\logback-core\1.2.11\logback-core-1.2.11.jar;D:\Apache\apache-maven-3.6.3-repo\org\apache\logging\log4j\log4j-to-slf4j\2.17.2\log4j-to-slf4j-2.17.2.jar;D:\Apache\apache-maven-3.6.3-repo\org\apache\logging\log4j\log4j-api\2.17.2\log4j-api-2.17.2.jar;D:\Apache\apache-maven-3.6.3-repo\org\slf4j\jul-to-slf4j\1.7.36\jul-to-slf4j-1.7.36.jar;D:\Apache\apache-maven-3.6.3-repo\jakarta\annotation\jakarta.annotation-api\2.0.0\jakarta.annotation-api-2.0.0.jar;D:\Apache\apache-maven-3.6.3-repo\org\yaml\snakeyaml\1.30\snakeyaml-1.30.jar;D:\Apache\apache-maven-3.6.3-repo\org\springframework\boot\spring-boot-actuator-autoconfigure\3.0.0-M3\spring-boot-actuator-autoconfigure-3.0.0-M3.jar;D:\Apache\apache-maven-3.6.3-repo\org\springframework\boot\spring-boot-actuator\3.0.0-M3\spring-boot-actuator-3.0.0-M3.jar;D:\Apache\apache-maven-3.6.3-repo\com\fasterxml\jackson\core\jackson-databind\2.13.3\jackson-databind-2.13.3.jar;D:\Apache\apache-maven-3.6.3-repo\com\fasterxml\jackson\core\jackson-annotations\2.13.3\jackson-annotations-2.13.3.jar;D:\Apache\apache-maven-3.6.3-repo\com\fasterxml\jackson\core\jackson-core\2.13.3\jackson-core-2.13.3.jar;D:\Apache\apache-maven-3.6.3-repo\com\fasterxml\jackson\datatype\jackson-datatype-jsr310\2.13.3\jackson-datatype-jsr310-2.13.3.jar;D:\Apache\apache-maven-3.6.3-repo\io\micrometer\micrometer-observation\1.10.0-M2\micrometer-observation-1.10.0-M2.jar;D:\Apache\apache-maven-3.6.3-repo\io\micrometer\micrometer-commons\1.10.0-M2\micrometer-commons-1.10.0-M2.jar;D:\Apache\apache-maven-3.6.3-repo\io\micrometer\micrometer-core\1.10.0-M2\micrometer-core-1.10.0-M2.jar;D:\Apache\apache-maven-3.6.3-repo\org\hdrhistogram\HdrHistogram\2.1.12\HdrHistogram-2.1.12.jar;D:\Apache\apache-maven-3.6.3-repo\org\latencyutils\LatencyUtils\2.0.3\LatencyUtils-2.0.3.jar;D:\Apache\apache-maven-3.6.3-repo\org\springframework\cloud\spring-cloud-starter-gateway\4.0.0-M2\spring-cloud-starter-gateway-4.0.0-M2.jar;D:\Apache\apache-maven-3.6.3-repo\org\springframework\cloud\spring-cloud-gateway-server\4.0.0-M2\spring-cloud-gateway-server-4.0.0-M2.jar;D:\Apache\apache-maven-3.6.3-repo\org\springframework\boot\spring-boot-starter-validation\3.0.0-M3\spring-boot-starter-validation-3.0.0-M3.jar;D:\Apache\apache-maven-3.6.3-repo\org\apache\tomcat\embed\tomcat-embed-el\10.0.21\tomcat-embed-el-10.0.21.jar;D:\Apache\apache-maven-3.6.3-repo\org\hibernate\validator\hibernate-validator\7.0.4.Final\hibernate-validator-7.0.4.Final.jar;D:\Apache\apache-maven-3.6.3-repo\jakarta\validation\jakarta.validation-api\3.0.1\jakarta.validation-api-3.0.1.jar;D:\Apache\apache-maven-3.6.3-repo\org\jboss\logging\jboss-logging\3.5.0.Final\jboss-logging-3.5.0.Final.jar;D:\Apache\apache-maven-3.6.3-repo\com\fasterxml\classmate\1.5.1\classmate-1.5.1.jar;D:\Apache\apache-maven-3.6.3-repo\io\projectreactor\addons\reactor-extra\3.5.0-M2\reactor-extra-3.5.0-M2.jar;D:\Apache\apache-maven-3.6.3-repo\org\springframework\boot\spring-boot-starter-webflux\3.0.0-M3\spring-boot-starter-webflux-3.0.0-M3.jar;D:\Apache\apache-maven-3.6.3-repo\org\springframework\boot\spring-boot-starter-json\3.0.0-M3\spring-boot-starter-json-3.0.0-M3.jar;D:\Apache\apache-maven-3.6.3-repo\com\fasterxml\jackson\datatype\jackson-datatype-jdk8\2.13.3\jackson-datatype-jdk8-2.13.3.jar;D:\Apache\apache-maven-3.6.3-repo\com\fasterxml\jackson\module\jackson-module-parameter-names\2.13.3\jackson-module-parameter-names-2.13.3.jar;D:\Apache\apache-maven-3.6.3-repo\org\springframework\boot\spring-boot-starter-reactor-netty\3.0.0-M3\spring-boot-starter-reactor-netty-3.0.0-M3.jar;D:\Apache\apache-maven-3.6.3-repo\io\projectreactor\netty\reactor-netty-http\1.1.0-M2\reactor-netty-http-1.1.0-M2.jar;D:\Apache\apache-maven-3.6.3-repo\io\micrometer\context-propagation-api\1.0.0-M2\context-propagation-api-1.0.0-M2.jar;D:\Apache\apache-maven-3.6.3-repo\io\netty\netty-codec-http\4.1.77.Final\netty-codec-http-4.1.77.Final.jar;D:\Apache\apache-maven-3.6.3-repo\io\netty\netty-common\4.1.77.Final\netty-common-4.1.77.Final.jar;D:\Apache\apache-maven-3.6.3-repo\io\netty\netty-buffer\4.1.77.Final\netty-buffer-4.1.77.Final.jar;D:\Apache\apache-maven-3.6.3-repo\io\netty\netty-transport\4.1.77.Final\netty-transport-4.1.77.Final.jar;D:\Apache\apache-maven-3.6.3-repo\io\netty\netty-codec\4.1.77.Final\netty-codec-4.1.77.Final.jar;D:\Apache\apache-maven-3.6.3-repo\io\netty\netty-handler\4.1.77.Final\netty-handler-4.1.77.Final.jar;D:\Apache\apache-maven-3.6.3-repo\io\netty\netty-codec-http2\4.1.77.Final\netty-codec-http2-4.1.77.Final.jar;D:\Apache\apache-maven-3.6.3-repo\io\netty\netty-resolver-dns\4.1.77.Final\netty-resolver-dns-4.1.77.Final.jar;D:\Apache\apache-maven-3.6.3-repo\io\netty\netty-resolver\4.1.77.Final\netty-resolver-4.1.77.Final.jar;D:\Apache\apache-maven-3.6.3-repo\io\netty\netty-codec-dns\4.1.77.Final\netty-codec-dns-4.1.77.Final.jar;D:\Apache\apache-maven-3.6.3-repo\io\netty\netty-resolver-dns-native-macos\4.1.77.Final\netty-resolver-dns-native-macos-4.1.77.Final-osx-x86_64.jar;D:\Apache\apache-maven-3.6.3-repo\io\netty\netty-resolver-dns-classes-macos\4.1.77.Final\netty-resolver-dns-classes-macos-4.1.77.Final.jar;D:\Apache\apache-maven-3.6.3-repo\io\netty\netty-transport-native-epoll\4.1.77.Final\netty-transport-native-epoll-4.1.77.Final-linux-x86_64.jar;D:\Apache\apache-maven-3.6.3-repo\io\netty\netty-transport-native-unix-common\4.1.77.Final\netty-transport-native-unix-common-4.1.77.Final.jar;D:\Apache\apache-maven-3.6.3-repo\io\netty\netty-transport-classes-epoll\4.1.77.Final\netty-transport-classes-epoll-4.1.77.Final.jar;D:\Apache\apache-maven-3.6.3-repo\io\projectreactor\netty\reactor-netty-core\1.1.0-M2\reactor-netty-core-1.1.0-M2.jar;D:\Apache\apache-maven-3.6.3-repo\io\netty\netty-handler-proxy\4.1.77.Final\netty-handler-proxy-4.1.77.Final.jar;D:\Apache\apache-maven-3.6.3-repo\io\netty\netty-codec-socks\4.1.77.Final\netty-codec-socks-4.1.77.Final.jar;D:\Apache\apache-maven-3.6.3-repo\org\springframework\spring-web\6.0.0-M4\spring-web-6.0.0-M4.jar;D:\Apache\apache-maven-3.6.3-repo\org\springframework\spring-beans\6.0.0-M4\spring-beans-6.0.0-M4.jar;D:\Apache\apache-maven-3.6.3-repo\org\springframework\spring-webflux\6.0.0-M4\spring-webflux-6.0.0-M4.jar;D:\Apache\apache-maven-3.6.3-repo\org\springframework\cloud\spring-cloud-starter-loadbalancer\4.0.0-M2\spring-cloud-starter-loadbalancer-4.0.0-M2.jar;D:\Apache\apache-maven-3.6.3-repo\org\springframework\cloud\spring-cloud-loadbalancer\4.0.0-M2\spring-cloud-loadbalancer-4.0.0-M2.jar;D:\Apache\apache-maven-3.6.3-repo\io\projectreactor\reactor-core\3.5.0-M2\reactor-core-3.5.0-M2.jar;D:\Apache\apache-maven-3.6.3-repo\org\reactivestreams\reactive-streams\1.0.3\reactive-streams-1.0.3.jar;D:\Apache\apache-maven-3.6.3-repo\org\springframework\boot\spring-boot-starter-cache\3.0.0-M3\spring-boot-starter-cache-3.0.0-M3.jar;D:\Apache\apache-maven-3.6.3-repo\org\springframework\spring-context-support\6.0.0-M4\spring-context-support-6.0.0-M4.jar;D:\Apache\apache-maven-3.6.3-repo\com\stoyanr\evictor\1.0.0\evictor-1.0.0.jar;D:\Apache\apache-maven-3.6.3-repo\org\slf4j\slf4j-api\1.7.36\slf4j-api-1.7.36.jar;D:\Apache\apache-maven-3.6.3-repo\org\springframework\spring-core\6.0.0-M4\spring-core-6.0.0-M4.jar;D:\Apache\apache-maven-3.6.3-repo\org\springframework\spring-jcl\6.0.0-M4\spring-jcl-6.0.0-M4.jar;D:\Program Files\JetBrains\ideaIU-2022.1.1.win\lib\idea_rt.jar" cloud.xuxiaowei.next.gateway.GatewayApplication
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
Connected to the target VM, address: '127.0.0.1:57498', transport: 'socket'
10:18:14.428 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.IllegalArgumentException: Unable to instantiate factory class [org.springframework.cloud.consul.config.ConsulConfigDataLocationResolver] for factory type [org.springframework.boot.context.config.ConfigDataLocationResolver]
	at org.springframework.core.io.support.SpringFactoriesLoader$FailureHandler.lambda$throwing$0(SpringFactoriesLoader.java:653)
	at org.springframework.core.io.support.SpringFactoriesLoader$FailureHandler.lambda$handleMessage$3(SpringFactoriesLoader.java:677)
	at org.springframework.core.io.support.SpringFactoriesLoader.instantiateFactory(SpringFactoriesLoader.java:231)
	at org.springframework.core.io.support.SpringFactoriesLoader.load(SpringFactoriesLoader.java:206)
	at org.springframework.core.io.support.SpringFactoriesLoader.load(SpringFactoriesLoader.java:162)
	at org.springframework.boot.context.config.ConfigDataLocationResolvers.<init>(ConfigDataLocationResolvers.java:66)
	at org.springframework.boot.context.config.ConfigDataEnvironment.createConfigDataLocationResolvers(ConfigDataEnvironment.java:160)
	at org.springframework.boot.context.config.ConfigDataEnvironment.<init>(ConfigDataEnvironment.java:148)
	at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.getConfigDataEnvironment(ConfigDataEnvironmentPostProcessor.java:101)
	at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:96)
	at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:89)
	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:109)
	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:94)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:85)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:66)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:65)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:350)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:150)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:195)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:114)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:77)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:85)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:66)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:65)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:350)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301)
	at cloud.xuxiaowei.next.gateway.GatewayApplication.main(GatewayApplication.java:16)
Caused by: java.lang.IllegalArgumentException: Log types cannot be injected, please use DeferredLogFactory
	at org.springframework.boot.context.config.ConfigDataLocationResolvers.lambda$new$0(ConfigDataLocationResolvers.java:64)
	at org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver.lambda$ofSupplied$3(SpringFactoriesLoader.java:589)
	at org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver$1.resolve(SpringFactoriesLoader.java:605)
	at org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver.lambda$and$0(SpringFactoriesLoader.java:555)
	at org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver$1.resolve(SpringFactoriesLoader.java:605)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at org.springframework.core.io.support.SpringFactoriesLoader$FactoryInstantiator.resolveArgs(SpringFactoriesLoader.java:390)
	at org.springframework.core.io.support.SpringFactoriesLoader$FactoryInstantiator.instantiate(SpringFactoriesLoader.java:380)
	at org.springframework.core.io.support.SpringFactoriesLoader.instantiateFactory(SpringFactoriesLoader.java:228)
	... 41 common frames omitted
Disconnected from the target VM, address: '127.0.0.1:57498', transport: 'socket'

Process finished with exit code 1

```

**Sample**
https://github.com/xuxiaowei-cloud/xuxiaowei-cloud-next/tree/ERROR_1

run https://github.com/xuxiaowei-cloud/xuxiaowei-cloud-next/blob/ERROR_1/gateway/src/main/java/cloud/xuxiaowei/next/gateway/GatewayApplication.java

**Comment by xuxiaowei-com-cn** [comment]
Downgrade the spring boot version from 3.0.0-m3 to 3.0.0-m2 to run normally

**Comment by xuxiaowei-com-cn** [comment]
Consul v1.12.0

**Comment by wilkinsona** [comment]
Thanks for the report but there's nothing we can do about this. For compatibility with Spring Boot 3.0.0-M3,  you need [this change](https://github.com/spring-cloud/spring-cloud-consul/commit/1f4baf8093567cb95f5292e4b0e30ea82a1d5504) that has been made in Spring Cloud Consul. You may need to use snapshots until a release is made.

**Comment by delor** [comment]
Got this exception on 3.0.2. What is causing this?
