### ISSUE TITLE
ConfigurationPropertiesBeanFactoryInitializationAotProcessor does not handle singleton

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#31248]
AOT generation with Spring Cloud is broken as `ConfigurationPropertiesBeanFactoryInitializationAotProcessor` loops over all the `@ConfigurationProperties`-annotated types and try to get its merged bean definition to register the necessary hints. A singleton does not have a bean definition, which leads to:

```
Exception in thread "main" org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'keyProperties' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:860)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedBeanDefinition(AbstractBeanFactory.java:1092)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBeanFactoryInitializationAotProcessor.processAheadOfTime(ConfigurationPropertiesBeanFactoryInitializationAotProcessor.java:67)
	at org.springframework.context.aot.BeanFactoryInitializationAotContributions.getContributions(BeanFactoryInitializationAotContributions.java:67)
	at org.springframework.context.aot.BeanFactoryInitializationAotContributions.<init>(BeanFactoryInitializationAotContributions.java:49)
	at org.springframework.context.aot.BeanFactoryInitializationAotContributions.<init>(BeanFactoryInitializationAotContributions.java:44)
	at org.springframework.context.aot.ApplicationContextAotGenerator.generateApplicationContext(ApplicationContextAotGenerator.java:55)
	at org.springframework.boot.AotProcessor.performAotProcessing(AotProcessor.java:150)
	at org.springframework.boot.AotProcessor.process(AotProcessor.java:110)
	at org.springframework.boot.AotProcessor.main(AotProcessor.java:227)
```

**Comment by snicoll** [comment]
Interestingly enough, Spring Native [uses the same logic](https://github.com/spring-projects-experimental/spring-native/blob/6290ad01fd22fdd49209099bde36f4294e724f95/spring-aot/src/main/java/org/springframework/boot/context/properties/ConfigurationPropertiesNativeConfigurationProcessor.java#L66) so it should be something new in Spring Cloud.

**Comment by spencergibb** [comment]
https://github.com/spring-projects/spring-framework/issues/28487 for some history. "keyProperties" and "textEncryptor" are registered the same way
