### ISSUE TITLE
Support Kotlin value classes for configuration binding

### ISSUE THREAD

**Issue by MrBuddyCasino** [spring-projects/spring-boot#31398]
Kotlin value classes currently cannot be used in configuration bindings in Spring 2.6.6

This is a repro case:

```
package com.example

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.context.properties.ConfigurationProperties
import org.springframework.boot.context.properties.ConfigurationPropertiesScan
import org.springframework.boot.context.properties.ConstructorBinding
import org.springframework.boot.runApplication
import org.springframework.context.annotation.Bean

fun main(args: Array<String>) {
    System.setProperty("SPRING_APPLICATION_JSON", "{ \"predicate\": \"C\" }")
    runApplication<SpringTest>(*args)
}

@SpringBootApplication
@ConfigurationPropertiesScan(basePackages = ["com.example"])
class SpringTest {

    @Bean
    fun someBean(config: PredicateConfiguration): String {
        println("predicate: ${config.predicate.value}")
        return ""
    }

}

@JvmInline
value class Predicate(val value: Char)

@ConfigurationProperties
@ConstructorBinding
data class PredicateConfiguration(val predicate: Predicate)
```

It fails with the following error message:
```
Failed to bind properties under '' to com.example.PredicateConfiguration:

    Reason: java.lang.IllegalArgumentException: object is not an instance of declaring class
```

**Comment by wilkinsona** [comment]
Thanks for the report. The problem can be reproduced without Spring Boot:

```kotlin
package com.example.gh31398

import org.springframework.beans.BeanUtils

class Gh31398Application

fun main(args: Array<String>) {
	val constructor = PredicateConfiguration::class.java.constructors[0]
	val args = arrayOf(Character.valueOf('c'))
	BeanUtils.instantiateClass(constructor, *args)
}

@JvmInline
value class Predicate(val value: Char)

data class PredicateConfiguration(val predicate: Predicate)
```

```
Exception in thread "main" org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.example.gh31398.PredicateConfiguration]: Illegal arguments for constructor; nested exception is java.lang.IllegalArgumentException: object is not an instance of declaring class
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:221)
	at com.example.gh31398.Gh31398ApplicationKt.main(Gh31398Application.kt:10)
Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at kotlin.reflect.jvm.internal.calls.InlineClassAwareCaller.call(InlineClassAwareCaller.kt:134)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:112)
	at org.springframework.beans.BeanUtils$KotlinDelegate.instantiateClass(BeanUtils.java:892)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:196)
	... 1 more
```

I'm not sure if this is something that can be addressed in Framework's support for instantiating Kotlin types or if it's a bug in Kotlin's reflection support.

We'll transfer this to the Framework team so that they can take a look.
