### ISSUE TITLE
Filewatch created during shutdown

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#3165]
```
Exception in thread "File Watcher" org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'org.springframework.boot.developertools.autoconfigure.LocalDeveloperToolsAutoConfiguration$LiveReloadConfiguration': Singleton bean creation not allowed while the singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:216)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1011)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.getTargetBean(ApplicationListenerMethodAdapter.java:240)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:210)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:109)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:99)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:364)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:333)
	at org.springframework.boot.developertools.classpath.ClassPathFileChangeListener.onChange(ClassPathFileChangeListener.java:59)
	at org.springframework.boot.developertools.filewatch.FileSystemWatcher.fireListeners(FileSystemWatcher.java:183)
	at org.springframework.boot.developertools.filewatch.FileSystemWatcher.updateSnapshots(FileSystemWatcher.java:176)
	at org.springframework.boot.developertools.filewatch.FileSystemWatcher.scan(FileSystemWatcher.java:153)
	at org.springframework.boot.developertools.filewatch.FileSystemWatcher.access$100(FileSystemWatcher.java:40)
	at org.springframework.boot.developertools.filewatch.FileSystemWatcher$1.run(FileSystemWatcher.java:122)
```

**Comment by philwebb** [comment]
https://gist.githubusercontent.com/olivergierke/ce459811c4b56d47448e/raw/724718785c6b49bcc174c2aba47dfcfba955e046/gistfile1.txt

**Comment by philwebb** [comment]
Ollie was using an older version. Seems fine with the latest code.
