### ISSUE TITLE
jetty starter 2.1.18.RELEASE internal incompatibility

### ISSUE THREAD

**Issue by NeoZephyr** [spring-projects/spring-boot#31678]
Http server can not start up, and here is error log

```
Exception in thread "Thread-22" java.lang.AbstractMethodError: org.eclipse.jetty.server.AllowedResourceAliasChecker$AllowedResourceAliasCheckListener.lifeCycleFailur
e(Lorg/eclipse/jetty/util/component/LifeCycle;Ljava/lang/Throwable;)V
	at org.eclipse.jetty.util.component.AbstractLifeCycle.setFailed(AbstractLifeCycle.java:237)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:98)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:180)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:201)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:108)
	at org.eclipse.jetty.server.Server.doStop(Server.java:470)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:93)
	at org.springframework.boot.web.embedded.jetty.JettyWebServer.stop(JettyWebServer.java:243)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.stopAndReleaseWebServer(ServletWebServerApplicationContext.java:306)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onClose(ServletWebServerApplicationContext.java:172)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1033)
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:946)
Exception in thread "Thread-22" java.lang.AbstractMethodError: org.eclipse.jetty.server.AllowedResourceAliasChecker$AllowedResourceAliasCheckListener.lifeCycleFailur
e(Lorg/eclipse/jetty/util/component/LifeCycle;Ljava/lang/Throwable;)V
	at org.eclipse.jetty.util.component.AbstractLifeCycle.setFailed(AbstractLifeCycle.java:237)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:98)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:180)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:201)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:108)
	at org.eclipse.jetty.server.Server.doStop(Server.java:470)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:93)
	at org.springframework.boot.web.embedded.jetty.JettyWebServer.stop(JettyWebServer.java:243)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.stopAndReleaseWebServer(ServletWebServerApplicationContext.java:306)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onClose(ServletWebServerApplicationContext.java:172)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1033)
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:946)
Exception in thread "Thread-22" java.lang.AbstractMethodError: org.eclipse.jetty.server.AllowedResourceAliasChecker$AllowedResourceAliasCheckListener.lifeCycleFailur
e(Lorg/eclipse/jetty/util/component/LifeCycle;Ljava/lang/Throwable;)V
	at org.eclipse.jetty.util.component.AbstractLifeCycle.setFailed(AbstractLifeCycle.java:237)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:98)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:180)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:201)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:108)
	at org.eclipse.jetty.server.Server.doStop(Server.java:470)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:93)
	at org.springframework.boot.web.embedded.jetty.JettyWebServer.stop(JettyWebServer.java:243)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.stopAndReleaseWebServer(ServletWebServerApplicationContext.java:306)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onClose(ServletWebServerApplicationContext.java:172)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1033)
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:946)

```

Here is the corresponding code
<img width="802" alt="image" src="https://user-images.githubusercontent.com/59204986/178402436-379e5f50-b9f1-463f-9234-0fafdd8e02a4.png">
<img width="591" alt="image" src="https://user-images.githubusercontent.com/59204986/178402451-24a1a923-5332-41cc-abd4-656513788071.png">

Here is dependencies
<img width="632" alt="image" src="https://user-images.githubusercontent.com/59204986/178402565-6dbfee1a-dd53-4136-9027-f967e4155e6d.png">

**Comment by wilkinsona** [comment]
You have a mixture of Jetty versions on the classpath: 9.4.48 and 9.4.43. This is the cause of the incompatibility. Also, please note that support for Spring Boot 2.1.x [ended in October 2019](https://spring.io/projects/spring-boot#support). You should upgrade to Spring Boot 2.6.x or 2.7.x as soon as possible.

**Comment by NeoZephyr** [comment]
> You have a mixture of Jetty versions on the classpath: 9.4.48 and 9.4.43. This is the cause of the incompatibility. Also, please note that support for Spring Boot 2.1.x [ended in October 2019](https://spring.io/projects/spring-boot#support). You should upgrade to Spring Boot 2.6.x or 2.7.x as soon as possible.

Ok, thanks for your reply!
