### ISSUE TITLE
reactor.netty.channel.AbortedException: Connection has been closed

### ISSUE THREAD

**Issue by vaclap** [spring-projects/spring-boot#31905]
SpringBoot 2.6.9

The development environment is normal. When deployed to the production environment, as the number of requests increases, this error will occur occasionally！

But on springboot 2.3.10.RELEASE without any errors。

```
reactor.netty.channel.AbortedException: Connection has been closed
  at reactor.netty.http.server.HttpServerOperations.onInboundClose(HttpServerOperations.java:575) ~[reactor-netty-http-1.0.8.jar!/:1.0.8]
  Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
  |_ checkpoint ⇢ com.mt.jump.auth.AuthFilter [DefaultWebFilterChain]
  |_ checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
  |_ checkpoint ⇢ HTTP POST "/user/save" [ExceptionHandlingWebHandler]
Stack trace:
    at reactor.netty.http.server.HttpServerOperations.onInboundClose(HttpServerOperations.java:575) ~[reactor-netty-http-1.0.8.jar!/:1.0.8]
    at reactor.netty.channel.ChannelOperationsHandler.channelInactive(ChannelOperationsHandler.java:74) ~[reactor-netty-core-1.0.8.jar!/:1.0.8]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
    at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:418) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
    at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389) ~[netty-codec-4.1.65.Final.jar!/:4.1.65.Final]
    at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354) ~[netty-codec-4.1.65.Final.jar!/:4.1.65.Final]
    at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:221) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
    at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
    at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:831) ~[netty-transport-4.1.65.Final.jar!/:4.1.65.Final]
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-common-4.1.65.Final.jar!/:4.1.65.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[netty-common-4.1.65.Final.jar!/:4.1.65.Final]
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[netty-transport-native-epoll-4.1.65.Final-linux-x86_64.jar!/:4.1.65.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.65.Final.jar!/:4.1.65.Final]
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.65.Final.jar!/:4.1.65.Final]
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.65.Final.jar!/:4.1.65.Final]
    at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

**Comment by wilkinsona** [comment]
@vaclap Thanks for the report. This error indicates that the connection between the client and server has been closed. This is out of Spring Boot's control as it's handled by (Reactor) Netty. If you believe the behavior is a bug, please open a [Reactor Netty issue](https://github.com/reactor/reactor-netty/issues).
