### ISSUE TITLE
Add native-image support for Mustache on WebFlux

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#32028]
The `mustache-webflux` sample fails because there is a constructor hint on `MustacheView` missing:

```
ion: Failed to instantiate [org.springframework.boot.web.reactive.result.view.MustacheView]: No default constructor found
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:146) ~[na:na]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ Handler com.example.mustache.webflux.TestController#index(String, Model) [DispatcherHandler]
	*__checkpoint ⇢ HTTP GET "/greeting" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:146) ~[na:na]
		at org.springframework.web.reactive.result.view.UrlBasedViewResolver.instantiateView(UrlBasedViewResolver.java:283) ~[mustache-webflux:6.0.0-SNAPSHOT]
		at org.springframework.web.reactive.result.view.UrlBasedViewResolver.createView(UrlBasedViewResolver.java:298) ~[mustache-webflux:6.0.0-SNAPSHOT]
		at org.springframework.boot.web.reactive.result.view.MustacheViewResolver.createView(MustacheViewResolver.java:72) ~[mustache-webflux:3.0.0-SNAPSHOT]
		at org.springframework.web.reactive.result.view.UrlBasedViewResolver.resolveViewName(UrlBasedViewResolver.java:237) ~[mustache-webflux:6.0.0-SNAPSHOT]
		at org.springframework.web.reactive.result.view.ViewResolutionResultHandler.lambda$resolveViews$2(ViewResolutionResultHandler.java:274) ~[mustache-webflux:6.0.0-SNAPSHOT]
		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onNext(FluxConcatMapNoPrefetch.java:183) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:272) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:230) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.request(FluxConcatMapNoPrefetch.java:336) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onSubscribe(MonoCollectList.java:80) ~[na:na]
		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onSubscribe(FluxConcatMapNoPrefetch.java:164) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:165) ~[na:na]
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:87) ~[na:na]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[na:na]
		at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2194) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2068) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55) ~[na:na]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[na:na]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200) ~[na:na]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200) ~[na:na]
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(MonoIgnoreThen.java:292) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(MonoIgnoreThen.java:187) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.MonoZip$ZipCoordinator.signal(MonoZip.java:251) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.MonoZip$ZipInner.onNext(MonoZip.java:336) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180) ~[na:na]
		at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:139) ~[na:na]
		at reactor.core.publisher.MonoZip$ZipInner.onSubscribe(MonoZip.java:325) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onSubscribe(MonoPeekTerminal.java:152) ~[na:na]
		at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55) ~[na:na]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4321) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.MonoZip.subscribe(MonoZip.java:128) ~[na:na]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[na:na]
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:240) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onComplete(MonoFlatMap.java:181) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.Operators.complete(Operators.java:137) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.MonoZip.subscribe(MonoZip.java:120) ~[na:na]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4321) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51) ~[na:na]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[na:na]
		at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.innerNext(FluxConcatMapNoPrefetch.java:258) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:863) ~[na:na]
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129) ~[na:na]
		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180) ~[na:na]
		at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:139) ~[na:na]
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:171) ~[na:na]
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.request(Operators.java:2158) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.request(FluxConcatMapNoPrefetch.java:338) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.MonoNext$NextSubscriber.request(MonoNext.java:108) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2194) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2068) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.MonoNext$NextSubscriber.onSubscribe(MonoNext.java:70) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onSubscribe(FluxConcatMapNoPrefetch.java:164) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:165) ~[na:na]
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:87) ~[na:na]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[na:na]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4321) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51) ~[na:na]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[mustache-webflux:3.5.0-M4]
		at reactor.core.publisher.MonoDeferContextual.subscribe(MonoDeferContextual.java:55) ~[na:na]
		at reactor.netty.http.server.HttpServer$HttpServerHandle.onStateChange(HttpServer.java:967) ~[na:na]
		at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:677) ~[na:na]
		at reactor.netty.transport.ServerTransport$ChildObserver.onStateChange(ServerTransport.java:478) ~[na:na]
		at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:570) ~[mustache-webflux:1.1.0-M4]
		at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93) ~[na:na]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[mustache-webflux:4.1.79.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[mustache-webflux:4.1.79.Final]
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[mustache-webflux:4.1.79.Final]
		at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:222) ~[na:na]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[mustache-webflux:4.1.79.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[mustache-webflux:4.1.79.Final]
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[mustache-webflux:4.1.79.Final]
		at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[mustache-webflux:4.1.79.Final]
		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[mustache-webflux:4.1.79.Final]
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) ~[mustache-webflux:4.1.79.Final]
		at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[mustache-webflux:4.1.79.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[mustache-webflux:4.1.79.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[mustache-webflux:4.1.79.Final]
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[mustache-webflux:4.1.79.Final]
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[mustache-webflux:4.1.79.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[mustache-webflux:4.1.79.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[mustache-webflux:4.1.79.Final]
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[mustache-webflux:4.1.79.Final]
		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[mustache-webflux:4.1.79.Final]
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) ~[na:na]
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[na:na]
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[na:na]
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[na:na]
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[na:na]
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[na:na]
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[na:na]
		at java.lang.Thread.run(Thread.java:833) ~[mustache-webflux:na]
		at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:705) ~[mustache-webflux:na]
		at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202) ~[na:na]
Caused by: java.lang.NoSuchMethodException: org.springframework.boot.web.reactive.result.view.MustacheView.<init>()
	at java.lang.Class.getConstructor0(DynamicHub.java:3585) ~[mustache-webflux:na]
	at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2754) ~[mustache-webflux:na]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:141) ~[na:na]
	at org.springframework.web.reactive.result.view.UrlBasedViewResolver.instantiateView(UrlBasedViewResolver.java:283) ~[mustache-webflux:6.0.0-SNAPSHOT]
	at org.springframework.web.reactive.result.view.UrlBasedViewResolver.createView(UrlBasedViewResolver.java:298) ~[mustache-webflux:6.0.0-SNAPSHOT]
	at org.springframework.boot.web.reactive.result.view.MustacheViewResolver.createView(MustacheViewResolver.java:72) ~[mustache-webflux:3.0.0-SNAPSHOT]
	at org.springframework.web.reactive.result.view.UrlBasedViewResolver.resolveViewName(UrlBasedViewResolver.java:237) ~[mustache-webflux:6.0.0-SNAPSHOT]
	at org.springframework.web.reactive.result.view.ViewResolutionResultHandler.lambda$resolveViews$2(ViewResolutionResultHandler.java:274) ~[mustache-webflux:6.0.0-SNAPSHOT]
	at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onNext(FluxConcatMapNoPrefetch.java:183) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:272) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:230) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.request(FluxConcatMapNoPrefetch.java:336) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onSubscribe(MonoCollectList.java:80) ~[na:na]
	at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onSubscribe(FluxConcatMapNoPrefetch.java:164) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:165) ~[na:na]
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:87) ~[na:na]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[na:na]
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2194) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2068) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55) ~[na:na]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[na:na]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200) ~[na:na]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200) ~[na:na]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(MonoIgnoreThen.java:292) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(MonoIgnoreThen.java:187) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.MonoZip$ZipCoordinator.signal(MonoZip.java:251) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.MonoZip$ZipInner.onNext(MonoZip.java:336) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180) ~[na:na]
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:139) ~[na:na]
	at reactor.core.publisher.MonoZip$ZipInner.onSubscribe(MonoZip.java:325) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onSubscribe(MonoPeekTerminal.java:152) ~[na:na]
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55) ~[na:na]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4321) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.MonoZip.subscribe(MonoZip.java:128) ~[na:na]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[na:na]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:240) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onComplete(MonoFlatMap.java:181) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.Operators.complete(Operators.java:137) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.MonoZip.subscribe(MonoZip.java:120) ~[na:na]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4321) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51) ~[na:na]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[na:na]
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.innerNext(FluxConcatMapNoPrefetch.java:258) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:863) ~[na:na]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129) ~[na:na]
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180) ~[na:na]
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:139) ~[na:na]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:171) ~[na:na]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.request(Operators.java:2158) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.request(FluxConcatMapNoPrefetch.java:338) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.MonoNext$NextSubscriber.request(MonoNext.java:108) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2194) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2068) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.MonoNext$NextSubscriber.onSubscribe(MonoNext.java:70) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onSubscribe(FluxConcatMapNoPrefetch.java:164) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:165) ~[na:na]
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:87) ~[na:na]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[na:na]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4321) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51) ~[na:na]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[mustache-webflux:3.5.0-M4]
	at reactor.core.publisher.MonoDeferContextual.subscribe(MonoDeferContextual.java:55) ~[na:na]
	at reactor.netty.http.server.HttpServer$HttpServerHandle.onStateChange(HttpServer.java:967) ~[na:na]
	at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:677) ~[na:na]
	at reactor.netty.transport.ServerTransport$ChildObserver.onStateChange(ServerTransport.java:478) ~[na:na]
	at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:570) ~[mustache-webflux:1.1.0-M4]
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93) ~[na:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[mustache-webflux:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[mustache-webflux:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[mustache-webflux:4.1.79.Final]
	at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:222) ~[na:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[mustache-webflux:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[mustache-webflux:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[mustache-webflux:4.1.79.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[mustache-webflux:4.1.79.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[mustache-webflux:4.1.79.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) ~[mustache-webflux:4.1.79.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[mustache-webflux:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[mustache-webflux:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[mustache-webflux:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[mustache-webflux:4.1.79.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[mustache-webflux:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[mustache-webflux:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[mustache-webflux:4.1.79.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[mustache-webflux:4.1.79.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[mustache-webflux:4.1.79.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) ~[na:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[na:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[na:na]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[na:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[na:na]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[na:na]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[na:na]
	at java.lang.Thread.run(Thread.java:833) ~[mustache-webflux:na]
	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:705) ~[mustache-webflux:na]
	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202) ~[na:na]
```

**Comment by snicoll** [comment]
Superseded by #32030
