### ISSUE TITLE
Spring Boot doesn't work with Mojarra 2.2.11

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#3216]
See http://www.beyondjava.net/blog/updating-to-mojarra-2-2-11-may-break-your-spring-boot-application/

Sample application can be found here https://github.com/bilak/spring-boot-primefaces-template problem can be found when you access this page `localhost:8080/view/fileupload.xhtml`

**Comment by philwebb** [comment]
It seems like we might need an easy way to get Spring to call specific `javax.servlet.ServletContainerInitializer` implementations and honor `@HandlesTypes`. It's not a great situation because we might need to do a full classpath scan.

**Comment by stephanrauh** [comment]
True, but for one it's part of the serlet API, and second you don't have to run the classpath scan if there's no ServletContainerInitializer registered.

**Comment by simongeard** [comment]
For what it's worth, I'm using the code below to make this work for me. It's a bit brutal, but narrowing the scanned packages to just the three listed makes a huge difference to startup performance... around 10 seconds instead of 30+...

	@Configuration
	public class JSFSetupBean implements ServletContextInitializer {

		private static final Logger LOGGER = LoggerFactory.getLogger(JSFSetupBean.class);

		@Override
		public void onStartup(ServletContext servletContext) throws ServletException {
			//Register JSF stuff
			runServletInitializer(servletContext, new FacesInitializer(), "com.sun.faces", "javax.faces", "net.bootsfaces");
		}

		/**
		 * <p>This fuss is needed because Spring Boot doesn't run {@link ServletContainerInitializer}
		 * instances off the classpath, but JSF relies on classpath scanning to get components
		 * and things registered. As a result, we're forced to do the scanning here, because we
		 * can't rely on the container to do it for us.</p>
		 *
		 * @see <a href="https://github.com/spring-projects/spring-boot/issues/321">Embedded Tomcat does not honor ServletContainerInitializers</a>.
		 * @see <a href="https://github.com/spring-projects/spring-boot/issues/3216">Spring Boot doesn't work with Mojarra 2.2.11</a>.
		 */
		private void runServletInitializer(ServletContext servletContext, FacesInitializer facesInitializer, String... basePackagesToScan)
				throws ServletException {
			ClassPathScanningCandidateComponentProvider scanner = constructScannerForServletInitializer(facesInitializer.getClass());
			Set<Class<?>> annotatedClasses = findAnnotatedClasses(scanner, basePackagesToScan);
			facesInitializer.onStartup(annotatedClasses, servletContext);
		}

		@SuppressWarnings("unchecked")
		private ClassPathScanningCandidateComponentProvider constructScannerForServletInitializer(Class<? extends ServletContainerInitializer> initializerClass) {
			ClassPathScanningCandidateComponentProvider scanner = new ClassPathScanningCandidateComponentProvider(false);
			for (Class<?> class1 : initializerClass.getAnnotation(HandlesTypes.class).value()) {
				if (class1.isAnnotation()) {
					LOGGER.debug("Filtering on annotation {}", class1);
					scanner.addIncludeFilter(new AnnotationTypeFilter((Class<? extends Annotation>) class1));
				} else {
					LOGGER.debug("Filtering on parent class or interface {}", class1);
					scanner.addIncludeFilter(new AssignableTypeFilter(class1));
				}
			}
			return scanner;
		}

		private Set<Class<?>> findAnnotatedClasses(ClassPathScanningCandidateComponentProvider scanner, String... basePackagesToScan) {
			Set<Class<?>> annotatedClasses = new HashSet<>();
			for (String basePackage : basePackagesToScan) {
				LOGGER.debug("Scanning under {}", basePackage);
				scanner.findCandidateComponents(basePackage).forEach(bd -> {
					annotatedClasses.add(ClassUtils.resolveClassName(bd.getBeanClassName(), getClass().getClassLoader()));
				});
			}
			return annotatedClasses;
		}
	}

It's not had huge testing, but seems to work... it's certainly resolved the problem that prompted it, which was that the BootFaces components weren't getting registered.

**Comment by philwebb** [comment]
For anyone following this issue, [this article](http://www.oakdalesoft.com/2015/09/spring-boot-with-jsfprimefaces/) seems to imply it's possible to get JSF working in some form.

**Comment by dmakariev** [comment]
seems that with the fix of the following issue : 
https://java.net/jira/browse/JAVASERVERFACES-3949
Mojarra 2.1.12+ works again fine with Spring Boot

**Comment by wilkinsona** [comment]
Thanks for the info, @dmakariev. Unfortunately, the sample app [linked to above](https://github.com/spring-projects/spring-boot/issues/3216#issue-87791536) still fails with 2.2.12:

```
2015-10-15 09:39:53.108  INFO 79495 --- [ost-startStop-1] j.e.resource.webcontainer.jsf.config     : Initializing Mojarra 2.2.12 ( 20150720-0848 https://svn.java.net/svn/mojarra~svn/tags/2.2.12@14885) for context ''
…
2015-10-15 09:40:09.749 ERROR 79495 --- [nio-8080-exec-1] j.e.r.webcontainer.jsf.application       : JSF1068: Cannot instantiate component with component-type net.bootsfaces.component.NavBar
2015-10-15 09:40:09.761 ERROR 79495 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[Faces Servlet]        : Servlet.service() for servlet [Faces Servlet] in context with path [] threw exception [Expression Error: Named Object: net.bootsfaces.component.NavBar not found.] with root cause

javax.faces.FacesException: Expression Error: Named Object: net.bootsfaces.component.NavBar not found.
	at com.sun.faces.application.ApplicationImpl.createComponentApplyAnnotations(ApplicationImpl.java:1912)
	at com.sun.faces.application.ApplicationImpl.createComponent(ApplicationImpl.java:1166)
	at com.sun.faces.facelets.tag.jsf.ComponentTagHandlerDelegateImpl.createComponent(ComponentTagHandlerDelegateImpl.java:602)
	at com.sun.faces.facelets.tag.jsf.ComponentTagHandlerDelegateImpl.apply(ComponentTagHandlerDelegateImpl.java:175)
	at javax.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:120)
	at javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:95)
	at javax.faces.view.facelets.DelegatingMetaTagHandler.applyNextHandler(DelegatingMetaTagHandler.java:137)
	at com.sun.faces.facelets.tag.jsf.ComponentTagHandlerDelegateImpl.apply(ComponentTagHandlerDelegateImpl.java:202)
	at javax.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:120)
	at javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:95)
	at com.sun.faces.facelets.tag.jsf.core.ViewHandler.apply(ViewHandler.java:225)
	at javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:95)
	at com.sun.faces.facelets.compiler.NamespaceHandler.apply(NamespaceHandler.java:93)
	at com.sun.faces.facelets.compiler.EncodingHandler.apply(EncodingHandler.java:87)
	at com.sun.faces.facelets.impl.DefaultFacelet.apply(DefaultFacelet.java:161)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.buildView(FaceletViewHandlingStrategy.java:1006)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:99)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:659)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:100)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by dmakariev** [comment]
Hi Andy, 

I’ve quickly tried the sample app,

I was able to run it with the following versions 

<spring-boot.version>1.2.6.RELEASE</spring-boot.version>
 <tomcat.version>8.0.23</tomcat.version>

         <dependency>
            <groupId>com.sun.faces</groupId>
            <artifactId>jsf-api</artifactId>
            <version>2.2.12</version>
        </dependency>
        <dependency>
            <groupId>com.sun.faces</groupId>
            <artifactId>jsf-impl</artifactId>
            <version>2.2.12</version>
        </dependency>

Although there was an issue with : bootsfaces :

2015-10-15 11:17:27.260 ERROR 31464 --- [nio-8080-exec-1] j.e.r.webcontainer.jsf.application       : JSF1068: Cannot instantiate component with component-type net.bootsfaces.component.NavBar
2015-10-15 11:17:27.270 ERROR 31464 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[Faces Servlet]        : Servlet.service() for servlet [Faces Servlet] in context with path [] threw exception [Expression Error: Named Object: net.bootsfaces.component.NavBar not found.] with root cause

so I had to comment it from the pom.xml 

I’m attaching also a patch file 
I hope that helps



Best Regards:
Dimitar

**Comment by persapiens** [comment]
Hi @philwebb ,

I have created [Jsf Spring Boot Starter ](https://github.com/persapiens/jsf-spring-boot-starter) that autoconfigure mojarra, primefaces and omnifaces, including configuration properties for them. Jsf web files (xhtml, css, js, images) should be located at **src/main/resources/WEB-INF/resources** folder. 
[Version 1.0.0](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22jsf-spring-boot-starter%22) is released at Maven Central, using Spring Boot version 1.3.5.

I have also created [Jsf Spring Boot Starter Example](https://github.com/persapiens/jsf-spring-boot-starter-example) project to show mojarra jsf and primefaces running inside an packaged jar spring boot application.

**Comment by philwebb** [comment]
Thanks @persapiens

**Comment by philwebb** [comment]
I've opened #5932 to add it to the third-party starter list

**Comment by persapiens** [comment]
It was a pleasure @philwebb

**Comment by snicoll** [comment]
Is that issue still relevant with the JSF starter @persapiens has created?

**Comment by persapiens** [comment]
Hi @snicoll, I think [JoinFaces](https://github.com/joinfaces/joinfaces) can be used to solve this issue. It was treated [here](https://github.com/joinfaces/joinfaces/issues/66). 

Now, there are a set of Spring Boot Starters combining possibilities to integrate Spring with many technologies related to JSF. It autoconfigures [PrimeFaces](http://primefaces.org/), [PrimeFaces Extensions](http://primefaces-extensions.github.io/), [BootsFaces](http://bootsfaces.net/), [ButterFaces](http://butterfaces.org/), [RichFaces](https://github.com/richfaces/richfaces), [OmniFaces](http://omnifaces.org/), [AngularFaces](http://angularfaces.net/), [Mojarra](https://javaserverfaces.java.net/) and [MyFaces](http://myfaces.apache.org/) libraries to run at embedded [Tomcat](http://tomcat.apache.org/), [Jetty](http://www.eclipse.org/jetty) or [Undertow](http://undertow.io) servlet containers.

It is my first strong involvement with open source. It has been a fantastic experience learning with people around the world.

**Comment by snicoll** [comment]
Thanks for confirming @persapiens and thanks for the starters you've initiated!
