### ISSUE TITLE
SpringBootTestContextBootstrapper logs exception if spring-tx is not on the class path

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#32249]
It's probably harmless, but since DEBUG logging is always on by default when tests are starting up it is definitely distracting.

Example:

```
14:03:56.470 [main] DEBUG org.springframework.boot.test.context.SpringBootTestContextBootstrapper - Could not load default TestExecutionListener [org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener]. Specify custom listener classes or make the default listener classes available.
java.lang.NoClassDefFoundError: org/springframework/transaction/interceptor/TransactionAttribute
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.base/java.lang.Class.getConstructors(Unknown Source)
	at org.springframework.core.io.support.SpringFactoriesLoader$FactoryInstantiator.findConstructor(SpringFactoriesLoader.java:406)
...
```

**Comment by snicoll** [comment]
See https://github.com/spring-projects/spring-framework/issues/28962

**Comment by dsyer** [comment]
I was using Boot M4 (with SFW M5). Thanks for the link - snapshots fixed it.
