### ISSUE TITLE
spring-boot-starter-jersey doesn't support multiple Jersey context

### ISSUE THREAD

**Issue by RaphC** [spring-projects/spring-boot#3260]
Hi,

I need to have 2 differents Jersey context which enable/disable certain filters and splitted by context-root. Actually I'm using `spring-boot-starter-jersey` and declare a `@Component` that extends `ResourceConfig`. When I try to add another Jersey `ResourceConfig` with a different `@ApplicationPath` I'm facing a issue

```
Wrapped by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'auditFilterRegistration' defined in class path resource [com/bouygtel/swad/recouvrement/appcontext/RecouvrementSpringConfiguration.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.springframework.boot.context.embedded.ServletRegistrationBean]: : Error creating bean with name 'org.springframework.boot.autoconfigure.jersey.JerseyAutoConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.glassfish.jersey.server.ResourceConfig org.springframework.boot.autoconfigure.jersey.JerseyAutoConfiguration.config; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [org.glassfish.jersey.server.ResourceConfig] is defined: expected single matching bean but found 2: recouvrementJerseyConfiguration,recouvrementSMJerseyConfiguration; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.jersey.JerseyAutoConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.glassfish.jersey.server.ResourceConfig org.springframework.boot.autoconfigure.jersey.JerseyAutoConfiguration.config; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [org.glassfish.jersey.server.ResourceConfig] is defined: expected single matching bean but found 2: recouvrementJerseyConfiguration,recouvrementSMJerseyConfiguration
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:464) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1119) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1014) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757) ~[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480) ~[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686) ~[spring-boot-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320) ~[spring-boot-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at org.springframework.boot.test.SpringApplicationContextLoader.loadContext(SpringApplicationContextLoader.java:103) ~[spring-boot-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at org.springframework.test.context.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:68) ~[spring-test-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.test.context.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:86) ~[spring-test-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	... 27 common frames omitted
```

So the `JerseyAutoConfiguration` is designed for only one `ResourceConfig` `@Component`

Is it possible to extend it in order to handle multiple jersey context

Thanks

**Comment by pandrez** [comment]
I have the same problem. Does this issue really make sense or are we doing something wrong?

**Comment by philwebb** [comment]
I'm not a Jersey expert so I'm not sure what the recommended way of configuring this would be. It looks like we currently add a single `org.glassfish.jersey.servlet.ServletContainer` and that can only manage a single `ResourceConfig`. 

Do you have any examples of non-spring projects that have two `ResourceConfigs`?

/cc @dsyer @wilkinsona

**Comment by wilkinsona** [comment]
My understanding is that a "traditional" Jersey application would achieve this by configuring two `ServletContainer` instances with each managing its own `ResourceConfig`. We could, in theory, update `JerseyAutoConfiguration` to take a collection of `ResourceConfig` instances and register a servlet or filter for each but it would make things quite a big more complex.

Echoing @philwebb's request, @pandrez @RaphC can you point us to examples/documentation on the recommended way to do this when Spring Boot isn't involved?

**Comment by pandrez** [comment]
@wilkinsona You are right! Each `ServletContainer` manages its own `ResourceConfig`. This way we can define for each `ResourceConfig` its own JaxRs `@Provider`s (for example, an `javax.ws.rs.extExceptionMapper` that maps an Exception to its corresponding JaxRS `Response`) which may be different across each `ResourceConfig`. I have never come across this requirement until now, with my Spring Boot project. I will investigate how to get over this problem without Spring Boot. Thank you for your attention!

**Comment by RaphC** [comment]
Hi,

This is my use case :
I want to publish a resource  in a secured way (the authorization is handled by a Jersey provider) for certain clients but I also want to expose this same resource without any authorization mechanism for others clients. Moreover I want to apply some treatment realized by others jersey providers/filters/writers (e.g filtering, auditing, linking, ) for certains clients and not for the other ones. My first idea is to load 2 jersey contexts with their own ResourceConfig which can be accessed from 2 différents uri.( /protected/my-reource and /unprotected/my-resource)

I hope my example I clear.

**Comment by wilkinsona** [comment]
Thanks, @RaphC. It's still not clear to me if what you're describing is the _recommended_ way to implement your use case. It sounds like it would work, but we wouldn't want to implement something that encourages people to use Jersey in an unusual way. Can you point us to any Jersey examples/documentation that covers this area?

**Comment by RaphC** [comment]
Here are different use cases I found on the web :

API versioning : http://stackoverflow.com/questions/11460977/multiple-jersey-servlets-in-one-single-web-xml
Expose services under multiple context : http://stackoverflow.com/questions/8550986/spring-jersey-how-to-expose-services-under-more-than-one-context

But no information on jersey doc about this case.

**Comment by wilkinsona** [comment]
Thanks, @RaphC.

The second answer to the question makes a very good point about two Jersey servlets leading to duplicate registration of any Jersey components in their application contexts. The solution is to use separate child application contexts for each separate Jersey servlet that you want to use. Unfortunately, that's beyond the scope of what you can achieve with Spring Boot's Jersey auto-configuration.

**Comment by RaphC** [comment]
No chance this feature will be supported in the future ?

**Comment by dsyer** [comment]
It seems to me to be too complicated to be called "autoconfig" (we try to make simple, mundane things easy, but if we start to stray into unusual use cases the code gets hard to understand and maintain). If you want to propose an implementation, please feel free to do so and we can discuss the merits separately.

**Comment by RaphC** [comment]
Thanks @dsyer 

I'll work on it then discuss it later.

Regards
