### ISSUE TITLE
Upgrade Reactor 2.0.4 (compatible with JsonPath 2.0)

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#3264]
Reactor 2.0.3 isn't 100% compatible with JsonPath 2.0 and `JsonPathSelector.matches` can fail with an `AbstractMethodError`:

```
java.lang.AbstractMethodError: reactor.bus.selector.JsonPathSelector$Jackson2JsonProvider.unwrap(Ljava/lang/Object;)Ljava/lang/Object;
at com.jayway.jsonpath.internal.token.EvaluationContextImpl.getValue(EvaluationContextImpl.java:139)
at com.jayway.jsonpath.internal.token.EvaluationContextImpl.getValue(EvaluationContextImpl.java:127)
at com.jayway.jsonpath.internal.token.PredicateContextImpl.evaluate(PredicateContextImpl.java:53)
at com.jayway.jsonpath.Criteria.evaluateIfPath(Criteria.java:379)
at com.jayway.jsonpath.Criteria.eval(Criteria.java:405)
at com.jayway.jsonpath.Criteria.apply(Criteria.java:364)
at com.jayway.jsonpath.Filter$SingleFilter.apply(Filter.java:80)
at com.jayway.jsonpath.internal.token.PredicatePathToken.accept(PredicatePathToken.java:80)
at com.jayway.jsonpath.internal.token.PredicatePathToken.evaluate(PredicatePathToken.java:66)
at com.jayway.jsonpath.internal.token.PathToken.handleObjectProperty(PathToken.java:71)
at com.jayway.jsonpath.internal.token.PropertyPathToken.evaluate(PropertyPathToken.java:44)
at com.jayway.jsonpath.internal.token.RootPathToken.evaluate(RootPathToken.java:53)
at com.jayway.jsonpath.internal.CompiledPath.evaluate(CompiledPath.java:53)
at com.jayway.jsonpath.internal.CompiledPath.evaluate(CompiledPath.java:61)
at com.jayway.jsonpath.JsonPath.read(JsonPath.java:178)
at com.jayway.jsonpath.JsonPath.read(JsonPath.java:304)
at reactor.bus.selector.JsonPathSelector.read(JsonPathSelector.java:88)
at reactor.bus.selector.JsonPathSelector.matches(JsonPathSelector.java:69)
```

**Comment by philwebb** [comment]
Has this been raised with the Reactor team?

/cc @jbrisbin

**Comment by wilkinsona** [comment]
Sorry, I should have linked to the PR I submitted and that Jon has already merged: https://github.com/reactor/reactor/pull/494. Thanks, Jon!

**Comment by philwebb** [comment]
Looks like this made it into Reactor 2.0.4.

**Comment by philwebb** [comment]
Unfortunately Bintray sync is failing so 2.0.4 isn't in central yet.
