### ISSUE TITLE
Spring boot 3-Rc1 native:compile (graalvm22-jdk17) on windows10 fails with error java.lang.LayerInstantiationException: Package com.oracle.svm.util in both module org.graalvm.nativeimage.pointsto and module org.graalvm.nativeimage.base

### ISSUE THREAD

**Issue by sarathchand09** [spring-projects/spring-boot#32847]
I am using spring intializer(image attached) , the bleow are the settings i got and i did nothing ,
 but mvn -Pnative native:compile -DskipTests
, but the build fails 

![image](https://user-images.githubusercontent.com/7546584/197361991-fa0dc328-6910-4463-ba56-b3b6ba246e31.png)

ERROR
[DEBUG] ImageClasspath Entry: org.apache.tomcat.embed:tomcat-embed-el:jar:10.0.27:compile (file:///C:/Users/S7MUISO/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/10.0.27/tomcat-embed-el-10.0.27.jar)
[DEBUG] ImageClasspath Entry: ch.qos.logback:logback-core:jar:1.4.4:compile (file:///C:/Users/S7MUISO/.m2/repository/ch/qos/logback/logback-core/1.4.4/logback-core-1.4.4.jar)
[DEBUG] ImageClasspath Entry: org.yaml:snakeyaml:jar:1.33:compile (file:///C:/Users/S7MUISO/.m2/repository/org/yaml/snakeyaml/1.33/snakeyaml-1.33.jar)
[DEBUG] ImageClasspath Entry: org.springframework:spring-web:jar:6.0.0-RC2:compile (file:///C:/Users/S7MUISO/.m2/repository/org/springframework/spring-web/6.0.0-RC2/spring-web-6.0.0-RC2.jar)
[DEBUG] ImageClasspath Entry: org.springframework:spring-beans:jar:6.0.0-RC2:compile (file:///C:/Users/S7MUISO/.m2/repository/org/springframework/spring-beans/6.0.0-RC2/spring-beans-6.0.0-RC2.jar)
[DEBUG] ImageClasspath Entry: org.springframework:spring-jcl:jar:6.0.0-RC2:compile (file:///C:/Users/S7MUISO/.m2/repository/org/springframework/spring-jcl/6.0.0-RC2/spring-jcl-6.0.0-RC2.jar)
[INFO] Executing: C:\Users\S7MUISO\workspace\graalvm-ce-java17-22.2.0\bin\native-image.cmd @target\tmp\native-image-4562211029154872855.args
Error occurred during initialization of boot layer
java.lang.LayerInstantiationException: Package com.oracle.svm.util in both module org.graalvm.nativeimage.pointsto and module org.graalvm.nativeimage.base
Error: Image build request failed with exit status 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.736 s
[INFO] Finished at: 2022-10-22T22:47:51+02:00
[INFO] Final Memory: 30M/120M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.graalvm.buildtools:native-maven-plugin:0.9.16:compile (default-cli) on project demo: Execution of C:\Users\S7MUISO\workspace\graalvm-ce-java17-22.2.0\bin\native-image.cmd @target\tmp\native-image-4562211029154872855.args returned non-zero result -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.graalvm.buildtools:native-maven-plugin:0.9.16:compile (default-cli) on project demo: Execution of C:\Users\S7MUISO\workspace\graalvm-ce-java17-22.2.0\bin\native-image.cmd @target\tmp\native-image-4562211029154872855.args returned non-zero result
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Execution of C:\Users\S7MUISO\workspace\graalvm-ce-java17-22.2.0\bin\native-image.cmd @target\tmp\native-image-4562211029154872855.args returned non-zero result
        at org.graalvm.buildtools.maven.AbstractNativeImageMojo.buildImage(AbstractNativeImageMojo.java:403)
        at org.graalvm.buildtools.maven.NativeCompileNoForkMojo.execute(NativeCompileNoForkMojo.java:96)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
[ERROR]
[ERROR]

**Comment by wilkinsona** [comment]
It looks like you're using Graal 22.2. We require 22.3 which is available from Bellsoft [here](https://bell-sw.com/pages/downloads/native-image-kit/#/nik-22-17-ea). GraalVM CE builds will also be available from [here](https://www.graalvm.org/downloads/) in the coming days.
