### ISSUE TITLE
Problems with @TestPropertySource with cached Spring context

### ISSUE THREAD

**Issue by johanhaleby** [spring-projects/spring-boot#3287]
I have a base class for all my integration tests that looks like this:

```java
@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(classes = MyContextConfig.class)
@WebAppConfiguration
@IntegrationTest("server.port:0")
@ActiveProfiles("itest")
public class ITestSupport {
   ... 
}
```

For example:

```java
public class MyITest extends ITestSupport {
   ... 
}
```

In a new integration test I'm writing I want to test that my Hystrix setup works as expected. Thus I want to change the property that controls the Hystrix execution timeout to simulate that the circuit breaker opens. I do this using the `@TestPropertySource` annotation like this:

```java
@TestPropertySource(properties = {"hystrix.timeout=5"})
public class MyHystrixITest extends ITestSupport {
   ... 
}
```

When I run MyHystrixITest standalone from Intellij everything works as expected. However when I run all my integration tests as a suite (for example when MyITest is executed before MyHystrixITest) I end up with this error:

```java
2015-06-19 08:29:40.686 ERROR 58158 --- [           main] o.a.coyote.http11.Http11NioProtocol      : Failed to start end point associated with ProtocolHandler ["http-nio-8083"]

java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:436)
	at sun.nio.ch.Net.bind(Net.java:428)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:338)
	at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:760)
	at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:472)
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:986)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:237)
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.addPreviouslyRemovedConnectors(TomcatEmbeddedServletContainer.java:186)
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:149)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:288)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:483)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration.createChildManagementContext(EndpointWebMvcAutoConfiguration.java:223)
	at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration.afterSingletonsInstantiated(EndpointWebMvcAutoConfiguration.java:145)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:775)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
	at org.springframework.boot.test.SpringApplicationContextLoader.loadContext(SpringApplicationContextLoader.java:103)
	at org.springframework.test.context.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:68)
	at org.springframework.test.context.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:86)
	at org.springframework.test.context.DefaultTestContext.getApplicationContext(DefaultTestContext.java:72)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:117)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:212)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:200)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:259)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:261)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:219)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:83)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:68)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:163)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

I.e. the port is already in use. This might actually not be a problem (but it *might* be so I'm including it here anyway) since I have indeed set the management port to 8083 in the `itest` profile. However if I change the management port for my hystrix itest like this:

```java
@TestPropertySource(properties = {"hystrix.timeout=5", "management.port=8084"})
public class MyHystrixITest extends ITestSupport {
   ... 
}
```

The value specified in `hystrix.timeout` is not applied and my test fails. I suppose that this doesn't have to be a bug either since if I add `@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_CLASS)` to `MyITest` then `MyHystrixITest` works as expected. The problem is that I have a lot of tests like `MyITest` and using `DirtiesContext` for each one of them just to make `MyHystrixITest` work is not feasible since it will severely slow down the test suite execution.  So my questions can be summarized as this:

<ol>
 <li>Is this expected behavior?</li>
 <li>What's my best option to solve this?</li>
</ol>

**Comment by wilkinsona** [comment]
I think this is working as designed.

Spring Framework's testing support uses [numerous different sources](http://docs.spring.io/spring/docs/current/spring-framework-reference/html/testing.html#testcontext-ctx-management-caching) when generating a cache key for a context. Your use of `@TestPropertySource` on `MyHystrixTest` will cause it to have a different key to `MyITest`. This results in two contexts being started, both of which try to listen on `8083`.

Do you have to use a specific management port? I see that you've set `server.port: 0`. Using any free port, or even the same free port, for the management endpoints would solve this I believe.

**Comment by johanhaleby** [comment]
Alright so I've tried to change my base class to look like this:

```java
@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(classes = MyContextConfig.class)
@WebAppConfiguration
@IntegrationTest({"server.port:0", "management.port:0"})
@ActiveProfiles("itest")
public class ITestSupport {
   ... 
}
```

While this avoids the `java.net.BindException: Address already in use` exception, the `MyHystrixITest` will still not apply the settings I've made in `@TestPropertySource` (`@TestPropertySource(properties = {"parkster.timeout=5"}`). The class now looks like this:

```java
@TestPropertySource(properties = {"hystrix.timeout=5"})
public class MyHystrixITest extends ITestSupport {
   ... 
}
````

I've also removed the `management.port` property (which was previously set to 8083) from the `application-itest.yml` file just in case.

**Comment by wilkinsona** [comment]
@johanhaleby Can you please put together a small sample that reproduces the problem? I've just tried to recreate it, but a test annotated with `@TestPropertySource` is causing a new application context to be created and the environment contains the configured properties as expected.

**Comment by johanhaleby** [comment]
@wilkinsona I've looked a bit closer and you're indeed right. I just presumed that the property wasn't set since my test was still failing. Perhaps this is a different issue altogether but what's the difference between a new application context being created (as the case when using `@TestPropertySource`) and using `@DirtiesContext`? My test seem to work when using `@DirtiesContext` + `@TestPropertySource` but not when using only using `@TestPropertySource`? Thanks a lot for your help so far.

**Comment by wilkinsona** [comment]
If you only used `@TestPropertySource`, but used it identically across multiple tests, then all of those tests would share an application context that will be cached. If you use `@DirtiesContext` then the context, even if it had been cached by a previous test, will be closed and discarded.

**Comment by johanhaleby** [comment]
Thanks a lot for your support.
