### ISSUE TITLE
Kotlin Auto Configuration Needs Reflection Hints

### ISSUE THREAD

**Issue by akefirad** [spring-projects/spring-boot#33234]
Having a simple Kotlin Spring Boot application ([link](https://start.spring.io/#!type=gradle-project&language=kotlin&platformVersion=3.0.0-RC2&packaging=jar&jvmVersion=17&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=native,web)), adding any auto-configuration with a non-bean method (e.g. a private auxiliary method) throws `ClassNotFoundException`:
```kotlin
@SpringBootApplication(proxyBeanMethods = false)
// @ImportAutoConfiguration(MyJavaConfiguration::class)
@ImportAutoConfiguration(MyKotlinConfiguration::class)
@ImportRuntimeHints(NativeRuntimeHints::class)
class Application

fun main(args: Array<String>) {
    runApplication<Application>(*args)
}

@AutoConfiguration
class MyKotlinConfiguration {
    @Bean
    fun foo() = Foo(bar())

    private fun bar() = Bar()
}

class Foo(private val bar: Bar) {
    fun foo() = "Hello ${bar.bar()}"
}

class Bar {
    fun bar(): String = "bar"
}
```
Stacktrace:
```
java.lang.ClassNotFoundException: com.example.demo.Bar
        at java.base@19.0.1/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:52) ~[test-kotlin-native:na]
        at java.base@19.0.1/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
        at java.base@19.0.1/java.lang.ClassLoader.loadClass(ClassLoader.java:132) ~[test-kotlin-native:na]
        at kotlin.reflect.jvm.internal.KDeclarationContainerImpl.parseType(KDeclarationContainerImpl.kt:273) ~[test-kotlin-native:1.7.20-release-201(1.7.20)]
        at kotlin.reflect.jvm.internal.KDeclarationContainerImpl.loadReturnType(KDeclarationContainerImpl.kt:288) ~[test-kotlin-native:1.7.20-release-201(1.7.20)]
        at kotlin.reflect.jvm.internal.KDeclarationContainerImpl.findMethodBySignature(KDeclarationContainerImpl.kt:198) ~[test-kotlin-native:1.7.20-release-201(1.7.20)]
        at kotlin.reflect.jvm.internal.KFunctionImpl$caller$2.invoke(KFunctionImpl.kt:68) ~[na:na]
        at kotlin.reflect.jvm.internal.KFunctionImpl$caller$2.invoke(KFunctionImpl.kt:61) ~[na:na]
        at kotlin.reflect.jvm.internal.ReflectProperties$LazyVal.invoke(ReflectProperties.java:63) ~[na:na]
        at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32) ~[test-kotlin-native:1.7.20-release-201(1.7.20)]
        at kotlin.reflect.jvm.internal.KFunctionImpl.getCaller(KFunctionImpl.kt:61) ~[na:na]
        at kotlin.reflect.jvm.ReflectJvmMapping.getJavaMethod(ReflectJvmMapping.kt:63) ~[na:na]
        at kotlin.reflect.jvm.ReflectJvmMapping.getKotlinFunction(ReflectJvmMapping.kt:136) ~[na:na]
        at org.springframework.core.MethodParameter$KotlinDelegate.getGenericReturnType(MethodParameter.java:914) ~[na:na]
        at org.springframework.core.MethodParameter.getGenericParameterType(MethodParameter.java:510) ~[test-kotlin-native:6.0.0-RC4]
        at org.springframework.core.SerializableTypeWrapper$MethodParameterTypeProvider.getType(SerializableTypeWrapper.java:291) ~[na:na]
        at org.springframework.core.SerializableTypeWrapper.forTypeProvider(SerializableTypeWrapper.java:107) ~[na:na]
        at org.springframework.core.ResolvableType.forType(ResolvableType.java:1413) ~[test-kotlin-native:6.0.0-RC4]
        at org.springframework.core.ResolvableType.forMethodParameter(ResolvableType.java:1334) ~[test-kotlin-native:6.0.0-RC4]
        at org.springframework.core.ResolvableType.forMethodParameter(ResolvableType.java:1316) ~[test-kotlin-native:6.0.0-RC4]
        at org.springframework.core.ResolvableType.forMethodParameter(ResolvableType.java:1283) ~[test-kotlin-native:6.0.0-RC4]
        at org.springframework.core.ResolvableType.forMethodReturnType(ResolvableType.java:1228) ~[test-kotlin-native:6.0.0-RC4]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:814) ~[test-kotlin-native:6.0.0-RC4]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:681) ~[test-kotlin-native:6.0.0-RC4]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:652) ~[test-kotlin-native:6.0.0-RC4]
        at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1632) ~[test-kotlin-native:6.0.0-RC4]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:559) ~[test-kotlin-native:6.0.0-RC4]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:531) ~[test-kotlin-native:6.0.0-RC4]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:106) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:745) ~[test-kotlin-native:6.0.0-RC4]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:565) ~[test-kotlin-native:6.0.0-RC4]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[test-kotlin-native:3.0.0-RC2]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[test-kotlin-native:3.0.0-RC2]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432) ~[test-kotlin-native:3.0.0-RC2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[test-kotlin-native:3.0.0-RC2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[test-kotlin-native:3.0.0-RC2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) ~[test-kotlin-native:3.0.0-RC2]
        at com.example.demo.ApplicationKt.main(Application.kt:25) ~[test-kotlin-native:na]
```
The root cause seems to be the way `java.lang.reflect.Method#kotlinFunction` getter is implemented. Adding the below hint resolve the issue:
```kotlin
class NativeRuntimeHints : RuntimeHintsRegistrar {
    override fun registerHints(hints: RuntimeHints, classLoader: ClassLoader?) {
        val t = MyKotlinConfiguration::class.java
        hints.reflection().registerType(t, MemberCategory.INTROSPECT_DECLARED_METHODS)
    }
}
```
Needless to say, there's no such issue with Java auto-configuration files.

**Comment by snicoll** [comment]
I don't really understand why you think this is related to auto-configuration. Looking at the call stack, there's nothing Spring Boot specific so I expect a regular `@Configuration` to have the same problem. Moving to framework.
