### ISSUE TITLE
Get stackoverflow error when doing simple get request

### ISSUE THREAD

**Issue by gaoxingliang** [spring-projects/spring-boot#33293]
Hi 
I'm using latest springboot-starter-web version `2.7.5`. but I got a stackoverflow error when using the `@Controller` annotation.

I **DON'T** see the error when using `@RestController`. 

## Reproduce steps:
there are three class files:
1. Main.java
```
package org.test.example;

import org.springframework.boot.*;
import org.springframework.boot.autoconfigure.*;

@SpringBootApplication
public class Main {
    public static void main(String[] args) {
        SpringApplication.run(Main.class, args);
    }
}
```
2. a interface `ControllerI`
```
package org.test.example;

import org.springframework.web.bind.annotation.*;

public interface ControllerI {
    @GetMapping("/greet/{user}")
    String greeting(@PathVariable("user") String user);
}
```
3. a simple impl class:
```
package org.test.example;

import org.springframework.stereotype.*;

@Controller
//@RestController
public class ControllerImpl implements ControllerI{
    @Override
    public String greeting(String user) {
        return String.format("Hello " + user);
    }
}

```
and when I using `curl http://127.0.0.1:8080/greet/myname`, it shows stackoverflowerror:

```
	at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:244) ~[tomcat-embed-core-9.0.68.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationHttpRequest.getSession(ApplicationHttpRequest.java:585) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
	at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:244) ~[tomcat-embed-core-9.0.68.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationHttpRequest.getSession(ApplicationHttpRequest.java:585) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
	at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:244) ~[tomcat-embed-core-9
```

**Comment by gaoxingliang** [comment]
Hi @wilkinsona Thanks for your explanation. Yes. The view is not found. I think the embedded tomcat should return a 404 error or some other error instead of a stackoverflow error. I will check more about the source code.

**Comment by gaoxingliang** [comment]
I found the root cause is when we search the view in class [RequestMappingHandlerAdapter](https://github.com/spring-projects/spring-framework/blob/5.0.x/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/annotation/RequestMappingHandlerAdapter.java#L893)
It will try to find the matched modelAndView object. and because my url use a path variable and this cause the recursive call.

so for my case, 
1. if the initial request is `/greet/edward` and then it will try to find the view `edward` under `/greet`. and then it goes into the controller and the controller will return :
`Helloedward` (see the source code [here](https://github.com/spring-projects/spring-framework/blob/5.0.x/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/annotation/ServletInvocableHandlerMethod.java#L102) )and 
2. then it will dispatch to the `/greet/Helloedward`  and again, it will dispatch (by setting the mav.viewName) to `/greet/HelloHelloedward` (in `DispatcherServlet` and it will try to render it again in [`InternalResourceView`](https://github.com/spring-projects/spring-framework/blob/d159cb65915840b2dc2297ee6b40309b8aa5d2aa/spring-webmvc/src/main/java/org/springframework/web/servlet/view/InternalResourceView.java#L170))




and this cause the infinite loop.
