### ISSUE TITLE
java.lang.ClassNotFoundException: org.junit.platform.launcher.TestExecutionListener

### ISSUE THREAD

**Issue by pedrorlmarques** [spring-projects/spring-boot#33397]
Given the following build.gradle
```
plugins {
	id 'java'
	id 'org.springframework.boot' version '3.0.0'
	id 'io.spring.dependency-management' version '1.1.0'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '17'

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.kafka:spring-kafka'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.kafka:spring-kafka-test'
}

tasks.named('test') {
	useJUnitPlatform()
}
```

If we add the  **spring-kafka-test** dependency on the classpath the junit5 stops working by throwing the following exception.

```
Caused by: java.lang.ClassNotFoundException: org.junit.platform.launcher.TestExecutionListener
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
```

Excepted results
- Junit5 is able to run with success

**Comment by wilkinsona** [comment]
Duplicates https://github.com/spring-projects/spring-kafka/issues/2490.
