### ISSUE TITLE
Add support for @StepScope

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-boot#335]
While trying to use step scopes on my yarn stuff I faced issues which ultimately went down to below error:

``` text
Scope 'step' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No context holder available for step scope
```

Step scopes are usually enable by user so I don't know how well it sits in boot configuration, but if enabled, whole job execution chain within a context needs to be step scoped. At least that's what I think if I've understood scoping correctly.

I assume that we need to have a story how JobLauncherCommandLineRunner can be configured using a step scope?

**Comment by JavaNeed** [comment]
I am getting the below error...

```org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.jobRepository': Scope 'step' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No context holder available for step scope
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:355)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.aop.target.SimpleBeanTargetSource.getTarget(SimpleBeanTargetSource.java:35)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:192)
	at com.sun.proxy.$Proxy1.getLastJobExecution(Unknown Source)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:98)
	at CustomerFileGenerationMain.main(CustomerFileGenerationMain.java:28)
Caused by: java.lang.IllegalStateException: No context holder available for step scope
	at org.springframework.batch.core.scope.StepScope.getContext(StepScope.java:167)
	at org.springframework.batch.core.scope.StepScope.get(StepScope.java:99)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:340)
	... 6 more```

for the below XML file

**Comment by philwebb** [comment]
@JavaNeed This issue has been closed since 2015. If you have a general problem, please ask on stackoverflow.com. If you think you've found a bug then please open a new issue with a small sample that reproduces it. Thanks!
