### ISSUE TITLE
LoggingApplicationListener Improperly reading CommandLine arguments

### ISSUE THREAD

**Issue by madorb** [spring-projects/spring-boot#3366]
We are deploying a Spring Boot app to Azure (don't ask). It has been working fine until Friday when it started failing on startup with:

```
Caused by: java.lang.IllegalStateException: java.io.FileNotFoundException: D:\Windows\system32\-Djava.util.logging.config.file="D:\Program Files (x86)\apache-tomcat-7.0.50\conf\logging.properties" (The filename, directory name, or volume label syntax is incorrect)
	at org.springframework.boot.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:215)
	at org.springframework.boot.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:184)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:164)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:145)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:119)
	at org.springframework.boot.context.event.EventPublishingRunListener.publishEvent(EventPublishingRunListener.java:111)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:65)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:273)
	at org.springframework.boot.context.web.SpringBootServletInitializer.run(SpringBootServletInitializer.java:130)
	at org.springframework.boot.context.web.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:110)
	at org.springframework.boot.context.web.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:69)
	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:175)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5444)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
```

It appears that spring is incorrectly interpreting the environment variable automatically set in azure:
 `JAVA.UTIL.LOGGING.CONFIG.FILE=D:\Program Files (x86)\apache-tomcat-7.0.50\conf\logging.properties`

Though I am still baffled about where the `D:\Windows\system32` is coming from. 

For reference here are the tomcat arguments that azure forces upon startup:

```
AZURE_TOMCAT7_CMDLINE=-Dport.http=%HTTP_PLATFORM_PORT% -Djava.util.logging.config.file="D:\Program Files (x86)\apache-tomcat-7.0.50\conf\logging.properties" -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Dsite.logdir="d:/home/LogFiles/" -Dsite.tempdir="d:\home\site\workdir" -classpath "D:\Program Files (x86)\apache-tomcat-7.0.50\bin\bootstrap.jar;D:\Program Files (x86)\apache-tomcat-7.0.50\bin\tomcat-juli.jar" -Dcatalina.base="D:\Program Files (x86)\apache-tomcat-7.0.50"  -Djava.io.tmpdir="d:\home\site\workdir" org.apache.catalina.startup.Bootstrap
```

Rolling back to 1.3.0.M1 works exactly as expected.

**Comment by snicoll** [comment]
you were on `1.3.0.BUILD-SNAPSHOT` previously, right?

**Comment by madorb** [comment]
@snicoll That's correct, I had been using BUILD-SNAPSHOT up until today, as it broke sometime around ~ Friday. Reverting to M1 resolved the issue today. 

I haven't had a chance to dive into the commits that broke it, but i suspect it's got to be one of the ones on 6/25 or 6/26 here: 

https://github.com/spring-projects/spring-boot/commits/b68382f3ba2987a4c863fc5876e1e305212673e6/spring-boot/src/main/java/org/springframework/boot/logging/LoggingApplicationListener.java

**Comment by wilkinsona** [comment]
I've reproduced this, but I'm not much closer to figuring out the cause. When running in Azure, this is the environment:

```
{USERPROFILE=D:\local\UserProfile, WEBSITE_OWNER_NAME=72b4e0c7-dab3-4bd6-85ec-ed3e80bd3de5+WestEuropewebspace, JAVA_HOME=D:\Program Files\Java\jdk1.7.0_51, REMOTEDEBUGGINGBITVERSION=vx86, WEBSITE_IIS_SITE_NAME=gh-3366, EXECUTABLE=d:\home\site\wwwroot\bin\apache-tomcat-7.0.52\bin\catalina.bat, SystemDrive=D:, CURRENT_DIR=D:\Windows\system32, _RUNJDB="D:\Program Files\Java\jdk1.7.0_51\bin\jdb", Path=D:\Program Files (x86)\nodejs\0.10.32;D:\Windows\system32;D:\Windows;D:\Windows\System32\Wbem;D:\Windows\System32\WindowsPowerShell\v1.0\;D:\Users\Administrator\AppData\Roaming\npm;D:\Program Files (x86)\nodejs\;d:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;D:\Program Files (x86)\Mercurial\;D:\Program Files (x86)\PHP\v5.4;D:\Python27;, WEBSITE_SCM_SEPARATE_STATUS=1, WEBSITE_HTTPLOGGING_RETENTION_DAYS=1, PROCESSOR_REVISION=2d07, ScmType=None, USERDOMAIN=WORKGROUP, AZURE_JETTY9_HOME=D:\Program Files (x86)\jetty-distribution-9.1.0.v20131115, ALLUSERSPROFILE=D:\local\ProgramData, WEBSOCKET_CONCURRENT_REQUEST_LIMIT=5, LOGGING_CONFIG=-Djava.util.logging.config.file="d:\home\site\wwwroot\bin\apache-tomcat-7.0.52\conf\logging.properties", APP_POOL_ID=gh-3366, JAVA_ENDORSED_DIRS=d:\home\site\wwwroot\bin\apache-tomcat-7.0.52\endorsed, ACTION=start, CATALINA_BASE=d:\home\site\wwwroot\bin\apache-tomcat-7.0.52, WEBSITE_INSTANCE_ID=4d637653fcd0369c9cf2733264d8243756488bb79f041ad936e301afdb7df9ba, TMP=D:\local\Temp, _EXECJAVA=start "Tomcat" "D:\Program Files\Java\jdk1.7.0_51\bin\java", LOCAL_EXPANDED=C:\DWASFiles\Sites\gh-3366, CommonProgramFiles=D:\Program Files\Common Files, PROMPT=$P$G, WEBSITE_SLOT_NAME=Production, LOGGING_MANAGER=-Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager, PROCESSOR_LEVEL=6, APPSETTING_WEBSITE_NODE_DEFAULT_VERSION=0.10.32, AZURE_TOMCAT7_HOME=D:\Program Files (x86)\apache-tomcat-7.0.50, CATALINA_TMPDIR=d:\home\site\wwwroot\bin\apache-tomcat-7.0.52\temp, LOCALAPPDATA=D:\local\LocalAppData, HTTP_PLATFORM_PORT=17000, COMPUTERNAME=RD000D3A21F983, SystemRoot=D:\Windows, APPSETTING_WEBSITE_SLOT_NAME=Production, USERNAME=RD000D3A21F983$, WEBSITE_COMPUTE_MODE=Shared, APPDATA=D:\local\AppData, ProgramData=D:\local\ProgramData, APPSETTING_WEBSITE_SITE_NAME=gh-3366, APP_POOL_CONFIG=C:\DWASFiles\Sites\gh-3366\Config\applicationhost.config, PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY, WEBSITE_NODE_DEFAULT_VERSION=0.10.32, WEBSITE_SITE_MODE=Limited, windows_tracing_logfile=, REMOTEDEBUGGINGVERSION=11.0.611103.400, ProgramFiles(x86)=D:\Program Files (x86), AZURE_TOMCAT7_CMDLINE=-Dport.http=%HTTP_PLATFORM_PORT% -Djava.util.logging.config.file="D:\Program Files (x86)\apache-tomcat-7.0.50\conf\logging.properties" -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Dsite.logdir="d:/home/LogFiles/" -Dsite.tempdir="d:\home\site\workdir" -classpath "D:\Program Files (x86)\apache-tomcat-7.0.50\bin\bootstrap.jar;D:\Program Files (x86)\apache-tomcat-7.0.50\bin\tomcat-juli.jar" -Dcatalina.base="D:\Program Files (x86)\apache-tomcat-7.0.50"  -Djava.io.tmpdir="d:\home\site\workdir" org.apache.catalina.startup.Bootstrap, windows_tracing_flags=, TEMP=D:\local\Temp, ProgramFiles=D:\Program Files, WEBSITE_AUTH_ENABLED=False, JAVA_OPTS=-Djava.net.preferIPv4Stack=true -Djava.util.logging.config.file="d:\home\site\wwwroot\bin\apache-tomcat-7.0.52\conf\logging.properties" -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager, WEBSITE_SKU=Free, SITE_BITNESS=x86, REWRITETABLE=, ProgramW6432=D:\Program Files, MAINCLASS=org.apache.catalina.startup.Bootstrap, PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 45 Stepping 7, GenuineIntel, WEBSITE_HTTPLOGGING_ENABLED=1, WEBSITE_SCM_ALWAYS_ON_ENABLED=0, APPSETTING_WEBSITE_AUTH_ENABLED=False, APPSETTING_WEBSITE_HTTPLOGGING_RETENTION_DAYS=1, PROCESSOR_ARCHITECTURE=AMD64, CLASSPATH=d:\home\site\wwwroot\bin\apache-tomcat-7.0.52\bin\bootstrap.jar;d:\home\site\wwwroot\bin\apache-tomcat-7.0.52\bin\tomcat-juli.jar, WEBSITE_HOSTNAME=gh-3366.azurewebsites.net, OS=Windows_NT, FP_NO_HOST_CHECK=NO, HOME_EXPANDED=C:\DWASFiles\Sites\gh-3366\VirtualDirectory0, APPSETTING_ScmType=None, JRE_HOME=D:\Program Files\Java\jdk1.7.0_51, CommonProgramW6432=D:\Program Files\Common Files, CATALINA_HOME=d:\home\site\wwwroot\bin\apache-tomcat-7.0.52, =D:=D:\Windows\System32, HOME=D:\home, REGION_NAME=West Europe, AZURE_JETTY9_CMDLINE=-Djava.net.preferIPv4Stack=true -Djetty.port=%HTTP_PLATFORM_PORT% -Djetty.base="D:\Program Files (x86)\jetty-distribution-9.1.0.v20131115" -Djetty.webapps="d:\home\site\wwwroot\webapps"  -jar "D:\Program Files (x86)\jetty-distribution-9.1.0.v20131115\start.jar" etc\jetty-logging.xml, AZURE_TOMCAT8_CMDLINE=-Dport.http=%HTTP_PLATFORM_PORT% -Djava.util.logging.config.file="D:\Program Files (x86)\apache-tomcat-8.0.23\conf\logging.properties" -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Dsite.logdir="d:/home/LogFiles/" -Dsite.tempdir="d:\home\site\workdir" -classpath "D:\Program Files (x86)\apache-tomcat-8.0.23\bin\bootstrap.jar;D:\Program Files (x86)\apache-tomcat-8.0.23\bin\tomcat-juli.jar" -Dcatalina.base="D:\Program Files (x86)\apache-tomcat-8.0.23"  -Djava.io.tmpdir="d:\home\site\workdir" org.apache.catalina.startup.Bootstrap, CATALINA_OPTS=-Dport.http=17000               , _RUNJAVA="D:\Program Files\Java\jdk1.7.0_51\bin\java", WEBSITE_SITE_NAME=gh-3366, windir=D:\Windows, AZURE_TOMCAT8_HOME=D:\Program Files (x86)\apache-tomcat-8.0.23, REMOTEDEBUGGINGPORT=, NUMBER_OF_PROCESSORS=4, PSModulePath=D:\Windows\system32\WindowsPowerShell\v1.0\Modules\;d:\Program Files\Microsoft Security Client\MpProvider\;D:\Program Files\Microsoft Message Analyzer\PowerShell\, PUBLIC=D:\Users\Public, APPSETTING_REMOTEDEBUGGINGVERSION=11.0.611103.400, CommonProgramFiles(x86)=D:\Program Files (x86)\Common Files, ComSpec=D:\Windows\system32\cmd.exe, TITLE=Tomcat}
```

And these are the system properties
```

{java.vendor=Oracle Corporation, sun.java.launcher=SUN_STANDARD, catalina.base=d:\home\site\wwwroot\bin\apache-tomcat-7.0.52, sun.management.compiler=HotSpot 64-Bit Tiered Compilers, port.http=17000, catalina.useNaming=true, os.name=Windows Server 2012, sun.boot.class.path=D:\Program Files\Java\jdk1.7.0_51\jre\lib\resources.jar;D:\Program Files\Java\jdk1.7.0_51\jre\lib\rt.jar;D:\Program Files\Java\jdk1.7.0_51\jre\lib\sunrsasign.jar;D:\Program Files\Java\jdk1.7.0_51\jre\lib\jsse.jar;D:\Program Files\Java\jdk1.7.0_51\jre\lib\jce.jar;D:\Program Files\Java\jdk1.7.0_51\jre\lib\charsets.jar;D:\Program Files\Java\jdk1.7.0_51\jre\lib\jfr.jar;D:\Program Files\Java\jdk1.7.0_51\jre\classes, java.util.logging.config.file=d:\home\site\wwwroot\bin\apache-tomcat-7.0.52\conf\logging.properties, sun.desktop=windows, java.vm.specification.vendor=Oracle Corporation, java.runtime.version=1.7.0_51-b13, user.name=RD000D3A21F983$, shared.loader=, tomcat.util.buf.StringCache.byte.enabled=true, java.naming.factory.initial=org.apache.naming.java.javaURLContextFactory, user.language=en, sun.boot.library.path=D:\Program Files\Java\jdk1.7.0_51\jre\bin, PID=23272, java.version=1.7.0_51, java.util.logging.manager=org.apache.juli.ClassLoaderLogManager, user.timezone=GMT, java.net.preferIPv4Stack=true, sun.arch.data.model=64, java.endorsed.dirs=d:\home\site\wwwroot\bin\apache-tomcat-7.0.52\endorsed, sun.cpu.isalist=amd64, sun.jnu.encoding=Cp1252, file.encoding.pkg=sun.io, package.access=sun.,org.apache.catalina.,org.apache.coyote.,org.apache.tomcat.,org.apache.jasper., file.separator=\, java.specification.name=Java Platform API Specification, java.class.version=51.0, user.country=US, java.home=D:\Program Files\Java\jdk1.7.0_51\jre, java.vm.info=mixed mode, os.version=6.2, path.separator=;, java.vm.version=24.51-b03, org.jboss.logging.provider=slf4j, user.variant=, java.awt.printerjob=sun.awt.windows.WPrinterJob, sun.io.unicode.encoding=UnicodeLittle, tomcat.util.scan.DefaultJarScanner.jarsToSkip=bootstrap.jar,commons-daemon.jar,tomcat-juli.jar,annotations-api.jar,el-api.jar,jsp-api.jar,servlet-api.jar,websocket-api.jar,catalina.jar,catalina-ant.jar,catalina-ha.jar,catalina-tribes.jar,jasper.jar,jasper-el.jar,ecj-*.jar,tomcat-api.jar,tomcat-util.jar,tomcat-coyote.jar,tomcat-dbcp.jar,tomcat-jni.jar,tomcat-spdy.jar,tomcat-i18n-en.jar,tomcat-i18n-es.jar,tomcat-i18n-fr.jar,tomcat-i18n-ja.jar,tomcat-juli-adapters.jar,catalina-jmx-remote.jar,catalina-ws.jar,tomcat-jdbc.jar,tools.jar,commons-beanutils*.jar,commons-codec*.jar,commons-collections*.jar,commons-dbcp*.jar,commons-digester*.jar,commons-fileupload*.jar,commons-httpclient*.jar,commons-io*.jar,commons-lang*.jar,commons-logging*.jar,commons-math*.jar,commons-pool*.jar,jstl.jar,geronimo-spec-jaxrpc*.jar,wsdl4j*.jar,ant.jar,ant-junit*.jar,aspectj*.jar,jmx.jar,h2*.jar,hibernate*.jar,httpclient*.jar,jmx-tools.jar,jta*.jar,log4j.jar,log4j-1*.jar,mail*.jar,slf4j*.jar,xercesImpl.jar,xmlParserAPIs.jar,xml-apis.jar,junit.jar,junit-*.jar,hamcrest*.jar,org.hamcrest*.jar,ant-launcher.jar,cobertura-*.jar,asm-*.jar,dom4j-*.jar,icu4j-*.jar,jaxen-*.jar,jdom-*.jar,jetty-*.jar,oro-*.jar,servlet-api-*.jar,tagsoup-*.jar,xmlParserAPIs-*.jar,xom-*.jar, awt.toolkit=sun.awt.windows.WToolkit, package.definition=sun.,java.,org.apache.catalina.,org.apache.coyote.,org.apache.tomcat.,org.apache.jasper., user.script=, java.naming.factory.url.pkgs=org.apache.naming, user.home=C:\, org.apache.catalina.startup.ContextConfig.jarsToSkip=, java.specification.vendor=Oracle Corporation, java.library.path=D:\Program Files\Java\jdk1.7.0_51\bin;D:\Windows\Sun\Java\bin;D:\Windows\system32;D:\Windows;D:\Program Files (x86)\nodejs\0.10.32;D:\Windows\system32;D:\Windows;D:\Windows\System32\Wbem;D:\Windows\System32\WindowsPowerShell\v1.0\;D:\Users\Administrator\AppData\Roaming\npm;D:\Program Files (x86)\nodejs\;d:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;D:\Program Files (x86)\Mercurial\;D:\Program Files (x86)\PHP\v5.4;D:\Python27;;., java.vendor.url=http://java.oracle.com/, org.apache.catalina.startup.TldConfig.jarsToSkip=tomcat7-websocket.jar, java.vm.vendor=Oracle Corporation, common.loader=${catalina.base}/lib,${catalina.base}/lib/*.jar,${catalina.home}/lib,${catalina.home}/lib/*.jar, java.runtime.name=Java(TM) SE Runtime Environment, sun.java.command=org.apache.catalina.startup.Bootstrap start, java.class.path=d:\home\site\wwwroot\bin\apache-tomcat-7.0.52\bin\bootstrap.jar;d:\home\site\wwwroot\bin\apache-tomcat-7.0.52\bin\tomcat-juli.jar, java.vm.specification.name=Java Virtual Machine Specification, java.vm.specification.version=1.7, catalina.home=d:\home\site\wwwroot\bin\apache-tomcat-7.0.52, sun.cpu.endian=little, sun.os.patch.level=, java.awt.headless=true, java.io.tmpdir=d:\home\site\wwwroot\bin\apache-tomcat-7.0.52\temp, java.vendor.url.bug=http://bugreport.sun.com/bugreport/, server.loader=, os.arch=amd64, java.awt.graphicsenv=sun.awt.Win32GraphicsEnvironment, java.ext.dirs=D:\Program Files\Java\jdk1.7.0_51\jre\lib\ext;D:\Windows\Sun\Java\lib\ext, user.dir=D:\Windows\system32, line.separator=
, java.vm.name=Java HotSpot(TM) 64-Bit Server VM, file.encoding=Cp1252, java.specification.version=1.7}
```

The failure would suggest that Spring environment contains a property named `logging.config`, but I can't tell where it's coming from. Running locally with the `AZURE_TOMCAT7_CMDLINE` environment variable doesn't trigger the problem. Neither does setting the `java.util.logging.config.file` system property.

I've recreated the problem on Azure so my next step is to debug it remotely. I'll do that tomorrow.

**Comment by wilkinsona** [comment]
The problem is that Azure sets a `LOGGING_CONFIG` environment variable with the value `-Djava.util.logging.config.file="d:\home\site\wwwroot\bin\apache-tomcat-7.0.52\conf\logging.properties"`. Boot gets this via the Spring Environment and it's then treated as a relative file path. `D:\Windows\system32` is the working directory which leads to Boot looking for a logging config file named `D:\Windows\system32\-Djava.util.logging.config.file="d:\home\site\wwwroot\bin\apache-tomcat-7.0.52\conf\logging.properties"`
