### ISSUE TITLE
 mvn -Pnative native:compile org.springframework.aop.framework.adapter.UnknownAdviceTypeException: Advice object [null] is neither a supported subinterface of [org.aopalli ance.aop.Advice] nor an [org.springframework.aop.Advisor]

### ISSUE THREAD

**Issue by admintertar** [spring-projects/spring-boot#33700]
```
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.shushang.x:x-cloud-booking-application:jar:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.springframework.boot:spring-boot-maven-plugin @ line 1
91, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] 
[INFO] -------------< com.shushang.x:x-cloud-booking-application >-------------
[INFO] Building x-cloud-booking-application 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] >>> native-maven-plugin:0.9.19:compile (default-cli) > package @ x-cloud-booking-application >>>
[WARNING] The POM for com.alibaba:druid:jar:1.2.6 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] 
[INFO] --- native-maven-plugin:0.9.19:add-reachability-metadata (add-reachability-metadata) @ x-cloud-booking-application ---
[INFO] [graalvm reachability metadata repository for ch.qos.logback:logback-classic:1.4.5]: Configuration directory not found. Trying latest version.
[INFO] [graalvm reachability metadata repository for ch.qos.logback:logback-classic:1.4.5]: Configuration directory is ch.qos.logback\logback-classic\1.4.1
[INFO] [graalvm reachability metadata repository for com.zaxxer:HikariCP:5.0.1]: Configuration directory is com.zaxxer\HikariCP\5.0.1
[INFO] [graalvm reachability metadata repository for com.mysql:mysql-connector-j:8.0.31]: Configuration directory is com.mysql\mysql-connector-j\8.0.31
[INFO] [graalvm reachability metadata repository for org.hibernate.validator:hibernate-validator:8.0.0.Final]: Configuration directory not found. Trying latest version. 
[INFO] [graalvm reachability metadata repository for org.hibernate.validator:hibernate-validator:8.0.0.Final]: Configuration directory is org.hibernate.validator\hiberna
te-validator\7.0.4.Final
[INFO] [graalvm reachability metadata repository for org.jboss.logging:jboss-logging:3.5.0.Final]: Configuration directory is org.jboss.logging\jboss-logging\3.5.0.Final
[INFO] [graalvm reachability metadata repository for io.undertow:undertow-core:2.3.2.Final]: Configuration directory not found. Trying latest version.
[INFO] [graalvm reachability metadata repository for io.undertow:undertow-core:2.3.2.Final]: Configuration directory is io.undertow\undertow-core\2.2.19.Final
[INFO] [graalvm reachability metadata repository for org.hdrhistogram:HdrHistogram:2.1.12]: Configuration directory is org.hdrhistogram\HdrHistogram\2.1.12
[INFO] [graalvm reachability metadata repository for io.netty:netty-buffer:4.1.86.Final]: Configuration directory not found. Trying latest version.
[INFO] [graalvm reachability metadata repository for io.netty:netty-buffer:4.1.86.Final]: Configuration directory is io.netty\netty-buffer\4.1.80.Final
[INFO] [graalvm reachability metadata repository for io.netty:netty-codec-http:4.1.86.Final]: Configuration directory not found. Trying latest version.
[INFO] [graalvm reachability metadata repository for io.netty:netty-codec-http:4.1.86.Final]: Configuration directory is io.netty\netty-codec-http\4.1.80.Final
[INFO] [graalvm reachability metadata repository for io.netty:netty-codec-http2:4.1.86.Final]: Configuration directory not found. Trying latest version.
[INFO] [graalvm reachability metadata repository for io.netty:netty-codec-http2:4.1.86.Final]: Configuration directory is io.netty\netty-codec-http2\4.1.80.Final        
[INFO] [graalvm reachability metadata repository for io.netty:netty-common:4.1.86.Final]: Configuration directory not found. Trying latest version.
[INFO] [graalvm reachability metadata repository for io.netty:netty-common:4.1.86.Final]: Configuration directory is io.netty\netty-common\4.1.80.Final
[INFO] [graalvm reachability metadata repository for io.netty:netty-handler:4.1.86.Final]: Configuration directory not found. Trying latest version.
[INFO] [graalvm reachability metadata repository for io.netty:netty-handler:4.1.86.Final]: Configuration directory is io.netty\netty-handler\4.1.80.Final
[INFO] [graalvm reachability metadata repository for io.netty:netty-resolver-dns:4.1.86.Final]: Configuration directory not found. Trying latest version.
[INFO] [graalvm reachability metadata repository for io.netty:netty-resolver-dns:4.1.86.Final]: Configuration directory is io.netty\netty-resolver-dns\4.1.80.Final      
[INFO] [graalvm reachability metadata repository for io.netty:netty-transport:4.1.86.Final]: Configuration directory not found. Trying latest version.
[INFO] [graalvm reachability metadata repository for io.netty:netty-transport:4.1.86.Final]: Configuration directory is io.netty\netty-transport\4.1.80.Final
[INFO] [graalvm reachability metadata repository for org.apache.commons:commons-pool2:2.11.1]: Configuration directory is org.apache.commons\commons-pool2\2.11.1        
[INFO] 
[INFO] --- maven-resources-plugin:3.3.0:resources (default-resources) @ x-cloud-booking-application ---
[INFO] Copying 2 resources
[INFO] Copying 10 resources
[INFO]
[INFO] --- flatten-maven-plugin:1.2.7:flatten (flatten) @ x-cloud-booking-application ---
[INFO] Generating flattened POM of project com.shushang.x:x-cloud-booking-application:jar:1.0-SNAPSHOT...
[INFO] 
[INFO] --- maven-compiler-plugin:3.10.1:compile (default-compile) @ x-cloud-booking-application ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] >>> maven-source-plugin:3.2.1:jar (default) > generate-sources @ x-cloud-booking-application >>>
[INFO]
[INFO] <<< maven-source-plugin:3.2.1:jar (default) < generate-sources @ x-cloud-booking-application <<<
[INFO]
[INFO]
[INFO] --- maven-source-plugin:3.2.1:jar (default) @ x-cloud-booking-application ---
[INFO] Building jar: D:\work-space\com.shushang\x-cloud-3.x\x-cloud\application\x-cloud-booking-application\target\app-sources.jar
[INFO] 
[INFO] --- maven-resources-plugin:3.3.0:testResources (default-testResources) @ x-cloud-booking-application ---
[INFO] skip non existing resourceDirectory D:\work-space\com.shushang\x-cloud-3.x\x-cloud\application\x-cloud-booking-application\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.10.1:testCompile (default-testCompile) @ x-cloud-booking-application ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ x-cloud-booking-application ---
[INFO] No tests to run.
[INFO]
[INFO] --- spring-boot-maven-plugin:3.0.1:process-aot (process-aot) @ x-cloud-booking-application ---
2023-01-06 00:44:11.741  INFO 8004 --- [] [           main] c.a.n.client.env.SearchableProperties    : properties search order:PROPERTIES->JVM->ENV->DEFAULT_SETTING
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.0.1)

2023-01-06 00:44:11.966  INFO 8004 --- [] [           main] c.s.x.booking.XBookingApplication        : Starting XBookingApplication using Java 17.0.4.1 with PID 8004 (D:
\work-space\com.shushang\x-cloud-3.x\x-cloud\application\x-cloud-booking-application\target\classes started by PING in D:\work-space\com.shushang\x-cloud-3.x\x-cloud\app
lication\x-cloud-booking-application)
2023-01-06 00:44:11.973  INFO 8004 --- [] [           main] c.s.x.booking.XBookingApplication        : The following 1 profile is active: "local"
2023-01-06 00:44:19.550  INFO 8004 --- [] [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository con
figuration mode
2023-01-06 00:44:19.553  INFO 8004 --- [] [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
2023-01-06 00:44:19.658  INFO 8004 --- [] [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 77 ms. Found 0 Redis r
epository interfaces.
2023-01-06 00:44:20.741  INFO 8004 --- [] [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=6a6886b4-93c0-3ed1-b1d6-4e6101494b88
2023-01-06 00:44:25.198  INFO 8004 --- [] [           main] i.s.s.b.a.SeataAutoConfiguration         : Automatically configure Seata
2023-01-06 00:44:25.305  INFO 8004 --- [] [           main] io.seata.config.ConfigurationFactory     : load Configuration from :Spring Configuration
2023-01-06 00:44:25.318  INFO 8004 --- [] [           main] io.seata.config.ConfigurationFactory     : load Configuration from :Spring Configuration
2023-01-06 00:44:26.206  INFO 8004 --- [] [           main] i.s.s.a.GlobalTransactionScanner         : Initializing Global Transaction Clients ... 
2023-01-06 00:44:26.492  INFO 8004 --- [] [           main] i.s.core.rpc.netty.NettyClientBootstrap  : NettyClientBootstrap has started
2023-01-06 00:44:26.524  INFO 8004 --- [] [           main] i.s.c.r.netty.NettyClientChannelManager  : will connect to 192.168.1.34:31171
2023-01-06 00:44:26.675  INFO 8004 --- [] [           main] i.s.core.rpc.netty.NettyPoolableFactory  : NettyPool create channel to transactionRole:TMROLE,address:192.168
.1.34:31171,msg:< RegisterTMRequest{applicationId='x-booking-application', transactionServiceGroup='default_tx_group'} >
2023-01-06 00:44:27.202  WARN 8004 --- [] [ctor_TMROLE_1_1] ServiceLoader$InnerEnhancedServiceLoader : Load [io.seata.serializer.hessian.HessianSerializer] class fail. c
om/caucho/hessian/io/AbstractHessianOutput
2023-01-06 00:44:27.247  INFO 8004 --- [] [           main] i.s.c.rpc.netty.TmNettyRemotingClient    : register TM success. client version:1.6.1, server version:1.5.2,ch
annel:[id: 0x45d8f266, L:/192.168.24.6:52298 - R:/192.168.1.34:31171]
2023-01-06 00:44:27.253  INFO 8004 --- [] [           main] i.s.core.rpc.netty.NettyPoolableFactory  : register success, cost 93 ms, version:1.5.2,role:TMROLE,channel:[i
d: 0x45d8f266, L:/192.168.24.6:52298 - R:/192.168.1.34:31171]
2023-01-06 00:44:27.255  INFO 8004 --- [] [           main] i.s.s.a.GlobalTransactionScanner         : Transaction Manager Client is initialized. applicationId[x-booking
-application] txServiceGroup[default_tx_group]
2023-01-06 00:44:27.276  INFO 8004 --- [] [           main] io.seata.rm.datasource.AsyncWorker       : Async Commit Buffer Limit: 10000
2023-01-06 00:44:27.278  INFO 8004 --- [] [           main] i.s.rm.datasource.xa.ResourceManagerXA   : ResourceManagerXA init ...
2023-01-06 00:44:27.289  INFO 8004 --- [] [           main] i.s.core.rpc.netty.NettyClientBootstrap  : NettyClientBootstrap has started
2023-01-06 00:44:27.290  INFO 8004 --- [] [           main] i.s.s.a.GlobalTransactionScanner         : Resource Manager is initialized. applicationId[x-booking-applicati
on] txServiceGroup[default_tx_group]
2023-01-06 00:44:27.291  INFO 8004 --- [] [           main] i.s.s.a.GlobalTransactionScanner         : Global Transaction Clients are initialized.
Exception in thread "main" org.springframework.aop.framework.adapter.UnknownAdviceTypeException: Advice object [null] is neither a supported subinterface of [org.aopalli
ance.aop.Advice] nor an [org.springframework.aop.Advisor]
        at org.springframework.aop.framework.adapter.DefaultAdvisorAdapterRegistry.wrap(DefaultAdvisorAdapterRegistry.java:62)
        at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.buildAdvisors(AbstractAutoProxyCreator.java:584)
        at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.buildProxy(AbstractAutoProxyCreator.java:502)
        at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.createProxyClass(AbstractAutoProxyCreator.java:470)
        at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.determineBeanType(AbstractAutoProxyCreator.java:252)
        at org.springframework.context.support.GenericApplicationContext.preDetermineBeanTypes(GenericApplicationContext.java:431)
        at org.springframework.context.support.GenericApplicationContext.refreshForAotProcessing(GenericApplicationContext.java:413)
        at org.springframework.context.aot.ApplicationContextAotGenerator.lambda$processAheadOfTime$0(ApplicationContextAotGenerator.java:54)
        at org.springframework.context.aot.ApplicationContextAotGenerator.withCglibClassHandler(ApplicationContextAotGenerator.java:67)
        at org.springframework.context.aot.ApplicationContextAotGenerator.processAheadOfTime(ApplicationContextAotGenerator.java:53)
        at org.springframework.context.aot.ContextAotProcessor.performAotProcessing(ContextAotProcessor.java:106)
        at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:84)
        at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:49)
        at org.springframework.context.aot.AbstractAotProcessor.process(AbstractAotProcessor.java:82)
        at org.springframework.boot.SpringApplicationAotProcessor.main(SpringApplicationAotProcessor.java:76)
2023-01-06 00:44:27.571  INFO 8004 --- [] [ctor_TMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : channel inactive: [id: 0x45d8f266, L:/192.168.24.6:52298 ! R:/192.
168.1.34:31171]
2023-01-06 00:44:27.580  INFO 8004 --- [] [ctor_TMROLE_1_1] i.s.c.r.netty.NettyClientChannelManager  : return to pool, rm channel:[id: 0x45d8f266, L:/192.168.24.6:52298 
! R:/192.168.1.34:31171]
2023-01-06 00:44:27.581  INFO 8004 --- [] [ctor_TMROLE_1_1] i.s.core.rpc.netty.NettyPoolableFactory  : channel valid false,channel:[id: 0x45d8f266, L:/192.168.24.6:52298
 ! R:/192.168.1.34:31171]
2023-01-06 00:44:27.582  INFO 8004 --- [] [ctor_TMROLE_1_1] i.s.core.rpc.netty.NettyPoolableFactory  : will destroy channel:[id: 0x45d8f266, L:/192.168.24.6:52298 ! R:/1
92.168.1.34:31171]
2023-01-06 00:44:27.582  INFO 8004 --- [] [ctor_TMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : ChannelHandlerContext(AbstractNettyRemotingClient$ClientHandler#0,
 [id: 0x45d8f266, L:/192.168.24.6:52298 ! R:/192.168.1.34:31171]) will closed
2023-01-06 00:44:27.583  INFO 8004 --- [] [ctor_TMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : ChannelHandlerContext(AbstractNettyRemotingClient$ClientHandler#0,
 [id: 0x45d8f266, L:/192.168.24.6:52298 ! R:/192.168.1.34:31171]) will closed
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  23.220 s
[INFO] Finished at: 2023-01-06T00:44:27+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:3.0.1:process-aot (process-aot) on project x-cloud-booking-application: Process terminat
ed with exit code: 1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by scottfrederick** [comment]
@admintertar Thanks for getting in touch. Unfortunately we'll need more information on what you're trying to do in order to help you. If you would like us to spend some time investigating, please provide a complete minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it and attaching it to this issue.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by admintertar** [comment]
Caused by a third party
