### ISSUE TITLE
Support Janino in a native image

### ISSUE THREAD

**Issue by gdrouet** [spring-projects/spring-boot#33758]
When building a native image with Spring Boot Maven plugin, Logback configuration relying on Janino leads to an error.

For instance, if we add to the `logback-spring.xml` file the following if statement:

```xml
        <if condition='isDefined("ENV")'>
            <then>
                <appender-ref ref="CONSOLE_JSON"/>
            </then>
            <else>
                <appender-ref ref="CONSOLE_LOCAL"/>
            </else>
        </if>
```

Then running a native image lead to this error:

```
Logging system failed to initialize using configuration from 'null'
java.util.EmptyStackException
	at java.base@17.0.5/java.util.Stack.peek(Stack.java:101)
	at ch.qos.logback.core.model.processor.ModelInterpretationContext.peekModel(ModelInterpretationContext.java:84)
	at ch.qos.logback.core.model.processor.conditional.ElseModelHandler.handle(ElseModelHandler.java:45)
	at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:241)
	at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:253)
	at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:253)
	at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:253)
	at ch.qos.logback.core.model.processor.DefaultProcessor.traversalLoop(DefaultProcessor.java:90)
	at ch.qos.logback.core.model.processor.DefaultProcessor.process(DefaultProcessor.java:106)
	at ch.qos.logback.core.joran.GenericXMLConfigurator.processModel(GenericXMLConfigurator.java:200)
	at org.springframework.boot.logging.logback.SpringBootJoranConfigurator.processModel(SpringBootJoranConfigurator.java:122)
	at org.springframework.boot.logging.logback.SpringBootJoranConfigurator.configureUsingAotGeneratedArtifacts(SpringBootJoranConfigurator.java:115)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initializeFromAotGeneratedArtifactsIfPossible(LogbackLoggingSystem.java:210)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:187)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:332)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:298)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:246)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:223)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
	at org.springframework.boot.context.event.EventPublishingRunListener.multicastInitialEvent(EventPublishingRunListener.java:136)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:81)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:64)
	at java.base@17.0.5/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:63)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:352)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291)
```

Note that a fat-jar run with `-Dspring.aot.enabled=true` does not help to reproduce the issue.

It would be great to have such support for native image.

**Comment by wilkinsona** [comment]
https://stackoverflow.com/questions/75514151/spring-boot-native-image-does-not-print-logs-when-logback-is-configured-with-con contains another sample that exhibits slightly different faulty behaviour – this sample starts successfully but no logging output is produced.

**Comment by hpoettker** [comment]
In the example from the stackoverflow question, I also get the exception from the original post if no metadata is added to `src/main/resources/META-INF/native-image`.

**Comment by wilkinsona** [comment]
Unfortunately, supporting Janino is non-trivial. It relies on generating `ch.qos.logback.core.joran.conditional.Condition` implementations at runtime, something that Graal does not support. Spring Native hacked around this with [a substitution](https://github.com/spring-projects-experimental/spring-native/blob/f5321412190ad70cdfd08e7479ce018175b5e144/spring-native/src/main/java/org/springframework/nativex/substitutions/logback/Target_PropertyEvalScriptBuilder.java). This option is not open to us. We do not use substitutions in Boot as the Graal team have been clear [that they should not be used](https://github.com/oracle/graal/issues/2904#issuecomment-705618165).

One option that we could explore is generating the `Condition` implementations at build time, including them in the native image and then reusing these pre-generated classes at runtime. This is what Framework does for CGLib-based proxies. This may not be possible without changes to Logback if the necessary hook points are not available.

**Comment by wilkinsona** [comment]
I've prototyped something in [this branch](https://github.com/wilkinsona/spring-boot/tree/gh-33758). It's not a lot of code, but I'm not happy with `AotIfModelHandler`. It duplicates much of the logic in Logback's `IfModelHandler` which we risk falling out of sync. I'd like to discuss our options with the rest of the team. My feeling is that we won't be able to do something here without some changes to Logback.

**Comment by hpoettker** [comment]
@wilkinsona Thanks for implementing #34315 so quickly! The sample application from the stackoverflow question now fails early and logs a meaningful exception. I've added it to the SO question.

**Comment by gdrouet** [comment]
Do you have any workaround to write an equivalent programmatically and have a chance to make it work with spring native?

**Comment by wilkinsona** [comment]
I'm afraid not. https://github.com/spring-projects/spring-boot/issues/25847 is tracking support for programmatic configuration of Logback.

**Comment by wilkinsona** [comment]
@ceki would you consider making some changes to `IfModelHandler` to make it more Graal-friendly? We'd like to be able to capture the class files that it creates so that they can be contributed to a GraalVM native image. Then, when the image is being executed, we'd like to be able to provide those classes to the handler rather than it compiling them again.

**Comment by ceki** [comment]
@wilkinsona **Sure, I am open to changes**.  I have looked at your efforts to support logback with GraalVM which are quite impressive.

For your information, I have started to explore a path for supporting GraalVM which you might find interesting:

Note: experimental changes in 1.4.9 (commit bd11e72017941331f2c3ba5101429359aced5a47 not yet released)

- JoranConfigurator is invoked by reflection and no longer as a service.
- JoranConfigurator  now supports a directive in logback.xml to dump/serialize the model it created into an ObjectOutputStream file with an .smo extension.
- SerializedModelConfigurator searches for serialized model files (.smo extension) and configures logback if a .smo file is found.
- SerializedModelConfigurator is invoked as a configurator service. This happens before JoranConfigurator.

Anyway, I am still experimenting and am not sure of the results, that is whether this will work with GraalVM without the need for an XML parser.

Coming back to your original question, the experimental approach outlined above is different than the question raised by Janino.

**Comment by ceki** [comment]
@wilkinsona As of [commit c440e08b](https://github.com/qos-ch/logback/commit/c440e08bd7bc4), logback supports loading a model configuration file without ever loading JoranConfigurator and without including java.xml in a native image. I have verified this to work with GraalVM.

**Comment by wilkinsona** [comment]
That sounds great. Thanks, @ceki. Are Logback snapshots published anywhere? I'd like to give the new serialisation support a try and see if we can rip out the stuff that I wrote.

**Comment by ceki** [comment]
@wilkinsona Logback snapshots are not published. You would need to check out from github source and  build at your end using the JDK 11+ and Maven. 

I will be documenting the procedure for using serialized model  (SMO) files shortly. The only "tricky" part is to remember to add  `<serializeModel file="${aVariablePointingToADestinationFile}"/>` directive in logback.xml.

**Comment by drubio-tlnd** [comment]
Hey, did the use of `scmo` file allows to use the janino ?

**Comment by syedyusufh** [comment]
@ceki could you please tell us the way to use logback + janino in a Spring Boot native image?

**Comment by edudar** [comment]
Redefining model input stream
```
public class SpringHardenedModelInputStream extends HardenedObjectInputStream {

    public static List<String> getWhilelist() {
        List<String> whitelist = HardenedModelInputStream.getWhilelist();

        whitelist.add(org.springframework.boot.logging.logback.SpringProfileModel.class.getName());
        whitelist.add(org.springframework.boot.logging.logback.SpringPropertyModel.class.getName());

        return whitelist;
    }

    public SpringHardenedModelInputStream(InputStream is) throws IOException {
        super(is, getWhilelist());
    }
}
```

and replacing `HardenedModelInputStream` in a configurator by creating a copy of `SerializedModelConfigurator` like `SpringSerializedModelConfigurator` works.

**Comment by guai** [comment]
would it work if logback supported condition in a simple predicate class instead of compiling expressions on the fly with janino?

**Comment by ceki** [comment]
@guai Sounds like a good idea. Please file a issue report with the [logback project](https://github.com/qos-ch/logback/issues).

**Comment by ceki** [comment]
@gdrouet FYI, [logback-tyler](https://github.com/qos-ch/logback-tyler) already translates janono-expressions into Java. It seems to me that the output generated logbaclk-tyler is a Configurator [auto-loadable](https://logback.qos.ch/manual/configuration.html#auto_configuration) and is quite suitable for a GraalVM application.

**Comment by DarkAtra** [comment]
hey @ceki, first of all: thanks for all your great work on logback-classic and logback-tyler.

I just gave it a try and quickly found that [the following requirement](https://github.com/qos-ch/logback-tyler/blob/fd0bb32af337c7f3299bac5d1759a8f35a3da5af/README.md#L23-L24) is not met in case of Spring Boot Applications:
> At runtime, TylerConfigurator does not have any additional dependencies other than logback-classic version 1.5.10.

I tried using version `0.9` of logback-tyler and setting the `logback.version` for our Spring Boot project to `1.5.11`. I then ran logback-tyler for our config file. This is a very simplified version of it:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <springProperty scope="context" name="consoleEnabled" source="logging.console.enabled"/>

    <if condition='${consoleEnabled}'>
        <then>
            <include resource="logback-console-appender.xml"/>
            <root level="info">
                <appender-ref ref="CONSOLE"/>
            </root>
        </then>
    </if>
</configuration>
```
This is the resulting code from logback-tyler (which does not compile):
 ```java
@Override
public Configurator.ExecutionStatus configure(LoggerContext loggerContext) {
    setContext(loggerContext);
    if(${consoleEnabled}) { // <-------- 1. issue: broken if condition
        IncludeModel includeModel = new IncludeModel();
        includeModel.setResource(subst("logback-console-appender.xml"));
        IncludeModelHandler includeModelHandler = new IncludeModelHandler(context);
        try {
            Model modelFromIncludedFile = includeModelHandler.buildModelFromIncludedFile(this, includeModel);
            processModelFromIncludedFile(modelFromIncludedFile);
        } catch(ModelHandlerException e) {
            addError("Failed to process IncludeModelHandler", e);
        }
        Logger logger_ROOT = setupLogger("ROOT", "info", null);
        logger_ROOT.addAppender(appenderCONSOLE); // <-------- 2. issue: broken appender reference
    }
    return ExecutionStatus.DO_NOT_INVOKE_NEXT_IF_ANY;
}
```

1. conditions with spring expressions are not converted correctly - probably because logback-tyler doesn't know anything about spring. Is there anything that spring-boot could do to participate in the conversion for spring specific features?
2. appenders defined in an included file are not correctly referenced (can also be seen in the example above) - this seems to be a bug in logback-tyler and is not related to Spring Boot

Also, the logback-tyler readme claims that:
> Running TylerConfigurator does not require XML parsers and usually executes noticeably faster than JoranConfigurator, logback's XML configurator.

However, `<include resource="logback-console-appender.xml"/>` is translated to:
```java
IncludeModel includeModel = new IncludeModel();
includeModel.setResource(subst("logback-console-appender.xml"));
IncludeModelHandler includeModelHandler = new IncludeModelHandler(context);
try {
    Model modelFromIncludedFile = includeModelHandler.buildModelFromIncludedFile(this, includeModel);
    processModelFromIncludedFile(modelFromIncludedFile);
} catch(ModelHandlerException e) {
    addError("Failed to process IncludeModelHandler", e);
}
```
To me it seems like `includeModelHandler.buildModelFromIncludedFile(this, includeModel)` uses an XML parser internally and the referenced xml file is probably also allowed to use conditions which then also requires Janino (an issue with GraalMV). Is there any way to configure logback-tyler so that it also resolves and translates included files?

**Comment by DarkAtra** [comment]
> @DarkAtra Since the issue you describe is mostly logback-tyler related, would you mind creating a new issue in the [logback project](https://github.com/qos-ch/logback/issues)?
> 
> Note at translation time logback-tyler usually does not have access to the included file. Thus, it should not be expected to translate the included file. The translation that logback-tyler produces currently seems likely to work at runtime when `TylerConfigurator` is invoked to configure logback.

sure, here they are:
* https://github.com/qos-ch/logback/issues/875
* https://github.com/qos-ch/logback/issues/874
* https://github.com/qos-ch/logback/issues/873

**Comment by philwebb** [comment]
As part of discussing #44235 in our team call today Janino native image support came up again. After some consideration, we've decided that we won't have the bandwidth to attempt to fix this directly in Spring Boot. We're going to treat Janino support in the same way as we do many other libraries, and rely on upstream native image support. This probably means https://github.com/qos-ch/logback/issues/757 or update in Janino itself.

Another future option might be to combine code generated by https://github.com/qos-ch/logback-tyler with whatever fix we can eventually provide for #25847.

I'm sorry we don't have more time to find a solution for folks watching this issue.
