### ISSUE TITLE
missing class only in native image

### ISSUE THREAD

**Issue by diginote** [spring-projects/spring-boot#33836]
Hi Team, 

my spring boot app (v3.0.1) uses `ldapTempate.search` to get information from ldap server. On JVM-mode the app starts fine but in native mode it throws `java.lang.ClassNotFoundException: javax.naming.ldap.PagedResultsResponseControl`.

```
java.lang.ClassNotFoundException: javax.naming.ldap.PagedResultsResponseControl
myapp |       at java.base@17.0.5/java.lang.Class.forName(DynamicHub.java:1132) ~[com.company.apps.AppInfoServiceApplication:na]
myapp |       at java.base@17.0.5/java.lang.Class.forName(DynamicHub.java:1105) ~[com.company.apps.AppInfoServiceApplication:na]
myapp |       at org.springframework.ldap.control.AbstractFallbackRequestAndResponseControlDirContextProcessor.loadControlClasses(AbstractFallbackRequestAndResponseControlDirContextProcessor.java:110) ~[com.company.apps.AppInfoServiceApplication:3.0.0]
myapp |       at org.springframework.ldap.control.PagedResultsDirContextProcessor.<init>(PagedResultsDirContextProcessor.java:81) ~[na:na]
myapp |       at org.springframework.ldap.control.PagedResultsDirContextProcessor.<init>(PagedResultsDirContextProcessor.java:60) ~[na:na]
myapp |       at com.company.apps.service.ldap.LdapServiceHelper.loadAllStaff(LdapServiceHelper.java:42) ~[com.company.apps.AppInfoServiceApplication:na]
myapp |       at java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:568) ~[com.company.apps.AppInfoServiceApplication:na]
myapp |       at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[na:na]
myapp |       at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[com.company.apps.AppInfoServiceApplication:6.0.3]
myapp |       at java.base@17.0.5/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
myapp |       at java.base@17.0.5/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[com.company.apps.AppInfoServiceApplication:na]
myapp |       at java.base@17.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
myapp |       at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[com.company.apps.AppInfoServiceApplication:na]
myapp |       at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
myapp |       at java.base@17.0.5/java.lang.Thread.run(Thread.java:833) ~[com.company.apps.AppInfoServiceApplication:na]
myapp |       at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775) ~[com.company.apps.AppInfoServiceApplication:na]
myapp |       at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203) ~[na:na]
```
Anybody an idea how to solve this issue?

**Comment by bclozel** [comment]
@diginote can you report this issue [against the spring-ldap project](https://github.com/spring-projects/spring-ldap/issues)? Could you provide a minimal, sample project that reproduces the problem there as well?

Thanks!
