### ISSUE TITLE
Maven goal `spring-boot-maven-plugin:process-aot` not working with latest 3.0.3

### ISSUE THREAD

**Issue by benweet** [spring-projects/spring-boot#34373]
Maven goal `spring-boot-maven-plugin:process-aot` does not work anymore on our side. It worked with v3.0.2. With latest v3.0.3 we have the following error :

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.getTypeParametersCascadingMetaDataForParameterizedType(AnnotationMetaDataProvider.java:679)
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.getTypeParametersCascadingMetadata(AnnotationMetaDataProvider.java:661)
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.findCascadingMetaData(AnnotationMetaDataProvider.java:628)
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.getParameterMetaData(AnnotationMetaDataProvider.java:432)
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.findExecutableMetaData(AnnotationMetaDataProvider.java:308)
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.getMetaData(AnnotationMetaDataProvider.java:292)
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.getMethodMetaData(AnnotationMetaDataProvider.java:279)
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.retrieveBeanConfiguration(AnnotationMetaDataProvider.java:131)
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.getBeanConfiguration(AnnotationMetaDataProvider.java:121)
	at org.hibernate.validator.internal.metadata.BeanMetaDataManagerImpl.getBeanConfigurationForHierarchy(BeanMetaDataManagerImpl.java:234)
	at org.hibernate.validator.internal.metadata.BeanMetaDataManagerImpl.createBeanMetaData(BeanMetaDataManagerImpl.java:201)
	at org.hibernate.validator.internal.metadata.BeanMetaDataManagerImpl.getBeanMetaData(BeanMetaDataManagerImpl.java:165)
	at org.hibernate.validator.internal.engine.ValidatorImpl.getConstraintsForClass(ValidatorImpl.java:316)
	at org.springframework.validation.beanvalidation.BeanValidationBeanRegistrationAotProcessor$BeanValidationDelegate.processAheadOfTime(BeanValidationBeanRegistrationAotProcessor.java:70)
	at org.springframework.validation.beanvalidation.BeanValidationBeanRegistrationAotProcessor.processAheadOfTime(BeanValidationBeanRegistrationAotProcessor.java:59)
	at org.springframework.beans.factory.aot.BeanDefinitionMethodGeneratorFactory.getAotContributions(BeanDefinitionMethodGeneratorFactory.java:151)
	at org.springframework.beans.factory.aot.BeanDefinitionMethodGeneratorFactory.getBeanDefinitionMethodGenerator(BeanDefinitionMethodGeneratorFactory.java:99)
	at org.springframework.beans.factory.aot.BeanDefinitionMethodGeneratorFactory.getBeanDefinitionMethodGenerator(BeanDefinitionMethodGeneratorFactory.java:115)
	at org.springframework.beans.factory.aot.BeanRegistrationsAotProcessor.processAheadOfTime(BeanRegistrationsAotProcessor.java:48)
	at org.springframework.beans.factory.aot.BeanRegistrationsAotProcessor.processAheadOfTime(BeanRegistrationsAotProcessor.java:36)
	at org.springframework.context.aot.BeanFactoryInitializationAotContributions.getContributions(BeanFactoryInitializationAotContributions.java:67)
	at org.springframework.context.aot.BeanFactoryInitializationAotContributions.<init>(BeanFactoryInitializationAotContributions.java:49)
	at org.springframework.context.aot.BeanFactoryInitializationAotContributions.<init>(BeanFactoryInitializationAotContributions.java:44)
	at org.springframework.context.aot.ApplicationContextAotGenerator.lambda$processAheadOfTime$0(ApplicationContextAotGenerator.java:58)
	at org.springframework.context.aot.ApplicationContextAotGenerator.withCglibClassHandler(ApplicationContextAotGenerator.java:67)
	at org.springframework.context.aot.ApplicationContextAotGenerator.processAheadOfTime(ApplicationContextAotGenerator.java:53)
	at org.springframework.context.aot.ContextAotProcessor.performAotProcessing(ContextAotProcessor.java:106)
	at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:84)
	at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:49)
	at org.springframework.context.aot.AbstractAotProcessor.process(AbstractAotProcessor.java:82)
	at org.springframework.boot.SpringApplicationAotProcessor.main(SpringApplicationAotProcessor.java:80)
```

We get the error by running `mvn native:compile -Pnative`.

**Comment by scottfrederick** [comment]
Thanks for the report. It is difficult to tell what's going on with limited information. If you would like us to spend some time investigating, please provide a complete minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it and attaching it to this issue.

**Comment by benweet** [comment]
Hi @scottfrederick 

You will find [a minimal sample here](https://github.com/spring-projects/spring-boot/files/10834090/Archive.zip). You will reproduce the problem by running `mvn native:compile -P native`.

Things I've noticed during my investigation :

- The project includes the `spring-boot-starter-validation` dependency and, during the `spring-boot-maven-plugin:process-aot` goal, Hibernate seems to validate all my beans methods, even the `DemoService.parseAndValidateUserDto()` method which is private and is not used during JSR 303 validation. It does work when I remove the `spring-boot-starter-validation` dependency or when I exclude the jakarta dependency as follows :

```
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-validation</artifactId>
			<exclusions>
				<exclusion>
					<groupId>jakarta.validation</groupId>
					<artifactId>jakarta.validation-api</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```

- It does work when I remove the String parameter of the `DemoService.parseAndValidateUserDto()` method.

- It does work when I use `spring-boot-starter-parent:3.0.2` as the project parent pom.

Cheers!

**Comment by philwebb** [comment]
It looks like the fix https://github.com/spring-projects/spring-framework/issues/29823 has now triggered another bug which I think could be https://hibernate.atlassian.net/browse/HV-1796.

I can replicate the same issue by adding the following test to your sample project:

```kotlin
class ValidationTests {

    @Test
    fun validate() {
        val validator: Validator = Validation.buildDefaultValidatorFactory().validator
        val clazz: Class<*> = DemoService::class.java
        validator.getConstraintsForClass(clazz)
    }

}
```

I don't think there is anything that we can do in Spring Boot to fix this, but perhaps Spring Framework can be more defensive when invoking `getConstraintsForClass`.

@bclozel Could you please transfer this issue?

/cc @sdeleuze
