### ISSUE TITLE
Subclassing RepositoryRestMvcConfiguration or SpringBootRepositoryRestMvcConfiguration causes EndpointWebMvcHypermediaConfiguration to fail with multiple ObjectMapper instances

### ISSUE THREAD

**Issue by spencergibb** [spring-projects/spring-boot#3439]
With 1.3.0.BUILD-SNAPSHOT using https://github.com/spring-cloud-samples/customers-stores
```
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.actuate.autoconfigure.EndpointWebMvcHypermediaConfiguration$LinksConfiguration$MvcEndpointAdvice': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.fasterxml.jackson.databind.ObjectMapper org.springframework.boot.actuate.autoconfigure.EndpointWebMvcHypermediaConfiguration$LinksConfiguration$MvcEndpointAdvice.mapper; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [com.fasterxml.jackson.databind.ObjectMapper] is defined: expected single matching bean but found 3: objectMapper,halObjectMapper,_halObjectMapper
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:766)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:819)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:522)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:677)
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:338)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:273)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:930)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:919)
	at example.customers.CustomerApp.main(CustomerApp.java:39)
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.fasterxml.jackson.databind.ObjectMapper org.springframework.boot.actuate.autoconfigure.EndpointWebMvcHypermediaConfiguration$LinksConfiguration$MvcEndpointAdvice.mapper; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [com.fasterxml.jackson.databind.ObjectMapper] is defined: expected single matching bean but found 3: objectMapper,halObjectMapper,_halObjectMapper
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:571)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 17 more
Caused by: org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [com.fasterxml.jackson.databind.ObjectMapper] is defined: expected single matching bean but found 3: objectMapper,halObjectMapper,_halObjectMapper
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1073)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:961)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:543)
	... 19 more
```

**Comment by wilkinsona** [comment]
The problem's triggered by the sample's `RepositoryRestMvcConfiguration` subclass (Aside: that should be a `SpringBootRepositoryRestMvcConfiguration` subclass in a Spring Boot app). This subclass pulls in the definition for Spring Data REST's `ObjectMapper`. This means that there's an `ObjectMapper` bean  _before_ Boot's `JacksonAutoConfiguration` has run. This prevents it from creating its `@Primary` `ObjectMapper` leading to the failure due to multiple `ObjectMapper` beans.

The problem can be avoided by removing the extension of `RepositoryRestMvcConfiguration`. I think the configuration can then be applied via `@PostConstruct`. That's certainly sufficient to get the two apps to start, but I've been unable to test fully as I can't get the config server to build and run from source.

In the longer term, I think we need some changes to Spring Data REST so that the configuration can be customised without having to a extend a class that contains bean definitions. An approach similar to Spring MVC's `WebMvcConfigurer` and `WebMvcConfigurerAdapter`, perhaps. /cc @olivergierke.

**Comment by izeye** [comment]
I have the same problem and @wilkinsona 's workaround works for me.

I guess the following guide needs to be changed due to this problem if it won't be fixed:

http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#howto-use-exposing-spring-data-repositories-rest-endpoint

**Comment by bedge** [comment]
Is there a workaround to attach a configureValidatingRepositoryEventListener if one cannot subclass a RepositoryRestMvcConfiguration?
Or, any kind of beforeSave... listener for that matter?

ie: 
```
public class Application extends RepositoryRestMvcConfiguration {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Override
    protected void configureValidatingRepositoryEventListener(ValidatingRepositoryEventListener validatingListener) {
        validatingListener.addValidator("beforeCreate", new PeopleValidator());
    }
}
```
(from http://stackoverflow.com/questions/24318405/spring-data-rest-validator)

**Comment by bedge** [comment]
I was able to work around this using
```
@Configuration
public class CollectionValidatorRegistrar implements InitializingBean {

	    @Autowired
	    ListableBeanFactory beanFactory;

	    @Autowired
	    ValidatingRepositoryEventListener validatingRepositoryEventListener;

	    @Autowired CollectionValidator collectionValidator;
		@Override
		public void afterPropertiesSet() throws Exception {
			validatingRepositoryEventListener.addValidator("beforeSave", collectionValidator);
		}

}
```

**Comment by wilkinsona** [comment]
I've discussed this with @olivergierke and opened [DATAREST-621](https://jira.spring.io/browse/DATAREST-621) which he hopes to tackle in time for Gosling RC1.

**Comment by bodiam** [comment]
Hi all, I'm suffering from the same issue in 1.3.0.M4. I'm subclassing RepositoryRestMvcConfiguration instead of SpringBootRepositoryRestMvcConfiguration. I understand now I shouldn't probably do this, and I'll migrate to the new way of doing things, but having a main application like this already triggers this issue:

````
@SpringBootApplication
public class Application extends RepositoryRestMvcConfiguration  {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}
````

**Comment by olivergierke** [comment]
The suggested workaround is extending `RepositoryRestConfigurerAdapter` introduced with Spring Data release train Gosling. Boot snapshots have already upgraded to that. Would you mind giving this a spin?

**Comment by bodiam** [comment]
Sure, I can try that. Is it a drop in replacement?

**Comment by Juchar** [comment]
By consequence it is also not possible to override `RepositoryRestMvcConfiguration#resourceDescriptionMessageSourceAccessor` to customize the location of the property files, correct?

**Comment by wilkinsona** [comment]
Correct. If that can't be customised via a `RespositoryRestConfigurerAdapter` subclass then you should raise a Spring Data REST enhancement request to improve its configuration model.
