### ISSUE TITLE
Combination of Redis dependencies breaks native compile since 3.0.3

### ISSUE THREAD

**Issue by marcust** [spring-projects/spring-boot#34491]
Ever since `3.0.3` (so present in `3.0.3` and `3.0.4`) native compiliation via `./mvnw -Pnative native:compile` is broken in one of my projects with

```
Exception in thread "main" java.lang.IllegalArgumentException: Code generation is not supported for bean definitions declaring an instance supplier callback : Root bean: class [org.springframework.integration.config.MessagingAnnotationPostProcessor]; scope=singleton; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodNames=null; destroyMethodNames=null
	at org.springframework.beans.factory.aot.BeanDefinitionMethodGenerator.<init>(BeanDefinitionMethodGenerator.java:82)
	at org.springframework.beans.factory.aot.BeanDefinitionMethodGeneratorFactory.getBeanDefinitionMethodGenerator(BeanDefinitionMethodGeneratorFactory.java:100)
	at org.springframework.beans.factory.aot.BeanDefinitionMethodGeneratorFactory.getBeanDefinitionMethodGenerator(BeanDefinitionMethodGeneratorFactory.java:115)
	at org.springframework.beans.factory.aot.BeanRegistrationsAotProcessor.processAheadOfTime(BeanRegistrationsAotProcessor.java:48)
	at org.springframework.beans.factory.aot.BeanRegistrationsAotProcessor.processAheadOfTime(BeanRegistrationsAotProcessor.java:36)
	at org.springframework.context.aot.BeanFactoryInitializationAotContributions.getContributions(BeanFactoryInitializationAotContributions.java:67)
	at org.springframework.context.aot.BeanFactoryInitializationAotContributions.<init>(BeanFactoryInitializationAotContributions.java:49)
	at org.springframework.context.aot.BeanFactoryInitializationAotContributions.<init>(BeanFactoryInitializationAotContributions.java:44)
	at org.springframework.context.aot.ApplicationContextAotGenerator.lambda$processAheadOfTime$0(ApplicationContextAotGenerator.java:58)
	at org.springframework.context.aot.ApplicationContextAotGenerator.withCglibClassHandler(ApplicationContextAotGenerator.java:67)
	at org.springframework.context.aot.ApplicationContextAotGenerator.processAheadOfTime(ApplicationContextAotGenerator.java:53)
	at org.springframework.context.aot.ContextAotProcessor.performAotProcessing(ContextAotProcessor.java:106)
	at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:84)
	at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:49)
	at org.springframework.context.aot.AbstractAotProcessor.process(AbstractAotProcessor.java:82)
	at org.springframework.boot.SpringApplicationAotProcessor.main(SpringApplicationAotProcessor.java:80)

```

in the `process-aot` step. This seems to be due to my combination of dependencies and independent of my code, as soon as 

```
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-redis</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.integration</groupId>
			<artifactId>spring-integration-redis</artifactId>
		</dependency>
```

are present in the `pom.xml` I see this. 

I did not see any functional limitations prior to 3.0.23 so this is purely a regression like https://github.com/spring-projects/spring-boot/issues/34371 for me due to https://github.com/spring-projects/spring-framework/issues/29556.

Minimum demo: [demo.zip](https://github.com/spring-projects/spring-boot/files/10899912/demo.zip)

**Comment by wilkinsona** [comment]
Thanks for the report. This should already be fixed in Spring Integration 6.0.4-SNAPSHOT due to [these changes](https://github.com/spring-projects/spring-integration/commit/5c96c0ded07e4630b7756e2643650bf3a01fbb5d). You can use a `spring-integration.version` property in your pom to override the version and double-check that is the case. If the problem persists, please open a new [Spring Integration issue](https://github.com/spring-projects/spring-integration/issues) .

**Comment by wilkinsona** [comment]
Yes, that's the plan.
