### ISSUE TITLE
@ServletComponentScan causes AOT processing to fail with "Code generation is not supported for bean definitions declaring an instance supplier callback"

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#34563]
```
Exception in thread "main" java.lang.IllegalArgumentException: Code generation is not supported for bean definitions declaring an instance supplier callback : Root bean: class [org.springframework.boot.web.servlet.ServletComponentRegisteringPostProcessor]; scope=singleton; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodNames=null; destroyMethodNames=null
	at org.springframework.beans.factory.aot.BeanDefinitionMethodGenerator.<init>(BeanDefinitionMethodGenerator.java:82)
	at org.springframework.beans.factory.aot.BeanDefinitionMethodGeneratorFactory.getBeanDefinitionMethodGenerator(BeanDefinitionMethodGeneratorFactory.java:100)
	at org.springframework.beans.factory.aot.BeanDefinitionMethodGeneratorFactory.getBeanDefinitionMethodGenerator(BeanDefinitionMethodGeneratorFactory.java:115)
	at org.springframework.beans.factory.aot.BeanRegistrationsAotProcessor.processAheadOfTime(BeanRegistrationsAotProcessor.java:48)
	at org.springframework.beans.factory.aot.BeanRegistrationsAotProcessor.processAheadOfTime(BeanRegistrationsAotProcessor.java:36)
	at org.springframework.context.aot.BeanFactoryInitializationAotContributions.getContributions(BeanFactoryInitializationAotContributions.java:67)
	at org.springframework.context.aot.BeanFactoryInitializationAotContributions.<init>(BeanFactoryInitializationAotContributions.java:49)
	at org.springframework.context.aot.BeanFactoryInitializationAotContributions.<init>(BeanFactoryInitializationAotContributions.java:44)
	at org.springframework.context.aot.ApplicationContextAotGenerator.lambda$processAheadOfTime$0(ApplicationContextAotGenerator.java:58)
	at org.springframework.context.aot.ApplicationContextAotGenerator.withCglibClassHandler(ApplicationContextAotGenerator.java:67)
	at org.springframework.context.aot.ApplicationContextAotGenerator.processAheadOfTime(ApplicationContextAotGenerator.java:53)
	at org.springframework.context.aot.ContextAotProcessor.performAotProcessing(ContextAotProcessor.java:106)
	at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:84)
	at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:49)
	at org.springframework.context.aot.AbstractAotProcessor.process(AbstractAotProcessor.java:82)
	at org.springframework.boot.SpringApplicationAotProcessor.main(SpringApplicationAotProcessor.java:80)
```

See https://github.com/spring-projects/spring-framework/issues/29803 for the background.

The problematic `servletComponentRegisteringPostProcessor` bean isn't needed in an AOT-processed context as the servlet components are registered during AOT processing and there's no need for them to be registered again at runtime. We can exclude the post-processor from the AOT processed context.

**Comment by wilkinsona** [comment]
I believe that's already been fixed in Spring Integration snapshots through [these changes](https://github.com/spring-projects/spring-integration/commit/5c96c0ded07e4630b7756e2643650bf3a01fbb5d).

**Comment by mmoayyed** [comment]
Thank you Andy. I appreciate the reference.

**Comment by Abhijeetmishr** [comment]
@wilkinsona is this issue needs fix ? can I pick this up ?

**Comment by sweetcard** [comment]
The exception has been found in spring boot v3.0.6.

**Comment by wilkinsona** [comment]
@sweetcard That is to be expected as the issue remains open as we have not yet had time to fix it.
