### ISSUE TITLE
`ServerSocketReceiver` doesn't work after upgrading Spring Boot 1.3.0.M2.

### ISSUE THREAD

**Issue by izeye** [spring-projects/spring-boot#3472]
`ServerSocketReceiver` doesn't work after upgrading Spring Boot 1.3.0.M2.

With Spring Boot 1.3.0.M1, `ServerSocketReceiver` works,

but with Spring Boot 1.3.0.M2, it doesn't work with the following error:

```
Exception in thread "main" java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.classic.net.server.RemoteAppenderServerRunner@4808f4b9 - listener: java.net.SocketException: Socket closed
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:141)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.reinitialize(LogbackLoggingSystem.java:169)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:64)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:49)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:102)
	at org.springframework.boot.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:211)
	at org.springframework.boot.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:189)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:169)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:150)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:119)
	at org.springframework.boot.context.event.EventPublishingRunListener.publishEvent(EventPublishingRunListener.java:111)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:65)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:307)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:273)
	at samples.springboot.Application.main(Application.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

This is a sample project reproducing the problem:

https://github.com/izeye/samples-spring-boot-branches/tree/logback-socket

After the `Application` started, run the `LogbackTests.test()`.

**Comment by philwebb** [comment]
We're changing log configuration behavior in 1.3 so that failures prevent the application from starting. See #3309 for background.

When you run the application with M1 you see the following output:

```
12:43:02,659 |-INFO in ch.qos.logback.classic.net.server.RemoteAppenderServerRunner@82a192c - listening on 0.0.0.0:10001
12:43:02,660 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@682b2fa - Registering current configuration as safe fallback point
12:43:18,192 |-ERROR in ch.qos.logback.classic.net.server.RemoteAppenderServerRunner@82a192c - listener: java.net.SocketException: Socket closed
12:43:18,192 |-INFO in ch.qos.logback.classic.net.server.RemoteAppenderServerRunner@82a192c - shutting down
12:43:18,192 |-ERROR in ch.qos.logback.classic.net.server.RemoteAppenderServerRunner@82a192c - listener: java.net.SocketException: Socket closed
12:43:18,192 |-INFO in ch.qos.logback.classic.net.server.RemoteAppenderServerRunner@82a192c - shutting down
```

So even though the application started, there was a problem with the log configuration.

We probably still need to track down why this failure occurs, I'm guessing it could be because we re-initialize the logging system.

**Comment by philwebb** [comment]
Renaming `logback.xml` to `logback-spring.xml` does seem to prevent the error.

**Comment by izeye** [comment]
@philwebb Thanks! Both work for me :+1:
