### ISSUE TITLE
Consider adding an Instant formatter from timestamp-like properties

### ISSUE THREAD

**Issue by JanecekPetr** [spring-projects/spring-boot#34849]
What I'm trying to achieve:

```java
@ConfigurationProperties
record ApplicationProps(Instant instant) {}
```

with the following `application.properties`:
```
instant = 1680612880417
```
where the value is millis since the epoch, see [`Instant.ofEpochMilli()`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/time/Instant.html#ofEpochMilli(long)).

Considerations:
- Why are we choosing `Instant.ofEpochMilli()` and not `Instant.ofEpochSecond()`? It just felt more natural. Is this uncertainty reason enough to refuse this request? That said, there already is a `Converter<Long, Instant>` which does exactly this. Therefore, an additional Formatter would be consistent with the already-existing Converter.
- Do we also need to add more similar formatters for types like `java.util.Date` or `java.sql.Timestamp`? I do no think think so as neither of them has a simple `ofEpochMilli()`-like creator method or clear semantics. Other `java.time` also are not good targets for this unless OffsetDateTime/ZonedDateTime is considered okay given a default timezone.

**Comment by snicoll** [comment]
> Why are we choosing Instant.ofEpochMilli() and not Instant.ofEpochSecond()? 

Because the usual way of representing a "time" is by using the number of ms, not seconds. I understand that you'd prefer seconds but that's not what the default representation is at the moment: the seconds variant is merely a shortcut for those who don't need ms precision.

Both inputs are numbers so it's impossible for us to know which format you want to use automatically. I can't even suggest to configure a custom converter, unless you want to trump the default one for every fields.

Having said all of that, I am not sure I understand what you'd expect from us. Can you clarify?

**Comment by JanecekPetr** [comment]
> I understand that you'd prefer seconds

Sorry, maybe I need to rephrase my question as that was _not_ what I meant. I absolutely prefer millis and I agree. I was just adding considerations and alternatives that _someone_ might ask for instead.

> Can you clarify?

Sure (should I also edit the original question?)!

Currently if you try the code I suggested above, it fails with:

```
...
Caused by: org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'java.time.Instant'; Failed to convert from type [java.lang.String] to type [@org.springframework.beans.factory.annotation.Value java.time.Instant] for value '123456789'
	at org.springframework.beans.TypeConverterSupport.convertIfNecessary(TypeConverterSupport.java:79) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1353) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1325) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:885) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:789) ~[spring-beans-6.0.6.jar:6.0.6]
	... 110 common frames omitted
Caused by: org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [@org.springframework.beans.factory.annotation.Value java.time.Instant] for value '123456789'
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:47) ~[spring-core-6.0.6.jar:6.0.6]
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:192) ~[spring-core-6.0.6.jar:6.0.6]
	at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:129) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.TypeConverterSupport.convertIfNecessary(TypeConverterSupport.java:73) ~[spring-beans-6.0.6.jar:6.0.6]
	... 114 common frames omitted
Caused by: java.lang.IllegalArgumentException: Parse attempt failed for value [123456789]
	at org.springframework.format.support.FormattingConversionService$ParserConverter.convert(FormattingConversionService.java:224) ~[spring-context-6.0.6.jar:6.0.6]
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:41) ~[spring-core-6.0.6.jar:6.0.6]
	... 117 common frames omitted
Caused by: java.time.format.DateTimeParseException: Text '123456789' could not be parsed at index 0
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2052) ~[na:na]
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1954) ~[na:na]
	at java.base/java.time.Instant.parse(Instant.java:397) ~[na:na]
	at org.springframework.format.datetime.standard.InstantFormatter.parse(InstantFormatter.java:50) ~[spring-context-6.0.6.jar:6.0.6]
	at org.springframework.format.datetime.standard.InstantFormatter.parse(InstantFormatter.java:40) ~[spring-context-6.0.6.jar:6.0.6]
	at org.springframework.format.support.FormattingConversionService$ParserConverter.convert(FormattingConversionService.java:218) ~[spring-context-6.0.6.jar:6.0.6]
	... 118 common frames omitted
```

Currently it is not possible to use a timestamp as a property of type `Instant`. I'd like Spring to parse that.

**Comment by wilkinsona** [comment]
@snicoll Given the involvement of `org.springframework.format.datetime.standard.InstantFormatter`, should this be transferred to Framework?

**Comment by snicoll** [comment]
Yes. We do have issues to move some of the converters that we have in Spring Boot already so that makes sense.
