### ISSUE TITLE
Document manual servlet-api 3.1 property setting required for undertow, when used through Spring.IO Platform

### ISSUE THREAD

**Issue by mikaelhg** [spring-projects/spring-boot#3495]
Please document this workaround in the "Use Undertow instead of Tomcat" section of the Spring Boot Reference Guide.

As described in spring-io/platform#167, when Spring Boot is used through the Spring.IO platform parent, it's currently necessary to manually set the property

    <properties>
        <servlet-api.version>3.1.0</servlet-api.version>
    </properties>

in your project's `pom.xml` file, in order for 

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-tomcat</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-undertow</artifactId>
        </dependency>

in order to avoid

    Caused by: java.lang.NoClassDefFoundError: javax/servlet/http/HttpSessionIdListener
    	at io.undertow.servlet.core.ApplicationListeners.<clinit>(ApplicationListeners.java:61)
    	at io.undertow.servlet.spec.ServletContextImpl.ensureNotProgramaticListener(ServletContextImpl.java:746)
    	at io.undertow.servlet.spec.ServletContextImpl.getSessionCookieConfig(ServletContextImpl.java:564)
    	at io.undertow.servlet.core.DeploymentManagerImpl.handleDeploymentSessionConfig(DeploymentManagerImpl.java:551)
    	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:153)
    	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.createDeploymentManager(UndertowEmbeddedServletContainerFactory.java:340)
    	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.getEmbeddedServletContainer(UndertowEmbeddedServletContainerFactory.java:203)
    	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:157)
    	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:130)
    	... 35 more
    Caused by: java.lang.ClassNotFoundException: javax.servlet.http.HttpSessionIdListener
    	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
    	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    	... 44 more

**Comment by wilkinsona** [comment]
If this is documented anywhere, it should be in the Platform's docs. Please open an issue there.

**Comment by mikaelhg** [comment]
That would be pretty pointless, given that nobody would think of looking there for help with class loading problems in Spring Boot application context initialization.
