### ISSUE TITLE
EOF exception thrown from tomcat 10.1.8

### ISSUE THREAD

**Issue by PriyaKumar2203** [spring-projects/spring-boot#35126]
```
2023-04-24T13:54:35.322+05:30 DEBUG 2464 --- [alina-utility-1] o.apache.catalina.session.ManagerBase    : Start expire sessions StandardManager at 1682324675318 sessioncount 0
2023-04-24T13:54:35.322+05:30 DEBUG 2464 --- [alina-utility-1] o.apache.catalina.session.ManagerBase    : End expire sessions StandardManager processingTime 4 expired sessions: 0
2023-04-24T13:55:13.791+05:30 DEBUG 2464 --- [o-8030-Acceptor] o.apache.tomcat.util.threads.LimitLatch  : Counting up[http-nio-8030-Acceptor] latch=1
2023-04-24T13:55:13.791+05:30 DEBUG 2464 --- [o-8030-Acceptor] o.apache.tomcat.util.threads.LimitLatch  : Counting up[http-nio-8030-Acceptor] latch=2
2023-04-24T13:55:13.850+05:30 DEBUG 2464 --- [nio-8030-exec-1] o.a.coyote.http11.Http11InputBuffer      : Before fill(): parsingHeader: [true], parsingRequestLine: [true], parsingRequestLinePhase: [0], parsingRequestLineStart: [0], byteBuffer.position(): [0], byteBuffer.limit(): [0], end: [0]
2023-04-24T13:55:13.851+05:30 DEBUG 2464 --- [nio-8030-exec-1] o.a.tomcat.util.net.SocketWrapperBase    : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@7c12dc2d:org.apache.tomcat.util.net.NioChannel@273da089:java.nio.channels.SocketChannel[connected local=/[0:0:0:0:0:0:0:1]:8030 remote=/[0:0:0:0:0:0:0:1]:62284]], Read from buffer: [0]
2023-04-24T13:55:13.851+05:30 DEBUG 2464 --- [nio-8030-exec-1] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header

java.io.EOFException: null
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.fillReadBuffer(NioEndpoint.java:1297)
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.read(NioEndpoint.java:1184)
	at org.apache.coyote.http11.Http11InputBuffer.fill(Http11InputBuffer.java:785)
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:348)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:263)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by wilkinsona** [comment]
Something appears to have sent in invalid HTTP request. This request is causing a parsing failure. If you believe that the request is valid, please report the bug to the Tomcat team including an example of the valid request that causes the parsing failure.
