### ISSUE TITLE
MediaType property binding issue in native builds

### ISSUE THREAD

**Issue by mockxe** [spring-projects/spring-boot#35410]
**Affects:** 6.0.8

---

**issue description:**
When setting a `org.springframework.http.MediaType` via config properties (e.g. `application/json`) it works well when running in jvm, for example by `./gradlew bootRun`. But when running natively, for example by `./gradlew nativeRun` it fails on startup with a property binding issue: `failed to convert java.lang.String to org.springframework.http.MediaType (caused by java.lang.IllegalArgumentException: Invalid token character '/' in token "application/json")` (full error below).
It is possible to fix the native version by specifying the media type as `application-json` but this let's the jvm version fail on startup with a similar issue.

This makes it hard to develop and debug on jvm and deploy as native image, when you use some general default config for both.

**reproduce:**
I encountered this when working with Spring Data REST, when I was setting `spring.data.rest.default-media-type`, but it also can be reproduced by setting up your own config properties which accept a `MediaType`.

full error when starting native build with `application/json` (bootRun works fine)
```
***************************
APPLICATION FAILED TO START
***************************

Description: Failed to bind properties under 'spring.data.rest.default-media-type' to org.springframework.http.MediaType:
Property: spring.data.rest.default-media-type
Value: "application/json"
Origin: class path resource [application.yml] - 13:27
Reason: failed to convert java.lang.String to org.springframework.http.MediaType (caused by java.lang.IllegalArgumentException: Invalid token character '/' in token "application/json")
Action: Update your application's configuration 
```

full error when starting jvm build with `application-json` (nativeRun works fine)
```
***************************
APPLICATION FAILED TO START
***************************

Description: Failed to bind properties under 'spring.data.rest.default-media-type' to org.springframework.http.MediaType:
Property: spring.data.rest.default-media-type
Value: "application-json"
Origin: class path resource [application.yml] - 13:27
Reason: failed to convert java.lang.String to org.springframework.http.MediaType (caused by org.springframework.util.InvalidMimeTypeException: Invalid mime type "application-json": does not contain '/')
Action: Update your application's configuration
```

**possible workarounds:**
 - in general, having multiple configs for developing (jvm) and deployment/production (native)
 - for this specific case with Spring Data REST, setting the media type programmatically via `config.setDefaultMediaType()` 

---
 
If you like I can prepare a repository with a minimal test case.

Thanks for your work

**Comment by mockxe** [comment]
hi and thanks for moving the issue, I wasn't sure where to put it.

regarding your comment: this is exactly the issue I was referring to. Intuitively I would configure a media type with a slash `/` (e.g. `application/json`),  this is also what my IDE suggests. This works well when doing a classic jvm build&run. I use `./gradlew bootRun`.

I also added GraalVM ("GraalVM Native Support", as it's called in Spring Initializr), which gives me the additional gradle task `nativeRun`. When I use this (or any other build that incorporates GraalVM native image build) to run the application, I get the same binding issue that you got.

Apparently, when using a native build, the constructor expects a media type with a dash `-` (e.g. `application-json`), the second option I proposed in my initial report. This works well in native builds, but is not compatible with jvm builds.

Ideally jvm and native build would use the same constructor to accept the same format.

I put together a minimal test case for you: https://github.com/mockxe/native-property-issue
It was created using [Spring Initializr](https://start.spring.io/#!type=gradle-project&language=java&platformVersion=3.0.6&packaging=jar&jvmVersion=17&groupId=io.mockxe&artifactId=native-property-issue&name=native-property-issue&description=&packageName=io.mockxe.native-property-issue&dependencies=native,data-rest,configuration-processor) with framework version 6.0.8 and boot version 3.0.9. I'm on a Liberica Native Image Kit
```
openjdk version "17.0.6" 2023-01-17 LTS
OpenJDK Runtime Environment GraalVM 22.3.1 (build 17.0.6+10-LTS)
OpenJDK 64-Bit Server VM GraalVM 22.3.1 (build 17.0.6+10-LTS, mixed mode, sharing)
```

Please see the test cases README.md for further information

I hope this information helps you.

**Comment by wilkinsona** [comment]
On the JVM, the creation of the `MediaType` is performed by `MediaTypeEditor`:

```
"main" #1 prio=5 os_prio=31 cpu=4988.82ms elapsed=183.75s tid=0x00007fd37a00b000 nid=0x2203 at breakpoint [0x0000700000992000]
   java.lang.Thread.State: RUNNABLE
	at org.springframework.http.MediaType.<init>(MediaType.java:557)
	at org.springframework.http.MediaType.parseMediaType(MediaType.java:745)
	at org.springframework.http.MediaTypeEditor.setAsText(MediaTypeEditor.java:37)
	at org.springframework.beans.TypeConverterDelegate.doConvertTextValue(TypeConverterDelegate.java:425)
	at org.springframework.beans.TypeConverterDelegate.doConvertValue(TypeConverterDelegate.java:398)
	at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:155)
	at org.springframework.beans.TypeConverterSupport.convertIfNecessary(TypeConverterSupport.java:73)
	at org.springframework.beans.TypeConverterSupport.convertIfNecessary(TypeConverterSupport.java:45)
	at org.springframework.boot.context.properties.bind.BindConverter$TypeConverterConverter.convert(BindConverter.java:221)
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:41)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:192)
	at org.springframework.boot.context.properties.bind.BindConverter.convert(BindConverter.java:109)
	at org.springframework.boot.context.properties.bind.BindConverter.convert(BindConverter.java:100)
	at org.springframework.boot.context.properties.bind.BindConverter.convert(BindConverter.java:92)
	at org.springframework.boot.context.properties.bind.Binder.bindProperty(Binder.java:459)
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:403)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:343)
	…
```

**Comment by firasrg** [comment]
Hello! I'd like to contribute here, it's my first time 😇. Is it possible ?

**Comment by quaff** [comment]
`ObjectToObjectConverter` is used if `spring-boot-starter-data-rest` present
```
     Caused by: org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [org.springframework.http.MediaType] for value [application/json]
       org.springframework.core.convert.support.ObjectToObjectConverter.convert(ObjectToObjectConverter.java:117)
       org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:41)
       org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:192)
       org.springframework.boot.context.properties.bind.BindConverter.convert(BindConverter.java:109)
       org.springframework.boot.context.properties.bind.BindConverter.convert(BindConverter.java:100)
       [...]
     Caused by: java.lang.IllegalArgumentException: Invalid token character '/' in token "application/json"
       org.springframework.util.MimeType.checkToken(MimeType.java:224)
       org.springframework.util.MimeType.<init>(MimeType.java:183)
       org.springframework.util.MimeType.<init>(MimeType.java:134)
       org.springframework.util.MimeType.<init>(MimeType.java:123)
       org.springframework.http.MediaType.<init>(MediaType.java:478)
       [...]
```

`ConverterNotFoundException` is thrown if we change `spring-boot-starter-data-rest` to `spring-boot-starter-web`
```
     Caused by: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [org.springframework.http.MediaType]
       org.springframework.boot.context.properties.bind.BindConverter.convert(BindConverter.java:118)
       org.springframework.boot.context.properties.bind.BindConverter.convert(BindConverter.java:100)
       org.springframework.boot.context.properties.bind.BindConverter.convert(BindConverter.java:92)
       org.springframework.boot.context.properties.bind.Binder.bindProperty(Binder.java:459)
       org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:403)
       [...]
```

**Comment by wilkinsona** [comment]
The problem's occurring because `MediaTypeEditor` is hidden due to a lack of reflection hint metadata for it. This prevents `BeanUtils.findEditorByConvention(Class<?>)` from creating and returning a `MediaTypeEditor` instance. A workaround is to provide a `RuntimeHintsRegistar` that registers the required reflection hint:

```java
static class PropertyEditorRuntimeHints implements RuntimeHintsRegistrar {

	@Override
	public void registerHints(RuntimeHints hints, ClassLoader classLoader) {
		hints.reflection().registerType(MediaTypeEditor.class, MemberCategory.INVOKE_PUBLIC_CONSTRUCTORS);
	}
		
}
```

This registrar must be imported using `@ImportRuntimeHints(PropertyEditorRuntimeHints.class)`.
