### ISSUE TITLE
BeanCreationException: Error creating bean with name "xxxxxx" defined in file : Bean instantiation via constructor failed.

### ISSUE THREAD

**Issue by nagaraju1692** [spring-projects/spring-boot#35419]
I have migrating spring boot application from java 11 to 19 , After changed the java version , I am able to build the application, But while running the server getting error as below.
Note: (Same code working for java 11);

Kindly let me know , if i missed something while migrating the java from 11 to 19.

Error Log:
=======

org.springframework.beans. factory. BeanCreationException: Error creating bean with name 'agentTable' defined in file
[C: \Nagaraju\Applications \pushkunBackend bitbucket\pushkun-backend\build\classes \java \main\jp\co\metlife\matterhorn\dal\AgentTable.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans. BeanInstantiationException: Failed to instantiate [jp.co.metlife.matterhorn.dal.AgentTable]: Constructor threw exception; nested exception is java. lang. ExceptionInInitializerError
org.springframework.beans. factory. support. ConstructorResolver. instantiate (ConstructorResolver. java: 315) ~ [spring-beans-5.3.23.jar: 5.3.231 at org.springframework.beans. factory. support. ConstructorResolver.autowireConstructor (ConstructorResolver. java: 296) ~ [spring-beans-5.3.23.jar: 5.3.23]
at org. springframework.beans. factory. support. AbstractAutowireCapableBeanFactory. autowireConstructor (AbstractAutowireCapableBeanFactory. java: 1372) ~ [spring-beans-5.3.23.jar: 5.3.23]
at org. springframework. beans. factory. support.AbstractAutowireCapableBeanFactory. createBeanInstance (AbstractAutowireCapableBeanFactory. java: 1222)
~[spring-beans-5.3.23.jar: 5.3.23]
at org.springframework.beans. factory. support. AbstractAutowireCapableBeanFactory. doCreateBean (AbstractAutowireCapableBeanFactory. java: 582) ~ [spring-beans-5.3.23.jar: 5.3.23]
at org.springframework.beans. factory. support.AbstractAutowireCapableBeanFactory.createBean (AbstractAutowireCapableBeanFactory. java: 542)
~ [spring-beans-5.3.23.jar: 5.3.23]
at org.springframework.beans. factory.support.AbstractBeanFactory. lambda$doGetBean$0 (AbstractBeanFactory. java: 335) ~ [spring-beans-5.3.23.jar: 5.3.231 at org.springframework.beans. factory.support. DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~ [spring-beans-5.3.23.jar: 5.3.23]
at org. springframework.beans. factory. support. AbstractBeanFactory. doGetBean (AbstractBeanFactory. java: 333) ~ [spring-beans-5.3.23.jar: 5.3.23] at org. springframework.beans. factory.support.AbstractBeanFactory-getBean (AbstractBeanFactory.java: 208) ~ [spring-beans-5.3.23.jar: 5.3.23] at org.springframework.beans. factory. support. DefaultListableBeanFactory. preInstantiateSingletons (DefaultListableBeanFactory. java: 955) ~ [spring-beans-5.3.23.jar: 5.3.231
at org.springframework.context. support.AbstractApplicationContext.finishBeanFactoryInitialization (AbstractApplicationContext.java: 918)
-[spring-context-5.3.23.jar: 5.3.23]
at org. springframework.context. support. AbstractApplicationContext.refresh (AbstractApplicationContext. java:583) ~ [spring-context-5.3.23.jar: 5.3.23] at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~ [spring-boot-2.6.13.jar: 2.6.13]
at org.springframework.boot.SpringApplication.refresh (SpringApplication.java:745) ~ [spring-boot-2.6.13.jar:2.6.13] at org.springframework.boot.SpringApplication. refreshContext (SpringApplication. java: 420) ~ [spring-boot-2.6.13.jar:2.6.13]
ат.

at org.springframework.boot.SpringApplication.run (SpringApplication.java: 307) ~ [spring-boot-2.6.13.jar:2.6.13] at org.springframework.boot.SpringApplication.run (SpringApplication. java: 1317) ~ [spring-boot-2.6.13.jar:2.6.13] at org.springframework.boot.SpringApplication.run (SpringApplication. java: 1306) ~ [spring-boot-2.6.13.jar: 2.6.13] at jp.co.metlife.matterhorn.Application.main (Application.java: 10) ~ [main/: na]
at java.base/jdk.internal.reflect. DirectMethodHandleAccessor. invoke (DirectMethodHandleAccessor. java: 104) ~ [na: na] at java.base/java.lang.reflect. Method. invoke (Method. java: 578) ~ [na: na] at org.springframework.boot.devtools. restart. RestartLauncher. run (RestartLauncher. java: 49) ~ [spring-boot-devtools-2.6.13.jar: 2.6.13]
Caused by: org. springframework.beans. BeanInstantiationException: Failed to instantiate [jp.co.metlife.matterhorn.dal.AgentTable]: Constructor threw exception; nested exception is java.lang. ExceptionInInitializerError

at org.springframework.beans. BeanUtils.instantiateClass (BeanUtils. java: 224) ~ [spring-beans-5.3.23.jar: 5.3.23] at org.springframework.beans. factory. support. SimpleInstantiationStrategy. instantiate (SimpleInstantiationStrategy. java:117) ~ [spring-beans-5.3.23.jar: 5.3.23]

Caused by: java.lang.ExceptionInInitializerError: null

org.skife.jdbi.v2.sqlöbject.SqlObject.buildSqlObject(SqlObject.java:71)~[jdbi-2.78.jar:2.78]
at org.skife.jdbi.v2.sqlobject.SqlObjectBuilder.onDemand(SqlObjectBuilder.java:64)~[jdbi-2.78.jar:2.78]
at org.skife.jdbi.v2. DBI. onDemand (DBI. java: 415) ~ [jdbi-2.78.jar: 2.781 at jp.co.metlife.matterhorn.dal.AgentTable.<init>(AgentTable.java:28)~[main/:na]
at java.base/jdk.internal. reflect. DirectConstructorHandleAccessor.newInstance (DirectConstructorlandleAccessor. java: 67) - [na:na) at java.base/java.lang. reflect.Constructor.newInstancewithCaller (Constructor. java: 500) ~ [na:nal at java.base/java.lang. reflect.Constructor. newInstance (Constructor. java: 484) ~ [na: nal at org.springframework.beans.BeanUtils.instantiateClass (BeanUtils.java:211) ~ [spring-beans-5.3.23.jar: 5.3.23]
24 common frames omitted
Caused by: java. lang. IllegalStateException: Unable to load cache item
at org.skife.jdbi.cglib.core.internal. LoadingCache.createEntry (LoadingCache.java: 79) ~ Lidbi-2.78.jar: 2.781
at org.skife.jdbi.cglib.core.internal. LoadingCache.get (LoadingCache. java: 34) ~ [jdbi-2.78.jar:2.781 at org.skife.jdbi.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:105)~[jdbi-2.78.jar:2.78] at org.skife.jdbi.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:278)~[jdbi-2.78.jar:2.78] at org.skife.jdbi.cglib.core.KeyFactory$Generator.create(KeyFactory.java:221).~[jdbi-2.78.jar:2.781 at org.skife.jdbi.cglib.core.KeyFactory.create (KeyFactory. java: 174) ~ [jdbi-2.78.jar:2.78] at org.skife.jdbi.cglib.core.KeyFactory.create(KeyFactory.java:153)~[idbi-2.78.jar:2.781 at org.skife.jdbi.cglib.proxy. Enhancer.<clinit> (Enhancer. java: 73) ~ [jdbi-2.78.jar:2.78]
32 common frames omitted
Caused by: java.lang.ExceptionInInitializerError: null
at org.skife.jdbi.cglib.core.KeyFactory$Generator.generateClass(KeyFactory-java:243)~[jdbi-2.78.jar:2.78]
at. ora.skife.idbi.calib.core.DefaultGeneratorStrateov.generate/DefaultGeneratorStrateav.java:25)~lidbi-2.78.jar:2.781

at org.skife.jdbi.cglib.core.KeyFactory$Generator.generateClass(KeyFactory.java:243)~[jdbi-2.78.jar:2.78]
103
at org.skife.jdbi.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy-java:25)~[jdbi-2.78.jar:2.78]
104
at org.skife.jdbi.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:312)~[jdbi-2.78.jar:2.78]
105
at org.skife.jdbi.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:85)~[jdbi-2.78.jar:2.78]
106
at org.skife.jdbi.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:83)~[jdbi-2.78.jar:2.78]
|107
at org.skife.jdbi.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)~[jdbi-2.78.jar:2.78]
at java.base/java.util.concurrent.FutureTask.run (FutureTask. java: 317) ~ [na:na]
108
109
at org.skife.jdbi.cglib.core.internal. LoadingCache.createEntry (LoadingCache. java: 61) ~ [jdbi-2.78.jar:2.78]
39 common frames omitted
110
Caused by: java.lang. reflect. InaccessibleObjectException: Unable to make protected final java. lang. Class
java.lang. ClassLoader.defineClass (java. lang. String, byte [I, int, int, java.security. ProtectionDomain) throws java. lang. ClassFormatError accessible:
module java.base does not "opens java. lang" to unnamed module @2965cd00
111
at java.base/java.lang.reflect. AccessibleObject.throwInaccessibleObjectException (AccessibleObject. java: 387). ~ [na: na]
112
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible (AccessibleObject.java: 363) ~ [na: na]
113 •
at java.base/java. lang. reflect. AccessibleObject.checkCanSetAccessible (AccessibleObject. java: 311) ~ [na:na]
114
115
at java.base/java.lang.reflect.Method.checkCanSetAccessible (Method. java: 201) ~ [na:na] at java.base/java.lang.reflect. Method.setAccessible (Method. java: 195) ~ [na:na]
116
at org.skife.jdbi.cglib.core.ReflectUtils$1.run (ReflectUtils.java:54) ~ [jdbi-2.78.jar:2.78]
117
at java.base/java.security.AccessController.doPrivileged (AccessController. java:318) ~ [nana]
118
at org.skife.jdbi.cglib.core.ReflectUtils.<clinit>(ReflectUtils.java:44)~[jdbi-2.78.jar:2.78]

**Comment by nagaraju1692** [comment]
That solution is not clear, Could you please elaborate which JDBI version need to use to fix the issues.

**Comment by wilkinsona** [comment]
Sorry, I don't know. The Spring Boot issue tracker is not the right place to ask for help with JDBI.
