### ISSUE TITLE
Cassandra external config loading fails in reactive context

### ISSUE THREAD

**Issue by ncheutin** [spring-projects/spring-boot#35672]
Hello,

When using external Cassandra config ( `datastax-java-driver { ... }` ) on a reactive project it fails with exception:
config:
```yaml
spring:
  cassandra:
    config: cassandra.conf
```

Exception:
```
Caused by: java.io.FileNotFoundException: ReactiveWebContext resource [cassandra.conf] cannot be resolved to URL
	at org.springframework.core.io.AbstractResource.getURL(AbstractResource.java:108)
	at org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration.loadConfig(CassandraAutoConfiguration.java:187)
	... 124 common frames omitted
```

The reason seems to be that in a reactive project resources are of type [`FilteredReactiveWebContextResource`](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/reactive/context/FilteredReactiveWebContextResource.java) that do not implement `getURL()`.

Then it fails in [CassandraAutoConfiguration](https://github.com/spring-projects/spring-boot/blob/2.7.x/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/cassandra/CassandraAutoConfiguration.java#L145).

I would expect that such scenario would be possible.

As workaround we can use the following, but I would still expect it to work by default like in a non-reactive context:
```yaml
spring:
  cassandra:
    config: classpath:cassandra.conf
```

Thanks

**Comment by ncheutin** [comment]
@scottfrederick apologies for the delay.
Attaching a demo project reproducing it.
[cassandra-reactive-demo.zip](https://github.com/spring-projects/spring-boot/files/11714322/cassandra-reactive-demo.zip)

**Comment by ncheutin** [comment]
@scottfrederick thanks for the detailed explanation.

If that's the way to go, fine with it.

The reason I thought it was a limitation only in reactive context is because in [this AWS example](https://github.com/aws-samples/amazon-keyspaces-examples/blob/main/java/datastax-v4/spring/src/main/resources/application.properties) it works without a `file:` or `classpath:` prefix for a reason I still do not understand.

**Comment by ncheutin** [comment]
Thanks again for the detailed explanation. 
Much appreciated.
