### ISSUE TITLE
Test Gradle Plugin against 8.2-rc-1

### ISSUE THREAD

**Issue by rpalcolea** [spring-projects/spring-boot#35699]
Hi folks,

Gradle 8.2 is around the corner with nagging around the usage of `Project.getConvention` -> https://docs.gradle.org/8.2-rc-1/userguide/upgrading_version_8.html#deprecated_access_to_conventions

This is the piece causing the warning https://github.com/spring-projects/spring-boot/blob/2.7.x/spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/main/java/org/springframework/boot/gradle/plugin/JavaPluginAction.java#L169 and some logs:

```
The Project.getConvention() method has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.2-rc-1/userguide/upgrading_version_8.html#deprecated_access_to_conventions
	at org.gradle.api.internal.project.DefaultProject.getConvention(DefaultProject.java:593)
	at org.springframework.boot.gradle.plugin.JavaPluginAction.sourceSets(JavaPluginAction.java:169)
	at org.springframework.boot.gradle.plugin.JavaPluginAction.configureBootJarTask(JavaPluginAction.java:102)
	at org.springframework.boot.gradle.plugin.JavaPluginAction.execute(JavaPluginAction.java:80)
	at org.springframework.boot.gradle.plugin.JavaPluginAction.execute(JavaPluginAction.java:60)
	at org.springframework.boot.gradle.plugin.SpringBootPlugin.lambda$null$0(SpringBootPlugin.java:126)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1.execute
```

While this is not a problem with Spring Boot Gradle Plugin 3.x, this could impact folks running with 2.7.x if Gradle 9.x comes out before they migrated to Spring Boot 3.x. 

Is 2.7.x still receiving changes? if so, would it make sense to change that usage from `JavaPluginConvention` to `JavaPluginExtension` instead?

**Comment by rpalcolea** [comment]
oh that was fast! Thanks @wilkinsona !
