### ISSUE TITLE
Provide a mechanism for disabling logging framework customisation and initialisation

### ISSUE THREAD

**Issue by ksmith14** [spring-projects/spring-boot#3571]
I'm attempting to use a Spring Boot powered WAR in a standalone instance of Jetty 9.3.1 that's been configured to do [centralized logging](http://www.eclipse.org/jetty/documentation/current/example-logging-logback-centralized.html), but the Logback support supplied by Spring Boot (i.e. LogbackLoggingSystem) appears to be causing a StackOverflowError:

```
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.eclipse.jetty.start.Main.invokeMain(Main.java:214)
    at org.eclipse.jetty.start.Main.start(Main.java:457)
    at org.eclipse.jetty.start.Main.main(Main.java:75)
Caused by: java.lang.StackOverflowError
    at java.io.UnixFileSystem.getBooleanAttributes0(Native Method)
    at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:242)
    at java.io.File.exists(File.java:819)
    at sun.misc.URLClassPath$FileLoader.getResource(URLClassPath.java:1245)
    at sun.misc.URLClassPath.getResource(URLClassPath.java:212)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:365)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    at org.eclipse.jetty.webapp.WebAppClassLoader.findClass(WebAppClassLoader.java:524)
    at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:457)
    at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:417)
    at org.springframework.boot.logging.logback.LogbackLoggingSystem$1.decide(LogbackLoggingSystem.java:71)
    at ch.qos.logback.classic.spi.TurboFilterList.getTurboFilterChainDecision(TurboFilterList.java:62)
    at ch.qos.logback.classic.LoggerContext.getTurboFilterChainDecision_0_3OrMore(LoggerContext.java:252)
    at ch.qos.logback.classic.Logger.callTurboFilters(Logger.java:772)
    at ch.qos.logback.classic.Logger.isDebugEnabled(Logger.java:490)
    at ch.qos.logback.classic.Logger.isDebugEnabled(Logger.java:486)
    at org.eclipse.jetty.util.log.JettyAwareLogger.isDebugEnabled(JettyAwareLogger.java:170)
    at org.eclipse.jetty.util.log.Slf4jLog.isDebugEnabled(Slf4jLog.java:110)
    at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:474)
    at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:417)
    at org.springframework.boot.logging.logback.LogbackLoggingSystem$1.decide(LogbackLoggingSystem.java:71)
    at ch.qos.logback.classic.spi.TurboFilterList.getTurboFilterChainDecision(TurboFilterList.java:62)
    at ch.qos.logback.classic.LoggerContext.getTurboFilterChainDecision_0_3OrMore(LoggerContext.java:252)
    at ch.qos.logback.classic.Logger.callTurboFilters(Logger.java:772)
    at ch.qos.logback.classic.Logger.isDebugEnabled(Logger.java:490)
    at ch.qos.logback.classic.Logger.isDebugEnabled(Logger.java:486)
    ...
```

I've tested it and it occurs with both Spring Boot 1.2.3.RELEASE and 1.2.5.RELEASE.

Here is a sample app to reproduce the problem (generated by Spring Initialzr with a couple of dependency tweaks): https://github.com/ksmith14/spring-boot-demo Just run `gradle war` and drop it in the Jetty webapps directory, then start Jetty (assuming it's been configured using the steps linked above).

**Comment by wilkinsona** [comment]
Spring Boot installs a filter with Logback. When a logging call is made, this filter is called and it triggers an attempt to load a class. Jetty's WebAppClassLoader is used. Unfortunately, it tries to perform some logging as part of loading the class. This results in the filter being called again. The class that the filter needs still hasn't been loaded so Jetty's WebAppClassLoader is called again and it tries to log something again. This results in an infinite loop.

Arguably, this is a bug in Jetty's centralized logging. We could consider providing a mechanism to switch off Spring Boot's logging support entirely to work around it.

**Comment by abhs50** [comment]
Hi Guys. Is there a ETA on when this issue will be pushed into release branch ?

**Comment by wilkinsona** [comment]
@abhs50 The change is already in master so it'll be in 1.4.0.M2 which is scheduled for release next week.

**Comment by abhs50** [comment]
@wilkinsona : Thanks for the update. Is there a release calendar I can look at to track this.

**Comment by spencergibb** [comment]
https://github.com/spring-projects/spring-boot/milestones

**Comment by ihrigb** [comment]
Is this fix in the current version (1.3.5.RELEASE)?

**Comment by wilkinsona** [comment]
@ihrigb No, as shown by this issue's milestone, it's in 1.4.0.M2 and later

**Comment by ihrigb** [comment]
Ok, I just thought it could have been in there. Thanks!
