### ISSUE TITLE
Native Image: Error with SpringBoot3.0.6 and SQL Server

### ISSUE THREAD

**Issue by yourchanges** [spring-projects/spring-boot#35793]
**Describe the issue**
Start a springboot3.0.6 project with sqlserver jdbc driver,  and build with graalvm-ce-java17-22.3.2 via "mvn -Pnative clean native:compile  -DskipTests=true -Dmaven.test.skip=true", it runs failed when query the db data

here is the exception
```
com.microsoft.sqlserver.jdbc.SQLServerException: Windows collation zh_CN is not supported by this driver. ClientConnectionId:4f2aa65f-5ccb-4d62-b871-9a4f8c1d0223
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:3806) ~[mybatisnativedemo:na]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.processEnvChange(SQLServerConnection.java:4983) ~[mybatisnativedemo:na]
        at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEnvChange(tdsparser.java:216) ~[mybatisnativedemo:na]
        at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:84) ~[na:na]
        at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37) ~[na:na]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:6299) ~[mybatisnativedemo:na]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:4911) ~[mybatisnativedemo:na]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:4849) ~[mybatisnativedemo:na]
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7620) ~[mybatisnativedemo:na]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3916) ~[mybatisnativedemo:na]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3358) ~[mybatisnativedemo:na]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2950) ~[mybatisnativedemo:na]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2790) ~[mybatisnativedemo:na]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1663) ~[mybatisnativedemo:na]
        at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1064) ~[mybatisnativedemo:na]
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[na:na]
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[mybatisnativedemo:na]
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[mybatisnativedemo:na]
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[na:na]
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[na:na]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100) ~[na:na]
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[mybatisnativedemo:na]
        at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:159) ~[na:na]
        at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:117) ~[na:na]
        at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80) ~[na:na]
        at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:80) ~[na:na]
        at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:67) ~[na:na]
        at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:337) ~[mybatisnativedemo:3.5.11]
        at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:86) ~[na:na]
        at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62) ~[na:na]
        at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325) ~[mybatisnativedemo:3.5.11]
        at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156) ~[mybatisnativedemo:3.5.11]
        at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109) ~[na:na]
        at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:89) ~[na:na]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:151) ~[na:na]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:145) ~[na:na]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140) ~[na:na]
        at java.base@17.0.7/java.lang.reflect.Method.invoke(Method.java:568) ~[mybatisnativedemo:na]
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:425) ~[na:na]
        at jdk.proxy4/jdk.proxy4.$Proxy129.selectList(Unknown Source) ~[na:na]
        at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:224) ~[mybatisnativedemo:3.0.1]
        at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:147) ~[na:na]
        at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:80) ~[na:na]
        at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:145) ~[na:na]
        at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86) ~[na:na]
        at jdk.proxy4/jdk.proxy4.$Proxy48.queryImeiInfoV2(Unknown Source) ~[na:na]
        at com.example.mybatisnativedemo.service.impl.ImeiInfoServiceImpl.queryImeiInfoV2(ImeiInfoServiceImpl.java:21) ~[mybatisnativedemo:na]
        at com.example.mybatisnativedemo.web.IMEIController.queryInfoV2(IMEIController.java:43) ~[mybatisnativedemo:na]
        at java.base@17.0.7/java.lang.reflect.Method.invoke(Method.java:568) ~[mybatisnativedemo:na]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207) ~[mybatisnativedemo:6.0.8]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152) ~[mybatisnativedemo:6.0.8]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[mybatisnativedemo:6.0.8]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[mybatisnativedemo:6.0.8]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[mybatisnativedemo:6.0.8]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[mybatisnativedemo:6.0.8]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081) ~[mybatisnativedemo:6.0.8]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974) ~[mybatisnativedemo:6.0.8]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011) ~[mybatisnativedemo:6.0.8]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903) ~[mybatisnativedemo:6.0.8]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:564) ~[mybatisnativedemo:6.0]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[mybatisnativedemo:6.0.8]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) ~[mybatisnativedemo:6.0]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[na:na]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[mybatisnativedemo:10.1.8]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[na:na]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[mybatisnativedemo:6.0.8]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[mybatisnativedemo:6.0.8]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[na:na]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[mybatisnativedemo:6.0.8]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[mybatisnativedemo:6.0.8]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[na:na]
        at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109) ~[mybatisnativedemo:6.0.8]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[mybatisnativedemo:6.0.8]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[na:na]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[mybatisnativedemo:6.0.8]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[mybatisnativedemo:6.0.8]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[na:na]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166) ~[na:na]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[na:na]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482) ~[mybatisnativedemo:10.1.8]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) ~[na:na]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[mybatisnativedemo:10.1.8]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[na:na]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341) ~[na:na]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390) ~[na:na]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[mybatisnativedemo:10.1.8]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894) ~[na:na]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741) ~[na:na]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[mybatisnativedemo:10.1.8]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[na:na]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[na:na]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[na:na]
        at java.base@17.0.7/java.lang.Thread.run(Thread.java:833) ~[mybatisnativedemo:na]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775) ~[mybatisnativedemo:na]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203) ~[na:na]
Caused by: java.io.UnsupportedEncodingException: Windows collation zh_CN is not supported by this driver.
        at com.microsoft.sqlserver.jdbc.SQLCollation.encodingFromLCID(SQLCollation.java:367) ~[na:na]
        at com.microsoft.sqlserver.jdbc.SQLCollation.<init>(SQLCollation.java:97) ~[na:na]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.processEnvChange(SQLServerConnection.java:4981) ~[mybatisnativedemo:na]
        ... 99 common frames omitted
Caused by: java.io.UnsupportedEncodingException: Codepage MS936 is not supported by the Java environment.
        at com.microsoft.sqlserver.jdbc.Encoding.checkSupported(SQLCollation.java:600) ~[mybatisnativedemo:na]
        at com.microsoft.sqlserver.jdbc.SQLCollation$WindowsLocale.getEncoding(SQLCollation.java:345) ~[mybatisnativedemo:na]
        at com.microsoft.sqlserver.jdbc.SQLCollation.encodingFromLCID(SQLCollation.java:363) ~[na:na]
        ... 101 common frames omitted

```

**Comment by snicoll** [comment]
@yourchanges I am not sure why you're reporting this against Spring Boot. From the stack trace, it looks something related to either the SQL Server driver, or your environment. You may find https://github.com/oracle/graal/issues/1370 to be useful. If not, please ask on StackOverflow.

**Comment by yourchanges** [comment]
workaround by add “-H:+AddAllCharsets” in compile phase
```
<plugin>
				<groupId>org.graalvm.buildtools</groupId>
				<artifactId>native-maven-plugin</artifactId>
				<configuration>
					<buildArgs combine.children="append">
						<buildArg>--enable-url-protocols=http</buildArg>
						<buildArg>-H:+AddAllCharsets</buildArg>
					</buildArgs>
				</configuration>
			</plugin>
```

**Comment by Grey1024** [comment]
I am a Java backend programmer from China, and I have lost my job. Now, I am looking for a coding job outside of China, and I don’t mind the salary. I am even willing to work for free. Additionally, I hope to improve my English communication skills. If you need my help, please contact me at [jeeun2023@outlook.com](mailto:jeeun2023@outlook.com).
I just want to find something to do; I love programming. If you have the patience to explain your work tasks to someone whose English is not good, I am willing to work for you without caring about payment.
