### ISSUE TITLE
Spring Data Solr Unable to locate Attribute

### ISSUE THREAD

**Issue by anthonyvialleton** [spring-projects/spring-boot#3585]
This : 

```java
@Repository
public interface DocumentSolrRepository extends SolrCrudRepository<Document, Long>, DocumentSolrRepositoryCustom {
    Set<Document> findByTextContaining(@Param("text") String test);
}
```

...was working fine until I manage to migrate to **Spring Boot**.

Before I was using version spring-data-solr version : **1.4.0.RELEASE** and now **Boot just got version 1.3.3**.

I tried to remove the **spring-boot-starter-data-solr** and **reset to static but I got the same issue**..

Error stacktrace : 

```
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'applicantController': Injection of resource dependencies failed;

Caused by: java.lang.IllegalArgumentException: Unable to locate Attribute  with the the given name [text] on this ManagedType [com.entity.Document]
    at org.hibernate.jpa.internal.metamodel.AbstractManagedType.checkNotNull(AbstractManagedType.java:144)
    at org.hibernate.jpa.internal.metamodel.AbstractManagedType.getAttribute(AbstractManagedType.java:130)
    at org.springframework.data.jpa.repository.query.QueryUtils.toExpressionRecursively(QueryUtils.java:475)
    at org.springframework.data.jpa.repository.query.JpaQueryCreator$PredicateBuilder.build(JpaQueryCreator.java:199)
    at org.springframework.data.jpa.repository.query.JpaQueryCreator.toPredicate(JpaQueryCreator.java:146)
    at org.springframework.data.jpa.repository.query.JpaQueryCreator.create(JpaQueryCreator.java:86)
    at org.springframework.data.jpa.repository.query.JpaQueryCreator.create(JpaQueryCreator.java:44)
    at org.springframework.data.repository.query.parser.AbstractQueryCreator.createCriteria(AbstractQueryCreator.java:109)
    at org.springframework.data.repository.query.parser.AbstractQueryCreator.createQuery(AbstractQueryCreator.java:88)
    at org.springframework.data.repository.query.parser.AbstractQueryCreator.createQuery(AbstractQueryCreator.java:73)
    at org.springframework.data.jpa.repository.query.PartTreeJpaQuery$QueryPreparer.<init>(PartTreeJpaQuery.java:110)
    at org.springframework.data.jpa.repository.query.PartTreeJpaQuery$CountQueryPreparer.<init>(PartTreeJpaQuery.java:230)
    at org.springframework.data.jpa.repository.query.PartTreeJpaQuery.<init>(PartTreeJpaQuery.java:64)
    at org.springframework.data.jpa.repository.query.JpaQueryLookupStrategy$CreateQueryLookupStrategy.resolveQuery(JpaQueryLookupStrategy.java:94)
    ... 68 more
```
Thx.

**Comment by wilkinsona** [comment]
And please don't deliberately post duplicate issues, it's just a waste of everyone's time. In addition to thousands of members of the community, the Spring Boot and Spring Data teams both monitor Stackoverflow. Someone will help you if they can when they have the time to do so.
