### ISSUE TITLE
JerseyAutoConfiguration fails with ClassNotFoundException in Tomcat WebContainer with IBM JDK6

### ISSUE THREAD

**Issue by rPraml** [spring-projects/spring-boot#3597]
If I try to run my webApp in Tomcat, I get a 
```
javax.servlet.ServletException: Failed to instantiate WebApplicationInitializer class
	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:160)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5517)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
...
Caused by: java.lang.NoClassDefFoundError: org.glassfish.jersey.server.ResourceConfig
...
Caused by: java.lang.ClassNotFoundException: org.glassfish.jersey.server.ResourceConfig
```

The problem is, that Tomcat tries to initialize all WebApplicationInitializer which will fail if the class references other classes (like ResourceConfig) that are not in the ClassPath.

I think it is wrong to implement WebApplicationListener in 
https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jersey/JerseyAutoConfiguration.java 
(Better split up in two files)

**Comment by snicoll** [comment]
Can you explain your setup please? That class implements `WebApplicationListener` for more than a year and we have tons of deployments using tomcat. 

Can you share a sample project please?

**Comment by rPraml** [comment]
I tried to build a small sample application and figured out, that the issue is related to my VM.
I use the VM from the IBM Lotus Domino server and it seems that this causes the issue

I've uploaded my sample project here
https://www.dropbox.com/s/n44zqja8jsrmiya/spring-boot-sample-app.zip?dl=0
and provided detailed information in the readme.txt:
```
This sample project describes the "NoClassDefFoundError: org.glassfish.jersey.server.ResourceConfig"
that I get if I try to run a WAR file in a Tomcat Container.

First, I've to say, this issue can't be reproduced with a standard Oracle VM (Tried: jdk1.6.0_45  jdk1.8.0_40  jre1.8.0_40)
I can only reproduce it with the JVM from IBM (that one that is shipped with Notes/Domino)

  $ java -version
  java version "1.6.0"
  Java(TM) SE Runtime Environment (build pwa6460sr16fp3ifix-20150325_01(SR16 FP3+IV70681+IV69513))
  IBM J9 VM (build 2.4, JRE 1.6.0 IBM J9 2.4 Windows 7 amd64-64 jvmwa6460sr16-20150325_241329 (JIT enabled, AOT enabled)
  J9VM - 20150325_241329
  JIT  - r9_20140523_64469ifx3
  GC   - GA24_Java6_SR16_20150325_0550_B241329)
  JCL  - 20141216_01

I know this VM is quite old, but I'm tied to this version, because it is the default VM of the Lotus Domino Server


To reproduce the issue:

1. compile everything with "mvn package" (with standard Oracle VM >= 1.7) 

2. Run the war in a Tomcat container using the Lotus/Domino VM.
   I bundled the Tomcat7 webapprunner (https://github.com/jsimone/webapp-runner) with this demo.

path/to/domino/jvm/bin/java -jar webapp-runner.jar target/myproject-0.0.1-SNAPSHOT.war

You will get this ouput:

------- output ----------
Adding Context  for target\myproject-0.0.1-SNAPSHOT.war
27.07.2015 14:07:22 org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-8080"]
27.07.2015 14:07:22 org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
INFO: Using a shared selector for servlet write/read
27.07.2015 14:07:22 org.apache.catalina.core.StandardService startInternal
INFO: Starting service Tomcat
27.07.2015 14:07:22 org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.57
27.07.2015 14:07:23 org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
INFO: No global web.xml found
27.07.2015 14:07:24 org.apache.catalina.startup.ContextConfig processAnnotationsJar
SEVERE: Unable to process Jar entry [org/springframework/beans/factory/parsing/ProblemReporter.class] from Jar [jar:jndi:/localhost/WEB-INF/lib/spring-beans-4.1
.6.RELEASE.jar!/] for annotations
Throwable occurred: java.io.EOFException
        at org.apache.tomcat.util.bcel.classfile.FastDataInputStream.readInt(FastDataInputStream.java:145)
        at org.apache.tomcat.util.bcel.classfile.ClassParser.readID(ClassParser.java:200)
        at org.apache.tomcat.util.bcel.classfile.ClassParser.parse(ClassParser.java:78)
        at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2071)
        at org.apache.catalina.startup.ContextConfig.processAnnotationsJar(ContextConfig.java:1947)
        at org.apache.catalina.startup.ContextConfig.processAnnotationsUrl(ContextConfig.java:1913)
        at org.apache.catalina.startup.ContextConfig.processAnnotations(ContextConfig.java:1898)
        at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1330)
        at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:889)
        at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:386)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5380)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1575)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1565)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:314)
        at java.util.concurrent.FutureTask.run(FutureTask.java:149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
        at java.lang.Thread.run(Thread.java:767)
27.07.2015 14:07:25 org.apache.catalina.core.StandardContext startInternal
SEVERE: Error during ServletContainerInitializer processing
Throwable occurred: javax.servlet.ServletException: Failed to instantiate WebApplicationInitializer class
        at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:160)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5481)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1575)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1565)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:314)
        at java.util.concurrent.FutureTask.run(FutureTask.java:149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
        at java.lang.Thread.run(Thread.java:767)
Caused by: java.lang.NoClassDefFoundError: org.glassfish.jersey.server.ResourceConfig
        at java.lang.J9VMInternals.verifyImpl(Native Method)
        at java.lang.J9VMInternals.verify(J9VMInternals.java:73)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:133)
        at java.lang.J9VMInternals.newInstanceImpl(Native Method)
        at java.lang.Class.newInstance(Class.java:1688)
        at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:157)
        ... 9 more
Caused by: java.lang.ClassNotFoundException: org.glassfish.jersey.server.ResourceConfig
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1720)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1571)
        ... 15 more
27.07.2015 14:07:25 org.apache.catalina.util.SessionIdGenerator createSecureRandom
INFO: Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [104] milliseconds.
27.07.2015 14:07:25 org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [] startup failed due to previous errors
SEVERE: Context [] failed in [org.apache.catalina.core.StandardContext] lifecycle. Allowing Tomcat to shutdown.
27.07.2015 14:07:25 org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-nio-8080"]
27.07.2015 14:07:25 org.apache.coyote.AbstractProtocol pause
INFO: Pausing ProtocolHandler ["http-nio-8080"]
----------------------------------------


The first "java.io.EOFException" doesn't matter here.
But then, the Tomcat container searches for WebApplicationInitializer and tries to create a new instance of 
"JerseyAutoConfiguration" (I debugged that)

I assume that the Domino VM is specially hardened by IBM and verifies if all class-fields have a valid declaration.
Unfortunately, the class in declaration "private ResourceConfig config;" does not exist and throws a CNFE.

As workaround, I've created an empty "org.glassfish.jersey.server.ResourceConfig" class in my application.
(not nice, but it works)
```

**Comment by carek** [comment]
It's an ugly hack but there is also another workaround.

<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>truezip-maven-plugin</artifactId>
				<version>1.2</version>
				<executions>
					<execution>
						<id>remove-JerseyAutoConfiguration</id>
						<goals>
							<goal>remove</goal>
						</goals>
						<phase>package</phase>
						<configuration>
							<fileset>
								<directory>${archive.path}/WEB-INF/lib/spring-boot-autoconfigure-1.2.6.RELEASE.jar/org/springframework/boot/autoconfigure/jersey/</directory>
								<includes>
									<include>JerseyAutoConfiguration.class</include>
								</includes>
							</fileset>
						</configuration>
					</execution>
				</executions>
			</plugin>

**Comment by wilkinsona** [comment]
Fixed in https://github.com/spring-projects/spring-boot/commit/40427cdb8275f0b556d6fb6e99983ebb4daf4d4e

**Comment by snicoll** [comment]
duplicates #4527
