### ISSUE TITLE
java.lang.ClassCastException in BeanFactory when getting Bean multithreaded

### ISSUE THREAD

**Issue by mathekcbo** [spring-projects/spring-boot#36108]
When calling prototype Beans the first time in a multithreaded manner, the following exception can happen:

`
Exception in thread "Thread-2" java.lang.ClassCastException: class java.lang.Class cannot be cast to class java.lang.String (java.lang.Class and java.lang.String are in module java.base of loader 'bootstrap')
        at org.springframework.beans.factory.support.AbstractBeanDefinition.getBeanClassName(AbstractBeanDefinition.java:393)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doResolveBeanClass(AbstractBeanFactory.java:1535)
        at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1502)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:492)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:344)
       ...
`

If this happens, the context/runtime will never raise this exception again. So it seems to be an issue only on startup.
This seems to happen since Spring Boot 3. There is nothing to find on google. We assume this error to be unknown so far.

To simplify things and for reproduction, we created a repository that can demonstrate the behaviour:
[Git Demo Repo for this issue](https://github.com/mathekcbo/sb3cce)

Please elaborate.
Thanks in advance

**Comment by wilkinsona** [comment]
`AbstractBeanDefinition` is part of Spring Framework. We'll transfer this issue so that they can investigate.
