### ISSUE TITLE
Fail to send email to gmail upgrading from 1.2.3 to 1.2.4

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#3624]
See [this stackoverflow thread](http://stackoverflow.com/questions/31721298/spring-boot-1-2-5-release-sending-e-mail-via-gmail-smtp?noredirect=1#comment51382982_31721298) and [this sample app](https://github.com/levgaas/SpringBoot-emailer).

After changing the credentials to a valid gmail address, the sample works fine with `1.2.0.RELEASE`. Upgrading to `1.2.5.RELEASE` and the sending process hangs for some reasons.

The actual problem happened between `1.2.3.RELEASE` and `1.2.4.RELEASE`

**Comment by snicoll** [comment]
Actually downgrading to `com.sun.mail:javax.mail:1.5.2` (instead of `1.5.3` fixed the issue for me). 

@wilkinsona thoughts?

**Comment by snicoll** [comment]
thread dump when the app is using `1.5.3`

```
"main" #1 prio=5 os_prio=31 tid=0x00007fa9aa802000 nid=0x1303 runnable [0x0000000106543000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(SocketInputStream.java:150)
	at java.net.SocketInputStream.read(SocketInputStream.java:121)
	at com.sun.mail.util.TraceInputStream.read(TraceInputStream.java:124)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	- locked <0x000000076b829a80> (a java.io.BufferedInputStream)
	at com.sun.mail.util.LineInputStream.readLine(LineInputStream.java:89)
	at com.sun.mail.smtp.SMTPTransport.readServerResponse(SMTPTransport.java:2285)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2032)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:697)
	- locked <0x000000076b3a6c80> (a com.sun.mail.smtp.SMTPTransport)
	at javax.mail.Service.connect(Service.java:364)
	- locked <0x000000076b3a6c80> (a com.sun.mail.smtp.SMTPTransport)
	at org.springframework.mail.javamail.JavaMailSenderImpl.connectTransport(JavaMailSenderImpl.java:486)
	at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:406)
	at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:345)
	at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:340)
	at com.naturalprogrammer.spring.email.SmtpMailSender.send(SmtpMailSender.java:30)
	at com.naturalprogrammer.spring.email.NaturalprogrammerSpringEmailApplication$AimerCommandLineRunner.run(NaturalprogrammerSpringEmailApplication.java:37)
	at org.springframework.boot.SpringApplication.runCommandLineRunners(SpringApplication.java:672)
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:690)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:321)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
	at com.naturalprogrammer.spring.email.NaturalprogrammerSpringEmailApplication.main(NaturalprogrammerSpringEmailApplication.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by wilkinsona** [comment]
It looks like there's a regression/behaviour change in Java Mail. [The change](https://java.net/projects/javamail/sources/mercurial/revision/704) is in both 1.5.3 and 1.5.4. Your app works with Boot 1.2.0 as it uses Java Mail 1.5.2. It fails with Boot 1.2.5 as it uses Java Mail 1.5.4.

The problem in 1.5.3+ appears to be that the SMTP transport connects on port 465 and GMail expects an SSL handshake. Java Mail incorrectly thinks it's not using SSL so it never initiates the handshake and the connection attempt (eventually) times out. You can convince Java Mail to do the right thing by being explicit about the use of SSL. Add the following to application.properties:

```properties
spring.mail.properties.mail.smtp.ssl.enable = true
```
