### ISSUE TITLE
-Dloader.path not working as expected with mapr

### ISSUE THREAD

**Issue by tenstriker** [spring-projects/spring-boot#3685]
```
$ java -Dloader.path=/opt/mapr/spark/spark-1.3.1/lib/spark-assembly-1.3.1-hadoop2.5.1-mapr-1501.jar,/opt/mapr/hadoop/hadoop-2.5.1/etc/hadoop -XX:PermSize=512m -XX:MaxPermSize=512m -Xms1024m -Dspring.profiles.active=noxbase -jar myspringbootapp.jar
java.lang.IllegalStateException: Unable to open nested entry 'minlog-1.2.jar'.
It has been compressed and nested jar files must be stored without compression. Please check the mechanism used to create your executable jar file
    at org.springframework.boot.loader.jar.JarFile.createJarFileFromFileEntry(JarFile.java:379)
    at org.springframework.boot.loader.jar.JarFile.createJarFileFromEntry(JarFile.java:355)
    at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:341)
    at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchive(JarFileArchive.java:108)
    at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchives(JarFileArchive.java:92)
    at org.springframework.boot.loader.PropertiesLauncher.getClassPathArchives(PropertiesLauncher.java:445)
    at org.springframework.boot.loader.Launcher.launch(Launcher.java:60)
    at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:608)
```

Similar to,
http://stackoverflow.com/questions/28074393/spring-boot-createjarfilefromfileentry

It works if I use,
/opt/mapr/spark/spark-1.3.1/lib instead of /opt/mapr/spark/spark-1.3.1/lib/spark-assembly-1.3.1-hadoop2.5.1-mapr-1501.jar

EDIT :
I can not use entire folder on loader.path as I need to exclude some of the libraries from the folder using some mechanism. Any suggestion for doing that is also welcome. I am just thinking of using revers find like find /opt/mapr ! -regex slf4j-log4j12-.\*

**Comment by dsyer** [comment]
I guess `spark-assembly-1.3.1-hadoop2.5.1-mapr-1501.jar` has been created for you by the "mapr" tool? Do you control the way that is done? if you do then change it to not compress the jars (see the error message in the stack trace).  If not then there is nothing you can do.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by tenstriker** [comment]
You can close this ticket. I am able to extract nested jars and provide it to loader.path for now
