### ISSUE TITLE
Docker Compose start fails with "unknown flag: --no-color"

### ISSUE THREAD

**Issue by wjzxc123** [spring-projects/spring-boot#36908]
> my dokcer compose version
![image](https://github.com/spring-projects/spring-boot/assets/32690579/0d22ba96-b34b-4284-b842-12ed16955150)

> Run Application Exception
```log
2023-08-10T14:58:30.033+08:00 ERROR 1308 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.boot.docker.compose.core.ProcessExitException: 'docker compose --file E:\project\java_project\github_project\yy-cloud\yy-auth\docker-compose.yaml --ansi never start --no-color --detach --wait' failed with exit code 16.

Stdout:


Stderr:
unknown flag: --no-color

	at org.springframework.boot.docker.compose.core.ProcessRunner.run(ProcessRunner.java:96) ~[spring-boot-docker-compose-3.1.0.jar:3.1.0]
	at org.springframework.boot.docker.compose.core.DockerCli.run(DockerCli.java:80) ~[spring-boot-docker-compose-3.1.0.jar:3.1.0]
	at org.springframework.boot.docker.compose.core.DefaultDockerCompose.start(DefaultDockerCompose.java:59) ~[spring-boot-docker-compose-3.1.0.jar:3.1.0]
	at org.springframework.boot.docker.compose.lifecycle.StartCommand.applyTo(StartCommand.java:51) ~[spring-boot-docker-compose-3.1.0.jar:3.1.0]
	at org.springframework.boot.docker.compose.lifecycle.DockerComposeLifecycleManager.start(DockerComposeLifecycleManager.java:117) ~[spring-boot-docker-compose-3.1.0.jar:3.1.0]
	at org.springframework.boot.docker.compose.lifecycle.DockerComposeListener.onApplicationEvent(DockerComposeListener.java:53) ~[spring-boot-docker-compose-3.1.0.jar:3.1.0]
	at org.springframework.boot.docker.compose.lifecycle.DockerComposeListener.onApplicationEvent(DockerComposeListener.java:35) ~[spring-boot-docker-compose-3.1.0.jar:3.1.0]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-6.0.9.jar:6.0.9]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-6.0.9.jar:6.0.9]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-6.0.9.jar:6.0.9]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131) ~[spring-context-6.0.9.jar:6.0.9]
	at org.springframework.boot.context.event.EventPublishingRunListener.multicastInitialEvent(EventPublishingRunListener.java:136) ~[spring-boot-3.1.0.jar:3.1.0]
	at org.springframework.boot.context.event.EventPublishingRunListener.contextLoaded(EventPublishingRunListener.java:98) ~[spring-boot-3.1.0.jar:3.1.0]
	at org.springframework.boot.SpringApplicationRunListeners.lambda$contextLoaded$4(SpringApplicationRunListeners.java:72) ~[spring-boot-3.1.0.jar:3.1.0]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118) ~[spring-boot-3.1.0.jar:3.1.0]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112) ~[spring-boot-3.1.0.jar:3.1.0]
	at org.springframework.boot.SpringApplicationRunListeners.contextLoaded(SpringApplicationRunListeners.java:72) ~[spring-boot-3.1.0.jar:3.1.0]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:415) ~[spring-boot-3.1.0.jar:3.1.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:310) ~[spring-boot-3.1.0.jar:3.1.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1305) ~[spring-boot-3.1.0.jar:3.1.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1294) ~[spring-boot-3.1.0.jar:3.1.0]
	at com.licon.YyAuthApplication.main(YyAuthApplication.java:9) ~[classes/:na]

2023-08-10T14:58:30.036+08:00  WARN 1308 --- [       Thread-0] c.a.n.common.http.HttpClientBeanHolder   : [HttpClientBeanHolder] Start destroying common HttpClient
2023-08-10T14:58:30.037+08:00  WARN 1308 --- [       Thread-5] c.a.nacos.common.notify.NotifyCenter     : [NotifyCenter] Start destroying Publisher
2023-08-10T14:58:30.037+08:00  WARN 1308 --- [       Thread-5] c.a.nacos.common.notify.NotifyCenter     : [NotifyCenter] Destruction of the end
2023-08-10T14:58:30.037+08:00  WARN 1308 --- [       Thread-0] c.a.n.common.http.HttpClientBeanHolder   : [HttpClientBeanHolder] Destruction of the end
Disconnected from the target VM, address: '127.0.0.1:58157', transport: 'socket'

Process finished with exit code 1
```

**Comment by wjzxc123** [comment]
#35921

**Comment by wilkinsona** [comment]
It looks like `up` supports `--no-color` but `start` does not.

**Comment by mhalbritter** [comment]
There are more problems with the start command. It uses `--detach --wait`, which are not supported in my docker compose:

```
> docker compose version
Docker Compose version 2.20.2
```

I'll fix that and see if we can add an integration test for this.
