### ISSUE TITLE
Spring boot devtools and orika mapper issue

### ISSUE THREAD

**Issue by pavel-v-chernykh** [spring-projects/spring-boot#3697]
Hello guys, I've faced with issue using ```spring-boot-devtools``` and orika mapper in the same project. It looks like class loader issue, but so far I have no enough expertise in this area for deep investigation. I've created small [demo](https://github.com/pavel-v-chernykh/spring-boot-devtools-with-orika-mapper-issue-demo) project where I reproduced this error. More details you can find in the README file of the [project](https://github.com/pavel-v-chernykh/spring-boot-devtools-with-orika-mapper-issue-demo)

**Comment by snicoll** [comment]
We had a similar issue with other components that are using the classloader to resolve resources. On first sight, this looks like the same problem. Thanks for the report.

**Comment by wilkinsona** [comment]
@pavel-v-chernykh Thanks for taking the time to share a sample that reproduces the problem.

This one's quite interesting as it's unlike other DevTools problems that I've seen. The failure occurs immediately, i.e. you don't have to make any changes to the application to trigger a restart before things break. The failure is:

```
sourceClass = class demo.domain.Demo
destinationType = demo.dto.DemoDto
resolvedStrategy = InstantiateAndUseCustomMapperStrategy<Demo, DemoDto> {customMapper: GeneratedMapper<Demo, DemoDto> {usedConverters: [BidirectionalConverter(DurationConverter)<Duration, Duration>], usedMappers: [], usedMapperFacades: [], usedTypes: [Duration] }, unenhancer: ma.glasnost.orika.unenhance.BaseUnenhancer@1a9c4db7, objectFactory: ma.glasnost.orika.generated.DemoDto_Demo_ObjectFactory144705354855797144719459973291$1@2f70ed8}
Error occurred: java.lang.IllegalArgumentException: demo.domain.Demo is an unsupported source class for constructing instances of demo.dto.DemoDto
-----begin dump of current state-----------------------------
Registered object factories: 1 (approximate size: 9,188.2 kB)
  [DemoDto] : {Demo=ma.glasnost.orika.generated.DemoDto_Demo_ObjectFactory144705354855797144719459973291$1@2f70ed8}
-------------------------------------------------------------
Registered mappers: 1 (approximate size: 10,380.0 kB)
  [0] : GeneratedMapper<Demo, DemoDto> {usedConverters: [BidirectionalConverter(DurationConverter)<Duration, Duration>], usedMappers: [], usedMapperFacades: [], usedTypes: [Duration] }
-------------------------------------------------------------
Registered concrete types: 5 (approximate size: 239.4 kB)
  [interface java.util.Map$Entry] : MapEntry<Object, Object>
  [interface java.util.List] : ArrayList<Object>
  [interface java.util.Set] : LinkedHashSet<Object>
  [interface java.util.Map] : LinkedHashMap<Object, Object>
  [interface java.util.Collection] : ArrayList<Object>
-------------------------------------------------------------
Resolved strategies: 1 (approximate size: 10,380.1 kB)
{source: Demo, dest: DemoDto, in-place:false}: InstantiateAndUseCustomMapperStrategy<Demo, DemoDto> {customMapper: GeneratedMapper<Demo, DemoDto> {usedConverters: [BidirectionalConverter(DurationConverter)<Duration, Duration>], usedMappers: [], usedMapperFacades: [], usedTypes: [Duration] }, unenhancer: ma.glasnost.orika.unenhance.BaseUnenhancer@1a9c4db7, objectFactory: ma.glasnost.orika.generated.DemoDto_Demo_ObjectFactory144705354855797144719459973291$1@2f70ed8}
-------------------------------------------------------------
Unenhance strategy: ma.glasnost.orika.unenhance.BaseUnenhancer@1a9c4db7
-----end dump of current state-------------------------------] with root cause
java.lang.IllegalArgumentException: demo.domain.Demo is an unsupported source class for constructing instances of demo.dto.DemoDto
	at ma.glasnost.orika.generated.DemoDto_Demo_ObjectFactory144705354855797144719459973291$1.create(DemoDto_Demo_ObjectFactory144705354855797144719459973291$1.java) ~[orika-core-1.4.6.jar:na]
	at ma.glasnost.orika.impl.mapping.strategy.InstantiateAndUseCustomMapperStrategy.getInstance(InstantiateAndUseCustomMapperStrategy.java:55) ~[orika-core-1.4.6.jar:na]
	at ma.glasnost.orika.impl.mapping.strategy.UseCustomMapperStrategy.map(UseCustomMapperStrategy.java:61) ~[orika-core-1.4.6.jar:na]
	at ma.glasnost.orika.impl.MapperFacadeImpl.map(MapperFacadeImpl.java:742) ~[orika-core-1.4.6.jar:na]
	at ma.glasnost.orika.impl.MapperFacadeImpl.map(MapperFacadeImpl.java:721) ~[orika-core-1.4.6.jar:na]
	at ma.glasnost.orika.impl.ConfigurableMapper.map(ConfigurableMapper.java:150) ~[orika-core-1.4.6.jar:na]
	at demo.web.DemoController.index(DemoController.java:22) ~[bin/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_60]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) ~[spring-web-4.2.2.BUILD-SNAPSHOT.jar:4.2.2.BUILD-SNAPSHOT]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137) ~[spring-web-4.2.2.BUILD-SNAPSHOT.jar:4.2.2.BUILD-SNAPSHOT]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110) ~[spring-webmvc-4.2.2.BUILD-SNAPSHOT.jar:4.2.2.BUILD-SNAPSHOT]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:806) ~[spring-webmvc-4.2.2.BUILD-SNAPSHOT.jar:4.2.2.BUILD-SNAPSHOT]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:729) ~[spring-webmvc-4.2.2.BUILD-SNAPSHOT.jar:4.2.2.BUILD-SNAPSHOT]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.2.2.BUILD-SNAPSHOT.jar:4.2.2.BUILD-SNAPSHOT]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959) ~[spring-webmvc-4.2.2.BUILD-SNAPSHOT.jar:4.2.2.BUILD-SNAPSHOT]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893) ~[spring-webmvc-4.2.2.BUILD-SNAPSHOT.jar:4.2.2.BUILD-SNAPSHOT]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.2.2.BUILD-SNAPSHOT.jar:4.2.2.BUILD-SNAPSHOT]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) ~[spring-webmvc-4.2.2.BUILD-SNAPSHOT.jar:4.2.2.BUILD-SNAPSHOT]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) ~[spring-webmvc-4.2.2.BUILD-SNAPSHOT.jar:4.2.2.BUILD-SNAPSHOT]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.0.28.jar:8.0.28]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:87) ~[spring-web-4.2.2.BUILD-SNAPSHOT.jar:4.2.2.BUILD-SNAPSHOT]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.2.2.BUILD-SNAPSHOT.jar:4.2.2.BUILD-SNAPSHOT]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77) ~[spring-web-4.2.2.BUILD-SNAPSHOT.jar:4.2.2.BUILD-SNAPSHOT]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.2.2.BUILD-SNAPSHOT.jar:4.2.2.BUILD-SNAPSHOT]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85) ~[spring-web-4.2.2.BUILD-SNAPSHOT.jar:4.2.2.BUILD-SNAPSHOT]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.2.2.BUILD-SNAPSHOT.jar:4.2.2.BUILD-SNAPSHOT]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518) [tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091) [tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673) [tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500) [tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456) [tomcat-embed-core-8.0.28.jar:8.0.28]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.0.28.jar:8.0.28]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
```

**Comment by wilkinsona** [comment]
The problem's due to Orika's auto-generated classes. By default it uses `JavassistCompilerStrategy` to produce compiled classes. These generated classes are tied to the app classloader. When a mapping attempt is made the two types involved in the mapping, `Demo` and `DemoDto` have been loaded by the restart classloader so the `Demo` that's being mapped doesn't match the `Demo` type that Orika's capable of mapping as it belongs to a different class loader.

In diagnosing the problem, I discovered an interesting workaround. Switching to an Eclipse JDT-based compiler strategy fixes the problem. Add the following to the `ConfigurableMapper` subclass

```
@Override
protected void configureFactoryBuilder(Builder factoryBuilder) {
    factoryBuilder.compilerStrategy(new EclipseJdtCompilerStrategy());
}
```

And add a dependency on `ma.glasnost.orika:orika-eclipse-tools:1.4.6`

The `EclipseJdtCompilerStrategy` generates source code to the root of the classpath that is then compiled. This changes the class loading model such that it's the restart classloader that loads the auto-generated classes.

**Comment by wilkinsona** [comment]
The problem can be avoid by hacking `ChangeableUrls` to consider Orika jars to be reloadable:

```
	private boolean isReloadable(URL url) {
		String urlString = url.toString();
		return (isFolderUrl(urlString) || urlString.contains("orika"))
				&& !isSkipped(urlString);
	}
```
 This causes the jars to be loaded via the `RestartClassLoader` and, therefore, causes the call to `this.getClass().getClassLoader` mentioned in the comment above to return the `RestartClassLoader` which is then used to load the auto-generated mapping classes.

I wonder if we should provide a configuration option that lets you specify one or more patterns which, when matched, will make a dependency reloadable.

**Comment by wilkinsona** [comment]
It looks like there may be some plans to address this in Orika 1.5: https://github.com/orika-mapper/orika/issues/86

**Comment by pavel-v-chernykh** [comment]
Wow, @wilkinsona, thanks for comprehensive investigation and explanation. True detective :+1:

**Comment by philwebb** [comment]
As part of #3316 I've added support for `META-INF/spring-devtools.properties` files which can be used to tweak which classloader is used for a given jar. You might be able to use this technique to pull orika up to the restart classloader.

**Comment by philwebb** [comment]
I don't think there's much more we can do on our end. Hopefullt Orika will fix the reported issue.

**Comment by timroes** [comment]
With the new configuration possibilities, you can now easily fix this, by adding the following line to the `META-INF/spring-devtools.properties` file in your project:

```
restart.include.orika=/orika-core.*\.jar
```

Thanks @philwebb for implementing it. And you already mentioned that there might be the possibility now, just wanted to add the concrete solution to this issue in case someone else is stumbling across it when searching for this problem.

**Comment by philwebb** [comment]
Thanks for the reminder @timroes

**Comment by wired00** [comment]
Thanks, I was using jhipster and this fixed things for me, hopefully fixed in orika soon

**Comment by AlexSylka** [comment]
We have similar issue but we don't use spring-devtools https://stackoverflow.com/q/52321672/4507790
