### ISSUE TITLE
I encountered a problem when using spring-boot 2.7.13

### ISSUE THREAD

**Issue by status2xx** [spring-projects/spring-boot#37185]
Code location：io.undertow.servlet.util.DispatchUtils#dispatchInclude

spring-boot 2.7.12   ->  Undertow - 2.2.24.Final （Program runs properly）

![](https://secure2.wostatic.cn/static/xq4wvC7MHXGViU9drukgNm/image.png?auth_key=1693812975-efCjHj4i8C71fEjssMHaCn-0-3fb960a63f33d7f32672ae0574189a4d)

Because the  spring-boot 2.7.13   ->  Undertow-2.2.25.Final has such an extra line, the force transfer fails

![](https://secure2.wostatic.cn/static/qLkFxNLbuFuXEPxNMPjJtD/image.png?auth_key=1693814289-3v4E63K3Mes8FuwY4iTQgE-0-5bff0a2e3239c2fea8b1c63d2126a964)

Code location：`org.springframework.web.util.UrlPathHelper.Servlet4Delegate#skipServletPathDetermination:779`

![](https://secure2.wostatic.cn/static/64s1uEbp3J8BCWXxMCb4gv/image.png?auth_key=1693814560-pNseyz4BqCz2QfmWYfEyoP-0-5d38a3592bee681123316d1012a69d08)

An example error message with shortened stack trace:

`Caused by: java.lang.ClassCastException: class javax.servlet.http.MappingMatch cannot be cast to class javax.servlet.http.HttpServletMapping (javax.servlet.http.MappingMatch and javax.servlet.http.HttpServletMapping are in unnamed module of loader 'app')
  at org.springframework.web.util.UrlPathHelper$Servlet4Delegate.skipServletPathDetermination(UrlPathHelper.java:779) ~[spring-web-5.3.28.jar:5.3.28]
  at org.springframework.web.util.UrlPathHelper.skipServletPathDetermination(UrlPathHelper.java:271) ~[spring-web-5.3.28.jar:5.3.28]
  at org.springframework.web.util.UrlPathHelper.getLookupPathForRequest(UrlPathHelper.java:250) ~[spring-web-5.3.28.jar:5.3.28]
  at org.springframework.web.util.UrlPathHelper.resolveAndCacheLookupPath(UrlPathHelper.java:199) ~[spring-web-5.3.28.jar:5.3.28]
  at org.springframework.web.servlet.handler.AbstractHandlerMapping.initLookupPath(AbstractHandlerMapping.java:579) ~[spring-webmvc-5.3.28.jar:5.3.28]
  at org.springframework.web.servlet.handler.AbstractUrlHandlerMapping.getHandlerInternal(AbstractUrlHandlerMapping.java:144) ~[spring-webmvc-5.3.28.jar:5.3.28]
  at org.springframework.web.socket.server.support.WebSocketHandlerMapping.getHandlerInternal(WebSocketHandlerMapping.java:104) ~[spring-websocket-5.3.28.jar:5.3.28]
  at org.springframework.web.servlet.handler.AbstractHandlerMapping.getHandler(AbstractHandlerMapping.java:498) ~[spring-webmvc-5.3.28.jar:5.3.28]
  at org.springframework.web.servlet.DispatcherServlet.getHandler(DispatcherServlet.java:1266) ~[spring-webmvc-5.3.28.jar:5.3.28]
  at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1048) ~[spring-webmvc-5.3.28.jar:5.3.28]
  at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965) ~[spring-webmvc-5.3.28.jar:5.3.28]
  at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.28.jar:5.3.28]
  ... 88 common frames omitted`

**Comment by bclozel** [comment]
I think this is an issue in Undertow, [this has been raised on their issue tracker](https://issues.redhat.com/browse/UNDERTOW-2296).

**Comment by status2xx** [comment]
Okay, thank you.
