### ISSUE TITLE
spring-boot-maven-plugin repackage compress

### ISSUE THREAD

**Issue by zhanhb** [spring-projects/spring-boot#3730]
The war or the jar is about 10M larger than the original one. For it seems that it is not compressed. Can it be added?

**Comment by snicoll** [comment]
The "original" one does not contain the embedded container so I guess the difference comes from that. Can you check?

**Comment by zhanhb** [comment]
lib-provided is only 5.98M and org\springframework\boot\loader is only 160K. I decompress the repackaged war and I package it by myself, it gets much smaller. lib-provided only contains spring-boot-starter-tomcat and tomcat-embed-jasper and sub depedencies.
Here is the list of lib-provided
```
ecj-4.4.2.jar
spring-boot-starter-tomcat-1.3.0.BUILD-SNAPSHOT.jar
tomcat-embed-core-8.0.24.jar
tomcat-embed-el-8.0.24.jar
tomcat-embed-jasper-8.0.24.jar
tomcat-embed-logging-juli-8.0.24.jar
tomcat-embed-websocket-8.0.24.jar
```

**Comment by wilkinsona** [comment]
> I decompress the repackaged war and I package it by myself, it gets much smaller

If you try to run the smaller war with `java -jar`, you'll find that it doesn't work. It'll fail with:

```
java.lang.IllegalStateException: Unable to open nested entry '…'. It has been compressed and nested jar files must be stored without compression. Please check the mechanism used to create your executable jar file
	at org.springframework.boot.loader.jar.JarFile.createJarFileFromFileEntry(JarFile.java:378)
	at org.springframework.boot.loader.jar.JarFile.createJarFileFromEntry(JarFile.java:355)
	at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:341)
	at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchive(JarFileArchive.java:108)
	at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchives(JarFileArchive.java:92)
	at org.springframework.boot.loader.ExecutableArchiveLauncher.getClassPathArchives(ExecutableArchiveLauncher.java:74)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:60)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:45)
```

In short, all of the entries in the repackaged jar or war are compressed other than those in `lib` and `lib-provided` which most be stored uncompressed for the nested jar support to work. Note that the _contents_ of the nested jars are still compressed.
