### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ahsaneajz** [spring-projects/spring-boot#37585]
[16:43:20 WARN]: java.lang.IllegalStateException: zip file closed
[16:43:20 WARN]:        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:840)
[16:43:20 WARN]:        at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:339)
[16:43:20 WARN]:        at java.base/java.util.jar.JarFile.getEntry(JarFile.java:517)
[16:43:20 WARN]:        at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:472)
[16:43:20 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:195)
[16:43:20 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
[16:43:20 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155)
[16:43:20 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:130)
[16:43:20 WARN]:        at io.papermc.paper.plugin.entrypoint.classloader.group.SpigotPluginClassLoaderGroup.lookupClass(SpigotPluginClassLoaderGroup.java:43)
[16:43:20 WARN]:        at io.papermc.paper.plugin.entrypoint.classloader.group.SimpleListPluginClassLoaderGroup.getClassByName(SimpleListPluginClassLoaderGroup.java:37)
[16:43:20 WARN]:        at io.papermc.paper.plugin.entrypoint.classloader.group.LockingClassLoaderGroup.getClassByName(LockingClassLoaderGroup.java:34)
[16:43:20 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:173)
[16:43:20 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150)
[16:43:20 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:579)
[16:43:20 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[16:43:20 WARN]:        at me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:58)
[16:43:20 WARN]:        at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:56)
[16:43:20 WARN]:        at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:48)
[16:43:20 WARN]:        at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:265)
[16:43:20 WARN]:        at me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:169)
[16:43:20 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[16:43:20 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:43:20 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:43:20 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by wilkinsona** [comment]
A stack trace alone isn't enough for us to diagnose a problem, particularly when it shows no signs that Spring Boot is involved. If you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.
