### ISSUE TITLE
H2 database - The write format 2 is smaller than the supported format 3 [2.2.224/5]

### ISSUE THREAD

**Issue by sergmain** [spring-projects/spring-boot#37621]
Spring Boot 3.2 upgraded its dependency on H2 to v2.2.224
Since version 2.2.220 H2 has a new format of db files which is incompatible with v2.1.214 

```
Caused by: org.h2.mvstore.MVStoreException: The write format 2 is smaller than the supported format 3 [2.2.224/5]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996) ~[h2-2.2.224.jar:2.2.224]
	at org.h2.mvstore.FileStore.getUnsupportedWriteFormatException(FileStore.java:943) ~[h2-2.2.224.jar:2.2.224]
	at org.h2.mvstore.FileStore.processCommonHeaderAttributes(FileStore.java:547) ~[h2-2.2.224.jar:2.2.224]
	at org.h2.mvstore.RandomAccessStore.readStoreHeader(RandomAccessStore.java:227) ~[h2-2.2.224.jar:2.2.224]
	at org.h2.mvstore.FileStore.start(FileStore.java:916) ~[h2-2.2.224.jar:2.2.224]
	at org.h2.mvstore.MVStore.<init>(MVStore.java:289) ~[h2-2.2.224.jar:2.2.224]
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035) ~[h2-2.2.224.jar:2.2.224]
	at org.h2.mvstore.db.Store.<init>(Store.java:133) ~[h2-2.2.224.jar:2.2.224]
	... 35 common frames omitted
```

This upgrade of db must be done manually.

Maybe I'm wrong but because of such incompatibility SB 3.x should stay with 2.1.214 and postpone upgrading to v2.2.220+ to SB 4.x

Related issue in H2:
https://github.com/h2database/h2database/issues/3903

**Comment by philwebb** [comment]
I don't think it's sensible for us to remain on H2 2.1.x indefinitely, I think it's better that we upgrade and persuade users to migrate their database files. If you don't want to do that, you can set the `h2.version` property in your build to downgrade.

**Comment by wilkinsona** [comment]
I've added [an entry](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2.0-M3-Release-Notes#h2-22) to the release notes.

**Comment by hehuipu** [comment]
I had confirmed when I set the h2.version  by the lastest 2.2.224,
it is still H2 2.2.214 for Spring Boot 3.1.5,
but for Spring Boot 3.2.0 it will change to H2 2.2.224.

it seemed there was any restrict for H2 version  in Spring Boot 3.1.5, but I can't find any dependency relation.
