### ISSUE TITLE
SERVER_HOME environment variable prevents Spring Boot from starting with M4

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#3775]
This is kind of related to #3427 but in a different way.

For some reason, `SERVER_HOME` was not processed by Spring Boot up to `1.3.0.M3`. Since M4, it is now processed and this leads to the following:

```
org.springframework.beans.NotWritablePropertyException: Invalid property 'HOME' of bean class [org.springframework.boot.autoconfigure.web.ServerProperties]: Bean property 'HOME' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
```

The weird thing here is that it is "expected" as anything that is not known by `ServerProperties` should blow up. But for some reason having a `SERVER_HOME` OS env works just fine *except* with `1.3.0.M4`

Maybe we have users out there that have such property and didn't notice so far. This makes #3427 even more relevant.

Steps to reproduce: create a app from start.spring.io with the `web` starter, **export** a `SERVER_HOME` OS env and run.

**Comment by wilkinsona** [comment]
I'm not sure that this is a regression. I'd argue that we've actually fixed a long-standing bug where `ignoreUnknownProperties = false` wasn't being honoured. A new minor version feels like a reasonable place to fix such a bug, i.e. I don't think we should change 1.2.x.

**Comment by sbrannen** [comment]
@wilkinsona, if you don't consider this a regression, the way that boot blows up should be at least somewhere in the vicinity of _user friendly_.

@snicoll actually raised this issue for me.

I've had a `SERVER_HOME` environment variable on my system for quite some time (think _Virgo_ :wink:).

As it stands now, I have an app that worked against boot 1.2.x and all 1.3.0 milestones thus far. Then I upgraded to 1.3.0 M4, and boom: 

    java.lang.IllegalStateException
        Caused by: org.springframework.context.ApplicationContextException
            Caused by: org.springframework.beans.factory.BeanCreationException
                Caused by: org.springframework.beans.factory.BeanCreationException
                    Caused by: org.springframework.beans.factory.BeanCreationException
                        Caused by: org.springframework.beans.factory.BeanCreationException
                            Caused by: org.springframework.beans.NotWritablePropertyException

**Comment by sbrannen** [comment]
After digging deeper, I come a cross a 121 stack trace, which in the end only tells me:

	Caused by: org.springframework.beans.NotWritablePropertyException: Invalid property 'HOME' of bean class [org.springframework.boot.autoconfigure.web.ServerProperties]: Bean property 'HOME' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
		at org.springframework.beans.BeanWrapperImpl.createNotWritablePropertyException(BeanWrapperImpl.java:229)
		at org.springframework.beans.AbstractNestablePropertyAccessor.setPropertyValue(AbstractNestablePropertyAccessor.java:423)
		at org.springframework.beans.AbstractNestablePropertyAccessor.setPropertyValue(AbstractNestablePropertyAccessor.java:280)
		at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:95)
		at org.springframework.validation.DataBinder.applyPropertyValues(DataBinder.java:810)
		at org.springframework.validation.DataBinder.doBind(DataBinder.java:706)
		at org.springframework.boot.bind.RelaxedDataBinder.doBind(RelaxedDataBinder.java:123)
		at org.springframework.validation.DataBinder.bind(DataBinder.java:691)
		at org.springframework.boot.bind.PropertiesConfigurationFactory.doBindPropertiesToTarget(PropertiesConfigurationFactory.java:259)
		at org.springframework.boot.bind.PropertiesConfigurationFactory.bindPropertiesToTarget(PropertiesConfigurationFactory.java:233)
		at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:298)
		... 91 more

There is **zero** mention of the `SERVER_HOME` environment variable that caused the problem.

So how should an unsuspecting/uninformed user come up with the idea that his `SERVER_HOME` environment variable -- which has been on his system literally for years and never adversely affected any application -- now all of a sudden is the reason that Spring Boot 1.3.0 M4 doesn't work, even for bare bones web apps created by the Spring Starter app?

**Comment by wilkinsona** [comment]
Thanks for the feedback, @sbrannen. Note that I was only making the case for this not being classed as a regression. I was not making a case for doing nothing to address the issue.

I think the point that you've made about the diagnostics for a binding failure is a good one. The problem's actually broader than this issue. For example, A `SERVER_PORT` environment variable with a strange or mistyped value with also cause a hard-to-diagnose failure. I've opened #3778.

**Comment by sbrannen** [comment]
@wilkinsona, thanks for opening #3778!

Improving the diagnostics is the very least that should be done in this regard.

**Comment by madorb** [comment]
I am seeing this same sort of issue in M4 with liquibase. Opened #3797 - looks to be due to having LIQUIBASE_HOME set. Some sort of more user friendly error / mentions in documentation would be much appreciated

**Comment by snicoll** [comment]
@madorb check also #3778

**Comment by sbrannen** [comment]
Thanks, @wilkinsona!!!
