### ISSUE TITLE
Binding does not auto-grow arrays in Maps (i.e. Map<String, String[]>

### ISSUE THREAD

**Issue by gokhanoner** [spring-projects/spring-boot#3789]
using spring-boot 1.2.5

I have property like this:

```
private Map<String, List<String>> headers;
```

This is working fine, but when I change the type to

```
private Map<String, List<Object>> headers;
```

i'm getting below error. Is this normal ??

```
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'columnProps': Could not bind properties to [unknown] (target=, ignoreInvalidFields=false, ignoreUnknownFields=true, ignoreNestedProperties=false); nested exception is java.lang.IndexOutOfBoundsException: Index: 5, Size: 5
    at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:303)
    at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:250)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1566)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
    at com.globalbilisim.fxmatch.VaadinFxMatch.main(VaadinFxMatch.java:20)
Caused by: java.lang.IndexOutOfBoundsException: Index: 5, Size: 5
    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.get(ArrayList.java:429)
    at org.springframework.boot.bind.RelaxedDataBinder$BeanPath.isArrayIndex(RelaxedDataBinder.java:533)
    at org.springframework.boot.bind.RelaxedDataBinder.extendCollectionIfNecessary(RelaxedDataBinder.java:311)
    at org.springframework.boot.bind.RelaxedDataBinder.initializePath(RelaxedDataBinder.java:262)
    at org.springframework.boot.bind.RelaxedDataBinder.initializePath(RelaxedDataBinder.java:279)
    at org.springframework.boot.bind.RelaxedDataBinder.initializePath(RelaxedDataBinder.java:279)
    at org.springframework.boot.bind.RelaxedDataBinder.initializePath(RelaxedDataBinder.java:279)
    at org.springframework.boot.bind.RelaxedDataBinder.normalizePath(RelaxedDataBinder.java:237)
    at org.springframework.boot.bind.RelaxedDataBinder.modifyProperty(RelaxedDataBinder.java:218)
    at org.springframework.boot.bind.RelaxedDataBinder.modifyProperties(RelaxedDataBinder.java:148)
    at org.springframework.boot.bind.RelaxedDataBinder.doBind(RelaxedDataBinder.java:123)
    at org.springframework.validation.DataBinder.bind(DataBinder.java:631)
    at org.springframework.boot.bind.PropertiesConfigurationFactory.doBindPropertiesToTarget(PropertiesConfigurationFactory.java:253)
    at org.springframework.boot.bind.PropertiesConfigurationFactory.bindPropertiesToTarget(PropertiesConfigurationFactory.java:227)
    at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:296)
    ... 18 more
```

**Comment by snicoll** [comment]
Hard to tell without your actual configuration (granted, it shouldn't blow up like that). Please share a sample project that reproduces the problem.

**Comment by gokhanoner** [comment]
Please see:
https://github.com/gokhanoner/spring-boot-3789

Change ```ActiveProfiles``` from err-1 to err-4, all 4 of them, inside ```ConfPropTestErr``` and see the failed configs.

Also, see ```ConfPropTestOK```for succsessful configs.

**Comment by snicoll** [comment]
`List<Object>` is nasty because the binder does not know what to do with it. You go with the weakest possible semantic. It could be a final node or `val1` may be part of the path (we don't know at this point since we're trying to bind `val1`.

We can rework the way the binder works to provide a better exception but that's all you'll get I am afraid. Why are you using `Object` in your signature?

**Comment by gokhanoner** [comment]
Well, I'm not using actually, I just put it as an example to show this also doesn't work.

My problem is with ```private Map<String, String[]>``` basically, if ```private Map<String, List<String>>``` is working, I guess Array should work to ?

**Comment by snicoll** [comment]
If I had the choice, I'd rather have one simple test rather than one thing focusing on a different problem than the one you are actually reporting. 

Auto-growing of arrays in maps does not seem to be supported.

**Comment by gokhanoner** [comment]
OK from your explanation:
 - List<String> works but List<Object> doesn't, Its OK.
 - Auto grow arrays inside Map also doesn't work, I guess this is also OK, but it should at least give a proper error, I suppose.

If that's the case, it's more like a documentation & raising a proper error, rather than an issue..

**Comment by snicoll** [comment]
I don't see why we couldn't support auto-grow of arrays inside map values. I'll have a look.
