### ISSUE TITLE
ElasticsearchClientConfigurations does not support elasticsearch-java 8.9.x+

### ISSUE THREAD

**Issue by mvh77** [spring-projects/spring-boot#37891]
org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchClientConfigurations.java in **spring-boot-autoconfigure:3.1.4** does not support **elasticsearch-java** 8.9.x+. Works until 8.8.2. Elasticsearch has changed the API for co.elastic.clients.transport.rest_client.RestClientTransport.java where it's no longer backwards compatible.

```
Caused by: java.lang.NoSuchMethodError: 'void co.elastic.clients.transport.rest_client.RestClientTransport.<init>(org.elasticsearch.client.RestClient, co.elastic.clients.json.JsonpMapper, co.elastic.clients.transport.TransportOptions)'
    at org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchClientConfigurations$ElasticsearchTransportConfiguration.restClientTransport(ElasticsearchClientConfigurations.java:94)
    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.base/java.lang.reflect.Method.invoke(Method.java:580)
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139)
    ... 75 more
```

**Comment by wilkinsona** [comment]
Duplicates https://github.com/spring-projects/spring-boot/issues/36669.
