### ISSUE TITLE
samples-web-ui breaks with spring loaded

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#3800]
Tried to run `spring-boot-samples-web-ui` using `mvn clean spring-boot:run` on the command line. I get the following:

```
2015-08-21 09:06:50.700 ERROR 73560 --- [           main] org.springsource.loaded.jvm.JVM          : Problems copying method. Incompatible JVM?
java.lang.IllegalArgumentException: Can not copy a non-root Method
	at java.lang.reflect.Method.copy(Method.java:151) ~[na:1.8.0_45]
	... 43 common frames omitted
Wrapped by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at org.springsource.loaded.jvm.JVM.copyMethod(JVM.java:134) ~[springloaded-1.2.0.RELEASE.jar:1.2.0.RELEASE]
	at org.springsource.loaded.ri.OriginalClassInvoker.createJavaMethod(OriginalClassInvoker.java:68) [springloaded-1.2.0.RELEASE.jar:1.2.0.RELEASE]
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlClassGetDeclaredMethods(ReflectiveInterceptor.java:151) [springloaded-1.2.0.RELEASE.jar:1.2.0.RELEASE]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:606) [spring-core-4.2.1.BUILD-SNAPSHOT.jar:4.2.1.BUILD-SNAPSHOT]
	at org.springframework.util.ReflectionUtils.doWithLocalMethods(ReflectionUtils.java:483) [spring-core-4.2.1.BUILD-SNAPSHOT.jar:4.2.1.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.buildLifecycleMetadata(InitDestroyAnnotationBeanPostProcessor.java:200) [spring-beans-4.2.1.BUILD-SNAPSHOT.jar:4.2.1.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.findLifecycleMetadata(InitDestroyAnnotationBeanPostProcessor.java:181) [spring-beans-4.2.1.BUILD-SNAPSHOT.jar:4.2.1.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessMergedBeanDefinition(InitDestroyAnnotationBeanPostProcessor.java:124) [spring-beans-4.2.1.BUILD-SNAPSHOT.jar:4.2.1.BUILD-SNAPSHOT]
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessMergedBeanDefinition(CommonAnnotationBeanPostProcessor.java:285) [spring-context-4.2.1.BUILD-SNAPSHOT.jar:4.2.1.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyMergedBeanDefinitionPostProcessors(AbstractAutowireCapableBeanFactory.java:935) [spring-beans-4.2.1.BUILD-SNAPSHOT.jar:4.2.1.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:518) [spring-beans-4.2.1.BUILD-SNAPSHOT.jar:4.2.1.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) [spring-beans-4.2.1.BUILD-SNAPSHOT.jar:4.2.1.BUILD-SNAPSHOT]
```

My env:

```
➜  spring-boot-sample-web-ui git:(master) mvn -version
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: /Users/snicoll/tools/maven
Java version: 1.8.0_45, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.5", arch: "x86_64", family: "mac"
```

The same sample ran from the IDE (without spring loaded) works just fine.

**Comment by wilkinsona** [comment]
I wonder where the version, 1.2.0.RELEASE, of Spring Loaded is coming from? 1.2.4.RELEASE is the latest, and is what's in `spring-boot-dependencies`

**Comment by htynkn** [comment]
The version `1.2.0.RELEASE` comes from the pom.xml in `spring-boot-samples-web-ui` folder.

[spring-boot-samples/spring-boot-sample-web-ui/pom.xml](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-samples/spring-boot-sample-web-ui/pom.xml)
