### ISSUE TITLE
Document that Crash requires a JDK and does not work with a JRE

### ISSUE THREAD

**Issue by wiselyman** [spring-projects/spring-boot#3813]
When I use `spring-boot-starter-remote-shell` in a spring boot project. When I use ssh client to input 
```
help 
```
which says:

```
help: exception: NullPointerException
```

and in the console of STS shows:
```
java.lang.NullPointerException: null
	at org.crsh.lang.impl.java.Compiler.compile(Compiler.java:56) ~[crash.shell-1.3.1.jar:na]
	at org.crsh.lang.impl.java.JavaCompiler.compileCommand(JavaCompiler.java:59) ~[crash.shell-1.3.1.jar:na]
	at org.crsh.lang.LanguageCommandResolver.resolveCommand(LanguageCommandResolver.java:128) ~[crash.shell-1.3.1.jar:na]
	at org.crsh.lang.LanguageCommandResolver.resolveCommand2(LanguageCommandResolver.java:109) ~[crash.shell-1.3.1.jar:na]
	at org.crsh.lang.LanguageCommandResolver.resolveCommand(LanguageCommandResolver.java:100) ~[crash.shell-1.3.1.jar:na]
	at org.crsh.shell.impl.command.CRaSH.getCommand(CRaSH.java:100) ~[crash.shell-1.3.1.jar:na]
	at org.crsh.shell.impl.command.CRaSHSession.getCommand(CRaSHSession.java:96) ~[crash.shell-1.3.1.jar:na]
	at org.crsh.lang.impl.script.PipeLineFactory.create(PipeLineFactory.java:89) ~[crash.shell-1.3.1.jar:na]
	at org.crsh.lang.impl.script.ScriptRepl.eval(ScriptRepl.java:88) ~[crash.shell-1.3.1.jar:na]
	at org.crsh.shell.impl.command.CRaSHSession.createProcess(CRaSHSession.java:163) ~[crash.shell-1.3.1.jar:na]
	at org.crsh.shell.impl.async.AsyncProcess.execute(AsyncProcess.java:172) ~[crash.shell-1.3.1.jar:na]
	at org.crsh.console.Console.iterate(Console.java:219) ~[crash.shell-1.3.1.jar:na]
	at org.crsh.console.Console.on(Console.java:158) ~[crash.shell-1.3.1.jar:na]
	at org.crsh.console.Console.on(Console.java:135) ~[crash.shell-1.3.1.jar:na]
	at org.crsh.console.jline.JLineProcessor.run(JLineProcessor.java:204) ~[crash.shell-1.3.1.jar:na]
	at org.crsh.ssh.term.CRaSHCommand.run(CRaSHCommand.java:99) ~[crash.connectors.ssh-1.3.1.jar:na]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_51]
```

The error also occured on my extend command .

**Comment by snicoll** [comment]
You need to provide more info or a sample project because this setup works for me. Don't you have a custom command in your project?

**Comment by wiselyman** [comment]
@snicoll 
Only an empty project with `Remote Shell` dependency generated by STS's `Spring Starter Project`

**Comment by wiselyman** [comment]
@snicoll 
pom.xml
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>org.test</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>demo</name>
	<description>Demo project for Spring Boot</description>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.3.0.M4</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-remote-shell</artifactId>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
	
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
	
	<repositories>
		<repository>
			<id>spring-snapshots</id>
			<name>Spring Snapshots</name>
			<url>https://repo.spring.io/snapshot</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
		<repository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
	</repositories>
	<pluginRepositories>
		<pluginRepository>
			<id>spring-snapshots</id>
			<name>Spring Snapshots</name>
			<url>https://repo.spring.io/snapshot</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</pluginRepository>
		<pluginRepository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>

</project>

```

DemoApplication
```java
package demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class DemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }
}

```

and nothing more!

**Comment by snicoll** [comment]
Please don't paste code here as it's bloating everything. Push your sample project somewhere as it's much more easy for us to clone it to check what's going on.

That being said, that's exactly what I have and it works for me. It looks like crash found a command on your box (no idea how) and that one fails. You may want to report that to the crash tracker or enable debug logs for `org.crsh` to understand what's going on. Feel free to reopen if you have found an actual bug in Spring Boot.

**Comment by wiselyman** [comment]
@snicoll 
Sorry for the pasted code ,I tested my code in Intellij IDEA,and everything is fine;and tests in STS(including mine and collegues 's pc) all went wrong result.
```
Version: 3.7.0.RELEASE
Build Id: 201506290652
Platform: Eclipse Mars (4.5.0)
```

may be something wrong with STS?

**Comment by snicoll** [comment]
I don't know. We're not tracking STS issue here obviously and it definitely doesn't sound like a Spring Boot issue to me.

**Comment by wanghuapeng** [comment]
the issue  same as me,  On my test ,  I found for >jre1.8, it have that error, but jre1.7 worked OK.

**Comment by philwebb** [comment]
I've tested with [STS 3.7.1.RC1](http://dist.springsource.com/release/STS/index.html) JDK 1.8.0_40 and I couldn't replicate the issue.

@wiselyman What happens if you "run as Java application" from STS?

**Comment by wanghuapeng** [comment]
I tested again, jdk1.8.0_45 worked OK,  but On jre1.8.0_60 have that error.

**Comment by wilkinsona** [comment]
I can reproduce this if I run the application with a JRE rather than with the JDK.

Crash compiles its commands on demand and relies on `javax.tools.ToolProvider.getSystemJavaCompiler()` returning a non-null value. If you run on a JRE, there's no compiler available so `null` is returned which causes the NPE.

In short, you can solve your problem by running your app with a JDK, rather than a JRE.

I'm surprised the [Crash's documentation](http://www.crashub.org/1.3/reference.html) doesn't note the JDK requirement. We should probably mention it [here in our documentation](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#production-ready-remote-shell).

**Comment by philwebb** [comment]
I've raise https://jira.exoplatform.org/browse/CRASH-240 to see if they can also improve the error message.
