### ISSUE TITLE
Issues with Spring Boot build behind corporate proxy

### ISSUE THREAD

**Issue by mrumpf** [spring-projects/spring-boot#3816]
The Spring Boot build does not work behind a corporate proxy.
The [Contribution Guidelines](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc) suggests the following command:

```
mvn -P snapshot,prepare install -DskipTests
```

But even if the `-DskipTests` parameter is given, the antunit test is run and fails because there is no proxy configuration passed to the antrun task:

```
[INFO] --- maven-antrun-plugin:1.7:run (antunit) @ spring-boot-antlib ---
[INFO] Executing tasks

main:
    [mkdir] Created dir: C:\work\workspaces\github\spring-boot\spring-boot-tools\spring-boot-antlib\target\it
     [copy] Copying 4 files to C:\work\workspaces\github\spring-boot\spring-boot-tools\spring-boot-antlib\target\it
[pathconvert] C:\work\workspaces\github\spring-boot\spring-boot-tools\spring-boot-antlib\target\spring-boot-antlib-1.3.0.BUILD-SNAPSHOT.jar
  [antunit] Build File: C:\work\workspaces\github\spring-boot\spring-boot-tools\spring-boot-antlib\target\it\sample\build.xml
  [antunit] Tests run: 5, Failures: 0, Errors: 5, Time elapsed: 43,502 sec
  [antunit] Target: test-findmainclass-set-property  caused an ERROR
  [antunit]     at line 10, column 133
  [antunit]     Message: impossible to resolve dependencies:
  [antunit]     resolve failed - see output for details
  [antunit]     took 9,039 sec
  [antunit] Target: test-exejar-find-start-class  caused an ERROR
  [antunit]     at line 10, column 133
  [antunit]     Message: impossible to resolve dependencies:
  [antunit]     resolve failed - see output for details
  [antunit]     took 8,593 sec
  [antunit] Target: test-findmainclass-log-message  caused an ERROR
  [antunit]     at line 10, column 133
  [antunit]     Message: impossible to resolve dependencies:
  [antunit]     resolve failed - see output for details
  [antunit]     took 8,588 sec
  [antunit] Target: test-findmainclass-override  caused an ERROR
  [antunit]     at line 10, column 133
  [antunit]     Message: impossible to resolve dependencies:
  [antunit]     resolve failed - see output for details
  [antunit]     took 8,594 sec
  [antunit] Target: test-exejar-explicit-start-class  caused an ERROR
  [antunit]     at line 10, column 133
  [antunit]     Message: impossible to resolve dependencies:
  [antunit]     resolve failed - see output for details
  [antunit]     took 8,659 sec
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Spring Boot Dependencies ........................... SUCCESS [  2.501 s]
[INFO] Spring Boot Parent ................................. SUCCESS [  1.508 s]
[INFO] Spring Boot Tools .................................. SUCCESS [  0.186 s]
[INFO] Spring Boot Configuration Metadata ................. SUCCESS [  2.067 s]
[INFO] Spring Boot Configuration Processor ................ SUCCESS [  0.341 s]
[INFO] Spring Boot Loader ................................. SUCCESS [  2.567 s]
[INFO] Spring Boot Loader Tools ........................... SUCCESS [  2.131 s]
[INFO] Spring Boot Maven Plugin ........................... SUCCESS [  6.725 s]
[INFO] Spring Boot Gradle Plugin .......................... SUCCESS [  2.073 s]
[INFO] Spring Boot Antlib ................................. FAILURE [ 46.009 s]
[INFO] Spring Boot Build .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:06 min
[INFO] Finished at: 2015-08-24T23:49:30+02:00
[INFO] Final Memory: 68M/673M
[INFO] ------------------------------------------------------------------------
```

So, there are actually 2 issues:
1. When using -DskipTests the antunit execution should also be skipped.
2. The proxy configuration from the Maven settings.xml must be passed to the antrun plugin

My current workaround to get the build past this module was to comment out the antrun plugin in the Maven POM of the antlib module.

**Comment by mrumpf** [comment]
I have created a ticket to add this feature to the Maven Antrun Plugin: https://issues.apache.org/jira/browse/MANTRUN-195

**Comment by mrumpf** [comment]
The maven-invoker-plugin causes additional issues:
1. It does not work with Maven 3.3.3+:
https://issues.apache.org/jira/browse/MNG-5792
2. The plugin does not respect the proxy settings from the parent command line:
`mvn -s ./settings.xml -f spring-boot-full-build -P full clean install`

**Comment by snicoll** [comment]
I am using `3.3.3` and I have no issue FWIW.

**Comment by mrumpf** [comment]
I get the following errors just before the build stops:

    [INFO] --- maven-invoker-plugin:1.9:run (integration-test) @ spring-boot-loader ---
    [INFO] Building: executable-dir\pom.xml
    [INFO] ..FAILED (0.0 s)
    [INFO]   Maven invocation failed. Error configuring command-line. Reason: Maven executable not found at: C:\work\tools\maven\3.3.3\bin\mvn.bat
    [INFO] Building: executable-jar\pom.xml
    [INFO] ..FAILED (0.0 s)
    [INFO]   Maven invocation failed. Error configuring command-line. Reason: Maven executable not found at: C:\work\tools\maven\3.3.3\bin\mvn.bat
    [INFO] Building: executable-props\pom.xml
    [INFO] ..FAILED (0.0 s)
    [INFO]   Maven invocation failed. Error configuring command-line. Reason: Maven executable not found at: C:\work\tools\maven\3.3.3\bin\mvn.bat
    [INFO] Building: executable-war\pom.xml
    [INFO] ..FAILED (0.0 s)
    [INFO]   Maven invocation failed. Error configuring command-line. Reason: Maven executable not found at: C:\work\tools\maven\3.3.3\bin\mvn.bat
    [INFO] -------------------------------------------------
    [INFO] Build Summary:
    [INFO]   Passed: 0, Failed: 4, Errors: 0, Skipped: 0
    [INFO] -------------------------------------------------

**Comment by mrumpf** [comment]
Until now I found `settings.xml` files:
1. The first one gets generated by the first Maven invocation and is then passed as a user `settings.xml` to the second Maven invocation.
2. The second user `settings.xml` file is located in `spring-boot\spring-boot-tools\spring-boot-loader\src\it\settings.xml`

Because the global `settings.xml` and the user `settings.xml` file get merged, a corporate proxy should be added to the `<proxies>` section of the global `settings.xml` file so that you do not need to modify the above mentioned Spring Boot files.

**Comment by mrumpf** [comment]
The next proxy issue is reported by the following test-case:

    Running org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfigurationTests
    Aug 27, 2015 12:23:50 AM de.flapdoodle.embed.process.runtime.Starter prepare
    SEVERE: prepare executable
    java.io.IOException: Could not open inputStream for http://downloads.mongodb.org/win32/mongodb-win32-x86_64-2008plus-2.6.10.zip
        at de.flapdoodle.embed.process.store.Downloader.downloadInputStream(Downloader.java:131)
        at de.flapdoodle.embed.process.store.Downloader.download(Downloader.java:69)
        at de.flapdoodle.embed.process.store.ArtifactStore.checkDistribution(ArtifactStore.java:63)
        at de.flapdoodle.embed.process.store.CachingArtifactStore.checkDistribution(CachingArtifactStore.java:59)
        at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:55)
        at org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration.createEmbeddedMongoServer(EmbeddedMongoAutoConfiguration.java:108)

It seems as if the Embedded MongoDB auto-configuration attempts to download a MongoDB server directly, which does not work behind a proxy.

**Comment by mrumpf** [comment]
The issue with the failing `<antunit>` comes from using Ivy inside the antunit `build.xml` file. Ivy does not respect Maven's proxy setting in the Maven global `settings.xml` file.
To fix this the Maven module's POM should list all dependencies and the Ivy should be configured to resolve the artifacts from the local Maven repositors only.
Another issue is that the provided `ivysettings.xml` file is missing the `repository` part of the path to the local M2 repository.
When adding `joda-time:joda-time:${joda-time.version}` as a dependency to the POM, Ivy does not respect the `optional` scope of the `org.joda:joda-convert:1.2` dependency so that it tries to resolve this library and fails. As a workaround I added this library to the POM as well, which makes the prepare build succeed.

**Comment by mrumpf** [comment]
The MongoDB download is triggered by the Embedded MongoDB feature of the Mongo auto-configuration test-cases: 
https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo
There is a way to set the proxy, but that means the proxy must be read from the Maven's global settings.xml:
https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo#customize-proxy-for-download

**Comment by mrumpf** [comment]
It seems as if setting the proxy at the command line, instead of using the global `settings.xml` works for the MongoDB case:
    mvn -s ./settings.xml -f spring-boot-full-build -P full clean install -rf :spring-boot-autoconfigure -X -Dhttp.proxyHost=proxy.company.net -Dhttp.proxyPort=80 -Dhttps.proxyHost=proxy.company.net -Dhttps.proxyPort=80

**Comment by mrumpf** [comment]
I have now set the proxy in Maven 3.2.1 global `${M2_HOME}/conf/settings.xml` and via the command line `-Dhttp.proxyHost=proxy.company.net -Dhttp.proxyPort=80 -Dhttps.proxyHost=proxy.company.net -Dhttps.proxyPort=80`. The next failure is in the Gradle integration tests:

    Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 7.721 sec <<< FAILURE! - in org.springframework.boot.gradle.BootRunResourceTests
    resourcesDirectlyFromSource(org.springframework.boot.gradle.BootRunResourceTests)  Time elapsed: 6.464 sec  <<< ERROR!
    org.gradle.tooling.GradleConnectionException: Could not install Gradle distribution from 'https://services.gradle.org/distributions/gradle-1.12-bin.zip'.
        at org.gradle.tooling.internal.consumer.DistributionFactory$ZippedDistribution.getToolingImplementationClasspath(DistributionFactory.java:107)
        at org.gradle.tooling.internal.consumer.loader.CachingToolingImplementationLoader.create(CachingToolingImplementationLoader.java:36)
        at org.gradle.tooling.internal.consumer.loader.SynchronizedToolingImplementationLoader.create(SynchronizedToolingImplementationLoader.java:40)
        at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.onStartAction(LazyConsumerActionExecutor.java:98)
        at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:81)
        at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:58)
        at org.gradle.tooling.internal.consumer.connection.LoggingInitializerConsumerActionExecutor.run(LoggingInitializerConsumerActionExecutor.java:44)
        at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:55)
        at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
        at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
        at org.gradle.tooling.internal.consumer.DefaultBuildLauncher.run(DefaultBuildLauncher.java:114)
        at org.springframework.boot.gradle.BootRunResourceTests.resourcesDirectlyFromSource(BootRunResourceTests.java:53)
    Caused by: java.lang.RuntimeException: java.net.ConnectException: Connection refused: connect
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:78)
        at org.gradle.wrapper.Install.createDist(Install.java:44)
        at org.gradle.tooling.internal.consumer.DistributionFactory$ZippedDistribution.getToolingImplementationClasspath(DistributionFactory.java:103)
        at org.gradle.tooling.internal.consumer.loader.CachingToolingImplementationLoader.create(CachingToolingImplementationLoader.java:36)
        at org.gradle.tooling.internal.consumer.loader.SynchronizedToolingImplementationLoader.create(SynchronizedToolingImplementationLoader.java:40)
        at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.onStartAction(LazyConsumerActionExecutor.java:98)
        at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:81)
        at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:58)
        at org.gradle.tooling.internal.consumer.connection.LoggingInitializerConsumerActionExecutor.run(LoggingInitializerConsumerActionExecutor.java:44)
        at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:55)
        at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
    Caused by: java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:656)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:200)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1123)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:998)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:56)
        at org.gradle.wrapper.Download.download(Download.java:42)
        at org.gradle.tooling.internal.consumer.DistributionFactory$ProgressReportingDownload.download(DistributionFactory.java:127)
        at org.gradle.wrapper.Install$1.call(Install.java:57)
        at org.gradle.wrapper.Install$1.call(Install.java:44)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:44)
        at org.gradle.tooling.internal.consumer.DistributionFactory$ZippedDistribution.getToolingImplementationClasspath(DistributionFactory.java:103)
        at org.gradle.tooling.internal.consumer.loader.CachingToolingImplementationLoader.create(CachingToolingImplementationLoader.java:36)
        at org.gradle.tooling.internal.consumer.loader.SynchronizedToolingImplementationLoader.create(SynchronizedToolingImplementationLoader.java:40)
        at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.onStartAction(LazyConsumerActionExecutor.java:98)
        at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:81)
        at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:58)
        at org.gradle.tooling.internal.consumer.connection.LoggingInitializerConsumerActionExecutor.run(LoggingInitializerConsumerActionExecutor.java:44)
        at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:55)
        at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by mrumpf** [comment]
The test-cases download a Gradle distribution and run some Gradle projects. This download fails when there is no proxy configured. I'm preparing a patch where a gradle.properties file is written for each Gradle integration test, which contains the systemProps.http(s).proxyHost|Port settings, generated from the Maven environment.

**Comment by philwebb** [comment]
Perhaps we can get the gradle builds to pickup an environment variable that we export from Maven?

**Comment by mrumpf** [comment]
I had some trouble with Cargo's zipUrlInstaller downloads via a very restrictive proxy:
https://codehaus-cargo.atlassian.net/browse/CARGO-1336

This issue has been fixed now and Spring Boot should update to the next release (no release date yet) to make the Cargo zipUrlInstaller feature more resilient against this kind of failure...

**Comment by mrumpf** [comment]
The test-case ```org.springframework.boot.cli.JarCommandIT.jarCreationWithGrabResolver()``` is causing another issue in a corporate environment (There is an older issue #1354 related to this).
The implementation doing the resolve operation is taking the Maven ```settings.xml``` into account which is nice, because the proxy configuration works out of the box.
But it uses a totally different repository for which there is no mirror available, at least in our corporate environment. My ```settings.xml``` has several mirrors for well-known repositories, because we have internal proxies for them. Direct download does not work in our environment in many cases as the proxies are sometimes truncating the JARs when they believe a virus is hidden inside the files.
When looking at the test-case it seems as if the Embedded Redis is just used as a dummy and we could easily specify another repository and a different dependency to make it work with a well-known repos. For example we could switch to Maven central for the Grabresolver and to version 0.6, because since version 0.6 embedded Redis is available on Maven central.

So the suggestion is to change the ```@Grab``` and ```@GrabResolver``` annotations to this:
```
@GrabResolver(name='central', root='http://central.maven.org/maven2/')
@Grab('com.orange.redis-embedded:embedded-redis:0.6')
```
A mirror for the Maven central repository should be available in all environments, so the test-case will not fail by downloading a a dependency from there.

But I'm not sure whether the exotic repository was purposely added @wilkinsona?

**Comment by mrumpf** [comment]
For the embedded Mono DB server download issue we might need an additional feature in the Maven surefire plugin (see https://issues.apache.org/jira/browse/SUREFIRE-1195)

**Comment by dsyer** [comment]
Isn't the point of that test that it *isn't* downloading from Maven Central. We need to use a different repository (not Maven Central and not one of the repo.spring.io ones).

**Comment by mrumpf** [comment]
I assumed that :( In a restricted environment like ours that means 
# Either I need to create mirror entry in my personal ```settings.xml``` which points to a proxy of this repository in our Nexus Maven repository server
# or make sure the library is present in our thrirdparty repository which is part of the public repositories proxy and the default mirror in my ```settings.xml```
Neither solution comes without manual steps to make the build work :(
Or has someone a better idea?

**Comment by mrumpf** [comment]
PR:  #4367

**Comment by vpavic** [comment]
In case someone find it useful, here's my collection of guidelines for dealing with corporate network proxies: https://github.com/vpavic/proxy-guidelines

It's targeted at Linux but general approach is the same other operating systems.

The only issue I'm having with running Spring Boot build behind our corporate proxy is described in #5883.

**Comment by wilkinsona** [comment]
Declining for the reasons [described here](https://github.com/spring-projects/spring-boot/pull/4367#issuecomment-272019206).
