### ISSUE TITLE
OpenTelemetryMetricsContainerConnectionDetailsFactoryIntegrationTests fails locally with container start error

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#38176]
```

java.lang.IllegalStateException: Mapped port can only be obtained after the container is started
	at org.testcontainers.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:512)
	at org.testcontainers.containers.ContainerState.getMappedPort(ContainerState.java:161)
	at org.springframework.boot.testcontainers.service.connection.otlp.OpenTelemetryMetricsContainerConnectionDetailsFactory$OpenTelemetryMetricsContainerConnectionDetails.getUrl(OpenTelemetryMetricsContainerConnectionDetailsFactory.java:58)
	at org.springframework.boot.actuate.autoconfigure.metrics.export.otlp.OtlpPropertiesConfigAdapter.lambda$0(OtlpPropertiesConfigAdapter.java:67)
	at org.springframework.boot.actuate.autoconfigure.metrics.export.properties.PropertiesConfigAdapter.get(PropertiesConfigAdapter.java:53)
	at org.springframework.boot.actuate.autoconfigure.metrics.export.otlp.OtlpPropertiesConfigAdapter.url(OtlpPropertiesConfigAdapter.java:67)
	at io.micrometer.registry.otlp.OtlpMeterRegistry.publish(OtlpMeterRegistry.java:161)
	at io.micrometer.core.instrument.push.PushMeterRegistry.publishSafely(PushMeterRegistry.java:67)
	at io.micrometer.core.instrument.push.PushMeterRegistry.close(PushMeterRegistry.java:135)
	at io.micrometer.registry.otlp.OtlpMeterRegistry.close(OtlpMeterRegistry.java:260)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:316)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:249)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:587)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:559)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1200)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:520)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1193)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1125)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1086)
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:1019)
```

**Comment by philwebb** [comment]
Possibly related to the testcontainers startup changes.

**Comment by philwebb** [comment]
The failure doesn't always make the test fail because `OtlpMeterRegistry` logs it as a warning. The container in question is otel/opentelemetry-collector-contrib:0.75.0. Here's a build that failed: https://ge.spring.io/s/nv7q47oi62pta

**Comment by philwebb** [comment]
The problem seems to be caused because of a lifecycle mismatch. The container is managed by the `@Testcontainers` annotation and is closed when the test ends. The `ApplicationContext` is managed by Spring and because of context caching remains open until the shutdown hook is is run.
