### ISSUE TITLE
spring-boot-starter-oauth2-client causes AOT processing to fail with "Default code generation is not supported for bean definitions declaring an instance supplier callback"

### ISSUE THREAD

**Issue by simon-hock** [spring-projects/spring-boot#38185]
Hi !
I am trying to build my application with AOT and it seems that the spring-boot-starter-oauth2-client doesn't support it well yet

I am currently pointing to spring-boot-starter-parent:3.2.0-RC1 with the following dependencies:
- spring-boot-starter-web
- spring-boot-starter-data-jpa
- spring-boot-starter-security
- spring-boot-starter-oauth2-client
- spring-boot-devtools
- spring-boot-configuration-processor

And the following build plugin configuration:
```
 <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${org.mapstruct.version}</version>
                        </path>
                    </annotationProcessorPaths>
                    <compilerArgs>
                        <compilerArg>
                            -Amapstruct.defaultComponentModel=spring
                        </compilerArg>
                    </compilerArgs>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.graalvm.buildtools</groupId>
                <artifactId>native-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <image>
                        <builder>paketobuildpacks/builder-jammy-tiny</builder>
                    </image>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
                <executions>
                    <execution>
                        <id>process-aot</id>
                        <goals>
                            <goal>process-aot</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
```

I have configured the OAuth2Client for an authentication with AzureAD.

When building the application, i have this error:

```
anValidationBeanRegistrationAotProcessor : No Bean Validation provider available - skipping validation constraint hint inference
Exception in thread "main" java.lang.IllegalStateException: Default code generation is not supported for bean definitions declaring an instance supplier callback: Root bean: class [org.springframework.security.oauth2.client.OAuth2AuthorizedClientManager]; scope=singleton; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodNames=null; destroyMethodNames=null
	at org.springframework.beans.factory.aot.DefaultBeanRegistrationCodeFragments.getTarget(DefaultBeanRegistrationCodeFragments.java:78)
	at org.springframework.beans.factory.aot.BeanDefinitionMethodGenerator.generateBeanDefinitionMethod(BeanDefinitionMethodGenerator.java:85)
	at org.springframework.beans.factory.aot.BeanRegistrationsAotContribution.lambda$generateRegisterBeanDefinitionsMethod$2(BeanRegistrationsAotContribution.java:90)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at org.springframework.beans.factory.aot.BeanRegistrationsAotContribution.generateRegisterBeanDefinitionsMethod(BeanRegistrationsAotContribution.java:88)
	at org.springframework.beans.factory.aot.BeanRegistrationsAotContribution.lambda$applyTo$1(BeanRegistrationsAotContribution.java:73)
	at org.springframework.aot.generate.GeneratedMethod.<init>(GeneratedMethod.java:54)
	at org.springframework.aot.generate.GeneratedMethods.add(GeneratedMethods.java:112)
	at org.springframework.aot.generate.GeneratedMethods.add(GeneratedMethods.java:89)
	at org.springframework.beans.factory.aot.BeanRegistrationsAotContribution.applyTo(BeanRegistrationsAotContribution.java:72)
	at org.springframework.context.aot.BeanFactoryInitializationAotContributions.applyTo(BeanFactoryInitializationAotContributions.java:78)
	at org.springframework.context.aot.ApplicationContextAotGenerator.lambda$processAheadOfTime$0(ApplicationContextAotGenerator.java:58)
	at org.springframework.context.aot.ApplicationContextAotGenerator.withCglibClassHandler(ApplicationContextAotGenerator.java:67)
	at org.springframework.context.aot.ApplicationContextAotGenerator.processAheadOfTime(ApplicationContextAotGenerator.java:53)
	at org.springframework.context.aot.ContextAotProcessor.performAotProcessing(ContextAotProcessor.java:106)
	at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:84)
	at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:49)
	at org.springframework.context.aot.AbstractAotProcessor.process(AbstractAotProcessor.java:82)
	at org.springframework.boot.SpringApplicationAotProcessor.main(SpringApplicationAotProcessor.java:80)
```

I think this is a bug like [this issue](https://github.com/spring-projects/spring-boot/issues/34563).

Any help would be appreciated !

And have a good day !

**Comment by quaff** [comment]
https://docs.spring.io/spring-framework/reference/core/aot.html
> Bean definitions with instance suppliers (lambdas or method references) cannot be transformed ahead-of-time (see related [spring-framework#29555](https://github.com/spring-projects/spring-framework/issues/29555) issue).

It's documented limitation.

**Comment by wilkinsona** [comment]
It is similar to https://github.com/spring-projects/spring-boot/issues/34563 but in that issue Spring Boot was defining the bean using an instance supplier and in this case I believe it's something else that it doing it. You haven't shared any code so I can't tell for certain but I suspect it's either your code or something in Spring Security that is defining the `OAuth2AuthorizedClientManager` bean in a way that is not compatible with AOT.

If you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by simon-hock** [comment]
Hi again !

Thanks for the extremely fast feedback !

I managed to reproduce using a minimal configuration. You can find the code [here](https://github.com/simon-hock/spring-security-aot)

While trying to reproduce the error, i found out that the version 3.1.5 works but neither 3.2.0-M3 nor 3.2.0-RC1 works.

**Comment by wilkinsona** [comment]
Thanks for the sample and for trying the RC. This is a regression in Spring Security 6.2, caused by the changes made for https://github.com/spring-projects/spring-security/issues/11783. Please open a [Spring Security issue](https://github.com/spring-projects/spring-security/issues).
