### ISSUE TITLE
Add the execution of the process-aot Maven plugin goal to m2e metadata

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects/spring-boot#38382]
To make sure that sources and classes generated and compiled during the AOT phase are available to program executions in STS and Eclipse in general, it would be nice if the `process-aot` goal was added to the `lifecycle-mapping-metadata.xml` for m2e.

```xml
<pluginExecution>
	<pluginExecutionFilter>
		<goals>
			<goal>process-aot</goal>
		</goals>
	</pluginExecutionFilter>
	<action>
		<execute>
			<runOnIncremental>false</runOnIncremental>
			<runOnConfiguration>true</runOnConfiguration>
		</execute>
	</action>
</pluginExecution>
```

I think we'd want to avoid running the goal for incremental compilation as it might take a few ms to run.

**Comment by odrotbohm** [comment]
I've tried to add this snippet to my IDE locally, and it indeed causes the phase to be triggered when the project is updated. That said, this doesn't seem to cause the additional folders to be registered as source folders. I wonder if STS could notify m2e about the additional source folders? /cc @martinlippert

**Comment by martinlippert** [comment]
Adding @BoykoAlex for awareness here

**Comment by martinlippert** [comment]
@odrotbohm We should probably move this issue over to the Spring Tools project: https://github.com/spring-projects/sts4/issues - WDYT?

**Comment by odrotbohm** [comment]
I don't think a move is the right option here because Boot would need to add the necessary metadata to their JAR files. So there is something to change here, assuming the suggestion is accepted. The additional registration of the source folders might be indeed something we should file a ticket for in the STS tracker.

**Comment by wilkinsona** [comment]
Sorry, @odrotbohm. Looks like this one fell through a crack. I think your suggestion makes sense, particularly as we already have a lifecycle mapping for the `build-info` goal.

**Comment by wilkinsona** [comment]
Testing of #51649 has revealed that there's quite a bit to this.

For this to work, the process-aot goal needs to run in a different lifecycle phase (probably PROCESS_CLASSES).

There's also a problem with the JVM that's used to perform AOT processing. In Eclipse, I have Maven configured to use an "execution environment based on maven-compiler-plugin-configuration". However, the `JavaProcessExecutor` in `spring-boot-maven-plugin` ends up using the JVM that's running Eclipse. This can lead to AOT processing failures:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/example/gh_51649/Gh51649Application has been compiled by a more recent version of the Java Runtime (class file version 69.0), this version of the Java Runtime only recognizes class file versions up to 65.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:423)
	at java.base/java.lang.Class.forName(Class.java:414)
	at org.springframework.boot.SpringApplicationAotProcessor.main(SpringApplicationAotProcessor.java:86)
```

We'll need to figure out how to determine the "execution environment based on maven-compiler-plugin-configuration" which is Eclipse-specific in Maven plugin code that cannot be coupled to Eclipse.

Lastly, reading the [m2e documentation](https://wiki.eclipse.org/M2E_compatible_maven_plugins), we also need to use `BuildContext` to record any filesystem changes that are made during AOT processing:

> Regardless of build type, all mojos mapped to <execute/> MUST use plexus-build-api [BuildContext](https://github.com/sonatype/sisu-build-api/blob/master/src/main/java/org/sonatype/plexus/build/incremental/BuildContext.java) to change workspace resources and to associate warning/error/info messages with workspace resources. Additionally, mojos mapped to <execute/> during incremental build or on configuration MUST use [BuildContext](https://github.com/sonatype/sisu-build-api/blob/master/src/main/java/org/sonatype/plexus/build/incremental/BuildContext.java) to skip execution when there none of relevant workspace resources changed.
> 
> BuildContext provides reasonable default behaviour for command line build. It has virtually no impact on build performance, i.e. all build context methods are just pass-though straight to filesystem and thus BuildContext can be used outside of m2e without any impact on the build result.
> 
> Use of BuildContext is required for two reasons
>
> All filesystem changes must be registered as such with build context. This allows m2e to synchronize these changes with their corresponding workspace resources, which will trigger required workspace processing of the changes. For example, if the mojo generates java source code, the new code will not be compiled or won't even be visible in workspace unless workspace is refreshed. Out-of-sync files under target/classes or target/test-classes can also cause unexpected JDT "clean" builds, which result in all non-java files removed.
>
>Mojos that runOnIncremental=true (the default), will be executed for any resource file, including all sources and generated files under target/. For performance and stability reasons it is absolutely essential to short-cut any time consuming work and all filesystem changes if there are no changes to the input sources processed by the mojo. For java code generating mojos, failure to act on relevant input changes only will almost certainly result in endless build -- mojo generates .java files, which triggers jdt to generate .class files, which triggers the mojo to generate .java files, and so on.
>
>Although the current plexus-build-api will still be supported, it will likely be replaced with a new version more tightly integrated with Maven CLI build and other Maven-based tools in the near future.


We already do this in `BuildInfoMojo`:

https://github.com/spring-projects/spring-boot/blob/59379ae449f15a6d17a333f5505941f4165ab3b2/build-plugin/spring-boot-maven-plugin/src/main/java/org/springframework/boot/maven/BuildInfoMojo.java#L125

That's only a single file, however, and AOT processing generates many, many more files. We might be able to perform directory-level refreshes for the generated sources, generated classes, and generated resources directories.

**Comment by wilkinsona** [comment]
I don't think it's possible for us to determine the execution environment from within our AOT-processing mojo. The problem that we're facing is https://github.com/eclipse-m2e/m2e-core/issues/248. Until that's resolved, there's no way for us to find and use the correct JVM when performing AOT processing.

I'm going to close this one for now because, as far as I can tell, it's unsupported by Eclipse/m2e. I've subscribed to the me2 issue so if that situation changes we can re-open this and take another look.
