### ISSUE TITLE
Actuator is always needed to build a native image with spring-boot-testcontainers

### ISSUE THREAD

**Issue by eddumelendez** [spring-projects/spring-boot#38392]
Among all `ContainerConnectionDetailsFactory`, `org.springframework.boot.testcontainers.service.connection.zipkin.ZipkinContainerConnectionDetailsFactory` is one of the ConnectionDetails that is not in `spring-boot-autoconfigure` and it is registered [here](https://github.com/spring-projects/spring-boot/blob/73685d1d02ea2574392249ab3a36e76378f104c9/spring-boot-project/spring-boot-testcontainers/src/main/resources/META-INF/spring/aot.factories#L12)

Project: https://github.com/eddumelendez/testcontainers-samples/tree/main/spring-boot-jpa
GHA: https://github.com/eddumelendez/testcontainers-samples/actions/runs/6899103097/job/18770192551?pr=5
Log:

```
Exception in thread "main" org.springframework.test.context.aot.TestContextAotException: Failed to generate AOT artifacts for test classes [com.example.springbootjpa.ProfileRepositoryTest]
	at org.springframework.test.context.aot.TestContextAotGenerator.lambda$processAheadOfTime$5(TestContextAotGenerator.java:285)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:986)
	at org.springframework.util.MultiValueMapAdapter.forEach(MultiValueMapAdapter.java:179)
	at org.springframework.test.context.aot.TestContextAotGenerator.processAheadOfTime(TestContextAotGenerator.java:243)
	at org.springframework.test.context.aot.TestContextAotGenerator.processAheadOfTime(TestContextAotGenerator.java:205)
	at org.springframework.test.context.aot.TestAotProcessor.performAotProcessing(TestAotProcessor.java:91)
	at org.springframework.test.context.aot.TestAotProcessor.doProcess(TestAotProcessor.java:72)
	at org.springframework.test.context.aot.TestAotProcessor.doProcess(TestAotProcessor.java:39)
	at org.springframework.context.aot.AbstractAotProcessor.process(AbstractAotProcessor.java:82)
	at org.springframework.boot.test.context.SpringBootTestAotProcessor.main(SpringBootTestAotProcessor.java:63)
Caused by: org.springframework.test.context.aot.TestContextAotException: Failed to process test class [com.example.springbootjpa.ProfileRepositoryTest] for AOT
	at org.springframework.test.context.aot.TestContextAotGenerator.processAheadOfTime(TestContextAotGenerator.java:322)
	at org.springframework.test.context.aot.TestContextAotGenerator.lambda$processAheadOfTime$5(TestContextAotGenerator.java:276)
	... 9 more
Caused by: java.lang.IllegalArgumentException: Unable to instantiate factory class [org.springframework.boot.testcontainers.service.connection.zipkin.ZipkinContainerConnectionDetailsFactory] for factory type [org.springframework.aot.hint.RuntimeHintsRegistrar]
	at org.springframework.core.io.support.SpringFactoriesLoader$FailureHandler.lambda$throwing$0(SpringFactoriesLoader.java:647)
	at org.springframework.core.io.support.SpringFactoriesLoader$FailureHandler.lambda$handleMessage$3(SpringFactoriesLoader.java:671)
	at org.springframework.core.io.support.SpringFactoriesLoader.instantiateFactory(SpringFactoriesLoader.java:231)
	at org.springframework.core.io.support.SpringFactoriesLoader.load(SpringFactoriesLoader.java:206)
	at org.springframework.core.io.support.SpringFactoriesLoader.load(SpringFactoriesLoader.java:142)
	at org.springframework.beans.factory.aot.AotServices$Loader.load(AotServices.java:211)
	at org.springframework.context.aot.RuntimeHintsBeanFactoryInitializationAotProcessor.processAheadOfTime(RuntimeHintsBeanFactoryInitializationAotProcessor.java:60)
	at org.springframework.context.aot.BeanFactoryInitializationAotContributions.getContributions(BeanFactoryInitializationAotContributions.java:67)
	at org.springframework.context.aot.BeanFactoryInitializationAotContributions.<init>(BeanFactoryInitializationAotContributions.java:49)
	at org.springframework.context.aot.BeanFactoryInitializationAotContributions.<init>(BeanFactoryInitializationAotContributions.java:44)
	at org.springframework.context.aot.ApplicationContextAotGenerator.lambda$processAheadOfTime$0(ApplicationContextAotGenerator.java:58)
	at org.springframework.context.aot.ApplicationContextAotGenerator.withCglibClassHandler(ApplicationContextAotGenerator.java:67)
	at org.springframework.context.aot.ApplicationContextAotGenerator.processAheadOfTime(ApplicationContextAotGenerator.java:53)
	at org.springframework.test.context.aot.TestContextAotGenerator.processAheadOfTime(TestContextAotGenerator.java:318)
	... 10 more
Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/actuate/autoconfigure/tracing/zipkin/ZipkinConnectionDetails
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3549)
	at java.base/java.lang.Class.getConstructors(Class.java:2227)
	at org.springframework.core.io.support.SpringFactoriesLoader$FactoryInstantiator.findConstructor(SpringFactoriesLoader.java:405)
	at org.springframework.core.io.support.SpringFactoriesLoader$FactoryInstantiator.forClass(SpringFactoriesLoader.java:394)
	at org.springframework.core.io.support.SpringFactoriesLoader.instantiateFactory(SpringFactoriesLoader.java:227)
	... 21 more
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.actuate.autoconfigure.tracing.zipkin.ZipkinConnectionDetails
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 27 more
```

**Comment by wilkinsona** [comment]
Thanks for catching this, @eddumelendez. I suspect that this was caused by the fix for https://github.com/spring-projects/spring-boot/issues/36606.

**Comment by philwebb** [comment]
Actually, since #36606 never made it to a release I'll close this one a superseded so it's not in the release notes.
