### ISSUE TITLE
CLI causes error with description option having white spaces

### ISSUE THREAD

**Issue by nobeans** [spring-projects/spring-boot#3841]
```
$ spring --version
Spring CLI v1.3.0.M4

$ spring init --description="a b c"
java.lang.IllegalArgumentException: Only the target location may be specified
        at org.springframework.util.Assert.isTrue(Assert.java:68)
        at org.springframework.boot.cli.command.init.InitCommand$InitOptionHandler.createProjectGenerationRequest(InitCommand.java:216)
        at org.springframework.boot.cli.command.init.InitCommand$InitOptionHandler.generateProject(InitCommand.java:207)
        at org.springframework.boot.cli.command.init.InitCommand$InitOptionHandler.run(InitCommand.java:188)
        at org.springframework.boot.cli.command.options.OptionHandler.run(OptionHandler.java:92)
        at org.springframework.boot.cli.command.OptionParsingCommand.run(OptionParsingCommand.java:53)
        at org.springframework.boot.cli.command.CommandRunner.run(CommandRunner.java:219)
        at org.springframework.boot.cli.command.CommandRunner.runAndHandleErrors(CommandRunner.java:171)
        at org.springframework.boot.cli.SpringCli.main(SpringCli.java:51)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
        at java.lang.Thread.run(Thread.java:745)
```
These are also failed.

```
$ spring init --description='a b c'
java.lang.IllegalArgumentException: Only the target location may be specified
        at org.springframework.util.Assert.isTrue(Assert.java:68)
        ..(snip)..
$ spring init --description='a\ b\ c'
java.lang.IllegalArgumentException: Only the target location may be specified
        at org.springframework.util.Assert.isTrue(Assert.java:68)
        ..(snip)..
$ spring init --description="a\ b\ c"
java.lang.IllegalArgumentException: Only the target location may be specified
        at org.springframework.util.Assert.isTrue(Assert.java:68)
        ..(snip)..
$ spring init --description=a\ b\ c
java.lang.IllegalArgumentException: Only the target location may be specified
        at org.springframework.util.Assert.isTrue(Assert.java:68)
        ..(snip)..
```

Without white spaces, it works well.

```
$ spring init --description=abc
Using service at https://start.spring.io
        ..(snip)..
```

I think the description option should accept white spaces.

**Comment by snicoll** [comment]
Good catch. There should be a way to escape that thing. Thanks for the report.

**Comment by snicoll** [comment]
See https://github.com/pholser/jopt-simple/issues/11
