### ISSUE TITLE
ClassNotFoundException when setting context class in SpringApplicationBuilder without spring-web

### ISSUE THREAD

**Issue by mjustin** [spring-projects/spring-boot#3856]
When running a Spring Boot application using the SpringApplicationBuilder and a custom context class, a ClassNotFoundException is thrown if spring-web is not on the classpath.  The behavior I would expect is that the application startup should not depend on spring-web being on the classpath.

````
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.boot.maven.RunMojo$LaunchRunner.run(RunMojo.java:418)
	at java.lang.Thread.run(Thread.java:724)
Caused by: java.lang.NoClassDefFoundError: org/springframework/web/context/WebApplicationContext
	at org.springframework.boot.SpringApplication.setApplicationContextClass(SpringApplication.java:875)
	at org.springframework.boot.builder.SpringApplicationBuilder.contextClass(SpringApplicationBuilder.java:253)
	at example.ExampleApplication.main(ExampleApplication.java:10)
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.springframework.web.context.WebApplicationContext
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more
````

The following example project demonstrates the problem.  It fails on "mvn spring-boot:run" with the ClassNotFoundException, but runs when when spring-web is added as a dependency.

ExampleApplication.java
````java
package example;

import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

@SpringBootApplication
public class ExampleApplication {
    public static void main(String[] args) {
        new SpringApplicationBuilder(ExampleApplication.class).contextClass(ExampleContext.class).run(args);
    }

    public static class ExampleContext extends AnnotationConfigApplicationContext {
    }
}
````

pom.xml:
````xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.example</groupId>
  <artifactId>example</artifactId>
  <version>0.0.1-SNAPSHOT</version>

  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>1.2.5.RELEASE</version>
    <relativePath/>
  </parent>

  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter</artifactId>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
</project>
````

**Comment by snicoll** [comment]
`SpringApplication#setApplicationContextClass` is not guarded indeed. Thanks for the report.
