### ISSUE TITLE
Failed to build project with JDK 21

### ISSUE THREAD

**Issue by quaff** [spring-projects/spring-boot#38704]
```
$ ./gradlew -v

------------------------------------------------------------
Gradle 7.6.3
------------------------------------------------------------

Build time:   2023-10-04 15:59:47 UTC
Revision:     1694251d59e0d4752d547e1fd5b5020b798a7e71

Kotlin:       1.7.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          21.0.1 (Homebrew 21.0.1)
OS:           Mac OS X 14.1.2 x86_64
```

```
$ ./gradlew build

> Task :buildSrc:test

ConventionsPluginTests > testRetryIsConfiguredWithZeroRetriesLocally() FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at ConventionsPluginTests.java:225

ConventionsPluginTests > testRetryIsConfiguredWithThreeRetriesOnCI() FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at ConventionsPluginTests.java:225

ConventionsPluginTests > javadocJarIsBuilt() FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at ConventionsPluginTests.java:225

ConventionsPluginTests > jarIncludesLegalFiles() FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at ConventionsPluginTests.java:225

ConventionsPluginTests > sourceJarIsBuilt() FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at ConventionsPluginTests.java:225

BomPluginIntegrationTests > libraryNamedSpringBootHasNoVersionProperty() FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at BomPluginIntegrationTests.java:327

BomPluginIntegrationTests > libraryPluginsAreIncludedInPluginManagementOfGeneratedPom() FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at BomPluginIntegrationTests.java:327

BomPluginIntegrationTests > moduleClassifiersAreIncludedInDependencyManagementOfGeneratedPom() FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at BomPluginIntegrationTests.java:327

BomPluginIntegrationTests > libraryModulesAreIncludedInDependencyManagementOfGeneratedPom() FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at BomPluginIntegrationTests.java:327

BomPluginIntegrationTests > moduleExclusionsAreIncludedInDependencyManagementOfGeneratedPom() FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at BomPluginIntegrationTests.java:327

BomPluginIntegrationTests > moduleTypesAreIncludedInDependencyManagementOfGeneratedPom() FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at BomPluginIntegrationTests.java:327

BomPluginIntegrationTests > libraryImportsAreIncludedInDependencyManagementOfGeneratedPom() FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at BomPluginIntegrationTests.java:327

OptionalDependenciesPluginIntegrationTests > optionalDependenciesAreAddedToMainSourceSetsRuntimeClasspath() FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at OptionalDependenciesPluginIntegrationTests.java:107

OptionalDependenciesPluginIntegrationTests > optionalConfigurationIsCreated() FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at OptionalDependenciesPluginIntegrationTests.java:107

OptionalDependenciesPluginIntegrationTests > optionalDependenciesAreAddedToTestSourceSetsRuntimeClasspath() FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at OptionalDependenciesPluginIntegrationTests.java:107

OptionalDependenciesPluginIntegrationTests > optionalDependenciesAreAddedToMainSourceSetsCompileClasspath() FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at OptionalDependenciesPluginIntegrationTests.java:107

OptionalDependenciesPluginIntegrationTests > optionalDependenciesAreAddedToTestSourceSetsCompileClasspath() FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at OptionalDependenciesPluginIntegrationTests.java:107

TestFailuresPluginIntegrationTests > multiProjectParallel() FAILED
    java.lang.AssertionError at TestFailuresPluginIntegrationTests.java:103

TestFailuresPluginIntegrationTests > multiProjectContinue() FAILED
    java.lang.AssertionError at TestFailuresPluginIntegrationTests.java:87

TestFailuresPluginIntegrationTests > singleProject() FAILED
    java.lang.AssertionError at TestFailuresPluginIntegrationTests.java:59

TestFailuresPluginIntegrationTests > multiProject() FAILED
    java.lang.AssertionError at TestFailuresPluginIntegrationTests.java:73

173 tests completed, 21 failed

> Task :buildSrc:test FAILED
```

```
org.gradle.testkit.runner.UnexpectedBuildFailure: Unexpected build execution failure in /var/folders/83/09n0dj9d1jn9rw1fyjt82dqm0000gn/T/junit762700940021135621 with arguments [jar]

Output:

FAILURE: Build failed with an exception.

* What went wrong:
Could not open cp_settings generic class cache for settings file '/private/var/folders/83/09n0dj9d1jn9rw1fyjt82dqm0000gn/T/junit762700940021135621/settings.gradle' (/Users/zhouyanming/workspace/spring-boot/buildSrc/build/tmp/test/work/.gradle-test-kit/caches/7.6.3/scripts/bjz83uv2xkjh11di8yzmi661i).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 65

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 36ms

	at app//org.gradle.testkit.runner.internal.DefaultGradleRunner.lambda$build$2(DefaultGradleRunner.java:264)
	at app//org.gradle.testkit.runner.internal.DefaultGradleRunner.run(DefaultGradleRunner.java:338)
	at app//org.gradle.testkit.runner.internal.DefaultGradleRunner.build(DefaultGradleRunner.java:262)
	at app//org.springframework.boot.build.ConventionsPluginTests.runGradle(ConventionsPluginTests.java:225)
	at app//org.springframework.boot.build.ConventionsPluginTests.runGradle(ConventionsPluginTests.java:216)
	at app//org.springframework.boot.build.ConventionsPluginTests.jarIncludesLegalFiles(ConventionsPluginTests.java:83)
	at java.base@21.0.1/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base@21.0.1/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base@21.0.1/java.util.ArrayList.forEach(ArrayList.java:1596)
```

**Comment by wilkinsona** [comment]
As [described in the README](https://github.com/spring-projects/spring-boot#building-from-source), you need Java 17 to build from source. If you want to run the tests with a JDK > 17, you can use `-PtoolchainVersion`, for example `-PtoolchainVersion=21`.
