### ISSUE TITLE
ClassNotFoundException when management role is set without Spring Security

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#3888]
To reproduce, create a vanilla app with the actuator (no Spring Security). It works fine but if you specify `management.security.role` you get this

```
Caused by: java.lang.NoClassDefFoundError: org/springframework/security/config/http/SessionCreationPolicy
    at org.springframework.boot.actuate.autoconfigure.ManagementServerProperties$Security.<init>(ManagementServerProperties.java:158)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
    at java.lang.Class.newInstance(Class.java:433)
    at org.springframework.beans.BeanUtils.instantiate(BeanUtils.java:78)
    at org.springframework.beans.AbstractNestablePropertyAccessor.newValue(AbstractNestablePropertyAccessor.java:914)
    at org.springframework.beans.AbstractNestablePropertyAccessor.createDefaultPropertyValue(AbstractNestablePropertyAccessor.java:887)
```

**Comment by snicoll** [comment]
okay so the trick is that `management.security` is `null` unless binding forces it to be created. If we set `management.security.role` then the security instance is created by the binder (and that obviously lead to the exception).

I can see the `security` object being top-level + a condition to enable it which means we'll have to move all the security aspect of the actuator to a separate auto-config element.

**Comment by dsyer** [comment]
A new bean `ManagementSecurityProperties` is probably the best solution, but `ManagementServerProperties` has `ignoreUnknownFields = true` so we would have to break that to fix this problem, unless we find a way to declare exclusions for `ignoreUnknownFields`.

**Comment by snicoll** [comment]
That's #3445

**Comment by dsyer** [comment]
Indeed. But that one is not marked for 1.3, and this one is (and is marked as a bug). I would argue we need to postpone this and downgrade it to an enhancement.l donut can be done properly in 1.4/2.0.

**Comment by snicoll** [comment]
Agreed

**Comment by snicoll** [comment]
Unfortunately, the issue is outside of our control at this stage. The guard makes sure that the `Security` inner class isn't created but when the binder processes `management.security`, it first makes sure it has a _default value_ for it before checking it can actually set the value. If that works fine, we end up in `NotWritablePropertyException` that's going to be ignored by the binder. 

Essentially, our guard only works if we don't attempt to bind any element of the `management.security` namespace. I guess it would be nice to only compute the default value once we have determined that we can actually set it. Maybe @jhoeller has some insight about that?

**Comment by philwebb** [comment]
@snicoll I've gone with the enum option. Ideally we wouldn't change this in 1.4 but a custom was hit by the issue.

**Comment by snicoll** [comment]
Rather than a sample that acts as an integration test can we please use [the test that I've started to craft](https://github.com/snicoll/spring-boot/commit/508f0645e2887cb6e7bf74b557315ed0e44e37b3#diff-02206cff3656613c79d53689357cd126R35)? It reproduces the exact same thing. If you agree I can replace that.

**Comment by wilkinsona** [comment]
Yes please, @snicoll

**Comment by snicoll** [comment]
Reopen to remove the sample and merge the integration test instead
