### ISSUE TITLE
 Issue in resourceHandlerMapping when migrating from 3.1.6 to 3.2.0

### ISSUE THREAD

**Issue by Kryptonian-C** [spring-projects/spring-boot#38933]
When I am migrating from springboot 3.1.6 to 3.2.0 I am facing the exact issue mentioned in 
https://github.com/spring-projects/spring-boot/issues/38636

The issue occurs only during deploying to prod but not on my local which is a windows machine.

I am having the below class and dependency which seems to be causing the issue.

public class SwaggerConfig implements WebFluxConfigurer

<dependency>
	<groupId>org.springdoc</groupId>
	<artifactId>springdoc-openapi-starter-webflux-ui</artifactId>
	<version>2.0.4</version>
</dependency>

Error
```
Application run failedorg.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webHandler' defined in class path resource [org/springframework/boot/autoconfigure/web/reactive/WebFluxAutoConfiguration$EnableWebFluxConfiguration.class]: Error creating bean with name 'resourceHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/reactive/WebFluxAutoConfiguration$EnableWebFluxConfiguration.class]: Failed to instantiate [org.springframework.web.reactive.HandlerMapping]: Factory method 'resourceHandlerMapping' threw exception with message: Uncaught exception during scan| at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:606)| at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521)| at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)| at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)| at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)| at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)| at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975)| at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:960)| at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:625)| at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66)| at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762)
```

**Comment by bclozel** [comment]
Despite its name, springdoc is not a project supported by the Spring team. You should report that against the project directly and probably [upgrade to a version that actually supports Spring Boot 3.2](https://github.com/springdoc/springdoc-openapi/releases/tag/v2.3.0).

**Comment by krunalpuri** [comment]
Kryptonian-C I'm facing same issue when deploying in prod, did you find any solution?

**Comment by anshuldogra37** [comment]
Facing the same issue. Any resolutions ?
