### ISSUE TITLE
java.net.BindException: Address already in use @SpringBootTest using Springboot 3.2.1

### ISSUE THREAD

**Issue by krizajb** [spring-projects/spring-boot#38964]
Hi, I am still dealing with the "Address already in use" exception in springboot 3.2.1. The only problem is, that is actually flaky. The setup is straight forward, two test classes annotated with `@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT, classes = Application.class)` randomly fail with the above mentioned exception. 

Tried disabling test management port, same result. I have seen that there were already two issues fixed on the same topic in 3.2.1 but this one is still present.

**Comment by wilkinsona** [comment]
This sounds like a different problem if it occurs with Actuator disabled. When you're using `RANDOM_PORT` the web servers should use an ephemeral port that's allocated by the operating system and is guaranteed to be free. Unfortunately, I don't think we'll be able to diagnose this one without a sample that reproduces it, even if only in a flaky manner.

**Comment by krizajb** [comment]
Deal, will try my best to somehow extract the project code and make it reproducable.

**Comment by krizajb** [comment]
Oh a thing I have forgot to mention, its about port 8080, which is actually the app default port. Stacktrace

`org.opentest4j.AssertionFailedError: Unexpected exception thrown: org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:152)
	at org.junit.jupiter.api.AssertDoesNotThrow.createAssertionFailedError(AssertDoesNotThrow.java:84)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:53)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:36)
	at org.junit.jupiter.api.Assertions.assertDoesNotThrow(Assertions.java:3168)
	at com.sportradar.mts.cil.odict.odop.MtsOdictOdopApplicationTests.startApplicationTest(MtsOdictOdopApplicationTests.java:20)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:287)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:467)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:256)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:201)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:979)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:628)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:464)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1358)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1347)
	at com.sportradar.mts.cil.odict.odop.MtsOdictOdopApplication.main(MtsOdictOdopApplication.java:10)
	at com.sportradar.mts.cil.odict.odop.MtsOdictOdopApplicationTests.lambda$startApplicationTest$0(MtsOdictOdopApplicationTests.java:20)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:49)
	... 6 more
Caused by: org.springframework.boot.web.server.PortInUseException: Port 8080 is already in use
	at org.springframework.boot.web.server.PortInUseException.lambda$throwIfPortBindingException$0(PortInUseException.java:70)
	at org.springframework.boot.web.server.PortInUseException.lambda$ifPortBindingException$1(PortInUseException.java:85)
	at org.springframework.boot.web.server.PortInUseException.ifCausedBy(PortInUseException.java:103)
	at org.springframework.boot.web.server.PortInUseException.ifPortBindingException(PortInUseException.java:82)
	at org.springframework.boot.web.server.PortInUseException.throwIfPortBindingException(PortInUseException.java:69)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:248)
	at org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:44)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:284)
	... 21 more
Caused by: java.lang.IllegalArgumentException: standardService.connector.startFailed
	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:235)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.addPreviouslyRemovedConnectors(TomcatWebServer.java:306)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:234)
	... 23 more
Caused by: org.apache.catalina.LifecycleException: Protocol handler start failed
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1046)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:232)
	... 25 more
Caused by: java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:555)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)
	at org.apache.tomcat.util.net.NioEndpoint.initServerSocket(NioEndpoint.java:247)
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:202)
	at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1280)
	at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:1366)
	at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:635)
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1043)
	... 27 more
`

**Comment by wilkinsona** [comment]
In that case, it sounds like something is causing `WebEnvironment.RANDOM_PORT` to have no effect. We'll need the previously requested sample to figure out what that is.

**Comment by krizajb** [comment]
It was wiremock that was running on port 8080. Seems like `WebEnvironment.RANDOM_PORT` is not having any effect, correct.

**Comment by wilkinsona** [comment]
Please share a sample and we can take a look.
