### ISSUE TITLE
Prohibit upgrades to HttpClient5 5.3

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#39007]

**Comment by wilkinsona** [comment]
This upgrade is causing intermittent failures due to an NPE:

```
java.lang.NullPointerException: Cannot invoke "org.apache.hc.client5.http.io.ManagedHttpClientConnection.isConsistent()" because "conn" is null
	at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.release(PoolingHttpClientConnectionManager.java:412)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.discardEndpoint(InternalExecRuntime.java:246)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.discardEndpoint(InternalExecRuntime.java:269)
```

It's been reported in [HTTPCLIENT-2313](https://issues.apache.org/jira/browse/HTTPCLIENT-2313) and should be fixed in 5.3.1. I don't fully understand why we're seeing intermittent failures. I suspect it may be because the problem only occurs when a connection is discarded from the pool and the time at which that happens may vary from run to run.
