### ISSUE TITLE
403 FORBIDDEN response after upgrading to springboot 3.0.x

### ISSUE THREAD

**Issue by akanks75** [spring-projects/spring-boot#39693]
IssueType : Bug
SpringBoot Version : 3.0.13
Problem Description:

Http request with invalid MediaTypes in `Accept` header returns 403 instead of 406 which is configured at `ExceptionHandler`. Getting below exception for unit test `testInvalidAcceptHeadersWithoutJsonType()`
```
2024-02-22T12:23:29.026+05:30  WARN 14240 --- [o-auto-1-exec-1] .m.m.a.ExceptionHandlerExceptionResolver : Failure in @ExceptionHandler com.example.TestRestAPI.controller.RESTApiAdviser#handleMyException(MyException)

org.springframework.web.HttpMediaTypeNotAcceptableException: No acceptable representation
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:256) ~[spring-webmvc-6.0.14.jar:6.0.14]
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.handleReturnValue(RequestResponseBodyMethodProcessor.java:194) ~[spring-webmvc-6.0.14.jar:6.0.14]
```
While unit test `testInvalidAcceptHeadersWithJsonType()`, where we just gave an additional `application/json` MediaType in `Accept` header, it returns excepted 406.

Attaching the sample code with both the unit tests 
[TestRestAPI.zip](https://github.com/spring-projects/spring-boot/files/14370190/TestRestAPI.zip)

**Comment by wilkinsona** [comment]
Open source support for Spring Boot 3.0.x [has ended](https://spring.io/projects/spring-boot#support). Please upgrade to Spring Boot 3.1.x or 3.2.x. If the problem still occurs, let us know and we can take another look.

**Comment by akanks75** [comment]
Even after upgrading to spring Boot 3.1.8, issue still persist. Attaching code with updated version 
[TestRestAPI.zip](https://github.com/spring-projects/spring-boot/files/14372214/TestRestAPI.zip)
