### ISSUE TITLE
GraalVM compilation broken in 3.2.3

### ISSUE THREAD

**Issue by smoell** [spring-projects/spring-boot#39744]
After migrating from Spring Boot 3.2.2 to 3.2.3 the GraalVM build fails with:

```
55.01 Error: Could not find target method: public static org.hibernate.bytecode.spi.BytecodeProvider org.springframework.orm.jpa.vendor.Target_BytecodeProviderInitiator.buildBytecodeProvider(java.lang.String)
55.01 com.oracle.svm.core.util.UserError$UserException: Could not find target method: public static org.hibernate.bytecode.spi.BytecodeProvider org.springframework.orm.jpa.vendor.Target_BytecodeProviderInitiator.buildBytecodeProvider(java.lang.String)
55.02   at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:73)
55.02   at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findOriginalMethod(AnnotationSubstitutionProcessor.java:872)
55.02   at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleMethodInAliasClass(AnnotationSubstitutionProcessor.java:463)
55.02   at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleAliasClass(AnnotationSubstitutionProcessor.java:427)
55.02   at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:400)
55.02   at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:356)
55.02   at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.createAnnotationSubstitutionProcessor(NativeImageGenerator.java:1003)
55.02   at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:888)
55.02   at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:579)
55.02   at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:539)
55.02   at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:408)
55.02   at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:612)
55.02   at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:134)
55.02   at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:94)
55.02 ------------------------------------------------------------------------------------------------------------------------
55.02                         3.0s (13.4% of total time) in 37 GCs | Peak RSS: 0.88GB | CPU load: 1.89
55.02 ========================================================================================================================
```

How to reproduce:
1. Check out repo https://github.com/smoell/unicorn-store-spring
2. Build application using `docker build -t unicorn:graal .`

**Comment by wilkinsona** [comment]
Unfortunately, you need to downgrade Hibernate as they have made some breaking changes that will have to be worked around in Spring Framework. See the noteworthy section of [the changelog](https://github.com/spring-projects/spring-boot/releases/tag/v3.2.3) for details.

**Comment by leonardocintra** [comment]
> Unfortunately, you need to downgrade Hibernate as they have made some breaking changes that will have to be worked around in Spring Framework. See the noteworthy section of [the changelog](https://github.com/spring-projects/spring-boot/releases/tag/v3.2.3) for details.

What version of hibernate should I use?

**Comment by philwebb** [comment]
@leonardocintra Please see the top section of the changlelog link
