### ISSUE TITLE
springboot is not support resin4 ? anytime error java.lang.ClassNotFoundException: org.slf4j.LoggerFactory

### ISSUE THREAD

**Issue by edwardlau** [spring-projects/spring-boot#4035]
Hi,
     I run spring-boot-deployment-test-tomcat to resin4.0.45 ,when i import to intellij idea 14 and run package, i copy the spring-boot-deployment-test-tomcat.war to 4.0.45&& unzip , i found resin jvm.log error is :

```Java
java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
                       	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
                       	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
                       	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
                       	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
                       	at org.jboss.logging.Slf4jLoggerProvider.getLogger(Slf4jLoggerProvider.java:33)
                       	at org.jboss.logging.LoggerProviders.find(LoggerProviders.java:37)
                       	at org.jboss.logging.LoggerProviders.<clinit>(LoggerProviders.java:32)
                       	at org.jboss.logging.Logger.getLogger(Logger.java:2163)
                       	at org.jboss.logging.Logger.getMessageLogger(Logger.java:2259)
                       	at org.jboss.logging.Logger.getMessageLogger(Logger.java:2214)
                       	at org.hibernate.validator.internal.util.logging.LoggerFactory.make(LoggerFactory.java:28)
                       	at org.hibernate.validator.internal.util.Version.<clinit>(Version.java:27)
                       	at org.hibernate.validator.internal.engine.ConfigurationImpl.<clinit>(ConfigurationImpl.java:63)
                       	at org.hibernate.validator.HibernateValidator.createGenericConfiguration(HibernateValidator.java:41)
                       	at javax.validation.Validation$GenericBootstrapImpl.configure(Validation.java:269)
                       	at org.springframework.validation.beanvalidation.LocalValidatorFactoryBean.afterPropertiesSet(LocalValidatorFactoryBean.java:223)
                       	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor$Jsr303ValidatorFactory.run(ConfigurationPropertiesBindingPostProcessor.java:384)
                       	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.afterPropertiesSet(ConfigurationPropertiesBindingPostProcessor.java:175)
                       	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1633)
                       	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
                       	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
                       	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
                       	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
                       	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
                       	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
                       	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
                       	at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:199)
                       	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:615)
                       	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:465)
                       	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
                       	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:687)
                       	at org.springframework.boot.SpringApplication.run(SpringApplication.java:321)
                       	at org.springframework.boot.context.web.SpringBootServletInitializer.run(SpringBootServletInitializer.java:133)
                       	at org.springframework.boot.context.web.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:124)
                       	at org.springframework.boot.context.web.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:81)
                       	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:175)
                       	at com.caucho.server.webapp.WebApp.callInitializer(WebApp.java:3591)
                       	at com.caucho.server.webapp.WebApp.callInitializers(WebApp.java:3473)
                       	at com.caucho.server.webapp.WebApp.startImpl(WebApp.java:3787)
                       	at com.caucho.server.webapp.WebApp.access$700(WebApp.java:208)
                       	at com.caucho.server.webapp.WebApp$StartupTask.run(WebApp.java:5317)
                       	at com.caucho.env.thread2.ResinThread2.runTasks(ResinThread2.java:173)
                       	at com.caucho.env.thread2.ResinThread2.run(ResinThread2.java:118)
```

springboot is not support resin4 ?

**Comment by wilkinsona** [comment]
Duplicates #4025
