### ISSUE TITLE
spring-boot-sample-web-jsp not working in no-embed tomcat8

### ISSUE THREAD

**Issue by M3lkior** [spring-projects/spring-boot#4046]
Hi,

I try to deploy your spring-boot-sample-web-jsp in my no-embed tomcat 8(.0.26) but when the server is starting, getting : 

```
2015-09-29 11:51:14.506 ERROR 788 --- [nio-8080-exec-1] o.s.boot.context.web.ErrorPageFilter     : Forwarding to error page from request [/] due to exception [L'uri absolue: http://www.springframework.org/tags ne peut Ãªtre rÃ©solu dans le fichier web.xml ou dans les fichiers jar dÃ©ployÃ©s avec cette application]
org.apache.jasper.JasperException: L'uri absolue: http://www.springframework.org/tags ne peut Ãªtre rÃ©solu dans le fichier web.xml ou dans les fichiers jar dÃ©ployÃ©s avec cette application
	at org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:55) ~[jasper.jar:8.0.26]
	at org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:277) ~[jasper.jar:8.0.26]
	at org.apache.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:75) ~[jasper.jar:8.0.26]
	at org.apache.jasper.compiler.TagLibraryInfoImpl.generateTldResourcePath(TagLibraryInfoImpl.java:243) ~[jasper.jar:8.0.26]
	at org.apache.jasper.compiler.TagLibraryInfoImpl.<init>(TagLibraryInfoImpl.java:124) ~[jasper.jar:8.0.26]
	at org.apache.jasper.compiler.Parser.parseTaglibDirective(Parser.java:411) ~[jasper.jar:8.0.26]
	at org.apache.jasper.compiler.Parser.parseDirective(Parser.java:469) ~[jasper.jar:8.0.26]
	at org.apache.jasper.compiler.Parser.parseElements(Parser.java:1430) ~[jasper.jar:8.0.26]
	at org.apache.jasper.compiler.Parser.parse(Parser.java:139) ~[jasper.jar:8.0.26]
	at org.apache.jasper.compiler.ParserController.doParse(ParserController.java:227) ~[jasper.jar:8.0.26]
	at org.apache.jasper.compiler.ParserController.parse(ParserController.java:100) ~[jasper.jar:8.0.26]
	at org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:199) ~[jasper.jar:8.0.26]
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:356) ~[jasper.jar:8.0.26]
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:336) ~[jasper.jar:8.0.26]
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:323) ~[jasper.jar:8.0.26]
	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:585) ~[jasper.jar:8.0.26]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:363) ~[jasper.jar:8.0.26]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396) ~[jasper.jar:8.0.26]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340) ~[jasper.jar:8.0.26]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) ~[servlet-api.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.26]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.26]
	at org.apa
```

**Comment by wilkinsona** [comment]
This works for me with both Tomcat 8.0.23 and 8.0.26.

The TLD for `http://www.springframework.org/tags` should be packaged in the `spring-webmvc-4.1.7.RELEASE.jar`. I'd recommend double-checking that you have that jar file in the war that you're deploying and that it hasn't been corrupted in some way.

**Comment by M3lkior** [comment]
Hey @wilkinsona,
Deploying this webapp from a external tomcat installation works fine.
I try to deploy this project from Eclipse WTP with "Serve modules without publishing" option and the problem occurs.

The same problem occurs (loading tlds in project/jar, thanks to JarScanner from tomcat-embed-jasper) when i have an opening project in my workspace containing tlds. JarScanner doesn't find tlds in my opening project when i start my boot application but it works when i close this project (and so, my module is considered as jar file)

Classpath loading in spring-boot can be conflictual with WTP classpath loading ?

**Comment by wilkinsona** [comment]
> Classpath loading in spring-boot can be conflictual with WTP classpath loading ?

When you deploy a Spring Boot application to a servlet container there's no custom class loading involved; your application will use the servlet container's standard class loading

> Deploying this webapp from a external tomcat installation works fine.
I try to deploy this project from Eclipse WTP with "Serve modules without publishing" option and the problem occurs.

This appears to be a problem with Tomcat or Eclipse WTP. It also occurs with a plain JSP and Servlet application that references a tag lib in a JAR. As far as I can tell, WTP isn't making the JAR file available to Tomcat's TLD scanning.
