### ISSUE TITLE
MongoDB without Spring Data MongoDB

### ISSUE THREAD

**Issue by ralscha** [spring-projects/spring-boot#4049]
When I add the mongodb driver (org.mongodb:mongo-java-driver) without spring-data-mongodb as a dependency and start the application it throws a ClassNotFoundException (Spring Boot 1.3.0.M5)

The problem is that MongoAutoConfiguration has a @ConditionalOnClass on MongoClient
But the class MongoProperties requires FieldNamingStrategy from the Spring Data library.

As a workaround I can exclude MongoAutoConfiguration from auto configuration
```
@EnableAutoConfiguration(exclude = MongoAutoConfiguration.class)
```

---

```
@ConditionalOnClass(MongoClient.class)
public class MongoAutoConfiguration {
```

```
public class MongoProperties {
        ....
	private Class<? extends FieldNamingStrategy> fieldNamingStrategy;
```

```
java.lang.ClassNotFoundException: org.springframework.data.mapping.model.FieldNamingStrategy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_60]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_60]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_60]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_60]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_60]
	at java.lang.Class.forName(Class.java:348) ~[na:1.8.0_60]
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114) ~[na:1.8.0_60]
	... 51 common frames omitted
Wrapped by: java.lang.TypeNotPresentException: Type org.springframework.data.mapping.model.FieldNamingStrategy not present
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117) ~[na:1.8.0_60]
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125) ~[na:1.8.0_60]
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49) ~[na:1.8.0_60]
	at sun.reflect.generics.reflectiveObjects.WildcardTypeImpl.getUpperBounds(WildcardTypeImpl.java:130) ~[na:1.8.0_60]
	at com.sun.beans.TypeResolver.resolve(TypeResolver.java:175) ~[na:1.8.0_60]
	at com.sun.beans.TypeResolver.resolve(TypeResolver.java:218) ~[na:1.8.0_60]
	at com.sun.beans.TypeResolver.resolve(TypeResolver.java:169) ~[na:1.8.0_60]
	at com.sun.beans.TypeResolver.resolve(TypeResolver.java:218) ~[na:1.8.0_60]
	at com.sun.beans.TypeResolver.resolveInClass(TypeResolver.java:96) ~[na:1.8.0_60]
	at java.beans.FeatureDescriptor.getParameterTypes(FeatureDescriptor.java:387) ~[na:1.8.0_60]
	at java.beans.MethodDescriptor.setMethod(MethodDescriptor.java:116) ~[na:1.8.0_60]
	at java.beans.MethodDescriptor.<init>(MethodDescriptor.java:72) ~[na:1.8.0_60]
	at java.beans.MethodDescriptor.<init>(MethodDescriptor.java:56) ~[na:1.8.0_60]
	at java.beans.Introspector.getTargetMethodInfo(Introspector.java:1205) ~[na:1.8.0_60]
	at java.beans.Introspector.getBeanInfo(Introspector.java:426) ~[na:1.8.0_60]
	at java.beans.Introspector.getBeanInfo(Introspector.java:173) ~[na:1.8.0_60]
	at org.springframework.beans.CachedIntrospectionResults.<init>(CachedIntrospectionResults.java:279) ~[spring-beans-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.beans.CachedIntrospectionResults.forClass(CachedIntrospectionResults.java:189) ~[spring-beans-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.beans.BeanWrapperImpl.getCachedIntrospectionResults(BeanWrapperImpl.java:177) ~[spring-beans-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.beans.BeanWrapperImpl.getPropertyDescriptors(BeanWrapperImpl.java:236) ~[spring-beans-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.filterPropertyDescriptorsForDependencyCheck(AbstractAutowireCapableBeanFactory.java:1368) ~[spring-beans-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.filterPropertyDescriptorsForDependencyCheck(AbstractAutowireCapableBeanFactory.java:1347) ~[spring-beans-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1209) ~[spring-beans-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543) ~[spring-beans-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	... 28 common frames omitted
```

**Comment by snicoll** [comment]
Good catch, thanks.
