### ISSUE TITLE
Problem with upgrade to MongoDB Driver 3.0.x

### ISSUE THREAD

**Issue by ralscha** [spring-projects/spring-boot#4051]
I have an application that uses starter-data-mongodb

```xml
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-mongodb</artifactId>
		</dependency>
```

and this application.yml
```
spring:
  data:
    mongodb:
      host: localhost
```

this works fine. 

Then I tried to upgrade the mongo-java driver to 3.0.4 and added this dependency

```xml
		<dependency>
			<groupId>org.mongodb</groupId>
			<artifactId>mongo-java-driver</artifactId>
			<version>3.0.4</version>
		</dependency>
```

and the application throws an IllegalArgumentException (credentialList can not be null)
To solve this I had to switch to uri config
```
spring:
  data:
    mongodb:
      uri: mongodb://localhost
```

--------

```
2015-09-29 19:05:07.940  WARN 4396 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt
java.lang.IllegalArgumentException: credentialList can not be null
	at com.mongodb.assertions.Assertions.notNull(Assertions.java:37) ~[mongo-java-driver-3.0.4.jar:na]
	at com.mongodb.connection.InternalStreamConnectionFactory.<init>(InternalStreamConnectionFactory.java:36) ~[mongo-java-driver-3.0.4.jar:na]
	at com.mongodb.connection.DefaultClusterableServerFactory.create(DefaultClusterableServerFactory.java:57) ~[mongo-java-driver-3.0.4.jar:na]
	at com.mongodb.connection.BaseCluster.createServer(BaseCluster.java:352) ~[mongo-java-driver-3.0.4.jar:na]
	at com.mongodb.connection.MultiServerCluster.addServer(MultiServerCluster.java:251) ~[mongo-java-driver-3.0.4.jar:na]
	at com.mongodb.connection.MultiServerCluster.<init>(MultiServerCluster.java:79) ~[mongo-java-driver-3.0.4.jar:na]


Caused by: java.lang.IllegalArgumentException: credentialList can not be null
	at com.mongodb.assertions.Assertions.notNull(Assertions.java:37)
	at com.mongodb.connection.InternalStreamConnectionFactory.<init>(InternalStreamConnectionFactory.java:36)
	at com.mongodb.connection.DefaultClusterableServerFactory.create(DefaultClusterableServerFactory.java:57)
	at com.mongodb.connection.BaseCluster.createServer(BaseCluster.java:352)
	at com.mongodb.connection.MultiServerCluster.addServer(MultiServerCluster.java:251)
	at com.mongodb.connection.MultiServerCluster.<init>(MultiServerCluster.java:79)
	at com.mongodb.connection.DefaultClusterFactory.create(DefaultClusterFactory.java:58)
	at com.mongodb.Mongo.createCluster(Mongo.java:660)
	at com.mongodb.Mongo.createCluster(Mongo.java:634)
	at com.mongodb.Mongo.<init>(Mongo.java:279)
	at com.mongodb.MongoClient.<init>(MongoClient.java:254)
	at org.springframework.boot.autoconfigure.mongo.MongoProperties.createMongoClient(MongoProperties.java:227)
	at org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration.mongo(MongoAutoConfiguration.java:69)
	at 
```

**Comment by ralscha** [comment]
Forgot the spring boot version
I tested it with *1.3.0.M5*

**Comment by philwebb** [comment]
I'm not sure that we'll have time to add Mongo 3.0.x support before Spring Boot 1.3 goes GA. It looks like changes to the authentication mechanism are the root cause.

If you define your own `MongoClient` `@Bean` Spring Boot's auto-configuration should step out of the way. Some of the differences between MongoDB 2.x and 3.x are discussed in the [Spring Data reference documentation](http://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#mongo.mongo-3.authentication).

If you do manage to get a working configuration we'd be happy to take a pull-request.

**Comment by ralscha** [comment]
```spring.data.mongodb.uri``` works fine. It's just something you need to be aware of that you have to use this config options with the driver version 3.

**Comment by philwebb** [comment]
Ah thanks for the clarification. We can at least add a note to the documentation.

**Comment by andrewrutter** [comment]
Running into the same problems here and cannot set credentials for the Mongo connection. Is there an example of using a MongoClient @bean with yml configurations that you are aware of?

**Comment by ralscha** [comment]
You can specify credentials with the ```spring.data.mongodb.uri``` config

```
spring:
  data:
    mongodb:
      uri: mongodb://user:secret@mongo1.example.com:12345,mongo2.example.com:23456/test
```

Here is a description about the URI format
http://docs.mongodb.org/manual/reference/connection-string/

**Comment by bartoszwalacik** [comment]
@philwebb could you please tell us what is your plan considering bumping version of mongo-java-driver from 2.13 to 3.0? Latest sprint-boot release (1.3.5) still uses the old mongo client version.

**Comment by philwebb** [comment]
@bartoszwalacik Spring Boot 1.4 will use the 3.2 version (it's currently on 3.2.2). We don't jump major versions on patch releases so Spring Boot 1.3.x will remain on version 2.x of the driver.

**Comment by bartoszwalacik** [comment]
@philwebb thanks for the quick answer, hope that Spring Boot 1.4.0 GA will be released soon.
