### ISSUE TITLE
Renew trust material for SSL tests

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#40589]
We're seeing failures in the following tests:

- `smoketest.amqp.SampleAmqpSimpleApplicationSslTests`
- `smoketest.data.cassandra.SampleCassandraApplicationReactiveSslTests`
- `smoketest.data.cassandra.SampleCassandraApplicationSslTests`
- `smoketest.data.couchbase.SampleCouchbaseApplicationReactiveSslTests`
- `smoketest.data.couchbase.SampleCouchbaseApplicationSslTests`
- `smoketest.data.redis.SampleRedisApplicationJedisSslTests`
- `smoketest.data.redis.SampleRedisApplicationReactiveSslTests`
- `smoketest.data.redis.SampleRedisApplicationSslTests`
- `smoketest.kafka.ssl.SampleKafkaSslApplicationTests`

The failures are due to certificate expiry:

```
Caused by: java.security.cert.CertificateExpiredException: NotAfter: Tue Apr 30 20:49:10 UTC 2024
	at java.base/sun.security.x509.CertificateValidity.valid(CertificateValidity.java:277)
	at java.base/sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:621)
	at java.base/sun.security.provider.certpath.BasicChecker.verifyValidity(BasicChecker.java:190)
	at java.base/sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144)
	at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
	... 85 more
```

We need to renew things with a new expiry date. We should probably set it a long way in the future to avoid this problem in the future and to make it more likely that we'll be able to rebuild a tag in the future should we need to.

**Comment by wilkinsona** [comment]
The following should also have their trust material updated as the certs expire later today:

- `smoketest.data.mongo.SampleMongoApplicationSslTests`
- `smoketest.data.mongo.SampleMongoApplicationReactiveSslTests`
