### ISSUE TITLE
`@AutoConfigureWebTestClient` does not work on mock environment

### ISSUE THREAD

**Issue by MasatoshiTada** [spring-projects/spring-boot#40622]
# Environment
- macOS 14.4.1 (M1 Pro MBP)
- Eclipse Temurin 21.0.3
- Spring Boot 3.2.5

# Description
I wrote a test with `@SpringBootTest` and `@AutoConfigureWebTestClient`.
This test fails with `UnsatisfiedDependencyException` and it seems there is no `WebTestClient` bean.

# Sample application
https://github.com/MasatoshiTada/web-test-client-sample
This has 3 tests:

- [`HelloIntegrationTest`](https://github.com/MasatoshiTada/web-test-client-sample/blob/main/src/test/java/com/example/webtestclientsample/HelloIntegrationTest.java) -> OK
- [`HelloRestControllerMockMvcTest`](https://github.com/MasatoshiTada/web-test-client-sample/blob/main/src/test/java/com/example/webtestclientsample/HelloRestControllerMockMvcTest.java) -> OK
- [`HelloRestControllerWebClientTest`](https://github.com/MasatoshiTada/web-test-client-sample/blob/main/src/test/java/com/example/webtestclientsample/HelloRestControllerWebClientTest.java) -> Failed

```java
package com.example.webtestclientsample;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.reactive.AutoConfigureWebTestClient;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.web.reactive.server.WebTestClient;

@SpringBootTest
@AutoConfigureWebTestClient
public class HelloRestControllerWebClientTest {

    @Autowired
    WebTestClient webClient;

    @Test
    void hello() {
        webClient.get().uri("/")
                .exchange()
                .expectStatus().isOk()
                .expectBody().json("""
                {"message":  "Hello"}
                """);
    }
}
```

The stack trace is below.

```shell
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.example.webtestclientsample.HelloRestControllerWebClientTest': Unsatisfied dependency expressed through field 'webClient': No qualifying bean of type 'org.springframework.test.web.reactive.server.WebTestClient' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:787)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:767)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:145)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:508)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1419)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireBeanProperties(AbstractAutowireCapableBeanFactory.java:398)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:143)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:98)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:260)
	at org.springframework.test.context.junit.jupiter.SpringExtension.postProcessTestInstance(SpringExtension.java:163)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.test.web.reactive.server.WebTestClient' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1880)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1406)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:784)
	... 21 more
```

**Comment by wilkinsona** [comment]
This is the expected [and documented](https://docs.spring.io/spring-boot/docs/3.2.x/reference/htmlsingle/#features.testing.spring-boot-applications.with-mock-environment) behavior. You need to use `@AutoConfigureMockMvc` to use `WebTestClient` with a Servlet/Spring MVC-based application. `@AutoConfigureWebTestClient` is for when you're using WebFlux on the server side.
