### ISSUE TITLE
Application property spring.main.web-environment=false  does not disable StandardServletEnvironment

### ISSUE THREAD

**Issue by frensley** [spring-projects/spring-boot#4068]
Using the property ``spring.main.web-environment=false`` in application properties still initializes the ``StandardServletEnvironment``. I believe this is because the properties are set onto ``SpringApplication`` __after__ ``getOrCreateEnvironment()`` is called. This makes it impossible to disable the ServletEnvironment through properties.

env: spring-boot:1.2.6.RELEASE

**Comment by snicoll** [comment]
Actually, doing so will lead to 

```
Caused by: java.lang.IllegalArgumentException: A ServletContext is required to configure default servlet handling
	at org.springframework.util.Assert.notNull(Assert.java:112)
	at org.springframework.web.servlet.config.annotation.DefaultServletHandlerConfigurer.<init>(DefaultServletHandlerConfigurer.java:53)
	at org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport.defaultServletHandlerMapping(WebMvcConfigurationSupport.java:426)
	at org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$EnableWebMvcConfiguration$$EnhancerBySpringCGLIB$$a6328373.CGLIB$defaultServletHandlerMapping$27(<generated>)
	at org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$EnableWebMvcConfiguration$$EnhancerBySpringCGLIB$$a6328373$$FastClassBySpringCGLIB$$32007cc0.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:309)
	at org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$EnableWebMvcConfiguration$$EnhancerBySpringCGLIB$$a6328373.defaultServletHandlerMapping(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 22 more
```

**Comment by frensley** [comment]
It looks like this issue could be fixed by a recent [commit](https://github.com/spring-projects/spring-boot/commit/2169bbbc9b46c74706b04d9663b6dba8b442edc4) in 1.3

**Comment by philwebb** [comment]
Fixed in 2169bbbc9b46c74706b04d9663b6dba8b442edc4

**Comment by farmerworking** [comment]
@philwebb 

both 
spring.main.webEnvironment=false
spring.main.web-environment=false
don't work

env: spring-boot:1.4.3.RELEASE

**Comment by wilkinsona** [comment]
@farmerworking This issue is closed and we believe that it's fixed. If you have a situation where that's not the case please open a new issue with a sample that recreates the problem.
