### ISSUE TITLE
Spring Boot Maven Plugin start not registered on 1.3.0.BUILD-SNAPSHOT

### ISSUE THREAD

**Issue by gjoris** [spring-projects/spring-boot#4072]
Hi all, 

When I noticed the updated document over at the documentation pages for the [Spring Boot Maven Plugin](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/maven-plugin/examples/it-random-port.html), I immediately tried it out, since I've been searching for a possibility to implement the jetty & failsafe behaviour. It was present in the previous version of the application I currently work at (Spring 3), but after refactoring and upgrading to Spring Boot 1.2.6 the setup is no longer functional. 

However, when I try booting the application with the plugin, it eventually fails with the message: 

```
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.3.0.BUILD-SNAPSHOT:start (pre-integration-test) on project ****************: Spring application did not start before the configured timeout (30000ms -> [Help 1]
```

The application shows correct logging, so it has booted correctly. My config matches the documentation page almost exactly, the only difference being that I configured my mainClass. 

The -e flag produces the following stack trace: 

```
Spring application did not start before the configured timeout (30000ms
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Spring application did not start before the configured timeout (30000ms
        at org.springframework.boot.maven.StartMojo.waitForSpringApplication(StartMojo.java:174)
        at org.springframework.boot.maven.StartMojo.runWithMavenJvm(StartMojo.java:149)
        at org.springframework.boot.maven.AbstractRunMojo.run(AbstractRunMojo.java:202)
        at org.springframework.boot.maven.AbstractRunMojo.execute(AbstractRunMojo.java:161)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
```

Is there anything I'm missing?

**Comment by snicoll** [comment]
[As described in the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. For general usage questions, please use [StackOverflow](http://stackoverflow.com).

When you do create the SO thread, it's much more interesting to see your _actual_ plugin configuration. You don't need to use the snapshot by the  way, `1.3.0.M5` is available from the milestone repository.
