### ISSUE TITLE
[MongoProperties] createMongoClient fail when using hasCustomAddress = true and hasCustomCredentials = false

### ISSUE THREAD

**Issue by amgohan** [spring-projects/spring-boot#4076]
When trying to connect to mongodb (java driver 3.0.3) using only : 

    spring.data.mongodb.host=localhost
    spring.data.mongodb.port=27017
    spring.data.mongodb.database=helloMongo

I get this error : 

    Caused by: java.lang.IllegalArgumentException: credentialList can not be null
    	at com.mongodb.assertions.Assertions.notNull(Assertions.java:37)
    	at com.mongodb.connection.InternalStreamConnectionFactory.<init>(InternalStreamConnectionFactory.java:36)
    	at com.mongodb.connection.DefaultClusterableServerFactory.create(DefaultClusterableServerFactory.java:57)
    	at com.mongodb.connection.BaseCluster.createServer(BaseCluster.java:352)
    	at com.mongodb.connection.MultiServerCluster.addServer(MultiServerCluster.java:251)
    	at com.mongodb.connection.MultiServerCluster.<init>(MultiServerCluster.java:79)
    	at com.mongodb.connection.DefaultClusterFactory.create(DefaultClusterFactory.java:58)
    	at com.mongodb.Mongo.createCluster(Mongo.java:660)
    	at com.mongodb.Mongo.createCluster(Mongo.java:634)
    	at com.mongodb.Mongo.<init>(Mongo.java:279)
    	at com.mongodb.MongoClient.<init>(MongoClient.java:254)
    	at org.springframework.boot.autoconfigure.mongo.MongoProperties.createMongoClient(MongoProperties.java:181)
    	at com.agileasoft.cheers.config.MongoDBConfiguration.mongoClient(MongoDBConfiguration.java:27)
    	at com.agileasoft.cheers.config.MongoDBConfiguration$$EnhancerBySpringCGLIB$$3a663ab7.CGLIB$mongoClient$1(<generated>)
    	at com.agileasoft.cheers.config.MongoDBConfiguration$$EnhancerBySpringCGLIB$$3a663ab7$$FastClassBySpringCGLIB$$26de08d0.invoke(<generated>)
    	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
    	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:318)
    	at com.agileasoft.cheers.config.MongoDBConfiguration$$EnhancerBySpringCGLIB$$3a663ab7.mongoClient(<generated>)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:483)
    	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
    	... 110 more

In MongoPorperties.createMongoClient : 

You should use the constructor new ```MongoClient(Arrays.asList(new ServerAddress(host, port)),  options);``` when credentials is null.

**Comment by philwebb** [comment]
Possibly related to #4051

**Comment by Powerrr** [comment]
This also affects me, and I can't use a workaround of setting only `spring.data.mongodb.uri` because I need to override the port for embedded mongo, and that can only be done (aside from writing custom configuration code) using `spring.data.mongodb.port`.

The above-suggested fix - using
```java
new MongoClient(Arrays.asList(new ServerAddress(host, port)), options)
```
instead of
```java
new MongoClient(Arrays.asList(new ServerAddress(host, port)), null, options)
```
seems valid, and you can also use an empty credentials list instead of `null`:
```java
new MongoClient(Arrays.asList(new ServerAddress(host, port)), Collections.<MongoCredential>emptyList(), options)
```

And as far as I can tell, both alternatives will work for version 2 of the mongo driver.
