### ISSUE TITLE
DataSourceProperties swallows UnsupportedClassVersionError

### ISSUE THREAD

**Issue by britter** [spring-projects/spring-boot#4082]
When using a database driver which has been compiled with a more recent Java version then the application is running with, the produced error message is not very helpful in finding the root cause of the problem:

```
Caused by: java.lang.IllegalStateException: Cannot load driver class: org.postgresql.Driver
	at org.springframework.util.Assert.state(Assert.java:385)
	at org.springframework.boot.autoconfigure.jdbc.DataSourceProperties.getDriverClassName(DataSourceProperties.java:122)
	at org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration$NonEmbeddedConfiguration.dataSource(DataSourceAutoConfiguration.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 45 more
```

Steps to reproduce: clone https://github.com/britter/spring-boot-unsupportedclassversionerror-example and run `mvn spring-boot:run` under Java 7.

The problem here is, that `DataSourceAutoConfiguration$NonEmbeddedConfiguration.dataSource(DataSourceAutoConfiguration)` uses `org.springframework.util.ClassUtils.isPresent(String)` to check whether it can load the driver class. the `isPresent(String)` method in turn catches all Throwables and swallows the root cause silently.

Proposed change: Propagate `UnsupportedClassVersionError` so that it is easier to find out what is going on. If this proposal is considered for inclusion, I can put together a PR.

Thank you!

**Comment by philwebb** [comment]
Seems like a sensible change. A pull request would be most welcome. Please remember to sign the CLA if you haven't already.

**Comment by zhanhb** [comment]
maybe 9.4-1203-jdbc41 is required.

**Comment by britter** [comment]
ICLA has been filed, confirmation number is 141320151003110519. Working on a PR now.
