### ISSUE TITLE
Exception on application startup with the newest version of micrometer-tracing-bridge-brave

### ISSUE THREAD

**Issue by mblaze** [spring-projects/spring-boot#40854]
I've encountered a problem with application startup with:
- org.springframework.boot:spring-boot-starter-actuator:3.2.5
- io.micrometer:micrometer-tracing-bridge-brave:1.3.0
- io.zipkin.brave:brave:6.0.3 (transitive from micrometer-tracing-bridge-brave)

I think the crucial part of the exception I'm getting is:
```
Caused by: java.lang.UnsupportedOperationException: As of Brave 5.18, you must implement PropagationFactory.get()
	at brave.propagation.Propagation$Factory.get(Propagation.java:95) ~[brave-6.0.3.jar:?]
	at brave.Tracing$Default.<init>(Tracing.java:371) ~[brave-6.0.3.jar:?]
	at brave.Tracing$Builder.build(Tracing.java:341) ~[brave-6.0.3.jar:?]
	at org.springframework.boot.actuate.autoconfigure.tracing.BraveAutoConfiguration.braveTracing(BraveAutoConfiguration.java:123) ~[spring-boot-actuator-autoconfigure-3.2.5.jar:3.2.5]
```

Downgrading to io.micrometer:micrometer-tracing-bridge-brave:1.2.6 seems to solve the issue.

As far as I was able to track the problem down it seems to be related to the implementation of `org.springframework.boot.actuate.autoconfigure.tracing.CompositePropagationFactory` being incompatible with `io.zipkin.brave:brave:6.x.x`. The incompatibility is related to the lack of an implementation of the method mentioned in the exception message.

**Comment by wilkinsona** [comment]
Spring Boot 3.2.x does not support Brave 6.0. Support is coming in Spring Boot 3.3 that will be released later this week.
