### ISSUE TITLE
Springboot v3.3.0 - application failing during startup due to zipkin / brave tracing version upgrade

### ISSUE THREAD

**Issue by ashishsinghTW** [spring-projects/spring-boot#40914]
I recently upgraded to springboot v3.3, after which the app is failing during startup. Service is hosted on gcp. Error:

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate 
[zipkin2.reporter.AsyncReporter]: Factory method 'stackdriverReporter' threw exception with message: Receiver class
zipkin2.reporter.stackdriver.StackdriverSender does not define or inherit an implementation of the resolved method 'abstract zipkin2.reporter.Encoding encoding()' 
of interface zipkin2.reporter.BytesMessageSender.
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:177)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:644)
	... 142 common frames omitted
Caused by: java.lang.AbstractMethodError: Receiver class zipkin2.reporter.stackdriver.StackdriverSender 
does not define or inherit an implementation of the resolved method 'abstract zipkin2.reporter.Encoding encoding()' 
of interface zipkin2.reporter.BytesMessageSender.
	at zipkin2.reporter.AsyncReporter$Builder.<init>(AsyncReporter.java:104)
	at zipkin2.reporter.AsyncReporter.builder(AsyncReporter.java:64)
	at zipkin2.reporter.AsyncReporter.builder(AsyncReporter.java:59)
	at com.google.cloud.spring.autoconfigure.trace.StackdriverTraceAutoConfiguration.stackdriverReporter(StackdriverTraceAutoConfiguration.java:178)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:140)
	... 143 common frames omitted
```

 I am using following tracing dependencies:
```
  implementation 'com.google.cloud:spring-cloud-gcp-starter-trace:5.3.0'
  implementation 'io.micrometer:micrometer-tracing-bridge-brave:1.3.0'
  implementation 'com.google.cloud:spring-cloud-gcp-starter-metrics':5.3.0
```

Any idea on why this might be happening ?

**Comment by mhalbritter** [comment]
Looks like `spring-cloud-gcp-starter-trace` is using Brave 5. They need to update it to Brave 6.

**Comment by codefromthecrypt** [comment]
Just to be concrete. For folks who still have deps on reporter 2.x, the path as suggested by @mhalbritter is correct. Upgrade to Brave 6 which decouples you from zipkin-reporter versions.

Then, if you have to use 2.x reporter, pin the last version of it like so

https://github.com/openzipkin/brave-example/blob/master/webflux5-sleuth/pom.xml#L28-L30

Then, update to 3.x. This is the least unhappy path.

**Comment by codefromthecrypt** [comment]
reworded my comment as I realized this was about boot 3.3 it should only ever use zipkin-reporter 3+
