### ISSUE TITLE
Error creating HealthEndpointConfiguration in AbstractAspectJAdvice.bindExplicitArguments in 3.2.6

### ISSUE THREAD

**Issue by pkubowicz** [spring-projects/spring-boot#40933]
I'm reporting a separate issue after my case was rejected to be part of https://github.com/spring-projects/spring-boot/issues/40895#issuecomment-2133002349.

Reproducing:
1. use spring-boot-starter-actuator
2. `@EnableAspectJAutoProxy`
3. `@EnableTransactionManagement(mode = AdviceMode.ASPECTJ)`

and context will fail to start with:
```
Error creating bean with name 'healthEndpointGroupsBeanPostProcessor' defined in class path resource [org/springframework/boot/actuate/autoconfigure/health/HealthEndpointConfiguration.class]: BeanPostProcessor before instantiation of bean failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'healthEndpointGroupsBeanPostProcessor' defined in class path resource [org/springframework/boot/actuate/autoconfigure/health/HealthEndpointConfiguration.class]: BeanPostProcessor before instantiation of bean failed
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
Caused by: java.lang.IllegalStateException: Expecting to find 3 arguments to bind by name in advice, but actually found 2 arguments.
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.bindExplicitArguments(AbstractAspectJAdvice.java:472)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.bindArgumentsByName(AbstractAspectJAdvice.java:438)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.calculateArgumentBindings(AbstractAspectJAdvice.java:389)
	at org.springframework.aop.aspectj.annotation.ReflectiveAspectJAdvisorFactory.getAdvice(ReflectiveAspectJAdvisorFactory.java:306)
	at org.springframework.aop.aspectj.annotation.InstantiationModelAwarePointcutAdvisorImpl.instantiateAdvice(InstantiationModelAwarePointcutAdvisorImpl.java:152)
	at org.springframework.aop.aspectj.annotation.InstantiationModelAwarePointcutAdvisorImpl.<init>(InstantiationModelAwarePointcutAdvisorImpl.java:116)
	at org.springframework.aop.aspectj.annotation.ReflectiveAspectJAdvisorFactory.getAdvisor(ReflectiveAspectJAdvisorFactory.java:216)
	at org.springframework.aop.aspectj.annotation.ReflectiveAspectJAdvisorFactory.getAdvisors(ReflectiveAspectJAdvisorFactory.java:146)
```

Same code works with Spring Boot 3.2.5.

Simple reproducing project: https://github.com/pkubowicz/spring-boot-326-aspects-bug
(run `./gradlew test` to see the error)

**Comment by wilkinsona** [comment]
Thanks for opening a separate issue. Since I made that request, I've learned that this is caused by a [regression in Spring Framework](https://github.com/spring-projects/spring-framework/issues/32882). Please see that issue for some suggestions on how to work around the problem.
