### ISSUE TITLE
Liquibase throws FileNotFoundException when using Jetty

### ISSUE THREAD

**Issue by toellrich** [spring-projects/spring-boot#4105]
When I switch from Tomcat to Jetty Liquibase logs the following warnings during startup (twice):

```
2015-10-07 09:58:30.980  WARN 10620 --- [           main] liquibase                                : No Liquibase-Packages entry found in MANIFEST.MF. Using fallback of entire 'liquibase' package
2015-10-07 09:58:30.983  WARN 10620 --- [           main] liquibase                                : Error initializing SpringLiquibase

java.io.FileNotFoundException: ServletContext resource [/liquibase] cannot be resolved to URL because it does not exist
	at org.springframework.web.context.support.ServletContextResource.getURL(ServletContextResource.java:156)
	at liquibase.integration.spring.SpringLiquibase$SpringResourceOpener.init(SpringLiquibase.java:116)
	at liquibase.resource.AbstractResourceAccessor.<init>(AbstractResourceAccessor.java:22)
	at liquibase.resource.ClassLoaderResourceAccessor.<init>(ClassLoaderResourceAccessor.java:18)
	at liquibase.integration.spring.SpringLiquibase$SpringResourceOpener.<init>(SpringLiquibase.java:73)
	at liquibase.integration.spring.SpringLiquibase.createResourceOpener(SpringLiquibase.java:468)
	at liquibase.integration.spring.SpringLiquibase.createLiquibase(SpringLiquibase.java:419)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:377)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1633)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:293)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:956)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:747)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:687)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:321)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:967)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:956)
	at hello.Application.main(Application.java:18)
```

Liquibase still seems to work alright though

**Comment by wilkinsona** [comment]
Duplicates #2878
