### ISSUE TITLE
[Spring boot 3.3.+] Using `Counter` from `io.micrometer:micrometer-registry-prometheus` causes error in the application

### ISSUE THREAD

**Issue by mauriciogeneroso** [spring-projects/spring-boot#41136]
## Context

After the upgrade to Spring `3.3.+`, when starting a project that contains the library `io.micrometer:micrometer-registry-prometheus`, and we use `Counter`, it couses the error on runtime:

<details> <summary>Stack Trace</summary>

```
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed: java.lang.NoClassDefFoundError: io/prometheus/metrics/tracer/initializer/SpanContextSupplier] with root cause

java.lang.ClassNotFoundException: io.prometheus.metrics.tracer.initializer.SpanContextSupplier
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	at io.prometheus.metrics.core.exemplars.ExemplarSampler.doSampleExemplar(ExemplarSampler.java:327) ~[prometheus-metrics-core-1.2.1.jar:na]
	at io.prometheus.metrics.core.exemplars.ExemplarSampler.updateExemplar(ExemplarSampler.java:310) ~[prometheus-metrics-core-1.2.1.jar:na]
	at io.prometheus.metrics.core.exemplars.ExemplarSampler.doObserveSingleExemplar(ExemplarSampler.java:123) ~[prometheus-metrics-core-1.2.1.jar:na]
	at io.prometheus.metrics.core.exemplars.ExemplarSampler.doObserve(ExemplarSampler.java:111) ~[prometheus-metrics-core-1.2.1.jar:na]
	at io.prometheus.metrics.core.exemplars.ExemplarSampler.lambda$observe$0(ExemplarSampler.java:99) ~[prometheus-metrics-core-1.2.1.jar:na]
	at io.prometheus.metrics.core.exemplars.ExemplarSampler.rateLimitedObserve(ExemplarSampler.java:276) ~[prometheus-metrics-core-1.2.1.jar:na]
	at io.prometheus.metrics.core.exemplars.ExemplarSampler.observe(ExemplarSampler.java:99) ~[prometheus-metrics-core-1.2.1.jar:na]
	at io.prometheus.metrics.core.metrics.Counter$DataPoint.inc(Counter.java:167) ~[prometheus-metrics-core-1.2.1.jar:na]
	at io.prometheus.metrics.core.metrics.Counter.inc(Counter.java:53) ~[prometheus-metrics-core-1.2.1.jar:na]
	at io.prometheus.metrics.core.datapoints.CounterDataPoint.inc(CounterDataPoint.java:53) ~[prometheus-metrics-core-1.2.1.jar:na]
	at com.example.demo.ControllerTest.test(ControllerTest.java:21) ~[main/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255) ~[spring-web-6.1.8.jar:6.1.8]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188) ~[spring-web-6.1.8.jar:6.1.8]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[spring-webmvc-6.1.8.jar:6.1.8]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:926) ~[spring-webmvc-6.1.8.jar:6.1.8]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:831) ~[spring-webmvc-6.1.8.jar:6.1.8]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.1.8.jar:6.1.8]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089) ~[spring-webmvc-6.1.8.jar:6.1.8]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979) ~[spring-webmvc-6.1.8.jar:6.1.8]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-6.1.8.jar:6.1.8]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903) ~[spring-webmvc-6.1.8.jar:6.1.8]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:564) ~[tomcat-embed-core-10.1.24.jar:6.0]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.1.8.jar:6.1.8]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) ~[tomcat-embed-core-10.1.24.jar:6.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:195) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-embed-websocket-10.1.24.jar:10.1.24]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-6.1.8.jar:6.1.8]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.8.jar:6.1.8]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-6.1.8.jar:6.1.8]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.8.jar:6.1.8]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-6.1.8.jar:6.1.8]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.8.jar:6.1.8]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:389) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63) ~[tomcat-embed-core-10.1.24.jar:10.1.24]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

</details>

### How to reproduce the error?

1. Start a new Spring boot application (it might be from `https://start.spring.io/`)
2. Includes the dependencies `web` and `prometheus`
3. Change the library 'io.micrometer:micrometer-registry-prometheus' to be `implementation` and not `runtimeOnly`
4. In the code, create a controller that contains a Counter like this one:

<details><summary>Controller</summary>

```
@RestController
@RequestMapping("/test")
public class ControllerTest {


    @GetMapping
    public String test() {
        Counter counter = Counter.builder()
            .name("test_metric")
            .build();

        counter.inc();
        return "test";
    }

}
```

</details>

--> Download a demo project: 
[demo.zip](https://github.com/user-attachments/files/15872906/demo.zip)

5. Start the application, and call `http://localhost:8080/test`
6. The error will happen

### Alternatives

The alternatives found to fix the issue, is setting the Counter without Examples (method `.withoutExemplars()`), or import the library `io.prometheus:metrics.tracer.initializer` explicitly.

### Notes

During investigation, found that the issue started with the change in the java_client 1.x on [this commit](https://github.com/prometheus/client_java/commit/966360b2735fb975a7110699efd4cb62284dfc0b)

**Comment by wilkinsona** [comment]
Thanks for the report but this is out of Spring Boot's control. With a dependency on `With only `io.micrometer:micrometer-registry-prometheus:1.13.0` (and no Spring Boot dependencies), the following will fail in the way that you have described:

```java
package com.example.gh_41136;

import io.prometheus.metrics.core.metrics.Counter;

public class Gh41136Application {

	public static void main(String[] args) {
		Counter.builder().name("test_metric").build().inc();
	}

}
```

Please open a [Micrometer issue](https://github.com/micrometer-metrics/micrometer).

**Comment by mauriciogeneroso** [comment]
Thank you @wilkinsona . Reported: https://github.com/micrometer-metrics/micrometer/issues/5225
