### ISSUE TITLE
Inject AuthenticationManagerBuilder breaks (only) in tests

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#4123]
I have the following very simple `@SpringBootApplication`:

``` java
@SpringBootApplication
public class SampleApplication {

    public static void main(String[] args) {
        SpringApplication.run(SampleApplication.class, args);
    }


    @Autowired
    public void configureAuth(AuthenticationManagerBuilder auth) throws Exception {
        auth.inMemoryAuthentication()
                .withUser("user").password("user").roles("USER").and()
                .withUser("hero").password("hero").roles("USER", "HERO");
    }

}
```

and a dummy test

``` java
@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(classes = com.example.SampleApplication.class)
public class SampleApplicationTest {

    @Test
    public void load() {

    }
}
```

The application start properly (with the right authentication manager) but the test fails with the following exception:

```
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.security.config.annotation.authentication.builders.AuthenticationManagerBuilder] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:1326)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1072)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:967)
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:616)
    ... 46 more
```

Moving the `@Autowired` method to a static inner class breaks in both cases. Same thing if it's in a separate `@Configuration` class.

**Comment by snicoll** [comment]
I can't reproduce with 1.4
