### ISSUE TITLE
Periodic java.lang.NullPointerException when building bootRepackage task

### ISSUE THREAD

**Issue by bedge** [spring-projects/spring-boot#4144]
I haven't been able to isolate the condition, but after working for a while and doing repeated builds on a spring-boot project, I start getting these errors in the build:

```
:cmas:bootRepackage FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cmas:bootRepackage'.
> java.lang.NullPointerException (no error message)

....

Caused by: java.lang.NullPointerException
        at org.springframework.boot.loader.tools.DefaultLaunchScript.loadContent(DefaultLaunchScript.java:74)
        at org.springframework.boot.loader.tools.DefaultLaunchScript.loadContent(DefaultLaunchScript.java:62)
        at org.springframework.boot.loader.tools.DefaultLaunchScript.<init>(DefaultLaunchScript.java:56)
        at org.springframework.boot.gradle.repackage.RepackageTask$RepackageAction.getLaunchScript(RepackageTask.java:228)
        at org.springframework.boot.gradle.repackage.RepackageTask$RepackageAction.repackage(RepackageTask.java:180)
        at org.springframework.boot.gradle.repackage.RepackageTask$RepackageAction.execute(RepackageTask.java:145)
        at org.springframework.boot.gradle.repackage.RepackageTask$RepackageAction.execute(RepackageTask.java:120)
        at org.gradle.internal.Actions$FilteredAction.execute(Actions.java:202)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:110)
        at org.gradle.api.internal.DefaultDomainObjectCollection.withType(DefaultDomainObjectCollection.java:120)
        at org.springframework.boot.gradle.repackage.RepackageTask.repackage(RepackageTask.java:97)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 68 more
```

It looks like the DefaultLaunchScript.loadContent is returning a null InputStream for the launch.sript.

This is using 1.3.0.SNAPSHOT.

I am using init.d wrapper:
```
springBoot {
	executable = true
}
```

I'm using java 7:
```
%> java -version
java version "1.7.0_72"
Java(TM) SE Runtime Environment (build 1.7.0_72-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.72-b04, mixed mode)
```
but the same thing happens with java 8 as well.

This started happening recently. I just switched back to this project. It was building fine as of Oct 2. No changes on my end since then.

It's annoyingly random. For the first few builds it's fine, but then when it starts happening, it's consistent. 
No idea what's triggering it.

**Comment by wilkinsona** [comment]
Shot in the dark: your Gradle cache has been polluted with a corrupted download of `spring-boot-loader-tools`, i.e. it works until Gradle performs a new download that gets corrupted and then it stops working. Clearing out the cache and building again might help to confirm this theory.

**Comment by wilkinsona** [comment]
Closing due to lack of response. If this is still a problem, please let us know and we can re-open the issue.
