### ISSUE TITLE
java.lang.LinkageError: loader 'app' attempted duplicate class definition for jakarta.persistence.TemporalType

### ISSUE THREAD

**Issue by aiden-sim** [spring-projects/spring-boot#41559]
I am using the latest version of Spring Boot, with the following configuration:

```
Java 21 
Spring Boot 3.3.2 
VM options: -javaagent:/aspectjweaver-1.9.22.1.jar -javaagent:/spring-instrument-6.1.11.jar
```

However, when starting the application, the following error occurs. I suspect there might be a conflict with aspectjweaver, but I'm not sure of the exact cause. I need help.

```java
Caused by: java.lang.LinkageError: loader 'app' attempted duplicate class definition for jakarta.persistence.TemporalType. (jakarta.persistence.TemporalType is in unnamed module of loader 'app')
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at org.hibernate.type.descriptor.jdbc.TimestampUtcAsJdbcTimestampJdbcType.getJdbcLiteralFormatter(TimestampUtcAsJdbcTimestampJdbcType.java:77)
	at org.hibernate.type.AbstractStandardBasicType.<init>(AbstractStandardBasicType.java:65)
	at org.hibernate.type.AbstractSingleColumnStandardBasicType.<init>(AbstractSingleColumnStandardBasicType.java:27)
	at org.hibernate.type.internal.BasicTypeImpl.<init>(BasicTypeImpl.java:29)
	at org.hibernate.type.internal.NamedBasicTypeImpl.<init>(NamedBasicTypeImpl.java:20)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.adaptTimestampTypesToDefaultTimeZoneStorage(MetadataBuildingProcess.java:810)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.handleTypes(MetadataBuildingProcess.java:732)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:176)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1431)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1502)
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:75)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:390)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:366)
	... 34 common frames omitted
```

**Comment by wilkinsona** [comment]
This is due to a bug in Hibernate: https://hibernate.atlassian.net/browse/HHH-18108.
