### ISSUE TITLE
Spring Boot 3.4.0-M2 GraalVM with Flyway is failing with error at runtime

### ISSUE THREAD

**Issue by sivaprasadreddy** [spring-projects/spring-boot#42063]
Creating a simple Spring Boot app with 3.4.0-M2 version using Flyway and GraalVM support.
The native image build is successful, but when run the application it is throwing the following error:

```
Caused by: org.graalvm.nativeimage.MissingReflectionRegistrationError: The program tried to reflectively invoke method public boolean org.flywaydb.core.internal.publishing.PublishingConfigurationExtension.isPublishResult() without it being registered for runtime reflection. Add public boolean org.flywaydb.core.internal.publishing.PublishingConfigurationExtension.isPublishResult() to the reflection metadata to solve this problem. See https://www.graalvm.org/latest/reference-manual/native-image/metadata/#reflection for help.
at org.graalvm.nativeimage.builder/com.oracle.svm.core.reflect.MissingReflectionRegistrationUtils.forQueriedOnlyExecutable(MissingReflectionRegistrationUtils.java:72)
at java.base@21.0.3/java.lang.reflect.Method.acquireMethodAccessor(Method.java:77)
```

Here is a minimal reproducer: https://github.com/siva-attic/spring-boot-graalvm-flyway-issue

PS: The same application with Spring Boot 3.3.3 is working fine.

**Comment by mhalbritter** [comment]
This is related to https://github.com/oracle/graalvm-reachability-metadata/issues/424 and has to be fixed on the metadata side.
