### ISSUE TITLE
Springboot 3.2.4 : restTemplate.exchange throws exception "Premature end of chunk coded message body: closing chunk expected"

### ISSUE THREAD

**Issue by abhupadh** [spring-projects/spring-boot#42391]
Running with Spring Boot v3.2.4, Spring v6.1.5.

After upgrading Spring Boot 2.x -> 3.2.4, our integration test using `RestTemplate` is failing with the below errors when executed requests using `restTemplate.exchange(url, HttpMethod.POST, entity, responseType)` . 

```java
org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://localhost:61267/csm/v2/internal/pipeline/jUnit_pipeline_region_code/jUnit_topic": Premature end of chunk coded message body: closing chunk expected

	at org.springframework.web.client.RestTemplate.createResourceAccessException(RestTemplate.java:915)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:895)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:790)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:672)
	at org.springframework.boot.test.web.client.TestRestTemplate.exchange(TestRestTemplate.java:711)
	at com.adobe.csm.util.EndpointTest.postAndAcceptHal(EndpointTest.java:203)
	at com.adobe.csm.api.internal.PipelinePublishEndpointTest.testPostAcceptHal(PipelinePublishEndpointTest.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	.....
	.....
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
Caused by: org.apache.hc.core5.http.ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected
```

This is how the RestTemplate was configured and nothing has changed, still the upgrade is causing such issues

```java
MappingJackson2HttpMessageConverter messageConverter =
        new MappingJackson2HttpMessageConverter();
    messageConverter.setObjectMapper(new HALMapper());
    restTemplate
        .getRestTemplate()
        .getMessageConverters()
        .removeIf(
            httpMessageConverter ->
                httpMessageConverter instanceof MappingJackson2HttpMessageConverter);
                
restTemplate.getRestTemplate().getMessageConverters().add(messageConverter);
```

**Comment by philwebb** [comment]
The exception itself if coming from `org.apache.hc.core5.http.ConnectionClosedException` so it's possible that in the process of upgrading Spring Boot, the related upgrade of Apache HTTP Client is causing you issues. Unfortunately it's very hard to say what's causing the problem from the limited information in this report.

If you'd like us to spend some time investigating, please take the time to provide a complete minimal sample (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by abhupadh** [comment]
fixed it by explicitly setting `HttpHeaders.CONTENT_LENGTH, 0` in the `Response` header of the original resource endpoint being tested.

**Comment by davidcanos** [comment]
I'm having the same problem in my Spring Boot application
The communication between two services (the only to crowded services in my fleet) raise this exception every 15 or 20 minutes in production env only since 14th May. No upgrade was made and no relevant change in the codebase. 
It does not happen after any upgrade, it start to happen after 14th May,  I was using 3.3 for a long time then, and upgraded to 3.4 due to this issue, but it's still happening.
I have rechecked logs, before that day, i've detected it happened once every week, totally irrelevant.

The first issue i detected was a DecodeException due to a PREMATURE EOF.
After upgrading to Apache Http 5, I've noticed it's a premature end of chunk coded message: closing chunk expected.

It happens with a lot of different endpoints (no pattern detected), with empty or non empty responses, large or small.

I have tried to get more debug but it doesn't spark any idea on me. I'm stuck.
I have tried to reproduce in another environment creating traffic with scripts but it does not work.

The exception: 
```
feign.FeignException: Premature end of chunk coded message body: closing chunk expected reading GET https://xxxxxxxxx
        at feign.FeignException.errorReading(FeignException.java:186)
        at feign.InvocationContext.decode(InvocationContext.java:127)
        at feign.InvocationContext.proceed(InvocationContext.java:94)
        at feign.ResponseHandler.handleResponse(ResponseHandler.java:69)
        at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:109)
        at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:53)
        at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:104)
        at org.springframework.cloud.openfeign.FeignCachingInvocationHandlerFactory$1.proceed(FeignCachingInvocationHandlerFactory.java:66)
        at org.springframework.cache.interceptor.CacheInterceptor.lambda$invoke$0(CacheInterceptor.java:55)
        at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:431)
        at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:416)
        at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:65)
        at org.springframework.cloud.openfeign.FeignCachingInvocationHandlerFactory.lambda$create$1(FeignCachingInvocationHandlerFactory.java:53)
        at jdk.proxy2/jdk.proxy2.$Proxy97.xxxx(Unknown Source)
at cxxxxxxxxxxxxxx(zzzzzz.java:53)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:359)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.cache.interceptor.CacheInterceptor.lambda$invoke$0(CacheInterceptor.java:55)
        at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:431)
        at org.springframework.cache.interceptor.CacheAspectSupport.evaluate(CacheAspectSupport.java:601)
        at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:448)
        at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:410)
        at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:65)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:728)
        at xxxxxxxx$$SpringCGLIB$$0.myMethod(<generated>)
        at xxxxx(xxxxxx.java:123)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:258)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:191)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:986)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:891)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:195)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:114)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:116)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:398)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:903)
        at [org.apache.tomcat.util.net](http://org.apache.tomcat.util.net/).NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1740)
        at [org.apache.tomcat.util.net](http://org.apache.tomcat.util.net/).SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1189)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:658)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.apache.hc.core5.http.ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected
        at org.apache.hc.core5.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:264)
        at org.apache.hc.core5.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:223)
        at org.apache.hc.core5.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:184)
        at [org.apache.hc.core5.http.io](http://org.apache.hc.core5.http.io/).EofSensorInputStream.read(EofSensorInputStream.java:138)
        at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:264)
        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:175)
        at java.base/java.util.zip.GZIPInputStream.read(GZIPInputStream.java:128)
        at org.apache.hc.client5.http.entity.LazyDecompressingInputStream.read(LazyDecompressingInputStream.java:71)
        at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:350)
        at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:393)
        at java.base/sun.nio.cs.StreamDecoder.lockedRead(StreamDecoder.java:217)
        at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:171)
        at java.base/[java.io](http://java.io/).Reader.read(Reader.java:212)
        at java.base/java.io.InputStreamReader.read(InputStreamReader.java:168)
        at feign.Util.toString(Util.java:244)
        at com.mycustomdecoder.lambda$customDecoder$0(FeignDecoderConfig.java:30) <- i have used a custom decoder to try to debug
        at feign.InvocationContext.decode(InvocationContext.java:121)
        ... 80 more

```
