### ISSUE TITLE
Log4j 2.4 breaks rc1 devtools

### ISSUE THREAD

**Issue by peterdnight** [spring-projects/spring-boot#4279]
devtools does not seem to like the log4j2 2.4 (see exception below); I am able to workaround by adding `<log4j2.version>2.3</log4j2.version>`

to reproduce - sts-starter project with rc1 devtools, and log4j2 (see below). start the project - change the @SpringBootApplication, and get the failure. 

On @JmsListener - it appears log4j2 seems to stop emitting the logs after the restart by dev tools. This is both the 2.3 and 2.4 versions. Not sure if it is log4j2 or because i have add a `@Bean DefaultJmsListenerContainerFactory` . It does receive and process the message, just no logs.

```
2015-10-22 16:43:14,630 restartedMain ERROR No log4j2 configuration file found. Using default configuration: logging only errors to the console.
2015-10-22 16:43:14,635 restartedMain FATAL Unable to register shutdown hook because JVM is shutting down. java.lang.IllegalStateException: Cannot add new shutdown hook as this is not started. Current state: STOPPED
	at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry.addShutdownCallback(DefaultShutdownCallbackRegistry.java:113)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.addShutdownCallback(Log4jContextFactory.java:271)
	at org.apache.logging.log4j.core.LoggerContext.setUpShutdownHook(LoggerContext.java:256)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:216)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:233)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:41)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:170)
	at org.springframework.boot.logging.log4j2.Log4J2LoggingSystem.getLoggerContext(Log4J2LoggingSystem.java:215)
	at org.springframework.boot.logging.log4j2.Log4J2LoggingSystem.getRootLoggerConfig(Log4J2LoggingSystem.java:207)
	at org.springframework.boot.logging.log4j2.Log4J2LoggingSystem.beforeInitialize(Log4J2LoggingSystem.java:130)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationStartedEvent(LoggingApplicationListener.java:179)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:119)
	at org.springframework.boot.context.event.EventPublishingRunListener.publishEvent(EventPublishingRunListener.java:111)
	at org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:60)
	at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:48)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:293)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1085)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1074)
	at com.example.Z1Application.main(Z1Application.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)

```

	<dependencies>
	
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-log4j2</artifactId>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
		</dependency>
	</dependencies>

**Comment by wilkinsona** [comment]
When a restart is triggered, DevTools runs and then clears all registered shutdown hooks. One such hook is Log4J2's `DefaultShutdownCallbackRegistry`. `Log4jContextFactory` maintains a reference to the `DefaultShutdownCallbackRegistry` and `LogManager` holds a static reference to `Log4jContextFactory`. Log4J2's classes are loaded by the app classloader which means that there's a single `LogManager`, `Log4jContextFactory`, and `DefaultShutdownCallbackRegistry` shared across restarts.

When `DefaultShutdownCallbackRegistry` is run as part of a restart it stops the `LoggerContext` and sets its own state to `STOPPED`. As the restart proceeds a new `LoggerContext` is created and an attempt is made to register a shutdown callback for it with the registry. This fails as the registry's state is still `STOPPED`.

**Comment by wilkinsona** [comment]
The symptom changes a little across versions, but this problem also occurs with 2.0, 2.1, and 2.2 in addition to 2.3 and 2.4 that were reported above.

**Comment by wilkinsona** [comment]
This reflective hack resets the shutdown callback registry and gets it ready for use again:

```java
if (ClassUtils.isPresent("org.apache.logging.log4j.LogManager",
		getClass().getClassLoader())) {
	LoggerContextFactory factory = LogManager.getFactory();
	Field field = ReflectionUtils.findField(factory.getClass(),
			"shutdownCallbackRegistry");
	ReflectionUtils.makeAccessible(field);
	ShutdownCallbackRegistry shutdownCallbackRegistry = (ShutdownCallbackRegistry) ReflectionUtils
					.getField(field, factory);
	Field stateField = ReflectionUtils
			.findField(shutdownCallbackRegistry.getClass(), "state");
	ReflectionUtils.makeAccessible(stateField);
	@SuppressWarnings("unchecked")
	AtomicReference<State> state = (AtomicReference<State>) ReflectionUtils
			.getField(stateField, shutdownCallbackRegistry);
	state.set(State.INITIALIZED);
	Method start = ReflectionUtils.findMethod(shutdownCallbackRegistry.getClass(),
			"start");
	ReflectionUtils.invokeMethod(start, shutdownCallbackRegistry);
}
```

Unfortunately, it doesn't get the log output going again.

**Comment by wilkinsona** [comment]
Clearing out the callbacks in the registry before the Restarter runs the JVM's shutdown hooks is better. It prevents the exception from occurring, and logging continues to work after a restart.

```java
private void prepareLog4J2ForRestart() throws Exception {
	if (ClassUtils.isPresent("org.apache.logging.log4j.LogManager",
			getClass().getClassLoader())) {
		LoggerContextFactory factory = LogManager.getFactory();
		Field field = ReflectionUtils.findField(factory.getClass(),
				"shutdownCallbackRegistry");
		ReflectionUtils.makeAccessible(field);
		ShutdownCallbackRegistry shutdownCallbackRegistry = (ShutdownCallbackRegistry) ReflectionUtils
				.getField(field, factory);
		Field hooksField = ReflectionUtils
				.findField(shutdownCallbackRegistry.getClass(), "hooks");
		ReflectionUtils.makeAccessible(hooksField);
		@SuppressWarnings("unchecked")
		Collection<Cancellable> state = (Collection<Cancellable>) ReflectionUtils
				.getField(hooksField, shutdownCallbackRegistry);
		state.clear();
	}
}
```

**Comment by peterdnight** [comment]
many thanks for the investigation. Will this be in the next nightly - I am keen to verify that `@JmsListeners` will still log. Only they were failing to emit logs - `@RestControllers` would emit after the restart.

**Comment by wilkinsona** [comment]
> Will this be in the next nightly

No. I haven't committed any changes. I want to discuss it with the rest of the team first as it's a rather unpleasant hack.
