### ISSUE TITLE
GraalVM native image - Flyway prevents startups

### ISSUE THREAD

**Issue by Schaka** [spring-projects/spring-boot#42977]
Upon compiling a native image via Gradle's bootBuildImage task and starting it, I'm met with the following error in Spring-Boot 3.4.0_RC1

```
naviseerr  | 2024-11-02T18:30:28.944Z  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
naviseerr  | 2024-11-02T18:30:28.944Z  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 23 ms
naviseerr  | 2024-11-02T18:30:28.991Z  WARN 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'artistRepository': Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'flyway': Instantiation of supplied bean failed
naviseerr  | 2024-11-02T18:30:28.991Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
naviseerr  | Application run failed
naviseerr  | org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'artistRepository': Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'flyway': Instantiation of supplied bean failed
naviseerr  |    at org.springframework.beans.factory.aot.BeanInstanceSupplier.resolveAutowiredArgument(BeanInstanceSupplier.java:369)
naviseerr  |    at org.springframework.beans.factory.aot.BeanInstanceSupplier.resolveArguments(BeanInstanceSupplier.java:289)
naviseerr  |    at org.springframework.beans.factory.aot.BeanInstanceSupplier.get(BeanInstanceSupplier.java:223)
naviseerr  |    at org.springframework.beans.factory.support.DefaultListableBeanFactory.obtainInstanceFromSupplier(DefaultListableBeanFactory.java:979)
naviseerr  |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1233)
naviseerr  |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1176)
naviseerr  |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:563)
naviseerr  |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:523)
naviseerr  |    at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:336)
naviseerr  |    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:288)
naviseerr  |    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:334)
naviseerr  |    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
naviseerr  |    at org.springframework.beans.factory.support.DefaultListableBeanFactory.instantiateSingleton(DefaultListableBeanFactory.java:1122)
naviseerr  |    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingleton(DefaultListableBeanFactory.java:1093)
naviseerr  |    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:1030)
naviseerr  |    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:987)
naviseerr  |    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:627)
naviseerr  |    at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
naviseerr  |    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752)
naviseerr  |    at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:439)
naviseerr  |    at org.springframework.boot.SpringApplication.run(SpringApplication.java:318)
naviseerr  |    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1361)
naviseerr  |    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1350)
naviseerr  |    at com.github.schaka.naviseerr.NaviseerrApplicationKt.main(NaviseerrApplication.kt:49)
naviseerr  |    at java.base@23.0.1/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
naviseerr  | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flyway': Instantiation of supplied bean failed
naviseerr  |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1239)
naviseerr  |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1176)
naviseerr  |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:563)
naviseerr  |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:523)
naviseerr  |    at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:336)
naviseerr  |    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:288)
naviseerr  |    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:334)
naviseerr  |    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
naviseerr  |    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:312)
naviseerr  |    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
naviseerr  |    at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
naviseerr  |    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1626)
naviseerr  |    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1514)
naviseerr  |    at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:913)
naviseerr  |    at org.springframework.beans.factory.support.RegisteredBean.resolveAutowiredArgument(RegisteredBean.java:253)
naviseerr  |    at org.springframework.beans.factory.aot.BeanInstanceSupplier.resolveAutowiredArgument(BeanInstanceSupplier.java:366)
naviseerr  |    ... 24 more
naviseerr  | Caused by: org.flywaydb.core.api.FlywayException: No serializer found for class org.flywaydb.core.internal.configuration.extensions.DeployScriptFilenameConfigurationExtension and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)
naviseerr  |    at org.flywaydb.core.extensibility.ConfigurationExtension.copy(ConfigurationExtension.java:45)
naviseerr  |    at java.base@23.0.1/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
naviseerr  |    at java.base@23.0.1/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1709)
naviseerr  |    at java.base@23.0.1/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)
naviseerr  |    at java.base@23.0.1/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
naviseerr  |    at java.base@23.0.1/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:636)
naviseerr  |    at java.base@23.0.1/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:291)
naviseerr  |    at java.base@23.0.1/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:656)
naviseerr  |    at java.base@23.0.1/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:662)
naviseerr  |    at java.base@23.0.1/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:667)
naviseerr  |    at org.flywaydb.core.internal.plugin.PluginRegister.getCopy(PluginRegister.java:109)
naviseerr  |    at org.flywaydb.core.api.configuration.ClassicConfiguration.configure(ClassicConfiguration.java:1710)
naviseerr  |    at org.flywaydb.core.api.configuration.ClassicConfiguration.<init>(ClassicConfiguration.java:157)
naviseerr  |    at org.flywaydb.core.Flyway.<init>(Flyway.java:130)
naviseerr  |    at org.flywaydb.core.api.configuration.FluentConfiguration.load(FluentConfiguration.java:64)
naviseerr  |    at org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration.flyway(FlywayAutoConfiguration.java:179)
naviseerr  |    at org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration__BeanDefinitions$FlywayConfiguration.lambda$getFlywayInstanceSupplier$2(FlywayAutoConfiguration__BeanDefinitions.java:127)
naviseerr  |    at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:68)
naviseerr  |    at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:54)
naviseerr  |    at org.springframework.beans.factory.aot.BeanInstanceSupplier.lambda$get$2(BeanInstanceSupplier.java:225)
naviseerr  |    at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:58)
naviseerr  |    at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:46)
naviseerr  |    at org.springframework.beans.factory.aot.BeanInstanceSupplier.invokeBeanSupplier(BeanInstanceSupplier.java:258)
naviseerr  |    at org.springframework.beans.factory.aot.BeanInstanceSupplier.get(BeanInstanceSupplier.java:225)
naviseerr  |    at org.springframework.beans.factory.support.DefaultListableBeanFactory.obtainInstanceFromSupplier(DefaultListableBeanFactory.java:979)
naviseerr  |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1233)
naviseerr  |    ... 39 more
naviseerr  | Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.flywaydb.core.internal.configuration.extensions.DeployScriptFilenameConfigurationExtension and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)
naviseerr  |    at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1328)
naviseerr  |    at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:414)
naviseerr  |    at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:53)
naviseerr  |    at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:30)
naviseerr  |    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:502)
naviseerr  |    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:341)
naviseerr  |    at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4811)
naviseerr  |    at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:4052)
naviseerr  |    at org.flywaydb.core.extensibility.ConfigurationExtension.copy(ConfigurationExtension.java:42)
naviseerr  |    ... 64 more
naviseerr exited with code 1
```

It seems Quarkus was facing [a similar issue](https://github.com/quarkusio/quarkus/issues/39596) that was [resolved here](https://github.com/quarkusio/quarkus/pull/39597/files).

I am unsure if I missed something and should maybe downgrade Flyway manually in hopes of solving this problem.
It's a bit bigger than a mininum reproducible project, but you can look at the source code here: https://github.com/Schaka/naviseerr

**Comment by snicoll** [comment]
This isn't a Spring Boot concern but rather a reachability metadata concern. @mhalbritter already submitted a PR for this (see https://github.com/oracle/graalvm-reachability-metadata/pull/531) that got merged recently so you need to configure the native plugin to use reachability metadata version `0.3.11` (released 2 days ago) until we do that automatically.

**Comment by wilkinsona** [comment]
Unfortunately, with 0.3.11 of the metadata, you'll then be affected by the problem that https://github.com/oracle/graalvm-reachability-metadata/pull/556 fixes. You can fix it yourself with some manual metadata for `org.flywaydb.core.internal.logging.slf4j.Slf4jLogCreator`.

**Comment by Schaka** [comment]
Yeah, I noticed that and downgraded to Flyway 10.15 for now. That still works for now and I'll be upgrading the metadata once GraalVM merges the `LogCreator` PR as well.

**Comment by mefernandez** [comment]
@snicoll Would you please hint at how to configure the native plugin to use reachability metadata version 0.3.11 in mvn pom.xml that inherits spring-boot-starter-parent 3.4.0? I did not find docs to do this. Thank you.

**Comment by mhalbritter** [comment]
See this example here: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.4-Release-Notes#netty-in-native-image
