### ISSUE TITLE
nosuchelementexception in query while upgrading springboot from 3.2.11 to 3.3.0 and using h2 database

### ISSUE THREAD

**Issue by SwapnaAnchuri** [spring-projects/spring-boot#43031]
We are using h2 database and for one of the query validation failed and getting below error while upgrading spring boot from 3.2.11 to 3.3.0.

```
at app//org.hibernate.query.hql.internal.StandardHqlTranslator.translate(StandardHqlTranslator.java:95)
	at app//org.hibernate.query.internal.QueryInterpretationCacheStandardImpl.createHqlInterpretation(QueryInterpretationCacheStandardImpl.java:145)
	at app//org.hibernate.query.internal.QueryInterpretationCacheStandardImpl.resolveHqlInterpretation(QueryInterpretationCacheStandardImpl.java:132)
	at app//org.hibernate.internal.AbstractSharedSessionContract.interpretHql(AbstractSharedSessionContract.java:802)
	at app//org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:852)
	at app//org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:765)
	at app//org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:140)
	at jdk.internal.reflect.GeneratedMethodAccessor214.invoke(Unknown Source)
	at java.base@17.0.4/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.4/java.lang.reflect.Method.invoke(Method.java:568)
	at app//org.springframework.orm.jpa.ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.invoke(ExtendedEntityManagerCreator.java:364)
	at app/jdk.proxy3/jdk.proxy3.$Proxy225.createQuery(Unknown Source)
	at app//org.springframework.data.jpa.repository.query.SimpleJpaQuery.validateQuery(SimpleJpaQuery.java:94)
	... 140 more
Caused by: java.util.NoSuchElementException
	at org.hibernate.internal.util.collections.StandardStack.pop(StandardStack.java:60)
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.visitSelectStatement(SemanticQueryBuilder.java:493)
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.visitStatement(SemanticQueryBuilder.java:449)
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.buildSemanticModel(SemanticQueryBuilder.java:322)
	at org.hibernate.query.hql.internal.StandardHqlTranslator.translate(StandardHqlTranslator.java:71)
	... 152 more
```

Please let me know the solution to fix this issue

**Comment by wilkinsona** [comment]
Thanks for the report, but this looks like a Hibernate problem that is out of Spring Boot's control. Please try upgrading to the latest 3.3.x release (3.3.5) to pick up the latest Hibernate 6.5.x release. If the problem remains, you should open a Hibernate issue providing a minimal sample that reproduces the problem.

**Comment by SwapnaAnchuri** [comment]
@wilkinsona : This issue exists in 3.3.5 version also

**Comment by wilkinsona** [comment]
Then I would recommend that you open a Hibernate issue as I suggested above.
