### ISSUE TITLE
Sample for SSO with Github not working

### ISSUE THREAD

**Issue by sloppycoder** [spring-projects/spring-boot#4312]
(spring-boot-sample-web-secure-github)[https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples/spring-boot-sample-web-secure-github/] does not work.

after ```man spring-boot:run``` I use Chrome to view http://localhost:8080. The sends a 302 redirect to http://localhost:8080/login, then I got 500 with following error at the console:

```
2015-10-27 15:15:10.600  INFO 33463 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization completed in 13 ms
2015-10-27 15:15:10.673 ERROR 33463 --- [nio-8080-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet/DispatcherPortlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
	at org.springframework.web.context.request.RequestContextHolder.currentRequestAttributes(RequestContextHolder.java:131) ~[spring-web-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.web.context.request.SessionScope.get(SessionScope.java:91) ~[spring-web-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:339) ~[spring-beans-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	... 57 common frames omitted
```

I tried with latest snapshot and v1.3.0.RC1. Same result.

**Comment by wilkinsona** [comment]
Duplicates #4270
