### ISSUE TITLE
Issue After Spring Boot Upgrade: Error Resolving Template

### ISSUE THREAD

**Issue by githuailoveyou** [spring-projects/spring-boot#43155]
Background:
Spring Boot version upgrade from 2.3.10 to 3.2.3
Spring version upgrade from 5.2.14 to 6.1.4
Previously, the request URL was: 10.65.10.160:8070/job/?Action=GetJobList&AccountId=180000000. After upgrading the Spring Boot and Spring versions, the following error occurs when making the request:

`c.k.a.c.RequestLoggingFilter            :40 : {} After request [GET /job/?Action=GetJobList&AccountId=180000000, client=10.65.10.201, headers=[user-agent:"curl/7.29.0", host:"10.65.10.160:8070", x-ksc-request-id:"c-202411061150", x-ksc-account-id:"180000000", x-ksc-region:"cn-shanghai-2", x-ksc-account-email:"ksc_rd@kingsoft.com", accept:"application/json"]]
[http-nio-8070-exec-1] o.a.c.c.C.[.[.[.[dispatcherServlet]     : : {} Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.thymeleaf.exceptions.TemplateInputException: Error resolving template [job], template might not exist or might not be accessible by any of the configured Template Resolvers] with root cause
org.thymeleaf.exceptions.TemplateInputException: Error resolving template [job], template might not exist or might not be accessible by any of the configured Template Resolvers
        at org.thymeleaf.engine.TemplateManager.resolveTemplate(TemplateManager.java:869) ~[thymeleaf-3.1.2.RELEASE.jar!/:3.1.2.RELEASE]
        at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:607) ~[thymeleaf-3.1.2.RELEASE.jar!/:3.1.2.RELEASE]
        at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103) ~[thymeleaf-3.1.2.RELEASE.jar!/:3.1.2.RELEASE]
        at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1077) ~[thymeleaf-3.1.2.RELEASE.jar!/:3.1.2.RELEASE]
        at org.thymeleaf.spring6.view.ThymeleafView.renderFragment(ThymeleafView.java:372) ~[thymeleaf-spring6-3.1.2.RELEASE.jar!/:3.1.2.RELEASE]
        at org.thymeleaf.spring6.view.ThymeleafView.render(ThymeleafView.java:192) ~[thymeleaf-spring6-3.1.2.RELEASE.jar!/:3.1.2.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1431) ~[spring-webmvc-6.1.4.jar!/:6.1.4]
        at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1167) ~[spring-webmvc-6.1.4.jar!/:6.1.4]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1106) ~[spring-webmvc-6.1.4.jar!/:6.1.4]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979) ~[spring-webmvc-6.1.4.jar!/:6.1.4]
`

code：
```
@RequestMapping(value = "/job", produces = {MediaType.APPLICATION_JSON_VALUE})
public class ScheduleJobController {

@RequestMapping(params = "Action=GetJobList")
    public Map<String, Object> getJobList() {
        // method implementation
    }
}
}
```

**Comment by githuailoveyou** [comment]
This issue did not occur before the Spring Boot and Spring upgrade.

**Comment by githuailoveyou** [comment]
no ok
10.65.10.160:8070/job/?Action=GetJobList&AccountId=180000000 

ok
10.65.10.160:8070/job?Action=GetJobList&AccountId=180000000

**Comment by philwebb** [comment]
Please read the release notes and the migration guide, specifically [this section](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#spring-mvc-and-webflux-url-matching-changes)

**Comment by githuailoveyou** [comment]
thank you  you great
