### ISSUE TITLE
Spring Boot 1.3 applications fail to deploy to Payara

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#4321]
Looks like an annotation issue again. 1.2.7 works fine, 1.3.0.M1+ all fail

```
 Error occurred during deployment: Exception while loading the app : java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: java.lang.RuntimeException: com.sun.faces.config.ConfigurationException: CONFIGURATION FAILED! java.util.concurrent.ExecutionException: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy. Please see server.log for more details. 
```

**Comment by wilkinsona** [comment]
The problem's caused by `com.sun.faces.config.FacesInitializer` which is a `ServletContainerInitializer`. It's annotated with `@HandleTypes` to indicate that it handles `@Resource` (among others). I thought that `@HandlesTypes` only applied to type-level annotations, but that's not the case. From the Servlet spec:

> The HandlesTypes annotation on the implementation of the ServletContainerInitializer is used to express interest in classes that may have annotations (type, method or field level annotations) specified in the value of the HandlesTypes or if it extends / implements one those classes anywhere in the class’ super types

The `accessTokenRequest` field on `OAuth2RestOperationsConfiguration.SessionScopedConfiguration` is annotated with `@Resource` which causes it to be passed to `FacesInitializer`. This ultimately leads to `com.sun.faces.config.DelegatingAnnotationProvider`calling `getAnnotations` on the class for `OAuth2RestOperationsConfiguration.SessionScopedConfiguration`. `SessionScopedConfiguration` is annotated with `@ConditionalOnBean(OAuth2ClientConfiguration.class)`. `OAuth2ClientConfiguration` isn't on the classpath which results in the `getAnnotations` call blowing up:

```
java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724) ~[na:1.8.0_60]
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531) ~[na:1.8.0_60]
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355) ~[na:1.8.0_60]
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286) ~[na:1.8.0_60]
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120) ~[na:1.8.0_60]
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72) ~[na:1.8.0_60]
	at java.lang.Class.createAnnotationData(Class.java:3521) ~[na:1.8.0_60]
	at java.lang.Class.annotationData(Class.java:3510) ~[na:1.8.0_60]
	at java.lang.Class.getAnnotations(Class.java:3446) ~[na:1.8.0_60]
	at com.sun.faces.config.DelegatingAnnotationProvider.createAnnotatedMap(DelegatingAnnotationProvider.java:127) ~[payara-micro-4.1.1.154.jar:na]
	at com.sun.faces.config.DelegatingAnnotationProvider.getAnnotatedClasses(DelegatingAnnotationProvider.java:89) ~[payara-micro-4.1.1.154.jar:na]
	at com.sun.faces.config.ConfigManager$AnnotationScanTask.call(ConfigManager.java:967) ~[payara-micro-4.1.1.154.jar:na]
	at com.sun.faces.config.ConfigManager$AnnotationScanTask.call(ConfigManager.java:918) ~[payara-micro-4.1.1.154.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_60]
	at com.sun.faces.config.ConfigManager.initialize(ConfigManager.java:387) ~[payara-micro-4.1.1.154.jar:na]
	... 35 common frames omitted
```

This is a similar problem to [GLASSFISH-21265](https://java.net/jira/browse/GLASSFISH-21265) which made `AnnotationProcessorImpl` more robust. It looks like `DelegatingAnnotationProvider` needs similar treatment.

**Comment by philwebb** [comment]
Thank you Andy. You rock!
