### ISSUE TITLE
Spring Batch applications fail to start when a custom JobRepository bean is defined

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#43236]
Sample at https://github.com/joshlong-attic/2024-11-20-batch-job-repository

**Comment by philwebb** [comment]
This bug exists in earlier versions, but given it's mostly going to be triggered by the new `MongoJobRepositoryFactoryBean` I think we should keep the target to 3.4

**Comment by philwebb** [comment]
The sample now appears to start if:

```xml
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-batch</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-jdbc</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```

and 

```java
	@Bean
	MongoTransactionManager mongoTransactionManager(MongoDatabaseFactory dbf) {
		return new MongoTransactionManager(dbf);
	}
```

**Comment by philwebb** [comment]
@mbhave pointed out that `BatchAutoConfiguration` depends on `DataSource` so it may back off entirely with the `pring-boot-starter-jdbc` exclusion. We probably need a more complete fix for Mongo support.

That might need to wait until 3.5, in which case we could revert my "fix" in 3.4

**Comment by wilkinsona** [comment]
Chatting with @fmbenhassine, this may need to wait for Spring Boot 4.0/Spring Batch 6.0 to allow some breaking changes to be made, such as `DefaultBatchConfiguration` losing its `DataSource` assumptions.

**Comment by snicoll** [comment]
> The sample now appears to start if:

That's essentially disabling the auto-configuration. The app starts but the Job doesn't. I was curious to see how that would work since some collections need to be created for the sample to work...

**Comment by snicoll** [comment]
So we haven't made much progress on the sample above. If we want to make progress, we need feedback on https://github.com/spring-projects/spring-batch/issues/5328. 

A bonus would be to see a path forward with regards to shared configuration. This is discussed in https://github.com/spring-projects/spring-batch/issues/4962#issuecomment-4038044449

**Comment by fmbenhassine** [comment]
> So we haven't made much progress on the sample above. If we want to make progress, we need feedback on https://github.com/spring-projects/spring-batch/issues/5328.

Feedback provided. The idempotency of the scripts is nice to have, but not blocking IMO (the JDBC scripts are not idempotent neither, we have an open feature request for that). So I believe Boot can use the same approach as JDBC with the drop/create schemas provided by Spring Batch for MongoDB.

> A bonus would be to see a path forward with regards to shared configuration. This is discussed in https://github.com/spring-projects/spring-batch/issues/4962#issuecomment-4038044449

No problem, I will reconsider this for Batch 6.1.

**Comment by snicoll** [comment]
Two more things:

1. I don't know why but I have to enable `.replicatSet` in a unit test with testcontainers or it fail as follows:
```

org.springframework.dao.InvalidDataAccessApiUsageException: Command execution failed on MongoDB server with error 20 (IllegalOperation): 'Transaction numbers are only allowed on a replica set member or mongos' on server localhost:62738. The full response is {"ok": 0.0, "errmsg": "Transaction numbers are only allowed on a replica set member or mongos", "code": 20, "codeName": "IllegalOperation"}

    at org.springframework.data.mongodb.core.MongoExceptionTranslator.doTranslateException(MongoExceptionTranslator.java:139)
    at org.springframework.data.mongodb.core.MongoExceptionTranslator.translateExceptionIfPossible(MongoExceptionTranslator.java:74)
    at org.springframework.data.mongodb.core.MongoTemplate.potentiallyConvertRuntimeException(MongoTemplate.java:3202)
    at org.springframework.data.mongodb.core.MongoTemplate.executeFindOneInternal(MongoTemplate.java:3071)
    at org.springframework.data.mongodb.core.MongoTemplate.doFindOne(MongoTemplate.java:2710)
    at org.springframework.data.mongodb.core.MongoTemplate.findOne(MongoTemplate.java:896)
    at org.springframework.batch.core.repository.dao.mongodb.MongoJobInstanceDao.getJobInstance(MongoJobInstanceDao.java:96)
    at org.springframework.batch.core.repository.explore.support.SimpleJobExplorer.getJobInstance(SimpleJobExplorer.java:132)
    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    at java.base/java.lang.reflect.Method.invoke(Method.java:565)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:359)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:158)
    at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:133)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:371)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:130)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:222)
    at jdk.proxy1/jdk.proxy1.$Proxy65.getJobInstance(Unknown Source)
    at org.springframework.batch.core.launch.support.TaskExecutorJobLauncher.createJobExecution(TaskExecutorJobLauncher.java:117)
    at org.springframework.batch.core.launch.support.TaskExecutorJobLauncher.run(TaskExecutorJobLauncher.java:108)
    at org.springframework.batch.core.launch.support.SimpleJobOperator.start(SimpleJobOperator.java:201)
    at org.springframework.batch.core.launch.support.TaskExecutorJobOperator.start(TaskExecutorJobOperator.java:117)
    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    at java.base/java.lang.reflect.Method.invoke(Method.java:565)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:359)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:158)
    at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:133)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:371)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:130)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:222)
    at jdk.proxy1/jdk.proxy1.$Proxy67.start(Unknown Source)
    at org.springframework.boot.batch.autoconfigure.JobLauncherApplicationRunner.execute(JobLauncherApplicationRunner.java:190)
    at org.springframework.boot.batch.autoconfigure.JobLauncherApplicationRunner.executeLocalJobs(JobLauncherApplicationRunner.java:174)
    at org.springframework.boot.batch.autoconfigure.JobLauncherApplicationRunner.launchJobFromProperties(JobLauncherApplicationRunner.java:154)
    at org.springframework.boot.batch.autoconfigure.JobLauncherApplicationRunner.run(JobLauncherApplicationRunner.java:149)
    at org.springframework.boot.batch.autoconfigure.JobLauncherApplicationRunner.run(JobLauncherApplicationRunner.java:143)
    at org.springframework.boot.batch.mongodb.autoconfigure.BatchDataMongoAutoConfigurationIntegrationTests.lambda$testDefinesAndLaunchesLocalJob$0(BatchDataMongoAutoConfigurationIntegrationTests.java:80)
    at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.accept(AbstractApplicationContextRunner.java:457)
    at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.consumeAssertableContext(AbstractApplicationContextRunner.java:371)
    at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.lambda$run$1(AbstractApplicationContextRunner.java:349)
    at org.springframework.boot.test.util.TestPropertyValues.lambda$applyToSystemProperties$0(TestPropertyValues.java:176)
    at org.springframework.boot.test.util.TestPropertyValues.applyToSystemProperties(TestPropertyValues.java:190)
    at org.springframework.boot.test.util.TestPropertyValues.applyToSystemProperties(TestPropertyValues.java:175)
    at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.lambda$run$0(AbstractApplicationContextRunner.java:349)
    at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.withContextClassLoader(AbstractApplicationContextRunner.java:377)
    at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.run(AbstractApplicationContextRunner.java:348)
    at org.springframework.boot.batch.mongodb.autoconfigure.BatchDataMongoAutoConfigurationIntegrationTests.testDefinesAndLaunchesLocalJob(BatchDataMongoAutoConfigurationIntegrationTests.java:78)
Caused by: com.mongodb.MongoQueryException: Command execution failed on MongoDB server with error 20 (IllegalOperation): 'Transaction numbers are only allowed on a replica set member or mongos' on server localhost:62738. The full response is {"ok": 0.0, "errmsg": "Transaction numbers are only allowed on a replica set member or mongos", "code": 20, "codeName": "IllegalOperation"}
    at com.mongodb.internal.operation.FindOperation.lambda$execute$1(FindOperation.java:312)
    at com.mongodb.internal.operation.SyncOperationHelper.lambda$withSourceAndConnection$1(SyncOperationHelper.java:145)
    at com.mongodb.internal.operation.SyncOperationHelper.withSuppliedResource(SyncOperationHelper.java:176)
    at com.mongodb.internal.operation.SyncOperationHelper.lambda$withSourceAndConnection$2(SyncOperationHelper.java:141)
    at com.mongodb.internal.operation.SyncOperationHelper.withSuppliedResource(SyncOperationHelper.java:176)
    at com.mongodb.internal.operation.SyncOperationHelper.withSourceAndConnection(SyncOperationHelper.java:137)
    at com.mongodb.internal.operation.FindOperation.lambda$execute$2(FindOperation.java:304)
    at com.mongodb.internal.operation.SyncOperationHelper.lambda$decorateReadWithRetries$14(SyncOperationHelper.java:337)
    at com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:67)
    at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:316)
    at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:70)
    at com.mongodb.client.internal.MongoClusterImpl$OperationExecutorImpl.execute(MongoClusterImpl.java:436)
    at com.mongodb.client.internal.FindIterableImpl.first(FindIterableImpl.java:210)
    at org.springframework.data.mongodb.core.MongoTemplate$FindOneCallback.doInCollection(MongoTemplate.java:3242)
    at org.springframework.data.mongodb.core.MongoTemplate$FindOneCallback.doInCollection(MongoTemplate.java:3216)
    at org.springframework.data.mongodb.core.MongoTemplate.executeFindOneInternal(MongoTemplate.java:3068)
    ... 46 more
```

2. I missed that `MongoTemplate` has to be configured in [a specific way](https://github.com/spring-projects/spring-batch/blob/258da33c2933cea1650ea61fb4703c4b75418eec/spring-batch-core/src/main/java/org/springframework/batch/core/repository/support/MongoJobRepositoryFactoryBean.java#L32-L37). That's quite unfortunate as it means we can't reuse the `MongoTemplate` our auto-configuration has produced.

**Comment by snicoll** [comment]
> I believe Boot can use the same approach as JDBC with the drop/create schemas provided by Spring Batch for MongoDB.

We have support for the embedded mode which is the sweet spot I was trying to talk about. If you run with an embedded database, then create the tables. With Mongo we're left with do it or don't do it. I agree it's not blocking but it's not the same situation as JDBC.
