### ISSUE TITLE
Spring Boot 3.4.0 Native Image fails on Netty netty-common-4.1.115. java.lang.NoSuchFieldException: producerIndex

### ISSUE THREAD

**Issue by rowi1de** [spring-projects/spring-boot#43273]
Using Spring Boot 3.4.0 Native Image fails on Netty netty-common-4.1.115. `java.lang.NoSuchFieldException: producerIndex`
See https://github.com/rowi1de/netty-native

```shell
2024-11-23 01:03:57 2024-11-23T00:03:57.949Z ERROR 1 --- [netty-native] [ctor-http-nio-2] r.netty.transport.ServerTransport        : [71e5e572, L:/172.18.0.4:8080 - R:/192.168.65.1:29377] onUncaughtException(SimpleConnection{channel=[id: 0x71e5e572, L:/172.18.0.4:8080 - R:/192.168.65.1:29377]})
2024-11-23 01:03:57 
2024-11-23 01:03:57 java.lang.ExceptionInInitializerError: null
2024-11-23 01:03:57     at java.base@21.0.5/java.lang.Class.ensureInitialized(DynamicHub.java:604) ~[netty.graalvm.NettyNativeApiApplicationKt:na]
2024-11-23 01:03:57     at java.base@21.0.5/java.lang.Class.ensureInitialized(DynamicHub.java:604) ~[netty.graalvm.NettyNativeApiApplicationKt:na]
2024-11-23 01:03:57     at java.base@21.0.5/java.lang.Class.ensureInitialized(DynamicHub.java:604) ~[netty.graalvm.NettyNativeApiApplicationKt:na]
2024-11-23 01:03:57     at java.base@21.0.5/java.lang.Class.ensureInitialized(DynamicHub.java:604) ~[netty.graalvm.NettyNativeApiApplicationKt:na]
2024-11-23 01:03:57     at java.base@21.0.5/java.lang.Class.ensureInitialized(DynamicHub.java:604) ~[netty.graalvm.NettyNativeApiApplicationKt:na]
2024-11-23 01:03:57     at java.base@21.0.5/java.lang.Class.ensureInitialized(DynamicHub.java:604) ~[netty.graalvm.NettyNativeApiApplicationKt:na]
2024-11-23 01:03:57     at io.netty.util.internal.PlatformDependent.newFixedMpscUnpaddedQueue(PlatformDependent.java:1102) ~[na:na]
2024-11-23 01:03:57     at io.netty.buffer.PoolThreadCache$MemoryRegionCache.<init>(PoolThreadCache.java:337) ~[netty.graalvm.NettyNativeApiApplicationKt:4.1.115.Final]
2024-11-23 01:03:57     at io.netty.buffer.PoolThreadCache$SubPageMemoryRegionCache.<init>(PoolThreadCache.java:302) ~[na:na]
2024-11-23 01:03:57     at io.netty.buffer.PoolThreadCache.createSubPageCaches(PoolThreadCache.java:113) ~[netty.graalvm.NettyNativeApiApplicationKt:4.1.115.Final]
2024-11-23 01:03:57     at io.netty.buffer.PoolThreadCache.<init>(PoolThreadCache.java:77) ~[netty.graalvm.NettyNativeApiApplicationKt:4.1.115.Final]
2024-11-23 01:03:57     at io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.initialValue(PooledByteBufAllocator.java:541) ~[na:na]
2024-11-23 01:03:57     at io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.initialValue(PooledByteBufAllocator.java:518) ~[na:na]
2024-11-23 01:03:57     at io.netty.util.concurrent.FastThreadLocal.initialize(FastThreadLocal.java:177) ~[netty.graalvm.NettyNativeApiApplicationKt:4.1.115.Final]
2024-11-23 01:03:57     at io.netty.util.concurrent.FastThreadLocal.get(FastThreadLocal.java:142) ~[netty.graalvm.NettyNativeApiApplicationKt:4.1.115.Final]
2024-11-23 01:03:57     at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:398) ~[na:na]
2024-11-23 01:03:57     at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188) ~[netty.graalvm.NettyNativeApiApplicationKt:4.1.115.Final]
2024-11-23 01:03:57     at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179) ~[netty.graalvm.NettyNativeApiApplicationKt:4.1.115.Final]
2024-11-23 01:03:57     at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:140) ~[netty.graalvm.NettyNativeApiApplicationKt:4.1.115.Final]
2024-11-23 01:03:57     at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:120) ~[netty.graalvm.NettyNativeApiApplicationKt:4.1.115.Final]
2024-11-23 01:03:57     at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:150) ~[netty.graalvm.NettyNativeApiApplicationKt:4.1.115.Final]
2024-11-23 01:03:57     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[na:na]
2024-11-23 01:03:57     at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[na:na]
2024-11-23 01:03:57     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[na:na]
2024-11-23 01:03:57     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[na:na]
2024-11-23 01:03:57     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[na:na]
2024-11-23 01:03:57     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[na:na]
2024-11-23 01:03:57     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[na:na]
2024-11-23 01:03:57     at java.base@21.0.5/java.lang.Thread.runWith(Thread.java:1596) ~[netty.graalvm.NettyNativeApiApplicationKt:na]
2024-11-23 01:03:57     at java.base@21.0.5/java.lang.Thread.run(Thread.java:1583) ~[netty.graalvm.NettyNativeApiApplicationKt:na]
2024-11-23 01:03:57     at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:902) ~[netty.graalvm.NettyNativeApiApplicationKt:na]
2024-11-23 01:03:57     at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:878) ~[netty.graalvm.NettyNativeApiApplicationKt:na]
2024-11-23 01:03:57 Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: producerIndex
2024-11-23 01:03:57     at io.netty.util.internal.shaded.org.jctools.util.UnsafeAccess.fieldOffset(UnsafeAccess.java:111) ~[na:na]
2024-11-23 01:03:57     at io.netty.util.internal.shaded.org.jctools.queues.unpadded.MpscUnpaddedArrayQueueProducerIndexField.<clinit>(MpscUnpaddedArrayQueue.java:38) ~[netty.graalvm.NettyNativeApiApplicationKt:4.1.115.Final]
2024-11-23 01:03:57     ... 32 common frames omitted
2024-11-23 01:03:57 Caused by: java.lang.NoSuchFieldException: producerIndex
2024-11-23 01:03:57     at java.base@21.0.5/java.lang.Class.checkField(DynamicHub.java:1044) ~[netty.graalvm.NettyNativeApiApplicationKt:na]
2024-11-23 01:03:57     at java.base@21.0.5/java.lang.Class.getDeclaredField(DynamicHub.java:1159) ~[netty.graalvm.NettyNativeApiApplicationKt:na]
2024-11-23 01:03:57     at io.netty.util.internal.shaded.org.jctools.util.UnsafeAccess.fieldOffset(UnsafeAccess.java:107) ~[na:na]
2024-11-23 01:03:57     ... 33 common frames omitted
2024-11-23 01:03:57 
```

**Comment by snicoll** [comment]
Thanks for trying the latest release. Before opening an issue, please review the [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.4-Release-Notes). There is [a section](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.4-Release-Notes#netty-in-native-image) about that particular issue.

**Comment by rowi1de** [comment]
> Thanks for trying the latest release. Before opening an issue, please review the [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.4-Release-Notes). There is [a section](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.4-Release-Notes#netty-in-native-image) about that particular issue.

@snicoll thanks for the hint, usually spring boot starters just work out of the box, will try this

**Comment by bclozel** [comment]
@rowi1de it was either shipping with this Netty version or shipping with the one before and then: https://github.com/netty/netty/security/advisories/GHSA-xq3w-v528-46rv

**Comment by snicoll** [comment]
Please take the time to read the issue. Adding +1 on a closed issue like that is pointless.

**Comment by pbilstein** [comment]
I read the issue and just wanted to give people a hint if they encounter similar issues. Never mind

**Comment by slowbreathing** [comment]
Hi @rowi1de , is there a work around for this problem. Thanks in advance.

**Comment by bclozel** [comment]
@slowbreathing you should use the latest Spring Boot 3.4.x which depends on Netty 4.1.118.Final. If not, please check your dependencies.

**Comment by slowbreathing** [comment]
I am using Spring boot 3.4.3 and from the dependencies i see that it uses  Netty 4.1.118.Final.

Let me know if should past the dependecies as well.

Trace is below.

-mongodb:27017] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server mongodb:27017
integrate-11-patient-1  | 
integrate-11-patient-1  | com.mongodb.MongoInternalException: Exception thrown from Netty Stream
integrate-11-patient-1  | 	at com.mongodb.internal.connection.netty.NettyStream$FutureAsyncCompletionHandler.get(NettyStream.java:494) ~[na:na]
integrate-11-patient-1  | 	at com.mongodb.internal.connection.netty.NettyStream.read(NettyStream.java:239) ~[na:na]
integrate-11-patient-1  | 	at com.mongodb.internal.connection.InternalStreamConnection.receiveResponseBuffers(InternalStreamConnection.java:829) ~[na:na]
integrate-11-patient-1  | 	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:517) ~[na:na]
integrate-11-patient-1  | 	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceiveInternal(InternalStreamConnection.java:448) ~[na:na]
integrate-11-patient-1  | 	at com.mongodb.internal.connection.InternalStreamConnection.lambda$sendAndReceive$0(InternalStreamConnection.java:375) ~[na:na]
integrate-11-patient-1  | 	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:378) ~[na:na]
integrate-11-patient-1  | 	at com.mongodb.internal.connection.CommandHelper.sendAndReceive(CommandHelper.java:100) ~[na:na]
integrate-11-patient-1  | 	at com.mongodb.internal.connection.CommandHelper.executeCommand(CommandHelper.java:49) ~[na:na]
integrate-11-patient-1  | 	at com.mongodb.internal.connection.InternalStreamConnectionInitializer.initializeConnectionDescription(InternalStreamConnectionInitializer.java:144) ~[na:na]
integrate-11-patient-1  | 	at com.mongodb.internal.connection.InternalStreamConnectionInitializer.startHandshake(InternalStreamConnectionInitializer.java:79) ~[na:na]
integrate-11-patient-1  | 	at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:235) ~[na:na]
integrate-11-patient-1  | 	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitor.lookupServerDescription(DefaultServerMonitor.java:219) ~[na:na]
integrate-11-patient-1  | 	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitor.run(DefaultServerMonitor.java:176) ~[na:na]
integrate-11-patient-1  | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:838) ~[com.stillwaters.medconnect.microservices.core.patient.PatientServiceApplication:na]
integrate-11-patient-1  | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211) ~[na:na]
integrate-11-patient-1  | Caused by: java.lang.ExceptionInInitializerError: null
integrate-11-patient-1  | 	at java.base@17.0.10/java.lang.Class.ensureInitialized(DynamicHub.java:579) ~[com.stillwaters.medconnect.microservices.core.patient.PatientServiceApplication:na]
integrate-11-patient-1  | 	at java.base@17.0.10/java.lang.Class.ensureInitialized(DynamicHub.java:579) ~[com.stillwaters.medconnect.microservices.core.patient.PatientServiceApplication:na]
integrate-11-patient-1  | 	at java.base@17.0.10/java.lang.Class.ensureInitialized(DynamicHub.java:579) ~[com.stillwaters.medconnect.microservices.core.patient.PatientServiceApplication:na]
integrate-11-patient-1  | 	at java.base@17.0.10/java.lang.Class.ensureInitialized(DynamicHub.java:579) ~[com.stillwaters.medconnect.microservices.core.patient.PatientServiceApplication:na]
integrate-11-patient-1  | 	at java.base@17.0.10/java.lang.Class.ensureInitialized(DynamicHub.java:579) ~[com.stillwaters.medconnect.microservices.core.patient.PatientServiceApplication:na]
integrate-11-patient-1  | 	at java.base@17.0.10/java.lang.Class.ensureInitialized(DynamicHub.java:579) ~[com.stillwaters.medconnect.microservices.core.patient.PatientServiceApplication:na]
integrate-11-patient-1  | 	at io.netty.util.internal.PlatformDependent.newFixedMpscUnpaddedQueue(PlatformDependent.java:1102) ~[na:na]
integrate-11-patient-1  | 	at io.netty.buffer.PoolThreadCache$MemoryRegionCache.<init>(PoolThreadCache.java:337) ~[com.stillwaters.medconnect.microservices.core.patient.PatientServiceApplication:4.1.118.Final]
integrate-11-patient-1  | 	at io.netty.buffer.PoolThreadCache$SubPageMemoryRegionCache.<init>(PoolThreadCache.java:302) ~[na:na]
integrate-11-patient-1  | 	at io.netty.buffer.PoolThreadCache.createSubPageCaches(PoolThreadCache.java:113) ~[com.stillwaters.medconnect.microservices.core.patient.PatientServiceApplication:4.1.118.Final]
integrate-11-patient-1  | 	at io.netty.buffer.PoolThreadCache.<init>(PoolThreadCache.java:77) ~[com.stillwaters.medconnect.microservices.core.patient.PatientServiceApplication:4.1.118.Final]
integrate-11-patient-1  | 	at io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.initialValue(PooledByteBufAllocator.java:541) ~[na:na]
integrate-11-patient-1  | 	at io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.initialValue(PooledByteBufAllocator.java:518) ~[na:na]
integrate-11-patient-1  | 	at io.netty.util.concurrent.FastThreadLocal.initialize(FastThreadLocal.java:177) ~[com.stillwaters.medconnect.microservices.core.patient.PatientServiceApplication:4.1.118.Final]
integrate-11-patient-1  | 	at io.netty.util.concurrent.FastThreadLocal.get(FastThreadLocal.java:142) ~[com.stillwaters.medconnect.microservices.core.patient.PatientServiceApplication:4.1.118.Final]
integrate-11-patient-1  | 	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:398) ~[na:na]
integrate-11-patient-1  | 	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188) ~[com.stillwaters.medconnect.microservices.core.patient.PatientServiceApplication:4.1.118.Final]
integrate-11-patient-1  | 	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179) ~[com.stillwaters.medconnect.microservices.core.patient.PatientServiceApplication:4.1.118.Final]
integrate-11-patient-1  | 	at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:140) ~[com.stillwaters.medconnect.microservices.core.patient.PatientServiceApplication:4.1.118.Final]
integrate-11-patient-1  | 	at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:120) ~[com.stillwaters.medconnect.microservices.core.patient.PatientServiceApplication:4.1.118.Final]
integrate-11-patient-1  | 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:150) ~[com.stillwaters.medconnect.microservices.core.patient.PatientServiceApplication:4.1.118.Final]
integrate-11-patient-1  | 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:796) ~[na:na]
integrate-11-patient-1  | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:732) ~[na:na]
integrate-11-patient-1  | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:658) ~[na:na]
integrate-11-patient-1  | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[na:na]
integrate-11-patient-1  | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998) ~[na:na]
integrate-11-patient-1  | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[na:na]
integrate-11-patient-1  | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[na:na]
integrate-11-patient-1  | 	at java.base@17.0.10/java.lang.Thread.run(Thread.java:840) ~[com.stillwaters.medconnect.microservices.core.patient.PatientServiceApplication:na]
integrate-11-patient-1  | 	... 2 common frames omitted
integrate-11-patient-1  | Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: producerIndex
integrate-11-patient-1  | 	at io.netty.util.internal.shaded.org.jctools.util.UnsafeAccess.fieldOffset(UnsafeAccess.java:111) ~[na:na]
integrate-11-patient-1  | 	at io.netty.util.internal.shaded.org.jctools.queues.unpadded.MpscUnpaddedArrayQueueProducerIndexField.<clinit>(MpscUnpaddedArrayQueue.java:38) ~[com.stillwaters.medconnect.microservices.core.patient.PatientServiceApplication:4.1.118.Final]
integrate-11-patient-1  | 	... 31 common frames omitted
integrate-11-patient-1  | Caused by: java.lang.NoSuchFieldException: producerIndex
integrate-11-patient-1  | 	at java.base@17.0.10/java.lang.Class.checkField(DynamicHub.java:1006) ~[com.stillwaters.medconnect.microservices.core.patient.PatientServiceApplication:na]
integrate-11-patient-1  | 	at java.base@17.0.10/java.lang.Class.getDeclaredField(DynamicHub.java:1121) ~[com.stillwaters.medconnect.microservices.core.patient.PatientServiceApplication:na]
integrate-11-patient-1  | 	at io.netty.util.internal.shaded.org.jctools.util.UnsafeAccess.fieldOffset(UnsafeAccess.java:107) ~[na:na]
integrate-11-patient-1  | 	... 32 common frames omitted
integrate-11-patient-1  |
