### ISSUE TITLE
Unable to find a @SpringBootConfiguration results in misleading error message

### ISSUE THREAD

**Issue by quaff** [spring-projects/spring-boot#43357]
Exception is raised if the test is not located in the same or sub package of `@SpringBootApplication` main class, even if I use `@ContextConfiguration` or `@SpringBootTest(classes=...)` according to the suggestion in exception message.

```
java.lang.IllegalStateException: Unable to find a @SpringBootConfiguration, you need to use @ContextConfiguration or @SpringBootTest(classes=...) with your test
	at org.springframework.util.Assert.state(Assert.java:76)
	at org.springframework.boot.test.context.SpringBootTestContextBootstrapper.findConfigurationClass(SpringBootTestContextBootstrapper.java:246)
	at org.springframework.boot.test.context.SpringBootTestContextBootstrapper.getOrFindConfigurationClasses(SpringBootTestContextBootstrapper.java:233)
	at org.springframework.boot.test.context.SpringBootTestContextBootstrapper.processMergedContextConfiguration(SpringBootTestContextBootstrapper.java:150)
	at org.springframework.test.context.support.AbstractTestContextBootstrapper.buildMergedContextConfiguration(AbstractTestContextBootstrapper.java:351)
	at org.springframework.test.context.support.AbstractTestContextBootstrapper.buildDefaultMergedContextConfiguration(AbstractTestContextBootstrapper.java:267)
	at org.springframework.test.context.support.AbstractTestContextBootstrapper.buildMergedContextConfiguration(AbstractTestContextBootstrapper.java:215)
	at org.springframework.test.context.support.AbstractTestContextBootstrapper.buildTestContext(AbstractTestContextBootstrapper.java:108)
	at org.springframework.boot.test.context.SpringBootTestContextBootstrapper.buildTestContext(SpringBootTestContextBootstrapper.java:111)
	at org.springframework.test.context.TestContextManager.<init>(TestContextManager.java:142)
	at org.springframework.test.context.TestContextManager.<init>(TestContextManager.java:126)
	at org.springframework.test.context.junit.jupiter.SpringExtension.getTestContextManager(SpringExtension.java:366)
	at org.springframework.test.context.junit.jupiter.SpringExtension.beforeAll(SpringExtension.java:131)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

```

the reproducer project [configuration-class-not-found.zip](https://github.com/user-attachments/files/17986517/configuration-class-not-found.zip)

**Comment by wilkinsona** [comment]
This is the expected behavior. In both `SpringBootTestWithContextConfigurationTests` and `SpringBootTestWithClassesAttributeTests` the nested `Config` class is annotated with `@TestConfiguration`. `@TestConfiguration` is specifically intended for use where you want the configuration [to be used in addition to the auto-detection of `@SpringBootConfiguration`](https://docs.spring.io/spring-boot/reference/testing/spring-boot-applications.html#testing.spring-boot-applications.detecting-configuration):

> If you want to customize the primary configuration, you can use a nested [`@TestConfiguration`](https://docs.spring.io/spring-boot/3.4.0/api/java/org/springframework/boot/test/context/TestConfiguration.html) class. Unlike a nested [`@Configuration`](https://docs.spring.io/spring-framework/docs/6.2.x/javadoc-api/org/springframework/context/annotation/Configuration.html) class, which would be used instead of your application’s primary configuration, a nested [`@TestConfiguration`](https://docs.spring.io/spring-boot/3.4.0/api/java/org/springframework/boot/test/context/TestConfiguration.html) class is used in addition to your application’s primary configuration.

If you use `@Configuration` instead of `@TestConfiguration` the tests both pass.

**Comment by philwebb** [comment]
Reopening due to https://github.com/spring-projects/spring-boot/pull/43358#issuecomment-2515959802
