### ISSUE TITLE
Spring Boot 3.4 failed on native compilation with Spring Cloud 2024.0.0

### ISSUE THREAD

**Issue by mmuniz75** [spring-projects/spring-boot#43491]
In the start if gradlew nativeCompile , I got the follow :

[main] faultConfiguringBeanFactoryPostProcessor : No bean named 'integrationHeaderChannelRegistry' has been explicitly defined. Therefore, a default DefaultHeaderChannelRegistry will be created.
Exception in thread "main" java.lang.StackOverflowError
        at java.base/java.lang.ref.Reference.refersToImpl(Reference.java:384)
        at java.base/java.lang.ref.Reference.refersTo(Reference.java:375)
        at java.base/java.lang.reflect.AccessibleObject.isAccessChecked(AccessibleObject.java:704)
        at java.base/java.lang.reflect.AccessibleObject.verifyAccess(AccessibleObject.java:735)
        at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:713)
        at java.base/java.lang.reflect.Method.invoke(Method.java:571)
        at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:281)
        at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:265)
        at org.springframework.core.SerializableTypeWrapper$TypeProxyInvocationHandler.invoke(SerializableTypeWrapper.java:209)
        at org.springframework.core.$Proxy7.getActualTypeArguments(Unknown Source)
        at org.springframework.core.ResolvableType.getGenerics(ResolvableType.java:809)
        at org.springframework.core.ResolvableType.getGeneric(ResolvableType.java:762)
        at org.springframework.validation.beanvalidation.BeanValidationBeanRegistrationAotProcessor$BeanValidationDelegate.lambda$processAheadOfTime$0(BeanValidationBeanRegistrationAotProcessor.java:154)
        at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:728)
        at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:707)

**Comment by bclozel** [comment]
Duplicates https://github.com/spring-projects/spring-framework/pull/33950
