### ISSUE TITLE
processAot hangs if JanusGraph is used when compiling for Graal VM

### ISSUE THREAD

**Issue by mdcarr941** [spring-projects/spring-boot#43546]
I've encountered a build issue in a Spring Boot 3.4.0 application which is compiled with Graal VM. I observed that `./gradlew bootRun` hangs indefinitely at the `:processAot` step if I call `JanusGraphFactory.open`. I created a repository with a minimal reproduction here: [https://github.com/mdcarr941/springboot-repro](https://github.com/mdcarr941/springboot-repro).

As a troubleshooting step, I tried calling `JanusGraphFactory.open` off the main thread. This had no effect.

I also found that the build completes successfully if I comment out 'org.graalvm.buildtools.native' gradle plugin in the build.gradle file.

I suspected some kind of deadlock was occurring in the gradle process, so I used jstack to get stack traces. I'm not familiar with the gradle internals, but it does look like all the threads are waiting on locks or monitors.
```
2024-12-17 11:31:34
Full thread dump Java HotSpot(TM) 64-Bit Server VM (21.0.4+8-LTS-jvmci-23.1-b41 mixed mode, sharing):

Threads class SMR info:
_java_thread_list=0x0000781a74001c50, length=14, elements={
0x0000781b10028ca0, 0x0000781b100f6f60, 0x0000781b100f85b0, 0x0000781b100fa0b0,
0x0000781b100fb6f0, 0x0000781b100fcc90, 0x0000781b100fe890, 0x0000781b100fff50,
0x0000781b10126250, 0x0000781b10185b40, 0x0000781b10a876b0, 0x0000781a5c0e4590,
0x0000781a540a7740, 0x0000781a74000ff0
}

"main" #1 [87144] prio=5 os_prio=0 cpu=557.18ms elapsed=27.65s tid=0x0000781b10028ca0 nid=87144 runnable  [0x0000781b151fd000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.EPoll.wait(java.base@21.0.4/Native Method)
        at sun.nio.ch.EPollSelectorImpl.doSelect(java.base@21.0.4/EPollSelectorImpl.java:121)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(java.base@21.0.4/SelectorImpl.java:130)
        - locked <0x00000000fe0b3cd8> (a sun.nio.ch.Util$2)
        - locked <0x00000000fe0b3970> (a sun.nio.ch.EPollSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(java.base@21.0.4/SelectorImpl.java:147)
        at org.gradle.internal.remote.internal.inet.SocketConnection$SocketInputStream.read(SocketConnection.java:190)
        at com.esotericsoftware.kryo.io.Input.fill(Input.java:146)
        at com.esotericsoftware.kryo.io.Input.require(Input.java:178)
        at com.esotericsoftware.kryo.io.Input.readVarInt(Input.java:355)
        at com.esotericsoftware.kryo.io.Input.readInt(Input.java:350)
        at org.gradle.internal.serialize.kryo.KryoBackedDecoder.readSmallInt(KryoBackedDecoder.java:133)
        at org.gradle.internal.serialize.DefaultSerializerRegistry$TaggedTypeSerializer.read(DefaultSerializerRegistry.java:159)
        at org.gradle.internal.serialize.Serializers$StatefulSerializerAdapter$1.read(Serializers.java:36)
        at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:86)
        at org.gradle.launcher.daemon.client.DaemonClientConnection.receive(DaemonClientConnection.java:82)
        at org.gradle.launcher.daemon.client.DaemonClient.monitorBuild(DaemonClient.java:246)
        at org.gradle.launcher.daemon.client.DaemonClient.executeBuild(DaemonClient.java:209)
        at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:158)
        at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:97)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:56)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:167)
        at org.gradle.launcher.cli.DefaultCommandLineActionFactory$ParseAndBuildAction.execute(DefaultCommandLineActionFactory.java:370)
        at org.gradle.launcher.cli.DefaultCommandLineActionFactory$ParseAndBuildAction.execute(DefaultCommandLineActionFactory.java:334)
        at org.gradle.launcher.cli.DebugLoggerWarningAction.execute(DebugLoggerWarningAction.java:74)
        at org.gradle.launcher.cli.DebugLoggerWarningAction.execute(DebugLoggerWarningAction.java:30)
        at org.gradle.launcher.cli.WelcomeMessageAction.execute(WelcomeMessageAction.java:97)
        at org.gradle.launcher.cli.WelcomeMessageAction.execute(WelcomeMessageAction.java:40)
        at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:50)
        at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:27)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:41)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:26)
        at org.gradle.launcher.cli.DefaultCommandLineActionFactory$WithLogging.execute(DefaultCommandLineActionFactory.java:482)
        at org.gradle.launcher.Main.doAction(Main.java:35)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:52)
        at java.lang.invoke.DirectMethodHandle$Holder.invokeVirtual(java.base@21.0.4/DirectMethodHandle$Holder)
        at java.lang.invoke.LambdaForm$MH/0x0000781a98016000.invoke(java.base@21.0.4/LambdaForm$MH)
        at java.lang.invoke.Invokers$Holder.invokeExact_MT(java.base@21.0.4/Invokers$Holder)
        at jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(java.base@21.0.4/DirectMethodHandleAccessor.java:154)
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(java.base@21.0.4/DirectMethodHandleAccessor.java:103)
        at java.lang.reflect.Method.invoke(java.base@21.0.4/Method.java:580)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:72)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:39)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:31)
        at java.lang.invoke.LambdaForm$DMH/0x0000781a98007000.invokeStatic(java.base@21.0.4/LambdaForm$DMH)
        at java.lang.invoke.LambdaForm$MH/0x0000781a98008400.invoke(java.base@21.0.4/LambdaForm$MH)
        at java.lang.invoke.Invokers$Holder.invokeExact_MT(java.base@21.0.4/Invokers$Holder)
        at jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(java.base@21.0.4/DirectMethodHandleAccessor.java:154)
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(java.base@21.0.4/DirectMethodHandleAccessor.java:103)
        at java.lang.reflect.Method.invoke(java.base@21.0.4/Method.java:580)
        at org.gradle.wrapper.GradleWrapperMain.main(SourceFile:70)

"Reference Handler" #9 [87152] daemon prio=10 os_prio=0 cpu=0.42ms elapsed=27.62s tid=0x0000781b100f6f60 nid=87152 waiting on condition  [0x0000781aefbfa000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.ref.Reference.waitForReferencePendingList(java.base@21.0.4/Native Method)
        at java.lang.ref.Reference.processPendingReferences(java.base@21.0.4/Reference.java:246)
        at java.lang.ref.Reference$ReferenceHandler.run(java.base@21.0.4/Reference.java:208)

"Finalizer" #10 [87153] daemon prio=8 os_prio=0 cpu=0.13ms elapsed=27.62s tid=0x0000781b100f85b0 nid=87153 in Object.wait()  [0x0000781aef7fe000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait0(java.base@21.0.4/Native Method)
        - waiting on <0x00000000fe7340f0> (a java.lang.ref.NativeReferenceQueue$Lock)
        at java.lang.Object.wait(java.base@21.0.4/Object.java:366)
        at java.lang.Object.wait(java.base@21.0.4/Object.java:339)
        at java.lang.ref.NativeReferenceQueue.await(java.base@21.0.4/NativeReferenceQueue.java:48)
        at java.lang.ref.ReferenceQueue.remove0(java.base@21.0.4/ReferenceQueue.java:158)
        at java.lang.ref.NativeReferenceQueue.remove(java.base@21.0.4/NativeReferenceQueue.java:89)
        - locked <0x00000000fe7340f0> (a java.lang.ref.NativeReferenceQueue$Lock)
        at java.lang.ref.Finalizer$FinalizerThread.run(java.base@21.0.4/Finalizer.java:173)

"Signal Dispatcher" #11 [87154] daemon prio=9 os_prio=0 cpu=0.27ms elapsed=27.62s tid=0x0000781b100fa0b0 nid=87154 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Service Thread" #12 [87155] daemon prio=9 os_prio=0 cpu=0.40ms elapsed=27.62s tid=0x0000781b100fb6f0 nid=87155 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Monitor Deflation Thread" #13 [87156] daemon prio=9 os_prio=0 cpu=1.45ms elapsed=27.62s tid=0x0000781b100fcc90 nid=87156 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"JVMCI-native CompilerThread0" #14 [87157] daemon prio=9 os_prio=0 cpu=489.76ms elapsed=27.62s tid=0x0000781b100fe890 nid=87157 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"C1 CompilerThread0" #15 [87158] daemon prio=9 os_prio=0 cpu=154.70ms elapsed=27.62s tid=0x0000781b100fff50 nid=87158 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"Common-Cleaner" #24 [87160] daemon prio=8 os_prio=0 cpu=1.08ms elapsed=27.61s tid=0x0000781b10126250 nid=87160 waiting on condition  [0x0000781aef3fa000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@21.0.4/Native Method)
        - parking to wait for  <0x00000000fe734218> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(java.base@21.0.4/LockSupport.java:269)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@21.0.4/AbstractQueuedSynchronizer.java:1847)
        at java.lang.ref.ReferenceQueue.await(java.base@21.0.4/ReferenceQueue.java:71)
        at java.lang.ref.ReferenceQueue.remove0(java.base@21.0.4/ReferenceQueue.java:143)
        at java.lang.ref.ReferenceQueue.remove(java.base@21.0.4/ReferenceQueue.java:218)
        at jdk.internal.ref.CleanerImpl.run(java.base@21.0.4/CleanerImpl.java:140)
        at java.lang.Thread.runWith(java.base@21.0.4/Thread.java:1596)
        at java.lang.Thread.run(java.base@21.0.4/Thread.java:1583)
        at jdk.internal.misc.InnocuousThread.run(java.base@21.0.4/InnocuousThread.java:186)

"Notification Thread" #25 [87162] daemon prio=9 os_prio=0 cpu=0.08ms elapsed=27.59s tid=0x0000781b10185b40 nid=87162 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"pool-1-thread-1" #32 [87168] prio=5 os_prio=0 cpu=95.65ms elapsed=27.26s tid=0x0000781b10a876b0 nid=87168 waiting on condition  [0x0000781aee3fe000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@21.0.4/Native Method)
        - parking to wait for  <0x00000000fee67958> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(java.base@21.0.4/LockSupport.java:269)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@21.0.4/AbstractQueuedSynchronizer.java:1758)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@21.0.4/ScheduledThreadPoolExecutor.java:1182)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@21.0.4/ScheduledThreadPoolExecutor.java:899)
        at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@21.0.4/ThreadPoolExecutor.java:1070)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@21.0.4/ThreadPoolExecutor.java:1130)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@21.0.4/ThreadPoolExecutor.java:642)
        at java.lang.Thread.runWith(java.base@21.0.4/Thread.java:1596)
        at java.lang.Thread.run(java.base@21.0.4/Thread.java:1583)

"C1 CompilerThread1" #16 [87796] daemon prio=9 os_prio=0 cpu=21.60ms elapsed=7.26s tid=0x0000781a5c0e4590 nid=87796 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"C1 CompilerThread2" #17 [87860] daemon prio=9 os_prio=0 cpu=7.70ms elapsed=1.76s tid=0x0000781a540a7740 nid=87860 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"Attach Listener" #33 [87951] daemon prio=9 os_prio=0 cpu=0.21ms elapsed=0.10s tid=0x0000781a74000ff0 nid=87951 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"VM Thread" os_prio=0 cpu=2.50ms elapsed=27.62s tid=0x0000781b100e92e0 nid=87151 runnable  

"GC Thread#0" os_prio=0 cpu=2.61ms elapsed=27.64s tid=0x0000781b10049a70 nid=87145 runnable  

"GC Thread#1" os_prio=0 cpu=2.61ms elapsed=27.45s tid=0x0000781a84008d10 nid=87166 runnable  

"GC Thread#2" os_prio=0 cpu=0.15ms elapsed=27.45s tid=0x0000781a8400b290 nid=87167 runnable  

"G1 Main Marker" os_prio=0 cpu=0.05ms elapsed=27.64s tid=0x0000781b1004b490 nid=87146 runnable  

"G1 Conc#0" os_prio=0 cpu=0.06ms elapsed=27.64s tid=0x0000781b1004c430 nid=87147 runnable  

"G1 Refine#0" os_prio=0 cpu=0.06ms elapsed=27.64s tid=0x0000781b100bec60 nid=87148 runnable  

"G1 Service" os_prio=0 cpu=0.50ms elapsed=27.64s tid=0x0000781b100bfc10 nid=87149 runnable  

"VM Periodic Task Thread" os_prio=0 cpu=7.20ms elapsed=27.63s tid=0x0000781b100ce480 nid=87150 waiting on condition  

JNI global refs: 26, weak refs: 0
```

**Comment by mdcarr941** [comment]
Thank you for such a prompt reply. I can confirm that after I moved the call to `JanusGraphFactory.open` to `afterPropertiesSet` and added a call to `JanusGraph.close` in `destroy`, gradle successfully produced a native binary and `bootRun` worked as expected.
