### ISSUE TITLE
Migrate Logback configuration class to use suppliers

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#43588]
See https://github.com/qos-ch/logback/commit/be0b5e027487c351a0f006c2b695a7a3fcd4918d (which triggered https://github.com/qos-ch/logback/issues/885 in Boot 3.4). In 3.5 we could update our code to also use suppliers.

**Comment by ceki** [comment]
@philwebb Please note that the use of suppliers for specifying converter classes is optional. Logback 1.5.14 and later will transparently adapt any converters specified as strings.

**Comment by snicoll** [comment]
@ceki I am a bit confused about the change. How is the use of suppliers optional? Looking at the code, it looks like that the `PATTERN_RULE_REGISTRY` map must have a String class name and it will fail if we attempt to use a supplier:

```
java.lang.ClassCastException: class org.springframework.boot.logging.logback.DefaultLogbackConfiguration$$Lambda$637/0x000000f00132a840 cannot be cast to class java.lang.String (org.springframework.boot.logging.logback.DefaultLogbackConfiguration$$Lambda$637/0x000000f00132a840 is in unnamed module of loader org.springframework.boot.testsupport.classpath.ModifiedClassPathClassLoader @33d05366; java.lang.String is in module java.base of loader 'bootstrap')
	at ch.qos.logback.core.pattern.PatternLayoutBase.migrateFromStringMapToSupplierMap(PatternLayoutBase.java:124)
	at ch.qos.logback.core.pattern.PatternLayoutBase.caterForLegacyConverterMaps(PatternLayoutBase.java:111)
	at ch.qos.logback.core.pattern.PatternLayoutBase.getEffectiveConverterMap(PatternLayoutBase.java:84)
	at ch.qos.logback.core.pattern.PatternLayoutBase.start(PatternLayoutBase.java:143)
	at ch.qos.logback.classic.encoder.PatternLayoutEncoder.start(PatternLayoutEncoder.java:28)
	at org.springframework.boot.logging.logback.LogbackConfigurator.start(LogbackConfigurator.java:110)
```

What should we do if we want to migrate [our code](https://github.com/spring-projects/spring-boot/blob/879d664bd57755cbd50bcc1f25d575561535113d/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/logging/logback/LogbackConfigurator.java#L58) to use suppliers?

**Comment by ceki** [comment]
@snicoll I only had 10 minutes to look into this. Which version of logback are you using? I am asking because version[ logback 1.5.14](https://logback.qos.ch/news.html#1.5.14) fixed a compatibility issue when accessing the pattern rule registry through the logging context. Are you using an earlier version of logback by any chance?

**Comment by snicoll** [comment]
Nope, I am using the latest. But you answered my question. I should change the key to lookup the map.
