### ISSUE TITLE
Request to put sequence numbers on Java stack traces when running in Cloud Foundry

### ISSUE THREAD

**Issue by Jim-Campbell** [spring-projects/spring-boot#4417]
Hi Spring!

I'm the PM in Cloud Foundry for the Loggregator sub-system. One of the characteristics of the Loggregator system is that log message order is not guaranteed. Since log messages are each single lines coming out of stdout/stderr, that means that the lines of a Java stack trace may be out of order. I have user reports of this causing pain.

I had a conversation with Andy Clement and Phil Webb today and we brainstormed a solution where the Boot logging subsystem could detect that it is running in CF, and prepend a sequence number to each stack trace log line. This would at least allow the stack trace to be reassembled into correct order after delivery by Loggregator.

Let me know who I need to talk to if you need further context in order to prioritize.

**Comment by philwebb** [comment]
Looking into this a bit more and I'm wondering if the suggested fix is actually going to be viable. Here's a typical failure trace:

```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                        

2015-11-10 09:58:04.978  INFO 50635 --- [           main] test.Application                         : Starting Application on pwmbp with PID 50635 (/Users/pwebb/projects/spring-boot/workspace/demo/target/classes started by pwebb in /Users/pwebb/projects/spring-boot/workspace/demo)
2015-11-10 09:58:04.981  INFO 50635 --- [           main] test.Application                         : No profiles are active
2015-11-10 09:58:05.037  INFO 50635 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@63e2203c: startup date [Tue Nov 10 09:58:05 PST 2015]; root of context hierarchy
2015-11-10 09:58:05.874  INFO 50635 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Overriding bean definition for bean 'beanNameViewResolver' with a different definition: replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration$WhitelabelErrorViewConfiguration; factoryMethodName=beanNameViewResolver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/web/ErrorMvcAutoConfiguration$WhitelabelErrorViewConfiguration.class]] with [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter; factoryMethodName=beanNameViewResolver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter.class]]
2015-11-10 09:58:06.670  INFO 50635 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 8080 (http)
2015-11-10 09:58:06.687  INFO 50635 --- [           main] o.apache.catalina.core.StandardService   : Starting service Tomcat
2015-11-10 09:58:06.688  INFO 50635 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.0.28
2015-11-10 09:58:06.790  INFO 50635 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2015-11-10 09:58:06.790  INFO 50635 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1759 ms
2015-11-10 09:58:07.139  INFO 50635 --- [ost-startStop-1] o.s.b.c.e.ServletRegistrationBean        : Mapping servlet: 'dispatcherServlet' to [/]
2015-11-10 09:58:07.144  INFO 50635 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'metricFilter' to: [/*]
2015-11-10 09:58:07.145  INFO 50635 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'characterEncodingFilter' to: [/*]
2015-11-10 09:58:07.145  INFO 50635 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2015-11-10 09:58:07.145  INFO 50635 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2015-11-10 09:58:07.145  INFO 50635 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'requestContextFilter' to: [/*]
2015-11-10 09:58:07.146  INFO 50635 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'webRequestLoggingFilter' to: [/*]
2015-11-10 09:58:07.146  INFO 50635 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'applicationContextIdFilter' to: [/*]
2015-11-10 09:58:07.257  INFO 50635 --- [           main] o.apache.catalina.core.StandardService   : Stopping service Tomcat
2015-11-10 09:58:07.273  INFO 50635 --- [           main] .b.l.ClasspathLoggingApplicationListener : Application failed to start with classpath: [file:/Users/pwebb/projects/spring-boot/workspace/demo/target/classes/, file:/Users/pwebb/projects/spring-boot/code/spring-boot-starters/spring-boot-starter/target/classes/, file:/Users/pwebb/projects/spring-boot/code/spring-boot/target/classes/, file:/Users/pwebb/.m2/repository/org/springframework/spring-context/4.2.3.BUILD-SNAPSHOT/spring-context-4.2.3.BUILD-SNAPSHOT.jar, file:/Users/pwebb/projects/spring-boot/code/spring-boot-autoconfigure/target/classes/, file:/Users/pwebb/projects/spring-boot/code/spring-boot-starters/spring-boot-starter-logging/target/classes/, file:/Users/pwebb/.m2/repository/ch/qos/logback/logback-classic/1.1.3/logback-classic-1.1.3.jar, file:/Users/pwebb/.m2/repository/ch/qos/logback/logback-core/1.1.3/logback-core-1.1.3.jar, file:/Users/pwebb/.m2/repository/org/slf4j/slf4j-api/1.7.12/slf4j-api-1.7.12.jar, file:/Users/pwebb/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.12/jcl-over-slf4j-1.7.12.jar, file:/Users/pwebb/.m2/repository/org/slf4j/jul-to-slf4j/1.7.12/jul-to-slf4j-1.7.12.jar, file:/Users/pwebb/.m2/repository/org/slf4j/log4j-over-slf4j/1.7.12/log4j-over-slf4j-1.7.12.jar, file:/Users/pwebb/.m2/repository/org/springframework/spring-core/4.2.3.BUILD-SNAPSHOT/spring-core-4.2.3.BUILD-SNAPSHOT.jar, file:/Users/pwebb/.m2/repository/org/yaml/snakeyaml/1.16/snakeyaml-1.16.jar, file:/Users/pwebb/projects/spring-boot/code/spring-boot-starters/spring-boot-starter-web/target/classes/, file:/Users/pwebb/projects/spring-boot/code/spring-boot-starters/spring-boot-starter-tomcat/target/classes/, file:/Users/pwebb/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/8.0.28/tomcat-embed-core-8.0.28.jar, file:/Users/pwebb/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/8.0.28/tomcat-embed-el-8.0.28.jar, file:/Users/pwebb/.m2/repository/org/apache/tomcat/embed/tomcat-embed-logging-juli/8.0.28/tomcat-embed-logging-juli-8.0.28.jar, file:/Users/pwebb/.m2/repository/org/apache/tomcat/embed/tomcat-embed-websocket/8.0.28/tomcat-embed-websocket-8.0.28.jar, file:/Users/pwebb/projects/spring-boot/code/spring-boot-starters/spring-boot-starter-validation/target/classes/, file:/Users/pwebb/.m2/repository/org/hibernate/hibernate-validator/5.2.2.Final/hibernate-validator-5.2.2.Final.jar, file:/Users/pwebb/.m2/repository/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar, file:/Users/pwebb/.m2/repository/org/jboss/logging/jboss-logging/3.3.0.Final/jboss-logging-3.3.0.Final.jar, file:/Users/pwebb/.m2/repository/com/fasterxml/classmate/1.1.0/classmate-1.1.0.jar, file:/Users/pwebb/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.6.1/jackson-databind-2.6.1.jar, file:/Users/pwebb/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.6.1/jackson-annotations-2.6.1.jar, file:/Users/pwebb/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.6.1/jackson-core-2.6.1.jar, file:/Users/pwebb/.m2/repository/org/springframework/spring-web/4.2.3.BUILD-SNAPSHOT/spring-web-4.2.3.BUILD-SNAPSHOT.jar, file:/Users/pwebb/.m2/repository/org/springframework/spring-aop/4.2.3.BUILD-SNAPSHOT/spring-aop-4.2.3.BUILD-SNAPSHOT.jar, file:/Users/pwebb/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar, file:/Users/pwebb/.m2/repository/org/springframework/spring-beans/4.2.3.BUILD-SNAPSHOT/spring-beans-4.2.3.BUILD-SNAPSHOT.jar, file:/Users/pwebb/.m2/repository/org/springframework/spring-webmvc/4.2.3.BUILD-SNAPSHOT/spring-webmvc-4.2.3.BUILD-SNAPSHOT.jar, file:/Users/pwebb/.m2/repository/org/springframework/spring-expression/4.2.3.BUILD-SNAPSHOT/spring-expression-4.2.3.BUILD-SNAPSHOT.jar, file:/Users/pwebb/projects/spring-boot/code/spring-boot-starters/spring-boot-starter-actuator/target/classes/, file:/Users/pwebb/projects/spring-boot/code/spring-boot-actuator/target/classes/]
2015-11-10 09:58:07.274 ERROR 50635 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'myController' defined in file [/Users/pwebb/projects/spring-boot/workspace/demo/target/classes/test/MyController.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [test.MyController]: Constructor threw exception; nested exception is java.lang.RuntimeException: test
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1105) ~[spring-beans-4.2.3.BUILD-SNAPSHOT.jar:4.2.3.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1050) ~[spring-beans-4.2.3.BUILD-SNAPSHOT.jar:4.2.3.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510) ~[spring-beans-4.2.3.BUILD-SNAPSHOT.jar:4.2.3.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.2.3.BUILD-SNAPSHOT.jar:4.2.3.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:305) ~[spring-beans-4.2.3.BUILD-SNAPSHOT.jar:4.2.3.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.2.3.BUILD-SNAPSHOT.jar:4.2.3.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:301) ~[spring-beans-4.2.3.BUILD-SNAPSHOT.jar:4.2.3.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:196) ~[spring-beans-4.2.3.BUILD-SNAPSHOT.jar:4.2.3.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772) ~[spring-beans-4.2.3.BUILD-SNAPSHOT.jar:4.2.3.BUILD-SNAPSHOT]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:844) ~[spring-context-4.2.3.BUILD-SNAPSHOT.jar:4.2.3.BUILD-SNAPSHOT]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544) ~[spring-context-4.2.3.BUILD-SNAPSHOT.jar:4.2.3.BUILD-SNAPSHOT]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[classes/:na]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761) [classes/:na]
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:356) [classes/:na]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:295) [classes/:na]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1085) [classes/:na]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1074) [classes/:na]
	at test.Application.main(Application.java:10) [classes/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [test.MyController]: Constructor threw exception; nested exception is java.lang.RuntimeException: test
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163) ~[spring-beans-4.2.3.BUILD-SNAPSHOT.jar:4.2.3.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:89) ~[spring-beans-4.2.3.BUILD-SNAPSHOT.jar:4.2.3.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1098) ~[spring-beans-4.2.3.BUILD-SNAPSHOT.jar:4.2.3.BUILD-SNAPSHOT]
	... 17 common frames omitted
Caused by: java.lang.RuntimeException: test
	at test.MyController.<init>(MyController.java:21) ~[classes/:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_40]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_40]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_40]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_40]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147) ~[spring-beans-4.2.3.BUILD-SNAPSHOT.jar:4.2.3.BUILD-SNAPSHOT]
	... 19 common frames omitted
```

The problem is that the stack trace doesn't currently include any sort of prefix so we'd need to add both the date/timestamp and then some index. This is probably going to mess up any log parsing.

Thinking about the problem some more, I wonder if the log capture process could add some additional meta-data that includes the line number. This might be a better long term solution anyway as anything we do here will obviously only work for Spring Boot applications and the problem will still arise if not using Boot.

So conceptually, the output would be tagged with a simple counter (the [NNNNN] item is meta-data not actually output to the screen):

```
[00001] 2015-11-10 09:58:04.978  INFO 50635 --- [           main] test.Application                         : Starting Application on pwmbp with PID 50635 (/Users/pwebb/projects/spring-boot/workspace/demo/target/classes started by pwebb in /Users/pwebb/projects/spring-boot/workspace/demo)
[00002] 2015-11-10 09:58:04.981  INFO 50635 --- [           main] test.Application                         : No profiles are active
[00003] 2015-11-10 09:58:05.037  INFO 50635 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@63e2203c: startup date [Tue Nov 10 09:58:05 PST 2015]; root of context hierarchy
```

The log lines are sent as usually to the distributed sinks:

```
[00001]  --> A
[00002]  --> A
[00003]  --> B
```

The collation occurs as the meta-data can be used to reconstruct order:

```
A --+ 
    +--> Collator (reconstructed order [00001], [00002], [00003])
B --+
```

**Comment by aclement** [comment]
I will just chime in that after we spoke I chatted with the person who had hit the problem of an out of order stack trace. We have seen it but only through the CF Java Client, not through the CF CLI and it looks like the java client may have been contributing to the problem. We have patched the java client to be smarter for the case we saw (and the java client is currently undergoing a big v2 rewrite anyway, that hopefully won't hit this). I guess that doesn't mean the problem can never happen but perhaps suggests it is less likely than we thought.

**Comment by Jim-Campbell** [comment]
Hmmm. Sequence numbers at the log capture level is a pretty big change, though I don't have specific context on how much it would screw people up.

Are you talking about needing date time to distinguish between different stack traces and then the sequence number with in each stack trace?

My inclination is to pause on this until I hear a real example (and preferably more than one) on out of order stack traces causing problems. I can also socialize the concept of the global sequence number and see what other users think. You can probably close the issue and I'll get in touch again if I hear about pain. That work?

**Comment by philwebb** [comment]
Sounds good. I'll close this for now. It seemed like a good idea during the call but I think a more robust solution (that's not Spring Boot specific) is probably needed.
