### ISSUE TITLE
Disable Spring Starter JPA/Hibernate for Unit test

### ISSUE THREAD

**Issue by nsdiv** [spring-projects/spring-boot#4426]
While running a unit test that tests our service layer, connecting to a database, even if it is an embedded one, is unnecessary. It is easier to just mock out all the beans.
I was able to do that successfully for spring boot Mongo. Here is the gist:
https://gist.github.com/nsdiv/9effb78e27ff6ca94381

However I am not able to do it for spring boot JPA/Hibernate. Here are the beans I'm mocking 

```java    
    @Bean
    public DataSource dataSource() {
        return null;
    }

    @Bean
    public LocalContainerEntityManagerFactoryBean entityManagerFactory(DataSource dataSource, JpaVendorAdapter jpaVendorAdapter) {
        return null;
    }

    @Bean
    public JpaVendorAdapter jpaVendorAdapter() {
        return null;
    }

    @Bean
    public NamedParameterJdbcTemplate mySqlJdbcTemplate(DataSource dataSource) {
        return null;
    }
```

However I get an NPE while creating a bean. On setting loglevel to DEBUG, the following is printed.

```
2015-11-10 15:24:26,739; thread=[main]; LogLevel=DEBUG; category=org.springframework.boot.autoconfigure.logging.AutoConfigurationReportLoggingInitializer; msg=


=========================
AUTO-CONFIGURATION REPORT
=========================
Positive matches:
-----------------
  AopAutoConfiguration
      - @ConditionalOnClass classes found: org.springframework.context.annotation.EnableAspectJAutoProxy,org.aspectj.lang.annotation.Aspect,org.aspectj.lang.reflect.Advice (OnClassCondition)
      - matched (OnPropertyCondition)

   AopAutoConfiguration.JdkDynamicAutoProxyConfiguration
      - matched (OnPropertyCondition)

   ArchaiusAutoConfiguration
      - @ConditionalOnClass classes found: com.netflix.config.ConcurrentCompositeConfiguration,org.apache.commons.configuration.ConfigurationBuilder (OnClassCondition)

   ArchaiusAutoConfiguration.ArchaiusEndpointConfiguration
      - @ConditionalOnClass classes found: org.springframework.boot.actuate.endpoint.Endpoint (OnClassCondition)

   ArchaiusAutoConfiguration.PropagateEventsConfiguration
      - @ConditionalOnClass classes found: org.springframework.cloud.context.environment.EnvironmentChangeEvent (OnClassCondition)
      - matched (OnPropertyCondition)

   AuditAutoConfiguration#authenticationAuditListener
      - @ConditionalOnClass classes found: org.springframework.security.authentication.event.AbstractAuthenticationEvent (OnClassCondition)

   AuditAutoConfiguration#authorizationAuditListener
      - @ConditionalOnClass classes found: org.springframework.security.access.event.AbstractAuthorizationEvent (OnClassCondition)

   AuditAutoConfiguration.AuditEventRepositoryConfiguration
      - @ConditionalOnMissingBean (types: org.springframework.boot.actuate.audit.AuditEventRepository; SearchStrategy: all) found no beans (OnBeanCondition)

   BootGlobalAuthenticationConfiguration
      - @ConditionalOnClass classes found: org.springframework.security.config.annotation.authentication.configurers.GlobalAuthenticationConfigurerAdapter (OnClassCondition)

   DataSourceAutoConfiguration
      - @ConditionalOnClass classes found: javax.sql.DataSource,org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType (OnClassCondition)

   DataSourceAutoConfiguration.DataSourceInitializerConfiguration
      - @ConditionalOnMissingBean (types: org.springframework.boot.autoconfigure.jdbc.DataSourceInitializer; SearchStrategy: all) found no beans (OnBeanCondition)

   DataSourceAutoConfiguration.JdbcTemplateConfiguration
      - existing auto database detected (DataSourceAutoConfiguration.DataSourceAvailableCondition)
      - existing bean configured database detected (DataSourceAutoConfiguration.DataSourceAvailableCondition)

   DataSourceAutoConfiguration.JdbcTemplateConfiguration#jdbcTemplate
      - @ConditionalOnMissingBean (types: org.springframework.jdbc.core.JdbcOperations; SearchStrategy: all) found no beans (OnBeanCondition)

   DataSourcePoolMetadataProvidersConfiguration.TomcatDataSourcePoolMetadataProviderConfiguration
      - @ConditionalOnClass classes found: org.apache.tomcat.jdbc.pool.DataSource (OnClassCondition)

   DataSourceTransactionManagerAutoConfiguration
      - @ConditionalOnClass classes found: org.springframework.jdbc.core.JdbcTemplate,org.springframework.transaction.PlatformTransactionManager (OnClassCondition)

   DataSourceTransactionManagerAutoConfiguration.TransactionManagementConfiguration
      - @ConditionalOnMissingBean (types: org.springframework.transaction.annotation.AbstractTransactionManagementConfiguration; SearchStrategy: all) found no beans (OnBeanCondition)

   .............
.....
.....

2015-11-10 15:24:26,745; thread=[main]; LogLevel=ERROR; category=org.springframework.boot.SpringApplication; msg=Application startup failed; 
java.lang.NullPointerException: null
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1501) ~[spring-beans-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:314) ~[spring-beans-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194) ~[spring-beans-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:960) ~[spring-context-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:749) ~[spring-context-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480) ~[spring-context-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:689) ~[spring-boot-1.2.7.RELEASE.jar:1.2.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:321) ~[spring-boot-1.2.7.RELEASE.jar:1.2.7.RELEASE]
	at org.springframework.boot.test.SpringApplicationContextLoader.loadContext(SpringApplicationContextLoader.java:103) [spring-boot-1.2.7.RELEASE.jar:1.2.7.RELEASE]
	at org.springframework.test.context.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:68) [spring-test-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.test.context.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:86) [spring-test-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.test.context.DefaultTestContext.getApplicationContext(DefaultTestContext.java:72) [spring-test-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:117) [spring-test-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83) [spring-test-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:212) [spring-test-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at 
```

**Comment by philwebb** [comment]
You're returning `null` objects for your `DataSource` beans so I'm not really surprised that you're seeing `NullPointerExceptions`. I'd suggest asking on stackoverflow.com for suggestions about mocking strategies.
