### ISSUE TITLE
Spring Boot 1.3.0.RC fails to load embedded FTL template

### ISSUE THREAD

**Issue by mkadan** [spring-projects/spring-boot#4467]
! This doesn't happen all the time, but happens consistently after a few minutes of a high load !

I have a Spring Boot based web app, which may generate content using Freemarker template, and sometimes the template fails to be loaded, though it has worked a few moments ago:

```
2015-11-13 20:48:43.069 ERROR 19885 --- [-8080-exec-1784] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.context.ApplicationContextException: Could not load FreeMarker template for URL [article.ftl]; nested exception is java.io.IOException: There was an error loading the template on an earlier attempt; it's attached as a cause] with root cause
java.util.zip.ZipException: invalid distance too far back
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164) ~[na:1.8.0_25]
	at org.springframework.boot.loader.jar.ZipInflaterInputStream.read(ZipInflaterInputStream.java:52) ~[aargauerzeitung-liveapp-updater-1.6.0-SNAPSHOT.jar!/:na]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284) ~[na:1.8.0_25]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[na:1.8.0_25]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[na:1.8.0_25]
	at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[na:1.8.0_25]
	at java.io.BufferedReader.read1(BufferedReader.java:210) ~[na:1.8.0_25]
	at java.io.BufferedReader.read(BufferedReader.java:286) ~[na:1.8.0_25]
	at freemarker.template.Template$LineTableBuilder.read(Template.java:701) ~[freemarker-2.3.23.jar!/:2.3.23]
	at freemarker.core.SimpleCharStream.FillBuff(SimpleCharStream.java:107) ~[freemarker-2.3.23.jar!/:2.3.23]
	at freemarker.core.SimpleCharStream.readChar(SimpleCharStream.java:188) ~[freemarker-2.3.23.jar!/:2.3.23]
	at freemarker.core.SimpleCharStream.BeginToken(SimpleCharStream.java:129) ~[freemarker-2.3.23.jar!/:2.3.23]
	at freemarker.core.FMParserTokenManager.getNextToken(FMParserTokenManager.java:7190) ~[freemarker-2.3.23.jar!/:2.3.23]
	at freemarker.core.FMParser.jj_scan_token(FMParser.java:5131) ~[freemarker-2.3.23.jar!/:2.3.23]
	at freemarker.core.FMParser.jj_3_16(FMParser.java:3812) ~[freemarker-2.3.23.jar!/:2.3.23]
	at freemarker.core.FMParser.jj_2_16(FMParser.java:3549) ~[freemarker-2.3.23.jar!/:2.3.23]
	at freemarker.core.FMParser.Root(FMParser.java:3427) ~[freemarker-2.3.23.jar!/:2.3.23]
	at freemarker.template.Template.<init>(Template.java:208) ~[freemarker-2.3.23.jar!/:2.3.23]
	at freemarker.cache.TemplateCache.loadTemplate(TemplateCache.java:495) ~[freemarker-2.3.23.jar!/:2.3.23]
	at freemarker.cache.TemplateCache.getTemplate(TemplateCache.java:409) ~[freemarker-2.3.23.jar!/:2.3.23]
	at freemarker.cache.TemplateCache.getTemplate(TemplateCache.java:261) ~[freemarker-2.3.23.jar!/:2.3.23]
	at freemarker.template.Configuration.getTemplate(Configuration.java:1786) ~[freemarker-2.3.23.jar!/:2.3.23]
	at freemarker.template.Configuration.getTemplate(Configuration.java:1655) ~[freemarker-2.3.23.jar!/:2.3.23]
	at org.springframework.web.servlet.view.freemarker.FreeMarkerView.getTemplate(FreeMarkerView.java:351) ~[spring-webmvc-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	at org.springframework.web.servlet.view.freemarker.FreeMarkerView.checkResource(FreeMarkerView.java:204) ~[spring-webmvc-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	at org.springframework.web.servlet.view.UrlBasedViewResolver.loadView(UrlBasedViewResolver.java:483) ~[spring-webmvc-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	at org.springframework.web.servlet.view.AbstractCachingViewResolver.createView(AbstractCachingViewResolver.java:244) ~[spring-webmvc-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	at org.springframework.web.servlet.view.UrlBasedViewResolver.createView(UrlBasedViewResolver.java:446) ~[spring-webmvc-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	at org.springframework.web.servlet.view.AbstractCachingViewResolver.resolveViewName(AbstractCachingViewResolver.java:146) ~[spring-webmvc-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	at org.springframework.web.servlet.view.ContentNegotiatingViewResolver.getCandidateViews(ContentNegotiatingViewResolver.java:291) ~[spring-webmvc-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	at org.springframework.web.servlet.view.ContentNegotiatingViewResolver.resolveViewName(ContentNegotiatingViewResolver.java:212) ~[spring-webmvc-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.resolveViewName(DispatcherServlet.java:1283) ~[spring-webmvc-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1224) ~[spring-webmvc-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1027) ~[spring-webmvc-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:971) ~[spring-webmvc-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893) ~[spring-webmvc-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) ~[spring-webmvc-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) ~[tomcat-embed-core-8.0.28.jar!/:8.0.28]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) ~[spring-webmvc-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) ~[tomcat-embed-core-8.0.28.jar!/:8.0.28]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) ~[tomcat-embed-core-8.0.28.jar!/:8.0.28]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.28.jar!/:8.0.28]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217) ~[tomcat-embed-core-8.0.28.jar!/:8.0.28]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [tomcat-embed-core-8.0.28.jar!/:8.0.28]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [tomcat-embed-core-8.0.28.jar!/:8.0.28]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [tomcat-embed-core-8.0.28.jar!/:8.0.28]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.0.28.jar!/:8.0.28]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [tomcat-embed-core-8.0.28.jar!/:8.0.28]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518) [tomcat-embed-core-8.0.28.jar!/:8.0.28]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091) [tomcat-embed-core-8.0.28.jar!/:8.0.28]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673) [tomcat-embed-core-8.0.28.jar!/:8.0.28]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500) [tomcat-embed-core-8.0.28.jar!/:8.0.28]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456) [tomcat-embed-core-8.0.28.jar!/:8.0.28]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_25]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.0.28.jar!/:8.0.28]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
```

This doesn't happen on Spring Boot 1.2.7.RELEASE, only on 1.3.0.RC.

As Freemarker versions are the same for both, and I run the apps on the same Java version, I think this line of the trace may be the cause of the problem:

```
	at org.springframework.boot.loader.jar.ZipInflaterInputStream.read(ZipInflaterInputStream.java:52) ~[aargauerzeitung-liveapp-updater-1.6.0-SNAPSHOT.jar!/:na]
```

Here is the `build.gradle` for my app (Spring Boot version was rolled back to `1.2.7.RELEASE` and the issue doesn't appear now):

```groovy
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'org.springframework.boot:spring-boot-gradle-plugin:1.2.7.RELEASE'
    }
}

def projectGroup = 'XXX'
def projectArtifact = 'YYY'
def projectVersion = '1.0.0-SNAPSHOT'

group projectGroup
version projectVersion

apply plugin: 'java'
apply plugin: 'spring-boot'

sourceCompatibility = JavaVersion.VERSION_1_8

jar {
    baseName = projectArtifact
    version = projectVersion
}

repositories {
    jcenter()
}

dependencies {
    compile 'org.springframework.boot:spring-boot-starter'
    compile 'org.springframework.boot:spring-boot-starter-jdbc'
    compile 'org.springframework.boot:spring-boot-starter-web'
    compile 'org.springframework.boot:spring-boot-starter-freemarker'
    compile 'org.springframework.boot:spring-boot-starter-aop'
    compile 'org.springframework.boot:spring-boot-starter-redis'
    compile 'org.springframework.boot:spring-boot-starter-actuator'
    compile 'com.fasterxml.jackson.core:jackson-databind:2.6.1'
    compile 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.6.1'
    compile 'mysql:mysql-connector-java:5.1.37'
    compile 'com.google.guava:guava:18.0'
    compile 'org.jsoup:jsoup:1.8.3'
    compile 'com.google.code.findbugs:jsr305:3.0.0'

    testCompile 'org.springframework.boot:spring-boot-starter-test'
}
```

**Comment by philwebb** [comment]
That's quite odd because not all that much has changed with the `org.springframework.boot.loader` code. You're definitely only seeing this with 1.3? Nothing is changing the JAR file whilst it's running is it?

**Comment by mkadan** [comment]
Yes, I just package a jar with gradle and run it with the command line, like java -jar XXX.jar
The only difference between the jar that works and the one that fails is Spring Boot version.

**Comment by philwebb** [comment]
Are you able to share some code that demonstrates the issue?

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
