### ISSUE TITLE
EmbeddedWebApplicationContext error on Spring Boot 1.3.0

### ISSUE THREAD

**Issue by ofbizbrazil** [spring-projects/spring-boot#4513]
Hi,

When I try to start my application that uses an Undertow server, it throws Null pointer exception.

```
INFO  xx.xx.xx.MyApp - Starting MyApp
INFO  xx.xx.xx.MyApp - No profiles are active
INFO  org.hibernate.validator.internal.util.Version - HV000001: Hibernate Validator 5.2.2.Final
WARN  io.undertow.websockets.jsr - UT026009: XNIO worker was not set on WebSocketDeploymentInfo, the default worker will be used
WARN  io.undertow.websockets.jsr - UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
INFO  io.undertow.servlet - Initializing Spring embedded WebApplicationContext
ERROR org.springframework.boot.SpringApplication - Application startup failed
org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is java.lang.RuntimeException: java.lang.NullPointerException
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:133) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:347) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:295) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1112) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1101) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at xx.xx.xx.MyApp.main(MyApp.java:21) [classes/:na]
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:225) ~[undertow-servlet-1.3.5.Final.jar:1.3.5.Final]
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.createDeploymentManager(UndertowEmbeddedServletContainerFactory.java:365) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.getEmbeddedServletContainer(UndertowEmbeddedServletContainerFactory.java:219) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:158) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:130) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	... 8 common frames omitted
Caused by: java.lang.NullPointerException: null
	at xx.xx.xx.security.support.StandardWebApplicationInitializer.onStartup(StandardWebApplicationInitializer.java:102) ~[classes/:na]
	at xx.xx.xx.vaadin.support.VaadinWebApplicationInitializer.onStartup(VaadinWebApplicationInitializer.java:43) ~[classes/:na]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.selfInitialize(EmbeddedWebApplicationContext.java:223) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.access$000(EmbeddedWebApplicationContext.java:85) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext$1.onStartup(EmbeddedWebApplicationContext.java:207) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory$Initializer.onStartup(UndertowEmbeddedServletContainerFactory.java:595) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:185) ~[undertow-servlet-1.3.5.Final.jar:1.3.5.Final]
	... 12 common frames omitted
```

It happens when I try to add a filter into, specifically into method addMappingForUrlPatterns.
```
// Charset encoding filter
final CharacterEncodingFilter characterEncodingFilter = new CharacterEncodingFilter();
final Dynamic dynCharacterEncodingFilter = servletContext.addFilter("characterEncodingFilter",
            characterEncodingFilter);
dynCharacterEncodingFilter.addMappingForUrlPatterns(EnumSet.allOf(DispatcherType.class), false, defaultUri);
dynCharacterEncodingFilter.setInitParameter("encoding", ApplicationConfig.DEFAULT_ENCODING);
```

**Comment by wilkinsona** [comment]
@ofbizbrazil Please try to do some problem diagnosis before opening an issue. If you've already done some, please let us know. `servletContext.addFilter` is returning `null`. You can read the javadoc for that method to learn why.

**Comment by ofbizbrazil** [comment]
@wilkinsona 

As I said is not the servletcontext returning null, but the method addmappings.

On Spring Boot 1.2.7 it works fine.

**Comment by philwebb** [comment]
@ofbizbrazil There's probably already a filter named `characterEncodingFilter` already registered by Boot which means that `servletContext.addFilter` will return `null`. As Andy suggested take a look at the `servletContext` Javadoc:

> return a FilterRegistration object that may be used to further configure the registered filter, or null if this ServletContext already contains a complete FilterRegistration for a filter with the given filterName.

The call `dynCharacterEncodingFilter.addMappingForUrlPatterns` most probably fails because `dynCharacterEncodingFilter` is `null`.
