### ISSUE TITLE
No qualifying bean of type SecurityProperties found for dependency after upgrade to 1.3.0

### ISSUE THREAD

**Issue by hohwille** [spring-projects/spring-boot#4525]
Thanks for releasing spring-boot 1.3.0.RELEASE and all your work.
However, I just updated a project and went trough some class and method not found errors until now my tests are sane. Also I had to add some ".and()" calls to my subclasses of ```WebSecurityConfigurerAdapter```. However, I now end up with this error and I can not find a problem on my side any more. Any ideas what might cause this error? Is there something broken in the release?

```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'securityFilterChainRegistration' defined in class path resource [org/springframework/boot/autoconfigure/security/SecurityFilterAutoConfiguration.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.springframework.boot.autoconfigure.security.SecurityProperties]: : No qualifying bean of type [org.springframework.boot.autoconfigure.security.SecurityProperties] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.boot.autoconfigure.security.SecurityProperties] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:464) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1123) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1018) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.boot.context.embedded.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:232) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.context.embedded.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:213) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.context.embedded.ServletContextInitializerBeans.addServletContextInitializerBeans(ServletContextInitializerBeans.java:89) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.context.embedded.ServletContextInitializerBeans.<init>(ServletContextInitializerBeans.java:77) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.getServletContextInitializerBeans(EmbeddedWebApplicationContext.java:235) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.selfInitialize(EmbeddedWebApplicationContext.java:222) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.access$000(EmbeddedWebApplicationContext.java:85) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext$1.onStartup(EmbeddedWebApplicationContext.java:207) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.context.embedded.tomcat.TomcatStarter.onStartup(TomcatStarter.java:55) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5170) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_45]
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.boot.autoconfigure.security.SecurityProperties] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:1373) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1119) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:813) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	... 26 common frames omitted
```

**Comment by wilkinsona** [comment]
The `SecurityProperties` bean should be auto-configured by `SecurityAutoConfiguration` as long as you have `spring-security-core` and `spring-security-config` on the classpath. It would appear that's not happening but it's impossible to tell why from the information that you've provided thus far.

Can you please provide a small sample that illustrates the problem?

**Comment by hohwille** [comment]
Thanks for the quick response.
Indeed I have this annotation on my main application class:
```
@SpringBootApplication(exclude = { SecurityAutoConfiguration.class })
```

However this used to work before. I instead subclasses ```WebSecurityConfigurerAdapter``` and that subclass is annotated with
```
@Configuration
@EnableWebSecurity
```

**Comment by wilkinsona** [comment]
You don't need to exclude `SecurityAutoConfiguration` to disable Spring Boot's auto-configuration of web security. Your own configuration class annotated with `@EnableWebSecurity` is sufficient to do that. That said, what you're doing isn't wrong, just a bit more complicated than it needs to be.

This has changed in 1.3 as the auto-configuration for the security filter has been moved into a separate class. It's intended purpose is to ensure the Spring Security's filter as the correct order. `SecurityFilterAutoConfiguration` needs to be updated to cope with there being no existing `SecurityProperties` bean.

**Comment by hohwille** [comment]
I removed the exclusion and then I can startup the application but security is not working properly anymore. 
It seems that the SecurityAutoConfiguration still interferes with my custom web securtiy config.

```
Caused by: org.springframework.security.access.AccessDeniedException: Zugriff verweigert
	at org.springframework.security.access.vote.AffirmativeBased.decide(AffirmativeBased.java:83) ~[spring-security-core-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:232) ~[spring-security-core-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:64) ~[spring-security-core-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208) ~[spring-aop-4.2.3.RELEASE.jar:4.2.3.RELEASE]
```

**Comment by hohwille** [comment]
After login with other custom authentication I get redirected to
```/security/html/login.html?targetUrl=``` what seems to be a default triggered by ```SecurityAutoConfiguration```.
So I am quite sure I still need to exclude ```SecurityAutoConfiguration```.

**Comment by wilkinsona** [comment]
Quite possibly; you haven't shown enough of your application for me to be able to tell. For example, `SecurityAutoConfiguration` will auto-configure an authentication manager if you haven't provided your own.

**Comment by hohwille** [comment]
BTW: My project has more than one boot application and there is also a second one that has 
```
@SpringBootApplication(exclude = { SecurityAutoConfiguration.class })
```
And that one is not causing the problem.

**Comment by hohwille** [comment]
Seems this one is the problem in the app that fails:
```
@Configuration
@EnableWebSecurity
public class CustomWebSecurityConfig extends WebSecurityConfigurerAdapter {
    @Bean
  @Override
  public AuthenticationManager authenticationManagerBean() throws Exception {

    // http://stackoverflow.com/questions/24865588/how-to-enable-secured-annotations-with-java-based-configuration
    return super.authenticationManagerBean();
  }
}
```

This one stopped working with spring boot 1.3.0 and I have to provide my own authentication manager as you suggested.

**Comment by hohwille** [comment]
Debugging the error leads into ```org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray``` 

This invokes this code:
```
					MethodParameter param = MethodParameter.forMethodOrConstructor(methodOrCtor, paramIndex);
					Object autowiredArgument = resolveAutowiredArgument(param, beanName, autowiredBeanNames, converter);
```

Here the value of ```methodOrCtor``` is:
```
public org.springframework.boot.context.embedded.DelegatingFilterProxyRegistrationBean org.springframework.boot.autoconfigure.security.SecurityFilterAutoConfiguration.securityFilterChainRegistration(org.springframework.boot.autoconfigure.security.SecurityProperties)
```

**Comment by hohwille** [comment]
I can also start the app with this annotation but still get the wrong security behaviour:
```
@SpringBootApplication(exclude = { SecurityAutoConfiguration.class, SecurityFilterAutoConfiguration.class })
```

Maybe it seems that my problem from here is not related to spring boot any more but to spring-security. I need some more investigation. I hoped the updated would be easier... We will see - maybe there will be an easy fix but it might be not so easy to find it...

**Comment by hohwille** [comment]
In case it helps. Here is my configure implementation of WebSecurityConfig for the problematic app:
```
  @Override
  protected void configure(HttpSecurity http) throws Exception {

    http.sessionManagement().sessionCreationPolicy(SessionCreationPolicy.NEVER) //
        .and().csrf().disable() //
        .authorizeRequests().anyRequest().authenticated() //
        .and().headers().frameOptions().disable().and() //
        .addFilterAfter(this.authenticationFilter, LogoutFilter.class);
  }
```
The authentication filter actually reads a JWT from OAuth2 bearer header and verifies it. On success it will consider the request as authenticated via:
```
      SecurityContextHolder.getContext().setAuthentication(authentication);
```

I could refactor this somehow to an implementation of ```AuthenticationManager``` or ```AuthenticationProvider``` but IMHO this is not at all related to my problem. The remaining problem is that still some magic is interfering my security config that did not take place in spring-boot 1.2.3 and spring 4.1.7.

**Comment by hohwille** [comment]
I just discovered that whenever I get the strange redirects to security/html/login.html I also always get this exception in the logs:
```
Caused by: org.apache.catalina.connector.ClientAbortException: java.io.IOException: An established connection was aborted by the software in your host machine
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:353) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:317) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.apache.catalina.connector.Response.flushBuffer(Response.java:510) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.apache.catalina.connector.ResponseFacade.flushBuffer(ResponseFacade.java:318) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
	at javax.servlet.ServletResponseWrapper.flushBuffer(ServletResponseWrapper.java:176) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
	at javax.servlet.ServletResponseWrapper.flushBuffer(ServletResponseWrapper.java:176) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.springframework.security.web.context.OnCommittedResponseWrapper.flushBuffer(OnCommittedResponseWrapper.java:143) ~[spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.security.web.context.SaveContextOnUpdateOrErrorResponseWrapper.flushBuffer(SaveContextOnUpdateOrErrorResponseWrapper.java:40) ~[spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.apache.cxf.transport.http.AbstractHTTPDestination$WrappedOutputStream.close(AbstractHTTPDestination.java:793) ~[cxf-rt-transports-http-3.0.6.jar:3.0.6]
	at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56) ~[cxf-core-3.0.6.jar:3.0.6]
	at org.apache.cxf.transport.http.AbstractHTTPDestination$BackChannelConduit.close(AbstractHTTPDestination.java:722) ~[cxf-rt-transports-http-3.0.6.jar:3.0.6]
	at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:62) ~[cxf-core-3.0.6.jar:3.0.6]
	... 90 common frames omitted
Caused by: java.io.IOException: An established connection was aborted by the software in your host machine
	at sun.nio.ch.SocketDispatcher.write0(Native Method) ~[na:1.8.0_45]
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51) ~[na:1.8.0_45]
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[na:1.8.0_45]
	at sun.nio.ch.IOUtil.write(IOUtil.java:65) ~[na:1.8.0_45]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471) ~[na:1.8.0_45]
	at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:124) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.apache.tomcat.util.net.NioBlockingSelector.write(NioBlockingSelector.java:101) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.apache.tomcat.util.net.NioSelectorPool.write(NioSelectorPool.java:172) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.apache.coyote.http11.InternalNioOutputBuffer.writeToSocket(InternalNioOutputBuffer.java:139) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.apache.coyote.http11.InternalNioOutputBuffer.flushBuffer(InternalNioOutputBuffer.java:244) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.apache.coyote.http11.AbstractOutputBuffer.flush(AbstractOutputBuffer.java:305) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.apache.coyote.http11.AbstractHttp11Processor.action(AbstractHttp11Processor.java:765) [tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.apache.coyote.Response.action(Response.java:177) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:349) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
	... 101 common frames omitted
```

Is there also something broken with the latest tomcat shipped with spring-boot 1.3.0.
It is really heavy that such update more or less upgrades the entire technology stack. This way it is hard to track down errors.

**Comment by wilkinsona** [comment]
> Is there also something broken with the latest tomcat shipped with spring-boot 1.3.0?

Not that I'm aware of. Spring Boot 1.3.0 and 1.2.7 both use Tomcat 8.0.28.

> It is really heavy that such update more or less upgrades the entire technology stack. This way it is hard to track down errors.

Sorry to hear that you've found the upgrade problematic. As this is a new minor release of Spring Boot, we've taken the opportunity to upgrade to new minor versions of other projects (Spring Framework 4.1 to 4.2, for example). We've also, with careful consideration, moved to a new major version of Spring Security which I suspect is what's affecting you the most here. This is [mentioned in the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.3-Release-Notes#spring-security-40) along with a link to Spring Security's migration guide.

**Comment by hohwille** [comment]
Nope. Spring boot 1.2.7 was shipped with tomcat 8.0.20.
See also e.g. here:
https://github.com/spring-projects/spring-boot/issues/3526

**Comment by hohwille** [comment]
> Sorry to hear that you've found the upgrade problematic

No worries. I  do not want to blame anybody. I am just having some trouble and pain. It might turn out as a small and simple problem once found.
In general updating to recent stuff is not a bad thing. However, my motivation for the update was actually just a small issue that has been fixed in spring-boot 1.3.0 and I would have preferred less impact :)

**Comment by wilkinsona** [comment]
> Nope. Spring boot 1.2.7 was shipped with tomcat 8.0.20.

No it wasn't. [1.2.7.RELEASE uses Tomcat 8.0.28](https://github.com/spring-projects/spring-boot/blob/v1.2.7.RELEASE/spring-boot-dependencies/pom.xml#L137).

> See also e.g. here:
#3526

I don't see how that issue is relevant to 1.2.7 as it was fixed in 1.2.6 (and upgraded to Tomcat 8.0.26).

**Comment by wilkinsona** [comment]
> However, my motivation for the update was actually just a small issue that has been fixed in spring-boot 1.3.0 and I would have preferred less impact :)

What was the issue? Perhaps it has been/could be fixed in 1.2.x as well.

**Comment by hohwille** [comment]
OK. My fault I actually updated spring-boot from 1.2.5.RELEASE to 1.3.0.RELEASE.

**Comment by hohwille** [comment]
> What was the issue? Perhaps it has been/could be fixed in 1.2.x as well.

https://github.com/spring-projects/spring-boot/issues/3515

However, I will do further investigation. Updating will come anyway just a question when. If I am already on my way, I will not give up too early. Thanks for all your support and quick reactions. That is really astounding.

**Comment by hohwille** [comment]
So, I downgraded tomcat back to 8.0.20 and that does not change the behaviour:
```
Caused by: java.io.IOException: An established connection was aborted by the software in your host machine
	at sun.nio.ch.SocketDispatcher.write0(Native Method) ~[na:1.8.0_45]
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51) ~[na:1.8.0_45]
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[na:1.8.0_45]
	at sun.nio.ch.IOUtil.write(IOUtil.java:65) ~[na:1.8.0_45]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471) ~[na:1.8.0_45]
	at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:127) ~[tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.tomcat.util.net.NioBlockingSelector.write(NioBlockingSelector.java:101) ~[tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.tomcat.util.net.NioSelectorPool.write(NioSelectorPool.java:173) ~[tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.coyote.http11.InternalNioOutputBuffer.writeToSocket(InternalNioOutputBuffer.java:139) ~[tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.coyote.http11.InternalNioOutputBuffer.flushBuffer(InternalNioOutputBuffer.java:244) ~[tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.coyote.http11.AbstractOutputBuffer.flush(AbstractOutputBuffer.java:305) ~[tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.coyote.http11.AbstractHttp11Processor.action(AbstractHttp11Processor.java:764) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.coyote.Response.action(Response.java:179) ~[tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:349) ~[tomcat-embed-core-8.0.20.jar:8.0.20]
	... 102 common frames omitted
```
As you can see by logbacks enhancements this was produced by tomcat 8.0.20 now. That is the version I was using before and that used to work.
I guess this error is not a bug in tomcat but some higher level problem where a buffer is flushed that has already been closed or something in case anything else gets damn wrong.

So what I can conclude so far:
* tomcat update is not related to my problem.
* the actual error I initially reported has already been clarified. I need to exclude ```SecurityFilterAutoConfiguration``` after updating to boot 1.3.0.
* however, there is still something wrong with what is going on with spring-security and its auto-config. I will dig further and let you know. We will then see if we can close this as invalid in the end or if something in boot shall also be changed/fixed.

**Comment by hohwille** [comment]
BTW: to downgrade tomcat it does not help to downgrade the version of spring-boot-starter-tomcat:
```
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-tomcat</artifactId>
      <version>1.2.3.RELEASE</version>
      <scope>provided</scope>
   </depenency>
```

Due to the dependency management I really had to do this:
```
    <dependency>
      <groupId>org.apache.tomcat.embed</groupId>
      <artifactId>tomcat-embed-core</artifactId>
      <version>8.0.20</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.tomcat.embed</groupId>
      <artifactId>tomcat-embed-el</artifactId>
      <version>8.0.20</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.tomcat.embed</groupId>
      <artifactId>tomcat-embed-logging-juli</artifactId>
      <version>8.0.20</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.tomcat.embed</groupId>
      <artifactId>tomcat-embed-websocket</artifactId>
      <version>8.0.20</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.tomcat</groupId>
      <artifactId>tomcat-jdbc</artifactId>
      <version>8.0.20</version>
    </dependency>
    <dependency>
      <groupId>org.apache.tomcat</groupId>
      <artifactId>tomcat-juli</artifactId>
      <version>8.0.20</version>
    </dependency>
```

This makes it not so easy to choose the version of tomcat independent from spring-boot itself.

**Comment by wilkinsona** [comment]
Can we please try to keep this issue focused on the problem with `SecurityProperties`? It doesn't help having multiple problems in the same issue.

That said, [as described in the documentation](This is [covered in the documentation]()), all you need to do to change the version of Tomcat is to configure the `tomcat.version` property:

```
<properties>
    <tomcat.version>8.0.20</tomcat.version>
</properties>

**Comment by hohwille** [comment]
I also found a problem related to the 403 problem.
Spring security seems to append the prefix "ROLE_" to the value annotated in @RolesAllowed what makes the jsr250 voter to fail as the granted authorities are without this prefix. I never understood what this strange prefix is for in spring-security that I already hit in other contexts before. I need to trace down who is appending this and how to stop it.

**Comment by hohwille** [comment]
In ```Jsr250MethodSecurityMetadataSource``` you can find the source of the prefix:

```
	private String defaultRolePrefix = "ROLE_";
```

It can be set using ```setDefaultRolePrefix```. I have no clue why it was empty before the update and now is the default "ROLE_". Maybe something changed in spring-security or in the auto-config of spring-boot.

**Comment by hohwille** [comment]
My spring boot application is annotated with this:
```
@EnableGlobalMethodSecurity(jsr250Enabled = true)
```

**Comment by hohwille** [comment]
I added this to my WebSecurityConfig 
```
  @Inject
  public void setJsr250MethodSecurityMetadataSource(Jsr250MethodSecurityMetadataSource source) {

    source.setDefaultRolePrefix("");
  }
```

Now, the problem is gone. I still have to trace down the source of the redirect after the 403. But that one might also be on my side.
I am still unsure if the way I "solved" the problem with the role prefix is a "hack" and there is a way more elegant way to set the role prefix - I assume so.
I also still do not know why the role prefix changed due to the update.

**Comment by jebeaudet** [comment]
Spring Security 4.0 has changed the way it handles the ROLE_ prefix : 
http://docs.spring.io/spring-security/site/migrate/current/3-to-4/html5/migrate-3-to-4-jc.html#m3to4-role-prefixing

**Comment by hohwille** [comment]
Thanks for the hint. Not a nice workaround.
DefaultRolesPrefixPostProcessor could have a prefix property given at construction time and could be provided by spring out of the box so I would only need:
```
@Bean
public static DefaultRolesPrefixPostProcessor defaultRolesPrefixPostProcessor() {
	return new DefaultRolesPrefixPostProcessor(MY_ROLE_PREFIX);
}
```

**Comment by hohwille** [comment]
Everything is clarified now. The url "/security/html/login.html" was no server-side redirect and came from the client (written by my colleague) as a reaction to the 403 error that is now resolved.
Nothing has to be fixed in spring-boot. Thanks for the support.

**Comment by GitoMat** [comment]
I actually got this problem after upgrading from 1.3.0.M4 to 1.3.0.M5. Removing @EnableAutoConfiguration(exclude = { SecurityAutoConfiguration.class }) seems to have fixed it, but I can't yet say if this broke anything else.

**Comment by reddynr** [comment]
Hi All ,

Please advice on below error is much helpful. Thanks

I am getting error : **No qualifying bean of type** [com.bns.mcac.config.DatabaseConfig] found for dependency [com.bns.mcac.config.DatabaseConfig]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
