### ISSUE TITLE
1.3.0  @EnableRedisHttpSession  ignoring Profile configuration  

### ISSUE THREAD

**Issue by jhernandezgt** [spring-projects/spring-boot#4528]
Upgrading from 1.2.7 to 1.3.0 is ignoring the current profile in the  configuration and the application startup will fail because keeps trying to connect to a redis instance 
```  
@Configuration
@Profile(PROFILE_PROD)
@EnableRedisHttpSession
public class ProdSessionConfig {

    @Bean
    HeaderHttpSessionStrategy sessionStrategy() {
        return new HeaderHttpSessionStrategy();
    }

}
2015-11-17 23:08:56.697  INFO 12356 --- [           main] Application         : The following profiles are active: dev
2015-11-17 23:09:03.973 ERROR 12356 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'enableRedisKeyspaceNotificationsInitializer' defined in class path resource [org/springframework/session/data/redis/config/annotation/web/http/RedisHttpSessionConfiguration.class]: Invocation of init method failed; nested exception is org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:838) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:347) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:295) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1112) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1101) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
```

**Comment by wilkinsona** [comment]
The problem isn't that your profile is being ignored, but that [1.3 now provides auto-configuration for Spring Session](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.3-Release-Notes#spring-session). You could either disable the auto-configuration all the time and continue with your current approach or disable it only in your dev profile and use the auto-configuration in production. One way to achieve the latter is to use a profile-specific properties file (`application-dev.properties` and the `spring.autoconfigure.exclude` property.

**Comment by zxkane** [comment]
I met the same issue. I'm using `redis` in production for cache and session. And the code uses in-memory cache for integration test without redis. Above exceptions breaks all test cases now.

@wilkinsona , could you shed the light on what the exact class should be excluded via `spring.autoconfigure.exclude` property. I tried to exclude `org.springframework.session.data.redis.config.annotation.web.http.RedisHttpSessionConfiguration`, but it does not work.

**Comment by zxkane** [comment]
It works again after excluding `org.springframework.boot.autoconfigure.session.SessionAutoConfiguration`.

**Comment by jhernandezgt** [comment]
I followed the exclusion with your example on my application-dev.properties 

 spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.session.SessionAutoConfiguration 

This works and doesn't try connect to redis anymore but other features like HeaderHttpSessionStrategy  are now disabled with this exclude, any ideas?

**Comment by wilkinsona** [comment]
@jhernandezgt I don't see how that's any different to what you were doing before. From the code you've shown `HeaderHttpSessionStrategy` would have been disabled unless the prod profile was active.

**Comment by jhernandezgt** [comment]
I have a different SessionConfig with @Profile(PROFILE_DEV) which only have
the HeaderHttpSessionStrategy without the Redis annotation

**Comment by wilkinsona** [comment]
Ok. Sounds to me like you should continue with that approach.
