### ISSUE TITLE
/restart endpoint fails with 'IllegalStateException: Servlets can not be added to context'

### ISSUE THREAD

**Issue by rshan2** [spring-projects/spring-boot#4544]
I generated a spring boot app with web support via Eclipse Spring Starter Project.

To enable context restarting I added spring-boot-starter-actuator and spring-cloud-context to the pom.xml and endpoints.restart.enabled=true to application.properties.

When I post to the /restart endpoint the context successfully closes and restarts, but then it all falls apart when the EmbeddedWebApplicationContext attempts to register a servlet.

    2015-11-18 20:04:25.439 ERROR 34393 --- [       Thread-5] o.s.boot.SpringApplication               : Application startup failed

    org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is java.lang.IllegalStateException: Servlets can not be added to context /demo as the context has been initialised
	    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:133) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	    at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:347) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	    at org.springframework.boot.SpringApplication.run(SpringApplication.java:295) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	    at org.springframework.cloud.context.restart.RestartEndpoint.restart(RestartEndpoint.java:161) [spring-cloud-context-1.0.2.RELEASE.jar:1.0.2.RELEASE]
	    at org.springframework.cloud.context.restart.RestartEndpoint.invoke(RestartEndpoint.java:95) [spring-cloud-context-1.0.2.RELEASE.jar:1.0.2.RELEASE]
	    at org.springframework.cloud.context.restart.RestartEndpoint.invoke(RestartEndpoint.java:44) [spring-cloud-context-1.0.2.RELEASE.jar:1.0.2.RELEASE]
	    at org.springframework.boot.actuate.endpoint.mvc.AbstractEndpointMvcAdapter.invoke(AbstractEndpointMvcAdapter.java:53) [spring-boot-actuator-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	    at org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke(EndpointMvcAdapter.java:45) [spring-boot-actuator-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	    at org.springframework.cloud.context.restart.RestartMvcEndpoint.access$001(RestartMvcEndpoint.java:37) [spring-cloud-context-1.0.2.RELEASE.jar:1.0.2.RELEASE]
	    at org.springframework.cloud.context.restart.RestartMvcEndpoint$1.run(RestartMvcEndpoint.java:54) [spring-cloud-context-1.0.2.RELEASE.jar:1.0.2.RELEASE]
	    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
    Caused by: java.lang.IllegalStateException: Servlets can not be added to context /demo as the context has been initialised
	    at org.apache.catalina.core.ApplicationContext.addServlet(ApplicationContext.java:1063) ~[catalina.jar:8.0.20]
	    at org.apache.catalina.core.ApplicationContext.addServlet(ApplicationContext.java:1027) ~[catalina.jar:8.0.20]
	    at org.apache.catalina.core.ApplicationContextFacade.addServlet(ApplicationContextFacade.java:522) ~[catalina.jar:8.0.20]
	    at org.springframework.boot.context.embedded.ServletRegistrationBean.onStartup(ServletRegistrationBean.java:190) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.selfInitialize(EmbeddedWebApplicationContext.java:223) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.access$000(EmbeddedWebApplicationContext.java:85) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext$1.onStartup(EmbeddedWebApplicationContext.java:207) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:162) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:130) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	... 13 common frames omitted

Environment:
Java 8
Tomcat 8
Spring Boot 1.3.0.RELEASE
spring-cloud-context 1.0.2.RELEASE

pom.xml:

    <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    	<modelVersion>4.0.0</modelVersion>
    
    	<groupId>com.example</groupId>
    	<artifactId>demo</artifactId>
    	<version>0.0.1-SNAPSHOT</version>
    	<packaging>war</packaging>
    
    	<name>demo</name>
    	<description>Demo project for Spring Boot</description>
    
    	<parent>
    		<groupId>org.springframework.boot</groupId>
    		<artifactId>spring-boot-starter-parent</artifactId>
    		<version>1.3.0.RELEASE</version>
    		<relativePath/> 
    	</parent>
    
    	<properties>
    		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    		<java.version>1.8</java.version>
    	</properties>
    
    	<dependencies>
    		<dependency>
    			<groupId>org.springframework.boot</groupId>
    			<artifactId>spring-boot-starter-actuator</artifactId>
    		</dependency>
    		<dependency>
    			<groupId>org.springframework.boot</groupId>
    			<artifactId>spring-boot-starter-web</artifactId>
    		</dependency>
    		<dependency>
    			<groupId>org.springframework.boot</groupId>
    			<artifactId>spring-boot-starter-tomcat</artifactId>
    			<scope>provided</scope>
    		</dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-context</artifactId>
                <version>1.0.2.RELEASE</version>
            </dependency>
      
    		<dependency>
    			<groupId>org.springframework.boot</groupId>
    			<artifactId>spring-boot-starter-test</artifactId>
    			<scope>test</scope>
    		</dependency>
    	</dependencies>
    	
    	<build>
    		<plugins>
    			<plugin>
    				<groupId>org.springframework.boot</groupId>
    				<artifactId>spring-boot-maven-plugin</artifactId>
    			</plugin>
    		</plugins>
    	</build>
    	
    	<repositories>
    		<repository>
    			<id>spring-snapshots</id>
    			<name>Spring Snapshots</name>
    			<url>https://repo.spring.io/snapshot</url>
    			<snapshots>
    				<enabled>true</enabled>
    			</snapshots>
    		</repository>
    		<repository>
    			<id>spring-milestones</id>
    			<name>Spring Milestones</name>
    			<url>https://repo.spring.io/milestone</url>
    			<snapshots>
    				<enabled>false</enabled>
    			</snapshots>
    		</repository>
    	</repositories>
    
    </project>

DemoApplication.java

    package com.example;

    import org.springframework.boot.SpringApplication;
    import org.springframework.boot.autoconfigure.SpringBootApplication;

    @SpringBootApplication
    public class DemoApplication {

        public static void main(String[] args) {
            SpringApplication.run(DemoApplication.class, args);
        }
    }

ServletInitializer.java

    package com.example;

    import org.springframework.boot.builder.SpringApplicationBuilder;
    import org.springframework.boot.context.web.SpringBootServletInitializer;

    public class ServletInitializer extends SpringBootServletInitializer {

	    @Override
	    protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
		    return application.sources(DemoApplication.class);
	     }
    }

What configuration override is necessary to make this work?

**Comment by wilkinsona** [comment]
This is really a Spring Cloud issue. To use the restart endpoint you need to use an embedded servlet container.
