### ISSUE TITLE
Support Elasticsearch auto-configuration without Spring Data Elasticsearch

### ISSUE THREAD

**Issue by izeye** [spring-projects/spring-boot#4550]
Spring Data Elasticsearch is nice but sometimes I want to use only Elasticsearch without it but with auto-configuration for Elasticsearch.

It would be nice if Spring Boot supports Elasticsearch auto-configuration without Spring Data Elasticsearch.

**Comment by wgorder** [comment]
+1 on this.  I actually prefer vanilla Elasticsearch with just their API's.

**Comment by snicoll** [comment]
Are you looking for the transport client support or also the embedding?

**Comment by izeye** [comment]
@snicoll I'm using the transport client support. Especially I copied some classes from Spring Data Elasticsearch and modified a little to use Elasticsearch 2.x: https://github.com/izeye/spring-boot-throwaway-branches/tree/elasticsearch-2.2/src/main/java/com/izeye/throwaway

**Comment by snicoll** [comment]
Thanks for the feedback @izeye

**Comment by ak47wyh** [comment]
please help me,thinks!
spring.data.elasticsearch.cluster-name=elasticsearch
spring.data.elasticsearch.cluster-nodes=127.0.0.1:9300

$ curl -XGET http://127.0.0.1:9200/_nodes/http?pretty
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
100 486 100 486 0 0 740 0 --:--:-- --:--:-- --:--:-- 740{
"cluster_name" : "elasticsearch",
"nodes" : {
"Ua1k4rWsTNKP6M5xObho1g" : {
"name" : "Master",
"transport_address" : "127.0.0.1:9300",
"host" : "127.0.0.1",
"ip" : "127.0.0.1",
"version" : "2.3.4",
"build" : "e455fd0",
"http_address" : "127.0.0.1:9200",
"http" : {
"bound_address" : [ "127.0.0.1:9200" ],
"publish_address" : "127.0.0.1:9200",
"max_content_length_in_bytes" : 104857600
}
}
}
}
NoNodeAvailableException[None of the configured nodes are available: []
]
at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290)
at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207)
at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:288)
at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1226)
at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:86)
at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:56)
at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:64)
at com.didispace.domain.esTest2.test(esTest2.java:59)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)

**Comment by bclozel** [comment]
The Java native transport should be deprecated in the future, see [here](https://www.elastic.co/blog/state-of-the-official-elasticsearch-java-clients) and [here](https://www.elastic.co/blog/the-elasticsearch-java-high-level-rest-client-is-out), so we won't add an auto-configuration for that now.

See #12600 for the ElasticSearch REST client support.
