### ISSUE TITLE
TypeNotPresentExceptionProxy thrown when running spring boot application jar

### ISSUE THREAD

**Issue by sebastianmontero** [spring-projects/spring-boot#4579]
Hi, I'm using spring boot 1.2.2.RELEASE and tomcat 8.0.20, when I run my web application from spring tool suite, everything runs without any problems, but when I build the application using mvn clean install, and run the generated jar using java -jar, I get the following stack trace: 

```
 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1566)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
```

**Comment by wilkinsona** [comment]
1.2.2 is quite old now and we've fixed a few of this sort of issue since then. Please try again with 1.2.7. If it still doesn't work please provide a small sample project that reproduces the problem.

**Comment by sebastianmontero** [comment]
Hi, after several hours of trying to solve the problem, I realized that I was building the jar with the option "Resolve Workspace artifacts" enabled, and I believe that was causing the problem. It's working now.

Thank you for your help.

**Comment by wilkinsona** [comment]
@sebastianmontero Thanks for following up. I'm glad to hear you figured out the problem

**Comment by Bokigetk** [comment]
java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
I got this error when trying to intergate swagger ui with spring mvc. please you help me or give me any suggestion. Thank in advance.

**Comment by snicoll** [comment]
@Bokigetk as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Please ask questions on StackOverflow.
