### ISSUE TITLE
Multiple DataSource doesn't work any more after upgrade to boot 1.3.0 Release

### ISSUE THREAD

**Issue by stevenguo** [spring-projects/spring-boot#4580]
The root cause is related with transaction manager configuration, it always failed for different reasons listed below.

I have multiple data source, my original configuration works well in boot 1.2.7, here is one data source's tx manager configuration:

```java
@Bean(name = "transactionManagerComplain")
@Primary  
public PlatformTransactionManager transactionManagerComplain(EntityManagerFactoryBuilder builder) {		
     return new JpaTransactionManager(complainEntityManagerFactory(builder).getObject());  
}
```  

After upgrade from 1.2.7 to 1.3.0, this configuration will failed with the following exception:

```
org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'transactionManager' is defined: No matching PlatformTransactionManager bean found for qualifier  'transactionManager' - neither qualifier match nor bean name match!
	at org.springframework.beans.factory.annotation.BeanFactoryAnnotationUtils.qualifiedBeanOfType(BeanFactoryAnnotationUtils.java:100)
	at org.springframework.beans.factory.annotation.BeanFactoryAnnotationUtils.qualifiedBeanOfType(BeanFactoryAnnotationUtils.java:56)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.determineQualifiedTransactionManager(TransactionAspectSupport.java:378)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.determineTransactionManager(TransactionAspectSupport.java:362)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:271)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:131)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
	at com.sun.proxy.$Proxy115.save(Unknown Source)
	at com.csst.complain.service.JPAsearchServiceTests.insertComplain(JPAsearchServiceTests.java:40)
```

After I changed the 1st datasource tx manager's name to the expected one of "transactionManager", it will told me transaction can't be commit. The configuration is like this:

```java
@Bean(name = "transactionManager")
@Primary  
public PlatformTransactionManager transactionManagerComplain(EntityManagerFactoryBuilder builder) {		
     return new JpaTransactionManager(complainEntityManagerFactory(builder).getObject());  
}
```

The exception is:

```
org.springframework.transaction.TransactionSystemException: Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Error while committing the transaction
	at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.validate(BeanValidationEventListener.java:160)
	at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.onPreInsert(BeanValidationEventListener.java:95)
	at org.hibernate.action.internal.EntityInsertAction.preInsert(EntityInsertAction.java:218)
	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:97)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:465)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:351)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:350)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:56)
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1258)
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:425)
	at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101)
	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:177)
	at org.hibernate.jpa.internal.TransactionImpl.commit(TransactionImpl.java:77)
	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:517)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:761)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:730)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:485)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:291)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:131)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
	at com.sun.proxy.$Proxy115.save(Unknown Source)
	at com.csst.complain.service.JPAsearchServiceTests.insertComplain(JPAsearchServiceTests.java:40)
```

Here is the test case:

```
@Before
public void insertComplain(){

	Complain complain = new Complain();
	complain.setCreatedBy("userId");
	complain.setTitle("bb");
	complain.setDescription("despription1");
	repo.save(complain);
}
```

All work well in Boot 1.2.7.

**Comment by snicoll** [comment]
@olivergierke and I discussed this and I don't really get where that could be coming from. Can you share a sample please?

**Comment by eugene-kamenev** [comment]
@stevenguo We have two hibernate/jpa configuration in same app. We made this by this example: https://github.com/drumonii/SpringBootTwoDataSources 
btw we didnt used two datasources before with spring boot versions less than 1.3.0.RELEASE

**Comment by stevenguo** [comment]
@eugene-kamenev @snicoll Thanks for your help! I can make it work by following @eugene-kamenev 's example. 

In 1.2.7, I didn't implement the following method:
@Bean(name = PRIMARY_ENTITY_MANAGER)
	@Primary
	public EntityManager entityManager(
			@Qualifier(PRIMARY_ENTITY_MANAGER_FACTORY) EntityManagerFactory entityManagerFactory) {
		return entityManagerFactory.createEntityManager();
	}

and I have one minor bean validation problem before save the object, but it seemed that it can work in 1.2.7, but 1.3.0 gave me a bean validation error (it seemed that 1.3.0 works as expected than 1.2.7).

**Comment by alex-sherwin** [comment]
Spring boot 1.3.0 moves to spring framework 4.2.0, where I also started to encounter the same scenario (I wasn't using spring boot, but upgrading from spring 4.0 to 4.3)

I was using the `@Transactional`, where previously the `value` could be set to the same `@Qualifier` value used to define the `PlatformTransactionManager`

After upgrading to Spring 4.3 this stopped working with the same `No matching PlatformTransactionManager bean found for qualifier` error

`@Transactional` added a new `transactionManager` attribute which I set to the value of the secondary `PlatformTransactionManager`'s bean name instead of qualifier and it started working again as expected.  I'm not sure if this is a bug in Spring, as the docs claim you can use the qualifier or bean name of the `PlatformTransactionManager`, but in practice I'm only seeing the bean name work

**Comment by snicoll** [comment]
@alex-sherwin I am not sure what you are reporting here and you've found out yourself that this is Spring Framework specific (and this isn't the Spring Framework issue tracker). If you're still having a problem, please create a new issue, preferably with a sample, on [the spring framework issue tracker](https://jira.spring.io/browse/SPR/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). Thanks!
