### ISSUE TITLE
Failed to unregister Commons DBCP2 DataSource XMbean.

### ISSUE THREAD

**Issue by hantsy** [spring-projects/spring-boot#4659]
Exception caught when stop a Spring Boot application by Ctrl+C.

	javax.management.InstanceNotFoundException: org.apache.commons.dbcp2:name=dataSource,type=BasicDataSource
		at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095)
		at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.exclusiveUnregisterMBean(DefaultMBeanServerInterceptor.java:427)
		at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.unregisterMBean(DefaultMBeanServerInterceptor.java:415)
		at com.sun.jmx.mbeanserver.JmxMBeanServer.unregisterMBean(JmxMBeanServer.java:546)
		at org.apache.commons.dbcp2.BasicDataSource.close(BasicDataSource.java:1822)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:483)

Same as the discussion on stackoverflow:

http://stackoverflow.com/questions/24947717/failed-to-unregister-datasource-jmx-mbean-while-shutting-down-a-spring-boot-appl

**Comment by wilkinsona** [comment]
With Commons DBCP2 2.1.1, the exception isn't thrown, it's just logged as a warning. Perhaps that's different in the version you're using? All it's telling you, albeit rather noisily, is that something has already unregistered the MBean. You can safely ignored the warning.

A bit more detail if you're interested:

By default, Spring Boot will auto-configure an `AnnotationMBeanExporter` for you. This component will register any MBeans that are published as Spring beans with the MBean server. It will then also unregister those MBeans for you when your application is shut down. You can disable this functionality by setting `spring.jmx.enabled` to `false`.

`BasicDataSource` implements `AutoCloseable`. This means that, as it's exposed as a Spring bean, its `close` method will be called automatically when your application is shut down. This `close` method also attempts to unregister the MBean and logs the exception as a result of `AnnotationMBeanExporter` having already unregistered it.

If the order is reversed, so that `BasicDataSource` is closed before `AnnotationMBeanExporter`, you'll get a different log message indicating that the MBean could not be unregistered, but it's more friendly as it doesn't include the (unnecessary, imo) exception:

```
2015-12-02 17:32:02.680  WARN 63700 --- [       Thread-2] o.s.j.e.a.AnnotationMBeanExporter        : Could not unregister MBean [org.apache.commons.dbcp2:name=dataSource,type=BasicDataSource] as said MBean is not registered (perhaps already unregistered by an external process)
```

**Comment by Areii** [comment]
I think your problem is caused by your datasource  isn't use @Bean(destroyMethod = "close")

**Comment by nenaraab** [comment]
In DBCP2 2.1.1 it's logged as a warning that includes the exception stack.

**Comment by jonfreedman** [comment]
Sadly I think the best solution to fixing these warnings & also avoiding the unpleasant situation where the datasources are registered with JMX twice is to switch to https://github.com/brettwooldridge/HikariCP
