### ISSUE TITLE
Release 1.3.0 doesn't work with GAE

### ISSUE THREAD

**Issue by jamesclark92** [spring-projects/spring-boot#4662]
When using
```
<parent>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-parent</artifactId>
  <version>1.1.0.BUILD-SNAPSHOT</version>
</parent>
 ```
and uploading to Google App Engine, you get the following error:

```
Failed startup of context com.google.apphosting.utils.jetty.RuntimeAppEngineWebAppContext@1b9f3bd{/,/base/data/home/apps/e~football-preds/1.388980235875970012}
    java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "modifyThreadGroup")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:382)
        at java.security.AccessController.checkPermission(AccessController.java:572)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
        at com.google.apphosting.runtime.security.CustomSecurityManager.checkPermission(CustomSecurityManager.java:55)
        at com.google.apphosting.runtime.security.CustomSecurityManager.checkAccess(CustomSecurityManager.java:136)
        at java.lang.ThreadGroup.checkAccess(ThreadGroup.java:315)
        at java.lang.Thread.init(Thread.java:391)
        at java.lang.Thread.init(Thread.java:349)
        at java.lang.Thread.<init>(Thread.java:675)
        at java.util.concurrent.Executors$DefaultThreadFactory.newThread(Executors.java:572)
        at java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:600)
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:943)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1383)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:110)
        at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:638)
        at org.springframework.boot.autoconfigure.BackgroundPreinitializer.submit(BackgroundPreinitializer.java:50)
        at org.springframework.boot.autoconfigure.BackgroundPreinitializer.onApplicationEvent(BackgroundPreinitializer.java:43)
        at org.springframework.boot.autoconfigure.BackgroundPreinitializer.onApplicationEvent(BackgroundPreinitializer.java:37)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:119)
        at org.springframework.boot.context.event.EventPublishingRunListener.publishEvent(EventPublishingRunListener.java:111)
        at org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:60)
        at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:48)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:293)
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
        at org.springframework.boot.legacy.context.web.SpringBootContextLoaderListener.initWebApplicationContext(SpringBootContextLoaderListener.java:61)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
        at org.mortbay.jetty.handler.ContextHandler.startContext(ContextHandler.java:548)
        at org.mortbay.jetty.servlet.Context.startContext(Context.java:136)
        at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1250)
        at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:517)
        at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:467)
        at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
        at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.createHandler(AppVersionHandlerMap.java:206)
        at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.getHandler(AppVersionHandlerMap.java:179)
        at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:136)
        at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:469)
        at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437)
        at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444)
        at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:256)
        at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308)
        at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300)
        at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441)
        at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:235)
```

**Comment by philwebb** [comment]
Google App Engine is unfortunately a Servlet 2.5 container so you need to do some work to get things to run. Did you follow [this section](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#cloud-deployment-gae) of the reference documentation?

Is this something that you've previously had working and now fails? Or is this the first time you're tring GAE?

**Comment by wilkinsona** [comment]
@philwebb This problem's new in 1.3 due to the introduction of BackgroundPreinitializer. I think we either need to disable it on GAE, or we need to configure the executor to use [GAE's custom thread factory](https://cloud.google.com/appengine/docs/java/javadoc/com/google/appengine/api/ThreadManager#currentRequestThreadFactory()).

**Comment by philwebb** [comment]
:hankey:

**Comment by philwebb** [comment]
Disabling it or catching and swallowing the exception is probably the best option.

**Comment by jamesclark92** [comment]
@wilkinsona So what is the latest version I can use?

**Comment by wilkinsona** [comment]
@jamesclark92 1.2.7.RELESE

**Comment by philwebb** [comment]
You'll still need to follow the instructions in the reference docs and use the `spring-boot-legacy` project I think.

**Comment by jamesclark92** [comment]
Yes that's what I have followed. There is a github project with an example that works using 1.1.0
