### ISSUE TITLE
Allow exit codes to be deduced from Exceptions

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#4803]
As part of the spring-task work it would be nice if specific exit codes could be generated by exceptions. 

Currently exit code generation looks like this:

```java
		System.exit(SpringApplication
				.exit(SpringApplication.run(SampleBatchApplication.class, args)));
```

It would be nice if you could just throw an exception from a command line runner and if it implements `ExitCodeGenerator` have the appropriate code returned.

**Comment by philwebb** [comment]
We need a way to also map exceptions without needing then to  implement the interface.

**Comment by wilkinsona** [comment]
Reopening as I'm seeing an NPE on master:

```
java.lang.NullPointerException: null
	at org.springframework.boot.SpringApplication.getExitCodeFromMappedException(SpringApplication.java:886) [classes/:na]
	at org.springframework.boot.SpringApplication.getExitCodeFromException(SpringApplication.java:875) [classes/:na]
	at org.springframework.boot.SpringApplication.handeExitCode(SpringApplication.java:861) [classes/:na]
	at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:832) [classes/:na]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:318) [classes/:na]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1180) [classes/:na]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1169) [classes/:na]
	at sample.data.mongo.SampleMongoApplication.main(SampleMongoApplication.java:59) [classes/:na]
```

I think it's because there's no mapper in the context and `SpringApplication` tries to call it anyway

**Comment by wilkinsona** [comment]
It's actually because `context` is null which will happen whenever refresh fails. Given that, I'm not sure how useful the mapping is.

**Comment by wilkinsona** [comment]
To answer my own question, the mapping is still useful when (and is primarily intended for) a command line runner throwing an exception.
