### ISSUE TITLE
NPE in devtools when restarting an application that uses the Log4j2 API

### ISSUE THREAD

**Issue by mrumpf** [spring-projects/spring-boot#4822]
When the application uses the Log4j2 API, the current implementation of the ```Log4j2RestartListener``` runs into a NPE when trying to make a private method accessible, which is not present:

```
2015-12-21 16:55:00.410 DEBUG 12620 --- [   File Watcher] o.s.boot.devtools.restart.Restarter: Restarting application
java.lang.NullPointerException
	at org.springframework.util.ReflectionUtils.makeAccessible(ReflectionUtils.java:439)
	at org.springframework.boot.devtools.log4j2.Log4J2RestartListener.prepareLog4J2ForRestart(Log4J2RestartListener.java:51)
	at org.springframework.boot.devtools.log4j2.Log4J2RestartListener.beforeRestart(Log4J2RestartListener.java:43)
	at org.springframework.boot.devtools.restart.Restarter.beforeRestart(Restarter.java:331)
	at org.springframework.boot.devtools.restart.Restarter.access$200(Restarter.java:81)
	at org.springframework.boot.devtools.restart.Restarter$2.call(Restarter.java:253)
	at org.springframework.boot.devtools.restart.Restarter$2.call(Restarter.java:249)
	at org.springframework.boot.devtools.restart.Restarter$LeakSafeThread.run(Restarter.java:602)
```

The application setup is to use logback as backend logger implementation and to redirect log4j2 to slf4j (via ```log4j-to-slf4j.jar```). In this case there is the class ```org.apache.logging.log4j.LogManager``` on the classpath (via ```log4j-api.jar```), but it seems as if the method ```shutdownCallbackRegistry``` is not available on the class ```SLF4JLoggerContextFactory```, which is generated by the ```getFactory``` method:
https://github.com/apache/logging-log4j2/blob/master/log4j-to-slf4j/src/main/java/org/apache/logging/slf4j/SLF4JLoggerContextFactory.java

This causes all my services to suddenly stop (disappear from the Spring Boot Dashboard) when a change is detected and dependent applications are restarted.

Version 2.5 of the Log4j2 libs is used.

**Comment by mrumpf** [comment]
In this case the ```SLF4JLoggerContextFactory``` implementation is used, which does not have the ```shutdownCallbackRegistry```method:
https://github.com/apache/logging-log4j2/blob/master/log4j-to-slf4j/src/main/java/org/apache/logging/slf4j/SLF4JLoggerContextFactory.java

**Comment by mrumpf** [comment]
What seems to be wrong here is the check for existence of the class ```org.apache.logging.log4j.LogManager```. This class is available in thje JAR file ```log4j-api.jar```. The check needs to look for a class which is only available in the core Log4j2 library.

So the code should look for the class, which is only available in the ```log4j-core.jar```:
https://github.com/apache/logging-log4j2/blob/master/log4j-core/src/main/java/org/apache/logging/log4j/core/impl/Log4jContextFactory.java
This is the same class which provides the field: ```shutdownCallbackRegistry```.

**Comment by snicoll** [comment]
Interesting, thanks. We should also change the same class in `LoggingSystem`

**Comment by snicoll** [comment]
Closing in favour of the PR (#4831)
