### ISSUE TITLE
Spring boot in Grails is trying is read my maven settings.xml and failing to create app

### ISSUE THREAD

**Issue by bond-** [spring-projects/spring-boot#4826]
Issue ref: https://github.com/grails/grails-core/issues/9487

Grails 3.1.0.M3 was reading my `settings.xml` present in `\<user.home\>/.m2/settings.xml`

Stacktrace:
```
| Error Error occurred running Grails CLI: Failed to determine active profiles:
    Failed to determine activation for profile snc-release at null
 (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
java.lang.IllegalStateException: Failed to determine active profiles:
    Failed to determine activation for profile snc-release at null

	at org.springframework.boot.cli.compiler.maven.MavenSettings.determineActiveProfiles(MavenSettings.java:134)
	at org.springframework.boot.cli.compiler.maven.MavenSettings.<init>(MavenSettings.java:87)
	at org.springframework.boot.cli.compiler.maven.MavenSettingsReader.readSettings(MavenSettingsReader.java:64)
	at org.springframework.boot.cli.compiler.grape.SettingsXmlRepositorySystemSessionAutoConfiguration.getSettings(SettingsXmlRepositorySystemSessionAutoConfiguration.java:47)
	at org.springframework.boot.cli.compiler.grape.SettingsXmlRepositorySystemSessionAutoConfiguration.apply(SettingsXmlRepositorySystemSessionAutoConfiguration.java:38)
	at org.springframework.boot.cli.compiler.grape.AetherGrapeEngineFactory.create(AetherGrapeEngineFactory.java:59)
	at org.grails.cli.profile.repository.MavenProfileRepository.<init>(MavenProfileRepository.groovy:51)
	at org.grails.cli.GrailsCli.createMavenProfileRepository(GrailsCli.groovy:327)
	at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:236)
	at org.grails.cli.GrailsCli.main(GrailsCli.groovy:162)
| Error Error occurred running Grails CLI: Failed to determine active profiles:
    Failed to determine activation for profile snc-release at null
```

`~/.m2/settings.xml`:
I'm having:
```
<profile>
	<id>snc-release</id>
	<activation>
		<file>
			<exists>${user.home}/.m2/some_dumy_file</exists>
		</file>
	</activation>

	<repositories>
		<repository>
			<!-- A repo to be activated -->
		</repository>
	</repositories>
</profile>
```

Workaround:
Delete my old maven `~/.m2/settings.xml`
Bad workaround but only solution to me right now.

**Comment by philwebb** [comment]
It looks like that root exception comes from `org.apache.maven.model.profile.DefaultProfileSelector` but I'm not sure why yet. If you're able to attache a remote debugger to the CLI, grabbing a stacktrace of the root cause would be very helpful.

**Comment by philwebb** [comment]
Not 100% sure if it's a bug our end or not, but we could certainly report more details from the `ModelProblemCollector`.

**Comment by bond-** [comment]
@philwebb Sorry for the inconvenience, but can you tell me the steps to launch it in debug mode. I'm unable to figure out. Please help me out on this one and I'll get you the proper stack trace.

**Comment by wilkinsona** [comment]
@bond- Thanks for the offer, but I've just managed to reproduce the unhelpful error message in a unit test. I think we have all we need now to improve this.

**Comment by wilkinsona** [comment]
The underlying cause of the failure is a `NullPointerException`:

```
java.lang.NullPointerException
	at org.apache.maven.model.profile.activation.FileProfileActivator.isActive(FileProfileActivator.java:140)
	at org.apache.maven.model.profile.DefaultProfileSelector.isActive(DefaultProfileSelector.java:111)
	at org.apache.maven.model.profile.DefaultProfileSelector.getActiveProfiles(DefaultProfileSelector.java:73)
	at org.springframework.boot.cli.compiler.maven.MavenSettings.determineActiveProfiles(MavenSettings.java:129)
```

We should fix the cause of that (if we can) and improve the diagnostics.
