### ISSUE TITLE
-XX:-UseSplitVerifier and Tomcat 7 cause NoClassDefFoundError

### ISSUE THREAD

**Issue by imgx64** [spring-projects/spring-boot#4839]
I had `JAVA_TOOL_OPTIONS='-XX:-UseSplitVerifier'` set for some unrelated reason (third party JAR broken by their so-called "obfuscation", which causes it to break without this option). We also have to use Java 7 and Tomcat 7. The problem is that when both are used together, I get exception `java.lang.NoClassDefFoundError: org/apache/tomcat/util/descriptor/web/ErrorPage: org.apache.tomcat.util.descriptor.web.ErrorPage` when I try to run the Spring Boot application.

To reproduce, create a new Spring Boot application and set these properties in pom.xml:
```
<java.version>1.7</java.version>
<tomcat.version>7.0.67</tomcat.version>
```

Then run the application with **Java 7**
```
java -XX:-UseSplitVerifier -jar target/demo-0.0.1-SNAPSHOT.jar
```

# Important: The bug only happens with Java 7 because -UseSplitVerifier was removed in 8.

Output:
```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.3.1.RELEASE)

2015-12-24 11:51:37.654  INFO 48707 --- [           main] com.example.DemoApplication              : Starting DemoApplication v0.0.1-SNAPSHOT on wsdvirgm with PID 48707 (/Users/csdvirg/workspaces/sts-3.7/demo/target/demo-0.0.1-SNAPSHOT.jar started by csdvirg in /Users/csdvirg/workspaces/sts-3.7/demo)
2015-12-24 11:51:37.657  INFO 48707 --- [           main] com.example.DemoApplication              : No active profile set, falling back to default profiles: default
2015-12-24 11:51:37.786  INFO 48707 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@5a2a7673: startup date [Thu Dec 24 11:51:37 AST 2015]; root of context hierarchy
2015-12-24 11:51:38.892  INFO 48707 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Overriding bean definition for bean 'beanNameViewResolver' with a different definition: replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration$WhitelabelErrorViewConfiguration; factoryMethodName=beanNameViewResolver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/web/ErrorMvcAutoConfiguration$WhitelabelErrorViewConfiguration.class]] with [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter; factoryMethodName=beanNameViewResolver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter.class]]
2015-12-24 11:51:39.615  WARN 48707 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is java.lang.NoClassDefFoundError: org/apache/tomcat/util/descriptor/web/ErrorPage
2015-12-24 11:51:39.621 ERROR 48707 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is java.lang.NoClassDefFoundError: org/apache/tomcat/util/descriptor/web/ErrorPage
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:133) ~[spring-boot-1.3.1.RELEASE.jar!/:1.3.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532) ~[spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.3.1.RELEASE.jar!/:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:764) [spring-boot-1.3.1.RELEASE.jar!/:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:357) [spring-boot-1.3.1.RELEASE.jar!/:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:305) [spring-boot-1.3.1.RELEASE.jar!/:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1124) [spring-boot-1.3.1.RELEASE.jar!/:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1113) [spring-boot-1.3.1.RELEASE.jar!/:1.3.1.RELEASE]
	at com.example.DemoApplication.main(DemoApplication.java:10) [demo-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_80]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_80]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_80]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_80]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53) [demo-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_80]
Caused by: java.lang.NoClassDefFoundError: org/apache/tomcat/util/descriptor/web/ErrorPage
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.configureContext(TomcatEmbeddedServletContainerFactory.java:393) ~[spring-boot-1.3.1.RELEASE.jar!/:1.3.1.RELEASE]
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.prepareContext(TomcatEmbeddedServletContainerFactory.java:203) ~[spring-boot-1.3.1.RELEASE.jar!/:1.3.1.RELEASE]
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.getEmbeddedServletContainer(TomcatEmbeddedServletContainerFactory.java:167) ~[spring-boot-1.3.1.RELEASE.jar!/:1.3.1.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:160) ~[spring-boot-1.3.1.RELEASE.jar!/:1.3.1.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:130) ~[spring-boot-1.3.1.RELEASE.jar!/:1.3.1.RELEASE]
	... 14 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.apache.tomcat.util.descriptor.web.ErrorPage
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[na:1.7.0_80]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[na:1.7.0_80]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_80]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[na:1.7.0_80]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[na:1.7.0_80]
	at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:178) ~[demo-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:142) ~[demo-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[na:1.7.0_80]
	... 19 common frames omitted

2015-12-24 11:51:39.623  INFO 48707 --- [           main] .b.l.ClasspathLoggingApplicationListener : Application failed to start with classpath: [jar:file:/Users/csdvirg/workspaces/sts-3.7/demo/target/demo-0.0.1-SNAPSHOT.jar!/, jar:file:/Users/csdvirg/workspaces/sts-3.7/demo/target/demo-0.0.1-SNAPSHOT.jar!/lib/spring-boot-starter-web-1.3.1.RELEASE.jar!/, jar:file:/Users/csdvirg/workspaces/sts-3.7/demo/target/demo-0.0.1-SNAPSHOT.jar!/lib/spring-boot-starter-1.3.1.RELEASE.jar!/, jar:file:/Users/csdvirg/workspaces/sts-3.7/demo/target/demo-0.0.1-SNAPSHOT.jar!/lib/spring-boot-1.3.1.RELEASE.jar!/, jar:file:/Users/csdvirg/workspaces/sts-3.7/demo/target/demo-0.0.1-SNAPSHOT.jar!/lib/spring-boot-autoconfigure-1.3.1.RELEASE.jar!/, jar:file:/Users/csdvirg/workspaces/sts-3.7/demo/target/demo-0.0.1-SNAPSHOT.jar!/lib/spring-boot-starter-logging-1.3.1.RELEASE.jar!/, jar:file:/Users/csdvirg/workspaces/sts-3.7/demo/target/demo-0.0.1-SNAPSHOT.jar!/lib/logback-classic-1.1.3.jar!/, jar:file:/Users/csdvirg/workspaces/sts-3.7/demo/target/demo-0.0.1-SNAPSHOT.jar!/lib/logback-core-1.1.3.jar!/, jar:file:/Users/csdvirg/workspaces/sts-3.7/demo/target/demo-0.0.1-SNAPSHOT.jar!/lib/slf4j-api-1.7.13.jar!/, jar:file:/Users/csdvirg/workspaces/sts-3.7/demo/target/demo-0.0.1-SNAPSHOT.jar!/lib/jcl-over-slf4j-1.7.13.jar!/, jar:file:/Users/csdvirg/workspaces/sts-3.7/demo/target/demo-0.0.1-SNAPSHOT.jar!/lib/jul-to-slf4j-1.7.13.jar!/, jar:file:/Users/csdvirg/workspaces/sts-3.7/demo/target/demo-0.0.1-SNAPSHOT.jar!/lib/log4j-over-slf4j-1.7.13.jar!/, jar:file:/Users/csdvirg/workspaces/sts-3.7/demo/target/demo-0.0.1-SNAPSHOT.jar!/lib/snakeyaml-1.16.jar!/, jar:file:/Users/csdvirg/workspaces/sts-3.7/demo/target/demo-0.0.1-SNAPSHOT.jar!/lib/spring-boot-starter-tomcat-1.3.1.RELEASE.jar!/, jar:file:/Users/csdvirg/workspaces/sts-3.7/demo/target/demo-0.0.1-SNAPSHOT.jar!/lib/tomcat-embed-core-7.0.67.jar!/, jar:file:/Users/csdvirg/workspaces/sts-3.7/demo/target/demo-0.0.1-SNAPSHOT.jar!/lib/tomcat-embed-el-7.0.67.jar!/, jar:file:/Users/csdvirg/workspaces/sts-3.7/demo/target/demo-0.0.1-SNAPSHOT.jar!/lib/tomcat-embed-logging-juli-7.0.67.jar!/, jar:file:/Users/csdvirg/workspaces/sts-3.7/demo/target/demo-0.0.1-SNAPSHOT.jar!/lib/tomcat-embed-websocket-7.0.67.jar!/, jar:file:/Users/csdvirg/workspaces/sts-3.7/demo/target/demo-0.0.1-SNAPSHOT.jar!/lib/spring-boot-starter-validation-1.3.1.RELEASE.jar!/, jar:file:/Users/csdvirg/workspaces/sts-3.7/demo/target/demo-0.0.1-SNAPSHOT.jar!/lib/hibernate-validator-5.2.2.Final.jar!/, jar:file:/Users/csdvirg/workspaces/sts-3.7/demo/target/demo-0.0.1-SNAPSHOT.jar!/lib/validation-api-1.1.0.Final.jar!/, jar:file:/Users/csdvirg/workspaces/sts-3.7/demo/target/demo-0.0.1-SNAPSHOT.jar!/lib/jboss-logging-3.3.0.Final.jar!/, jar:file:/Users/csdvirg/workspaces/sts-3.7/demo/target/demo-0.0.1-SNAPSHOT.jar!/lib/classmate-1.1.0.jar!/, jar:file:/Users/csdvirg/workspaces/sts-3.7/demo/target/demo-0.0.1-SNAPSHOT.jar!/lib/jackson-databind-2.6.4.jar!/, jar:file:/Users/csdvirg/workspaces/sts-3.7/demo/target/demo-0.0.1-SNAPSHOT.jar!/lib/jackson-annotations-2.6.4.jar!/, jar:file:/Users/csdvirg/workspaces/sts-3.7/demo/target/demo-0.0.1-SNAPSHOT.jar!/lib/jackson-core-2.6.4.jar!/, jar:file:/Users/csdvirg/workspaces/sts-3.7/demo/target/demo-0.0.1-SNAPSHOT.jar!/lib/spring-web-4.2.4.RELEASE.jar!/, jar:file:/Users/csdvirg/workspaces/sts-3.7/demo/target/demo-0.0.1-SNAPSHOT.jar!/lib/spring-aop-4.2.4.RELEASE.jar!/, jar:file:/Users/csdvirg/workspaces/sts-3.7/demo/target/demo-0.0.1-SNAPSHOT.jar!/lib/aopalliance-1.0.jar!/, jar:file:/Users/csdvirg/workspaces/sts-3.7/demo/target/demo-0.0.1-SNAPSHOT.jar!/lib/spring-beans-4.2.4.RELEASE.jar!/, jar:file:/Users/csdvirg/workspaces/sts-3.7/demo/target/demo-0.0.1-SNAPSHOT.jar!/lib/spring-context-4.2.4.RELEASE.jar!/, jar:file:/Users/csdvirg/workspaces/sts-3.7/demo/target/demo-0.0.1-SNAPSHOT.jar!/lib/spring-webmvc-4.2.4.RELEASE.jar!/, jar:file:/Users/csdvirg/workspaces/sts-3.7/demo/target/demo-0.0.1-SNAPSHOT.jar!/lib/spring-expression-4.2.4.RELEASE.jar!/, jar:file:/Users/csdvirg/workspaces/sts-3.7/demo/target/demo-0.0.1-SNAPSHOT.jar!/lib/spring-core-4.2.4.RELEASE.jar!/]
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is java.lang.NoClassDefFoundError: org/apache/tomcat/util/descriptor/web/ErrorPage
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:133)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:764)
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:357)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:305)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1124)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1113)
	at com.example.DemoApplication.main(DemoApplication.java:10)
	... 6 more
Caused by: java.lang.NoClassDefFoundError: org/apache/tomcat/util/descriptor/web/ErrorPage
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.configureContext(TomcatEmbeddedServletContainerFactory.java:393)
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.prepareContext(TomcatEmbeddedServletContainerFactory.java:203)
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.getEmbeddedServletContainer(TomcatEmbeddedServletContainerFactory.java:167)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:160)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:130)
	... 14 more
Caused by: java.lang.ClassNotFoundException: org.apache.tomcat.util.descriptor.web.ErrorPage
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:178)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:142)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 19 more
```

**Comment by imgx64** [comment]
The problem is in [TomcatEmbeddedServletContainerFactory in this line](https://github.com/spring-projects/spring-boot/blob/a87a1f053f7109fc649498c91cfeaa86c2cac38b/spring-boot/src/main/java/org/springframework/boot/context/embedded/tomcat/TomcatEmbeddedServletContainerFactory.java#L684):
```
nativePage = new org.apache.tomcat.util.descriptor.web.ErrorPage();
```

Replacing it with the below line seems to fix the issue:
```
nativePage = BeanUtils.instantiate(ClassUtils
	.forName("org.apache.tomcat.util.descriptor.web.ErrorPage", null));
```
