### ISSUE TITLE
Issue setting up a DataSource

### ISSUE THREAD

**Issue by jinxiyin** [spring-projects/spring-boot#484]
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlSessionFactory' defined in file [D:\FuLiBao\thymeleaf-workspace\epsf-gataway\target\classes\META-INF\spring\mybatis\gw-weixin-mybatis.xml]: Cannot resolve reference to bean 'dataSource' while setting bean property 'dataSource'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.jdbc.TomcatDataSourceConfiguration': Initialization of bean failed; nested exception is java.lang.NoSuchMethodError: org.springframework.boot.autoconfigure.jdbc.TomcatDataSourceConfiguration.setBeanFactory(Lorg/springframework/beans/factory/BeanFactory;)V
    at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:328)
    at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:107)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1456)
    at 
... <snip>
    ... 18 common frames omitted
Caused by: java.lang.NoSuchMethodError: org.springframework.boot.autoconfigure.jdbc.TomcatDataSourceConfiguration.setBeanFactory(Lorg/springframework/beans/factory/BeanFactory;)V
    at org.springframework.boot.autoconfigure.jdbc.TomcatDataSourceConfiguration$$EnhancerBySpringCGLIB$$69617c46.setBeanFactory(<generated>)
    at org.springframework.context.annotation.ConfigurationClassPostProcessor$EnhancedConfigurationBeanPostProcessor.postProcessPropertyValues(ConfigurationClassPostProcessor.java:442)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1185)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
    ... 33 common frames omitted
```

```
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager' 
defined in file [D:\FuLiBao\thymeleaf-workspace\epsf-gataway\target\classes\META-INF\spring\mybatis\gw-weixin-db.xml]: 
Cannot resolve reference to bean 'dataSource' while setting bean property 'dataSource'; nested exception is org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/TomcatDataSourceConfiguration.class]: Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public javax.sql.DataSource org.springframework.boot.autoconfigure.jdbc.TomcatDataSourceConfiguration.dataSource()] threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: 
Cannot determine embedded database driver class for database type NONE. If you want an embedded database please put a supported one on the classpath.
    at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:328)
    at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:107)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1456)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1197)
... <snip>
```

**Comment by xyy8202826** [comment]
In my case I put the application.properties file in the wrong folder.
reference http://stackoverflow.com/a/33451297/5598826
