### ISSUE TITLE
GsonHttpMessageConvertersConfiguration has a @ConditionalOnMissingBean without specifying a bean

### ISSUE THREAD

**Issue by tmeighen** [spring-projects/spring-boot#4841]
Line 48 of GsonHttpMessageConvertersConfiguration has a @ConditionalOnMissingBean annotation that does not specify any bean.

Launching a simple non-web application with 1.3.1.RELEASE results in the following stack trace:

java.lang.IllegalStateException: Error processing condition on org.springframework.boot.autoconfigure.web.GsonHttpMessageConvertersConfiguration$GsonHttpMessageConverterConfiguration.gsonHttpMessageConverter
	at 
...
Caused by: java.lang.IllegalArgumentException: @ConditionalOnMissingBean annotations must specify at least one bean (type, name or annotation)
	at org.springframework.util.Assert.isTrue(Assert.java:68) ~[spring-core-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$BeanSearchSpec.validate(OnBeanCondition.java:279) ~[spring-boot-autoconfigure-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$BeanSearchSpec.<init>(OnBeanCondition.java:275) ~[spring-boot-autoconfigure-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:111) ~[spring-boot-autoconfigure-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47) ~[spring-boot-autoconfigure-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	... 16 common frames omitted

**Comment by snicoll** [comment]
You don't need to specify the type if the annotation is specified on a {{@Bean}} method as the return type is inferred as the thing the annotation should look for. There's nothing wrong with the code you mentioned and it must be more than "a simple non-web application". Can you share a project that exhibits this issue please?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by tmeighen** [comment]
Sorry for not getting back sooner (wrong e-mail configured). 

I've done some more investigation and I'm not sure that this is a valid case. Basically a transitive dependency was pulling in spring-web 4.0.5.RELEASE which obviously conflicts with the version that Spring Boot needs. I built a stripped down project to display the behavior. You can have a look at it and see if the issue is valid or if it's just a matter of misconfiguration. In my particular case excluding the transitive dependency should fix things.
[gson-bug-sample.tar.gz](https://github.com/spring-projects/spring-boot/files/81930/gson-bug-sample.tar.gz)

**Comment by wilkinsona** [comment]
@tmeighen Thanks for taking the time to pull together the sample.

This isn't a valid case but I wonder if the error message could be improved. `GsonHttpMessageConverter` doesn't exist in `spring-web-4.0.5.RELEASE` so the attempt to deduce the type fails.

That's failure's currently logged as a debug message:

```
if (logger.isDebugEnabled()) {
	logger.debug("Unable to deduce bean type for "
			+ methodMetadata.getDeclaringClassName() + "."
			+ methodMetadata.getMethodName(), ex);
}
```

When the configuration is validated (checking for a name, type or annotation) it fails as it was relying on the deduced type. At the point, it would be useful to know the exception that caused the deduction of the type to fail.

**Comment by wilkinsona** [comment]
I've opened #4943 to improve the diagnostics

**Comment by izeye** [comment]
I guess @wilkinsona meant #4934 above :smile:
