### ISSUE TITLE
java.lang.IllegalAccessError when injecting a bean in a multi-modules Boot project + devtools

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#4857]
While trying to find the origin of a Sagan issue (see spring-io/sagan#613), I managed to create a repro project showing the behavior, see spring-projects/spring-boot-issues#44.

```
Caused by: java.lang.IllegalAccessError: class sagan.projects.support.$Proxy114 cannot access its superinterface sagan.projects.support.ProjectMetadataRepository
	at java.lang.reflect.Proxy.defineClass0(Native Method) ~[na:1.8.0_40]
	at java.lang.reflect.Proxy.access$300(Proxy.java:228) ~[na:1.8.0_40]
	at java.lang.reflect.Proxy$ProxyClary.apply(Proxy.java:642) ~[na:1.8.0_40]
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557) ~[na:1.8.0_40]
	at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230) ~[na:1.8.0_40]
	at java.lang.reflect.WeakCache.get(WeakCache.java:127) ~[na:1.8.0_40]
	at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419) ~[na:1.8.0_40]
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:719) ~[na:1.8.0_40]
	at org.springframework.aop.framework.JdkDynamicAopProxy.getProxy(JdkDynamicAopProxy.java:121) ~[spring-aop-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:109) ~[spring-aop-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:208) ~[spring-data-commons-1.11.2.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.initAndReturn(RepositoryFactoryBeanSupport.java:251) ~[spring-data-commons-1.11.2.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:237) ~[spring-data-commons-1.11.2.RELEASE.jar:na]
	at org.springframework.data.jpa.repository.support.JpaRepositoryFactoryBean.afterPropertiesSet(JpaRepositoryFactoryBean.java:92) ~[spring-data-jpa-1.9.2.RELEASE.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	... 47 common frames omitted
```

The setup:

* a multi-modules Boot project
* a `demo-core` module containing a **non-public** Spring Data JPA repository interface
* this repository is then `@Autowired` in a Controller located in a `demo-web` module (getting the previous as a compile dependency)
* devtools as a compile dependency in `demo-web`

To reproduce this issue, one should run the project with the command `./gradlew :demo-web:bootRun`.

Note that there are many workarounds for this:

* making the repository interface `public`
* removing devtools from the classpath
* merging everything into a single module
* running the application from the IDE

**Comment by olivergierke** [comment]
Can't this be solved by adding the necessary configuration using [the means @philwebb added in Boot 1.3](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-devtools-customizing-classload)?

**Comment by wilkinsona** [comment]
Yeah, we think so. It's assigned to me so that I can check that's the case

**Comment by wilkinsona** [comment]
@bclozel Sorry that it took us so long to look at this one.

The project dependency on `demo-core` means that it's added to `demo-web` as a jar file. This means that DevTools doesn't consider it to be eligible for reloading and its classes are loaded via the app class loader. One the other hand, `demo-web` is one the classpath as a folder, is considered eligible for reloading and is loaded via the restart class loader. It's this split across two class loaders that's the problem. It can be avoided by adding a `META-INF/spring-devtools.properties` file to `demo-web` with the following contents:

```
restart.include.demo-core=/demo-core.jar
```
