### ISSUE TITLE
SocialWebAutoConfiguration fails with Thymeleaf 3 as SpringSocialDialect is incompatible

### ISSUE THREAD

**Issue by lukosan** [spring-projects/spring-boot#4858]
e.g.

```
@Configuration
@ConditionalOnClass(SpringTemplateEngine.class)
protected static class SpringSocialThymeleafConfig {
    // snip
}
```

means you cannot go:

```
@EnableAutoConfiguration(exclude={SpringSocialThymeleafConfig.class})
```

You want to do this if you're using Thymleaf3 instead of Thymeleaf2 because SpringTemplateEngine.class does exist but one of the Beans created by SpringSocialThymleafConfig requires Thymeleaf2 so will throw an exception on instantiation.

**Comment by snicoll** [comment]
that is not an auto-configuration class anyway so even if it was public it wouldn't change anything. I guess we should change the condition to only kick in when Thymeleaf 2 is available.

Can you share the exception please? Maybe we can fix that in the process.

**Comment by lukosan** [comment]
Hmm, just gone off on a bit of an adventure by delving into EnableAutoConfigurationImportSelector and you're right that it wouldn't make a difference as it only exludes the classes specifically registered with spring.factories and not their inner @Configuration classes. This means the auto-configuration classes are a bit of an all-or-nothing but I guess that's not too much of a problem cos they can be just reimplemented by whatever code is using them as a dependency.

Anyway, the exception is:
```
Factory method 'springSocialDialect' threw exception; nested exception is java.lang.NoSuchMethodError: org.thymeleaf.dialect.AbstractDialect: method <init>()V not found
```
because AbstractDialect no longer has a no-args constructor in version 3 - so probably not really fixable.

**Comment by snicoll** [comment]
>  This means the auto-configuration classes are a bit of an all-or-nothing 

Not really. Individual inner `@Configuration` classes (and even `@Bean` definitions) may have extra conditions that allow to exclude them. 

Your case here is border line since Spring Boot itself does not support Thymeleaf 3 (#4393).

**Comment by lukosan** [comment]
Yes, rather than "all-or-nothing" a better phrase would be "my-way-or-the-highway" (which as I said is fair enough as no one's forcing you to use them and they're jolly helpful in the main). Thanks for the swift triage.

**Comment by tleveque23** [comment]
We have a similar problem with flywaydb. We need to exclude flywaydb auto-configuration because we are using it differently with our own classes. But the exclude on FlywayAutoConfiguration.class is not working when EndpointAutoConfiguration.class is not excluded because EndpointAutoConfiguration has a inner class "FlywayEndpointConfiguration"!
That means the only way to make our application start is to exclude EndpointAutoConfiguration! And EndpointAutoConfiguration is the main reason we are using Springboot!

**Comment by philwebb** [comment]
@tleveque23 Could you raise a new issue for that one with some more details. The `FlywayEndpointConfiguration` is protected with conditions so it's not immediately obvious why it wouldn't work if `FlywayAutoConfiguration` is excluded. A sample app would also be helpful to show what you mean.

**Comment by wilkinsona** [comment]
The root cause of the failure with `SpringSocialDialect` is:

```
Caused by: java.lang.NoSuchMethodError: org.thymeleaf.dialect.AbstractDialect: method <init>()V not found
	at org.springframework.social.connect.web.thymeleaf.SpringSocialDialect.<init>(SpringSocialDialect.java:47) ~[spring-social-web-1.1.4.RELEASE.jar:1.1.4.RELEASE]
	at org.springframework.boot.autoconfigure.social.SocialWebAutoConfiguration$SpringSocialThymeleafConfig.springSocialDialect(SocialWebAutoConfiguration.java:173) ~[classes/:na]
	at org.springframework.boot.autoconfigure.social.SocialWebAutoConfiguration$SpringSocialThymeleafConfig$$EnhancerBySpringCGLIB$$9131d13a.CGLIB$springSocialDialect$0(<generated>) ~[classes/:na]
	at org.springframework.boot.autoconfigure.social.SocialWebAutoConfiguration$SpringSocialThymeleafConfig$$EnhancerBySpringCGLIB$$9131d13a$$FastClassBySpringCGLIB$$2d5f3596.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356) ~[spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.boot.autoconfigure.social.SocialWebAutoConfiguration$SpringSocialThymeleafConfig$$EnhancerBySpringCGLIB$$9131d13a.springSocialDialect(<generated>) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_102]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	... 91 common frames omitted
```

We can avoid it by requiring `SpringResourceResourceResolver` to be on the classpath. It's part of Thymeleaf's Spring support that exists Thymeleaf 2.1.x but does not exist in 3.0.x.
