### ISSUE TITLE
https + spring boot 1.3.0.RELEASE + tomcat7.0.59 does not work

### ISSUE THREAD

**Issue by rareman** [spring-projects/spring-boot#4869]
application.properties
server.port=443
server.ssl.enabled=true
server.ssl.protocol=TLS
server.ssl.key-alias=hkrt
server.ssl.key-password=123456
server.ssl.key-store=classpath:hkrt.jks
server.ssl.key-store-password=123456
server.tomcat.basedir=tomcat-base

-

https + spring boot 1.3.0.RELEASE + tomcat7.0.59 does not work
https + spring boot 1.2.5.RELEASE + tomcat7.0.59 OK

-

	//spring boot 1.3.0.RELEASE
	try {
		protocol.setKeystoreFile(ResourceUtils.getURL(ssl.getKeyStore()).toString());
	} catch (FileNotFoundException var4) {
		throw new EmbeddedServletContainerException("Could not load key store: " + var4.getMessage(), var4);
	}

	public static URL getURL(String resourceLocation) throws FileNotFoundException {
		Assert.notNull(resourceLocation, "Resource location must not be null");
		if (resourceLocation.startsWith(CLASSPATH_URL_PREFIX)) {
			String path = resourceLocation.substring(CLASSPATH_URL_PREFIX.length());
			ClassLoader cl = ClassUtils.getDefaultClassLoader();
			URL url = (cl != null ? cl.getResource(path) : ClassLoader.getSystemResource(path));
			if (url == null) {
				String description = "class path resource [" + path + "]";
				throw new FileNotFoundException(description +
						" cannot be resolved to URL because it does not exist");
			}
			return url;
		}
		try {
			// try URL
			return new URL(resourceLocation);
		}
		catch (MalformedURLException ex) {
			// no URL -> treat as file path
			try {
				return new File(resourceLocation).toURI().toURL();
			}
			catch (MalformedURLException ex2) {
				throw new FileNotFoundException("Resource location [" + resourceLocation +
						"] is neither a URL not a well-formed file path");
			}
		}
	}

	if(!"PKCS11".equalsIgnoreCase(type) && !"".equalsIgnoreCase(path)) {
		istream = ConfigFileLoader.getInputStream(path);
	}

	//spring boot 1.2.5.RELEASE
	try {
		File ex = ResourceUtils.getFile(ssl.getKeyStore());
		protocol.setKeystoreFile(ex.getAbsolutePath());
	} catch (FileNotFoundException var4) {
		throw new EmbeddedServletContainerException("Could not find key store " + ssl.getKeyStore(), var4);
	}

	public static File getFile(String resourceLocation) throws FileNotFoundException {
		Assert.notNull(resourceLocation, "Resource location must not be null");
		if(resourceLocation.startsWith("classpath:")) {
			String ex = resourceLocation.substring("classpath:".length());
			String description = "class path resource [" + ex + "]";
			ClassLoader cl = ClassUtils.getDefaultClassLoader();
			URL url = cl != null?cl.getResource(ex):ClassLoader.getSystemResource(ex);
			if(url == null) {
				throw new FileNotFoundException(description + " cannot be resolved to absolute file path because it does not exist");
			} else {
				return getFile(url, description);
			}
		} else {
			try {
				return getFile(new URL(resourceLocation));
			} catch (MalformedURLException var5) {
				return new File(resourceLocation);
			}
		}
	}

	if(!"PKCS11".equalsIgnoreCase(type) && !"".equalsIgnoreCase(path)) {
		File ex = new File(path);
		if(!ex.isAbsolute()) {
			ex = new File(System.getProperty("catalina.base"), path);
		}

		istream = new FileInputStream(ex);
	}

-

2016-01-04 14:37:48.165 ERROR 4916 --- [           main] o.apache.catalina.core.StandardService   : Failed to start connector [Connector[org.apache.coyote.http11.Http11NioProtocol-443]]

org.apache.catalina.LifecycleException: Failed to start component [Connector[org.apache.coyote.http11.Http11NioProtocol-443]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154) ~[tomcat-embed-core-7.0.59.jar:7.0.59]
	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:241) ~[tomcat-embed-core-7.0.59.jar:7.0.59]
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.addPreviouslyRemovedConnectors(TomcatEmbeddedServletContainer.java:194) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:151) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:290) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:540) [spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:347) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:295) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1112) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1101) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at com.icardpay.fastpay.Application.main(Application.java:12) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_45]
	at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_45]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144) [idea_rt.jar:na]
Caused by: org.apache.catalina.LifecycleException: service.getName(): "Tomcat";  Protocol handler start failed
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1014) ~[tomcat-embed-core-7.0.59.jar:7.0.59]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) ~[tomcat-embed-core-7.0.59.jar:7.0.59]
	... 18 common frames omitted
Caused by: java.io.FileNotFoundException: E:\springboot\tomcat-base\file:\E:\springboot\hk-fastpay\hk-fastpay-test\target\classes\hkrt.jks (文件名、目录名或卷标语法不正确。)
	at java.io.FileInputStream.open(Native Method) ~[na:1.6.0_45]
	at java.io.FileInputStream.<init>(FileInputStream.java:120) ~[na:1.6.0_45]
	at org.apache.tomcat.util.net.jsse.JSSESocketFactory.getStore(JSSESocketFactory.java:413) ~[tomcat-embed-core-7.0.59.jar:7.0.59]
	at org.apache.tomcat.util.net.jsse.JSSESocketFactory.getKeystore(JSSESocketFactory.java:319) ~[tomcat-embed-core-7.0.59.jar:7.0.59]
	at org.apache.tomcat.util.net.jsse.JSSESocketFactory.getKeyManagers(JSSESocketFactory.java:577) ~[tomcat-embed-core-7.0.59.jar:7.0.59]
	at org.apache.tomcat.util.net.jsse.JSSESocketFactory.getKeyManagers(JSSESocketFactory.java:517) ~[tomcat-embed-core-7.0.59.jar:7.0.59]
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:493) ~[tomcat-embed-core-7.0.59.jar:7.0.59]
	at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:653) ~[tomcat-embed-core-7.0.59.jar:7.0.59]
	at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:449) ~[tomcat-embed-core-7.0.59.jar:7.0.59]
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1007) ~[tomcat-embed-core-7.0.59.jar:7.0.59]
	... 19 common frames omitted

**Comment by wilkinsona** [comment]
You need to use a more up-to-date version of Tomcat 7. 7.0.63 is the latest, IIRC.

**Comment by rareman** [comment]
use Java 6 and Tomcat 7.0.67

https://bz.apache.org/bugzilla/show_bug.cgi?id=58658

2016-01-04 18:07:18.234 ERROR 5092 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Exception sending context initialized event to listener instance of class org.apache.tomcat.websocket.server.WsContextListener

java.lang.NoClassDefFoundError: java/nio/charset/StandardCharsets
	at org.apache.tomcat.websocket.WsWebSocketContainer.<clinit>(WsWebSocketContainer.java:112) ~[tomcat-embed-websocket-7.0.67.jar:7.0.67]
	at org.apache.tomcat.websocket.server.WsSci.init(WsSci.java:154) ~[tomcat-embed-websocket-7.0.67.jar:7.0.67]
	at org.apache.tomcat.websocket.server.WsContextListener.contextInitialized(WsContextListener.java:39) ~[tomcat-embed-websocket-7.0.67.jar:7.0.67]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5077) [tomcat-embed-core-7.0.67.jar:7.0.67]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5591) [tomcat-embed-core-7.0.67.jar:7.0.67]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-7.0.67.jar:7.0.67]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1574) [tomcat-embed-core-7.0.67.jar:7.0.67]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1564) [tomcat-embed-core-7.0.67.jar:7.0.67]
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303) [na:1.6.0_45]
	at java.util.concurrent.FutureTask.run(FutureTask.java:138) [na:1.6.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895) [na:1.6.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918) [na:1.6.0_45]
	at java.lang.Thread.run(Thread.java:662) [na:1.6.0_45]
Caused by: java.lang.ClassNotFoundException: java.nio.charset.StandardCharsets
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202) ~[na:1.6.0_45]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.6.0_45]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190) ~[na:1.6.0_45]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306) ~[na:1.6.0_45]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301) ~[na:1.6.0_45]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247) ~[na:1.6.0_45]
	... 13 common frames omitted

2016-01-04 18:07:18.237 ERROR 5092 --- [ost-startStop-1] o.apache.catalina.core.StandardContext   : One or more listeners failed to start. Full details will be found in the appropriate container log file
2016-01-04 18:07:18.239 ERROR 5092 --- [ost-startStop-1] o.apache.catalina.core.StandardContext   : Context [] startup failed due to previous errors

**Comment by wilkinsona** [comment]
Sorry, you didn't mention your use of Java 6 earlier. That part of the problem is a duplicate of #4846. You can work around it by excluding `tomcat-embed-websocket`.

**Comment by rareman** [comment]
That ' s right, @wilkinsona thank you!
