### ISSUE TITLE
DevTools is not compatible with Spring Session 1.1.0.M1 with Redis

### ISSUE THREAD

**Issue by tsachev** [spring-projects/spring-boot#4895]
Spring Session 1.1.0.M1 defines `sessionRedisTemplate` as `RedisOperations<Object,Object>` rather than `RedisOperations<String,ExpiringSession>` (see spring-projects/spring-session#259).
This makes DevTools unusable with the next version of Spring Session, because the application fails to start with following error:

```
2016-01-07 12:00:15,775 org.springframework.boot.SpringApplication [restartedMain] ERROR: Application startup failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'restartCompatibleRedisSerializerConfigurer' defined in class path resource [org/springframework/boot/devtools/autoconfigure/LocalDevToolsAutoConfiguration$RestartConfiguration$RedisRestartConfiguration.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.springframework.data.redis.core.RedisTemplate]: : No qualifying bean of type [org.springframework.data.redis.core.RedisTemplate] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.data.redis.core.RedisTemplate] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}
    at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
    at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:464)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1123)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1018)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:764)
    at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:357)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:305)
    at com.samplestore.SamplestoreApplication.main(SamplestoreApplication.java:41)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.data.redis.core.RedisTemplate] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:1373)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1119)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
    at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:813)
    at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
    ... 22 more

```

This seems to be since 1.3.1 when `RestartCompatibleRedisSerializerConfigurer` was introduced to resolve #3805.

**Comment by wilkinsona** [comment]
It's a shame that Spring Session has broken this. I deliberately declared the template's types as narrowly as possible to avoid Dev Tools changing the serialiser of a template other than the one used by Spring Session. Perhaps we can do so via bean name instead. WDYT, @robwinch? Is the bean name a reasonable thing for us to depend on?

**Comment by tsachev** [comment]
I guess you mean @rwinch?

**Comment by rwinch** [comment]
Thanks for the mention @tsachev 

@wilkinsona You are right this isn't ideal that Spring Session changed. If you like we can continue to support the old mechanism, but that would be deprecated in favor of the name based strategy you mentioned.

**Comment by wilkinsona** [comment]
@rwinch Thanks. If you are happy for us to treat the bean name as API then I think we can just move to that. It should be transparent to users and work with Spring Session 1.0 and 1.1.

**Comment by rifatdover** [comment]
Hi when I implement spring-boot-devtools and spring-boot-starter-redis session repository returns null session. Is that related to this? @tsachev @wilkinsona @rwinch

**Comment by wilkinsona** [comment]
@rifatdover No, I don't think so. This issue is about a problem that stops your application from starting. Also, you have to be using a milestone of Spring Session which isn't the default.
