### ISSUE TITLE
Fat jar jvm process will exit, when throw a RuntimeException

### ISSUE THREAD

**Issue by hengyunabc** [spring-projects/spring-boot#4912]
```java
@SpringBootApplication
public class AaaApplication {

	public static void main(String[] args) throws InterruptedException {
        Thread t = new Thread(new Runnable(){

            @Override
            public void run() {
                while(true){
                    System.err.println("sleep");
                    try {
                        TimeUnit.SECONDS.sleep(1);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
            
        });
        
        t.setDaemon(false);
        t.start();
        
        TimeUnit.SECONDS.sleep(3);
        
	    throw new RuntimeException("RuntimeException");
	    
//		SpringApplication.run(AaaApplication.class, args);
	}
}
```

A simple spring boot demo. 

When run it in ide, the process will not exit.

When run it as a fat jar, the process will exit.

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: RuntimeException
	at com.example.AaaApplication.main(AaaApplication.java:35)
	... 6 more
``` 

The sleep thread is not daemon, why the process will exit?

**Comment by hengyunabc** [comment]
Add non daemon thread count check in ```org.springframework.boot.loader.Launcher``` will be better?

```java
    private static ThreadGroup getRoot() {
        ThreadGroup group = Thread.currentThread().getThreadGroup();
        ThreadGroup parent;
        while ((parent = group.getParent()) != null) {
            group = parent;
        }
        return group;
    }
    
    private static int nonDaemonThreadCount(){
        int count = 0;
        
        ThreadGroup root = getRoot();
        Thread[] threads = new Thread[root.activeCount()];
        while (root.enumerate(threads, true) == threads.length) {
            threads = new Thread[threads.length * 2];
        }
        for (Thread thread : threads) {
            if (thread != null && !thread.isDaemon()) {
                count++;
            }
        }
        return count;
    }
    
	/**
	 * Launch the application. This method is the initial entry point that should be
	 * called by a subclass {@code public static void main(String[] args)} method.
	 * @param args the incoming arguments
	 */
	protected void launch(String[] args) {
		try {
			JarFile.registerUrlProtocolHandler();
			ClassLoader classLoader = createClassLoader(getClassPathArchives());
			launch(args, getMainClass(), classLoader);
		}
		catch (Exception ex) {
			ex.printStackTrace();
			if(nonDaemonThreadCount() <= 1) {
			    System.exit(1);
			}
		}
	}
```

**Comment by wilkinsona** [comment]
As part of changing this, we need to check that the simple sample application still has the desired exit code behaviour.

**Comment by hengyunabc** [comment]
I make a mistake. The check code should be in MainMethodRunner, not in Launcher.

```java
public class MainMethodRunner implements Runnable {

	private final String mainClassName;

	private final String[] args;

	/**
	 * Create a new {@link MainMethodRunner} instance.
	 * @param mainClass the main class
	 * @param args incoming arguments
	 */
	public MainMethodRunner(String mainClass, String[] args) {
		this.mainClassName = mainClass;
		this.args = (args == null ? null : args.clone());
	}

	@Override
	public void run() {
		try {
			Class<?> mainClass = Thread.currentThread().getContextClassLoader()
					.loadClass(this.mainClassName);
			Method mainMethod = mainClass.getDeclaredMethod("main", String[].class);
			if (mainMethod == null) {
				throw new IllegalStateException(
						this.mainClassName + " does not have a main method");
			}
			mainMethod.invoke(null, new Object[] { this.args });
		}
		catch (Exception ex) {
			UncaughtExceptionHandler handler = Thread.currentThread()
					.getUncaughtExceptionHandler();
			if (handler != null) {
				handler.uncaughtException(Thread.currentThread(), ex);
			}
			else {
				ex.printStackTrace();
			}
			if(nonDaemonThreadCount() <= 1) {
                System.exit(1);
            }
		}
	}

    private static ThreadGroup getRoot() {
        ThreadGroup group = Thread.currentThread().getThreadGroup();
        ThreadGroup parent;
        while ((parent = group.getParent()) != null) {
            group = parent;
        }
        return group;
    }

    private static int nonDaemonThreadCount(){
        int count = 0;

        ThreadGroup root = getRoot();
        Thread[] threads = new Thread[root.activeCount()];
        while (root.enumerate(threads, true) == threads.length) {
            threads = new Thread[threads.length * 2];
        }
        for (Thread thread : threads) {
            if (thread != null && !thread.isDaemon()) {
                count++;
            }
        }
        return count;
    }
}
```

**Comment by wilkinsona** [comment]
Fixed in https://github.com/spring-projects/spring-boot/commit/2dc3660a3260726d543f4f70b634c1283e11f308.
