### ISSUE TITLE
Session persistence problem with devtools' autorestart

### ISSUE THREAD

**Issue by AmitHe** [spring-projects/spring-boot#4939]
The session persistence seems not working and the stack trace when auto restart is as follow: 
``` 
2016-01-14 11:25:00.798 ERROR 4188 --- [ost-startStop-1] o.a.catalina.session.StandardManager     : Exception loading sessions from persistent storage

java.lang.ClassCastException: cannot assign instance of java.lang.StackTraceElement to field java.util.Collections$UnmodifiableList.list of type java.util.List in instance of java.util.Collections$UnmodifiableList
	at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2089) ~[na:1.8.0_31]
	at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1261) ~[na:1.8.0_31]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1999) ~[na:1.8.0_31]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918) ~[na:1.8.0_31]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801) ~[na:1.8.0_31]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) ~[na:1.8.0_31]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993) ~[na:1.8.0_31]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918) ~[na:1.8.0_31]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801) ~[na:1.8.0_31]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) ~[na:1.8.0_31]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993) ~[na:1.8.0_31]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918) ~[na:1.8.0_31]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801) ~[na:1.8.0_31]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) ~[na:1.8.0_31]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371) ~[na:1.8.0_31]
	at org.apache.catalina.session.StandardSession.doReadObject(StandardSession.java:1627) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.session.StandardSession.readObjectData(StandardSession.java:1090) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.session.StandardManager.doLoad(StandardManager.java:261) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.session.StandardManager.load(StandardManager.java:180) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.session.StandardManager.startInternal(StandardManager.java:460) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5272) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_31]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_31] 
```
And I checked the spring-boot document and found this section:[20.2.6 Known limitations](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#using-boot-devtools-known-restart-limitations) , It's really a pity that it seems the reason. But anyway is there a way to improve this problem?

**Comment by snicoll** [comment]
Looking at the stacktrace, I don't think it's related to the section you referenced. It is rather something you put in the (HTTP) session that Tomcat can't read back when the app restarts. I can't tell which one but you may want to look at your code and check that all objects you put in the session are properly serializable.

If you think you've hit a bug, please reopen and share a sample that reproduces the problem.
