### ISSUE TITLE
RedisProperties.Pool Needs maxWaitMillis Property

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-boot#4950]
The default redis pool configuration sets `maxActive` to `8` but there is no property for `maxWaitMillis`. When the limit is reached, threads hang for ever. Adding a `maxWaitMillis` property to the pool (with some suitable default) will throw

````
Exception in thread "main" 2016-01-15 11:38:11.914  INFO 41244 --- [       Thread-4] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@32cf48b7: startup date [Fri Jan 15 11:38:06 EST 2016]; root of context hierarchy
org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.fetchJedisConnector(JedisConnectionFactory.java:162)
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.getConnection(JedisConnectionFactory.java:251)
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.getConnection(JedisConnectionFactory.java:58)
	at com.example.RedisBootApplication.main(RedisBootApplication.java:19)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.util.Pool.getResource(Pool.java:50)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:99)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:12)
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.fetchJedisConnector(JedisConnectionFactory.java:155)
	... 3 more
Caused by: java.util.NoSuchElementException: Timeout waiting for idle object
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:449)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
	at redis.clients.util.Pool.getResource(Pool.java:48)
	... 6 more
````

**Comment by garyrussell** [comment]
Invalid - `setMaxWait()` - doh.

**Comment by garyrussell** [comment]
Although I'm not sure `-1` is a good default since threads just hang if all connections are in use for an extensive period.
