### ISSUE TITLE
org.springframework.aop.framework.AopConfigException: Could not generate CGLIB subclass of class [class org.apache.catalina.core.ApplicationContextFacade]

### ISSUE THREAD

**Issue by wushp** [spring-projects/spring-boot#4967]
usage
--------------------------------------------------------------------------------------------------------------
i deploy spring boot as a war to tomcat.

application.properties
--------------------------------------------------------------------------------------------------------------
```
server.port=8080
server.tomcat.uri-encoding=UTF-8
server.context-path=/gy-ht

multipart.enabled=true
multipart.max-file-size=100Mb

mysql.healthcheck.url=${sqlserver.healthcheck.url}
mysql.healthcheck.username=${sqlserver.healthcheck.username}
mysql.healthcheck.password=${sqlserver.healthcheck.password}

#velocity
spring.velocity.properties.velocimacro.library=common/VM_global_library.vm
spring.velocity.toolbox-config-location=toolbox.xml
logging.level.org.apache.velocity=error
spring.velocity.charset=UTF-8
spring.velocity.content-type=text/html
spring.velocity.cache=true
```

log
---------------------------------------------------------------------------------------------------------------
```
due to exception [Could not generate CGLIB subclass of class [class org.apache.catalina.core.ApplicationContextFacade]: Common causes of this problem include using a final class or a non-visible class; nested exception is org.springframework.cglib.core.CodeGenerationException: java.lang.reflect.InvocationTargetException-->null]
org.springframework.aop.framework.AopConfigException: Could not generate CGLIB subclass of class [class org.apache.catalina.core.ApplicationContextFacade]: Common causes of this problem include using a final class or a non-visible class; nested exception is org.springframework.cglib.core.CodeGenerationException: java.lang.reflect.InvocationTargetException-->null
	at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:206)
	at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:152)
	at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:96)
	at org.springframework.boot.web.servlet.view.velocity.EmbeddedVelocityToolboxView.getToolboxConfigFileAwareServletContext(EmbeddedVelocityToolboxView.java:71)
	at org.springframework.boot.web.servlet.view.velocity.EmbeddedVelocityToolboxView.setContextToolbox(EmbeddedVelocityToolboxView.java:60)
	at org.springframework.boot.web.servlet.view.velocity.EmbeddedVelocityToolboxView.createVelocityContext(EmbeddedVelocityToolboxView.java:52)
	at org.springframework.web.servlet.view.velocity.VelocityView.renderMergedTemplateModel(VelocityView.java:288)
	at org.springframework.web.servlet.view.AbstractTemplateView.renderMergedOutputModel(AbstractTemplateView.java:167)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1244)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1027)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:971)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.boot.context.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:116)
	at org.springframework.boot.context.web.ErrorPageFilter.access$000(ErrorPageFilter.java:60)
	at org.springframework.boot.context.web.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:91)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.boot.context.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:109)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2517)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2506)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.cglib.core.CodeGenerationException: java.lang.reflect.InvocationTargetException-->null
	at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:237)
	at org.springframework.cglib.proxy.Enhancer.createHelper(Enhancer.java:377)
	at org.springframework.cglib.proxy.Enhancer.createClass(Enhancer.java:317)
	at org.springframework.aop.framework.ObjenesisCglibAopProxy.createProxyClassAndInstance(ObjenesisCglibAopProxy.java:56)
	at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:202)
	... 53 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:384)
	at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:219)
	... 57 more
Caused by: java.lang.NoClassDefFoundError: org/springframework/aop/SpringProxy
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	... 62 more
Caused by: java.lang.ClassNotFoundException: org.springframework.aop.SpringProxy
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 64 more
```

**Comment by wushp** [comment]
spring boot version
--------------------------------------------------------------------------------------------------------------
1.2.7.RELEASE

**Comment by wilkinsona** [comment]
Can you please provide a small sample project that reproduces the problem? I would guess that you are component scanning Tomcat's classes, perhaps because your main class is in an `org.*` package.

**Comment by wushp** [comment]
where is the demo
https://github.com/wushp/test-issue-1929.git

**Comment by wilkinsona** [comment]
Thanks. I've reproduced the problem. FWIW, my guess was wrong.

**Comment by wilkinsona** [comment]
This looks like a regression caused by the fix for #2912.

@wushp There's a workaround. Add this bean to your `WebConfig` class:

```
	@Bean
	public VelocityViewResolver velocityViewResolver(VelocityProperties velocityProperties) {
		VelocityViewResolver viewResolver = new VelocityViewResolver();
		velocityProperties.applyToViewResolver(viewResolver);
		return viewResolver;
	}
```

You also have the location of the toolbox config file configured incorrectly. It should be:

```
spring.velocity.toolbox-config-location=/WEB-INF/classes/toolbox.xml
```

**Comment by wilkinsona** [comment]
`org.springframework.aop.SpringProxy` cannot be found as `org.springframework.cglib.core.ReflectUtils.defineClass` is being called with Tomcat's class loader rather than the web app's class loader.

**Comment by wushp** [comment]
thanks!!!!!!!!!!!!!!!!!!!!! amazing !!!!  i will try it latter~
