### ISSUE TITLE
Regression in spring-boot 1.3.3 on log properties

### ISSUE THREAD

**Issue by Polve** [spring-projects/spring-boot#5274]
Trying to upgrade from boot 1.3.2 to 1.3.3 the app would not start any more with the following exception:

```
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'PID' in string value "/tmp/cm.log-${PID}" 
        at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:174)
        at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:126)
        at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:204)
        at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:178)
        at org.springframework.core.env.AbstractPropertyResolver.resolveNestedPlaceholders(AbstractPropertyResolver.java:195)
        at org.springframework.core.env.PropertySourcesPropertyResolver.getProperty(PropertySourcesPropertyResolver.java:87)
        at org.springframework.core.env.PropertySourcesPropertyResolver.getProperty(PropertySourcesPropertyResolver.java:60)
        at org.springframework.core.env.AbstractEnvironment.getProperty(AbstractEnvironment.java:531)
        at org.springframework.boot.logging.LogFile.get(LogFile.java:116)
        at org.springframework.boot.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:250)
```

in the config/application.yml file I have set

> logging:
>   file: /tmp/cm.log-${PID}
>

**Comment by wilkinsona** [comment]
This is a regression caused by the changes for #5073 made in https://github.com/spring-projects/spring-boot/commit/ddfadce94d02ff7cc5484fde7acd3478ace6dea2.

You can work around the problem by calling `System.setProperty("PID", new ApplicationPid().toString())` before you call `SpringApplication.run()`.

**Comment by Polve** [comment]
The workaround works fine, thanks

**Comment by Polve** [comment]
Actually I spoke a bit too early: the workaround does not work for testing, since the main() method is not used.

Any hint for solving the problem there?

**Comment by wilkinsona** [comment]
You could set the property in a `@BeforeClass` method or use different configuration for `logging.file` in your tests.
