### ISSUE TITLE
Exception thrown when upgrading from Boot 1.3.3.RELEASE to Boot 1.4.0.BUILD-SNAPSHOT

### ISSUE THREAD

**Issue by mikegehard** [spring-projects/spring-boot#5342]
I have a somewhat complex Kotlin (1.0.0)/Spring Cloud/Boot app that fails to boot when I upgrade Boot.

The error is:
```
± mg |use-boot14-snapshot ✗| → ./gradlew applications/billing:bootRun
:components/payments:compileJava UP-TO-DATE
:components/payments:processResources UP-TO-DATE
:components/payments:classes UP-TO-DATE
:components/payments:jar UP-TO-DATE
:applications/billing:compileKotlin UP-TO-DATE
:applications/billing:compileJava UP-TO-DATE
:applications/billing:processResources UP-TO-DATE
:applications/billing:classes UP-TO-DATE
:applications/billing:findMainClass
:applications/billing:bootRun
Failed to instantiate [ch.qos.logback.classic.LoggerContext]
Reported exception:
java.lang.AbstractMethodError: ch.qos.logback.classic.pattern.EnsureExceptionHandling.process(Lch/qos/logback/core/Context;Lch/qos/logback/core/pattern/Converter;)V
	at ch.qos.logback.core.pattern.PatternLayoutBase.start(PatternLayoutBase.java:88)
	at ch.qos.logback.classic.encoder.PatternLayoutEncoder.start(PatternLayoutEncoder.java:28)
	at ch.qos.logback.classic.BasicConfigurator.configure(BasicConfigurator.java:50)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:164)
	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:140)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:119)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:328)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:280)
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:273)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:181)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1112)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1101)
	at com.example.billing.ApplicationKt.main(Application.kt:25)
:applications/billing:bootRun FAILED

FAILURE: Build failed with an exception.
``` 

Working 1.3.3 commit:
https://github.com/mikegehard/user-management-evolution-kotlin/commit/0d1306e57050b2d1b24b6337cadf6ad346ce986c

Broken 1.4.0 Snapshot commit:
https://github.com/mikegehard/user-management-evolution-kotlin/tree/use-boot14-snapshot

**Comment by snicoll** [comment]
Wha

**Comment by mikegehard** [comment]
Thanks for the tip @snicoll about the dependency version mismatch.

My thinking is that since this occurred when I upgraded the Spring Boot version so it might be a Spring Boot issue. Because I turn a lot of my dependency version management over to Boot, I would expect that Boot would help me manage those dependencies and this could be an incorrect assumption.

I will do a little more digging to see if I can figure out what might be causing the dependency version mismatch. I'm wondering if the version of Spring Cloud (Brixton.M3) might be a cause of the issue.

**Comment by spencergibb** [comment]
There have always been hickups trying to use a future version of boot before Spring Cloud updates to that version.

**Comment by mikegehard** [comment]
Oh that's good information @spencergibb. Thanks. I'll temper my desire to use Boot 1.4 for a bit. :smile:

**Comment by snicoll** [comment]
> My thinking is that since this occurred when I upgraded the Spring Boot version it might be a Spring Boot issue

If you're using Spring Boot vanilla, that's a correct assumption. You're not :)
