### ISSUE TITLE
Suppression of analysed failure stack traces isn't working for executable archives

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#5358]
In the latest 1.4.0 snapshots, the stack trace of a failure that's been analysed is being output to the console:

```
2016-03-08 10:12:19.057 ERROR 42886 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   :

***************************
APPLICATION FAILED TO START
***************************

Description:

Embedded servlet container failed to start. Port 8080 was already in use.

Action:

Identify and stop the process that's listening on port 8080 or configure this application to listen on another port.

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:62)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:101)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
	... 3 more
Caused by: org.springframework.boot.context.embedded.PortInUseException: Port 8080 is already in use
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.checkThatConnectorsHaveStarted(TomcatEmbeddedServletContainer.java:187)
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:170)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:293)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:768)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:362)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
	at sample.web.staticcontent.SampleWebStaticApplication.main(SampleWebStaticApplication.java:33)
	... 8 more
```

This problem does not occur when the main method is run directly (in an IDE, for example).

**Comment by wilkinsona** [comment]
The unwanted stack trace is produced by `Launcher.launch(String[])` as a result of it catching an exception:

```
protected void launch(String[] args) {
	try {
		JarFile.registerUrlProtocolHandler();
		ClassLoader classLoader = createClassLoader(getClassPathArchives());
		launch(args, getMainClass(), classLoader);
	}
	catch (Exception ex) {
		ex.printStackTrace();
		System.exit(1);
	}
}
```

**Comment by wilkinsona** [comment]
Removing the call to `ex.printStackTrace()` means that applications may fail silently. Here's an alternative solution: https://github.com/wilkinsona/spring-boot/commit/29291a3b6ec32d41fe26545083339f84ba11c90a

It's an improvement on the previous attempt as it allows the exception from a launch failure to be handled by the JVM and it reduces the amount of exception catching and wrapping in the launcher. It does, however, require breaking API changes to be able to do so.
