### ISSUE TITLE
spring-boot-maven-plugin does not allow a single profile to be specified via the profiles config parameter

### ISSUE THREAD

**Issue by mrumpf** [spring-projects/spring-boot#5429]
The Spring Boot Maven Plugin has a conifguration option called "profiles".
The plural indicates that multiple profiles must be specified and the documentation mentions that those profile names must be separated by comma.

When there is a single profile name only:

````
           <build>
                <plugins>
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>pre-integration-test</id>
                                <goals>
                                    <goal>start</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>post-integration-test</id>
                                <goals>
                                    <goal>stop</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <useTestClasspath>true</useTestClasspath>
                            <mainClass>com.company.app.MyApplication</mainClass>
                            <maxAttempts>600</maxAttempts>
                            <fork>true</fork>
                            <profiles>ci</profiles>
                            <!-- jvmArguments>-Dspring.profiles.active=ci</jvmArguments -->
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <version>2.18.1</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>integration-test</goal>
                                    <goal>verify</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
````

The following exception occurs

````
23:10:04 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.4.0.M1:start (pre-integration-test) on project citest: Unable to parse configuration of mojo org.springframework.boot:spring-boot-maven-plugin:1.4.0.M1:start for parameter profiles: Cannot assign configuration entry 'profiles' with value 'ci' of type java.lang.String to property of type java.lang.String[]
23:10:04 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:220)
23:10:04 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
23:10:04 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
23:10:04 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
23:10:04 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
23:10:04 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
23:10:04 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
23:10:04 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
23:10:04 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
23:10:04 	at org.jvnet.hudson.maven3.launcher.Maven32Launcher.main(Maven32Launcher.java:132)
23:10:04 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:10:04 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:10:04 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:10:04 	at java.lang.reflect.Method.invoke(Method.java:498)
23:10:04 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
23:10:04 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
23:10:04 	at jenkins.maven3.agent.Maven32Main.launch(Maven32Main.java:186)
23:10:04 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:10:04 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:10:04 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:10:04 	at java.lang.reflect.Method.invoke(Method.java:498)
23:10:04 	at hudson.maven.Maven3Builder.call(Maven3Builder.java:136)
23:10:04 	at hudson.maven.Maven3Builder.call(Maven3Builder.java:71)
23:10:04 	at hudson.remoting.UserRequest.perform(UserRequest.java:120)
23:10:04 	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
23:10:04 	at hudson.remoting.Request$2.run(Request.java:326)
23:10:04 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
23:10:04 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
23:10:04 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
23:10:04 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
23:10:04 	at java.lang.Thread.run(Thread.java:745)
23:10:04 Caused by: org.apache.maven.plugin.PluginConfigurationException: Unable to parse configuration of mojo org.springframework.boot:spring-boot-maven-plugin:1.4.0.M1:start for parameter profiles: Cannot assign configuration entry 'profiles' with value 'ci' of type java.lang.String to property of type java.lang.String[]
23:10:04 	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields(DefaultMavenPluginManager.java:607)
23:10:04 	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:539)
23:10:04 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:119)
23:10:04 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
23:10:04 	... 30 more
23:10:04 Caused by: org.codehaus.plexus.component.configurator.ComponentConfigurationException: Cannot assign configuration entry 'profiles' with value 'ci' of type java.lang.String to property of type java.lang.String[]
23:10:04 	at org.codehaus.plexus.component.configurator.converters.AbstractConfigurationConverter.failIfNotTypeCompatible(AbstractConfigurationConverter.java:100)
23:10:04 	at org.codehaus.plexus.component.configurator.converters.composite.ArrayConverter.fromConfiguration(ArrayConverter.java:65)
23:10:04 	at org.eclipse.sisu.plexus.CompositeBeanHelper.convertProperty(CompositeBeanHelper.java:273)
23:10:04 	at org.eclipse.sisu.plexus.CompositeBeanHelper.setProperty(CompositeBeanHelper.java:210)
23:10:04 	at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.processConfiguration(ObjectWithFieldsConverter.java:101)
23:10:04 	at org.codehaus.plexus.component.configurator.BasicComponentConfigurator.configureComponent(BasicComponentConfigurator.java:34)
23:10:04 	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields(DefaultMavenPluginManager.java:577)
23:10:04 	... 33 more
````

The only workaround I found is to use the parameter `<jvmArguments>-Dspring.profiles.active=ci</jvmArguments>.

To prevent others from messing around with different options, either the documentation should make clear that a single profile cannot be specified via the `profiles` parameter and the `jvmArguments` should be used instead. Or better the `profiles` parameter should support single profiles as well.

**Comment by snicoll** [comment]
Have you looked at [the documentation](http://docs.spring.io/spring-boot/docs/current/maven-plugin/examples/run-profiles.html) by any chance? That should be:

```
<profiles>
  <profile>ci</profile>
</profiles>
```

**Comment by mrumpf** [comment]
I looked at http://docs.spring.io/spring-boot/docs/current/maven-plugin/start-mojo.html#profiles
I did not get to the example you mentioned. Sorry.

**Comment by snicoll** [comment]
Nothing to do with us I am afraid, that's how Maven deals with arrays in the pom.
