### ISSUE TITLE
Auto-configure repositories for Redis

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#5448]
Hopper RC1 brings support for Redis repositories. We should improve our auto-configuration to support that as well.

See gh-5150

**Comment by eddumelendez** [comment]
@snicoll I have been working on this in 4fa5cb5 but hard to test it. Can you give  a hint? Thanks in advance.

**Comment by snicoll** [comment]
There is a RedisTestServer that runs if redis is available. I would use that. Are you going to submit a PR for this?

**Comment by eddumelendez** [comment]
Thanks @snicoll PR is under way.

**Comment by snicoll** [comment]
Closing in favour of the PR #5455

**Comment by philwebb** [comment]
Seems to break the latest Buildpack.

```
2016-03-22T15:46:08.80-0700 [APP/0]      OUT 2016-03-22 22:46:08.804  WARN 14 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'redisKeyValueAdapter': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.redis.core.RedisKeyValueAdapter]: Constructor threw exception; nested exception is java.lang.NullPointerException
2016-03-22T15:46:08.80-0700 [APP/0]      OUT 2016-03-22 22:46:08.806  INFO 14 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2016-03-22T15:46:08.80-0700 [APP/0]      OUT 2016-03-22 22:46:08.808  INFO 14 --- [           main] o.s.j.d.e.EmbeddedDatabaseFactory        : Shutting down embedded database: url='jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false'
2016-03-22T15:46:08.81-0700 [APP/0]      OUT 2016-03-22 22:46:08.815  INFO 14 --- [           main] o.apache.catalina.core.StandardService   : Stopping service Tomcat
2016-03-22T15:46:08.85-0700 [APP/0]      OUT 2016-03-22 22:46:08.850  INFO 14 --- [           main] utoConfigurationReportLoggingInitializer : 
2016-03-22T15:46:08.85-0700 [APP/0]      OUT Error starting ApplicationContext. To display the auto-configuration report enable debug logging (start with --debug)
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 2016-03-22 22:46:08.880 ERROR 14 --- [           main] o.s.boot.SpringApplication               : Application startup failed
2016-03-22T15:46:08.88-0700 [APP/0]      OUT org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'redisKeyValueAdapter': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.redis.core.RedisKeyValueAdapter]: Constructor threw exception; nested exception is java.lang.NullPointerException
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:279) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar!/:4.3.0.BUILD-SNAPSHOT]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1143) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar!/:4.3.0.BUILD-SNAPSHOT]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar!/:4.3.0.BUILD-SNAPSHOT]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar!/:4.3.0.BUILD-SNAPSHOT]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar!/:4.3.0.BUILD-SNAPSHOT]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar!/:4.3.0.BUILD-SNAPSHOT]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar!/:4.3.0.BUILD-SNAPSHOT]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar!/:4.3.0.BUILD-SNAPSHOT]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar!/:4.3.0.BUILD-SNAPSHOT]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:775) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar!/:4.3.0.BUILD-SNAPSHOT]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:841) ~[spring-context-4.3.0.BUILD-SNAPSHOT.jar!/:4.3.0.BUILD-SNAPSHOT]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:540) ~[spring-context-4.3.0.BUILD-SNAPSHOT.jar!/:4.3.0.BUILD-SNAPSHOT]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.4.0.BUILD-SNAPSHOT.jar!/:1.4.0.BUILD-SNAPSHOT]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:773) [spring-boot-1.4.0.BUILD-SNAPSHOT.jar!/:1.4.0.BUILD-SNAPSHOT]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:368) [spring-boot-1.4.0.BUILD-SNAPSHOT.jar!/:1.4.0.BUILD-SNAPSHOT]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-1.4.0.BUILD-SNAPSHOT.jar!/:1.4.0.BUILD-SNAPSHOT]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1190) [spring-boot-1.4.0.BUILD-SNAPSHOT.jar!/:1.4.0.BUILD-SNAPSHOT]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1179) [spring-boot-1.4.0.BUILD-SNAPSHOT.jar!/:1.4.0.BUILD-SNAPSHOT]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at com.gopivotal.cloudfoundry.test.ApplicationConfiguration.main(ApplicationConfiguration.java:41) [classes/:na]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_73-]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_73-]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_73-]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_73-]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54) [app/:na]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:100) [app/:na]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [app/:na]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58) [app/:na]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.redis.core.RedisKeyValueAdapter]: Constructor threw exception; nested exception is java.lang.NullPointerException
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar!/:4.3.0.BUILD-SNAPSHOT]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar!/:4.3.0.BUILD-SNAPSHOT]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:271) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar!/:4.3.0.BUILD-SNAPSHOT]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	... 26 common frames omitted
2016-03-22T15:46:08.88-0700 [APP/0]      OUT Caused by: java.lang.NullPointerException: null
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at org.springframework.data.redis.listener.KeyspaceEventMessageListener.init(KeyspaceEventMessageListener.java:78) ~[spring-data-redis-1.7.0.RC1.jar!/:na]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at org.springframework.data.redis.core.RedisKeyValueAdapter.initKeyExpirationListener(RedisKeyValueAdapter.java:509) ~[spring-data-redis-1.7.0.RC1.jar!/:na]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at org.springframework.data.redis.core.RedisKeyValueAdapter.<init>(RedisKeyValueAdapter.java:160) ~[spring-data-redis-1.7.0.RC1.jar!/:na]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_73-]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_73-]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_73-]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_73-]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar!/:4.3.0.BUILD-SNAPSHOT]
2016-03-22T15:46:08.88-0700 [APP/0]      OUT 	... 28 common frames omitted
2016-03-22T15:46:08.91-0700 [APP/0]      OUT Exit status 1
```

**Comment by christophstrobl** [comment]
@philwebb I altered `SampleRedisApplication` and the `RedisKeyValueAdapter`, `Listener...` and repository support seem to be fine so far.
https://github.com/spring-projects/spring-boot/compare/master...christophstrobl:issue/5448_verify

**Comment by philwebb** [comment]
@nebhale Did you have a way to replicate this issue?

**Comment by nebhale** [comment]
@philwebb Our system tests would reproduce it.  Can I update to the latest `-SNAPSHOT` for testing the fix?

**Comment by philwebb** [comment]
@nebhale We've not made any changes to fix it as yet. I just wanted a way to reproduce locally if possible.

**Comment by snicoll** [comment]
@nebhale how can I test this? Does it work with `1.4.0.M1`?

**Comment by snicoll** [comment]
@nebhale can you help? It's a blocker for M2 and we're about to release it. I am still not sure what the problem is.

**Comment by nebhale** [comment]
@snicoll This works with M1 in our system tests, but if I release that to the snapshot it starts failing again.  I can check a snapshot if an update has been made.

**Comment by snicoll** [comment]
You said that already. I don't know what those system tests are and nothing indicates that this failure is related to this problem. It's failing quite low so that's why I am asking for a way to reproduce myself...

**Comment by philwebb** [comment]
Problem seems to be because [FakeRedisConnectionFactory](https://github.com/cloudfoundry/java-test-applications/blob/master/core/src/main/java/com/gopivotal/cloudfoundry/test/core/FakeRedisConnectionFactory.java) returns `null` and `KeyspaceEventMessageListener` doesn't expect that.
