### ISSUE TITLE
Tomcat war deployment of JSP sample is not working due to "tomcat-embed-el" dependency

### ISSUE THREAD

**Issue by RawSanj** [spring-projects/spring-boot#5454]
I packaged the sample app - [spring-boot-sample-tomcat-jsp](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples/spring-boot-sample-tomcat-jsp) into war file after changing the `<parent></parent>` to use Spring-boot 1.3.3 in `pom.xml`.

Then deployed the `war` file in Tomcat, there was NO Error during app deployment.
But when I visit http://localhost:8080/spring-boot-sample-tomcat-jsp/ I am getting below error:

	There was an unexpected error (type=Internal Server Error, status=500).
	javax.servlet.ServletException: java.lang.NoSuchMethodError:
	org.apache.el.lang.ELSupport.coerceToType(Ljavax/el/ELContext;Ljava/lang/Object;Ljava/lang/Class;)Ljava/lang/Object;

I found that this is due to the presence of **tomcat-embed-el-8.0.32.jar** in the `lib` folder.

Somehow the `tomcat-embed-el` is getting added even when it is not defined in the `pom.xml`

When I add below code in `pom.xml`, then the **tomcat-embed-el-8.0.32.jar**  is not added into `lib` folder and error is resolved.

	<dependency>
		<groupId>org.apache.tomcat.embed</groupId>
		<artifactId>tomcat-embed-el</artifactId>
		<scope>provided</scope>
	</dependency>

Spring-Boot version - 1.3.3
Tomcat version - 8.0

Sample Application: [Repo](https://github.com/RawSanj/SOFRepos/tree/master/spring-boot-sample-tomcat-jsp).

**Comment by dsyer** [comment]
spring-boot-starter-web depends on spring-boot-starter-tomcat (which is scope=provided in the sample) and also spring-boot-starter-validation (which is not, and depends transitively on tomcat-embed-el).

**Comment by philwebb** [comment]
I think that changing `spring-boot-starter-web` to directly depend on `hibernate-validator` rather than `spring-boot-starter-validation` will be enough to fix this. I'm reluctant to make that change in 1.3.x since there might be other problems with it.

The commit message for #2678 seems to suggest that `spring-boot-starter-validation` was added mainly for non-web applications.

**Comment by wilkinsona** [comment]
The change made in https://github.com/spring-projects/spring-boot/commit/a6c1668bd9765f73aca88e61d4c4da570f1d20f6 appears to have broken the TomEE deployment test. The test app now fails to deploy with:

```
org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1083)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1880)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.tomee.catalina.TomEERuntimeException: org.apache.openejb.OpenEJBException: Creating UB-JOB1/spring-boot-deployment-tests/spring-boot-deployment-test-ax.validation.spi.ConfigurationState.getParameterNameProvider()Ljavax/validation/ParameterNameProvider;
	at org.apache.tomee.catalina.TomcatWebAppBuilder.startInternal(TomcatWebAppBuilder.java:1257)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.configureStart(TomcatWebAppBuilder.java:1087)
	at org.apache.tomee.catalina.GlobalListenerSupport.lifecycleEvent(GlobalListenerSupport.java:130)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5378)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 10 more
Caused by: org.apache.openejb.OpenEJBException: Creating application failed: /opt/bamboo-home/xml-data/build-dir/BOOTtest-tomee/target/cargo/configurations/tomee1x/webapps/bootapp: javax.validation.spi.ConfigurationState.der;
	at org.apache.openejb.assembler.classic.Assembler.createApplication(Assembler.java:896)
	at org.apache.openejb.assembler.classic.Assembler.createApplication(Assembler.java:623)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.startInternal(TomcatWebAppBuilder.java:1248)
	... 16 more
Caused by: java.lang.NoSuchMethodError: javax.validation.spi.ConfigurationState.getParameterNameProvider()
	at org.hibernate.validator.internal.engine.ValidatorFactoryImpl.<init>(ValidatorFactoryImpl.java:142)
	at org.hibernate.validator.HibernateValidator.buildValidatorFactory(HibernateValidator.java:35)
	at org.apache.bval.jsr303.ConfigurationImpl.doPrivBuildValidatorFactory(ConfigurationImpl.java:252)
	at org.apache.bval.jsr303.util.SecureActions$5.run(SecureActions.java:131)
	at org.apache.bval.jsr303.util.SecureActions$5.run(SecureActions.java:129)
	at org.apache.bval.jsr303.ConfigurationImpl.run(ConfigurationImpl.java:337)
	at org.apache.bval.jsr303.ConfigurationImpl.buildValidatorFactory(ConfigurationImpl.java:244)
	at org.apache.openejb.assembler.classic.ValidatorBuilder.buildFactory(ValidatorBuilder.java:77)
	at org.apache.openejb.assembler.classic.ValidatorBuilder.buildFactory(ValidatorBuilder.java:47)
	at org.apache.openejb.assembler.classic.Assembler.createApplication(Assembler.java:711)
```

**Comment by dsyer** [comment]
TomEE doesn't have an EL implementation. Great. I guess it makes sense to fix this in the test, rather than hacking more at the starters?

**Comment by philwebb** [comment]
Yeah, I think that makes sense.

**Comment by wilkinsona** [comment]
The problem is that the TomEE test app is now excluding the wrong thing: it's excluding the validation starter but now needs to exclude Hibernate Validator directly
