### ISSUE TITLE
Embedded MongoDB fails to shutdown gracefully

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-boot#5487]
The problem can be reproduced by changing ```spring-boot-sample-data-mongodb``` to a web application:

```diff
diff --git spring-boot-samples/spring-boot-sample-data-mongodb/pom.xml spring-boot-samples/spring-boot-sample-data-mongodb/pom.xml
index 1ff97bb..ff92880 100644
--- spring-boot-samples/spring-boot-sample-data-mongodb/pom.xml
+++ spring-boot-samples/spring-boot-sample-data-mongodb/pom.xml
@@ -21,7 +21,7 @@
        <dependencies>
                <dependency>
                        <groupId>org.springframework.boot</groupId>
-                       <artifactId>spring-boot-starter</artifactId>
+                       <artifactId>spring-boot-starter-web</artifactId>
                </dependency>
                <dependency>
                        <groupId>org.springframework.boot</groupId>
```

Shutting down the app generates the following output:

```
2016-03-24 20:17:32.379  INFO 8202 --- [       Thread-3] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-03-24T20:17:32.378+0100 [signalProcessingThread] got signal 2 (Interrupt), will terminate after current cmd ends
2016-03-24 20:17:32.379  INFO 8202 --- [       Thread-3] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-03-24T20:17:32.378+0100 [signalProcessingThread] now exiting
2016-03-24 20:17:32.379  INFO 8202 --- [       Thread-3] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-03-24T20:17:32.378+0100 [signalProcessingThread] dbexit: 
2016-03-24 20:17:32.380  INFO 8202 --- [       Thread-3] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-03-24T20:17:32.378+0100 [signalProcessingThread] shutdown: going to close listening sockets...
2016-03-24 20:17:32.380  INFO 8202 --- [       Thread-3] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-03-24T20:17:32.378+0100 [signalProcessingThread] closing listening socket: 5
2016-03-24 20:17:32.380  INFO 8202 --- [       Thread-3] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-03-24T20:17:32.378+0100 [signalProcessingThread] closing listening socket: 7
2016-03-24 20:17:32.380  INFO 8202 --- [       Thread-3] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-03-24T20:17:32.378+0100 [signalProcessingThread] removing socket file: /tmp/mongodb-41282.sock
2016-03-24 20:17:32.380  INFO 8202 --- [       Thread-3] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-03-24T20:17:32.378+0100 [signalProcessingThread] shutdown: going to flush diaglog...
2016-03-24 20:17:32.380  INFO 8202 --- [       Thread-3] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-03-24T20:17:32.378+0100 [signalProcessingThread] shutdown: going to close sockets...
2016-03-24 20:17:32.380  INFO 8202 --- [       Thread-3] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-03-24T20:17:32.378+0100 [signalProcessingThread] shutdown: waiting for fs preallocator...
2016-03-24 20:17:32.381  INFO 8202 --- [       Thread-3] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-03-24T20:17:32.378+0100 [signalProcessingThread] shutdown: closing all files...
2016-03-24 20:17:32.381  INFO 8202 --- [       Thread-3] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-03-24T20:17:32.379+0100 [signalProcessingThread] closeAllFiles() finished
2016-03-24 20:17:32.381  INFO 8202 --- [       Thread-3] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-03-24T20:17:32.379+0100 [signalProcessingThread] shutdown: removing fs lock...
2016-03-24 20:17:32.381  INFO 8202 --- [       Thread-3] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-03-24T20:17:32.379+0100 [signalProcessingThread] dbexit: really exiting now
2016-03-24 20:17:32.383  INFO 8202 --- [       Thread-7] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@446cdf90: startup date [Thu Mar 24 20:17:25 CET 2016]; root of context hierarchy
2016-03-24 20:17:32.385  INFO 8202 --- [       Thread-7] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2016-03-24 20:17:32.393  WARN 8202 --- [       Thread-1] d.flapdoodle.embed.mongo.runtime.Mongod  : sendShutdown /127.0.0.1:41282

java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_74]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_74]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_74]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_74]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_74]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_74]
	at de.flapdoodle.embed.mongo.runtime.Mongod.sendShutdown(Mongod.java:86) ~[de.flapdoodle.embed.mongo-1.50.2.jar!/:na]
	at de.flapdoodle.embed.mongo.AbstractMongoProcess.sendStopToMongoInstance(AbstractMongoProcess.java:133) [de.flapdoodle.embed.mongo-1.50.2.jar!/:na]
	at de.flapdoodle.embed.mongo.AbstractMongoProcess.stopInternal(AbstractMongoProcess.java:107) [de.flapdoodle.embed.mongo-1.50.2.jar!/:na]
	at de.flapdoodle.embed.process.runtime.AbstractProcess.stop(AbstractProcess.java:170) [de.flapdoodle.embed.process-1.50.1.jar!/:na]
	at de.flapdoodle.embed.process.runtime.Executable.stop(Executable.java:73) [de.flapdoodle.embed.process-1.50.1.jar!/:na]
	at de.flapdoodle.embed.process.runtime.Executable$JobKiller.run(Executable.java:90) [de.flapdoodle.embed.process-1.50.1.jar!/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_74]

2016-03-24 20:17:32.494  WARN 8202 --- [       Thread-1] d.f.embed.mongo.AbstractMongoProcess     : could not stop mongod with db command, try next
2016-03-24 20:17:32.506  INFO 8202 --- [       Thread-1] d.f.e.process.runtime.ProcessControl     : execSuccess: false [kill, -2, 8226]
2016-03-24 20:17:32.506  WARN 8202 --- [       Thread-1] d.f.embed.mongo.AbstractMongoProcess     : could not stop mongod, try next
2016-03-24 20:17:32.507  WARN 8202 --- [       Thread-1] d.f.embed.mongo.AbstractMongoProcess     : could not stop mongod the second time, try one last thing
```

This happens regardless of the way the app is run - I've tried Intellij IDEA, ```mvn spring-boot:run``` and ```java -jar```.

Looks like a race condition between shutdown hooks, potentially similar to one reported in #4135.

**Comment by philwebb** [comment]
I've spent a bit of time trying to track down why this happens and I'm afraid it doesn't look like there is much we can do. It seems the error is annoying but not actually causing any real problems.

Here's what I think happens:

When you hit ctrl-c in the terminal window the keystroke is somehow propagated to the embedded mongo process. You can see in the log that the process starts to respond:

```
2016-03-24 20:17:32.379  INFO 8202 --- [       Thread-3] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-03-24T20:17:32.378+0100 [signalProcessingThread] got signal 2 (Interrupt), will terminate after current cmd ends
```

Back in the JVM, shutdown hooks start to run and flapdoodle tries to send a network request to shutdown mongo. The problem is that mongo has already gone at this point so you get the socket error.

If instead of hitting ctrl-c, you run `kill -2` in a different terminal on the java program everything shuts down cleanly. Perhaps there is something that flapdoodle can do when it creates the process to stop ctrl-c from being propagated. I couldn't see anything obvious when I looked at their code but I would suggest raising it with them. Their issue tracker is [here](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues).

**Comment by vpavic** [comment]
@philwebb thanks for the analysis. I do agree that this falls into annoying-but-harmless category.
I'll try reporting this to flapdoodle.
