### ISSUE TITLE
Building project fails with error: "Could not find property 'main' on task ':run'"

### ISSUE THREAD

**Issue by sergeykad** [spring-projects/spring-boot#5501]
Building project fails with error seen below although I have the following configuration:
```groovy
bootRepackage {
	mainClass = 'com.mypackage.Main'
}
```

It seems to be a conflict with org.akhikhl.gretty Gradle plugin.

Using Gradle 1.12, spring-boot-gradle-plugin:1.3.3.RELEASE, org.akhikhl.gretty:gretty:+

    Caused by: groovy.lang.MissingPropertyException: Could not find property 'main' on task ':run'.
        at org.gradle.api.internal.AbstractDynamicObject.propertyMissingException(AbstractDynamicObject.java:43)
        at org.gradle.api.internal.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:35)
        at org.gradle.api.internal.CompositeDynamicObject.getProperty(CompositeDynamicObject.java:97)
        at org.gradle.api.internal.AbstractTask.property(AbstractTask.java:383)
        at org.springframework.boot.gradle.run.FindMainClassTask.findMainClass(FindMainClassTask.java:90)
        at org.springframework.boot.gradle.run.FindMainClassTask.setMainClassNameProperty(FindMainClassTask.java:56)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)

**Comment by philwebb** [comment]
That's odd, I wonder if Gretty replaced the `run` task with its own version. Perhaps @akhikhl knows?

We can certainly be more defensive in our code when trying to get the `main` property on the `run` task.

@sergeykad Do you have an example project that you could share that demonstrates the issue?

**Comment by sergeykad** [comment]
I just found the similar bug here: [https://github.com/akhikhl/gretty/issues/247](https://github.com/akhikhl/gretty/issues/247)
