### ISSUE TITLE
spring-boot-gradle-plugin - NoSuchMethodError: org.springframework.boot.loader.tools.Repackager.repackage(Ljava/io/File;Lorg/springframework/boot/loader/tools/Libraries;Lorg/springframework/boot/loader/tools/LaunchScript;)V

### ISSUE THREAD

**Issue by sergeykad** [spring-projects/spring-boot#5560]
I am running Gradle 2.12 build with org.springframework.boot:spring-boot-gradle-plugin:1.3.3.RELEASE

It's failing with the following error:
<pre>org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':foo-services:bootRepackage'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.NoSuchMethodError: org.springframework.boot.loader.tools.Repackager.repackage(Ljava/io/File;Lorg/springframework/boot/loader/tools/Libraries;Lorg/springframework/boot/loader/tools/LaunchScript;)V
        at org.springframework.boot.gradle.repackage.RepackageTask$RepackageAction.repackage(RepackageTask.java:226)
        at org.springframework.boot.gradle.repackage.RepackageTask$RepackageAction.execute(RepackageTask.java:190)
        at org.springframework.boot.gradle.repackage.RepackageTask$RepackageAction.execute(RepackageTask.java:165)
        at org.gradle.internal.Actions$FilteredAction.execute(Actions.java:202)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:110)
        at org.gradle.api.internal.tasks.RealizableTaskCollection.all(RealizableTaskCollection.java:182)
        at org.gradle.api.internal.DefaultDomainObjectCollection.withType(DefaultDomainObjectCollection.java:120)
        at org.springframework.boot.gradle.repackage.RepackageTask.repackage(RepackageTask.java:140)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:227)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 14 more

</pre>

**Comment by wilkinsona** [comment]
It works for me with Gradle 2.12. 

The missing method was added in Spring Boot 1.3.0. `Repackager` is in the `spring-boot-loader-tools` module so it looks like Gradle's somehow got an older version of `spring-boot-loader-tools` on the classpath. You can list those dependencies by adding and running a new `DependencyReportTask`:

```
task buildScriptDependencies(type: org.gradle.api.tasks.diagnostics.DependencyReportTask) {
    configurations = project.buildscript.configurations
}
```

```
gradle buildScriptDependencies
:buildScriptDependencies

------------------------------------------------------------
Root project
------------------------------------------------------------

classpath
\--- org.springframework.boot:spring-boot-gradle-plugin:1.3.3.RELEASE
     +--- org.springframework.boot:spring-boot-loader-tools:1.3.3.RELEASE
     |    \--- org.springframework:spring-core:4.2.5.RELEASE
     |         \--- commons-logging:commons-logging:1.2
     \--- io.spring.gradle:dependency-management-plugin:0.5.6.RELEASE

BUILD SUCCESSFUL

Total time: 3.169 secs
```

If that shows a mismatch, try clearing out Gradle's caches (in `~/.gradle/caches`) and building your project again.

**Comment by sergeykad** [comment]
You are right. It for some reason uses the spring-boot-loader-tools-1.2.3.RELEASE.jar despite that the dependencies graph looks like in your post.
I deleted the caches folder, restarted my PC, but it was re-downloaded on the next build run and I got the same error.

<pre>
Download https://jcenter.bintray.com/org/springframework/boot/spring-boot-loader-tools/1.2.3.RELEASE/spring-boot-loader-tools-1.2.3.RELEASE.jar
Download https://jcenter.bintray.com/org/springframework/boot/spring-boot-dependency-tools/1.2.3.RELEASE/spring-boot-dependency-tools-1.2.3.RELEASE.jar
Download https://jcenter.bintray.com/org/springframework/boot/spring-boot-gradle-plugin/1.3.3.RELEASE/spring-boot-gradle-plugin-1.3.3.RELEASE.jar
Download https://jcenter.bintray.com/org/springframework/boot/spring-boot-loader-tools/1.3.3.RELEASE/spring-boot-loader-tools-1.3.3.RELEASE.jar
Download https://jcenter.bintray.com/org/springframework/boot/spring-boot-starter-parent/1.3.3.RELEASE/spring-boot-starter-parent-1.3.3.RELEASE.pom
Download https://jcenter.bintray.com/org/springframework/boot/spring-boot-dependencies/1.3.3.RELEASE/spring-boot-dependencies-1.3.3.RELEASE.pom
Download https://jcenter.bintray.com/org/springframework/boot/spring-boot-starter/1.3.3.RELEASE/spring-boot-starter-1.3.3.RELEASE.pom
Download https://jcenter.bintray.com/org/springframework/boot/spring-boot/1.3.3.RELEASE/spring-boot-1.3.3.RELEASE.pom
Download https://jcenter.bintray.com/org/springframework/boot/spring-boot-autoconfigure/1.3.3.RELEASE/spring-boot-autoconfigure-1.3.3.RELEASE.pom
Download https://jcenter.bintray.com/org/springframework/boot/spring-boot-starter-logging/1.3.3.RELEASE/spring-boot-starter-logging-1.3.3.RELEASE.pom
Download https://jcenter.bintray.com/org/springframework/boot/spring-boot-starters/1.3.3.RELEASE/spring-boot-starters-1.3.3.RELEASE.pom
Download https://jcenter.bintray.com/org/springframework/boot/spring-boot-parent/1.3.3.RELEASE/spring-boot-parent-1.3.3.RELEASE.pom
Download https://jcenter.bintray.com/org/springframework/boot/spring-boot-starter/1.3.3.RELEASE/spring-boot-starter-1.3.3.RELEASE.jar
Download https://jcenter.bintray.com/org/springframework/boot/spring-boot/1.3.3.RELEASE/spring-boot-1.3.3.RELEASE.jar
Download https://jcenter.bintray.com/org/springframework/boot/spring-boot-autoconfigure/1.3.3.RELEASE/spring-boot-autoconfigure-1.3.3.RELEASE.jar
Download https://jcenter.bintray.com/org/springframework/boot/spring-boot-starter-logging/1.3.3.RELEASE/spring-boot-starter-logging-1.3.3.RELEASE.jar
</pre>

**Comment by sergeykad** [comment]
The wrong spring-boot-loader-tools jar version was coming from the [Gretty plugin](https://plugins.gradle.org/plugin/org.akhikhl.gretty) that I used.
As a workaround I removed Gretty from my build, but I am curious why it caused conflict and why the older version was used.

**Comment by wilkinsona** [comment]
I'm glad to hear that you figured out the problem. FWIW, I can't recreate the problem when I add the Gretty plugin. Either way, Spring Boot's plugin doesn't do anything to affect the resolution of dependencies on the buildscript classpath so, unfortunately, there's nothing we can do to help you here. Posting on the Gradle forums with a `build.gradle` that reproduces the problem is probably your best bet.
