### ISSUE TITLE
Upgrade to Cassandra Driver 2.1.10

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#5576]

**Comment by wilkinsona** [comment]
Not all modules are available at 2.1.10 (2.1.9 is the latest version of `cassandra-driver-dse` at the moment). Let's leave this one for now.

**Comment by bijukunjummen** [comment]
@wilkinsona, there appears to be transitive dependency on netty libraries also now via cassandra java drive, which are not getting resolved via the spring-boot-starter-cassandra, this leads to the following exception during startup of Cassandra boot apps, just wanted to report, I have not analyzed anymore than this at this point:

```
Caused by: java.lang.NoClassDefFoundError: io/netty/util/Timer
	at com.datastax.driver.core.Cluster$Builder.<init>(Cluster.java:685) ~[cassandra-driver-core-2.1.9.jar:na]
	at com.datastax.driver.core.Cluster.builder(Cluster.java:193) ~[cassandra-driver-core-2.1.9.jar:na]
	at org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration.cluster(CassandraAutoConfiguration.java:57) ~[spring-boot-autoconfigure-1.4.0.M2.jar:1.4.0.M2]
	at org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration$$EnhancerBySpringCGLIB$$7f63f514.CGLIB$cluster$0(<generated>) ~[spring-boot-autoconfigure-1.4.0.M2.jar:1.4.0.M2]
	at org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration$$EnhancerBySpringCGLIB$$7f63f514$$FastClassBySpringCGLIB$$9b6d5626.invoke(<generated>) ~[spring-boot-autoconfigure-1.4.0.M2.jar:1.4.0.M2]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.0.RC1.jar:4.3.0.RC1]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:355) ~[spring-context-4.3.0.RC1.jar:4.3.0.RC1]
	at org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration$$EnhancerBySpringCGLIB$$7f63f514.cluster(<generated>) ~[spring-boot-autoconfigure-1.4.0.M2.jar:1.4.0.M2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_05]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_05]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_05]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_05]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.0.RC1.jar:4.3.0.RC1]
	... 24 common frames omitted
Caused by: java.lang.ClassNotFoundException: io.netty.util.Timer
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[na:1.8.0_05]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[na:1.8.0_05]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_05]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[na:1.8.0_05]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_05]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[na:1.8.0_05]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_05]
	... 37 common frames omitted
```

**Comment by wilkinsona** [comment]
@bijukunjummen We have a Cassandra sample that's working fine, so there must be more to it. If the problem persists, please open a new issue with more details.

**Comment by bijukunjummen** [comment]
Okay, sorry forgot to mention that this happens with Spring Boot version 1.4.0.M2. I will verify once more and open a new ticket.

**Comment by javanotes** [comment]
Experienced the same issue as reported by  @bijukunjummen .

**Comment by wilkinsona** [comment]
@bijukunjummen We never figured out what @bijukunjummen's problem was as a new ticket was never opened. If you have a similar problem, please open a new issue with a sample project that reproduces it.

**Comment by bijukunjummen** [comment]
I did not get a chance to try after that @wilkinsona, @javanotes. Will give it a try with the latest Spring boot released version soon and let you guys know if I am still seeing the issue.
