### ISSUE TITLE
CLI Build fails on Windows

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#5650]
```
java.lang.IllegalArgumentException: name
	at sun.misc.URLClassPath$Loader.findResource(URLClassPath.java:494)
	at sun.misc.URLClassPath.findResource(URLClassPath.java:176)
	at java.net.URLClassLoader$2.run(URLClassLoader.java:557)
	at java.net.URLClassLoader$2.run(URLClassLoader.java:555)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findResource(URLClassLoader.java:554)
	at org.springframework.boot.loader.LaunchedURLClassLoader.findResource(LaunchedURLClassLoader.java:53)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1093)
	at org.springframework.core.io.ClassPathResource.resolveURL(ClassPathResource.java:147)
	at org.springframework.core.io.ClassPathResource.exists(ClassPathResource.java:135)
	at org.springframework.boot.cli.util.ResourceUtils.getUrlsFromPrefixedWildcardPath(ResourceUtils.java:113)
	at org.springframework.boot.cli.util.ResourceUtils.getUrlsFromWildcardPath(ResourceUtils.java:90)
	at org.springframework.boot.cli.util.ResourceUtils.getUrls(ResourceUtils.java:77)
	at org.springframework.boot.cli.command.options.SourceOptions.<init>(SourceOptions.java:81)
	at org.springframework.boot.cli.command.options.SourceOptions.<init>(SourceOptions.java:69)
	at org.springframework.boot.cli.command.options.SourceOptions.<init>(SourceOptions.java:47)
	at org.springframework.boot.cli.command.run.RunCommand$RunOptionHandler.run(RunCommand.java:95)
	at org.springframework.boot.cli.command.options.OptionHandler.run(OptionHandler.java:84)
	at org.springframework.boot.cli.command.OptionParsingCommand.run(OptionParsingCommand.java:54)
	at org.springframework.boot.cli.command.CommandRunner.run(CommandRunner.java:219)
	at org.springframework.boot.cli.command.CommandRunner.runAndHandleErrors(CommandRunner.java:171)
	at org.springframework.boot.cli.SpringCli.main(SpringCli.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58)
Cannot create URL from path [C:/Users/pwebb/projects/spring-boot/code/spring-boot-cli/target/test-app.jar]

class path resource [C:/Users/pwebb/projects/spring-boot/code/spring-boot-cli/target/test-app.jar]
java.lang.IllegalArgumentException: name
	at sun.misc.URLClassPath$Loader.findResource(URLClassPath.java:494)
	at sun.misc.URLClassPath.findResource(URLClassPath.java:176)
	at java.net.URLClassLoader$2.run(URLClassLoader.java:557)
	at java.net.URLClassLoader$2.run(URLClassLoader.java:555)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findResource(URLClassLoader.java:554)
	at org.springframework.boot.loader.LaunchedURLClassLoader.findResource(LaunchedURLClassLoader.java:53)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1093)
	at org.springframework.core.io.ClassPathResource.resolveURL(ClassPathResource.java:147)
	at org.springframework.core.io.ClassPathResource.exists(ClassPathResource.java:135)
	at org.springframework.boot.cli.util.ResourceUtils.getUrlsFromPrefixedWildcardPath(ResourceUtils.java:113)
	at org.springframework.boot.cli.util.ResourceUtils.getUrlsFromWildcardPath(ResourceUtils.java:90)
	at org.springframework.boot.cli.util.ResourceUtils.getUrls(ResourceUtils.java:77)
	at org.springframework.boot.cli.command.options.SourceOptions.<init>(SourceOptions.java:81)
	at org.springframework.boot.cli.command.options.SourceOptions.<init>(SourceOptions.java:69)
	at org.springframework.boot.cli.command.options.SourceOptions.<init>(SourceOptions.java:47)
	at org.springframework.boot.cli.command.run.RunCommand$RunOptionHandler.run(RunCommand.java:95)
	at org.springframework.boot.cli.command.options.OptionHandler.run(OptionHandler.java:84)
	at org.springframework.boot.cli.command.OptionParsingCommand.run(OptionParsingCommand.java:54)
	at org.springframework.boot.cli.command.CommandRunner.run(CommandRunner.java:219)
	at org.springframework.boot.cli.command.CommandRunner.runAndHandleErrors(CommandRunner.java:171)
	at org.springframework.boot.cli.SpringCli.main(SpringCli.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58)
Cannot create URL from path [C:/Users/pwebb/projects/spring-boot/code/spring-boot-cli/target/test-app.jar]
```

Looks like #486

**Comment by wilkinsona** [comment]
I am pretty sure that I discovered that the assertion that `URLClassLoader` would handle the fully-qualified path was wrong. I think the escape hatch from #486 is more of a workaround and I'd prefer not to reinstate it if possible. If there's time, I'd like to track down the root cause this morning and perhaps implement a different fix.

**Comment by wilkinsona** [comment]
The test added in #486 was:

```java
// This path is invalid - it should return null even on Windows.
// A regular URLClassLoader will deal with it gracefully.
assertNull(getClass().getClassLoader().getResource(
		"c:\\Users\\user\\bar.properties"));
LaunchedURLClassLoader loader = new LaunchedURLClassLoader(new URL[] { new URL(
		"jar:file:src/test/resources/jars/app.jar!/") }, getClass()
		.getClassLoader());
// So we should too...
assertNull(loader.getResource("c:\\Users\\user\\bar.properties"));
```

The reason that the first assertion passes while the second was throwing an `IllegalArgumentException` isn't due to differences between `URLClassLoader` and `LaunchedURLClassLoader`, it's because the two class loaders have different class paths. If a plain `URLClassLoader` is created with the same class path, it too will throw an `IllegalArgumentException`:

```java
URLClassLoader plainLoader = new URLClassLoader(
		new URL[] { new URL("jar:file:src/test/resources/jars/app.jar!/") },
		getClass().getClassLoader());
plainLoader.getResource("c:\\Users\\user\\bar.properties"); // Throws IllegalArgumentException
```

**Comment by wilkinsona** [comment]
If the class loaders are created with `file:/src/test/resources/jars/app.jar` as the URL, then neither throws an `IllegalArgumentException`.

The `IllegalArgumentException` is being thrown by `Loader` due to a `MalformedURLException` when the supplied `name` is used to create a new `URL`. The different behaviour is a result of the different URLs causing `URLClassPath` to use a different loader. When the URL is `file:/src/test/resources/jars/app.jar` a `JarLoader` is used. `JarLoader` does not try to create a new URL using the given name. When the URL is `jar:file:src/test/resources/jars/app.jar!/` a `Loader` is used. `Loader` tries to create a new `URL` with `context` `jar:file:src/test/resources/jars/app.jar!/` and `spec` `c:%5cUsers%5cuser%5cbar.properties` which results in a `MalformedURLException` with the message `unknown protocol: c`.

**Comment by wilkinsona** [comment]
The underlying cause of the failure in the CLI build is that any URL containing a `:` is treated as an explicit `file:`, `classpath:` or `classpath*:` URL. This means that any fully-qualified Windows path is handled incorrectly and goes down a different code path to a fully-qualified path on a Unix-like platform.
