### ISSUE TITLE
Devtools startup exception on invalid manifest

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#5665]
To reproduce just use devtools and drop the following dependency:

```
<dependency>
	<groupId>org.ehcache</groupId>
	<artifactId>ehcache</artifactId>
	<version>3.0.0.rc2</version>
</dependency>
```

This dependency contains the following manifest:

```
Manifest-Version: 1.0
provider: gradle
Implementation-Title: ehcache
Implementation-Version: 3.0.0.rc2 bb924219d30952dfaa97b6702ca1a4547a17
 7ba2
Built-By: jenkins-slave
Built-JDK: 1.6.0_45
Build-Time: 2016-03-25T06:29:33-0700
Class-Path: slf4j-api-1.7.7.jar
...
```

This fails 

```
Exception in thread "main" java.lang.IllegalStateException: Class-Path attribute contains malformed URL
	at org.springframework.boot.devtools.restart.ChangeableUrls.getUrlsFromClassPathAttribute(ChangeableUrls.java:133)
	at org.springframework.boot.devtools.restart.ChangeableUrls.getUrlsFromClassPathOfJarManifestIfPossible(ChangeableUrls.java:99)
	at org.springframework.boot.devtools.restart.ChangeableUrls.fromUrlClassLoader(ChangeableUrls.java:88)
	at org.springframework.boot.devtools.restart.DefaultRestartInitializer.getUrls(DefaultRestartInitializer.java:91)
	at org.springframework.boot.devtools.restart.DefaultRestartInitializer.getInitialUrls(DefaultRestartInitializer.java:54)
	at org.springframework.boot.devtools.restart.Restarter.<init>(Restarter.java:133)
	at org.springframework.boot.devtools.restart.Restarter.initialize(Restarter.java:519)
	at org.springframework.boot.devtools.restart.RestartApplicationListener.onApplicationStartedEvent(RestartApplicationListener.java:68)
	at org.springframework.boot.devtools.restart.RestartApplicationListener.onApplicationEvent(RestartApplicationListener.java:45)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:121)
	at org.springframework.boot.context.event.EventPublishingRunListener.publishEvent(EventPublishingRunListener.java:111)
	at org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:60)
	at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:48)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1182)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1171)
	at com.example.cfp.CfpApplication.main(CfpApplication.java:21)
Caused by: java.net.MalformedURLException: no protocol: slf4j-api-1.7.7.jar
	at java.net.URL.<init>(URL.java:586)
	at java.net.URL.<init>(URL.java:483)
	at java.net.URL.<init>(URL.java:432)
	at org.springframework.boot.devtools.restart.ChangeableUrls.getUrlsFromClassPathAttribute(ChangeableUrls.java:130)
	... 18 more
```

**Comment by snicoll** [comment]
Maybe related to #5127
