### ISSUE TITLE
Multiple MBeanExporter are created

### ISSUE THREAD

**Issue by romainmoreau** [spring-projects/spring-boot#5682]
Here are three Spring Boot parts that are relying on JMX:
- the `spring-boot-starter-actuator` dependency;
- the `@EnableMBeanExport` annotation;
- a Spring Boot App profile to launch the application from Eclipse using Spring Tool Suite 3.7.3.RELEASE.

When these three parts are used together with Spring Boot 1.4.0.M2, the application fails to start:

```
2016-04-13 19:22:51.399 ERROR 3748 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfiguration': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfiguration$$EnhancerBySpringCGLIB$$5b336419]: Constructor threw exception; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [org.springframework.jmx.export.MBeanExporter] is defined: expected single matching bean but found 2: mbeanExporter,endpointMBeanExporter
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:279) ~[spring-beans-4.3.0.RC1.jar:4.3.0.RC1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1143) ~[spring-beans-4.3.0.RC1.jar:4.3.0.RC1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046) ~[spring-beans-4.3.0.RC1.jar:4.3.0.RC1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510) ~[spring-beans-4.3.0.RC1.jar:4.3.0.RC1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.3.0.RC1.jar:4.3.0.RC1]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.0.RC1.jar:4.3.0.RC1]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.0.RC1.jar:4.3.0.RC1]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.0.RC1.jar:4.3.0.RC1]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.0.RC1.jar:4.3.0.RC1]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:775) ~[spring-beans-4.3.0.RC1.jar:4.3.0.RC1]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:841) ~[spring-context-4.3.0.RC1.jar:4.3.0.RC1]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:540) ~[spring-context-4.3.0.RC1.jar:4.3.0.RC1]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:765) [spring-boot-1.4.0.M2.jar:1.4.0.M2]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) [spring-boot-1.4.0.M2.jar:1.4.0.M2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-1.4.0.M2.jar:1.4.0.M2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1182) [spring-boot-1.4.0.M2.jar:1.4.0.M2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1171) [spring-boot-1.4.0.M2.jar:1.4.0.M2]
	at fr.romainmoreau.JmxReproApplication.main(JmxReproApplication.java:11) [classes/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfiguration$$EnhancerBySpringCGLIB$$5b336419]: Constructor threw exception; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [org.springframework.jmx.export.MBeanExporter] is defined: expected single matching bean but found 2: mbeanExporter,endpointMBeanExporter
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163) ~[spring-beans-4.3.0.RC1.jar:4.3.0.RC1]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122) ~[spring-beans-4.3.0.RC1.jar:4.3.0.RC1]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:271) ~[spring-beans-4.3.0.RC1.jar:4.3.0.RC1]
	... 17 common frames omitted
Caused by: org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [org.springframework.jmx.export.MBeanExporter] is defined: expected single matching bean but found 2: mbeanExporter,endpointMBeanExporter
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveNotUnique(DependencyDescriptor.java:172) ~[spring-beans-4.3.0.RC1.jar:4.3.0.RC1]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1059) ~[spring-beans-4.3.0.RC1.jar:4.3.0.RC1]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory$DependencyObjectProvider.getIfAvailable(DefaultListableBeanFactory.java:1544) ~[spring-beans-4.3.0.RC1.jar:4.3.0.RC1]
	at org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfiguration.<init>(SpringApplicationAdminJmxAutoConfiguration.java:63) ~[spring-boot-autoconfigure-1.4.0.M2.jar:1.4.0.M2]
	at org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfiguration$$EnhancerBySpringCGLIB$$5b336419.<init>(<generated>) ~[spring-boot-autoconfigure-1.4.0.M2.jar:1.4.0.M2]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_77]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_77]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_77]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_77]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147) ~[spring-beans-4.3.0.RC1.jar:4.3.0.RC1]
	... 19 common frames omitted
```

A workaround is to simply not use one of these parts.
With Spring Boot 1.3.3 or 1.4.0.M1, there is no issue.

Here's a reproduction project: https://github.com/romainmoreau/jmx-repro

**Comment by wilkinsona** [comment]
Multiple MBeans are also create in 1.4.0.M1, however a `NoUniqueBeanDefinitionException` is not thrown. This is because `SpringApplicationAdminJmxAutoConfiguration` had its `MBeanExporter` injected into a field named `mbeanExporter` and this is an exact match for the name of one of the `MBeanExporter` beans.

In 1.4.0.M2, `SpringApplicationAdminJmxAutoConfiguration` has been updated to use constructor injection. An `ObjectProvider<MBeanExporter>` is now injected using the name `mbeanExporterProvider`. This change in name means that there's no longer an exact match with the name of one of the `MBeanExporter` beans and a `NoUniqueBeanDefinitionException` results.

We could change the name of the constructor argument, but, ideally, we'd address the underlying problem of there being multiple `MBeanExporter` beans in the context, none of which is `@Primary`. Unfortunately, I'm not sure that's possible when `@EnableMBeanExport` is used as the creation of the `MBeanExporter` bean is then out of Boot's control.

@romainmoreau Is there a reason why you are using `@EnableMBeanExport`? In its absence, Spring Boot will auto-configure an `MBeanExporter` for you, with the added bonus that it is marked `@Primary` thereby avoiding the problem described above.

**Comment by romainmoreau** [comment]
If I [remove the `spring-boot-starter-actuator`dependency and remove the `@EnableMBeanExport`annotation](https://github.com/romainmoreau/jmx-repro/commit/58ec84adf4831eb6ac993d24b3a1aa2ddc56b4f6) in the reproduction project, any `@ManagedResource` aren't auto configured by Spring Boot, so `@ManagedOperation` annotated methods aren't exposed to JMX

I suppose that it's the presence of `spring-boot-starter-actuator`dependency that activates the auto configuration, not the presence of the `@ManagedResource` or the `@ManagedOperation` annotations.

So, to answer more specifically your question, I was keeping the `@EnableMBeanExport` annotation in order to have more modularity: if some day I wouldn't need the `spring-boot-starter-actuator`dependency anymore, I could have removed it without worrying about breaking the managed operations which are silently not exposed to JMX.

**Comment by snicoll** [comment]
That's not what I see. `JmxAutoConfiguration` is responsible of that and has nothing to do with the actuator. I agree with @wilkinsona, by adding that annotation you're working around what Boot does (correctly) by default (that is creating a `@Primary` `MBeanExporter`). 

Can you double check or share a sample that reproduces the issue please?

**Comment by romainmoreau** [comment]
I notice that I forgot the `@Component` annotation on my [reproduction project](https://github.com/romainmoreau/jmx-repro) and my managed method was `private`...

So you guys are right: I don't need the `@EnableMBeanExport` annotation anymore.

Sorry for the false alarm.

**Comment by salmar** [comment]
Spring Integration also creates its own `MBeanExporter` (see [IntegrationAutoConfiguration](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/integration/IntegrationAutoConfiguration.java)) marked as `@Primary`. When upgrading to Spring Boot 1.4, two `@Primary` `MBeanExporter`s are created, leading to the following stacktrace:

```
Caused by: org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [org.springframework.jmx.export.MBeanExporter] is defined: more than one 'primary' bean found among candidates: [mbeanExporter, integrationMbeanExporter, endpointMBeanExporter]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.determinePrimaryCandidate(DefaultListableBeanFactory.java:1285) ~[spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.determineAutowireCandidate(DefaultListableBeanFactory.java:1246) ~[spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1061) ~[spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory$DependencyObjectProvider.getIfAvailable(DefaultListableBeanFactory.java:1549) ~[spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
	at org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfiguration.<init>(SpringApplicationAdminJmxAutoConfiguration.java:63) ~[spring-boot-autoconfigure-1.4.0.RC1.jar:1.4.0.RC1]
	at org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfiguration$$EnhancerBySpringCGLIB$$47222922.<init>(<generated>) ~[spring-boot-autoconfigure-1.4.0.RC1.jar:1.4.0.RC1]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408) ~[na:1.8.0]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147) ~[spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
	... 25 common frames omitted
```

**Comment by wilkinsona** [comment]
@salmar Are you using `@EnableMBeanExport`? If not, can you please open a separate issue with details of how to reproduce your problem?

**Comment by salmar** [comment]
I'm not using `@EnableMBeanExport`. Will try to build a sample to reproduce it

**Comment by snicoll** [comment]
Isn't that #6328 anyway?
