### ISSUE TITLE
NoClassDefFoundError in testing upgrading to boot 1.4.M2

### ISSUE THREAD

**Issue by Polve** [spring-projects/spring-boot#5695]
I'm using boot 1.3 and tried to upgrade to latest milestone to be sure my code keeps working fine.
I've problems in my test classes, they now fail with this error:
```
java.lang.NoClassDefFoundError: Could not initialize class org.springframework.test.context.junit4.SpringRunner
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:29)
        at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:21)
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
        at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
        at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:26)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

Even if I migrated the class annotations from:

```
> @RunWith(SpringJUnit4ClassRunner.class)
> @SpringApplicationConfiguration(classes = TestConfig.class)
```

to

```
> @RunWith(SpringRunner.class)
> @SpringBootTest(classes = TestConfig.class)
```

Is there anything else I've to do to make my tests work again?

**Comment by philwebb** [comment]
Could you please check what version of `spring-test` you're using. Spring Boot 1.4.M2 needs Spring Framework 4.3.RC1.

**Comment by Polve** [comment]
I'm not pinning the spring version so boot should pull the right one automatically.
I checked with mvn dependency:resolve and I indeed find:
[INFO]    org.springframework:spring-test:jar:4.3.0.RC1:test

**Comment by wilkinsona** [comment]
@Polve Were there any earlier exceptions logged? A `NoClassDefFoundError` is typically a knock-on effect of an earlier failure to load and define a class. Failing that, can you please provide a small sample that reproduces the problem?

**Comment by wilkinsona** [comment]
@Polve One more thing: what version of JUnit are you using? You'll need 4.12.

**Comment by Polve** [comment]
Doh! It's pulling junit 4.11.
Shouldn't spring declare correct dependencies for that?

**Comment by snicoll** [comment]
You are probably overriding it somewhere. Hard for us to tell without looking at the actual project.

**Comment by Polve** [comment]
Culprit found: for reason I don't remember I was pinning junit to version 4.11, my bad.

I'm sorry for the noise, thanks very much for the help
