### ISSUE TITLE
NullPointerException with devtools in 1.4.0.M2

### ISSUE THREAD

**Issue by wangxufire** [spring-projects/spring-boot#5704]
```
Exception in thread "main" java.lang.NullPointerException
	at org.springframework.boot.devtools.restart.ChangeableUrls.getUrlsFromClassPathAttribute(ChangeableUrls.java:121)
	at org.springframework.boot.devtools.restart.ChangeableUrls.getUrlsFromClassPathOfJarManifestIfPossible(ChangeableUrls.java:99)
	at org.springframework.boot.devtools.restart.ChangeableUrls.fromUrlClassLoader(ChangeableUrls.java:88)
	at org.springframework.boot.devtools.restart.DefaultRestartInitializer.getUrls(DefaultRestartInitializer.java:91)
	at org.springframework.boot.devtools.restart.DefaultRestartInitializer.getInitialUrls(DefaultRestartInitializer.java:54)
	at org.springframework.boot.devtools.restart.Restarter.<init>(Restarter.java:133)
	at org.springframework.boot.devtools.restart.Restarter.initialize(Restarter.java:519)
	at org.springframework.boot.devtools.restart.RestartApplicationListener.onApplicationStartedEvent(RestartApplicationListener.java:68)
	at org.springframework.boot.devtools.restart.RestartApplicationListener.onApplicationEvent(RestartApplicationListener.java:45)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:121)
	at org.springframework.boot.context.event.EventPublishingRunListener.publishEvent(EventPublishingRunListener.java:111)
	at org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:60)
	at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:48)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
```
worked correctly with 1.3.3.RELEASE

**Comment by wilkinsona** [comment]
The [line in question](https://github.com/spring-projects/spring-boot/blob/v1.4.0.M2/spring-boot-devtools/src/main/java/org/springframework/boot/devtools/restart/ChangeableUrls.java#L121) is:

```
		String classPath = manifest.getMainAttributes()
				.getValue(Attributes.Name.CLASS_PATH);
```

`manifest` must be `null` (`getMainAttributes` will never return `null`), so I guess there's a jar on the classpath that doesn't have a `META-INF/MANIFEST.MF`.
