### ISSUE TITLE
Spring loaded 1.2.5.RELEASE does not work with Spring Boot 1.4.0.M2

### ISSUE THREAD

**Issue by hantsy** [spring-projects/spring-boot#5710]
I am trying to upgrade my samples to the latest 1.4.0.M2 and the springloaded caused failure when run `mvn spring-boot:run`.

The spring boot maven plugin configuration

            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <dependencies>
                    <dependency>
                        <groupId>org.springframework</groupId>
                        <artifactId>springloaded</artifactId>
                        <version>1.2.5.RELEASE</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>

And spring devtools is added as a dependency in the Maven POM file.

It worked with Spring Boot 1.3.3.RELEASE, and I checked the docs of 1.4.0.M2, it still described howt to use Springloaded 1.2.0.RELEASE and Spring Boot 1.4.0.M2 which was also not worked in my example.

My example: [https://github.com/hantsy/angularjs-springmvc-sample-boot](https://github.com/hantsy/angularjs-springmvc-sample-boot)

The errors I got fromc cmd window when run `mvn spring-boot:run`.

	[INFO] Attaching agents: [E:\Users\hantsy\.m2\repository\org\springframework\springloaded\1.2.5.RELEASE\springloaded-1.2.5.RELEASE.jar]
	Exception in thread "main" java.lang.NullPointerException
			at org.springframework.boot.devtools.restart.ChangeableUrls.getUrlsFromClassPathAttribute(ChangeableUrls.java:121)
			at org.springframework.boot.devtools.restart.ChangeableUrls.getUrlsFromClassPathOfJarManifestIfPossible(ChangeableUrls.java:99)
			at org.springframework.boot.devtools.restart.ChangeableUrls.fromUrlClassLoader(ChangeableUrls.java:88)
			at org.springframework.boot.devtools.restart.DefaultRestartInitializer.getUrls(DefaultRestartInitializer.java:91)
			at org.springframework.boot.devtools.restart.DefaultRestartInitializer.getInitialUrls(DefaultRestartInitializer.java:54)
			at org.springframework.boot.devtools.restart.Restarter.<init>(Restarter.java:133)
			at org.springframework.boot.devtools.restart.Restarter.initialize(Restarter.java:519)
			at org.springframework.boot.devtools.restart.RestartApplicationListener.onApplicationStartedEvent(RestartApplicationListener.java:68)
			at org.springframework.boot.devtools.restart.RestartApplicationListener.onApplicationEvent(RestartApplicationListener.java:45)
			at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
			at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
			at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:121)
			at org.springframework.boot.context.event.EventPublishingRunListener.publishEvent(EventPublishingRunListener.java:111)
			at org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:60)
			at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:48)
			at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
			at org.springframework.boot.SpringApplication.run(SpringApplication.java:1182)
			at org.springframework.boot.SpringApplication.run(SpringApplication.java:1171)
			at com.hantsylabs.restexample.springmvc.Application.main(Application.java:67)

**Comment by wilkinsona** [comment]
Duplicates #5704
