### ISSUE TITLE
@MockBean does not work for @RefreshScope bean

### ISSUE THREAD

**Issue by colin-shine** [spring-projects/spring-boot#5724]
Sample project:
https://github.com/colin-shine/mockbean-issue

Run the `MyTest` to see the problem.

Spring Boot: `v1.4.0.M2`
Spring Cloud Config: `1.1.0.RC2`

`@MockBean` detects 2 beans instead of one:

```
java.lang.IllegalStateException: Unable to register mock bean issues.spring.shine.colin.BeanB expected a single existing bean to replace but found [beanB, scopedTarget.beanB]
	at org.springframework.boot.test.mock.mockito.MockitoPostProcessor.getBeanName(MockitoPostProcessor.java:218)
	at org.springframework.boot.test.mock.mockito.MockitoPostProcessor.registerMock(MockitoPostProcessor.java:171)
	at org.springframework.boot.test.mock.mockito.MockitoPostProcessor.register(MockitoPostProcessor.java:161)
	at org.springframework.boot.test.mock.mockito.MockitoPostProcessor.postProcessBeanFactory(MockitoPostProcessor.java:131)
	at org.springframework.boot.test.mock.mockito.MockitoPostProcessor.postProcessBeanFactory(MockitoPostProcessor.java:119)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:284)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:174)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:680)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:522)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:765)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:104)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:98)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:116)
	... 27 more
```

**Comment by colin-shine** [comment]
FYI, I currently use [this approach](https://lkrnac.net/blog/2015/12/mock-spring-bean-v2/), which works perfectly. The `@Primary` mock takes precedence over the 2 beans (the proxy and target).

**Comment by colin-shine** [comment]
I have hacked together a fix to the problem [here](https://github.com/colin-shine/mockbean-issue/commit/333bf3bfe19e5e706997cf6a08fdb799e097d21e), using the new `TypeExcludeFilters` mechanism, as it seemed the easiest way to get started. 

Am I on the right path here? It seems a bit messy doing String comparisons on all implemented interfaces etc. I'd prefer to do an `isAssignableFrom` check instead

**Comment by colin-shine** [comment]
I've made a stab at a fix [here](https://github.com/colin-shine/mockbean-issue/commit/669a873463d709d14e5e88769de08e303bb69dcd), using a `ContextCustomizer` and a `BeanFactoryPostProcessor`.

It gets all `@MockBean` fields from the test class and looks for any `@RefreshScope` beans of the same type. If any are found, the bean definitions are removed, which removes the duplicate causing the problem.

Am I on the right track here? Would this form the basis of some kind of test auto configuration in the Spring Cloud Config project?

**Comment by spencergibb** [comment]
BTW, `@RefreshScope` is part of spring-cloud-commons, not spring-cloud-config.

**Comment by philwebb** [comment]
The `scopedTarget.` prefix is used by [ScopedProxyUtils](https://github.com/spring-projects/spring-framework/blob/183594207fbb447e1b59262b4469f2aefbb8a3ec/spring-aop/src/main/java/org/springframework/aop/scope/ScopedProxyUtils.java#L37) so I think it's safe to just filter those from the candidates.

**Comment by colin-shine** [comment]
@philwebb I have created an [Issues Pull Request](https://github.com/spring-projects/spring-boot-issues/pull/48) incorporating your feedback.

**Comment by philwebb** [comment]
Thanks @colin-shine
