### ISSUE TITLE
mvn spring-boot:run fails with fork and/or jvmArguments with 1.4.0.M3

### ISSUE THREAD

**Issue by kuhnroyal** [spring-projects/spring-boot#5736]
I have a maven plugin configuration with `jvmArguments` set, this implies `fork=true`. Startup fails with the provided stacktrace. Removing `jvmArguments works.
Removing `jvmArguments` and setting `fork=true` fails as well.

```
Exception in thread "main" java.lang.NullPointerException
	at org.springframework.boot.devtools.restart.ChangeableUrls.getUrlsFromClassPathAttribute(ChangeableUrls.java:121)
	at org.springframework.boot.devtools.restart.ChangeableUrls.getUrlsFromClassPathOfJarManifestIfPossible(ChangeableUrls.java:99)
	at org.springframework.boot.devtools.restart.ChangeableUrls.fromUrlClassLoader(ChangeableUrls.java:88)
	at org.springframework.boot.devtools.restart.DefaultRestartInitializer.getUrls(DefaultRestartInitializer.java:91)
	at org.springframework.boot.devtools.restart.DefaultRestartInitializer.getInitialUrls(DefaultRestartInitializer.java:54)
	at org.springframework.boot.devtools.restart.Restarter.<init>(Restarter.java:133)
	at org.springframework.boot.devtools.restart.Restarter.initialize(Restarter.java:519)
	at org.springframework.boot.devtools.restart.RestartApplicationListener.onApplicationStartedEvent(RestartApplicationListener.java:68)
	at org.springframework.boot.devtools.restart.RestartApplicationListener.onApplicationEvent(RestartApplicationListener.java:45)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:121)
	at org.springframework.boot.context.event.EventPublishingRunListener.publishEvent(EventPublishingRunListener.java:111)
	at org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:60)
	at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:48)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
	at com.example.Application.main(Application.java:33)
```

**Comment by snicoll** [comment]
Duplicates #5704
