### ISSUE TITLE
spring boot 1.4.0.M2 breaks tests using hateaos

### ISSUE THREAD

**Issue by runningonfumes** [spring-projects/spring-boot#5758]
A test that worked in 1.4.0.M1 does no longer work for M2.

It is related to jackson and the use of hateaos.

The setup is like this

        mockMvc = MockMvcBuilders.standaloneSetup(myController)
                        .setMessageConverters(HalConverter.createHALMessageConverter())
                        .setControllerAdvice(new GlobalControllerExceptionHandler())
                        .build();

The HalConverter class is as follows : 

        public class HalConverter {
            public static HttpMessageConverter<Object> createHALMessageConverter() {
                ObjectMapper objectMapper = new ObjectMapper();
                objectMapper.registerModule(new Jackson2HalModule());

                CurieProvider curieProvider = new DefaultCurieProvider("a", new UriTemplate("http://localhost:8080/myapp/rels/{rel}"));
                objectMapper.setHandlerInstantiator(new Jackson2HalModule.HalHandlerInstantiator(new DefaultRelProvider(), curieProvider, null));

                MappingJackson2HttpMessageConverter halConverter = new MappingJackson2HttpMessageConverter();
                halConverter.setObjectMapper(objectMapper);
                halConverter.setSupportedMediaTypes(Arrays.asList(MediaTypes.HAL_JSON, MediaType.APPLICATION_JSON));

                return halConverter;
            }
        }

Running the test gives the following error

    11:55:44.582 [main] WARN org.springframework.http.converter.json.MappingJackson2HttpMessageConverter - Failed to evaluate deserialization for type [simple type, class com.thanksys.presentment.MyResource]
            org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.hateoas.hal.Jackson2HalModule$HalLinkListDeserializer]: Constructor threw exception; nested exception is java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.deser.std.ContainerDeserializerBase: method <init>(Ljava/lang/Class;)V not found
            at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163)
            at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:104)
            at org.springframework.hateoas.hal.Jackson2HalModule$HalHandlerInstantiator.findInstance(Jackson2HalModule.java:682)
            at org.springframework.hateoas.hal.Jackson2HalModule$HalHandlerInstantiator.deserializerInstance(Jackson2HalModule.java:692)
            at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.deserializerInstance(DefaultDeserializationContext.java:232)
            at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findDeserializerFromAnnotation(BasicDeserializerFactory.java:1772)
            at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.constructSettableProperty(BeanDeserializerFactory.java:728)
            at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.addBeanProps(BeanDeserializerFactory.java:509)
            at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:228)
            at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:143)
            at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:406)
            at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:352)
            at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
            at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
            at com.fasterxml.jackson.databind.deser.DeserializerCache.hasValueDeserializerFor(DeserializerCache.java:191)
            at com.fasterxml.jackson.databind.DeserializationContext.hasValueDeserializerFor(DeserializationContext.java:422)
            at com.fasterxml.jackson.databind.ObjectMapper.canDeserialize(ObjectMapper.java:2646)
            at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.canRead(AbstractJackson2HttpMessageConverter.java:147)
            at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodArgumentResolver.readWithMessageConverters(AbstractMessageConverterMethodArgumentResolver.java:191)
            at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.readWithMessageConverters(RequestResponseBodyMethodProcessor.java:153)
            at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.resolveArgument(RequestResponseBodyMethodProcessor.java:131)
            at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:121)
            at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:161)
            at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:128)
            at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:114)
            at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
            at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
            at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
            at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
            at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
            at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
            at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:883)
            at javax.servlet.http.HttpServlet.service(HttpServlet.java:651)
            at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
            at org.springframework.test.web.servlet.TestDispatcherServlet.service(TestDispatcherServlet.java:65)
            at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
            at org.springframework.mock.web.MockFilterChain$ServletFilterProxy.doFilter(MockFilterChain.java:167)
            at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:134)
            at org.springframework.test.web.servlet.MockMvc.perform(MockMvc.java:155)
            at com.thanksys.presentment.MyControllerTest.testPut(MyControllerTest.java:84)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:497)
            at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
            at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
            at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
            at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
            at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
            at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
            at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
            at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
            at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
            at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
            at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
            at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
            at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
            at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
            at org.mockito.internal.runners.JUnit45AndHigherRunnerImpl.run(JUnit45AndHigherRunnerImpl.java:37)
            at org.mockito.runners.MockitoJUnitRunner.run(MockitoJUnitRunner.java:62)
            at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
            at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
            at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
            at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
            at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:497)
            at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
            Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.deser.std.ContainerDeserializerBase: method <init>(Ljava/lang/Class;)V not found
            at org.springframework.hateoas.hal.Jackson2HalModule$HalLinkListDeserializer.<init>(Jackson2HalModule.java:519)
            at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
            at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
            at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
            at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
            ... 69 common frames omitted
            11:55:44.583 [main] DEBUG org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod - Error resolving argument [1] [type=com.thanksys.presentment.MyResource]
            HandlerMethod details:

**Comment by wilkinsona** [comment]
Thanks for the report. Unfortunately, this code path in Spring HATEOAS is incompatible with Jackson 2.7 due to the removal of the `ContainerSerializerBase(Class<?>)` constructor in [this commit](https://github.com/FasterXML/jackson-databind/commit/a5301ba825a33f95ca9749655d2ccf67c0f512a3#diff-431839367c5eccdcd048960395c0782dL28). This appears to be a [known issue](https://github.com/spring-projects/spring-hateoas/issues/438). Until a fix is available, you should be able to downgrade to Jackson 2.6.x.

@olivergierke @gregturn we could do with a fix for the HATEOAS issue in time for Boot 1.4's release please.

**Comment by olivergierke** [comment]
We kind of live in the tension of any version before Spring 4.3 not supporting Jackson 2.7 anyway and Spring HATEOAS and Spring Data upgrading to Jackson 2.7 but stay on Spring 4.2 this creates a weird situation. I'll have a look what we can do to maybe still compile against Jackson 2.6 but make sure we run fine against 2.7.

**Comment by runningonfumes** [comment]
At least for now, downgrading Jackson to 2.6.6 did indeed solve the issue. 

Thanks

**Comment by benavid** [comment]
Hi, I am having the same issue. I think that is a problem with the dependencies. I am using the following configuration:

org.springframework.data:spring-data-rest-webmvc:2.2.0.RELEASE
org.springframework:spring-webmvc:4.0.7.RELEASE
org.springframework:spring-context:4.0.7.RELEASE
org.elasticsearch:elasticsearch:2.4.0
com.fasterxml.jackson.core:jackson-databind:2.8.1
spring-test 4.1.1.RELEASE

Any idea what could be the problem?

**Comment by philwebb** [comment]
@benavid This issue has been closed for a while. Please ask any questions on stackoverflow.com. Having a dependency on `spring-context` and `spring-webmvc` 4.0.7 looks very odd to me. I would recommend using Spring Boot's managed dependencies if at all possible.
