### ISSUE TITLE
Cannot use sliced tests with caching

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#5765]
I am trying to write a slice of my app and that app has `@EnableCaching` on it.

This is what I get:

```
Caused by: java.lang.IllegalStateException: No CacheResolver specified, and no bean of type CacheManager found. Register a CacheManager bean or remove the @EnableCaching annotation from your configuration.
	at org.springframework.cache.interceptor.CacheAspectSupport.afterSingletonsInstantiated(CacheAspectSupport.java:192)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:795)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:841)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:540)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:765)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:104)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:98)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:116)
	... 28 more
```

It looks like that such slices do not invoke certain auto-configurations (typically here we could just set it to "none" via a property). I've tried with `DataJpaTest` and `WebMvcTest`.

**Comment by philwebb** [comment]
I think we should add a `@ImportBaseAutoConfiguration` or something similar to import common things like this.

**Comment by nekperu15739** [comment]
Hi, i'm having the same problem running a test with @JooqTest and spring boot 2.1.5.RELEASE, any ideas?

`Caused by: java.lang.IllegalStateException: No CacheResolver specified, and no bean of type CacheManager found. Register a CacheManager bean or remove the @EnableCaching annotation from your configuration.
	at org.springframework.cache.interceptor.CacheAspectSupport.afterSingletonsInstantiated(CacheAspectSupport.java:227)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:860)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:127)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:117)
	... 25 more`

**Comment by wilkinsona** [comment]
@nekperu15739 It looks like we missed annotating `@JooqTest` with `@AutoConfigureCache`. Can you please open a new issue so that we can correct this? In the meantime, adding `@AutoConfigureCache` to your test class alongside `@JooqTest` should work around the problem.

**Comment by nekperu15739** [comment]
> @nekperu15739 It looks like we missed annotating `@JooqTest` with `@AutoConfigureCache`. Can you please open a new issue so that we can correct this? In the meantime, adding `@AutoConfigureCache` to your test class alongside `@JooqTest` should work around the problem.

it works fine, thanks for help.
