### ISSUE TITLE
feign dependency breaks spring boot 1.4.0.M2 

### ISSUE THREAD

**Issue by runningonfumes** [spring-projects/spring-boot#5772]
Adding the dependency 

    compile('org.springframework.cloud:spring-cloud-starter-feign') 

to my gradle file results in a crash when starting the spring boot app. Without this dependency everything works just fine.

    Starting a new Gradle Daemon for this build (subsequent builds will be faster).
    :clean
    :compileJava
    :processResources
    :classes
    :findMainClass
    :bootRun
    Exception in thread "main" java.lang.NullPointerException
            at org.springframework.boot.devtools.restart.ChangeableUrls.getUrlsFromClassPathAttribute(ChangeableUrls.java:121)
            at org.springframework.boot.devtools.restart.ChangeableUrls.getUrlsFromClassPathOfJarManifestIfPossible(ChangeableUrls.java:99)
            at org.springframework.boot.devtools.restart.ChangeableUrls.fromUrlClassLoader(ChangeableUrls.java:88)
            at org.springframework.boot.devtools.restart.DefaultRestartInitializer.getUrls(DefaultRestartInitializer.java:91)
            at org.springframework.boot.devtools.restart.DefaultRestartInitializer.getInitialUrls(DefaultRestartInitializer.java:54)
            at org.springframework.boot.devtools.restart.Restarter.<init>(Restarter.java:133)
            at org.springframework.boot.devtools.restart.Restarter.initialize(Restarter.java:519)
            at org.springframework.boot.devtools.restart.RestartApplicationListener.onApplicationStartedEvent(RestartApplicationListener.java:68)
            at org.springframework.boot.devtools.restart.RestartApplicationListener.onApplicationEvent(RestartApplicationListener.java:45)
            at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
            at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
            at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:121)
            at org.springframework.boot.context.event.EventPublishingRunListener.publishEvent(EventPublishingRunListener.java:111)
            at org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:60)
            at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:48)
            at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
            at org.springframework.boot.SpringApplication.run(SpringApplication.java:1182)
            at org.springframework.boot.SpringApplication.run(SpringApplication.java:1171)
            at com.thanksys.LoyaltyApplication.main(LoyaltyApplication.java:11)
    :bootRun FAILED

**Comment by wilkinsona** [comment]
Duplicates #5704
