### ISSUE TITLE
Spring session store type should be explicit

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#5838]
@rwinch and I had a chat on what was done in #5158 and he raised a very good point. Unlike caching, the conditions to actually enable Spring Session are less exclusive. 

For instance, the JDBC store kicks in with the mere presence of a `DataSource`. That's like super common. There is a danger that the store type changes for an existing app just  because it go a new requirement. Let's say you use mongo only, the session store will use that. At some point, you need a relational database for some reasons -> all your sessions are wiped out because it's trying to store them on said data source.

To be on the safe side, we should make `spring.session.store-type` explicit and only enable the auto-config if that value is set.

**Comment by philwebb** [comment]
I think this is also causing a test failure at the moment. The exception is:

```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'redisMessageListenerContainer' defined in class path resource [org/springframework/boot/autoconfigure/session/RedisSessionConfiguration$SpringBootRedisHttpSessionConfiguration.class]: Unsatisfied dependency expressed through method 'redisMessageListenerContainer' parameter 1: No qualifying bean of type [org.springframework.session.data.redis.RedisOperationsSessionRepository] found for dependency [org.springframework.session.data.redis.RedisOperationsSessionRepository]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.session.data.redis.RedisOperationsSessionRepository] found for dependency [org.springframework.session.data.redis.RedisOperationsSessionRepository]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:467) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1123) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1018) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:775) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861) ~[spring-context-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541) ~[spring-context-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[classes/:na]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:765) ~[classes/:na]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) ~[classes/:na]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[classes/:na]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134) [classes/:na]
	at sample.session.redis.SampleSessionRedisApplicationTests.sessionExpiry(SampleSessionRedisApplicationTests.java:52) [test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382) [.cp/:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192) [.cp/:na]
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.session.data.redis.RedisOperationsSessionRepository] found for dependency [org.springframework.session.data.redis.RedisOperationsSessionRepository]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:1398) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1051) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1018) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:834) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741) ~[spring-beans-4.3.0.BUILD-SNAPSHOT.jar:4.3.0.BUILD-SNAPSHOT]
	... 41 common frames omitted
```

I think the root cause is that `sessionBean` has been defined in more than one config and the Redis one got clobbered.

**Comment by philwebb** [comment]
I think I've fixed the test failure in 2d243f0668939c401654221ad6392f7f6301272c

**Comment by snicoll** [comment]
They're going to be mutually exclusive soon so that will go away but your change is interesting anyway :)

**Comment by snicoll** [comment]
There's a nasty side effect for people upgrading. `store-type` is mandatory but has no default value so for a user using Spring Session in 1.3, the auto-configuration will not apply anymore with 1.4. I don't know the occurence of users that are using Spring Session and do not inject `SessionRepository` in their own code  but at least our own sample broke without any warning so we need to take that into account.

I've tackled the migration issue with a release notes entry but @rwinch would like us to be more defensive. Things we discussed:

1. Update `store-type` to default to `redis`. While it kind of reflects what we had in 1.3, it is awkward to state that redis is the default now  we have many other options. Conceptually, it does not seem to be valid
2. Throw an exception if `store-type` is not set. This means that any user using spring session upgrading will have an exception message asking them to set the store type. It also means that anybody having spring session on the classpath but not using it would have to set the `store-type` to `none` explicitly`
3. Use redis by default in the auto-configuration and log a warning asking users to set the value explicitly.

I broke the build because I forgot to upgrade the sample so I think we need to do something.We're leaning towards 2. What do you think @philwebb @wilkinsona @dsyer ?

**Comment by vpavic** [comment]
IMO setting a default value for ```store-type``` does not feel right. Option no. 2 sounds the most appropriate.

**Comment by dsyer** [comment]
Can't we retain the current behaviour if spring-data-redis is on the classpath at least? It's not the only situation where we choose a default config based in the classpath content.

**Comment by philwebb** [comment]
I think we should try to retain 1.3 behavior if possible. My feeling is that if Redis is on the classpath and `store-type` is not specified then it's a reasonable default. If `store-type` is not specified and Redis is missing we should default to `none`.
