### ISSUE TITLE
Improve @PropertyMapping annotations can only be used on test classes message

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#5897]
This is a follow-on from #5882.

In trying to produce the idiomatic 1.4 equivalent of @dsyer's slightly unusual test I discovered that `@PropertyMapping` prevents a test class from also being annotation with `@Component`. For example, this will fall in a heap:

```java
@RunWith(SpringRunner.class)
@WebMvcTest
@RestController
public class WebMvcTests {

	private static Log logger = LogFactory.getLog(WebMvcTests.class);

	@Autowired
	private MockMvc mockMvc;

	private static Object span;

	@RequestMapping("/ping")
	public String ping() {
		logger.info("ping");
		WebMvcTests.span = new Object();
		return "ping";
	}

	@RequestMapping("/future")
	public CompletableFuture<String> future() {
		logger.info("future");
		return CompletableFuture.completedFuture("ping");
	}

	@Test
	public void getCallsEndpoint() throws Exception {
		this.mockMvc.perform(get("/ping")).andDo(print());
		assertThat(WebMvcTests.span, is(notNullValue()));
	}

	@Test
	public void futureCreatesAsync() throws Exception {
		this.mockMvc.perform(get("/future")).andExpect(request().asyncStarted());
	}

}
```

The failure is:

```
java.lang.IllegalStateException: @PropertyMapping annotations can only be used on test classes
	at org.springframework.util.Assert.state(Assert.java:392)
	at org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer$PropertyMappingCheckBeanPostProcessor.postProcessBeforeInitialization(PropertyMappingContextCustomizer.java:80)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:399)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:119)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
	at org.springframework.boot.test.autoconfigure.AutoConfigureReportTestExecutionListener.prepareTestInstance(AutoConfigureReportTestExecutionListener.java:46)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:230)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:228)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:287)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:289)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:247)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

The nearest equivalent in 1.4 that works is:

```java
@RunWith(SpringRunner.class)
@WebMvcTest
public class WebMvcTests {

	private static Log logger = LogFactory.getLog(WebMvcTests.class);

	@Autowired
	private MockMvc mockMvc;

	private static Object span;

	@Test
	public void getCallsEndpoint() throws Exception {
		this.mockMvc.perform(get("/ping")).andDo(print());
		assertThat(WebMvcTests.span, is(notNullValue()));
	}

	@Test
	public void futureCreatesAsync() throws Exception {
		this.mockMvc.perform(get("/future")).andExpect(request().asyncStarted());
	}

	@TestConfiguration
	@RestController
	static class Foo {

		@RequestMapping("/ping")
		public String ping() {
			logger.info("ping");
			WebMvcTests.span = new Object();
			return "ping";
		}

		@RequestMapping("/future")
		public CompletableFuture<String> future() {
			logger.info("future");
			return CompletableFuture.completedFuture("ping");
		}

	}

}
```

**Comment by philwebb** [comment]
I think making the test itself a component is probably bad practice but we should certainly enhance the error message.

**Comment by philwebb** [comment]
A bit more digging. With the original test, two instances of `WebMvcTests` are created. The first is by JUnit and the second is by Spring. I think this is quite likely to cause other problems so we are best to still throw some kind of exception.
