### ISSUE TITLE
Autoconfigured Tomcat-DataSource pool not picking up driverClassName when using multiple datasources and JdbcTemplate

### ISSUE THREAD

**Issue by kiview** [spring-projects/spring-boot#5909]
I've experienced the following warning log after configuring my Spring-Boot 1.3.3 application to use multiple datasources as documented here [How to two datasources](https://docs.spring.io/spring-boot/docs/current/reference/html/howto-data-access.html#howto-two-datasources):

`2016-05-04 10:37:53.395  WARN 1 --- [pool-1-thread-1] o.a.tomcat.jdbc.pool.PooledConnection    : Not loading a JDBC driver as driverClassName property is null.`

This warning disappears once I manually specify the `driverClassName` inside my `application.properties`. Please note that this warning does not seem break any JDBC functionalty (maybe pooling is not working correctly. but there are no errors when using the `JdbcTemplate`, only afore mentioned warnings).

I have defined the `spring-boot-start-jdbc` depdency inside of my pom.

Debugging the problem is a bit difficult for me, since breaking inside the `DataSourceBuilder.create().build()` code will provide me with uninitialized properties. However, once the build `DataSource` is used as a depdency somewhere else, it is correctly intialized. I assume this some PostContruct-Hook provided by `@ConfigurationProperties`?

I'll try to provide an example project ASAP.

**Comment by wilkinsona** [comment]
>  I assume this some PostContruct-Hook provided by @ConfigurationProperties?

Correct, the configuration properties are applied via a bean post-processor.

> I'll try to provide an example project ASAP.

Thanks

**Comment by snicoll** [comment]
@kiview before you do, can you please check #5906 isn't helping?

**Comment by kiview** [comment]
Making the bean declaration `static` lead to the following error:

```
2016-05-10 17:35:50.576  WARN 10440 --- [pool-1-thread-1] o.a.tomcat.jdbc.pool.PooledConnection    : Not loading a JDBC driver as driverClassName property is null.
2016-05-10 17:35:50.580 ERROR 10440 --- [pool-1-thread-1] o.a.tomcat.jdbc.pool.ConnectionPool      : Unable to create initial connections of pool.

java.sql.SQLException: The url cannot be null
	at java.sql.DriverManager.getConnection(DriverManager.java:649)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:305)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:200)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:708)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:642)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:464)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:141)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:115)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:102)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:126)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:390)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:470)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:480)
	at org.springframework.jdbc.core.JdbcTemplate.queryForList(JdbcTemplate.java:501)
	at de.gdata.emd.watchdog.risk.fetcher.FetcherSourceSettings.loadSources(FetcherSourceSettings.java:31)
	at de.gdata.emd.watchdog.risk.fetcher.RateFetcher.queryRates(RateFetcher.java:43)
	at de.gdata.emd.watchdog.risk.watcher.RateWatcher.watch(RateWatcher.java:27)
	at de.gdata.emd.watchdog.risk.watcher.RateWatcherShiftPlan.invokeWatcher(RateWatcherShiftPlan.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by snicoll** [comment]
I don't know what bean declaration you are talking about I am afraid. Waiting for the sample then.

**Comment by kiview** [comment]
I've added an example project:
https://github.com/kiview/MultipleDataSourcesBug

**Comment by wilkinsona** [comment]
Thanks for the sample. This is working as expected.

The logic for determining a driver class name from a JDBC URL is in Boot's `DataSourceProperties` class. That class is used by `DataSourceAutoConfiguration` which is switched off due to the presence of your own `DataSource` beans. As `DataSourceProperties` is not involved in the creation of either of your `DataSource` beans they are left without a driver class name. As you have observed, configuring the driver class name in `application.properties` resolves the problem and is what I would recommend that you do. For the record, it's also what @snicoll [has done in his demo application](https://github.com/snicoll-demos/demo-multi-entity-managers/blob/master/src/main/resources/application.properties).

**Comment by kiview** [comment]
Thanks a lot for the answer.

Maybe this behavior could be documented in the [How-to Data Access](https://docs.spring.io/spring-boot/docs/current/reference/html/howto-data-access.html#howto-configure-a-datasource) as well?
