### ISSUE TITLE
Issue when trace logging is enabled

### ISSUE THREAD

**Issue by whgibbo** [spring-projects/spring-boot#5921]
Hi,
Currently using Spring Boot 1.4.0.M1 and noticed the following issue when the logging level is set to **trace**, we had it set at the root level in our case. 

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'infoEndpoint' defined in class path resource [org/springframework/boot/actuate/autoconfigure/EndpointAutoConfiguration.class]: Bean instantiation
 via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.endpoint.InfoEndpoint]: Factory method 'infoEndpoint' threw exception; nested exceptio
n is java.util.MissingFormatArgumentException: Format specifier '%s'
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1123)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1018)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:768)
        at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:362)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1183)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1172)
        at com.intel.cec.keyservice.Application.main(Application.java:37)
        ... 8 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.endpoint.InfoEndpoint]: Factory method 'infoEndpoint' threw exception; nested exception is java.util.MissingFormatArgumentE
xception: Format specifier '%s'
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
        ... 26 more
Caused by: java.util.MissingFormatArgumentException: Format specifier '%s'
        at java.util.Formatter.format(Formatter.java:2519)
        at java.util.Formatter.format(Formatter.java:2455)
        at java.lang.String.format(String.java:2940)
        at org.springframework.boot.bind.PropertiesConfigurationFactory.bindPropertiesToTarget(PropertiesConfigurationFactory.java:234)
        at org.springframework.boot.bind.PropertiesConfigurationFactory.getObject(PropertiesConfigurationFactory.java:223)
        at org.springframework.boot.actuate.autoconfigure.EndpointAutoConfiguration$InfoPropertiesConfiguration.gitInfo(EndpointAutoConfiguration.java:234)
        at org.springframework.boot.actuate.autoconfigure.EndpointAutoConfiguration.infoEndpoint(EndpointAutoConfiguration.java:128)
        at org.springframework.boot.actuate.autoconfigure.EndpointAutoConfiguration$$EnhancerBySpringCGLIB$$46d2c5e1.CGLIB$infoEndpoint$3(<generated>)
        at org.springframework.boot.actuate.autoconfigure.EndpointAutoConfiguration$$EnhancerBySpringCGLIB$$46d2c5e1$$FastClassBySpringCGLIB$$5c1536a0.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:355)
        at org.springframework.boot.actuate.autoconfigure.EndpointAutoConfiguration$$EnhancerBySpringCGLIB$$46d2c5e1.infoEndpoint(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
```

So from the stack trace it is throwing an exception on line **234** of org.springframework.boot.bind.PropertiesConfigurationFactory.java which has the following line:

   **this.logger.trace(String.format("Properties:%n%s" + this.properties));**

So looks like this should be replaced with:
    **this.logger.trace("Properties:" + this.properties);**

**Comment by wilkinsona** [comment]
Problem was introduced in https://github.com/spring-projects/spring-boot/commit/cafe1dc4c6f37e3adaf4d7825181d43a6aa55e53. Only 1.4 is affected.

**Comment by whgibbo** [comment]
Thanks, looks like a search and replace was done..
