### ISSUE TITLE
Avoid creating the `userInfoRestTemplate`

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#5967]
The `userInfoRestTemplate` is used internally by the auto-configuration in several areas and is defined as a `@Bean` to share its state. It can also be overridden by the user. Is that really necessary? Maybe we could share it differently?

**Comment by dsyer** [comment]
I'm seeing test failures related to this as well:

```
...
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.servlet.Filter]: Factory method 'springSecurityFilterChain' threw exception; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [org.springframework.security.oauth2.client.OAuth2RestOperations] is defined: expected single matching bean but found 2: userInfoRestTemplate,loadBalancedOauth2RestTemplate
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.3.0.RC2.jar:4.3.0.RC2]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.3.0.RC2.jar:4.3.0.RC2]
	... 23 common frames omitted
Caused by: org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [org.springframework.security.oauth2.client.OAuth2RestOperations] is defined: expected single matching bean but found 2: userInfoRestTemplate,loadBalancedOauth2RestTemplate
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:367) ~[spring-beans-4.3.0.RC2.jar:4.3.0.RC2]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:333) ~[spring-beans-4.3.0.RC2.jar:4.3.0.RC2]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1088) ~[spring-context-4.3.0.RC2.jar:4.3.0.RC2]
	at org.springframework.boot.autoconfigure.security.oauth2.client.SsoSecurityConfigurer.oauth2SsoFilter(SsoSecurityConfigurer.java:86) ~[spring-boot-autoconfigure-1.4.0.BUILD-SNAPSHOT.jar:1.4.0.BUILD-SNAPSHOT]
	at org.springframework.boot.autoconfigure.security.oauth2.client.SsoSecurityConfigurer.configure(SsoSecurityConfigurer.java:58) ~[spring-boot-autoconfigure-1.4.0.BUILD-SNAPSHOT.jar:1.4.0.BUILD-SNAPSHOT]
...
```

(This is from spring-cloud-security with Boot 1.4.)

**Comment by snicoll** [comment]
Well we removed the `@Primary` one so you were relying on the one created by the auto-config anyway (which isn't what you want I guess).

**Comment by dsyer** [comment]
The failure is in the `SsoSecurityConfigurer` though, so the bug is there really (it does a bean lookup with no qualifier).

**Comment by snicoll** [comment]
@dsyer it looks like 684c8c8 provides a solution for this issue. Any reason why it's still open?

**Comment by dsyer** [comment]
It was marked "For Team Discussion" so I thought someone wanted to discuss it.
