### ISSUE TITLE
Obscure class loader issue with spring-dev-tools

### ISSUE THREAD

**Issue by tkvangorder** [spring-projects/spring-boot#5969]
I ran into a pretty obscure issue that was related to class loading when marshaling a Rabbit message from a queue into a Spring Integration Channel.

The setup: 

We have a single spring boot application that provides a method to flush a cache. There are other instances of the same spring boot application in our cluster that we want to propagate the flush event to. We are using spring integration with a channel that is wired out of the flush method on the first instance to a fan out exchange. We then have a second inbound channel that is wired to a queue that is bound to the exchange. 

I have limited my testing to make sure the application that generates the flush event also receives the event via its inbound rabbit listener. So the source application == the target application. 

This is how I have setup the integration using the DSL : 

```java
		@Autowired
		private AmqpLoggingErrorHandler errorHandler;

		@Autowired
		@Qualifier("jacksonMessageConverter")
		private MessageConverter messageConverter;
		
		// ==============================================================================================================
		// Create fan out exchanges for production cache refreshes. A fan out exchange will send a message to
		// all of its registered bindings.
		// ==============================================================================================================
		@Bean
		public List<Exchange> exchangesCategoryRefresh() {
			return Arrays.asList(
				new FanoutExchange(EXCHANGE_NAME_CATEGORY_REFRESH_PRODUCTION),
			);
		}

		// ==============================================================================================================
		// Setup the out bound cache refresh flow to rabbit.
		// ==============================================================================================================
		@Bean
		public IntegrationFlow flowCacheRefreshProductionOutToRabbit(RabbitTemplate rabbitTemplate) {
	        return IntegrationFlows.from(CHANNEL_NAME_CATEGORY_REFRESH_PRODUCTION_OUT)
	                .handle(
	                		Amqp.outboundAdapter(rabbitTemplate).exchangeName(EXCHANGE_NAME_CATEGORY_REFRESH_PRODUCTION).routingKey(BINDING_KEY_CATEGORY_REFRESH))
	                .get();
	    }

		// ==============================================================================================================
		// Now setup then inbound flow: 
		// An anonymous queue that is a source for the CATEGORY_REFRESH_IN channel.
		// ==============================================================================================================
		@Bean
		public Queue queueCategoryCacheRefresh() {
			return new AnonymousQueue();
		}

		@Bean(name=CHANNEL_NAME_CATEGORY_REFRESH_IN)
		public MessageChannel channelCategoryRefreshIn() {
			return MessageChannels.direct().get();
		}		
		
		@Bean
		public IntegrationFlow flowRabbitToCategoryRefresh(ConnectionFactory factory, CategoryServiceImpl categoryService) {
	        return IntegrationFlows
	        		.from(
        				Amqp.inboundAdapter(factory, queueCategoryCacheRefresh())
        				.errorHandler(errorHandler)
	        			.messageConverter(messageConverter).get()
        			)
	                .channel(channelCategoryRefreshIn())
	                .handle(categoryService, "handleCategoryCacheRefreshRequest")
                .get();
	    }

		// ==============================================================================================================		
		// Finally, based on environment: bind that queue onto the correct exchange.
		// ==============================================================================================================		
		@Bean
		public Binding bindingCacheRefreshProductionIn() {

			return new Binding(queueCategoryCacheRefresh().getName(),
				DestinationType.QUEUE, EXCHANGE_NAME_CATEGORY_REFRESH_PRODUCTION, BINDING_KEY_CATEGORY_REFRESH, null);
		}

```

The infrastructure works great for this example...the message is passed to rabbit and then received by in bound adapter. This is where the wheels come off, the attempt to hand the message to the handler/method results in this error: 

```
Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1004E:(pos 8): Method call: Method handleCategoryCacheRefreshRequest(com.build.domain.category.CategoryCacheRefreshRequest) cannot be found on com.build.service.category.CategoryServiceImpl type
	at org.springframework.expression.spel.ast.MethodReference.findAccessorForMethod(MethodReference.java:211) ~[spring-expression-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:125) ~[spring-expression-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.expression.spel.ast.MethodReference.access$000(MethodReference.java:49) ~[spring-expression-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.expression.spel.ast.MethodReference$MethodValueRef.getValue(MethodReference.java:347) ~[spring-expression-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:88) ~[spring-expression-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.expression.spel.ast.SpelNodeImpl.getTypedValue(SpelNodeImpl.java:131) ~[spring-expression-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:330) ~[spring-expression-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.integration.util.AbstractExpressionEvaluator.evaluateExpression(AbstractExpressionEvaluator.java:166) ~[spring-integration-core-4.2.5.RELEASE.jar:na]
	at org.springframework.integration.util.MessagingMethodInvokerHelper.processInternal(MessagingMethodInvokerHelper.java:317) ~[spring-integration-core-4.2.5.RELEASE.jar:na]
	at org.springframework.integration.util.MessagingMethodInvokerHelper.process(MessagingMethodInvokerHelper.java:155) ~[spring-integration-core-4.2.5.RELEASE.jar:na]
	at org.springframework.integration.handler.MethodInvokingMessageProcessor.processMessage(MethodInvokingMessageProcessor.java:93) ~[spring-integration-core-4.2.5.RELEASE.jar:na]

```

After, triple, quadruple checking that my method name matched and after a lot of debugging I discovered that the problem was that the arguments did not match because they were different classes of the SAME domain object: 

`ReflectionHelper.comapreArguments()`

I found that the expected argument was a different class then the supplied argument and the only way that could happen is if the classes were coming from different class loaders. 

From the debugger, I was able to find the class loaders for each type: 
```
suppliedArg.getType().getClassLoader() == sun.misc.Launcher$AppClassLoader@14dad5dc
expectedArg.getType().getClassLoader() == org.springframework.boot.devtools.restart.classloader.RestartClassLoader@2c070528
```

After removing the spring-dev-tools dependency from my project, everything worked as expected. 

Please let me know if you need anymore details, as this bug will prevent us from using spring dev tools.

**Comment by wilkinsona** [comment]
Can you try configuring your application so that `com.build.service.category.CategoryServiceImpl` is always loaded by the restart class loader? See http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-devtools-customizing-classload for details.

**Comment by tkvangorder** [comment]
@wilkinsona 

The classes in question are in maven projects that are in the same eclipse workspace, so they end up in the classpath as fully qualified folders. (UGH!) 

This is what my lauch configuration looks like (I have removed the JVM args and a majority of my classpath for brevity):

```
C:\opt\jdk1.8.0\bin\javaw.exe ... -classpath C:\devel_eureka\build-parent\build-web\build-webservices\target\classes;C:\devel_eureka\build-parent\build-services\target\classes;C:\devel_eureka\build-parent\build-core\build-domain\target\classes;...
```

I added the file "META-INF/spring-devtools.properties" and I just brute-forced the expressions : 

```
restart.include.buildservices=C:\\devel_eureka\\build-parent\\build-services\\target\\classes
restart.include.builddomain=C:\\devel_eureka\\build-parent\\build-core\\build-domain\\target\\classes
```

This type of pattern will be problematic for us because it : requires the fully qualified path and we have developers both on Windows and Macs (so the pattern will be different depending on OS)

The class `com.build.service.category.CategoryServiceImpl` is in the `build-service` module and the
message being marshalled from Rabbit into my handler is in the `build-domain`.

I am still running into the same issue and I am wondering if its because the message object is being marshalled from a string into a Java object via a Jackson message converter?

**Comment by wilkinsona** [comment]
> This type of pattern will be problematic for us because it : requires the fully qualified path and we have developers both on Windows and Macs (so the pattern will be different depending on OS)

It's a regex so it should be possible to devise a pattern that works on both platforms. Something like `.*(/|\\)build-services(/|\\)target(/|\\)classes`, for example.

> I am still running into the same issue and I am wondering if its because the message object is being marshalled from a string into a Java object via a Jackson message converter?

It sounds like something is using the wrong class loader, but I can't tell what that something is. Can you provide a sample project that reproduces the problem?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
