### ISSUE TITLE
IllegalArgumentException from AnnotationsPropertySource if property mapped annotation is on a super class

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#6006]
The failure is:

```
java.lang.IllegalArgumentException: Annotation must not be null
	at org.springframework.util.Assert.notNull(Assert.java:115)
	at org.springframework.core.annotation.AnnotationUtils.isInJavaLangAnnotationPackage(AnnotationUtils.java:908)
	at org.springframework.boot.test.autoconfigure.properties.AnnotationsPropertySource.collectProperties(AnnotationsPropertySource.java:71)
	at org.springframework.boot.test.autoconfigure.properties.AnnotationsPropertySource.collectProperties(AnnotationsPropertySource.java:82)
	at org.springframework.boot.test.autoconfigure.properties.AnnotationsPropertySource.getProperties(AnnotationsPropertySource.java:63)
	at org.springframework.boot.test.autoconfigure.properties.AnnotationsPropertySource.<init>(AnnotationsPropertySource.java:58)
	at org.springframework.boot.test.autoconfigure.properties.AnnotationsPropertySource.<init>(AnnotationsPropertySource.java:53)
	at org.springframework.boot.test.autoconfigure.properties.AnnotationsPropertySourceTests.foo(AnnotationsPropertySourceTests.java:174)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

Reported by @marceloverdijk on Gitter

**Comment by wilkinsona** [comment]
Problem was introduced in https://github.com/spring-projects/spring-boot/commit/41ddda4a15da42b08883949d9767cb6cc6a8c743#diff-d56d64bb21f2275a31853a2f0d011006

**Comment by marceloverdijk** [comment]
Thx! This worked for me!
