### ISSUE TITLE
Logback fails loadConfiguration when setting springProperty in logback-spring.xml

### ISSUE THREAD

**Issue by dharrigan** [spring-projects/spring-boot#6011]
Hi,

Java 1.8u91
Running Spring Boot 1.4M3.

According to the latest [documentation](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#_profile_specific_configuration), this is permitted:

```
<springProfile name="staging">
    <!-- configuration to be enabled when the "staging" profile is active -->
</springProfile>
```

However, if inserted into the logback-spring.xml file, the bootup fails with this message:

```
ERROR in org.springframework.boot.logging.logback.SpringPropertyAction - The "name" and "source" attributes of <springProperty> must be set
ERROR in ch.qos.logback.core.joran.spi.Interpreter@37:46 - RuntimeException in Action for tag [springProperty] java.lang.NullPointerException
ERROR in org.springframework.boot.logging.logback.SpringPropertyAction - The "name" and "source" attributes of <springProperty> must be set
ERROR in ch.qos.logback.core.joran.spi.Interpreter@55:48 - RuntimeException in Action for tag [springProperty] java.lang.NullPointerException
```

```
java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in org.springframework.boot.logging.logback.SpringPropertyAction - The "name" and "source" attributes of <springProperty> must be set
ERROR in ch.qos.logback.core.joran.spi.Interpreter@37:46 - RuntimeException in Action for tag [springProperty] java.lang.NullPointerException
ERROR in org.springframework.boot.logging.logback.SpringPropertyAction - The "name" and "source" attributes of <springProperty> must be set
ERROR in ch.qos.logback.core.joran.spi.Interpreter@55:48 - RuntimeException in Action for tag [springProperty] java.lang.NullPointerException
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:152)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:72)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:50)
```

In the `begin` method in `SpringPropertyAction`, the source is being set to null.

-=david=-

**Comment by dharrigan** [comment]
My mistake, had wrong property referenced!
