### ISSUE TITLE
FileSystemWatcherTests.waitsForPollingInterval fails intermittently

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#6038]
```
java.lang.AssertionError: 
Expected: <2>
     but: was <1>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.springframework.boot.devtools.filewatch.FileSystemWatcherTests.waitsForPollingInterval(FileSystemWatcherTests.java:168)
```

**Comment by wilkinsona** [comment]
It looks like the changes made in 9f42534 has fixed this
