### ISSUE TITLE
Can't autowire groovy inner interface bean(used spring cloud)

### ISSUE THREAD

**Issue by yyq2013** [spring-projects/spring-boot#6042]
Libraries: Spring boot 1.3.5.RELEASE and 1.4.0.M3 with groovy 2.4.6 and spring cloud 1.1.0.RELESE all have this issue.

Issue:  following code not work
`@Autowired
  private AppClient appClient;`
`@FeignClient("service-discovery")
    interface AppClient {
        @RequestMapping(path = "/hi", method = RequestMethod.GET)
        String hi();
    }`

When startup the project, the debug log "2016-05-26 11:47:40.397 DEBUG 233424 --- [           main] o.s.c.n.feign.FeignClientsRegistrar$2    : Ignored because not a concrete top-level class: file [D:\workspace\ServiceDiscovery\build\classes\main\com\example\ServiceDiscoveryApplication$AppClient.class]"

Error stack:
`Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.example.ServiceDiscoveryApplication$AppClient] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:1373) ~[spring-beans-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1119) ~[spring-beans-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014) ~[spring-beans-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:545) ~[spring-beans-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	... 23 common frames omitted`

Test project:
[ServiceDiscovery.zip](https://github.com/spring-projects/spring-boot/files/283434/ServiceDiscovery.zip)

**Comment by snicoll** [comment]
Feign is not part of Spring Boot, so please raise that against [the proper issue tracker](https://github.com/spring-cloud/spring-cloud-netflix/issues)
