### ISSUE TITLE
Wildfly 10.0 deploy war 'cannot be cast to WsServerContainer' exception

### ISSUE THREAD

**Issue by mrkeuz** [spring-projects/spring-boot#6166]
### Problem

I took application from blog post: 
https://spring.io/blog/2014/11/23/bootiful-java-ee-support-in-spring-boot-1-2
and just up spring-boot version to 1.3.5.RELEASE  (1.2.0.BUILD-SNAPSHOT don't work too)

I tried deploy spring-boot app to WildFly server and got error.

I found that it's don't work. 

Workaround is globally ignore `tomcat-embed-websocket` via "provide" maven trick like this:

```
<dependency>
       <artifactId>tomcat-embed-websocket</artifactId>
       <groupId>org.apache.tomcat.embed</groupId>
      <scope>provided</scope>
</dependency>
```

### Environment:

Wildfly-10.0.0.Final
Spring Boot 1.3.5.RELEASE 
Jdk1.8.0_31

### Bug report
```
16:38:27,649 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 111) MSC000001: Failed to start service jboss.undertow.deployment.default-server.default-host./ee-test: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./ee-test: java.lang.RuntimeException: java.lang.ClassCastException: org.apache.tomcat.websocket.server.WsServerContainer cannot be cast to io.undertow.websockets.jsr.ServerWebSocketContainer
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:85)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: java.lang.RuntimeException: java.lang.ClassCastException: org.apache.tomcat.websocket.server.WsServerContainer cannot be cast to io.undertow.websockets.jsr.ServerWebSocketContainer
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:231)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:100)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:82)
	... 6 more
Caused by: java.lang.ClassCastException: org.apache.tomcat.websocket.server.WsServerContainer cannot be cast to io.undertow.websockets.jsr.ServerWebSocketContainer
	at io.undertow.websockets.jsr.Bootstrap$WebSocketListener.contextInitialized(Bootstrap.java:104)
	at io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:187)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:198)
	... 8 more

16:38:27,651 ERROR [org.jboss.as.controller.management-operation] (management-handler-thread - 4) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "ee-test.war")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.undertow.deployment.default-server.default-host./ee-test" => "org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./ee-test: java.lang.RuntimeException: java.lang.ClassCastException: org.apache.tomcat.websocket.server.WsServerContainer cannot be cast to io.undertow.websockets.jsr.ServerWebSocketContainer
    Caused by: java.lang.RuntimeException: java.lang.ClassCastException: org.apache.tomcat.websocket.server.WsServerContainer cannot be cast to io.undertow.websockets.jsr.ServerWebSocketContainer
    Caused by: java.lang.ClassCastException: org.apache.tomcat.websocket.server.WsServerContainer cannot be cast to io.undertow.websockets.jsr.ServerWebSocketContainer"}}
16:38:27,653 ERROR [org.jboss.as.server] (management-handler-thread - 4) WFLYSRV0021: Deploy of deployment "ee-test.war" was rolled back with the following failure message: 
{"WFLYCTL0080: Failed services" => {"jboss.undertow.deployment.default-server.default-host./ee-test" => "org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./ee-test: java.lang.RuntimeException: java.lang.ClassCastException: org.apache.tomcat.websocket.server.WsServerContainer cannot be cast to io.undertow.websockets.jsr.ServerWebSocketContainer
    Caused by: java.lang.RuntimeException: java.lang.ClassCastException: org.apache.tomcat.websocket.server.WsServerContainer cannot be cast to io.undertow.websockets.jsr.ServerWebSocketContainer
    Caused by: java.lang.ClassCastException: org.apache.tomcat.websocket.server.WsServerContainer cannot be cast to io.undertow.websockets.jsr.ServerWebSocketContainer"}}
```

**Comment by wilkinsona** [comment]
If you are deploying to an external servlet container or application server, then you should either exclude the embedded container (if you'll only deploy as a war) or mark it as provided (if you want the war to also be executable). This is [described in the documentation](http://docs.spring.io/spring-boot/docs/1.3.5.RELEASE/reference/htmlsingle/#howto-create-a-deployable-war-file).

The sample project you linked to has a bug in it. It's trying to use Undertow, but hasn't excluded Tomcat from `spring-boot-starter-jersey`. If you're deploying to Wildfly, you should also mark the `spring-boot-starter-undertow` dependency as `provided` or exclude it too.

**Comment by mrkeuz** [comment]
Thanks for explanation!

**Comment by zaenk** [comment]
Some Spring Boot Starters also includes `spring-boot-starter-tomcat` by default (e.g.: `spring-boot-starter-thymeleaf` or some cloud starters)

You can find which dependencies includes Tomcat with:

```bash
./mvnw dependency:tree -Dincludes=org.springframework.boot:spring-boot-starter-tomcat
# or:
./gradlew dependencyInsight --dependency spring-boot-starter-tomcat --configuration compile
```

After excluding Tomcat from all of them, you might need to add `javax.servlet-api` as provided:

```xml
<dependency>
    <artifactId>javax.servlet</artifactId>
    <groupId>javax.servlet-api</groupId>
    <scope>provided</scope>
</dependency>
```

or:

```groovy
providedCompile('javax.servlet:javax.servlet-api')
```

**Comment by snicoll** [comment]
> After excluding Tomcat from all of them

Excluding the tomcat starter from `spring-boot-starter-web` (as explained in the documentation) should be enough.

**Comment by zaenk** [comment]
> Excluding the tomcat starter from spring-boot-starter-web (as explained in the documentation) should be enough.

@snicoll: That was not enough for me. This is the configuration what finally started working on WildFly 10 for me:

```groovy
/*...*/
dependencies {
	compile('org.springframework.boot:spring-boot-starter-web') {
		exclude group: 'org.springframework.boot', module: 'spring-boot-starter-tomcat'
	}
	compile('org.springframework.boot:spring-boot-starter-thymeleaf') {
		exclude group: 'org.springframework.boot', module: 'spring-boot-starter-tomcat'
	}
	compile('org.springframework.cloud:spring-cloud-starter-oauth2') {
		exclude group: 'org.springframework.boot', module: 'spring-boot-starter-tomcat'
	}
	providedRuntime('org.springframework.boot:spring-boot-starter-undertow')
	providedCompile('javax.servlet:javax.servlet-api')
	/*...*/
}
```

**Comment by wilkinsona** [comment]
@zaenk That's Gradle and you were posting Maven snippets earlier. As you've shown, Gradle handles exclusions differently to Maven.

**Comment by pavelety** [comment]
To resolve this in Wildfly 11 I edited pom.xml like this
```xml
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-web</artifactId>
	<exclusions>
		<exclusion>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
		</exclusion>
		<exclusion>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-logging</artifactId>
		</exclusion>
	</exclusions>
</dependency>
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-log4j2</artifactId>
	<scope>provided</scope>
</dependency>
<dependency>
	<groupId>javax</groupId>
	<artifactId>javaee-web-api</artifactId>
	<version>7.0</version>
	<scope>provided</scope>
</dependency>
```
Also I resolved here problems with log4j2
