### ISSUE TITLE
@ConfigurationProperties to inject environment properties into a structure of nested objects

### ISSUE THREAD

**Issue by s-bortolussi** [spring-projects/spring-boot#6204]
I use `@ConfigurationProperties `to inject environment properties into a structure of nested objects.

```java
@Component
@ConfigurationProperties
public class ServiceProperties {

    private Map<String,Service> services;

    public Map<String, Service> getServices() {
        return services;
    }

    public void setServices(Map<String, Service> services) {
        this.services = services;
    }

}

public class Service {

    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
```

Setting env property as follows fails
```
SERVICES_DEV_NAME=a name
```

with following stacktrace
```java
Caused by: org.springframework.validation.BindException: org.springframework.boot.bind.RelaxedDataBinder$RelaxedBeanPropertyBindingResult: 1 errors
Field error in object 'target' on field 'services[DEV_NAME]': rejected value [a name]; codes [typeMismatch.target.services[DEV_NAME],typeMismatch.target.services,typeMismatch.services[DEV_NAME],typeMismatch.services,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [target.services[DEV_NAME],services[DEV_NAME]]; arguments []; default message [services[DEV_NAME]]]; default message [Failed to convert property value of type [java.lang.String] to required type [com.example.Service] for property 'services[DEV_NAME]'; nested exception is java.lang.IllegalStateException: Cannot convert value of type [java.lang.String] to required type [com.example.Service] for property 'services[DEV_NAME]': no matching editors or conversion strategy found]
	at org.springframework.boot.bind.PropertiesConfigurationFactory.validate(PropertiesConfigurationFactory.java:362)
	at org.springframework.boot.bind.PropertiesConfigurationFactory.doBindPropertiesToTarget(PropertiesConfigurationFactory.java:271)
	at org.springframework.boot.bind.PropertiesConfigurationFactory.bindPropertiesToTarget(PropertiesConfigurationFactory.java:241)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:334)
	... 48 more
```
Can be reproduce using [following code](https://github.com/s-bortolussi/env-properties-demo).

Notice that, setting env property as follows succeed, but raises [compatiblity issues across shells](stackoverflow.com/questions/2821043/allowed-characters-in-linux-environment-variable-names)
```
SERVICES[DEV]_NAME=a name
```

What should be the format of env variable when dealing with Spring Boot Configuration Binding of Map/nested properties ?

Thanks

**Comment by philwebb** [comment]
Unfortunately the square brackets are a requirement for map based binding (see #5315). The best work-around we can suggest so far is to use `SPRING_APPLICATION_JSON="..."` as an environment variable, with the value being a json structure to process. See `org.springframework.boot.env.SpringApplicationJsonEnvironmentPostProcessor` for details of how it works.

**Comment by s-bortolussi** [comment]
@philwebb thanks for the quick reply.
