### ISSUE TITLE
Defining custom converter in spring boot

### ISSUE THREAD

**Issue by navgrover** [spring-projects/spring-boot#6213]
**I have defined a custom converter in spring boot v1.3.5.RELEASE. When I execute the convert, following error happens:**

```
org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [com.slalom.anytrack.repository.resource.Resource] to type [com.slalom.anytrack.services.resource.ResourceEngagement]
	at org.springframework.core.convert.support.GenericConversionService.handleConverterNotFound(GenericConversionService.java:313) ~[spring-core-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:195) ~[spring-core-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:176) ~[spring-core-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
	at com.slalom.anytrack.services.resource.ResourceServiceImpl.formulateResources(ResourceServiceImpl.java:57) ~[anytrack-service-1.0.0-SNAPSHOT.jar!/:1.0.0-SNAPSHOT]
	at com.slalom.anytrack.services.resource.ResourceServiceImpl.getResources(ResourceServiceImpl.java:40) ~[anytrack-service-1.0.0-SNAPSHOT.jar!/:1.0.0-SNAPSHOT]
	at com.slalom.anytrack.api.v1.controller.ResourceController.getResources(ResourceController.java:39) ~[anytrack-api.jar!/:1.0.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) ~[spring-web-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[spring-web-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110) ~[spring-webmvc-4.2.6.RELEASE.jar
```

**Here is the code:**

```java
@Configuration
public class ConversionServiceConfig {

    @Autowired
    private Set<Converter> converters;

    @Bean
    public ConversionService conversionService() {
        ConversionServiceFactoryBean factory = new ConversionServiceFactoryBean();
        factory.setConverters(converters);
        factory.afterPropertiesSet();
        return factory.getObject();
    }
}
```

**Here is how i am calling the convert:**
```java       
@Autowired
ConversionService conversionService;

ResourceEngagement resourceEngagement = conversionService.convert(resource, ResourceEngagement.class);
```

**Here is the converter defined**

```java
@Component
public class ResourceToResourceEngagementConverter implements Converter<Resource, ResourceEngagement>{

    @Override
    public ResourceEngagement convert(Resource resource) {
        ResourceEngagement resourceEngagement = new ResourceEngagement();
        
        resourceEngagement.setName(resource.getName());
        resourceEngagement.setEmail(resource.getEmail());
        resourceEngagement.setId(resource.getId());
        resourceEngagement.setTitle(resource.getTitle());

        return resourceEngagement;
    }
}
```

**Comment by philwebb** [comment]
You have to be a bit careful using `conversionService` as a bean name. My best guess is that your `@Autowired` converters in `ConversionServiceConfig` are `null` (try adding a breakpoint to see). If it is `null` it's probably because `ConfigurationPropertiesBindingPostProcessor` is kicking in before `AutowiredAnnotationBeanPostProcessor`.

Try renaming your `conversionService()` `@Bean` method.

**Comment by navgrover** [comment]
Renaming the `conversionService()` `@Bean` method did the trick. 
Appreciate your help.

**Comment by spencergibb** [comment]
@philwebb yeah we had someone complain similarly. They seemed upset that they couldn't name a bean `resourceRepository`. 

https://github.com/spring-cloud/spring-cloud-config/issues/417#issuecomment-226289321

**Comment by spencergibb** [comment]
I wonder if some kind of bean name conflict actuator report could be made.

**Comment by philwebb** [comment]
Interesting idea, but It probably wouldn't help in this case because the app wouldn't start. Perhaps we should have chosen more obscure bean names.
