### ISSUE TITLE
Can't load log4j2 config file

### ISSUE THREAD

**Issue by damaru-inc** [spring-projects/spring-boot#6246]
Spring boot 1.3.5:

I have a web app based on Spring Boot. It worked fine using log4j (version 1) When I try to use log4j2 (version 2) and deploy it on a local jboss, I get the error when the app starts.

The file log4j2.xml is at the top of the classpath.

The Log4J2LoggingSystem.getConfigurationSource class identifies the url to the file as vfs:/C/devtools....

The ResourceUtils.getFile function throws an exception because it only allows urs starting with the "file:" scheme and rejects this one because the scheme is "vfs:".

```
Caused by: java.io.FileNotFoundException: URL cannot be resolved to absolute file path because it does not reside in the file system: vfs:/C:/devtools/jboss/jboss-as-7.1.3.Final/bin/content/template.ear/sis-app-template-war.war/WEB-INF/classes/log4j2.xml
at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:218) [spring-core-4.2.6.RELEASE.jar:4.2.6.RELEASE]
at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:202) [spring-core-4.2.6.RELEASE.jar:4.2.6.RELEASE]
at org.springframework.boot.logging.log4j2.Log4J2LoggingSystem.getConfigurationSource(Log4J2LoggingSystem.java:176) [spring-boot-1.3.5.RELEASE.jar:1.3.5.RELEASE]
at org.springframework.boot.logging.log4j2.Log4J2LoggingSystem.loadConfiguration(Log4J2LoggingSystem.java:164) [spring-boot-1.3.5.RELEASE.jar:1.3.5.RELEASE]
```

**Comment by wilkinsona** [comment]
It's rather misleading that `ResourceUtils.isFileURL` returns `true` and then `ResourceUtils.getFile()` fails because it's not actually a `File`. Looks like we'll need to do our own check for the `URL` having a `file` protocol.
