### ISSUE TITLE
Maven build failed when using spring-boot-starter-web version 1.4.0.BUILD-SNAPSHOT

### ISSUE THREAD

**Issue by debabratp** [spring-projects/spring-boot#6247]
I am using spring-boot-starter-web version 1.4.0.BUILD-SNAPSHOT.  During build I am getting the below error

> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'restTemplateBuilder' defined in class path resource [org/springframework/boot/autoconfigure/web/WebClientAutoConfiguration$RestTemplateConfiguration.class]: Post-processing failed of bean type [class org.springframework.boot.web.client.RestTemplateBuilder] failed; nested exception is java.lang.IllegalStateException: Failed to introspect bean class [org.springframework.boot.web.client.RestTemplateBuilder] for resource metadata: could not find class that it depends on
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyMergedBeanDefinitionPostProcessors(AbstractAutowireCapableBeanFactory.java:940) ~[spring-beans-4.3.1.BUILD-SNAPSHOT.jar:4.3.1.BUILD-SNAPSHOT]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:518) ~[spring-beans-4.3.1.BUILD-SNAPSHOT.jar:4.3.1.BUILD-SNAPSHOT]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.3.1.BUILD-SNAPSHOT.jar:4.3.1.BUILD-SNAPSHOT]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.1.BUILD-SNAPSHOT.jar:4.3.1.BUILD-SNAPSHOT]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.1.BUILD-SNAPSHOT.jar:4.3.1.BUILD-SNAPSHOT]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.1.BUILD-SNAPSHOT.jar:4.3.1.BUILD-SNAPSHOT]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.1.BUILD-SNAPSHOT.jar:4.3.1.BUILD-SNAPSHOT]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:775) ~[spring-beans-4.3.1.BUILD-SNAPSHOT.jar:4.3.1.BUILD-SNAPSHOT]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861) ~[spring-context-4.3.1.BUILD-SNAPSHOT.jar:4.3.1.BUILD-SNAPSHOT]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541) ~[spring-context-4.3.1.BUILD-SNAPSHOT.jar:4.3.1.BUILD-SNAPSHOT]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.4.0.BUILD-SNAPSHOT.jar:1.4.0.BUILD-SNAPSHOT]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) [spring-boot-1.4.0.BUILD-SNAPSHOT.jar:1.4.0.BUILD-SNAPSHOT]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:369) [spring-boot-1.4.0.BUILD-SNAPSHOT.jar:1.4.0.BUILD-SNAPSHOT]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:313) [spring-boot-1.4.0.BUILD-SNAPSHOT.jar:1.4.0.BUILD-SNAPSHOT]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1176) [spring-boot-1.4.0.BUILD-SNAPSHOT.jar:1.4.0.BUILD-SNAPSHOT]
        at com.springboot.tutorial.App.main(App.java:23) [classes/:na]
Caused by: java.lang.IllegalStateException: Failed to introspect bean class [org.springframework.boot.web.client.RestTemplateBuilder] for resource metadata: could not find class that it depends on
        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.findResourceMetadata(CommonAnnotationBeanPostProcessor.java:344) ~[spring-context-4.3.1.BUILD-SNAPSHOT.jar:4.3.1.BUILD-SNAPSHOT]
        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessMergedBeanDefinition(CommonAnnotationBeanPostProcessor.java:297) ~[spring-context-4.3.1.BUILD-SNAPSHOT.jar:4.3.1.BUILD-SNAPSHOT]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyMergedBeanDefinitionPostProcessors(AbstractAutowireCapableBeanFactory.java:935) ~[spring-beans-4.3.1.BUILD-SNAPSHOT.jar:4.3.1.BUILD-SNAPSHOT]
        ... 15 common frames omitted
Caused by: java.lang.NoClassDefFoundError: Lorg/springframework/http/client/BasicAuthorizationInterceptor;
        at java.lang.Class.getDeclaredFields0(Native Method) ~[na:1.8.0_73]
        at java.lang.Class.privateGetDeclaredFields(Class.java:2583) ~[na:1.8.0_73]
        at java.lang.Class.getDeclaredFields(Class.java:1916) ~[na:1.8.0_73]
        at org.springframework.util.ReflectionUtils.getDeclaredFields(ReflectionUtils.java:713) ~[spring-core-4.3.1.BUILD-SNAPSHOT.jar:4.3.1.BUILD-SNAPSHOT]
        at org.springframework.util.ReflectionUtils.doWithLocalFields(ReflectionUtils.java:655) ~[spring-core-4.3.1.BUILD-SNAPSHOT.jar:4.3.1.BUILD-SNAPSHOT]
        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.buildResourceMetadata(CommonAnnotationBeanPostProcessor.java:361) ~[spring-context-4.3.1.BUILD-SNAPSHOT.jar:4.3.1.BUILD-SNAPSHOT]
        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.findResourceMetadata(CommonAnnotationBeanPostProcessor.java:340) ~[spring-context-4.3.1.BUILD-SNAPSHOT.jar:4.3.1.BUILD-SNAPSHOT]
        ... 17 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.http.client.BasicAuthorizationInterceptor
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_73]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_73]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_73]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_73]
        ... 24 common frames omitted

From the error it look like there is a issue in spring-context-4.3.1.BUILD-SNAPSHOT.jar:4.3.1.BUILD-SNAPSHOT.

**Comment by snicoll** [comment]
There isn't. It's outdated and we're working on that feature so that particular build may be inconsistent. Thanks for letting us know but once [this build](https://build.spring.io/browse/BOOT-PUB-4343) completes we should be fine.

**Comment by igor-dmitriev** [comment]
I got the same issue with Spring Boot 1.4.0.RELEASE, any updates?

**Comment by snicoll** [comment]
@igor-dmitriev I replied last year (?!) that it wasn't. This issue is closed so if you think you've found an issue, please create a separate issue with a sample that reproduces the problem

**Comment by igor-dmitriev** [comment]
Hm. I'll try to reproduce, but I think it won't be easy to reflect my production env.
Btw, I've fixed it temporary adding dependency to my pom:
        ```
  <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-beans</artifactId>
                <version>4.3.2.RELEASE</version> <!-- 4.3.2.RELEASE in Spring Boot 1.4.0 -->
            </dependency>

            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-web</artifactId>
                <version>4.3.2.RELEASE</version> <!-- 4.3.2.RELEASE in Spring Boot 1.4.0 -->
            </dependency>
```
it works, but obviously it's not a perfect solution.

**Comment by snicoll** [comment]
@igor-dmitriev you shouldn't be doing that. Maybe your maven cache is corrupted or something. Either way, join us on Gitter if you want to chat or create a separate issue with a sample.
