### ISSUE TITLE
java.lang.NoSuchMethodError: org.springframework.test.context.MergedContextConfiguration.getContextCustomizers

### ISSUE THREAD

**Issue by jasoncarreira** [spring-projects/spring-boot#6307]
Trying out spring-boot-starter-test and I get this error

    java.lang.NoSuchMethodError: org.springframework.test.context.MergedContextConfiguration.getContextCustomizers()Ljava/util/Set;

	at org.springframework.boot.test.context.SpringBootTestContextBootstrapper.createModifiedConfig(SpringBootTestContextBootstrapper.java:270)
	at org.springframework.boot.test.context.SpringBootTestContextBootstrapper.processMergedContextConfiguration(SpringBootTestContextBootstrapper.java:118)
	at org.springframework.test.context.support.AbstractTestContextBootstrapper.buildMergedContextConfiguration(AbstractTestContextBootstrapper.java:376)
	at org.springframework.test.context.support.AbstractTestContextBootstrapper.buildMergedContextConfiguration(AbstractTestContextBootstrapper.java:307)
	at org.springframework.test.context.support.AbstractTestContextBootstrapper.buildTestContext(AbstractTestContextBootstrapper.java:110)
	at org.springframework.boot.test.context.SpringBootTestContextBootstrapper.buildTestContext(SpringBootTestContextBootstrapper.java:73)
	at org.springframework.test.context.TestContextManager.<init>(TestContextManager.java:120)
	at org.springframework.test.context.TestContextManager.<init>(TestContextManager.java:105)

This is my test:

    @RunWith(SpringJUnit4ClassRunner.class)
    @SpringBootTest
    //@JsonTest
    @SpringApplicationConfiguration(ServiceTestApplication.class)
    public class JsonSerializationTest {

        private JacksonTester<NestupUser> json;

        @Before
        public void setup() {
            ObjectMapper objectMappper = new ObjectMapper();
            // Possibly configure the mapper
            JacksonTester.initFields(this, objectMappper);
        }

        @Test
        public void serializeJson() throws IOException {
            Role[] roles = {Role.COMPANY_ADMIN, Role.AUTHENTICATED_USER};
            User details = new User("John","ManyJohns","manyjohns@yoyodyne.com","bigboote",61,68,45000,"YoyoDyne", new HashSet<>(Arrays.asList(roles)));

            assertThat(this.json.write(details))
                .extractingJsonPathStringValue("@.email")
                .isEqualTo("manyjohns@yoyodyne.com");

            assertThat(this.json.write(details))
                .extractingJsonPathStringValue("@.roles")
                .isEqualTo(roles);
        }

    }

**Comment by wilkinsona** [comment]
That method is new in Spring Framework 4.3, which Boot 1.4 requires. You must have an old version of `spring-test` on the classpath. You can avoid this sort of problem by letting Boot's dependency management control your dependencies' versions.

**Comment by jasoncarreira** [comment]
The problem was not updating the spring boot pom parent to 1.4 so it was still bringing in some 1.3.5 dependencies
