### ISSUE TITLE
Broken compatibility with Mockito 2.0.47-beta+ in Spring Boot 1.4.0.M3

### ISSUE THREAD

**Issue by szpak** [spring-projects/spring-boot#6320]
Built-in support for Mockito beans inside a Spring context is nice, but the current snapshot (2016-07-05) fails with the following error when used with Mockito 2.0.47-beta+:

```
Caused by: java.lang.NoSuchMethodError: org.mockito.Answers.get()Lorg/mockito/stubbing/Answer;
	at org.springframework.boot.test.mock.mockito.MockDefinition.createMock(MockDefinition.java:154)
	at org.springframework.boot.test.mock.mockito.MockitoPostProcessor.createMock(MockitoPostProcessor.java:206)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 46 more
```

There reason is [removing](https://github.com/mockito/mockito/commit/da5e750957b494e7fa0548bf1286d67b8b0386d5) (in 2.0.47-beta) a deprecated `get()` method which were stopped to be needed when `Answers` [started](https://github.com/mockito/mockito/commit/34f4436d988f04eaf7635b0497067ee8df7971a6) to implement `Answer` interface directly (in 2.0.2-beta).

Mockito 2.x is still a moving target, but it would be bad to force people to hack `MockDefinition` locally due to one method. I will prepare a PR to handle both Mockito versions.

**Comment by snicoll** [comment]
Closing in favour of the PR #6323
