### ISSUE TITLE
configprops endpoint fails with NoSuchMethodError on Java 7

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#6325]
The failure is:
```
java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.JavaType.getTypeName()Ljava/lang/String;
	at org.springframework.boot.actuate.endpoint.ConfigurationPropertiesReportEndpoint$GenericSerializerModifier.isReadable(ConfigurationPropertiesReportEndpoint.java:312) ~[spring-boot-actuator-1.4.0.RC1.jar:1.4.0.RC1]
	at org.springframework.boot.actuate.endpoint.ConfigurationPropertiesReportEndpoint$GenericSerializerModifier.changeProperties(ConfigurationPropertiesReportEndpoint.java:302) ~[spring-boot-actuator-1.4.0.RC1.jar:1.4.0.RC1]
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.constructBeanSerializer(BeanSerializerFactory.java:401) ~[jackson-databind-2.7.5.jar:2.7.5]
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanSerializer(BeanSerializerFactory.java:271) ~[jackson-databind-2.7.5.jar:2.7.5]
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:223) ~[jackson-databind-2.7.5.jar:2.7.5]
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:157) ~[jackson-databind-2.7.5.jar:2.7.5]
	at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1215) ~[jackson-databind-2.7.5.jar:2.7.5]
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1167) ~[jackson-databind-2.7.5.jar:2.7.5]
	at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:490) ~[jackson-databind-2.7.5.jar:2.7.5]
	at com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:688) ~[jackson-databind-2.7.5.jar:2.7.5]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:107) ~[jackson-databind-2.7.5.jar:2.7.5]
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3508) ~[jackson-databind-2.7.5.jar:2.7.5]
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3449) ~[jackson-databind-2.7.5.jar:2.7.5]
	at org.springframework.boot.actuate.endpoint.ConfigurationPropertiesReportEndpoint.safeSerialize(ConfigurationPropertiesReportEndpoint.java:158) ~[spring-boot-actuator-1.4.0.RC1.jar:1.4.0.RC1]
	at org.springframework.boot.actuate.endpoint.ConfigurationPropertiesReportEndpoint.extract(ConfigurationPropertiesReportEndpoint.java:114) ~[spring-boot-actuator-1.4.0.RC1.jar:1.4.0.RC1]
	at org.springframework.boot.actuate.endpoint.ConfigurationPropertiesReportEndpoint.extract(ConfigurationPropertiesReportEndpoint.java:99) ~[spring-boot-actuator-1.4.0.RC1.jar:1.4.0.RC1]
	at org.springframework.boot.actuate.endpoint.ConfigurationPropertiesReportEndpoint.invoke(ConfigurationPropertiesReportEndpoint.java:86) ~[spring-boot-actuator-1.4.0.RC1.jar:1.4.0.RC1]
	at org.springframework.boot.actuate.endpoint.ConfigurationPropertiesReportEndpoint.invoke(ConfigurationPropertiesReportEndpoint.java:61) ~[spring-boot-actuator-1.4.0.RC1.jar:1.4.0.RC1]
	at org.springframework.boot.actuate.endpoint.mvc.AbstractEndpointMvcAdapter.invoke(AbstractEndpointMvcAdapter.java:56) ~[spring-boot-actuator-1.4.0.RC1.jar:1.4.0.RC1]
	at org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke(EndpointMvcAdapter.java:44) ~[spring-boot-actuator-1.4.0.RC1.jar:1.4.0.RC1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_65]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_65]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) ~[spring-web-4.3.1.RELEASE.jar:4.3.1.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[spring-web-4.3.1.RELEASE.jar:4.3.1.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:114) ~[spring-webmvc-4.3.1.RELEASE.jar:4.3.1.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) ~[spring-webmvc-4.3.1.RELEASE.jar:4.3.1.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) ~[spring-webmvc-4.3.1.RELEASE.jar:4.3.1.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.3.1.RELEASE.jar:4.3.1.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963) ~[spring-webmvc-4.3.1.RELEASE.jar:4.3.1.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897) ~[spring-webmvc-4.3.1.RELEASE.jar:4.3.1.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.1.RELEASE.jar:4.3.1.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) ~[spring-webmvc-4.3.1.RELEASE.jar:4.3.1.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) ~[tomcat-embed-core-8.5.3.jar:8.5.3]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) ~[spring-webmvc-4.3.1.RELEASE.jar:4.3.1.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) ~[tomcat-embed-core-8.5.3.jar:8.5.3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230) ~[tomcat-embed-core-8.5.3.jar:8.5.3]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.3.jar:8.5.3]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.5.3.jar:8.5.3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.3.jar:8.5.3]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.3.jar:8.5.3]
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55) ~[spring-boot-1.4.0.RC1.jar:1.4.0.RC1]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.1.RELEASE.jar:4.3.1.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.3.jar:8.5.3]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.3.jar:8.5.3]
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:105) ~[spring-boot-actuator-1.4.0.RC1.jar:1.4.0.RC1]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.1.RELEASE.jar:4.3.1.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.3.jar:8.5.3]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.3.jar:8.5.3]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-4.3.1.RELEASE.jar:4.3.1.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.1.RELEASE.jar:4.3.1.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.3.jar:8.5.3]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.3.jar:8.5.3]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:87) ~[spring-web-4.3.1.RELEASE.jar:4.3.1.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.1.RELEASE.jar:4.3.1.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.3.jar:8.5.3]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.3.jar:8.5.3]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77) ~[spring-web-4.3.1.RELEASE.jar:4.3.1.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.1.RELEASE.jar:4.3.1.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.3.jar:8.5.3]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.3.jar:8.5.3]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) ~[spring-web-4.3.1.RELEASE.jar:4.3.1.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.1.RELEASE.jar:4.3.1.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.3.jar:8.5.3]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.3.jar:8.5.3]
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:107) ~[spring-boot-actuator-1.4.0.RC1.jar:1.4.0.RC1]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.1.RELEASE.jar:4.3.1.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.3.jar:8.5.3]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.3.jar:8.5.3]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[tomcat-embed-core-8.5.3.jar:8.5.3]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108) [tomcat-embed-core-8.5.3.jar:8.5.3]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:522) [tomcat-embed-core-8.5.3.jar:8.5.3]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.3.jar:8.5.3]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.5.3.jar:8.5.3]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.3.jar:8.5.3]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349) [tomcat-embed-core-8.5.3.jar:8.5.3]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1110) [tomcat-embed-core-8.5.3.jar:8.5.3]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.3.jar:8.5.3]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:785) [tomcat-embed-core-8.5.3.jar:8.5.3]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1425) [tomcat-embed-core-8.5.3.jar:8.5.3]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) [tomcat-embed-core-8.5.3.jar:8.5.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_65]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.3.jar:8.5.3]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_65]
```

This is caused by the changes made for https://github.com/spring-projects/spring-boot/issues/5081 (https://github.com/spring-projects/spring-boot/commit/ef5087c5ee9f65e44ba800f3e34a05f312b0a3e9). They inadvertently introduced a call to `java.lang.reflect.Type.getTypeName()` which is new in Java 8 and should have been caught by animal sniffer.

**Comment by philwebb** [comment]
I wonder why Animal sniffer didn't pick it up?

**Comment by snicoll** [comment]
We had a few other issues like that in the core framework. It's unknown at this point but we should resume investigation.
