### ISSUE TITLE
Spring Boot Remote Shell with embedded server works only if archive is JAR and not WAR

### ISSUE THREAD

**Issue by anand1st** [spring-projects/spring-boot#6384]
I was running a Spring Boot application (v1.3.6) with embedded undertow in a WAR archive. Recently, I've added remote-shell commands and they worked just fine using `mvn spring-boot:run`. Once packaged into WAR, java -jar {filename}.war and upon ssh into the shell and typing `help`, I get the following exception.
`java.io.IOException: Cannot resolve jar:file:{path-to-WAR-archive}!/WEB-INF/classes`

All my shell commands were not loaded either.

**Comment by anand1st** [comment]
Workaround:

Changing to JAR instead of WAR archive fixed this problem.

**Comment by wilkinsona** [comment]
The exception is:

```
java.io.IOException: Cannot resolve jar:file:/Users/awilkinson/dev/workspaces/spring/spring-boot/1.3.x/gh-6384/target/gh-6384-0.0.1-SNAPSHOT.war!/WEB-INF/classes
	at org.crsh.util.ZipIterator.create(ZipIterator.java:100)
	at org.crsh.vfs.spi.url.Node._mergeEntries(Node.java:165)
	at org.crsh.vfs.spi.url.Node.mergeEntries(Node.java:142)
	at org.crsh.vfs.spi.url.Node.merge(Node.java:75)
	at org.crsh.vfs.spi.url.URLDriver.merge(URLDriver.java:42)
	at org.crsh.lang.impl.java.ClasspathResolver.<init>(ClasspathResolver.java:49)
	at org.crsh.lang.impl.java.Compiler.compile(Compiler.java:56)
	at org.crsh.lang.impl.java.JavaCompiler.compileCommand(JavaCompiler.java:59)
	at org.crsh.lang.LanguageCommandResolver.resolveCommand(LanguageCommandResolver.java:128)
	at org.crsh.lang.LanguageCommandResolver.resolveCommand2(LanguageCommandResolver.java:109)
	at org.crsh.lang.LanguageCommandResolver.getDescriptions(LanguageCommandResolver.java:87)
	at org.crsh.shell.impl.command.CRaSH.getCommands(CRaSH.java:111)
	at org.crsh.shell.impl.command.system.help.main(help.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.crsh.cli.impl.lang.MethodDescriptor$1.invoke(MethodDescriptor.java:164)
	at org.crsh.cli.impl.lang.MethodDescriptor$1.invoke(MethodDescriptor.java:106)
	at org.crsh.lang.impl.java.ProducerCommandMatch$1.close(ProducerCommandMatch.java:117)
	at org.crsh.shell.impl.command.pipeline.CommandInvokerAdapter.close(CommandInvokerAdapter.java:296)
	at org.crsh.shell.impl.command.pipeline.PipeLine.close(PipeLine.java:106)
	at org.crsh.shell.impl.command.spi.CommandInvoker.invoke(CommandInvoker.java:52)
	at org.crsh.shell.impl.command.CRaSHCommandProcess.doInvoke(CRaSHCommandProcess.java:39)
	at org.crsh.shell.impl.command.CRaSHProcess.execute(CRaSHProcess.java:60)
	at org.crsh.shell.impl.async.AsyncProcess$2.call(AsyncProcess.java:207)
	at org.crsh.shell.impl.async.AsyncProcess$2.call(AsyncProcess.java:177)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

In terms of the built-in commands, the exception itself appears to be benign. It's output each time `help` is called but all the built-in commands are listed and appear to work as expected.

**Comment by wilkinsona** [comment]
The way in which CRaSH scans the classpath is rather naive and it's being tripped up when it's being given a URL that points to an entry inside a jar/war rather than to the root. Unfortunately, there's nothing we can do about that.

Interestingly, the behaviour is improved with Boot 1.4. I believe this is due to the improvements that we've made to `LaunchedURLClassLoader` and, specifically, its delegation model (#4897). I no longer set the exception when `help` is run and the `imx` command is available.

@anand1st Can you please try your app with 1.4.0.RC1 (available from https://repo.spring.io/libs-milestone) and let us know how you get on?

**Comment by anand1st** [comment]
Sorry for the delay. 1.4.0.RC1 sort of broke my app. Had to fix that first.

Anyway, have tested my application with the latest 1.4.0.RC1... and yes, the exception no longer appears with `help`

New issues observed:
1) Custom commands don't show up in both WAR and JAR archives.
2) Simple Shell Auth  don't work. Had to use the default user@localhost and the generated UUID as password to login and check.

The missing exception is a big problem now as developers developing custom commands won't know why something doesn't work.

**Comment by snicoll** [comment]
> 1.4.0.RC1 sort of broke my app

Unrelated but if you've noticed any regression, please report them as we still have two weeks to work on that before GA. Thanks!

**Comment by anand1st** [comment]
> Unrelated but if you've noticed any regression, please report them (in separate issues) as we still have two weeks to work on that before GA. Thanks!

Had direct dependencies on elasticsearch-1.5.2 `FilterBuilder` for custom searches. This class no longer exists in elasticsearch-2.3.x Nothing related to spring boot or data libraries.

**Comment by wilkinsona** [comment]
> 2) Simple Shell Auth don't work. Had to use the default user@localhost and the generated UUID as password to login and check.

It works for me. I would guess that it didn't work for you because the [property prefix has changed from `shell` to `management.shell`](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.4.0-M3-Release-Notes#remote-shell) in 1.4.0.M3.

**Comment by wilkinsona** [comment]
> 1) Custom commands don't show up in both WAR and JAR archives.

I can't reproduce this. In 1.4 custom commands work in both a jar and a war. Can you please provide a small sample that shows a custom command not working with 1.4?

**Comment by anand1st** [comment]
I just tested this with a new spring-boot 1.4 project. Yes, you are right. It's working. I'll have to check my app again to see why remote-shell isn't working there. Will update once I figure out what the problem is.

I'm not sure if I should close this issue as this problem is still an issue with 1.3.6.RELEASE. For now, it seems to be fixed with 1.4.0.RC1. Will leave it to you to decide.

**Comment by wilkinsona** [comment]
It works in 1.4 because of #4897. Unfortunately, that's too big a change to back port to 1.3.x. Ideally, the class path scanning code in Crash wouldn't be so naive but I think that's unlikely to happen.

**Comment by anand1st** [comment]
There's some rather odd behaviour. I now know why my custom commands didn't work. My app modules have the following structure: `services`, `app`

The `app` module pulls all artifacts and builds the entire executable. I had put in my controller classes and the main method inside the `app` modules. I had also included in a `my.utils.ShellUtils` java class inside this module as I was adding in my custom commands inside this module (in src/main/resources/commands) and was using `ShellUtils` as a helper class in my commands. When I type my custom command inside the shell (btw, the custom command didn't appear when I typed `help`), the following exception was obtained:
```
2016-07-18 14:31:55.157 ERROR 24849 --- [pool-8-thread-3] o.crsh.shell.impl.command.CRaSHSession   : Error while evaluating request 'custom' Could not compile command

org.crsh.shell.impl.command.spi.CommandException: Could not compile command
	at org.crsh.lang.impl.java.JavaCompiler.compileCommand(JavaCompiler.java:65) ~[crash.shell-1.3.2.jar!/:na]
	at org.crsh.lang.LanguageCommandResolver.resolveCommand(LanguageCommandResolver.java:128) ~[crash.shell-1.3.2.jar!/:na]
	at org.crsh.lang.LanguageCommandResolver.resolveCommand2(LanguageCommandResolver.java:109) ~[crash.shell-1.3.2.jar!/:na]
	at org.crsh.lang.LanguageCommandResolver.resolveCommand(LanguageCommandResolver.java:100) ~[crash.shell-1.3.2.jar!/:na]
	at org.crsh.shell.impl.command.CRaSH.getCommand(CRaSH.java:100) ~[crash.shell-1.3.2.jar!/:na]
	at org.crsh.shell.impl.command.CRaSHSession.getCommand(CRaSHSession.java:96) ~[crash.shell-1.3.2.jar!/:na]
	at org.crsh.lang.impl.script.PipeLineFactory.create(PipeLineFactory.java:89) ~[crash.shell-1.3.2.jar!/:na]
	at org.crsh.lang.impl.script.ScriptRepl.eval(ScriptRepl.java:88) ~[crash.shell-1.3.2.jar!/:na]
	at org.crsh.shell.impl.command.CRaSHSession.createProcess(CRaSHSession.java:163) ~[crash.shell-1.3.2.jar!/:na]
	at org.crsh.shell.impl.async.AsyncProcess.execute(AsyncProcess.java:172) ~[crash.shell-1.3.2.jar!/:na]
	at org.crsh.console.Console.iterate(Console.java:219) ~[crash.shell-1.3.2.jar!/:na]
	at org.crsh.console.Console.on(Console.java:158) ~[crash.shell-1.3.2.jar!/:na]
	at org.crsh.console.Console.on(Console.java:135) ~[crash.shell-1.3.2.jar!/:na]
	at org.crsh.console.jline.JLineProcessor.run(JLineProcessor.java:204) ~[crash.shell-1.3.2.jar!/:na]
	at org.crsh.ssh.term.CRaSHCommand.run(CRaSHCommand.java:99) ~[crash.connectors.ssh-1.3.2.jar!/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]
Caused by: org.crsh.lang.impl.java.CompilationFailureException: package my.utils does not exist
```  

When I stopped using the ShellUtils and moved all helper methods into my custom command, then everything worked just fine. With 1.3.6.RELEASE, the `ShellUtils` could be loaded up in my custom commands but not with 1.4.0.RC1.

However, if I put the `ShellUtils` inside the `services` module, then everything works as expected. It's just that it cannot be in the same module as the custom commands. The behaviour is the same for both WAR and JAR archives.

**Comment by wilkinsona** [comment]
I'm not 100% sure that I've understood all of that. Can you provide a sample that clearly shows the different behaviours that you have described?

**Comment by anand1st** [comment]
:-) Will provide sample in a while.

**Comment by anand1st** [comment]
[spring-boot-test.zip](https://github.com/spring-projects/spring-boot/files/368549/spring-boot-test.zip)

Please see attached. The project contains 2 modules `app` and `service`. `app` has a dependency on `service`.
I've created 3 custom commands i.e. `test1`, `test2` and `test3` inside the `app` module:
- `test1` is a simple normal command without any helper classes
- `test2` is using a helper class from the `app` module
- `test3` is using a helper class from the `service` module

`test1` and `test3` work just fine. `test2` doesn't work. Typing `test2` on the shell gives the above error.

**Comment by wilkinsona** [comment]
Thanks. That's given me a clear picture of what's going on.

It's ultimately due to the naive class path scanning in Crash. The problem is that Crash isn't capable of loading classes from a jar file that aren't at the root of the jar, despite that non-root location being on the class path.

It fails with a war file in both 1.3.6 and 1.4.0 because the classes are in `/WEB-INF/classes`. It also fails with a jar file in 1.4 because classes have moved from `/` to `/BOOT-INF/classes`. Thankfully, Crash can load classes from a jar file that's embedded inside another which is why `test3` works.

I'll see if I can plug a better class path scanner into Crash (it is quite extensible). In the mean time, you can work around your problem by packaging any helper classes in a separate module.

**Comment by wilkinsona** [comment]
Unfortunately, the plug point is a bit too high up. We'd need to plug in a whole new `org.crsh.lang.spi.Language` as how it creates the underlying compiler and configures its classpath is all hard coded.

You might like to [open a CRASH issue](https://jira.exoplatform.org/projects/CRASH/issues/CRASH-244?filter=allopenissues) requesting an enhancement to their class path scanning logic. Unfortunately, I don't have much hope that I'll have any effect as the Crash project is pretty much dormant now.

I think that the best we can do is to update Boot's documentation to describe the limitation and work around.

**Comment by anand1st** [comment]
I agree with you. Thanks for your help Andy.

**Comment by bgmf** [comment]
I'm affected by this as well. I only realized it yesterdays, when I wanted to updated our Hazelcast cluster application from **1.3.5** to **1.4.0**...

@anand1st have you already opened an issue at the _CRaSH_ issue tracker? If so, could you please provide me a link to the issue?

I don't know, if this would result in any other drawbacks, but you **could** override the _managed spring-boot-maven-plugin_ with a version like **1.3.7.RELEASE** and would get a Spring Boot 1.4 JAR in the old format, so that Crash is "happy" and you could still use the Spring boot 1.4 features...
Just as an idea.

**Comment by wilkinsona** [comment]
@bgmf I'd strongly recommend against trying to use Boot 1.4 with Boot 1.3's Maven plugin. As documented, a far more robust alternative is to package the dependencies of any custom shell commands in a nested jar rather than directly in the executable jar itself.

**Comment by bgmf** [comment]
@wilkinsona For now we postponed the idea of updating that particular part altogether. To package the deps of the custom command would require to create a jar with many parts of our (ok, still small) application. Beside some model classes we get some services from the context (e.g. `invocationContext.getAttributes().get("spring.beanfactory");`). While I understand your suggestion it would mean more work then we currently want to spent on it. For now.

**Comment by anand1st** [comment]
@bgmf No, I didn't as there's not much activity going on in that project.

**Comment by existme** [comment]
I have the same issue and had high hopes for this. It would be nice if we could find a work around!

**Comment by bric3** [comment]
It's a bit outdated, but since we had this issue as well, I published a quick fix resolving this issue in (https://github.com/crashub/crash/pull/119).

It might be worth investigating https://github.com/corda/crash fork as well for other updates.
