### ISSUE TITLE
AspectJ + Jersey2 + NullPointerException

### ISSUE THREAD

**Issue by ednilsoncampos** [spring-projects/spring-boot#6395]
I have a problem after enable Aspect in jersey.
I have two services rest: one @RestController and other jersey2 @Path.
The spring rest workin with @Aspect but the service with jersey throw a NullPointerException when is acessed.

Follow the stack trace:

```
java.lang.NullPointerException: null
	at org.glassfish.jersey.server.ResourceConfig.getProperties(ResourceConfig.java:754) ~[jersey-server-2.22.2.jar:na]
	at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:386) ~[jersey-container-servlet-core-2.22.2.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:177) ~[jersey-container-servlet-core-2.22.2.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:369) ~[jersey-container-servlet-core-2.22.2.jar:na]
	at javax.servlet.GenericServlet.init(GenericServlet.java:158) ~[tomcat-embed-core-8.0.36.jar:8.0.36]
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1238) [tomcat-embed-core-8.0.36.jar:8.0.36]
	at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:844) [tomcat-embed-core-8.0.36.jar:8.0.36]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:135) [tomcat-embed-core-8.0.36.jar:8.0.36]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [tomcat-embed-core-8.0.36.jar:8.0.36]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [tomcat-embed-core-8.0.36.jar:8.0.36]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) [tomcat-embed-core-8.0.36.jar:8.0.36]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.0.36.jar:8.0.36]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [tomcat-embed-core-8.0.36.jar:8.0.36]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528) [tomcat-embed-core-8.0.36.jar:8.0.36]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1099) [tomcat-embed-core-8.0.36.jar:8.0.36]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:670) [tomcat-embed-core-8.0.36.jar:8.0.36]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520) [tomcat-embed-core-8.0.36.jar:8.0.36]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476) [tomcat-embed-core-8.0.36.jar:8.0.36]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_92]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.0.36.jar:8.0.36]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]

2016-07-14 12:52:16.842 ERROR 2156 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[.[.example.JerseyConfig]  : Allocate exception for servlet com.example.JerseyConfig

java.lang.NullPointerException: null
	at org.glassfish.jersey.server.ResourceConfig.getProperties(ResourceConfig.java:754) ~[jersey-server-2.22.2.jar:na]
	at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:386) ~[jersey-container-servlet-core-2.22.2.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:177) ~[jersey-container-servlet-core-2.22.2.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:369) ~[jersey-container-servlet-core-2.22.2.jar:na]
	at javax.servlet.GenericServlet.init(GenericServlet.java:158) ~[tomcat-embed-core-8.0.36.jar:8.0.36]
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1238) ~[tomcat-embed-core-8.0.36.jar:8.0.36]
	at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:844) ~[tomcat-embed-core-8.0.36.jar:8.0.36]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:135) ~[tomcat-embed-core-8.0.36.jar:8.0.36]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [tomcat-embed-core-8.0.36.jar:8.0.36]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [tomcat-embed-core-8.0.36.jar:8.0.36]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) [tomcat-embed-core-8.0.36.jar:8.0.36]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.0.36.jar:8.0.36]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [tomcat-embed-core-8.0.36.jar:8.0.36]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528) [tomcat-embed-core-8.0.36.jar:8.0.36]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1099) [tomcat-embed-core-8.0.36.jar:8.0.36]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:670) [tomcat-embed-core-8.0.36.jar:8.0.36]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520) [tomcat-embed-core-8.0.36.jar:8.0.36]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476) [tomcat-embed-core-8.0.36.jar:8.0.36]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_92]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.0.36.jar:8.0.36]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]
```
Main Dependencies
 ```
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jersey</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
            <scope>provided</scope>
        </dependency>
```
Anotation class:
```
@SpringBootApplication
@EnableAspectJAutoProxy
public class DemoAopApplication
...
@Aspect
@Component
public class ServiceMonitor
...
@Path("monitor")
public class DemoRest
...
@Configuration
public class JerseyConfig extends ResourceConfig {
    public JerseyConfig() {
        super.register(DemoRest.class);
    }    
}
```
Someone help me?

**Comment by philwebb** [comment]
Could you please provide a sample application that shows the issue? You can submit a putt request to https://github.com/spring-projects/spring-boot-issues or just point us at a personal GitHub project.

**Comment by ednilsoncampos** [comment]
Follow link [github](https://github.com/ednilsoncampos/demo-aop.git)

Thanks

**Comment by wilkinsona** [comment]
Thanks for the sample. The problem's to do with your aspect and the fact that it causes `JerseyConfig` to be proxied. CGLib can't proxy final methods and `JerseyConfig` has quite a few of those, including `getProperties()` which is causing the `NullPointerException`.

Numerous messages are logged at startup:

```
2016-07-15 16:11:16.476  INFO 43183 --- [ost-startStop-1] o.s.aop.framework.CglibAopProxy          : Unable to proxy method [final void org.glassfish.jersey.server.ResourceConfig.lock()] because it is final: All calls to this method via a proxy will NOT be routed to the target instance.
2016-07-15 16:11:16.476  INFO 43183 --- [ost-startStop-1] o.s.aop.framework.CglibAopProxy          : Unable to proxy method [public final java.lang.Object org.glassfish.jersey.server.ResourceConfig.getProperty(java.lang.String)] because it is final: All calls to this method via a proxy will NOT be routed to the target instance.
2016-07-15 16:11:16.476  INFO 43183 --- [ost-startStop-1] o.s.aop.framework.CglibAopProxy          : Unable to proxy method [public final java.lang.ClassLoader org.glassfish.jersey.server.ResourceConfig.getClassLoader()] because it is final: All calls to this method via a proxy will NOT be routed to the target instance.
2016-07-15 16:11:16.476  INFO 43183 --- [ost-startStop-1] o.s.aop.framework.CglibAopProxy          : Unable to proxy method [public final java.util.Set org.glassfish.jersey.server.ResourceConfig.getClasses()] because it is final: All calls to this method via a proxy will NOT be routed to the target instance.
2016-07-15 16:11:16.476  INFO 43183 --- [ost-startStop-1] o.s.aop.framework.CglibAopProxy          : Unable to proxy method [public final org.glassfish.jersey.server.ResourceConfig org.glassfish.jersey.server.ResourceConfig.packages(boolean,java.lang.String[])] because it is final: All calls to this method via a proxy will NOT be routed to the target instance.
2016-07-15 16:11:16.476  INFO 43183 --- [ost-startStop-1] o.s.aop.framework.CglibAopProxy          : Unable to proxy method [public final org.glassfish.jersey.server.ResourceConfig org.glassfish.jersey.server.ResourceConfig.packages(java.lang.String[])] because it is final: All calls to this method via a proxy will NOT be routed to the target instance.
2016-07-15 16:11:16.476  INFO 43183 --- [ost-startStop-1] o.s.aop.framework.CglibAopProxy          : Unable to proxy method [public final java.util.Set org.glassfish.jersey.server.ResourceConfig.getResources()] because it is final: All calls to this method via a proxy will NOT be routed to the target instance.
2016-07-15 16:11:16.476  INFO 43183 --- [ost-startStop-1] o.s.aop.framework.CglibAopProxy          : Unable to proxy method [public final java.util.Map org.glassfish.jersey.server.ResourceConfig.getProperties()] because it is final: All calls to this method via a proxy will NOT be routed to the target instance.
2016-07-15 16:11:16.476  INFO 43183 --- [ost-startStop-1] o.s.aop.framework.CglibAopProxy          : Unable to proxy method [final void org.glassfish.jersey.server.ResourceConfig.invalidateCache()] because it is final: All calls to this method via a proxy will NOT be routed to the target instance.
2016-07-15 16:11:16.476  INFO 43183 --- [ost-startStop-1] o.s.aop.framework.CglibAopProxy          : Unable to proxy method [public final boolean org.glassfish.jersey.server.ResourceConfig.isProperty(java.lang.String)] because it is final: All calls to this method via a proxy will NOT be routed to the target instance.
2016-07-15 16:11:16.477  INFO 43183 --- [ost-startStop-1] o.s.aop.framework.CglibAopProxy          : Unable to proxy method [public final org.glassfish.jersey.server.ResourceConfig org.glassfish.jersey.server.ResourceConfig.registerClasses(java.lang.Class[])] because it is final: All calls to this method via a proxy will NOT be routed to the target instance.
2016-07-15 16:11:16.477  INFO 43183 --- [ost-startStop-1] o.s.aop.framework.CglibAopProxy          : Unable to proxy method [public final org.glassfish.jersey.server.ResourceConfig org.glassfish.jersey.server.ResourceConfig.registerClasses(java.util.Set)] because it is final: All calls to this method via a proxy will NOT be routed to the target instance.
2016-07-15 16:11:16.477  INFO 43183 --- [ost-startStop-1] o.s.aop.framework.CglibAopProxy          : Unable to proxy method [public final org.glassfish.jersey.server.ResourceConfig org.glassfish.jersey.server.ResourceConfig.addProperties(java.util.Map)] because it is final: All calls to this method via a proxy will NOT be routed to the target instance.
2016-07-15 16:11:16.477  INFO 43183 --- [ost-startStop-1] o.s.aop.framework.CglibAopProxy          : Unable to proxy method [public final org.glassfish.jersey.server.ResourceConfig org.glassfish.jersey.server.ResourceConfig.registerInstances(java.lang.Object[])] because it is final: All calls to this method via a proxy will NOT be routed to the target instance.
2016-07-15 16:11:16.477  INFO 43183 --- [ost-startStop-1] o.s.aop.framework.CglibAopProxy          : Unable to proxy method [public final org.glassfish.jersey.server.ResourceConfig org.glassfish.jersey.server.ResourceConfig.registerInstances(java.util.Set)] because it is final: All calls to this method via a proxy will NOT be routed to the target instance.
2016-07-15 16:11:16.477  INFO 43183 --- [ost-startStop-1] o.s.aop.framework.CglibAopProxy          : Unable to proxy method [public final org.glassfish.jersey.server.ResourceConfig org.glassfish.jersey.server.ResourceConfig.registerResources(org.glassfish.jersey.server.model.Resource[])] because it is final: All calls to this method via a proxy will NOT be routed to the target instance.
2016-07-15 16:11:16.477  INFO 43183 --- [ost-startStop-1] o.s.aop.framework.CglibAopProxy          : Unable to proxy method [public final org.glassfish.jersey.server.ResourceConfig org.glassfish.jersey.server.ResourceConfig.registerResources(java.util.Set)] because it is final: All calls to this method via a proxy will NOT be routed to the target instance.
2016-07-15 16:11:16.477  INFO 43183 --- [ost-startStop-1] o.s.aop.framework.CglibAopProxy          : Unable to proxy method [public final org.glassfish.jersey.server.ResourceConfig org.glassfish.jersey.server.ResourceConfig.registerFinder(org.glassfish.jersey.server.ResourceFinder)] because it is final: All calls to this method via a proxy will NOT be routed to the target instance.
2016-07-15 16:11:16.477  INFO 43183 --- [ost-startStop-1] o.s.aop.framework.CglibAopProxy          : Unable to proxy method [public final org.glassfish.jersey.server.ResourceConfig org.glassfish.jersey.server.ResourceConfig.setApplicationName(java.lang.String)] because it is final: All calls to this method via a proxy will NOT be routed to the target instance.
2016-07-15 16:11:16.477  INFO 43183 --- [ost-startStop-1] o.s.aop.framework.CglibAopProxy          : Unable to proxy method [public final java.util.Set org.glassfish.jersey.server.ResourceConfig.getSingletons()] because it is final: All calls to this method via a proxy will NOT be routed to the target instance.
2016-07-15 16:11:16.477  INFO 43183 --- [ost-startStop-1] o.s.aop.framework.CglibAopProxy          : Unable to proxy method [final org.glassfish.jersey.model.internal.ComponentBag org.glassfish.jersey.server.ResourceConfig.getComponentBag()] because it is final: All calls to this method via a proxy will NOT be routed to the target instance.
2016-07-15 16:11:16.477  INFO 43183 --- [ost-startStop-1] o.s.aop.framework.CglibAopProxy          : Unable to proxy method [final void org.glassfish.jersey.server.ResourceConfig.configureAutoDiscoverableProviders(org.glassfish.hk2.api.ServiceLocator)] because it is final: All calls to this method via a proxy will NOT be routed to the target instance.
2016-07-15 16:11:16.477  INFO 43183 --- [ost-startStop-1] o.s.aop.framework.CglibAopProxy          : Unable to proxy method [final void org.glassfish.jersey.server.ResourceConfig.configureForcedAutoDiscoverableProviders(org.glassfish.hk2.api.ServiceLocator)] because it is final: All calls to this method via a proxy will NOT be routed to the target instance.
2016-07-15 16:11:16.477  INFO 43183 --- [ost-startStop-1] o.s.aop.framework.CglibAopProxy          : Unable to proxy method [final void org.glassfish.jersey.server.ResourceConfig.configureMetaProviders(org.glassfish.hk2.api.ServiceLocator)] because it is final: All calls to this method via a proxy will NOT be routed to the target instance.
2016-07-15 16:11:16.477  INFO 43183 --- [ost-startStop-1] o.s.aop.framework.CglibAopProxy          : Unable to proxy method [public final javax.ws.rs.core.Application org.glassfish.jersey.server.ResourceConfig.getApplication()] because it is final: All calls to this method via a proxy will NOT be routed to the target instance.
2016-07-15 16:11:16.478  INFO 43183 --- [ost-startStop-1] o.s.aop.framework.CglibAopProxy          : Unable to proxy method [final org.glassfish.jersey.server.ResourceConfig org.glassfish.jersey.server.ResourceConfig.setApplication(javax.ws.rs.core.Application)] because it is final: All calls to this method via a proxy will NOT be routed to the target instance.
2016-07-15 16:11:16.478  INFO 43183 --- [ost-startStop-1] o.s.aop.framework.CglibAopProxy          : Unable to proxy method [public final org.glassfish.jersey.server.ServerConfig org.glassfish.jersey.server.ResourceConfig.getConfiguration()] because it is final: All calls to this method via a proxy will NOT be routed to the target instance.
2016-07-15 16:11:16.478  INFO 43183 --- [ost-startStop-1] o.s.aop.framework.CglibAopProxy          : Unable to proxy method [public final java.util.Set org.glassfish.jersey.server.ResourceConfig.getInstances()] because it is final: All calls to this method via a proxy will NOT be routed to the target instance.
2016-07-15 16:11:16.478  INFO 43183 --- [ost-startStop-1] o.s.aop.framework.CglibAopProxy          : Unable to proxy method [public final org.glassfish.jersey.server.ResourceConfig org.glassfish.jersey.server.ResourceConfig.setClassLoader(java.lang.ClassLoader)] because it is final: All calls to this method via a proxy will NOT be routed to the target instance.
2016-07-15 16:11:16.478  INFO 43183 --- [ost-startStop-1] o.s.aop.framework.CglibAopProxy          : Unable to proxy method [public final org.glassfish.jersey.server.ResourceConfig org.glassfish.jersey.server.ResourceConfig.files(boolean,java.lang.String[])] because it is final: All calls to this method via a proxy will NOT be routed to the target instance.
2016-07-15 16:11:16.478  INFO 43183 --- [ost-startStop-1] o.s.aop.framework.CglibAopProxy          : Unable to proxy method [public final org.glassfish.jersey.server.ResourceConfig org.glassfish.jersey.server.ResourceConfig.files(java.lang.String[])] because it is final: All calls to this method via a proxy will NOT be routed to the target instance.
```

You should modify the pointcuts in your aspect and/or repackage your code so that your aspect doesn't apply to `JerseyConfig`. For example, you could move everything except `DemoAopApplication` and `JerseyConfig` into `com.example.foo` and change the pointcut to `execution(* com.example.foo..*.*(..))`

**Comment by ednilsoncampos** [comment]
Very thanks!!
