### ISSUE TITLE
Automatically disable DevTools when running a Cucumber test

### ISSUE THREAD

**Issue by johan-backstrom** [spring-projects/spring-boot#6412]
We have a set of "semi integration" cucumber tests in the same project as a spring boot app. The tests first start up the spring boot app with SpringApplicationBuilder and then run the tests against it. These tests suddenly started quitting silently just as the Spring Boot app was starting. We have worked around the problem, but I thought I'd report it anyway.

In the example code below the application is started with the parameter "--monkey=666". What happens then is that the parent thread (cucumber.api.cli.Main) is restarted by spring-boot-dev-tools and the monkey-parameter is passed to it, resulting in the error below. We would expect the spring boot app to be restarted with its parameter, not Cucumber. It would also have helped a lot if there were some sort of log output when the restart occurs.

Code in cucumber @Before annotated method (simplified for readability):

```
@Before
public synchronized void startServer() throws Exception {
        app = new SpringApplicationBuilder()
                .sources(Application.class)
                .properties(System.getProperties())
                .build()
                .run("--monkey=666");
}
```

Error message:

```
Exception in thread "restartedMain" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: cucumber.runtime.CucumberException: Unknown option: --monkey=666
	at cucumber.runtime.RuntimeOptions.parse(RuntimeOptions.java:131)
	at cucumber.runtime.RuntimeOptions.<init>(RuntimeOptions.java:77)
	at cucumber.runtime.RuntimeOptions.<init>(RuntimeOptions.java:70)
	at cucumber.runtime.RuntimeOptions.<init>(RuntimeOptions.java:62)
	at cucumber.api.cli.Main.run(Main.java:31)
	at cucumber.api.cli.Main.main(Main.java:18)
	... 5 more
```

Gradle dependencies (not complete list):

```
    compile("org.springframework.boot:spring-boot-devtools:1.3.5.RELEASE")
    compile("org.springframework.boot:spring-boot-starter-web:1.3.5.RELEASE")
    testCompile('info.cukes:cucumber-spring:1.2.2')
    testCompile('org.springframework:spring-tx:4.2.6.RELEASE')
```

**Comment by philwebb** [comment]
Are you able to provide a minimal project on GitHub that reproduces the issue? By default we try to automatically disable DevTools when tests are running. Perhaps there's something about the way that cucumber tests are started which means this isn't working.

**Comment by johan-backstrom** [comment]
Here's a small java project that reproduces the described behaviour: https://github.com/johan-backstrom/spring-boot-6412

**Comment by wilkinsona** [comment]
Thanks for the sample, @johan-backstrom.

As @philwebb suspected, the problem is that DevTools isn't being automatically disabled. You said above that you have a workaround but, just in case this is more elegant, you can disable DevTools using a system property. Add the following to `javaexec` in your `cucumber` task:

```
jvmArgs = ['-Dspring.devtools.restart.enabled=false']
```

**Comment by wilkinsona** [comment]
>  It would also have helped a lot if there were some sort of log output when the restart occurs.

Unfortunately, the restart intentionally happens _very_ early so we can't meaningfully log anything

**Comment by wilkinsona** [comment]
The stack when we're getting the initial URLs is:

```
java.lang.Thread.getStackTrace(Thread.java:1552)
org.springframework.boot.devtools.restart.DefaultRestartInitializer.getInitialUrls(DefaultRestartInitializer.java:46)
org.springframework.boot.devtools.restart.Restarter.<init>(Restarter.java:134)
org.springframework.boot.devtools.restart.Restarter.initialize(Restarter.java:531)
org.springframework.boot.devtools.restart.RestartApplicationListener.onApplicationStartedEvent(RestartApplicationListener.java:64)
org.springframework.boot.devtools.restart.RestartApplicationListener.onApplicationEvent(RestartApplicationListener.java:46)
org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:121)
org.springframework.boot.context.event.EventPublishingRunListener.publishEvent(EventPublishingRunListener.java:111)
org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:60)
org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:48)
org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
com.github.johan.backstrom.CucumberSteps.the_app_is_running(CucumberSteps.java:19)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
cucumber.runtime.Utils$1.call(Utils.java:37)
cucumber.runtime.Timeout.timeout(Timeout.java:13)
cucumber.runtime.Utils.invoke(Utils.java:31)
cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:37)
cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:37)
cucumber.runtime.Runtime.runStep(Runtime.java:298)
cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44)
cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:39)
cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:48)
cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:163)
cucumber.runtime.Runtime.run(Runtime.java:120)
cucumber.api.cli.Main.run(Main.java:36)
cucumber.api.cli.Main.main(Main.java:18)
```
