### ISSUE TITLE
Hard to identify cause of IllegalStateException thrown by DevTools when it can't read jar's manifest

### ISSUE THREAD

**Issue by rsallar** [spring-projects/spring-boot#6417]
Hi, application does not launch when activating devtools (eclipse-neon windows).
Spring boot version is 1.3.6.RELEASE
The error is 
```
Exception in thread "main" java.lang.IllegalStateException: Failed to read Class-Path attribute from manifest of jar file:/C:/Users/Ramon/.m2/repository/ognl/ognl/3.0.8/ognl-3.0.8.jar
	at org.springframework.boot.devtools.restart.ChangeableUrls.getUrlsFromClassPathOfJarManifestIfPossible(ChangeableUrls.java:100)
	at org.springframework.boot.devtools.restart.ChangeableUrls.fromUrlClassLoader(ChangeableUrls.java:88)
	at org.springframework.boot.devtools.restart.DefaultRestartInitializer.getUrls(DefaultRestartInitializer.java:91)
	at org.springframework.boot.devtools.restart.DefaultRestartInitializer.getInitialUrls(DefaultRestartInitializer.java:54)
	at org.springframework.boot.devtools.restart.Restarter.<init>(Restarter.java:134)
	at org.springframework.boot.devtools.restart.Restarter.initialize(Restarter.java:531)
	at org.springframework.boot.devtools.restart.RestartApplicationListener.onApplicationStartedEvent(RestartApplicationListener.java:64)
	at org.springframework.boot.devtools.restart.RestartApplicationListener.onApplicationEvent(RestartApplicationListener.java:46)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:121)
	at org.springframework.boot.context.event.EventPublishingRunListener.publishEvent(EventPublishingRunListener.java:111)
	at org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:60)
	at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:48)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
	at com.github.rsallar.underevalprj.UnderevalprjApplication.main(UnderevalprjApplication.java:10)
```

You can check the code here:

https://github.com/rsallar/underevalprj/tree/bug-devtools

**Comment by wilkinsona** [comment]
It works fine for me on OS X. It could be due to a corrupted jar. Can you try cleaning out your Maven cache and trying again?

**Comment by rsallar** [comment]
You were right. Sorry for bothering.

**Comment by wilkinsona** [comment]
We could improve the exception by including the cause

**Comment by nikilsss** [comment]
I am getting same error 
Exception in thread "main" java.lang.IllegalStateException: Failed to read Class-Path attribute from manifest of jar file:/C:/Users/NIKIL/.m2/repository/org/hibernate/hibernate-core/5.0.12.Final/hibernate-core-5.0.12.Final.jar
	at org.springframework.boot.devtools.restart.ChangeableUrls.getUrlsFromClassPathOfJarManifestIfPossible(ChangeableUrls.java:110)
	at org.springframework.boot.devtools.restart.ChangeableUrls.fromUrlClassLoader(ChangeableUrls.java:96)
	at org.springframework.boot.devtools.restart.DefaultRestartInitializer.getUrls(DefaultRestartInitializer.java:93)
	at org.springframework.boot.devtools.restart.DefaultRestartInitializer.getInitialUrls(DefaultRestartInitializer.java:56)
	at org.springframework.boot.devtools.restart.Restarter.<init>(Restarter.java:140)
	at org.springframework.boot.devtools.restart.Restarter.initialize(Restarter.java:546)
	at org.springframework.boot.devtools.restart.RestartApplicationListener.onApplicationStartingEvent(RestartApplicationListener.java:67)
	at org.springframework.boot.devtools.restart.RestartApplicationListener.onApplicationEvent(RestartApplicationListener.java:45)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
	at org.springframework.boot.context.event.EventPublishingRunListener.starting(EventPublishingRunListener.java:68)
	at org.springframework.boot.SpringApplicationRunListeners.starting(SpringApplicationRunListeners.java:48)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151)
	at com.kaawaa.WedeliverApplication.main(WedeliverApplication.java:10)
Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)
	at java.util.zip.ZipFile.read(Native Method)
	at java.util.zip.ZipFile.access$1400(Unknown Source)
	at java.util.zip.ZipFile$ZipFileInputStream.read(Unknown Source)
	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(Unknown Source)
	at java.util.zip.InflaterInputStream.read(Unknown Source)
	at sun.misc.IOUtils.readFully(Unknown Source)
	at java.util.jar.JarFile.getBytes(Unknown Source)
	at java.util.jar.JarFile.getManifestFromReference(Unknown Source)
	at java.util.jar.JarFile.getManifest(Unknown Source)
	at org.springframework.boot.devtools.restart.ChangeableUrls.getUrlsFromManifestClassPathAttribute(ChangeableUrls.java:131)
	at org.springframework.boot.devtools.restart.ChangeableUrls.getUrlsFromClassPathOfJarManifestIfPossible(ChangeableUrls.java:107)
	... 16 more
 i am tried cleaning building ..I have just added dependency  spring boot stater data jpa and create model class

**Comment by nikilsss** [comment]
what can be the fest solution so that when i encounter these i can solve it without wasting my 4 days  and for your kind response i have just started learning spring boot

**Comment by wilkinsona** [comment]
We now include the cause. In your case you can see that the failure was due to a `ZipException`. That's a very strong indication that you have a corrupted jar. The message of the `IllegalStateException` tells you which jar is causing the problem:

```
file:/C:/Users/NIKIL/.m2/repository/org/hibernate/hibernate-core/5.0.12.Final/hibernate-core-5.0.12.Final.jar
```

You should remove that jar from your Maven cache and try building your project again so that Maven has another go at downloading it.

**Comment by suthernfriend** [comment]
for me. the following (under linux) helped: 

> rm -rf ~/.m2

however should be the last thing you try

**Comment by lokeshkumarputta** [comment]
Yes, i have deleted exception jar and clean up the Maven and run the Sprint Boot application. Now its working fine.

**Comment by aymenbraiek** [comment]
exception jar  ?????

**Comment by wilkinsona** [comment]
The jar at the path in the message of the exception.
