### ISSUE TITLE
Stack trace when interrupting forked spring-boot:run -Xdebug

### ISSUE THREAD

**Issue by mjustin** [spring-projects/spring-boot#6498]
As of Spring Boot 1.3.6, using ctrl-C to interrupt the currently running Spring Boot process when using "mvn spring-boot:run" displays a scary-looking but harmless stack trace:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.502 s
[INFO] Finished at: 2016-07-28T17:43:51-04:00
[INFO] Final Memory: 47M/729M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.3.7.RELEASE:run (default-cli) on project fulfillment-event-listener: Could not exec java: Application finished with non-zero exit code: 130 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.3.7.RELEASE:run (default-cli) on project fulfillment-event-listener: Could not exec java
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Could not exec java
    at org.springframework.boot.maven.RunMojo.runWithForkedJvm(RunMojo.java:52)
    at org.springframework.boot.maven.AbstractRunMojo.doRunWithForkedJvm(AbstractRunMojo.java:238)
    at org.springframework.boot.maven.AbstractRunMojo.run(AbstractRunMojo.java:216)
    at org.springframework.boot.maven.AbstractRunMojo.execute(AbstractRunMojo.java:185)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    ... 19 more
Caused by: org.apache.maven.plugin.MojoExecutionException: Application finished with non-zero exit code: 130
```

Is this intentional and desirable?  It looks like it was introduced by commit ec7d6381aa63513479e3e3b689da5c326dbb9077.

Edit: It looks like the whole stack trace is only displayed when running with the -X debug flag.  Maybe it's not as much of an issue, but the question is probably still valid whether "Could not exec java: Application finished with non-zero exit code: 130" should be displayed in this scenario.

**Comment by wilkinsona** [comment]
We could consider ignoring an exit code of 130 which is [produced in response to SIGINT](http://journal.thobe.org/2013/02/jvms-and-kill-signals.html) and perhaps 143 (SIGTERM) as well.

**Comment by mjustin** [comment]
Even if the exit code is ignored, it might still be worth logging that it was forcibly terminated (so that it's obvious what happened in the logs).  I think my issue with this right now is that it's presented as an error with the running of the program ("Could not exec java"), when that's not quite what's happening.

**Comment by IamGabrielWu** [comment]
Hi Even start the spring boot without X, like this  mvn spring-boot:run .  When ctrl+c this application, there still is 'Could not exec java: Application finished with non-zero exit code: 130'.

Is it a spring boot problem when shutting it down in this way ?

Error message: 

```
^C2016-08-04 07:11:51.027  INFO 867 --- [       Thread-3] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@7c417213: startup date [Thu Aug 04 07:10:32 CST 2016]; root of context hierarchy
2016-08-04 07:11:51.030  INFO 867 --- [       Thread-3] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:21 min
[INFO] Finished at: 2016-08-04T07:11:51+08:00
[INFO] Final Memory: 19M/226M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.4.0.RELEASE:run (default-cli) on project admin-seed: Could not exec java: Application finished with non-zero exit code: 130 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by wilkinsona** [comment]
Grade fails the build when SIGTERM is sent to the process so, for consistency, the Maven plugin should continue to do so too.
