### ISSUE TITLE
Spring Boot 1.4.0 Boot error due to JdbcTemplate dependency

### ISSUE THREAD

**Issue by sachinwalia2k8** [spring-projects/spring-boot#6499]
I have an application that manually creates DataSource and uses a third party Data access library on top of JDBC. Because of that my code doesn't depend on JdbcTemplate. I upgraded to Spring Boot 1.4.0 today and noticed application fail to boot.  Please note same codebase worked fine with Spring Boot 1.4.0.RC1

```
2016-07-28 21:57:25,081 [ERROR] [Logger::o.s.b.SpringApplication] [Thread::restartedMain] - Application startup failed
java.lang.IllegalStateException: Could not evaluate condition on org.springframework.boot.autoconfigure.transaction.TransactionAutoConfiguration due to org/springframework/jdbc/core/JdbcTemplate not found. Make sure your own configuration does not rely on that class. This can also happen if you are @ComponentScanning a springframework package (e.g. if you put a @ComponentScan in the default package by mistake)
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:55)
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:102)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader$TrackedConditionEvaluator.shouldSkip(ConfigurationClassBeanDefinitionReader.java:436)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:127)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:116)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:333)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:243)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:273)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:98)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:681)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:523)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:369)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:313)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
```

**Comment by snicoll** [comment]
`JdbcTemplateAutoConfiguration` has no guard for `JdbcTemplate` at all anymore (see the change in #6449). Previously we had a `@ConditionalOnType` on `EmbeddedDatabaseType` that was guarding that as a side effect.

In the meantime you could add `JdbcTemplateAutoConfiguration.class` to the list of exclusions, something like:

```
@SpringBootApplication(excludes=JdbcTemplateAutoConfiguration.class)
public class YourApp { ... }
```

**Comment by snicoll** [comment]
The  next `1.4.1.BUILD-SNAPSHOT` should fix this issue, @sachinwalia2k8 I'd appreciate if you could give that a try. Thanks!

**Comment by sachinwalia2k8** [comment]
@snicoll - i can try it out. do i need to include some repo to get the snapshot build?

**Comment by snicoll** [comment]
@sachinwalia2k8 Yes indeed, generate a project from start.spring.io to get an idea of the setup. Choose `1.4.1.BUILD-SNAPSHOT` and the build of your choice. Then look at the generated build.

**Comment by kazuki43zoo** [comment]
@sachinwalia2k8 Oh... , I've mistaken a modification. 
@snicoll Thanks for fix and provide a workaround.
