### ISSUE TITLE
SampleHypermediaJpaApplication fails to start with a NullPointerException

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#6584]
```
Caused by: java.lang.NullPointerException: null
	at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcHypermediaManagementContextConfiguration.curieProvider(EndpointWebMvcHypermediaManagementContextConfiguration.java:136) ~[classes/:na]
	at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcHypermediaManagementContextConfiguration$$EnhancerBySpringCGLIB$$d3044c2f.CGLIB$curieProvider$3(<generated>) ~[classes/:na]
	at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcHypermediaManagementContextConfiguration$$EnhancerBySpringCGLIB$$d3044c2f$$FastClassBySpringCGLIB$$c7d26387.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356) ~[spring-context-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcHypermediaManagementContextConfiguration$$EnhancerBySpringCGLIB$$d3044c2f.curieProvider(<generated>) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_74]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	... 107 common frames omitted
```

The tests pass though (which is why CI hasn't caught the problem).

**Comment by wilkinsona** [comment]
This is a regression caused by #4502

**Comment by vpavic** [comment]
Funny how `management.getPort()` got all the attention in #4502 and we all missed the fact that `server.getPort()` could be null :smile:
