### ISSUE TITLE
Spring boot application (1.4.0) fails to start due error with printing banner 

### ISSUE THREAD

**Issue by interair** [spring-projects/spring-boot#6617]
There is issue with printing banner at headless jvm: but from my point of view such issue shouldn't prevent starting whole application:
Environment:

```
FROM debian:stretch
RUN apt-get update && apt-get install -y --no-install-recommends openjdk-8-jdk-headless && apt-get clean
ADD ./spring-boot.jar /spring-boot.jar
ENTRYPOINT java -server -jar spring-boot.jar
```

Spring boot: 1.4.0.RELEASE

Exception:

```
ERROR o.s.b.SpringApplication - Application startup failed
java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
        at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:807)
        at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886)
        at java.awt.Image.getScaledInstance(Image.java:178)
        at org.springframework.boot.ImageBanner.resizeImage(ImageBanner.java:125)
        at org.springframework.boot.ImageBanner.readImage(ImageBanner.java:108)
        at org.springframework.boot.ImageBanner.printBanner(ImageBanner.java:100)
        at org.springframework.boot.ImageBanner.printBanner(ImageBanner.java:76)
        at org.springframework.boot.SpringApplicationBannerPrinter$Banners.printBanner(SpringApplicationBannerPrinter.java:142)
        at org.springframework.boot.SpringApplicationBannerPrinter.print(SpringApplicationBannerPrinter.java:71)
        at org.springframework.boot.SpringApplication.printBanner(SpringApplication.java:551)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:309)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
        at com.codeabovelab.dm.cluman.Application.main(Application.java:33)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58)
```

**Comment by philwebb** [comment]
We probably can't display the banner without AWT support, but I agree that we should still let the app run.

**Comment by philwebb** [comment]
BTW, deleting `banner.gif` will bypass that code in the meantime.

**Comment by snicoll** [comment]
Or you can disable the banner via configuration `spring.main.banner-mode=off`

**Comment by interair** [comment]
Thank you
`spring.main.banner-mode=off`
works
