### ISSUE TITLE
@MockBean SpringDataRepository fails with NoUniqueBeanDefinitionException

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#6640]
# Description 

If `@MockBean` is used on a Spring Data repository that is also `@Autowired` into another component in Spring Boot 1.4.0.RELEASE, a `NoUniqueBeanDefinitionException` is thrown. For example (link to GitHub repository with complete sample further down):

```java
@RestController
public class MessageController {
	public MessageController(MessageRepository repository) {
	}
}

@RunWith(SpringRunner.class)
@SpringBootTest
public class SpringDataTests {
	@MockBean
	MessageRepository messageRepository;

	@Test
	public void contextLoads() {
	}

}
```

Produces:

```
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:83)
	at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:189)
	at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:131)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:230)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:228)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:287)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:289)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:247)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'messageController' defined in file [/Users/rwinch/code/spring-boot-gh-6640/target/classes/sample/withcontroller/MessageController.class]: Unsatisfied dependency expressed through constructor parameter 0: No qualifying bean of type [sample.withcontroller.MessageRepository] is defined: expected single matching bean but found 2: messageRepository,sample.withcontroller.MessageRepository#0; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [sample.withcontroller.MessageRepository] is defined: expected single matching bean but found 2: messageRepository,sample.withcontroller.MessageRepository#0
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:189)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1143)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:776)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:369)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:313)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:111)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:98)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:116)
	... 25 more
Caused by: org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [sample.withcontroller.MessageRepository] is defined: expected single matching bean but found 2: messageRepository,sample.withcontroller.MessageRepository#0
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveNotUnique(DependencyDescriptor.java:172)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1065)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1019)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
	... 43 more


```

# Complete Sample 

You can find a sample of the project at https://github.com/rwinch/spring-boot-gh-6640

* [WithControllerTests](https://github.com/rwinch/spring-boot-gh-6640/blob/master/src/test/java/sample/withcontroller/WithControllerTests.java) will fail
* [NotSpringData](https://github.com/rwinch/spring-boot-gh-6640/blob/master/src/test/java/sample/notspringdata/NotSpringDataTests.java) will pass because it is not a Spring Data repository
* [NoControllerTests](https://github.com/rwinch/spring-boot-gh-6640/blob/master/src/test/java/sample/nocontroller/NoControllerTests.java) will pass because the Spring Data repository is not being `@Autowired` into another component (only into the test)

# Related to?

Possibly related to #6602

**Comment by snicoll** [comment]
That's most probably related to #6602 yes.

**Comment by wilkinsona** [comment]
Duplicates #6541

**Comment by rwinch** [comment]
I'm curious why this is a duplicate. The other issue has trouble
differentiating between two interfaces with different generic types. This
issue there is only a single interface. Can you explain how it is a
duplicate?

**Comment by wilkinsona** [comment]
@rwinch Have you read the duplicate issue and [this comment](https://github.com/spring-projects/spring-boot/issues/6541#issuecomment-238502837) in particular? Hopefully it explains my reasoning.

**Comment by rwinch** [comment]
@wilkinsona Thanks for the response. I didn't notice that you had pointed at a separate issue than @snicoll and I were referencing. You are correct. This is a duplicate and is fixed in the latest SNAPSHOT (as mentioned in the issue, #6541, you linked to)
