### ISSUE TITLE
Error updating from 1.3.1 to 1.4, UnsatisfiedDependencyException 

### ISSUE THREAD

**Issue by narup** [spring-projects/spring-boot#6705]
Hello Team,

I just upgraded my spring-boot version from 1.3.1 to 1.4 RELEASE version but getting this exception below: 

Code is same and was working with 1.3.1 version. I tried to look around for existing issues, didn't find any. Is there something I could be missing or some configuration that was ignored in previous version but not in 1.4?
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'cardViewController': Unsatisfied dependency expressed through field 'dashboardService': Error creating bean with name 'dashboardServiceImpl': Unsatisfied dependency expressed through field 'signupInfoService': Error creating bean with name 'signupInfoServiceImpl': Unsatisfied dependency expressed through field 'signupInfoRepository': No qualifying bean of type [com.app.repository.api.SignupInfoRepository] found for dependency [com.app.repository.api.SignupInfoRepository]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.app.repository.api.SignupInfoRepository] found for dependency [com.app.repository.api.SignupInfoRepository]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'signupInfoServiceImpl': Unsatisfied dependency expressed through field 'signupInfoRepository': No qualifying bean of type [com.app.repository.api.SignupInfoRepository] found for dependency [com.app.repository.api.SignupInfoRepository]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.app.repository.api.SignupInfoRepository] found for dependency [com.app.repository.api.SignupInfoRepository]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dashboardServiceImpl': Unsatisfied dependency expressed through field 'signupInfoService': Error creating bean with name 'signupInfoServiceImpl': Unsatisfied dependency expressed through field 'signupInfoRepository': No qualifying bean of type [com.app.repository.api.SignupInfoRepository] found for dependency [com.app.repository.api.SignupInfoRepository]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.app.repository.api.SignupInfoRepository] found for dependency [com.app.repository.api.SignupInfoRepository]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'signupInfoServiceImpl': Unsatisfied dependency expressed through field 'signupInfoRepository': No qualifying bean of type [com.app.repository.api.SignupInfoRepository] found for dependency [com.app.repository.api.SignupInfoRepository]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.app.repository.api.SignupInfoRepository] found for dependency [com.app.repository.api.SignupInfoRepository]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:569)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:349)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:776)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:369)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:313)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
	at com.app.MainApplication.main(MainApplication.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:483)

```

**Comment by narup** [comment]
Hmm. never mind I found the cause of an issue. I use spring-boot-starter-data-mongodb for MongoDB. I noticed one of my document model was missing `@Document` annotation. Looks like it was not an issue with 1.3.1 version. After I added that annotation it's working

**Comment by philwebb** [comment]
Glad you managed to sort it.
