### ISSUE TITLE
after upgrading from 1.3.7.RELEASE to 1.4.0.RELEASE mongodb driver throws json serialize exception

### ISSUE THREAD

**Issue by ranadeepak** [spring-projects/spring-boot#6757]
Hi,
Today I upgraded from Spring Boot version 1.3.7.RELEASE to 1.4.0.RELEASE. I am using spring-boot-starter-data-mongodb starter in my project. After upgrade, I am getting json serialization exception for one of the enum type in my domain object. This works fine with 1.3.7.RELEASE.

The stacktrace is as follows: 
```
java.lang.RuntimeException: json can't serialize type : class com.pb.lunchandlearn.domain.TrainingStatus
	at com.mongodb.util.ClassMapBasedObjectSerializer.serialize(ClassMapBasedObjectSerializer.java:79) ~[mongodb-driver-3.2.2.jar:na]
	at com.mongodb.util.JSONSerializers$MapSerializer.serialize(JSONSerializers.java:323) ~[mongodb-driver-3.2.2.jar:na]
	at com.mongodb.util.ClassMapBasedObjectSerializer.serialize(ClassMapBasedObjectSerializer.java:82) ~[mongodb-driver-3.2.2.jar:na]
	at com.mongodb.util.JSON.serialize(JSON.java:53) ~[mongodb-driver-3.2.2.jar:na]
	at com.mongodb.util.JSON.serialize(JSON.java:39) ~[mongodb-driver-3.2.2.jar:na]
	at com.mongodb.BasicDBObject.toString(BasicDBObject.java:196) ~[mongodb-driver-3.2.2.jar:na]
	at org.springframework.data.mongodb.repository.query.PartTreeMongoQuery.createQuery(PartTreeMongoQuery.java:113) ~[spring-data-mongodb-1.9.2.RELEASE.jar:na]
	at org.springframework.data.mongodb.repository.query.AbstractMongoQuery.execute(AbstractMongoQuery.java:81) ~[spring-data-mongodb-1.9.2.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:482) ~[spring-data-commons-1.12.2.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:460) ~[spring-data-commons-1.12.2.RELEASE.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:61) ~[spring-data-commons-1.12.2.RELEASE.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at com.sun.proxy.$Proxy94.findAllByStatusOrderByScore(Unknown Source) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:52) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at com.sun.proxy.$Proxy94.findAllByStatusOrderByScore(Unknown Source) ~[na:na]
```

**Comment by wilkinsona** [comment]
It's very hard to know what the problem is based purely on a stack trace. Can you provide a small sample that reproduces the problem?

**Comment by ranadeepak** [comment]
I have an enum:
public enum TrainingStatus {
	NOMINATED,
	SCHEDULED,
	CANCELLED,
	COMPLETED,
	POSTPONED
}

this is reffered in domain class:
@Document(collection = "trainings")
public final class Training {
	@NotNull
	@Indexed
	private TrainingStatus status;
        ...other fields
}

In my repository interface, have a find* method for Training objects by the 'status' property:

public interface TrainingRepository extends MongoRepository<Training, String> {
	@Query(fields = "{'name': 1, 'likesCount': 1, 'score': 1}")
	Page<Training> findAllByStatusOrderByScore(TrainingStatus status, Pageable pageable);
}

And eventually, I call this method from one of my service class:

trainingRepository.findAllByStatusOrderByScore(status, pageable);

This above line is throwing the exception.

Hope this would be helpful.

**Comment by wilkinsona** [comment]
It's not as helpful as a complete, minimal sample that reproduces the problem. Unfortunately, we don't have time to piece things together from snippets of code, particularly when it's not even clear that there's a bug in Spring Boot (this could be a Spring Data problem).

If you'd like us to spend some time trying to find where the problem is, please spend some time providing a sample that reproduces the problem.

**Comment by ranadeepak** [comment]
Yeah, there are chances that its a Spring Data issue, let me drill down a bit more, If needed, I will get back to you.

Thanks!

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by ranadeepak** [comment]
Hey,
The issue is at spring-data-monogodb end. So I have a workaround for now. So we surely close this thread!
