### ISSUE TITLE
Provide exclude support for test auto-configuration

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#6809]
See http://stackoverflow.com/questions/39253152/how-to-exclude-disable-a-specific-auto-configuration-in-spring-boot-1-4-0-for-d/39253304#39253304 for background. We ideally need a way to opt out of imported auto-configuration for tests.

**Comment by michael-simons** [comment]
As discovered in #7600 not working at the moment, see attached project:
[exclude_test.zip](https://github.com/spring-projects/spring-boot/files/678513/exclude_test.zip)

Test is the same as in `ImportAutoConfigurationImportSelectorTests`, excludes Thymeleaf:

```java
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.ImportAutoConfiguration;
import org.springframework.boot.autoconfigure.thymeleaf.ThymeleafAutoConfiguration;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.ApplicationContext;
import org.springframework.test.context.junit4.SpringRunner;

@RunWith(SpringRunner.class)
public class F {

	@Autowired
	private ApplicationContext context;

	@Test
	public void testContextLoads() throws Exception {
		Assert.assertTrue(true);
	}

	@TestConfiguration
	@ImportAutoConfiguration(exclude = ThymeleafAutoConfiguration.class)
	static class Config {

	}
}
```

failure is:
Caused by: java.lang.IllegalStateException: The following classes could not be excluded because they are not auto-configuration classes:
	- org.springframework.boot.autoconfigure.thymeleaf.ThymeleafAutoConfiguration

	at org.springframework.boot.autoconfigure.EnableAutoConfigurationImportSelector.checkExcludedClasses(EnableAutoConfigurationImportSelector.java:172)
	at org.springframework.boot.autoconfigure.EnableAutoConfigurationImportSelector.selectImports(EnableAutoConfigurationImportSelector.java:89)
	at org.springframework.context.annotation.ConfigurationClassParser.processDeferredImportSelectors(ConfigurationClassParser.java:474)
	... 39 common frames omitted
