### ISSUE TITLE
Under load LogbackLoggingSystem fails with java.io.IOException: Stream Closed when refreshing the Spring Context

### ISSUE THREAD

**Issue by davidmelia** [spring-projects/spring-boot#6831]
Hi,

When using Spring Boot 1.4 & Spring Cloud Brixton.SR5 and POSTing to the /refresh actuator endpoint under load you get the following error:

```
ERROR in c.q.l.c.recovery.ResilientFileOutputStream@862013521 - IO failure while writing to file [app.log] java.io.IOException: Stream Closed
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:152)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:72)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:50)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:106)
	at org.springframework.boot.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:289)
	at org.springframework.boot.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:262)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:231)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:207)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:121)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:68)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:335)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
	at org.springframework.cloud.context.refresh.ContextRefresher.addConfigFilesToEnvironment(ContextRefresher.java:67)
	at org.springframework.cloud.context.refresh.ContextRefresher.refresh(ContextRefresher.java:53)
	at org.springframework.cloud.endpoint.RefreshEndpoint.refresh(RefreshEndpoint.java:46)
	at org.springframework.cloud.endpoint.RefreshEndpoint.invoke(RefreshEndpoint.java:52)
```

I have created a bitbucket example https://bitbucket.org/davidmelia/spring-boot-refresh-logback-bug

1. Check out https://bitbucket.org/davidmelia/spring-boot-refresh-logback-bug as a maven project
1. Run the boot app
2. Run the com.example.StressApp main method which stresses the app and gets log generation going.
3. Run curl -X POST http://localhost:8080/refresh     (the error can sometimes be immediate but you may have to do up to 15 times to get it)

Thanks

P.S. As the error seems to originate in a Spring Boot Class (LogbackLoggingSystem) I wasn't sure if to raise this with the Spring Cloud team or yourself - I can move it if needs be :-)

**Comment by philwebb** [comment]
I think it's probably a Spring Cloud issue, I've opened https://github.com/spring-cloud/spring-cloud-commons/issues/128. I'll close this one for now but we can reopen if it ends up being our fault.

**Comment by bin01** [comment]
Seeing this same issue when we integrate using Consul. Is there a workaround for this fix?

**Comment by spencergibb** [comment]
@bin01 this issue is closed and had been relocated. See above.

**Comment by bin01** [comment]
@spencergibb Sorry was going through different issues related to this and finally ended up posting here.
