### ISSUE TITLE
Customising DispatcherServlet's mapping using a ServletRegistrationBean breaks error pages and default ignored paths

### ISSUE THREAD

**Issue by nick-pww** [spring-projects/spring-boot#6877]
Using spring boot 1.4 it seems that `ErrorMvcAutoConfiguration` fails to correctly see response codes from Spring Security (and other areas) correctly. With this enabled, we always get 404 responses instead of the required 401 or 403 or even 500 responses back.

Sample config below:

``` java
    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http
            .formLogin().loginProcessingUrl(RemoteAuthFilter.DEFAULT_PROCESSING_URL)
                .and()
                .csrf().disable()
                .authorizeRequests()                
                .anyRequest().authenticated()
                .and()
                .addFilterAfter(authFilter(), JwtPreAuthFilter.class)
                .addFilter(jwtAuthFilter())
                .exceptionHandling().authenticationEntryPoint(authEntryPoint())
                .and()
                .sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS);
    }

    @Bean
    public AuthenticationEntryPoint authEntryPoint() {
        return new Http403ForbiddenEntryPoint();
    }
```

With this setup, anytime we access a restricted page with out being logged in a 404 is returned. Also, whenever authorization fails we get 404 as well. The logs show that everything is processing correctly:

For not being authenticated we see:

```
2016-09-13 10:43:46.190 DEBUG 27668 --- [io-13080-exec-1] o.s.s.w.a.ExceptionTranslationFilter     : Access is denied (user is anonymous); redirecting to authentication entry point
```

and for auth failiures we see:

```
2016-09-13 10:49:28.570 DEBUG 27668 --- [io-13080-exec-4] .a.SimpleUrlAuthenticationFailureHandler : No failure URL set, sending 401 Unauthorized error
```

However, both result in seeing 404 response similar to:

```
-> % curl -v http://localhost:13080/spring/env
*   Trying ::1...
* Connected to localhost (::1) port 13080 (#0)
> GET /spring/env HTTP/1.1
> Host: localhost:13080
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 404
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< Content-Length: 0
< Date: Tue, 13 Sep 2016 14:39:00 GMT
<
* Connection #0 to host localhost left intact
```

(yes, dispatcher servlet is mapped to `/spring`)

**Comment by snicoll** [comment]
@nick-pww there's no such thing as a `{code}` macro here. I've fixed your description.

**Comment by nick-pww** [comment]
@snicoll Yes, sorry, was trying to fix, but you were editing at the same time. :)

**Comment by nick-pww** [comment]
Also, just to confirm the work around, as soon as I add:

```
@SpringBootApplication(exclude = {ErrorMvcAutoConfiguration.class})
```

everything works as expected with 401 and 403 responses being returned.

**Comment by snicoll** [comment]
The 404 is most probably an attempt to resolve the error page. You should have something in your logs that tells it couldn't resolve the error page, hence the 404. 

That kind of question is better suited for stackoverflow anyway. Can you please share a sample that reproduce the problem so that we can confirm this is the problem?

**Comment by nick-pww** [comment]
@snicoll there is nothing in the logs about the error page. I do not have one, but was under the impression that spring-boot provides a default one out of the box. Here's the complete log output for this (access denied exception in this case)
```
2016-09-13 11:27:26.784 DEBUG 13475 --- [io-13080-exec-1] o.s.s.access.vote.AffirmativeBased       : Voter: org.springframework.security.web.access.expression.WebExpressionVoter@71810faa, returned: -1                                                          [45/9010]
2016-09-13 11:27:26.784 DEBUG 13475 --- [io-13080-exec-1] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'authorizationAuditListener'
2016-09-13 11:27:26.784 DEBUG 13475 --- [io-13080-exec-1] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'delegatingApplicationListener'
2016-09-13 11:27:26.785 DEBUG 13475 --- [io-13080-exec-1] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'auditListener'
2016-09-13 11:27:26.785 DEBUG 13475 --- [io-13080-exec-1] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'delegatingApplicationListener'
2016-09-13 11:27:26.785 DEBUG 13475 --- [io-13080-exec-1] o.s.b.a.audit.listener.AuditListener     : AuditEvent [timestamp=Tue Sep 13 11:27:26 EDT 2016, principal=anonymousUser, type=AUTHORIZATION_FAILURE, data={type=org.springframework.security.access.AccessDeniedEx
ception, message=Access is denied}]
2016-09-13 11:27:26.790 DEBUG 13475 --- [io-13080-exec-1] o.s.s.w.a.ExceptionTranslationFilter     : Access is denied (user is anonymous); redirecting to authentication entry point

org.springframework.security.access.AccessDeniedException: Access is denied
        at org.springframework.security.access.vote.AffirmativeBased.decide(AffirmativeBased.java:84) ~[spring-security-core-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:233) ~[spring-security-core-4.1.1.RELEASE.jar:4.1.1.RELEASE]
.
.
2016-09-13 11:27:26.792 DEBUG 13475 --- [io-13080-exec-1] o.s.s.w.a.ExceptionTranslationFilter     : Calling Authentication entry point.
2016-09-13 11:27:26.792 DEBUG 13475 --- [io-13080-exec-1] o.s.s.w.a.Http403ForbiddenEntryPoint     : Pre-authenticated entry point called. Rejecting access
2016-09-13 11:27:26.792 DEBUG 13475 --- [io-13080-exec-1] o.s.s.w.header.writers.HstsHeaderWriter  : Not injecting HSTS header since it did not match the requestMatcher org.springframework.security.web.header.writers.HstsHeaderWriter$SecureRequestMatcher@7601b11a
2016-09-13 11:27:26.793 DEBUG 13475 --- [io-13080-exec-1] s.s.w.c.SecurityContextPersistenceFilter : SecurityContextHolder now cleared, as request processing completed
2016-09-13 11:27:26.793 DEBUG 13475 --- [io-13080-exec-1] o.s.b.w.f.OrderedRequestContextFilter    : Cleared thread-bound request context: org.apache.catalina.connector.RequestFacade@71827be5
```

This is with DEBUG on `org.springframework`. I would expect at least the generic white label page here as nothing else is provided configuration wise. I'll see if I can get a sample project, but probably wont be today.

**Comment by nick-pww** [comment]
Think I found the root cause. Because I have the dispatcher servlet at non-default location, it's failing to find the error page:
```
    @Bean
	public ServletRegistrationBean dispatcherRegistration(DispatcherServlet dispatcherServlet) {
		ServletRegistrationBean registration = new ServletRegistrationBean(dispatcherServlet);
		registration.addUrlMappings("/spring/*");
		return registration;
	}
```

Feel like this is a pretty standard setting, but don't see anywhere to update this `/error` mapping. If I change the mapping back to just "/*" it works, but can't do that due to other requirements.

**Comment by philwebb** [comment]
@nick-pww I have a feeling you might want to use the `server.servlet-path` property rather than redefining the registration bean.

A sample would really help us track down what's going on.

**Comment by nick-pww** [comment]
[sample.tar.gz](https://github.com/spring-projects/spring-boot/files/474621/sample.tar.gz)

Quick project that highlights the issue. Run with no properties and it works fine, set servlet.path=/anythingelse and it will break the error pages.

`/test/ok` for working response in any configuration
`/test/error` to force error, but still get a 404 when servlet path is moved.

**Comment by nick-pww** [comment]
Oh, also, was unaware of the server.servlet-path property. That will probably work just fine (haven't tested yet), but would still be nice to get correct response codes back in the above case even if the whitelabel page does not work. Not sure how feasible that is though.

Thanks for the tip and the help!

**Comment by wilkinsona** [comment]
@nick-pww Sorry for the delay and thanks for the sample.

As suspected above, the problem is with the error pages. There's a disconnect between your custom registration of the dispatcher servlet and the code that configures the error pages. The former changes the dispatcher servlet's mapping and the latter is not aware of the change. As a result, the error page is registered at `/error` when it should have been registered at `/spring/error`.

Further investigation shows that, when Spring Security is in used, the default ignored paths are also configured incorrectly and CSS, JavaScript etc becomes secured by default. This is because `ServerProperties` is used to determine the complete ignored paths and it's unaware that the mapping has been customised.

As suggested above by @philwebb, setting `server.servlet-path` avoids these problems.

I agree it'd be nice if what you're doing worked, but it's not entirely straightforward. We use an (undocumented) specific name for the dispatcher servlet's registration. If you use this name for your registration bean then that would give us an opportunity to inspect its URL mappings. We'd then need to update `ErrorPageCustomizer`, `IgnoredPathsWebSecurityConfigurerAdapter`, and anything else that's affected to use a path that's determined by looking at the registration rather than whatever's in server properties.

Even without the use of the particular name for the registration bean, things might improve in 2.0 when `ServletRegistrationBean` will become generic (#7666).

**Comment by nick-pww** [comment]
Thanks for the updates and further explanation @wilkinsona 
The work around from @philwebb did indeed solve the problem for us, sorry for not reporting that earlier on.

**Comment by wilkinsona** [comment]
We've discussed this and it's not something that we think is worth tackling. If properties are used where they're available then the problem can be avoided.

**Comment by nick-pww** [comment]
@wilkinsona Makes sense to me. I believe I was unaware of this property when I initially did the setup, and haven't had any issues since with actually setting/using said property.
