### ISSUE TITLE
v1.4.0.RELEASE has hidden dependency on tomcat-juli 

### ISSUE THREAD

**Issue by abhijitsarkar** [spring-projects/spring-boot#6890]
Using Spring Cloud. After upgrading to Boot v1.4.0.RELEASE and Spring 4.3.2.RELEASE, the app wouldn't start without an explicit runtime dependency declared on `org.apache.tomcat:tomcat-juli`.

Stacktrace below, with proprietary package name replaced by xxx

```
org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'servletContainer' defined in xxx.cloud.gateway.GatewayApp: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.context.embedded.EmbeddedServletContainerFactory]: Factory method 'servletContainer' threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/juli/logging/LogFactory
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:137) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:535) ~[spring-context-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:369) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:313) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134) [spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
	at xxx.cloud.gateway.GatewayApp.main(GatewayApp.java:37) [classes!/:2.2.0-SNAPSHOT-b0-r0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [gateway-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT-b0-r0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [gateway-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT-b0-r0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [gateway-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT-b0-r0]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58) [gateway-2.2.0-SNAPSHOT.jar:2.2.0-SNAPSHOT-b0-r0]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'servletContainer' defined in xxx.cloud.gateway.GatewayApp: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.context.embedded.EmbeddedServletContainerFactory]: Factory method 'servletContainer' threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/juli/logging/LogFactory
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599) ~[spring-beans-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1123) ~[spring-beans-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1018) ~[spring-beans-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510) ~[spring-beans-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.getEmbeddedServletContainerFactory(EmbeddedWebApplicationContext.java:199) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:162) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:134) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
	... 15 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.context.embedded.EmbeddedServletContainerFactory]: Factory method 'servletContainer' threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/juli/logging/LogFactory
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
	... 26 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/apache/juli/logging/LogFactory
	at org.apache.catalina.util.LifecycleBase.<clinit>(LifecycleBase.java:37) ~[tomcat-embed-core-8.0.33.jar!/:8.0.33]
```

**Comment by philwebb** [comment]
Check the version on Tomcat that you're using. We expect Tomcat 8.5.4 or higher by default now. If you want to use an older version you'll need to add `tomcat-juli` as [documented in the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.4-Release-Notes#downgrading-tomcat)

**Comment by abhijitsarkar** [comment]
I don't have an explicit Tomcat dependency, it's pulled in in by Boot. Why'd v1.4 pull in an older Tomcat?

**Comment by philwebb** [comment]
It shouldn't. What does `mvn dependency:tree` show?

**Comment by abhijitsarkar** [comment]
> What does `mvn dependency:tree` show?

Gradle. `./gradlew -q dependencies --configuration runtime`, and relevant portion shown below.

```
+--- org.springframework.cloud:spring-cloud-starter: -> 1.1.1.RELEASE
|    +--- org.springframework.boot:spring-boot-starter:1.3.5.RELEASE -> 1.4.0.RELEASE
|    |    +--- org.springframework.boot:spring-boot:1.4.0.RELEASE
|    |    |    +--- org.springframework:spring-core:4.3.2.RELEASE
|    |    |    |    \--- commons-logging:commons-logging:1.2
|    |    |    \--- org.springframework:spring-context:4.3.2.RELEASE
|    |    |         +--- org.springframework:spring-aop:4.3.2.RELEASE
|    |    |         |    +--- org.springframework:spring-beans:4.3.2.RELEASE
|    |    |         |    |    \--- org.springframework:spring-core:4.3.2.RELEASE (*)
|    |    |         |    \--- org.springframework:spring-core:4.3.2.RELEASE (*)
|    |    |         +--- org.springframework:spring-beans:4.3.2.RELEASE (*)
|    |    |         +--- org.springframework:spring-core:4.3.2.RELEASE (*)
|    |    |         \--- org.springframework:spring-expression:4.3.2.RELEASE
|    |    |              \--- org.springframework:spring-core:4.3.2.RELEASE (*)
|    |    +--- org.springframework.boot:spring-boot-autoconfigure:1.4.0.RELEASE
|    |    |    \--- org.springframework.boot:spring-boot:1.4.0.RELEASE (*)
|    |    +--- org.springframework.boot:spring-boot-starter-logging:1.4.0.RELEASE
|    |    |    +--- ch.qos.logback:logback-classic:1.1.7
|    |    |    |    +--- ch.qos.logback:logback-core:1.1.7
|    |    |    |    \--- org.slf4j:slf4j-api:1.7.20 -> 1.7.21
|    |    |    +--- org.slf4j:jcl-over-slf4j:1.7.21
|    |    |    |    \--- org.slf4j:slf4j-api:1.7.21
|    |    |    +--- org.slf4j:jul-to-slf4j:1.7.21
|    |    |    |    \--- org.slf4j:slf4j-api:1.7.21
|    |    |    \--- org.slf4j:log4j-over-slf4j:1.7.21
|    |    |         \--- org.slf4j:slf4j-api:1.7.21
|    |    +--- org.springframework:spring-core:4.3.2.RELEASE (*)
|    |    \--- org.yaml:snakeyaml:1.17 -> 1.16
|    +--- org.springframework.cloud:spring-cloud-context:1.1.1.RELEASE
|    |    \--- org.springframework.security:spring-security-crypto:4.0.4.RELEASE
|    +--- org.springframework.cloud:spring-cloud-commons:1.1.1.RELEASE
|    |    \--- org.springframework.security:spring-security-crypto:4.0.4.RELEASE
|    \--- org.springframework.security:spring-security-rsa:1.0.1.RELEASE
|         +--- org.springframework.security:spring-security-crypto:3.2.7.RELEASE -> 4.0.4.RELEASE
|         +--- org.springframework:spring-core:4.1.6.RELEASE -> 4.3.2.RELEASE (*)
|         \--- org.bouncycastle:bcpkix-jdk15on:1.47
|              \--- org.bouncycastle:bcprov-jdk15on:1.47
+--- org.springframework.boot:spring-boot-starter-web: -> 1.4.0.RELEASE
|    +--- org.springframework.boot:spring-boot-starter:1.4.0.RELEASE (*)
|    +--- org.springframework.boot:spring-boot-starter-tomcat:1.4.0.RELEASE
|    |    +--- org.apache.tomcat.embed:tomcat-embed-core:8.5.4 -> 8.0.33
|    |    +--- org.apache.tomcat.embed:tomcat-embed-el:8.5.4 -> 8.0.33
|    |    \--- org.apache.tomcat.embed:tomcat-embed-websocket:8.5.4 -> 8.0.33
|    |         \--- org.apache.tomcat.embed:tomcat-embed-core:8.0.33

```

I see that something is downgrading Tomcat, but from the above tree, there's no way to tell what.

**Comment by wilkinsona** [comment]
Rather than using `spring-cloud-starter-parent` you should use `spring-cloud-dependencies`:

```groovy
dependencyManagement {
        imports {
                mavenBom "org.springframework.cloud:spring-cloud-dependencies:Brixton.SR5"
        }
}
```

If you generate a project using start.spring.io, it'll produce the correct configuration for you.
