### ISSUE TITLE
FailureAnalyzer inaccurate when SSL keystore password is incorrect

### ISSUE THREAD

**Issue by btiernay** [spring-projects/spring-boot#6896]
The following log snippet shows that when an SSL exception is thrown, the FailureAnalyzer reports:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Embedded servlet container failed to start. Port 443 was already in use.

Action:

Identify and stop the process that's listening on port 443 or configure this application to listen on another port.
```

However, the port is free but the root cause is a bad keystore password:

```
2016-09-15 10:41:00,701 [WrapperSimpleAppMain] ERROR o.a.c.h.Http11NioProtocol - Failed to start end point associated with ProtocolHandler [https-jsse-nio-443]
java.lang.IllegalArgumentException: java.io.IOException: Keystore was tampered with, or password was incorrect
       	at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:103)
       	at org.apache.tomcat.util.net.AbstractJsseEndpoint.initialiseSsl(AbstractJsseEndpoint.java:81)
       	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:245)
       	at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:874)
       	at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:573)
       	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1035)
       	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:152)
       	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:225)
       	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.addPreviouslyRemovedConnectors(TomcatEmbeddedServletContainer.java:234)
       	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:179)
       	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:297)
       	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:145)
       	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544)
       	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
       	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
       	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:369)
       	at org.springframework.boot.SpringApplication.run(SpringApplication.java:313)
       	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
       	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
       	at org.icgc.dcc.dev.server.ServerMain.main(ServerMain.java:31)
       	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       	at java.lang.reflect.Method.invoke(Method.java:498)
       	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
       	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
       	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
       	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58)
       	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       	at java.lang.reflect.Method.invoke(Method.java:498)
       	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:290)
       	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Keystore was tampered with, or password was incorrect
       	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:780)
       	at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:56)
       	at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224)
       	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70)
       	at java.security.KeyStore.load(KeyStore.java:1445)
       	at org.apache.tomcat.util.net.SSLUtilBase.getStore(SSLUtilBase.java:136)
       	at org.apache.tomcat.util.net.SSLHostConfigCertificate.getCertificateKeystore(SSLHostConfigCertificate.java:187)
       	at org.apache.tomcat.util.net.jsse.JSSEUtil.getKeyManagers(JSSEUtil.java:189)
       	at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:101)
       	... 33 common frames omitted
Caused by: java.security.UnrecoverableKeyException: Password verification failed
       	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:778)
       	... 41 common frames omitted
2016-09-15 10:41:00,703 [WrapperSimpleAppMain] ERROR o.a.c.c.StandardService - Failed to start connector [Connector[HTTP/1.1-443]]
org.apache.catalina.LifecycleException: Failed to start component [Connector[HTTP/1.1-443]]
       	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:158)
       	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:225)
       	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.addPreviouslyRemovedConnectors(TomcatEmbeddedServletContainer.java:234)
       	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:179)
       	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:297)
       	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:145)
       	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544)
       	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
       	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
       	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:369)
       	at org.springframework.boot.SpringApplication.run(SpringApplication.java:313)
       	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
       	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
       	at org.icgc.dcc.dev.server.ServerMain.main(ServerMain.java:31)
       	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       	at java.lang.reflect.Method.invoke(Method.java:498)
       	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
       	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
       	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
       	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58)
       	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       	at java.lang.reflect.Method.invoke(Method.java:498)
       	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:290)
       	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.catalina.LifecycleException: service.getName(): "Tomcat";  Protocol handler start failed
       	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1042)
       	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:152)
       	... 27 common frames omitted
Caused by: java.lang.IllegalArgumentException: java.io.IOException: Keystore was tampered with, or password was incorrect
       	at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:103)
       	at org.apache.tomcat.util.net.AbstractJsseEndpoint.initialiseSsl(AbstractJsseEndpoint.java:81)
       	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:245)
       	at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:874)
       	at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:573)
       	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1035)
       	... 28 common frames omitted
Caused by: java.io.IOException: Keystore was tampered with, or password was incorrect
       	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:780)
       	at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:56)
       	at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224)
       	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70)
       	at java.security.KeyStore.load(KeyStore.java:1445)
       	at org.apache.tomcat.util.net.SSLUtilBase.getStore(SSLUtilBase.java:136)
       	at org.apache.tomcat.util.net.SSLHostConfigCertificate.getCertificateKeystore(SSLHostConfigCertificate.java:187)
       	at org.apache.tomcat.util.net.jsse.JSSEUtil.getKeyManagers(JSSEUtil.java:189)
       	at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:101)
       	... 33 common frames omitted
Caused by: java.security.UnrecoverableKeyException: Password verification failed
       	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:778)
       	... 41 common frames omitted
2016-09-15 10:41:00,712 [WrapperSimpleAppMain] INFO  o.a.c.h.Http11NioProtocol - Pausing ProtocolHandler ["https-jsse-nio-443"]
2016-09-15 10:41:00,712 [WrapperSimpleAppMain] INFO  o.a.c.c.StandardService - Stopping service Tomcat
2016-09-15 10:41:00,720 [WrapperSimpleAppMain] INFO  o.a.c.u.LifecycleBase - The stop() method was called on component [StandardServer[-1]] after stop() had already been called. The second call will be ignored.
2016-09-15 10:41:00,720 [WrapperSimpleAppMain] INFO  o.a.c.h.Http11NioProtocol - Stopping ProtocolHandler ["https-jsse-nio-443"]
2016-09-15 10:41:00,721 [WrapperSimpleAppMain] INFO  o.a.c.h.Http11NioProtocol - Destroying ProtocolHandler ["https-jsse-nio-443"]
2016-09-15 10:41:00,732 [WrapperSimpleAppMain] INFO  o.s.b.a.l.AutoConfigurationReportLoggingInitializer -

Error starting ApplicationContext. To display the auto-configuration report enable debug logging (start with --debug)


2016-09-15 10:41:00,744 [WrapperSimpleAppMain] ERROR o.s.b.d.LoggingFailureAnalysisReporter -

***************************
APPLICATION FAILED TO START
***************************

Description:

Embedded servlet container failed to start. Port 443 was already in use.

Action:

Identify and stop the process that's listening on port 443 or configure this application to listen on another port.
```

**Comment by wilkinsona** [comment]
Thanks, @btiernay. I saw this yesterday when battling with the Tomcat 8.5.5 upgrade but forgot to log an issue.

**Comment by wilkinsona** [comment]
I can't see a good way to fix this. The `Connector` is started as a result of a call to `StandardService.addConnector(Connector)`. It swallows any exception that's thrown from `start`. The other places where a `Connector` could be started is in `StandardService.startInternal`. It too swallows any exceptions thrown by the `Connector`. Later on, the only information that we have is that the connector has failed to start. We currently assume that's due to a port clash but it could be any number of things.

Some options I've considered:

- Start the `Connector` before calling `addConnector(Connector)`. This works as the subsequent call to `start` becomes a no-op. However, it does mean that there's a brief period when the `Connector` is started but the service doesn't know about it
- Rather than adding the `Connector`, add a wrapper subclass that delegates every method call to the actual `Connector` and catches and stores any exception throw from its delegate's `start` method. I don't like this option as `Connector` has a _lot_ of methods.
- Call `start` on the `Connector` after calling `addConnector(Connector)` if it's state is `FAILED`. This will hopefully trigger the failure again. I think this'll work but at the cost of the failure being logged twice. 

@markt-asf Is there a better way to tackle this? We'd like to be able to get hold of the exception that caused a `Connector` to fail to start.

**Comment by wilkinsona** [comment]
Interestingly the third option doesn't work. The attempt to start the failed connector does fail, but with a different error. It results in a `java.net.BindException: Address already in use` which tells me that Tomcat has left the socket open despite the start failure. When things are in that state I can connect to the port but HTTP requests hang.

**Comment by markt-asf** [comment]
You might be able to tweak option 3 to call stop() to clean up before calling start() again.
I have a couple of other ideas but I need to dig into the code a little first.

**Comment by wilkinsona** [comment]
I don't think tweaking option 3 will work. `LifecycleBase` already calls `stop()` if `start()` is called and the connector's state is `FAILED`. Even if we could get it to work, it's really a hack and creates the possibility that the start will fail to first time and the restart will succeed. The first failure will log a couple of exceptions that won't actually be a problem. That's likely to cause a lot of confusion.

**Comment by wilkinsona** [comment]
It doesn't look like there's a good solution for this without making API changes in Tomcat. For the time being at least, we'll have to change the exception that's thrown and implement another failure analyzer.
