### ISSUE TITLE
Error : Could not evaluate condition on org.springframework.cloud.netflix.zuul.ZuulConfiguration#routeLocator due to com/netflix/zuul/ZuulFilter not found

### ISSUE THREAD

**Issue by sabarnath** [spring-projects/spring-boot#7024]
Bug report :+1: 
Getting following error while start the spring boot admin server

2016-09-26 18:36:35.108 ERROR 11162 --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: Could not evaluate condition on org.springframework.cloud.netflix.zuul.ZuulConfiguration#routeLocator due to com/netflix/zuul/ZuulFilter not found. Make sure your own configuration does not rely on that class. This can also happen if you are @ComponentScanning a springframework package (e.g. if you put a @ComponentScan in the default package by mistake)
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:55) ~[spring-boot-autoconfigure-1.4.1.RELEASE.jar!/:1.4.1.RELEASE]
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:102) ~[spring-context-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:178) ~[spring-context-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]

**Comment by sabarnath** [comment]
I have been using following dependencies 

spring boot parent version : 1.4.1.RELEASE
spring-boot-admin-server : 1.4.1
spring-boot-admin-server-ui : 1.4.1
spring-boot-admin-starter-client - 1.4.1

**Comment by wilkinsona** [comment]
@sabarnath Spring Boot Admin is a separate, third-party project. Its issues are tracked [here](https://github.com/codecentric/spring-boot-admin/issues).
