### ISSUE TITLE
the issue for devtools

### ISSUE THREAD

**Issue by kevinmonster911** [spring-projects/spring-boot#7169]
I used mybatis and spring boot with gradle to build web appliction.
I can run "gradle clean && gradle build  && gradle bootRun" successfully, but after added a devtools dependency with compile scope as following:
compile("org.springframework.boot:spring-boot-devtools"
gradle build  will be failed. the detail message as following
```
 Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userDomain': Unsatisfied dependency expressed through field 'userDao'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userDao' defined in file [/Users/kevinmonster/workspace/cz/mygroovy/build/classes/main/hello/dao/UserDao.class]: Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property 'mapperHelper' of bean class [org.mybatis.spring.mapper.MapperFactoryBean]: Bean property 'mapperHelper' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
19:18:05.567 [DEBUG] [TestEventLogger]          at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:569)
19:18:05.567 [DEBUG] [TestEventLogger]          at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
19:18:05.567 [DEBUG] [TestEventLogger]          at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:349)
19:18:05.567 [DEBUG] [TestEventLogger]          at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1219)
19:18:05.567 [DEBUG] [TestEventLogger]          at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
19:18:05.567 [DEBUG] [TestEventLogger]          at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
19:18:05.567 [DEBUG] [TestEventLogger]          at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:325)
19:18:05.567 [DEBUG] [TestEventLogger]          at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
19:18:05.567 [DEBUG] [TestEventLogger]          at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:207)
19:18:05.567 [DEBUG] [TestEventLogger]          at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1128)
19:18:05.567 [DEBUG] [TestEventLogger]          at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1056)
19:18:05.567 [DEBUG] [TestEventLogger]          at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:566)
19:18:05.567 [DEBUG] [TestEventLogger]          ... 63 common frames omitted
19:18:05.567 [DEBUG] [TestEventLogger]     Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userDao' defined in file [/Users/kevinmonster/workspace/cz/mygroovy/build/classes/main/hello/dao/UserDao.class]: Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property 'mapperHelper' of bean class [org.mybatis.spring.mapper.MapperFactoryBean]: Bean property 'mapperHelper' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
```

my project github address is git@github.com:kevinmonster911/gradleboot.git

**Comment by snicoll** [comment]
@kevinmonster911 mybatis support is not handled here. Please report that issue [in their issue tracker](https://github.com/mybatis/spring-boot-starter) and we'll see where that leads. If it happens to be a spring boot issue, we'll reopen this issue. Thank you.
