### ISSUE TITLE
Spring boot (1.4.1.RELEASE) loader cannot find classnames with cyrillic characters

### ISSUE THREAD

**Issue by olimpiks** [spring-projects/spring-boot#7202]
```java
@SpringBootApplication
public class App implements ApplicationRunner {

//    public class Pojo_english_spring {} //ok
    public class Pojo_russian_весна {} //fail

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }

    @Override
    public void run(ApplicationArguments args) throws Exception {
    }
}
```

```
...
java.io.FileNotFoundException: JAR entry com/acme/App$Pojo_russian_весна.class not found in /tmp/test/target/spring-boot-app-0.0.1-SNAPSHOT.jar!/BOOT-INF/classes
	at org.springframework.boot.loader.jar.JarURLConnection.throwFileNotFound(JarURLConnection.java:180) ~[spring-boot-app-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.jar.JarURLConnection.connect(JarURLConnection.java:102) ~[spring-boot-app-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.jar.JarURLConnection.getInputStream(JarURLConnection.java:166) ~[spring-boot-app-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at org.springframework.core.io.UrlResource.getInputStream(UrlResource.java:169) ~[spring-core-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:50) ~[spring-core-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:98) ~[spring-core-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
	at org.springframework.core.type.classreading.CachingMetadataReaderFactory.getMetadataReader(CachingMetadataReaderFactory.java:102) ~[spring-core-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:279) ~[spring-context-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
	... 26 common frames omitted
```

With spring-boot:1.3.8.RELEASE - it works fine.

**Comment by olimpiks** [comment]
Created a [pull request](https://github.com/spring-projects/spring-boot-issues/pull/57) with sample application for this issue.

**Comment by wilkinsona** [comment]
There's a bug in `AsciiBytes`. It's `hashCode` method should be compatible with `String`'s but it isn't in this case. This test fails:

```java
@Test
public void hashCodeSameAsStringWithCyrillicCharacteres() throws Exception {
	String s = "com/example/Pojo_russian_весна.class";
	AsciiBytes a = new AsciiBytes(s);
	assertThat(s.hashCode()).isEqualTo(a.hashCode());
}
```
