### ISSUE TITLE
MalformedURLException when using undertow with server.context-path

### ISSUE THREAD

**Issue by kuhnroyal** [spring-projects/spring-boot#7212]
With Spring-boot 1.4.1 + Undertow, when setting `server.context-path=/foo` and requesting `HOST/foo` the following exception is thrown.
Undertow seems to add a trailing slash only after the `Handler.getRootJarFileFromUrl(Handler.java:147)` is called. The path parameter at this point is an empty string instead of `/`.

Adding a `null/empty` check and replacing it with `/` at https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/context/embedded/undertow/UndertowEmbeddedServletContainerFactory.java#L617 would fix this. 

``` java
java.lang.RuntimeException: java.net.MalformedURLException: Jar URL does not contain !/ separator                                                                                                                                              
        at io.undertow.servlet.handlers.ServletPathMatches.getServletHandlerByPath(ServletPathMatches.java:121)                                                                                                                                
        at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:127)                                                                                                                                    
        at io.undertow.server.handlers.HttpContinueReadHandler.handleRequest(HttpContinueReadHandler.java:65)                                                                                                                                  
        at io.undertow.server.handlers.encoding.EncodingHandler.handleRequest(EncodingHandler.java:72)                                                                                                                                         
        at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:94)                                                                                                                                                          
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:207)                                                                                                                                                               
        at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:233)                                                                                                                        
        at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:131)                                                                                                                                            
        at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:145)                                                    
        at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:92)                                                                                                                                             
        at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:51)                                                                                                                                             
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)                                                                                    
        at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291)                                                                                                                                                                 
        at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286)                                                                                                                                                                 
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)                                                                   
        at org.xnio.nio.QueuedNioTcpServer$1.run(QueuedNioTcpServer.java:128)                                                                                                                                                                  
        at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:580)                                                                                                                                                                            
        at org.xnio.nio.WorkerThread.run(WorkerThread.java:464)                                                                                                         
Caused by: java.net.MalformedURLException: Jar URL does not contain !/ separator                                                                                                                                                               
        at org.springframework.boot.loader.jar.Handler.getRootJarFileFromUrl(Handler.java:147)                                                                                                                                                 
        at org.springframework.boot.loader.jar.Handler.openConnection(Handler.java:91)                                                                 
        at java.net.URL.openConnection(URL.java:979)                                                                                                                                                                                           
        at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory$JarResourceManager.getResource(UndertowEmbeddedServletContainerFactory.java:622)                                                         
        at io.undertow.servlet.handlers.ServletPathMatches.getServletHandlerByPath(ServletPathMatches.java:91)                                                          
        ... 17 common frames omitted 
```

**Comment by wilkinsona** [comment]
With a context path of `/foo`, a request to `HOST/foo` should redirect to `HOST/foo/`:

```
$ curl -v localhost:8080/foo
*   Trying ::1...
* Connected to localhost (::1) port 8080 (#0)
> GET /foo HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.46.0
> Accept: */*
>
< HTTP/1.1 302 Found
< Connection: keep-alive
< Location: http://localhost:8080/foo/
< Content-Length: 0
< Date: Mon, 24 Oct 2016 12:06:53 GMT
<
* Connection #0 to host localhost left intact
```

If that's not happening, then something else is wrong. Can you please provide a small sample that reproduces the behaviour you have described?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by kuhnroyal** [comment]
I can not reproduce this in a new project. I have however 2 bigger projects with this behavior.
I will reopen this if I manage to reproduce it in a blank project.
