### ISSUE TITLE
Problem when using relative path in Common Document Root of servlet container

### ISSUE THREAD

**Issue by JavaSteven** [spring-projects/spring-boot#7223]
The method `getCommonDocumentRoot()` in `AbstractEmbeddedServletContainerFactory` seems incorrect. 
It uses the `new File()` constructor which uses java working directory and then returns the absolute path which uses java user directory. See [java bug](http://bugs.java.com/bugdatabase/view_bug.do;:YfiG?bug_id=4483097) for more info.
In my case this results in a different absolute path returning (returns `_/rootdir/src/main/webapp_` instead of `_/rootdir/subproject/src/main/webapp_`).
I'm using spring-boot version 1.4.0.RELEASE.

I receive following error on startup of embedded tomcat:

```
java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:911)
    at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:890)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:152)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1403)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1393)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:158)
    ... 6 common frames omitted
Caused by: org.apache.catalina.LifecycleException: Failed to start component [org.apache.catalina.webresources.StandardRoot@67f944fa]
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:158)
    at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:4831)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4963)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:152)
    ... 6 common frames omitted
Caused by: java.lang.IllegalArgumentException: The main resource set specified [_/rootdir/src/main/webapp_] is not valid
    at org.apache.catalina.webresources.StandardRoot.createMainResourceSet(StandardRoot.java:725)
    at org.apache.catalina.webresources.StandardRoot.startInternal(StandardRoot.java:686)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:152)
    ... 9 common frames omitted
```

**Comment by wilkinsona** [comment]
@JavaSteven Are you changing the value of the `user.dir` system property and, if so, why?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by JavaSteven** [comment]
@wilkinsona No, I'm not changing the user.dir system property deliberately. I have a gradle multiproject and when I run the gradle bootRun command from the root project I have this problem. However when I run the  same command on the child spring boot project, I have no problems.

**Comment by wilkinsona** [comment]
@JavaSteven Thanks. That behaviour's rather surprising. Can you please provide a small sample that reproduces it?

**Comment by JavaSteven** [comment]
@wilkinsona I've added a little project to https://github.com/JavaSteven/spring-boot-7223
I've found the problem: I set the system properties in the bootRun gradle configuration. I clearly overlooked that one. Is there another way to pass system variables to a gradle bootRun task?

**Comment by wilkinsona** [comment]
Thanks, I can see what's happening now. 

As you've discovered, passing all of one JVM's system properties into another can cause problems. Even if we fixed the specific problem that you've described, I suspect others may then crop up. 

Let's take a step back. What were you trying to achieve by passing in the system properties?

**Comment by JavaSteven** [comment]
@wilkinsona We use it to override some configuration like server.port and spring.datasource properties

**Comment by wilkinsona** [comment]
Thanks. So what you're looking for is #1176. In the meantime, I'd do something like this in your build.gradle:

```groovy
bootRun {
	if (project.hasProperty("bootRunArgs")) {
		args = project.getProperty("bootRunArgs").split(" ") as List
	}
}
```

You can then use the `bootRunArgs` project property to pass command line arguments into your app:

```
gradle -PbootRunArgs="--server.port=9090" bootRun
```

This gives you precise control over what's passed into the app when it's run, rather than blindly copying over all of the system properties.
