### ISSUE TITLE
Problem importing into Eclipse Mars

### ISSUE THREAD

**Issue by marioja** [spring-projects/spring-boot#7231]
I tried to import the Spring Boot into eclipse Mars using the Eclipse Installer as documented but I encountered an error:
- After clicking Finish and the new Eclipse Mars installation starts with the ws workspace, a long build process takes place.
- In the Eclipse Updater window, the following appears:

```
29KB/31KB (91%) https://repo.maven.apache.org/maven2/de/gesellix/unix-socket-factory/2015-01-27T15-02-14/unix-socket-factory-2015-01-27T15-02-14.jar
31KB/31KB (98%) https://repo.maven.apache.org/maven2/de/gesellix/unix-socket-factory/2015-01-27T15-02-14/unix-socket-factory-2015-01-27T15-02-14.jar
31KB/31KB (100%) https://repo.maven.apache.org/maven2/de/gesellix/unix-socket-factory/2015-01-27T15-02-14/unix-socket-factory-2015-01-27T15-02-14.jar
Setting classpath containers
Updating configuration for spring-boot-dependencies
Connecting Git team provider.
Updating configuration for spring-boot-parent
Updating configuration for spring-boot-tools
Updating configuration for spring-boot-configuration-processor
ERROR: org.eclipse.m2e.maveneclipse code=-1 NLS missing message: mavenEclipseProjectConfiguratorError in: org.eclipse.m2e.maveneclipse.internal.messages
java.lang.IllegalStateException: Location file C:\Users\mario\git\spring-boot\spring-boot-tools\spring-boot-configuration-processor\C:\Users\mario\git\spring-boot\spring-boot-tools\spring-boot-configuration-processor\..\..\eclipse\org.eclipse.jdt.ui.prefs does not exist
  at org.eclipse.m2e.maveneclipse.handler.additionalconfig.LocationFileParameter.getContent(LocationFileParameter.java:51)
  at org.eclipse.m2e.maveneclipse.handler.additionalconfig.FileParameter.copyToProject(FileParameter.java:64)
  at org.eclipse.m2e.maveneclipse.handler.additionalconfig.FilesParameters.copyFilesToProject(FilesParameters.java:59)
  at org.eclipse.m2e.maveneclipse.handler.additionalconfig.AdditionalConfigConfigurationHandler.handle(AdditionalConfigConfigurationHandler.java:37)
  at org.eclipse.m2e.maveneclipse.handler.SingleParameterConfigurationHandler.handle(SingleParameterConfigurationHandler.java:42)
  at org.eclipse.m2e.maveneclipse.handler.ConfigurationHandlers.handle(ConfigurationHandlers.java:79)
  at org.eclipse.m2e.maveneclipse.MavenEclipseProjectConfigurator.configure(MavenEclipseProjectConfigurator.java:84)`
`  at org.eclipse.m2e.maveneclipse.MavenEclipseProjectConfigurator.configureRawClasspath(MavenEclipseProjectConfigurator.java:66)
  at org.eclipse.m2e.jdt.internal.AbstractJavaProjectConfigurator.invokeJavaProjectConfigurators(AbstractJavaProjectConfigurator.java:176)
  at org.eclipse.m2e.jdt.internal.AbstractJavaProjectConfigurator.configure(AbstractJavaProjectConfigurator.java:132)
  at org.eclipse.m2e.core.project.configurator.AbstractLifecycleMapping.configure(AbstractLifecycleMapping.java:120)
  at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$3.call(ProjectConfigurationManager.java:501)
  at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$3.call(ProjectConfigurationManager.java:1)
  at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
  at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
  at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:494)`
`  at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.configureNewMavenProjects(ProjectConfigurationManager.java:281)
  at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$1.call(ProjectConfigurationManager.java:168)
  at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$1.call(ProjectConfigurationManager.java:1)
  at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)`
`  at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
  at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
  at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1355)
  at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.importProjects(ProjectConfigurationManager.java:136)
  at org.eclipse.oomph.setup.maven.impl.MavenImportTaskImpl.perform(MavenImportTaskImpl.java:344)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3151)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.access$1(SetupTaskPerformer.java:3094)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:4315)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:4309)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.access$0(SetupTaskPerformer.java:4307)`
`  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3085)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3060)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:2960)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:556)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:682)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)`

Took 422 seconds.
There are failed tasks.
Press Back to choose different settings or Cancel to abort.
```

**Comment by wilkinsona** [comment]
No one on the Boot team uses Windows, so you may be the first person to try following the instructions on Windows. It looks like a Windows path problem. This is wrong:

```
C:\Users\mario\git\spring-boot\spring-boot-tools\spring-boot-configuration-processor\C:\Users\mario\git\spring-boot\spring-boot-tools\spring-boot-configuration-processor\..\..\eclipse\org.eclipse.jdt.ui.prefs
```

The correct path is this:

```
C:\Users\mario\git\spring-boot\spring-boot-tools\spring-boot-configuration-processor\..\..\eclipse\org.eclipse.jdt.ui.prefs
```

**Comment by wilkinsona** [comment]
This looks like a bug in https://github.com/philwebb/m2eclipse-maveneclipse to me, specifically the [logic in `LocationFileParameter`](https://github.com/philwebb/m2eclipse-maveneclipse/blob/master/org.eclipse.m2e.maveneclipse/src/org/eclipse/m2e/maveneclipse/handler/additionalconfig/LocationFileParameter.java#L44-L49) which attempts to handle relative paths.

@philwebb Does it make sense to use `new File(location).isAbsolute()` instead of checking for starting with `/` or `\\`?

**Comment by marioja** [comment]
@snicoll Thanks for editing the markup.  I only found out about the Markdown triple backquotes after and I was coming in to correct my mistake.  @philwebb is this going to get fixed or I am the lone windows guy forever (creating Ubuntu VM)?

**Comment by marioja** [comment]
I tried on ubuntu 16.10 and got this error:

```
Fetching content.xml.xz from http://download.eclipse.org/releases/mars/201602261000/
ERROR: org.eclipse.equinox.p2.metadata.repository code=1002 Unable to read repository at file:/home/lmario/.p2/org.eclipse.equinox.p2.repository/cache/-1377987690.
java.io.EOFException
  at java.io.DataInputStream.readFully(DataInputStream.java:197)
  at org.tukaani.xz.rangecoder.RangeDecoder.prepareInputBuffer(Unknown Source)
  at org.tukaani.xz.LZMA2InputStream.decodeChunkHeader(Unknown Source)
  at org.tukaani.xz.LZMA2InputStream.read(Unknown Source)
  at org.tukaani.xz.BlockInputStream.read(Unknown Source)
  at org.tukaani.xz.SingleXZInputStream.read(Unknown Source)
  at org.tukaani.xz.XZInputStream.read(Unknown Source)
  at org.tukaani.xz.XZInputStream.read(Unknown Source)
  at com.sun.org.apache.xerces.internal.impl.XMLEntityManager$RewindableInputStream.read(XMLEntityManager.java:2890)
  at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:674)
  at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:148)
  at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:805)
  at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
  at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
  at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
  at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
  at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryIO$Parser.parse(MetadataRepositoryIO.java:209)
  at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryIO.read(MetadataRepositoryIO.java:63)
  at org.eclipse.equinox.internal.p2.metadata.repository.XZedSimpleMetadataRepositoryFactory.load(XZedSimpleMetadataRepositoryFactory.java:84)
  at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:57)
  at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:768)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.eclipse.oomph.util.ReflectUtil.invokeMethod(ReflectUtil.java:116)
  at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:386)
  at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:193)
  at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager$Metadata.loadRepository(CachingRepositoryManager.java:453)
  at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:96)
  at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:92)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl$RepositoryLoader$Worker.perform(ProfileTransactionImpl.java:1613)
  at org.eclipse.oomph.util.WorkerPool$Worker.run(WorkerPool.java:416)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

Took 13 seconds.
There are failed tasks.
Press Back to choose different settings or Cancel to abort.
```

**Comment by wilkinsona** [comment]
I've never seen that before. It looks like P2 has corrupted its cache somehow. It doesn't, as far as I can tell, have anything to do with Boot's setup configuration so I don't think we'll be able to do anything about it. You could try deleting the cache and having another go.

**Comment by marioja** [comment]
I assumed deleting the cache meant to remove the folder .p2 in my home directory.  I did that and I got the same error.  I noticed in the eclipse installer the icon with two right/left arrows spinning asking for update.  I did the update and it restarted the installer.  Now things are in progress (at least it went way further than before).  Will report back on the Linux result but my problem remains on Windows.

**Comment by wilkinsona** [comment]
> but my problem remains on Windows.

It's worth noting that you don't have to use the Oomph-based setup.

You can get a working environment fairly easily with any Eclipse installation that has M2E installed. It should work out of the box with Spring Tool Suite, for example. Alternatively, if you want to use the Oomph-based setup, you could just remove the [configuration that configures the m2eclipse-maveneclipse plugin](https://github.com/spring-projects/spring-boot/blob/f28fa3e1ab4b8ebc48d290ab68fffb6caaafb3e6/eclipse/spring-boot-project.setup#L66-L67).

In both cases, the resulting setup won't quite be perfect as, for example, you want have our code formatting settings applied automatically, but I'd hope that it's good enough for your purposes.

**Comment by philwebb** [comment]
I'll look at fixing the m2e plugin. I'm also currently working on a better code formatting solution and trying to upgrade to neon.

**Comment by philwebb** [comment]
I've pushed an updated version of the plugin to Bintray. Thanks!
