### ISSUE TITLE
Jackson Errors in /env actuator if Groovy Closures are used.

### ISSUE THREAD

**Issue by robertoschwald** [spring-projects/spring-boot#7242]
When you define a closure in Groovy scripts relevant for the application configuration, Jackson fails in the /env endpoint on GroovyClassLoader$1

This for example occurs in Grails 3.x applications. 

Related Grails issue: https://github.com/grails/grails-core/issues/10279

I tried already to workaround the issue, with no success. See Grails Ticket.

###Expected Behaviour

Jackson does not fail on application.groovy when using the env activator endpoint

###Actual Behaviour

Exception occurs (see above)

###Environment Information

Operating System: OSX 10.12.1
Spring-Boot-Actuator Version: 1.2.7.RELEASE
Groovy Version: 2.4.5
Grails Version: 3.1.13 (also tested with 3.0.10, same problem)
JDK Version: 1.8.0_91 ORACLE

### Stacktrace
```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: 
No serializer found for class groovy.lang.GroovyClassLoader$1 and no properties discovered to
 create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) ) 
(through reference chain: java.util.LinkedHashMap["applicationConfig: 
[classpath:/application.groovy]"]->java.util.LinkedHashMap["grails.gorm.default.mapping"]-
>_run_closure1["delegate"]->script14775830011902070609279["binding"]-
>groovy.util.ConfigBinding["callable"]->groovy.util._parse_closure6["delegate"]-
>groovy.util.ConfigSlurper["classLoader"]->groovy.lang.GroovyClassLoader["resourceLoader"])
    at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:69)
    at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:32)
    at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:693)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:675)
    at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:157)
    at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:693)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:675)
    at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:157)
    at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:693)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:675)
    at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:157)
    at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:693)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:675)
    at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:157)
    at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:693)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:675)
    at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:157)
    at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:693)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:675)
    at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:157)
    at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:561)
    at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:469)
    at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:29)
    at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:561)
    at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:469)
    at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:29)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:130)
    at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1387)
    at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:889)
    at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:269)
    ... 19 common frames omitted

```

**Comment by wilkinsona** [comment]
In the interests of keeping the problem diagnosis in one place, I'm going to close this one in favour of the existing Grails issue. If it turns out that changes are needed in Boot we can re-open this issue or open a new one as appropriate.
