### ISSUE TITLE
LogFileMvcEndpoint doesn't work with latest Spring Framework 4.3 snapshots

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#7254]
Each request directly creates and uses a `ResourceHttpRequestHandler`. This has caused problems in the past so we started calling `afterPropertiesSet` on it. It's now causing problems again as we aren't called `setApplicationContext` on it. We either need to start doing that, or we need to take a different approach. It's tempting to investigate the latter as I think we're only using `ResourceHttpRequestHandler` as an easy way of supporting range requests.

The failure is:

```
java.lang.IllegalStateException: java.lang.IllegalStateException: ApplicationObjectSupport instance [ResourceHttpRequestHandler [locations=[], resolvers=[org.springframework.web.servlet.resource.PathResourceResolver@67bc551]]] does not run in an ApplicationContext
	at org.springframework.context.support.ApplicationObjectSupport.getApplicationContext(ApplicationObjectSupport.java:141)
	at org.springframework.web.context.support.WebApplicationObjectSupport.getWebApplicationContext(WebApplicationObjectSupport.java:107)
	at org.springframework.web.context.support.WebApplicationObjectSupport.getServletContext(WebApplicationObjectSupport.java:128)
	at org.springframework.web.servlet.resource.ResourceHttpRequestHandler.initContentNegotiationStrategy(ResourceHttpRequestHandler.java:306)
	at org.springframework.web.servlet.resource.ResourceHttpRequestHandler.afterPropertiesSet(ResourceHttpRequestHandler.java:268)
	at org.springframework.boot.actuate.endpoint.mvc.LogFileMvcEndpoint$Handler.<init>(LogFileMvcEndpoint.java:111)
	at org.springframework.boot.actuate.endpoint.mvc.LogFileMvcEndpoint.invoke(LogFileMvcEndpoint.java:85)
```

**Comment by wilkinsona** [comment]
Fixed by 60355e0e11aa3afc8526fabc6c77078ddb11cc34
