### ISSUE TITLE
Build fails due to port conflict in `LocalDevToolsAutoConfigurationTests`

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-boot#7268]
Project build has started to fail for me due to 4 tests from `LocalDevToolsAutoConfigurationTests` attempting to start Tomcat on port 8080. I guess this is due to some recent change since I've always had httpd running on 8080 but did not encounter this issue.

Here's the test report:

```
-------------------------------------------------------------------------------
Test set: org.springframework.boot.devtools.autoconfigure.LocalDevToolsAutoConfigurationTests
-------------------------------------------------------------------------------
Tests run: 16, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 5.972 sec <<< FAILURE! - in org.springframework.boot.devtools.autoconfigure.LocalDevToolsAutoConfigurationTests
liveReloadTriggeredOnContextRefresh(org.springframework.boot.devtools.autoconfigure.LocalDevToolsAutoConfigurationTests)  Time elapsed: 0.286 sec  <<< ERROR!
org.springframework.boot.context.embedded.tomcat.ConnectorStartFailedException: Connector configured to listen on port 8080 failed to start
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.checkThatConnectorsHaveStarted(TomcatEmbeddedServletContainer.java:205)
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:183)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:297)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:145)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:736)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:369)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:313)
	at org.springframework.boot.devtools.autoconfigure.LocalDevToolsAutoConfigurationTests.initializeAndRun(LocalDevToolsAutoConfigurationTests.java:267)
	at org.springframework.boot.devtools.autoconfigure.LocalDevToolsAutoConfigurationTests.initializeAndRun(LocalDevToolsAutoConfigurationTests.java:259)
	at org.springframework.boot.devtools.autoconfigure.LocalDevToolsAutoConfigurationTests.liveReloadTriggeredOnContextRefresh(LocalDevToolsAutoConfigurationTests.java:141)

resourceCachePeriodIsZero(org.springframework.boot.devtools.autoconfigure.LocalDevToolsAutoConfigurationTests)  Time elapsed: 0.177 sec  <<< ERROR!
org.springframework.boot.context.embedded.tomcat.ConnectorStartFailedException: Connector configured to listen on port 8080 failed to start
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.checkThatConnectorsHaveStarted(TomcatEmbeddedServletContainer.java:205)
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:183)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:297)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:145)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:736)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:369)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:313)
	at org.springframework.boot.devtools.autoconfigure.LocalDevToolsAutoConfigurationTests.initializeAndRun(LocalDevToolsAutoConfigurationTests.java:267)
	at org.springframework.boot.devtools.autoconfigure.LocalDevToolsAutoConfigurationTests.initializeAndRun(LocalDevToolsAutoConfigurationTests.java:259)
	at org.springframework.boot.devtools.autoconfigure.LocalDevToolsAutoConfigurationTests.resourceCachePeriodIsZero(LocalDevToolsAutoConfigurationTests.java:127)

liveReloadNotTriggeredOnClassPathChangeWithRestart(org.springframework.boot.devtools.autoconfigure.LocalDevToolsAutoConfigurationTests)  Time elapsed: 0.324 sec  <<< ERROR!
org.springframework.boot.context.embedded.tomcat.ConnectorStartFailedException: Connector configured to listen on port 8080 failed to start
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.checkThatConnectorsHaveStarted(TomcatEmbeddedServletContainer.java:205)
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:183)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:297)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:145)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:736)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:369)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:313)
	at org.springframework.boot.devtools.autoconfigure.LocalDevToolsAutoConfigurationTests.initializeAndRun(LocalDevToolsAutoConfigurationTests.java:267)
	at org.springframework.boot.devtools.autoconfigure.LocalDevToolsAutoConfigurationTests.initializeAndRun(LocalDevToolsAutoConfigurationTests.java:259)
	at org.springframework.boot.devtools.autoconfigure.LocalDevToolsAutoConfigurationTests.liveReloadNotTriggeredOnClassPathChangeWithRestart(LocalDevToolsAutoConfigurationTests.java:161)

liveReloadTriggeredOnClassPathChangeWithoutRestart(org.springframework.boot.devtools.autoconfigure.LocalDevToolsAutoConfigurationTests)  Time elapsed: 0.224 sec  <<< ERROR!
org.springframework.boot.context.embedded.tomcat.ConnectorStartFailedException: Connector configured to listen on port 8080 failed to start
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.checkThatConnectorsHaveStarted(TomcatEmbeddedServletContainer.java:205)
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:183)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:297)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:145)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:736)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:369)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:313)
	at org.springframework.boot.devtools.autoconfigure.LocalDevToolsAutoConfigurationTests.initializeAndRun(LocalDevToolsAutoConfigurationTests.java:267)
	at org.springframework.boot.devtools.autoconfigure.LocalDevToolsAutoConfigurationTests.initializeAndRun(LocalDevToolsAutoConfigurationTests.java:259)
	at org.springframework.boot.devtools.autoconfigure.LocalDevToolsAutoConfigurationTests.liveReloadTriggeredOnClassPathChangeWithoutRestart(LocalDevToolsAutoConfigurationTests.java:150)
```

**Comment by snicoll** [comment]
Thanks @vpavic - this has been introduced in 1.5

**Comment by snicoll** [comment]
@philwebb I am confused by the change. Why is this necessary in 1.5 but it isn't necessary in 1.4?

**Comment by vpavic** [comment]
Thanks for fixing this - I can confirm that the build now runs fine.

**Comment by spurthigulivindala** [comment]
where i have to use this setEnvirornment(false) this property in application class  or in application.properties.please clarify this....i m also getting same error as shown above

**Comment by spurthigulivindala** [comment]
how can i set that server properties

**Comment by snicoll** [comment]
@spurthigulivindala we  don't use the tracker for questions (and this issue is closed anyway). Please ask on StackOverflow.
