### ISSUE TITLE
Any `management.security` properties cause ClassNotFoundException when spring-security is not present

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#7276]
If `SampleActuatorUiApplication` is updated so that spring security is not included and the security properties bean definition is removed the application will start fine. However if a `mangement.security.enabled=false` property is then added to `application.properties` startup will fail:

```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                        

2016-11-02 10:17:04.110  INFO 40471 --- [           main] s.a.ui.SampleActuatorUiApplication       : Starting SampleActuatorUiApplication on pwmbp with PID 40471 (/Users/pwebb/projects/spring-boot/code15x/spring-boot-samples/spring-boot-sample-actuator-ui/target/classes started by pwebb in /Users/pwebb/projects/spring-boot/code15x/spring-boot-samples/spring-boot-sample-actuator-ui)
2016-11-02 10:17:04.113  INFO 40471 --- [           main] s.a.ui.SampleActuatorUiApplication       : No active profile set, falling back to default profiles: default
2016-11-02 10:17:04.173  INFO 40471 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@1a84f40f: startup date [Wed Nov 02 10:17:04 PDT 2016]; root of context hierarchy
2016-11-02 10:17:05.799  INFO 40471 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 8080 (http)
2016-11-02 10:17:05.816  INFO 40471 --- [           main] o.apache.catalina.core.StandardService   : Starting service Tomcat
2016-11-02 10:17:05.817  INFO 40471 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.5
2016-11-02 10:17:05.927  INFO 40471 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2016-11-02 10:17:05.927  INFO 40471 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1758 ms
2016-11-02 10:17:06.223  INFO 40471 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Mapping servlet: 'dispatcherServlet' to [/]
2016-11-02 10:17:06.227  INFO 40471 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'metricsFilter' to: [/*]
2016-11-02 10:17:06.228  INFO 40471 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2016-11-02 10:17:06.228  INFO 40471 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2016-11-02 10:17:06.228  INFO 40471 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2016-11-02 10:17:06.228  INFO 40471 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
2016-11-02 10:17:06.228  INFO 40471 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'webRequestLoggingFilter' to: [/*]
2016-11-02 10:17:06.228  INFO 40471 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'applicationContextIdFilter' to: [/*]
2016-11-02 10:17:06.527  INFO 40471 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : jolokia: No access restrictor found, access to any MBean is allowed
2016-11-02 10:17:06.620  WARN 40471 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$EnableWebMvcConfiguration': Unsatisfied dependency expressed through method 'setConfigurers' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.actuate.autoconfigure.EndpointWebMvcManagementContextConfiguration': Unsatisfied dependency expressed through field 'managementServerProperties'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'managementServerProperties': Could not bind properties to ManagementServerProperties (prefix=management, ignoreInvalidFields=false, ignoreUnknownFields=true, ignoreNestedProperties=false); nested exception is org.springframework.beans.NullValueInNestedPathException: Invalid property 'security' of bean class [org.springframework.boot.actuate.autoconfigure.ManagementServerProperties]: Could not instantiate property type [org.springframework.boot.actuate.autoconfigure.ManagementServerProperties$Security] to auto-grow nested property path; nested exception is java.lang.NoClassDefFoundError: org/springframework/security/config/http/SessionCreationPolicy
2016-11-02 10:17:06.624  INFO 40471 --- [           main] o.apache.catalina.core.StandardService   : Stopping service Tomcat
2016-11-02 10:17:06.646  INFO 40471 --- [           main] utoConfigurationReportLoggingInitializer : 

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2016-11-02 10:17:06.656 ERROR 40471 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$EnableWebMvcConfiguration': Unsatisfied dependency expressed through method 'setConfigurers' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.actuate.autoconfigure.EndpointWebMvcManagementContextConfiguration': Unsatisfied dependency expressed through field 'managementServerProperties'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'managementServerProperties': Could not bind properties to ManagementServerProperties (prefix=management, ignoreInvalidFields=false, ignoreUnknownFields=true, ignoreNestedProperties=false); nested exception is org.springframework.beans.NullValueInNestedPathException: Invalid property 'security' of bean class [org.springframework.boot.actuate.autoconfigure.ManagementServerProperties]: Could not instantiate property type [org.springframework.boot.actuate.autoconfigure.ManagementServerProperties$Security] to auto-grow nested property path; nested exception is java.lang.NoClassDefFoundError: org/springframework/security/config/http/SessionCreationPolicy
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:648) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:349) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1219) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:754) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866) ~[spring-context-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) ~[spring-context-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[classes/:na]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:736) [classes/:na]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:369) [classes/:na]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:313) [classes/:na]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1161) [classes/:na]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1150) [classes/:na]
	at sample.actuator.ui.SampleActuatorUiApplication.main(SampleActuatorUiApplication.java:53) [classes/:na]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.actuate.autoconfigure.EndpointWebMvcManagementContextConfiguration': Unsatisfied dependency expressed through field 'managementServerProperties'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'managementServerProperties': Could not bind properties to ManagementServerProperties (prefix=management, ignoreInvalidFields=false, ignoreUnknownFields=true, ignoreNestedProperties=false); nested exception is org.springframework.beans.NullValueInNestedPathException: Invalid property 'security' of bean class [org.springframework.boot.actuate.autoconfigure.ManagementServerProperties]: Could not instantiate property type [org.springframework.boot.actuate.autoconfigure.ManagementServerProperties$Security] to auto-grow nested property path; nested exception is java.lang.NoClassDefFoundError: org/springframework/security/config/http/SessionCreationPolicy
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:569) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:349) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1219) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:372) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1128) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1023) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:207) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1289) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1258) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveMultipleBeans(DefaultListableBeanFactory.java:1164) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1089) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1059) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:640) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	... 19 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'managementServerProperties': Could not bind properties to ManagementServerProperties (prefix=management, ignoreInvalidFields=false, ignoreUnknownFields=true, ignoreNestedProperties=false); nested exception is org.springframework.beans.NullValueInNestedPathException: Invalid property 'security' of bean class [org.springframework.boot.actuate.autoconfigure.ManagementServerProperties]: Could not instantiate property type [org.springframework.boot.actuate.autoconfigure.ManagementServerProperties$Security] to auto-grow nested property path; nested exception is java.lang.NoClassDefFoundError: org/springframework/security/config/http/SessionCreationPolicy
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:329) ~[classes/:na]
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:288) ~[classes/:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1575) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:207) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1131) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1059) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:566) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	... 44 common frames omitted
Caused by: org.springframework.beans.NullValueInNestedPathException: Invalid property 'security' of bean class [org.springframework.boot.actuate.autoconfigure.ManagementServerProperties]: Could not instantiate property type [org.springframework.boot.actuate.autoconfigure.ManagementServerProperties$Security] to auto-grow nested property path; nested exception is java.lang.NoClassDefFoundError: org/springframework/security/config/http/SessionCreationPolicy
	at org.springframework.beans.AbstractNestablePropertyAccessor.newValue(AbstractNestablePropertyAccessor.java:919) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.AbstractNestablePropertyAccessor.createDefaultPropertyValue(AbstractNestablePropertyAccessor.java:887) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.AbstractNestablePropertyAccessor.setDefaultValue(AbstractNestablePropertyAccessor.java:875) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.AbstractNestablePropertyAccessor.getNestedPropertyAccessor(AbstractNestablePropertyAccessor.java:839) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.AbstractNestablePropertyAccessor.getPropertyAccessorForPropertyPath(AbstractNestablePropertyAccessor.java:813) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.AbstractNestablePropertyAccessor.setPropertyValue(AbstractNestablePropertyAccessor.java:270) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.boot.bind.RelaxedDataBinder$RelaxedBeanWrapper.setPropertyValue(RelaxedDataBinder.java:699) ~[classes/:na]
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:95) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.validation.DataBinder.applyPropertyValues(DataBinder.java:834) ~[spring-context-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.validation.DataBinder.doBind(DataBinder.java:730) ~[spring-context-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.boot.bind.RelaxedDataBinder.doBind(RelaxedDataBinder.java:128) ~[classes/:na]
	at org.springframework.validation.DataBinder.bind(DataBinder.java:715) ~[spring-context-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.boot.bind.PropertiesConfigurationFactory.doBindPropertiesToTarget(PropertiesConfigurationFactory.java:266) ~[classes/:na]
	at org.springframework.boot.bind.PropertiesConfigurationFactory.bindPropertiesToTarget(PropertiesConfigurationFactory.java:236) ~[classes/:na]
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:325) ~[classes/:na]
	... 57 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/springframework/security/config/http/SessionCreationPolicy
	at org.springframework.boot.actuate.autoconfigure.ManagementServerProperties$Security.<init>(ManagementServerProperties.java:186) ~[classes/:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_40]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_40]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_40]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_40]
	at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_40]
	at org.springframework.beans.BeanUtils.instantiate(BeanUtils.java:77) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	at org.springframework.beans.AbstractNestablePropertyAccessor.newValue(AbstractNestablePropertyAccessor.java:914) ~[spring-beans-4.3.4.BUILD-SNAPSHOT.jar:4.3.4.BUILD-SNAPSHOT]
	... 71 common frames omitted

```

**Comment by snicoll** [comment]
Looks like #3888 to me.

**Comment by philwebb** [comment]
Thanks.
