### ISSUE TITLE
DevTools and Proxy

### ISSUE THREAD

**Issue by alexandr-v** [spring-projects/spring-boot#7331]
Hi, 

Spring Boot 1.4.1
Example:  https://github.com/alexandr-v/spring-boot-devtools-proxy

At startup I get an exception:
```
...
Caused by: org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'testServiceImpl' is expected to be of type [com.example.service.TestService] but was actually of type [org.springframework.cglib.proxy.Proxy$ProxyImpl$$EnhancerByCGLIB$$b2eee2d7]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:378) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
...
```

On line 385 in AbstractBeanFactory.class in variable "requiredType" interface TestService loaded by RestartClassLoader, but interface TestService in proxy class loaded by AppClassLoader

Did I do something wrong? or this is bug?)

If remove spring-boot-devtools from maven dependencies, this works fine...

**Comment by wilkinsona** [comment]
CGLib is using the wrong class loader for the `TestService` interface. It's using the app class loader rather than Dev Tools' class loader. This means that type check fails and so the `BeanNotOfRequiredTypeException` is thrown. It works fine is you use Spring Framework's proxy support rather than calling CGLib directly:

```
Object proxiedBean = new DefaultAopProxyFactory().createAopProxy(new ProxyFactory(bean)).getProxy(classLoader);
```
