### ISSUE TITLE
Liquibase Hikari Datasource no connection test query

### ISSUE THREAD

**Issue by kevinamasur** [spring-projects/spring-boot#7404]
I'm trying to use the liquibase auto configurations for my MSSQL Server database.  I want my liquibase changes to use a different database user than the one my regular spring datasource is using. I'm providing the following to my liquibase config:

```
liquibase:
    enabled: true
    url: jdbc:jtds:sqlserver://xxxxx
    user: xxxxx
    password: xxxxx
```

I also have a separate hikari datasource in my config as well.  When spring starts up it makes a new hikari datasource for the liquibase changes.  However the hikari datasource that gets created causes and error:

`HikariPool-1 - Failed to execute isValid() for connection, configure connection test query. (null)`

It appears that the hikari datasource the liquibase auto configuration creates by default has null for the connection test query.

I'm using Spring boot 1.4.1

Looking at [LiquibaseAutoConfiguration.java](https://github.com/spring-projects/spring-boot/blob/v1.4.2.RELEASE/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration.java) the getDatasource method returns a default datasource from the datasource builder:

```
return DataSourceBuilder.create().url(this.properties.getUrl())
			.username(this.properties.getUser())
			.password(this.properties.getPassword()).build();
```

However the DataSource the DataSourceBuilder returns doesn't set a default for connection test query.  I'm able to work around this issue by configuring my own SpringLiquibase bean and manually creating the hikari datasource but the default one that gets created should still work.

**Comment by philwebb** [comment]
Does the "HikariPool-1 - Failed to execute isValid() for connection, configure connection test query. (null)" error result in a full stack-trace? If so could you please attach it? A sample project would also be quite helpful.

**Comment by snicoll** [comment]
I am not sure I get this either. There is nothing special in that code, it's the same code as the one used for auto-configuration. So if it fails for the Liquibase created data source it should also fail the same way for the main auto-configured data source. What am I missing?

**Comment by kevinamasur** [comment]
I created the following repo which has this issue [here](https://github.com/kevinamasur/liquibase-hikari-issue)

When starting the server Spring fails to start because it fails to create the liquibase bean.  Liquibase attempts to create its own hikari datasource using the DataSourceBuilder.  The Hikari datasource the liquibase bean attempts to create shows the following log:

```
2016-11-20 20:32:19.286 DEBUG 86540 --- [           main] com.zaxxer.hikari.HikariConfig           : HikariPool-1 - configuration:
2016-11-20 20:32:19.289 DEBUG 86540 --- [           main] com.zaxxer.hikari.HikariConfig           : allowPoolSuspension.............false
2016-11-20 20:32:19.289 DEBUG 86540 --- [           main] com.zaxxer.hikari.HikariConfig           : autoCommit......................true
2016-11-20 20:32:19.289 DEBUG 86540 --- [           main] com.zaxxer.hikari.HikariConfig           : catalog.........................null
2016-11-20 20:32:19.289 DEBUG 86540 --- [           main] com.zaxxer.hikari.HikariConfig           : connectionInitSql...............null
2016-11-20 20:32:19.289 DEBUG 86540 --- [           main] com.zaxxer.hikari.HikariConfig           : connectionTestQuery.............null
2016-11-20 20:32:19.289 DEBUG 86540 --- [           main] com.zaxxer.hikari.HikariConfig           : connectionTimeout...............30000
2016-11-20 20:32:19.290 DEBUG 86540 --- [           main] com.zaxxer.hikari.HikariConfig           : dataSource......................null
2016-11-20 20:32:19.290 DEBUG 86540 --- [           main] com.zaxxer.hikari.HikariConfig           : dataSourceClassName.............null
2016-11-20 20:32:19.290 DEBUG 86540 --- [           main] com.zaxxer.hikari.HikariConfig           : dataSourceJNDI..................null
2016-11-20 20:32:19.290 DEBUG 86540 --- [           main] com.zaxxer.hikari.HikariConfig           : dataSourceProperties............{password=<masked>}
2016-11-20 20:32:19.290 DEBUG 86540 --- [           main] com.zaxxer.hikari.HikariConfig           : driverClassName................."net.sourceforge.jtds.jdbc.Driver"
2016-11-20 20:32:19.290 DEBUG 86540 --- [           main] com.zaxxer.hikari.HikariConfig           : healthCheckProperties...........{}
2016-11-20 20:32:19.290 DEBUG 86540 --- [           main] com.zaxxer.hikari.HikariConfig           : healthCheckRegistry.............null
2016-11-20 20:32:19.290 DEBUG 86540 --- [           main] com.zaxxer.hikari.HikariConfig           : idleTimeout.....................600000
2016-11-20 20:32:19.290 DEBUG 86540 --- [           main] com.zaxxer.hikari.HikariConfig           : initializationFailFast..........true
2016-11-20 20:32:19.290 DEBUG 86540 --- [           main] com.zaxxer.hikari.HikariConfig           : isolateInternalQueries..........false
2016-11-20 20:32:19.290 DEBUG 86540 --- [           main] com.zaxxer.hikari.HikariConfig           : jdbc4ConnectionTest.............false
2016-11-20 20:32:19.290 DEBUG 86540 --- [           main] com.zaxxer.hikari.HikariConfig           : jdbcUrl........................."jdbc:jtds:sqlserver://localhost:1433/smallBlock"
2016-11-20 20:32:19.290 DEBUG 86540 --- [           main] com.zaxxer.hikari.HikariConfig           : leakDetectionThreshold..........0
2016-11-20 20:32:19.290 DEBUG 86540 --- [           main] com.zaxxer.hikari.HikariConfig           : maxLifetime.....................1800000
2016-11-20 20:32:19.291 DEBUG 86540 --- [           main] com.zaxxer.hikari.HikariConfig           : maximumPoolSize.................10
2016-11-20 20:32:19.291 DEBUG 86540 --- [           main] com.zaxxer.hikari.HikariConfig           : metricRegistry..................null
2016-11-20 20:32:19.291 DEBUG 86540 --- [           main] com.zaxxer.hikari.HikariConfig           : metricsTrackerFactory...........null
2016-11-20 20:32:19.291 DEBUG 86540 --- [           main] com.zaxxer.hikari.HikariConfig           : minimumIdle.....................10
2016-11-20 20:32:19.291 DEBUG 86540 --- [           main] com.zaxxer.hikari.HikariConfig           : password........................<masked>
2016-11-20 20:32:19.291 DEBUG 86540 --- [           main] com.zaxxer.hikari.HikariConfig           : poolName........................"HikariPool-1"
2016-11-20 20:32:19.291 DEBUG 86540 --- [           main] com.zaxxer.hikari.HikariConfig           : readOnly........................false
2016-11-20 20:32:19.291 DEBUG 86540 --- [           main] com.zaxxer.hikari.HikariConfig           : registerMbeans..................false
2016-11-20 20:32:19.291 DEBUG 86540 --- [           main] com.zaxxer.hikari.HikariConfig           : scheduledExecutorService........null
2016-11-20 20:32:19.291 DEBUG 86540 --- [           main] com.zaxxer.hikari.HikariConfig           : threadFactory...................null
2016-11-20 20:32:19.291 DEBUG 86540 --- [           main] com.zaxxer.hikari.HikariConfig           : transactionIsolation............null
2016-11-20 20:32:19.291 DEBUG 86540 --- [           main] com.zaxxer.hikari.HikariConfig           : username........................"ngc"
2016-11-20 20:32:19.291 DEBUG 86540 --- [           main] com.zaxxer.hikari.HikariConfig           : validationTimeout...............5000
2016-11-20 20:32:19.291  INFO 86540 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Started.
2016-11-20 20:32:19.354  INFO 86540 --- [           main] com.zaxxer.hikari.pool.PoolBase          : HikariPool-1 - Driver does not support get/set network timeout for connections. (null)
2016-11-20 20:32:19.354 ERROR 86540 --- [           main] com.zaxxer.hikari.pool.PoolBase          : HikariPool-1 - Failed to execute isValid() for connection, configure connection test query. (null)
2016-11-20 20:32:19.354  INFO 86540 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Close initiated...
2016-11-20 20:32:19.354 DEBUG 86540 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Before closing stats (total=0, active=0, idle=0, waiting=0)
2016-11-20 20:32:19.354 DEBUG 86540 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - After closing stats (total=0, active=0, idle=0, waiting=0)
2016-11-20 20:32:19.355  INFO 86540 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Closed.
```

Which leads to the following stacktrace:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: null
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1583) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:296) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1076) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:851) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761) ~[spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371) ~[spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at com.kevin.masur.Application.main(Application.java:18) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_65]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_65]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147) [idea_rt.jar:na]
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: null
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:516) ~[HikariCP-2.4.7.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:118) ~[HikariCP-2.4.7.jar:na]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:94) ~[HikariCP-2.4.7.jar:na]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:388) ~[liquibase-core-3.5.0.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1642) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1579) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	... 21 common frames omitted
Caused by: java.lang.AbstractMethodError: null
	at net.sourceforge.jtds.jdbc.JtdsConnection.isValid(JtdsConnection.java:2833) ~[jtds-1.3.1.jar:1.3.1]
	at com.zaxxer.hikari.pool.PoolBase.checkDriverSupport(PoolBase.java:375) ~[HikariCP-2.4.7.jar:na]
	at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:350) ~[HikariCP-2.4.7.jar:na]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:321) ~[HikariCP-2.4.7.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:506) ~[HikariCP-2.4.7.jar:na]
	... 26 common frames omitted
```

If I turn off the liquibase integrations or allow it to use the default spring.datasource the app starts up fine.  The spring datasource works because I can manually set properties on the datasource that gets created.  Specifically the spring.datasource.hikari.connection-test-query property.  However I can't configure the datasource that liquibase attempts to create, nor does it provide a default for the connection-test-query.  See the configuration for the liquibase and spring datasource below:

```
spring:
  datasource:
    username: springuser
    password: springuser
    url: jdbc:jtds:sqlserver://localhost:1433/smallBlock
    driverClassName: net.sourceforge.jtds.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 5
      pool-name: my-servicePool
      idle-timeout: 10000
      connection-test-query: SELECT 1
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
liquibase:
  url: ${spring.datasource.url}
  user: liquibaseuser
  password: liquibaseuser
  change-log: classpath:liquibase-changeLog.xml
  enabled: true
  default-schema: dbo
```

**Comment by philwebb** [comment]
OK, the issue is that `net.sourceforge.jtds.jdbc.JtdsConnection` doesn't implement `isValid` so you _need_ to specify a `connection-test-query` to ensure that that method isn't called. We don't offer the `hikari.connection-test-query` property for liquibase.

You'll need to define your liquibase datasource in code. You can use the `@LiquibaseDataSource` qualifier for that. Something like:

```java
@Bean
@LiquibaseDataSource
public DataSource liquibaseDataSource(LiquibaseProperties properties) {
	 HikariDataSource ds = (HikariDataSource) DataSourceBuilder.create().url(this.properties.getUrl())
					.username(this.properties.getUser())
					.password(this.properties.getPassword())
					.type(HikariDataSource.class).build();
	ds.setConnectionTestQuery("SELECT 1");
	return ds;
}
```

**Comment by hwck** [comment]
oracle use
ds.setConnectionTestQuery("SELECT 1 FROM DUAL");
