### ISSUE TITLE
SSL-client-auth with self-signed cert stopped working

### ISSUE THREAD

**Issue by jarmoni** [spring-projects/spring-boot#7406]
In 1.3.5.RELEASE I could test Client-auth with self-signed certificates as described [here](https://github.com/viniciusccarvalho/boot-two-way-ssl-example). Unfortunately in 1.4.2.RELEASE this does not work anymore, the server-startup fails because of invalid truststore (seems to require a 'TrustedCertEntry' which of course is not present because the server-cert is self-signed) :
```
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
	at java.security.cert.PKIXParameters.<init>(PKIXParameters.java:157)
	at java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:130)
	at org.apache.tomcat.util.net.jsse.JSSEUtil.getParameters(JSSEUtil.java:332)
	at org.apache.tomcat.util.net.jsse.JSSEUtil.getTrustManagers(JSSEUtil.java:264)
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:101)
	... 19 common frames omitted
```
My application.properties:
```
server.ssl.client-auth=need
server.ssl.enabled= true
server.ssl.key-password=s3cr3t
server.ssl.key-store=classpath:server.jks
server.ssl.key-store-password=s3cr3t
server.ssl.trust-store=classpath:server.jks
server.ssl.trust-store-password= s3cr3t
```
When I remove the truststore entries, the server starts up but no client authentication is possible - because of missing "trust-information" (not surprising).

Is there any way to make the "old" behaviour working again? The requirement of "real" CA-signed certificates for a simple test-setup  seems to be a bit of overhead...

**Comment by wilkinsona** [comment]
This is due to a change in Tomcat (see #7069 and #6703). The TL;DR is that Tomcat has improved its SSL security which requires trust stores to contain at least one certificate and yours does not.
