### ISSUE TITLE
How can I fix this issue?

### ISSUE THREAD

**Issue by 383124397** [spring-projects/spring-boot#7470]
Question

Use the spring-boot start a java web project, I have already add ours' servlet, but it always throw a exception:

java.lang.UnsupportedOperationException: Section 4.4 of the Servlet 3.0 specification does not permit this method to be called from a ServletContextListener that was not defined in web.xml, a web-fragment.xml file nor annotated with @WebListener
	at org.apache.catalina.core.StandardContext$NoPluggabilityServletContext.getServletRegistrations(StandardContext.java:6603)
	at com.ctriposs.baiji.rpc.server.BaijiListener.getContextPath(BaijiListener.java:239)
	at com.ctriposs.baiji.rpc.server.BaijiListener.registerService(BaijiListener.java:207)
	at com.ctriposs.baiji.rpc.server.BaijiListener.contextInitialized(BaijiListener.java:110)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4725)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5189)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1403)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1393)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745) 

Root Cause Code:
Map<String, ? extends ServletRegistration> servletRegistrations = context.getServletRegistrations();

context.getServletRegistrations(); method is not be support in StandContext$NoPluggabilityServletContext

it's tomcat-embed-core logic.

**Comment by 383124397** [comment]
Question

Use the spring-boot start a java web project, I have already add ours' servlet, but it always throw a exception:

java.lang.UnsupportedOperationException: Section 4.4 of the Servlet 3.0 specification does not permit this method to be called from a ServletContextListener that was not defined in web.xml, a web-fragment.xml file nor annotated with @WebListener
	at org.apache.catalina.core.StandardContext$NoPluggabilityServletContext.getServletRegistrations(StandardContext.java:6603)
	at com.ctriposs.baiji.rpc.server.BaijiListener.getContextPath(BaijiListener.java:239)
	at com.ctriposs.baiji.rpc.server.BaijiListener.registerService(BaijiListener.java:207)
	at com.ctriposs.baiji.rpc.server.BaijiListener.contextInitialized(BaijiListener.java:110)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4725)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5189)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1403)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1393)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745) 

Root Cause Code:
Map<String, ? extends ServletRegistration> servletRegistrations = context.getServletRegistrations();

context.getServletRegistrations(); method is not be support in StandContext$NoPluggabilityServletContext

it's tomcat-embed-core logic.
