### ISSUE TITLE
find a problem in fat jar that is spring-boot-starter-jersey

### ISSUE THREAD

**Issue by vincent-ren** [spring-projects/spring-boot#7472]
I send a problem to engineers.I have build a project use spring boot and jersey, i download this project at http://start.spring.io/ ,use this project start by SpringBootApplication main is ok, but when i add this project in my tomcat, it have a strange error that make project can not run. I find this problem take a full day. I find a fat jar has problem, this fat jar`s artifactId is spring-boot-starter-jersey, i must exclusions jersey-bean-validation and jersey-spring3, and add jersey-spring3 that version is 2.22.1, then this project has run. I am very hungry to know your reply. I will focus this issue. Thank you!
this spring-boot-starter-parent version is 1.4.2.RELEASE, I send my sample project, this bug in fat jar spring-boot-starter-jersey, when this project run in your tomcat,it will has strange error, if you cancel my notes, it will run success! when you see this sample project, you will know all this. I am very hungry to get your reply. I will focus this issue. Thank you!
[test-123.zip](https://github.com/spring-projects/spring-boot/files/611359/test-123.zip)

**Comment by wilkinsona** [comment]
What do we need to do with the sample project to recreate the failure? I have tried starting it both as an executable war (`java -jar target/test-123-0.0.1-SNAPSHOT.war`) and by deploying it to Tomcat 8.5.4. It started successfully in both cases.

**Comment by vincent-ren** [comment]
I deploying it to tomcat 8.0.39 it will failure. Do you cancel notes in this pom.xml? don`t cancel will failure.
this is my error message:
SEVERE: ContainerBase.addChild: start: 
org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/test-123]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:162)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:753)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:587)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1798)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [org.apache.catalina.webresources.StandardRoot@5a78ef0]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:162)
	at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:4969)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5099)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	... 10 more
Caused by: org.apache.catalina.LifecycleException: Failed to initialize component [org.apache.catalina.webresources.JarResourceSet@33bd4f75]
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:135)
	at org.apache.catalina.webresources.StandardRoot.startInternal(StandardRoot.java:706)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	... 13 more
Caused by: java.lang.IllegalArgumentException: java.util.zip.ZipException: invalid LOC header (bad signature)
	at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.initInternal(AbstractSingleArchiveResourceSet.java:113)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:102)
	... 16 more
Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)
	at java.util.zip.ZipFile.read(Native Method)
	at java.util.zip.ZipFile.access$1400(ZipFile.java:60)
	at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:717)
	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:419)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at sun.misc.IOUtils.readFully(IOUtils.java:65)
	at java.util.jar.JarFile.getBytes(JarFile.java:425)
	at java.util.jar.JarFile.getManifestFromReference(JarFile.java:193)
	at java.util.jar.JarFile.getManifest(JarFile.java:180)
	at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.initInternal(AbstractSingleArchiveResourceSet.java:111)
	... 17 more

Nov 24, 2016 9:16:14 PM org.apache.catalina.startup.HostConfig deployDescriptor
SEVERE: Error deploying configuration descriptor /home/vincent/workspace2/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/conf/Catalina/localhost/test-123.xml
java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/test-123]]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:757)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:587)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1798)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Nov 24, 2016 9:16:14 PM org.apache.catalina.startup.HostConfig deployDescriptor
INFO: Deployment of configuration descriptor /home/vincent/workspace2/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/conf/Catalina/localhost/test-123.xml has finished in 38 ms
Nov 24, 2016 9:16:14 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-nio-8080"]
Nov 24, 2016 9:16:14 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["ajp-nio-8009"]
Nov 24, 2016 9:16:14 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 547 ms

**Comment by wilkinsona** [comment]
One of the jar files in your war file is corrupted. Try clearing your Maven cache and rebuilding.

**Comment by vincent-ren** [comment]
when I cancel all notes in this pom.xml, it will start successfully.

**Comment by vincent-ren** [comment]
I have mvn clean package this project, and executable war (java -jar test-123-0.0.1-SNAPSHOT.war) it is successfully, but I deployed this war to my tomcat 8.0.39, it run error! @wilkinsona please try again, I wait your reply, thank you very much.

**Comment by vincent-ren** [comment]
@wilkinsona can you give me your deployed war? I am need it! thank you! my email is vincent.ijava@gmail.com  I am very sorry to trouble you, but i also want to help spring boot can strengthen! thank you!

**Comment by vincent-ren** [comment]
@wilkinsona  Sorry to trouble you and I am happy to get success, i delete my repository and then mvn clean package, deployed this war. It started successfully. Thank you!
