### ISSUE TITLE
Cannot start multiple spring boot application on embedded tomcat 8.5.8

### ISSUE THREAD

**Issue by laiynus** [spring-projects/spring-boot#7474]
I use Spring boot 1.4.2.RELEASE
Java 1.8.92
Embedded tomcat 8.5.8
And Windows OS

I try to run multiple spring boot applications as part of one core. First application starts fine, but others not. I have message that address already in use. Here the full stacktrace:

```
java.net.BindException: Address already in use: bind
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)]
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:229) 
        at org.apache.tomcat.util.net.AbstractEndpoint.init(AbstractEndpoint.java:875) 
        at org.apache.tomcat.util.net.AbstractJsseEndpoint.init(AbstractJsseEndpoint.java:213) 
        at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:558)
        at org.apache.coyote.http11.AbstractHttp11Protocol.init(AbstractHttp11Protocol.java:65) 
        at org.apache.catalina.connector.Connector.initInternal(Connector.java:968)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
        at org.apache.catalina.core.StandardService.initInternal(StandardService.java:549) 
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
        at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:875)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107) 
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:140) 
        at org.apache.catalina.startup.Tomcat.start(Tomcat.java:342)
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.initialize(TomcatEmbeddedServletC
ontainer.java:96)
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.<init>(TomcatEmbeddedServletConta
iner.java:82)
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.getTomcatEmbeddedServletCo
ntainer(TomcatEmbeddedServletContainerFactory.java:535) 
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.getEmbeddedServletContaine
r(TomcatEmbeddedServletContainerFactory.java:177)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWe
bApplicationContext.java:164) 
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.j
ava:134) 
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:536) 
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.jav
a:122) 
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761) 
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371) 
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) 
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134) 
        at com.khrapavitski.springbootsample.common.ApplicationBuilder.lambda$build$0(ApplicationBuilder.java:70)
        at java.util.ArrayList.forEach(ArrayList.java:1249) 
        at com.khrapavitski.springbootsample.common.ApplicationBuilder.build(ApplicationBuilder.java:64)
        at Application.main(Application.java:25) 
```

But if I set `tomcat.version=8.5.6`, applications run fine.

**Test project is here** 
[springbootsample.zip](https://github.com/spring-projects/spring-boot/files/611515/springbootsample.zip)

Thank you,
Raman

**Comment by wilkinsona** [comment]
We don't support Tomcat 8.5.8 (hence our use of 8.5.6 at the moment). There's a bug in Tomcat 8.5.8 which means that it always creates and starts a default connector: https://bz.apache.org/bugzilla/show_bug.cgi?id=60368
