### ISSUE TITLE
Parsing error of multipart.max-file-size for MB suffix

### ISSUE THREAD

**Issue by tzielins** [spring-projects/spring-boot#7613]
Bug report

SpringBoot 1.4.2.RELEASE

Mulitypart max file size cannot be configured in the properties files using MB suffix as it raises the exception on startup.

Parameter:

spring.http.multipart.max-file-size=25MB

```
Caused by: java.lang.NumberFormatException: For input string: "25MB "
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.valueOf(Long.java:803)
	at org.springframework.boot.web.servlet.MultipartConfigFactory.parseSize(MultipartConfigFactory.java:120)
	at org.springframework.boot.web.servlet.MultipartConfigFactory.setMaxFileSize(MultipartConfigFactory.java:70)
	at org.springframework.boot.autoconfigure.web.MultipartProperties.createMultipartConfig(MultipartProperties.java:149)
	at org.springframework.boot.autoconfigure.web.MultipartAutoConfiguration.multipartConfigElement(MultipartAutoConfiguration.java:64)
	at org.springframework.boot.autoconfigure.web.MultipartAutoConfiguration$$EnhancerBySpringCGLIB$$d1e086d.CGLIB$multipartConfigElement$0(<generated>)
	at org.springframework.boot.autoconfigure.web.MultipartAutoConfiguration$$EnhancerBySpringCGLIB$$d1e086d$$FastClassBySpringCGLIB$$e30ef616.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)

```
At the same time it parses ok the max request parameter:
spring.http.multipart.max-request-size

**Comment by tzielins** [comment]
The problem was in a white character after the value. Sorry for not noticing it before
