### ISSUE TITLE
Basic Actuator app fails to run on Cloud Foundry

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#7622]
A vanilla Spring Boot app with the Actuator (Boot 1.5) appears to require Spring Security on the classpath if you run it in CF:

```
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cloudFoundryIgnoredRequestCustomizer' defined in class path resource [org/springframework/boot/actuate/cloudfoundry/CloudFoundryActuatorAutoConfiguration.class]: Post-processing of merged bean definition failed; nested exception is java.lang.NoClassDefFoundError: org/springframework/security/config/annotation/web/builders/WebSecurity$IgnoredRequestConfigurer
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:754) ~[spring-beans-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866) ~[spring-context-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) ~[spring-context-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:736) [spring-boot-1.5.0.BUILD-20161208.222750-215.jar!/:1.5.0.BUILD-SNAPSHOT]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:369) [spring-boot-1.5.0.BUILD-20161208.222750-215.jar!/:1.5.0.BUILD-SNAPSHOT]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:313) [spring-boot-1.5.0.BUILD-20161208.222750-215.jar!/:1.5.0.BUILD-SNAPSHOT]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1161) [spring-boot-1.5.0.BUILD-20161208.222750-215.jar!/:1.5.0.BUILD-SNAPSHOT]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1150) [spring-boot-1.5.0.BUILD-20161208.222750-215.jar!/:1.5.0.BUILD-SNAPSHOT]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [app/:na]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [app/:na]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [app/:na]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [app/:na]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT Caused by: java.lang.NoClassDefFoundError: org/springframework/security/config/annotation/web/builders/WebSecurity$IgnoredRequestConfigurer
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at java.lang.Class.getDeclaredMethods0(Native Method) ~[na:1.8.0_111]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[na:1.8.0_111]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[na:1.8.0_111]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:613) ~[spring-core-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at org.springframework.util.ReflectionUtils.doWithLocalMethods(ReflectionUtils.java:489) ~[spring-core-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.buildLifecycleMetadata(InitDestroyAnnotationBeanPostProcessor.java:206) ~[spring-beans-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.findLifecycleMetadata(InitDestroyAnnotationBeanPostProcessor.java:187) ~[spring-beans-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessMergedBeanDefinition(InitDestroyAnnotationBeanPostProcessor.java:125) ~[spring-beans-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessMergedBeanDefinition(CommonAnnotationBeanPostProcessor.java:295) ~[spring-context-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyMergedBeanDefinitionPostProcessors(AbstractAutowireCapableBeanFactory.java:947) ~[spring-beans-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring-beans-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	... 23 common frames omitted
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_111]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_111]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_111]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	... 34 common frames omitted
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.0.BUILD-20161208.222750-215.jar!/:1.5.0.BUILD-SNAPSHOT]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at demo.TraceApplication.main(TraceApplication.java:23) [classes/:na]
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT Caused by: java.lang.ClassNotFoundException: org.springframework.security.config.annotation.web.builders.WebSecurity$IgnoredRequestConfigurer
2016-12-12T13:21:17.19+0000 [APP/PROC/WEB/0]OUT 	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94) ~[app/:na]
2016-12-12T13:21:17.28+0000 [APP/PROC/WEB/0]OUT Exit status 1
```

**Comment by dsyer** [comment]
Fixed in 1baf3c6
