### ISSUE TITLE
Deployment to TomEE 1.7.4 fails due to MethodValidationPostProcessor auto-configuration

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#7665]
The failure is:

```
[INFO] [talledLocalContainer] Caused by: java.lang.NoClassDefFoundError: org/hibernate/validator/method/MethodConstraintViolationException
[INFO] [talledLocalContainer] 	at org.springframework.validation.beanvalidation.MethodValidationInterceptor.<init>(MethodValidationInterceptor.java:92) ~[spring-context-4.3.4.RELEASE.jar:4.3.4.RELEASE]
[INFO] [talledLocalContainer] 	at org.springframework.validation.beanvalidation.MethodValidationPostProcessor.createMethodValidationAdvice(MethodValidationPostProcessor.java:121) ~[spring-context-4.3.4.RELEASE.jar:4.3.4.RELEASE]
[INFO] [talledLocalContainer] 	at org.springframework.validation.beanvalidation.MethodValidationPostProcessor.afterPropertiesSet(MethodValidationPostProcessor.java:109) ~[spring-context-4.3.4.RELEASE.jar:4.3.4.RELEASE]
[INFO] [talledLocalContainer] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1642) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
[INFO] [talledLocalContainer] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1579) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
[INFO] [talledLocalContainer] 	... 29 common frames omitted
[INFO] [talledLocalContainer] Caused by: java.lang.ClassNotFoundException: org.hibernate.validator.method.MethodConstraintViolationException
[INFO] [talledLocalContainer] 	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1858) ~[catalina.jar:7.0.68]
[INFO] [talledLocalContainer] 	at org.apache.tomee.catalina.LazyStopWebappClassLoader.loadClass(LazyStopWebappClassLoader.java:171) ~[tomee-catalina-1.7.4.jar:1.7.4]
[INFO] [talledLocalContainer] 	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1701) ~[catalina.jar:7.0.68]
[INFO] [talledLocalContainer] 	... 34 common frames omitted
```

The test app for TomEE excludes our Hibernate Validator dependency because, IIIRC, it's bundled in TomEE. Presumably it's an old version. I think we have a couple of options:

1. Figure out how to convince TomEE to use our version of Hibernate Validator
2. Change the test to use TomEE 7

**Comment by wilkinsona** [comment]
> The test app for TomEE excludes our Hibernate Validator dependency because, IIIRC, it's bundled in TomEE

I didn't remember correctly. TomEE uses Apache BVal so the code that's trying to use Hibernate Validator needs to be switched off.

**Comment by wilkinsona** [comment]
The problem is that `MethodValidationInterceptor` requires either Bean Validation 1.1 or Bean Validation 1.0 and Hibernate Validator 4.3. TomEE provides Bean Validation 1.0 but with Apache BVal so it blows up looking for the required Hibernate Validator classes.

The auto-configuration is enabled when Bean Validation 1.0 or 1.1 is on the classpath. I think we should update the conditions such the Bean Validation 1.1 is required.
