### ISSUE TITLE
UndertowEmbeddedServletContainerFactory$JarResourceManager.getResource failure

### ISSUE THREAD

**Issue by rohajda** [spring-projects/spring-boot#7717]
I have build WAR application using JHipster. It is using **1.4.2.RELEASE** spring boot. I have setup contextPath for server as `/foo`  I starting application using WAR file as 

`java -jar myApp.war`

When calling application as `http://localhost:8080/foo/ `  - everything works fine.

When I call application as `http://localhost:8080/foo` - i am getting following error

```
java.lang.RuntimeException: java.net.MalformedURLException: No !/ in spec 'file:/Users/robert/Documents/myApp.war!'
	at io.undertow.servlet.handlers.ServletPathMatches.getServletHandlerByPath(ServletPathMatches.java:121)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:127)
	at io.undertow.server.handlers.HttpContinueReadHandler.handleRequest(HttpContinueReadHandler.java:65)
	at io.undertow.server.handlers.encoding.EncodingHandler.handleRequest(EncodingHandler.java:72)
	at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:94)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:207)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:233)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:131)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:57)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at io.undertow.protocols.ssl.SslConduit$SslReadReadyHandler.readReady(SslConduit.java:1122)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:559)
Caused by: java.net.MalformedURLException: No !/ in spec 'file:/Users/robert/Documents/myApp.war!'
	at java.net.URL.<init>(URL.java:627)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory$JarResourceManager.getResource(UndertowEmbeddedServletContainerFactory.java:621)
	at io.undertow.servlet.handlers.ServletPathMatches.getServletHandlerByPath(ServletPathMatches.java:91)
	... 13 common frames omitted


```

 When checking JarResourceManager static class in UndertowEmbeddedServletContainerFactory I see source of problem which maybe can be fixed in that method itself. If **path** is empty string , URL constructor throwing exception as it cannot find it. I feel if there is empty string we should default value to `"/"` to ensure system works as URL itself is corrected later on in processing.

**Existing code**
```
@Override
		public Resource getResource(String path) throws IOException {
			URL url = new URL("jar:file:" + this.jarPath + "!" + path);
			URLResource resource = new URLResource(url, url.openConnection(), path);
			if (resource.getContentLength() < 0) {
				return null;
			}
			return resource;
		}
```

**Suggestion to fix**
```
@Override
		public Resource getResource(String path) throws IOException {
			String correctedPath = path==null || path.isEmpty() ? "/" : path;
                        URL url = new URL("jar:file:" + this.jarPath + "!" + correctedPath);
                        URLResource resource = new URLResource(url, url.openConnection(), correctedPath);
			if (resource.getContentLength() < 0) {
				return null;
			}
			return resource;
		}
```

**Comment by wilkinsona** [comment]
I would expect the request to `http://localhost:8080/foo` to be redirected to `http://localhost:8080/foo/`. That's exactly what happens with jar packaging. It's only with war packaging that the failure described above occurs.

This should be fixed by making sure that the redirect is performed, rather than changing `JarResourceManager`.

**Comment by rohajda** [comment]
if it is possible to redirect it should solve the problem too, i just find much easier to end that / in case it is not there. I think i saw something similar for other type of resource but cannot remmember where

**Comment by wilkinsona** [comment]
The redirect behaviour differs because the failure's occurring in `ServletInitialHandler` before it's had a chance to perform the redirect. It only occurs with a war file as jar file's use a `FileResourceManager` that points to a temporary directory rather than our `JarResourceManager` that points to the war archive.
