### ISSUE TITLE
spring-boot 1.4.2 causes deprecation warning with Gradle 3.3-rc-1

### ISSUE THREAD

**Issue by huxi** [spring-projects/spring-boot#7734]
> The ProjectDependency.getProjectConfiguration() method has been deprecated and is scheduled to be removed in Gradle 4.0.

## Relevant stack trace:
```
The ProjectDependency.getProjectConfiguration() method has been deprecated and is scheduled to be removed in Gradle 4.0.
        at org.gradle.api.internal.artifacts.dependencies.DefaultProjectDependency.getProjectConfiguration(DefaultProjectDependency.java:74)
        at org.gradle.api.internal.artifacts.dependencies.DefaultProjectDependency_Decorated.getProjectConfiguration(Unknown Source)
        at org.springframework.boot.gradle.repackage.ProjectLibraries.getLibrariesForFileDependencies(ProjectLibraries.java:131)
        at org.springframework.boot.gradle.repackage.ProjectLibraries.getLibraries(ProjectLibraries.java:113)
        at org.springframework.boot.gradle.repackage.ProjectLibraries.doWithLibraries(ProjectLibraries.java:90)
        at org.springframework.boot.gradle.repackage.RepackagePluginFeatures$RegisterInputsOutputsAction.addLibraryDependencies(RepackagePluginFeatures.java:158)
        at org.springframework.boot.gradle.repackage.RepackagePluginFeatures$RegisterInputsOutputsAction.setupInputOutputs(RepackagePluginFeatures.java:151)
        at org.springframework.boot.gradle.repackage.RepackagePluginFeatures$RegisterInputsOutputsAction.execute(RepackagePluginFeatures.java:136)
        at org.springframework.boot.gradle.repackage.RepackagePluginFeatures$RegisterInputsOutputsAction.execute(RepackagePluginFeatures.java:114)
        at org.gradle.internal.Actions$FilteredAction.execute(Actions.java:205)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:117)
        at org.gradle.api.internal.tasks.RealizableTaskCollection.all(RealizableTaskCollection.java:192)
        at org.gradle.api.internal.DefaultDomainObjectCollection.withType(DefaultDomainObjectCollection.java:127)
        at org.springframework.boot.gradle.repackage.RepackagePluginFeatures$1.execute(RepackagePluginFeatures.java:84)
        at org.springframework.boot.gradle.repackage.RepackagePluginFeatures$1.execute(RepackagePluginFeatures.java:81)
```

This is just meant as a quick holler to make you aware of the issue.

**Comment by philwebb** [comment]
Thanks for the heads up.

**Comment by patelkunal** [comment]
(y) waiting for this to be in release version

**Comment by bamapookie** [comment]
I am still getting this with Spring Boot 1.5.1 and Gradle 3.3.  Note there has to be a sub-module (even if it is empty) and a classifier in the springBoot task.

*build.gradle*
```
buildscript {
    ext {
        springBootVersion = '1.5.1.RELEASE'
    }
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath group: 'org.springframework.boot', name: 'spring-boot-gradle-plugin', version: springBootVersion
    }
}
apply plugin: 'org.springframework.boot'
repositories {
    mavenCentral()
}
dependencies {
    compile project(':sub') // Important!  Needed to reproduce the bug!
}
springBoot {
    classifier = 'boot' // Important!  Needed to reproduce the bug!
}
allprojects {
    apply plugin: 'java'
}
task wrapper(type: Wrapper) {
    gradleVersion = '3.3'
    distributionType = Wrapper.DistributionType.ALL
}
```

*settings.gradle*
```
include 'sub'
```

Empty sub/build.settings file.

**Comment by bamapookie** [comment]
Created new issue: https://github.com/spring-projects/spring-boot/issues/8154
