### ISSUE TITLE
Upgrade to Jetty that fixes JsrSession NPE and revert workaround

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#7750]
As soon as https://github.com/eclipse/jetty.project/issues/1202 is fixed and an updated Jetty version is release we should revert a116579cfc8b34cbe4d38da7d4117f8cb3893c1b.

**Comment by wilkinsona** [comment]
9.4.1 has been tagged. We just need to wait for it to reach Maven Central.

**Comment by wilkinsona** [comment]
We get a different NPE, both with and without our workaround, now:

```java
java.io.IOException: Connect failure
	at org.eclipse.jetty.websocket.jsr356.ClientContainer.connect(ClientContainer.java:165) ~[javax-websocket-client-impl-9.4.1.v20170120.jar:9.4.1.v20170120]
	at org.eclipse.jetty.websocket.jsr356.ClientContainer.connectToServer(ClientContainer.java:188) ~[javax-websocket-client-impl-9.4.1.v20170120.jar:9.4.1.v20170120]
	at org.springframework.web.socket.client.standard.StandardWebSocketClient$1.call(StandardWebSocketClient.java:150) ~[spring-websocket-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at org.springframework.web.socket.client.standard.StandardWebSocketClient$1.call(StandardWebSocketClient.java:147) ~[spring-websocket-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_102]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
Caused by: java.lang.NullPointerException: null
	at org.springframework.web.socket.adapter.standard.StandardWebSocketSession.initializeNativeSession(StandardWebSocketSession.java:185) ~[spring-websocket-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.onOpen(StandardWebSocketHandlerAdapter.java:61) ~[spring-websocket-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at org.eclipse.jetty.websocket.jsr356.endpoints.JsrEndpointEventDriver.onConnect(JsrEndpointEventDriver.java:140) ~[javax-websocket-client-impl-9.4.1.v20170120.jar:9.4.1.v20170120]
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.openSession(AbstractEventDriver.java:233) ~[websocket-common-9.4.1.v20170120.jar:9.4.1.v20170120]
	at org.eclipse.jetty.websocket.jsr356.endpoints.AbstractJsrEventDriver.openSession(AbstractJsrEventDriver.java:104) ~[javax-websocket-client-impl-9.4.1.v20170120.jar:9.4.1.v20170120]
	at org.eclipse.jetty.websocket.common.WebSocketSession.open(WebSocketSession.java:504) ~[websocket-common-9.4.1.v20170120.jar:9.4.1.v20170120]
	at org.eclipse.jetty.websocket.common.WebSocketSession.onOpened(WebSocketSession.java:433) ~[websocket-common-9.4.1.v20170120.jar:9.4.1.v20170120]
	at org.eclipse.jetty.io.AbstractConnection.onOpen(AbstractConnection.java:200) ~[jetty-io-9.4.1.v20170120.jar:9.4.1.v20170120]
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onOpen(AbstractWebSocketConnection.java:566) ~[websocket-common-9.4.1.v20170120.jar:9.4.1.v20170120]
	at org.eclipse.jetty.io.AbstractEndPoint.upgrade(AbstractEndPoint.java:432) ~[jetty-io-9.4.1.v20170120.jar:9.4.1.v20170120]
	at org.eclipse.jetty.websocket.client.WebSocketUpgradeRequest.upgrade(WebSocketUpgradeRequest.java:622) ~[websocket-client-9.4.1.v20170120.jar:9.4.1.v20170120]
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.exchangeTerminating(HttpChannelOverHTTP.java:116) ~[jetty-client-9.4.1.v20170120.jar:9.4.1.v20170120]
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:451) ~[jetty-client-9.4.1.v20170120.jar:9.4.1.v20170120]
	at org.eclipse.jetty.client.HttpReceiver.responseSuccess(HttpReceiver.java:405) ~[jetty-client-9.4.1.v20170120.jar:9.4.1.v20170120]
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.messageComplete(HttpReceiverOverHTTP.java:281) ~[jetty-client-9.4.1.v20170120.jar:9.4.1.v20170120]
	at org.eclipse.jetty.http.HttpParser.parseHeaders(HttpParser.java:1076) ~[jetty-http-9.4.1.v20170120.jar:9.4.1.v20170120]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1326) ~[jetty-http-9.4.1.v20170120.jar:9.4.1.v20170120]
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:170) ~[jetty-client-9.4.1.v20170120.jar:9.4.1.v20170120]
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:131) ~[jetty-client-9.4.1.v20170120.jar:9.4.1.v20170120]
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:70) ~[jetty-client-9.4.1.v20170120.jar:9.4.1.v20170120]
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:130) ~[jetty-client-9.4.1.v20170120.jar:9.4.1.v20170120]
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:116) ~[jetty-client-9.4.1.v20170120.jar:9.4.1.v20170120]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) ~[jetty-io-9.4.1.v20170120.jar:9.4.1.v20170120]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112) ~[jetty-io-9.4.1.v20170120.jar:9.4.1.v20170120]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) ~[jetty-io-9.4.1.v20170120.jar:9.4.1.v20170120]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672) ~[jetty-util-9.4.1.v20170120.jar:9.4.1.v20170120]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590) ~[jetty-util-9.4.1.v20170120.jar:9.4.1.v20170120]
	... 1 common frames omitted
```

It looks like Jetty is returning `null` from `javax.websocket.Session.getNegotiatedSessions()`. The javadoc is silent on whether or not that is spec compliant.

**Comment by wilkinsona** [comment]
We can change our workaround to tolerate the new behaviour, but I've opened [SPR-15180](https://jira.spring.io/browse/SPR-15180) to see if we can make Spring Framework more robust.

/cc @rstoyanchev
