### ISSUE TITLE
spring-boot-devtool: auto reload not working with spring-cloud-stream

### ISSUE THREAD

**Issue by peanutpi** [spring-projects/spring-boot#7803]
I am trying to use **spring-dev-tool** to auto-reload my application. 
My application is running as a **docker container** in a **Vagrant machine**.

But I am getting following error 

    2016-12-28 03:49:19.224  INFO ["scs-producer",,,] 5 --- [  restartedMain] o.s.s.c.ThreadPoolTaskScheduler          : Initializing ExecutorService
    2016-12-28 03:49:20.216  INFO ["scs-producer",,,] 5 --- [  restartedMain] o.s.i.c.k.CompositeKryoRegistrar         : configured Kryo registration [40, java.io.File] with serializer org.springframework.integration.codec.kryo.FileSerializer
    2016-12-28 03:49:21.593  INFO ["scs-producer",,,] 5 --- [  restartedMain] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
    2016-12-28 03:49:21.602  INFO ["scs-producer",,,] 5 --- [  restartedMain] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'integrationMbeanExporter' has been autodetected for JMX exposure
    2016-12-28 03:49:21.603  INFO ["scs-producer",,,] 5 --- [  restartedMain] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'configurationPropertiesRebinder' has been autodetected for JMX exposure
    2016-12-28 03:49:21.608  INFO ["scs-producer",,,] 5 --- [  restartedMain] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'refreshEndpoint' has been autodetected for JMX exposure
    2016-12-28 03:49:21.609  INFO ["scs-producer",,,] 5 --- [  restartedMain] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'restartEndpoint' has been autodetected for JMX exposure
    2016-12-28 03:49:21.609  INFO ["scs-producer",,,] 5 --- [  restartedMain] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'refreshScope' has been autodetected for JMX exposure
    2016-12-28 03:49:21.610  INFO ["scs-producer",,,] 5 --- [  restartedMain] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'environmentManager' has been autodetected for JMX exposure
    2016-12-28 03:49:21.612  INFO ["scs-producer",,,] 5 --- [  restartedMain] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'environmentManager': registering with JMX server as MBean [org.springframework.cloud.context.environment:name=environmentManager,type=EnvironmentManager]
    2016-12-28 03:49:21.647  INFO ["scs-producer",,,] 5 --- [  restartedMain] o.a.c.c.StandardService                  : Stopping service Tomcat
    2016-12-28 03:49:21.697  INFO ["scs-producer",,,] 5 --- [  restartedMain] utoConfigurationReportLoggingInitializer :
    
    Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
    2016-12-28 03:49:21.713 ERROR ["scs-producer",,,] 5 --- [  restartedMain] o.s.b.SpringApplication                  : Application startup failed
    
    org.springframework.jmx.export.UnableToRegisterMBeanException: Unable to register MBean [org.springframework.cloud.context.environment.EnvironmentManager@5d22f775] with key 'environmentManager'; nested exception is javax.management.InstanceAlreadyExistsException: org.springframework.cloud.context.environment:name=environmentManager,type=EnvironmentManager
          at org.springframework.jmx.export.MBeanExporter.registerBeanNameOrInstance(MBeanExporter.java:625) ~[spring-context-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
          at org.springframework.jmx.export.MBeanExporter.registerBeans(MBeanExporter.java:550) ~[spring-context-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
          at org.springframework.jmx.export.MBeanExporter.afterSingletonsInstantiated(MBeanExporter.java:432) ~[spring-context-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
          at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:774) ~[spring-beans-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
          at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866) ~[spring-context-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
          at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) ~[spring-context-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
          at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
          at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
          at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
          at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
          at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
          at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
          at com.dw.test.ScsProducerApplication.main(ScsProducerApplication.java:24) [?:?]
          at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
          at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
          at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
          at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
          at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
    Caused by: javax.management.InstanceAlreadyExistsException: org.springframework.cloud.context.environment:name=environmentManager,type=EnvironmentManager
          at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437) ~[?:1.8.0_112]
          at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898) ~[?:1.8.0_112]
          at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966) ~[?:1.8.0_112]
          at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900) ~[?:1.8.0_112]
          at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324) ~[?:1.8.0_112]
          at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522) ~[?:1.8.0_112]
          at org.springframework.jmx.support.MBeanRegistrationSupport.doRegister(MBeanRegistrationSupport.java:195) ~[spring-context-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
          at org.springframework.jmx.export.MBeanExporter.registerBeanInstance(MBeanExporter.java:678) ~[spring-context-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
          at org.springframework.jmx.export.MBeanExporter.registerBeanNameOrInstance(MBeanExporter.java:615) ~[spring-context-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
          ... 17 more
    
    2016-12-28 03:49:21.729  INFO ["scs-producer",,,] 5 --- [  restartedMain] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@2fb1c977: startup date [Wed Dec 28 03:48:37 GMT 2016]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@4b45caee
    2016-12-28 03:49:21.734  WARN ["scs-producer",,,] 5 --- [  restartedMain] ationConfigEmbeddedWebApplicationContext : Exception thrown from LifecycleProcessor on context close
    
    java.lang.IllegalStateException: LifecycleProcessor not initialized - call 'refresh' before invoking lifecycle methods via the context: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@2fb1c977: startup date [Wed Dec 28 03:48:37 GMT 2016]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@4b45caee
          at org.springframework.context.support.AbstractApplicationContext.getLifecycleProcessor(AbstractApplicationContext.java:417) ~[spring-context-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
          at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1002) [spring-context-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
          at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:961) [spring-context-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
          at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:818) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
          at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
          at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
          at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175) [spring-boot-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
          at com.dw.test.ScsProducerApplication.main(ScsProducerApplication.java:24) [?:?]
          at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
          at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
          at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
          at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
          at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
    
    2016-12-28 03:49:21.748  INFO ["scs-producer",,,] 5 --- [  restartedMain] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
    2016-12-28 03:49:21.749  INFO ["scs-producer",,,] 5 --- [  restartedMain] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
    2016-12-28 03:49:21.757  INFO ["scs-producer",,,] 5 --- [  restartedMain] o.s.i.m.IntegrationMBeanExporter         : Unregistering JMX-exposed beans on shutdown

My remote client logs

      .   ____          _                                              __ _ _
     /\\ / ___'_ __ _ _(_)_ __  __ _          ___               _      \ \ \ \
    ( ( )\___ | '_ | '_| | '_ \/ _` |        | _ \___ _ __  ___| |_ ___ \ \ \ \
     \\/  ___)| |_)| | | | | || (_| []::::::[]   / -_) '  \/ _ \  _/ -_) ) ) ) )
      '  |____| .__|_| |_|_| |_\__, |        |_|_\___|_|_|_\___/\__\___|/ / / /
     =========|_|==============|___/===================================/_/_/_/
     :: Spring Boot Remote ::  (v1.4.2.RELEASE)
    
    2016-12-28 09:17:19.455  INFO ["scs-producer",,,] 9009 --- [           main] o.s.b.d.RemoteSpringApplication          : Starting RemoteSpringApplication v1.4.2.RELEASE on Pratik-desktop with PID 9009 (/home/developer/.m2/repository/org/springframework/boot/spring-boot-devtools/1.4.2.RELEASE/spring-boot-devtools-1.4.2.RELEASE.jar started by developer in /media/dev/my-projects/scs-producer)
    2016-12-28 09:17:19.457  INFO ["scs-producer",,,] 9009 --- [           main] o.s.b.d.RemoteSpringApplication          : No active profile set, falling back to default profiles: default
    2016-12-28 09:17:19.479  INFO ["scs-producer",,,] 9009 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@268f106e: startup date [Wed Dec 28 09:17:19 IST 2016]; root of context hierarchy
    2016-12-28 09:17:20.184  WARN ["scs-producer",,,] 9009 --- [           main] o.s.b.d.r.c.RemoteClientConfiguration    : The connection to http://10.2.0.100:8080 is insecure. You should use a URL starting with 'https://'.
    2016-12-28 09:17:20.252  INFO ["scs-producer",,,] 9009 --- [           main] o.s.b.d.a.OptionalLiveReloadServer       : LiveReload server is running on port 35729
    2016-12-28 09:17:20.277  INFO ["scs-producer",,,] 9009 --- [           main] o.s.b.d.RemoteSpringApplication          : Started RemoteSpringApplication in 1.137 seconds (JVM running for 1.796)
    2016-12-28 09:18:38.377  INFO ["scs-producer",,,] 9009 --- [   File Watcher] o.s.b.d.r.c.ClassPathChangeUploader      : Uploaded 2 class resources
    2016-12-28 09:18:38.755  INFO ["scs-producer",,,] 9009 --- [pool-2-thread-1] o.s.b.d.r.c.DelayedLiveReloadTrigger     : Remote server has changed, triggering LiveReload

My pom.xml

    <parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.4.2.RELEASE</version>
		<relativePath />
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-stream-kafka</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-zipkin</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-log4j2</artifactId>
		</dependency>
	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>Camden.SR3</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

- When I am trying to run the same application without spring-cloud-stream  related dependencies It is reloading spring without any error.

## versions
- spring-boot : 1.4.2.RELEASE
- spring-boot-devtools : 1.4.2.RELEASE
- spring-cloud-stream : 1.1.0.RELEASE
- spring-cloud-starter-stream-kafka : 1.1.0.RELEASE

**Comment by wilkinsona** [comment]
This may well be a duplicate of #7179. Can you please try with Spring Boot 1.4.3?

**Comment by peanutpi** [comment]
Reproducible with spring-boot 1.4.3.RELEASE

**Comment by wilkinsona** [comment]
@peanutpi Thanks. Can you please put together a small Spring Cloud Stream application that reproduces the problem. The fewer dependencies it has and the simpler the environment it uses (no Docker or Vagrant, for example) the more likely that someone will have time to dig into this for you.

**Comment by peanutpi** [comment]
@wilkinsona Thanks for the reply. I think the culprit is "spring-cloud-starter-zipkin". after removing this from pom.xml devtool is working as expected.

I'll upload a simple project which contains this dependencies. Do I have to create a new issue ?

**Comment by wilkinsona** [comment]
> I'll upload a simple project which contains this dependencies

Thank you

> I'll upload a simple project which contains this dependencies

No, not yet at least. Lets use this one until we figure out where the problem is

**Comment by peanutpi** [comment]
You can checkout this project to try on. https://github.com/peanutpi/sb-devtool-demo

**Comment by wilkinsona** [comment]
@peanutpi Thanks for the sample. Unfortunately, I can't recreate the problem with it.

It starts up successfully and also restarts successfully when I make a change (I removed your configuration for a specific trigger file). I've also checked in JConsole that the problematic MBean, `environmentManager`, is registered.

I've done the above with both local and remove DevTools. What steps do I need to take to use your sample to reproduce the problem?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by peanutpi** [comment]
@wilkinsona When we tried to reproduce this issue we are getting this error 6/10 times. and there are no extra steps.

**Comment by wilkinsona** [comment]
Sorry, I can't reproduce this. I've just had at least 20 successful restarts in a row.

The log that you've included above doesn't show the output from when the context was closed immediately prior to the restart. It should contain lines like this:

```
2017-02-15 16:59:21.605  INFO [-,,,] 77887 --- [     Thread-116] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2017-02-15 16:59:21.605  INFO [-,,,] 77887 --- [     Thread-116] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans
```

Perhaps something went wrong when the MBean was being unregistered?

Something else you could try is to add an `MBeanExportListener` to verify that all of the MBeans are being unregistered when the context is closed:

```java
package com.example;

import javax.management.ObjectName;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.jmx.export.MBeanExporter;
import org.springframework.jmx.export.MBeanExporterListener;

@SpringBootApplication
public class SbDevtoolDemoApplication {

	public static void main(String[] args) {
		SpringApplication.run(SbDevtoolDemoApplication.class, args);
	}

	SbDevtoolDemoApplication(MBeanExporter exporter) {
		exporter.setListeners(new MBeanExporterListener() {

			@Override
			public void mbeanRegistered(ObjectName objectName) {

			}

			@Override
			public void mbeanUnregistered(ObjectName objectName) {
				System.out.println(objectName);
			}

		});
	}

}
```

**Comment by peanutpi** [comment]
For now I am closing the issue. I am not able to make time for this.
