### ISSUE TITLE
Cannot decrypt password from another http client except curl

### ISSUE THREAD

**Issue by searhiy** [spring-projects/spring-boot#7805]
I'm working with spring-cloud-config-server and encrypt/decrypt APIs

In documentation you worked with curl http client:

```
curl localhost:8888/encrypt -d mysicret
AEAx7i0kZwFXPPNoQEa/0YDppxgbnF0G9LI2m0+GmQ7Je8u82wua5MYcTx9Hf6+YfMCS8W8OWGl1JlMWQjNUaax8D3kNG2DFmw7ZnPCbWKnEWvD7bbSWPP/7hjip2wlgqTo=

```
```
logs:
2017-01-02 14:53:03.641 DEBUG 15136 --- [8888-Acceptor-0] o.apache.tomcat.util.threads.LimitLatch  : Counting up[http-nio-8888-Acceptor-0] latch=1
2017-01-02 14:53:03.641 DEBUG 15136 --- [nio-8888-exec-2] o.a.coyote.http11.Http11InputBuffer      : Received [POST /encrypt HTTP/1.1
Host: localhost:8888
User-Agent: curl/7.50.1
Accept: */*
Content-Length: 8
Content-Type: application/x-www-form-urlencoded

mysicret]
2017-01-02 14:53:03.642 DEBUG 15136 --- [nio-8888-exec-2] o.a.c.authenticator.AuthenticatorBase    : Security checking request POST /encrypt
2017-01-02 14:53:03.642 DEBUG 15136 --- [nio-8888-exec-2] org.apache.catalina.realm.RealmBase      :   No applicable constraints defined
2017-01-02 14:53:03.642 DEBUG 15136 --- [nio-8888-exec-2] o.a.c.authenticator.AuthenticatorBase    :  Not subject to any constraint
2017-01-02 14:53:03.642 DEBUG 15136 --- [nio-8888-exec-2] org.apache.tomcat.util.http.Parameters   : Set encoding to UTF-8
2017-01-02 14:53:03.642 DEBUG 15136 --- [nio-8888-exec-2] org.apache.tomcat.util.http.Parameters   : Start processing with input [mysicret]
2017-01-02 14:53:03.642 DEBUG 15136 --- [nio-8888-exec-2] org.apache.tomcat.util.http.Parameters   : Parameter starting at position [0] and ending at position [8] with a value of [0] was not followed by an = character
2017-01-02 14:53:03.643 DEBUG 15136 --- [nio-8888-exec-2] o.s.b.w.f.OrderedRequestContextFilter    : Bound request context to thread: org.apache.catalina.connector.RequestFacade@3e17ea8b
2017-01-02 14:53:03.643 DEBUG 15136 --- [nio-8888-exec-2] o.s.web.servlet.DispatcherServlet        : DispatcherServlet with name 'dispatcherServlet' processing POST request for [/encrypt]
2017-01-02 14:53:03.643 DEBUG 15136 --- [nio-8888-exec-2] o.s.b.a.e.mvc.EndpointHandlerMapping     : Looking up handler method for path /encrypt
2017-01-02 14:53:03.643 DEBUG 15136 --- [nio-8888-exec-2] o.s.b.a.e.mvc.EndpointHandlerMapping     : Did not find handler method for [/encrypt]
2017-01-02 14:53:03.643 DEBUG 15136 --- [nio-8888-exec-2] s.w.s.m.m.a.RequestMappingHandlerMapping : Looking up handler method for path /encrypt
2017-01-02 14:53:03.643 DEBUG 15136 --- [nio-8888-exec-2] s.w.s.m.m.a.RequestMappingHandlerMapping : Returning handler method [public java.lang.String org.springframework.cloud.config.server.encryption.EncryptionController.encrypt(java.lang.String,org.springframework.http.MediaType)]
2017-01-02 14:53:03.643 DEBUG 15136 --- [nio-8888-exec-2] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'encryptionController'
2017-01-02 14:53:03.644 DEBUG 15136 --- [nio-8888-exec-2] m.m.a.RequestResponseBodyMethodProcessor : Read [class java.lang.String] as "application/x-www-form-urlencoded;charset=UTF-8" with [org.springframework.http.converter.StringHttpMessageConverter@45658133]
2017-01-02 14:53:03.651  INFO 15136 --- [nio-8888-exec-2] o.s.c.c.s.e.EncryptionController         : Encrypted data
2017-01-02 14:53:03.651 DEBUG 15136 --- [nio-8888-exec-2] m.m.a.RequestResponseBodyMethodProcessor : Written [AEAtyGdGRAPh27TEwWV1ZqREbM2mqcv6Fgbc5hDAc69dIndWR6xaFwE+CI2zd227Imo1xAC0dKglZO5yRYJdlErQWNvjcT3GmJ89X/rVPWdTrFIkKTZDfyzSAJMF3CcEEr0=] as "text/plain" using [org.springframework.http.converter.StringHttpMessageConverter@45658133]
2017-01-02 14:53:03.651 DEBUG 15136 --- [nio-8888-exec-2] o.s.web.servlet.DispatcherServlet        : Null ModelAndView returned to DispatcherServlet with name 'dispatcherServlet': assuming HandlerAdapter completed request handling
2017-01-02 14:53:03.652 DEBUG 15136 --- [nio-8888-exec-2] o.s.web.servlet.DispatcherServlet        : Successfully completed request
2017-01-02 14:53:03.652 DEBUG 15136 --- [nio-8888-exec-2] o.s.b.w.f.OrderedRequestContextFilter    : Cleared thread-bound request context: org.apache.catalina.connector.RequestFacade@3e17ea8b
2017-01-02 14:53:03.652 DEBUG 15136 --- [nio-8888-exec-2] o.apache.coyote.http11.Http11Processor   : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@16acf206:org.apache.tomcat.util.net.NioChannel@31525625:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:8888 remote=/0:0:0:0:0:0:0:1:59689]], Status in: [OPEN_READ], State out: [OPEN]
2017-01-02 14:53:03.655 DEBUG 15136 --- [nio-8888-exec-3] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header

java.io.EOFException: null
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.fillReadBuffer(NioEndpoint.java:1202) ~[tomcat-embed-core-8.5.6.jar:8.5.6]
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.read(NioEndpoint.java:1149) ~[tomcat-embed-core-8.5.6.jar:8.5.6]
	at org.apache.coyote.http11.Http11InputBuffer.fill(Http11InputBuffer.java:742) ~[tomcat-embed-core-8.5.6.jar:8.5.6]
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:404) ~[tomcat-embed-core-8.5.6.jar:8.5.6]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:667) ~[tomcat-embed-core-8.5.6.jar:8.5.6]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.6.jar:8.5.6]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802) [tomcat-embed-core-8.5.6.jar:8.5.6]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410) [tomcat-embed-core-8.5.6.jar:8.5.6]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.6.jar:8.5.6]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_101]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.6.jar:8.5.6]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]

2017-01-02 14:53:03.656 DEBUG 15136 --- [nio-8888-exec-3] o.apache.coyote.http11.Http11Processor   : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@16acf206:org.apache.tomcat.util.net.NioChannel@31525625:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:8888 remote=/0:0:0:0:0:0:0:1:59689]], Status in: [OPEN_READ], State out: [CLOSED]
2017-01-02 14:53:03.656 DEBUG 15136 --- [nio-8888-exec-3] o.apache.tomcat.util.threads.LimitLatch  : Counting down[http-nio-8888-exec-3] latch=1

```
```

curl localhost:8888/decrypt -d AEBhVUHaNVsBsMuwrW7sEAsgmyyYNLvHV4LMcfpb4aQZee8+vr4G6JvKRzR/02ZVGDTLacsbhfdN7c3jzsNfCe58aUPqlpFT9UAEp0C88pHlx7fib8R+XDQczy3Gy+Faw8Y=
mysicret

```
```

logs: 
2017-01-02 14:53:54.382 DEBUG 15136 --- [8888-Acceptor-0] o.apache.tomcat.util.threads.LimitLatch  : Counting up[http-nio-8888-Acceptor-0] latch=1
2017-01-02 14:53:54.383 DEBUG 15136 --- [nio-8888-exec-6] o.a.coyote.http11.Http11InputBuffer      : Received [POST /decrypt HTTP/1.1
Host: localhost:8888
User-Agent: curl/7.50.1
Accept: */*
Content-Length: 132
Content-Type: application/x-www-form-urlencoded

AEBQzoGzPA9xK5IScUtLBfXGcJ0yOQW1AH8MLNJAtX3EyNpnAqZtHp3TqYiqyap0nf5n0fNE+WcUmY/HrCNzBz08gqJXTyc6evhruxkZ7GcJmNNADBD8KqFrjNunkryMZ7c=]
2017-01-02 14:53:54.384 DEBUG 15136 --- [nio-8888-exec-6] o.a.c.authenticator.AuthenticatorBase    : Security checking request POST /decrypt
2017-01-02 14:53:54.384 DEBUG 15136 --- [nio-8888-exec-6] org.apache.catalina.realm.RealmBase      :   No applicable constraints defined
2017-01-02 14:53:54.384 DEBUG 15136 --- [nio-8888-exec-6] o.a.c.authenticator.AuthenticatorBase    :  Not subject to any constraint
2017-01-02 14:53:54.384 DEBUG 15136 --- [nio-8888-exec-6] org.apache.tomcat.util.http.Parameters   : Set encoding to UTF-8
2017-01-02 14:53:54.385 DEBUG 15136 --- [nio-8888-exec-6] org.apache.tomcat.util.http.Parameters   : Start processing with input [AEBQzoGzPA9xK5IScUtLBfXGcJ0yOQW1AH8MLNJAtX3EyNpnAqZtHp3TqYiqyap0nf5n0fNE+WcUmY/HrCNzBz08gqJXTyc6evhruxkZ7GcJmNNADBD8KqFrjNunkryMZ7c=]
2017-01-02 14:53:54.385 DEBUG 15136 --- [nio-8888-exec-6] o.s.b.w.f.OrderedRequestContextFilter    : Bound request context to thread: org.apache.catalina.connector.RequestFacade@3e17ea8b
2017-01-02 14:53:54.385 DEBUG 15136 --- [nio-8888-exec-6] o.s.web.servlet.DispatcherServlet        : DispatcherServlet with name 'dispatcherServlet' processing POST request for [/decrypt]
2017-01-02 14:53:54.385 DEBUG 15136 --- [nio-8888-exec-6] o.s.b.a.e.mvc.EndpointHandlerMapping     : Looking up handler method for path /decrypt
2017-01-02 14:53:54.385 DEBUG 15136 --- [nio-8888-exec-6] o.s.b.a.e.mvc.EndpointHandlerMapping     : Did not find handler method for [/decrypt]
2017-01-02 14:53:54.385 DEBUG 15136 --- [nio-8888-exec-6] s.w.s.m.m.a.RequestMappingHandlerMapping : Looking up handler method for path /decrypt
2017-01-02 14:53:54.385 DEBUG 15136 --- [nio-8888-exec-6] s.w.s.m.m.a.RequestMappingHandlerMapping : Returning handler method [public java.lang.String org.springframework.cloud.config.server.encryption.EncryptionController.decrypt(java.lang.String,org.springframework.http.MediaType)]
2017-01-02 14:53:54.385 DEBUG 15136 --- [nio-8888-exec-6] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'encryptionController'
2017-01-02 14:53:54.386 DEBUG 15136 --- [nio-8888-exec-6] m.m.a.RequestResponseBodyMethodProcessor : Read [class java.lang.String] as "application/x-www-form-urlencoded;charset=UTF-8" with [org.springframework.http.converter.StringHttpMessageConverter@45658133]
2017-01-02 14:53:54.393  INFO 15136 --- [nio-8888-exec-6] o.s.c.c.s.e.EncryptionController         : Decrypted cipher data
2017-01-02 14:53:54.394 DEBUG 15136 --- [nio-8888-exec-6] m.m.a.RequestResponseBodyMethodProcessor : Written [mysicret] as "text/plain" using [org.springframework.http.converter.StringHttpMessageConverter@45658133]
2017-01-02 14:53:54.394 DEBUG 15136 --- [nio-8888-exec-6] o.s.web.servlet.DispatcherServlet        : Null ModelAndView returned to DispatcherServlet with name 'dispatcherServlet': assuming HandlerAdapter completed request handling
2017-01-02 14:53:54.394 DEBUG 15136 --- [nio-8888-exec-6] o.s.web.servlet.DispatcherServlet        : Successfully completed request
2017-01-02 14:53:54.394 DEBUG 15136 --- [nio-8888-exec-6] o.s.b.w.f.OrderedRequestContextFilter    : Cleared thread-bound request context: org.apache.catalina.connector.RequestFacade@3e17ea8b
2017-01-02 14:53:54.394 DEBUG 15136 --- [nio-8888-exec-6] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header

java.io.EOFException: null
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.fillReadBuffer(NioEndpoint.java:1202) ~[tomcat-embed-core-8.5.6.jar:8.5.6]
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.read(NioEndpoint.java:1149) ~[tomcat-embed-core-8.5.6.jar:8.5.6]
	at org.apache.coyote.http11.Http11InputBuffer.fill(Http11InputBuffer.java:742) ~[tomcat-embed-core-8.5.6.jar:8.5.6]
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:404) ~[tomcat-embed-core-8.5.6.jar:8.5.6]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:667) ~[tomcat-embed-core-8.5.6.jar:8.5.6]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.6.jar:8.5.6]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802) [tomcat-embed-core-8.5.6.jar:8.5.6]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410) [tomcat-embed-core-8.5.6.jar:8.5.6]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.6.jar:8.5.6]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_101]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.6.jar:8.5.6]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]

2017-01-02 14:53:54.395 DEBUG 15136 --- [nio-8888-exec-6] o.apache.coyote.http11.Http11Processor   : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@143be04d:org.apache.tomcat.util.net.NioChannel@31525625:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:8888 remote=/0:0:0:0:0:0:0:1:59698]], Status in: [OPEN_READ], State out: [CLOSED]
2017-01-02 14:53:54.395 DEBUG 15136 --- [nio-8888-exec-6] o.apache.tomcat.util.threads.LimitLatch  : Counting down[http-nio-8888-exec-6] latch=1


```

But it doesn't work with other http clients:
1. Postman: decrypt

```
2017-01-02 14:55:38.299 DEBUG 15136 --- [8888-Acceptor-0] o.apache.tomcat.util.threads.LimitLatch  : Counting up[http-nio-8888-Acceptor-0] latch=1
2017-01-02 14:55:38.299 DEBUG 15136 --- [nio-8888-exec-9] o.a.coyote.http11.Http11InputBuffer      : Received [POST /decrypt HTTP/1.1
Host: localhost:8888
Connection: keep-alive
Content-Length: 265
Postman-Token: 30786004-a8ab-83b5-1704-0b813e1b3b37
Cache-Control: no-cache
Origin: chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
Content-Type: text/plain
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.8

------WebKitFormBoundaryYhWLZEtIrmGFR9p0
Content-Disposition: form-data; name="-d"

AEAx7i0kZwFXPPNoQEa/0YDppxgbnF0G9LI2m0+GmQ7Je8u82wua5MYcTx9Hf6+YfMCS8W8OWGl1JlMWQjNUaax8D3kNG2DFmw7ZnPCbWKnEWvD7bbSWPP/7hjip2wlgqTo=
------WebKitFormBoundaryYhWLZEtIrmGFR9p0--
]
2017-01-02 14:55:38.299 DEBUG 15136 --- [nio-8888-exec-9] o.a.c.authenticator.AuthenticatorBase    : Security checking request POST /decrypt
2017-01-02 14:55:38.299 DEBUG 15136 --- [nio-8888-exec-9] org.apache.catalina.realm.RealmBase      :   No applicable constraints defined
2017-01-02 14:55:38.299 DEBUG 15136 --- [nio-8888-exec-9] o.a.c.authenticator.AuthenticatorBase    :  Not subject to any constraint
2017-01-02 14:55:38.299 DEBUG 15136 --- [nio-8888-exec-9] org.apache.tomcat.util.http.Parameters   : Set encoding to UTF-8
2017-01-02 14:55:38.300 DEBUG 15136 --- [nio-8888-exec-9] o.s.b.w.f.OrderedRequestContextFilter    : Bound request context to thread: org.apache.catalina.connector.RequestFacade@3e17ea8b
2017-01-02 14:55:38.300 DEBUG 15136 --- [nio-8888-exec-9] o.s.web.servlet.DispatcherServlet        : DispatcherServlet with name 'dispatcherServlet' processing POST request for [/decrypt]
2017-01-02 14:55:38.300 DEBUG 15136 --- [nio-8888-exec-9] o.s.b.a.e.mvc.EndpointHandlerMapping     : Looking up handler method for path /decrypt
2017-01-02 14:55:38.300 DEBUG 15136 --- [nio-8888-exec-9] o.s.b.a.e.mvc.EndpointHandlerMapping     : Did not find handler method for [/decrypt]
2017-01-02 14:55:38.300 DEBUG 15136 --- [nio-8888-exec-9] s.w.s.m.m.a.RequestMappingHandlerMapping : Looking up handler method for path /decrypt
2017-01-02 14:55:38.300 DEBUG 15136 --- [nio-8888-exec-9] s.w.s.m.m.a.RequestMappingHandlerMapping : Returning handler method [public java.lang.String org.springframework.cloud.config.server.encryption.EncryptionController.decrypt(java.lang.String,org.springframework.http.MediaType)]
2017-01-02 14:55:38.300 DEBUG 15136 --- [nio-8888-exec-9] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'encryptionController'
2017-01-02 14:55:38.301 DEBUG 15136 --- [nio-8888-exec-9] m.m.a.RequestResponseBodyMethodProcessor : Read [class java.lang.String] as "text/plain;charset=UTF-8" with [org.springframework.http.converter.StringHttpMessageConverter@45658133]
2017-01-02 14:55:38.304 DEBUG 15136 --- [nio-8888-exec-9] .m.m.a.ExceptionHandlerExceptionResolver : Resolving exception from handler [public java.lang.String org.springframework.cloud.config.server.encryption.EncryptionController.decrypt(java.lang.String,org.springframework.http.MediaType)]: org.springframework.cloud.config.server.encryption.InvalidCipherException
2017-01-02 14:55:38.304 DEBUG 15136 --- [nio-8888-exec-9] .m.m.a.ExceptionHandlerExceptionResolver : Invoking @ExceptionHandler method: public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.cloud.config.server.encryption.EncryptionController.invalidCipher()
2017-01-02 14:55:38.305 DEBUG 15136 --- [nio-8888-exec-9] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : Written [{description=Text not encrypted with this key, status=INVALID}] as "application/json" using [org.springframework.http.converter.json.MappingJackson2HttpMessageConverter@1665fa54]
2017-01-02 14:55:38.305 DEBUG 15136 --- [nio-8888-exec-9] o.s.web.servlet.DispatcherServlet        : Null ModelAndView returned to DispatcherServlet with name 'dispatcherServlet': assuming HandlerAdapter completed request handling
2017-01-02 14:55:38.305 DEBUG 15136 --- [nio-8888-exec-9] o.s.web.servlet.DispatcherServlet        : Successfully completed request
2017-01-02 14:55:38.305 DEBUG 15136 --- [nio-8888-exec-9] o.s.b.w.f.OrderedRequestContextFilter    : Cleared thread-bound request context: org.apache.catalina.connector.RequestFacade@3e17ea8b
2017-01-02 14:55:38.307 DEBUG 15136 --- [nio-8888-exec-9] o.apache.coyote.http11.Http11Processor   : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@156571b2:org.apache.tomcat.util.net.NioChannel@31525625:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:8888 remote=/0:0:0:0:0:0:0:1:59716]], Status in: [OPEN_READ], State out: [CLOSED]
2017-01-02 14:55:38.307 DEBUG 15136 --- [nio-8888-exec-9] o.apache.tomcat.util.threads.LimitLatch  : Counting down[http-nio-8888-exec-9] latch=1
```

2. Intellij REST client: decrypt

```
2017-01-02 14:56:42.868 DEBUG 15136 --- [8888-Acceptor-0] o.apache.tomcat.util.threads.LimitLatch  : Counting up[http-nio-8888-Acceptor-0] latch=1
2017-01-02 14:56:42.869 DEBUG 15136 --- [nio-8888-exec-1] o.a.coyote.http11.Http11InputBuffer      : Received [POST /decrypt HTTP/1.1
Accept: */*
Content-Type: text/plain
Content-Length: 145
Host: localhost:8888
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.2 (Java/1.8.0_112-release)
Accept-Encoding: gzip,deflate

-d=AEAx7i0kZwFXPPNoQEa%2F0YDppxgbnF0G9LI2m0%2BGmQ7Je8u82wua5MYcTx9Hf6%2BYfMCS8W8OWGl1JlMWQjNUaax8D3kNG2DFmw7ZnPCbWKnEWvD7bbSWPP%2F7hjip2wlgqTo%3D]
2017-01-02 14:56:42.869 DEBUG 15136 --- [nio-8888-exec-1] o.a.c.authenticator.AuthenticatorBase    : Security checking request POST /decrypt
2017-01-02 14:56:42.869 DEBUG 15136 --- [nio-8888-exec-1] org.apache.catalina.realm.RealmBase      :   No applicable constraints defined
2017-01-02 14:56:42.869 DEBUG 15136 --- [nio-8888-exec-1] o.a.c.authenticator.AuthenticatorBase    :  Not subject to any constraint
2017-01-02 14:56:42.869 DEBUG 15136 --- [nio-8888-exec-1] org.apache.tomcat.util.http.Parameters   : Set encoding to UTF-8
2017-01-02 14:56:42.870 DEBUG 15136 --- [nio-8888-exec-1] o.s.b.w.f.OrderedRequestContextFilter    : Bound request context to thread: org.apache.catalina.connector.RequestFacade@3e17ea8b
2017-01-02 14:56:42.870 DEBUG 15136 --- [nio-8888-exec-1] o.s.web.servlet.DispatcherServlet        : DispatcherServlet with name 'dispatcherServlet' processing POST request for [/decrypt]
2017-01-02 14:56:42.870 DEBUG 15136 --- [nio-8888-exec-1] o.s.b.a.e.mvc.EndpointHandlerMapping     : Looking up handler method for path /decrypt
2017-01-02 14:56:42.870 DEBUG 15136 --- [nio-8888-exec-1] o.s.b.a.e.mvc.EndpointHandlerMapping     : Did not find handler method for [/decrypt]
2017-01-02 14:56:42.870 DEBUG 15136 --- [nio-8888-exec-1] s.w.s.m.m.a.RequestMappingHandlerMapping : Looking up handler method for path /decrypt
2017-01-02 14:56:42.870 DEBUG 15136 --- [nio-8888-exec-1] s.w.s.m.m.a.RequestMappingHandlerMapping : Returning handler method [public java.lang.String org.springframework.cloud.config.server.encryption.EncryptionController.decrypt(java.lang.String,org.springframework.http.MediaType)]
2017-01-02 14:56:42.870 DEBUG 15136 --- [nio-8888-exec-1] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'encryptionController'
2017-01-02 14:56:42.870 DEBUG 15136 --- [nio-8888-exec-1] m.m.a.RequestResponseBodyMethodProcessor : Read [class java.lang.String] as "text/plain;charset=UTF-8" with [org.springframework.http.converter.StringHttpMessageConverter@45658133]
2017-01-02 14:56:42.874 DEBUG 15136 --- [nio-8888-exec-1] .m.m.a.ExceptionHandlerExceptionResolver : Resolving exception from handler [public java.lang.String org.springframework.cloud.config.server.encryption.EncryptionController.decrypt(java.lang.String,org.springframework.http.MediaType)]: org.springframework.cloud.config.server.encryption.InvalidCipherException
2017-01-02 14:56:42.874 DEBUG 15136 --- [nio-8888-exec-1] .m.m.a.ExceptionHandlerExceptionResolver : Invoking @ExceptionHandler method: public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.cloud.config.server.encryption.EncryptionController.invalidCipher()
2017-01-02 14:56:42.875 DEBUG 15136 --- [nio-8888-exec-1] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : Written [{description=Text not encrypted with this key, status=INVALID}] as "application/json" using [org.springframework.http.converter.json.MappingJackson2HttpMessageConverter@1665fa54]
2017-01-02 14:56:42.875 DEBUG 15136 --- [nio-8888-exec-1] o.s.web.servlet.DispatcherServlet        : Null ModelAndView returned to DispatcherServlet with name 'dispatcherServlet': assuming HandlerAdapter completed request handling
2017-01-02 14:56:42.875 DEBUG 15136 --- [nio-8888-exec-1] o.s.web.servlet.DispatcherServlet        : Successfully completed request
2017-01-02 14:56:42.875 DEBUG 15136 --- [nio-8888-exec-1] o.s.b.w.f.OrderedRequestContextFilter    : Cleared thread-bound request context: org.apache.catalina.connector.RequestFacade@3e17ea8b
2017-01-02 14:56:42.876 DEBUG 15136 --- [nio-8888-exec-1] o.apache.coyote.http11.Http11Processor   : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@398ba60c:org.apache.tomcat.util.net.NioChannel@31525625:java.nio.channels.SocketChannel[connected local=/127.0.0.1:8888 remote=/127.0.0.1:59723]], Status in: [OPEN_READ], State out: [CLOSED]
2017-01-02 14:56:42.876 DEBUG 15136 --- [nio-8888-exec-1] o.apache.tomcat.util.threads.LimitLatch  : Counting down[http-nio-8888-exec-1] latch=1

```

response JSON in both cases (bad request):

```
{
  "description": "Text not encrypted with this key",
  "status": "INVALID"
}
```

keytool -genkey -keyalg RSA -alias mykey2 -dname "CN=Web Server,OU=Unit,O=Organization,L=City,S=State,C=US" -keypass password -keystore sk_server2.jks -storepass store2 -keysize 512

Spring-Boot 1.4.3.RELEASE

application.yaml
```
encrypt:
  key-store:
    location: classpath:sk_server2.jks
    password: store2
    alias: mykey2
    secret: password
```

**Comment by searhiy** [comment]
It's work. I had to insert this string as text field. Sorry

**Comment by snicoll** [comment]
@searhiy besides, this is the tracker of Spring Boot here, not Spring Cloud. Please consider this next time you think you've found an issue.
