### ISSUE TITLE
Can't change html when using "spring-boot-starter-groovy-templates" with Eclipse.

### ISSUE THREAD

**Issue by cebbec** [spring-projects/spring-boot#7892]
Hi,

Same issue that [#4921](https://github.com/spring-projects/spring-boot/issues/4921) but with the spring-boot-starter-groovy-templates.

Here is my build.gradle

```
apply plugin: 'groovy'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'

buildscript {
    repositories {
        jcenter()
        maven { url 'http://repo.spring.io/snapshot' }
        maven { url 'http://repo.spring.io/milestone' }
    }
    dependencies { classpath 'org.springframework.boot:spring-boot-gradle-plugin:1.4.3.RELEASE' }
}

repositories {
    jcenter()
    maven { url "http://repo.spring.io/snapshot" }
    maven { url "http://repo.spring.io/milestone" }
}

ext {
    groovyVersion = '2.4.7'
}

dependencies {
    compile("org.springframework.boot:spring-boot-starter-web")
    compile("org.springframework.boot:spring-boot-devtools")
    compile 'org.springframework.boot:spring-boot-starter-groovy-templates'
}
```

The project is nearly the same as [https://github.com/kurofune/spring-boot-sample](https://github.com/a-monty-only/spring-boot-sample) except the template file which is a groovy template.

After the first modification of the template file, I encounter the `Contains: Could not delete: ...\bin\templates\index.tpl.
java.nio.file.FileSystemException: ...\bin\templates\index.tpl.`

I am on windows 7 x64.

I also try the latest snapshot `classpath 'org.springframework.boot:spring-boot-gradle-plugin:2.0.0.BUILD-SNAPSHOT`, same error.

If you have any question...thanks

**Comment by philwebb** [comment]
Are you able to share the project that you're using to test this on github?

**Comment by cebbec** [comment]
Here is the sample project [sample-groovy-template](https://github.com/cebbec/spring-boot-sample). To reproduce, you have to run the application and while it is running, modify the index.tpl. I have the livereload plugin on chrome to see changes in realtime.

**Comment by philwebb** [comment]
I'm having some trouble replicating this issue (just getting my Windows VM to load is causing trouble). Looking though the code, it looks like we handle Groovy Templates quite differently to Mustache. I don't think we've got the same underlying problem as #4921.

Our Groovy Template support delegates to `groovy.text.markup.MarkupTemplateEngine` and we don't appear to open any files ourselves. I can't see anything obvious in the Groovy code either that would retain a file lock.

How are you actually running your application? Is it from an IDE (if so which one)? Is it possible that something else is keeping a lock on that file?

**Comment by wilkinsona** [comment]
I can reproduce this using Windows 7 in a VM running the app in STS 3.8.3. It's the app's process that's keeping the file open.

**Comment by wilkinsona** [comment]
It's a bug in Groovy. Here's the stack trace of when the file handle that isn't closed is opened:

```
[java.io.FileInputStream opened by thread http-nio-8080-exec-1 from Wed Jan 18 09:59:53 GMT 2017
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at sun.net.www.protocol.file.FileURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.file.FileURLConnection.initializeHeaders(Unknown Source)
	at sun.net.www.protocol.file.FileURLConnection.getHeaderField(Unknown Source)
	at java.net.URLConnection.getContentEncoding(Unknown Source)
	at groovy.lang.GroovyCodeSource.<init>(GroovyCodeSource.java:176)
	at groovy.text.markup.MarkupTemplateEngine$MarkupTemplateMaker.<init>(MarkupTemplateEngine.java:222)
	at groovy.text.markup.MarkupTemplateEngine.createTemplateByPath(MarkupTemplateEngine.java:145)
	at org.springframework.web.servlet.view.groovy.GroovyMarkupView.getTemplate(GroovyMarkupView.java:124)
	at org.springframework.web.servlet.view.groovy.GroovyMarkupView.renderMergedTemplateModel(GroovyMarkupView.java:114)
	at org.springframework.web.servlet.view.AbstractTemplateView.renderMergedOutputModel(AbstractTemplateView.java:167)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1257)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1037)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:980)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:89)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)
```

I've opened GROOVY-8056. We'll pick up a new version of Groovy that fixes the problem as and when it's available.
