### ISSUE TITLE
Provide dependency management for commons-lang3

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#7896]
Related to htmlunit upgrade. In the [CFP app](https://github.com/snicoll-demos/cfp-example), we use `webjars-locator` that brings commons-lang 3.1 - HtmlUnit requires 3.4

Since we don't have dependency management for commons-lang3, using HTML unit with Boot 1.5 SNAPSHOT leads to

```
Caused by: java.lang.NoSuchMethodError: org.apache.commons.lang3.StringUtils.countMatches(Ljava/lang/CharSequence;C)I
	at com.gargoylesoftware.htmlunit.javascript.host.css.ComputedCSSStyleDeclaration.getEmptyHeight(ComputedCSSStyleDeclaration.java:1267)
	at com.gargoylesoftware.htmlunit.javascript.host.css.ComputedCSSStyleDeclaration.getCalculatedHeight(ComputedCSSStyleDeclaration.java:1186)
	at com.gargoylesoftware.htmlunit.javascript.host.css.ComputedCSSStyleDeclaration.getCalculatedHeight(ComputedCSSStyleDeclaration.java:1160)
	at com.gargoylesoftware.htmlunit.javascript.host.css.ComputedCSSStyleDeclaration.getTop(ComputedCSSStyleDeclaration.java:1407)
	at com.gargoylesoftware.htmlunit.javascript.host.html.HTMLElement.getOffsetTop(HTMLElement.java:2420)
	at com.gargoylesoftware.htmlunit.javascript.host.html.HTMLElement.getPosY(HTMLElement.java:2342)
	at com.gargoylesoftware.htmlunit.javascript.host.event.MouseEvent.getScreenY(MouseEvent.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sourceforge.htmlunit.corejs.javascript.MemberBox.invoke(MemberBox.java:153)

```

**Comment by snicoll** [comment]
Only required once we upgrade htmlunit, see #7232
