### ISSUE TITLE
Upgrade to Narayana 5.5.1.Final

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#8096]

**Comment by wilkinsona** [comment]
This causes a test failure:

```
shouldGetConnectionAndCommit(org.springframework.boot.jta.narayana.NarayanaDataSourceBeanTests)  Time elapsed: 0.009 sec  <<< ERROR!
java.lang.NullPointerException: null
	at com.arjuna.ats.internal.jdbc.ConnectionImple.commit(ConnectionImple.java:280)
	at org.springframework.boot.jta.narayana.NarayanaDataSourceBeanTests.shouldGetConnectionAndCommit(NarayanaDataSourceBeanTests.java:94)
```

**Comment by wilkinsona** [comment]
This looks suspect too although it doesn't cause the test to fail:

```
java.lang.NullPointerException: null
	at com.arjuna.ats.internal.jdbc.ConnectionImple.getModifier(ConnectionImple.java:1087) ~[jdbc-5.5.1.Final.jar:5.5.1.Final]
	at com.arjuna.ats.internal.jdbc.ConnectionImple.getConnection(ConnectionImple.java:874) ~[jdbc-5.5.1.Final.jar:5.5.1.Final]
	at com.arjuna.ats.internal.jdbc.ConnectionImple.commit(ConnectionImple.java:280) ~[jdbc-5.5.1.Final.jar:5.5.1.Final]
	at org.springframework.boot.jta.narayana.NarayanaDataSourceBeanTests.shouldGetConnectionAndCommitWithCredentials(NarayanaDataSourceBeanTests.java:119) ~[test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_102]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283) [surefire-junit4-2.18.1.jar:2.18.1]
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173) [surefire-junit4-2.18.1.jar:2.18.1]
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153) [surefire-junit4-2.18.1.jar:2.18.1]
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128) [surefire-junit4-2.18.1.jar:2.18.1]
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203) [surefire-booter-2.18.1.jar:2.18.1]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155) [surefire-booter-2.18.1.jar:2.18.1]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103) [surefire-booter-2.18.1.jar:2.18.1]
```
