### ISSUE TITLE
spring-boot 1.4.4 causes deprecation warnings with Gradle 3.4-rc-1

### ISSUE THREAD

**Issue by huxi** [spring-projects/spring-boot#8120]
This is a follow-up to issue #7734.

> The ProjectDependency.getProjectConfiguration() method has been deprecated and is scheduled to be removed in Gradle 4.0.

> ModuleDependency.getConfiguration() has been deprecated and is scheduled to be removed in Gradle 4.0. Use ModuleDependency.getTargetConfiguration() instead.

## Relevant stack traces:
```
The ProjectDependency.getProjectConfiguration() method has been deprecated and is scheduled to be removed in Gradle 4.0.
        at org.gradle.api.internal.artifacts.dependencies.DefaultProjectDependency.getProjectConfiguration(DefaultProjectDependency.java:74)
        at org.gradle.api.internal.artifacts.dependencies.DefaultProjectDependency_Decorated.getProjectConfiguration(Unknown Source)
        at org.springframework.boot.gradle.repackage.ProjectLibraries.getLibrariesForFileDependencies(ProjectLibraries.java:131)
        at org.springframework.boot.gradle.repackage.ProjectLibraries.getLibraries(ProjectLibraries.java:113)
        at org.springframework.boot.gradle.repackage.ProjectLibraries.doWithLibraries(ProjectLibraries.java:90)
        at org.springframework.boot.gradle.repackage.RepackagePluginFeatures$RegisterInputsOutputsAction.addLibraryDependencies(RepackagePluginFeatures.java:158)
        at org.springframework.boot.gradle.repackage.RepackagePluginFeatures$RegisterInputsOutputsAction.setupInputOutputs(RepackagePluginFeatures.java:151)
        at org.springframework.boot.gradle.repackage.RepackagePluginFeatures$RegisterInputsOutputsAction.execute(RepackagePluginFeatures.java:136)
        at org.springframework.boot.gradle.repackage.RepackagePluginFeatures$RegisterInputsOutputsAction.execute(RepackagePluginFeatures.java:114)
        at org.gradle.internal.Actions$FilteredAction.execute(Actions.java:205)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:135)
        at org.gradle.api.internal.tasks.RealizableTaskCollection.all(RealizableTaskCollection.java:192)
        at org.gradle.api.internal.DefaultDomainObjectCollection.withType(DefaultDomainObjectCollection.java:158)
        at org.springframework.boot.gradle.repackage.RepackagePluginFeatures$1.execute(RepackagePluginFeatures.java:84)
        at org.springframework.boot.gradle.repackage.RepackagePluginFeatures$1.execute(RepackagePluginFeatures.java:81)
```

```
ModuleDependency.getConfiguration() has been deprecated and is scheduled to be removed in Gradle 4.0. Use ModuleDependency.getTargetConfiguration() instead.
        at org.gradle.api.internal.artifacts.dependencies.AbstractModuleDependency.getConfiguration(AbstractModuleDependency.java:56)
        at org.gradle.api.internal.artifacts.dependencies.DefaultProjectDependency_Decorated.getConfiguration(Unknown Source)
        at org.gradle.api.internal.artifacts.dependencies.DefaultProjectDependency.getProjectConfiguration(DefaultProjectDependency.java:75)
        at org.gradle.api.internal.artifacts.dependencies.DefaultProjectDependency_Decorated.getProjectConfiguration(Unknown Source)
        at org.springframework.boot.gradle.repackage.ProjectLibraries.getLibrariesForFileDependencies(ProjectLibraries.java:131)
        at org.springframework.boot.gradle.repackage.ProjectLibraries.getLibraries(ProjectLibraries.java:113)
        at org.springframework.boot.gradle.repackage.ProjectLibraries.doWithLibraries(ProjectLibraries.java:90)
        at org.springframework.boot.gradle.repackage.RepackagePluginFeatures$RegisterInputsOutputsAction.addLibraryDependencies(RepackagePluginFeatures.java:158)
        at org.springframework.boot.gradle.repackage.RepackagePluginFeatures$RegisterInputsOutputsAction.setupInputOutputs(RepackagePluginFeatures.java:151)
        at org.springframework.boot.gradle.repackage.RepackagePluginFeatures$RegisterInputsOutputsAction.execute(RepackagePluginFeatures.java:136)
        at org.springframework.boot.gradle.repackage.RepackagePluginFeatures$RegisterInputsOutputsAction.execute(RepackagePluginFeatures.java:114)
        at org.gradle.internal.Actions$FilteredAction.execute(Actions.java:205)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:135)
        at org.gradle.api.internal.tasks.RealizableTaskCollection.all(RealizableTaskCollection.java:192)
        at org.gradle.api.internal.DefaultDomainObjectCollection.withType(DefaultDomainObjectCollection.java:158)
        at org.springframework.boot.gradle.repackage.RepackagePluginFeatures$1.execute(RepackagePluginFeatures.java:84)
        at org.springframework.boot.gradle.repackage.RepackagePluginFeatures$1.execute(RepackagePluginFeatures.java:81)
```

This is just meant as a quick holler to make you aware of the issue.

**Comment by wilkinsona** [comment]
Thanks. We don't officially support Gradle 3.x with Boot 1.4's plugin. We've already fixed this in 1.5 which does support Gradle 3.x.

**Comment by huxi** [comment]
@wilkinsona Just double-checking: did you also fix the new deprecation warning that wasn't mentioned in the previous issue?

#7734 was only about 
> The ProjectDependency.getProjectConfiguration() method has been deprecated and is scheduled to be removed in Gradle 4.0.

while this one is also about
> ModuleDependency.getConfiguration() has been deprecated and is scheduled to be removed in Gradle 4.0. Use ModuleDependency.getTargetConfiguration() instead.

**Comment by wilkinsona** [comment]
Whoops. I missed the `ModuleDependency` part. Thanks for pointing it out.
