### ISSUE TITLE
Depending on both spring boot mongo and spring boot solr generates java.lang.IllegalStateException

### ISSUE THREAD

**Issue by aruberto** [spring-projects/spring-boot#8225]
When running a project that depends on both 'org.springframework.boot:spring-boot-starter-data-mongodb' and 'org.springframework.boot:spring-boot-starter-data-solr', the following exception is thrown:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'solrConverter': Initialization of bean failed; nested exception is org.springframework.beans.ConversionNotSupportedException: Failed to convert property value of type 'org.springframework.data.mongodb.core.convert.CustomConversions' to required type 'org.springframework.data.solr.core.convert.CustomConversions' for property 'customConversions'; nested exception is java.lang.IllegalStateException: Cannot convert value of type 'org.springframework.data.mongodb.core.convert.CustomConversions' to required type 'org.springframework.data.solr.core.convert.CustomConversions' for property 'customConversions': no matching editors or conversion strategy found
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866) ~[spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) ~[spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) [spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) [spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162) [spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151) [spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
	at io.github.aruberto.CustomConversionsBugApplication.main(CustomConversionsBugApplication.java:10) [main/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147) [idea_rt.jar:na]
Caused by: org.springframework.beans.ConversionNotSupportedException: Failed to convert property value of type 'org.springframework.data.mongodb.core.convert.CustomConversions' to required type 'org.springframework.data.solr.core.convert.CustomConversions' for property 'customConversions'; nested exception is java.lang.IllegalStateException: Cannot convert value of type 'org.springframework.data.mongodb.core.convert.CustomConversions' to required type 'org.springframework.data.solr.core.convert.CustomConversions' for property 'customConversions': no matching editors or conversion strategy found
	at org.springframework.beans.AbstractNestablePropertyAccessor.convertIfNecessary(AbstractNestablePropertyAccessor.java:605) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.AbstractNestablePropertyAccessor.convertForProperty(AbstractNestablePropertyAccessor.java:617) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.BeanWrapperImpl.convertForProperty(BeanWrapperImpl.java:216) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.convertForProperty(AbstractAutowireCapableBeanFactory.java:1577) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1536) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1276) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	... 20 common frames omitted
Caused by: java.lang.IllegalStateException: Cannot convert value of type 'org.springframework.data.mongodb.core.convert.CustomConversions' to required type 'org.springframework.data.solr.core.convert.CustomConversions' for property 'customConversions': no matching editors or conversion strategy found
	at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:306) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.AbstractNestablePropertyAccessor.convertIfNecessary(AbstractNestablePropertyAccessor.java:590) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	... 26 common frames omitted
```

Java Version - Java 8 b121
Spring Version - 1.5.1 (1.4.4 doesn't seem to have this issue)
Example project reproducing issue: https://github.com/aruberto/spring-boot-custom-conversions-error

**Comment by aruberto** [comment]
As a side note, when I add following to prevent the customConversions bean in [MongoDataAutoConfiguration.java](https://github.com/spring-projects/spring-boot/blob/d4c4bc35fdb9597fcb84e450da0cf7690cd462f4/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/data/mongo/MongoDataAutoConfiguration.java#L141) from getting defined, the application starts successfully

```
	@Bean
	public CustomConversions mongoCustomConversions() {
		return new CustomConversions(Collections.emptyList());
	}
```

**Comment by snicoll** [comment]
`customConversions` is a bean name that is used by `SolrRepositoryConfigExtension`. And we use the same (because of the name, that wasn't very smart I guess, for Mongo.

@christophstrobl would it be possible to rename the one in Solr?

**Comment by christophstrobl** [comment]
I'll take care of that - created [DATASOLR-362](https://jira.spring.io/browse/DATASOLR-362).

**Comment by snicoll** [comment]
this is new in 1.5 so it's something that was introduced in `Ingalls`

**Comment by deronjic** [comment]
we have the same problem with using solr and cassandra 

Caused by: java.lang.IllegalStateException: Cannot convert value of type 'org.springframework.data.cassandra.convert.CustomConversions' to required type 'org.springframework.data.solr.core.convert.CustomConversions' for property 'customConversions': no matching editors or conversion strategy found
	at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:306)
	at org.springframework.beans.AbstractNestablePropertyAccessor.convertIfNecessary(AbstractNestablePropertyAccessor.java:590)

**Comment by snicoll** [comment]
@deronjic this issue is closed. I've done a quick test and couldn't reproduce the issue. Please create a separate issue with a sample that I can run to reproduce what you're experiencing. Thanks!

**Comment by mattbroekhuis** [comment]
@deronjic  did you ever figure out how to get these both to work?

**Comment by snicoll** [comment]
@mattbroekhuis as I said in the comment _just_ above yours, this issue is closed.

> Please create a separate issue with a sample that I can run to reproduce what you're experiencing.

**Comment by jaafarnaddaf** [comment]
@snicoll I have this same issue in my project, and I still don't know how to work around it. Any suggestions?

**Comment by wilkinsona** [comment]
@jaafarnaddaf Please read the other comments in the issue. They already suggest what to do if you think you have this problem (which we believe has been fixed):

> Please create a separate issue with a sample that I can run to reproduce what you're experiencing.
