### ISSUE TITLE
@ConditionalOnBean with an annotation attribute may instantiate factory bean that provides no type information

### ISSUE THREAD

**Issue by hengyunabc** [spring-projects/spring-boot#8269]
When `@ConditionalOnBean` has annotation :

```
@ConditionalOnBean(annotation = { MyAnnotation.class })
public class MyAutoConfiguration {
```

In `org.springframework.boot.autoconfigure.condition.OnBeanCondition#getBeanNamesForAnnotation` call `beanFactory#getBeanNamesForAnnotation`:

```java
	private String[] getBeanNamesForAnnotation(
			ConfigurableListableBeanFactory beanFactory, String type,
			ClassLoader classLoader, boolean considerHierarchy) throws LinkageError {
		String[] result = NO_BEANS;
		try {
			@SuppressWarnings("unchecked")
			Class<? extends Annotation> typeClass = (Class<? extends Annotation>) ClassUtils
					.forName(type, classLoader);
			result = beanFactory.getBeanNamesForAnnotation(typeClass);
```

stack:

```
java.lang.Thread.State: RUNNABLE
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:239)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getTypeForFactoryBean(AbstractBeanFactory.java:1474)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryBean(AbstractAutowireCapableBeanFactory.java:808)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getType(AbstractBeanFactory.java:615)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAnnotationOnBean(DefaultListableBeanFactory.java:597)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForAnnotation(DefaultListableBeanFactory.java:564)
    at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanNamesForAnnotation(OnBeanCondition.java:198)
    at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchingBeans(OnBeanCondition.java:144)
    at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:81)
    at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47)
    at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:102)
    at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader$TrackedConditionEvaluator.shouldSkip(ConfigurationClassBeanDefinitionReader.java:436)
    at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader$TrackedConditionEvaluator.shouldSkip(ConfigurationClassBeanDefinitionReader.java:425)
    at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:127)
    at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:116)
    at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:333)
    at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:243)
    at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:273)
    at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:98)
    at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:681)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:523)
    - locked <0x1c78> (a java.lang.Object)
    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
    at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:369)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:313)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
```

---

As described above, bean creation before `BeanFactoryPostProcessor`, so `BeanFactoryPostProcessor` will not work.

**Comment by wilkinsona** [comment]
What version of Spring Boot are you using? The line numbers in the stack trace don't match up with Spring Framework 4.3.6.RELEASE which is the version using by Spring Boot 1.4.4.RELEASE and 1.5.1.RELEASE.

**Comment by wilkinsona** [comment]
I'm also not sure that your analysis is correct. It's hard to be certain as the line numbers don't match up, but I believe that the code path you've shown in the stack above will only be entered when there's an existing `FactoryBean` singleton, i.e. no bean creation will be triggered.

Can you please provide a sample that triggers early initialisation of a bean?

**Comment by hengyunabc** [comment]
[demo.zip](https://github.com/spring-projects/spring-boot/files/772019/demo.zip)

```java
/**
 * load from META-INF/spring.factories
 *
 * @author hengyunabc 2017-02-14
 *
 */
@Configuration
public class MyAutoConfiguration {

	@Bean
	// if comment this line, it will be fine.
	@ConditionalOnBean(annotation = { MyAnnotation.class })
	public String abc() {
		return "abc";
	}
}
```

**Comment by wilkinsona** [comment]
Your factory bean doesn't provide any type information in its signature so the framework has no choice but to instantiate it and call `getObjectType()` on it to try to determine the type of object that it will produce. There's nothing we can do about that I'm afraid. You need to implement your factory bean so that it either provides more type information by using generics or so that it can return something useful from `getObjectType()`.

**Comment by hengyunabc** [comment]
In fact, the factory bean provide bean type from user config.

In demo. the bean type is `java.lang.String`.

```xml
	<bean name="myServiceFactoryBean" class="com.example.MyServiceFactoryBean">
		<!-- service class is dynamic -->
		<property name="interfaceName" value="java.lang.String" />
		<property name="version">
			<value>${service.version}</value>
		</property>
	</bean>
```

In demo, why the first time `factoryBean.getObjectType()` return null?

Because `org.springframework.boot.autoconfigure.condition.OnBeanCondition` call `beanFactory.getBeanNamesForAnnotation(typeClass)` before `BeanFactoryPostProcessor`.

In addition, According to this method, `factoryBean.getObjectType()` return null is allowed:

```java
//Class<?> org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getTypeForFactoryBean(FactoryBean<?> factoryBean)

	/**
	 * Determine the type for the given FactoryBean.
	 * @param factoryBean the FactoryBean instance to check
	 * @return the FactoryBean's object type,
	 * or {@code null} if the type cannot be determined yet
	 */
	protected Class<?> getTypeForFactoryBean(final FactoryBean<?> factoryBean) {
		try {
			if (System.getSecurityManager() != null) {
				return AccessController.doPrivileged(new PrivilegedAction<Class<?>>() {
					@Override
					public Class<?> run() {
						return factoryBean.getObjectType();
					}
				}, getAccessControlContext());
			}
			else {
				return factoryBean.getObjectType();
			}
		}
		catch (Throwable ex) {
			// Thrown from the FactoryBean's getObjectType implementation.
			logger.warn("FactoryBean threw exception from getObjectType, despite the contract saying " +
					"that it should return null if the type of its object cannot be determined yet", ex);
			return null;
		}
	}
```

**Comment by wilkinsona** [comment]
> In fact, the factory bean provide bean type from user config

That information is only available at runtime once your factory bean has been instantiated and initialised. The ideal is to provide that information in the bean's type signature using generics.

> In demo, why the first time factoryBean.getObjectType() return null?

Because `getObjectType()` is called as early as possible in the factory bean's lifecycle. If it was called after the bean had been initialised (at which point all its setter would have been called) it may have caused early instantiation of other beans.

> In addition, According to this method, factoryBean.getObjectType() return null is allowed

It is allowed. I haven't said anywhere that it isn't However, if you want the type produced by your factory bean to be properly considered by `@ConditionalOnBean` then I would recommend making some changes. Perhaps the simplest thing that you could do would be to make `interfaceName` a constructor argument rather than a property. That will ensure that it's available as soon as your factory bean has been instantiated.

**Comment by hengyunabc** [comment]
I know how to avoid this problem. For example，use `@Import` instead of `@ConditionalOnBean(annotation = { MyAnnotation.class })`

```
@Target({ ElementType.TYPE })
@Retention(RetentionPolicy.RUNTIME)
@Import(MyConfig.class)
public @interface MyAnnotation {

}
```

---

But what I want to say is that: `@ConditionalOnBean` support annotation is not a good idea.  `org.springframework.boot.autoconfigure.condition.OnBeanCondition#getBeanNamesForAnnotation` break old code.

Please try the new demo, javaVersion is null.

[demo.zip](https://github.com/spring-projects/spring-boot/files/773587/demo.zip)

**Comment by wilkinsona** [comment]
Thanks, that new demo is a better illustration of why this is a problem.

Looking more closely, the javadoc for `getBeanNamesForAnnotation` states that it will find beans `without creating any bean instances yet`. That's evidently not the case for factory beans. I've asked the framework team if the current behaviour is intended. If it is, we may be able to do something to avoid the instantiation that's similar to what we've done for finding beans by type.

**Comment by wilkinsona** [comment]
The current behaviour of Spring Framework is intended (and the javadoc may be updated to better describe what happens) so we'll need to handle this ourselves.
