### ISSUE TITLE
Regression Error In Spring Boot 1.4.3 with Fat Jar packaging

### ISSUE THREAD

**Issue by tkvangorder** [spring-projects/spring-boot#8291]
We have one legacy application that is still using JSPs + Tiles. We recently upgraded from spring boot 1.4.1 to 1.4.4 and are encountering an error when attempting to launch the application deployed as a fat jar. 

We are serving the jsps from the classpath by putting all resources in /src/main/resources/META-INF/resources/WEB-INF :  

 ![screen shot 2017-02-14 at 9 46 50 am](https://cloud.githubusercontent.com/assets/1878529/22942213/66cee508-f29d-11e6-9ef9-643b2801fada.png)

The code works correcting when running from Eclipse, the code works correctly when packaged with the spring-boot-maven-plugin 1.4.2 but does NOT work when using a version of spring-boot-maven-plugin 1.4.3 (or higher)

The resources cannot be loaded when using the fat jar and this is the exception we are seeing: 

```
Caused by: java.lang.IllegalArgumentException: No URL for ServletContext resource [/WEB-INF/tiles-definitions.xml]
	at org.springframework.web.servlet.view.tiles3.SpringWildcardServletTilesApplicationContext.getResources(SpringWildcardServletTilesApplicationContext.java:96) ~[spring-webmvc-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
	at org.springframework.web.servlet.view.tiles3.TilesConfigurer$SpringTilesContainerFactory.getSources(TilesConfigurer.java:305) ~[spring-webmvc-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
	at org.apache.tiles.factory.BasicTilesContainerFactory.createLocaleDefinitionDao(BasicTilesContainerFactory.java:182) ~[tiles-core-3.0.5.jar!/:3.0.5]
	at org.apache.tiles.factory.BasicTilesContainerFactory.createDefinitionsFactory(BasicTilesContainerFactory.java:137) ~[tiles-core-3.0.5.jar!/:3.0.5]
	at org.springframework.web.servlet.view.tiles3.TilesConfigurer$SpringTilesContainerFactory.createDefinitionsFactory(TilesConfigurer.java:353) ~[spring-webmvc-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
	at org.apache.tiles.factory.BasicTilesContainerFactory.createContainer(BasicTilesContainerFactory.java:86) ~[tiles-core-3.0.5.jar!/:3.0.5]
	at org.apache.tiles.startup.AbstractTilesInitializer.createContainer(AbstractTilesInitializer.java:114) ~[tiles-core-3.0.5.jar!/:3.0.5]
	at org.apache.tiles.startup.AbstractTilesInitializer.initialize(AbstractTilesInitializer.java:64) ~[tiles-core-3.0.5.jar!/:3.0.5]
	at org.springframework.web.servlet.view.tiles3.TilesConfigurer.afterPropertiesSet(TilesConfigurer.java:271) ~[spring-webmvc-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
	... 24 common frames omitted
Caused by: java.io.FileNotFoundException: ServletContext resource [/WEB-INF/tiles-definitions.xml] cannot be resolved to URL because it does not exist
	at org.springframework.web.context.support.ServletContextResource.getURL(ServletContextResource.java:156) ~[spring-web-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
	at org.springframework.web.servlet.view.tiles3.SpringWildcardServletTilesApplicationContext.getResources(SpringWildcardServletTilesApplicationContext.java:91) ~[spring-webmvc-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
	... 34 common frames omitted
```

and the code around this: 

```java
	@Bean
	public TilesConfigurer tilesConfigurer() {
		TilesConfigurer tilesConfigurer = new TilesConfigurer();
		tilesConfigurer.setDefinitions("/WEB-INF/tiles-definitions.xml");
		tilesConfigurer.setServletContext(servletContext);
		return tilesConfigurer;
	}
```

Our workaround for now is to override the maven plugin version within the pom file. 

```
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<version>1.4.2.RELEASE</version>
				<configuration>
					<executable>true</executable>
				</configuration>			
				<executions>
					<execution>
						<goals>
							<goal>repackage</goal>
						</goals>
					</execution>
				</executions>				
			</plugin>
```
So we are packaging the application with the spring-boot-maven-plugin 1.4.2. This works even when using the 1.4.4 Spring runtime, so it appears to be a difference in the packaging vs a difference in the runtime.

**Comment by wilkinsona** [comment]
It's a difference in the launcher, specifically [this change](https://github.com/spring-projects/spring-boot/commit/2d8344d46d09c6c0de0bfe593f31b883a407f622). It brings things into line with the Servlet spec which states that resources in "META-INF/resources directory of a JAR file inside the web application’s WEB-INF/lib directory" should be available. I consider `BOOT-INF/lib` in a jar to be analogous to `WEB-INF/lib` in a war.

Overriding the version of the Maven plugin so that it's different to the version of Boot that you are using is a _really_ bad idea. IMO, @ghillert is being irresponsible by promoting it in his Spring Boot JSP demo project and I've already asked him to stop doing so.

Also, please note that JSPs in far jars are not supported. I'd strongly recommend moving to war packaging (you can still run your application with java -jar).

**Comment by tkvangorder** [comment]
Thanks Andy, makes sense. This is a legacy application that we have not had time to refactor. We moved to a fat jar for this application to make it consistent with all of our other spring boot applications. I will work with our OPs team to move this to a war.
