### ISSUE TITLE
Colon in profile name yields obscure IllegalArgumentException

### ISSUE THREAD

**Issue by anders-holmberg-baath** [spring-projects/spring-boot#8294]
This issue was originally reported to the spring-cloud project as [Colon in profile name yields obscure IllegalArgumentException](https://github.com/spring-cloud/spring-cloud-config/issues/637). Following their and my conclusions, I've adapted the report and added it to this project instead.

Since around Spring Boot 1.4.0 and later, using `:` (colon) in profile names results in a rather unhelpful error message, given a profile `test:abc` the following error and stack trace is shown:

```
08:39:09.050 [main] ERROR org.springframework.boot.SpringApplication - Application startup failed
java.lang.IllegalArgumentException: name
	at sun.misc.URLClassPath$Loader.findResource(URLClassPath.java:658)
	at sun.misc.URLClassPath.findResource(URLClassPath.java:188)
	at java.net.URLClassLoader$2.run(URLClassLoader.java:569)
	at java.net.URLClassLoader$2.run(URLClassLoader.java:567)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findResource(URLClassLoader.java:566)
	at org.springframework.boot.loader.LaunchedURLClassLoader.findResource(LaunchedURLClassLoader.java:58)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1096)
	at org.springframework.core.io.ClassPathResource.resolveURL(ClassPathResource.java:147)
	at org.springframework.core.io.ClassPathResource.exists(ClassPathResource.java:135)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.loadIntoGroup(ConfigFileApplicationListener.java:469)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:444)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:380)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.addPropertySources(ConfigFileApplicationListener.java:215)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.postProcessEnvironment(ConfigFileApplicationListener.java:184)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:171)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:157)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:73)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:336)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:138)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:84)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:62)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:73)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:336)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151)
	at com.example.ConfigServerApplication.main(ConfigServerApplication.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
```

Which points to a part of `URLClassPath` where a `MalformedURLException` is caught on constructing a `URL`, the exception is handled by the following rather unhelpful line:
```
throw new IllegalArgumentException("name");
```

which explains the exception as presented in the error message above.

Using `:` in profile names works fine with Spring Boot 1.3.8.RELEASE or earlier.

To complicate matters, it seems the issue only occurs when running the jar with `java -jar <jarfile>`, when for instance running with the Maven plugin, `mvn spring-boot:run` the issue does not occur.

I originally reported this issue to the spring-cloud project, as I discovered the issue when updating a cloud-config server. But it is their and my conclusion that it should be reported here.

I suspect the following commit may have something to do with the issue [Use a conventional delegation model in LaunchedURLClassLoader](https://github.com/spring-projects/spring-boot/commit/87fe0b2adeef85c842c009bfeebac1c84af8a5d7).

Project demonstrating the issue: https://github.com/anders-holmberg-baath/spring-cloud-config-issue-637 especially the "shorter path", as it was added after concluding that the issue is not within the domain of the config-server, but rather the spring-boot core.

**Comment by wilkinsona** [comment]
This has never worked properly, it just used to fail silently.

When a profile named `test:abc` is active, `ConfigFileApplicationListener` attempts to load a resource named `application-test:abc.properties`. Due to the `:` in the name, `application-test` is considered to be the protocol of a URL. There's no handler registered for this protocol so a `MalformedURLException` is thrown. This is turned into the unhelpful `IllegalStateException` shown above. In 1.3.x, `LaunchedURLClassLoader` swallowed this exception and returned `null`. This meant that any profile-specific configuration file for the `test:abc` profile would silently not be loaded. In 1.4.x the exception is no longer caught and the application fails to start.

**Comment by anders-holmberg-baath** [comment]
I believe it has worked, but surely not properly.
In a setup using the Spring Cloud config-server; when the exception was silently dropped, the config-server was able to load the configuration and the application using the profile was able to start (but would not have received any configuration from its local configuration files, had there been any for that profile).

To be clear, I don't think it's necessary to support colon in profile names, but the error message needs some clarification.

**Comment by wilkinsona** [comment]
The difference in behaviour is due to the different `Loader` implementations in the JDK's `sun.misc.URLClassPath`. `JarLoader` and `FileLoader` both swallow the `MalformedURLException` and return `null`. `Loader` turns it into an `IllegalArgumentException` with an unhelpful error message.

The underlying problem can be reproduced without involving Boot at all:

```java
new URLClassLoader( new URL[] { new URL("jar:file:whatever.jar!/") }).getResource("a:b.properties");
```

As far as I can tell, it's impossible to load a resource with a `:` in its name via a class loader so I think we have a couple of options here:

1. Fail hard stating the profiles with a `:` in their name are not supported. Other characters such as `/` will also cause problems.
2. Log a warning in `ConfigFileApplicationListener` when an exception is thrown while trying to locate a profile-specific configuration file.

**Comment by snicoll** [comment]
My vote is for 1. There isn't much we can do about it anyway

**Comment by wilkinsona** [comment]
Thanks, @snicoll.

I should have said that 2 is closer to the behaviour of 1.3, but with a warning now rather than just silently not loading a profile-specific configure file. If you're not trying to use a profile-specific configuration file then failing hard when things otherwise would have worked is perhaps a bit much.

**Comment by martin-g** [comment]
+1 for option 1)

**Comment by bclozel** [comment]
If it never really worked properly, I guess developers don't rely on those profiles being activated. So a WARN message should be enough - my vote goes to 2).

The only downside is we won't fail hard if people made a typo with a `:` in the profile name. If we choose 1), we should somehow fail hard if we don't find a  a profile-specific configure file for any profile name.

**Comment by philwebb** [comment]
Option 3) We strip out `:` entirely. i.e. `dev:region1` looks for `application-devregion1.properties`.

**Comment by wilkinsona** [comment]
We're going to catch the exception and then fail hard by throwing another one with a more helpful message
