### ISSUE TITLE
addToBB(InternalNioOutputBuffer.java:210)

### ISSUE THREAD

**Issue by Edward1030** [spring-projects/spring-boot#8332]
at org.apache.coyote.http11.InternalNioOutputBuffer.addToBB(InternalNioOutputBuffer.java:210)
	at org.apache.coyote.http11.InternalNioOutputBuffer.commit(InternalNioOutputBuffer.java:202)
	at org.apache.coyote.http11.AbstractHttp11Processor.action(AbstractHttp11Processor.java:774)
	at org.apache.coyote.Response.action(Response.java:174)
	at org.apache.coyote.Response.sendHeaders(Response.java:365)
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:352)
	at org.apache.catalina.connector.OutputBuffer.close(OutputBuffer.java:309)
	at org.apache.catalina.connector.CoyoteOutputStream.close(CoyoteOutputStream.java:108)
	at com.baidubce.bce.iotpaas.core.httpserver.response.DeviceCommonResponse.respond(DeviceCommonResponse.java:40)
	at com.baidubce.voice.obser.DeviceObserver.update(DeviceObserver.java:42)
	at com.baidubce.voice.obser.VoiceObservable.notifyObservers(VoiceObservable.java:39)
	at com.baidubce.voice.obser.VoiceObservable.doBusiness(VoiceObservable.java:28)
	at com.baidubce.voice.VoiceRecognition.getResult(VoiceRecognition.java:97)
	at com.baidubce.voice.VoiceRecognition.recognitionCallback(VoiceRecognition.java:47)

**Comment by wilkinsona** [comment]
I'm guessing this was opened in error. Please provide some more context if that's not the case. A portion of a stack trace doesn't really tell us anything.
