### ISSUE TITLE
App broken with update. Can I manually downgrade to 1.4.x?

### ISSUE THREAD

**Issue by santafebound** [spring-projects/spring-boot#8365]
There was a breaking update last night (at least for my app, and based on this commit: https://github.com/spring-projects/spring-boot/commit/8318177b0d8a2c75a1514f5ee3767affd282706f) and I'm wondering if it is possible to override the dependency in my pom file to call version 1.4.x for Springboot, just so it's exactly like it was before? What would the markup be and where do I put it?

```
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 3.035 s
    [INFO] Finished at: 2017-02-22T10:53:28+01:00
    [INFO] Final Memory: 18M/218M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal on project tmt: Could not resolve dependencies for project cz.nnit:tmt:war:0.0.1-SNAPSHOT: Failed to collect dependencies at org.springframework.boot:spring-boot-starter-security:jar:2.0.0.BUILD-SNAPSHOT -> org.springframework.boot:spring-boot-starter:jar:2.0.0.BUILD-SNAPSHOT -> org.springframework.boot:spring-boot:jar:2.0.0.BUILD-SNAPSHOT -> org.springframework:spring-core:jar:5.0.0.BUILD-SNAPSHOT: Failed to read artifact descriptor for org.springframework:spring-core:jar:5.0.0.BUILD-SNAPSHOT: Failure to find io.projectreactor:reactor-bom:pom:Aluminium-SR1 in https://repo.spring.io/snapshot was cached in the local repository, resolution will not be reattempted until the update interval of spring-snapshots has elapsed or updates are forced -> [Help 1]
    org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project tmt: Could not resolve dependencies for project cz.nnit:tmt:war:0.0.1-SNAPSHOT: Failed to collect dependencies at org.springframework.boot:spring-boot-starter-security:jar:2.0.0.BUILD-SNAPSHOT -> org.springframework.boot:spring-boot-starter:jar:2.0.0.BUILD-SNAPSHOT -> org.springframework.boot:spring-boot:jar:2.0.0.BUILD-SNAPSHOT -> org.springframework:spring-core:jar:5.0.0.BUILD-SNAPSHOT
    	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
    	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
    	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:245)
    	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:199)
    	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
    	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
    	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
    	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
    Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project cz.nnit:tmt:war:0.0.1-SNAPSHOT: Failed to collect dependencies at org.springframework.boot:spring-boot-starter-security:jar:2.0.0.BUILD-SNAPSHOT -> org.springframework.boot:spring-boot-starter:jar:2.0.0.BUILD-SNAPSHOT -> org.springframework.boot:spring-boot:jar:2.0.0.BUILD-SNAPSHOT -> org.springframework:spring-core:jar:5.0.0.BUILD-SNAPSHOT
    	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:180)
    	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
    	... 29 more
    Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at org.springframework.boot:spring-boot-starter-security:jar:2.0.0.BUILD-SNAPSHOT -> org.springframework.boot:spring-boot-starter:jar:2.0.0.BUILD-SNAPSHOT -> org.springframework.boot:spring-boot:jar:2.0.0.BUILD-SNAPSHOT -> org.springframework:spring-core:jar:5.0.0.BUILD-SNAPSHOT
    	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:291)
    	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:316)
    	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:172)
    	... 30 more
    Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.springframework:spring-core:jar:5.0.0.BUILD-SNAPSHOT
    	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:329)
    	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:198)
    	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:535)
    	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:519)
    	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:409)
    	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:363)
    	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
    	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.doRecurse(DefaultDependencyCollector.java:504)
    	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:458)
    	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:363)
    	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
    	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.doRecurse(DefaultDependencyCollector.java:504)
    	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:458)
    	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:363)
    	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
    	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.doRecurse(DefaultDependencyCollector.java:504)
    	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:458)
    	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:363)
    	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
    	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254)
    	... 32 more
    Caused by: org.apache.maven.model.resolution.UnresolvableModelException: Failure to find io.projectreactor:reactor-bom:pom:Aluminium-SR1 in https://repo.spring.io/snapshot was cached in the local repository, resolution will not be reattempted until the update interval of spring-snapshots has elapsed or updates are forced
    	at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:177)
    	at org.apache.maven.model.building.DefaultModelBuilder.importDependencyManagement(DefaultModelBuilder.java:1192)
    	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:455)
    	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:421)
    	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:411)
    	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:320)
    	... 51 more
    Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Failure to find io.projectreactor:reactor-bom:pom:Aluminium-SR1 in https://repo.spring.io/snapshot was cached in the local repository, resolution will not be reattempted until the update interval of spring-snapshots has elapsed or updates are forced
    	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
    	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
    	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
    	at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:173)
    	... 56 more
    Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find io.projectreactor:reactor-bom:pom:Aluminium-SR1 in https://repo.spring.io/snapshot was cached in the local repository, resolution will not be reattempted until the update interval of spring-snapshots has elapsed or updates are forced
    	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:231)
    	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206)
    	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:585)
    	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:503)
    	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
    	... 59 more
    [ERROR] 
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by wilkinsona** [comment]
The change you have referenced is unrelated to the problem you're seeing. The problem you are seeing is due to [this change](https://github.com/spring-projects/spring-framework/commit/c85f063d92d1d6ac0daa134ac4b64dac2c218182) in Spring Framework. We'll work with the Framework and Reactor teams to fix it.

**Comment by santafebound** [comment]
In the meantime, which dependencies can I manually downgrade to get this working like it was last night?

**Comment by philwebb** [comment]
@santafebound You can't mix Spring Boot 2.0.0 and 1.4.x versions. The 2.0.0 SNAPSHOT is unstable and you're likely to see issues like this from time to time. If you're working on a production application I'd strongly recommend that you stick to only `.RELEASE` versions.
