### ISSUE TITLE
classnot found: org/slf4j/LoggerFactory in spring-boot-starter-webflux 

### ISSUE THREAD

**Issue by gfinger** [spring-projects/spring-boot#8407]
In a freshly generated webflux project, generated with the Initializer, the sl4j.LoggerFactory is missing. This is the stacktrace

```
Caused by: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:273)
	at org.springframework.boot.SpringApplication.<clinit>(SpringApplication.java:217)
	at com.sap.newton.dts.api.DigitalTwinServiceApiApplication.main(DigitalTwinServiceApiApplication.java:19)
	... 6 more
```

**Comment by snicoll** [comment]
Nope. Check that your maven local cache isn't corrupted. That works just fine for me.

**Comment by gfinger** [comment]
gosh, yes, "mvn -U" didn't help, only when I removed by local repository completely, the dependencies got cleared up. Thanks!

**Comment by snicoll** [comment]
Why do you want `mvn -U` to help? Slf4j is not on snapshots.

There is [`mvn dependency:purge-local-repository`](https://maven.apache.org/plugins/maven-dependency-plugin/purge-local-repository-mojo.html) to deal with that stuff. Please consider doing that before opening an issue.
