### ISSUE TITLE
Null pointer when using the maven-versions-plugin

### ISSUE THREAD

**Issue by bquintanaj** [spring-projects/spring-boot#8426]
As described here:
https://github.com/mojohaus/versions-maven-plugin/issues/51
there seems to be a bug in the versions maven plugin currently included with Spring Boot (2.2).

I'm getting the same null pointer myself when using the plugin in my project:
```
[0;39morg.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.2:set (default-cli) on project encourage-distribution: Execution default-cli of goal org.codehaus.mojo:versions-maven-plugin:2.2:set failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212) ~[maven-core-3.3.9.jar:3.3.9]
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153) ~[maven-core-3.3.9.jar:3.3.9]
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145) ~[maven-core-3.3.9.jar:3.3.9]
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116) ~[maven-core-3.3.9.jar:3.3.9]
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80) ~[maven-core-3.3.9.jar:3.3.9]
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51) ~[maven-core-3.3.9.jar:3.3.9]
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128) ~[maven-core-3.3.9.jar:3.3.9]
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307) ~[maven-core-3.3.9.jar:3.3.9]
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193) ~[maven-core-3.3.9.jar:3.3.9]
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106) ~[maven-core-3.3.9.jar:3.3.9]
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863) [maven-embedder-3.3.9.jar:3.3.9]
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288) [maven-embedder-3.3.9.jar:3.3.9]
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199) [maven-embedder-3.3.9.jar:3.3.9]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289) [plexus-classworlds-2.5.2.jar:na]
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229) [plexus-classworlds-2.5.2.jar:na]
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415) [plexus-classworlds-2.5.2.jar:na]
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356) [plexus-classworlds-2.5.2.jar:na]
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.codehaus.mojo:versions-maven-plugin:2.2:set failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145) ~[maven-core-3.3.9.jar:3.3.9]
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207) ~[maven-core-3.3.9.jar:3.3.9]
	... 20 common frames omitted
Caused by: java.lang.NullPointerException: null
	at org.codehaus.mojo.versions.api.PomHelper.getModelEntry(PomHelper.java:1571) ~[na:na]
	at org.codehaus.mojo.versions.SetMojo.applyChange(SetMojo.java:275) ~[na:na]
	at org.codehaus.mojo.versions.SetMojo.execute(SetMojo.java:239) ~[na:na]
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134) ~[maven-core-3.3.9.jar:3.3.9]
	... 21 common frames omitted
```

It seems, however, that it's been fixed in the version 2.3, so Spring Boot could use 2.3 instead.

**Comment by bquintanaj** [comment]
I can confirm that the version 2.3 works for me.

**Comment by snicoll** [comment]
Closing in favour of PR #8429
