### ISSUE TITLE
Regression: Cannot update from @Spring

### ISSUE THREAD

**Issue by hohwille** [spring-projects/spring-boot#8482]
I have a test that I can not get to working after upgrading from spring boot 1.3.x to 1.5.1
I replaced this:
```
@SpringApplicationConfiguration(classes = SpringBootTestConfig.class)
```
with
```
@SpringBootTest(webEnvironment = WebEnvironment.NONE, classes = SpringBootTestConfig.class)
```
But now I am getting this error
```
Caused by: java.lang.IllegalStateException: The following classes could not be excluded because they are not auto-configuration classes:
	- <mypackage>.AbstractServiceConfig
	at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.handleInvalidExcludes(AutoConfigurationImportSelector.java:192)
	at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.checkExcludedClasses(AutoConfigurationImportSelector.java:177)
	at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.selectImports(AutoConfigurationImportSelector.java:99)
	at org.springframework.context.annotation.ConfigurationClassParser.processDeferredImportSelectors(ConfigurationClassParser.java:537)
	... 38 more
```
My ```SpringBootTestConfig``` however looks like this:
```
@ComponentScan(excludeFilters = @ComponentScan.Filter(type = FilterType.ASSIGNABLE_TYPE, value = {
AbstractServiceConfig.class }))
@SpringBootApplication(exclude = { AbstractServiceConfig.class })
public class SpringBootTestConfig {
...
}
```
Could you give me any hints why the excludes are not working properly?

**Comment by wilkinsona** [comment]
The `exclude` attribute on `SpringBootApplication` is for excluding auto-configuration classes and `AbstractServiceConfig` is not an auto-configuration class. We used to just silently ignore the exclusion attempt and it just had no effect. #6865 changed this so that it fails fast hopefully making it clear that the exclusion won't work.

You should just be able to remove the `exclude` from `@SpringBootApplication` on `SpringBootTestConfig`.

**Comment by hohwille** [comment]
Indeed. Sorry for confusion and thanks for your great work and support! Removed ```exclude``` and it works.
