### ISSUE TITLE
NoClassDefFoundError with spring-boot-starter-test

### ISSUE THREAD

**Issue by larsgrefer** [spring-projects/spring-boot#8492]
I get a `NoClassDefFoundError` in my unit tests with `spring-boot-starter-test`:

```
java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.<clinit>(SpringJUnit4ClassRunner.java:96)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy3.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:147)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:129)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 39 more
```
This is my `build.grade` https://github.com/freefair/okhttp-spring-boot/blob/89137d7c8d42a19b7ed4d235ad642fd0ad85a617/autoconfigure/build.gradle

You can reproduce this on freefair/okhttp-spring-boot@89137d7c8d42a19b7ed4d235ad642fd0ad85a617 by running `.\gradlew clean auto:test`

I've tested this with `1.5.1.RELEASE` and `1.5.2.RELEASE`. Both fail with the same error.

**Comment by philwebb** [comment]
The commons logging API classes are required dependencies for Spring Test. Usually they either get pulled in via a transitive dependency on `spring-core`, or the commons-logging jar is excluded and `org.slf4j:jcl-over-slf4j` is used instead (it contains the classes with the same name).

It's not entirely clear to me why `commons-logging` has been excluded in this case. I guess something in our plugin must be doing that. Here's your dependency tree:

```
$ ./gradlew clean auto:dependencies

:autoconfigure:clean UP-TO-DATE
:starters:okhttp:clean UP-TO-DATE
:starters:okhttp2:clean UP-TO-DATE
:starters:okhttp3:clean UP-TO-DATE
:autoconfigure:dependencies

------------------------------------------------------------
Project :autoconfigure
------------------------------------------------------------

apiElements - API elements for main. (n)
No dependencies

archives - Configuration for archive artifacts.
No dependencies

checkstyle - The Checkstyle libraries to be used for this project.
\--- com.puppycrawl.tools:checkstyle:7.6
     +--- antlr:antlr:2.7.7
     +--- org.antlr:antlr4-runtime:4.6
     +--- commons-beanutils:commons-beanutils:1.9.3
     |    \--- commons-collections:commons-collections:3.2.2
     +--- commons-cli:commons-cli:1.3.1
     \--- com.google.guava:guava:19.0

compile - Dependencies for source set 'main' (deprecated, use 'implementation ' instead).
\--- org.springframework.boot:spring-boot-autoconfigure: -> 1.5.2.RELEASE
     \--- org.springframework.boot:spring-boot:1.5.2.RELEASE
          +--- org.springframework:spring-core:4.3.7.RELEASE
          \--- org.springframework:spring-context:4.3.7.RELEASE
               +--- org.springframework:spring-aop:4.3.7.RELEASE
               |    +--- org.springframework:spring-beans:4.3.7.RELEASE
               |    |    \--- org.springframework:spring-core:4.3.7.RELEASE
               |    \--- org.springframework:spring-core:4.3.7.RELEASE
               +--- org.springframework:spring-beans:4.3.7.RELEASE (*)
               +--- org.springframework:spring-core:4.3.7.RELEASE
               \--- org.springframework:spring-expression:4.3.7.RELEASE
                    \--- org.springframework:spring-core:4.3.7.RELEASE

compileClasspath - Compile classpath for source set 'main'.
+--- org.springframework.boot:spring-boot-autoconfigure: -> 1.5.2.RELEASE
|    \--- org.springframework.boot:spring-boot:1.5.2.RELEASE
|         +--- org.springframework:spring-core:4.3.7.RELEASE
|         \--- org.springframework:spring-context:4.3.7.RELEASE
|              +--- org.springframework:spring-aop:4.3.7.RELEASE
|              |    +--- org.springframework:spring-beans:4.3.7.RELEASE
|              |    |    \--- org.springframework:spring-core:4.3.7.RELEASE
|              |    \--- org.springframework:spring-core:4.3.7.RELEASE
|              +--- org.springframework:spring-beans:4.3.7.RELEASE (*)
|              +--- org.springframework:spring-core:4.3.7.RELEASE
|              \--- org.springframework:spring-expression:4.3.7.RELEASE
|                   \--- org.springframework:spring-core:4.3.7.RELEASE
+--- org.projectlombok:lombok: -> 1.16.14
+--- org.springframework:spring-web: -> 4.3.7.RELEASE
|    +--- org.springframework:spring-aop:4.3.7.RELEASE (*)
|    +--- org.springframework:spring-beans:4.3.7.RELEASE (*)
|    +--- org.springframework:spring-context:4.3.7.RELEASE (*)
|    \--- org.springframework:spring-core:4.3.7.RELEASE
+--- com.squareup.okhttp3:okhttp:3.+ -> 3.6.0
|    \--- com.squareup.okio:okio:1.11.0
+--- com.squareup.okhttp3:logging-interceptor:3.+ -> 3.6.0
|    \--- com.squareup.okhttp3:okhttp:3.6.0 (*)
+--- com.squareup.okhttp:okhttp:2.+ -> 2.7.5
|    \--- com.squareup.okio:okio:1.6.0 -> 1.11.0
+--- com.squareup.okhttp:logging-interceptor:2.+ -> 2.7.5
|    \--- com.squareup.okhttp:okhttp:2.7.5 (*)
\--- org.springframework.boot:spring-boot-configuration-processor: -> 1.5.2.RELEASE
     \--- com.vaadin.external.google:android-json:0.0.20131108.vaadin1

compileOnly - Compile only dependencies for source set 'main'.
+--- org.projectlombok:lombok: -> 1.16.14
+--- org.springframework:spring-web: -> 4.3.7.RELEASE
|    +--- org.springframework:spring-aop:4.3.7.RELEASE
|    |    +--- org.springframework:spring-beans:4.3.7.RELEASE
|    |    |    \--- org.springframework:spring-core:4.3.7.RELEASE
|    |    \--- org.springframework:spring-core:4.3.7.RELEASE
|    +--- org.springframework:spring-beans:4.3.7.RELEASE (*)
|    +--- org.springframework:spring-context:4.3.7.RELEASE
|    |    +--- org.springframework:spring-aop:4.3.7.RELEASE (*)
|    |    +--- org.springframework:spring-beans:4.3.7.RELEASE (*)
|    |    +--- org.springframework:spring-core:4.3.7.RELEASE
|    |    \--- org.springframework:spring-expression:4.3.7.RELEASE
|    |         \--- org.springframework:spring-core:4.3.7.RELEASE
|    \--- org.springframework:spring-core:4.3.7.RELEASE
+--- com.squareup.okhttp3:okhttp:3.+ -> 3.6.0
|    \--- com.squareup.okio:okio:1.11.0
+--- com.squareup.okhttp3:logging-interceptor:3.+ -> 3.6.0
|    \--- com.squareup.okhttp3:okhttp:3.6.0 (*)
+--- com.squareup.okhttp:okhttp:2.+ -> 2.7.5
|    \--- com.squareup.okio:okio:1.6.0 -> 1.11.0
+--- com.squareup.okhttp:logging-interceptor:2.+ -> 2.7.5
|    \--- com.squareup.okhttp:okhttp:2.7.5 (*)
\--- org.springframework.boot:spring-boot-configuration-processor: -> 1.5.2.RELEASE
     \--- com.vaadin.external.google:android-json:0.0.20131108.vaadin1

default - Configuration for default artifacts.
\--- org.springframework.boot:spring-boot-autoconfigure: -> 1.5.2.RELEASE
     \--- org.springframework.boot:spring-boot:1.5.2.RELEASE
          +--- org.springframework:spring-core:4.3.7.RELEASE
          \--- org.springframework:spring-context:4.3.7.RELEASE
               +--- org.springframework:spring-aop:4.3.7.RELEASE
               |    +--- org.springframework:spring-beans:4.3.7.RELEASE
               |    |    \--- org.springframework:spring-core:4.3.7.RELEASE
               |    \--- org.springframework:spring-core:4.3.7.RELEASE
               +--- org.springframework:spring-beans:4.3.7.RELEASE (*)
               +--- org.springframework:spring-core:4.3.7.RELEASE
               \--- org.springframework:spring-expression:4.3.7.RELEASE
                    \--- org.springframework:spring-core:4.3.7.RELEASE

findbugs - The FindBugs libraries to be used for this project.
\--- com.google.code.findbugs:findbugs:3.0.1
     +--- net.jcip:jcip-annotations:1.0
     +--- com.google.code.findbugs:jsr305:2.0.1
     +--- com.google.code.findbugs:bcel-findbugs:6.0
     +--- com.google.code.findbugs:jFormatString:2.0.1
     +--- dom4j:dom4j:1.6.1
     |    \--- xml-apis:xml-apis:1.0.b2 -> 1.4.01
     +--- org.ow2.asm:asm-debug-all:5.0.2
     +--- org.ow2.asm:asm-commons:5.0.2
     |    \--- org.ow2.asm:asm-tree:5.0.2
     |         \--- org.ow2.asm:asm:5.0.2
     +--- commons-lang:commons-lang:2.6
     +--- com.apple:AppleJavaExtensions:1.4
     \--- jaxen:jaxen:1.1.6

findbugsPlugins - The FindBugs plugins to be used for this project.
No dependencies

implementation - Implementation only dependencies for source set 'main'. (n)
No dependencies

runtime - Runtime dependencies for source set 'main' (deprecated, use 'runtimeOnly ' instead).
\--- org.springframework.boot:spring-boot-autoconfigure: -> 1.5.2.RELEASE
     \--- org.springframework.boot:spring-boot:1.5.2.RELEASE
          +--- org.springframework:spring-core:4.3.7.RELEASE
          \--- org.springframework:spring-context:4.3.7.RELEASE
               +--- org.springframework:spring-aop:4.3.7.RELEASE
               |    +--- org.springframework:spring-beans:4.3.7.RELEASE
               |    |    \--- org.springframework:spring-core:4.3.7.RELEASE
               |    \--- org.springframework:spring-core:4.3.7.RELEASE
               +--- org.springframework:spring-beans:4.3.7.RELEASE (*)
               +--- org.springframework:spring-core:4.3.7.RELEASE
               \--- org.springframework:spring-expression:4.3.7.RELEASE
                    \--- org.springframework:spring-core:4.3.7.RELEASE

runtimeClasspath - Runtime classpath of source set 'main'.
\--- org.springframework.boot:spring-boot-autoconfigure: -> 1.5.2.RELEASE
     \--- org.springframework.boot:spring-boot:1.5.2.RELEASE
          +--- org.springframework:spring-core:4.3.7.RELEASE
          \--- org.springframework:spring-context:4.3.7.RELEASE
               +--- org.springframework:spring-aop:4.3.7.RELEASE
               |    +--- org.springframework:spring-beans:4.3.7.RELEASE
               |    |    \--- org.springframework:spring-core:4.3.7.RELEASE
               |    \--- org.springframework:spring-core:4.3.7.RELEASE
               +--- org.springframework:spring-beans:4.3.7.RELEASE (*)
               +--- org.springframework:spring-core:4.3.7.RELEASE
               \--- org.springframework:spring-expression:4.3.7.RELEASE
                    \--- org.springframework:spring-core:4.3.7.RELEASE

runtimeElements - Elements of runtime for main. (n)
No dependencies

runtimeOnly - Runtime only dependencies for source set 'main'. (n)
No dependencies

testCompile - Dependencies for source set 'test' (deprecated, use 'testImplementation ' instead).
+--- org.springframework.boot:spring-boot-autoconfigure: -> 1.5.2.RELEASE
|    \--- org.springframework.boot:spring-boot:1.5.2.RELEASE
|         +--- org.springframework:spring-core:4.3.7.RELEASE
|         \--- org.springframework:spring-context:4.3.7.RELEASE
|              +--- org.springframework:spring-aop:4.3.7.RELEASE
|              |    +--- org.springframework:spring-beans:4.3.7.RELEASE
|              |    |    \--- org.springframework:spring-core:4.3.7.RELEASE
|              |    \--- org.springframework:spring-core:4.3.7.RELEASE
|              +--- org.springframework:spring-beans:4.3.7.RELEASE (*)
|              +--- org.springframework:spring-core:4.3.7.RELEASE
|              \--- org.springframework:spring-expression:4.3.7.RELEASE
|                   \--- org.springframework:spring-core:4.3.7.RELEASE
+--- org.springframework.boot:spring-boot-starter-test: -> 1.5.2.RELEASE
|    +--- org.springframework.boot:spring-boot-test:1.5.2.RELEASE
|    |    \--- org.springframework.boot:spring-boot:1.5.2.RELEASE (*)
|    +--- org.springframework.boot:spring-boot-test-autoconfigure:1.5.2.RELEASE
|    |    +--- org.springframework.boot:spring-boot-test:1.5.2.RELEASE (*)
|    |    \--- org.springframework.boot:spring-boot-autoconfigure:1.5.2.RELEASE (*)
|    +--- com.jayway.jsonpath:json-path:2.2.0
|    |    +--- net.minidev:json-smart:2.2.1
|    |    |    \--- net.minidev:accessors-smart:1.1
|    |    |         \--- org.ow2.asm:asm:5.0.3
|    |    \--- org.slf4j:slf4j-api:1.7.16 -> 1.7.24
|    +--- junit:junit:4.12
|    |    \--- org.hamcrest:hamcrest-core:1.3
|    +--- org.assertj:assertj-core:2.6.0
|    +--- org.mockito:mockito-core:1.10.19
|    |    +--- org.hamcrest:hamcrest-core:1.1 -> 1.3
|    |    \--- org.objenesis:objenesis:2.1
|    +--- org.hamcrest:hamcrest-core:1.3
|    +--- org.hamcrest:hamcrest-library:1.3
|    |    \--- org.hamcrest:hamcrest-core:1.3
|    +--- org.skyscreamer:jsonassert:1.4.0
|    |    \--- com.vaadin.external.google:android-json:0.0.20131108.vaadin1
|    +--- org.springframework:spring-core:4.3.7.RELEASE
|    \--- org.springframework:spring-test:4.3.7.RELEASE
|         \--- org.springframework:spring-core:4.3.7.RELEASE
\--- com.squareup.okhttp3:okhttp:3.+ -> 3.6.0
     \--- com.squareup.okio:okio:1.11.0

testCompileClasspath - Compile classpath for source set 'test'.
+--- org.springframework.boot:spring-boot-autoconfigure: -> 1.5.2.RELEASE
|    \--- org.springframework.boot:spring-boot:1.5.2.RELEASE
|         +--- org.springframework:spring-core:4.3.7.RELEASE
|         \--- org.springframework:spring-context:4.3.7.RELEASE
|              +--- org.springframework:spring-aop:4.3.7.RELEASE
|              |    +--- org.springframework:spring-beans:4.3.7.RELEASE
|              |    |    \--- org.springframework:spring-core:4.3.7.RELEASE
|              |    \--- org.springframework:spring-core:4.3.7.RELEASE
|              +--- org.springframework:spring-beans:4.3.7.RELEASE (*)
|              +--- org.springframework:spring-core:4.3.7.RELEASE
|              \--- org.springframework:spring-expression:4.3.7.RELEASE
|                   \--- org.springframework:spring-core:4.3.7.RELEASE
+--- org.springframework.boot:spring-boot-starter-test: -> 1.5.2.RELEASE
|    +--- org.springframework.boot:spring-boot-test:1.5.2.RELEASE
|    |    \--- org.springframework.boot:spring-boot:1.5.2.RELEASE (*)
|    +--- org.springframework.boot:spring-boot-test-autoconfigure:1.5.2.RELEASE
|    |    +--- org.springframework.boot:spring-boot-test:1.5.2.RELEASE (*)
|    |    \--- org.springframework.boot:spring-boot-autoconfigure:1.5.2.RELEASE (*)
|    +--- com.jayway.jsonpath:json-path:2.2.0
|    |    +--- net.minidev:json-smart:2.2.1
|    |    |    \--- net.minidev:accessors-smart:1.1
|    |    |         \--- org.ow2.asm:asm:5.0.3
|    |    \--- org.slf4j:slf4j-api:1.7.16 -> 1.7.24
|    +--- junit:junit:4.12
|    |    \--- org.hamcrest:hamcrest-core:1.3
|    +--- org.assertj:assertj-core:2.6.0
|    +--- org.mockito:mockito-core:1.10.19
|    |    +--- org.hamcrest:hamcrest-core:1.1 -> 1.3
|    |    \--- org.objenesis:objenesis:2.1
|    +--- org.hamcrest:hamcrest-core:1.3
|    +--- org.hamcrest:hamcrest-library:1.3
|    |    \--- org.hamcrest:hamcrest-core:1.3
|    +--- org.skyscreamer:jsonassert:1.4.0
|    |    \--- com.vaadin.external.google:android-json:0.0.20131108.vaadin1
|    +--- org.springframework:spring-core:4.3.7.RELEASE
|    \--- org.springframework:spring-test:4.3.7.RELEASE
|         \--- org.springframework:spring-core:4.3.7.RELEASE
\--- com.squareup.okhttp3:okhttp:3.+ -> 3.6.0
     \--- com.squareup.okio:okio:1.11.0

testCompileOnly - Compile only dependencies for source set 'test'.
No dependencies

testImplementation - Implementation only dependencies for source set 'test'. (n)
No dependencies

testRuntime - Runtime dependencies for source set 'test' (deprecated, use 'testRuntimeOnly ' instead).
+--- org.springframework.boot:spring-boot-autoconfigure: -> 1.5.2.RELEASE
|    \--- org.springframework.boot:spring-boot:1.5.2.RELEASE
|         +--- org.springframework:spring-core:4.3.7.RELEASE
|         \--- org.springframework:spring-context:4.3.7.RELEASE
|              +--- org.springframework:spring-aop:4.3.7.RELEASE
|              |    +--- org.springframework:spring-beans:4.3.7.RELEASE
|              |    |    \--- org.springframework:spring-core:4.3.7.RELEASE
|              |    \--- org.springframework:spring-core:4.3.7.RELEASE
|              +--- org.springframework:spring-beans:4.3.7.RELEASE (*)
|              +--- org.springframework:spring-core:4.3.7.RELEASE
|              \--- org.springframework:spring-expression:4.3.7.RELEASE
|                   \--- org.springframework:spring-core:4.3.7.RELEASE
+--- org.springframework.boot:spring-boot-starter-test: -> 1.5.2.RELEASE
|    +--- org.springframework.boot:spring-boot-test:1.5.2.RELEASE
|    |    \--- org.springframework.boot:spring-boot:1.5.2.RELEASE (*)
|    +--- org.springframework.boot:spring-boot-test-autoconfigure:1.5.2.RELEASE
|    |    +--- org.springframework.boot:spring-boot-test:1.5.2.RELEASE (*)
|    |    \--- org.springframework.boot:spring-boot-autoconfigure:1.5.2.RELEASE (*)
|    +--- com.jayway.jsonpath:json-path:2.2.0
|    |    +--- net.minidev:json-smart:2.2.1
|    |    |    \--- net.minidev:accessors-smart:1.1
|    |    |         \--- org.ow2.asm:asm:5.0.3
|    |    \--- org.slf4j:slf4j-api:1.7.16 -> 1.7.24
|    +--- junit:junit:4.12
|    |    \--- org.hamcrest:hamcrest-core:1.3
|    +--- org.assertj:assertj-core:2.6.0
|    +--- org.mockito:mockito-core:1.10.19
|    |    +--- org.hamcrest:hamcrest-core:1.1 -> 1.3
|    |    \--- org.objenesis:objenesis:2.1
|    +--- org.hamcrest:hamcrest-core:1.3
|    +--- org.hamcrest:hamcrest-library:1.3
|    |    \--- org.hamcrest:hamcrest-core:1.3
|    +--- org.skyscreamer:jsonassert:1.4.0
|    |    \--- com.vaadin.external.google:android-json:0.0.20131108.vaadin1
|    +--- org.springframework:spring-core:4.3.7.RELEASE
|    \--- org.springframework:spring-test:4.3.7.RELEASE
|         \--- org.springframework:spring-core:4.3.7.RELEASE
\--- com.squareup.okhttp3:okhttp:3.+ -> 3.6.0
     \--- com.squareup.okio:okio:1.11.0

testRuntimeClasspath - Runtime classpath of source set 'test'.
+--- org.springframework.boot:spring-boot-autoconfigure: -> 1.5.2.RELEASE
|    \--- org.springframework.boot:spring-boot:1.5.2.RELEASE
|         +--- org.springframework:spring-core:4.3.7.RELEASE
|         \--- org.springframework:spring-context:4.3.7.RELEASE
|              +--- org.springframework:spring-aop:4.3.7.RELEASE
|              |    +--- org.springframework:spring-beans:4.3.7.RELEASE
|              |    |    \--- org.springframework:spring-core:4.3.7.RELEASE
|              |    \--- org.springframework:spring-core:4.3.7.RELEASE
|              +--- org.springframework:spring-beans:4.3.7.RELEASE (*)
|              +--- org.springframework:spring-core:4.3.7.RELEASE
|              \--- org.springframework:spring-expression:4.3.7.RELEASE
|                   \--- org.springframework:spring-core:4.3.7.RELEASE
+--- org.springframework.boot:spring-boot-starter-test: -> 1.5.2.RELEASE
|    +--- org.springframework.boot:spring-boot-test:1.5.2.RELEASE
|    |    \--- org.springframework.boot:spring-boot:1.5.2.RELEASE (*)
|    +--- org.springframework.boot:spring-boot-test-autoconfigure:1.5.2.RELEASE
|    |    +--- org.springframework.boot:spring-boot-test:1.5.2.RELEASE (*)
|    |    \--- org.springframework.boot:spring-boot-autoconfigure:1.5.2.RELEASE (*)
|    +--- com.jayway.jsonpath:json-path:2.2.0
|    |    +--- net.minidev:json-smart:2.2.1
|    |    |    \--- net.minidev:accessors-smart:1.1
|    |    |         \--- org.ow2.asm:asm:5.0.3
|    |    \--- org.slf4j:slf4j-api:1.7.16 -> 1.7.24
|    +--- junit:junit:4.12
|    |    \--- org.hamcrest:hamcrest-core:1.3
|    +--- org.assertj:assertj-core:2.6.0
|    +--- org.mockito:mockito-core:1.10.19
|    |    +--- org.hamcrest:hamcrest-core:1.1 -> 1.3
|    |    \--- org.objenesis:objenesis:2.1
|    +--- org.hamcrest:hamcrest-core:1.3
|    +--- org.hamcrest:hamcrest-library:1.3
|    |    \--- org.hamcrest:hamcrest-core:1.3
|    +--- org.skyscreamer:jsonassert:1.4.0
|    |    \--- com.vaadin.external.google:android-json:0.0.20131108.vaadin1
|    +--- org.springframework:spring-core:4.3.7.RELEASE
|    \--- org.springframework:spring-test:4.3.7.RELEASE
|         \--- org.springframework:spring-core:4.3.7.RELEASE
\--- com.squareup.okhttp3:okhttp:3.+ -> 3.6.0
     \--- com.squareup.okio:okio:1.11.0

testRuntimeOnly - Runtime only dependencies for source set 'test'. (n)
No dependencies

(*) - dependencies omitted (listed previously)

BUILD SUCCESSFUL

Total time: 0.9 secs
```

Adding the following to your `dependencies` seems to fix the issue:

```
    testCompile 'commons-logging:commons-logging'
```

**Comment by philwebb** [comment]
@wilkinsona Any reason you can think of why `commons-logging` wasn't included?

**Comment by larsgrefer** [comment]
The pom generated by `./gradlew clean auto:install` contains an exclusion for `commons-logging`.

**Comment by wilkinsona** [comment]
>  I guess something in our plugin must be doing that

The exclusion is in Spring Boot Starter Test and you get the same behaviour with Maven, i.e. there's nothing Gradle-specific happening here.

> Any reason you can think of why commons-logging wasn't included?

Because it's a starter and we want `org.slf4j:jcl-over-slf4j` to be used instead.

@larsgrefer's app is atypical as the only starter it's using is `spring-boot-starter-test`. We could consider adding a dependency on `spring-boot-starter-logging` to `spring-boot-starter-test` but we'd want to check that it doesn't make it harder for people to switch logging backend.

**Comment by larsgrefer** [comment]
Thank you for your fast replies.

I *fixed* my issue by adding a direct dependency on `spring-boot-starter-logging`, but in my opinion my first approach should work too.

**Comment by snicoll** [comment]
I don't think I agree with that. The logging framework switch is really a feature of Spring Boot (the runtime). If you're only using the test infrastructure, you're not really using the runtime (and hence shouldn't expect that feature to apply).

**Comment by larsgrefer** [comment]
@snicoll One of the key features of Maven and Gradle is the transitive dependency management. When I declare a dependency on a library I want to use, I expect to get all transitive dependencies needed to use the library.

**Comment by snicoll** [comment]
I got that. If you agree your project is atypical then we're one step away from my point.

**Comment by wilkinsona** [comment]
> The logging framework switch is really a feature of Spring Boot (the runtime). If you're only using the test infrastructure, you're not really using the runtime (and hence shouldn't expect that feature to apply)

The runtime is being used here: there's a dependency on `spring-boot-autoconfigure`.

The starters are intended to be optional and I think that should include only using the test starter. I could see someone developing a war that's going to be deployed to an app server taking that approach, for example. I still think it's atypical but I agree with @larsgrefer that it should work. Let's see what we can do.

**Comment by wilkinsona** [comment]
As I suspected, adding a dependency on `spring-boot-starter-logging` to `spring-boot-starter-test` means that any project that is swapping out Logback for Log4J2 will now require an extra exclusion to be configured. 

Adding a dependency on `spring-boot-starter` to `spring-boot-starter-test` seems to work. In addition to `spring-boot-starter-logging`, `spring-boot-starter` also pulls in `spring-boot` and `spring-boot-autoconfigure` but `spring-boot-starter-test` already depends on both of these. This looks like a viable option to me. Let's see what the rest of the team thinks.

**Comment by snicoll** [comment]
Works for me.

**Comment by philwebb** [comment]
I'm fine with that change, it matches most of the other starters. I think it wasn't done initially because it was assumed that the other starters would always be added manually (given that they need to be in compile scope generally).

**Comment by philwebb** [comment]
Not keen to do this in 1.5.x since there's a work-around. Will target to 2.0

**Comment by liebichw** [comment]
I hit the same problem, and our project is using log4j 2.
Can I just force spring boot test to use log4j 2 ?

**Comment by larsgrefer** [comment]
@liebichw exclude the `spring-boot-starter-logging` and include `spring-boot-starter-log4j2`

http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-configure-log4j-for-logging

**Comment by liebichw** [comment]
Hi,

On 2017-04-20 13:18, Lars Grefer wrote:
> @liebichw <https://github.com/liebichw> exclude the |spring-boot-starter-logging| and include |spring-boot-starter-log4j2|
> 
> http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-configure-log4j-for-logging

Thanks, that did it and solved my problem. - Wolfgang
