### ISSUE TITLE
UnsatisfiedDependencyException with spring-boot-starter-data-rest and spring-boot-starter-amqp

### ISSUE THREAD

**Issue by thecrait** [spring-projects/spring-boot#8507]
Bug report
springBootVersion = '1.5.2.RELEASE'

Hi,
using a Mongo(or PagingAndSorting)Repository to persist an AMQP-Message either directly or in a wrapper class works great.

Including the "spring-boot-starter-data-rest"-dependency in the project causes an "UnsatisfiedDependencyException" when starting the application.

The problem seems to occur when the AMQP-Message object is parsed to create the ReST-Resources for it. Some of the Generics used in the AMQP message seem to cause a null-pointer exception in spring-data-rest code.

I included a sample application with
_spring-boot-starter-amqp
spring-boot-starter-data-mongodb
spring-boot-starter-data-rest_
that repoduces the issue.

Zip of the application: [test.zip](https://github.com/spring-projects/spring-boot/files/821334/test.zip)

**Comment by wilkinsona** [comment]
Thanks for the sample. I don't think this is a problem with Spring Boot, but with Spring Data MongoDB or Spring Data REST. The underlying failure is:

```
Caused by: java.lang.NullPointerException: null
	at org.springframework.data.rest.core.UriToEntityConverter.<init>(UriToEntityConverter.java:71) ~[spring-data-rest-core-2.6.1.RELEASE.jar:na]
	at org.springframework.data.rest.webmvc.config.RepositoryRestMvcConfiguration.uriToEntityConverter(RepositoryRestMvcConfiguration.java:650) ~[spring-data-rest-webmvc-2.6.1.RELEASE.jar:na]
	at org.springframework.data.rest.webmvc.config.RepositoryRestMvcConfiguration.defaultConversionService(RepositoryRestMvcConfiguration.java:230) ~[spring-data-rest-webmvc-2.6.1.RELEASE.jar:na]
	at org.springframework.data.rest.webmvc.config.RepositoryRestMvcConfiguration$$EnhancerBySpringCGLIB$$5836bf08.CGLIB$defaultConversionService$6(<generated>) ~[spring-data-rest-webmvc-2.6.1.RELEASE.jar:na]
	at org.springframework.data.rest.webmvc.config.RepositoryRestMvcConfiguration$$EnhancerBySpringCGLIB$$5836bf08$$FastClassBySpringCGLIB$$219fc350.invoke(<generated>) ~[spring-data-rest-webmvc-2.6.1.RELEASE.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358) ~[spring-context-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.data.rest.webmvc.config.RepositoryRestMvcConfiguration$$EnhancerBySpringCGLIB$$5836bf08.defaultConversionService(<generated>) ~[spring-data-rest-webmvc-2.6.1.RELEASE.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_102]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	... 47 common frames omitted
```

Given that the NPE is being thrown by code in Spring Data REST, that seems like a reasonable place to start. Can you please open a [JIRA ticket](https://jira.spring.io/browse/DATAREST)?.

**Comment by snicoll** [comment]
Indeed. 

When you do create the JIRA ticket, you can share that this NPE comes from the fact  a `domainType` of `java.lang.reflect.TypeVariable<java.lang.Object>` is detected for whatever reason and that one doesn't have an entity, so `entity.hasIdProperty()`fails with an NPE.

**Comment by olivergierke** [comment]
Thanks for the ping. Indeed a bug on our side. I have a fix for SD REST locally but we can actually even fix this one level deeper in SD Commons, as `java.lang` types should never actually be considered entities by the mapping context in the first place.

For reference, the SDR ticket is [here](https://jira.spring.io/browse/DATAREST-1018), the SD Commons one is [here](https://jira.spring.io/browse/DATACMNS-1006).
