### ISSUE TITLE
Spring profiles activation through Environment variable not working 

### ISSUE THREAD

**Issue by waldmeye** [spring-projects/spring-boot#8509]
In my application.yml, I have a LEVEL environment variable and I configured springboot as follow:

```
spring:
  profiles:
    active: ${LEVEL:local}
```

in my application-local.yml, I configured:

```
spring:
  profiles:
    active: local
```

in my application-dev.yml, I configured:

```
spring:
  profiles:
    active: dev
```

When I start my application with SpringBoot v1.4.1 --> works perfectly. The right profile is loaded.
When I start my application with SpringBoot v1.5.2 --> I got this error:

```
17:05:12.086 [main] ERROR org.springframework.boot.SpringApplication - Application startup failed
java.lang.IllegalArgumentException: Invalid profile []: must contain text
	at org.springframework.core.env.AbstractEnvironment.validateProfile(AbstractEnvironment.java:365)
	at org.springframework.core.env.AbstractEnvironment.setActiveProfiles(AbstractEnvironment.java:256)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.prependProfile(ConfigFileApplicationListener.java:598)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.addProfiles(ConfigFileApplicationListener.java:577)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.maybeActivateProfiles(ConfigFileApplicationListener.java:554)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.handleProfileProperties(ConfigFileApplicationListener.java:517)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.loadIntoGroup(ConfigFileApplicationListener.java:477)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:460)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:380)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.addPropertySources(ConfigFileApplicationListener.java:215)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.postProcessEnvironment(ConfigFileApplicationListener.java:184)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:171)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:157)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:73)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:336)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
```

Is that a bug or I'm missing something?

**Comment by wilkinsona** [comment]
Your configuration is rather strange. Activating a profile in a configuration file that's specific to that profile (for example activating the `local` profile in `application-local.yml`) will have no effect as the profile must already be active for the file to be read at all.

What are you trying to achieve?

**Comment by waldmeye** [comment]
I have several Environment. Each environment has a environment variable "LEVEL" where LEVEL values can be [local, dev, test, int ,prod]. I have a common config application.yml and several specific configs:
- application.yml (common to all environments)
- application-dev.yml (for dev environment)
- application-test.yml (for test environment)
...
Until SpringBoot-v.1.4.1, when I deploy on the different environment, the variable "LEVEL" was read and the correct profile was used. 
For example:
I deployed on dev, "LEVEL" environment variable was read (= dev) so application-dev.yml was used.
With SpringBoot-v.1.5.2, I got the error posted in my previous message.

Is that normal? and how can I achieve the same result when deploying?

**Comment by wilkinsona** [comment]
After a bit more experimentation, I can reproduce the behaviour that you're seeing if I configure the `LEVEL` environment variable with an empty value. In 1.4 that empty profile name is ignored. In 1.5 it causes the failure that you're seeing. That difference is a side-effect of [this change](https://github.com/spring-projects/spring-boot/commit/919d0c617227bff1bfd58ed57d9d5080c82f6ac1).

It's certainly possible to restore 1.4's behaviour, but I'm not totally sure that 1.5's behaviour isn't better. What's the reason for configuring `LEVEL` with an empty value?

**Comment by waldmeye** [comment]
Hmm actually ${LEVEL} is never empty. It is defined as Environment Variable on each System where I deploy my App. When I start in Debug, I can see my Variable with the correct value (dev, test, ...) under:
propertySources --> propertySourceList --> SystemEnvironmentPropertySource --> source (list of property)

So I don't understand why it says it is empty. It's like he is not searching at the right place (here in SystemEnvironmentPropertySource )

if LEVEL is undefined, then it takes "local" als default profile, as defined im my application.yml:
spring:
  profiles:
    active: ${LEVEL:local}

if LEVEL is defined with an empty value, then the error is correct for me. But in my case, LEVEL is never defined as empty value and is present in the SystemEnvironmentPropertySource list.

How can I tell at start to read the value of LEVEL in the SystemEnvironmentPropertySource ?

**Comment by wilkinsona** [comment]
> How can I tell at start to read the value of LEVEL in the SystemEnvironmentPropertySource?

That should happen automatically.

Can you please provide a small sample and some step-by-step instructions to reproduce the behaviour you have described?

**Comment by waldmeye** [comment]
Hmm nothing special, I defined 3 application.yml files and an environment variable STAGE. I start my App and it crashes directly. 
I can reproduce it in IntelliJ easily. 
I start with an environment variable Stage=dev (or whatever) and it crashes.
What is funny is that if I rename my environment variable Stage to spring.profiles.active=dev (or local or ...)
then it runs perfectly!!! Weird!! 
I joined u some pics
![applicationconfig](https://cloud.githubusercontent.com/assets/1659036/23658639/a6382482-0343-11e7-935b-1ed9ba77f10e.PNG)
![applicationconfigdev](https://cloud.githubusercontent.com/assets/1659036/23658647/aaee5596-0343-11e7-97be-32280460dc05.PNG)
![applicationconfiglocal](https://cloud.githubusercontent.com/assets/1659036/23658650/ac95cbf4-0343-11e7-902c-350534455b35.PNG)
![intellijstartspringbootappnotok](https://cloud.githubusercontent.com/assets/1659036/23658655/b0e91378-0343-11e7-811d-a3d431efc44f.PNG)
![erroratstart](https://cloud.githubusercontent.com/assets/1659036/23658659/b5203bc4-0343-11e7-8da8-dadde1ce155a.PNG)
![intellijstartspringbootappok](https://cloud.githubusercontent.com/assets/1659036/23658664/b7c45ec8-0343-11e7-9904-db11c48f24fb.PNG)

**Comment by philwebb** [comment]
@waldmeye Could you please upload your sample to GitHub so we can run it? The pictures give us clues, but something we can run will help us a lot more.

**Comment by waldmeye** [comment]
Ok here you have a small "HelloWorld" project that reproduces exactly the same error as mine when you start it with an environment variable "LEVEL=x"

[kib.zip](https://github.com/spring-projects/spring-boot/files/827020/kib.zip)

**Comment by wilkinsona** [comment]
Thanks, @waldmeye. I've reproduced the problem you're seeing. Interestingly, it only occurs when Spring Cloud Sleuth is on the classpath which triggers the use of the bootstrap parent context.

**Comment by wilkinsona** [comment]
The problem's caused by this configuration in your `bootstrap.yml`:

```yaml
spring:
  profiles:
    active: ${ESTA_CLOUDPROFILES_ACTIVE:}
```

The `ESTA_CLOUDPROFILES_ACTIVE` environment variable isn't set so it's defaulting to an empty string. 

This brings me back to my earlier question: what's the request for configuring the active profiles with an empty value?

If no profiles are explicitly activated, then the `default` profile is made active. You could use this configuration which, in my opinion, expresses the intent more clearly:

```yaml
spring:
  profiles:
    active: ${ESTA_CLOUDPROFILES_ACTIVE:default}
```

**Comment by waldmeye** [comment]
ok thanks for the answer! yes ${ESTA_CLOUDPROFILES_ACTIVE:} should have a default value, it's a mistake in the config, not in springboot! 
Thanks a lot for the support!
