### ISSUE TITLE
Eclipse Installer cannot install Oxygen with provided setup file

### ISSUE THREAD

**Issue by rweisleder** [spring-projects/spring-boot#8513]
I followed the [contributing guideline](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-the-eclipse-installer) to install a complete new environment using the Eclipse Installer and the provided setup file.

After choosing "Eclipse IDE for Java Developers" I selected "Latest Release (Neon)" as Product Version and followed the other instructions. After clicking "Finish" the installation failed with this error log:

```
Executing bootstrap tasks
Java(TM) SE Runtime Environment 1.8.0_121-b13
Product org.eclipse.products.epp.package.java.latest.released
Project com.github.user.project.spring.boot.default
Bundle org.eclipse.oomph.setup 1.6.0.v20161125-0947, build=2790, branch=33010448bcf5775ec23e485876cbb07a0340b9b5
Bundle org.eclipse.oomph.setup.core 1.6.0.v20161128-0928, build=2790, branch=33010448bcf5775ec23e485876cbb07a0340b9b5
Bundle org.eclipse.oomph.setup.installer 1.6.0.v20161114-1007, build=2790, branch=33010448bcf5775ec23e485876cbb07a0340b9b5
Bundle org.eclipse.oomph.setup.p2 1.6.0.v20161019-0656, build=2790, branch=33010448bcf5775ec23e485876cbb07a0340b9b5
Performing Workspace C:\Users\xxx\workspaces\spring-boot-neon\ws
Performing P2 Director (Eclipse IDE for Java Developers (Neon))
Offline = false
Mirrors = true
Resolving 42 requirements from 12 repositories to C:\Users\xxx\workspaces\spring-boot-neon\eclipse
Requirement epp.package.java [4.5.0,4.6.0)
Requirement org.eclipse.platform.feature.group
Requirement org.eclipse.jdt.feature.group
Requirement AnyEditTools.feature.group
Requirement org.eclipse.m2e.maveneclipse.feature.feature.group
Requirement org.springframework.ide.eclipse.boot.dash.feature.feature.group
Requirement org.springframework.ide.eclipse.feature.feature.group
Requirement org.springframework.ide.eclipse.maven.feature.feature.group
Requirement org.eclipse.jst.server_adapters.feature.feature.group
Requirement org.eclipse.jst.server_adapters.ext.feature.feature.group
Requirement org.eclipse.jst.server_ui.feature.feature.group
Requirement org.eclipse.wst.server_adapters.feature.feature.group
Requirement org.eclipse.jst.web_ui.feature.feature.group
Requirement org.eclipse.wst.web_ui.feature.feature.group
Requirement org.sonatype.m2e.buildhelper.feature.feature.group
Requirement org.eclipse.mylyn.github.feature.feature.group
Requirement org.springframework.ide.eclipse.jdt.formatter.feature.feature.group
Requirement epp.package.java [4.6.0,4.7.0)
Requirement org.eclipse.platform.feature.group [4.6.0,4.7.0)
Requirement org.eclipse.rcp.feature.group [4.6.0,4.7.0)
Requirement org.eclipse.buildship.feature.group
Requirement org.eclipse.egit.feature.group
Requirement org.eclipse.egit.mylyn.feature.group
Requirement org.eclipse.jgit.feature.group
Requirement org.eclipse.m2e.feature.feature.group
Requirement org.eclipse.m2e.logback.feature.feature.group
Requirement org.eclipse.mylyn.bugzilla_feature.feature.group
Requirement org.eclipse.mylyn.context_feature.feature.group
Requirement org.eclipse.mylyn.git.feature.group
Requirement org.eclipse.mylyn.hudson.feature.group
Requirement org.eclipse.mylyn.ide_feature.feature.group
Requirement org.eclipse.mylyn.java_feature.feature.group
Requirement org.eclipse.mylyn.wikitext_feature.feature.group
Requirement org.eclipse.mylyn_feature.feature.group
Requirement org.eclipse.recommenders.mylyn.rcp.feature.feature.group
Requirement org.eclipse.recommenders.rcp.feature.feature.group
Requirement org.eclipse.recommenders.snipmatch.rcp.feature.feature.group
Requirement org.eclipse.wst.xml_ui.feature.feature.group
Requirement org.eclipse.oomph.setup.feature.group
Requirement org.eclipse.oomph.setup.jdt.feature.group
Requirement org.eclipse.oomph.setup.maven.feature.group
Requirement org.eclipse.oomph.setup.workingsets.feature.group
Repository http://download.eclipse.org/technology/epp/packages/mars/R
Repository http://download.eclipse.org/releases/mars
Repository http://andrei.gmxhome.de/eclipse
Repository https://dl.bintray.com/philwebb/m2eclipse-maveneclipse
Repository https://dl.bintray.com/philwebb/spring-eclipse-code-formatter
Repository http://dist.springsource.com/release/TOOLS/update/e4.5
Repository http://download.eclipse.org/egit/github/updates/
Repository http://download.eclipse.org/technology/epp/packages/neon
Repository http://download.eclipse.org/releases/neon/201612211000
Repository http://download.eclipse.org/oomph/updates/milestone/latest
Repository http://download.eclipse.org/technology/m2e/milestones/1.5
Repository http://download.eclipse.org/webtools/repository/luna
Adding repository http://download.eclipse.org/technology/epp/packages/mars/R
Adding repository http://dist.springsource.com/release/TOOLS/update/e4.5
Adding repository http://download.eclipse.org/egit/github/updates/
Adding repository http://andrei.gmxhome.de/eclipse
Adding repository http://download.eclipse.org/webtools/repository/luna
Fetching p2.index from http://download.eclipse.org/technology/epp/packages/neon/
Fetching p2.index from http://download.eclipse.org/releases/neon/201612211000/
Fetching p2.index from http://download.eclipse.org/releases/mars/
Adding repository http://download.eclipse.org/oomph/updates/milestone/latest
Adding repository http://download.eclipse.org/technology/m2e/milestones/1.5
Fetching p2.index from http://download.eclipse.org/releases/mars/
Fetching p2.index from http://download.eclipse.org/releases/neon/201612211000/
Fetching p2.index from http://download.eclipse.org/technology/epp/packages/neon/
Adding repository http://download.eclipse.org/technology/epp/packages/neon
Adding repository http://download.eclipse.org/releases/neon/201612211000
Adding repository http://download.eclipse.org/releases/mars
Adding repository https://dl.bintray.com/philwebb/spring-eclipse-code-formatter
Fetching p2.index from https://dl.bintray.com/philwebb/m2eclipse-maveneclipse/ (172B)
Fetching site.xml from http://andrei.gmxhome.de/eclipse/ (4,74kB)
Adding repository https://dl.bintray.com/philwebb/m2eclipse-maveneclipse
Calculating requirements and dependencies.
Cannot complete the request.  Generating details.
ERROR: org.eclipse.equinox.p2.director code=10054 Cannot complete the install because of a conflicting dependency.
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:280)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.resolve(ProfileTransactionImpl.java:425)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:337)
  at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:729)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3305)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3233)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3214)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3114)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:556)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:682)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
  ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1488836061745
  ERROR: org.eclipse.equinox.p2.director code=1 Only one of the following can be installed at once: 
    ERROR: org.eclipse.equinox.p2.director code=0 Eclipse IDE for Java Developers 4.6.2.20161208-0625 (epp.package.java 4.6.2.20161208-0625)
    ERROR: org.eclipse.equinox.p2.director code=0 Eclipse IDE for Java Developers 4.5.0.20150621-1200 (epp.package.java 4.5.0.20150621-1200)
    ERROR: org.eclipse.equinox.p2.director code=0 Eclipse IDE for Java Developers 4.5.1.20150917-1200 (epp.package.java 4.5.1.20150917-1200)
    ERROR: org.eclipse.equinox.p2.director code=0 Eclipse IDE for Java Developers 4.5.2.20160218-0600 (epp.package.java 4.5.2.20160218-0600)
    ERROR: org.eclipse.equinox.p2.director code=0 Eclipse IDE for Java Developers 4.6.0.20160613-1800 (epp.package.java 4.6.0.20160613-1800)
    ERROR: org.eclipse.equinox.p2.director code=0 Eclipse IDE for Java Developers 4.6.1.20160913-0645 (epp.package.java 4.6.1.20160913-0645)
    ERROR: org.eclipse.equinox.p2.director code=0 Eclipse IDE for Java Developers 4.6.1.20161007-1200 (epp.package.java 4.6.1.20161007-1200)
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1488836061745
    ERROR: org.eclipse.equinox.p2.director code=0 To: epp.package.java [4.5.0,4.6.0)
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1488836061745
    ERROR: org.eclipse.equinox.p2.director code=0 To: epp.package.java [4.6.0,4.7.0)

Took 13 seconds.
There are failed tasks.
Press Back to choose different settings or Cancel to abort.
```

I went back to the first setup page and selected "Mars" and started the installation again, which was successful. Relevant part of the log:

```
Executing bootstrap tasks
Java(TM) SE Runtime Environment 1.8.0_121-b13
Product org.eclipse.products.epp.package.java.mars
Project com.github.user.project.spring.boot.default
Bundle org.eclipse.oomph.setup 1.6.0.v20161125-0947, build=2790, branch=33010448bcf5775ec23e485876cbb07a0340b9b5
Bundle org.eclipse.oomph.setup.core 1.6.0.v20161128-0928, build=2790, branch=33010448bcf5775ec23e485876cbb07a0340b9b5
Bundle org.eclipse.oomph.setup.installer 1.6.0.v20161114-1007, build=2790, branch=33010448bcf5775ec23e485876cbb07a0340b9b5
Bundle org.eclipse.oomph.setup.p2 1.6.0.v20161019-0656, build=2790, branch=33010448bcf5775ec23e485876cbb07a0340b9b5
Performing Workspace C:\Users\xxx\workspaces\spring-boot-mars\ws
Performing P2 Director (Eclipse IDE for Java Developers (Mars))
Offline = false
Mirrors = true
Resolving 25 requirements from 12 repositories to C:\Users\xxx\workspaces\spring-boot-mars\eclipse
Requirement epp.package.java [4.5.0,4.6.0)
Requirement org.eclipse.platform.feature.group
Requirement org.eclipse.jdt.feature.group
Requirement AnyEditTools.feature.group
Requirement org.eclipse.m2e.maveneclipse.feature.feature.group
Requirement org.springframework.ide.eclipse.boot.dash.feature.feature.group
Requirement org.springframework.ide.eclipse.feature.feature.group
Requirement org.springframework.ide.eclipse.maven.feature.feature.group
Requirement org.eclipse.jst.server_adapters.feature.feature.group
Requirement org.eclipse.jst.server_adapters.ext.feature.feature.group
Requirement org.eclipse.jst.server_ui.feature.feature.group
Requirement org.eclipse.wst.server_adapters.feature.feature.group
Requirement org.eclipse.jst.web_ui.feature.feature.group
Requirement org.eclipse.wst.web_ui.feature.feature.group
Requirement org.sonatype.m2e.buildhelper.feature.feature.group
Requirement org.eclipse.mylyn.github.feature.feature.group
Requirement org.springframework.ide.eclipse.jdt.formatter.feature.feature.group
Requirement org.eclipse.platform.feature.group [4.5.0,4.6.0)
Requirement org.eclipse.rcp.feature.group [4.5.0,4.6.0)
Requirement org.eclipse.jdt.feature.group [3.11.0,3.12.0)
Requirement org.eclipse.oomph.setup.feature.group
Requirement org.eclipse.oomph.setup.jdt.feature.group
Requirement org.eclipse.oomph.setup.maven.feature.group
Requirement org.eclipse.m2e.feature.feature.group
Requirement org.eclipse.oomph.setup.workingsets.feature.group
Repository http://download.eclipse.org/technology/epp/packages/mars/R
Repository http://download.eclipse.org/releases/mars
Repository http://andrei.gmxhome.de/eclipse
Repository https://dl.bintray.com/philwebb/m2eclipse-maveneclipse
Repository https://dl.bintray.com/philwebb/spring-eclipse-code-formatter
Repository http://dist.springsource.com/release/TOOLS/update/e4.5
Repository http://download.eclipse.org/egit/github/updates/
Repository http://download.eclipse.org/technology/epp/packages/mars
Repository http://download.eclipse.org/releases/mars/201602261000
Repository http://download.eclipse.org/oomph/updates/milestone/latest
Repository http://download.eclipse.org/technology/m2e/milestones/1.5
Repository http://download.eclipse.org/webtools/repository/luna
Adding repository http://download.eclipse.org/releases/mars
Adding repository https://dl.bintray.com/philwebb/m2eclipse-maveneclipse
Adding repository http://andrei.gmxhome.de/eclipse
Adding repository http://dist.springsource.com/release/TOOLS/update/e4.5
Adding repository http://download.eclipse.org/technology/epp/packages/mars
Adding repository http://download.eclipse.org/egit/github/updates/
Adding repository https://dl.bintray.com/philwebb/spring-eclipse-code-formatter
Adding repository http://download.eclipse.org/releases/mars/201602261000
Adding repository http://download.eclipse.org/webtools/repository/luna
Adding repository http://download.eclipse.org/technology/m2e/milestones/1.5
Adding repository http://download.eclipse.org/technology/epp/packages/mars/R
Adding repository http://download.eclipse.org/oomph/updates/milestone/latest
Calculating requirements and dependencies.
```

I'm not sure if this is an error of Eclipse or of the setup file.

**Comment by schlauergerd** [comment]
Ah, two lines above it says "any Eclipse Mars based distribution", my bad...

But what about Neon and upcoming releases?

**Comment by snicoll** [comment]
@rweisleder sorry that one must have fallen through the cracks. Is this still a problem?

**Comment by rweisleder** [comment]
For me it isn't a problem anymore because I installed Eclipse Mars due to this error.

With all updates for Eclipse Installer installed it's still reproducible. Other new contributors could stumble upon this.

**Comment by pierrefevrier** [comment]
I have the same issue right now with Oxygen release.
