### ISSUE TITLE
ClassCastException during parsing of YAML configuration

### ISSUE THREAD

**Issue by michael-simons** [spring-projects/spring-boot#8540]
Hello,

I'm currently testing the 2.0.0.BUILD-SNAPSHOTS as I'm working on an example project regarding external configuration.

Latest build delivers a `ClassCastException` during startup:

```
Caused by: java.lang.ClassCastException: org.springframework.boot.env.OriginTrackedValue$OriginTrackedCharSequence cannot be cast to java.lang.String
	at org.springframework.beans.factory.config.YamlProcessor.buildFlattenedMap(YamlProcessor.java:277)
	at org.springframework.beans.factory.config.YamlProcessor.buildFlattenedMap(YamlProcessor.java:294)
	at org.springframework.beans.factory.config.YamlProcessor.buildFlattenedMap(YamlProcessor.java:302)
	at org.springframework.beans.factory.config.YamlProcessor.buildFlattenedMap(YamlProcessor.java:294)
	at org.springframework.beans.factory.config.YamlProcessor.getFlattenedMap(YamlProcessor.java:271)
	at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:223)
	at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:161)
	at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:138)
	at org.springframework.boot.env.OriginTrackedYamlLoader.load(OriginTrackedYamlLoader.java:76)
	at org.springframework.boot.env.YamlPropertySourceLoader.load(YamlPropertySourceLoader.java:45)
	at org.springframework.boot.env.PropertySourcesLoader.load(PropertySourcesLoader.java:127)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.loadIntoGroup(ConfigFileApplicationListener.java:428)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:415)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:335)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.addPropertySources(ConfigFileApplicationListener.java:190)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.postProcessEnvironment(ConfigFileApplicationListener.java:172)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:159)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:145)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:73)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:369)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338)
```

With the following configuration:

```yaml
someValue: 4711

example:
    the-greeting: Hello, World!
    interval: 1000
    precision: 42.23
    servers:
        - name: springbootbuch
          url: http://springbootbuch.de

---
spring:
    profiles: demo1

example:
    the-greeting: Hello, Demo1!
    servers:
        - name: demo
          url: http://test.com

---
spring:
    profiles: demo2

example:
    the-greeting: Hello, Demo2!
    interval: 2000
    servers:
        - name: bootifultodos
          url: http://bootifultodos.de

---
spring:
    profiles: "!demo2"

someValue: 2109
```

The configuration is maybe a bit extreme, but serves the purpose of explaining external configuration very well. The whole project is available [here](https://github.com/springbootbuch/extconfig), but that doesn't build right now due to open bug #8011 (present in 1.4.x, 1.5.x and 2.0.x).

I have attached a simplified version that contains the error described in this ticket and nothing else. Using 1.5.x it starts just fine: 
[extconfig-simplified.zip](https://github.com/spring-projects/spring-boot/files/827339/extconfig-simplified.zip)

My expectations: Spring Boot should parse this configuration file as before, taking the negated profiles into regard.
If it's too early to write bugs for 2.0.0, please let me know. 

Edit: The exception also happens if I use " for the string values.

Thanks,
Michael

**Comment by spencergibb** [comment]
FYI, I also see this in builds here https://circleci.com/gh/spring-cloud-incubator/spring-cloud-gateway/34

**Comment by Toparvion** [comment]
Facing the same problem with `spring-boot 2.0.0.BUILD-SNAPSHOT` (as of current date).
The YAML config looks like:

```yaml
server:
  port: 8080

remote:
  incoming:
    address: localhost
    port: 21005

choices:
  - group: Logs UPC-1
    pathBase: C:\lang\analog\log-samples\
    paths:
      - logSample.log as "Example ($F)"
```

Debugger helps to see that the error arises while handling `group` entry. In this case the entry's key is really `org.springframework.boot.env.OriginTrackedValue$OriginTrackedCharSequence` (while for all other keys it has `String` class).
Ready to provide additional details if needed.

**Comment by spencergibb** [comment]
I can confirm that adding
```
choices:
  - group: Logs UPC-1
    pathBase: C:\lang\analog\log-samples\
    paths:
      - logSample.log as "Example ($F)"
```
to `test-yaml.yml` breaks `OriginTrackedYamlLoaderTests`.

**Comment by spencergibb** [comment]
Adding the following method to `OriginTrackedYamlLoader.OriginTrackingConstructor` fixed the error:

```java
		@Override
		protected void constructMapping2ndStep(MappingNode node, Map<Object, Object> mapping) {
			List<NodeTuple> nodeValue = node.getValue();
			for (NodeTuple tuple : nodeValue) {
				Node keyNode = tuple.getKeyNode();
				Node valueNode = tuple.getValueNode();
				Object key = constructObject(keyNode);
				if (key != null) {
					try {
						key.hashCode();// check circular dependencies
					} catch (Exception e) {
						throw new RuntimeException("while constructing a mapping " +
								node.getStartMark()+ "found unacceptable key " + key + ", " +
								tuple.getKeyNode().getStartMark(), e);
					}
				}
				Object value = constructObject(valueNode);
				if (keyNode.isTwoStepsConstruction()) {
                /*
                 * if keyObject is created it 2 steps we should postpone putting
                 * it in map because it may have different hash after
                 * initialization compared to clean just created one. And map of
                 * course does not observe key hashCode changes.
                 */
					/*maps2fill.add(0,
							new RecursiveTuple<Map<Object, Object>, RecursiveTuple<Object, Object>>(
									mapping, new RecursiveTuple<Object, Object>(key, value)));*/
				} else {
					if (key instanceof CharSequence) {
						mapping.put(key.toString(), value);
					} else {
						mapping.put(key, value);
					}
				}
			}
		}
```

Not sure the commented out `maps2fill` statement is a good thing though.

**Comment by mbhave** [comment]
@spencergibb fixed it in a slightly different way. thanks anyway!
