### ISSUE TITLE
Actuator /loggers endpoint: 'java.lang.IllegalArgumentException: EffectiveLevel must not be null'

### ISSUE THREAD

**Issue by wujek-srujek** [spring-projects/spring-boot#8639]
I'm using 1.5.2.RELEASE and configure logging using logback-spring.xml. When I go to the 'loggers' endpoint, I get:

	Caused by: java.lang.IllegalArgumentException: EffectiveLevel must not be null
		at org.springframework.util.Assert.notNull(Assert.java:134)
		at org.springframework.boot.logging.LoggerConfiguration.<init>(LoggerConfiguration.java:45)
		at org.springframework.boot.logging.logback.LogbackLoggingSystem.getLoggerConfiguration(LogbackLoggingSystem.java:241)
		at org.springframework.boot.logging.logback.LogbackLoggingSystem.getLoggerConfigurations(LogbackLoggingSystem.java:218)
		at org.springframework.boot.actuate.endpoint.LoggersEndpoint.invoke(LoggersEndpoint.java:58)
		at org.springframework.boot.actuate.endpoint.LoggersEndpoint.invoke(LoggersEndpoint.java:40)
		at org.springframework.boot.actuate.endpoint.mvc.AbstractEndpointMvcAdapter.invoke(AbstractEndpointMvcAdapter.java:56)
		at org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke(EndpointMvcAdapter.java:42)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
		at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
		at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116)
		at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
		at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
		at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
		at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
		at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
		at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
		... 86 common frames omitted

(this is just the root cause)

Configuration:

    <?xml version="1.0" encoding="UTF-8"?>
    
    <configuration>
        <include resource="org/springframework/boot/logging/logback/defaults.xml"/>
        <include resource="org/springframework/boot/logging/logback/console-appender.xml"/>
    
        <logger name="com.my.package" level="ALL"/>
        <logger name="org.hibernate.SQL" level="DEBUG"/>
    
        <root level="INFO">
            <appender-ref ref="CONSOLE"/>
        </root>
    </configuration>

**Comment by philwebb** [comment]
I've replicated this locally. The root cause is we don't know how to map `ALL` to one of our `LoggingLevel` values. 

Our current mappings are:

```java
		LEVELS.map(LogLevel.TRACE, Level.TRACE);
		LEVELS.map(LogLevel.DEBUG, Level.DEBUG);
		LEVELS.map(LogLevel.INFO, Level.INFO);
		LEVELS.map(LogLevel.WARN, Level.WARN);
		LEVELS.map(LogLevel.ERROR, Level.ERROR);
		LEVELS.map(LogLevel.FATAL, Level.ERROR);
		LEVELS.map(LogLevel.OFF, Level.OFF);
```

**Comment by philwebb** [comment]
You can work around the issue by using `<logger name="com.my.package" level="TRACE"/>`
