### ISSUE TITLE
spring-boot sets up org.jboss.logging.provider system property to slf4j, thus setting it so for entire vm in which glassfish is running, causing glassfish server to crash whenever any hibernate specific class is loaded.

### ISSUE THREAD

**Issue by vinayvishal** [spring-projects/spring-boot#8669]
**Issue**

In versions v1.1.10.RELEASE and v1.2.0.RC2,  to address gh-1928 [[1](https://github.com/spring-projects/spring-boot/issues/1928)], `org.jboss.logger.provider` system property is being set in `LogbackLoggingSystem.java` [[2](https://github.com/spring-projects/spring-boot/blob/1.1.x/spring-boot/src/main/java/org/springframework/boot/logging/logback/LogbackLoggingSystem.java)] to `slf4j`.

**Bug Report**

From application server's context, this results in setting this system property for entire jvm thus causing glassfish to crash down when spring-boot sample application is deployed on glassfish [3]. corresponding glassfish issue is GLASSFISH-21641 [[4](https://java.net/jira/browse/GLASSFISH-21641)].

Since glassfish too uses hibernate validator and hibernate validator uses jboss logging [[5](http://docs.jboss.org/hibernate/orm/4.3/topical/html/logging/Logging.html)], setting this property to slf4j results in glassfish looking for sfl4j specific classes, for any other application deployed on glassfish or even for glassfish itself, which results in `java.lang.ClassNotFoundException` for `org.slf4j.LoggerFactory`, thus ultimately resulting in `java.lang.NoClassDefFoundError` while trying to load `org.hibernate.validator.internal.engine.ConfigurationImpl` class.

**Enhancement**

Since jboss logging supports `java.util.ServiceLoader` approach too for finding application specific logger [[5](http://docs.jboss.org/hibernate/orm/4.3/topical/html/logging/Logging.html)], ideally this should be preferred over setting system property which is global to entire vm thus impacting other applications too deployed on the same vm.

[1] https://github.com/spring-projects/spring-boot/issues/1928
[2] https://github.com/spring-projects/spring-boot/blob/1.1.x/spring-boot/src/main/java/org/springframework/boot/logging/logback/LogbackLoggingSystem.java
[3] https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-deployment-test-glassfish/1.4.2.RELEASE
[4] https://java.net/jira/browse/GLASSFISH-21641
[5] http://docs.jboss.org/hibernate/orm/4.3/topical/html/logging/Logging.html
[6] http://stackoverflow.com/questions/7597925/scope-of-system-setproperty-in-tomcat/7598004#7598004

**Comment by wilkinsona** [comment]
> Since jboss logging supports java.util.ServiceLoader approach too for finding application specific logger [5], ideally this should be preferred over setting system property

I agree that it would be better not to use the service loader approach, but I'm not sure that we can. Using a system property allows us to make a decision at runtime, whereas using the service loader requires the decision to be made once and then applied to everyone who uses the `spring-boot` jar.

Given that #1928 was addressing a problem with Log4j which we no longer support, I wonder if we may be able to remove the setting of the system property altogether. It'll require some experimentation to see if the problem that was reported can be created with something other than Log4j.

**Comment by philwebb** [comment]
For 1.5.x we could perhaps only set `org.jboss.logging.provider` if it's not already defined. That way you could at least tweak Glassfish to start.

**Comment by wilkinsona** [comment]
The problem reported in #1928 doesn't appear to occur with Log4j2, but you can get in a bit of a mess if you try hard enough when the system property isn't set.

Log4j2 has its own SLF4J binding. If you have both Log4j2 and Logback on the classpath you get some error output when Logback appears first:

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/awilkinson/.m2/repository/ch/qos/logback/logback-classic/1.1.11/logback-classic-1.1.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/awilkinson/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.7/log4j-slf4j-impl-2.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
```

When Logback appears second the application fails to start with a recommendation to tidy up your classpath:

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/awilkinson/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.7/log4j-slf4j-impl-2.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/awilkinson/.m2/repository/ch/qos/logback/logback-classic/1.1.11/logback-classic-1.1.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Exception in thread "main" java.lang.IllegalArgumentException: LoggerFactory is not a Logback LoggerContext but Logback is on the classpath. Either remove Logback or the competing implementation (class org.apache.logging.slf4j.Log4jLoggerFactory loaded from file:/Users/awilkinson/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.7/log4j-slf4j-impl-2.7.jar). If you are using WebLogic you will need to add 'org.slf4j' to prefer-application-packages in WEB-INF/weblogic.xml: org.apache.logging.slf4j.Log4jLoggerFactory
	at org.springframework.util.Assert.instanceCheckFailed(Assert.java:389)
	at org.springframework.util.Assert.isInstanceOf(Assert.java:327)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.getLoggerContext(LogbackLoggingSystem.java:273)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.beforeInitialize(LogbackLoggingSystem.java:97)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationStartingEvent(LoggingApplicationListener.java:230)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:209)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
	at org.springframework.boot.context.event.EventPublishingRunListener.starting(EventPublishingRunListener.java:68)
	at org.springframework.boot.SpringApplicationRunListeners.starting(SpringApplicationRunListeners.java:48)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151)
	at sample.data.jpa.SampleDataJpaApplication.main(SampleDataJpaApplication.java:26)
```

I think both of these are fine.

If you take things a step further, you can shoot yourself in the foot by having Logback and Log4j2 on the classpath in that order but the latter without its `log4j-slf4j-impl` module. At this point you don't get any warnings or error output at startup, but JBoss Logging uses Log4j2 while everything else uses SLF4J and Logback. The result of this is that any logging that's performed through JBoss Logging is silently lost.

I think this boils down to two choices:

1. Set the system property and potentially cause problems for people using Glassfish and perhaps other app servers too
2. Let people with a messed up classpath silently lose logging that performed throught JBoss logging

My inclination is that 2 is the lesser of two evils and that we should remove the call that sets the system property.

**Comment by philwebb** [comment]
A third option might be to only set the property if we're running from a fat jar (if that's even possible).

**Comment by wilkinsona** [comment]
We've decided to remove the setting of the system property. There's a small risk that it will be a breaking change (see the rather convoluted scenario described above) so this will have to wait till 2.0.

**Comment by vinayvishal** [comment]
Thanks for the update.
