### ISSUE TITLE
spring-boot application stops when logging.config points to incorrect file location for logfj2 external configuartion file

### ISSUE THREAD

**Issue by rashmi-dey** [spring-projects/spring-boot#8696]
In my spring-boot application I have externalized the log4j2.xml file and added the location of the configuration file using logging.config properties in application.properties file.

If I give an incorrect file location in logging.config then my application doesn't start and throw the following error:

    [main] ERROR org.springframework.boot.SpringApplication - Application startup failed
    java.lang.IllegalStateException: java.io.FileNotFoundException: /tmp/log4j2.xml (No such file or directory)
    	at org.springframework.boot.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:315) ~[spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
    	at org.springframework.boot.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:276) ~[spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
    	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:239) ~[spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
    	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:212) ~[spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
    	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167) ~[spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]
    	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]
    	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122) ~[spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]
    	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:73) ~[spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
    	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54) ~[spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
    	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:336) [spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
    	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) [spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
    	at my.application.Application.main(Application.java:67) [classes/:?]
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
    	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
    	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144) [idea_rt.jar:?]

I think the ideally the application should startup with default logging. Is there a way so that I can put in the default logging configuration or have spring-boot application start with default logging capabilities.

I am using log4j2 and spring-boot. 

In initializeSystem(ConfigurableEnvironment environment, LoggingSystem system, LogFile logFile) function of LoggingApplicationListner.java shouldn;t we try using default logging configuration or look for log configuration in classpath, when the file path mentioned in logging.config is invalid.

I am new on posting question, please pardon if I am missing any information.

**Comment by wilkinsona** [comment]
> I think the ideally the application should startup with default logging

We (the Spring Boot team) have discussed this before and we disagree. In our opinion, it's better that an application fails to start if there's an error in its logging configuration. This makes it less likely that you'll lose information or miss out on alerts due to a configuration mistake.

**Comment by rashmi-dey** [comment]
I agree that it can cause issues. But shouldn't it look for the configuration file in classpath or see if default logging can be started. It can log an error saying the file is missing rather then not letting the application to start. And for monitoring, users can monitor that the logging has started properly by ensuring the log files are present or by any other way.

**Comment by philwebb** [comment]
> And for monitoring, users can monitor that the logging has started properly by ensuring the log files are present or by any other way.

This relies on an appropriate monitoring solution having been setup and tested. If this doesn't happen then configuration errors won't be caught. We prefer the hard failure that must be fixed.

If you don't like these defaults you can set the `LoggingSystem.SYSTEM_PROPERTY` system property to `LoggingSystem.NONE` and configure your logging library however you like.
