### ISSUE TITLE
Provide better diagnostics when a nested jar file cannot be read

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#8711]
`JarFile.getNestedJarFile(JarEntry)` currently catches `IOException` and throws a new `IOException` with a message that includes the name of the nested jar file that could not be read. We should catch `Exception` instead so that other failures (such as the one seen in #8707) will also identify the problematic nested entry

**Comment by venkattarigopula** [comment]
Hello,
 I am having same issue. I tried to build on spring boot 1.5.4 and 1.5.6. But same exception is coming while running the docker. 

Exception in thread "main" java.lang.IndexOutOfBoundsException
	at org.springframework.boot.loader.jar.AsciiBytes.<init>(AsciiBytes.java:68)
	at org.springframework.boot.loader.jar.CentralDirectoryFileHeader.load(CentralDirectoryFileHeader.java:83)
	at org.springframework.boot.loader.jar.CentralDirectoryParser.parseEntries(CentralDirectoryParser.java:68)
	at org.springframework.boot.loader.jar.CentralDirectoryParser.parse(CentralDirectoryParser.java:57)
	at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:118)
	at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:106)
	at org.springframework.boot.loader.jar.JarFile.createJarFileFromFileEntry(JarFile.java:290)
	at org.springframework.boot.loader.jar.JarFile.createJarFileFromEntry(JarFile.java:260)
	at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:248)
	at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:237)
	at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchive(JarFileArchive.java:103)
	at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchives(JarFileArchive.java:87)
	at org.springframework.boot.loader.ExecutableArchiveLauncher.getClassPathArchives(ExecutableArchiveLauncher.java:72)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:49)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58)

thanks and regards,
Venkat

**Comment by venkattarigopula** [comment]
The issue has been resolved. Because of the maven repos corruption, it could not load the jar. Deleted the repo and downloaded again. it solved the issue
