### ISSUE TITLE
ClassNotFoundException for org.elasticsearch.cluster.health.ClusterHealthStatus

### ISSUE THREAD

**Issue by syakovyn** [spring-projects/spring-boot#8778]
I'm using `org.springframework.boot:spring-boot-starter-actuator:1.5.2.RELEASE` and `org.elasticsearch:elasticsearch:1.5.2`. When performing the healthcheck I'm getting strange exception:

java.lang.ClassNotFoundException: org.elasticsearch.cluster.health.ClusterHealthStatus
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_66]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_66]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_66]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_66]
	at org.springframework.boot.actuate.health.ElasticsearchHealthIndicator$1.<clinit>(ElasticsearchHealthIndicator.java:54) ~[spring-boot-actuator-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.actuate.health.ElasticsearchHealthIndicator.doHealthCheck(ElasticsearchHealthIndicator.java:54) ~[spring-boot-actuator-1.5.2.RELEASE.jar:1.5.2.RELEASE]

As far as I know, `org.elasticsearch.cluster.health.ClusterHealthStatus` was moved from `org.elasticsearch.action.admin.cluster.health.ClusterHealthStatus` in ElasticSearch 2.x, that I am not using, nor I can see it being referenced in spring-boot-actuator.

The further examination of the source code of ElasticsearchHealthIndicator.class showed:
1. Java source code line 54: `switch (response.getStatus()) {`. Nothing suspicious.
2. Decompiled code: `switch(null.$SwitchMap$org$elasticsearch$cluster$health$ClusterHealthStatus[response.getStatus().ordinal()]) {`. Somehow `org.elasticsearch.cluster.health.ClusterHealthStatus` reference appeared in the compiled code.
3. Byte code: 
L7
    LINENUMBER 54 L7
    GETSTATIC org/springframework/boot/actuate/health/ElasticsearchHealthIndicator$1.$SwitchMap$org$elasticsearch$cluster$health$ClusterHealthStatus : [I

**Comment by syakovyn** [comment]
I went through the different versions of org.springframework.boot:spring-boot-actuator and the last version, not affected by the mixed classes issue, is 1.3.8.RELEASE

**Comment by wilkinsona** [comment]
Spring Boot 1.4 and 1.5 require Elasticsearch 2.4.x and that is the version that's provided in their dependency management. You'll need to stick with Spring Boot 1.3.x or upgrade your Elasticsearch dependency.
