### ISSUE TITLE
Actuator and AutoConfigure crash when setAllowBeanDefinitionOverriding(false);

### ISSUE THREAD

**Issue by mistriel** [spring-projects/spring-boot#8833]
Hi,

I'm using Boot 1.4.4.RELEASE with Actuator and AutoConfigure in my classpath.
I also set Bean Definition Override to false : 
```java
public class BeanOverrideDisablerApplicationContextInitializer
		implements ApplicationContextInitializer<ConfigurableApplicationContext> {

	@Override
	public void initialize(ConfigurableApplicationContext applicationContext) {

		if (applicationContext.getBeanFactory() instanceof DefaultListableBeanFactory) {
			((DefaultListableBeanFactory) applicationContext.getBeanFactory()).setAllowBeanDefinitionOverriding(false);
		}

	}

}

```

When i have multiple bean candidates with the same name i handle this in my custom 
`BeanDefinitionRegistryPostProcessor` .

# Failure 
Upon startup (when both in the classpath) i get the following exception : 

```
org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'ignoredPathsWebSecurityConfigurerAdapter' defined in class path resource [org/springframework/boot/actuate/autoconfigure/ManagementWebSecurityAutoConfiguration.class]: Cannot register bean definition [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.actuate.autoconfigure.ManagementWebSecurityAutoConfiguration; factoryMethodName=ignoredPathsWebSecurityConfigurerAdapter; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/actuate/autoconfigure/ManagementWebSecurityAutoConfiguration.class]] for bean 'ignoredPathsWebSecurityConfigurerAdapter': There is already [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.security.SpringBootWebSecurityConfiguration; factoryMethodName=ignoredPathsWebSecurityConfigurerAdapter; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/security/SpringBootWebSecurityConfiguration.class]] bound.
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.registerBeanDefinition(DefaultListableBeanFactory.java:814)
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:260)
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:140)
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:116)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:320)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:228)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:270)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:93)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:686)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:524)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:372)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1187)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1176)
        at com.amdocs.msnext.boot.Boot.main(Boot.java:21)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
```

## A Bit Analysis

Looking on ManagementWebSecurityAutoConfiguration (actuator) and on SpringBootWebSecurityConfiguration (autoconfigure) configuration classes,
The bean 'ignoredPathsWebSecurityConfigurerAdapter'  is annotated specifically as  @ConditionalOnMissingBean 

AFAIK this error should not have happen in this case, is it ?
Thanks,
Avi.

**Comment by wilkinsona** [comment]
They're two different classes:

- `org.springframework.boot.autoconfigure.security.SpringBootWebSecurityConfiguration.IgnoredPathsWebSecurityConfigurerAdapter`
- `org.springframework.boot.actuate.autoconfigure.ManagementWebSecurityAutoConfiguration.IgnoredPathsWebSecurityConfigurerAdapter`

This has already been tidied up in 1.5: https://github.com/spring-projects/spring-boot/issues/7106

**Comment by mistriel** [comment]
Thanks its indeed resolved in 1.5.
Yet i don't quiet understand your answer - just for the discussion if you don't mind,
you are right that those are two different classes yet the bean name is the same.
so setting the Bean Definition Override to false should normally cause that issue above  **unless there is conditional mentioned** (and there is on both configuration classes).

So the exception should be considered as a bug, doesn't it ?

**Comment by wilkinsona** [comment]
The condition uses the bean's class not it's name

**Comment by jjroldan1** [comment]
The condition never kicks in as the same bean name is used and only one makes it to the context.
