### ISSUE TITLE
When spring.freemarker.template-loader-path contains an S3 bucket, then PathBasedTemplateAvailabilityProvider throws an Exception

### ISSUE THREAD

**Issue by bgiaccio** [spring-projects/spring-boot#8936]
I'm attempting to store my FTL templates in an s3 bucket.  I was initially using spring-boot 1.5.2.RELEASE and was getting an exception at startup.

Then I found https://github.com/spring-projects/spring-boot/issues/8842  and thinking this might help I switched to 1.5.3.BUILD-SNAPSHOT.  However, the issue wasn't resolved it was just moved to the new classes.

```ini
spring.freemarker.template-loader-path=s3://my-bucket/templates, classpath:/templates/
```

The strange thing is running as a spring-boot application in Eclipse or from maven it works just fine, but when I bundle the jar and run 'java -jar foo.jar'  I get the following stack trace at startup and the application aborts.

```
Caused by: java.lang.IllegalArgumentException: name
	at sun.misc.URLClassPath$Loader.findResource(URLClassPath.java:693) ~[na:1.8.0_121]
	at sun.misc.URLClassPath.findResource(URLClassPath.java:215) ~[na:1.8.0_121]
	at java.net.URLClassLoader$2.run(URLClassLoader.java:569) ~[na:1.8.0_121]
	at java.net.URLClassLoader$2.run(URLClassLoader.java:567) ~[na:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_121]
	at java.net.URLClassLoader.findResource(URLClassLoader.java:566) ~[na:1.8.0_121]
	at org.springframework.boot.loader.LaunchedURLClassLoader.findResource(LaunchedURLClassLoader.java:58) ~[compliance-service-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at java.lang.ClassLoader.getResource(ClassLoader.java:1096) ~[na:1.8.0_121]
	at org.springframework.core.io.ClassPathResource.resolveURL(ClassPathResource.java:147) ~[spring-core-4.3.8.BUILD-SNAPSHOT.jar!/:4.3.8.BUILD-SNAPSHOT]
	at org.springframework.core.io.ClassPathResource.exists(ClassPathResource.java:135) ~[spring-core-4.3.8.BUILD-SNAPSHOT.jar!/:4.3.8.BUILD-SNAPSHOT]
	at org.springframework.boot.autoconfigure.template.PathBasedTemplateAvailabilityProvider.isTemplateAvailable(PathBasedTemplateAvailabilityProvider.java:73) ~[spring-boot-autoconfigure-1.5.3.BUILD-SNAPSHOT.jar!/:1.5.3.BUILD-SNAPSHOT]
	at org.springframework.boot.autoconfigure.template.PathBasedTemplateAvailabilityProvider.isTemplateAvailable(PathBasedTemplateAvailabilityProvider.java:64) ~[spring-boot-autoconfigure-1.5.3.BUILD-SNAPSHOT.jar!/:1.5.3.BUILD-SNAPSHOT]
	at org.springframework.boot.autoconfigure.template.TemplateAvailabilityProviders.findProvider(TemplateAvailabilityProviders.java:159) ~[spring-boot-autoconfigure-1.5.3.BUILD-SNAPSHOT.jar!/:1.5.3.BUILD-SNAPSHOT]
	at org.springframework.boot.autoconfigure.template.TemplateAvailabilityProviders.getProvider(TemplateAvailabilityProviders.java:146) ~[spring-boot-autoconfigure-1.5.3.BUILD-SNAPSHOT.jar!/:1.5.3.BUILD-SNAPSHOT]
	at org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration$ErrorTemplateMissingCondition.getMatchOutcome(ErrorMvcAutoConfiguration.java:183) ~[spring-boot-autoconfigure-1.5.3.BUILD-SNAPSHOT.jar!/:1.5.3.BUILD-SNAPSHOT]
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47) ~[spring-boot-autoconfigure-1.5.3.BUILD-SNAPSHOT.jar!/:1.5.3.BUILD-SNAPSHOT]
	... 29 common frames omitted
```

When running inside eclipse the Resource returned is of type **ServletContextResource** and ```exists()``` properly returns false.  But the command line stack seems to indicate **ClassPathResource** was returned

My application also properly retrieves templates stored in the s3 bucket (when I run in eclipse) via a call to freemarker.template.Configuration.getTemplate("file.ftl").  So I'm certain the ResourceResolver itself is configured in the end:
> 2017-04-18 20:33:23.941  INFO 77795 --- [           main] o.s.ui.freemarker.SpringTemplateLoader   : SpringTemplateLoader for FreeMarker: using resource loader [org.springframework.cloud.aws.core.io.s3.PathMatchingSimpleStorageResourcePatternResolver\\@626c19cf] and template loader path [s3://my-bucket/templates/]
> 2017-04-18 20:33:23.941  INFO 77795 --- [           main] o.s.w.s.v.f.FreeMarkerConfigurer         : ClassTemplateLoader for Spring macros added to FreeMarker configuration

**Comment by wilkinsona** [comment]
I would guess that you haven't configured the S3-capable `ResourceLoader` early enough for it to be used to verify that a template location is available. I can certainly replicate the error you're seeing if I set the `ResourceLoader` after the context has been refreshed. Using an `ApplicationContextInitializer` to set the `ResourceLoader` fixes the problem. For example:

```java
new SpringApplicationBuilder(SampleWebFreeMarkerApplication.class)
        .initializers((context) -> {
            ((GenericApplicationContext) context).setResourceLoader(
                    new SimpleStorageResourceLoader(new AmazonS3Client()));
        }).run(args);
```
