### ISSUE TITLE
Not able to load values from application  properties with map,

### ISSUE THREAD

**Issue by prabhujk** [spring-projects/spring-boot#8970]
Not able to load values from application properties with map,

for below code, using XML I can set either string or map - but with Spring Boot application properties, it sets only String, but not map, below B is not set

```
#simple String
client.categories=Admin

# or its some time its map
client.categories.user=admin
client.categories.location=apt
```

```java
@ConfigurationProperties(prefix = ClientProperties.PREFIX)
public class ClientProperties {

    public static final String PREFIX = "client";

    private Map<String, String> categories = new HashMap<String, String>();

    public void setCategories(String categories) {
        this.categories.put(PREFIX, categories);
    }
    public void setCategories(Map<String, String> categories) {
        this.categories = categories;
    }
```

**Comment by philwebb** [comment]
I'm sorry but I'm not understanding the issue description. Could you please provide a sample that shows what you mean?

**Comment by prabhujk** [comment]
I wanted to set values to categories ,  some times its simple String, but some time it will be map
i can achieve this in xml like below ,   but  how do i active in application properties,  the above values String works, but not map - we referred spring.mvc.media-types to set map - still it does not work, since i have 2 difference setters for same attribute,  i dont have any getter method for this

<bean id="propertyConfigurer" class="ClientProperties">
		<property name="categories" value="Admin" />		
		OR 
		<property name="categories">
			<map>
				<entry key="user" value="admin" />
	                        <entry key="location" value="Apt" />
			</map>`
		</property>
	</bean>``

**Comment by prabhujk** [comment]
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'propertySourceBootstrapclient.ration': Unsatisfied dependency expressed through field 'propertySourceLocators'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'client.ervicePropertySourceLocator' defined in com .client.lient.autoclient.re.client.lientAutoclient.ration: Unsatisfied dependency expressed through method 'client.ervicePropertySourceLocator' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name .client.com .client.lient.autoclient.re.client.lientProperties': Could not bind properties to client.lientProperties (prefix.client. ignoreInvalidFields=false, ignoreUnknownFields=true, ignoreNestedProperties=false); nested exception is org.springframework.validation.BindException: org.springframework.boot.bind.RelaxedDataBinder$RelaxedBeanPropertyBindingResult: 1 errors
Field error in object .client. on field 'categories': rejected value [Admin]; codes [typeMismatch.client.categories,typeMismatch.categories,typeMismatch.java.util.Map,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes .client.categories,categories]; arguments []; default message [categories]]; default message [Failed to convert property value of type 'java.lang.String' to required type 'java.util.Map' for property 'categories'; nested exception is java.lang.IllegalStateException: Cannot convert value of type 'java.lang.String' to required type 'java.util.Map' for property 'categories': no matching editors or conversion strategy found]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:588) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866) ~[spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) ~[spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) [spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) [spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134) ~[spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:175) ~[spring-cloud-context-1.2.0.RC1.jar:1.2.0.RC1]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:98) ~[spring-cloud-context-1.2.0.RC1.jar:1.2.0.RC1]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:64) ~[spring-cloud-context-1.2.0.RC1.jar:1.2.0.RC1]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167) ~[spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122) ~[spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:73) ~[spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54) ~[spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:336) [spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) [spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162) [spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151) [spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
	at com..example.DemoApplication.main(DemoApplication.java:15) [classes/:na]

**Comment by philwebb** [comment]
Oh I see. You can't bind a single property to two different setters. It's not supported because the binder won't be able to work out easily which setter to call.

You'll either need to introduce two setters:

```java
    // bind with client.category=admin
    public void setCategory(String categories) {
        this.categories.put(PREFIX, categories);
    }

    // bind with client.categories.location=apt
    public void setCategories(Map<String, String> categories) {
        this.categories = categories;
    }
```

Or just update your properties file to consistently use the map form:

```
client.categories.client=admin
# or
client.categories.location=apt
```

**Comment by prabhujk** [comment]
i am not clear on your comment "You'll either need to introduce two setters:"

i do have this as show in the 1st section,  it does work in xml - issue is only in sprint boot application.prop  and bootstrap.prop

**Comment by philwebb** [comment]
You need two setters with _different_ names. 

XML `<property>` tags and Spring Boot `@ConfigurationProperties` serve a different purpose. The XML has a nested `<map>` element so it knows it's binding to a map. The `application.properties` file has no place to add this additional context, so has to use the type information from the class itself. Having two setter with different types will not work.
