### ISSUE TITLE
spring-boot-gradle-plugin - Cannot configure the 'publishing' extension after it has been accessed

### ISSUE THREAD

**Issue by edeandrea** [spring-projects/spring-boot#8980]
Hi - I've been using the spring-boot-gradle-plugin for some time now, most recently with version `1.5.2.RELEASE`. After moving from `1.5.2.RELEASE` to `1.5.3.RELEASE` my builds now fail with this error:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'entitlements-rs'.
> Cannot configure the 'publishing' extension after it has been accessed.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring root project 'entitlements-rs'.
        at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:94)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:89)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:76)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.access$000(LifecycleProjectEvaluator.java:33)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:53)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:50)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:50)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:648)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:126)
        at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:60)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:38)
        at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuildAction.execute(DefaultGradleLauncher.java:207)
        at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuildAction.execute(DefaultGradleLauncher.java:204)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:146)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:112)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:95)
        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:66)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:31)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
Caused by: org.gradle.api.InvalidUserDataException: Cannot configure the 'publishing' extension after it has been accessed.
        at org.gradle.api.internal.plugins.ExtensionsStorage$DeferredConfigurableExtensionHolder.configureLater(ExtensionsStorage.java:202)
        at org.gradle.api.internal.plugins.ExtensionsStorage$DeferredConfigurableExtensionHolder.configure(ExtensionsStorage.java:196)
        at org.gradle.api.internal.plugins.ExtensionsStorage.configureExtension(ExtensionsStorage.java:74)
        at org.gradle.api.internal.plugins.DefaultConvention.configure(DefaultConvention.java:201)
        at org.gradle.api.internal.plugins.DefaultConvention.configure(DefaultConvention.java:196)
        at io.spring.gradle.dependencymanagement.DependencyManagementPlugin.configurePublishingExtension(DependencyManagementPlugin.java:90)
        at io.spring.gradle.dependencymanagement.DependencyManagementPlugin.access$100(DependencyManagementPlugin.java:37)
        at io.spring.gradle.dependencymanagement.DependencyManagementPlugin$3.execute(DependencyManagementPlugin.java:83)
        at io.spring.gradle.dependencymanagement.DependencyManagementPlugin$3.execute(DependencyManagementPlugin.java:79)
        at org.gradle.internal.Actions$FilteredAction.execute(Actions.java:205)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:136)
        at org.gradle.api.internal.DefaultDomainObjectCollection.withType(DefaultDomainObjectCollection.java:159)
        at io.spring.gradle.dependencymanagement.DependencyManagementPlugin.configurePomCustomization(DependencyManagementPlugin.java:79)
        at io.spring.gradle.dependencymanagement.DependencyManagementPlugin.access$000(DependencyManagementPlugin.java:37)
        at io.spring.gradle.dependencymanagement.DependencyManagementPlugin$1.execute(DependencyManagementPlugin.java:56)
        at io.spring.gradle.dependencymanagement.DependencyManagementPlugin$1.execute(DependencyManagementPlugin.java:52)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:89)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:78)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:221)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:145)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
        at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:315)
        at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:225)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:138)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:35)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy24.afterEvaluate(Unknown Source)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:82)
        ... 56 more


BUILD FAILED

Total time: 1.107 secs
```

We do have our own enterprise plugins which do configure the publishing extension. We've found until now as long as we apply the `org.springframework.boot` plugin before our plugins then we've been fine. Version `1.5.3.RELEASE` seems to have broken that.

This is what our plugin does. With version `1.5.3.RELEASE` it doesn't seem to matter if the `org.springframework.boot` plugin is applied before or after our own.

```
project.configure(project.publishing) {
	publications {
		mainJava(MavenPublication) {
			artifactId "${ -> project.projectInfoExtension.artifactId}"
			from project.components.java
			artifact project.tasks[SOURCESJAR_TASK_NAME]
			artifact project.tasks[JAVADOCJAR_TASK_NAME]
		}
	}
}

// And then configure the artifactoryPublish task to publish the main publication
project.configure(project.tasks['artifactoryPublish']) {
	publications 'mainJava'
}
```

**Comment by wilkinsona** [comment]
This problem is more related to the [dependency management plugin](https://github.com/spring-gradle-plugins/dependency-management-plugin) rather than Spring Boot's plugin itself.

Unfortunately, there's a [bug in Gradle](https://github.com/gradle/gradle/issues/1373) which means that it isn't safe to access a publication's pom until a project has been evaluated. The dependency management plugin accesses the pom in order to configure it with a customisation that adds dependency management to it. If it's done too early then any Gradle configuration to Maven scope mapping customisations are lost and the resulting pom may be wrong.

To work around this problem, the dependency management plugin [now configures the pom customisation in `afterEvaluate`](https://github.com/spring-gradle-plugins/dependency-management-plugin/commit/36b05114b96b3fc41647fbc4c30b248fd62aa9c0). This change is what's triggering the failure you are seeing. I would guess it's due to the configuration of the `artifactoryPublish` task which will be "freezing" the `mainJava` publication.

You should be able to apply a similar workaround by moving your interaction with the publication into `afterEvaluate` as well. Please let us know if that works.

**Comment by edeandrea** [comment]
@wilkinsona Thanks for the quick reply! I'll try it out and let you know what I find. I appreciate the help!

**Comment by edeandrea** [comment]
Looks like I'll be able to work around this issue. I did run into https://github.com/gradle/gradle/issues/1061 as well that I also need to work around. I'll let you know once I'm complete.

**Comment by edeandrea** [comment]
Looks like I'm all set. Just to document for those which may come across this issue - this is what I did in our enterprise plugins:

```
project.afterEvaluate { proj ->
	proj.configure(proj.publishing) {
		publications {
			mainJava(MavenPublication) {
				artifactId "${ -> proj.projectInfoExtension.artifactId}"
				// Change due to https://github.com/gradle/gradle/issues/1061
                               // from proj.components.java
				artifact proj.tasks['jar']
				artifact proj.tasks[SOURCESJAR_TASK_NAME]
				artifact proj.tasks[JAVADOCJAR_TASK_NAME]

                                pom.withXml {
                                                // See https://github.com/gradle/gradle/issues/1061 as to why we need to do this
						PluginHelper.fixMavenPomDependencySection(proj, asNode())
				}
			}
		}
	}

	// And then configure the artifactoryPublish task to publish the main publication
	proj.configure(proj.tasks['artifactoryPublish']) {
		publications 'mainJava'
	}
}
```

**Comment by wilkinsona** [comment]
That's good news. Thanks for following up, @edeandrea
