### ISSUE TITLE
Loading unknown truststore fails with "no such algorithm: JKS for provider SunJSSE"

### ISSUE THREAD

**Issue by pintiliea** [spring-projects/spring-boot#9006]

**Comment by pintiliea** [comment]
Hello everyone,

I'm getting this _no such algorithm: JKS for provider SunJSSE_ exception after I load a PKCS12 keystore.  You can see from the stacktrace that it tries to load the truststore:

```
at org.eclipse.jetty.util.ssl.SslContextFactory.loadTrustStore(SslContextFactory.java:1023) ~[jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
```
I don't have a truststore declared in the config, so I don't know what truststore spring tries to load. I debugged this and see this at the beginning, _before_ the exception happens:

```
trustStore is: D:\apps\jdk1.8.0_111\jre\lib\security\cacerts
trustStore type is : jks
trustStore provider is : 
init truststore
adding as trusted cert:
  Subject: CN=Equifax Secure Global eBusiness CA-1, O=Equifax Secure Inc., C=US
  ... (very long list)
```

I'm configuring Jetty for SSL (TLS) and I have this configuration:

```
server:
    port: 443
    ssl:
        enabled: true
        enabled-protocols: TLSv1.2
        protocol: TLS
        ciphers:
            ...
        client-auth: need                     
        # ~~~ key managers ~~~
        key-store: classpath:security/tls/server-keypair.p12 
        key-store-provider: SunJSSE       
        key-store-type: PKCS12               
        key-store-password: storepass1 
        key-alias: mykeypair
        # key-password: keypass1             # (not for PKCS12)
        # ~~~ trust managers ~~~
        # trust-store-provider: SUN          #  Set the truststore's type to SUN to fix the error!
```
To get rid of this error I need to provide this line to the config:

```
trust-store-provider: SUN          
```
Why?

--
Kind regards,
Alex


Attachment:

```
org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Jetty servlet container
	at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainer.start(JettyEmbeddedServletContainer.java:150) ~[spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:297) ~[spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:145) ~[spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545) ~[spring-context-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at my.server.Server.main(Server.java:13) [classes/:na] // funny it's 13 isn't it?
Caused by: java.security.KeyStoreException: JKS not found
	at java.security.KeyStore.getInstance(KeyStore.java:899) ~[na:na]
	at org.eclipse.jetty.util.security.CertificateUtils.getKeyStore(CertificateUtils.java:40) ~[jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.ssl.SslContextFactory.loadTrustStore(SslContextFactory.java:1023) ~[jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.ssl.SslContextFactory.load(SslContextFactory.java:254) ~[jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:219) ~[jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131) ~[jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113) ~[jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:72) ~[jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131) ~[jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113) ~[jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:270) ~[jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81) ~[jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236) ~[jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainer.start(JettyEmbeddedServletContainer.java:132) ~[spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	... 10 common frames omitted
Caused by: java.security.NoSuchAlgorithmException: no such algorithm: JKS for provider SunJSSE
	at sun.security.jca.GetInstance.getService(GetInstance.java:87) ~[na:na]
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:206) ~[na:na]
	at java.security.Security.getImpl(Security.java:698) ~[na:na]
	at java.security.KeyStore.getInstance(KeyStore.java:896) ~[na:na]
	... 26 common frames omitted
```

**Comment by wilkinsona** [comment]
This looks like standard behaviour for SSL in Jetty to me. If there's no trust store configured, Jetty will use the key store as the trust store. That's why you see `CertifacteUtils.getKeyStore` being called. That method's called with `JKS` as the `type` because the default trust store type is `JKS`. Only if the trust store type is `null` will Jetty use the configured key store type instead.

**Comment by pintiliea** [comment]
Ok, thanks for clarifying this.
