### ISSUE TITLE
spring cloud    command fails.

### ISSUE THREAD

**Issue by grincarl** [spring-projects/spring-boot#9024]
I just followed the instructions on brew installing spring boot. 
Everything appears to have installed properly.
spring version
Spring CLI v1.5.3.RELEASE
I am running spring cloud and receiving the following error.
spring -d cloud
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.NoSuchMethodError: org.springframework.boot.cli.compiler.grape.AetherGrapeEngineFactory.create(Lgroovy/lang/GroovyClassLoader;Ljava/util/List;Lorg/springframework/boot/cli/compiler/grape/DependencyResolutionContext;)Lorg/springframework/boot/cli/compiler/grape/AetherGrapeEngine;
	at org.springframework.cloud.launcher.cli.LauncherCommand.populateClassloader(LauncherCommand.java:90)
	at org.springframework.cloud.launcher.cli.LauncherCommand.run(LauncherCommand.java:56)
	at org.springframework.boot.cli.command.CommandRunner.run(CommandRunner.java:219)
	at org.springframework.boot.cli.command.CommandRunner.runAndHandleErrors(CommandRunner.java:171)
	at org.springframework.boot.cli.SpringCli.main(SpringCli.java:63)

**Comment by spencergibb** [comment]
This should be opened in the spring-cloud-cli repo and has already been fixed in https://github.com/spring-cloud/spring-cloud-cli/issues/60#issuecomment-297134795 Try v 1.3.2.RELEASE of spring cloud cli

**Comment by wilkinsona** [comment]
Thank you, @spencergibb. I'm surprised by your use of AetherGrapeEngineFactory. We've always considered that to be internal. What do you need to use it for?

**Comment by snicoll** [comment]
Duplicates https://github.com/spring-cloud/spring-cloud-cli/issues/60
