### ISSUE TITLE
Auto-configuration report not displayed if EmbeddedServletContainerFactory fails

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-boot#9054]
In the process of trying to replace Tomcat with Undertow in a new application, I copied and pasted the standard Maven exclusion and Undertow starter dependency to my POM. My application is failing to launch, however, with this error:

```
org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:137) ~[spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:536) ~[spring-context-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at com.artsquare.workshop.launcher.WorkshopLauncher.main(WorkshopLauncher.groovy:13) [classes/:na]
Caused by: org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.getEmbeddedServletContainerFactory(EmbeddedWebApplicationContext.java:189) ~[spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:162) ~[spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:134) ~[spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	... 8 common frames omitted
```

I figured this was probably some sort of classpath bug on my part, so I added `--debug` to turn on the auto-configuration report--but it does not display in this case.

Expected behavior: I see the report (and can use it to trace the conditions on the embedded servlet factories).

Actual behavior: The report is not printed when the application bails at the initial context refresh.

**Comment by philwebb** [comment]
Finding the `EmbeddedServletContainerFactory` bean happens really early in the lifecycle so it might not be possible for us to display the report. Did you solve the underlying issue?

**Comment by chrylis** [comment]
No, I didn't. This was as bare-bones a project as I could make (a single placeholder `@RestController`), using the copypasta Tomcat-exclude/Undertow-include, but I couldn't get it to work. Finally gave up and went back to Tomcat.

**Comment by philwebb** [comment]
@chrylis Can you share the project?

**Comment by wilkinsona** [comment]
I would guess that it was a corrupted Undertow jar. @chrylis you could try clearing out your Maven or Gradle cache and seeing if that helps.

**Comment by wilkinsona** [comment]
These dependencies are sufficient to reproduce the problem:

```xml
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<exclusions>
				<exclusion>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-starter-tomcat</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-undertow</artifactId>
			<exclusions>
				<exclusion>
					<artifactId>undertow-core</artifactId>
					<groupId>io.undertow</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
```

I'd guess that in @chrylis's case, the `undertow-core` jar was corrupted.

**Comment by wilkinsona** [comment]
The problem is that we try to use the context to publish the `ApplicationFailedEvent` and the context doesn't have a multicaster. As a result, the event is stored in `earlyApplicationEvents` and then never gets published.

**Comment by chrylis** [comment]
I finally figured out what I think happened. The Eclipse file watcher noticed the POM had been updated while I was running something from the CLI, and so I got competing file downloads. The actual one that got saved was fine, but maybe Eclipse had a file handle open to a copy that got munged. Weird root cause, but it would be great if a backstop could still be added for the reporting.

**Comment by zhujiejun** [comment]
@chrylis  Can you share you project?
