### ISSUE TITLE
When filter init throw exception, embedded tomcat started success, but all request return 404

### ISSUE THREAD

**Issue by hengyunabc** [spring-projects/spring-boot#9094]
version: 1.4.x

Add a Filter:

```java
	@Bean
	FilterRegistrationBean testFilter() {
		FilterRegistrationBean filterRegistrationBean = new FilterRegistrationBean();
		filterRegistrationBean.setFilter(new Filter() {
			@Override
			public void init(FilterConfig filterConfig) throws ServletException {
				throw new ServletException();
			}

			@Override
			public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain)
					throws IOException, ServletException {
			}

			@Override
			public void destroy() {
			}

		});
		filterRegistrationBean.setUrlPatterns(Arrays.asList("/test"));
		return filterRegistrationBean;
	}
```

Tomcat print error log:

```

javax.servlet.ServletException: null
	at com.test.Application$1.init(Application.java:38) ~[classes/:na]
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:279) ~[tomcat-embed-core-8.5.6.jar:8.5.6]
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:109) ~[tomcat-embed-core-8.5.6.jar:8.5.6]
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4572) [tomcat-embed-core-8.5.6.jar:8.5.6]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5215) [tomcat-embed-core-8.5.6.jar:8.5.6]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.5.6.jar:8.5.6]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1403) [tomcat-embed-core-8.5.6.jar:8.5.6]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1393) [tomcat-embed-core-8.5.6.jar:8.5.6]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_112]

2017-05-04 20:27:24.987 ERROR 27434 --- [ost-startStop-1] o.apache.catalina.core.StandardContext   : One or more Filters failed to start. Full details will be found in the appropriate container log file
2017-05-04 20:27:24.987 ERROR 27434 --- [ost-startStop-1] o.apache.catalina.core.StandardContext   : Context [] startup failed due to previous errors
```

But spring boot started success:

```
2017-05-04 20:29:24.521  INFO 27483 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 7001 (http)
2017-05-04 20:29:24.531  INFO 27483 --- [           main] com.test.Application         : Started Application in 11.163 seconds (JVM running for 23.375)
```

---

All http request will return 404.

**Comment by philwebb** [comment]
Closing in favor of PR #9095
