### ISSUE TITLE
BackgroundPreinitializer should print the Exception info

### ISSUE THREAD

**Issue by hengyunabc** [spring-projects/spring-boot#9138]
[demo.zip](https://github.com/spring-projects/spring-boot/files/985759/demo.zip)

* Run DemoApplication, the error message is confusing :

```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.hibernate.validator.internal.engine.ConfigurationImpl
	at org.hibernate.validator.HibernateValidator.createGenericConfiguration(HibernateValidator.java:33) ~[hibernate-validator-5.3.5.Final.jar:5.3.5.Final]
	at javax.validation.Validation$GenericBootstrapImpl.configure(Validation.java:276) ~[validation-api-1.1.0.Final.jar:na]
	at org.springframework.boot.validation.MessageInterpolatorFactory.getObject(MessageInterpolatorFactory.java:53) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.autoconfigure.validation.DefaultValidatorConfiguration.defaultValidator(DefaultValidatorConfiguration.java:43) ~[spring-boot-autoconfigure-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_112]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_112]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_112]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_112]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	... 32 common frames omitted
```

* Add a breakpoint at `run()` method in  `org.springframework.boot.autoconfigure.BackgroundPreinitializer` , breakpoint type is `Suspend thread`, not `Suspend VM`.

```java
@Order(LoggingApplicationListener.DEFAULT_ORDER + 1)
public class BackgroundPreinitializer
		implements ApplicationListener<ApplicationEnvironmentPreparedEvent> {

	@Override
	public void onApplicationEvent(ApplicationEnvironmentPreparedEvent event) {
		try {
			Thread thread = new Thread(new Runnable() {

				@Override
				public void run() {
					runSafely(new MessageConverterInitializer());
					runSafely(new MBeanFactoryInitializer());
					runSafely(new ValidationInitializer());
					runSafely(new JacksonInitializer());
					runSafely(new ConversionServiceInitializer());
				}
```

* Then debug DemoApplication, the  error message is:

```
Caused by: java.lang.NoSuchMethodError: org.jboss.logging.Logger.getMessageLogger(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/Object;
	at org.hibernate.validator.internal.util.logging.LoggerFactory.make(LoggerFactory.java:19) ~[hibernate-validator-5.3.5.Final.jar:5.3.5.Final]
	at org.hibernate.validator.internal.util.Version.<clinit>(Version.java:22) ~[hibernate-validator-5.3.5.Final.jar:5.3.5.Final]
	at org.hibernate.validator.internal.engine.ConfigurationImpl.<clinit>(ConfigurationImpl.java:71) ~[hibernate-validator-5.3.5.Final.jar:5.3.5.Final]
	at org.hibernate.validator.HibernateValidator.createGenericConfiguration(HibernateValidator.java:33) ~[hibernate-validator-5.3.5.Final.jar:5.3.5.Final]
	at javax.validation.Validation$GenericBootstrapImpl.configure(Validation.java:276) ~[validation-api-1.1.0.Final.jar:na]
	at org.springframework.boot.validation.MessageInterpolatorFactory.getObject(MessageInterpolatorFactory.java:53) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.autoconfigure.validation.DefaultValidatorConfiguration.defaultValidator(DefaultValidatorConfiguration.java:43) ~[spring-boot-autoconfigure-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_112]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_112]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_112]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_112]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	... 32 common frames omitted
```

* The user can find out `org.jboss.logging.Logger` is missing  the method `getMessageLogger(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/Object`, then find the maven dependencies problem.

`org.jboss.logging.Logger` is loaded from `jboss-common`, the right jar should be `jboss-logging`.

```xml
		<dependency>
			<groupId>jboss.common</groupId>
			<artifactId>jboss-common</artifactId>
			<version>1.2.1.GA</version>
		</dependency>
```

---

0. `BackgroundPreinitializer` try to load `hibernate.validator`, it fail, but do not print any message.
0. The ClassLoader mark hibernate class is invalidated.
0. `MessageInterpolatorFactory` try to load hibernate class, the ClassLoader throw exception: `java.lang.NoClassDefFoundError: Could not initialize class org.hibernate.validator.internal.engine.ConfigurationImpl`
0. It is difficult for users to find real reasons

**Comment by philwebb** [comment]
The `BackgroundPreinitializer` is designed to trigger things that are expensive to load. It runs early, and in a background thread. It's intentionally designed to fail silently if something goes wrong, with the assumption that exception will be thrown again if it ends up actually being needed. Actually, there are a great many occasions when we expect `BackgroundPreinitializer` to fail.

I've tried running your sample application, but it appears to start fine for me. I don't see any exceptions. Have you got a sample the replicates the initial stack trace that you posted?

```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.hibernate.validator.internal.engine.ConfigurationImpl
	at org.hibernate.validator.HibernateValidator.createGenericConfiguration(HibernateValidator.java:33) ~[hibernate-validator-5.3.5.Final.jar:5.3.5.Final]
	at javax.validation.Validation$GenericBootstrapImpl.configure(Validation.java:276) ~[validation-api-1.1.0.Final.jar:na]
	at org.springframework.boot.validation.MessageInterpolatorFactory.getObject(MessageInterpolatorFactory.java:53) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.autoconfigure.validation.DefaultValidatorConfiguration.defaultValidator(DefaultValidatorConfiguration.java:43) ~[spring-boot-autoconfigure-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_112]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_112]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_112]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_112]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	... 32 common frames omitted
```

**Comment by hengyunabc** [comment]
@philwebb Sorry that `jboss-common:1.2.1.GA` do not exist in maven central repository.

Please try the new demo. 
[demo.zip](https://github.com/spring-projects/spring-boot/files/998453/demo.zip)

---

I know that `BackgroundPreinitializer`  is designed to trigger things that are expensive to load. 

Print exception when logger level is debug will be better?

**Comment by philwebb** [comment]
I don't think there's much we can do about this one since we actively expect background initializes to fail. For example `ValidationInitializer` will also fail if no validator classes are available. That's a perfectly legitimate thing to happen with lots of applications.

It's a little unfortunate that the second call throws a different exception. It does make tracking down the cause a little harder. Unfortunately, I think adding `printStackTrace()` to `BackgroundPreinitializer` will just cause noise for most users.

**Comment by kgilmer** [comment]
FWIW I spent hours debugging this exact problem. @hengyunabc saved me but it would be really nice if startup error messages could describe their root causes.
