### ISSUE TITLE
See if we can drop the use of SocketUtils.findAvailableTcpPort() from EndpointWebMvcAutoConfigurationTests

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#9230]
It's causing intermittent build failures like this:

```
org.springframework.boot.web.server.PortInUseException: Port 40224 is already in use
	at org.springframework.boot.web.embedded.undertow.UndertowServletWebServer.start(UndertowServletWebServer.java:168)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.startWebServer(ServletWebServerApplicationContext.java:293)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:144)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:122)
	at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration.createChildManagementContext(EndpointWebMvcAutoConfiguration.java:178)
	at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration.afterSingletonsInstantiated(EndpointWebMvcAutoConfiguration.java:144)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:771)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:122)
	at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfigurationTests.managementServerCanDisableSslWhenUsingADifferentPort(EndpointWebMvcAutoConfigurationTests.java:571)
```

It'd be nice if we could use 0 instead and let the OS allocate a port which is actually guaranteed to be available.

**Comment by wilkinsona** [comment]
Duplicate of #9382
