### ISSUE TITLE
Groovy Templates do not use the templates prefix in MockMVC tests

### ISSUE THREAD

**Issue by berlin-ab** [spring-projects/spring-boot#926]
`gradle test` should reproduce this issue.

https://github.com/berlin-ab/spring-boot-pivot/tree/bug/template-prefix-missing-in-integration-test

We have a template `examples/index.tpl`:

```
package templates.examples

layout 'layouts/application.tpl', content: contents {
    h2("inside the template")
}
```

And a layout `layouts/application.tpl`:

```
package templates.layouts

html {
    body {
        h1("Example Layout")
        content()
    }
}
```
#### error message:

```
java.io.IOException: Unable to load template:layouts/application.tpl
    at org.springframework.boot.autoconfigure.groovy.template.GroovyTemplateResolver.resolveTemplate(GroovyTemplateResolver.java:56)
    at groovy.text.markup.MarkupTemplateEngine.resolveTemplate(MarkupTemplateEngine.java:176)
    at groovy.text.markup.BaseTemplate.layout(BaseTemplate.java:377)
    at templates.examples.index.run(index.tpl:3)
    at groovy.text.markup.BaseTemplate.writeTo(BaseTemplate.java:420)
    at org.springframework.boot.autoconfigure.groovy.template.web.GroovyTemplateView.renderMergedOutputModel(GroovyTemplateView.java:49)
    at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:267)
    at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1221)
    at org.springframework.test.web.servlet.TestDispatcherServlet.render(TestDispatcherServlet.java:102)
    at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1005)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:952)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:870)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:961)
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:852)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
```

**Comment by roercik85** [comment]
The problem is location of application.tpl file. If You move it to GROVY_HOME, it will work correctly.
