### ISSUE TITLE
 mongodb-reactive Cannot kill pinned cursor when client abandoned. 

### ISSUE THREAD

**Issue by xmlking** [spring-projects/spring-boot#9350]
I am using `spring-boot-starter-data-mongodb-reactive` in my Spring Boot project,
Exploring MongoDB's tailable cursor with  WebFlux and Server Sent Events(SSE).
I noticed if the client (EventSource in the Browser) terminate/cancel/abandon the request, the Spring Boot emitting following error in the console. 

**What is expected:**
when client  cancel request, Server App/MongoDB should gracefully kill  running cursor in MongoDB. 

**How to reproduce:**
Demo app : https://github.com/xmlking/reactive-apps
if you close the browser, following will be printed to the server console log.

```
2017-05-29 23:11:48.245  INFO 2285 --- [       Thread-7] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2017-05-29T23:11:48.243-0700 I COMMAND  [conn3] killcursors test.guestBookEntry keyUpdates:0 writeConflicts:0 exception: Cannot kill pinned cursor: 19301877704 code:16089 numYields:0 locks:{ Global: { acquireCount: { r: 2 } }, Database: { acquireCount: { r: 1 } }, Collection: { acquireCount: { r: 1 } } } 4ms
2017-05-29 23:11:48.987  WARN 2285 --- [      Thread-12] org.mongodb.driver.connection            : Callback onResult call produced an error

java.lang.NullPointerException: null
        at com.mongodb.operation.AsyncQueryBatchCursor$CommandResultSingleResultCallback.onResult(AsyncQueryBatchCursor.java:255) ~[mongodb-driver-core-3.4.2.jar:na]
        at com.mongodb.operation.AsyncQueryBatchCursor$CommandResultSingleResultCallback.onResult(AsyncQueryBatchCursor.java:235) ~[mongodb-driver-core-3.4.2.jar:na]
        at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49) [mongodb-driver-core-3.4.2.jar:na]
        at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor$1.onResult(DefaultServer.java:185) [mongodb-driver-core-3.4.2.jar:na]
        at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49) [mongodb-driver-core-3.4.2.jar:na]
        at com.mongodb.connection.CommandProtocol$CommandResultCallback.callCallback(CommandProtocol.java:271) [mongodb-driver-core-3.4.2.jar:na]
        at com.mongodb.connection.ResponseCallback.onResult(ResponseCallback.java:48) [mongodb-driver-core-3.4.2.jar:na]
        at com.mongodb.connection.ResponseCallback.onResult(ResponseCallback.java:23) [mongodb-driver-core-3.4.2.jar:na]
        at com.mongodb.connection.DefaultConnectionPool$PooledConnection$2.onResult(DefaultConnectionPool.java:470) [mongodb-driver-core-3.4.2.jar:na]
        at com.mongodb.connection.DefaultConnectionPool$PooledConnection$2.onResult(DefaultConnectionPool.java:464) [mongodb-driver-core-3.4.2.jar:na]
        at com.mongodb.connection.UsageTrackingInternalConnection$3.onResult(UsageTrackingInternalConnection.java:119) [mongodb-driver-core-3.4.2.jar:na]
        at com.mongodb.connection.UsageTrackingInternalConnection$3.onResult(UsageTrackingInternalConnection.java:115) [mongodb-driver-core-3.4.2.jar:na]
        at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49) [mongodb-driver-core-3.4.2.jar:na]
        at com.mongodb.connection.InternalStreamConnection.executeCallbackAndReceiveResponse(InternalStreamConnection.java:378) [mongodb-driver-core-3.4.2.jar:na]
        at com.mongodb.connection.InternalStreamConnection.access$1700(InternalStreamConnection.java:66) [mongodb-driver-core-3.4.2.jar:na]
        at com.mongodb.connection.InternalStreamConnection$ResponseBuffersCallback.onResult(InternalStreamConnection.java:420) [mongodb-driver-core-3.4.2.jar:na]
        at com.mongodb.connection.InternalStreamConnection$ResponseBuffersCallback.onResult(InternalStreamConnection.java:389) [mongodb-driver-core-3.4.2.jar:na]
        at com.mongodb.connection.InternalStreamConnection$ResponseHeaderCallback.onSuccess(InternalStreamConnection.java:562) [mongodb-driver-core-3.4.2.jar:na]
        at com.mongodb.connection.InternalStreamConnection$ResponseHeaderCallback.access$2200(InternalStreamConnection.java:517) [mongodb-driver-core-3.4.2.jar:na]
        at com.mongodb.connection.InternalStreamConnection$ResponseHeaderCallback$ResponseBodyCallback.onResult(InternalStreamConnection.java:584) [mongodb-driver-core-3.4.2.jar:na]
        at com.mongodb.connection.InternalStreamConnection$ResponseHeaderCallback$ResponseBodyCallback.onResult(InternalStreamConnection.java:568) [mongodb-driver-core-3.4.2.jar:na]
        at com.mongodb.connection.InternalStreamConnection$3.completed(InternalStreamConnection.java:447) [mongodb-driver-core-3.4.2.jar:na]
        at com.mongodb.connection.InternalStreamConnection$3.completed(InternalStreamConnection.java:444) [mongodb-driver-core-3.4.2.jar:na]
        at com.mongodb.connection.AsynchronousSocketChannelStream$BasicCompletionHandler.completed(AsynchronousSocketChannelStream.java:218) [mongodb-driver-core-3.4.2.jar:na]
        at com.mongodb.connection.AsynchronousSocketChannelStream$BasicCompletionHandler.completed(AsynchronousSocketChannelStream.java:201) [mongodb-driver-core-3.4.2.jar:na]
        at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126) [na:1.8.0_101]
        at sun.nio.ch.Invoker.invokeDirect(Invoker.java:157) [na:1.8.0_101]
        at sun.nio.ch.UnixAsynchronousSocketChannelImpl.implRead(UnixAsynchronousSocketChannelImpl.java:553) [na:1.8.0_101]
        at sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:276) [na:1.8.0_101]
        at sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:297) [na:1.8.0_101]
        at com.mongodb.connection.AsynchronousSocketChannelStream.readAsync(AsynchronousSocketChannelStream.java:125) [mongodb-driver-core-3.4.2.jar:na]
        at com.mongodb.connection.InternalStreamConnection.readAsync(InternalStreamConnection.java:444) [mongodb-driver-core-3.4.2.jar:na]
        at com.mongodb.connection.InternalStreamConnection.access$2000(InternalStreamConnection.java:66) [mongodb-driver-core-3.4.2.jar:na]
        at com.mongodb.connection.InternalStreamConnection$ResponseHeaderCallback.onResult(InternalStreamConnection.java:541) [mongodb-driver-core-3.4.2.jar:na]
        at com.mongodb.connection.InternalStreamConnection$ResponseHeaderCallback.onResult(InternalStreamConnection.java:517) [mongodb-driver-core-3.4.2.jar:na]
        at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49) [mongodb-driver-core-3.4.2.jar:na]
        at com.mongodb.connection.InternalStreamConnection$3.completed(InternalStreamConnection.java:447) [mongodb-driver-core-3.4.2.jar:na]
        at com.mongodb.connection.InternalStreamConnection$3.completed(InternalStreamConnection.java:444) [mongodb-driver-core-3.4.2.jar:na]
        at com.mongodb.connection.AsynchronousSocketChannelStream$BasicCompletionHandler.completed(AsynchronousSocketChannelStream.java:218) [mongodb-driver-core-3.4.2.jar:na]
        at com.mongodb.connection.AsynchronousSocketChannelStream$BasicCompletionHandler.completed(AsynchronousSocketChannelStream.java:201) [mongodb-driver-core-3.4.2.jar:na]
        at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126) [na:1.8.0_101]
        at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishRead(UnixAsynchronousSocketChannelImpl.java:430) [na:1.8.0_101]
        at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:191) [na:1.8.0_101]
        at sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:213) [na:1.8.0_101]
        at sun.nio.ch.KQueuePort$EventHandlerTask.run(KQueuePort.java:301) [na:1.8.0_101]
        at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112) [na:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]


```

**Comment by wilkinsona** [comment]
This is due to a bug in Mongo's Java Driver that should be fixed by [this commit](https://github.com/mongodb/mongo-java-driver/commit/2db486ffacc71345b3f449d61c928d4b04a7a6ed). It's only in their `master` branch as far as I can tell, so it'll be available in 3.5. We'll upgrade to that in due course.
