### ISSUE TITLE
Exception when using FIPS compliant security provider for SSL in Undertow server

### ISSUE THREAD

**Issue by maniek45** [spring-projects/spring-boot#9351]
I'm trying to upgrade in my application spring-boot library version from 1.5.2 to 1.5.3 but I've failed with the exception when application is starting. I'm using Bouncy Castle FIPS JCA security provider (https://www.bouncycastle.org/fips-java) as a first security provider on the list of providers. 

Looking at the spring-boot code I've noticed that in the method UndertowEmbeddedServletContainerFactory#getKeyManagers() the array of KeyManager's is wrapped in ConfigurableAliasKeyManager class instance by using getConfigurableAliasKeyManagers() method. Because of this wrapping it is impossible to configure SSL when using provider in FIPS mode.

Stack trace:

```
org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is java.lang.IllegalStateException: java.security.KeyManagementException: FIPS mode: only SunJSSE KeyManagers may be used
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:137) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:536) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at com.mot.ssc.SscApplication.main(SscApplication.java:43) [main/:?]
Caused by: java.lang.IllegalStateException: java.security.KeyManagementException: FIPS mode: only SunJSSE KeyManagers may be used
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.configureSsl(UndertowEmbeddedServletContainerFactory.java:287) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.createBuilder(UndertowEmbeddedServletContainerFactory.java:256) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.getEmbeddedServletContainer(UndertowEmbeddedServletContainerFactory.java:237) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:164) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:134) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	... 8 more
Caused by: java.security.KeyManagementException: FIPS mode: only SunJSSE KeyManagers may be used
	at sun.security.ssl.SSLContextImpl.chooseKeyManager(SSLContextImpl.java:148) ~[?:1.8.0_112-internal]
	at sun.security.ssl.SSLContextImpl.engineInit(SSLContextImpl.java:65) ~[?:1.8.0_112-internal]
	at javax.net.ssl.SSLContext.init(SSLContext.java:282) ~[?:1.8.0_112-internal]
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.configureSsl(UndertowEmbeddedServletContainerFactory.java:270) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.createBuilder(UndertowEmbeddedServletContainerFactory.java:256) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.getEmbeddedServletContainer(UndertowEmbeddedServletContainerFactory.java:237) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:164) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:134) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	... 8 more
```

**Comment by wilkinsona** [comment]
Can you please provide a small sample that reproduces the problem?

**Comment by maniek45** [comment]
The sample code is below. Unfortunately I cannot send you my keystore and truststore files, but they can contain any key and certificate in order to start the application.

Environment variables:
-------------------------------
export SERVER_PORT=8443
export SERVER_SSL_KEY_STORE=<keystore_file_in_p12_format>
export SERVER_SSL_KEY_ALIAS=<keystore_key_entry_name>
export SERVER_SSL_KEY_STORE_PASSWORD=<keystore_password>
export SERVER_SSL_KEY_STORE_TYPE=PKCS12
export SERVER_SSL_TRUST_STORE_PASSWORD=<truststore_password>
export SERVER_SSL_TRUST_STORE=<truststore_file_in_p12_format>
export SERVER_SSL_TRUST_STORE_TYPE=PKCS12

Sample code:
-------------------------------
`@SpringBootApplication
public class SscApplication {

	public static void main(String[] args) throws Exception {
		SpringApplication.run(SscApplication.class, args);
	}

	@Bean
	public EmbeddedServletContainerFactory servletContainer(ServerProperties serverProperties) {
		final int port = serverProperties.getPort();

		Ssl sslForUndertow = new Ssl();
		sslForUndertow.setKeyStore(serverProperties.getSsl().getKeyStore());
		sslForUndertow.setKeyStorePassword(serverProperties.getSsl().getKeyStorePassword());
		sslForUndertow.setKeyStoreType(serverProperties.getSsl().getKeyStoreType());
		sslForUndertow.setKeyAlias(serverProperties.getSsl().getKeyAlias());
		sslForUndertow.setTrustStore(serverProperties.getSsl().getTrustStore());
		sslForUndertow.setTrustStorePassword(serverProperties.getSsl().getTrustStorePassword());
		sslForUndertow.setTrustStoreType(serverProperties.getSsl().getTrustStoreType());

		UndertowEmbeddedServletContainerFactory factory = new UndertowEmbeddedServletContainerFactory();
		factory.setSsl(sslForUndertow);
		factory.setPort(port);
		factory.addDeploymentInfoCustomizers(deploymentInfo -> deploymentInfo
				.addSecurityConstraint(new SecurityConstraint()
						.addWebResourceCollection(new WebResourceCollection().addUrlPattern("/*"))
						.setTransportGuaranteeType(TransportGuaranteeType.CONFIDENTIAL)
						.setEmptyRoleSemantic(SecurityInfo.EmptyRoleSemantic.PERMIT))
				.setConfidentialPortManager(exchange -> port)
				.addInitialHandlerChainWrapper(handler -> {
					return new AllowedMethodsHandler(handler, new HttpString("GET"), new HttpString("POST"),
							new HttpString("PUT"), new HttpString("DELETE"));
				}));
		return factory;
	}
}`

In addition to the code you should modify <JRE_location>\lib\security\java.security file in the JRE used to run the sample application which shall contain only the following list of security providers:

`
security.provider.1=org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider
security.provider.2=com.sun.net.ssl.internal.ssl.Provider BCFIPS
security.provider.3=sun.security.provider.Sun`

**Comment by maniek45** [comment]
Btw. In order to run sample code you also need to download Bouncy Castle FIPS provider jar (https://www.bouncycastle.org/fips-java)

**Comment by wilkinsona** [comment]
Thanks. Unfortunately, I've been unable to reproduce the failure you're seeing. Instead, BouncyCastle fails slightly earlier when it's loaded the KeyStore:

```
Caused by: org.bouncycastle.jcajce.provider.ProvIOException: exception unwrapping private key - java.lang.NullPointerException
	at org.bouncycastle.jcajce.provider.ProvPKCS12$PKCS12KeyStoreSpi.unwrapKey(ProvPKCS12.java:879) ~[bc-fips-1.0.0.jar:na]
	at org.bouncycastle.jcajce.provider.ProvPKCS12$PKCS12KeyStoreSpi.engineLoad(ProvPKCS12.java:1108) ~[bc-fips-1.0.0.jar:na]
	at java.security.KeyStore.load(KeyStore.java:1445) ~[na:1.8.0_121]
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.loadKeyStore(UndertowEmbeddedServletContainerFactory.java:378) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.getKeyStore(UndertowEmbeddedServletContainerFactory.java:344) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.getKeyManagers(UndertowEmbeddedServletContainerFactory.java:310) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	... 13 common frames omitted
Caused by: java.lang.NullPointerException: null
	at org.bouncycastle.jcajce.provider.BaseCipher.engineGetParameters(BaseCipher.java:275) ~[bc-fips-1.0.0.jar:na]
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1020) ~[na:1.8.0_121]
	at javax.crypto.Cipher.init(Cipher.java:1245) ~[na:1.8.0_121]
	at javax.crypto.Cipher.init(Cipher.java:1186) ~[na:1.8.0_121]
	at org.bouncycastle.jcajce.provider.ProvPKCS12$PKCS12KeyStoreSpi.createPKCS12Cipher(ProvPKCS12.java:964) ~[bc-fips-1.0.0.jar:na]
	at org.bouncycastle.jcajce.provider.ProvPKCS12$PKCS12KeyStoreSpi.unwrapKey(ProvPKCS12.java:859) ~[bc-fips-1.0.0.jar:na]
	... 18 common frames omitted
```

The change that you're seeing is an unfortunate side-effect of the fix for https://github.com/spring-projects/spring-boot/issues/8245. In https://github.com/spring-projects/spring-boot/commit/4607f8bc2fb20da1681fede9094fe0af25ef0917 we have updated our Undertow integration to adopt the same approach as Tomcat and Jetty already take by decorating each `X509ExtendedKeyManager` with one that knows how to use the key alias.

@maniek45 Given that I can't reproduced the problem, I'd be interested to know if you see a similar failure with Tomcat and/or Jetty. That would allow us to validate my analysis above. If it does work with Tomcat or Jetty then we'll need to dig deeper to understand why. If it doesn't then we may be stuck and you'll have to drop back to configuring Undertow's SSL yourself rather than getting the factory to do it.

One improvement that we could make is to only perform the decoration for a non-null key alias. However, that won't help in the case described above as it has an alias configured.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by maniek45** [comment]
I've checked the Tomcat and Jetty versions and both reports the same issue about non-FIPS compliant KeyManagers (see the listings below). 
I think that your suggestion to perform decoration only in case of not-null key alias seems reasonable. We don't need to configure this key alias as we have only one entry with private key in our keystore.

Tomcat version:
```
2017-06-09 08:19:50.528 +0200 ERROR 1096 --- [  restartedMain] o.a.c.h.Http11NioProtocol                : Failed to start end point associated with ProtocolHandler ["https-jsse-nio-8443"]

java.lang.IllegalArgumentException: java.security.KeyManagementException: FIPS mode: only SunJSSE KeyManagers may be used
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:114) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.initialiseSsl(AbstractJsseEndpoint.java:85) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:225) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:978) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:628) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1022) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:225) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.addPreviouslyRemovedConnectors(TomcatEmbeddedServletContainer.java:250) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:193) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:297) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:145) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at com.mot.ssc.SscApplication.main(SscApplication.java:41) [main/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112-internal]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112-internal]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-1.5.4.RELEASE.jar:1.5.4.RELEASE]
Caused by: java.security.KeyManagementException: FIPS mode: only SunJSSE KeyManagers may be used
	at sun.security.ssl.SSLContextImpl.chooseKeyManager(SSLContextImpl.java:148) ~[?:1.8.0_112-internal]
	at sun.security.ssl.SSLContextImpl.engineInit(SSLContextImpl.java:65) ~[?:1.8.0_112-internal]
	at javax.net.ssl.SSLContext.init(SSLContext.java:282) ~[?:1.8.0_112-internal]
	at org.apache.tomcat.util.net.jsse.JSSESSLContext.init(JSSESSLContext.java:43) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:112) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	... 24 more
```

Jetty version:
```
2017-06-09 07:36:56.433 +0200 ERROR 10292 --- [  restartedMain] o.s.b.SpringApplication                  : Application startup failed

org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Jetty servlet container
	at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainer.start(JettyEmbeddedServletContainer.java:161) ~[spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:297) ~[spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:145) ~[spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) ~[spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at com.mot.ssc.SscApplication.main(SscApplication.java:48) [main/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112-internal]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112-internal]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-1.5.4.RELEASE.jar:1.5.4.RELEASE]
Caused by: java.security.KeyManagementException: FIPS mode: only SunJSSE KeyManagers may be used
	at sun.security.ssl.SSLContextImpl.chooseKeyManager(SSLContextImpl.java:148) ~[?:1.8.0_112-internal]
	at sun.security.ssl.SSLContextImpl.engineInit(SSLContextImpl.java:65) ~[?:1.8.0_112-internal]
	at javax.net.ssl.SSLContext.init(SSLContext.java:282) ~[?:1.8.0_112-internal]
	at org.eclipse.jetty.util.ssl.SslContextFactory.load(SslContextFactory.java:306) ~[jetty-util-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:220) ~[jetty-util-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131) ~[jetty-util-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113) ~[jetty-util-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:72) ~[jetty-server-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131) ~[jetty-util-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113) ~[jetty-util-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:270) ~[jetty-server-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81) ~[jetty-server-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236) ~[jetty-server-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainer.start(JettyEmbeddedServletContainer.java:143) ~[spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	... 15 more
```

**Comment by wilkinsona** [comment]
@maniek45 Thanks for trying Tomcat and Jetty. They do the decoration for us so we have no control over when it does and does not happen. We can use this issue to change our decoration with Undertow so that it only happens when an alias is configured.

**Comment by maniek45** [comment]
Thank you. Sounds good :-) Fix should solve an issue and let us upgrade spring-boot version.
