### ISSUE TITLE
Springboot + mongodb : An error when mongodb authentication is enabled.

### ISSUE THREAD

**Issue by tando7** [spring-projects/spring-boot#9353]
I wrote a sample code by referring the following site, and it works fine.
https://spring.io/guides/gs/accessing-data-mongodb/

But since there is no authentication required to connect to mongodb, I added "authorization: enabled" to mongodb.config file.
And I also added the following info in the applicaton.yml file in the project.

As the result, I am having the following error regardless of the auth-info is correct or not.
It appears to be throwing the following exception:
`org.springframework.data.mongodb.UncategorizedMongoDbException`

Could you give me an advice how to resolve this?
Thank you in advance.

```yaml
spring:
  data:    
    mongodb:
      host: localhost
      port: 27017
      uri: mongodb://localhost:27017/test 
      database: test
      username: name
      password: 
      repositories:
        enabled: true  
```
      

```
`
  .   ____       `   _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.2.RELEASE)

2017-05-30 17:51:54.693  INFO 9460 --- [           main] com.example.demo.DemoMongo2Application   : Starting DemoMongo2Application on HP1988WIN10 with PID 9460 (C:\Users\user\Documents\dev\Java\workspace\demoMongo2\bin started by user in C:\Users\user\Documents\dev\Java\workspace\demoMongo2)
2017-05-30 17:51:54.696  INFO 9460 --- [           main] com.example.demo.DemoMongo2Application   : No active profile set, falling back to default profiles: default
2017-05-30 17:51:54.752  INFO 9460 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@74e52303: startup date [Tue May 30 17:51:54 JST 2017]; root of context hierarchy
2017-05-30 17:51:55.835  INFO 9460 --- [           main] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[localhost:27017], mode=MULTIPLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2017-05-30 17:51:55.836  INFO 9460 --- [           main] org.mongodb.driver.cluster               : Adding discovered server localhost:27017 to client view of cluster
2017-05-30 17:51:56.099  INFO 9460 --- [localhost:27017] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:1, serverValue:1}] to localhost:27017
2017-05-30 17:51:56.102  INFO 9460 --- [localhost:27017] org.mongodb.driver.cluster               : Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 4, 4]}, minWireVersion=0, maxWireVersion=5, maxDocumentSize=16777216, roundTripTimeNanos=1041206}
2017-05-30 17:51:56.103  INFO 9460 --- [localhost:27017] org.mongodb.driver.cluster               : Discovered cluster type of STANDALONE
2017-05-30 17:51:56.477  INFO 9460 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2017-05-30 17:51:56.578  INFO 9460 --- [           main] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:2, serverValue:2}] to localhost:27017
2017-05-30 17:51:56.607  INFO 9460 --- [           main] utoConfigurationReportLoggingInitializer : 

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2017-05-30 17:51:56.618 ERROR 9460 --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:779) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:760) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:747) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
```

**Comment by wilkinsona** [comment]
@tando7 Can you please edit your problem description to improve the formatting? The syntax is described [here](https://guides.github.com/features/mastering-markdown/).

**Comment by wilkinsona** [comment]
@tando7 I can't see any sign of the error in the log output that you've shared. Can you provide some details of the actual error that you're seeing?
