### ISSUE TITLE
Datasource initialization fail when run with JDK 9

### ISSUE THREAD

**Issue by schauder** [spring-projects/spring-boot#9354]
I'm trying to get the Spring Data examples to run with JDK9 (see https://jira.spring.io/browse/DATACMNS-1033)

The JPA examples fail, complaining about the `DataSource` being `null`.

I reduced the examples to make them as simple as possible and found that `DataSourceIntializer.init()` which sets the `DataSource` in the initializer is never called, although there actually is a `DataSource` created, triggering the creation of the `DataSourceInitializer` in `DataSourceInitializerPostProcessor.postProcessAfterInitialization(Object bean, String beanName)`

We use HsqlDb and there are other tests with the same database that actually do work haven't figured out the difference yet.

An example that executes (runs all tests) fine with Java 8 and fails with Java 9 is here: https://github.com/schauder/spring-data-examples/tree/issue/DATACMNS-1033

**Comment by wilkinsona** [comment]
With Java 9, `@PostConstruct` isn't on the classpath by default any more. I think you'll need to launch the JVM with `-addmods java.se.ee`. Can you try that please?

**Comment by snicoll** [comment]
You can also add the jsr250 jar to your app

**Comment by schauder** [comment]
@wilkinsona I think it is {{--add-modules}} by now. And it doesn't work either. I get the same result, no matter if I use {{--add-modules java.se.ee}} or {{--add-modules java.xml.ws.annotation}} as I did before.

**Comment by schauder** [comment]
@snicoll adding jsr250 doesn't change anything either.

**Comment by wilkinsona** [comment]
@schauder I've spent 15 mins or so trying to use the code you linked to above to reproduce the problem you've described and failed to do so. I've hit various problems:

 - Missing Maven Toolchain configuration
 - Missing Spring Data JPA dependency
 - ClassNotFoundException for  javax.xml.bind.JAXBException from Hibernate

Can you please provide a sample that we can run as-is to reproduce the problem that you're seeing?

**Comment by schauder** [comment]
I'm sorry for that, looking into it right now.

**Comment by schauder** [comment]
Sorry again. It looks like I messed my local maven repository really badly.

It now should work and produced the described problem with only a little preparation from your side

* checkout branch issue/DATACMNS-1033

* configure your toolchain.xml to have a jdk9

* execute ./mci-with-jdk9.sh

**Comment by wilkinsona** [comment]
Thanks, @schauder. I can reproduce the problem now. However, that's not entirely surprising as I can't spot any configuration that would make `@PostConstruct` available. If I use `--add-modules java.se.ee` to make it available I see a failure related to `javax.transaction.SystemException`. I think that may be due to that package being split. The alternate, as @snicoll suggested, is to add a dependency:

```xml
<dependency>
	<groupId>javax.annotation</groupId>
	<artifactId>javax.annotation-api</artifactId>
	<version>1.2</version>
</dependency>
```

With that in place things get further, but I then see a failure related to AspectJ:

```
java.lang.NoClassDefFoundError: org/aspectj/util/PartialOrder$PartialComparable
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:996)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:173)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:772)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:670)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:593)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:551)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:486)
	at org.springframework.aop.aspectj.autoproxy.AspectJAwareAdvisorAutoProxyCreator.sortAdvisors(AspectJAwareAdvisorAutoProxyCreator.java:73)
	at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findEligibleAdvisors(AbstractAdvisorAutoProxyCreator.java:92)
	at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.getAdvicesAndAdvisorsForBean(AbstractAdvisorAutoProxyCreator.java:70)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.wrapIfNecessary(AbstractAutoProxyCreator.java:346)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:298)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:431)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1716)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:408)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:119)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:244)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:227)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:289)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:291)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:246)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:98)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
Caused by: java.lang.ClassNotFoundException: org.aspectj.util.PartialOrder$PartialComparable
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:553)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:486)
	... 42 common frames omitted
```

This isn't on the classpath either so it's not clear to me why Spring Framework's trying to use it. However, adding a dependency on `aspectjweaver` is sufficient to get the test to pass.

**Comment by AlanBateman** [comment]
Java SE defines a small subset of JTA, I assume the EE version is needed here. There are a couple of options:

1. Deploy the EE version of the java.transaction module on the upgrade module module (`--upgrade-module-path`) to override the small subset of JTA that Java SE defines.

2. Deploy the EE version of JTA on the class path. This will work if you can ensure that the java.transaction is not resolve (don't specify `--add-modules java.se.ee` as that will resolve all the problematic EE modules that are included in the JDK).

Yes, it complicated. The subset of JTA that Java SE defines can be blamed on CORBA. The java.corba and java.transaction modules are proposed to be deprecated in Java SE 9 so that they can be dropped from Java SE and the JDK in the future. Once they are removed then a lot of complexity with overriding will go away.

**Comment by wilkinsona** [comment]
@AlanBateman Thanks very much for taking the time to fill in the blanks in my understanding. In this case the EE version of JTA was already on the class path, but specifying `--add-modules java.se.ee` to make `@PostConstruct` available then broke things.

**Comment by AlanBateman** [comment]
`@PostConstruct` is one of the JSR-250 defined "Common Annotations". This is an EE JSR with only a tiny subset defined by Java SE for JAX-WS usage. If you use `--add-modules java.xml.ws.annotation` then the types in javax.annotation will be visible but will hide any other types in that package that are on the class path. This is some of the main motivations to not resolve the  java.xml.ws.annotation module by default.
