### ISSUE TITLE
Bug in SpringValidatorAdaptor making 3rd-party validators not working properly with Spring enhanced objects

### ISSUE THREAD

**Issue by cooniur** [spring-projects/spring-boot#9439]
Suppose we have the following class:
```
@Validated
@ConfigurationProperties(prefix = "notification.email")
public class NotificationEmailProperties {
    private boolean enabled = false;

    @NotEmpty
    private String sender;

    @NotEmpty
    private String replyTo;

    @NotEmpty
    private String testRecipient;

// getters & setters are omitted
}
```
During my app start-up, Spring decides to create a proxy for this class somehow (why?), shown using IntelliJ expression evaluation:

```
context = {ValidationContext@11483} "ValidationContext{rootBean=NotificationEmailProperties{enabled=true, sender='notification@myapp.com', replyTo='admin@myapp.com', testRecipient='notification-test-email-dump@myapp.com'}}"
 constraintValidatorManager = {ConstraintValidatorManager@11452} 
 rootBean = {NotificationEmailProperties$$EnhancerBySpringCGLIB$$70cc8279@11322} "NotificationEmailProperties{enabled=true, sender='notification@myapp.com', replyTo='admin@myapp.com', testRecipient='notification-test-email-dump@myapp.com'}"
  CGLIB$BOUND = false
  CGLIB$CALLBACK_0 = {CglibAopProxy$DynamicAdvisedInterceptor@11345} 
  CGLIB$CALLBACK_1 = {CglibAopProxy$StaticUnadvisedInterceptor@11346} 
   target = {NotificationEmailProperties@9291} "NotificationEmailProperties{enabled=true, sender='notification@myapp.com', replyTo='admin@myapp.com', testRecipient='notification-test-email-dump@myapp.com'}"
    enabled = true
    sender = "notification@myapp.com"
    replyTo = "admin@myapp.com"
    testRecipient = "notification-test-email-dump@myapp.com"
  CGLIB$CALLBACK_2 = {CglibAopProxy$SerializableNoOp@11347} 
  CGLIB$CALLBACK_3 = {CglibAopProxy$StaticDispatcher@11348} 
  CGLIB$CALLBACK_4 = {CglibAopProxy$AdvisedDispatcher@11349} 
  CGLIB$CALLBACK_5 = {CglibAopProxy$EqualsInterceptor@11350} 
  CGLIB$CALLBACK_6 = {CglibAopProxy$HashCodeInterceptor@11351} 
  enabled = false
  sender = null
  replyTo = null
  testRecipient = null
 rootBeanClass = {Class@9348} "class com.myapp.infrastructure.email.NotificationEmailProperties$$EnhancerBySpringCGLIB$$70cc8279"
 ```
Note that the field values (sender, replyTo & testRecipient) in the proxy are all null.

Then this Spring enhanced bean is passed into Hibernate's `ValidatorImpl` in `SpringValidatorAdapter#validate` at [line 94](https://github.com/spring-projects/spring-framework/blob/v4.3.8.RELEASE/spring-context/src/main/java/org/springframework/validation/beanvalidation/SpringValidatorAdapter.java#L94) via `this.targetValidator.validate(target)`, where target = the proxy. However, Hibernate's `ValidatorImpl` retrieves field values from the proxy (which are all null), not from the actual object, therefore, fails the validation.

So it seems the `target` needs to be converted to the actual bean object before calling `this.targetValidator.validate(target)` (in `SpringValidatorAdapter#validate` at [line 94](https://github.com/spring-projects/spring-framework/blob/v4.3.8.RELEASE/spring-context/src/main/java/org/springframework/validation/beanvalidation/SpringValidatorAdapter.java#L94)) to make sure 3rd party validators work properly without being affected by Spring proxy.

This happens during configuration properties rebind, shown in the following detailed stack trace:
```
org.springframework.validation.BindException: org.springframework.boot.bind.RelaxedDataBinder$RelaxedBeanPropertyBindingResult: 3 errors
Field error in object 'notification.email' on field 'sender': rejected value [null]; codes [NotEmpty.notification.email.sender,NotEmpty.sender,NotEmpty.java.lang.String,NotEmpty]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [notification.email.sender,sender]; arguments []; default message [sender]]; default message [may not be empty]
Field error in object 'notification.email' on field 'replyTo': rejected value [null]; codes [NotEmpty.notification.email.replyTo,NotEmpty.replyTo,NotEmpty.java.lang.String,NotEmpty]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [notification.email.replyTo,replyTo]; arguments []; default message [replyTo]]; default message [may not be empty]
Field error in object 'notification.email' on field 'testRecipient': rejected value [null]; codes [NotEmpty.notification.email.testRecipient,NotEmpty.testRecipient,NotEmpty.java.lang.String,NotEmpty]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [notification.email.testRecipient,testRecipient]; arguments []; default message [testRecipient]]; default message [may not be empty]
	at org.springframework.boot.bind.PropertiesConfigurationFactory.checkForBindingErrors(PropertiesConfigurationFactory.java:359)
	at org.springframework.boot.bind.PropertiesConfigurationFactory.doBindPropertiesToTarget(PropertiesConfigurationFactory.java:276)
	at org.springframework.boot.bind.PropertiesConfigurationFactory.bindPropertiesToTarget(PropertiesConfigurationFactory.java:240)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:329)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:291)
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.rebind(ConfigurationPropertiesRebinder.java:100)
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.rebind(ConfigurationPropertiesRebinder.java:88)
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.onApplicationEvent(ConfigurationPropertiesRebinder.java:120)
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.onApplicationEvent(ConfigurationPropertiesRebinder.java:49)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:383)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:337)
	at org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration.afterSingletonsInstantiated(ConfigurationPropertiesRebinderAutoConfiguration.java:79)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:781)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
	at com.myapp.Application.main(Application.java:21)
```

Let me know if there is any confusion in my description and I'm happy to provide more details.

Thanks!

**Comment by snicoll** [comment]
Duplicates #8173

**Comment by cooniur** [comment]
Caused by bug in Spring Cloud: https://github.com/spring-cloud/spring-cloud-commons/issues/177
