### ISSUE TITLE
Allow abstract serializers/deserializer in @JsonComponent classes

### ISSUE THREAD

**Issue by tsachev** [spring-projects/spring-boot#9442]
Sometimes it makes sense to wrap multiple serializers/deserializers in a single `@JsonComponent` class and share common logic in an abstract parent.

currently if I have 

```
@JsonComponent
class MyComponents {
  static abstract class AbstractSerializer<T> extends JsonSerializer<T> {
    //...
  }
  static class SomePojoSerializer extends AbstractSerializer<SomePojo> {
    //..
  }
  static class OtherPojoSerializer extends AbstractSerializer<OtherPojo> {
    //..
  }
}
```
I get exception like

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jsonComponentModule': Invocation of init method failed; nested exception is java.lang.IllegalStateException: java.lang.InstantiationException

	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:135)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:415)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1707)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:575)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:492)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:233)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:304)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:747)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:862)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:88)

...

Caused by: java.lang.IllegalStateException: java.lang.InstantiationException
	at org.springframework.boot.jackson.JsonComponentModule.addJsonBean(JsonComponentModule.java:89)
	at org.springframework.boot.jackson.JsonComponentModule.addJsonBeans(JsonComponentModule.java:70)
	at org.springframework.boot.jackson.JsonComponentModule.registerJsonComponents(JsonComponentModule.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:364)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:309)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:132)
	... 35 more
Caused by: java.lang.InstantiationException
	at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.springframework.boot.jackson.JsonComponentModule.addJsonBean(JsonComponentModule.java:86)
	... 44 more
```
PR comming

**Comment by wilkinsona** [comment]
Thanks, @tsachev. Just FYI, there's no need to open an issue if you intend to open a PR too.
