### ISSUE TITLE
RandomAccessDataFileTests#seekFailuresDoNotPreventSubsequentReads does not work with Java 9

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#9529]
This test has to spy on the internal `FilePool` of a `File`. Unfortunately, this breaks on `close` with JDK9 as closing the file will go through the spy/mock and the `closed` field of the `RandomAccessFile` is `null`

```
java.lang.NullPointerException
	at java.base/java.io.RandomAccessFile.close(RandomAccessFile.java:639)
	at org.springframework.boot.loader.data.RandomAccessDataFile$FilePool.close(RandomAccessDataFile.java:268)
	at org.springframework.boot.loader.data.RandomAccessDataFile.close(RandomAccessDataFile.java:117)
	at org.springframework.boot.loader.data.RandomAccessDataFileTests.cleanup(RandomAccessDataFileTests.java:97)
```

**Comment by philwebb** [comment]
JUnit `Assume` is useful for this kind of thing. See https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/test/java/org/springframework/tests/Assume.java

**Comment by wilkinsona** [comment]
I can't reproduce this with 9+181.
