### ISSUE TITLE
Potential NPE in NettyWebServer.stop() when context refresh fails

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#9542]
```
Caused by: java.lang.NullPointerException: null
    	at org.springframework.boot.web.embedded.netty.NettyWebServer.stop(NettyWebServer.java:113) ~[spring-boot-2.0.0.M2.jar:2.0.0.M2]
    	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.stopAndReleaseReactiveWebServer(ReactiveWebServerApplicationContext.java:148) ~[spring-boot-2.0.0.M2.jar:2.0.0.M2]
    	... 7 common frames omitted
```

https://stackoverflow.com/questions/44590741/spring-boot-webflux-application-wont-start-illegalstateexception

**Comment by snicoll** [comment]
Relates to #9146
