### ISSUE TITLE
Property binding attempts to convert scalar value to property object

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-projects/spring-boot#9604]
I have a problem with Boot 2.0 & Configuration properties

## Description

Having an autoconfiguration (https://github.com/spring-cloud/spring-cloud-contract/blob/2.0.x/spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/spring/AutoConfigureStubRunner.java):

 ```java
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@Documented
@ImportAutoConfiguration
@AutoConfigureMessageVerifier
@PropertyMapping(value = "stubrunner", skip = SkipPropertyMapping.ON_DEFAULT_VALUE)
public @interface AutoConfigureStubRunner {
```

It's mapped to such a property (https://github.com/spring-cloud/spring-cloud-contract/blob/2.0.x/spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/spring/StubRunnerProperties.java)

```java
@ConfigurationProperties("stubrunner")
public class StubRunnerProperties {
```

I get such an exception when running consumer apps (those using `AutoConfigureStubRunner`)

 ```
Caused by: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [org.springframework.cloud.contract.stubrunner.spring.StubRunnerProperties]
    at org.springframework.core.convert.support.GenericConversionService.handleConverterNotFound(GenericConversionService.java:319) ~[spring-core-5.0.0.BUILD-SNAPSHOT.jar:5.0.0.BUILD-SNAPSHOT]
    at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:192) ~[spring-core-5.0.0.BUILD-SNAPSHOT.jar:5.0.0.BUILD-SNAPSHOT]
    at org.springframework.boot.context.properties.bind.convert.BinderConversionService.lambda$convert$1(BinderConversionService.java:106) ~[spring-boot-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
    at org.springframework.boot.context.properties.bind.convert.BinderConversionService.callConversionService(BinderConversionService.java:114) ~[spring-boot-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
    at org.springframework.boot.context.properties.bind.convert.BinderConversionService.convert(BinderConversionService.java:106) ~[spring-boot-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
    at org.springframework.boot.context.properties.bind.convert.BinderConversionService.convert(BinderConversionService.java:95) ~[spring-boot-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
    at org.springframework.boot.context.properties.bind.Binder.bindProperty(Binder.java:289) ~[spring-boot-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
    at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:248) ~[spring-boot-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
    at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:197) ~[spring-boot-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
    ... 82 common frames omitted
```

The whole flow of exceptions looks like this:

```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'stubFlowRegistrar' defined in class path resource [org/springframework/cloud/contract/stubrunner/messaging/stream/StubRunnerStreamConfiguration.class]: Unsatisfied dependency expressed through method 'stubFlowRegistrar' parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.cloud.contract.stubrunner.spring.StubRunnerConfiguration': Unsatisfied dependency expressed through field 'props'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'stubrunner-org.springframework.cloud.contract.stubrunner.spring.StubRunnerProperties': Could not bind properties to StubRunnerProperties (prefix=stubrunner, ignoreInvalidFields=false, ignoreUnknownFields=true); nested exception is org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'stubrunner' to org.springframework.cloud.contract.stubrunner.spring.StubRunnerProperties
```

## How to reproduce it?

Just run the script that builds the whole project in a proper order. You will fail on the `beer-producer` app.
```
$ git clone git@github.com:spring-cloud-samples/spring-cloud-contract-samples.git
$ cd spring-cloud-contract-samples
$ git checokut 2.0.x
$ ./scripts/runAcceptanceTests.sh
```

**Comment by mbhave** [comment]
@marcingrzejszczak I wasn't able to run the sample. Compilation failure at `BeerIntoxicationBase.java:[3,45] package com.jayway.restassured.module.mockmvc does not exist`. Just looking at the error, it seems like the `ConverterNotFoundException` would occur if a property `stubrunner: some-value` was found in the environment. But I would need to debug further to see which properties it is trying to bind. Could you help fix the sample for that?

**Comment by marcingrzejszczak** [comment]
Yeah - sorry. Now it's fixed :)

**Comment by mbhave** [comment]
Thanks! This is the failure analysis for the failure.
```
Binding to target [Bindable@221ffed type = org.springframework.cloud.contract.stubrunner.spring.StubRunnerProperties, value = 'provided', annotations = array<Annotation>[[empty]]] failed:
    Property: stubrunner
    Value:
    Origin: "stubrunner" from property source "applicationConfig: [classpath:/application.yaml]"
    Reason: No converter found capable of converting from type [java.lang.String] to type [org.springframework.cloud.contract.stubrunner.spring.StubRunnerProperties]
```
Most of the `application.yaml` files in that sample have properties under `stubrunner` commented out, like [this one](https://github.com/spring-cloud-samples/spring-cloud-contract-samples/blob/master/consumer_with_stubs_per_consumer/src/test/resources/application.yaml#L1), for example. The binder finds property `stubrunner` with an empty value and tries to bind that and conversion fails. If you remove `stubrunner` entirely from the properties files where you don't want to specify properties for it, it should work.

**Comment by marcingrzejszczak** [comment]
I have completely forgotten about those files!! I'll remove them tomorrow and see if it works. That's strange then that it used to work in the previous versions of Boot...

**Comment by philwebb** [comment]
I'll close this one for now, I think once those properties are removed things should work. We can reopen if that's not the case.

**Comment by marcingrzejszczak** [comment]
Yeah, I confirm that the problem is fixed. Sorry for the commotion.
