### ISSUE TITLE
NoClassDefFoundError when using WebFlux with Tomcat

### ISSUE THREAD

**Issue by michael-simons** [spring-projects/spring-boot#9689]
Hi,

using Tomcat instead of Netty as described here https://stackoverflow.com/questions/43472091/using-spring-boot-weblfux-with-embedded-tomcat/43604933?noredirect=1#comment76739146_43604933

```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-webflux</artifactId>
    <exclusions>
        <exclusion>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-reactor-netty</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-tomcat</artifactId>            
</dependency>
```

leads to `java.lang.NoClassDefFoundError: io/netty/buffer/Unpooled` during some test, but not alway.

This 

```
 @RestController
        public static class Dingens {
            @GetMapping(path = "/", produces = MediaType.TEXT_EVENT_STREAM_VALUE)
            Flux<String> getStuff() {
                return Flux.range(1, 20).map(i -> Integer.toString(i));
                
            }
        }
```

can be tested with 

```
@Test
    public void contextLoads() {
        FluxExchangeResult<String> result = this.client.get()
                .uri("/")
                .accept(TEXT_EVENT_STREAM)
                .exchange()
                .expectStatus().isOk()
                .expectHeader().contentType(TEXT_EVENT_STREAM)
                .returnResult(String.class);

        StepVerifier.create(result.getResponseBody())                
                .consumeNextWith(s -> assertThat(s, is("1")))
                .expectNextCount(19)
                .expectComplete()
                .verify();
    }
```

However given 

```
@RestController
public class ThingController {

    @GetMapping(path = "/api/things", produces = MediaType.TEXT_EVENT_STREAM_VALUE)
    public Flux<Thing> getAll() {
        return Flux.range(1, 20).map(i -> new Thing("This is a thing"));

    }
}
```

and basically the same test

```
  @Test
    public void testSomeMethod() {
        FluxExchangeResult<Thing> result = this.client.get()
                .uri("/api/things")
                .accept(TEXT_EVENT_STREAM)
                .exchange()
                .expectStatus().isOk()
                .expectHeader().contentType(TEXT_EVENT_STREAM)
                .returnResult(Thing.class);

        StepVerifier.create(result.getResponseBody())
                .consumeNextWith(film -> assertThat(film.getTitle(), is(equalTo("This is a thing"))))
                .expectNextCount(19)
                .expectComplete()
                .verify();
    }
[InitializrSpringbootProject.zip](https://github.com/spring-projects/spring-boot/files/1127227/InitializrSpringbootProject.zip)

```

I end up with 

```
testSomeMethod(com.example.demo.ThingControllerTest)  Time elapsed: 0.358 sec  <<< ERROR!
java.lang.NoClassDefFoundError: io/netty/buffer/Unpooled
	at com.example.demo.ThingControllerTest.testSomeMethod(ThingControllerTest.java:40)
Caused by: java.lang.ClassNotFoundException: io.netty.buffer.Unpooled
	at com.example.demo.ThingControllerTest.testSomeMethod(ThingControllerTest.java:40)
```

Demo project is attached. 
[InitializrSpringbootProject.zip](https://github.com/spring-projects/spring-boot/files/1127232/InitializrSpringbootProject.zip)

**Comment by bclozel** [comment]
Thanks for the detailed and very useful (as usual) report!
This sounds really familiar and indeed, this is something that's been fixed just a week ago in the framework snapshots -  see [SPR-14528](https://jira.spring.io/browse/SPR-14528).

We'll have a new milestone in a couple of weeks.
In the meantime, you can just add the tomcat starter and forget about excluding reactor-netty; tomcat and other containers should be auto-configured before, as you might get reactor-netty for its client (actually, to power `WebClient`).

Thanks!

**Comment by bclozel** [comment]
Oh and as a side note, if you'd like to get more useful stacktraces in such a reactive environment, you can set the following property `spring.reactor.stacktrace-mode.enabled=true`. This will leverage the [debugging feature in reactor](http://projectreactor.io/docs/core/release/reference/#_debugging_reactor); this is rather expensive at runtime, but it's perfectly fine in development mode. This feature is automatically enabled if you've got devtools enabled.

**Comment by michael-simons** [comment]
Thanks for taking care 👍 And even more so for the configuration tipp!
