### ISSUE TITLE
java.lang.NoClassDefFoundError when using XmlExpectationsHelper

### ISSUE THREAD

**Issue by barracuda317** [spring-projects/spring-boot#9691]
I want to test, if the responded xml matches with the expected xml. Therefore i use the following Code-Snippet:

```
this.mockMvc.perform(post("/getDynamicData").
        contentType(MediaType.APPLICATION_XML).
        content(FileUtils.readFileToString(xmlResource.getFile()))).
        andExpect(status().isOk()).
        andExpect(content().xml(FileUtils.readFileToString(xmlResponse.getFile())));
```
Doing so, I end up with a NoClassDefFoundError in `content().xml(...)`:

```
java.lang.NoClassDefFoundError: org/custommonkey/xmlunit/XMLUnit

	at org.springframework.test.util.XmlExpectationsHelper.assertXmlEqual(XmlExpectationsHelper.java:80)
	at org.springframework.test.web.servlet.result.ContentResultMatchers$7.match(ContentResultMatchers.java:181)
	at org.springframework.test.web.servlet.MockMvc$1.andExpect(MockMvc.java:171)
	at com.dcs.chargenow.poimgmt.dynamicdata.controller.DynamicDataControllerTest.oneProviderOneChargePointSuccess(DynamicDataControllerTest.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ClassNotFoundException: org.custommonkey.xmlunit.XMLUnit
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 33 more
```

**Comment by philwebb** [comment]
As mentioned in the Javadoc of `xml()` you need to include an XMLUnit dependency.

> Use of this matcher requires the [XMLUnit](http://xmlunit.sourceforge.net) library.

You'll need to add an `xmlunit:xmlunit:1.6` dependency to your build file.

**Comment by philwebb** [comment]
I've raised #9695 to discuss if we should add an XMLUnit managed dependency.

**Comment by Krannthi** [comment]
There XMLUnit core , matchers and legacy artifacts on the maven repo. When I added them, I couldn't get the expected results. But if I added the above mentioned dependency(xmlunit:xmlunit:1.6), it worked. What's the difference ?
