### ISSUE TITLE
Upgrading from 2.0.0.M1->2.0.0.M2: ClassNotFoundException: org.eclipse.jetty.server.ResourceService$WelcomeFactory

### ISSUE THREAD

**Issue by smigfu** [spring-projects/spring-boot#9773]
After upgrading from `2.0.0.M1` to `2.0.0.M2` I see the exception down below when compiling . I can see that between the version Jetty was upgraded from `jetty-9.4.5.v20170502` to `jetty-9.4.6.v20170531` but I am not sure if this is relevant for the issue. My pom.xml looks as following:

```
                <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-tomcat</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-jetty</artifactId>
		</dependency>
```

```
java.lang.NoClassDefFoundError: org/eclipse/jetty/server/ResourceService$WelcomeFactory
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_121]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_121]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_121]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_121]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_121]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_121]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_121]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_121]
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114) ~[?:1.8.0_121]
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125) ~[?:1.8.0_121]
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49) ~[?:1.8.0_121]
	at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68) ~[?:1.8.0_121]
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138) ~[?:1.8.0_121]
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49) ~[?:1.8.0_121]
	at sun.reflect.generics.repository.MethodRepository.getReturnType(MethodRepository.java:68) ~[?:1.8.0_121]
	at java.lang.reflect.Method.getGenericReturnType(Method.java:255) ~[?:1.8.0_121]
	at org.springframework.core.MethodParameter.getGenericParameterType(MethodParameter.java:411) ~[spring-core-5.0.0.RC2.jar:5.0.0.RC2]
	at org.springframework.core.SerializableTypeWrapper$MethodParameterTypeProvider.getType(SerializableTypeWrapper.java:319) ~[spring-core-5.0.0.RC2.jar:5.0.0.RC2]
	at org.springframework.core.SerializableTypeWrapper.forTypeProvider(SerializableTypeWrapper.java:140) ~[spring-core-5.0.0.RC2.jar:5.0.0.RC2]
	at org.springframework.core.ResolvableType.forType(ResolvableType.java:1355) ~[spring-core-5.0.0.RC2.jar:5.0.0.RC2]
	at org.springframework.core.ResolvableType.forMethodParameter(ResolvableType.java:1271) ~[spring-core-5.0.0.RC2.jar:5.0.0.RC2]
	at org.springframework.core.ResolvableType.forMethodParameter(ResolvableType.java:1237) ~[spring-core-5.0.0.RC2.jar:5.0.0.RC2]
	at org.springframework.core.ResolvableType.forMethodReturnType(ResolvableType.java:1180) ~[spring-core-5.0.0.RC2.jar:5.0.0.RC2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:787) ~[spring-beans-5.0.0.RC2.jar:5.0.0.RC2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:669) ~[spring-beans-5.0.0.RC2.jar:5.0.0.RC2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:637) ~[spring-beans-5.0.0.RC2.jar:5.0.0.RC2]
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1494) ~[spring-beans-5.0.0.RC2.jar:5.0.0.RC2]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:414) ~[spring-beans-5.0.0.RC2.jar:5.0.0.RC2]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:384) ~[spring-beans-5.0.0.RC2.jar:5.0.0.RC2]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:504) ~[spring-beans-5.0.0.RC2.jar:5.0.0.RC2]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:497) ~[spring-beans-5.0.0.RC2.jar:5.0.0.RC2]
	at org.springframework.context.support.AbstractApplicationContext.getBeansOfType(AbstractApplicationContext.java:1183) ~[spring-context-5.0.0.RC2.jar:5.0.0.RC2]
	at org.springframework.boot.SpringApplication.getExitCodeFromMappedException(SpringApplication.java:879) ~[spring-boot-2.0.0.M2.jar:2.0.0.M2]
	at org.springframework.boot.SpringApplication.getExitCodeFromException(SpringApplication.java:865) ~[spring-boot-2.0.0.M2.jar:2.0.0.M2]
	at org.springframework.boot.SpringApplication.handleExitCode(SpringApplication.java:851) ~[spring-boot-2.0.0.M2.jar:2.0.0.M2]
	at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:802) ~[spring-boot-2.0.0.M2.jar:2.0.0.M2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) ~[spring-boot-2.0.0.M2.jar:2.0.0.M2]
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:138) ~[spring-boot-test-2.0.0.M2.jar:2.0.0.M2]
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99) ~[spring-test-5.0.0.RC2.jar:5.0.0.RC2]
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:117) ~[spring-test-5.0.0.RC2.jar:5.0.0.RC2]
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:104) ~[spring-test-5.0.0.RC2.jar:5.0.0.RC2]
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:117) ~[spring-test-5.0.0.RC2.jar:5.0.0.RC2]
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83) ~[spring-test-5.0.0.RC2.jar:5.0.0.RC2]
	at org.springframework.boot.test.autoconfigure.SpringBootDependencyInjectionTestExecutionListener.prepareTestInstance(SpringBootDependencyInjectionTestExecutionListener.java:44) ~[spring-boot-test-autoconfigure-2.0.0.M2.jar:2.0.0.M2]
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:242) [spring-test-5.0.0.RC2.jar:5.0.0.RC2]
	at org.springframework.test.context.junit4.statements.RunPrepareTestInstanceCallbacks.evaluate(RunPrepareTestInstanceCallbacks.java:63) [spring-test-5.0.0.RC2.jar:5.0.0.RC2]
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84) [spring-test-5.0.0.RC2.jar:5.0.0.RC2]
	at org.springframework.test.context.junit4.statements.SpringFailOnTimeout.evaluate(SpringFailOnTimeout.java:87) [spring-test-5.0.0.RC2.jar:5.0.0.RC2]
	at org.springframework.test.context.junit4.statements.ProfileValueChecker.evaluate(ProfileValueChecker.java:102) [spring-test-5.0.0.RC2.jar:5.0.0.RC2]
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239) [junit-4.12.jar:4.12]
	at org.junit.rules.RunRules.evaluate(RunRules.java:20) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61) [spring-test-5.0.0.RC2.jar:5.0.0.RC2]
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70) [spring-test-5.0.0.RC2.jar:5.0.0.RC2]
	at org.springframework.test.context.junit4.statements.ProfileValueChecker.evaluate(ProfileValueChecker.java:102) [spring-test-5.0.0.RC2.jar:5.0.0.RC2]
	at org.springframework.test.context.junit4.rules.SpringClassRule$TestContextManagerCacheEvictor.evaluate(SpringClassRule.java:230) [spring-test-5.0.0.RC2.jar:5.0.0.RC2]
	at org.junit.rules.RunRules.evaluate(RunRules.java:20) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192) [.cp/:?]
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.server.ResourceService$WelcomeFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
	... 77 more
```

**Comment by wilkinsona** [comment]
That class exists in both 9.4.5 and 9.4.6. I'd guess that you may have a corrupted download of `jetty-server`. Please try purging it from Maven's cache and see if that helps. If it doesn't, please provide a complete, minimal sample that reproduces the problem.

**Comment by smigfu** [comment]
Thanks, indeed my jetty-xyz.jar were corrupt. After purging them everything worked as expected. 👍
