### ISSUE TITLE
Spring Boot 2.0.0.M2 doesn't work with Spring Data MongoDB Kay.M4

### ISSUE THREAD

**Issue by juergenzimmermann** [spring-projects/spring-boot#9780]
When I use the attached testcase I cannot start the server implemented in `Main.java` (see the console output below).

I'm using the following versions:
JDK 8u131
Gradle 4.1-milestone-1
MongoDB 3.5.10

The local MongoDB server is started w/o an authentication database. I get the same error when using an authentication database.

Console output:
````
Starting a Gradle Daemon, 1 busy and 2 incompatible Daemons could not be reused, use --status for details

> Task :bootRun

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::             (v2.0.0.M2)

2017-07-18 13:09:44.301  INFO 9372 --- [           main] de.hska.test.Microservice                : Starting Microservice on iwi-w-ziju01-d with PID 9372 (C:\Users\ziju0001\IdeaProjects\testcase\build\classes\java\main started by ziju0001 in C:\Users\ziju0001\IdeaProjects\testcase)
2017-07-18 13:09:44.305  INFO 9372 --- [           main] de.hska.test.Microservice                : No active profile set, falling back to default profiles: default
2017-07-18 13:09:44.382  INFO 9372 --- [           main] ConfigServletWebServerApplicationContext : Refreshing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@402e37bc: startup date [Tue Jul 18 13:09:44 CEST 2017]; root of context hierarchy
2017-07-18 13:09:46.642  INFO 9372 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2017-07-18 13:09:46.658  INFO 9372 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2017-07-18 13:09:46.661  INFO 9372 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.15
2017-07-18 13:09:46.807  INFO 9372 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2017-07-18 13:09:46.807  INFO 9372 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 2429 ms
2017-07-18 13:09:47.015  INFO 9372 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Mapping servlet: 'dispatcherServlet' to [/]
2017-07-18 13:09:47.021  INFO 9372 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2017-07-18 13:09:47.022  INFO 9372 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2017-07-18 13:09:47.022  INFO 9372 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2017-07-18 13:09:47.022  INFO 9372 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
2017-07-18 13:09:47.085  WARN 9372 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'testController': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'testService': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'de.hska.test.service.TestRepository' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
2017-07-18 13:09:47.088  INFO 9372 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2017-07-18 13:09:47.110  INFO 9372 --- [           main] utoConfigurationReportLoggingInitializer :

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2017-07-18 13:09:47.230 ERROR 9372 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   :

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of constructor in de.hska.test.service.TestService required a bean of type 'de.hska.test.service.TestRepository' that could not be found.


Action:

Consider defining a bean of type 'de.hska.test.service.TestRepository' in your configuration.
````

**Comment by juergenzimmermann** [comment]
[testcase.zip](https://github.com/spring-projects/spring-boot/files/1155745/testcase.zip)

**Comment by juergenzimmermann** [comment]
Testcase is uploaded.

**Comment by snicoll** [comment]
@juergenzimmermann Your project doesn't compile for me.

**Comment by juergenzimmermann** [comment]
Hmm, I just downloaded the uploaded testcase.zip, unzipped, "gradle clean compileJava", "gradle" and had no problems to reproduces (see screenshot below). Which versions of Java and Gradle do you use?

![grafik](https://user-images.githubusercontent.com/734334/28316520-82e51ad8-6bc3-11e7-9572-74709b59803f.png)

**Comment by snicoll** [comment]
The test do not compile

**Comment by juergenzimmermann** [comment]
@snicoll Uups. I've forgotten to delete the test stuff when producing the testcase. Sorry for the inconvenience. Please delete the directory below src\test\java

**Comment by juergenzimmermann** [comment]
Testcase updated: without src\test\java and src\test\resources
[testcase.zip](https://github.com/spring-projects/spring-boot/files/1155812/testcase.zip)

**Comment by snicoll** [comment]
Here's an excerpt of the auto-configuration report

```
 MongoRepositoriesAutoConfiguration:
      Did not match:
         - @ConditionalOnMissingBean (types: org.springframework.data.mongodb.repository.support.MongoRepositoryFactoryBean,org.springframework.data.mongodb.repository.config.MongoRepositoryConfigurationExtension; SearchStrategy: all) found beans of type'org.springframework.data.mongodb.repository.config.MongoRepositoryConfigurationExtension'org.springframework.data.mongodb.repository.config.MongoRepositoryConfigurationExtension#0 (OnBeanCondition)
      Matched:
         - @ConditionalOnClass found required classes 'com.mongodb.Mongo', 'org.springframework.data.mongodb.repository.MongoRepository'; @ConditionalOnMissingClass did not find unwanted class (OnClassCondition)
         - @ConditionalOnProperty (spring.data.mongodb.repositories.enabled=true) matched (OnPropertyCondition)
```

I've removed the unnecessary `@EnableMongoRepositories` on your config class and ended up with

```
java.lang.NullPointerException: null
	at org.springframework.data.repository.config.RepositoryBeanNameGenerator.getRepositoryInterfaceFromFactory(RepositoryBeanNameGenerator.java:81) ~[spring-data-commons-2.0.0.M4.jar:na]
	at org.springframework.data.repository.config.RepositoryBeanNameGenerator.getRepositoryInterfaceFrom(RepositoryBeanNameGenerator.java:75) ~[spring-data-commons-2.0.0.M4.jar:na]
	at org.springframework.data.repository.config.RepositoryBeanNameGenerator.generateBeanName(RepositoryBeanNameGenerator.java:52) ~[spring-data-commons-2.0.0.M4.jar:na]
	at org.springframework.data.repository.config.RepositoryConfigurationSourceSupport.generateBeanName(
```

We do not use the tracker for support request and that project is quite involved anyway . If you want us to look into it, please create a focused sample on the issue you're experiencing.

**Comment by juergenzimmermann** [comment]
@snicoll Well, the issue is that my microservices are working fine with Spring Boot 1.5.4.RELEASE and Spring Data Ingalls-SR4. After upgrading to Spring Boot 2.0.0.M2 and Spring Data Kay-M4 they don't start anymore. Therefore, I extracted the attached testcase so that you can reproduce it.
Due to the NPE I think it's an issue with Spring Data and now I created https://jira.spring.io/browse/DATAMONGO-1742

**Comment by snicoll** [comment]
Let's follow up with the issue you have created.

**Comment by olivergierke** [comment]
I'd like to bring this back to Boot as this seems to be related to the way the project is run using the Boot Gradle plugin. I observe the following:

- If I run the project using `gradle bootRun` it fails as described. The line causing the NullPointerException seems to indicate that a FactoryBean for the repository doesn't get the repository interface configured as constructor argument properly.
- Running `gradle bootJar` and running the app with `java -jar build/libs/*.jar` causes the same issue

However:

- If I run the main class in the IDE the project bootstraps but then runs into the `data.json` missing. That however indicates the repositories are bootstrapping properly
- If I remove the `spring-context-indexer` dependency, the project also runs fine from the command line.

To me this looks like with the indexer in place for some reason the repositories don't get populated properly if the indexer is in place. I can also see the index file created properly but apparently there seems to be a difference in the way this gets used when running inside the IDE VS. running from the command line. I just have a hard time debugging things as everything looks fine if I run stuff from within the IDE.

Maybe @snicoll might have an idea what could go wrong with the indexing in place?

**Comment by philwebb** [comment]
Some IDEs (Eclipse at least) don't always configure annotation processors correctly. That might explain why it works in the IDE but not on the command line. If it is an indexer problem it might well end up being a framework bug, but rather than open another one I suggest that we track things down here first.

@olivergierke You might as well close DATAMONGO-1742

**Comment by olivergierke** [comment]
More insight:

- For some reason the execution IDE is not actually using the index as the lookup of the index file fails. It's generated, I can see that. I suspect a slightly different classloader arrangement causing the issue.
- The indexing applied causes a different type of `BeanDefinition` being returned from `ClassPathScanningCandidateComponentProvider.findCandidateComponents(…)`. Our `BeanNameGenerator` currently tries to look up bean names from the constructor argument used on non-`ScannedGenericBeanDefinition` (which in the non-index case is true for the bean definitions for our repository factories). As the scan for custom implementations now apparently sees an `AnnotatedBeanDefinition` and thus also runs into the path that expects the constructor argument, which then fails.

Looks like we need to adapt the implementation of `RepositoryBeanNameGenerator` to only apply our custom name resolution in the desired case. I've changed the [ticket](https://jira.spring.io/browse/DATACMNS-1115) accordingly and will take it from there. Until RC1, I fear we have to recommend not using the indexer with a Spring Data project.

**Comment by wilkinsona** [comment]
Thanks, @olivergierke. Sounds like we can close this one again

**Comment by snicoll** [comment]
@juergenzimmermann for the record and independently of the issue you're having, I am wondering why you're using the component indexer for that microservice of yours. Our test shows that it doesn't make much of a difference (close to nothing) for small-ish project (less than 500 classes to scan), the main reason being classpath scanning is damn fast.

**Comment by juergenzimmermann** [comment]
@snicoll I thought that upgrading also implys using the indexer. Thank you for the clarification in the docs.

**Comment by snicoll** [comment]
Can you please expand how you came to that conclusion?

**Comment by juergenzimmermann** [comment]
@snicoll a few weeks ago I read about the indexer (in the JIRA ticket system?) and made a note that we should add a dependency on the indexer when we start piloting the upgrade. Sorry, my failure.
