### ISSUE TITLE
AopAutoConfiguration ought to be conditional on aspectjweaver

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#9880]
Most (all) of what happens in `AopAutoConfiguration` is to `@EnableAspectJAutoProxy`. Proxies cannot be created unless the aspectjweaver is on the classpath. If the user wants to use AspectJ natively they wouldn't include the weaver, so logically it makes sense to back off if the weaver isn't present.

**Comment by snicoll** [comment]
`MetricRepositoryAutoConfigurationTests` fails now with this change:

```
java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy

	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3521)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getAnnotations(Class.java:3446)
	at org.springframework.core.type.StandardAnnotationMetadata.<init>(StandardAnnotationMetadata.java:69)
	at org.springframework.beans.factory.annotation.AnnotatedGenericBeanDefinition.<init>(AnnotatedGenericBeanDefinition.java:58)```
